// AlloFlow Section: LIVE_QUIZ
// Module: modules/live_quiz
// Variant: local (cloud-stripped)
// Source lines: 6127–6144
// Hash: 08b62304825a44b1
// Cloud stripped: false (0 replacements)
// Extracted: 2026-04-11T18:46:20.676Z
// DO NOT EDIT — re-generated by scripts/extract_modules_local.js
// @section LIVE_QUIZ — CDN wrapper (source: teacher_module.js)
const TeacherLiveQuizControls = React.memo((props) => {
    const Ext = window.AlloModules && window.AlloModules.TeacherLiveQuizControls;
    if (Ext) return <Ext {...props} />;
    return null;
});

const calculateAnalyticsMetrics = (dashboardData) => {
    const ext = window.AlloModules && window.AlloModules.calculateAnalyticsMetrics;
    if (ext) return ext(dashboardData);
    return { averageScore: 0, quizCompletionRate: 0, avgAdventureLevel: 0, misconceptions: [] };
};
const LongitudinalProgressChart = React.memo((props) => {
    const Ext = window.AlloModules && window.AlloModules.LongitudinalProgressChart;
    if (Ext) return <Ext {...props} />;
    return <div className="text-xs text-slate-600 italic text-center py-4">Loading progress chart...</div>;
});

