// AlloFlow Section: INTERACTIVE_GAMES
// Module: modules/games
// Variant: local (cloud-stripped)
// Source lines: 5758–6026
// Hash: 49ef1a11c48c5cb7
// Cloud stripped: false (0 replacements)
// Extracted: 2026-04-11T18:46:20.676Z
// DO NOT EDIT — re-generated by scripts/extract_modules_local.js
// @section INTERACTIVE_GAMES — Confetti, Memory, Matching, Timeline, Crossword, Bingo, etc.
const ConfettiExplosion = React.memo(() => (
  <div className="absolute inset-0 overflow-hidden pointer-events-none z-50 flex justify-center items-center">
    {[...Array(20)].map((_, i) => (
      <div
        key={i}
        className="absolute"
        style={{
            top: '50%', left: '50%',
            transform: `rotate(${i * 18}deg) translate(100px)`
        }}
      >
        <div
            className="w-2 h-2 rounded-full animate-[ping_1s_ease-out_forwards]"
            style={{
                backgroundColor: ['#fbbf24', '#f472b6', '#60a5fa', '#34d399'][i % 4]
            }}
        />
      </div>
    ))}
  </div>
));
const Stamp = ({ label = "VERIFIED", color = "text-green-600 border-green-600", position = "top-2 right-6", size = "large" }) => {
  const sizeClasses = size === 'small'
    ? "border-2 px-2 py-0.5 text-[10px] tracking-wide"
    : "border-4 px-4 py-1 text-xl tracking-widest";
  return (
    <div className={`
      absolute ${position}
      ${sizeClasses} rounded-lg font-black uppercase
      opacity-0 animate-[stamp_0.4s_ease-in_forwards] ${color}
      z-20 pointer-events-none backdrop-blur-[1px] bg-white/10 shadow-sm mask-image-grunge origin-center
    `}>
      {label}
    </div>
  );
};
const ComplexityGauge = React.memo(({ level }) => {
  const getColor = (l) => {
      if (l < 4) return 'bg-green-500';
      if (l < 7) return 'bg-yellow-500';
      return 'bg-red-500';
  };
  return (
    <div className="w-full h-3 bg-slate-100 rounded-full overflow-hidden border border-slate-200 relative mt-2">
      <div className="absolute inset-0 flex">
          <div className="flex-1 border-r border-white/50"></div>
          <div className="flex-1 border-r border-white/50"></div>
          <div className="flex-1"></div>
      </div>
      <div
        className={`h-full transition-all duration-300 ease-out ${getColor(level)}`}
        style={{ width: `${((level - 1) / 8) * 100}%` }}
      ></div>
    </div>
  );
});
const Sticker = ({ type, x, y }) => {
    const icons = {
        star: '⭐',
        check: '✅',
        idea: '💡',
        love: '❤️',
    };
    return (
        <div
            className="absolute text-3xl drop-shadow-md animate-[ping_0.4s_ease-out_reverse_forwards] pointer-events-none select-none z-50 hover:scale-110 transition-transform"
            style={{ top: y - 15, left: x - 15 }}
        >
            {icons[type]}
        </div>
    );
};
const MatchVisuals = () => (
  <div className="absolute inset-0 z-20 flex items-center justify-center pointer-events-none overflow-hidden rounded-xl">
    <div className="absolute inset-0 bg-green-400/20 animate-pulse"></div>
    <CheckCircle2 className="text-green-600 w-10 h-10 drop-shadow-lg animate-[bounce_0.6s_infinite]" />
    {[...Array(8)].map((_, i) => (
      <div
        key={i}
        className="absolute text-lg"
        style={{
            top: '50%', left: '50%',
            transform: `rotate(${i * 45}deg) translate(25px)`,
            animation: `ping 1s ease-out infinite ${i * 0.1}s`
        }}
      >
        ✨
      </div>
    ))}
  </div>
);
// Expose for CDN game modules
window.AlloModules = window.AlloModules || {};
window.AlloModules.ConfettiExplosion = ConfettiExplosion;
window.AlloModules.MatchVisuals = MatchVisuals;
const AnimatedNumber = ({ value, duration = 1000, disableAnimations = false }) => {
  const [displayValue, setDisplayValue] = useState(value);
  const startTimeRef = useRef(null);
  const startValueRef = useRef(value);
  const animationFrameRef = useRef(null);
  useEffect(() => {
    if (disableAnimations) {
        setDisplayValue(value);
        return;
    }
    if (value === displayValue) return;
    startValueRef.current = displayValue;
    startTimeRef.current = null;
    const animate = (timestamp) => {
      if (!startTimeRef.current) startTimeRef.current = timestamp;
      const progress = timestamp - startTimeRef.current;
      const percentage = Math.min(progress / duration, 1);
      const ease = (x) => (x === 1 ? 1 : 1 - Math.pow(2, -10 * x));
      const current = Math.round(startValueRef.current + (value - startValueRef.current) * ease(percentage));
      setDisplayValue(current);
      if (progress < duration) {
        animationFrameRef.current = requestAnimationFrame(animate);
      }
    };
    if (animationFrameRef.current) {
        cancelAnimationFrame(animationFrameRef.current);
    }
    animationFrameRef.current = requestAnimationFrame(animate);
    return () => {
        if (animationFrameRef.current) {
            cancelAnimationFrame(animationFrameRef.current);
        }
    };
  }, [value, duration, disableAnimations]);
  return <>{displayValue}</>;
};
const ClozeInput = React.memo(({ targetWord, onCorrect, isSolved }) => {
  const { t } = useContext(LanguageContext);
  const [val, setVal] = useState(isSolved ? targetWord : '');
  const [status, setStatus] = useState(isSolved ? 'success' : 'neutral');
  useEffect(() => {
      if (isSolved) {
          setVal(targetWord);
          setStatus('success');
      } else {
          setVal('');
          setStatus('neutral');
      }
  }, [isSolved, targetWord]);
  const normalize = (str) => str ? str.toLowerCase().trim().replace(/[^a-z0-9]/g, '') : '';
  const handleDrop = (e) => {
    e.preventDefault();
    if (status === 'success') return;
    const droppedText = e.dataTransfer.getData("text/plain");
    if (normalize(droppedText) === normalize(targetWord)) {
        setVal(targetWord);
        setStatus('success');
        if (onCorrect) onCorrect(targetWord);
    } else {
        setStatus('error');
        setTimeout(() => setStatus('neutral'), 800);
    }
  };
  const handleDragOver = (e) => {
      if (status !== 'success') {
          e.preventDefault();
          if(status !== 'active') setStatus('active');
      }
  };
  const handleDragLeave = () => {
      if (status === 'active') setStatus('neutral');
  };
  const handleChange = (e) => {
      if (status === 'success') return;
      const newVal = e.target.value;
      setVal(newVal);
      if (normalize(newVal) === normalize(targetWord)) {
          setStatus('success');
          if (onCorrect) onCorrect(targetWord);
      }
  };
  const width = Math.max(80, targetWord.length * 12) + 'px';
  return (
      <span
        className="inline-block mx-1 relative align-middle"
        onDrop={handleDrop}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
      >
          <input
              type="text"
              value={val}
              onChange={handleChange}
              readOnly={status === 'success'}
              className={`
                  text-center border-b-2 px-1 py-0.5 text-sm font-bold transition-all outline-none focus:ring-2 focus:ring-indigo-400 rounded-t
                  ${status === 'success' ? 'border-green-500 bg-green-50 text-green-800' :
                    status === 'error' ? 'border-red-500 bg-red-50 animate-pulse' :
                    status === 'active' ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-200' :
                    'border-indigo-300 bg-white focus:border-indigo-500 focus:bg-indigo-50 focus:ring-2 focus:ring-indigo-200'}
              `}
              style={{ width }}
              placeholder="?"
              autoComplete="off"
              aria-label={t('games.fill_blank.input_label')}
          />
          {status === 'success' && (
              <span className="absolute -top-2 -right-2 text-green-500 bg-white rounded-full shadow-sm animate-in zoom-in duration-300"><CheckCircle2 size={16} className="fill-green-100"/></span>
          )}
      </span>
  );
});
// ═══ Game Components (loaded from CDN games_module.js) ═══
// Proxy components that delegate to CDN-loaded implementations.
// Games load during app init; by the time user opens a game, they're available.
const MemoryGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.MemoryGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const MatchingGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.MatchingGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const TimelineGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.TimelineGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const ConceptSortGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.ConceptSortGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const VennGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.VennGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const CrosswordGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.CrosswordGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const SyntaxScramble = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.SyntaxScramble;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const BingoGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.BingoGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const StudentBingoGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.StudentBingoGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const WordScrambleGame = React.memo((props) => {
  const Impl = window.AlloModules && window.AlloModules.WordScrambleGame;
  return Impl ? <Impl {...props} /> : <div className="p-8 text-center text-slate-500">Loading game...</div>;
});
const SkeletonLoader = ({ type }) => {
  return (
    <div className="w-full animate-pulse space-y-4 p-4">
      <div className="h-8 bg-slate-200 rounded w-3/4 mb-6"></div>
      {type === 'image' ? (
        <div className="w-full h-64 bg-slate-200 rounded-lg mb-4"></div>
      ) : (
        <div className="space-y-3">
          <div className="h-4 bg-slate-200 rounded w-full"></div>
          <div className="h-4 bg-slate-200 rounded w-full"></div>
          <div className="h-4 bg-slate-200 rounded w-5/6"></div>
          <div className="h-4 bg-slate-200 rounded w-full"></div>
        </div>
      )}
      <div className="h-32 bg-slate-100 rounded-lg border border-slate-200 mt-6"></div>
    </div>
  );
};
