// AlloFlow Section: QUICKSTART_WIZARD
// Module: modules/teacher
// Variant: local (cloud-stripped)
// Source lines: 6176–6191
// Hash: 2526e601e12ec5a4
// Cloud stripped: false (0 replacements)
// Extracted: 2026-04-11T18:46:20.676Z
// DO NOT EDIT — re-generated by scripts/extract_modules_local.js
// @section QUICKSTART_WIZARD — CDN wrapper (source: quickstart_source.jsx → quickstart_module.js)
const QuickStartWizard = React.memo((props) => {
    const Ext = window.AlloModules && window.AlloModules.QuickStartWizard;
    if (Ext) return <Ext {...props} />;
    if (!props.isOpen) return null;
    return (
        <div className="fixed inset-0 z-[300] bg-slate-900/90 flex items-center justify-center p-4 animate-in fade-in duration-300" onClick={props.onClose}>
            <div className="bg-white rounded-2xl p-8 text-center max-w-md shadow-2xl" onClick={(e) => e.stopPropagation()}>
                <div className="text-4xl mb-3">🚀</div>
                <p className="text-lg font-bold text-slate-700">Loading Setup Wizard...</p>
                <p className="text-sm text-slate-600 mt-2">Module loading from CDN.</p>
                <button onClick={props.onClose} className="mt-4 px-4 py-2 bg-slate-200 text-slate-700 font-bold rounded-lg text-sm hover:bg-slate-300 transition-all">Close</button>
            </div>
        </div>
    );
});
