// AlloFlow Section: CHARTS
// Module: modules/analytics
// Variant: local (cloud-stripped)
// Source lines: 11782–11913
// Hash: 3f95065f01431f05
// Cloud stripped: false (0 replacements)
// Extracted: 2026-04-03T15:54:19.660Z
// DO NOT EDIT — re-generated by scripts/extract_modules_local.js
// @section CHARTS — Bar charts and longitudinal progress
const SimpleBarChart = React.memo(({ data, color = "indigo" }) => {
  const { t } = useContext(LanguageContext);
  const height = 150;
  const width = 300;
  const margin = 20;
  const chartHeight = height - margin * 2;
  const chartWidth = width - margin * 2;
  if (!data || data.length === 0) return <div className="text-xs text-slate-500 italic text-center py-8">{t('dashboard.empty.no_data')}</div>;
  const maxValue = Math.max(...data.map(d => d.value), 1);
  const barWidth = Math.min(40, (chartWidth / data.length) * 0.6);
  const gap = (chartWidth - (barWidth * data.length)) / (data.length + 1);
  return (
    <div className="w-full h-full flex items-center justify-center select-none">
      <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-auto max-h-[160px]" preserveAspectRatio="xMidYMid meet" role="img" aria-label={t('dashboard.bar_chart_aria') || 'Bar chart showing session data'}>
        {data.map((d, i) => {
          const barHeight = (d.value / maxValue) * chartHeight;
          const x = gap + i * (barWidth + gap);
          const y = height - margin - barHeight;
          return (
            <g key={i} className="group">
              <rect
                x={x}
                y={y}
                width={barWidth}
                height={barHeight}
                rx="4"
                className={`fill-${color}-500 group-hover:fill-${color}-600 transition-all duration-300`}
              />
              <text
                x={x + barWidth / 2}
                y={y - 5}
                textAnchor="middle"
                className="fill-slate-500 text-[10px] font-bold opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 transition-opacity"
              >
                {d.value}
              </text>
              <text
                x={x + barWidth / 2}
                y={height - 5}
                textAnchor="middle"
                className="fill-slate-400 text-[11px] uppercase tracking-wider font-medium"
              >
                {d.label.length > 5 ? d.label.substring(0, 4) + '.' : d.label}
              </text>
            </g>
          );
        })}
        <line x1="0" y1={height - margin} x2={width} y2={height - margin} stroke="#e2e8f0" strokeWidth="2" strokeLinecap="round" />
      </svg>
    </div>
  );
});
const SimpleDonutChart = ({ percentage, label, color = "indigo" }) => {
  const size = 100;
  const strokeWidth = 10;
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const safePercent = Math.min(100, Math.max(0, percentage || 0));
  const offset = circumference - (safePercent / 100) * circumference;
  return (
    <div className="flex flex-col items-center justify-center select-none">
      <div className="relative w-24 h-24">
        <svg viewBox={`0 0 ${size} ${size}`} className="transform -rotate-90 w-full h-full" role="img" aria-label={`${safePercent}% complete`}>
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            className="stroke-slate-100 fill-none"
            strokeWidth={strokeWidth}
          />
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            className={`stroke-${color}-500 fill-none transition-all duration-1000 ease-out`}
            strokeWidth={strokeWidth}
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap="round"
          />
        </svg>
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span className={`text-xl font-black text-${color}-600`}>{Math.round(safePercent)}%</span>
        </div>
      </div>
      <span className="text-xs font-bold text-slate-500 uppercase tracking-wider mt-2 text-center leading-tight">{label}</span>
    </div>
  );
};
const ConfettiEffect = ({ isActive }) => {
  if (!isActive) return null;
  const colors = ['#f43f5e', '#8b5cf6', '#3b82f6', '#22c55e', '#f59e0b', '#ec4899'];
  const particles = Array.from({ length: 50 }, (_, i) => ({
    id: i,
    color: colors[i % colors.length],
    left: Math.random() * 100,
    delay: Math.random() * 2,
    size: Math.random() * 8 + 4,
    duration: Math.random() * 2 + 2
  }));
  return (
    <div className="fixed inset-0 pointer-events-none z-[10001] overflow-hidden">
      <style>{`
        @keyframes confetti-fall {
          0% { transform: translateY(-100px) rotate(0deg); opacity: 1; }
          100% { transform: translateY(100vh) rotate(720deg); opacity: 0; }
        }
        .confetti-particle {
          position: absolute;
          top: -20px;
          animation: confetti-fall linear forwards;
        }
      `}</style>
      {particles.map(p => (
        <div
          key={p.id}
          className="confetti-particle"
          style={{
            left: `${p.left}%`,
            width: p.size,
            height: p.size,
            backgroundColor: p.color,
            animationDelay: `${p.delay}s`,
            animationDuration: `${p.duration}s`,
            borderRadius: Math.random() > 0.5 ? '50%' : '0%',
          }}
        />
      ))}
    </div>
  );
};
