// AlloFlow Section: CHARTS
// Module: modules/analytics
// Variant: local (cloud-stripped)
// Source lines: 6095–6112
// Hash: 80a78fa8de7745fe
// Cloud stripped: false (0 replacements)
// Extracted: 2026-04-11T18:46:20.676Z
// DO NOT EDIT — re-generated by scripts/extract_modules_local.js
// @section CHARTS — CDN wrappers (source: teacher_module.js)
const SimpleBarChart = React.memo((props) => {
    const Ext = window.AlloModules && window.AlloModules.SimpleBarChart;
    if (Ext) return <Ext {...props} />;
    return <div className="text-xs text-slate-600 italic text-center py-4">Loading chart...</div>;
});
const SimpleDonutChart = (props) => {
    const Ext = window.AlloModules && window.AlloModules.SimpleDonutChart;
    if (Ext) return <Ext {...props} />;
    return <div className="text-xs text-slate-600 italic text-center py-4">Loading chart...</div>;
};
const ConfettiEffect = ({ isActive }) => {
    if (!isActive) return null;
    const Ext = window.AlloModules && window.AlloModules.ConfettiEffect;
    if (Ext) return <Ext isActive={isActive} />;
    return null;
};

