// AlloFlow Section: SPEECH_BUBBLE
// Module: modules/allobot
// Variant: local (cloud-stripped)
// Source lines: 4452–4474
// Hash: 53310f9e08667b0f
// Cloud stripped: false (0 replacements)
// Extracted: 2026-04-11T18:46:20.676Z
// DO NOT EDIT — re-generated by scripts/extract_modules_local.js
// @section SPEECH_BUBBLE — CDN wrapper (source: allobot_source.jsx → allobot_module.js)
// Full components (SpeechBubble, LandingDust, JetpackParticles, ReactionBubble, BotConfettiBurst, AlloBot)
// extracted to allobot_module.js (~2,175 lines → 16-line wrapper).
const SpeechBubble = React.memo((props) => {
    const Ext = window.AlloModules && window.AlloModules.SpeechBubble;
    return Ext ? <Ext {...props} /> : null;
});
const LandingDust = (props) => {
    const Ext = window.AlloModules && window.AlloModules.LandingDust;
    return Ext ? <Ext {...props} /> : null;
};
const JetpackParticles = (props) => {
    const Ext = window.AlloModules && window.AlloModules.JetpackParticles;
    return Ext ? <Ext {...props} /> : null;
};
const ReactionBubble = (props) => {
    const Ext = window.AlloModules && window.AlloModules.ReactionBubble;
    return Ext ? <Ext {...props} /> : null;
};
const BotConfettiBurst = (props) => {
    const Ext = window.AlloModules && window.AlloModules.BotConfettiBurst;
    return Ext ? <Ext {...props} /> : null;
};
