// AlloFlow Section: ADVENTURE_UI
// Module: modules/adventure
// Variant: local (cloud-stripped)
// Source lines: 10906–11781
// Hash: 883a9564a0f250a4
// Cloud stripped: false (0 replacements)
// Extracted: 2026-04-03T01:00:22.506Z
// DO NOT EDIT — re-generated by scripts/extract_modules_local.js
// @section ADVENTURE_UI — Inventory, dice, shop, role selection, student entry
const InventoryGrid = React.memo(({ inventory, onSelect }) => {
  if (!inventory || inventory.length === 0) return null;
  return (
    <div className="flex items-center gap-2 bg-indigo-800/50 px-4 py-1.5 rounded-full border border-indigo-600/50">
      <Backpack size={16} className="text-yellow-400" />
      <div className="flex -space-x-2">
        {inventory.map((item, idx) => (
          <div
            key={item.id || idx}
            data-help-key="inventory_item" onClick={() => onSelect(item)}
            className="group relative transition-transform hover:z-20 hover:scale-110 cursor-pointer"
          >
            <div className="w-8 h-8 rounded-lg bg-indigo-950 border-2 border-indigo-400 flex items-center justify-center overflow-hidden shadow-sm relative">
              {item.image ? (
                <img loading="lazy"
                  src={item.image}
                  alt={item.name}
                  className="w-full h-full object-contain pixelated"
                  style={STYLE_IMAGE_PIXELATED}
                  decoding="async"
                />
              ) : item.icon ? (
                <span className="text-lg">{item.icon}</span>
              ) : item.isLoading ? (
                <RefreshCw size={10} className="text-indigo-600 animate-spin"/>
              ) : (
                <span className="text-[10px] font-bold text-indigo-300">{item.name.charAt(0)}</span>
              )}
            </div>
            <div className="absolute top-full left-1/2 -translate-x-1/2 mt-2 hidden group-hover:flex flex-col items-center z-50 w-32">
              <div className="w-2 h-2 bg-black/90 rotate-45 -mb-1 border-t border-l border-white/20"></div>
              <div className="bg-black/90 text-white text-[10px] px-2 py-1 rounded shadow-lg font-bold border border-white/20 text-center">
                {item.name}
                {item.effectType && <div className="font-normal opacity-80 text-[11px] mt-0.5 border-t border-white/10 pt-0.5">{item.description}</div>}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}, (prevProps, nextProps) => {
  if (prevProps.inventory === nextProps.inventory) return true;
  if (!prevProps.inventory || !nextProps.inventory) return false;
  if (prevProps.inventory.length !== nextProps.inventory.length) return false;
  for (let i = 0; i < prevProps.inventory.length; i++) {
      const prev = prevProps.inventory[i];
      const next = nextProps.inventory[i];
      if (!prev || !next) return false;
      if (prev.id !== next.id) return false;
      if (prev.image !== next.image) return false;
      if (prev.isLoading !== next.isLoading) return false;
  }
  return true;
});
const DiceOverlay = React.memo(({ result, onComplete }) => {
  const { t } = useContext(LanguageContext);
  const [currentRotation, setCurrentRotation] = useState(() => {
      const rX = Math.floor(Math.random() * 360);
      const rY = Math.floor(Math.random() * 360);
      return `rotateX(${rX}deg) rotateY(${rY}deg) rotateZ(0deg)`;
  });
  useEffect(() => {
    playDiceSound();
    const spinCount = 4 + Math.floor(Math.random() * 2);
    const targetRotation = getD20Rotation(result, spinCount);
    const rollTimer = setTimeout(() => {
        setCurrentRotation(targetRotation);
    }, 50);
    const endTimer = setTimeout(() => onComplete(), 3500);
    return () => {
      clearTimeout(rollTimer);
      clearTimeout(endTimer);
    };
  }, [onComplete, result]);
  return (
    <div
      className="fixed inset-0 bg-black/60 z-[200] backdrop-blur-sm flex items-center justify-center"
      onClick={onComplete}
    >
      <button
        onClick={(e) => { e.stopPropagation(); onComplete(); }}
        className="absolute top-6 right-6 text-white/70 hover:text-white bg-white/10 hover:bg-white/20 p-2 rounded-full transition-colors z-[202]"
        title={t('common.skip_animation')}
        aria-label={t('common.skip_animation')}
      >
        <X size={32} />
      </button>
      <div role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); e.currentTarget.click(); }}} className="dice-container" onClick={(e) => e.stopPropagation()}>
        <div
          className="dice"
          style={{ transform: currentRotation }}
        >
            {Array.from({ length: 20 }, (_, i) => {
                const num = i + 1;
                const isResult = num === result;
                return (
                    <div
                        key={i}
                        className={`face face-${num} ${isResult ? 'bg-yellow-400 text-indigo-900 border-yellow-500 shadow-[inset_0_0_40px_rgba(255,255,255,0.4)]' : ''}`}
                    >
                        {num}
                    </div>
                );
            })}
        </div>
      </div>
    </div>
  );
});
const AdventureShop = React.memo(({ gold, globalXP, onClose, onPurchase }) => {
  const shopRef = useRef(null);
  useFocusTrap(shopRef, true);
  const { t } = useContext(LanguageContext);
  return (
    <div
        ref={shopRef}
        role="dialog"
        aria-modal="true"
        className="fixed inset-0 z-[150] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-200"
        onClick={onClose}
    >
      <div role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); e.currentTarget.click(); }}} className="bg-slate-900 border-4 border-indigo-500 rounded-3xl shadow-2xl max-w-2xl w-full overflow-hidden relative flex flex-col max-h-[90vh]" onClick={e => e.stopPropagation()}>
        <div className="bg-indigo-600 p-3 sm:p-6 text-white flex justify-between items-center shrink-0 shadow-lg relative z-10">
            <div>
                <h2 className="text-2xl font-black uppercase tracking-widest flex items-center gap-3">
                    <div className="bg-yellow-400 text-indigo-900 p-2 rounded-lg shadow-inner border-2 border-indigo-800">
                        <ShoppingBag size={24} />
                    </div>
                    {t('adventure.shop')}
                </h2>
                <p className="text-indigo-200 text-sm font-bold mt-1 ml-1">{t('adventure.shop_desc')}</p>
            </div>
            <button onClick={onClose} className="bg-indigo-800 hover:bg-indigo-700 text-white p-2 rounded-full transition-colors border-2 border-indigo-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" autoFocus aria-label={t('adventure.close_shop_aria')}>
                <X size={24}/>
            </button>
        </div>
        <div className="bg-slate-800 p-2 sm:p-4 flex justify-between items-center border-b border-slate-700 shrink-0 gap-2 sm:gap-4 flex-wrap sm:flex-nowrap">
            <div className="flex gap-6">
                <div className="flex items-center gap-2 bg-slate-700 px-4 py-2 rounded-xl border border-slate-600">
                    <span className="text-2xl">💰</span>
                    <div>
                        <div className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">{t('adventure.gold')}</div>
                        <div className="text-xl font-black text-yellow-400 leading-none">{gold}</div>
                    </div>
                </div>
                <div className="flex items-center gap-2 bg-slate-700 px-4 py-2 rounded-xl border border-slate-600">
                    <span className="text-2xl">🏆</span>
                    <div>
                        <div className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">{t('adventure.global_xp')}</div>
                        <div className="text-xl font-black text-green-400 leading-none">{globalXP}</div>
                    </div>
                </div>
            </div>
            <div className="text-xs text-slate-500 italic text-right ml-auto">
                {t('adventure.xp_earn_tip')}
            </div>
        </div>
        <div className="p-3 sm:p-6 overflow-y-auto custom-scrollbar bg-slate-900 grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4 flex-1 min-h-0">
            {ADVENTURE_SHOP_ITEMS.map((item) => (
                <div key={item.id} className="bg-slate-800 border-2 border-slate-700 rounded-2xl p-3 sm:p-4 flex flex-col hover:border-indigo-500 transition-colors group relative overflow-hidden">
                    <div className="flex justify-between items-start mb-2 relative z-10">
                        <div className="text-2xl sm:text-4xl bg-slate-700 w-10 h-10 sm:w-16 sm:h-16 rounded-xl flex items-center justify-center shadow-inner border border-slate-600">
                            {item.icon}
                        </div>
                        <div className="text-right">
                            <div className="text-yellow-400 font-black text-lg">{item.cost} G</div>
                            <span className="text-[10px] font-bold uppercase text-slate-300 bg-slate-900 px-2 py-0.5 rounded border border-slate-700">
                                {t(`adventure.effects.${item.effectType}`) || item.effectType}
                            </span>
                        </div>
                    </div>
                    <div className="relative z-10 flex flex-col flex-1">
                        <h3 className="text-white font-bold text-lg mb-1 group-hover:text-indigo-300 transition-colors">
                            {t(`adventure.shop_items.${item.id}_name`) || item.name}
                        </h3>
                        <p className="text-slate-500 text-xs leading-relaxed mb-2 sm:mb-4 min-h-[2em] flex-1 overflow-y-auto custom-scrollbar">
                            {t(`adventure.shop_items.${item.id}_desc`) || item.description}
                        </p>
                        <button
                            onClick={() => onPurchase(item)}
                            disabled={gold < item.cost}
                            className={`w-full py-2 sm:py-2.5 rounded-xl font-bold text-sm sm:text-base flex items-center justify-center gap-2 transition-all active:scale-95 shrink-0 min-h-[40px] ${
                                gold >= item.cost
                                ? 'bg-yellow-500 hover:bg-yellow-400 text-indigo-900 shadow-lg shadow-yellow-500/30 border-2 border-yellow-300 ring-1 ring-yellow-400/50'
                                : 'bg-slate-700 text-slate-500 cursor-not-allowed'
                            }`}
                        >
                            {gold >= item.cost ? t('adventure.buy_now') : t('adventure.no_gold')}
                        </button>
                    </div>
                    <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none"></div>
                </div>
            ))}
        </div>
      </div>
    </div>
  );
});
const RoleSelectionModal = React.memo(({ onSelect, onGateRequired }) => {
  const { t } = useContext(LanguageContext);
  const roleRef = useRef(null);
  useFocusTrap(roleRef, true);
  const handleRoleClick = (role) => {
    if (APP_CONFIG._cfg_validation_key && ['teacher', 'parent', 'independent'].includes(role)) {
        if (onGateRequired) onGateRequired(role);
    } else {
        onSelect(role);
    }
  };
  const [micStatus, setMicStatus] = useState('idle');
  const handleMicCheck = () => {
      const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
      if (!SpeechRecognition) {
          alert(t('roles.voice_not_supported'));
          return;
      }
      setMicStatus('requesting');
      const recognition = new SpeechRecognition();
      recognition.onstart = () => {
          setMicStatus('granted');
          recognition.stop();
      };
      recognition.onerror = (event) => {
          if (event.error === 'not-allowed' || event.error === 'permission-denied') {
              setMicStatus('denied');
          } else {
              setMicStatus('granted');
          }
      };
      try {
          recognition.start();
      } catch (e) {
          warnLog("Unhandled error:", e);
          setMicStatus('denied');
      }
  };
  return (
  <div
    ref={roleRef}
    role="dialog"
    aria-modal="true"
    className="fixed inset-0 z-[300] bg-slate-900/90 backdrop-blur-md overflow-y-auto py-8 px-4 animate-in fade-in duration-300"
  >
    <div className="min-h-full flex items-center justify-center">
    <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-3xl w-full text-center border-4 border-indigo-100 transform transition-all animate-in zoom-in-95 duration-300 relative">
      <div className="absolute top-4 right-4">
          <UiLanguageSelector />
      </div>
      <div className="flex justify-center mb-6">
        <div className="bg-indigo-100 p-4 rounded-full shadow-inner">
           <Layers size={48} className="text-indigo-600" />
        </div>
      </div>
      <h2 className="text-3xl font-black text-slate-800 mb-2 tracking-tight">{t('roles.title')}</h2>
      <p className="text-slate-500 mb-8 font-medium">{t('roles.subtitle')}</p>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <button
            onClick={() => handleRoleClick('student')}
            className="flex flex-col items-center h-full justify-start gap-3 p-6 rounded-xl border-2 border-slate-100 hover:border-teal-400 hover:bg-teal-50 transition-all group shadow-sm hover:shadow-md active:scale-95 focus:ring-4 focus:ring-indigo-500 focus:ring-offset-2 focus:outline-none"
            data-help-key="role_student"
        >
            <div className="bg-teal-100 text-teal-600 p-4 rounded-full group-hover:scale-110 transition-transform group-hover:rotate-12">
                <GraduationCap size={32} />
            </div>
            <span className="font-bold text-slate-700 group-hover:text-teal-700">{t('roles.student')}</span>
        </button>
        <button
            onClick={() => handleRoleClick('teacher')}
            className="flex flex-col items-center h-full justify-start gap-3 p-6 rounded-xl border-2 border-slate-100 hover:border-indigo-400 hover:bg-indigo-50 transition-all group shadow-sm hover:shadow-md active:scale-95 focus:ring-4 focus:ring-indigo-500 focus:ring-offset-2 focus:outline-none"
            data-help-key="role_teacher"
        >
            <div className="bg-indigo-100 text-indigo-600 p-4 rounded-full group-hover:scale-110 transition-transform group-hover:-rotate-12">
                <School size={32} />
            </div>
            <span className="font-bold text-slate-700 group-hover:text-indigo-700">{t('roles.teacher')}</span>
        </button>
        <button
            aria-label={t('common.like')}
            onClick={() => handleRoleClick('parent')}
            className="flex flex-col items-center h-full justify-start gap-3 p-6 rounded-xl border-2 border-slate-100 hover:border-orange-400 hover:bg-orange-50 transition-all group shadow-sm hover:shadow-md active:scale-95 focus:ring-4 focus:ring-indigo-500 focus:ring-offset-2 focus:outline-none"
            data-help-key="role_parent"
        >
            <div className="bg-orange-100 text-orange-600 p-4 rounded-full group-hover:scale-110 transition-transform group-hover:rotate-12">
                <Heart size={32} />
            </div>
            <span className="font-bold text-slate-700 group-hover:text-orange-700">{t('roles.parent')}</span>
        </button>
        <button
            onClick={() => handleRoleClick('independent')}
            className="flex flex-col items-center h-full justify-start gap-3 p-6 rounded-xl border-2 border-slate-100 hover:border-cyan-400 hover:bg-cyan-50 transition-all group shadow-sm hover:shadow-md active:scale-95 focus:ring-4 focus:ring-cyan-500 focus:ring-offset-2 focus:outline-none"
            data-help-key="role_independent"
        >
            <div className="bg-cyan-100 text-cyan-600 p-4 rounded-full group-hover:scale-110 transition-transform group-hover:rotate-12">
                <UserCircle2 size={32} />
            </div>
            <span className="font-bold text-slate-700 group-hover:text-cyan-700">{t('roles.independent')}</span>
        </button>
      </div>
      <div className="border-t border-slate-100 pt-4">
          <p className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-2">{t('roles.mic_setup')}</p>
          <button
              aria-label={t('common.confirm')}
            onClick={handleMicCheck}
            disabled={micStatus === 'granted' || micStatus === 'requesting'}
            className={`flex items-center justify-center gap-2 w-full py-2 rounded-lg text-xs font-bold transition-all ${
                micStatus === 'granted' ? 'bg-green-100 text-green-700 cursor-default' :
                micStatus === 'denied' ? 'bg-red-50 text-red-500 border border-red-100' :
                micStatus === 'requesting' ? 'bg-slate-100 text-slate-500' :
                'bg-white border border-slate-200 text-slate-500 hover:bg-slate-50 hover:text-indigo-600'
            }`}
          >
              {micStatus === 'granted' ? <CheckCircle size={14} /> :
               micStatus === 'denied' ? <XCircle size={14} /> :
               micStatus === 'requesting' ? <RefreshCw size={14} className="animate-spin"/> :
               <Mic size={14} />}
              {micStatus === 'granted' ? t('roles.mic_ready') :
               micStatus === 'denied' ? t('roles.mic_denied') :
               micStatus === 'requesting' ? t('roles.mic_requesting') :
               t('roles.mic_enable')}
          </button>
          {micStatus === 'idle' && (
              <p className="text-[11px] text-slate-500 mt-2">
                  {t('roles.mic_tip')}
              </p>
          )}
      </div>
    </div>
    </div>
  </div>
  );
});
const StudentEntryModal = React.memo(({ isOpen, onClose, onConfirm }) => {
  const { t } = useContext(LanguageContext);
  const [selectedAdj, setSelectedAdj] = useState('');
  const [selectedAnimal, setSelectedAnimal] = useState('');
  const entryRef = useRef(null);
  useFocusTrap(entryRef, isOpen);
  const adjectives = t('codenames.adjectives') || [];
  const animals = t('codenames.animals') || [];
  const randomizeName = useCallback(() => {
    if (adjectives.length > 0 && animals.length > 0) {
        const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
        const animal = animals[Math.floor(Math.random() * animals.length)];
        setSelectedAdj(adj);
        setSelectedAnimal(animal);
    }
  }, [adjectives, animals]);
  useEffect(() => {
    if (isOpen && (!selectedAdj || !selectedAnimal)) {
      randomizeName();
    }
  }, [isOpen, randomizeName]);
  const getFullName = () => `${selectedAdj} ${selectedAnimal}`;
  const handleConfirm = (mode) => {
    if (selectedAdj && selectedAnimal) {
      onConfirm(getFullName(), mode);
    }
  };
  if (!isOpen) return null;
  return (
    <div
        ref={entryRef}
        role="dialog"
        aria-modal="true"
        className="fixed inset-0 z-[300] bg-slate-900/90 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-300"
    >
      <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full text-center border-4 border-indigo-100 transform transition-all animate-in zoom-in-95 duration-300 relative">
        <button
            onClick={onClose}
            className="absolute top-4 right-4 p-2 rounded-full text-slate-500 hover:text-slate-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors"
            aria-label={t('common.close')}
        >
            <X size={20} />
        </button>
        <h2 className="text-2xl font-black text-slate-800 mb-2">{t('wizard.step_codename') || 'Pick Your Codename!'}</h2>
        <p className="text-slate-500 mb-6 font-medium">{t('modals.student_entry_sub')}</p>
        <div className="bg-indigo-50 p-4 rounded-xl border border-indigo-100 mb-6">
            <div className="flex gap-2 mb-4">
                <select
                    value={selectedAdj}
                    onChange={(e) => setSelectedAdj(e.target.value)}
                    className="w-1/2 p-2 rounded-lg border border-indigo-200 text-indigo-900 font-bold text-sm focus:ring-2 focus:ring-indigo-400 outline-none cursor-pointer"
                    aria-label={t('modals.entry.select_adjective')}
                    data-help-key="entry_adjective"
                >
                    {adjectives.map((adj, i) => (
                        <option key={i} value={adj}>{adj}</option>
                    ))}
                </select>
                <select
                    value={selectedAnimal}
                    onChange={(e) => setSelectedAnimal(e.target.value)}
                    className="w-1/2 p-2 rounded-lg border border-indigo-200 text-indigo-900 font-bold text-sm focus:ring-2 focus:ring-indigo-400 outline-none cursor-pointer"
                    aria-label={t('modals.entry.select_animal')}
                    data-help-key="entry_animal"
                >
                    {animals.map((anim, i) => (
                        <option key={i} value={anim}>{anim}</option>
                    ))}
                </select>
            </div>
            <div className="flex items-center justify-between bg-white p-3 rounded-xl shadow-sm border border-indigo-100">
                <div className="text-xl font-black text-indigo-600 tracking-tight truncate mr-2">
                    {selectedAdj} {selectedAnimal}
                </div>
                <button
                    onClick={randomizeName}
                    className="p-2 bg-indigo-100 text-indigo-600 rounded-full hover:bg-indigo-200 hover:scale-110 transition-all shrink-0"
                    title={t('modals.entry.randomize_codename')}
                    aria-label={t('modals.entry.randomize_codename')}
                    data-help-key="entry_randomize_btn"
                >
                    <RefreshCw size={18} />
                </button>
            </div>
        </div>
        <p className="text-xs text-slate-500 font-bold flex items-center justify-center gap-1 mb-6">
            <ShieldCheck size={12} className="text-green-500"/> {t('entry.warning')}
        </p>
        <div className="flex flex-col gap-3">
            <button
                aria-label={t('common.generate')}
                onClick={() => handleConfirm('new')}
                disabled={!selectedAdj || !selectedAnimal}
                className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 rounded-xl shadow-lg transition-all active:scale-95 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                data-help-key="entry_start_new"
            >
                <Sparkles size={18} className="text-yellow-400 fill-current" /> {t('entry.start')}
            </button>
            <button
                aria-label={t('common.upload')}
                onClick={() => handleConfirm('load')}
                disabled={!selectedAdj || !selectedAnimal}
                className="w-full bg-white border-2 border-slate-200 text-slate-600 hover:border-indigo-300 hover:text-indigo-600 font-bold py-2.5 rounded-xl transition-all active:scale-95 flex items-center justify-center gap-2 text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                data-help-key="entry_load_exist"
            >
                <Upload size={16} /> {t('entry.load')}
            </button>
        </div>
        <button onClick={onClose} className="mt-4 text-sm text-slate-500 hover:text-slate-600 underline focus:outline-none focus:ring-2 focus:ring-slate-400 rounded">{t('common.cancel')}</button>
      </div>
    </div>
  );
});
const StudentWelcomeModal = React.memo(({ isOpen, onClose, onUpload }) => {
  const { t } = useContext(LanguageContext);
  const welcomeRef = useRef(null);
  useFocusTrap(welcomeRef, isOpen);
  if (!isOpen) return null;
  return (
    <div
        ref={welcomeRef}
        role="dialog"
        aria-modal="true"
        className="fixed inset-0 z-[300] bg-slate-900/90 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-300"
    >
      <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full text-center border-4 border-teal-100 transform transition-all animate-in zoom-in-95 duration-300 relative">
        <button
            onClick={onClose}
            className="absolute top-4 right-4 p-2 rounded-full text-slate-500 hover:text-slate-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors"
            aria-label={t('welcome.close_aria')}
        >
            <X size={20} />
        </button>
        <div className="flex justify-center mb-6">
          <div className="bg-teal-100 p-4 rounded-full shadow-inner">
             <FolderOpen size={48} className="text-teal-600" />
          </div>
        </div>
        <h2 className="text-2xl font-black text-slate-800 mb-2">{t('modals.student_welcome')}</h2>
        <p className="text-slate-500 mb-8 font-medium">{t('welcome.prompt')}</p>
        <div className="space-y-3">
            <button
                aria-label={t('common.upload')}
                onClick={() => {
                    onUpload();
                    onClose();
                }}
                className="w-full flex items-center justify-center gap-3 p-4 rounded-xl bg-teal-700 text-white font-bold hover:bg-teal-700 transition-all shadow-md hover:shadow-lg hover:scale-[1.02] active:scale-95"
                data-help-key="welcome_load_btn"
            >
                <Upload size={20} /> {t('welcome.load')}
            </button>
            <button
                aria-label={t('common.close')}
                onClick={onClose}
                className="w-full p-3 rounded-xl text-slate-500 font-bold hover:bg-slate-100 transition-colors active:scale-95"
                data-help-key="welcome_skip_btn"
            >
                {t('welcome.skip')}
            </button>
        </div>
      </div>
    </div>
  );
});
const RosterKeyPanel = React.memo(({ isOpen, onClose, rosterKey, setRosterKey, onApplyGroup, onSyncToSession, onBatchGenerate, activeSessionCode, t, isParentMode, isIndependentMode }) => {
  const [newGroupName, setNewGroupName] = useState('');
  const [newGroupColor, setNewGroupColor] = useState('#4F46E5');
  const [newStudentName, setNewStudentName] = useState('');
  const [rosterAdj, setRosterAdj] = useState('');
  const [rosterAnimal, setRosterAnimal] = useState('');
  const [useCustomName, setUseCustomName] = useState(false);
  const rosterAdjectives = t('codenames.adjectives') || [];
  const rosterAnimals = t('codenames.animals') || [];
  const randomizeRosterName = () => {
    if (rosterAdjectives.length > 0 && rosterAnimals.length > 0) {
      setRosterAdj(rosterAdjectives[Math.floor(Math.random() * rosterAdjectives.length)]);
      setRosterAnimal(rosterAnimals[Math.floor(Math.random() * rosterAnimals.length)]);
    }
  };
  const [newStudentGroup, setNewStudentGroup] = useState('');
  const [expandedGroup, setExpandedGroup] = useState(null);
  const [editingField, setEditingField] = useState(null);
  const [showBatchConfig, setShowBatchConfig] = useState(false);
  const [batchTypes, setBatchTypes] = useState({ simplified: true, glossary: false, quiz: false, 'sentence-frames': false, brainstorm: false, faq: false, outline: false, adventure: false, 'concept-sort': false, image: false, timeline: false, dbq: false });
  const fileInputRef = useRef(null);
  const panelRef = useRef(null);
  useFocusTrap(panelRef, isOpen);
  if (!isOpen) return null;
  const groups = rosterKey?.groups || {};
  const students = rosterKey?.students || {};
  const groupIds = Object.keys(groups);
  const getStudentsInGroup = (gId) => Object.entries(students).filter(([_, g]) => g === gId).map(([name]) => name);
  const getUnassigned = () => Object.entries(students).filter(([_, g]) => !g || !groups[g]).map(([name]) => name);
  const handleImport = (e) => {
    const file = e.target?.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const data = JSON.parse(ev.target.result);
        if (data.groups || data.students) {
          setRosterKey({ className: data.className || '', groups: data.groups || {}, students: data.students || {} });
        }
      } catch(err) { console.error('Invalid roster JSON:', err); }
    };
    reader.readAsText(file);
    e.target.value = '';
  };
  const handleExport = () => {
    const exportData = {
            ...(rosterKey || { groups: {}, students: {} }),
            exportVersion: 2,
            exportDate: new Date().toISOString()
        };
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'roster_key_' + (rosterKey?.className || 'roster').replace(/[^a-zA-Z0-9]/g, '_') + '_' + new Date().toISOString().slice(0,10) + '.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  const handleAddGroup = () => {
    if (!newGroupName.trim()) return;
    const id = newGroupName.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-');
    setRosterKey(prev => ({
      ...(prev || { students: {} }),
      className: prev?.className || '',
      groups: { ...(prev?.groups || {}), [id]: { name: newGroupName.trim(), color: newGroupColor, profile: { gradeLevel: '3rd Grade', leveledTextLanguage: 'English' } } },
      students: prev?.students || {}
    }));
    setNewGroupName('');
    setExpandedGroup(id);
  };
  const handleRemoveGroup = (gId) => {
    setRosterKey(prev => {
      const ng = { ...prev.groups }; delete ng[gId];
      const ns = { ...prev.students };
      Object.keys(ns).forEach(s => { if (ns[s] === gId) ns[s] = ''; });
      return { ...prev, groups: ng, students: ns };
    });
  };
  const handleUpdateGroupProfile = (gId, field, value) => {
    setRosterKey(prev => ({
      ...prev,
      groups: { ...prev.groups, [gId]: { ...prev.groups[gId], profile: { ...prev.groups[gId].profile, [field]: value } } }
    }));
  };
  const handleUpdateGroupMeta = (gId, field, value) => {
    setRosterKey(prev => ({
      ...prev,
      groups: { ...prev.groups, [gId]: { ...prev.groups[gId], [field]: value } }
    }));
  };
  const handleAddStudent = () => {
    const codename = rosterAdj && rosterAnimal ? `${rosterAdj} ${rosterAnimal}` : '';
    if (!codename) return;
    const displayName = useCustomName && newStudentName.trim() ? newStudentName.trim() : '';
    setRosterKey(prev => ({
      ...(prev || { groups: {} }),
      className: prev?.className || '',
      groups: prev?.groups || {},
      students: { ...(prev?.students || {}), [codename]: newStudentGroup || '' },
      displayNames: { ...(prev?.displayNames || {}), ...(displayName ? { [codename]: displayName } : {}) }
    }));
    setNewStudentName('');
    randomizeRosterName();
  };
  const handleRemoveStudent = (name) => {
    setRosterKey(prev => {
      const ns = { ...prev.students }; delete ns[name];
      return { ...prev, students: ns };
    });
  };
  const handleMoveStudent = (name, toGroup) => {
    setRosterKey(prev => ({ ...prev, students: { ...prev.students, [name]: toGroup } }));
  };
  const COLORS = ['#4F46E5', '#059669', '#D97706', '#DC2626', '#7C3AED', '#0891B2', '#BE185D', '#65A30D'];
  const GRADE_OPTIONS = ['Pre-K', 'Kindergarten', '1st Grade', '2nd Grade', '3rd Grade', '4th Grade', '5th Grade', '6th Grade', '7th Grade', '8th Grade', '9th Grade', '10th Grade', '11th Grade', '12th Grade'];
  const LANG_OPTIONS = ['English', 'Spanish', 'French', 'Arabic', 'Somali', 'Vietnamese', 'Portuguese', 'Mandarin', 'Korean', 'Tagalog', 'Russian', 'Japanese'];
  const ProfileField = ({ label, value, field, gId, type = 'text', options }) => (
    <div className="flex items-center gap-2 text-xs">
      <span className="font-bold text-slate-500 w-24 shrink-0">{label}:</span>
      {type === 'select' ? (
        <select value={value || ''} onChange={e => handleUpdateGroupProfile(gId, field, e.target.value)}
          aria-label={label}
          className="flex-1 px-2 py-1 rounded-lg border border-slate-200 text-slate-700 text-xs focus:ring-2 focus:ring-indigo-400 outline-none">
          <option value="">—</option>
          {options.map(o => <option key={o} value={o}>{o}</option>)}
        </select>
      ) : type === 'range' ? (
        <div className="flex-1 flex items-center gap-2">
          <input type="range" min="0.5" max="1.5" step="0.05" value={value || 1}
            aria-label={label}
            onChange={e => handleUpdateGroupProfile(gId, field, parseFloat(e.target.value))}
            className="flex-1 accent-indigo-500" />
          <span className="text-slate-600 font-mono w-10 text-right">{(value || 1).toFixed(2)}x</span>
        </div>
      ) : type === 'toggle' ? (
        <button onClick={() => handleUpdateGroupProfile(gId, field, !value)}
          className={`px-3 py-1 rounded-full text-xs font-bold transition-all ${value ? 'bg-green-100 text-green-700' : 'bg-slate-100 text-slate-500'}`}>
          {value ? 'On' : 'Off'}
        </button>
      ) : (
        <input type="text" value={value || ''} onChange={e => handleUpdateGroupProfile(gId, field, e.target.value)}
          aria-label={label}
          placeholder="—" className="flex-1 px-2 py-1 rounded-lg border border-slate-200 text-slate-700 text-xs focus:ring-2 focus:ring-indigo-400 outline-none" />
      )}
    </div>
  );
  return (
    <div ref={panelRef} role="dialog" aria-modal="true" className="fixed inset-0 z-[260] bg-slate-900/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[85vh] flex flex-col border-2 border-indigo-100 animate-in zoom-in-95 duration-200">
        <div className="flex items-center justify-between p-5 border-b border-slate-100">
          <div data-help-key="roster_panel_header">
            <h2 className="text-lg font-black text-slate-800 flex items-center gap-2">
              <ClipboardList size={20} className="text-indigo-500" /> {isParentMode ? 'Family Learning Profiles' : (isIndependentMode ? 'My Learning Profile' : (t('roster.title') || 'Class Roster & Progress Tracking'))}
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">{isParentMode ? 'Manage family member profiles and track learning progress' : (isIndependentMode ? 'Manage your learning profile and track your progress' : (t('roster.subtitle') || 'Organize student groups with differentiated profiles for instruction'))}</p>
          </div>
          <button onClick={onClose} className="p-2 rounded-full hover:bg-slate-100 transition-colors" aria-label={t('common.close')}>
            <X size={20} className="text-slate-500" />
          </button>
        </div>
        <div className="flex flex-wrap gap-2 px-5 py-3 border-b border-slate-50 bg-slate-50/50">
          <button onClick={() => fileInputRef.current?.click()} className="px-3 py-1.5 bg-indigo-50 text-indigo-700 rounded-lg text-xs font-bold hover:bg-indigo-100 transition-colors flex items-center gap-1.5">
            <Upload size={14} /> {t('roster.import') || 'Import JSON'}
          </button>
          <button onClick={handleExport} disabled={!rosterKey} className="px-3 py-1.5 bg-green-50 text-green-700 rounded-lg text-xs font-bold hover:bg-green-100 transition-colors flex items-center gap-1.5 disabled:opacity-40">
            <Download size={14} /> {t('roster.export') || 'Export JSON'}
          </button>
          <button onClick={() => setShowBatchConfig(true)} disabled={!rosterKey || Object.keys(rosterKey?.groups || {}).length === 0} className="px-3 py-1.5 bg-amber-50 text-amber-700 rounded-lg text-xs font-bold hover:bg-amber-100 transition-colors flex items-center gap-1.5 disabled:opacity-40 border border-amber-200">
            <Layers size={14} /> {t('roster.batch_generate') || 'Differentiate by Group'}
          </button>
          {activeSessionCode && (
            <button onClick={onSyncToSession} disabled={!rosterKey || groupIds.length === 0} className="px-3 py-1.5 bg-purple-50 text-purple-700 rounded-lg text-xs font-bold hover:bg-purple-100 transition-colors flex items-center gap-1.5 disabled:opacity-40 ml-auto">
              <RefreshCw size={14} /> {t('roster.sync_session') || 'Sync to Live Session'}
            </button>
          )}
          <input ref={fileInputRef} type="file" accept=".json" onChange={handleImport} className="hidden" aria-label={t('roster.import') || 'Import roster JSON file'} />
        </div>
        <div className="flex-1 overflow-y-auto p-5 space-y-3 custom-scrollbar">
          <div className="flex items-center gap-2 mb-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">{t('roster.class_name') || 'Class Name'}:</label>
            <input type="text" value={rosterKey?.className || ''} onChange={e => setRosterKey(prev => ({ ...(prev || { groups: {}, students: {} }), className: e.target.value }))}
              aria-label={t('roster.class_name') || 'Class Name'}
              placeholder={t('common.placeholder_ms_smith_period_3')}
              className="flex-1 px-3 py-1.5 rounded-lg border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-400 outline-none" />
          </div>
          {groupIds.map(gId => {
            const group = groups[gId];
            const gStudents = getStudentsInGroup(gId);
            const isExpanded = expandedGroup === gId;
            return (
              <div key={gId} className="border border-slate-200 rounded-xl overflow-hidden transition-all hover:border-indigo-200">
                <button onClick={() => setExpandedGroup(isExpanded ? null : gId)}
                  className="w-full flex items-center gap-3 p-3 bg-slate-50 hover:bg-slate-100 transition-colors text-left">
                  <div className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: group.color || '#4F46E5' }} />
                  <div className="flex-1 min-w-0">
                    <div className="font-bold text-sm text-slate-800 truncate">{group.name}</div>
                    <div className="text-[10px] text-slate-500">{gStudents.length} student{gStudents.length !== 1 ? 's' : ''} · {group.profile?.gradeLevel || '—'} · {group.profile?.leveledTextLanguage || '—'}</div>
                  </div>
                  <ChevronDown size={16} className={`text-slate-500 transition-transform ${isExpanded ? 'rotate-180' : ''}`} />
                </button>
                {isExpanded && (
                  <div className="p-4 space-y-3 border-t border-slate-100 bg-white">
                    <div className="flex gap-2 items-center mb-2">
                      <input type="text" value={group.name} onChange={e => handleUpdateGroupMeta(gId, 'name', e.target.value)}
                        aria-label={t('roster.group_name') || 'Group name'}
                        className="flex-1 px-2 py-1 rounded-lg border border-slate-200 text-sm font-bold focus:ring-2 focus:ring-indigo-400 outline-none" />
                      <div className="flex gap-1">
                        {COLORS.map(c => (
                          <button key={c} onClick={() => handleUpdateGroupMeta(gId, 'color', c)}
                            className={`w-5 h-5 rounded-full border-2 transition-all ${group.color === c ? 'border-slate-800 scale-110' : 'border-transparent hover:scale-105'}`}
                            style={{ backgroundColor: c }} />
                        ))}
                      </div>
                    </div>
                    <div className="grid grid-cols-1 gap-2 bg-slate-50 p-3 rounded-xl">
                      <ProfileField label={t('roster.grade') || 'Grade'} value={group.profile?.gradeLevel} field="gradeLevel" gId={gId} type="select" options={GRADE_OPTIONS} />
                      <ProfileField label={t('roster.language') || 'Language'} value={group.profile?.leveledTextLanguage} field="leveledTextLanguage" gId={gId} type="select" options={LANG_OPTIONS} />
                      <ProfileField label={t('roster.reading') || 'Reading Lvl'} value={group.profile?.readingLevel} field="readingLevel" gId={gId} />
                      <ProfileField label={t('roster.interests') || 'Interests'} value={group.profile?.studentInterests} field="studentInterests" gId={gId} />
                      <ProfileField label={t('roster.dok') || 'DOK Level'} value={group.profile?.dokLevel} field="dokLevel" gId={gId} type="select" options={['1', '2', '3', '4']} />
                      <ProfileField label={t('roster.tts_speed') || 'TTS Speed'} value={group.profile?.ttsSpeed} field="ttsSpeed" gId={gId} type="range" />
                      <ProfileField label={t('roster.karaoke') || 'Karaoke'} value={group.profile?.karaokeMode} field="karaokeMode" gId={gId} type="toggle" />
                      <ProfileField label={t('roster.simplify') || 'Simplify'} value={group.profile?.simplifyLevel} field="simplifyLevel" gId={gId} type="select" options={['basic', 'intermediate', 'advanced']} />
                      <ProfileField label={t('roster.custom') || 'Custom Instr.'} value={group.profile?.leveledTextCustomInstructions} field="leveledTextCustomInstructions" gId={gId} />
                    </div>
                    <div>
                      <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-1.5">{t('roster.students_in_group') || 'Students'}</div>
                      <div className="flex flex-wrap gap-1.5">
                        {gStudents.map(name => (
                          <span key={name} className="inline-flex items-center gap-1 px-2.5 py-1 bg-indigo-50 text-indigo-700 rounded-full text-xs font-medium">
                            {name}
                            {rosterKey?.progressHistory?.[name]?.length > 0 && (
                              <span className="text-[11px] bg-indigo-100 text-indigo-500 px-1 py-0.5 rounded-full font-mono" title={`${rosterKey.progressHistory[name].length} sessions`}>
                                {rosterKey.progressHistory[name].length}s
                              </span>
                            )}
                            <button onClick={() => handleMoveStudent(name, '')} className="hover:text-red-500 transition-colors ml-0.5" aria-label={'Remove ' + name}>
                              <X size={12} />
                            </button>
                          </span>
                        ))}
                        {gStudents.length === 0 && <span className="text-xs text-slate-500 italic">{t('roster.no_students') || 'No students assigned'}</span>}
                      </div>
                    </div>
                    <div className="flex gap-2 pt-2 border-t border-slate-100">
                      <button onClick={() => onApplyGroup(gId)} className="px-3 py-1.5 bg-indigo-600 text-white rounded-lg text-xs font-bold hover:bg-indigo-700 transition-colors flex items-center gap-1.5">
                        <Sparkles size={12} /> {t('roster.apply_to_generator') || 'Apply to Generator'}
                      </button>
                      <button onClick={() => handleRemoveGroup(gId)} className="px-3 py-1.5 bg-red-50 text-red-600 rounded-lg text-xs font-bold hover:bg-red-100 transition-colors ml-auto flex items-center gap-1.5">
                        <Trash2 size={12} /> {t('roster.delete_group') || 'Delete Group'}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
          <div className="flex gap-2 items-center p-3 border-2 border-dashed border-slate-200 rounded-xl hover:border-indigo-300 transition-colors">
            <input type="text" value={newGroupName} onChange={e => setNewGroupName(e.target.value)}
              aria-label={t('roster.new_group_placeholder') || 'New group name'}
              placeholder={t('roster.new_group_placeholder') || 'New group name...'}
              onKeyDown={e => e.key === 'Enter' && handleAddGroup()}
              className="flex-1 px-3 py-1.5 rounded-lg border border-slate-200 text-sm focus:ring-2 focus:ring-indigo-400 outline-none" />
            <div className="flex gap-1">
              {COLORS.slice(0, 4).map(c => (
                <button key={c} onClick={() => setNewGroupColor(c)}
                  className={`w-4 h-4 rounded-full border-2 ${newGroupColor === c ? 'border-slate-800' : 'border-transparent'}`}
                  style={{ backgroundColor: c }} />
              ))}
            </div>
            <button onClick={handleAddGroup} disabled={!newGroupName.trim()}
              className="px-3 py-1.5 bg-indigo-600 text-white rounded-lg text-xs font-bold hover:bg-indigo-700 transition-colors disabled:opacity-40 flex items-center gap-1">
              <Plus size={14} /> {t('roster.add_group') || 'Add'}
            </button>
          </div>
           <div className="mt-4 pt-4 border-t border-slate-100">
             <div className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-2 flex items-center gap-1.5">
               <Users size={14} /> {t('roster.manage_students') || 'Manage Students'}
             </div>
             <div className="flex flex-col gap-2">
               <div className="flex items-center gap-2 text-[10px]">
                 <button onClick={() => { setUseCustomName(false); if (!rosterAdj || !rosterAnimal) randomizeRosterName(); }}
                   className={`px-2 py-1 rounded-full font-bold transition-all ${!useCustomName ? 'bg-teal-100 text-teal-800 border border-teal-300' : 'text-slate-500 hover:text-slate-600'}`}>
                   🎲 Codename Only
                 </button>
                 <button onClick={() => setUseCustomName(true)}
                   className={`px-2 py-1 rounded-full font-bold transition-all ${useCustomName ? 'bg-teal-100 text-teal-800 border border-teal-300' : 'text-slate-500 hover:text-slate-600'}`}>
                   ✏️ Codename + Real Name
                 </button>
               </div>
               <div className="flex gap-2 items-center">
                 <div className="flex-1 flex flex-col gap-1.5">
                     <div className="flex gap-1.5 items-center">
                       <select value={rosterAdj} onChange={e => setRosterAdj(e.target.value)}
                         aria-label={t('codenames.pick_adjective') || 'Pick adjective'}
                         className="flex-1 px-2 py-1.5 rounded-lg border border-slate-200 text-xs focus:ring-2 focus:ring-teal-400 outline-none">
                         <option value="">{t('codenames.pick_adjective') || '— Adjective —'}</option>
                         {rosterAdjectives.map(a => <option key={a} value={a}>{a}</option>)}
                       </select>
                       <select value={rosterAnimal} onChange={e => setRosterAnimal(e.target.value)}
                         aria-label={t('codenames.pick_animal') || 'Pick animal'}
                         className="flex-1 px-2 py-1.5 rounded-lg border border-slate-200 text-xs focus:ring-2 focus:ring-teal-400 outline-none">
                         <option value="">{t('codenames.pick_animal') || '— Animal —'}</option>
                         {rosterAnimals.map(a => <option key={a} value={a}>{a}</option>)}
                       </select>
                       <button onClick={randomizeRosterName} title={t('common.randomize') || 'Randomize'} className="p-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-500 transition-colors">
                         <RefreshCw size={12} />
                       </button>
                     </div>
                     {useCustomName && (
                       <input type="text" value={newStudentName} onChange={e => setNewStudentName(e.target.value)}
                         aria-label={t('roster.display_name_placeholder') || 'Student display name'}
                         placeholder={t('roster.display_name_placeholder') || 'Real name (for your reference only)...'}
                         onKeyDown={e => e.key === 'Enter' && handleAddStudent()}
                         className="px-3 py-1.5 rounded-lg border border-indigo-200 bg-indigo-50/50 text-sm focus:ring-2 focus:ring-indigo-400 outline-none" />
                     )}
                   </div>
                 <select value={newStudentGroup} onChange={e => setNewStudentGroup(e.target.value)}
                   aria-label={t('roster.assign_to_group') || 'Assign to group'}
                   className="px-2 py-1.5 rounded-lg border border-slate-200 text-xs focus:ring-2 focus:ring-indigo-400 outline-none">
                   <option value="">{t('roster.unassigned') || 'Unassigned'}</option>
                   {groupIds.map(gId => <option key={gId} value={gId}>{groups[gId].name}</option>)}
                 </select>
                 <button onClick={handleAddStudent} disabled={!rosterAdj || !rosterAnimal}
                   className="px-3 py-1.5 bg-teal-700 text-white rounded-lg text-xs font-bold hover:bg-teal-700 transition-colors disabled:opacity-40 flex items-center gap-1">
                   <Plus size={14} /> {t('roster.add_student') || 'Add'}
                 </button>
               </div>
               {rosterAdj && rosterAnimal && (
                 <div className="text-xs text-teal-600 font-medium pl-1">
                   {useCustomName && newStudentName.trim()
                     ? <span>Codename: <strong>{rosterAdj} {rosterAnimal}</strong> · Display: <strong>{newStudentName.trim()}</strong></span>
                     : <span>Codename: <strong>{rosterAdj} {rosterAnimal}</strong></span>}
                 </div>
               )}
             </div>
           </div>
          {getUnassigned().length > 0 && (
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl mt-2">
              <div className="text-[10px] font-bold text-amber-700 uppercase tracking-wider mb-1.5">{t('roster.unassigned_students') || 'Unassigned Students'}</div>
              <div className="flex flex-wrap gap-1.5">
                {getUnassigned().map(name => (
                  <span key={name} className="inline-flex items-center gap-1 px-2.5 py-1 bg-white text-amber-800 rounded-full text-xs font-medium border border-amber-200">
                    {name}
                    {rosterKey?.progressHistory?.[name]?.length > 0 && (
                      <span className="text-[11px] bg-amber-100 text-amber-600 px-1 py-0.5 rounded-full font-mono ml-0.5" title={`${rosterKey.progressHistory[name].length} sessions`}>
                        {rosterKey.progressHistory[name].length}s
                      </span>
                    )}
                    <select onChange={e => { if (e.target.value) handleMoveStudent(name, e.target.value); }} value=""
                      aria-label={t('roster.move_student_to_group') || 'Move to group'}
                      className="text-[10px] bg-transparent border-none outline-none focus:ring-2 focus:ring-amber-400 focus:ring-offset-1 cursor-pointer text-amber-600 ml-1 w-4">
                      <option value="">→</option>
                      {groupIds.map(gId => <option key={gId} value={gId}>{groups[gId].name}</option>)}
                    </select>
                    <button onClick={() => handleRemoveStudent(name)} className="hover:text-red-500 transition-colors" aria-label={'Remove ' + name}>
                      <X size={12} />
                    </button>
                  </span>
                ))}
              </div>
            </div>
          )}
          {rosterKey && (
            <div className="flex gap-4 pt-3 border-t border-slate-100 text-[10px] text-slate-500 font-medium">
              <span>{groupIds.length} group{groupIds.length !== 1 ? 's' : ''}</span>
              <span>{Object.keys(students).length} student{Object.keys(students).length !== 1 ? 's' : ''}</span>
              <span>{getUnassigned().length} unassigned</span>
              <span className="ml-auto flex items-center gap-1"><ShieldCheck size={10} className="text-green-500" /> Local only</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
});
