// Generated by scripts/stage-runner.cjs. Do not edit by hand.
export const RUNNER_RELEASE_CONTRACT = {
  "schema": 1,
  "service": "alloflow-remediation-runner",
  "version": "0.3.0",
  "protocol": {
    "runSchema": 1,
    "checkpointSchema": 1,
    "checkpointEngineAbi": 1
  },
  "build": {
    "runnerBuildSha256": "5d74f96a7fadce7099ec73fb939db04c75b1a1960117ba93389b1d2715171217",
    "manifestSha256": "90a7ce58b7882ca6889634ebc2f11da00e4c5fc332f4a8831e072b0dfe036a8e"
  },
  "modelConfig": {
    "geminiBase": "http://gemini.internal/v1beta/models"
  }
} as const;

export type RunnerReleaseContract = typeof RUNNER_RELEASE_CONTRACT;

async function sha256Text(value: string): Promise<string> {
  const hash = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(value),
  );
  return Array.from(
    new Uint8Array(hash),
    (byte) => byte.toString(16).padStart(2, "0"),
  ).join("");
}

export async function expectedRunnerBuildForModel(model: string) {
  if (model.length === 0 || model.length > 256) {
    throw new Error("invalid_runner_model");
  }
  const modelConfigSha256 = await sha256Text(JSON.stringify({
    geminiBase: RUNNER_RELEASE_CONTRACT.modelConfig.geminiBase,
    geminiModel: model,
    geminiFallbackModel: model,
  }));
  const checkpointEngineSha256 = await sha256Text(
    "alloflow-checkpoint-engine-abi:" +
      RUNNER_RELEASE_CONTRACT.protocol.checkpointEngineAbi + "\n" +
      RUNNER_RELEASE_CONTRACT.build.manifestSha256 + "\n" +
      RUNNER_RELEASE_CONTRACT.build.runnerBuildSha256 + "\n" +
      modelConfigSha256,
  );
  return {
    runnerBuildSha256: RUNNER_RELEASE_CONTRACT.build.runnerBuildSha256,
    manifestSha256: RUNNER_RELEASE_CONTRACT.build.manifestSha256,
    modelConfigSha256,
    checkpointEngineSha256,
  } as const;
}
