// Generated by scripts/stage-runner.cjs. Do not edit by hand.
export const RUNNER_RELEASE_CONTRACT = {
  "schema": 1,
  "service": "alloflow-remediation-runner",
  "version": "0.3.0",
  "protocol": {
    "runSchema": 1,
    "checkpointSchema": 1,
    "checkpointEngineAbi": 1
  },
  "build": {
    "runnerBuildSha256": "4c810041bc36c549a05cd3904312e4a27ca760fc7082472937a991a36f0d4d7a",
    "manifestSha256": "a48e5ba690d2b90b97706e4f378e2e04f4b249278c7fe63935e0500b7ed6a31d"
  },
  "modelConfig": {
    "geminiBase": "http://gemini.internal/v1beta/models"
  }
} as const;

export type RunnerReleaseContract = typeof RUNNER_RELEASE_CONTRACT;

async function sha256Text(value: string): Promise<string> {
  const hash = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(value),
  );
  return Array.from(
    new Uint8Array(hash),
    (byte) => byte.toString(16).padStart(2, "0"),
  ).join("");
}

export async function expectedRunnerBuildForModel(model: string) {
  if (model.length === 0 || model.length > 256) {
    throw new Error("invalid_runner_model");
  }
  const modelConfigSha256 = await sha256Text(JSON.stringify({
    geminiBase: RUNNER_RELEASE_CONTRACT.modelConfig.geminiBase,
    geminiModel: model,
    geminiFallbackModel: model,
  }));
  const checkpointEngineSha256 = await sha256Text(
    "alloflow-checkpoint-engine-abi:" +
      RUNNER_RELEASE_CONTRACT.protocol.checkpointEngineAbi + "\n" +
      RUNNER_RELEASE_CONTRACT.build.manifestSha256 + "\n" +
      RUNNER_RELEASE_CONTRACT.build.runnerBuildSha256 + "\n" +
      modelConfigSha256,
  );
  return {
    runnerBuildSha256: RUNNER_RELEASE_CONTRACT.build.runnerBuildSha256,
    manifestSha256: RUNNER_RELEASE_CONTRACT.build.manifestSha256,
    modelConfigSha256,
    checkpointEngineSha256,
  } as const;
}
