/* PasstheEPPP — Question Batch 29 (Domains 5-8, ~70 questions) */
(function(){
if(typeof EPPPData==='undefined')return;

const batch29 = {
5: [ // Assessment & Diagnosis
{q:"A standard error of measurement (SEM) is used to:",options:["Determine test validity","Estimate the range within which a person's true score likely falls","Calculate interrater reliability","Determine the test's factor structure"],correct:1,rationale:"The SEM indicates measurement precision and is used to construct confidence intervals around observed scores. True score = observed score ± SEM. Smaller SEM indicates more precise measurement."},
{q:"Which MMPI-2 validity scale detects clients who are 'faking bad' or exaggerating symptoms?",options:["L (Lie) scale","K (Correction) scale","F (Infrequency) scale","S (Superlative) scale"],correct:2,rationale:"The F scale contains items rarely endorsed by the normative population. Elevated F scores suggest exaggeration, malingering, genuine severe pathology, or random responding. The L scale detects naively positive self-presentation."},
{q:"Construct validity is best established through:",options:["Expert review of test items","Correlation with a criterion measure","Convergent and discriminant evidence","Test-retest reliability"],correct:2,rationale:"Construct validity requires showing that a test correlates with measures of the same construct (convergent validity) and does NOT correlate with measures of different constructs (discriminant validity). Factor analysis also contributes."},
{q:"A test with a reliability coefficient of .60 is generally considered:",options:["Excellent for clinical use","Acceptable for research purposes only","Too low for any use","Adequate for clinical decisions"],correct:1,rationale:"Reliability of .60 is generally below the threshold for clinical use (typically ≥.80-.90 for individual decisions). It may be acceptable for research with group comparisons, where individual precision is less critical."},
{q:"The Wechsler scales use which type of IQ score?",options:["Ratio IQ","Deviation IQ","Mental age","Percentile rank"],correct:1,rationale:"Wechsler scales use deviation IQ scores (M=100, SD=15) based on comparison to age-matched peers in the normative sample. This replaced the older ratio IQ (MA/CA × 100) which was problematic for adults."},
{q:"In psychological assessment, incremental validity refers to:",options:["How much a test score increases over repeated administrations","The extent to which a test adds predictive power beyond existing information","How much a test's reliability increases with more items","The degree to which test norms are updated"],correct:1,rationale:"Incremental validity addresses whether adding a new test to an assessment battery provides meaningful additional predictive value beyond what is already known from other sources. It is essential for justifying test use."},
{q:"A ceiling effect in testing means:",options:["The test is too easy, so high-ability examinees cannot be differentiated","The test is too hard, so low-ability examinees cannot be differentiated","The testing room is too small","Scores are normally distributed"],correct:0,rationale:"A ceiling effect occurs when a test is too easy for the population, causing scores to cluster at the top with no room to differentiate among high-ability individuals. This reduces variability and can mask real differences."},
{q:"Which of the following best describes content validity?",options:["The test predicts future performance","The test measures the theoretical construct it claims to measure","The test adequately samples the domain of content it is intended to assess","The test has high internal consistency"],correct:2,rationale:"Content validity assesses whether test items adequately represent the full domain of the construct being measured. It is typically established through expert judgment and item specification tables, not statistical analysis."},
{q:"Sensitivity of a diagnostic test refers to:",options:["The proportion of true positives correctly identified","The proportion of true negatives correctly identified","The overall accuracy of the test","The test's reliability"],correct:0,rationale:"Sensitivity = true positives / (true positives + false negatives). A highly sensitive test correctly identifies most people WITH the condition but may include false positives. Specificity addresses true negatives."},
{q:"The NEO-PI-R measures which personality model?",options:["Myers-Briggs types","Big Five (Five Factor Model)","Cattell's 16 factors","Eysenck's PEN model"],correct:1,rationale:"The NEO-PI-R (Costa & McCrae) measures the Five Factor Model: Neuroticism, Extraversion, Openness, Agreeableness, and Conscientiousness. Each domain has six facets, for a total of 30 facets."},
{q:"When a test has high specificity, it means:",options:["It correctly identifies people who don't have the condition","It correctly identifies people who do have the condition","It measures only one construct","It has a narrow range of items"],correct:0,rationale:"Specificity = true negatives / (true negatives + false positives). A highly specific test has few false positives — when it says someone does NOT have the condition, it is usually correct."},
{q:"The Halstead-Reitan Neuropsychological Battery is an example of a:",options:["Projective personality test","Fixed neuropsychological battery","Flexible neuropsychological battery","Structured clinical interview"],correct:1,rationale:"The Halstead-Reitan is a fixed battery (standardized set of tests administered to all patients), as opposed to the flexible/process approach used in the Boston Process Approach. It assesses brain-behavior relationships across multiple cognitive domains."},
{q:"Regression to the mean suggests that:",options:["All scores will eventually be average","Extreme scores on initial testing tend to be less extreme on retesting","Test reliability increases over time","Group means never change"],correct:1,rationale:"Regression to the mean is a statistical phenomenon where extreme scores tend to move toward the average on retesting, even without intervention. This is important to consider when evaluating treatment effects."},
{q:"A scatter analysis on the WISC-V refers to examining:",options:["The distribution of scores within a normative sample","Differences between a child's subtest and index scores","The relationship between age and IQ","Test-retest reliability across age groups"],correct:1,rationale:"Scatter analysis examines the pattern of variability across an individual's subtest or index scores. Significant scatter (large discrepancies) can suggest specific cognitive strengths/weaknesses and may inform diagnostic hypotheses."},
{q:"Which assessment tool is considered the gold standard for diagnosing autism spectrum disorder?",options:["MMPI-2","ADOS-2 (Autism Diagnostic Observation Schedule)","Conners Rating Scales","Beck Depression Inventory"],correct:1,rationale:"The ADOS-2 is a semi-structured, standardized observational assessment considered the gold standard for ASD diagnosis. It uses structured social presses to evaluate social communication and restricted/repetitive behaviors."},
{q:"The Bayes' theorem application in assessment shows that positive predictive value depends heavily on:",options:["Test reliability only","Base rate of the condition in the population","The examiner's experience","Test length"],correct:1,rationale:"Even a test with excellent sensitivity and specificity will produce many false positives when the base rate is low. Bayes' theorem shows that positive predictive value is strongly influenced by prior probability (base rate)."},
{q:"Response bias in self-report measures includes all of the following EXCEPT:",options:["Social desirability","Acquiescence (yea-saying)","Random responding","Criterion contamination"],correct:3,rationale:"Criterion contamination is a validity issue (when the criterion measure is influenced by knowledge of predictor scores), not a response bias. Social desirability, acquiescence, and random responding are all common response biases in self-report measures."},
{q:"Concurrent validity is demonstrated when a test:",options:["Predicts future outcomes","Correlates with a criterion measured at the same time","Has been validated across multiple cultures","Shows stability across administrations"],correct:1,rationale:"Concurrent validity is a type of criterion validity established when test scores correlate with a criterion measured at the same time (e.g., a new depression scale correlating with existing validated depression measures administered simultaneously)."}
],

6: [ // Treatment
{q:"Systematic desensitization was developed by:",options:["Aaron Beck","B.F. Skinner","Joseph Wolpe","Carl Rogers"],correct:2,rationale:"Joseph Wolpe developed systematic desensitization based on the principle of reciprocal inhibition — pairing relaxation (incompatible with anxiety) with gradually increasing exposure to feared stimuli through an anxiety hierarchy."},
{q:"Which therapeutic approach uses the ABCDE model?",options:["Person-centered therapy","Rational Emotive Behavior Therapy (REBT)","Psychoanalysis","Gestalt therapy"],correct:1,rationale:"Ellis's REBT uses the ABCDE model: Activating event, Beliefs (rational vs. irrational), Consequences (emotional/behavioral), Disputing irrational beliefs, and new Effect. The goal is to identify and challenge irrational beliefs."},
{q:"Transference in psychoanalytic therapy refers to:",options:["The therapist's emotional reaction to the client","The client projecting feelings about significant others onto the therapist","Behavioral skills learned in therapy","The therapeutic alliance"],correct:1,rationale:"Transference involves the client unconsciously redirecting feelings, attitudes, and desires from past relationships (often parental) onto the therapist. Analysis of transference is a central technique in psychoanalytic therapy."},
{q:"Which therapeutic factor did Yalom identify as most frequently cited by group therapy members as helpful?",options:["Catharsis","Interpersonal learning","Universality","Instillation of hope"],correct:2,rationale:"Universality — learning that one's problems are not unique and that others share similar struggles — is consistently rated as one of the most helpful therapeutic factors in group therapy by members."},
{q:"In solution-focused brief therapy, the 'miracle question' is used to:",options:["Explore childhood trauma","Help clients envision their preferred future without the problem","Test reality orientation","Assess for psychosis"],correct:1,rationale:"The miracle question asks clients to imagine waking up to find their problem solved, then to describe that scenario in detail. This helps identify concrete goals and shifts focus from problems to solutions."},
{q:"Exposure and response prevention (ERP) is the first-line psychological treatment for:",options:["Major depressive disorder","Generalized anxiety disorder","Obsessive-compulsive disorder","Bipolar disorder"],correct:2,rationale:"ERP involves systematic exposure to obsessional triggers while preventing the compulsive ritual response. It is the most effective psychological treatment for OCD, often combined with SSRIs for moderate to severe cases."},
{q:"The empty chair technique is primarily associated with:",options:["Cognitive-behavioral therapy","Gestalt therapy","Psychoanalytic therapy","Behavioral therapy"],correct:1,rationale:"The empty chair technique (Fritz Perls) involves the client speaking to an imagined person in an empty chair to resolve unfinished business, explore conflicting parts of the self, or express unexpressed emotions."},
{q:"According to motivational interviewing, 'rolling with resistance' means:",options:["Confronting the client's denial directly","Accepting and exploring the client's ambivalence without arguing","Ignoring resistant behavior","Terminating therapy when resistance occurs"],correct:1,rationale:"Rolling with resistance avoids direct confrontation, instead accepting the client's perspective and exploring ambivalence. Argumentation and persuasion are counterproductive. The therapist shifts perspectives and reframes statements."},
{q:"The therapeutic alliance is considered:",options:["Important only in psychodynamic therapy","The strongest predictor of therapy outcome across orientations","Only relevant in the early stages of therapy","Less important than specific techniques"],correct:1,rationale:"Research consistently shows that the therapeutic alliance (Bordin: bond, goals, tasks) is the strongest common factor predicting therapy outcomes, accounting for more variance than specific techniques across all therapy orientations."},
{q:"Interpersonal therapy (IPT) focuses on which of the following?",options:["Unconscious conflicts from childhood","Current interpersonal relationships and communication patterns","Behavioral experiments and thought records","Free association and dream analysis"],correct:1,rationale:"IPT focuses on four interpersonal problem areas: grief, role disputes, role transitions, and interpersonal deficits. It is time-limited (12-16 sessions) and has strong evidence for depression, eating disorders, and other conditions."},
{q:"In behavior therapy, a token economy is an application of:",options:["Classical conditioning","Operant conditioning","Observational learning","Cognitive restructuring"],correct:1,rationale:"Token economies use operant conditioning principles — tokens (secondary reinforcers) are earned for desired behaviors and exchanged for backup reinforcers (privileges, items). They are used in psychiatric units, classrooms, and correctional settings."},
{q:"Which is NOT considered an evidence-based treatment for PTSD?",options:["Prolonged Exposure","Cognitive Processing Therapy","EMDR","Psychoanalytic free association"],correct:3,rationale:"PE, CPT, and EMDR all have strong empirical support for PTSD treatment (APA and VA/DoD guidelines). Traditional psychoanalytic free association lacks empirical support as a first-line PTSD treatment."},
{q:"Dialectical behavior therapy (DBT) was originally developed for the treatment of:",options:["Schizophrenia","Major depressive disorder","Borderline personality disorder","Generalized anxiety disorder"],correct:2,rationale:"Linehan developed DBT specifically for chronically suicidal individuals with BPD. It integrates CBT with Zen mindfulness philosophy, balancing change strategies with acceptance (the central dialectic)."},
{q:"The concept of unconditional positive regard is central to:",options:["Rational emotive behavior therapy","Person-centered therapy","Cognitive therapy","Behavioral therapy"],correct:1,rationale:"Rogers's person-centered therapy emphasizes three core conditions: unconditional positive regard (accepting the client without conditions), empathy, and congruence (genuineness). These create conditions for self-actualization."},
{q:"Behavioral activation for depression primarily targets:",options:["Cognitive distortions","Avoidance behavior and inactivity","Unconscious conflicts","Medication compliance"],correct:1,rationale:"Behavioral activation targets the withdrawal and avoidance that maintain depression by systematically scheduling pleasant and mastery activities. It has strong evidence as a standalone treatment for depression, comparable to full CBT."},
{q:"What is the primary mechanism of change in prolonged exposure therapy for PTSD?",options:["Cognitive restructuring","Habituation and emotional processing through repeated confrontation with feared memories","Medication-assisted processing","Relaxation training"],correct:1,rationale:"Prolonged exposure works through habituation (anxiety decreases with repeated, prolonged exposure to trauma memories) and emotional processing (modifying pathological fear structures). It includes both imaginal and in-vivo exposure components."},
{q:"Countertransference refers to:",options:["The client's resistance to therapy","The therapist's emotional reactions to the client based on the therapist's own issues","The client's transfer of feelings onto the therapist","Premature termination"],correct:1,rationale:"Countertransference involves the therapist's unconscious emotional reactions to the client, often triggered by the therapist's own unresolved conflicts. Modern views consider it a useful clinical tool when recognized and managed."},
{q:"Which approach to family therapy emphasizes intergenerational patterns and differentiation of self?",options:["Structural family therapy","Strategic family therapy","Bowenian family therapy","Narrative therapy"],correct:2,rationale:"Bowen's intergenerational approach focuses on differentiation of self (separating thought from emotion), triangulation patterns, and multigenerational transmission of emotional patterns. Genograms are a key assessment tool."}
],

7: [ // Research Methods
{q:"Type I error in hypothesis testing refers to:",options:["Failing to reject a false null hypothesis","Rejecting a true null hypothesis","Using the wrong statistical test","Having insufficient sample size"],correct:1,rationale:"Type I error (α) is incorrectly rejecting the null hypothesis when it is actually true — finding a significant effect that doesn't really exist (false positive). The conventional α level of .05 means accepting a 5% risk of Type I error."},
{q:"Which measure of central tendency is most appropriate for skewed distributions?",options:["Mean","Median","Mode","Standard deviation"],correct:1,rationale:"The median is most appropriate for skewed distributions because it is not affected by extreme scores (outliers). The mean is pulled in the direction of the skew, making it a less representative measure of central tendency."},
{q:"In a 2×3 factorial design, how many conditions exist?",options:["2","3","5","6"],correct:3,rationale:"A 2×3 factorial design has 2 levels of one IV × 3 levels of another IV = 6 conditions total. Factorial designs allow examination of main effects and interaction effects."},
{q:"Cohen's d of 0.80 is generally considered:",options:["Small effect","Medium effect","Large effect","Negligible effect"],correct:2,rationale:"Cohen's conventions for d: 0.20 = small, 0.50 = medium, 0.80 = large. A d of 0.80 means the two group means differ by 0.80 standard deviations, considered a large and practically significant effect."},
{q:"Random assignment in experiments serves primarily to:",options:["Increase external validity","Control for confounding variables across conditions","Ensure a representative sample","Reduce Type II errors"],correct:1,rationale:"Random assignment distributes individual differences and potential confounding variables equally across conditions, allowing causal inferences. Note: random ASSIGNMENT (to conditions) ≠ random SAMPLING (from population)."},
{q:"Which research design is most vulnerable to cohort effects?",options:["Longitudinal","Cross-sectional","Sequential","Single-subject"],correct:1,rationale:"Cross-sectional designs compare different age groups at one time point, making them vulnerable to cohort effects — differences between groups that reflect generational experiences rather than developmental changes."},
{q:"An interaction effect in ANOVA indicates that:",options:["Both main effects are significant","The effect of one IV depends on the level of another IV","There are no significant main effects","The sample sizes are unequal"],correct:1,rationale:"An interaction occurs when the effect of one independent variable differs across levels of another. On a graph, non-parallel lines suggest an interaction. Understanding interactions is essential for interpreting factorial designs."},
{q:"Which correlation coefficient indicates the strongest relationship?",options:["r = +.45","r = -.78","r = +.62","r = -.30"],correct:1,rationale:"The strength of a correlation is determined by its absolute value, regardless of sign. |-.78| = .78 is the largest, indicating the strongest relationship. The negative sign indicates an inverse relationship, not a weaker one."},
{q:"Internal consistency reliability is measured by:",options:["Test-retest correlation","Cronbach's alpha","Inter-rater agreement","Alternate forms correlation"],correct:1,rationale:"Cronbach's alpha estimates internal consistency by examining the correlations among all items on a test. It reflects the degree to which items measure the same construct. Alpha ≥ .70 is generally considered acceptable for research."},
{q:"A positively skewed distribution has:",options:["A tail extending to the left","A tail extending to the right","A symmetrical shape","Two peaks"],correct:1,rationale:"In a positively skewed distribution, the tail extends to the right (positive direction), with most scores clustering at the lower end. Examples include income distributions. Mean > Median > Mode in positive skew."},
{q:"The Hawthorne effect refers to:",options:["Participants changing behavior because they know they are being studied","The researcher's expectations influencing results","Regression to the mean","Maturation effects"],correct:0,rationale:"The Hawthorne effect is when participants modify behavior simply because they are being observed, regardless of the experimental manipulation. It is a threat to external validity and can be controlled with naturalistic or unobtrusive measures."},
{q:"In a meta-analysis, what is the primary outcome measure?",options:["Statistical significance level","Effect size","Sample size","Publication year"],correct:1,rationale:"Meta-analysis quantitatively combines results across studies using effect sizes (e.g., d, r, odds ratios), providing a more precise estimate of an effect. It overcomes limitations of individual studies through aggregation."},
{q:"Which threat to internal validity occurs when participants drop out of a study differentially across conditions?",options:["History","Maturation","Attrition (mortality)","Instrumentation"],correct:2,rationale:"Differential attrition occurs when participants drop out at different rates across conditions, potentially creating systematic differences between groups that confound the results. It is especially problematic in longitudinal studies."},
{q:"A Pearson correlation of r = 0 indicates:",options:["A perfect inverse relationship","No linear relationship","Definitely no relationship of any kind","A very strong relationship"],correct:1,rationale:"r = 0 indicates no LINEAR relationship between variables. However, there could still be a curvilinear relationship (e.g., the Yerkes-Dodson relationship between arousal and performance). Always examine scatterplots."},
{q:"Multicollinearity in multiple regression refers to:",options:["The DV being non-normal","High correlations among predictor variables","Outliers influencing regression","Unequal sample sizes"],correct:1,rationale:"Multicollinearity occurs when predictor variables are highly intercorrelated, which inflates standard errors, makes individual β weights unstable, and can lead to misleading conclusions about individual predictors' contributions."},
{q:"The purpose of a pilot study is to:",options:["Provide definitive conclusions","Test procedures and identify potential problems before the main study","Replace the main study","Increase the sample size"],correct:1,rationale:"Pilot studies are small-scale preliminary studies conducted to evaluate feasibility, refine procedures, test materials, estimate effect sizes for power analysis, and identify potential problems before committing to a full study."},
{q:"In APA style, a p-value of .03 means:",options:["There is a 3% chance the null hypothesis is true","There is a 3% probability of obtaining these results if the null hypothesis is true","The effect is clinically significant","97% of the variance is explained"],correct:1,rationale:"A p-value of .03 means there is a 3% probability of obtaining results as extreme as observed, assuming the null hypothesis is true. It does NOT mean there is a 3% chance the null hypothesis is true (a common misconception)."},
{q:"Which sampling method gives every member of the population an equal chance of being selected?",options:["Convenience sampling","Snowball sampling","Simple random sampling","Purposive sampling"],correct:2,rationale:"Simple random sampling gives every member an equal probability of selection, producing the most representative sample. It is the gold standard for external validity but is often impractical. Other probability methods (stratified, cluster) also aim for representativeness."}
],

8: [ // Ethics & Professional Issues
{q:"According to APA Ethics Code Standard 9.01, psychologists base their assessments on:",options:["Clinical intuition alone","Information and techniques sufficient to substantiate their findings","A single test score","The referring professional's opinion"],correct:1,rationale:"Standard 9.01 requires that assessments be based on adequate information and techniques. Psychologists should not base opinions on insufficient data and should identify limitations of their conclusions."},
{q:"When a psychologist discovers they have a conflict of interest in a case, the most appropriate first step is to:",options:["Continue treatment but document the conflict","Immediately terminate the relationship","Discuss the conflict with the client and explore options","Ignore the conflict if it seems minor"],correct:2,rationale:"When a conflict of interest is identified, the psychologist should discuss it openly with the client, explore options, and determine the best course of action. This may include transfer, consultation, or continuing with informed consent and documentation."},
{q:"Under HIPAA, the minimum necessary standard requires that:",options:["All patient information must be shared with insurance companies","Only the minimum amount of PHI necessary for the purpose should be disclosed","Patients must sign a release for every communication","Psychotherapy notes must always be included in records requests"],correct:1,rationale:"The HIPAA minimum necessary standard requires covered entities to make reasonable efforts to limit PHI disclosure to the minimum necessary to accomplish the intended purpose. Psychotherapy notes receive additional protections."},
{q:"A psychologist treating a couple decides to see one partner individually. This creates potential ethical concerns primarily related to:",options:["Informed consent only","Confidentiality and multiple relationships","Insurance billing","Record keeping"],correct:1,rationale:"Seeing one partner individually creates concerns about confidentiality (what information is shared between individual and couples sessions?) and multiple relationships (shifting therapeutic alliances). Clear policies should be established at the outset."},
{q:"Privileged communication refers to:",options:["The ethical obligation to maintain confidentiality","A legal protection preventing disclosure in court proceedings","The right to refuse treatment","The therapist's right to break confidentiality"],correct:1,rationale:"Privileged communication is a LEGAL concept (distinct from the ethical concept of confidentiality) that protects certain communications from being compelled in legal proceedings. Privilege belongs to the client and varies by jurisdiction."},
{q:"When conducting research with deception, APA Ethics Code requires:",options:["Never using deception under any circumstances","Using deception freely as long as results are published","Debriefing participants after the study and explaining the deception","Obtaining a waiver from participants"],correct:2,rationale:"Standard 8.07 requires that when deception is used (and justified because non-deceptive alternatives wouldn't work), researchers must debrief participants as early as feasible, explain the deception, and allow participants to withdraw their data."},
{q:"Which legal case established the right to refuse treatment?",options:["Tarasoff v. Regents","O'Connor v. Donaldson","Rennie v. Klein","Youngberg v. Romeo"],correct:2,rationale:"Rennie v. Klein (1978) established that involuntarily committed patients have the constitutional right to refuse medication except in emergencies. The court ruled that patients retain rights to make treatment decisions."},
{q:"A client asks their therapist to write a letter supporting their disability claim. The therapist should:",options:["Refuse because it creates a dual relationship","Write whatever the client requests","Agree only if the letter accurately reflects clinical findings and falls within their competence","Report the client for potential fraud"],correct:2,rationale:"Psychologists can write letters supporting disability claims if the content accurately reflects their clinical assessment and professional opinion. They should clearly state the basis for their conclusions and any limitations."},
{q:"APA Standard 2.01 addresses boundaries of competence and requires that psychologists:",options:["Practice only within areas of demonstrated competence","Can practice in any area after obtaining a general license","Need only read about new areas before practicing in them","Should refer all cases outside their specialty"],correct:0,rationale:"Standard 2.01 requires psychologists to provide services only within their boundaries of competence based on education, training, supervised experience, or other professional experience. New areas require additional training or supervision."},
{q:"When a psychologist is subpoenaed for client records, the most appropriate FIRST response is to:",options:["Immediately release all records","Contact the client and their attorney before release","Destroy sensitive records","Comply fully without question"],correct:1,rationale:"A subpoena is not the same as a court order. The psychologist should notify the client, seek their consent or direction (privilege belongs to the client), and may need to file a motion to quash or seek a protective order if appropriate."},
{q:"The Goldwater Rule (APA Section 7.3) prohibits psychologists from:",options:["Testifying in court","Providing professional opinions on public figures they haven't personally examined","Conducting forensic evaluations","Publishing case studies"],correct:1,rationale:"Section 7.3 states that psychologists should not offer professional opinions about individuals they have not personally evaluated. This was established after psychiatrists publicly diagnosed Barry Goldwater during his presidential campaign."},
{q:"In rural practice settings, the APA Ethics Code acknowledges that:",options:["Multiple relationships are always unethical","Some multiple relationships may be unavoidable and not always harmful","Rural psychologists need not follow ethical standards","Confidentiality requirements are relaxed"],correct:1,rationale:"Standard 3.05 recognizes that in small communities, some multiple relationships may be unavoidable. The key question is whether the relationship is reasonably expected to impair objectivity, competence, or risk exploitation."},
{q:"Duty to protect, as established by Tarasoff, applies when:",options:["Any client expresses anger","A client makes a credible threat of serious harm to an identifiable third party","A client discusses past violence","A client has a history of aggression"],correct:1,rationale:"Tarasoff II established a duty to protect when a therapist determines (or should determine) that a patient presents a serious danger of violence to a reasonably identifiable potential victim. The duty may be fulfilled through warning, hospitalization, or other appropriate measures."},
{q:"When working with interpreters in therapy, the psychologist should:",options:["Rely entirely on the interpreter's judgment about content","Brief the interpreter on confidentiality and roles beforehand","Use family members as interpreters whenever possible","Avoid working with interpreters"],correct:1,rationale:"When interpreters are needed, psychologists should ensure they understand confidentiality requirements, their role (to interpret, not counsel), and cultural nuances. Professional interpreters are preferred over family members to avoid boundary issues."},
{q:"Informed consent in therapy must include all of the following EXCEPT:",options:["Nature and anticipated course of treatment","Potential risks and benefits","Alternative treatments available","Guarantee of successful outcome"],correct:3,rationale:"Informed consent must cover the nature of therapy, risks/benefits, alternatives, limits of confidentiality, and the voluntary nature of participation. Therapists cannot and should not guarantee outcomes — doing so would be misleading."},
{q:"A psychologist's primary obligation under the APA Ethics Code is to:",options:["The referring professional","The insurance company","The welfare and protection of the individuals and groups they serve","Their employer"],correct:2,rationale:"Principle A (Beneficence and Nonmaleficence) and the overall Ethics Code prioritize the welfare of those served. When obligations conflict, the psychologist must resolve them in a way that protects the client's interests to the extent feasible."},
{q:"Cultural formulation in DSM-5-TR is intended to help clinicians:",options:["Apply the same diagnostic criteria regardless of culture","Understand how cultural factors influence diagnosis and treatment","Avoid diagnosing patients from different cultures","Use only culture-specific assessment tools"],correct:1,rationale:"The Cultural Formulation Interview (CFI) in DSM-5-TR helps clinicians assess how cultural identity, cultural explanations of illness, cultural stressors/supports, and the cultural features of the clinical relationship influence diagnosis and treatment."},
{q:"When a minor's parent requests access to therapy records, the psychologist should:",options:["Release all records immediately","Consider the minor's age, maturity, and relevant laws before deciding","Refuse all requests from parents","Release records only to the other parent"],correct:1,rationale:"Access depends on jurisdiction, the minor's age, the nature of treatment (e.g., substance abuse), and clinical judgment about potential harm. Many states give mature minors or emancipated minors greater confidentiality protections."}
]
};

Object.entries(batch29).forEach(([domainId, questions]) => {
    const domain = EPPPData.getDomain(parseInt(domainId));
    if (domain) questions.forEach(q => domain.questions.push(q));
});

console.log('PasstheEPPP: Loaded ' + Object.values(batch29).reduce((s,q)=>s+q.length,0) + ' questions (batch 29).');
})();
