'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'../..'),OUT=__dirname,source=fs.readFileSync(path.join(OUT,'baseline-runtime.js'));
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const fixture=fs.readFileSync(path.join(ROOT,'dev-tools/watercycle_signal_inspection_qa.cjs'),'utf8');
const html=Function('return '+fixture.match(/const html=(`[^]*?`);\r?\nconst mime=/)[1])();
const report={title:'Water Cycle dashboard and nearby Conditions layout audit',startedAt:new Date().toISOString(),sourceSha256:hash(source),method:'Frozen actual runtime with owned ephemeral server and isolated Chromium. Read-only rendered audit; no learner tabs, preview port, runtime edits, or Git writes.',snapshots:[],errors:[],completed:false,browserClosed:false,serverClosed:false};
const mime={'.js':'text/javascript','.css':'text/css'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html'});return res.end(html);}if(url.pathname==='/stem_lab/stem_tool_watercycle.js'){res.writeHead(200,{'Content-Type':'text/javascript'});return res.end(source);}const file=path.resolve(ROOT,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,bytes)=>{res.writeHead(error?404:200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(error?'Not found':bytes);});});
async function capture(page,selector,name){await page.locator(selector).screenshot({path:path.join(OUT,name),animations:'disabled',timeout:60000});}
async function dashboardSnapshot(page,label){return page.evaluate(label=>{const dashboard=document.querySelector('.wc-signal-dashboard'),chart=dashboard.querySelector('.wc-signal-chart'),bars=dashboard.querySelector('.wc-signal-bars'),items=[...bars.children];const rect=el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};};const last=rect(items.at(-1)),c=rect(chart),b=rect(bars);return{label,viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,dashboard:rect(dashboard),chart:c,bars:b,lastBar:last,unusedHeightBelowLastBar:Math.max(0,c.bottom-last.bottom),unusedColumnArea:Math.max(0,c.bottom-last.bottom)*b.w,tableOpen:dashboard.querySelector('.wc-signal-values').open,gridDomOrder:[...dashboard.querySelector('.wc-signal-grid').children].map(el=>el.className),storageHeading:bars.querySelector('h2,h3,h4,strong')?.textContent||null,storageAria:bars.getAttribute('aria-label'),driver:dashboard.querySelector('.wc-signal-driver').innerText,readout:dashboard.querySelector('.wc-signal-reading').innerText,chartText:[...chart.querySelectorAll('.wc-signal-plot text')].map(el=>el.textContent)};},label);}
async function conditionsSnapshot(page,label){return page.evaluate(label=>{const rect=el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};};return{label,viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,labs:[...document.querySelectorAll('.wc-climate-lab,.wc-land-lab')].map(lab=>({classes:lab.className,rect:rect(lab),open:lab.open,summary:lab.querySelector('summary').innerText,heading:lab.querySelector('h4')?.innerText,controls:[...lab.querySelectorAll('input,select,button')].map(el=>({id:el.id,label:el.getAttribute('aria-label')||el.textContent.slice(0,50),rect:rect(el)})),fontSizes:[...lab.querySelectorAll('p,small,label,legend')].map(el=>({text:el.innerText.slice(0,90),font:getComputedStyle(el).fontSize}))}))};},label);}
async function main(){await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;try{browser=await chromium.launch({headless:true});for(const width of [1280,320]){const context=await browser.newContext({viewport:{width,height:1800},reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',error=>report.errors.push(String(error)));await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>mountSignalReview({wcMode:'explore',wcSection:'data',journeyView:'2d',journeyActive:false,journeyState:'idle',journeyPaused:true,wc2dPaused:true,activeStage:'infiltration',climTemp:15,climSolar:1,climWind:1,landRainIntensity:55,landSaturation:45,landPermeability:'medium',landSlope:'moderate',landCover:'grass'},'light'));await page.locator('.wc-signal-dashboard').waitFor();await page.locator('#wcSignalInspectPlace').selectOption('cloud');await page.waitForTimeout(80);report.snapshots.push(await dashboardSnapshot(page,'desktop-or-phone-folded-'+width));await capture(page,'.wc-signal-dashboard','dashboard-folded-'+width+'.png');await page.locator('.wc-signal-values summary').focus();await page.keyboard.press('Enter');await page.waitForTimeout(80);report.snapshots.push(await dashboardSnapshot(page,'desktop-or-phone-open-'+width));await capture(page,'.wc-signal-dashboard','dashboard-open-table-'+width+'.png');console.log('Captured dashboard '+width);await page.locator('.wc-section-tabs').getByRole('button',{name:/^Change the conditions\./}).click();for(const selector of ['.wc-climate-lab','.wc-land-lab']){if(!await page.locator(selector).evaluate(el=>el.open))await page.locator(selector+' > summary').click();}await page.waitForTimeout(80);report.snapshots.push(await conditionsSnapshot(page,'conditions-'+width));await capture(page,'.wc-climate-lab','climate-lab-'+width+'.png');await capture(page,'.wc-land-lab','land-lab-'+width+'.png');console.log('Captured Conditions '+width);await page.evaluate(()=>ReactDOM.unmountComponentAtNode(document.getElementById('slot')));await context.close();}report.completed=true;}catch(error){report.errors.push(String(error.stack||error));throw error;}finally{try{if(browser)await browser.close();report.browserClosed=true;}catch(error){report.errors.push('Browser cleanup '+String(error));}try{await new Promise(resolve=>server.close(resolve));report.serverClosed=true;}catch(error){report.errors.push('Server cleanup '+String(error));}report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(OUT,'baseline-results.json'),JSON.stringify(report,null,2)+'\n');}console.log(JSON.stringify({sourceSha256:report.sourceSha256,snapshots:report.snapshots.length,errors:report.errors,completed:report.completed,browserClosed:report.browserClosed,serverClosed:report.serverClosed},null,2));}
main().catch(error=>{console.error(error);process.exitCode=1;server.close();});
