const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const generated=path.join(__dirname,'capture-harness.generated.cjs');require('esbuild').buildSync({entryPoints:[path.resolve(__dirname,'../../../tests/e2e/helpers/stem_gl_harness.ts')],bundle:true,platform:'node',format:'cjs',outfile:generated,external:['@playwright/test']});
const {GlHarness}=require(generated),initial=process.argv.includes('--initial'),prefix=initial?'initial-':'';
(async()=>{
 const harness=new GlHarness({toolFile:initial?'reports/cephalopod-hunter-enhancement/pass-twenty/baseline.generated.cjs':'stem_lab/stem_tool_cephalopodlab.js',toolId:'cephalopodLab',width:1100,height:1000,layout:'document'});await harness.start();
 const browser=await chromium.launch({headless:true}),errors=[],warnings=[],captures=[];let page;
 try{
  page=await browser.newPage({viewport:{width:1280,height:1100}});page.setDefaultTimeout(90000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning'&&/WebGL|shader|context|THREE/i.test(m.text()))warnings.push(m.text());});
  await page.goto(harness.url+'/__harness');await page.waitForFunction(()=>!!window.THREE?.Clock&&!!window.StemLab?._registry?.cephalopodLab&&typeof window.__mount==='function');
  await page.evaluate(()=>{const w=window;w.__reviewStep=0;w.__reviewTicks=0;w.__reviewPaused=false;
   // A zero delta still runs live AI and consumes existing random draws. Use
   // the actual pause control between counted steps so screenshot wall time
   // cannot alter the seeded world. Every positive step resumes and freezes
   // again only after that complete synchronous simulation/render callback.
   function togglePause(){const canvas=document.querySelector('canvas[role=application]');if(!canvas)throw Error('Pause fixture requires actual gameplay canvas');const overlays=Array.from(canvas.parentElement.children).filter(el=>el.children.length===3&&el.children[1].textContent==='Paused'&&el.children[2].textContent==='Press Esc to resume');if(overlays.length!==1)throw Error('Expected one exact native pause veil');overlays[0].style.visibility='hidden';canvas.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true}));w.__reviewPaused=!w.__reviewPaused;}
   w.THREE.Clock.prototype.getDelta=function(){const dt=w.__reviewStep;w.__reviewStep=0;if((dt>0&&w.__reviewPaused)||(dt===0&&!w.__reviewPaused))togglePause();if(dt){w.__reviewTicks++;queueMicrotask(()=>{if(!w.__reviewPaused)togglePause();});}return dt;};w.__mount({cephalopodLab:{activeSection:'hunt',hunt3DActive:true,huntSpeciesId:'commonOcto',huntMode:'observe',huntSeed:2743,huntQuality:'balanced',_threeLoaded:true}});});
  await page.locator('canvas[role=application]').waitFor({state:'visible'});await page.waitForFunction(()=>window.__glRecorder.records.some(r=>r.scene?.getObjectByName('cl-player')&&r.canvas.isConnected));
  async function step(count){await page.evaluate(async count=>{const w=window;for(let i=0;i<count;i++){const before=w.__reviewTicks;w.__reviewStep=.05;for(let tries=0;tries<120&&w.__reviewTicks===before;tries++)await new Promise(resolve=>requestAnimationFrame(resolve));if(w.__reviewTicks!==before+1)throw Error('Clock step not consumed exactly once');}},count);}
  await step(20);
  const fixtures=await page.evaluate(()=>{
   const w=window,T=w.THREE,scene=w.__glRecorder.records.filter(r=>r.scene&&r.canvas.isConnected).at(-1).scene;scene.updateMatrixWorld(true);
   const moray=scene.children.find(o=>'homeX'in o.userData&&o.userData.aggroRange),jellies=scene.children.filter(o=>o.userData.bellGeo&&o.userData.bellBasePos),jelly=jellies[0];if(!moray||jellies.length!==5)throw Error('Missing actual moray/five jellies');
   const views={};function view(o,offset,target){return{camera:o.localToWorld(new T.Vector3(...offset)).toArray(),target:o.localToWorld(new T.Vector3(...target)).toArray()};}
   for(const [name,offset,target]of [['moray-oblique',[2.4,1.1,3.5],[0,.10,.25]],['moray-side',[3.2,.8,.1],[0,.10,0]],['moray-face',[0,.35,3.2],[0,.10,1.55]],['moray-tail',[-2.4,1.2,-3.5],[0,.10,-.3]],['moray-reef',[7,3,9],[0,.4,0]],['moray-phone',[3.3,1.4,4.8],[0,.1,0]]])views[name]=view(moray,offset,target);
   for(const [name,offset,target]of [['jelly-oblique',[1.2,.65,1.4],[0,-.15,0]],['jelly-crown',[0,1.4,.5],[0,.1,0]],['jelly-underside',[.25,-1.2,1.4],[0,-.2,0]],['jelly-phone',[1.7,.65,2.2],[0,-.2,0]]])views[name]=view(jelly,offset,target);
   w.__reviewScene=scene;w.__reviewPlayer=scene.getObjectByName('cl-player');w.__reviewIsDen=o=>o.isGroup&&o.children.length===5&&o.children[4].geometry?.type==='RingGeometry'&&o.children[4].geometry.parameters.outerRadius===2;
   w.__reviewInitialDens=scene.children.filter(w.__reviewIsDen).map(o=>o.uuid);if(w.__reviewInitialDens.length!==4)throw Error('Initial den count is not four');
   return{seed:2743,initialTicks:20,moray:{position:moray.position.toArray(),quaternion:moray.quaternion.toArray(),state:moray.userData.state,stateTimer:moray.userData.stateTimer,cooldownUntil:moray.userData.cooldownUntil},jellies:jellies.map(o=>({position:o.position.toArray(),quaternion:o.quaternion.toArray(),pulsePhase:o.userData.pulsePhase,driftAngle:o.userData.driftAngle,driftSpeed:o.userData.driftSpeed,verticalPhase:o.userData.verticalPhase,tentaclePhases:o.userData.tents.map(t=>t.basePhase)})),crabs:scene.children.filter(o=>o.userData.cfg).map(o=>({type:o.userData.type,position:o.position.toArray(),wanderAngle:o.userData.wanderAngle,wanderTimer:o.userData.wanderTimer})),views};
  });
  async function camera(view){await page.evaluate(view=>{const w=window,T=w.THREE,p=new T.Vector3(...view.camera),target=new T.Vector3(...view.target);w.__reviewScene.onBeforeRender=function(renderer,scene,camera){camera.position.copy(p);camera.lookAt(target);camera.updateMatrixWorld(true);};},view);}
  async function capture(name){await page.evaluate(async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const canvas=document.querySelector('canvas[role=application]'),veil=Array.from(canvas.parentElement.children).find(el=>el.children.length===3&&el.children[1].textContent==='Paused'&&el.children[2].textContent==='Press Esc to resume');if(!window.__reviewPaused||document.querySelector('[data-hud=burn]')?.textContent!=='Paused'||!veil||getComputedStyle(veil).visibility!=='hidden')throw Error('Detail capture requires the actual paused simulation and hidden native veil');});const file=prefix+name+'.png';await page.locator('canvas[role=application]').screenshot({path:path.join(__dirname,file)});captures.push(file);}
  for(const name of ['moray-oblique','moray-side','moray-face','moray-tail','moray-reef','jelly-oblique','jelly-crown','jelly-underside']){await camera(fixtures.views[name]);await capture(name);}
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.getElementById('wrap').style.width='100%';window.dispatchEvent(new Event('resize'));});for(const name of ['moray-phone','jelly-phone']){await camera(fixtures.views[name]);await capture(name);}
  await page.setViewportSize({width:1280,height:1100});await page.evaluate(()=>{document.getElementById('wrap').style.width='1100px';window.dispatchEvent(new Event('resize'));window.__reviewPlayer.position.x=-220;});
  let extraTicks=0,found=false;while(extraTicks<12&&!found){await step(1);extraTicks++;found=await page.evaluate(()=>window.__reviewScene.children.some(o=>window.__reviewIsDen(o)&&!window.__reviewInitialDens.includes(o.uuid)));}assert(found,'The actual exploration branch did not create a den');
  fixtures.streamed=await page.evaluate(()=>{const w=window,T=w.THREE,scene=w.__reviewScene,den=scene.children.find(o=>w.__reviewIsDen(o)&&!w.__reviewInitialDens.includes(o.uuid));scene.updateMatrixWorld(true);function view(offset,target){return{camera:den.localToWorld(new T.Vector3(...offset)).toArray(),target:den.localToWorld(new T.Vector3(...target)).toArray()};}return{ticks:w.__reviewTicks,playerPosition:w.__reviewPlayer.position.toArray(),denCount:scene.children.filter(w.__reviewIsDen).length,denPosition:den.position.toArray(),denQuaternion:den.quaternion.toArray(),views:{'streamed-den-front':view([0,1.4,4.8],[0,.75,0]),'streamed-den-rear':view([-3,1.2,-3.7],[0,.75,0]),'streamed-den-phone':view([3.1,1.7,5.3],[0,.75,0])}};});
  const fixtureFile=path.join(__dirname,'visual-fixtures.json');if(initial)fs.writeFileSync(fixtureFile,JSON.stringify(fixtures,null,2)+'\n');else assert.deepEqual(JSON.parse(JSON.stringify(fixtures)),JSON.parse(fs.readFileSync(fixtureFile,'utf8')),'Seeded actors/phases, streamed den spawn or fixed cameras changed');
  for(const name of ['streamed-den-front','streamed-den-rear']){await camera(fixtures.streamed.views[name]);await capture(name);}
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.getElementById('wrap').style.width='100%';window.dispatchEvent(new Event('resize'));});await camera(fixtures.streamed.views['streamed-den-phone']);await capture('streamed-den-phone');
  fs.writeFileSync(path.join(__dirname,prefix+'capture-results.json'),JSON.stringify({errors,warnings,captures,extraTicks,fixture:'Actual pause/resume isolates every counted .05s simulation frame from screenshot wall time. Only the native pause veil is hidden for unobscured detail QA; actors, scenery, lighting and other UI remain. Actual moray/first seeded jelly, five jelly phases and crab positions match before/after; 20 steps. Camera-only detail views. A player relocation to X=-220 triggers the real first streamed den; tick count, position/yaw/grounding and cameras must match. No creatures, dens or scenery moved/hidden for composition. Phone390x844.'},null,2)+'\n');console.log(JSON.stringify({errors,captures,extraTicks}));if(errors.length)process.exitCode=1;
 }catch(e){fs.writeFileSync(path.join(__dirname,prefix+'capture-failure.json'),JSON.stringify({message:e.message,errors,warnings,captures},null,2)+'\n');throw e;}finally{await browser.close();await harness.stop();}
})().catch(e=>{console.error(e);process.exitCode=1;});
