const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),sourcePath=path.join(root,'stem_lab/stem_tool_circuit.js'),mirrorPath=path.join(root,'desktop/web-app/public/stem_lab/stem_tool_circuit.js');
const source=fs.readFileSync(sourcePath,'utf8'),hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const results={sourceSha256:hash(source),checks:[],errors:[],axe:[],layouts:[],contentBounds:[],actions:[],focus:[],focusTransitions:[],nodeIds:[],textResize:[],motion:[],styleScope:[],scanStyles:[],screenshots:[],visualIssues:[],voltageGeometry:[],writingSpace:[]};
const voltageScope='.circuit-voltage-explorer',writingScope='.circuit-reflection-editor';
(async()=>{
  const browser=await chromium.launch({headless:true});let page;
  try{
    results.mirrorSha256=hash(fs.readFileSync(mirrorPath));assert.equal(results.mirrorSha256,results.sourceSha256);console.log('Circuit voltage-explorer audit: '+results.sourceSha256);
    page=await browser.newPage({viewport:{width:1280,height:1000},reducedMotion:'reduce'});page.on('pageerror',error=>results.errors.push(error.message));
    await page.setContent('<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Circuit voltage explorer and writing space</title></head><body><main id="root"></main></body></html>');
    await page.addStyleTag({path:path.join(root,'dev-tools/.cache/sweep-tailwind.css')});await page.addStyleTag({content:'body{margin:0;background:#070f1b;font-family:system-ui}#root{max-width:960px;margin:20px auto;padding:12px}*{box-sizing:border-box}'});
    for(const file of ['desktop/web-app/node_modules/react/umd/react.development.js','desktop/web-app/node_modules/react-dom/umd/react-dom.development.js'])await page.addScriptTag({path:path.join(root,file)});await page.addScriptTag({content:source});
    await page.evaluate(()=>{
      const noop=()=>{},icons=new Proxy({},{get:()=>()=>React.createElement('span')});window.awards=[];
      const observations=[StemLab.circuitActiveObservation({input:1},'First saved point.'),StemLab.circuitActiveObservation({input:1.5},'Only the input changed.')];
      const active={...StemLab.circuitActiveDesign({input:1}),view:'schematic',probeRed:'drive',probeBlack:'base',observations,notebookOpen:true,investigationTitle:'Follow voltage around the lamp loop',reflection:'My claim: raising the input increases lamp current until the supply and lamp resistance set the limit.\n\n'+StemLab.circuitActiveComparisonEvidence(...observations).text+'\n\nMy reasoning: the two voltage drops still add to the supply. I can check each drop with the red and black probes.',lessonRecords:{gain:{choice:'less',tested:true,explanation:'Keep my guided work.'}},reference:{version:1,design:StemLab.circuitActiveDesign({input:.8})},undo:[StemLab.circuitActiveDesign({input:.9})],redo:[StemLab.circuitActiveDesign({input:2})]};
      function Host(){const[data,setData]=React.useState({_circuit:{activeWorkbench:true},_circuitActive:active});window.state=data;window.setState=setData;return StemLab._registry.circuit.render({React,icons,toolData:data,setToolData:setData,t:(_key,fallback)=>fallback,gradeLevel:'8',addToast:noop,awardXP:(...args)=>awards.push(args),announceToSR:noop,a11yClick:fn=>({onClick:fn}),setStemLabTool:noop,setStemLabTab:noop,setToolSnapshots:noop});}
      window.auditRoot=ReactDOM.createRoot(document.querySelector('#root'));auditRoot.render(React.createElement(Host));
    });
    await page.getByRole('heading',{name:'A small signal. A brighter idea.'}).waitFor();await page.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});
    const voltage=page.locator(voltageScope),reflection=page.locator('.circuit-notebook-reflection'),click=name=>page.getByRole('button',{name,exact:true}).click();
    async function screenshot(name,scope,width){
      await page.evaluate(()=>document.activeElement?.blur());await page.mouse.move(0,0);
      const clip=await page.locator(scope).evaluate(el=>{const r=el.getBoundingClientRect(),x=Math.max(0,Math.floor(r.x+scrollX)-6),y=Math.max(0,Math.floor(r.y+scrollY)-6);return {x,y,width:Math.min(document.documentElement.scrollWidth-x,Math.ceil(r.right+scrollX)+6-x),height:Math.ceil(r.bottom+scrollY)+6-y};});
      const file=name+'-'+width+'.png';await page.screenshot({path:path.join(__dirname,file),clip,fullPage:true,animations:'disabled'});results.screenshots.push({name,width,file,clip});
    }
    async function focusCheck(name,scope,selector,width){
      const locator=page.locator(scope).locator(selector);await locator.evaluate(el=>el.blur());const before=await locator.evaluate(el=>getComputedStyle(el).boxShadow);await page.keyboard.press('Tab');await locator.focus();
      const actual=await locator.evaluate(el=>{const s=getComputedStyle(el);return {focused:document.activeElement===el,focusVisible:el.matches(':focus-visible'),outlineStyle:s.outlineStyle,outlineWidth:s.outlineWidth,outlineColor:s.outlineColor,boxShadow:s.boxShadow};});
      actual.visible=actual.focused&&actual.focusVisible&&((actual.outlineStyle!=='none'&&parseFloat(actual.outlineWidth)>=2&&!['transparent','rgba(0, 0, 0, 0)'].includes(actual.outlineColor))||(actual.boxShadow!=='none'&&actual.boxShadow!==before));results.focus.push({name,width,selector,...actual});if(!actual.visible)results.visualIssues.push({name,width,type:'focus',selector,actual});
    }
    async function inspect(name,scope,{widths=[1280,390,320],focus=[],scale=1}={}){
      for(const width of widths){
        await page.setViewportSize({width,height:1000});await page.evaluate(()=>document.fonts.ready);
        if(scope==='.circuit-notebook-recovery'){const controls=await page.locator(scope).locator('button').evaluateAll(elements=>elements.map(el=>{const s=getComputedStyle(el);return {text:el.textContent,disabled:el.disabled,opacity:s.opacity,color:s.color,background:s.backgroundColor,transition:s.transition};}));results.scanStyles.push({name,width,phase:'before-axe',controls});for(const control of controls)if(!control.disabled&&Number(control.opacity)<.99)results.visualIssues.push({name,width,type:'enabled-control-opacity',control});}
        const violations=await page.evaluate(async()=>{const scan=await axe.run(document.querySelector('#root'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return scan.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});results.axe.push({name,width,scale,violations});if(violations.length)results.visualIssues.push({name,width,type:'axe',violations});
        if(scope==='.circuit-notebook-recovery')results.scanStyles.push({name,width,phase:'after-axe',controls:await page.locator(scope).locator('button').evaluateAll(elements=>elements.map(el=>{const s=getComputedStyle(el);return {text:el.textContent,disabled:el.disabled,opacity:s.opacity,color:s.color,background:s.backgroundColor,transition:s.transition};}))});
        const dimensions=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));results.layouts.push({name,scale,...dimensions});if(dimensions.scrollWidth>width+1)results.visualIssues.push({name,width,type:'page-overflow',...dimensions});
        const duplicates=await page.evaluate(()=>{const ids=new Map();for(const el of document.querySelectorAll('[id]'))if(el.id)ids.set(el.id,(ids.get(el.id)||0)+1);return [...ids].filter(([,count])=>count>1);});results.nodeIds.push({name,width,duplicates});if(duplicates.length)results.visualIssues.push({name,width,type:'duplicate-ids',duplicates});
        const cards=await page.locator(scope).evaluate(root=>[root,...root.querySelectorAll('.circuit-voltage-reading,.circuit-voltage-readings,.circuit-voltage-guidance,.circuit-reflection-heading,.circuit-reflection-cue,.circuit-reflection-count')].filter(el=>el.checkVisibility()).map(el=>{
          const r=el.getBoundingClientRect(),s=getComputedStyle(el),left=r.left+parseFloat(s.borderLeftWidth)+parseFloat(s.paddingLeft),right=r.right-parseFloat(s.borderRightWidth)-parseFloat(s.paddingRight),lines=[],violations=[];const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let text;
          // Measure visible word ranges: pre-wrap may legally hang a trailing space beyond its content box.
          while((text=walker.nextNode())){if(!text.textContent.trim()||!text.parentElement.checkVisibility()||text.parentElement.closest('[aria-hidden="true"],textarea,input'))continue;const parentStyle=getComputedStyle(text.parentElement);if(parentStyle.position==='absolute'&&parseFloat(parentStyle.width)<=1&&parseFloat(parentStyle.height)<=1&&parentStyle.clip!=='auto')continue;for(const match of text.textContent.matchAll(/\S+/gu)){const range=document.createRange();range.setStart(text,match.index);range.setEnd(text,match.index+match[0].length);for(const rect of range.getClientRects()){if(rect.width<.1||rect.height<.1)continue;const line={text:match[0],context:text.textContent.trim(),left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom};lines.push(line);if(rect.left<left-1||rect.right>right+1)violations.push({...line,overLeft:Math.max(0,left-rect.left),overRight:Math.max(0,rect.right-right)});}}}
          return {selector:el.id?'#'+el.id:'.'+el.className.trim().split(/\s+/).join('.'),stage:el.getAttribute('data-stage'),left,right,clientWidth:el.clientWidth,scrollWidth:el.scrollWidth,lines,violations};
        }));results.contentBounds.push({name,width,scale,cards});for(const card of cards)if(card.violations.length||card.scrollWidth>card.clientWidth+1)results.visualIssues.push({name,width,type:'card-content-bounds',card});
        const actions=await page.locator(scope).locator('button,summary,textarea,select').evaluateAll(elements=>elements.filter(el=>el.checkVisibility()).map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return {tag:el.tagName,label:el.getAttribute('aria-label')||el.textContent.trim(),width:r.width,height:r.height,disabled:!!el.disabled,transitionDuration:s.transitionDuration};}));results.actions.push({name,width,scale,actions});for(const action of actions){if(action.width<43.9||action.height<43.9)results.visualIssues.push({name,width,type:'control-size',action});if(action.transitionDuration.split(',').some(value=>parseFloat(value)*(value.trim().endsWith('ms')?.001:1)>.0000101))results.visualIssues.push({name,width,type:'reduced-motion-transition',action});}
        for(const selector of focus)await focusCheck(name,scope,selector,width);
        await screenshot(name,scope,width);
        if(results.visualIssues.length)throw Error('Material visual issue in '+name+' at '+width+'px; inspect browser-results.json.');
      }
      await page.setViewportSize({width:1280,height:1000});
    }
    async function resizeText(scope,scale){
      const record=await page.locator(scope).evaluate((el,scale)=>{for(const[node,style]of window.auditTextStyles||[]){if(style===null)node.removeAttribute('style');else node.setAttribute('style',style);}window.auditTextStyles=[];if(scale===1)return null;const nodes=[el,...el.querySelectorAll('*')],sizes=nodes.map(node=>parseFloat(getComputedStyle(node).fontSize));window.auditTextStyles=nodes.map(node=>[node,node.getAttribute('style')]);nodes.forEach((node,i)=>{if(Number.isFinite(sizes[i])){node.style.setProperty('transition','none','important');node.style.setProperty('animation','none','important');node.style.setProperty('font-size',(sizes[i]*scale)+'px','important');}});const target=el.querySelector('textarea,button')||el;return {scale,elements:nodes.length,beforeFontSize:sizes[nodes.indexOf(target)],afterFontSize:parseFloat(getComputedStyle(target).fontSize)};},scale);
      if(record){results.textResize.push({scope,...record});assert.equal(record.afterFontSize,record.beforeFontSize*scale);}return record;
    }
    async function exactInput(value){const input=page.getByRole('spinbutton',{name:'Input voltage (V) exact value',exact:true});await input.fill(String(value));await input.press('Enter');await page.waitForFunction(value=>state._circuitActive.input===value,value);}



    const protectedState=()=>page.evaluate(()=>JSON.stringify(Object.fromEntries(Object.entries(state._circuitActive).filter(([key])=>!['probeRed','probeBlack'].includes(key)))));
    async function keyboardButton(name,key='Enter'){await page.getByRole('button',{name,exact:true}).focus();await page.keyboard.press(key);}
    async function design(values){await page.evaluate(values=>setState(prev=>({...prev,_circuitActive:{...prev._circuitActive,...StemLab.circuitActiveDesign(values)}})),values);await page.waitForFunction(values=>JSON.stringify(StemLab.circuitActiveDesign(state._circuitActive))===JSON.stringify(StemLab.circuitActiveDesign(values)),values);}
    async function geometry(name){const record=await page.locator(voltageScope).evaluate(el=>{const budget=StemLab.circuitActiveVoltageBudget(state._circuitActive),column=el.querySelector('.circuit-voltage-column'),box=column.getBoundingClientRect(),css=getComputedStyle(column),height=column.clientHeight-parseFloat(css.paddingTop)-parseFloat(css.paddingBottom);return {name:null,width:innerWidth,budget,view:state._circuitActive.view,columnHeight:height,borderHeight:box.height,hidden:el.querySelector('.circuit-voltage-graphic').getAttribute('aria-hidden'),segments:[...el.querySelectorAll('[data-voltage-segment]')].map(segment=>({id:segment.dataset.voltageSegment,inlinePercent:parseFloat(segment.style.height),height:segment.getBoundingClientRect().height,minHeight:getComputedStyle(segment).minHeight})),pressed:[...el.querySelectorAll('button')].map(button=>({label:button.textContent,pressed:button.getAttribute('aria-pressed')}))};});record.name=name;results.voltageGeometry.push(record);assert.equal(record.hidden,'true');assert.ok(record.columnHeight>0);for(const segment of record.budget.segments){const actual=record.segments.find(row=>row.id===segment.id);assert.ok(Math.abs(actual.inlinePercent-segment.fraction*100)<1e-4,'CSSOM may round percentages to six significant digits');assert.ok(Math.abs(actual.height-record.columnHeight*segment.fraction)<=1,'Rendered '+segment.id+' span must stay proportional');if(segment.fraction===0)assert.ok(actual.height<.1,'Zero lamp voltage must have zero span height');}assert.ok(Math.abs(record.budget.segments.reduce((sum,s)=>sum+s.voltage,0)-record.budget.supply)<1e-10);return record;}
    async function voltageCase(name,values,{widths=[1280,390,320],scale=1}={}){await design(values);for(const width of widths){await page.setViewportSize({width,height:1000});await geometry(name);await inspect(name,voltageScope,{widths:[width],scale,focus:['button:text-is("Measure lamp drop")','button:text-is("Measure transistor drop")']});}}
    const original=await protectedState();await keyboardButton('Measure lamp drop');await page.waitForFunction(()=>state._circuitActive.probeRed==='supply'&&state._circuitActive.probeBlack==='collector');assert.equal(await voltage.getByRole('button',{name:'Measure lamp drop',exact:true}).getAttribute('aria-pressed'),'true');assert.match(await page.getByLabel('Active voltmeter reading',{exact:true}).innerText(),/660.00 mV/);assert.equal(await protectedState(),original);
    await keyboardButton('Measure transistor drop','Space');await page.waitForFunction(()=>state._circuitActive.probeRed==='collector'&&state._circuitActive.probeBlack==='emitter');assert.equal(await voltage.getByRole('button',{name:'Measure transistor drop',exact:true}).getAttribute('aria-pressed'),'true');assert.match(await page.getByLabel('Active voltmeter reading',{exact:true}).innerText(),/4.34\s?V/);assert.equal(await protectedState(),original);
    for(const region of ['cutoff','active','saturated']){const button=page.locator('.circuit-region-card[data-region="'+region+'"] button');await button.focus();await page.keyboard.press('Enter');await page.waitForFunction(region=>StemLab.circuitActiveVoltageBudget(state._circuitActive).region===region,region);await geometry('keyboard-region-'+region);}
    results.checks.push({name:'Keyboard measurement actions set strict ordered probes without electrical Undo or saved-work changes; keyboard graph-region actions update the same voltage budget'});
    await voltageCase('active-voltage',{input:1,supply:5});await voltageCase('cutoff-voltage',{input:0,supply:3.2});await voltageCase('saturated-voltage',{input:5,supply:7.5,loadResistance:470});await voltageCase('light-sensor-voltage',{project:'light',light:50,supply:5});
    await click('3D experiment board');await voltageCase('dark-sensor-voltage',{project:'dark',light:20,supply:9,loadResistance:680});assert.equal(await page.evaluate(()=>state._circuitActive.view),'3d');
    await resizeText(voltageScope,2);await voltageCase('voltage-200pct-text',{project:'dark',light:20,supply:9,loadResistance:680},{widths:[320],scale:2});await resizeText(voltageScope,1);
    await click('NPN schematic');await design({input:1.2,supply:12,loadResistance:1000,beta:80});await keyboardButton('Measure lamp drop');await keyboardButton('Reverse active probes');assert.deepEqual(await page.evaluate(()=>[state._circuitActive.probeRed,state._circuitActive.probeBlack]),['collector','supply']);assert.match(await page.getByLabel('Active voltmeter reading',{exact:true}).innerText(),/-4.00\s?V/);assert.deepEqual(await voltage.locator('button').evaluateAll(buttons=>buttons.map(button=>button.getAttribute('aria-pressed'))),['false','false']);await geometry('reversed-nondefault-probes');await inspect('reversed-nondefault-probes',voltageScope,{widths:[320],focus:['button:text-is("Measure lamp drop")','button:text-is("Measure transistor drop")']});
    await click('Measure supply');assert.deepEqual(await page.evaluate(()=>[state._circuitActive.probeRed,state._circuitActive.probeBlack]),['supply','emitter']);assert.deepEqual(await voltage.locator('button').evaluateAll(buttons=>buttons.map(button=>button.getAttribute('aria-pressed'))),['false','false']);await geometry('custom-supply-probes');
    results.checks.push({name:'Physical spans track cutoff, active, saturation and both loaded sensor circuits at multiple supplies and resistances; both board views retain probe choice; reversed/custom probes are never falsely selected'});

    const writingBefore=await page.evaluate(()=>{window.auditReflectionNode=document.querySelector('.circuit-notebook-reflection');auditReflectionNode.focus();auditReflectionNode.setSelectionRange(7,30,'backward');return {state:JSON.stringify(state._circuitActive),text:auditReflectionNode.value,rows:auditReflectionNode.rows,height:auditReflectionNode.getBoundingClientRect().height};});assert.ok(writingBefore.rows>=6);await inspect('default-writing-space',writingScope,{widths:[1280],focus:['textarea','button']});
    // Re-establish the selected range after the screenshot's focus checks, then use the real keyboard action.
    await reflection.evaluate(el=>{el.style.height='500px';el.focus();el.setSelectionRange(7,30,'backward');});await keyboardButton('Expand writing space','Space');assert.equal(await reflection.evaluate(el=>el.style.height),'');
    const expanded=await page.evaluate(()=>{const el=document.querySelector('.circuit-notebook-reflection'),button=document.querySelector('.circuit-reflection-size-toggle');return {sameNode:el===auditReflectionNode,rows:el.rows,height:el.getBoundingClientRect().height,selection:[el.selectionStart,el.selectionEnd,el.selectionDirection],text:el.value,state:JSON.stringify(state._circuitActive),buttonFocused:document.activeElement===button,expanded:button.getAttribute('aria-expanded'),controls:button.getAttribute('aria-controls'),id:el.id,count:document.querySelector('.circuit-reflection-count').textContent,liveCount:!!document.querySelector('.circuit-reflection-count').closest('[aria-live],[role="status"]')};});assert.equal(expanded.sameNode,true);assert.equal(expanded.text,writingBefore.text);assert.equal(expanded.state,writingBefore.state);assert.ok(expanded.rows>writingBefore.rows);assert.ok(expanded.height>writingBefore.height);assert.deepEqual(expanded.selection,[7,30,'backward']);assert.equal(expanded.buttonFocused,true);assert.equal(expanded.expanded,'true');assert.equal(expanded.controls,expanded.id);assert.equal(expanded.liveCount,false);assert.ok(expanded.count.includes(String(expanded.text.length)));results.writingSpace.push({before:writingBefore,...expanded});results.focusTransitions.push({action:'Keyboard Expand writing space retains toggle focus',focused:true});
    await inspect('expanded-writing-space',writingScope,{focus:['textarea','button']});await resizeText(writingScope,2);await inspect('expanded-writing-space-200pct-text',writingScope,{widths:[320],scale:2,focus:['textarea','button']});await resizeText(writingScope,1);
    await reflection.evaluate(el=>{el.style.height='700px';el.setSelectionRange(7,30,'backward');});await keyboardButton('Reduce writing space');assert.equal(await reflection.evaluate(el=>el.style.height),'');const reduced=await page.evaluate(()=>{const el=document.querySelector('.circuit-notebook-reflection'),button=document.querySelector('.circuit-reflection-size-toggle');return {sameNode:el===auditReflectionNode,rows:el.rows,selection:[el.selectionStart,el.selectionEnd,el.selectionDirection],text:el.value,state:JSON.stringify(state._circuitActive),focused:document.activeElement===button,expanded:button.getAttribute('aria-expanded')};});assert.equal(reduced.sameNode,true);assert.equal(reduced.rows,writingBefore.rows);assert.equal(reduced.text,writingBefore.text);assert.equal(reduced.state,writingBefore.state);assert.deepEqual(reduced.selection,[7,30,'backward']);assert.equal(reduced.focused,true);assert.equal(reduced.expanded,'false');results.writingSpace.push({reduced});results.focusTransitions.push({action:'Keyboard Reduce writing space retains toggle focus',focused:true});
    await keyboardButton('Expand writing space');await exactInput(2.3);assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('.circuit-notebook-reflection')),false);assert.equal(await reflection.evaluate(el=>el.rows),expanded.rows);assert.equal(await reflection.inputValue(),writingBefore.text);
    results.checks.push({name:'Writing starts with six rows; keyboard expand/reduce preserve textarea identity, caret/direction, text, local-only state and toggle focus; quiet count and live-circuit rerenders do not steal focus'});
    const styles=await page.evaluate(()=>{const live=document.querySelector('.circuit-voltage-explorer'),outside=document.createElement('section');outside.className=live.className;document.body.appendChild(outside);const a=getComputedStyle(live),b=getComputedStyle(outside),record={liveBackground:a.backgroundColor,outsideBackground:b.backgroundColor,liveBorder:a.borderTopWidth,outsideBorder:b.borderTopWidth};outside.remove();return record;});assert.ok(styles.liveBackground!==styles.outsideBackground||styles.liveBorder!==styles.outsideBorder);results.styleScope.push(styles);
    const motion=await page.evaluate(()=>({reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,animations:document.getAnimations().filter(a=>a.playState==='running'&&Number(a.effect?.getTiming().duration)>.01).length}));assert.equal(motion.reduced,true);assert.equal(motion.animations,0);results.motion.push(motion);assert.deepEqual(await page.evaluate(()=>awards),[]);assert.deepEqual(results.errors,[]);assert.deepEqual(results.visualIssues,[]);results.passed=true;await page.evaluate(()=>auditRoot.unmount());
  }catch(error){results.failure=error.stack;throw error;}
  finally{results.sourceSha256AtEnd=hash(fs.readFileSync(sourcePath));results.mirrorSha256AtEnd=hash(fs.readFileSync(mirrorPath));results.sourceChangedDuringRun=results.sourceSha256AtEnd!==results.sourceSha256;results.mirrorMatches=results.mirrorSha256AtEnd===results.sourceSha256AtEnd;if(results.sourceChangedDuringRun||!results.mirrorMatches){results.passed=false;results.errors.push('Circuit source changed or mirror differs during audit.');process.exitCode=1;}fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify(results,null,2));await browser.close();}
  console.log('Voltage explorer: '+results.checks.length+' workflows, '+results.axe.length+' axe scans, '+results.screenshots.length+' screenshots, '+results.visualIssues.length+' visual issues.');
})().catch(error=>{console.error(error);process.exitCode=1;});
