const fs=require('fs');let harness=fs.readFileSync('reports/geometry-world-deep-dive-2026-09-08/audit.cjs','utf8').split('const results =')[0];harness=harness.replace('window.__mount({_introShownOnce:true});','window.__mount({_introShownOnce:true,worldActive:true,renderQuality:"saver",autoCycle:false,tutorialDismissed:true});');
const run=async function(){
 const result={assertions:[],errors:[],scope:'Actual Chromium WebGL, mouse, keyboard, touch, responsive layout, and fullscreen.'};await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:960},hasTouch:true});page.setDefaultTimeout(30000);page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/THREE.WebGLProgram|shader error/i.test(m.text()))result.errors.push(m.text());});
 const check=(name,pass,details)=>{result.assertions.push({name,pass:!!pass,details});console.log((pass?'PASS ':'FAIL ')+name);},shot=name=>page.screenshot({path:path.join(out,name+'.jpg'),type:'jpeg',quality:78,timeout:60000}),frames=()=>page.evaluate(()=>new Promise(resolve=>{let n=0;function tick(){if(++n>10)resolve();else requestAnimationFrame(tick);}requestAnimationFrame(tick);}));
 const pose=()=>page.evaluate(()=>({position:__geoWorldEngine.camera.position.toArray(),quaternion:__geoWorldEngine.camera.quaternion.toArray()}));
 const bounds=()=>page.evaluate(()=>{const e=__geoWorldEngine,box=new THREE.Box3().setFromObject(e._buildBatchPreview.group),a=e.renderer.domElement.getBoundingClientRect(),card=document.querySelector('.gwe-preview-review').getBoundingClientRect(),points=[];e.camera.updateMatrixWorld(true);for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const p=new THREE.Vector3(x,y,z).project(e.camera);points.push({x:a.left+(p.x+1)*a.width/2,y:a.top+(1-p.y)*a.height/2,z:p.z});}return {minX:Math.min(...points.map(p=>p.x)),maxX:Math.max(...points.map(p=>p.x)),minY:Math.min(...points.map(p=>p.y)),maxY:Math.max(...points.map(p=>p.y)),card:{left:card.left,right:card.right,top:card.top,bottom:card.bottom},viewport:{left:a.left,right:a.right,top:a.top,bottom:a.bottom},clipped:points.some(p=>p.z< -1||p.z>1)};});
 const fits=b=>!b.clipped&&b.minX>=b.viewport.left&&b.maxX<=b.viewport.right&&b.minY>=b.viewport.top&&b.maxY<=b.viewport.bottom&&(b.maxX<b.card.left||b.minX>b.card.right||b.maxY<b.card.top||b.minY>b.card.bottom);
 try{
  await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await page.locator('.gwe-home').waitFor({timeout:60000});await page.waitForFunction(()=>!!window.__geoWorldEngine);await page.locator('.gwe-home-card[data-path=build]').click();await page.getByRole('button',{name:'Open blank sandbox',exact:true}).click();await page.waitForFunction(()=>__geoWorldEngine._currentLesson.sandbox&&!document.querySelector('.gwe-home'));
  await page.getByRole('button',{name:'Find a tool',exact:true}).click();await page.getByRole('searchbox').fill('arch');await page.getByRole('searchbox').press('Enter');await page.locator('#gwe-starter-corner-x').fill('6');await page.locator('#gwe-starter-corner-z').fill('1');await page.getByRole('button',{name:'Preview starter',exact:true}).click();const original=await pose(),initial=await page.evaluate(()=>({blocks:JSON.stringify(StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks),history:__geoWorldEngine._undoStack.length,material:__ctx.toolData.geometryWorld.selectedBlock}));
  await page.getByRole('button',{name:'Review in world',exact:true}).click();await page.waitForFunction(()=>!!__geoWorldEngine._previewReviewCamera);await frames();const first=bounds();check('Preview fits beside its card without clipping',fits(await first),await first);await shot('01-fitted-review');
  await page.locator('.gwe-preview-camera-tools>summary').click();await frames();check('Opening camera controls preserves an unobstructed model',fits(await bounds()),await bounds());await page.getByRole('button',{name:'View preview from perspective',exact:true}).click();await frames();await shot('02-angle-controls');const before=await pose(),b=await bounds(),x=(b.minX+b.maxX)/2,y=(b.minY+b.maxY)/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+80,y+20,{steps:8});await page.mouse.up();await frames();const after=await pose();check('Dragging rotates the preview without locking the cursor',JSON.stringify(before.quaternion)!==JSON.stringify(after.quaternion)&&await page.evaluate(()=>!document.pointerLockElement));
  await page.mouse.wheel(0,80);await frames();check('Scroll zoom changes the camera without changing material selection',JSON.stringify(after.position)!==JSON.stringify((await pose()).position)&&await page.evaluate(initial=>__ctx.toolData.geometryWorld.selectedBlock===initial.material,initial));
  await page.getByRole('button',{name:'View preview from top',exact:true}).click();await frames();check('Top view looks down on the complete proposal',await page.evaluate(()=>__geoWorldEngine.camera.getWorldDirection(new THREE.Vector3()).y<-.95)&&fits(await bounds()));await shot('03-top-view');
  await page.locator('#geoworld-fs-wrap').focus();await page.keyboard.press('b');await page.keyboard.press('Control+z');await page.keyboard.press('f');await frames();check('Building and history shortcuts do not alter the world during review',await page.evaluate(initial=>JSON.stringify(StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks)===initial.blocks&&__geoWorldEngine._undoStack.length===initial.history,initial));
  await page.getByRole('button',{name:'Back to tools',exact:true}).click();await frames();check('Back to tools restores the original camera and keeps the proposal',JSON.stringify(await pose())===JSON.stringify(original)&&await page.evaluate(()=>!__geoWorldEngine._previewReviewCamera&&!!__geoWorldEngine._buildBatchPreview));
  await page.getByRole('button',{name:'Review in world',exact:true}).click();await page.waitForFunction(()=>!!__geoWorldEngine._previewReviewCamera);await page.setViewportSize({width:320,height:844});await frames();const phone=await bounds();check('Rotating into phone portrait automatically refits below the review card',fits(phone)&&phone.minY>phone.card.bottom,phone);await shot('04-phone-fitted-review');
  await page.locator('.gwe-preview-camera-tools>summary').click();await frames();check('Expanded phone camera controls remain usable without covering the model',fits(await bounds())&&await page.locator('.gwe-preview-camera-tools button').evaluateAll(nodes=>nodes.every(e=>e.getBoundingClientRect().height>=44)),await bounds());await shot('05-phone-camera-controls');await page.locator('.gwe-preview-camera-tools>summary').click();await frames();
  const touchBounds=await bounds(),cx=Math.round((touchBounds.minX+touchBounds.maxX)/2),cy=Math.round((touchBounds.minY+touchBounds.maxY)/2),session=await page.context().newCDPSession(page),touchBefore=await pose();await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-30,y:cy,id:1},{x:cx+30,y:cy,id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-45,y:cy,id:1},{x:cx+45,y:cy,id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await frames();const touchAfter=await pose();check('A real two-finger pinch zooms without triggering touch movement',JSON.stringify(touchBefore.position)!==JSON.stringify(touchAfter.position)&&await page.evaluate(()=>!__geoWorldEngine._touchActive&&!__geoWorldEngine._touchMoveId&&!__geoWorldEngine._touchLookId));
  await page.locator('.gwe-preview-camera-tools>summary').click();await page.getByRole('button',{name:'Fit model',exact:true}).click();await page.locator('.gwe-preview-camera-tools>summary').click();await frames();check('Fit model recovers the full view after pinch zoom',fits(await bounds()));
  await page.getByRole('button',{name:'Enter fullscreen for the Geometry World workspace',exact:true}).click();await page.waitForFunction(()=>!!document.fullscreenElement);await frames();check('Fullscreen refits the preview around its controls',fits(await bounds()),await bounds());await page.getByRole('button',{name:'Exit fullscreen for the Geometry World workspace',exact:true}).click();await page.waitForFunction(()=>!document.fullscreenElement);
  await page.setViewportSize({width:844,height:390});await frames();check('Short landscape preserves access to the model and review actions',fits(await bounds()),await bounds());await shot('06-short-landscape-review');await page.locator('.gwe-preview-review').focus();await page.keyboard.press('Escape');await frames();check('Escape releases review input, removes the proposal, and restores the original position',await page.evaluate(original=>!__geoWorldEngine._previewReviewCamera&&!__geoWorldEngine._buildBatchPreview&&__geoWorldEngine.camera.position.toArray().every((n,i)=>Math.abs(n-original.position[i])<1e-6),original));
  await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'Find a tool',exact:true}).click();await page.getByRole('searchbox').fill('arch');await page.getByRole('searchbox').press('Enter');await page.getByRole('button',{name:'Preview starter',exact:true}).click();await page.getByRole('button',{name:'Review in world',exact:true}).click();await page.waitForFunction(()=>!!__geoWorldEngine._previewReviewCamera);await frames();await page.getByRole('button',{name:'Apply preview',exact:true}).click();await frames();check('Apply commits once and releases preview camera ownership',await page.evaluate(initial=>!__geoWorldEngine._previewReviewCamera&&!__geoWorldEngine._buildBatchPreview&&__geoWorldEngine._undoStack.length===initial.history+1&&StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks.length>0,initial));
 }catch(error){result.failure=error.stack;console.error(error.stack);await shot('failure').catch(()=>{});}
 finally{fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.assertions.filter(a=>a.pass).length,failed:result.assertions.filter(a=>!a.pass),errors:result.errors,failure:result.failure}));await browser.close();await new Promise(r=>server.close(r));if(result.failure||result.errors.length||result.assertions.some(a=>!a.pass))process.exitCode=1;}
};eval(harness+'('+run.toString()+')();');
