/* PasstheEPPP — Question Batch 32 (Domains 1-4, ~70 questions) */
(function(){
if(typeof EPPPData==='undefined')return;
const batch32={
1:[
{q:"Which neurotransmitter abnormality is most associated with Alzheimer's disease?",options:["Excess dopamine","Deficient acetylcholine","Excess serotonin","Deficient norepinephrine"],correct:1,rationale:"Alzheimer's disease is characterized by degeneration of cholinergic neurons in the basal forebrain (nucleus basalis of Meynert). Acetylcholinesterase inhibitors are the primary pharmacological treatment."},
{q:"The suprachiasmatic nucleus (SCN) is the brain's primary center for regulating:",options:["Motor coordination","Circadian rhythms","Pain perception","Language processing"],correct:1,rationale:"The SCN in the hypothalamus serves as the master biological clock, synchronizing circadian rhythms to the light-dark cycle via input from the retinohypothalamic tract. It regulates sleep-wake, hormone release, and body temperature cycles."},
{q:"Which condition results from excess cerebrospinal fluid in the ventricles?",options:["Meningitis","Hydrocephalus","Encephalitis","Multiple sclerosis"],correct:1,rationale:"Hydrocephalus involves accumulation of CSF in the ventricles, causing increased intracranial pressure. In infants, it causes head enlargement. Normal pressure hydrocephalus in older adults presents with dementia, gait disturbance, and urinary incontinence."},
{q:"Glutamate is the brain's primary:",options:["Inhibitory neurotransmitter","Excitatory neurotransmitter","Neuromodulator","Hormone"],correct:1,rationale:"Glutamate is the most abundant excitatory neurotransmitter in the brain. It is essential for learning and memory (LTP). Excessive glutamate causes excitotoxicity — neuronal death from overactivation — implicated in stroke and neurodegenerative diseases."},
{q:"The insula is increasingly recognized for its role in:",options:["Motor planning","Interoception and awareness of bodily states","Visual processing","Auditory perception"],correct:1,rationale:"The insula processes interoceptive awareness (internal body states), emotional experience, empathy, and disgust. It integrates bodily sensations with emotional and cognitive processing, playing a key role in subjective feeling states."},
{q:"Neuroplasticity refers to the brain's ability to:",options:["Remain unchanged throughout life","Reorganize neural connections in response to experience or injury","Only grow during childhood","Produce new neurotransmitters"],correct:1,rationale:"Neuroplasticity is the brain's capacity to reorganize by forming new neural connections. It underlies learning, recovery from brain injury, and adaptation. It occurs throughout the lifespan but is greatest during critical periods in early development."},
{q:"Which medication class carries the highest risk of seizures upon abrupt withdrawal?",options:["SSRIs","Benzodiazepines","Atypical antipsychotics","Stimulants"],correct:1,rationale:"Abrupt discontinuation of benzodiazepines (especially after chronic use) can cause life-threatening withdrawal seizures due to GABA rebound. Gradual tapering is essential. Alcohol and barbiturate withdrawal carry similar seizure risks."},
{q:"The ventral tegmental area (VTA) is the origin of which major dopamine pathway?",options:["Nigrostriatal pathway","Mesolimbic pathway","Tuberoinfundibular pathway","Spinothalamic pathway"],correct:1,rationale:"The VTA is the origin of the mesolimbic (reward) and mesocortical pathways. The mesolimbic pathway (VTA to nucleus accumbens) mediates reward and motivation. The nigrostriatal pathway originates in the substantia nigra."},
{q:"Epigenetics in psychology refers to:",options:["Changes in DNA sequence","Changes in gene expression without altering the DNA sequence, often influenced by environment","Genetic mutations","Chromosomal abnormalities"],correct:1,rationale:"Epigenetic mechanisms (DNA methylation, histone modification) alter gene expression without changing the DNA sequence. Environmental factors (stress, nutrition, toxins, parenting) can produce epigenetic changes that affect behavior and even be transmitted across generations."},
{q:"Which structure controls the release of hormones from the anterior pituitary?",options:["Pineal gland","Hypothalamus","Thalamus","Adrenal gland"],correct:1,rationale:"The hypothalamus produces releasing and inhibiting hormones that travel via the hypophyseal portal system to control anterior pituitary hormone secretion (GH, TSH, ACTH, FSH, LH, prolactin). This is the neuroendocrine link."},
{q:"Anosognosia — lack of awareness of one's own neurological deficit — is most commonly associated with damage to the:",options:["Left frontal lobe","Right parietal lobe","Cerebellum","Occipital lobe"],correct:1,rationale:"Anosognosia is most commonly seen with right parietal lobe damage, often in conjunction with left hemispatial neglect after stroke. Patients may deny paralysis of their left limbs despite clear evidence."},
{q:"The HPA axis refers to the:",options:["Hippocampal-Parietal-Amygdala axis","Hypothalamic-Pituitary-Adrenal axis","Hypothalamic-Prefrontal-Auditory axis","Hippocampal-Prefrontal-Anterior axis"],correct:1,rationale:"The HPA axis is the primary stress response system. The hypothalamus releases CRH, triggering ACTH release from the pituitary, which stimulates cortisol release from the adrenal cortex. Chronic activation is linked to depression, anxiety, and immune suppression."},
{q:"Which neurotransmitter is most directly involved in the regulation of mood, sleep, and appetite?",options:["Dopamine","Acetylcholine","Serotonin","Glutamate"],correct:2,rationale:"Serotonin (5-HT) regulates mood, sleep, appetite, pain perception, and impulse control. Deficiencies are implicated in depression, anxiety, and OCD. SSRIs target this system. Most serotonin is produced in the raphe nuclei."},
{q:"Prosopagnosia is the inability to:",options:["Speak fluently","Recognize familiar faces","Perceive colors","Coordinate movements"],correct:1,rationale:"Prosopagnosia (face blindness) results from damage to the fusiform face area in the inferior temporal cortex. Patients can see faces but cannot recognize them, even of family members or their own reflection."},
{q:"Methylphenidate (Ritalin) works primarily by:",options:["Blocking serotonin receptors","Blocking reuptake of dopamine and norepinephrine","Enhancing GABA activity","Inhibiting monoamine oxidase"],correct:1,rationale:"Methylphenidate blocks the dopamine and norepinephrine transporters, increasing catecholamine availability in the synapse. This enhances activity in prefrontal circuits, improving attention, focus, and impulse control in ADHD."},
{q:"Mirror neurons fire both when an individual performs an action and when they:",options:["Sleep","Observe another performing the same action","Hear a loud noise","Experience pain"],correct:1,rationale:"Mirror neurons, discovered in primate premotor cortex, fire during both action execution and observation of others performing the same action. They are theorized to underlie imitation, empathy, language development, and theory of mind."},
{q:"The default mode network (DMN) is most active during:",options:["Focused attention tasks","Rest and internally directed thought (mind-wandering, self-reflection)","Intense physical exercise","Sleep"],correct:1,rationale:"The DMN (medial prefrontal cortex, posterior cingulate, precuneus) is active during rest, self-referential thought, mind-wandering, and future planning. It deactivates during focused external tasks. Abnormal DMN activity is linked to depression, ADHD, and Alzheimer's."},
{q:"Lamotrigine is a mood stabilizer primarily used for:",options:["Acute mania","Bipolar depression and maintenance prevention","Schizophrenia","ADHD"],correct:1,rationale:"Lamotrigine is FDA-approved for bipolar maintenance and is particularly effective for preventing depressive episodes. Unlike lithium and valproate, it is not effective for acute mania. It works by blocking voltage-gated sodium channels and reducing glutamate release."}
],
2:[
{q:"The concept of 'desirable difficulties' in learning refers to:",options:["Making learning as easy as possible","Introducing challenges during learning that slow acquisition but enhance long-term retention","Difficulties that prevent learning","Physical challenges during study"],correct:1,rationale:"Bjork's concept of desirable difficulties includes strategies like spacing, interleaving, testing, and varying practice conditions. These feel harder during learning but produce superior long-term retention and transfer compared to easier methods."},
{q:"Change blindness demonstrates that:",options:["People notice all changes in their visual field","People can fail to detect large changes in visual scenes","Visual perception is perfect","Attention is unlimited"],correct:1,rationale:"Change blindness occurs when people fail to notice substantial changes in visual scenes, especially during visual disruptions (blinks, saccades, scene cuts). It demonstrates that we perceive far less detail than we assume and that attention is required for awareness."},
{q:"The generation effect in memory research shows that:",options:["Information that is generated by the learner is better remembered than information merely read","Generated memories are always false","Older adults generate fewer memories","Memory generation declines with age"],correct:0,rationale:"The generation effect demonstrates that actively producing information (generating answers, completing word fragments) produces stronger memory than passively reading it. It supports active learning strategies over passive review."},
{q:"According to the broaden-and-build theory (Fredrickson), positive emotions:",options:["Narrow attention to focus on threats","Broaden thought-action repertoires and build lasting personal resources","Have no functional purpose","Only affect mood, not cognition"],correct:1,rationale:"Fredrickson's broaden-and-build theory proposes that positive emotions expand cognition and behavioral options (broaden) and build enduring resources — social bonds, resilience, skills, knowledge — creating an upward spiral of well-being."},
{q:"Prospective memory refers to:",options:["Remembering past events","Remembering to perform intended actions in the future","Memory for facts and concepts","Unconscious procedural memory"],correct:1,rationale:"Prospective memory involves remembering to carry out planned actions (taking medication, attending meetings). It requires both remembering WHAT to do and WHEN to do it. It is particularly vulnerable in aging and ADHD."},
{q:"The anchoring bias leads people to:",options:["Ignore all reference points","Rely too heavily on the first piece of information encountered when making judgments","Only use the most recent information","Always seek additional information"],correct:1,rationale:"Anchoring occurs when an initial value (even arbitrary) disproportionately influences subsequent estimates. For example, hearing a high asking price anchors perceptions of value even when the anchor is clearly irrelevant."},
{q:"Interleaving as a study strategy involves:",options:["Studying one topic thoroughly before moving to the next","Mixing different types of problems or topics during practice","Studying in one long session","Using only one study method"],correct:1,rationale:"Interleaving involves mixing different problem types or topics during practice rather than blocking (studying one type at a time). Though it feels harder, interleaving consistently produces better discrimination and transfer in long-term retention."},
{q:"Somatic marker hypothesis (Damasio) proposes that:",options:["Emotions are irrelevant to decision-making","Bodily (somatic) emotional signals guide decision-making and reasoning","Only rational analysis produces good decisions","Emotions always impair judgment"],correct:1,rationale:"Damasio's somatic marker hypothesis proposes that emotions, experienced as body states, provide crucial signals that guide decision-making. Patients with ventromedial prefrontal cortex damage make poor real-world decisions despite intact intellect."},
{q:"Retrieval-induced forgetting occurs when:",options:["Forgetting happens because of brain damage","Practicing retrieval of some items causes forgetting of related, unpracticed items","All retrieval improves memory","Forgetting only occurs during sleep"],correct:1,rationale:"Retrieval-induced forgetting demonstrates that selectively practicing some memories can inhibit access to related but unpracticed memories. This has implications for eyewitness interviews — selective questioning may impair memory for unasked-about details."},
{q:"The negativity bias refers to the tendency for:",options:["Only remembering negative events","Negative events having a disproportionately larger impact on cognition and behavior than positive events of equal magnitude","People being generally pessimistic","Negative thinking causing depression"],correct:1,rationale:"The negativity bias means that negative information receives more attention and cognitive processing than equivalent positive information. Bad impressions form faster, negative feedback has more impact, and losses feel larger than equivalent gains (loss aversion)."},
{q:"Cognitive load theory identifies three types of cognitive load:",options:["Low, medium, and high","Intrinsic, extraneous, and germane","Visual, auditory, and kinesthetic","Short-term, working, and long-term"],correct:1,rationale:"Intrinsic load relates to task complexity, extraneous load to poor instructional design, and germane load to schema formation and learning. Effective instruction minimizes extraneous load while managing intrinsic load and promoting germane processing."},
{q:"The illusion of transparency is the belief that:",options:["One's internal states are obvious to others","Others are always honest","One can see through deception","Glass is invisible"],correct:0,rationale:"The illusion of transparency leads people to overestimate how apparent their internal states (nervousness, lying, emotions) are to observers. This causes unnecessary anxiety in public speaking and overestimation of leakage when lying."},
{q:"Transfer-appropriate processing suggests that memory is best when:",options:["Information is processed deeply","The type of processing at retrieval matches the type used at encoding","Information is rehearsed many times","Emotional content is involved"],correct:1,rationale:"Transfer-appropriate processing (Morris et al.) proposes that memory depends on the match between encoding and retrieval processes. If the test requires phonemic processing, phonemic encoding may outperform semantic encoding, challenging pure depth-of-processing views."},
{q:"The planning fallacy describes the tendency to:",options:["Plan too carefully","Underestimate the time, costs, and risks of future actions while overestimating benefits","Overestimate completion time","Avoid making plans"],correct:1,rationale:"The planning fallacy (Kahneman & Tversky) is the systematic tendency to underestimate task completion time and costs, even when aware of past overruns. It occurs because people focus on the specific case rather than distributional information (base rates of similar projects)."},
{q:"Construal level theory proposes that psychologically distant events are represented more:",options:["Concretely","Abstractly","Accurately","Emotionally"],correct:1,rationale:"Construal level theory (Trope & Liberman) proposes that greater psychological distance (temporal, spatial, social, hypothetical) leads to more abstract, high-level construals, while proximity produces concrete, low-level construals. This affects judgment, preferences, and self-control."},
{q:"The Zeigarnik effect states that:",options:["Completed tasks are better remembered","Uncompleted or interrupted tasks are better remembered than completed ones","Only emotionally charged tasks are remembered","Memory declines exponentially with time"],correct:1,rationale:"Zeigarnik found that uncompleted tasks create cognitive tension that enhances recall. Once a task is completed, the tension dissipates and the memory becomes less accessible. This relates to goal-directed motivation and intrusive thoughts about unfinished business."},
{q:"Emotional intelligence (Mayer & Salovey) is defined as the ability to:",options:["Suppress all emotions","Perceive, use, understand, and manage emotions in self and others","Have high IQ and emotional stability","Avoid emotional situations"],correct:1,rationale:"Mayer and Salovey's ability model defines emotional intelligence as four branches: perceiving emotions accurately, using emotions to facilitate thinking, understanding emotional complexity, and managing emotions effectively. It is distinct from personality traits."},
{q:"The self-reference effect in memory demonstrates that:",options:["Self-focused people have better memory","Information processed in relation to oneself is better remembered","Self-generated information is always accurate","Memory is independent of personal relevance"],correct:1,rationale:"The self-reference effect shows that relating information to oneself (self-referential encoding) produces superior memory compared to semantic, phonemic, or structural encoding. It leverages the rich, elaborate nature of self-knowledge as an organizational framework."}
],
3:[
{q:"Cognitive dissonance is LEAST likely to occur when:",options:["A person has freely chosen a counter-attitudinal behavior","External justification for the behavior is strong","The behavior has important consequences","The person feels responsible for the behavior"],correct:1,rationale:"Strong external justification (large reward or punishment) provides sufficient reason for the behavior, reducing dissonance. Minimal external justification creates maximum dissonance because the person cannot attribute their behavior to external forces."},
{q:"What is moral disengagement (Bandura)?",options:["A personality disorder","Cognitive processes that allow people to commit harmful acts without self-condemnation","Loss of moral development","Physical disengagement from immoral situations"],correct:1,rationale:"Bandura identified mechanisms through which people disengage moral self-regulation: moral justification, euphemistic labeling, advantageous comparison, displacement/diffusion of responsibility, disregarding consequences, dehumanization, and attribution of blame."},
{q:"The halo effect in social perception refers to:",options:["A tendency to see oneself as better than others","Allowing one positive trait to influence perception of other traits","Only noticing positive traits in attractive people","A religious bias in person perception"],correct:1,rationale:"The halo effect (Thorndike) occurs when a positive impression in one area (attractiveness, competence) creates a bias toward positive evaluation in other, unrelated areas. The 'horns effect' is its negative counterpart."},
{q:"According to realistic group conflict theory, prejudice increases when:",options:["Groups have no contact","Groups compete for scarce resources","Groups have different values but no competition","Cultural differences exist"],correct:1,rationale:"Realistic group conflict theory (Sherif) proposes that intergroup hostility arises from actual competition for limited resources (jobs, territory, power). Reducing competition through superordinate goals decreases prejudice."},
{q:"The concept of social proof refers to:",options:["Evidence used in legal proceedings","People looking to others' behavior to determine appropriate action, especially in ambiguous situations","Scientific proof of social theories","Government documentation of social programs"],correct:1,rationale:"Social proof (Cialdini) is the tendency to look to others' behavior as a guide, especially in uncertain situations. It drives conformity, explains bystander effect, and is used in marketing (bestseller lists, reviews, 'most popular' labels)."},
{q:"Emotional contagion refers to:",options:["Emotions causing physical illness","The automatic spread of emotions from one person to others","Deliberately manipulating others' emotions","Emotional intelligence training"],correct:1,rationale:"Emotional contagion is the automatic, unconscious tendency to mimic and synchronize expressions, vocalizations, and postures with others, leading to convergence of emotional states. It occurs through facial feedback, mimicry, and mirror neuron activation."},
{q:"The scarcity principle in persuasion states that:",options:["Abundant resources are most valued","People value things more when they are rare or becoming less available","Only expensive items are persuasive","Scarcity reduces demand"],correct:1,rationale:"Cialdini's scarcity principle: limited availability increases perceived value and desire. Loss framing (what you might miss) is more motivating than gain framing. 'Limited time offer' and 'only 3 left' leverage scarcity."},
{q:"Attribution theory distinguishes between which three dimensions?",options:["Id, ego, superego","Locus, stability, controllability","Cognitive, affective, behavioral","Intrinsic, extrinsic, amotivation"],correct:1,rationale:"Weiner's attribution theory identifies three dimensions: locus (internal/external), stability (stable/unstable), and controllability (controllable/uncontrollable). These attributions influence expectations, emotions, and motivation differently."},
{q:"Informational social influence occurs when people conform because they:",options:["Want to be liked by the group","Believe the group has accurate information","Are explicitly told to conform","Fear punishment"],correct:1,rationale:"Informational influence occurs when people conform because they believe others possess accurate knowledge, especially in ambiguous situations. Normative influence involves conforming to gain social approval or avoid rejection."},
{q:"Moral licensing refers to:",options:["Legal permission to behave immorally","Past moral behavior making people MORE likely to behave immorally later","Always behaving morally","A license to practice moral philosophy"],correct:1,rationale:"Moral licensing occurs when prior moral behavior establishes 'moral credits' that people feel free to spend on subsequent immoral actions. For example, expressing egalitarian opinions may lead to later discriminatory behavior."},
{q:"The concept of basking in reflected glory (BIRGing) involves:",options:["Taking personal credit for others' achievements","Associating oneself with successful others to boost self-esteem","Reflecting on personal accomplishments","Avoiding association with unsuccessful groups"],correct:1,rationale:"BIRGing (Cialdini) involves identifying with successful others (e.g., wearing team merchandise after a win) to enhance self-esteem. CORFing (Cutting Off Reflected Failure) is distancing from unsuccessful associations."},
{q:"Hostile attribution bias is most associated with:",options:["Depression","Reactive aggression — interpreting ambiguous situations as intentionally hostile","Social anxiety","Altruistic behavior"],correct:1,rationale:"Hostile attribution bias involves interpreting ambiguous social cues as deliberately hostile or threatening. It is strongly associated with reactive aggression in children and adults, and is a key cognitive target in anger management interventions."},
{q:"Social comparison theory (Festinger) proposes that people evaluate themselves by:",options:["Comparing to objective standards only","Comparing their abilities and opinions to those of similar others","Avoiding all comparisons","Only comparing to superior others"],correct:1,rationale:"Festinger proposed that in the absence of objective standards, people evaluate themselves by comparing to similar others. Upward comparisons (to superior others) can motivate or depress; downward comparisons (to inferior others) can boost self-esteem."},
{q:"The authoritarian personality (Adorno) is characterized by:",options:["Open-mindedness and tolerance","Rigid adherence to conventional values, submission to authority, and aggression toward outgroups","Democratic leadership style","Creativity and independence"],correct:1,rationale:"Adorno's F-scale measures authoritarian personality traits: conventionalism, authoritarian submission, authoritarian aggression, anti-intraception, superstition, power and toughness. It was developed to understand the psychological basis of fascism and prejudice."},
{q:"Reciprocity norm as a persuasion principle operates through:",options:["Threatening consequences","Creating obligation — people feel compelled to return favors","Appealing to logic","Providing information"],correct:1,rationale:"The reciprocity norm (Cialdini) is the universal social rule that we should repay what others give us. It creates social obligation and is exploited in persuasion (free samples, unsolicited gifts) because people feel uncomfortable being indebted."},
{q:"The looking-glass self (Cooley) refers to:",options:["Using mirrors in therapy","Developing self-concept based on how we believe others perceive us","Narcissistic self-focus","Visual self-perception"],correct:1,rationale:"Cooley's looking-glass self proposes that self-concept develops through a three-step process: imagining how we appear to others, imagining their judgment of us, and developing feelings (pride or shame) based on these imagined judgments."},
{q:"Uncertainty reduction theory (Berger & Calabrese) applies to:",options:["Scientific research","Initial interactions where strangers reduce uncertainty about each other through communication","Anxiety disorders","Decision-making under risk"],correct:1,rationale:"Uncertainty reduction theory explains how strangers use communication to reduce uncertainty about each other during initial interactions. People seek information through passive (observation), active (asking others), and interactive (direct conversation) strategies."},
{q:"Collective narcissism refers to:",options:["An individual personality disorder","An exaggerated belief in the greatness and entitlement of one's ingroup","Normal group pride","Individual narcissism in group settings"],correct:1,rationale:"Collective narcissism is the belief that one's ingroup is exceptional and deserving of special treatment, combined with a demand for external validation. It predicts intergroup hostility, conspiracy beliefs, and sensitivity to perceived group-level threats."}
],
4:[
{q:"Sensitive periods differ from critical periods in that sensitive periods:",options:["Are absolute deadlines for development","Represent optimal but not exclusive windows for learning — development can still occur outside them","Only apply to physical growth","Do not exist in human development"],correct:0,rationale:"Sensitive periods are windows of enhanced susceptibility to environmental input, but development can still occur outside them (just less optimally). Critical periods imply an absolute deadline. Most developmental processes involve sensitive rather than strict critical periods."},
{q:"Synaptic pruning during adolescence primarily occurs in the:",options:["Cerebellum","Prefrontal cortex","Visual cortex","Brainstem"],correct:1,rationale:"Prefrontal cortex pruning during adolescence eliminates underused synaptic connections, increasing neural efficiency through a 'use it or lose it' process. The PFC matures last (mid-20s), explaining adolescents' developing executive function and impulse control."},
{q:"Secure base behavior in attachment refers to:",options:["The infant's refusal to explore the environment","Using the caregiver as a base from which to explore and returning for comfort when threatened","Attachment to physical objects","The caregiver's attachment to the infant"],correct:1,rationale:"Secure base behavior is the hallmark of secure attachment: the infant confidently explores the environment, periodically returning to the caregiver for reassurance, then resuming exploration. This balance of exploration and proximity-seeking indicates healthy attachment."},
{q:"The violation of expectation paradigm in infant research is used to assess:",options:["Motor skill development","Cognitive abilities by measuring looking time when events violate physical or social expectations","Language comprehension","Emotional regulation"],correct:1,rationale:"The violation of expectation method assumes infants look longer at surprising (unexpected) events. If an infant looks longer at an impossible event, this suggests they had an expectation that was violated, indicating cognitive understanding beyond what behavioral methods might reveal."},
{q:"Scaffolding, as applied to cognitive development, is gradually:",options:["Increased as the learner progresses","Removed as the learner demonstrates competence (fading)","Kept constant throughout learning","Applied only to adults"],correct:1,rationale:"Scaffolding is systematically faded — reduced as the learner gains competence. The process moves from high support (modeling, direct instruction) through guided practice to independent performance, keeping the task within the learner's ZPD."},
{q:"Fast mapping in language development refers to:",options:["Speaking rapidly","Children's ability to learn new words from minimal exposure (often a single encounter)","A language intervention technique","Mapping neural pathways for speech"],correct:1,rationale:"Fast mapping (Carey & Bartlett) describes the remarkable ability of young children to infer the meaning of a new word from a single or very few exposures. Full understanding (extended mapping) develops gradually through subsequent encounters."},
{q:"Secular trends in development refer to:",options:["Religious influences on development","Generational changes in developmental patterns (e.g., earlier onset of puberty over decades)","Daily variations in behavior","Cultural differences in parenting"],correct:1,rationale:"Secular trends are long-term generational changes in developmental patterns. For example, the age of menarche has decreased significantly over the past century in developed nations, likely due to improved nutrition and health care."},
{q:"Embryonic period of prenatal development (weeks 3-8) is considered the most critical for:",options:["Brain growth","Organ formation (organogenesis) — most vulnerable to teratogens","Weight gain","Behavioral development"],correct:1,rationale:"During the embryonic period, all major organs and body systems form (organogenesis). This is the period of greatest vulnerability to teratogens because disruption to organogenesis can cause structural birth defects. The fetal period (weeks 9-birth) involves growth and refinement."},
{q:"Socioemotional selectivity theory (Carstensen) predicts that older adults:",options:["Seek many new relationships","Prioritize emotionally meaningful relationships and experiences as perceived time decreases","Become socially isolated by choice","Show no changes in social motivation"],correct:1,rationale:"Carstensen's theory proposes that as people perceive their remaining time as limited, they shift goals from information-gathering to emotional fulfillment, preferring close relationships over novel contacts. This positivity shift improves emotional well-being in aging."},
{q:"Adolescent risk-taking is best explained by:",options:["General cognitive deficiency","Imbalance between an active limbic system (reward sensitivity) and an immature prefrontal cortex (impulse control)","Peer pressure alone","Hormonal changes exclusively"],correct:1,rationale:"The dual-systems model explains adolescent risk-taking: the limbic system (reward sensitivity) matures earlier than the prefrontal cortex (cognitive control), creating a developmental mismatch. Peer presence amplifies reward sensitivity more in adolescents than adults."},
{q:"The still-face paradigm demonstrates that infants:",options:["Prefer still faces over animated ones","Expect and rely on caregiver emotional responsiveness — becoming distressed when it is absent","Cannot detect facial expressions","Are indifferent to caregiver affect"],correct:1,rationale:"In Tronick's still-face paradigm, infants become distressed when caregivers suddenly become expressionless after normal interaction. This demonstrates infants' sensitivity to social contingency and their active role in bidirectional social interaction."},
{q:"Transitional objects (Winnicott) serve what developmental function?",options:["Physical protection","Providing comfort and symbolizing the caregiver during the transition to independence","Language development","Motor skill practice"],correct:1,rationale:"Winnicott's concept of transitional objects (blankets, stuffed animals) describes items that represent the mother's presence and provide comfort as the infant begins to develop a separate sense of self, bridging the gap between dependence and independence."},
{q:"Joint attention, which emerges around 9-12 months, involves:",options:["Focusing on one toy exclusively","Sharing attention with another person toward a third object or event","Parallel play","Competitive interaction"],correct:1,rationale:"Joint attention involves coordinating attention between an object/event and another person (following gaze, pointing, showing). It is a crucial social-cognitive milestone, considered a precursor to language and theory of mind. Deficits in joint attention are an early marker of ASD."},
{q:"According to the bioecological model (Bronfenbrenner), proximal processes refer to:",options:["Distant environmental influences","Regular, reciprocal interactions between the developing person and their immediate environment","Genetic determinism","Cultural values"],correct:1,rationale:"Proximal processes are the engines of development — sustained, progressively complex, reciprocal interactions between the person and immediate environment (parent-child play, reading, peer interaction). Their effectiveness varies by person characteristics and context."},
{q:"Deferred imitation indicates which cognitive ability?",options:["Object permanence","Mental representation — the ability to encode, store, and reproduce observed behavior after a delay","Language comprehension","Fine motor skills"],correct:1,rationale:"Deferred imitation (reproducing a behavior after a delay) demonstrates mental representation — the ability to form, store, and retrieve cognitive representations of observed events. It emerges around 6-9 months, earlier than Piaget originally proposed."},
{q:"Executive function includes all of the following EXCEPT:",options:["Working memory","Inhibitory control","Cognitive flexibility","Sensory registration"],correct:3,rationale:"Executive functions include working memory (holding and manipulating information), inhibitory control (resisting impulses), and cognitive flexibility (shifting between tasks/perspectives). Sensory registration is a basic perceptual process, not an executive function."},
{q:"The 'positivity effect' in aging refers to older adults':",options:["Tendency to complain more","Preferential processing and remembering of positive over negative information","Increased positive personality traits","More positive economic outlook"],correct:1,rationale:"The positivity effect (Carstensen) is the age-related shift toward preferentially attending to and remembering positive versus negative information. It is linked to socioemotional selectivity theory and contributes to emotional well-being in older adulthood."},
{q:"Overregularization errors in language development (e.g., 'goed,' 'mouses') indicate that children:",options:["Have poor language ability","Are learning grammatical rules and overapplying them — a sign of progress","Are imitating adult errors","Have hearing impairments"],correct:1,rationale:"Overregularization (overgeneralization) demonstrates that children are not merely imitating but actively inferring and applying grammatical rules. Saying 'goed' instead of 'went' shows rule learning — they cannot have heard adults say 'goed.'"}
]
};
Object.entries(batch32).forEach(([domainId, questions]) => {
    const domain = EPPPData.getDomain(parseInt(domainId));
    if (domain) questions.forEach(q => domain.questions.push(q));
});
console.log('PasstheEPPP: Loaded ' + Object.values(batch32).reduce((s,q)=>s+q.length,0) + ' questions (batch 32).');
})();
