/* PasstheEPPP — Question Batch 31 (Domains 5-8, ~70 questions) */
(function(){
if(typeof EPPPData==='undefined')return;
const batch31={
5:[
{q:"Predictive validity is established when a test score:",options:["Correlates with a criterion measured at the same time","Predicts a future criterion measure","Has high internal consistency","Is reviewed by experts for content coverage"],correct:1,rationale:"Predictive validity, a type of criterion validity, is demonstrated when test scores predict future outcomes (e.g., GRE scores predicting graduate school performance). The time interval between predictor and criterion distinguishes it from concurrent validity."},
{q:"Which projective test uses ambiguous inkblots?",options:["Thematic Apperception Test","Rorschach Inkblot Test","Sentence Completion Test","Draw-A-Person Test"],correct:1,rationale:"The Rorschach uses 10 symmetrical inkblots (5 achromatic, 5 chromatic). The Exner Comprehensive System and newer R-PAS provide standardized administration and scoring. It assesses personality structure, thought processes, and emotional functioning."},
{q:"In Item Response Theory (IRT), the item characteristic curve shows the relationship between:",options:["Item difficulty and discrimination","Latent trait level and probability of correct response","Test length and reliability","Age and performance"],correct:1,rationale:"The ICC plots the probability of a correct response (y-axis) as a function of the latent trait being measured (x-axis). IRT parameters include difficulty (b), discrimination (a), and guessing (c)."},
{q:"A confidence interval of 95% around a test score means:",options:["The true score falls within this range 95% of the time across repeated measurements","There is a 95% chance the true score is exactly at the center","The test is 95% reliable","95% of people score within this range"],correct:0,rationale:"A 95% confidence interval means that if we repeatedly tested the individual, 95% of the constructed intervals would contain the true score. It reflects measurement precision and is derived from the SEM."},
{q:"Face validity differs from other forms of validity because it:",options:["Is the most important type of validity","Is based on subjective judgment of whether a test appears to measure what it claims","Requires statistical evidence","Always correlates with construct validity"],correct:1,rationale:"Face validity is NOT a true form of validity — it is an informal assessment of whether a test LOOKS like it measures what it claims. It affects test acceptability and examinee motivation but is not evidence of actual measurement quality."},
{q:"The MCMI-IV (Millon Clinical Multiaxial Inventory) is specifically designed to align with:",options:["The Big Five personality model","DSM personality disorder categories","Developmental milestones","Neuropsychological functioning"],correct:1,rationale:"The MCMI-IV is designed to assess personality disorders and clinical syndromes in alignment with DSM diagnostic categories. Unlike the MMPI (which assesses general psychopathology), the MCMI specifically measures personality pathology."},
{q:"When the base rate of a condition is very low, even a good screening test will produce:",options:["Very few false negatives","A high number of false positives","Perfect classification","No errors"],correct:1,rationale:"When base rates are low (rare conditions), the positive predictive value drops even with high sensitivity and specificity. Most positive screens will be false positives. This is a critical Bayesian concept for clinical decision-making."},
{q:"The Flynn effect refers to:",options:["Declining IQ scores over generations","Rising IQ scores across generations in many countries","Cultural bias in IQ tests","The effect of coaching on test scores"],correct:1,rationale:"The Flynn effect is the substantial and consistent increase in IQ scores over generations (~3 pts/decade). Proposed explanations include improved nutrition, education, environmental stimulation, and reduced disease. It necessitates periodic renorming of IQ tests."},
{q:"Standard scores (z-scores, T-scores) are preferred over raw scores because they:",options:["Are always positive numbers","Allow meaningful comparison across different tests and distributions","Are easier to calculate","Eliminate measurement error"],correct:1,rationale:"Standard scores convert raw scores to a common scale based on means and SDs, enabling comparison across different tests. Z-scores (M=0, SD=1) and T-scores (M=50, SD=10) are widely used in clinical and research settings."},
{q:"Malingering is best described as:",options:["Unconscious symptom production","Intentional production of false or exaggerated symptoms for external gain","Genuine symptom presentation","A factitious disorder"],correct:1,rationale:"Malingering involves intentional fabrication or exaggeration of symptoms motivated by external incentives (avoiding work, obtaining compensation, evading legal consequences). Unlike factitious disorder, the motivation is external rather than assuming the sick role."},
{q:"Test bias in assessment refers to:",options:["A test being unfair in content","Systematic error in prediction for different demographic groups","Any test that shows mean score differences between groups","Poor test design"],correct:1,rationale:"Test bias is a STATISTICAL concept — it exists when a test systematically overpredicts or underpredicts criterion performance for one group relative to another. Mean score differences alone do NOT constitute bias."},
{q:"The Vineland Adaptive Behavior Scales measure:",options:["Intelligence","Adaptive functioning in communication, daily living, socialization, and motor skills","Academic achievement","Personality traits"],correct:1,rationale:"The Vineland-3 assesses adaptive behavior in four domains: Communication, Daily Living Skills, Socialization, and Motor Skills. It is used in diagnosing intellectual disability (which requires both low IQ AND adaptive deficits)."},
{q:"Which assessment approach emphasizes the process of problem-solving rather than just the final answer?",options:["Standardized testing","Boston Process Approach","Computer-adaptive testing","Group testing"],correct:1,rationale:"The Boston Process Approach (Kaplan) emphasizes how a person solves problems, not just whether they get the right answer. Qualitative analysis of errors, strategies, and processes provides richer clinical information than scores alone."},
{q:"In classical test theory, observed score equals:",options:["True score minus error","True score plus error","Error score only","Predicted score plus residual"],correct:1,rationale:"Classical test theory posits that X (observed) = T (true) + E (error). Reliability is the ratio of true score variance to observed score variance. Error is assumed to be random with a mean of zero."},
{q:"Differential item functioning (DIF) analysis is used to detect:",options:["Items that are too easy or too hard","Items that function differently across groups after controlling for ability level","Changes in test format","Coaching effects"],correct:1,rationale:"DIF analysis identifies items that have different statistical properties for different groups (gender, ethnicity) after matching on overall ability. Items showing DIF may indicate bias and may need revision or removal."},
{q:"An assessment is ecologically valid when:",options:["It is administered outdoors","Its results predict real-world functioning","It uses only paper-and-pencil tasks","It has high internal consistency"],correct:1,rationale:"Ecological validity refers to the degree to which assessment results generalize to and predict real-world functioning. It is a major concern in neuropsychological assessment, where lab-based tests may not reflect daily functioning."},
{q:"Which WAIS-IV index measures working memory?",options:["Verbal Comprehension Index","Perceptual Reasoning Index","Working Memory Index","Processing Speed Index"],correct:2,rationale:"The WAIS-IV Working Memory Index includes Digit Span and Arithmetic subtests, measuring the ability to hold and manipulate information in consciousness. It is sensitive to attentional processes and is often affected by anxiety."},
{q:"Structured clinical interviews (e.g., SCID-5) are preferred over unstructured interviews primarily because they:",options:["Are faster to administer","Provide higher reliability and validity for diagnostic purposes","Require less training","Are more flexible"],correct:1,rationale:"Structured interviews improve diagnostic reliability by standardizing the questions asked, reducing interviewer variability and subjective judgment. The SCID-5 provides systematic coverage of DSM-5 disorders with decision trees."}
],
6:[
{q:"Paradoxical intention, used in some forms of therapy, involves:",options:["Encouraging the client to engage in the feared behavior","Prescribing the symptom or feared outcome","Using progressive relaxation","Analyzing dreams for hidden meaning"],correct:1,rationale:"Paradoxical intention (Frankl/logotherapy; also used in strategic therapy) involves prescribing the symptom — asking clients to intentionally engage in the very behavior they're trying to suppress. This reduces anxiety by removing the fear of the symptom."},
{q:"Which therapy specifically uses behavioral experiments to test cognitive distortions?",options:["Psychoanalytic therapy","Cognitive Therapy (Beck)","Person-centered therapy","Play therapy"],correct:1,rationale:"Beck's cognitive therapy uses behavioral experiments to empirically test the validity of automatic thoughts and beliefs. Clients design real-world tests of their predictions, creating direct evidence that challenges distorted cognitions."},
{q:"The stages of change model (Prochaska & DiClemente) includes which stages?",options:["Denial, anger, bargaining, acceptance","Precontemplation, contemplation, preparation, action, maintenance","Assessment, intervention, termination","Trust, autonomy, initiative, industry"],correct:1,rationale:"The Transtheoretical Model identifies five stages: Precontemplation (not considering change), Contemplation (aware but ambivalent), Preparation (planning), Action (actively changing), and Maintenance (sustaining change). Relapse can occur at any stage."},
{q:"Flooding differs from systematic desensitization in that it:",options:["Uses gradual exposure through a hierarchy","Exposes the client to the most feared stimulus immediately and intensely","Pairs relaxation with each step","Always uses imaginal rather than in-vivo exposure"],correct:1,rationale:"Flooding involves immediate, prolonged exposure to the most feared stimulus without a gradual hierarchy or relaxation training. The theory is that anxiety will extinguish through habituation when the client cannot escape and no actual harm occurs."},
{q:"In structural family therapy (Minuchin), the therapist's role is to:",options:["Remain neutral and reflective","Actively restructure dysfunctional family organization and boundaries","Interpret unconscious family dynamics","Teach individual coping skills"],correct:1,rationale:"Minuchin's structural approach actively restructures family organization: strengthening or loosening boundaries, disrupting enmeshment or disengagement, clarifying hierarchies, and realigning subsystems through techniques like enactment and joining."},
{q:"Acceptance and Commitment Therapy (ACT) is classified as a:",options:["First-wave behavior therapy","Second-wave cognitive therapy","Third-wave cognitive-behavioral therapy","Psychodynamic therapy"],correct:2,rationale:"ACT is a 'third wave' CBT approach emphasizing psychological flexibility through six core processes: acceptance, cognitive defusion, present moment awareness, self-as-context, values, and committed action. It uses metaphors and experiential exercises."},
{q:"Which factor has research consistently shown to be the LEAST important in therapy outcome?",options:["Therapeutic alliance","Client factors (motivation, severity)","Specific therapeutic technique","Therapist factors (empathy, warmth)"],correct:2,rationale:"The common factors research (Wampold) consistently shows that specific techniques account for the smallest portion of outcome variance (~15%). The therapeutic alliance, client factors, and therapist effects account for substantially more variance."},
{q:"Premack's principle states that:",options:["Low-probability behaviors reinforce high-probability behaviors","High-probability behaviors can reinforce low-probability behaviors","All behaviors have equal reinforcement value","Punishment is more effective than reinforcement"],correct:1,rationale:"Premack's principle (the 'Grandma's rule') states that a more preferred activity (high-probability behavior) can serve as a reinforcer for a less preferred activity (low-probability behavior). Example: 'You can play after you finish homework.'"},
{q:"Cognitive Processing Therapy (CPT) for PTSD specifically targets:",options:["Body-based trauma memories","Stuck points — maladaptive beliefs about the trauma","Interpersonal dysfunction","Substance use"],correct:1,rationale:"CPT identifies and challenges 'stuck points' — maladaptive beliefs about the traumatic event related to safety, trust, power/control, esteem, and intimacy. It uses Socratic dialogue and written accounts to modify these cognitions."},
{q:"The therapeutic technique of 'reframing' involves:",options:["Rebuilding physical structures","Offering an alternative interpretation of a situation or behavior","Returning to earlier stages of therapy","Using a frame of reference from another culture"],correct:1,rationale:"Reframing presents a situation or behavior in a new light, changing its meaning without changing the facts. For example, relabeling a teen's 'stubbornness' as 'independence.' It is used across many therapy orientations, especially strategic/systemic."},
{q:"Which outcome is associated with the 'dodo bird verdict' in psychotherapy research?",options:["CBT is consistently superior to all other approaches","All bona fide treatments produce roughly equivalent outcomes","Psychotherapy is ineffective","Only medication is effective for mental disorders"],correct:1,rationale:"The dodo bird verdict (Rosenzweig, Luborsky) suggests that all bona fide psychotherapies produce roughly equivalent outcomes, supporting the importance of common factors (alliance, empathy, expectations) over specific techniques."},
{q:"In narrative therapy, 'externalizing the problem' involves:",options:["Blaming others for the problem","Separating the person from the problem so the problem becomes an entity they can relate to differently","Projecting feelings onto others","Ignoring internal experiences"],correct:1,rationale:"Externalizing (White & Epston) linguistically separates the person from the problem ('the depression' vs. 'you are depressed'), reducing shame, increasing agency, and enabling the person to take action against the problem."},
{q:"Harm reduction is an approach primarily used with:",options:["Phobias","Substance use disorders","Learning disabilities","Personality disorders"],correct:1,rationale:"Harm reduction accepts that abstinence may not be immediately achievable and focuses on reducing negative consequences of substance use (needle exchange, controlled drinking, medication-assisted treatment). It meets clients where they are."},
{q:"Which therapy technique involves the therapist strategically taking a 'one-down' position?",options:["Cognitive restructuring","Strategic family therapy","Exposure therapy","Psychoeducation"],correct:1,rationale:"In strategic therapy (Haley, Madanes), the therapist may take a one-down (less powerful) position, using paradox, reframing, and directives. Strategic approaches emphasize shifting power dynamics and interrupting repetitive problem-maintaining sequences."},
{q:"Eye Movement Desensitization and Reprocessing (EMDR) involves:",options:["Only eye movement exercises","Bilateral stimulation while processing traumatic memories using an eight-phase protocol","Hypnosis","Medication-assisted therapy"],correct:1,rationale:"EMDR uses bilateral stimulation (eye movements, tapping, or auditory tones) while the client processes traumatic memories. The eight-phase protocol includes history taking, preparation, assessment, desensitization, installation, body scan, closure, and re-evaluation."},
{q:"The concept of 'resistance' in therapy is viewed most differently by which two orientations?",options:["CBT and DBT","Psychoanalytic and motivational interviewing","Gestalt and person-centered","Family therapy and group therapy"],correct:1,rationale:"Psychoanalysis views resistance as unconscious defense against threatening material that must be analyzed. MI reframes resistance as ambivalence and the therapist's job is to roll with it rather than confront it — resistance signals the therapist should change strategy."},
{q:"Which medication is considered first-line pharmacological treatment for PTSD?",options:["Benzodiazepines","SSRIs (sertraline, paroxetine)","Antipsychotics","Lithium"],correct:1,rationale:"SSRIs (sertraline/Zoloft and paroxetine/Paxil are FDA-approved for PTSD) are first-line pharmacological treatments. Benzodiazepines are contraindicated for PTSD as they may interfere with extinction learning and increase risk of dependence."},
{q:"Mentalization-based therapy (MBT) was developed primarily for:",options:["Schizophrenia","Borderline personality disorder","ADHD","Autism spectrum disorder"],correct:1,rationale:"MBT (Bateman & Fonagy) was developed for BPD, focusing on improving the capacity to understand one's own and others' mental states (mentalizing). It is based on attachment theory and has strong evidence for reducing self-harm and improving interpersonal functioning."}
],
7:[
{q:"Statistical power is the probability of:",options:["Making a Type I error","Correctly rejecting a false null hypothesis","Failing to find a significant result","Making a Type II error"],correct:1,rationale:"Power = 1 - β (probability of Type II error). Higher power means greater ability to detect a true effect. Power is increased by larger sample sizes, larger effect sizes, higher alpha levels, and more sensitive measures."},
{q:"In a within-subjects (repeated measures) design, the primary advantage is:",options:["No order effects","Each participant serves as their own control, reducing individual differences","Larger sample sizes are needed","Less time-consuming"],correct:1,rationale:"Within-subjects designs eliminate individual differences as a confound because each participant is compared to themselves. This increases statistical power but introduces order effects, which can be controlled through counterbalancing."},
{q:"Effect size is important because it:",options:["Replaces the need for significance testing","Indicates the practical significance and magnitude of an effect","Is always the same as statistical significance","Is only relevant in meta-analyses"],correct:1,rationale:"Effect size quantifies the magnitude of an effect regardless of sample size. A result can be statistically significant but have a trivially small effect size (especially with large N), making effect sizes essential for evaluating practical importance."},
{q:"Ecological validity refers to the extent to which:",options:["Research is conducted outdoors","Research findings generalize to real-world settings","Statistical assumptions are met","Participants represent the population"],correct:1,rationale:"Ecological validity is a component of external validity addressing whether findings from controlled research settings generalize to natural, everyday environments. Laboratory studies often trade ecological validity for internal validity."},
{q:"Stratified random sampling ensures that:",options:["All participants are randomly assigned to conditions","The sample proportionally represents key subgroups in the population","Only certain strata of the population are studied","Randomization is not needed"],correct:1,rationale:"Stratified sampling divides the population into meaningful subgroups (strata — e.g., gender, ethnicity) and randomly samples from each stratum proportionally. This ensures representation of key subgroups, increasing external validity."},
{q:"Which statistical test is appropriate for comparing means of three or more independent groups?",options:["Independent t-test","Paired t-test","One-way ANOVA","Chi-square test"],correct:2,rationale:"One-way ANOVA compares means across three or more groups simultaneously, controlling the familywise Type I error rate. Multiple t-tests would inflate error rate. A significant ANOVA is followed by post-hoc tests to identify which groups differ."},
{q:"A mediating variable explains:",options:["Why a confound exists","HOW or WHY an independent variable affects the dependent variable","The moderating influence of a third variable","Measurement error"],correct:1,rationale:"A mediator explains the mechanism or process through which the IV affects the DV (IV → Mediator → DV). For example, therapy reduces depression THROUGH changing cognitive distortions (cognitions mediate the therapy-depression relationship)."},
{q:"A moderating variable specifies:",options:["The mechanism of an effect","WHEN or FOR WHOM the relationship between IV and DV changes","The direction of causation","The error term"],correct:1,rationale:"A moderator changes the strength or direction of the IV-DV relationship. For example, severity of depression may moderate treatment effectiveness — CBT may work better for mild-moderate depression than severe. Moderators answer 'when' or 'for whom' questions."},
{q:"Solomon four-group design controls for:",options:["Only practice effects","Testing effects and the interaction of testing with treatment","Maturation only","Demand characteristics only"],correct:1,rationale:"The Solomon four-group design uses four conditions: (1) pretest-treatment-posttest, (2) pretest-no treatment-posttest, (3) treatment-posttest, (4) posttest only. This controls for testing sensitization and its interaction with the treatment."},
{q:"Qualitative research differs from quantitative research primarily in its:",options:["Use of larger sample sizes","Emphasis on understanding meaning and subjective experience through non-numerical data","Statistical rigor","Generalizability"],correct:1,rationale:"Qualitative research seeks to understand meaning, experience, and context through methods like interviews, observation, and content analysis, producing rich descriptive data rather than numerical outcomes. It uses purposive rather than random sampling."},
{q:"Multiple regression analysis is used to:",options:["Compare means of multiple groups","Predict a DV from two or more IVs simultaneously","Test for interactions only","Analyze nominal data"],correct:1,rationale:"Multiple regression predicts a continuous DV from multiple predictor variables, determining each predictor's unique contribution (β weights) while controlling for the others. R² indicates total variance explained."},
{q:"Demand characteristics in research refer to:",options:["Physical requirements of the study","Cues in the experimental setting that suggest expected behavior to participants","Researcher expectations","Statistical requirements"],correct:1,rationale:"Demand characteristics are cues in the research setting that communicate what behavior is expected, potentially causing participants to alter their responses to confirm (or sometimes disconfirm) the hypothesis, threatening internal validity."},
{q:"A Type II error occurs when:",options:["A true null hypothesis is rejected","A false null hypothesis is not rejected — a real effect is missed","The wrong statistical test is used","Sample size is too large"],correct:1,rationale:"Type II error (β) is failing to reject a false null hypothesis — concluding no effect exists when one actually does (false negative). It is more likely with small samples, small effect sizes, and low power."},
{q:"The coefficient of determination (r²) tells us:",options:["The direction of the relationship","The proportion of variance in one variable explained by the other","The significance level","The reliability of the measures"],correct:1,rationale:"r² represents the proportion of shared variance between two variables. An r of .50 produces r² = .25, meaning 25% of variance in one variable is accounted for by the other. This is more interpretable than r alone."},
{q:"Quasi-experimental designs differ from true experiments in that they:",options:["Use random assignment","Lack random assignment to conditions","Never have control groups","Are always longitudinal"],correct:1,rationale:"Quasi-experiments lack random assignment (often because it's impractical or unethical). They may use pre-existing groups (e.g., classrooms, hospitals). This limits causal inference because groups may differ systematically on confounding variables."},
{q:"Bonferroni correction is used to:",options:["Increase Type I error rate","Control the familywise Type I error rate when making multiple comparisons","Improve statistical power","Correct for non-normal distributions"],correct:1,rationale:"The Bonferroni correction divides the desired alpha by the number of comparisons (α/k) to control the inflated Type I error rate from multiple testing. It is conservative — reducing Type I error risk but increasing Type II error risk."},
{q:"Single-subject (single-case) research designs are most commonly used in:",options:["Large-scale epidemiological studies","Applied behavior analysis and clinical practice","Survey research","Correlational studies"],correct:1,rationale:"Single-subject designs (ABA, multiple baseline, alternating treatments) are widely used in applied behavior analysis and clinical settings where individual-level treatment effects are of interest. The participant serves as their own control."},
{q:"Construct validity of a research study refers to:",options:["Whether the study can be replicated","Whether the operational definitions adequately capture the theoretical constructs being studied","Whether findings generalize to other settings","Whether confounds are controlled"],correct:1,rationale:"Construct validity addresses whether the measures and manipulations used actually represent the theoretical constructs of interest. Poor operationalization threatens construct validity — you may be measuring or manipulating something different than intended."}
],
8:[
{q:"The Specialty Guidelines for Forensic Psychology address the unique ethical challenges of:",options:["Child therapy","Practicing psychology within the legal system","Academic research","Industrial-organizational psychology"],correct:1,rationale:"APA's Specialty Guidelines for Forensic Psychology provide guidance for psychologists working in legal contexts, addressing issues like dual roles, objectivity, informed consent, and the difference between therapeutic and forensic relationships."},
{q:"A psychologist moving to a new state must:",options:["Continue practicing under their old license","Obtain licensure in the new state before practicing","Practice only under supervision","Wait one year before practicing"],correct:1,rationale:"Psychology licenses are state-specific (not nationally portable). Psychologists relocating must obtain a new license in the destination state. PSYPACT (Psychology Interjurisdictional Compact) now allows telepsychology across participating states without separate licenses."},
{q:"In forensic evaluation, the referral question typically comes from:",options:["The patient/client","The court, attorney, or legal system","The insurance company","A family member"],correct:1,rationale:"Forensic evaluations differ from clinical assessments in that the referral comes from the legal system, the evaluee may not be willing, and the psychologist's duty is to provide objective information to the attorney/court, not to serve the evaluee's interests."},
{q:"Standard 4.05 of the APA Ethics Code addresses:",options:["Record keeping","Disclosures of confidential information","Test construction","Advertising"],correct:1,rationale:"Standard 4.05 specifies the limited circumstances under which psychologists may disclose confidential information: with consent, as mandated by law, to protect the client or others, to obtain payment, or other provisions allowed by law."},
{q:"The concept of 'assent' in research refers to:",options:["Full legal consent from adult participants","Agreement to participate from individuals who cannot give legal consent (e.g., children)","Withdrawal from a study","Researcher consent to share data"],correct:1,rationale:"Assent is obtained from individuals (typically children or those with cognitive impairments) who cannot provide full informed consent. It involves explaining the study in developmentally appropriate terms. Parents/guardians provide the legal consent."},
{q:"A psychologist who publishes data from therapy sessions without client consent has violated which standard?",options:["Standard 2.01 (Boundaries of Competence)","Standard 4.07 (Use of Confidential Information for Didactic or Other Purposes)","Standard 5.01 (Avoidance of False Statements)","Standard 6.01 (Documentation of Professional Work)"],correct:1,rationale:"Standard 4.07 states that psychologists do not disclose identifiable confidential information in writings, lectures, or public media unless they have obtained consent or take reasonable steps to disguise the person or organization."},
{q:"The Jaffee v. Redmond (1996) Supreme Court decision established:",options:["Duty to warn","Federal psychotherapist-patient privilege","Right to refuse treatment","Standards for forensic evaluation"],correct:1,rationale:"Jaffee v. Redmond established that communications between psychotherapists and patients are protected by federal privilege in federal courts, recognizing the importance of confidentiality for effective therapy."},
{q:"When a psychologist suspects child abuse, they are:",options:["Permitted but not required to report","Required to report under mandatory reporting laws in all states","Required to get the client's permission before reporting","Only required to report if they have proof"],correct:1,rationale:"All 50 states have mandatory reporting laws requiring psychologists (among others) to report suspected child abuse/neglect. Reports are based on reasonable suspicion, not proof. Failure to report can result in criminal charges and ethical sanctions."},
{q:"The principle of justice in the APA Ethics Code primarily concerns:",options:["Punishment of wrongdoing","Fairness and equitable treatment for all persons","Legal proceedings","Financial equity in billing"],correct:1,rationale:"Principle D (Justice) recognizes that all persons are entitled to access and benefit from the contributions of psychology, with fairness and equity. Psychologists should be aware of potential biases and ensure services are not unfairly limited."},
{q:"An IRB's primary purpose is to:",options:["Fund research","Protect the rights and welfare of research participants","Publish research findings","Hire researchers"],correct:1,rationale:"Institutional Review Boards review research protocols to ensure the protection of human participants' rights and welfare. They evaluate risks vs. benefits, informed consent procedures, participant selection, and data confidentiality measures."},
{q:"Feigning incompetence to stand trial is addressed by which forensic concept?",options:["Malingering assessment","Fitness to practice evaluation","Parole assessment","Civil commitment"],correct:0,rationale:"When defendants are evaluated for competency to stand trial, the possibility of malingering (feigning incompetence to avoid trial) must be assessed. Specialized instruments (TOMM, SIRS) help detect malingered cognitive impairment and psychiatric symptoms."},
{q:"The duty to protect third parties generally does NOT apply when:",options:["A client makes a specific threat against an identifiable victim","A client expresses general feelings of anger without specificity","A client has a documented history of violence","A client owns weapons"],correct:1,rationale:"Tarasoff and subsequent laws generally require a specific, credible threat against an identifiable victim. Generalized expressions of anger without specific targets typically do not trigger the duty, though clinical judgment and documentation remain important."},
{q:"Standard 3.04 (Avoiding Harm) states that psychologists:",options:["Must never cause any distress in therapy","Take reasonable steps to avoid harming clients and minimize unavoidable harm","Are liable for all negative therapy outcomes","Can only practice with low-risk clients"],correct:1,rationale:"Standard 3.04 recognizes that some degree of discomfort may be inherent in psychological services but requires psychologists to take reasonable steps to avoid and minimize harm. This is distinct from Principle A (Beneficence/Nonmaleficence)."},
{q:"Which legal standard for civil commitment requires evidence of mental illness AND danger to self or others?",options:["Parens patriae only","Police power only","Both parens patriae and police power doctrines","Neither — commitment requires only a diagnosis"],correct:2,rationale:"Civil commitment draws on two legal doctrines: parens patriae (state's obligation to care for those who cannot care for themselves) and police power (state's authority to protect the public). Modern standards require mental illness AND dangerousness."},
{q:"Pro bono service is:",options:["Required by law to constitute 50% of a psychologist's practice","Encouraged by the APA Ethics Code as a contribution to the profession and society","Prohibited by the APA Ethics Code","Only appropriate for unlicensed providers"],correct:1,rationale:"Principle B (Fidelity and Responsibility) encourages psychologists to contribute a portion of their professional time for little or no compensation. Pro bono service is encouraged but not mandated as a specific percentage."},
{q:"In a custody evaluation, the psychologist's primary concern should be:",options:["The wishes of the parent who hired them","The best interests of the child","Equal treatment of both parents regardless of evidence","The recommendation of the child's teacher"],correct:1,rationale:"APA Guidelines for Child Custody Evaluations direct that the child's best interests are the primary consideration. The evaluator should remain impartial, assess both parents, and make evidence-based recommendations regardless of who retained them."},
{q:"Which case extended Tarasoff to include a duty to protect (not just warn)?",options:["Tarasoff I (1974)","Tarasoff II (1976)","Jablonski v. United States","Hedlund v. Superior Court"],correct:1,rationale:"Tarasoff I (1974) established a duty to warn. Tarasoff II (1976) expanded this to a broader duty to protect, meaning therapists may fulfill the obligation through various means (warning, hospitalizing, notifying police), not solely by warning the potential victim."},
{q:"Telepsychology guidelines emphasize the importance of:",options:["Only using telephone sessions","Ensuring competence in the technology used and being aware of jurisdictional issues","Avoiding all technology in psychological practice","Using social media for therapy"],correct:1,rationale:"APA's telepsychology guidelines require competence in the technology platform, awareness of jurisdictional/licensing requirements (practicing where the client is located), ensuring confidentiality of electronic communications, and addressing emergency protocols remotely."}
]
};
Object.entries(batch31).forEach(([domainId, questions]) => {
    const domain = EPPPData.getDomain(parseInt(domainId));
    if (domain) questions.forEach(q => domain.questions.push(q));
});
console.log('PasstheEPPP: Loaded ' + Object.values(batch31).reduce((s,q)=>s+q.length,0) + ' questions (batch 31).');
})();
