/* PasstheEPPP — Question Bank Batch 26
   Enhanced rationale format — 80 new questions across all 8 domains */
(function(){
    if (typeof EPPPData === 'undefined') return;

    const batch26 = [
        // ===== Domain 1: Biological Bases (10) =====
        {domainId:1, q:"Diffusion tensor imaging (DTI) measures:", options:["Blood flow in the brain","White matter tract integrity by tracking the DIFFUSION of water molecules along myelinated axon pathways","Neurotransmitter concentrations","Brain electrical activity"], answer:1, difficulty:"hard", rationale:"Correct: (B) DTI: an MRI technique that measures directional water diffusion. Water diffuses preferentially along axon bundles (anisotropic diffusion). Fractional anisotropy (FA) values indicate white matter integrity. Used to study connectivity and traumatic brain injury.\n\nWhy others are wrong:\n(A) Blood flow → fMRI (BOLD signal) or arterial spin labeling\n(C) Neurotransmitter concentrations → PET with specific radioligands\n(D) Electrical activity → EEG or MEG"},
        {domainId:1, q:"The thalamus is often described as the brain's:", options:["Movement center","RELAY STATION — routing sensory information to the appropriate cortical areas (except olfaction, which bypasses the thalamus)","Emotion center","Memory center"], answer:1, difficulty:"easy", rationale:"Correct: (B) The thalamus relays sensory information: visual (LGN → V1), auditory (MGN → A1), somatosensory (VPL → S1). Exception: olfaction goes directly from olfactory bulb to piriform cortex without thalamic relay.\n\nWhy others are wrong:\n(A) Movement center → motor cortex, basal ganglia, cerebellum\n(C) Emotion center → amygdala and limbic system (though the thalamus connects to these structures)\n(D) Memory center → hippocampus"},
        {domainId:1, q:"Positron emission tomography (PET) works by:", options:["Using magnetic fields","Detecting gamma rays emitted from radioactive tracers injected into the bloodstream, revealing metabolic activity","Using ultrasound waves","Measuring skin conductance"], answer:1, difficulty:"medium", rationale:"Correct: (B) PET: a radioactive tracer (e.g., fluorodeoxyglucose/FDG) is injected and metabolized by active brain cells. The tracer emits positrons → positron-electron annihilation → gamma rays detected by the scanner. Maps metabolic activity and receptor binding.\n\nWhy others are wrong:\n(A) Magnetic fields → MRI/fMRI\n(C) Ultrasound → transcranial Doppler or obstetric imaging\n(D) Skin conductance → galvanic skin response (GSR), a peripheral measure"},
        {domainId:1, q:"Glia cells differ from neurons in that they:", options:["Generate action potentials","Provide structural support, insulation (myelin), nutrients, and immune defense — but do NOT generate action potentials","Have no important functions","Are only found in the PNS"], answer:1, difficulty:"easy", rationale:"Correct: (B) Glia (~50% of brain cells): astrocytes (blood-brain barrier, nutrients, synaptic cleanup), oligodendrocytes (CNS myelin), Schwann cells (PNS myelin), microglia (immune defense). Essential support but don't fire action potentials.\n\nWhy others are wrong:\n(A) Neurons generate action potentials — glia do not\n(C) Glia have CRITICAL functions — they support, protect, and maintain neurons\n(D) Different glia types exist in both CNS (astrocytes, oligodendrocytes, microglia) and PNS (Schwann cells)"},
        {domainId:1, q:"Down syndrome (Trisomy 21) is caused by:", options:["A recessive gene","An extra copy of chromosome 21, resulting in intellectual disability, characteristic facial features, and increased risk of cardiac defects","A viral infection","A nutritional deficiency"], answer:1, difficulty:"easy", rationale:"Correct: (B) Down syndrome: three copies of chromosome 21 (trisomy). Most common chromosomal cause of intellectual disability. Features: characteristic facial morphology, heart defects, hypotonia, ID (mild to moderate), increased Alzheimer's risk. Maternal age is a risk factor.\n\nWhy others are wrong:\n(A) Down syndrome is chromosomal (extra chromosome), not a single recessive gene\n(C) It's a genetic/chromosomal condition, not caused by infection\n(D) It's chromosomal, not nutritional — no dietary intervention prevents it"},
        {domainId:1, q:"The amygdala plays a central role in:", options:["Motor coordination","Emotional processing, particularly FEAR conditioning, threat detection, and emotional memory formation","Language production","Visual acuity"], answer:1, difficulty:"easy", rationale:"Correct: (B) The amygdala: rapid threat detection (subcortical 'low road' via thalamus), fear conditioning, emotional memory enhancement, social evaluation, and emotion recognition in facial expressions. Bilateral damage → Klüver-Bucy syndrome.\n\nWhy others are wrong:\n(A) Motor coordination → cerebellum\n(C) Language production → Broca's area\n(D) Visual acuity → retina and visual cortex (V1)"},
        {domainId:1, q:"Clozapine (Clozaril) is unique among antipsychotics because:", options:["It has no side effects","It is effective for TREATMENT-RESISTANT schizophrenia but carries a risk of agranulocytosis requiring regular blood monitoring","It is available over the counter","It only blocks dopamine"], answer:1, difficulty:"hard", rationale:"Correct: (B) Clozapine: the only antipsychotic with demonstrated superiority for treatment-resistant schizophrenia (~30% of patients). Risk of agranulocytosis (~1%) requires mandatory weekly-to-monthly blood monitoring (CBC). Also carries metabolic and sedation risks.\n\nWhy others are wrong:\n(A) Clozapine has significant side effects (agranulocytosis, weight gain, sedation, metabolic syndrome, seizure risk)\n(C) Clozapine is prescription-only with mandatory blood monitoring requirements (REMS program)\n(D) Clozapine blocks multiple receptor types: D2, D4, 5-HT2A, muscarinic, histaminergic, and adrenergic"},
        {domainId:1, q:"The cerebellum's role extends beyond motor coordination to include:", options:["Only balance","Cognitive functions including timing, language processing, attention, and emotional regulation","No other functions beyond motor","Only reflexes"], answer:1, difficulty:"medium", rationale:"Correct: (B) Modern research reveals cerebellar contributions beyond motor: cognitive timing, verbal working memory, language processing, attention shifting, and emotional regulation. Cerebellar cognitive affective syndrome documents these deficits after cerebellar damage.\n\nWhy others are wrong:\n(A) Balance is ONE function — the cerebellum has extensive non-motor roles\n(C) The 'motor only' view is outdated — extensive cognitive and affective functions are documented\n(D) Reflexes are primarily mediated by the spinal cord — the cerebellum fine-tunes voluntary movements and supports cognition"},
        {domainId:1, q:"Sleep deprivation primarily affects:", options:["Only physical strength","Attention, executive function, emotional regulation, memory consolidation, immune function, and metabolic processes","Nothing significant","Only dream frequency"], answer:1, difficulty:"easy", rationale:"Correct: (B) Sleep deprivation impairs: sustained attention, working memory, decision-making, emotional regulation (increased amygdala reactivity), immune function (reduced NK cells), metabolism (insulin resistance), and memory consolidation (both declarative and procedural).\n\nWhy others are wrong:\n(A) Sleep deprivation has WIDESPREAD cognitive, emotional, and physiological effects beyond physical strength\n(C) Sleep deprivation has SIGNIFICANT, well-documented effects across multiple domains\n(D) Sleep deprivation affects far more than dream frequency — it impairs waking cognition and health"},
        {domainId:1, q:"The pituitary gland is called the 'master gland' because:", options:["It is the largest endocrine gland","It regulates OTHER endocrine glands through hormones like ACTH, TSH, FSH, LH, and growth hormone — though it is itself controlled by the hypothalamus","It directly produces all hormones","It has no regulatory function"], answer:1, difficulty:"easy", rationale:"Correct: (B) The anterior pituitary secretes trophic hormones controlling other glands: ACTH (adrenals), TSH (thyroid), FSH/LH (gonads), GH (growth), prolactin (mammary). The posterior pituitary stores/releases oxytocin and ADH. The hypothalamus controls the pituitary.\n\nWhy others are wrong:\n(A) The pituitary is actually quite small (pea-sized) — its importance is in regulatory function\n(C) Many hormones are produced by peripheral glands (thyroid, adrenals, gonads) — the pituitary REGULATES them\n(D) The pituitary's PRIMARY function is regulation of other endocrine glands"},

        // ===== Domain 3: Social & Cultural (10) =====
        {domainId:3, q:"The bystander effect (Darley & Latané) is mediated by:", options:["Only personal callousness","Diffusion of responsibility, pluralistic ignorance, and evaluation apprehension","Physical distance only","Only the victim's characteristics"], answer:1, difficulty:"medium", rationale:"Correct: (B) Three mechanisms: (1) diffusion of responsibility (others will help), (2) pluralistic ignorance (others don't seem concerned, so it must not be an emergency), and (3) evaluation apprehension (fear of embarrassment if it's not a real emergency).\n\nWhy others are wrong:\n(A) The bystander effect is SITUATIONAL — callousness isn't the primary factor\n(C) Physical distance matters but doesn't capture the three core psychological mechanisms\n(D) While victim characteristics matter, the effect is primarily driven by the NUMBER of observers and social processes"},
        {domainId:3, q:"Heuristic-systematic model (HSM, Chaiken) proposes:", options:["Only one mode of processing","TWO modes: systematic processing (careful analysis) and heuristic processing (relying on simple rules/cues) — similar to ELM's central/peripheral routes","That persuasion is impossible","That all processing is automatic"], answer:1, difficulty:"hard", rationale:"Correct: (B) Chaiken's HSM: systematic = thorough, analytic evaluation of arguments (high effort). Heuristic = reliance on simple decision rules (low effort). Unlike ELM, HSM proposes both can occur simultaneously and interact.\n\nWhy others are wrong:\n(A) The model specifically identifies TWO processing modes\n(C) The model explains HOW persuasion occurs through different processing routes\n(D) Systematic processing is deliberate and effortful, not automatic"},
        {domainId:3, q:"Social norms influence behavior through:", options:["No mechanisms","Descriptive norms (what people actually DO) and injunctive norms (what people SHOULD do according to social approval)","Only legal mandates","Only personal values"], answer:1, difficulty:"medium", rationale:"Correct: (B) Cialdini: descriptive norms (perceived typical behavior — 'most people recycle here') guide behavior through informational influence. Injunctive norms (perceived approval — 'people should recycle') guide through normative pressure/social sanctions.\n\nWhy others are wrong:\n(A) Social norms have well-documented behavioral influence mechanisms\n(C) Social norms operate BEYOND legal mandates through informal social pressure\n(D) Norms exert influence independent of personal values — people may follow norms they don't personally endorse"},
        {domainId:3, q:"The social dominance orientation (SDO) scale measures:", options:["Only political affiliation","Individual preference for GROUP-BASED social hierarchy and inequality — higher SDO predicts greater support for discrimination and opposition to equality","Only social skills","Only leadership ability"], answer:1, difficulty:"hard", rationale:"Correct: (B) Sidanius & Pratto: SDO measures preference for hierarchical intergroup relations. High SDO individuals favor policies maintaining group-based inequality, endorse legitimizing myths, and oppose egalitarian social change.\n\nWhy others are wrong:\n(A) SDO relates to hierarchy preferences, not specific political parties (though it correlates with certain ideologies)\n(C) SDO measures attitudes toward social hierarchy, not interpersonal social skills\n(D) SDO measures preference for social dominance systems broadly, not individual leadership capacity"},
        {domainId:3, q:"Right-wing authoritarianism (RWA, Altemeyer) is characterized by:", options:["Only economic conservatism","High conventionalism (adherence to established norms), authoritarian submission (deference to authority), and authoritarian aggression (hostility toward norm violators)","Only left-wing ideology","Social liberalism"], answer:1, difficulty:"hard", rationale:"Correct: (B) Altemeyer's three components: (1) conventionalism (strong adherence to traditional norms), (2) authoritarian submission (uncritical deference to established authorities), and (3) authoritarian aggression (aggression toward people perceived as violating norms).\n\nWhy others are wrong:\n(A) RWA is a personality/attitudinal construct, not purely economic\n(C) Despite the name, RWA can be found across political spectrums (it's about submission to authority)\n(D) High RWA is associated with social conservatism, not liberalism"},
        {domainId:3, q:"Intersectionality (Crenshaw) recognizes that:", options:["Only one identity shapes experience","Multiple social identities (race, gender, class, sexuality, disability) INTERSECT to create unique experiences of privilege and oppression","Identity has no impact on experience","Only race matters"], answer:1, difficulty:"medium", rationale:"Correct: (B) Crenshaw (1989): intersectionality recognizes that social categories don't operate independently. A Black woman's experience isn't simply 'Black' + 'woman' — the intersection creates qualitatively different experiences of discrimination and privilege.\n\nWhy others are wrong:\n(A) Intersectionality fundamentally argues that MULTIPLE identities shape experience simultaneously\n(C) Identity significantly shapes lived experience — intersectionality documents HOW\n(D) While race is important, intersectionality examines the INTERACTION of ALL social identities"},
        {domainId:3, q:"Cognitive dissonance is GREATEST when:", options:["The behavior is forced with large external justification","The behavior was freely chosen, the commitment is public, the consequences are foreseeable, and there is INSUFFICIENT external justification","The behavior doesn't matter to the person","There is strong external pressure to comply"], answer:1, difficulty:"hard", rationale:"Correct: (B) Dissonance is maximized when: (1) free choice (not coerced), (2) insufficient justification ('I did it for only $1'), (3) public commitment, (4) foreseeable consequences, and (5) the behavior is important. Less external justification → more internal attitude change.\n\nWhy others are wrong:\n(A) LARGE external justification REDUCES dissonance — 'I did it because they paid me $20' provides justification\n(C) Dissonance requires the behavior to be personally IMPORTANT and self-relevant\n(D) Strong external pressure provides JUSTIFICATION, which REDUCES dissonance"},
        {domainId:3, q:"The looking-glass self (Cooley) proposes that:", options:["Self-concept is entirely innate","Our self-concept is formed by how we IMAGINE others perceive us — we see ourselves as we think others see us","Self-concept has nothing to do with social interaction","Only objective self-evaluation matters"], answer:1, difficulty:"medium", rationale:"Correct: (B) Cooley (1902): three components — (1) we imagine how we appear to others, (2) we imagine their judgment of our appearance, (3) we develop feelings about ourselves based on our perception of their judgments. Self is fundamentally social.\n\nWhy others are wrong:\n(A) The looking-glass self theory emphasizes that self-concept is SOCIALLY constructed\n(C) Social interaction is CENTRAL to this theory — self-concept IS a social product\n(D) The theory emphasizes PERCEIVED (imagined) judgments, which may differ from objective reality"},
        {domainId:3, q:"The illusory correlation occurs when:", options:["Only real correlations are perceived","People OVERESTIMATE the relationship between distinctive events — particularly between minority group membership and rare negative behaviors","Correlations are always accurate","Only statisticians notice correlations"], answer:1, difficulty:"medium", rationale:"Correct: (B) Hamilton & Gifford: when two distinctive (uncommon) events co-occur, people overestimate their association. Since minority groups and negative behaviors are both statistically infrequent, their co-occurrence is disproportionately noticed and remembered.\n\nWhy others are wrong:\n(A) The 'illusory' part means the perceived correlation is STRONGER than reality\n(C) Illusory correlations demonstrate that perceived correlations are often INACCURATE\n(D) Everyone is susceptible to illusory correlations — it's a basic cognitive bias"},
        {domainId:3, q:"Acculturation strategies (Berry) include:", options:["Only assimilation","Integration, assimilation, separation, and marginalization — based on maintenance of heritage culture and relationships with the dominant culture","Only one possible strategy","Strategies that never change"], answer:1, difficulty:"medium", rationale:"Correct: (B) Berry's fourfold model: Integration (maintain heritage + adopt new culture — best outcomes), Assimilation (adopt new, abandon heritage), Separation (maintain heritage, reject new), Marginalization (reject both — worst outcomes).\n\nWhy others are wrong:\n(A) Assimilation is ONE of four strategies\n(C) Four distinct strategies exist, producing different well-being outcomes\n(D) Acculturation strategies can change over time and across contexts"},

        // ===== Domain 5: Assessment (5) =====
        {domainId:5, q:"The WAIS-V is designed for ages:", options:["6-16","16-90 — the adult version of the Wechsler intelligence scales","2-5","0-3"], answer:1, difficulty:"easy", rationale:"Correct: (B) WAIS-V (Wechsler Adult Intelligence Scale, 5th ed.): ages 16:0-90:11. Provides FSIQ and index scores. It overlaps with WISC-V at age 16, allowing clinicians to choose the more appropriate measure.\n\nWhy others are wrong:\n(A) Ages 6-16 = WISC-V\n(C) Ages 2:6-7:7 = WPPSI-IV\n(D) Ages 0-3 = Bayley Scales"},
        {domainId:5, q:"Practice effects in testing refer to:", options:["Improved scores from familiarity","Score improvements on retesting due to FAMILIARITY with the test format, items, or strategies — rather than true ability change","Decreased scores on retesting","Effects that never occur"], answer:1, difficulty:"easy", rationale:"Correct: (B) Practice effects: score improvements from repeated testing reflect familiarity with test procedures, remembered items, or developed strategies — NOT genuine ability improvement. These inflate test-retest reliability estimates and can confound longitudinal studies.\n\nWhy others are wrong:\n(A) This answer IS essentially correct — but the key distinction is familiarity vs. true ability change\n(C) Practice effects typically INCREASE scores, not decrease them\n(D) Practice effects are well-documented and virtually universal on cognitive tests"},
        {domainId:5, q:"The NEO-PI-R (NEO Personality Inventory-Revised) measures:", options:["Only depression","The Big Five personality factors: Neuroticism, Extraversion, Openness, Agreeableness, and Conscientiousness","Only intelligence","Only psychopathology"], answer:1, difficulty:"easy", rationale:"Correct: (B) NEO-PI-R (Costa & McCrae): 240-item self-report measuring the Big Five (OCEAN/CANOE) personality dimensions, each with six facets. Comprehensive normal personality assessment used in clinical, educational, and occupational settings.\n\nWhy others are wrong:\n(A) The NEO-PI-R measures broad personality, not specifically depression\n(C) Intelligence → Wechsler scales, Stanford-Binet\n(D) The NEO-PI-R measures NORMAL personality — psychopathology → MMPI-2, PAI, MCMI-IV"},
        {domainId:5, q:"Base rate in diagnostic assessment refers to:", options:["The cost of the test","The PREVALENCE of a condition in the population being tested — affecting the predictive value of test results","The passing score","The time to complete the test"], answer:1, difficulty:"medium", rationale:"Correct: (B) Base rate: the proportion of the population that actually has the condition. Low base rates decrease positive predictive value (many false positives). Ignoring base rates (base rate neglect) leads to diagnostic errors.\n\nWhy others are wrong:\n(A) Base rate refers to condition prevalence, not financial cost\n(C) The passing/cutoff score is a separate concept from base rate\n(D) Administration time is unrelated to base rate"},
        {domainId:5, q:"The Halstead-Reitan Neuropsychological Battery assesses:", options:["Only personality","Brain-behavior relationships through a comprehensive battery measuring attention, memory, motor function, sensory processing, abstracting, and language","Only reading ability","Only emotional intelligence"], answer:1, difficulty:"medium", rationale:"Correct: (B) Halstead-Reitan: comprehensive fixed battery of neuropsychological tests (Category Test, TPT, Rhythm Test, Speech Sounds, Finger Tapping, Trail Making, etc.). Assesses brain-behavior relationships across multiple cognitive and motor domains.\n\nWhy others are wrong:\n(A) The H-R Battery assesses cognitive/neuropsychological function, not personality\n(C) Reading is just one small component — the battery is comprehensive\n(D) Emotional intelligence is assessed by the MSCEIT, not the H-R Battery"},

        // ===== Domain 6: Treatment (5) =====
        {domainId:6, q:"Flooding (implosive therapy) involves:", options:["Gradual hierarchical exposure","IMMEDIATE, prolonged exposure to the most feared stimulus until anxiety habituates — without a gradual approach","Only relaxation techniques","Avoiding all feared stimuli"], answer:1, difficulty:"easy", rationale:"Correct: (B) Flooding (Stampfl): direct, prolonged exposure to the maximum anxiety-provoking stimulus. Based on extinction: sustained exposure without aversive consequence → anxiety habituates. Faster than SD but more distressing.\n\nWhy others are wrong:\n(A) Gradual hierarchy = systematic desensitization (Wolpe) — flooding bypasses the hierarchy\n(C) Flooding involves intense exposure, not relaxation\n(D) Avoidance MAINTAINS fear — flooding CONFRONTS it directly"},
        {domainId:6, q:"Solution-focused brief therapy (SFBT) assumes:", options:["Problems must be thoroughly analyzed before solutions are explored","Clients have STRENGTHS and RESOURCES to solve problems — focus on solutions and what's working rather than problem analysis","Therapists provide all solutions","Therapy must be long-term"], answer:1, difficulty:"easy", rationale:"Correct: (B) de Shazer & Berg: SFBT focuses on what's already WORKING (exceptions to the problem), preferred futures (miracle question), and client strengths. Key tenets: if it works, do more; if it doesn't, try something different.\n\nWhy others are wrong:\n(A) SFBT intentionally MINIMIZES problem analysis — focusing on solutions instead\n(C) CLIENTS generate solutions — the therapist facilitates discovery of existing strengths\n(D) SFBT is designed as BRIEF therapy (often 5-8 sessions)"},
        {domainId:6, q:"Aversion therapy pairs:", options:["A pleasant stimulus with relaxation","An UNDESIRABLE behavior with an AVERSIVE stimulus to reduce the behavior through classical conditioning","Only positive reinforcement with behavior","A neutral stimulus with a reward"], answer:1, difficulty:"easy", rationale:"Correct: (B) Aversion therapy: pairs the unwanted behavior/stimulus (alcohol, smoking) with an aversive response (nausea via disulfiram, electric shock, covert sensitization imagery). Based on classical conditioning to create negative associations.\n\nWhy others are wrong:\n(A) Pleasant stimulus + relaxation = systematic desensitization or relaxation training\n(C) Positive reinforcement increases behavior — aversion therapy decreases it\n(D) Neutral + reward = positive reinforcement conditioning"},
        {domainId:6, q:"Genograms in family therapy:", options:["Are standardized psychological tests","Are multigenerational family maps showing relationships, patterns, medical/mental health history, and recurring family dynamics across 3+ generations","Only show current family members","Are never used in therapy"], answer:1, difficulty:"easy", rationale:"Correct: (B) Genograms (Bowen, McGoldrick): visual diagrams mapping at least three generations. Include relationship patterns (close, conflictual, cutoff), major events, medical/mental health history, occupations, and family roles. Identify multigenerational patterns.\n\nWhy others are wrong:\n(A) Genograms are clinical tools/visual representations, not standardized tests with norms\n(C) Genograms specifically include MULTIPLE generations (usually 3+) to show patterns\n(D) Genograms are widely used in family therapy, medical family therapy, and even individual therapy"},
        {domainId:6, q:"The dose-response relationship in psychotherapy research shows:", options:["More therapy always equals better outcomes","Most improvement occurs in the EARLY sessions, with diminishing returns over time — approximately 50% improve by session 8 and 75% by session 26","All clients need 100+ sessions","Therapy length doesn't matter"], answer:1, difficulty:"medium", rationale:"Correct: (B) Howard et al. (1986), Lambert: the dose-response curve is negatively accelerating — rapid improvement early, then diminishing returns. This informs session limits and expected treatment trajectories (not everyone follows this pattern).\n\nWhy others are wrong:\n(A) The relationship is NEGATIVELY ACCELERATING — not linear improvement with more therapy\n(C) Most clients show significant improvement well before 100 sessions\n(D) Therapy length matters — but with diminishing returns over time"},

        // ===== Domain 7: Research (5) =====
        {domainId:7, q:"Counterbalancing in within-subjects designs:", options:["Is unnecessary","Controls for ORDER EFFECTS by varying the sequence of conditions across participants","Eliminates all confounds","Only applies to between-subjects designs"], answer:1, difficulty:"easy", rationale:"Correct: (B) Counterbalancing: varying the order in which conditions are experienced. Complete counterbalancing: all possible orders. Latin square: systematic partial counterbalancing. This distributes practice, fatigue, and carryover effects equally.\n\nWhy others are wrong:\n(A) Counterbalancing is ESSENTIAL in within-subjects designs to control order effects\n(C) Counterbalancing controls ORDER effects specifically — not all possible confounds\n(D) Counterbalancing is specifically used in WITHIN-subjects (repeated measures) designs"},
        {domainId:7, q:"Matched-pairs design:", options:["Randomly assigns without matching","PAIRS participants on relevant variables (age, IQ, severity) and then randomly assigns ONE member of each pair to each condition","Has no advantages over simple random assignment","Is the same as a within-subjects design"], answer:1, difficulty:"medium", rationale:"Correct: (B) Matched-pairs: participants matched on potentially confounding variables are paired, then randomly assigned to conditions. Reduces error variance from individual differences while maintaining independent groups.\n\nWhy others are wrong:\n(A) Matching specifically PRECEDES random assignment to reduce error\n(C) Matched-pairs designs REDUCE error variance by controlling for known confounds — an advantage over simple random assignment\n(D) Matched pairs use DIFFERENT participants in each condition (between-subjects) — within-subjects uses the SAME participants"},
        {domainId:7, q:"Standard deviation is:", options:["The same as the mean","A measure of VARIABILITY — the average distance of scores from the mean in a distribution","A measure of central tendency","Only used in qualitative research"], answer:1, difficulty:"easy", rationale:"Correct: (B) SD measures spread/dispersion: larger SD = more variability, smaller SD = less variability. In a normal distribution: ~68% of scores fall within ±1 SD, ~95% within ±2 SD, ~99.7% within ±3 SD of the mean.\n\nWhy others are wrong:\n(A) The mean is a measure of central tendency; SD is a measure of variability\n(C) Central tendency = mean, median, mode; SD is VARIABILITY/dispersion\n(D) SD is fundamental to quantitative (not qualitative) research and statistics"},
        {domainId:7, q:"A confounding variable:", options:["Is always controlled in research","Is an UNCONTROLLED variable that systematically covaries with the IV and could provide an ALTERNATIVE explanation for results","Never affects research outcomes","Is the same as the dependent variable"], answer:1, difficulty:"easy", rationale:"Correct: (B) Confound: a variable that varies systematically with the IV, making it impossible to determine whether the IV or the confound caused the DV change. Random assignment, matching, and statistical control help manage confounds.\n\nWhy others are wrong:\n(A) Confounds are UNCONTROLLED — if controlled, they're no longer confounding\n(C) Confounds can SERIOUSLY compromise research conclusions\n(D) Confounds are THIRD variables — distinct from both the IV and DV"},
        {domainId:7, q:"APA style requires research papers to include:", options:["Only results","Title page, abstract, introduction, method, results, discussion, and references — following a specific formatting structure","No citations","Only a conclusion paragraph"], answer:1, difficulty:"easy", rationale:"Correct: (B) APA 7th edition structure: title page, abstract, introduction (literature review + hypotheses), method (participants, measures, procedure), results (statistical analyses), discussion (interpretation, limitations, implications), references.\n\nWhy others are wrong:\n(A) APA papers include MULTIPLE required sections, not just results\n(C) APA style REQUIRES in-text citations and a references list\n(D) APA papers have a detailed structure far beyond a single paragraph"},

        // ===== Domain 8: Ethics (5) =====
        {domainId:8, q:"The HIPAA Privacy Rule requires:", options:["No protections for health information","Safeguards protecting individuals' protected health information (PHI) — limiting use and disclosure to treatment, payment, and healthcare operations without authorization","Only verbal notification of privacy practices","That all records be destroyed immediately after treatment"], answer:1, difficulty:"medium", rationale:"Correct: (B) HIPAA Privacy Rule: covered entities must protect PHI, provide Notice of Privacy Practices, limit disclosures to minimum necessary, obtain authorization for uses beyond treatment/payment/operations, and ensure patient rights (access, amendment, accounting).\n\nWhy others are wrong:\n(A) HIPAA specifically MANDATES protections for health information\n(C) HIPAA requires a WRITTEN Notice of Privacy Practices provided to patients\n(D) HIPAA requires record RETENTION, not immediate destruction"},
        {domainId:8, q:"Competence to stand trial requires that the defendant:", options:["Be found not guilty","Have a CURRENT ability to understand the charges against them AND assist in their own defense — Dusky v. United States (1960)","Have an IQ above average","Have no mental illness of any kind"], answer:1, difficulty:"medium", rationale:"Correct: (B) Dusky standard: competence = sufficient present ability to consult with one's attorney with a reasonable degree of rational understanding AND a factual and rational understanding of the proceedings.\n\nWhy others are wrong:\n(A) Competence to stand trial is about ABILITY to participate, not guilt/innocence\n(C) Many individuals with below-average IQ are competent to stand trial — it's about functional legal abilities\n(D) Having a mental illness doesn't automatically mean incompetence — the question is whether the illness impairs legal understanding/participation"},
        {domainId:8, q:"The McNaughten rule (insanity defense) requires proving that:", options:["The defendant was angry during the crime","At the time of the act, the defendant had a mental disease causing them to NOT KNOW the nature of their act OR that it was wrong","The defendant had any mental health history","The defendant planned the crime poorly"], answer:1, difficulty:"hard", rationale:"Correct: (B) McNaughten (1843): the defendant, due to a 'disease of the mind,' either (1) did not know the NATURE and QUALITY of the act, or (2) did not know that the act was WRONG. This is a COGNITIVE standard focused on knowledge.\n\nWhy others are wrong:\n(A) Anger doesn't meet the McNaughten standard — it requires a mental disease affecting knowledge\n(C) A mental health history alone is insufficient — the disease must have affected knowledge AT THE TIME of the act\n(D) Poor planning doesn't meet McNaughten — the standard is about knowledge, not planning ability"},
        {domainId:8, q:"Psychologists working with interpreters must:", options:["Rely entirely on the interpreter's clinical judgment","Obtain informed consent regarding the interpreter's involvement, ensure interpreter competence, and take reasonable steps to protect confidentiality","Never use interpreters","Allow anyone to interpret regardless of qualifications"], answer:1, difficulty:"medium", rationale:"Correct: (B) When using interpreters: obtain client consent, ensure interpreter competence (linguistic AND cultural), brief the interpreter on confidentiality, avoid using family members when possible (dual roles), and maintain responsibility for the assessment/treatment.\n\nWhy others are wrong:\n(A) Clinical judgment remains the PSYCHOLOGIST'S responsibility — the interpreter facilitates communication\n(C) Ethical practice sometimes REQUIRES interpreters for effective service delivery to diverse populations\n(D) Interpreter quality matters — using unqualified interpreters can lead to miscommunication and harm"},
        {domainId:8, q:"The irreconcilable conflict clause in the Ethics Code instructs psychologists that:", options:["Ethical conflicts never occur","When a conflict between the Ethics Code and law/organizational demands cannot be resolved, psychologists may comply with law/demands AS LONG AS it doesn't involve violating basic human rights","They must always violate the law to follow ethics","They should simply resign from all positions if conflicts arise"], answer:1, difficulty:"hard", rationale:"Correct: (B) Standard 1.02/1.03: when conflicts are unresolvable, psychologists may adhere to law or organizational requirements. However, under NO circumstances does this permit compliance that would result in violating fundamental human rights.\n\nWhy others are wrong:\n(A) Ethical-legal conflicts DO occur and the Code explicitly addresses them\n(C) Breaking the law isn't automatically required — reasonable resolution is attempted first\n(D) Resignation is one option but not the only recourse — the Code provides a resolution framework"}
    ];

    batch26.forEach(q => {
        const domain = EPPPData.domains.find(d => d.id === q.domainId);
        if (domain) {
            domain.questions.push({
                q: q.q, options: q.options, answer: q.answer,
                difficulty: q.difficulty, rationale: q.rationale,
                domainId: q.domainId, domainName: domain.name
            });
        }
    });

    console.log(`PasstheEPPP: Loaded ${batch26.length} additional questions (batch 26 — enhanced rationales).`);
})();
