#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');
const { execFileSync } = require('child_process');
const ROOT = __dirname;
const SOURCE = path.join(ROOT, 'quickstart_source.jsx');
const OUTPUT = path.join(ROOT, 'quickstart_module.js');
const PUBLIC_OUTPUT = path.join(ROOT, 'prismflow-deploy', 'public', 'quickstart_module.js');
const source = fs.readFileSync(SOURCE, 'utf8');
const compiled = babel.transformSync(source, {
  plugins: [['@babel/plugin-transform-react-jsx', { useBuiltIns: false }]], babelrc: false, configFile: false,
  parserOpts: { sourceType: 'script', plugins: ['jsx'] }, generatorOpts: { jsescOption: { minimal: true } },
}).code;
const output = `/**
 * AlloFlow QuickStartWizard Module
 * Auto-generated by _build_quickstart_module.js. Source: quickstart_source.jsx
 */
(function() {
  'use strict';
  if (window.__quickstartModuleLoaded) { console.warn('[QuickStartWizard] Already loaded - skipping'); return; }
  window.__quickstartModuleLoaded = true;
  var React = window.React;
  if (!React) { console.error('[QuickStartWizard] React not found on window'); return; }
  var useState = React.useState;
  var useEffect = React.useEffect;
  var useRef = React.useRef;
  var useCallback = React.useCallback;
  var useMemo = React.useMemo;
  var useContext = React.useContext;
  var LanguageContext = window.AlloLanguageContext;
  var _shared = window.__alloShared || {};
  var safeGetItem = _shared.safeGetItem || function(k) { try { return localStorage.getItem(k); } catch(e) { return null; } };
  var safeSetItem = _shared.safeSetItem || function(k,v) { try { localStorage.setItem(k,v); } catch(e) {} };
  var warnLog = _shared.warnLog || function() { console.warn.apply(console, arguments); };
  var _hooks = window.__alloHooks || {};
  var useFocusTrap = _hooks.useFocusTrap || function() {};
${compiled}
})();
`;
fs.writeFileSync(OUTPUT, output, 'utf8');
fs.writeFileSync(PUBLIC_OUTPUT, output, 'utf8');
execFileSync(process.execPath, ['-c', OUTPUT], { stdio: 'inherit' });
execFileSync(process.execPath, ['-c', PUBLIC_OUTPUT], { stdio: 'inherit' });
console.log(`Built ${OUTPUT} and synchronized deploy output`);
