#!/usr/bin/env node
/**
 * Build view_confirm_dialog_module.js from view_confirm_dialog_source.jsx
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SOURCE = path.join(ROOT, 'view_confirm_dialog_source.jsx');
const OUTPUT = path.join(ROOT, 'view_confirm_dialog_module.js');
const TMP = path.join(ROOT, '_tmp_confirm_dialog_entry.jsx');

if (!fs.existsSync(SOURCE)) { console.error('Source not found:', SOURCE); process.exit(1); }

const source = fs.readFileSync(SOURCE, 'utf-8');
const entry = `/* global React */\n\n${source}\n\nwindow.__confirmDialogExports = { ConfirmDialog };\n`;
fs.writeFileSync(TMP, entry, 'utf-8');

console.log('Compiling view_confirm_dialog_source.jsx with esbuild...');
try {
    execSync(`npx esbuild "${TMP}" --bundle=false --format=esm --jsx=transform --jsx-factory=React.createElement --jsx-fragment=React.Fragment --outfile="${TMP}.compiled.js" --target=es2020`, { cwd: ROOT, stdio: 'inherit' });
} catch (e) {
    console.error('esbuild failed');
    try { fs.unlinkSync(TMP); } catch(_) {}
    process.exit(1);
}

const compiled = fs.readFileSync(TMP + '.compiled.js', 'utf-8')
    .replace(/\/\*.*global.*\*\/\n/g, '')
    .replace(/window\.__confirmDialogExports\s*=\s*\{[^}]+\};?\s*/, '')
    .trim();

fs.unlinkSync(TMP);
fs.unlinkSync(TMP + '.compiled.js');

const outputCode = `/**
 * AlloFlow Confirm Dialog Module
 *
 * Auto-generated by _build_view_confirm_dialog_module.js — DO NOT EDIT MANUALLY.
 * Source: view_confirm_dialog_source.jsx
 */
(function() {
  'use strict';
  if (window.AlloModules && window.AlloModules.ConfirmDialog) {
    console.log('[CDN] ConfirmDialog already loaded, skipping');
    return;
  }
  var React = window.React;
  if (!React) { console.error('[ConfirmDialog] React not found on window'); return; }

${compiled}

  window.AlloModules = window.AlloModules || {};
  window.AlloModules.ConfirmDialog = { ConfirmDialog: ConfirmDialog };
  console.log('[CDN] ConfirmDialog loaded');
})();
`;

fs.writeFileSync(OUTPUT, outputCode, 'utf-8');
console.log(`Built ${OUTPUT} (${outputCode.split('\n').length} lines)`);
