#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

const ROOT = __dirname;
const SOURCE = path.join(ROOT, 'view_end_session_preview_source.jsx');
const OUTPUT = path.join(ROOT, 'view_end_session_preview_module.js');
const PUBLIC = path.join(ROOT, 'desktop/web-app/public/view_end_session_preview_module.js');

function compileJsx(source) {
  const result = babel.transformSync(source, {
    plugins: ['@babel/plugin-transform-react-jsx'],
    configFile: false,
    babelrc: false,
  });
  return result.code;
}

function buildEndSessionPreviewModule(source) {
  const compiled = compileJsx(source);
  return `/**
 * AlloFlow End Session Preview Module
 * Auto-generated by _build_view_end_session_preview_module.js — DO NOT EDIT.
 * Source: view_end_session_preview_source.jsx
 */
(function() {
  'use strict';
  if (window.AlloModules && window.AlloModules.EndSessionPreview) {
    console.log('[CDN] EndSessionPreview already loaded, skipping');
    return;
  }
  var React = window.React;
  if (!React) { console.error('[EndSessionPreview] React not found on window'); return; }

${compiled}

  window.AlloModules = window.AlloModules || {};
  window.AlloModules.EndSessionPreview = { EndSessionPreview: EndSessionPreview };
  console.log('[CDN] EndSessionPreview loaded');
})();
`;
}

module.exports = { buildEndSessionPreviewModule };

if (require.main === module) {
  if (!fs.existsSync(SOURCE)) {
    console.error('Source not found:', SOURCE);
    process.exit(1);
  }
  const output = buildEndSessionPreviewModule(fs.readFileSync(SOURCE, 'utf8'));
  fs.writeFileSync(OUTPUT, output, 'utf8');
  fs.mkdirSync(path.dirname(PUBLIC), { recursive: true });
  fs.writeFileSync(PUBLIC, output, 'utf8');
  console.log('Built view_end_session_preview_module.js and public mirror (' + Buffer.byteLength(output) + ' bytes)');
}
