/**
 * AlloFlow Leadership Hub Module
 * Auto-generated by _build_admin_hub_module.js — DO NOT EDIT MANUALLY.
 * Source: admin_hub_source.jsx
 * Container shell for the admin tool suite (walkthrough, dispro, meetings).
 */
(function() {
  'use strict';
  if (window.AlloModules && window.AlloModules.AdminHub) {
    console.log('[CDN] AdminHub already loaded, skipping');
    return;
  }
  var React = window.React;
  if (!React) { console.error('[AdminHub] React not found on window'); return; }

const ADMIN_HUB_STORAGE_MANIFEST = [
  { prefix: "allo_udlwalk_", tool: "UDL Walkthrough" },
  // config, roster, sessions, draft
  { prefix: "allo_wcop_", tool: "Walkthrough Copilot" },
  // delivery log
  { prefix: "allo_dispro_", tool: "Disproportionality Analyzer" },
  // analyses, draft
  { prefix: "allo_mtss_", tool: "MTSS Triage" },
  // datasets, groups
  { prefix: "allo_sped_", tool: "SpEd Timelines" },
  // cases, config
  { prefix: "allo_meetdocs_", tool: "Meeting Documentation" },
  // meetings, templates, draft
  { prefix: "allo_famann_", tool: "Family Announcements" },
  // saved, config, draft
  { prefix: "allo_educator_evaluation_", tool: "Educator Evaluation" },
  // local workspace, onboarding
  { prefix: "allo_school_rewards_", tool: "School Rewards & Store" }
  // launcher URL, setup checklist
];
const ADMIN_HUB_STORAGE_PREFIXES = ADMIN_HUB_STORAGE_MANIFEST.map((entry) => entry.prefix);
const ADMIN_HUB_BACKUP_FORMAT = "alloflow-leadership-hub-backup";
function _adminHubGroupByTool(keys) {
  const counts = [];
  for (const entry of ADMIN_HUB_STORAGE_MANIFEST) {
    const n = keys.filter((k) => k.indexOf(entry.prefix) === 0).length;
    if (n > 0) counts.push({ tool: entry.tool, count: n });
  }
  return counts;
}
function _adminHubKeyAllowed(key) {
  return typeof key === "string" && ADMIN_HUB_STORAGE_PREFIXES.some((p) => key.indexOf(p) === 0);
}
function _adminHubCollectBackup() {
  const keys = {};
  let count = 0;
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (!_adminHubKeyAllowed(key)) continue;
    const value = localStorage.getItem(key);
    if (typeof value === "string") {
      keys[key] = value;
      count++;
    }
  }
  return { format: ADMIN_HUB_BACKUP_FORMAT, version: 1, exportedAt: (/* @__PURE__ */ new Date()).toISOString(), keyCount: count, keys };
}
const ADMIN_HUB_DRIVE_CFG_KEY = "allo_adminhubdrive_config_v1";
function _adminHubDriveCfg() {
  try {
    const parsed = JSON.parse(localStorage.getItem(ADMIN_HUB_DRIVE_CFG_KEY) || "null");
    return parsed && typeof parsed === "object" && typeof parsed.url === "string" && typeof parsed.token === "string" ? parsed : null;
  } catch (_) {
    return null;
  }
}
function _adminHubHash(text) {
  let h = 5381;
  for (let i = 0; i < text.length; i++) {
    h = (h << 5) + h + text.charCodeAt(i) | 0;
  }
  return String(h);
}
async function _adminHubDrivePost(url, body) {
  const res = await fetch(url, { method: "POST", body: JSON.stringify(body) });
  return res.json();
}
async function _adminHubMaybeDriveBackup(opts) {
  const force = !!(opts && opts.force);
  try {
    const cfg = _adminHubDriveCfg();
    if (!cfg) return { status: "no-config" };
    const backup = _adminHubCollectBackup();
    if (backup.keyCount === 0) return { status: "empty" };
    const hash = _adminHubHash(JSON.stringify(backup.keys));
    if (!force && cfg.lastHash === hash) return { status: "unchanged", lastSavedAt: cfg.lastSavedAt };
    const reply = await _adminHubDrivePost(cfg.url, { token: cfg.token, action: "save", payload: backup });
    if (!reply || reply.ok !== true) return { status: "error", error: String(reply && reply.error || "save-failed") };
    const next = { ...cfg, lastSavedAt: (/* @__PURE__ */ new Date()).toISOString(), lastHash: hash };
    try {
      localStorage.setItem(ADMIN_HUB_DRIVE_CFG_KEY, JSON.stringify(next));
    } catch (_) {
    }
    return { status: "saved", keyCount: backup.keyCount, lastSavedAt: next.lastSavedAt };
  } catch (err) {
    return { status: "error", error: String(err && err.message || err) };
  }
}
function AdminHubDriveBackup({ tt, addToast }) {
  const [cfg, setCfg] = React.useState(() => _adminHubDriveCfg());
  const [setupOpen, setSetupOpen] = React.useState(false);
  const [urlInput, setUrlInput] = React.useState("");
  const [tokenInput, setTokenInput] = React.useState("");
  const [busy, setBusy] = React.useState(false);
  const [autoNote, setAutoNote] = React.useState("");
  const writeCfg = (next) => {
    try {
      if (next) localStorage.setItem(ADMIN_HUB_DRIVE_CFG_KEY, JSON.stringify(next));
      else localStorage.removeItem(ADMIN_HUB_DRIVE_CFG_KEY);
    } catch (_) {
    }
    setCfg(next);
  };
  const saveToDrive = React.useCallback(async ({ auto, force } = {}) => {
    const result = await _adminHubMaybeDriveBackup({ force: !!force });
    if (result.status === "saved") {
      setCfg(_adminHubDriveCfg());
      setAutoNote("");
      if (!auto) addToast(tt("adminhub.drive_saved", "Backup saved to your school Drive ({count} items).").replace("{count}", String(result.keyCount)), "success");
    } else if (result.status === "unchanged") {
      if (auto) setAutoNote(tt("adminhub.drive_unchanged", "No changes since the last Drive backup."));
    } else if (result.status === "empty") {
      if (!auto) addToast(tt("adminhub.backup_empty", "Nothing to back up yet — the hub tools have no saved data on this device."), "info");
    } else if (result.status === "error") {
      addToast((auto ? tt("adminhub.drive_auto_failed", "Automatic Drive backup failed: ") : tt("adminhub.drive_save_failed", "Drive backup failed: ")) + result.error, "error");
    }
    return result;
  }, [addToast, tt]);
  React.useEffect(() => {
    if (!_adminHubDriveCfg()) return;
    saveToDrive({ auto: true });
  }, [saveToDrive]);
  if (!cfg) {
    return /* @__PURE__ */ React.createElement("div", { className: "mt-2 border-t border-slate-200 pt-2", "data-help-key": "adminhub_drive_section" }, !setupOpen ? /* @__PURE__ */ React.createElement(
      "button",
      {
        type: "button",
        "data-help-key": "adminhub_drive_setup_open",
        onClick: () => setSetupOpen(true),
        className: "text-[11px] font-bold text-indigo-700 underline underline-offset-2 hover:text-indigo-900"
      },
      tt("adminhub.drive_setup_open", "Set up automatic Drive backup (school Google account)"),
      /* @__PURE__ */ React.createElement("span", { "aria-hidden": "true" }, " →")
    ) : /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("p", { className: "text-[11px] text-slate-600" }, tt("adminhub.drive_setup_intro", "A 3-minute script on your school-managed Google account saves this hub to your Drive automatically — covered by your district’s data agreement. Follow the setup steps in the leader’s guide, then paste the web-app URL and token here.")), /* @__PURE__ */ React.createElement("div", { className: "mt-2 flex flex-col sm:flex-row gap-2 sm:items-end" }, /* @__PURE__ */ React.createElement("div", { className: "flex-1 min-w-0" }, /* @__PURE__ */ React.createElement("label", { htmlFor: "adminhub-drive-url", className: "block text-[11px] font-bold text-slate-700 mb-0.5" }, tt("adminhub.drive_url_label", "Web app URL")), /* @__PURE__ */ React.createElement(
      "input",
      {
        id: "adminhub-drive-url",
        type: "url",
        value: urlInput,
        onChange: (e) => setUrlInput(e.target.value),
        placeholder: tt("adminhub.drive_url_placeholder", "Web app URL ending in /exec"),
        className: "min-h-10 w-full rounded-lg border border-slate-300 bg-white px-2 text-xs"
      }
    )), /* @__PURE__ */ React.createElement("div", { className: "w-full sm:w-40" }, /* @__PURE__ */ React.createElement("label", { htmlFor: "adminhub-drive-token", className: "block text-[11px] font-bold text-slate-700 mb-0.5" }, tt("adminhub.drive_token_label", "Backup token")), /* @__PURE__ */ React.createElement(
      "input",
      {
        id: "adminhub-drive-token",
        type: "password",
        value: tokenInput,
        onChange: (e) => setTokenInput(e.target.value),
        placeholder: tt("adminhub.drive_token_placeholder", "From setup()"),
        className: "min-h-10 w-full rounded-lg border border-slate-300 bg-white px-2 text-xs"
      }
    )), /* @__PURE__ */ React.createElement(
      "button",
      {
        type: "button",
        "data-help-key": "adminhub_drive_connect",
        disabled: busy || !urlInput.trim() || !tokenInput.trim(),
        onClick: async () => {
          setBusy(true);
          try {
            const url = urlInput.trim();
            const reply = await _adminHubDrivePost(url, { token: tokenInput.trim(), action: "ping" });
            if (!reply || reply.ok !== true) throw new Error(reply && reply.error || "no-reply");
            const next = { url, token: tokenInput.trim(), folder: String(reply.folder || ""), lastSavedAt: null, lastHash: null };
            writeCfg(next);
            setSetupOpen(false);
            setUrlInput("");
            setTokenInput("");
            addToast(tt("adminhub.drive_connected", "Drive backup connected. Saving a first backup now…"), "success");
            await saveToDrive({ force: true });
          } catch (err) {
            addToast(tt("adminhub.drive_connect_failed", "Could not connect: ") + String(err && err.message || err) + tt("adminhub.drive_connect_hint", " — check the URL ends in /exec, the token matches setup(), and the deployment allows Anyone."), "error");
          } finally {
            setBusy(false);
          }
        },
        className: "min-h-10 px-3 rounded-lg border border-indigo-300 bg-white text-xs font-bold text-indigo-800 hover:bg-indigo-50 disabled:opacity-50"
      },
      busy ? tt("adminhub.drive_connecting", "Connecting…") : tt("adminhub.drive_connect", "Connect & test")
    ))));
  }
  return /* @__PURE__ */ React.createElement("div", { className: "mt-2 border-t border-slate-200 pt-2 flex flex-wrap items-center justify-between gap-2", "data-help-key": "adminhub_drive_section" }, /* @__PURE__ */ React.createElement("p", { role: "status", "aria-live": "polite", className: "text-[11px] text-slate-600 min-w-0", "data-help-key": "adminhub_drive_status" }, /* @__PURE__ */ React.createElement("span", { className: "font-bold text-emerald-800" }, tt("adminhub.drive_on", "Drive auto-backup on")), cfg.folder ? " · " + cfg.folder : "", " · ", cfg.lastSavedAt ? tt("adminhub.drive_last_saved", "last saved {time}").replace("{time}", new Date(cfg.lastSavedAt).toLocaleString()) : tt("adminhub.drive_not_yet", "no backup saved yet"), autoNote ? " · " + autoNote : ""), /* @__PURE__ */ React.createElement("div", { className: "flex gap-2 shrink-0" }, /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      "data-help-key": "adminhub_drive_save_now",
      disabled: busy,
      onClick: async () => {
        setBusy(true);
        try {
          await saveToDrive({ force: true });
        } finally {
          setBusy(false);
        }
      },
      className: "min-h-10 px-3 rounded-lg border border-emerald-300 bg-white text-[11px] font-bold text-emerald-800 hover:bg-emerald-50 disabled:opacity-50"
    },
    busy ? tt("adminhub.drive_saving", "Saving…") : tt("adminhub.drive_save_now", "Back up to Drive now")
  ), /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      "data-help-key": "adminhub_drive_disconnect",
      onClick: () => {
        if (window.confirm(tt("adminhub.drive_disconnect_confirm", "Stop backing up to Drive? Existing backups stay in your Drive folder; only the connection on this device is removed."))) {
          writeCfg(null);
          addToast(tt("adminhub.drive_disconnected", "Drive backup disconnected."), "info");
        }
      },
      className: "min-h-10 px-3 rounded-lg border border-slate-300 bg-white text-[11px] font-bold text-slate-600 hover:bg-slate-100"
    },
    tt("adminhub.drive_disconnect", "Disconnect")
  )));
}
function AdminHubPanel(props) {
  const { onClose, t, openTool = (() => {
  }), addToast = (() => {
  }), onOpenSchoolRewards } = props;
  const tt = React.useCallback((key, fallback) => {
    if (typeof t === "function") {
      try {
        const v = t(key);
        if (v) return v;
      } catch (_) {
      }
    }
    return fallback;
  }, [t]);
  const openHubTool = React.useCallback((toolId) => {
    if (toolId !== "rewards") {
      openTool(toolId);
      return;
    }
    if (typeof onOpenSchoolRewards === "function") {
      onClose();
      onOpenSchoolRewards();
      return;
    }
    let portalUrl = "";
    try {
      const candidate = new URL(String(window.localStorage.getItem("allo_school_rewards_portal_url_v1") || "").trim());
      if (candidate.protocol === "https:" && candidate.hostname === "script.google.com" && !candidate.port && !candidate.username && !candidate.password && !candidate.search && !candidate.hash && /^\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(candidate.pathname)) portalUrl = candidate.origin + candidate.pathname;
    } catch (_) {
    }
    if (!portalUrl) {
      addToast(tt("adminhub.rewards_connect_first", "Connect School Rewards in Project Settings first."), "info");
      return;
    }
    try {
      const popup = window.open(portalUrl, "_blank", "noopener,noreferrer");
      if (!popup) {
        addToast(tt("adminhub.rewards_popup_blocked", "School Rewards was blocked. Allow pop-ups and try again."), "error");
        return;
      }
      popup.opener = null;
      onClose();
    } catch (_) {
      addToast(tt("adminhub.rewards_open_failed", "School Rewards could not open."), "error");
    }
  }, [addToast, onClose, onOpenSchoolRewards, openTool, tt]);
  const dialogRef = React.useRef(null);
  React.useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return void 0;
    const previousFocus = document.activeElement;
    const trapStack = window.__alloFocusTrapStack || (window.__alloFocusTrapStack = []);
    const trap = { root: dialog };
    trapStack.push(trap);
    const isTopTrap = () => trapStack[trapStack.length - 1] === trap;
    const getFocusable = () => Array.from(dialog.querySelectorAll(
      'button:not([disabled]), [href], input:not([disabled]), [tabindex]:not([tabindex="-1"])'
    )).filter((el) => !el.closest('[hidden], [inert], [aria-hidden="true"]'));
    const first = getFocusable()[0];
    (first || dialog).focus();
    const onKeyDown = (event) => {
      if (!isTopTrap()) return;
      if (event.key === "Escape") {
        event.preventDefault();
        event.stopPropagation();
        onClose();
        return;
      }
      if (event.key !== "Tab") return;
      const focusable = getFocusable();
      if (focusable.length === 0) {
        event.preventDefault();
        dialog.focus();
        return;
      }
      const firstItem = focusable[0], lastItem = focusable[focusable.length - 1];
      if (!dialog.contains(document.activeElement)) {
        event.preventDefault();
        (event.shiftKey ? lastItem : firstItem).focus();
      } else if (event.shiftKey && document.activeElement === firstItem) {
        event.preventDefault();
        lastItem.focus();
      } else if (!event.shiftKey && document.activeElement === lastItem) {
        event.preventDefault();
        firstItem.focus();
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      const wasTop = isTopTrap();
      const idx = trapStack.indexOf(trap);
      if (idx !== -1) trapStack.splice(idx, 1);
      if (wasTop && previousFocus && previousFocus !== document.body && previousFocus.isConnected && typeof previousFocus.focus === "function") previousFocus.focus();
    };
  }, [onClose]);
  const TOOLS = [
    {
      id: "mtss",
      icon: "🧮",
      title: tt("adminhub.mtss_title", "MTSS Triage"),
      desc: tt("adminhub.mtss_desc", "Screening scores against YOUR benchmark cut points: suggested risk bands for team review (never automatic placement), intervention grouping, and window-over-window progress."),
      accent: "from-violet-50 to-purple-50 border-violet-600",
      titleCls: "text-violet-800",
      descCls: "text-violet-700"
    },
    {
      id: "announcements",
      icon: "📣",
      title: tt("adminhub.announcements_title", "Family Announcements"),
      desc: tt("adminhub.announcements_desc", "One announcement, every family language: AI-translated with human review, exported as accessible lang-tagged documents with a translation disclosure — the whole-building packet the Bridge’s live messaging doesn’t cover."),
      accent: "from-emerald-50 to-lime-50 border-emerald-700",
      titleCls: "text-emerald-900",
      descCls: "text-emerald-800"
    },
    {
      id: "evaluation",
      icon: "✅",
      title: tt("adminhub.evaluation_title", "Educator Evaluation"),
      desc: tt("adminhub.evaluation_desc", "Opens your connected district evaluation portal; otherwise your private on-device workspace — completion and weighting views, walkthroughs, formal observations, SPM / SLO, dialogue, receipts, and audit history, with framework profiles for PA Act 13 and Maine PEPG."),
      accent: "from-blue-50 to-indigo-50 border-blue-700",
      titleCls: "text-blue-900",
      descCls: "text-blue-800"
    },
    {
      id: "rewards",
      icon: "🎟️",
      title: tt("adminhub.rewards_title", "School Rewards & Store"),
      desc: tt("adminhub.rewards_desc", "Open the connected Google Education rewards ledger for staff recognition, private student balance emails, prize previews, and locked trimester store checkout."),
      accent: "from-emerald-50 to-teal-50 border-emerald-700",
      titleCls: "text-emerald-900",
      descCls: "text-emerald-800"
    },
    {
      id: "walkthrough",
      icon: "🚪",
      title: tt("adminhub.walkthrough_title", "UDL Walkthrough"),
      desc: tt("adminhub.walkthrough_desc", "Growth-framed classroom visits scored against UDL 3.0 look-fors — feedback cards for teachers, a building heatmap, trends, and inter-rater checks for research use."),
      accent: "from-cyan-50 to-sky-50 border-cyan-600",
      titleCls: "text-cyan-800",
      descCls: "text-cyan-700"
    },
    {
      id: "walkthroughCopilot",
      icon: "📝",
      title: tt("adminhub.walkthrough_copilot_title", "Walkthrough Copilot"),
      desc: tt("adminhub.walkthrough_copilot_desc", "Turn shorthand walkthrough notes into evidence-based coaching feedback you write and approve — every claim cited back to your own notes, with practice scenarios for building the habit. Formative coaching only; never rates anyone."),
      accent: "from-teal-50 to-emerald-50 border-teal-600",
      titleCls: "text-teal-800",
      descCls: "text-teal-700"
    },
    {
      id: "dispro",
      icon: "⚖️",
      title: tt("adminhub.dispro_title", "Disproportionality Analyzer"),
      desc: tt("adminhub.dispro_desc", "Risk indexes, risk ratios, and composition from aggregate discipline or identification counts — stability cautions, alternate ratios for small groups, multi-year trends."),
      accent: "from-slate-50 to-indigo-50 border-slate-600",
      titleCls: "text-slate-800",
      descCls: "text-slate-600"
    },
    {
      id: "timelines",
      icon: "⏰",
      title: tt("adminhub.timelines_title", "SpEd Timelines"),
      desc: tt("adminhub.timelines_desc", "Evaluation clocks, IEP annuals, and triennials on one urgency dashboard with per-provider caseloads — student codes only; due dates are editable prefills you confirm against your state rule."),
      accent: "from-amber-50 to-orange-50 border-amber-600",
      titleCls: "text-amber-800",
      descCls: "text-amber-700"
    },
    {
      id: "diagnosisEligibility",
      icon: "🧩",
      title: tt("adminhub.eligibility_title", "Diagnosis, Evaluation & School Eligibility"),
      desc: tt("adminhub.eligibility_desc", "Compare clinical diagnosis, IDEA, and Section 504; follow the evaluation path; review federal definitions, safeguards, and timelines; explore open-question cases; and build a privacy-safe meeting-preparation guide. Never decides eligibility, services, or placement."),
      accent: "from-fuchsia-50 to-violet-50 border-fuchsia-700",
      titleCls: "text-fuchsia-900",
      descCls: "text-fuchsia-800"
    },
    {
      id: "meetings",
      icon: "📋",
      title: tt("adminhub.meetings_title", "Meeting Documentation"),
      desc: tt("adminhub.meetings_desc", "Turn notes or a transcript into your district’s meeting format — SST, IEP team, 504, and custom templates — with source-anchored decisions, an action-item tracker, and local name masking before any AI call."),
      accent: "from-emerald-50 to-teal-50 border-emerald-600",
      titleCls: "text-emerald-800",
      descCls: "text-emerald-700"
    }
  ];
  return /* @__PURE__ */ React.createElement("div", { className: "fixed inset-0 z-[260] bg-black/40 flex items-center justify-center overflow-y-auto p-3 sm:p-4", style: { zIndex: 260 }, role: "presentation", onClick: onClose }, /* @__PURE__ */ React.createElement("div", { ref: dialogRef, tabIndex: -1, "data-help-key": "adminhub_panel", className: "allo-docsuite bg-white rounded-2xl shadow-2xl w-full max-w-2xl p-5 sm:p-8 max-h-[90vh] overflow-y-auto focus:outline-none focus:ring-2 focus:ring-indigo-500", style: { maxHeight: "90vh" }, role: "dialog", "aria-modal": "true", "aria-labelledby": "adminhub-title", "aria-describedby": "adminhub-subtitle", onClick: (e) => e.stopPropagation() }, /* @__PURE__ */ React.createElement("div", { className: "flex items-center justify-between mb-4" }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h2", { id: "adminhub-title", className: "text-xl font-bold text-slate-800 flex items-center gap-2" }, /* @__PURE__ */ React.createElement("span", { "aria-hidden": "true" }, "🏛️"), " ", tt("adminhub.title", "Leadership Hub")), /* @__PURE__ */ React.createElement("p", { id: "adminhub-subtitle", className: "text-sm text-slate-600 mt-1" }, tt("adminhub.subtitle", "Tools for principals, coaches, and student-services leaders"))), /* @__PURE__ */ React.createElement("button", { type: "button", onClick: onClose, className: "min-w-11 min-h-11 p-2 inline-flex items-center justify-center rounded-lg text-slate-600 hover:text-slate-900 hover:bg-slate-100 transition-colors text-xl", "aria-label": tt("adminhub.close_aria", "Close Leadership Hub") }, "✕")), /* @__PURE__ */ React.createElement("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4" }, TOOLS.map((tool) => /* @__PURE__ */ React.createElement(
    "button",
    {
      key: tool.id,
      type: "button",
      "data-help-key": "adminhub_tool_card",
      onClick: () => openHubTool(tool.id),
      className: "flex items-start gap-3 p-4 bg-gradient-to-br border rounded-xl hover:shadow-lg hover:scale-[1.02] transition-all motion-reduce:transform-none motion-reduce:transition-none text-left " + tool.accent
    },
    /* @__PURE__ */ React.createElement("span", { className: "text-3xl mt-1", "aria-hidden": "true" }, tool.icon),
    /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h3", { className: "font-bold " + tool.titleCls }, tool.title), /* @__PURE__ */ React.createElement("p", { className: "text-xs mt-1 " + tool.descCls }, tool.desc))
  ))), /* @__PURE__ */ React.createElement("div", { className: "mt-5 rounded-xl border border-slate-200 bg-slate-50 p-3", "data-help-key": "adminhub_backup_section" }, /* @__PURE__ */ React.createElement("div", { className: "flex flex-wrap items-center justify-between gap-2" }, /* @__PURE__ */ React.createElement("div", { className: "min-w-0" }, /* @__PURE__ */ React.createElement("h3", { className: "text-xs font-black uppercase tracking-wide text-slate-700" }, tt("adminhub.backup_title", "Back up this hub")), /* @__PURE__ */ React.createElement("p", { className: "text-[11px] text-slate-500 mt-0.5" }, tt("adminhub.backup_desc", "Everything above lives only in this browser. Download one file with all of it, and restore on a new device or after a wipe."))), /* @__PURE__ */ React.createElement("div", { className: "flex gap-2 shrink-0" }, /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      "data-help-key": "adminhub_backup_export",
      onClick: () => {
        try {
          const backup = _adminHubCollectBackup();
          if (backup.keyCount === 0) {
            addToast(tt("adminhub.backup_empty", "Nothing to back up yet — the hub tools have no saved data on this device."), "info");
            return;
          }
          const blob = new Blob([JSON.stringify(backup, null, 2)], { type: "application/json" });
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = "alloflow-leadership-hub-backup-" + backup.exportedAt.slice(0, 10) + ".json";
          document.body.appendChild(a);
          a.click();
          a.remove();
          setTimeout(() => {
            try {
              URL.revokeObjectURL(url);
            } catch (_) {
            }
          }, 5e3);
          addToast(tt("adminhub.backup_done", "Backup downloaded ({count} saved items). Keep it where you keep confidential files.").replace("{count}", String(backup.keyCount)), "success");
        } catch (err) {
          addToast(tt("adminhub.backup_failed", "Backup failed: ") + String(err && err.message || err), "error");
        }
      },
      className: "min-h-10 px-3 rounded-lg border border-indigo-300 bg-white text-xs font-bold text-indigo-800 hover:bg-indigo-50"
    },
    tt("adminhub.backup_export", "Download backup")
  ), /* @__PURE__ */ React.createElement(
    "button",
    {
      type: "button",
      "data-help-key": "adminhub_backup_restore",
      onClick: () => {
        const input = document.createElement("input");
        input.type = "file";
        input.accept = "application/json,.json";
        input.onchange = () => {
          const file = input.files && input.files[0];
          if (!file) return;
          const reader = new FileReader();
          reader.onload = () => {
            try {
              const data = JSON.parse(String(reader.result || ""));
              if (!data || data.format !== ADMIN_HUB_BACKUP_FORMAT || typeof data.keys !== "object" || data.keys === null) {
                addToast(tt("adminhub.restore_not_backup", "That file is not a Leadership Hub backup."), "error");
                return;
              }
              const entries = Object.entries(data.keys).filter(([k, v]) => _adminHubKeyAllowed(k) && typeof v === "string");
              const rejected = Object.keys(data.keys).length - entries.length;
              if (entries.length === 0) {
                addToast(tt("adminhub.restore_empty", "The backup contains no hub data."), "error");
                return;
              }
              const stamp = typeof data.exportedAt === "string" ? data.exportedAt.slice(0, 10) : "?";
              const breakdown = _adminHubGroupByTool(entries.map(([k]) => k)).map((g) => "· " + g.tool + ": " + g.count + " " + (g.count === 1 ? tt("adminhub.restore_item_one", "item") : tt("adminhub.restore_item_many", "items"))).join("\n");
              const ok = window.confirm(
                tt("adminhub.restore_confirm", "Restore this backup, dated {date}?").replace("{date}", stamp) + "\n\n" + breakdown + "\n\n" + tt("adminhub.restore_confirm_effect", "Data for these tools on this device will be replaced by the backup. Tools not listed are left alone, and nothing outside the Leadership Hub is touched.")
              );
              if (!ok) return;
              for (const [k, v] of entries) localStorage.setItem(k, v);
              addToast(
                (rejected > 0 ? tt("adminhub.restore_done_skipped", "Restored {count} items; {skipped} entries outside the hub were ignored. Reopen a tool to see its data.").replace("{skipped}", String(rejected)) : tt("adminhub.restore_done", "Restored {count} items. Reopen a tool to see its data.")).replace("{count}", String(entries.length)),
                "success"
              );
            } catch (err) {
              addToast(tt("adminhub.restore_failed", "Restore failed: ") + String(err && err.message || err), "error");
            }
          };
          reader.readAsText(file);
        };
        input.click();
      },
      className: "min-h-10 px-3 rounded-lg border border-slate-300 bg-white text-xs font-bold text-slate-700 hover:bg-slate-100"
    },
    tt("adminhub.backup_restore", "Restore from backup")
  ))), /* @__PURE__ */ React.createElement("p", { className: "text-[11px] text-amber-800 mt-2" }, tt("adminhub.backup_caveat", "The file contains whatever the tools store — codes, notes, and settings. Treat it like the confidential records it may describe, and delete old copies per your retention policy.")), /* @__PURE__ */ React.createElement(AdminHubDriveBackup, { tt, addToast })), /* @__PURE__ */ React.createElement("p", { className: "mt-3 text-[11px] text-slate-500 border-t border-slate-200 pt-3" }, tt("adminhub.covenant", "How this suite handles information: analysis tools use aggregate counts or de-identified codes. Everything you enter stays in your signed-in profile on this device and is never uploaded, protected by your device sign-in rather than by separate encryption. Connecting a district portal adds shared, authenticated records staff can see and acknowledge. Apply your district’s retention rules, and keep a backup so a lost device is not a lost year. Human review stays in control—never an automated verdict about a teacher or student.")), /* @__PURE__ */ React.createElement("p", { className: "mt-2 text-[11px]" }, /* @__PURE__ */ React.createElement(
    "a",
    {
      href: "https://alloflow-cdn.pages.dev/guide/for-school-leaders.html",
      target: "_blank",
      rel: "noopener noreferrer",
      "data-help-key": "adminhub_guide_link",
      "aria-label": tt("adminhub.guide_link_aria", "Leader’s guide: how to use these tools (opens in a new tab)"),
      className: "font-bold text-indigo-700 underline underline-offset-2 hover:text-indigo-900"
    },
    tt("adminhub.guide_link", "Leader’s guide: how to use these tools"),
    /* @__PURE__ */ React.createElement("span", { "aria-hidden": "true" }, " →")
  ))));
}

  window.AlloModules = window.AlloModules || {};
  window.AlloModules.AdminHub = { AdminHubPanel: AdminHubPanel, maybeDriveBackup: _adminHubMaybeDriveBackup };
  console.log('[CDN] AdminHub loaded');
})();
