/* Accessible independent responses shared by solo encounters and resumed runs. */
function ConceptQuestSoloQuestion({ item, response = {}, onChange, disabled, guideOpen, onGuideOpen, t }) {
  const tr = (key, fallback) => { const value = t?.('concept_quest.' + key); return typeof value === 'string' && value !== 'concept_quest.' + key ? value : fallback; };
  const uid = React.useId();
  const update = patch => onChange({ ...response, ...patch });
  const type = item.type || 'mcq';
  const optionImage = index => item.optionImageUrls?.[index] ? <img src={item.optionImageUrls[index]} alt={item.optionImageAltTexts?.[index] || tr('solo_no_image_description', 'No visual description provided.')} className="mb-2 max-h-36 max-w-full rounded-lg object-contain"/> : null;
  const choiceClass = selected => 'flex min-h-11 items-start gap-3 rounded-xl border-2 p-3 text-left ' + (selected ? 'border-indigo-600 bg-indigo-50' : 'border-slate-300 bg-white');
  const textClass = 'min-h-11 w-full rounded-lg border border-slate-400 bg-white px-3 py-2 text-slate-900 focus:ring-4 focus:ring-indigo-200';
  const guide = window.AlloModules.ConceptQuestSoloEngine.answerGuide(item);
  const renderChoice = (option, index, field, name, image) => <label key={index} className={choiceClass(response[field] === index)}><input type="radio" name={uid + name} checked={response[field] === index} onChange={() => update({ [field]: index })} className="mt-1"/><span className="min-w-0 break-words">{image && optionImage(index)}<span className="mr-2 font-bold">{String.fromCharCode(65 + index)}.</span>{option}</span></label>;
  const pairs = Array.isArray(item.pairs) ? item.pairs : [];
  const orderItems = Array.isArray(item.items) ? item.items : [];
  const presented = Array.isArray(item.presentedOrder) && item.presentedOrder.length ? item.presentedOrder.map(entry => typeof entry === 'number' ? orderItems[entry] : entry) : orderItems;
  return <fieldset disabled={disabled} className="space-y-4" data-solo-question-type={type}>
    <legend className="mb-2 font-bold">{tr('solo_choose_answer', '2. Respond to the encounter')}</legend>
    <h4 id={uid + '-prompt'} className="break-words text-lg font-bold">{item.prompt || item.question}</h4>
    {item.question_en && <p className="text-sm italic text-slate-600">{item.question_en}</p>}
    {item.imageUrl && <img src={item.imageUrl} alt={item.imageAltText || tr('solo_no_image_description', 'No visual description provided.')} className="max-h-72 w-full rounded-xl bg-white object-contain"/>}
    {!item.selfReviewRequired && type === 'mcq' && <div className="space-y-2">{(item.options || []).map((option,index) => renderChoice(option,index,'answerIndex','answer',true))}</div>}
    {!item.selfReviewRequired && type === 'multi-select' && <><p className="text-sm text-slate-600">{tr('solo_select_all', 'Select every answer that applies.')}</p><div className="space-y-2">{(item.options || []).map((option,index) => { const selected = (response.selectedIndices || []).includes(index); return <label key={index} className={choiceClass(selected)}><input type="checkbox" checked={selected} onChange={() => update({selectedIndices:selected ? response.selectedIndices.filter(value => value !== index) : [...(response.selectedIndices || []),index]})} className="mt-1"/><span className="min-w-0 break-words">{optionImage(index)}{option}</span></label>; })}</div></>}
    {!item.selfReviewRequired && (type === 'fill-blank' || type === 'numeric-response') && <>
      <label className="block text-sm font-semibold">{type === 'numeric-response' ? tr('solo_numeric_answer', 'Your value') : tr('solo_fill_answer', 'Complete the blank')}<input aria-describedby={uid + '-prompt'} inputMode={type === 'numeric-response' ? 'decimal' : undefined} value={response.text || ''} maxLength={4000} onChange={event => update({text:event.target.value})} className={textClass + ' mt-2'}/></label>
      {type === 'numeric-response' && <><label className="block text-sm font-semibold">{tr('solo_units', 'Units')}<input value={response.unit || ''} maxLength={100} onChange={event => update({unit:event.target.value})} className={textClass + ' mt-2'}/></label><p className="text-sm text-slate-600">{tr('solo_numeric_help', 'Enter a number, decimal, or fraction. Include units when the question requires them.')}</p>{response.text && !window.AlloModules.ConceptQuestSoloEngine.grade(item,response).complete && <p role="status" className="text-sm text-amber-900">{tr('solo_numeric_invalid', 'Check that the value is a valid number and that any units in both fields agree.')}</p>}</>}
    </>}
    {!item.selfReviewRequired && type === 'sequence-sense' && <>
      <ol className="list-inside list-decimal space-y-2 rounded-xl border border-slate-200 bg-white p-4">{presented.map((text,index) => <li key={index} className="break-words">{text}</li>)}</ol>
      <label className="block text-sm font-semibold">{tr('solo_sequence_check', 'Is this sequence in the correct order?')}<select value={response.verifyAnswer || ''} onChange={event => update({verifyAnswer:event.target.value,wrongIndex:null})} className={textClass + ' mt-2'}><option value="">{tr('solo_select_response', 'Choose a response')}</option><option value="yes">{tr('solo_yes', 'Yes')}</option><option value="no">{tr('solo_no', 'No')}</option></select></label>
      {response.verifyAnswer === 'no' && <label className="block text-sm font-semibold">{tr('solo_wrong_position', 'Which position needs correcting?')}<select value={response.wrongIndex ?? ''} onChange={event => update({wrongIndex:event.target.value === '' ? null : Number(event.target.value)})} className={textClass + ' mt-2'}><option value="">{tr('solo_select_position', 'Choose a position')}</option>{presented.map((text,index) => <option key={index} value={index}>{index + 1}. {text}</option>)}</select></label>}
      <label className="block text-sm font-semibold">{tr('solo_ordering_reason', 'What principle determines the order?')}{Array.isArray(item.principleOptions) && item.principleOptions.length ? <select value={response.principleAnswer || ''} onChange={event => update({principleAnswer:event.target.value})} className={textClass + ' mt-2'}><option value="">{tr('solo_select_response', 'Choose a response')}</option>{item.principleOptions.map((option,index) => <option key={index} value={option}>{option}</option>)}</select> : <input value={response.principleAnswer || ''} onChange={event => update({principleAnswer:event.target.value})} maxLength={2000} className={textClass + ' mt-2'}/>} </label>
    </>}
    {!item.selfReviewRequired && type === 'relation-mismatch' && <>
      <ul className="space-y-2">{pairs.map((pair,index) => <li key={index} className="rounded-lg border border-slate-300 bg-white p-3">{index + 1}. {pair.left} <span aria-hidden="true">↔</span> {pair.right}</li>)}</ul>
      <label className="block text-sm font-semibold">{tr('solo_mismatch_pair', 'Which pair does not belong?')}<select value={response.pairIndex ?? ''} onChange={event => update({pairIndex:event.target.value === '' ? null : Number(event.target.value)})} className={textClass + ' mt-2'}><option value="">{tr('solo_select_pair', 'Choose a pair')}</option>{pairs.map((pair,index) => <option key={index} value={index}>{index + 1}. {pair.left} / {pair.right}</option>)}</select></label>
      <label className="block text-sm font-semibold">{tr('solo_correct_partner', 'Choose or write the correct partner')}{Array.isArray(item.candidatePartners) && item.candidatePartners.length ? <select value={response.partnerAnswer || ''} onChange={event => update({partnerAnswer:event.target.value})} className={textClass + ' mt-2'}><option value="">{tr('solo_select_response', 'Choose a response')}</option>{item.candidatePartners.map((partner,index) => <option key={index} value={partner}>{partner}</option>)}</select> : <input value={response.partnerAnswer || ''} onChange={event => update({partnerAnswer:event.target.value})} className={textClass + ' mt-2'}/>}</label>
    </>}
    {!item.selfReviewRequired && type === 'answer-evidence' && <><div role="group" aria-label={tr('solo_answer_part', 'Answer')} className="space-y-2">{(item.answerOptions || item.options || []).map((option,index) => renderChoice(option,index,'answerIndex','answer',false))}</div><h5 className="font-bold">{item.evidencePrompt || tr('solo_evidence_part', 'Choose the evidence that supports your answer.')}</h5><div role="group" aria-label={tr('solo_evidence_label', 'Supporting evidence')} className="space-y-2">{(item.evidenceOptions || []).map((option,index) => renderChoice(option,index,'evidenceIndex','evidence',false))}</div></>}
    {item.selfReviewRequired && <>
      <p className="rounded-lg bg-indigo-50 p-3 text-sm text-indigo-950">{tr('solo_written_scope', 'Explain your reasoning, then compare it with the answer guide. This is a self-review checkpoint; it is not automatically graded and does not award correctness XP.')}</p>
      <label className="block text-sm font-semibold">{tr('solo_your_explanation', 'Your explanation')}<textarea value={response.text || ''} onChange={event => update({text:event.target.value,guideRevealed:false,selfReview:''})} rows={4} maxLength={4000} className={textClass + ' mt-2'}/></label>
      <button type="button" disabled={!(response.text || '').trim()} onClick={() => { update({guideRevealed:true}); onGuideOpen?.(true); }} className="min-h-11 rounded-lg border border-indigo-300 bg-white px-3 py-2 font-bold text-indigo-800 disabled:opacity-50">{tr('solo_compare_guide', 'Compare with answer guide')}</button>
      {guideOpen && response.guideRevealed && <><div className="rounded-lg border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-950" role="status"><strong>{tr('solo_answer_guide', 'Answer guide')}: </strong>{guide}</div><label className="block text-sm font-semibold">{tr('solo_self_review_label', 'After comparing your explanation')}<select value={response.selfReview || ''} onChange={event => update({selfReview:event.target.value})} className={textClass + ' mt-2'}><option value="">{tr('solo_select_response', 'Choose a response')}</option><option value="understood">{tr('solo_understood', 'My explanation covers the key ideas')}</option><option value="needs-practice">{tr('solo_need_practice', 'I want more practice with this idea')}</option></select></label></>}
    </>}
  </fieldset>;
}
