import {learningDocument,learningText,downloadLearningFile} from './lesson_board_sharing.js';
import {prepareFinale,finaleReview,finaleArtifact,FINALE_TEXT_LIMIT} from './lesson_board_finale.js';
import {derive} from './lesson_board_engine.js';
import {tr} from './lesson_board_strings.js';
const React=window.React;
export function BoardFinale({board,run,value,onChange,disabled=false,role='solo',preview=false,t}){
 const review=finaleReview(board,run,value),draft=review.draft,progress=derive(board,run),heading=React.useRef(null),feedback=React.useRef(null),[error,setError]=React.useState(''),[focusFeedback,setFocusFeedback]=React.useState(0);
 React.useEffect(()=>{if(focusFeedback)feedback.current?.focus();},[focusFeedback]);
 if(!progress.complete)return null;
 const update=patch=>{if(!disabled){setError('');onChange(prepareFinale(board,run,{...draft,...patch,reviewed:false}));}};
 const project=review.project,effect=project?.effect.kind==='yield'?tr(t,'finale_yield','Earn +1 {resource} on each future successful exploration.',{resource:board.resources[project.effect.resource]}):tr(t,'finale_path','Open a direct path to {location}.',{location:board.locations.find(node=>node.id===project?.effect.targetId)?.name||board.locations.at(-1).name});
 const choices=[{id:'instant',label:tr(t,'finale_instant','Collect another full reward immediately without exploring.')},{id:'path',label:project?.effect.kind==='path'?effect:tr(t,'finale_other_path','Open a new direct path to a distant location.')},{id:'yield',label:project?.effect.kind==='yield'?effect:tr(t,'finale_other_yield','Earn an extra resource on each future successful exploration.')}];
 if(board.projects.findIndex(item=>item.id===project?.id)%2===1)choices.reverse();
 const readable=()=>{try{downloadLearningFile(learningText(learningDocument(board,run,{role,finale:draft,preview},{game:false,finale:true,practice:false,evidence:true},t)),'txt','lesson-board-plan');setError('');}catch(_){setError(tr(t,'finale_download_failed','Your plan could not be downloaded. Your current response is still shown here.'));}};
 const download=()=>{try{const blob=new Blob([JSON.stringify(finaleArtifact(board,run,draft),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='lesson-board-finale.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setError('');}catch(_){setError(tr(t,'finale_download_failed','Your plan could not be downloaded. Your current response is still shown here.'));}};
 return <section className="lb-notice lb-finale" data-board-finale={review.complete?'complete':draft?'active':'ready'}><h3 ref={heading} tabIndex={-1}>{tr(t,'finale_title','Final challenge: put your discoveries to work')}</h3><p>{tr(t,'finale_scenario','A new team is joining {board}. Choose a construction you completed and connect two lesson concepts to plan their first investigation.',{board:board.title})}</p><p className="lb-muted">{tr(t,'finale_separate','Your mission is already complete. This challenge records a plan without changing supplies or game scores.')}</p>
 {!draft?<button type="button" className="lb-primary" data-start-finale disabled={disabled} onClick={()=>{onChange(prepareFinale(board,run,{started:true}));setTimeout(()=>heading.current?.focus(),0);}}>{tr(t,'finale_start','Start the final challenge')}</button>:<>
 {role!=='solo'&&<p data-finale-private>{role==='teacher'?tr(t,'finale_teacher','Use your plan to model a discussion. Each learner has a separate plan in their own tab. Ask learners to discuss or download theirs to share.'):tr(t,'finale_private','Your plan stays in this browser tab, including after a reload. Discuss it or download it to share with your teacher before the board ends or restarts.')}</p>}
 <fieldset disabled={disabled}><legend>{tr(t,'finale_project_step','1. Put a completed construction to use')}</legend><label>{tr(t,'finale_project','Construction for the new team')}<select data-finale-project value={draft.projectId} onChange={event=>update({projectId:event.target.value,effectChoice:''})}><option value="">{tr(t,'finale_pick_project','Choose a completed construction')}</option>{board.projects.filter(item=>progress.built.includes(item.id)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{project&&<><p>{project.description}</p><label>{tr(t,'finale_effect','Which board effect would this construction provide?')}<select data-finale-effect value={draft.effectChoice} onChange={event=>update({effectChoice:event.target.value})}><option value="">{tr(t,'finale_pick_effect','Choose its effect')}</option>{choices.map(choice=><option key={choice.id} value={choice.id}>{choice.label}</option>)}</select></label></>}</fieldset>
 <fieldset disabled={disabled}><legend>{tr(t,'finale_evidence_step','2. Connect evidence from two concepts')}</legend><p>{tr(t,'finale_evidence_help','Choose two explored locations with different concept labels. Use their lesson evidence to explain a connection.')}</p>{[0,1].map(index=>{const node=board.locations.find(node=>node.id===draft.evidenceIds[index]);return <div key={index}><label>{tr(t,'finale_evidence','Evidence location {number}',{number:index+1})}<select data-finale-evidence={index} value={node?.id||''} onChange={event=>{const ids=[...draft.evidenceIds];ids[index]=event.target.value;update({evidenceIds:ids});}}><option value="">{tr(t,'finale_pick_evidence','Choose explored evidence')}</option>{board.locations.filter(item=>progress.visited.includes(item.id)&&(!draft.evidenceIds.includes(item.id)||item.id===node?.id)).map(item=><option key={item.id} value={item.id}>{item.name} · {board.concepts.find(concept=>concept.id===item.conceptId)?.name}</option>)}</select></label>{node&&<><p data-finale-concept={index}>{board.concepts.find(concept=>concept.id===node.conceptId)?.name}</p><details data-finale-source={node.id}><summary>{tr(t,'finale_read_evidence','Read evidence: {name}',{name:node.name})}</summary><blockquote>{node.sourceQuote}</blockquote><p>{node.explanation}</p></details></>}</div>;})}</fieldset>
 <fieldset disabled={disabled}><legend>{tr(t,'finale_plan_step','3. Explain the investigation plan')}</legend><label>{tr(t,'finale_response_mode','How will you explain your plan?')}<select data-finale-mode value={draft.mode} onChange={event=>update({mode:event.target.value,oralConfirmed:false})}><option value="text">{tr(t,'finale_write','Write my explanation')}</option><option value="oral">{tr(t,'finale_oral','Explain aloud or with my communication tools')}</option></select></label><details><summary>{tr(t,'finale_starters','Sentence starters and review prompts')}</summary><p>{tr(t,'finale_starter_project','Our construction helps the team by…')}</p><p>{tr(t,'finale_starter_connection','The evidence at the two locations connects because…')}</p><p>{tr(t,'finale_starter_investigation','To investigate this connection, the new team could…')}</p></details>{draft.mode==='text'?<label>{tr(t,'finale_explanation','My plan and evidence')}<textarea data-finale-explanation maxLength={FINALE_TEXT_LIMIT} value={draft.explanation} onChange={event=>update({explanation:event.target.value})}/><small>{tr(t,'finale_length','{count}/{limit} characters',{count:draft.explanation.length,limit:FINALE_TEXT_LIMIT})}</small></label>:<><p>{tr(t,'finale_oral_help','Use speech, signing, a drawing, or your communication tools. No microphone or recording is needed. Explain the construction, the evidence connection, and what the team could investigate.')}</p><label className="lb-row"><input style={{width:'auto'}} type="checkbox" data-finale-oral-confirmed checked={draft.oralConfirmed} onChange={event=>update({oralConfirmed:event.target.checked})}/><span style={{flex:'1 1 0',minWidth:0}}>{tr(t,'finale_oral_done','I have explained my plan.')}</span></label></>}
 <p>{tr(t,'finale_self_review','Review your explanation:')}</p>{[['connection',tr(t,'finale_check_connection','I connected the two lesson concepts.')],['evidence',tr(t,'finale_check_evidence','I used evidence from both selected locations.')],['purpose',tr(t,'finale_check_purpose','I explained how the construction helps the new team investigate.')]].map(([id,label])=><label className="lb-row" key={id}><input style={{width:'auto'}} type="checkbox" data-finale-check={id} checked={draft.checks[id]} onChange={event=>update({checks:{...draft.checks,[id]:event.target.checked}})}/><span style={{flex:'1 1 0',minWidth:0}}>{label}</span></label>)}</fieldset>
 <div className="lb-row"><button type="button" className="lb-primary" data-review-finale disabled={disabled} onClick={()=>{onChange({...draft,reviewed:true});setFocusFeedback(n=>n+1);}}>{tr(t,'finale_review','Review my plan')}</button><button type="button" data-download-readable-finale onClick={readable}>{tr(t,'finale_readable_download','Download readable plan')}</button><button type="button" data-download-finale onClick={download}>{tr(t,'finale_download_data','Download plan data (JSON)')}</button></div>
 {draft.reviewed&&<section data-finale-feedback><h4 ref={feedback} tabIndex={-1}>{review.complete?tr(t,'finale_finished','Your plan is ready to discuss'):tr(t,'finale_revise','Strengthen your plan')}</h4><p role="status">{review.complete?tr(t,'finale_success','Board rules and evidence choices checked. You have completed your self-review.'):tr(t,'finale_feedback_help','Use the feedback below, revise your choices, then review again.')}</p><ul><li>{review.rules?tr(t,'finale_rule_ok','Your selected effect matches the construction.'):project?tr(t,'finale_rule_fix','Revisit the construction effect: {effect}',{effect}):tr(t,'finale_project_missing','Choose a completed construction and its effect.')}</li><li>{review.connections?tr(t,'finale_connection_ok','Your evidence covers two different lesson concepts.'):tr(t,'finale_connection_fix','Choose two explored locations with different concept labels.')}</li><li>{review.response?tr(t,'finale_response_ok','Your explanation is included or marked as explained.'):tr(t,'finale_response_fix','Write your plan, or explain it using your communication tools and mark it as explained.')}</li><li>{review.selfReview?tr(t,'finale_checks_ok','You checked your connection, evidence, and construction purpose.'):tr(t,'finale_checks_fix','Review your explanation against each of the three prompts before checking them.')}</li></ul><p className="lb-muted">{tr(t,'finale_feedback_scope','These checks verify the board rule and your selected evidence. The meaning of your explanation needs your own or your teacher’s review; it is not automatically graded.')}</p><p>{tr(t,'finale_discuss','Discuss: How would your investigation change if the team used a different construction?')}</p></section>}{error&&<p role="alert">{error}</p>}
 </> }</section>;
}
