import * as engine from './lesson_board_engine.js';
import { fingerprint, readLibrary, saveBoard, removeBoard, restoreSolo } from './lesson_board_storage.js';
import { BoardAuthoring } from './lesson_board_authoring.jsx';
import { BoardView, Styles, tr } from './lesson_board_ui.jsx';
import { useRoomDialog } from './connected_escape_room_accessibility.jsx';
const React = window.React;
const { useState, useEffect, useRef } = React;
const runtime = { locks: new Set(), listeners: new Set(), errors: new Map(), emit() { this.listeners.forEach(fn => fn()); } };
const connection = (appId, code) => { const fb = window.__alloFirebase || {}, db = fb.db || window.__alloShared?.db; if (!db || !fb.doc || !fb.updateDoc || !fb.getDoc || !appId || !code) throw Error('The live session connection is unavailable.'); return { fb, ref: fb.doc(db, 'artifacts', appId, 'public', 'data', 'sessions', code) }; };
const scopeOf = (appId, code, state) => [appId, code, state?.attemptId].join(':');
const runPatch = (state, patch) => Object.fromEntries(Object.entries(patch).map(([path, value]) => ['escapeRoomState.teamProgress.All.boardRuns.' + state.attemptId + '.' + path, value]));
const applyDocument = (data, patch) => engine.merge(data, patch);
const checkSize = data => { if (JSON.stringify(data).length > 76000) throw Error('This session is near its storage limit. End the board and start a fresh session before continuing.'); };
function useRuntime(scope) { const [, tick] = useState(0); useEffect(() => { const fn = () => tick(n => n + 1); runtime.listeners.add(fn); return () => runtime.listeners.delete(fn); }, []); return { busy: runtime.locks.has(scope), error: runtime.errors.get(scope) || '' }; }
function Confirmation({ title, message, confirm, onConfirm, onCancel, busy, t }) {
  const cancel = useRef(null), trigger = useRef(document.activeElement);
  useEffect(() => { cancel.current?.focus(); return () => { if (trigger.current?.isConnected) trigger.current.focus(); }; }, []);
  return <div className="lb-notice" role="group" aria-label={title} onKeyDown={event => { if (event.key === 'Escape' && !busy) { event.preventDefault(); event.stopPropagation(); onCancel(); } }}><h3>{title}</h3><p>{message}</p><div className="lb-row"><button type="button" disabled={busy} onClick={onConfirm}>{confirm}</button><button type="button" ref={cancel} disabled={busy} onClick={onCancel}>{tr(t, 'cancel', 'Cancel')}</button></div></div>;
}
export function LessonBoardSolo({ board, user, appId, onBack, preview = false, t }) {
  const storageKey = preview ? '' : 'allo-board-solo:' + appId + ':' + (user?.uid || 'local') + ':' + fingerprint(JSON.stringify(board));
  const [initial] = useState(() => { try { return { run: preview ? engine.emptyRun() : restoreSolo(board, sessionStorage.getItem(storageKey)) }; } catch (error) { return { run: engine.emptyRun(), error: error.message }; } });
  const [run, setRun] = useState(initial.run), [error, setError] = useState(initial.error || ''), [storageError, setStorageError] = useState(''), [confirm, setConfirm] = useState(false), [reset, setReset] = useState(0);
  const update = next => { setRun(next); if (storageKey) try { sessionStorage.setItem(storageKey, JSON.stringify({ version: 1, board: JSON.stringify(board), run: next })); setStorageError(''); } catch (_) { setStorageError(tr(t, 'solo_storage', 'This game is available in memory, but progress could not be saved in this tab.')); } };
  const action = fn => { try { setError(''); update(fn(run)); } catch (error) { setError(error.message); } };
  const answer = value => action(current => { const req = { attemptId: 'solo', turn: current.turn, requestId: engine.identity('answer'), kind: 'answer', targetId: engine.stepOf(current).targetId, value }; const answered = engine.merge(current, engine.processAction(board, current, req, 'solo', { attemptId: 'solo', active: true })); return engine.merge(answered, engine.resolve(board, answered, { solo: {} })); });
  return <><div className="lb-row"><button type="button" onClick={onBack}>{tr(t, 'back_setup', 'Back to board setup')}</button><button type="button" onClick={() => setConfirm(true)}>{preview ? tr(t, 'reset_preview', 'Reset preview') : tr(t, 'restart_solo', 'Restart solo board')}</button><span>{preview ? tr(t, 'preview_label', 'Practice preview') : tr(t, 'solo_label', 'Solo · progress saved in this tab')}</span></div>{error && <p className="lb-notice" role="alert">{error}</p>}{storageError && <p className="lb-notice" role="status">{storageError}</p>}{initial.error && error && <button type="button" onClick={() => { setConfirm(true); }}>{tr(t, 'new_local', 'Start a new local game')}</button>}{confirm && <Confirmation t={t} title={tr(t, 'restart_title', 'Restart this board?')} message={tr(t, 'restart_solo_notice', 'This resets your local progress and unfinished settings. The board stays available.')} confirm={tr(t, 'reset_progress', 'Reset my progress')} onCancel={() => setConfirm(false)} onConfirm={() => { update(engine.emptyRun()); setError(''); if (storageKey) try { sessionStorage.removeItem(storageKey + ':draft'); } catch (_) {} setReset(n => n + 1); setConfirm(false); }}/>}<BoardView key={reset} board={board} run={run} busy={!!(initial.error && error) || confirm} roster={{ solo: {} }} workspaceKey={storageKey && storageKey + ':draft'} onMove={id => action(current => engine.merge(current, engine.begin(board, current, id)))} onAnswer={answer} onAdvance={() => action(current => engine.merge(current, engine.advance(board, current)))} t={t}/></>;
}
export function LessonBoardSetup({ inputText, generatedContent, language = 'English', callGemini, user, appId, activeSessionCode, sessionData, allowLive = true, onClose, onLaunched, t }) {
  const source = engine.sourceText(inputText, generatedContent), scope = language + ':' + source, dialog = useRef(null), closeRef = useRef(onClose), scopeRef = useRef(scope), request = useRef(0), generationBusy = useRef(null), mounted = useRef(true);
  closeRef.current = onClose; scopeRef.current = scope; useRoomDialog(dialog, closeRef);
  const [board, setBoard] = useState(null), [library, setLibrary] = useState([]), [stage, setStage] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [theme, setTheme] = useState(''), [level, setLevel] = useState(''), [playing, setPlaying] = useState(''), [choice, setChoice] = useState(null);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; request.current++; }; }, []);
  useEffect(() => { request.current++; setStage(''); setError(''); setNotice(''); setBoard(null); setLibrary([]); setPlaying(''); setChoice(null); try { const saved = readLibrary(localStorage, source, language); setLibrary(saved); setBoard(saved[0] || null); } catch (error) { setError(error.message); } }, [scope]);
  const generate = async () => { if (stage || choice || generationBusy.current?.scope === scope) return; const id = ++request.current, started = scope; generationBusy.current = { id, scope }; setError(''); setNotice(''); try { const next = await engine.generateBoard(callGemini, source, { language, theme, level, seed: engine.identity('variation') }, stage => { if (mounted.current && request.current === id) setStage(stage); }); if (mounted.current && request.current === id && scopeRef.current === started) setBoard(next); } catch (error) { if (mounted.current && request.current === id) setError(error.message); } finally { if (generationBusy.current?.id === id) generationBusy.current = null; if (mounted.current && request.current === id) setStage(''); } };
  const save = () => { try { const next = saveBoard(localStorage, source, language, board); setLibrary(next); setNotice(tr(t, 'saved', 'Board saved in this browser.')); setError(''); } catch (error) { setError(error.message); } };
  const play = type => { try { engine.prepareBoard(board, source); if (type === 'solo') setLibrary(saveBoard(localStorage, source, language, board)); setError(''); setPlaying(type); } catch (error) { setError(error.message); } };
  const launch = async () => {
    if (stage || choice) return; setStage('launching'); setError(''); const id = ++request.current, started = scope;
    try { const mailboxVersion = window.__alloLessonBoardMailboxVersion?.(); if (mailboxVersion !== null && mailboxVersion !== undefined && mailboxVersion < 21) throw Error('Update your Class Mailbox script to version 21 or later in Live Sessions setup before launching a board.'); const valid = engine.prepareBoard(board, source), { fb, ref } = connection(appId, activeSessionCode), snapshot = await fb.getDoc(ref), latest = snapshot.data();
      if (!mounted.current || request.current !== id || scopeRef.current !== started) return;
      if (!latest) throw Error('The live session is no longer available.'); if (latest.escapeRoomState?.isActive || latest.quizState?.isActive) throw Error('End the current live activity before launching this board.');
      setLibrary(saveBoard(localStorage, source, language, valid)); const next = engine.createSession(valid, user?.uid, latest.roster || {}); checkSize({ ...latest, escapeRoomState: next }); await fb.updateDoc(ref, { escapeRoomState: next }); if (mounted.current && request.current === id) { onLaunched?.(); onClose?.(); }
    } catch (error) { if (mounted.current && request.current === id) setError(error.message); } finally { if (mounted.current && request.current === id) setStage(''); }
  };
  return <div className="lb-backdrop"><section className="lb lb-dialog" data-theme={board?.theme} ref={dialog} role="dialog" aria-modal="true" aria-label={tr(t, 'title', 'Lesson board game')} tabIndex={-1}><Styles/><div className="lb-row lb-between"><h2>{tr(t, 'title', 'Lesson board game')}</h2><button type="button" onClick={onClose}>{tr(t, 'close', 'Close')}</button></div>{playing && board ? <LessonBoardSolo key={JSON.stringify(board)} board={board} user={user} appId={appId} preview={playing === 'preview'} t={t} onBack={() => { setPlaying(''); setTimeout(() => dialog.current?.querySelector('[data-board-play-solo]')?.focus(), 0); }}/> : <>
    <p>{tr(t, 'intro', 'Generate a lesson-based board, explore its activities, and build useful projects. Play solo or share one cooperative board with your class.')}</p><p>{tr(t, 'language', 'Board language: {language}', { language })}</p><details><summary>{tr(t, 'source', 'Lesson source')}</summary><blockquote>{source || tr(t, 'need_source', 'Add lesson text or generate a quiz first.')}</blockquote></details>
    {error && <p className="lb-notice" role="alert">{error}</p>}<p role="status">{stage === 'generating' ? tr(t, 'generating', 'Creating the board and lesson activities…') : stage === 'repairing' ? tr(t, 'repairing', 'Repairing paths, activities, or resource balance…') : stage === 'launching' ? tr(t, 'launching', 'Launching the shared board…') : notice}</p>
    <div className="lb-form"><label>{tr(t, 'theme', 'Setting preference (optional)')}<input value={theme} maxLength={150} disabled={!!stage || !!choice} onChange={e => setTheme(e.target.value)}/></label><label>{tr(t, 'level', 'Learner level (optional)')}<input value={level} maxLength={80} disabled={!!stage || !!choice} onChange={e => setLevel(e.target.value)}/></label></div><button type="button" className="lb-primary" data-generate-board disabled={!!stage || !!choice || source.length < 40} onClick={generate}>{board ? tr(t, 'generate_another', 'Generate another board') : tr(t, 'generate', 'Generate lesson board')}</button>
    {library.length > 0 && <details><summary>{tr(t, 'saved_boards', 'Saved boards for this lesson')} ({library.length}/4)</summary>{library.map((saved, index) => <div className="lb-row" key={index}><span>{saved.title}</span><button type="button" disabled={!!stage || !!choice} onClick={() => setChoice({ kind: 'open', index })}>{tr(t, 'open_saved', 'Open saved board')}</button><button type="button" disabled={!!stage || !!choice} onClick={() => setChoice({ kind: 'remove', index })}>{tr(t, 'remove_saved', 'Remove saved board')}</button></div>)}</details>}
    {choice && <Confirmation t={t} title={choice.kind === 'open' ? tr(t, 'open_saved', 'Open saved board') : tr(t, 'remove_saved', 'Remove saved board')} message={choice.kind === 'open' ? tr(t, 'replace_notice', 'Replace the current preview and any unsaved edits with {name}?', { name: library[choice.index]?.title }) : tr(t, 'remove_notice', 'Remove {name} from this browser library? The current preview stays available.', { name: library[choice.index]?.title })} confirm={choice.kind === 'open' ? tr(t, 'replace_preview', 'Replace preview') : tr(t, 'remove_saved', 'Remove saved board')} onCancel={() => setChoice(null)} onConfirm={() => { try { if (choice.kind === 'open') setBoard(library[choice.index]); else setLibrary(removeBoard(localStorage, source, language, choice.index)); setChoice(null); setError(''); } catch (error) { setError(error.message); } }}/>}
    {board && <><section className="lb-panel" style={{ marginTop: 18 }}><h3>{board.title}</h3><p>{board.mission}</p><p>{tr(t, 'overview', '{locations} locations · {concepts} concepts · three projects to choose from', { locations: board.locations.length, concepts: board.concepts.length })}</p><div className="lb-row"><button type="button" disabled={!!stage || !!choice} onClick={() => play('preview')}>{tr(t, 'try_board', 'Try the board')}</button><button type="button" data-board-play-solo disabled={!!stage || !!choice} onClick={() => play('solo')}>{tr(t, 'play_solo', 'Play solo')}</button><button type="button" disabled={!!stage || !!choice} onClick={save}>{tr(t, 'save_board', 'Save board')}</button>{allowLive && activeSessionCode && <button type="button" className="lb-primary" data-launch-board disabled={!!stage || !!choice || sessionData?.escapeRoomState?.isActive || sessionData?.quizState?.isActive} onClick={launch}>{tr(t, 'launch', 'Launch for everyone')}</button>}</div><p className="lb-muted">{tr(t, 'review_guidance', 'Check the activities, solutions and constructions before play. Connection and balance checks do not establish factual accuracy.')}</p>{allowLive && activeSessionCode && <p className="lb-muted">{tr(t, 'host_required', 'Keep the teacher session open and connected during live play. The teacher chooses moves and resolves activities after learners respond.')}</p>}</section>
      <BoardAuthoring board={board} source={source} disabled={!!stage || !!choice} t={t} onChange={next => { setNotice(''); setError(''); setBoard(next); }}/>
    </>}
  </>}</section></div>;
}
export function LessonBoardHost({ sessionData, activeSessionCode, appId }) {
  const state = sessionData?.escapeRoomState, scope = scopeOf(appId, activeSessionCode, state), [retry, setRetry] = useState(0), current = useRef({ state, sessionData }); current.current = { state, sessionData };
  useRuntime(scope);
  useEffect(() => { if (state?.mode !== 'lesson-board' || !state.isActive || runtime.locks.has(scope) || engine.validateBoard(state.board).length) return;
    const run = engine.runOf(state), step = engine.stepOf(run), requests = Object.entries(state.teamProgress?.All?.boardActions || {}).filter(([uid, action]) => Object.prototype.hasOwnProperty.call(sessionData.roster || {}, uid) && state.teams?.[uid] === 'All' && engine.validAction(action, state.attemptId, run.turn) && step.seen?.[uid]?.requestId !== action.requestId).slice(0, 16);
    if (!requests.length) return; let next = run, patch = {}; for (const [uid, action] of requests) { const planned = engine.processAction(state.board, next, action, uid, { attemptId: state.attemptId, active: state.isActive, paused: state.isPaused }); next = engine.merge(next, planned); Object.assign(patch, planned); }
    if (!Object.keys(patch).length) return; runtime.locks.add(scope); runtime.emit();
    (async () => { try { const { fb, ref } = connection(appId, activeSessionCode), update = runPatch(state, patch); checkSize(applyDocument(sessionData, update)); await fb.updateDoc(ref, update); runtime.errors.delete(scope); } catch (error) { runtime.errors.set(scope, error.message || 'Actions are waiting for confirmation.'); } finally { runtime.locks.delete(scope); runtime.emit(); } })();
  }, [state, sessionData?.roster, retry, scope]);
  useEffect(() => { const timer = setInterval(() => setRetry(n => n + 1), 5000); return () => clearInterval(timer); }, [scope]);
  return null;
}
export function LessonBoardStudent({ sessionData, user, targetAppId, activeSessionCode, t }) {
  const state = sessionData?.escapeRoomState, run = engine.runOf(state), scope = scopeOf(targetAppId, activeSessionCode, state) + ':' + user?.uid, storageKey = 'allo-board-pending:' + scope;
  const [pending, setPending] = useState(null), pendingRef = useRef(null), sendRef = useRef(null), scopeRef = useRef(scope), mounted = useRef(true), [sending, setSending] = useState(false), [slow, setSlow] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [joining, setJoining] = useState(false), joinRef = useRef(null), [pendingSaved, setPendingSaved] = useState(true); scopeRef.current = scope;
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => { pendingRef.current = null; sendRef.current = null; if (joinRef.current?.scope !== scope) joinRef.current = null; setJoining(!!joinRef.current); setPendingSaved(true); setPending(null); setSending(false); setError(''); setNotice(''); try { const raw = sessionStorage.getItem(storageKey); if (raw && raw.length < 1000) { const action = JSON.parse(raw); if (engine.validAction(action, state.attemptId, run.turn)) { pendingRef.current = action; setPending(action); } else sessionStorage.removeItem(storageKey); } } catch (_) {} }, [scope]);
  const join = async () => { if (!user?.uid || joinRef.current?.scope === scope) return; const started = scope, ticket = { scope }; joinRef.current = ticket; setJoining(true); try { const { fb, ref } = connection(targetAppId, activeSessionCode); await fb.updateDoc(ref, { ['escapeRoomState.teams.' + user.uid]: 'All' }); } catch (_) { if (mounted.current && scopeRef.current === started) setError(tr(t, 'join_failed', 'Could not join the board. Retry when connected.')); } finally { if (joinRef.current === ticket) { joinRef.current = null; if (mounted.current && scopeRef.current === started) setJoining(false); } } };
  useEffect(() => { if (user?.uid && state?.mode === 'lesson-board' && state.isActive && state.teams?.[user.uid] !== 'All') join(); }, [scope, state?.isActive]);
  const clearPending = message => { pendingRef.current = null; sendRef.current = null; setPending(null); setSending(false); setNotice(message); setError(''); try { sessionStorage.removeItem(storageKey); } catch (_) {} };
  const receipt = engine.stepOf(run).seen?.[user?.uid];
  useEffect(() => { if (!pending) return; if (receipt?.requestId === pending.requestId) clearPending(receipt.code === 'vote-recorded' ? tr(t, 'proposal_recorded', 'Your proposal is confirmed.') : ['answer-recorded', 'already-answered'].includes(receipt.code) ? tr(t, 'answer_recorded', 'Your response is confirmed. Wait for the shared review.') : tr(t, 'window_closed', 'This action window has closed. Review the current move.')); else if (pending.turn !== run.turn || (pending.kind === 'vote' ? engine.stepOf(run).phase !== 'choose' : engine.stepOf(run).phase !== 'answer' || pending.targetId !== engine.stepOf(run).targetId)) clearPending(tr(t, 'moved_on', 'The teacher advanced the board. Review the current move before responding again.')); }, [pending, receipt, run.turn, engine.stepOf(run).phase, engine.stepOf(run).targetId]);
  useEffect(() => { setSlow(false); if (!pending) return; const timer = setTimeout(() => setSlow(true), 10000); return () => clearTimeout(timer); }, [pending?.requestId]);
  const transmit = async action => { if (sendRef.current || pendingRef.current?.requestId !== action.requestId) return; const started = scope, ticket = {}; sendRef.current = ticket; setSending(true); setError(''); try { const { fb, ref } = connection(targetAppId, activeSessionCode); await fb.updateDoc(ref, { ['escapeRoomState.teamProgress.All.boardActions.' + user.uid]: action }); } catch (_) { if (mounted.current && scopeRef.current === started && pendingRef.current?.requestId === action.requestId) setError(tr(t, 'send_failed', 'The action could not be sent. Your response is kept; retry when connected.')); } finally { if (sendRef.current === ticket) { sendRef.current = null; if (mounted.current && scopeRef.current === started) setSending(false); } } };
  const action = (kind, targetId, value = '') => { if (!user?.uid || pendingRef.current || state.isPaused || !state.isActive || state.teams?.[user?.uid] !== 'All') return; const next = { attemptId: state.attemptId, turn: run.turn, requestId: engine.identity('move'), kind, targetId, value }; pendingRef.current = next; setPending(next); setNotice(''); try { sessionStorage.setItem(storageKey, JSON.stringify(next)); setPendingSaved(true); } catch (_) { setPendingSaved(false); } transmit(next); };
  if (state?.mode !== 'lesson-board' || !state.isActive) return null;
  if (!user?.uid) return <div className="lb lb-overlay"><Styles/><p role="status">{tr(t, 'waiting_identity', 'Waiting for your live session connection…')}</p></div>;
  if (engine.validateBoard(state.board).length) return <div className="lb lb-overlay"><Styles/><p role="alert">{tr(t, 'invalid', 'This board could not be opened. Ask the teacher to regenerate it.')}</p></div>;
  return <div className="lb lb-overlay" data-theme={state.board.theme} role="region" aria-label={tr(t, 'live_board', 'Cooperative lesson board')}><Styles/><div className="lb-shell">{state.teams?.[user?.uid] !== 'All' && <button type="button" disabled={joining} onClick={join}>{tr(t, 'join_board', 'Join shared board')}</button>}{error && <p className="lb-notice" role="alert">{error}</p>}{pending && <div className="lb-notice" data-board-pending role="status"><p>{sending ? tr(t, 'sending', 'Sending your action…') : tr(t, 'waiting', 'Waiting for teacher confirmation. Keep this page open.')}</p>{!pendingSaved && <p>{tr(t, 'pending_not_saved', 'Browser storage is unavailable. Keep this page open until confirmation; a reload may lose this pending action.')}</p>}{(slow || error || !sending) && <button type="button" aria-disabled={sending || state.isPaused} onClick={() => { if (!sending && !state.isPaused) transmit(pending); }}>{tr(t, 'retry_action', 'Retry this action')}</button>}</div>}<BoardView key={scope} board={state.board} run={run} role="student" uid={user.uid} roster={sessionData.roster} pending={pending} paused={state.isPaused} busy={state.teams?.[user?.uid] !== 'All'} notice={notice} workspaceKey={'allo-board-draft:' + scope} t={t} onMove={id => action('vote', id)} onAnswer={value => action('answer', engine.stepOf(run).targetId, value)}/></div></div>;
}
export function LessonBoardTeacher({ sessionData, appId, activeSessionCode, t }) {
  const state = sessionData?.escapeRoomState, scope = scopeOf(appId, activeSessionCode, state), run = engine.runOf(state), { busy, error: hostError } = useRuntime(scope), [error, setError] = useState(''), [confirm, setConfirm] = useState(''), current = useRef({ state, run, sessionData }), mounted = useRef(true); current.current = { state, run, sessionData };
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => { setError(''); setConfirm(''); }, [scope]);
  const commit = async kind => {
    if (runtime.locks.has(scope)) return; runtime.locks.add(scope); runtime.emit(); setError('');
    try { const { fb, ref } = connection(appId, activeSessionCode), latest = (await fb.getDoc(ref)).data(), fresh = latest?.escapeRoomState;
      if (!fresh || fresh.mode !== 'lesson-board' || fresh.attemptId !== state.attemptId || !fresh.isActive) throw Error('This board has changed. Review the current session.');
      const freshRun = engine.runOf(fresh); if (freshRun.turn !== run.turn || engine.stepOf(freshRun).phase !== engine.stepOf(run).phase) throw Error('The teacher already advanced this move.');
      let patch;
      if (kind === 'pause') patch = { 'escapeRoomState.isPaused': !fresh.isPaused };
      else if (kind === 'end') patch = { 'escapeRoomState.isActive': false, 'escapeRoomState.isGameOver': true };
      else if (kind === 'restart') patch = { escapeRoomState: engine.createSession(fresh.board, fresh.hostId, latest.roster) };
      else { if (fresh.isPaused) throw Error('Resume the board before choosing a move.'); const changes = kind === 'resolve' ? engine.resolve(fresh.board, freshRun, latest.roster) : kind === 'next' ? engine.advance(fresh.board, freshRun) : engine.begin(fresh.board, freshRun, kind.move); patch = runPatch(fresh, changes); }
      checkSize(applyDocument(latest, patch)); await fb.updateDoc(ref, patch); if (mounted.current && current.current.state?.attemptId === state.attemptId) setConfirm('');
    } catch (error) { if (mounted.current && current.current.state?.attemptId === state.attemptId) setError(error.message); } finally { runtime.locks.delete(scope); runtime.emit(); }
  };
  if (state?.mode !== 'lesson-board' || !state.isActive) return null;
  if (engine.validateBoard(state.board).length) return <p role="alert">{tr(t, 'invalid', 'This board could not be opened. Ask the teacher to regenerate it.')}</p>;
  return <section className="lb lb-panel" data-theme={state.board.theme} aria-label={tr(t, 'teacher_controls', 'Lesson board teacher controls')}><Styles/><LessonBoardHost sessionData={sessionData} appId={appId} activeSessionCode={activeSessionCode}/><div className="lb-row"><button type="button" disabled={busy || !!confirm} onClick={() => commit('pause')}>{state.isPaused ? tr(t, 'resume', 'Resume board') : tr(t, 'pause', 'Pause board')}</button><button type="button" disabled={busy || !!confirm} onClick={() => setConfirm('restart')}>{tr(t, 'restart', 'Restart shared board')}</button><button type="button" disabled={busy || !!confirm} onClick={() => setConfirm('end')}>{tr(t, 'end', 'End board')}</button></div><p className="lb-muted">{tr(t, 'host_required', 'Keep the teacher session open and connected during live play. The teacher chooses moves and resolves activities after learners respond.')}</p>{(error || hostError) && <p role="alert" className="lb-notice">{error || hostError}</p>}{confirm && <Confirmation busy={busy} t={t} title={confirm === 'restart' ? tr(t, 'restart_title', 'Restart this board?') : tr(t, 'end_title', 'End the shared board?')} message={confirm === 'restart' ? tr(t, 'restart_live_notice', 'Everyone starts again with no explored locations, constructed projects, or responses. The generated board stays the same.') : tr(t, 'end_notice', 'This closes the board for everyone. Review the learning before ending.')} confirm={confirm === 'restart' ? tr(t, 'restart_everyone', 'Restart for everyone') : tr(t, 'end_everyone', 'End for everyone')} onCancel={() => setConfirm('')} onConfirm={() => commit(confirm)}/>}<BoardView key={scope} board={state.board} run={run} role="teacher" roster={sessionData.roster || {}} busy={busy || !!confirm} paused={state.isPaused} onMove={id => commit({ move: id })} onResolve={() => commit('resolve')} onAdvance={() => commit('next')} t={t}/></section>;
}
window.AlloModules = window.AlloModules || {};
window.AlloModules.LessonBoardModule = true;
window.AlloModules.LessonBoardEngine = engine;
window.AlloModules.LessonBoardSetup = LessonBoardSetup;
window.AlloModules.LessonBoardSolo = LessonBoardSolo;
window.AlloModules.LessonBoardHost = LessonBoardHost;
window.AlloModules.LessonBoardStudent = LessonBoardStudent;
window.AlloModules.LessonBoardTeacher = LessonBoardTeacher;
