// Shared, deterministic guidance. No network, storage, identities or mutations.
// Embedded locally in the School Rewards panel and both AlloBot modules.
function createSchoolStoreSetupGuide() {
  const paths = [
    { id: 'practice', title: 'Try the demo', intro: 'Explore with fictional data. No Google setup or real student records are needed.', steps: [
      { id: 'understand', title: 'Start with fictional data', body: 'Practice uses simulated accounts, balances and delivery. It does not connect to a school ledger. The separate local guided demo also needs its presentation server running.', target: 'practice', manualHash: 'quickstart' },
      { id: 'try', title: 'Try an award and a purchase', body: 'Open practice, use its fictional roles, review the learner, award points and complete a reviewed checkout. Reset to rehearse again. No real email or printer command is sent.', target: 'practice', manualHash: 'store' }
    ] },
    { id: 'join', title: 'Join my school’s existing Store', intro: 'For teachers and cashiers: use the Store your school has already approved. You do not need to create an Apps Script project.', steps: [
      { id: 'link', title: 'Get the approved Store link', body: 'Ask your school administrator for the managed Store web-app address ending in /exec and confirm that they have granted your staff or cashier role. Do not put the address, credentials or student details in chat.', target: 'connection', manualHash: 'setup' },
      { id: 'save', title: 'Save the address on this device', body: 'Paste the approved address into the Store connection field and choose Save address. If you edit a saved address, save or discard the change before opening the Store. Only Disconnect removes the saved address. Saving does not sign you in, grant access or verify the deployment.', target: 'connection', manualHash: 'setup' },
      { id: 'open', title: 'Open your school’s Store', body: 'Open the Store with your own managed school Google account. An opening attempt is not proof that the tab opened or that access was granted. If no tab appears, use the direct fallback link. If access is denied, ask the administrator rather than creating another Store. More local tips are under Help opening your Store.', target: 'launch', manualHash: 'access' },
      { id: 'check', title: 'Confirm your school and role', body: 'Open the deployment check and read its result. Confirm the expected school and role with the administrator. AlloBot cannot see or certify that separate Google page. Teachers award; cashiers check out; students see only their own records.', target: 'check', manualHash: 'troubleshooting' }
    ] },
    { id: 'setup', title: 'Set up a Store for my school', intro: 'For the school administrator or technology coordinator. This is a reviewed school-wide setup, not something every teacher repeats.', steps: [
      { id: 'approval', title: 'Confirm district review and ownership', body: 'Identify the managed account and technical owner. Obtain district review of the code, requested permissions, storage, email and retention. Stop and consult IT if Google or district policy blocks access; do not bypass a warning.', target: 'approval', manualHash: 'privacy' },
      { id: 'handoff', title: 'Choose who will do the technical work', body: 'The technology coordinator can use the existing handoff packet. Enter school configuration only in the setup form, not in AlloBot. The packet contains configuration and source files and should go to the intended coordinator.', target: 'handoff', manualHash: 'setup' },
      { id: 'files', title: 'Prepare the reviewed project files', body: 'Follow the existing checklist for Code.gs, Portal.html, Index.html and appsscript.json. Copying a file or ticking a box does not verify the installed project. Have the technical owner check the actual files.', target: 'files', manualHash: 'setup' },
      { id: 'configuration', title: 'Run the reviewed one-time setup', body: 'Check the school configuration and managed account. The technical owner runs the generated setup function only after approval and verifies its result. AlloBot does not execute it or approve Google permissions.', target: 'configuration', manualHash: 'setup' },
      { id: 'deploy', title: 'Deploy privately and save the link', body: 'Use the domain-restricted deployment described in the checklist, never public access. Save its /exec address locally. Source changes require a new reviewed deployment version; saving a URL does not publish code.', target: 'deploy', manualHash: 'setup' },
      { id: 'verify', title: 'Verify with approved test accounts', body: 'Read the deployment check and test each intended role with approved test accounts and fictional records. A recorded verification checkbox is your confirmation, not automatic evidence from AlloBot.', target: 'check', manualHash: 'setup' },
      { id: 'first-week', title: 'Finish the Store’s first-week checklist', body: 'Inside the signed-in Store, use Admin setup for staff, roster, categories, prizes and shopping windows. Add optional class links, Classroom imports or Print Lab only after their own review. Educator Evaluation remains separate.', target: 'launch', manualHash: 'admin' }
    ] }
  ];
  const troubleshooting = [
    { id: 'new-tab', title: 'Nothing opened in a new tab', body: 'An opening request is not confirmation that a new tab appeared. Check your other tabs, then use the direct fallback link shown after your attempt. If your browser or district blocks it, ask your technology coordinator about the approved browser settings. Do not bypass a Google or district security warning.', manualHash: 'troubleshooting' },
    { id: 'sign-in', title: 'Google asks me to sign in', body: 'Use your own managed school Google account and the school-approved Store link. Being signed into Gemini or a personal Google account does not grant Store access. If the wrong account appears, use the account-switching method approved by your school; do not share passwords or accounts.', manualHash: 'access' },
    { id: 'role-access', title: 'I can sign in, but access is denied', body: 'Ask the Store administrator to confirm the approved deployment, allowed school domain and your assigned role. A teacher or cashier needs the corresponding staff access; students use their own managed identity. The launcher cannot grant a role, and creating another Store will not fix access to the existing one.', manualHash: 'troubleshooting' },
    { id: 'address', title: 'My Store link will not save, or looks wrong', body: 'Ask the administrator for the approved HTTPS script.google.com deployment address ending in /macros/s/{deployment}/exec, without extra query parameters or a fragment. Do not use the editor address or a /dev test link. An edited address must be saved or discarded before launching. The saved-address badge does not verify which school is behind the link.', manualHash: 'setup' },
    { id: 'connections', title: 'Which Google connection do I need?', body: 'The school-managed Store has its own sign-in and staff roles. Classroom authorization is a separate read-only roster import and does not grant Store access. Canvas and desktop launch the Store; they do not hold its official ledger. Educator Evaluation has separate personnel records and permissions. A Clever launch link does not replace these approvals.', manualHash: 'classroom' }
  ];
  function freeze(value) { if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); } return value; }
  freeze(paths);
  freeze(troubleshooting);
  return Object.freeze({ version: 1, getPaths: () => paths, getPath: id => paths.find(path => path.id === id) || null, getTroubleshooting: () => troubleshooting });
}
if (typeof module !== 'undefined' && module.exports) module.exports = { createSchoolStoreSetupGuide };
