/**
 * AlloFlow Walkthrough Copilot Module
 *
 * Auto-generated by _build_walkthrough_copilot_module.js - DO NOT EDIT MANUALLY.
 * Source: walkthrough_copilot_source.jsx
 * Bundled logic: walkthrough_copilot_module.js, walkthrough_copilot_fixtures.js,
 *                walkthrough_copilot_scenarios.js
 *
 * Formative walkthrough and coaching support. Turns shorthand observation notes
 * into evidence-based coaching feedback the observer writes and approves. Never
 * assigns a rating, calculates a summative score, or makes an employment
 * recommendation. Practice scenarios are synthetic and ship their own
 * suggestions, so no AI provider is contacted.
 */
(function() {
  'use strict';
  if (window.AlloModules && window.AlloModules.WalkthroughCopilot
      && window.AlloModules.WalkthroughCopilot.WalkthroughCopilotPanel) {
    console.log('[CDN] WalkthroughCopilot already loaded, skipping');
    return;
  }
  (function() {
    if (document.getElementById('allo-live-wcop')) return;
    var liveRegion = document.createElement('div');
    liveRegion.id = 'allo-live-wcop';
    liveRegion.setAttribute('aria-live', 'polite');
    liveRegion.setAttribute('aria-atomic', 'true');
    liveRegion.setAttribute('role', 'status');
    liveRegion.className = 'sr-only';
    liveRegion.style.cssText = 'position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);border:0';
    document.body.appendChild(liveRegion);
  })();

/* bundled from walkthrough_copilot_module.js */
/*
 * AlloFlow Walkthrough Copilot - headless note-analysis core.
 *
 * Formative walkthrough and coaching support only. This module never assigns a
 * rating, never calculates an annual or Act 13 score, and never makes an
 * employment recommendation. See CLAUDE_WALKTHROUGH_COPILOT_HANDOFF.md.
 *
 * The module owns the integrity boundary: it holds the observer's source notes
 * immutable, validates every model-proposed suggestion against them, separates
 * objective evidence from interpretation, and refuses to produce output until a
 * human has decided every suggestion. It knows nothing about React, Drive,
 * Apps Script, or a particular model provider. An adapter supplies suggestions;
 * this module decides whether they may be shown, approved, or exported.
 *
 * Two artifacts with opposite retention rules live here. The DRAFT (rejected
 * suggestions, confidence values, warnings) never leaves the session. The
 * RECORD (approved feedback) is what export produces. exportDraft deliberately
 * omits everything in the first category.
 *
 * Source is kept pure ASCII on disk; see the encoding notes in the handoff.
 */
(function () {
  'use strict';

  var CONTRACT_VERSION = '1.0';

  var MAX_NOTE_CHARS = 20000;
  var MAX_FIELD_CHARS = 4000;
  var MAX_SUGGESTIONS = 60;
  var MAX_SPANS_PER_SUGGESTION = 8;
  var MAX_DOMAINS = 12;
  var MAX_COMPONENTS = 120;

  var DECISIONS = ['pending', 'accepted', 'edited', 'rejected'];
  var MODES = ['demo', 'approved'];

  var DEMO_WATERMARK = 'DEMO DRAFT - synthetic content, not a record of any real observation.';

  var DEFAULT_DISCLOSURE =
    'Notes from this walkthrough were organized with AI assistance. '
    + 'The observer wrote, reviewed, and approved all feedback below.';
  var DEFAULT_FORMATIVE_SENTENCE =
    'This is formative coaching feedback and is not part of a summative evaluation.';

  // Fields a suggestion may never carry. The model must not be able to smuggle a
  // rating or an employment recommendation through an unexpected key.
  var FORBIDDEN_SUGGESTION_KEYS = [
    'rating', 'ratings', 'score', 'scores', 'performanceLevel', 'level',
    'summativeRating', 'effectivenessRating', 'recommendation', 'employment',
    'employmentRecommendation', 'act13', 'annualRating', 'rank', 'percentile'
  ];

  // Judgment language belongs in `interpretation`, never in `objectiveEvidence`.
  // This is a heuristic word list, so it is deliberately generous: a warning
  // costs a moment's thought, while a missed judgment ships as though it were
  // something the observer saw. The everyday appraisal words matter as much as
  // the formal ones, because shorthand notes are written in everyday language.
  var JUDGMENT_WORDS = [
    'effective', 'ineffective', 'excellent', 'poor', 'strong', 'weak',
    'engaged', 'disengaged', 'unprepared', 'prepared', 'professional',
    'unprofessional', 'rigorous', 'exemplary', 'inadequate', 'proficient',
    'skilled', 'unskilled', 'mastery', 'struggling',
    'great', 'wonderful', 'terrific', 'impressive', 'seamless', 'masterful',
    'flawless', 'chaotic', 'disorganized', 'enthusiastic', 'warm',
    'love', 'loves', 'clearly love'
  ];

  // Collective subjects that generalize beyond a single cited moment.
  var COLLECTIVE_TERMS = [
    'students', 'the class', 'everyone', 'all students', 'the students',
    'the whole class', 'every student', 'the group', 'they all'
  ];

  function isObject(value) {
    return !!value && typeof value === 'object' && !Array.isArray(value);
  }
  function isString(value) {
    return typeof value === 'string';
  }
  function isNonEmptyString(value) {
    return isString(value) && value.trim() !== '';
  }
  function error(code, path, message) {
    return { code: code, path: path, message: message };
  }
  function warning(code, path, message) {
    return { code: code, path: path, message: message };
  }
  function ok(value, warnings) {
    return { ok: true, errors: [], warnings: warnings || [], value: value };
  }
  function bad(errors, warnings) {
    return { ok: false, errors: errors || [], warnings: warnings || [], value: null };
  }
  function lower(value) {
    return isString(value) ? value.toLowerCase() : '';
  }
  function containsAny(haystack, needles) {
    var text = lower(haystack);
    for (var i = 0; i < needles.length; i += 1) {
      if (text.indexOf(needles[i]) !== -1) return needles[i];
    }
    return null;
  }
  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }
  function stamp(options) {
    if (options && isNonEmptyString(options.now)) return options.now;
    return new Date().toISOString();
  }

  /* ---------------------------------------------------------------------- *
   * Framework configuration
   *
   * Domain count and labels come from configuration. Nothing here assumes four
   * domains or Danielson's numbering, so a district using another model works
   * without a code change. Rubric performance-level text is deliberately not
   * part of this contract; districts supply their own.
   * ---------------------------------------------------------------------- */

  function validateFramework(framework) {
    var errors = [];
    if (!isObject(framework)) {
      return bad([error('framework-invalid', 'framework', 'A framework configuration object is required.')]);
    }
    if (!isNonEmptyString(framework.id)) {
      errors.push(error('framework-id', 'framework.id', 'The framework needs an id.'));
    }
    if (!Array.isArray(framework.domains) || framework.domains.length === 0) {
      errors.push(error('framework-domains', 'framework.domains', 'The framework needs at least one domain.'));
    } else if (framework.domains.length > MAX_DOMAINS) {
      errors.push(error('framework-domains', 'framework.domains', 'Too many domains in the framework configuration.'));
    }
    if (!Array.isArray(framework.components) || framework.components.length === 0) {
      errors.push(error('framework-components', 'framework.components', 'The framework needs at least one component.'));
    } else if (framework.components.length > MAX_COMPONENTS) {
      errors.push(error('framework-components', 'framework.components', 'Too many components in the framework configuration.'));
    }
    if (errors.length) return bad(errors);

    var domainIds = Object.create(null);
    framework.domains.forEach(function (domain, index) {
      if (!isObject(domain) || !isNonEmptyString(domain.id) || !isNonEmptyString(domain.label)) {
        errors.push(error('domain-invalid', 'framework.domains[' + index + ']', 'Each domain needs an id and a label.'));
        return;
      }
      if (domainIds[domain.id]) {
        errors.push(error('domain-duplicate', 'framework.domains[' + index + ']', 'Duplicate domain id ' + domain.id + '.'));
      }
      domainIds[domain.id] = true;
    });

    var componentIds = Object.create(null);
    framework.components.forEach(function (component, index) {
      if (!isObject(component) || !isNonEmptyString(component.id) || !isNonEmptyString(component.label)) {
        errors.push(error('component-invalid', 'framework.components[' + index + ']', 'Each component needs an id and a label.'));
        return;
      }
      if (componentIds[component.id]) {
        errors.push(error('component-duplicate', 'framework.components[' + index + ']', 'Duplicate component id ' + component.id + '.'));
      }
      componentIds[component.id] = true;
      if (!domainIds[component.domainId]) {
        errors.push(error('component-orphan', 'framework.components[' + index + ']', 'Component ' + component.id + ' references unknown domain ' + component.domainId + '.'));
      }
    });

    if (errors.length) return bad(errors);
    return ok({
      id: framework.id,
      label: isNonEmptyString(framework.label) ? framework.label : framework.id,
      domains: clone(framework.domains),
      components: clone(framework.components)
    });
  }

  /* ---------------------------------------------------------------------- *
   * Disclosure
   *
   * Disclosure is structural, not a preference. It may be reworded but never
   * emptied, and a blank disclosure blocks export.
   * ---------------------------------------------------------------------- */

  // "Not supplied" and "deliberately cleared" are different. An absent field is
  // initialization and takes the default. A field the user emptied is kept
  // empty, so export blocks and they are told why, rather than the default
  // silently reappearing under wording they meant to replace.
  function normalizeDisclosure(input) {
    var source = isObject(input) ? input : {};
    var supplied = typeof source.text !== 'undefined' && source.text !== null;
    var text = supplied ? String(source.text).trim() : DEFAULT_DISCLOSURE;

    var formativeSupplied = typeof source.formativeSentence !== 'undefined' && source.formativeSentence !== null;
    var formative = formativeSupplied ? String(source.formativeSentence).trim() : DEFAULT_FORMATIVE_SENTENCE;

    return {
      text: text,
      includeFormativeSentence: source.includeFormativeSentence !== false,
      formativeSentence: formative
    };
  }

  function disclosureLine(disclosure) {
    if (!isObject(disclosure) || !isNonEmptyString(disclosure.text)) return '';
    if (!disclosure.includeFormativeSentence || !isNonEmptyString(disclosure.formativeSentence)) {
      return disclosure.text;
    }
    return disclosure.text + ' ' + disclosure.formativeSentence;
  }

  /* ---------------------------------------------------------------------- *
   * Draft lifecycle
   * ---------------------------------------------------------------------- */

  function createDraft(input, options) {
    var source = isObject(input) ? input : {};
    var errors = [];

    var frameworkReport = validateFramework(source.framework);
    if (!frameworkReport.ok) return frameworkReport;

    if (!isNonEmptyString(source.sourceNotes)) {
      errors.push(error('notes-empty', 'sourceNotes', 'Enter observation notes before analyzing.'));
    } else if (source.sourceNotes.length > MAX_NOTE_CHARS) {
      errors.push(error('notes-long', 'sourceNotes', 'These notes are too long to analyze in one draft.'));
    }

    var mode = isNonEmptyString(source.mode) ? source.mode : 'demo';
    if (DECISIONS.indexOf(mode) !== -1 || MODES.indexOf(mode) === -1) {
      if (MODES.indexOf(mode) === -1) {
        errors.push(error('mode-invalid', 'mode', 'Mode must be demo or approved.'));
      }
    }
    if (mode === 'approved') {
      var approval = source.approval;
      if (!isObject(approval) || approval.providerApproved !== true || approval.scopeConfirmed !== true
        || !isNonEmptyString(approval.affirmedBy)) {
        errors.push(error('approval-missing', 'approval',
          'Approved mode requires an affirmation naming who approved the provider and the formative scope.'));
      }
    }

    if (errors.length) return bad(errors);

    var at = stamp(options);
    var draft = {
      contractVersion: CONTRACT_VERSION,
      id: isNonEmptyString(source.id) ? source.id : 'walkthrough-draft',
      createdAt: at,
      mode: mode,
      approval: mode === 'approved'
        ? {
          affirmedAt: at,
          affirmedBy: source.approval.affirmedBy,
          providerApproved: true,
          scopeConfirmed: true
        }
        : null,
      framework: frameworkReport.value,
      disclosure: normalizeDisclosure(source.disclosure),
      sourceNotesOriginal: source.sourceNotes,
      sourceNotesFrozenAt: at,
      context: isObject(source.context) ? clone(source.context) : {},
      collectionType: isNonEmptyString(source.collectionType) ? source.collectionType : 'unspecified',
      suggestions: [],
      globalWarnings: [],
      principalApproval: { approvedAt: null, approvedSuggestionIds: [] }
    };
    return ok(draft);
  }

  /* ---------------------------------------------------------------------- *
   * Suggestion validation
   *
   * A suggestion may only survive if every claim traces to an exact span of the
   * frozen notes. Offsets are verified against the note text itself, so a model
   * cannot invent a quotation that merely looks plausible.
   * ---------------------------------------------------------------------- */

  function validateSpan(notes, span, path, errors) {
    if (!isObject(span)) {
      errors.push(error('span-invalid', path, 'Each source span must be an object.'));
      return false;
    }
    var start = span.start;
    var end = span.end;
    if (typeof start !== 'number' || typeof end !== 'number'
      || !isFinite(start) || !isFinite(end)
      || start < 0 || end <= start || end > notes.length) {
      errors.push(error('span-range', path, 'Source span offsets fall outside the observation notes.'));
      return false;
    }
    if (!isString(span.text)) {
      errors.push(error('span-text', path, 'Each source span must quote the note text it refers to.'));
      return false;
    }
    if (notes.slice(start, end) !== span.text) {
      errors.push(error('span-mismatch', path,
        'A cited excerpt does not match the observation notes exactly. The suggestion was not shown.'));
      return false;
    }
    return true;
  }

  function detectForbiddenKeys(suggestion, path, errors) {
    Object.keys(suggestion).forEach(function (key) {
      if (FORBIDDEN_SUGGESTION_KEYS.indexOf(key) !== -1) {
        errors.push(error('field-forbidden', path + '.' + key,
          'A suggestion may not carry a rating, score, or employment recommendation.'));
      }
    });
  }

  function suggestionWarnings(suggestion, path) {
    var warnings = [];
    var judgment = containsAny(suggestion.objectiveEvidence, JUDGMENT_WORDS);
    if (judgment) {
      warnings.push(warning('evidence-judgment', path + '.objectiveEvidence',
        'The word "' + judgment + '" is a judgment. Move it to interpretation or restate what was observed.'));
    }
    var collective = containsAny(suggestion.interpretation, COLLECTIVE_TERMS)
      || containsAny(suggestion.objectiveEvidence, COLLECTIVE_TERMS);
    if (collective && suggestion.sourceSpans.length < 2) {
      warnings.push(warning('generalization-unsupported', path,
        'This describes "' + collective + '" but cites a single moment. Add evidence or narrow the claim.'));
    }
    if (!isNonEmptyString(suggestion.interpretation)) {
      warnings.push(warning('interpretation-absent', path + '.interpretation',
        'No interpretation was offered, so this stands as evidence only.'));
    }
    return warnings;
  }

  function validateSuggestions(draft, rawSuggestions) {
    if (!isObject(draft) || !isString(draft.sourceNotesOriginal)) {
      return bad([error('draft-invalid', 'draft', 'A frozen draft is required before suggestions can be validated.')]);
    }
    if (!Array.isArray(rawSuggestions)) {
      return bad([error('suggestions-invalid', 'suggestions', 'Suggestions must be provided as a list.')]);
    }
    if (rawSuggestions.length > MAX_SUGGESTIONS) {
      return bad([error('suggestions-many', 'suggestions', 'Too many suggestions were returned to review reliably.')]);
    }

    var notes = draft.sourceNotesOriginal;
    var componentIndex = Object.create(null);
    draft.framework.components.forEach(function (component) {
      componentIndex[component.id] = component;
    });

    var errors = [];
    var warnings = [];
    var accepted = [];
    var seenIds = Object.create(null);

    rawSuggestions.forEach(function (raw, index) {
      var path = 'suggestions[' + index + ']';
      if (!isObject(raw)) {
        errors.push(error('suggestion-invalid', path, 'Each suggestion must be an object.'));
        return;
      }
      detectForbiddenKeys(raw, path, errors);

      if (!isNonEmptyString(raw.id)) {
        errors.push(error('suggestion-id', path + '.id', 'Each suggestion needs an id.'));
        return;
      }
      if (seenIds[raw.id]) {
        errors.push(error('suggestion-duplicate', path + '.id', 'Duplicate suggestion id ' + raw.id + '.'));
        return;
      }
      seenIds[raw.id] = true;

      // An explicit insufficient-evidence result is a legitimate answer and is
      // kept, but it never carries a component claim.
      if (raw.result === 'insufficient_evidence') {
        accepted.push({
          id: raw.id,
          result: 'insufficient_evidence',
          domainId: null,
          componentId: null,
          sourceSpans: [],
          objectiveEvidence: '',
          interpretation: '',
          note: isNonEmptyString(raw.note) ? raw.note.slice(0, MAX_FIELD_CHARS) : 'The notes do not establish this.',
          confidence: null,
          warnings: [],
          decision: 'pending',
          approvedText: null
        });
        return;
      }

      var component = componentIndex[raw.componentId];
      if (!component) {
        errors.push(error('component-unknown', path + '.componentId',
          'Suggestion references a component that is not in the configured framework.'));
        return;
      }
      if (isNonEmptyString(raw.domainId) && raw.domainId !== component.domainId) {
        errors.push(error('domain-mismatch', path + '.domainId',
          'Suggestion domain does not match the component it cites.'));
        return;
      }
      if (!isNonEmptyString(raw.objectiveEvidence)) {
        errors.push(error('evidence-empty', path + '.objectiveEvidence',
          'A suggestion must state the evidence observed.'));
        return;
      }
      if (raw.objectiveEvidence.length > MAX_FIELD_CHARS
        || (isString(raw.interpretation) && raw.interpretation.length > MAX_FIELD_CHARS)) {
        errors.push(error('field-long', path, 'Suggestion text exceeds the allowed length.'));
        return;
      }
      if (!Array.isArray(raw.sourceSpans) || raw.sourceSpans.length === 0) {
        errors.push(error('span-absent', path + '.sourceSpans',
          'Every claim must cite at least one excerpt from the observation notes.'));
        return;
      }
      if (raw.sourceSpans.length > MAX_SPANS_PER_SUGGESTION) {
        errors.push(error('span-many', path + '.sourceSpans', 'Too many cited excerpts on one suggestion.'));
        return;
      }
      var spansOk = true;
      raw.sourceSpans.forEach(function (span, spanIndex) {
        if (!validateSpan(notes, span, path + '.sourceSpans[' + spanIndex + ']', errors)) spansOk = false;
      });
      if (!spansOk) return;

      var confidence = typeof raw.confidence === 'number' && isFinite(raw.confidence)
        ? Math.min(1, Math.max(0, raw.confidence))
        : null;

      var candidate = {
        id: raw.id,
        result: 'supported',
        domainId: component.domainId,
        componentId: component.id,
        sourceSpans: clone(raw.sourceSpans),
        objectiveEvidence: raw.objectiveEvidence.trim(),
        interpretation: isNonEmptyString(raw.interpretation) ? raw.interpretation.trim() : '',
        note: '',
        confidence: confidence,
        warnings: [],
        decision: 'pending',
        approvedText: null
      };
      candidate.warnings = suggestionWarnings(candidate, path);
      warnings = warnings.concat(candidate.warnings);
      accepted.push(candidate);
    });

    if (errors.length) return bad(errors, warnings);

    var next = clone(draft);
    next.suggestions = accepted;
    next.globalWarnings = globalWarnings(next);
    return ok(next, warnings.concat(next.globalWarnings));
  }

  function globalWarnings(draft) {
    var warnings = [];
    var covered = Object.create(null);
    draft.suggestions.forEach(function (suggestion) {
      if (suggestion.result === 'supported' && suggestion.decision !== 'rejected') {
        covered[suggestion.domainId] = true;
      }
    });
    draft.framework.domains.forEach(function (domain) {
      if (!covered[domain.id]) {
        warnings.push(warning('domain-empty', 'domains.' + domain.id,
          'No evidence was recorded for ' + domain.label + '.'));
      }
    });
    if (draft.suggestions.length === 0) {
      warnings.push(warning('suggestions-none', 'suggestions',
        'No supported components were identified in these notes.'));
    }
    return warnings;
  }

  /* ---------------------------------------------------------------------- *
   * Human decisions
   *
   * Every transition returns a new draft. The frozen notes are copied forward
   * untouched, and editing a suggestion never rewrites its cited excerpt.
   * ---------------------------------------------------------------------- */

  function decideSuggestion(draft, suggestionId, decision, approvedText) {
    if (!isObject(draft) || !Array.isArray(draft.suggestions)) {
      return bad([error('draft-invalid', 'draft', 'A draft is required.')]);
    }
    if (DECISIONS.indexOf(decision) === -1 || decision === 'pending') {
      return bad([error('decision-invalid', 'decision', 'Decision must be accepted, edited, or rejected.')]);
    }
    var index = -1;
    draft.suggestions.forEach(function (suggestion, position) {
      if (suggestion.id === suggestionId) index = position;
    });
    if (index === -1) {
      return bad([error('suggestion-unknown', 'suggestionId', 'That suggestion is not part of this draft.')]);
    }
    if (decision === 'edited' && !isNonEmptyString(approvedText)) {
      return bad([error('edit-empty', 'approvedText', 'An edited suggestion needs approved text.')]);
    }
    if (isString(approvedText) && approvedText.length > MAX_FIELD_CHARS) {
      return bad([error('edit-long', 'approvedText', 'Approved text exceeds the allowed length.')]);
    }

    var next = clone(draft);
    var target = next.suggestions[index];
    target.decision = decision;
    if (decision === 'rejected') {
      target.approvedText = null;
    } else if (decision === 'edited') {
      target.approvedText = approvedText.trim();
    } else {
      target.approvedText = target.result === 'insufficient_evidence'
        ? target.note
        : target.objectiveEvidence;
    }
    // The cited excerpt is never rewritten by an edit.
    target.sourceSpans = clone(draft.suggestions[index].sourceSpans);
    next.sourceNotesOriginal = draft.sourceNotesOriginal;
    next.globalWarnings = globalWarnings(next);
    return ok(next);
  }

  /* ---------------------------------------------------------------------- *
   * Export gating
   * ---------------------------------------------------------------------- */

  function exportReadiness(draft) {
    var errors = [];
    if (!isObject(draft) || !Array.isArray(draft.suggestions)) {
      return bad([error('draft-invalid', 'draft', 'A draft is required.')]);
    }
    if (!isNonEmptyString(disclosureLine(draft.disclosure))) {
      errors.push(error('disclosure-empty', 'disclosure',
        'The disclosure cannot be blank. Reword it if needed, but it must travel with the feedback.'));
    }
    var pending = draft.suggestions.filter(function (suggestion) {
      return suggestion.decision === 'pending';
    });
    if (pending.length) {
      errors.push(error('decisions-pending', 'suggestions',
        'Accept, edit, or reject every suggestion before copying feedback.'));
    }
    var keeps = draft.suggestions.filter(function (suggestion) {
      return suggestion.decision === 'accepted' || suggestion.decision === 'edited';
    });
    if (!keeps.length) {
      errors.push(error('nothing-approved', 'suggestions',
        'Nothing has been approved, so there is no feedback to copy.'));
    }
    if (errors.length) return bad(errors);
    return ok({ approvedCount: keeps.length });
  }

  /* ---------------------------------------------------------------------- *
   * Record output
   *
   * This is the boundary between the draft and the record. Rejected
   * suggestions, confidence values, and warnings are dropped here and never
   * appear in anything that can be filed.
   * ---------------------------------------------------------------------- */

  function buildFormOutput(draft, fieldMap, options) {
    var readiness = exportReadiness(draft);
    if (!readiness.ok) return readiness;

    var map = isObject(fieldMap) ? fieldMap : {};
    var line = disclosureLine(draft.disclosure);
    var watermark = draft.mode === 'demo' ? DEMO_WATERMARK : '';
    var header = watermark ? watermark + '\n' + line : line;

    var byDomain = Object.create(null);
    draft.framework.domains.forEach(function (domain) {
      byDomain[domain.id] = [];
    });
    draft.suggestions.forEach(function (suggestion) {
      if (suggestion.decision !== 'accepted' && suggestion.decision !== 'edited') return;
      if (suggestion.result === 'insufficient_evidence') return;
      var text = suggestion.approvedText || suggestion.objectiveEvidence;
      byDomain[suggestion.domainId].push(text);
    });

    var fields = draft.framework.domains.map(function (domain) {
      var body = byDomain[domain.id].join('\n\n');
      return {
        key: map[domain.id] || domain.label,
        domainId: domain.id,
        label: domain.label,
        empty: body === '',
        // The disclosure travels with every field, so a single-field copy
        // can never arrive without it.
        text: header + '\n\n' + (body === '' ? 'No evidence was recorded for this domain during this walkthrough.' : body)
      };
    });

    var contextFields = [];
    ['teacherDisplayName', 'date', 'period', 'subject', 'observer'].forEach(function (key) {
      if (isNonEmptyString(draft.context[key])) {
        contextFields.push({ key: map[key] || key, domainId: null, label: key, empty: false, text: draft.context[key] });
      }
    });

    var copyAll = contextFields.map(function (field) {
      return field.label + ': ' + field.text;
    }).join('\n');

    var body = fields.map(function (field) {
      var domainBody = field.text.slice(header.length).replace(/^\n+/, '');
      return field.label + '\n' + domainBody;
    }).join('\n\n');

    return ok({
      contractVersion: CONTRACT_VERSION,
      mode: draft.mode,
      watermark: watermark,
      disclosure: line,
      collectionType: draft.collectionType,
      generatedAt: stamp(options),
      contextFields: contextFields,
      fields: fields,
      copyAll: (copyAll ? copyAll + '\n\n' : '') + header + '\n\n' + body
    });
  }

  function exportDraft(draft, fieldMap, options) {
    var output = buildFormOutput(draft, fieldMap, options);
    if (!output.ok) return output;
    var at = stamp(options);
    var approvedIds = draft.suggestions.filter(function (suggestion) {
      return suggestion.decision === 'accepted' || suggestion.decision === 'edited';
    }).map(function (suggestion) {
      return suggestion.id;
    });
    return ok({
      record: output.value,
      principalApproval: { approvedAt: at, approvedSuggestionIds: approvedIds },
      // Deliberately absent: rejected suggestions, confidence values, warnings,
      // and the raw notes. Those belong to the session only.
      containsDraftArtifacts: false
    });
  }

  /* ---------------------------------------------------------------------- *
   * Practice mode
   *
   * Compares the observer's decisions against a scenario's reference reading.
   * This deliberately produces no score, no percentage, and no pass mark. The
   * reference is one defensible reading, so the output is framed as agreement
   * and divergence between two readings, with prompts for discussion.
   *
   * Practice results are self-reported and unverified. They must never be
   * presented as certification, calibration, or a measure of anyone's skill.
   * ---------------------------------------------------------------------- */

  function keptSuggestions(draft) {
    return draft.suggestions.filter(function (suggestion) {
      return suggestion.decision === 'accepted' || suggestion.decision === 'edited';
    });
  }

  function compareToReference(scenario, draft) {
    if (!isObject(scenario) || !isObject(scenario.reference)) {
      return bad([error('scenario-invalid', 'scenario', 'A scenario with a reference reading is required.')]);
    }
    if (!isObject(draft) || !Array.isArray(draft.suggestions)) {
      return bad([error('draft-invalid', 'draft', 'A reviewed draft is required.')]);
    }
    var pending = draft.suggestions.filter(function (suggestion) {
      return suggestion.decision === 'pending';
    });
    if (pending.length) {
      return bad([error('decisions-pending', 'suggestions',
        'Decide every suggestion before comparing readings.')]);
    }

    var reference = scenario.reference;
    var support = Array.isArray(reference.support) ? reference.support : [];
    var overreach = Array.isArray(reference.overreach) ? reference.overreach : [];
    var kept = keptSuggestions(draft);
    var keptComponents = kept.map(function (suggestion) { return suggestion.componentId; });
    var keptIds = kept.map(function (suggestion) { return suggestion.id; });

    var agreements = [];
    var divergences = [];

    support.forEach(function (componentId) {
      if (keptComponents.indexOf(componentId) !== -1) {
        agreements.push({
          componentId: componentId,
          note: 'You and the reference reading both found this supported by the notes.'
        });
      } else {
        divergences.push({
          kind: 'reference-kept-you-did-not',
          componentId: componentId,
          note: 'The reference reading kept this one. Look again at what the notes actually record, then decide whether you still disagree.'
        });
      }
    });

    overreach.forEach(function (componentId) {
      if (keptComponents.indexOf(componentId) !== -1) {
        divergences.push({
          kind: 'you-kept-reference-did-not',
          componentId: componentId,
          note: 'The reference reading treats this as reaching past the evidence. What in the notes would have to be there for it to hold?'
        });
      } else {
        agreements.push({
          componentId: componentId,
          note: 'You and the reference reading both declined to claim this.'
        });
      }
    });

    var declaredInsufficient = draft.suggestions.some(function (suggestion) {
      return suggestion.result === 'insufficient_evidence'
        && (suggestion.decision === 'accepted' || suggestion.decision === 'edited');
    });
    if (reference.expectInsufficient === true && !declaredInsufficient) {
      divergences.push({
        kind: 'insufficient-not-declared',
        componentId: null,
        note: 'The reference reading says the honest result here is that the notes do not establish much. Saying so is a finding, not a failure.'
      });
    }

    var pair = reference.preferBetweenPair;
    if (isObject(pair)) {
      var keptPreferred = keptIds.indexOf(pair.prefer) !== -1;
      var keptWeaker = keptIds.indexOf(pair.over) !== -1;
      if (keptWeaker && !keptPreferred) {
        divergences.push({
          kind: 'weaker-of-pair',
          componentId: pair.componentId,
          note: 'Two candidates addressed this component. The reference reading prefers the one that quotes an action over the one that quotes a conclusion.'
        });
      } else if (keptPreferred && !keptWeaker) {
        agreements.push({
          componentId: pair.componentId,
          note: 'You kept the candidate grounded in an observable action rather than the one that carried a conclusion.'
        });
      }
    }

    return ok({
      scenarioId: scenario.id,
      trustModel: 'learner-device-unverified',
      selfReported: true,
      isCalibration: false,
      agreements: agreements,
      divergences: divergences,
      referenceNote: isNonEmptyString(reference.note) ? reference.note : '',
      discussion: Array.isArray(scenario.discussion) ? scenario.discussion.slice() : [],
      disclaimer: 'The reference reading is one defensible reading, not an answer key. '
        + 'Use it to start a conversation, not to settle one.'
    });
  }

  /* ---------------------------------------------------------------------- *
   * Session teardown
   * ---------------------------------------------------------------------- */

  function clearDraft(draft) {
    if (!isObject(draft)) return ok(null);
    return ok({
      id: draft.id,
      cleared: true,
      sourceNotesOriginal: '',
      suggestions: [],
      globalWarnings: [],
      note: 'The working draft was cleared. Anything not copied out is gone.'
    });
  }

  var api = {
    CONTRACT_VERSION: CONTRACT_VERSION,
    DEFAULT_DISCLOSURE: DEFAULT_DISCLOSURE,
    DEFAULT_FORMATIVE_SENTENCE: DEFAULT_FORMATIVE_SENTENCE,
    DEMO_WATERMARK: DEMO_WATERMARK,
    MODES: MODES.slice(),
    DECISIONS: DECISIONS.slice(),
    validateFramework: validateFramework,
    normalizeDisclosure: normalizeDisclosure,
    disclosureLine: disclosureLine,
    createDraft: createDraft,
    validateSuggestions: validateSuggestions,
    decideSuggestion: decideSuggestion,
    exportReadiness: exportReadiness,
    buildFormOutput: buildFormOutput,
    exportDraft: exportDraft,
    compareToReference: compareToReference,
    clearDraft: clearDraft
  };

  if (typeof window !== 'undefined') {
    window.AlloModules = window.AlloModules || {};
    window.AlloModules.WalkthroughCopilot = api;
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();

/* bundled from walkthrough_copilot_fixtures.js */
/*
 * AlloFlow Walkthrough Copilot - framework configurations and synthetic fixtures.
 *
 * FRAMEWORK CONFIGURATIONS
 *
 * These carry domain and component STRUCTURE only. No performance-level rubric
 * language appears here, and none should be added. The rubric descriptors that
 * distinguish one performance level from another are the substantial expression
 * in a published framework and are the district's to supply, under whatever
 * license or local authorship applies to them.
 *
 * The Portland structure below is transcribed from Portland Public Schools'
 * publicly posted educator evaluation guidebook, which describes The Portland
 * Framework for Teaching as a local adaptation of the Danielson framework with
 * four domains and twenty-two components. Confirm it against the district's
 * current Performance Evaluation and Professional Growth System Guidebook
 * before any real use; that document is not published and must be requested.
 *
 * SYNTHETIC FIXTURES
 *
 * Every fixture is invented. No real educator, student, school, lesson, or
 * observation is represented. Names are deliberately generic placeholders.
 */
(function () {
  'use strict';

  var PORTLAND_FRAMEWORK = {
    id: 'portland-framework-for-teaching',
    label: 'The Portland Framework for Teaching (structure only)',
    domains: [
      { id: 'd1', label: 'Domain 1: Planning and Preparation' },
      { id: 'd2', label: 'Domain 2: The Classroom Environment' },
      { id: 'd3', label: 'Domain 3: Instruction' },
      { id: 'd4', label: 'Domain 4: Professional Responsibilities' }
    ],
    components: [
      { id: '1a', domainId: 'd1', label: 'Demonstrating Knowledge of Content and Pedagogy' },
      { id: '1b', domainId: 'd1', label: 'Demonstrating Knowledge of Students' },
      { id: '1c', domainId: 'd1', label: 'Setting Instructional Outcomes' },
      { id: '1d', domainId: 'd1', label: 'Demonstrating Knowledge of Resources' },
      { id: '1e', domainId: 'd1', label: 'Designing Coherent Instruction' },
      { id: '1f', domainId: 'd1', label: 'Designing Student Assessments' },
      { id: '2a', domainId: 'd2', label: 'Creating an Environment of Respect and Rapport' },
      { id: '2b', domainId: 'd2', label: 'Establishing a Culture for Learning' },
      { id: '2c', domainId: 'd2', label: 'Managing Classroom Procedures' },
      { id: '2d', domainId: 'd2', label: 'Managing Student Behavior' },
      { id: '2e', domainId: 'd2', label: 'Organizing Physical Space' },
      { id: '3a', domainId: 'd3', label: 'Communicating with Students' },
      { id: '3b', domainId: 'd3', label: 'Using Questioning and Discussion Techniques' },
      { id: '3c', domainId: 'd3', label: 'Engaging Students in Learning' },
      { id: '3d', domainId: 'd3', label: 'Using Assessment in Instruction' },
      { id: '3e', domainId: 'd3', label: 'Demonstrating Flexibility and Responsiveness' },
      { id: '4a', domainId: 'd4', label: 'Reflection on Teaching' },
      { id: '4b', domainId: 'd4', label: 'Maintaining Accurate Records' },
      { id: '4c', domainId: 'd4', label: 'Communicating with Families' },
      { id: '4d', domainId: 'd4', label: 'Participating in a Professional Community' },
      { id: '4e', domainId: 'd4', label: 'Growing and Developing Professionally' },
      { id: '4f', domainId: 'd4', label: 'Showing Professionalism' }
    ]
  };

  // A deliberately different shape, used to prove nothing assumes four domains.
  var THREE_DOMAIN_FRAMEWORK = {
    id: 'district-local-example',
    label: 'Local three-domain example',
    domains: [
      { id: 'env', label: 'Learning Environment' },
      { id: 'inst', label: 'Instruction' },
      { id: 'prof', label: 'Professional Practice' }
    ],
    components: [
      { id: 'env-1', domainId: 'env', label: 'Routines and transitions' },
      { id: 'inst-1', domainId: 'inst', label: 'Questioning and discussion' },
      { id: 'inst-2', domainId: 'inst', label: 'Checking for understanding' },
      { id: 'prof-1', domainId: 'prof', label: 'Collaboration with colleagues' }
    ]
  };

  // Synthetic observation notes. Written in the clipped shorthand a principal
  // actually produces, including one contradiction and one thin claim so the
  // validators have something real to catch.
  var SAMPLE_NOTES = [
    '9:05 entered. Do Now on board, timer running. 22 present.',
    '9:07 T asks "what evidence in paragraph 2 supports that?" waits ~5 sec before calling on anyone.',
    '9:09 three hands up, T takes two responses, asks second student to build on the first.',
    '9:12 one student at back has head down, no materials out.',
    '9:14 T circulates, stops at four desks, quiet check-ins.',
    '9:18 transition to partner work, took about 90 seconds, some milling.',
    '9:21 exit ticket posted on board for later.',
    'anchor chart from last week still up and referenced.'
  ].join('\n');

  function spanFor(notes, snippet) {
    var start = notes.indexOf(snippet);
    if (start === -1) throw new Error('Fixture snippet not found in notes: ' + snippet);
    return { start: start, end: start + snippet.length, text: snippet };
  }

  // Suggestions a well-behaved adapter would return for SAMPLE_NOTES.
  function goodSuggestions(notes) {
    return [
      {
        id: 's-3b',
        componentId: '3b',
        domainId: 'd3',
        objectiveEvidence: 'The teacher asked "what evidence in paragraph 2 supports that?" and waited about five seconds before calling on a student, then asked a second student to build on the first response.',
        interpretation: 'Wait time and the build-on move gave more than one student a route into the discussion.',
        confidence: 0.8,
        sourceSpans: [
          spanFor(notes, '9:07 T asks "what evidence in paragraph 2 supports that?" waits ~5 sec before calling on anyone.'),
          spanFor(notes, '9:09 three hands up, T takes two responses, asks second student to build on the first.')
        ]
      },
      {
        id: 's-2c',
        componentId: '2c',
        domainId: 'd2',
        objectiveEvidence: 'A Do Now was posted with a timer running at the start of the period, and the transition to partner work took about ninety seconds with some milling.',
        interpretation: 'Opening routine is established; the mid-period transition is the slower one.',
        confidence: 0.7,
        sourceSpans: [
          spanFor(notes, '9:05 entered. Do Now on board, timer running. 22 present.'),
          spanFor(notes, '9:18 transition to partner work, took about 90 seconds, some milling.')
        ]
      },
      {
        id: 's-3d',
        componentId: '3d',
        domainId: 'd3',
        objectiveEvidence: 'The teacher circulated and stopped at four desks for quiet check-ins, and an exit ticket was posted for later.',
        interpretation: 'Checking for understanding happened in conversation; the exit ticket was not yet collected during this visit.',
        confidence: 0.6,
        sourceSpans: [
          spanFor(notes, '9:14 T circulates, stops at four desks, quiet check-ins.'),
          spanFor(notes, '9:21 exit ticket posted on board for later.')
        ]
      },
      {
        id: 's-insufficient',
        result: 'insufficient_evidence',
        note: 'The notes do not establish anything about planning, family communication, or professional collaboration. A walkthrough of this length would not normally show them.'
      }
    ];
  }

  // Each of these should be caught. They exist so tests can prove the
  // validators fail on real defects rather than passing vacuously.
  function badSuggestions(notes) {
    return {
      fabricatedQuote: {
        id: 'bad-fabricated',
        componentId: '3a',
        objectiveEvidence: 'The teacher told the class "we will revisit this tomorrow".',
        interpretation: 'Closure was signalled.',
        sourceSpans: [{ start: 0, end: 20, text: 'The teacher told the class "we will revisit this tomorrow".' }]
      },
      uncitedClaim: {
        id: 'bad-uncited',
        componentId: '2a',
        objectiveEvidence: 'Rapport between teacher and students was warm throughout.',
        interpretation: 'Positive climate.',
        sourceSpans: []
      },
      unknownComponent: {
        id: 'bad-unknown',
        componentId: '9z',
        objectiveEvidence: 'Something happened.',
        sourceSpans: [spanFor(notes, '9:05 entered. Do Now on board, timer running. 22 present.')]
      },
      carriesRating: {
        id: 'bad-rating',
        componentId: '3c',
        rating: 'proficient',
        objectiveEvidence: 'The teacher circulated and stopped at four desks for quiet check-ins.',
        sourceSpans: [spanFor(notes, '9:14 T circulates, stops at four desks, quiet check-ins.')]
      },
      judgmentAsEvidence: {
        id: 'warn-judgment',
        componentId: '3c',
        objectiveEvidence: 'Students were engaged and the lesson was effective.',
        interpretation: 'Good pacing.',
        sourceSpans: [spanFor(notes, '9:09 three hands up, T takes two responses, asks second student to build on the first.')]
      },
      overGeneralized: {
        id: 'warn-generalized',
        componentId: '3c',
        objectiveEvidence: 'Three hands went up and the teacher took two responses.',
        interpretation: 'The students were all participating.',
        sourceSpans: [spanFor(notes, '9:09 three hands up, T takes two responses, asks second student to build on the first.')]
      },
      mismatchedDomain: {
        id: 'bad-domain',
        componentId: '3b',
        domainId: 'd1',
        objectiveEvidence: 'The teacher asked a text-evidence question.',
        sourceSpans: [spanFor(notes, '9:07 T asks "what evidence in paragraph 2 supports that?" waits ~5 sec before calling on anyone.')]
      }
    };
  }

  var SAMPLE_CONTEXT = {
    teacherDisplayName: 'Educator A (synthetic)',
    date: '2026-09-15',
    period: 'Period 2',
    subject: 'Grade 7 ELA',
    observer: 'Observer B (synthetic)'
  };

  var SAMPLE_FIELD_MAP = {
    d1: 'Domain 1 - Planning',
    d2: 'Domain 2 - Classroom Environment',
    d3: 'Domain 3 - Instruction',
    d4: 'Domain 4 - Professional Responsibilities',
    teacherDisplayName: 'Employee',
    date: 'Date',
    period: 'Period',
    observer: 'Principal'
  };

  var api = {
    PORTLAND_FRAMEWORK: PORTLAND_FRAMEWORK,
    THREE_DOMAIN_FRAMEWORK: THREE_DOMAIN_FRAMEWORK,
    SAMPLE_NOTES: SAMPLE_NOTES,
    SAMPLE_CONTEXT: SAMPLE_CONTEXT,
    SAMPLE_FIELD_MAP: SAMPLE_FIELD_MAP,
    spanFor: spanFor,
    goodSuggestions: goodSuggestions,
    badSuggestions: badSuggestions
  };

  if (typeof window !== 'undefined') {
    window.AlloModules = window.AlloModules || {};
    window.AlloModules.WalkthroughCopilotFixtures = api;
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();

/* bundled from walkthrough_copilot_scenarios.js */
/*
 * AlloFlow Walkthrough Copilot - practice scenarios.
 *
 * A built-in professional-learning mode. Each scenario is a synthetic
 * observation that teaches one habit of evidence-based feedback, and each one
 * targets a specific way a walkthrough write-up goes wrong. The traps here are
 * the same failures the core validators catch, so practising the habit and
 * using the tool reinforce each other.
 *
 * Every scenario ships its own candidate suggestions. Practice mode therefore
 * runs with NO AI provider, NO network call, and NO district approval, which is
 * also what makes it safe to demonstrate to anyone at any time.
 *
 * WHAT THIS IS NOT. The reference reading attached to each scenario is one
 * defensible reading by one author. It is not an answer key, not a validated
 * observation-calibration instrument, and not evidence of inter-rater
 * reliability. Two careful observers can read the same lesson differently and
 * both be defensible. Practice results are self-reported and unverified in the
 * sense used by docs/PD_MICROCREDENTIAL_FOUNDATION.md, and must never be
 * presented as certification, calibration, or a measure of anyone's skill.
 *
 * All content is invented. No real educator, student, school, or lesson.
 */
(function () {
  'use strict';

  function spanFor(notes, snippet) {
    var start = notes.indexOf(snippet);
    if (start === -1) throw new Error('Scenario snippet not found in notes: ' + snippet);
    return { start: start, end: start + snippet.length, text: snippet };
  }

  function build(config) {
    var notes = config.notes;
    return {
      id: config.id,
      title: config.title,
      minutes: config.minutes,
      setting: config.setting,
      teaches: config.teaches,
      trap: config.trap,
      notes: notes,
      candidates: config.candidates(notes),
      reference: config.reference,
      discussion: config.discussion
    };
  }

  /* ------------------------------------------------------------------ *
   * 1. Thin notes. A short drop-in records very little. The pull is to
   *    write a full four-domain report anyway.
   * ------------------------------------------------------------------ */
  var THIN_NOTES = [
    '10:42 in. Small group at back table, rest independent reading.',
    '10:44 T with small group, hears one student read aloud, prompts on a word.',
    '10:47 out.'
  ].join('\n');

  var THIN = build({
    id: 'thin-notes',
    title: 'A five-minute drop-in',
    minutes: 5,
    setting: 'Grade 4 literacy block',
    teaches: 'Saying what the notes do not establish, instead of filling the gap.',
    trap: 'A short visit produces thin notes. The habit of completing every domain turns thin notes into confident claims nobody observed.',
    notes: THIN_NOTES,
    candidates: function (notes) {
      return [
        {
          id: 'thin-c1',
          componentId: '3d',
          objectiveEvidence: 'The teacher worked with a small group at the back table, listened to one student read aloud, and prompted on a word.',
          interpretation: 'A brief listen-in with in-the-moment prompting.',
          confidence: 0.7,
          sourceSpans: [spanFor(notes, '10:44 T with small group, hears one student read aloud, prompts on a word.')]
        },
        {
          id: 'thin-c2',
          componentId: '1e',
          objectiveEvidence: 'The lesson was well designed with a small group rotation and independent reading.',
          interpretation: 'Coherent planning.',
          confidence: 0.5,
          sourceSpans: [spanFor(notes, '10:42 in. Small group at back table, rest independent reading.')]
        },
        {
          id: 'thin-c3',
          result: 'insufficient_evidence',
          note: 'Five minutes in one corner of the room does not establish planning, classroom environment, or professional responsibilities.'
        }
      ];
    },
    reference: {
      support: ['3d'],
      overreach: ['1e'],
      expectInsufficient: true,
      note: 'Seeing a rotation running does not show how it was designed, why those groups, or what assessment informed them. That is a conference question, not a walkthrough observation.'
    },
    discussion: [
      'What would you have to see, or ask, to say anything about planning?',
      'Is a five-minute visit worth writing up at all? What makes it useful to the teacher?',
      'How do you word "I was only here briefly" without it sounding like an apology?'
    ]
  });

  /* ------------------------------------------------------------------ *
   * 2. One student becomes the whole class.
   * ------------------------------------------------------------------ */
  var GENERALIZE_NOTES = [
    '1:15 T poses problem on board, asks for strategies.',
    '1:17 one student explains a strategy at the board, uses the term "regrouping" correctly.',
    '1:19 T asks "did anyone solve it a different way?" pause, no hands.',
    '1:21 T moves on to guided practice.',
    '1:24 two students near window talking, not on task.'
  ].join('\n');

  var GENERALIZE = build({
    id: 'one-student-generalization',
    title: 'One voice, twenty-four students',
    minutes: 10,
    setting: 'Grade 6 mathematics',
    teaches: 'Keeping a claim the size of the evidence behind it.',
    trap: 'One articulate student is the most memorable thing in the notes, and the write-up quietly promotes them into "students".',
    notes: GENERALIZE_NOTES,
    candidates: function (notes) {
      return [
        {
          id: 'gen-c1',
          componentId: '3c',
          objectiveEvidence: 'Students were engaged and using precise mathematical vocabulary.',
          interpretation: 'Strong participation across the class.',
          confidence: 0.6,
          sourceSpans: [spanFor(notes, '1:17 one student explains a strategy at the board, uses the term "regrouping" correctly.')]
        },
        {
          id: 'gen-c2',
          componentId: '3b',
          objectiveEvidence: 'The teacher asked "did anyone solve it a different way?" and paused, and no hands went up before the class moved to guided practice.',
          interpretation: 'The invitation for alternative strategies did not draw a response on this occasion.',
          confidence: 0.8,
          sourceSpans: [
            spanFor(notes, '1:19 T asks "did anyone solve it a different way?" pause, no hands.'),
            spanFor(notes, '1:21 T moves on to guided practice.')
          ]
        }
      ];
    },
    reference: {
      support: ['3b'],
      overreach: ['3c'],
      expectInsufficient: false,
      note: 'One student at the board and two students off task are both in the notes. Neither is the class. The honest observation is about what the teacher asked and what came back.'
    },
    discussion: [
      'What would "students were engaged" require you to have recorded?',
      'The unanswered question is the most useful thing here. How do you raise it as a coaching point rather than a criticism?',
      'Do the two off-task students belong in the write-up at all?'
    ]
  });

  /* ------------------------------------------------------------------ *
   * 3. The observer's own judgments are already in the notes.
   * ------------------------------------------------------------------ */
  var JUDGMENT_NOTES = [
    '9:30 great rapport, kids clearly love this teacher.',
    '9:32 T greets three students by name at the door.',
    '9:35 strong classroom management.',
    '9:36 T uses a hand signal, noise level drops, takes about four seconds.',
    '9:40 lesson felt a bit flat.'
  ].join('\n');

  var JUDGMENT = build({
    id: 'judgment-in-notes',
    title: 'Notes that already decided',
    minutes: 10,
    setting: 'Grade 8 science',
    teaches: 'Separating what was seen from what it meant, even when your own notes blurred them.',
    trap: 'Shorthand written in the moment carries conclusions. Copied forward, a conclusion becomes an "observation" the teacher cannot dispute because nothing concrete was recorded.',
    notes: JUDGMENT_NOTES,
    candidates: function (notes) {
      return [
        {
          id: 'judg-c1',
          componentId: '2a',
          objectiveEvidence: 'There was great rapport and the students clearly love this teacher.',
          interpretation: 'Positive climate.',
          confidence: 0.5,
          sourceSpans: [spanFor(notes, '9:30 great rapport, kids clearly love this teacher.')]
        },
        {
          id: 'judg-c2',
          componentId: '2a',
          objectiveEvidence: 'The teacher greeted three students by name at the door.',
          interpretation: 'Greeting by name is one observable way rapport gets built.',
          confidence: 0.75,
          sourceSpans: [spanFor(notes, '9:32 T greets three students by name at the door.')]
        },
        {
          id: 'judg-c3',
          componentId: '2c',
          objectiveEvidence: 'The teacher used a hand signal and the noise level dropped in about four seconds.',
          interpretation: 'A practised, non-verbal transition signal.',
          confidence: 0.85,
          sourceSpans: [spanFor(notes, '9:36 T uses a hand signal, noise level drops, takes about four seconds.')]
        }
      ];
    },
    reference: {
      support: ['2c'],
      overreach: [],
      expectInsufficient: false,
      note: 'Both rapport candidates point at the same component. One quotes a conclusion, the other quotes an action. "Lesson felt a bit flat" is the hardest line in the notes: it is a real impression with nothing recorded behind it, and it should either be grounded or left out.',
      preferBetweenPair: { componentId: '2a', prefer: 'judg-c2', over: 'judg-c1' }
    },
    discussion: [
      'Your notes said "strong classroom management" and also recorded a four-second hand signal. Which one can the teacher act on?',
      'What do you do with "felt a bit flat" when you cannot say why?',
      'Is there a way to take notes that keeps the impression without disguising it as evidence?'
    ]
  });

  /* ------------------------------------------------------------------ *
   * 4. Two observations pull in opposite directions.
   * ------------------------------------------------------------------ */
  var CONTRADICTION_NOTES = [
    '11:05 directions given clearly, posted on board and read aloud.',
    '11:08 partner task begins.',
    '11:09 at least six students ask a neighbour what they are supposed to do.',
    '11:11 T restates the task, work starts.'
  ].join('\n');

  var CONTRADICTION = build({
    id: 'contradiction',
    title: 'Clear directions, confused room',
    minutes: 8,
    setting: 'Grade 5 social studies',
    teaches: 'Holding a contradiction open instead of resolving it silently.',
    trap: 'The write-up picks whichever half fits the story it is already telling, and the more interesting observation disappears.',
    notes: CONTRADICTION_NOTES,
    candidates: function (notes) {
      return [
        {
          id: 'con-c1',
          componentId: '3a',
          objectiveEvidence: 'Directions were given clearly, posted on the board and read aloud.',
          interpretation: 'Communication of the task was clear.',
          confidence: 0.6,
          sourceSpans: [spanFor(notes, '11:05 directions given clearly, posted on board and read aloud.')]
        },
        {
          id: 'con-c2',
          componentId: '3a',
          objectiveEvidence: 'Directions were posted and read aloud, and at the start of the partner task at least six students asked a neighbour what they were supposed to do. The teacher restated the task and work began.',
          interpretation: 'The directions were delivered in two modes and a substantial number of students still needed them restated. What made the restatement land is worth exploring.',
          confidence: 0.8,
          sourceSpans: [
            spanFor(notes, '11:05 directions given clearly, posted on board and read aloud.'),
            spanFor(notes, '11:09 at least six students ask a neighbour what they are supposed to do.'),
            spanFor(notes, '11:11 T restates the task, work starts.')
          ]
        }
      ];
    },
    reference: {
      support: ['3a'],
      overreach: [],
      expectInsufficient: false,
      note: 'The contradiction is the finding. A write-up that keeps only the first note is not wrong about that note, it is just useless to the teacher.',
      preferBetweenPair: { componentId: '3a', prefer: 'con-c2', over: 'con-c1' }
    },
    discussion: [
      'Which version would you rather receive about your own classroom?',
      '"Directions given clearly" was your own judgment written at 11:05. Did 11:09 change it?',
      'How do you write a contradiction so it reads as curiosity rather than a gotcha?'
    ]
  });

  /* ------------------------------------------------------------------ *
   * 5. Reaching into a domain the visit cannot see.
   * ------------------------------------------------------------------ */
  var OUT_OF_SCOPE_NOTES = [
    '2:10 lab stations set up before students arrive, materials counted out per station.',
    '2:13 T circulates with a clipboard, marks something after each station visit.',
    '2:20 two students ask to redo a measurement, T agrees and adjusts the timer.',
    '2:25 out.'
  ].join('\n');

  var OUT_OF_SCOPE = build({
    id: 'out-of-scope',
    title: 'What the clipboard does not tell you',
    minutes: 15,
    setting: 'High school chemistry',
    teaches: 'Noticing when a visible artifact tempts an invisible conclusion.',
    trap: 'Stations were ready and a clipboard was in use, so the write-up credits planning and record-keeping it never actually saw.',
    notes: OUT_OF_SCOPE_NOTES,
    candidates: function (notes) {
      return [
        {
          id: 'oos-c1',
          componentId: '3e',
          objectiveEvidence: 'Two students asked to redo a measurement, the teacher agreed and adjusted the timer.',
          interpretation: 'The teacher adjusted the plan in the moment to let students repeat their work.',
          confidence: 0.8,
          sourceSpans: [spanFor(notes, '2:20 two students ask to redo a measurement, T agrees and adjusts the timer.')]
        },
        {
          id: 'oos-c2',
          componentId: '4b',
          objectiveEvidence: 'The teacher maintained accurate records, marking after each station visit.',
          interpretation: 'Record keeping is thorough.',
          confidence: 0.55,
          sourceSpans: [spanFor(notes, '2:13 T circulates with a clipboard, marks something after each station visit.')]
        },
        {
          id: 'oos-c3',
          componentId: '1d',
          objectiveEvidence: 'Lab stations were set up before students arrived with materials counted out per station.',
          interpretation: 'Resources were prepared in advance.',
          confidence: 0.6,
          sourceSpans: [spanFor(notes, '2:10 lab stations set up before students arrive, materials counted out per station.')]
        }
      ];
    },
    reference: {
      support: ['3e'],
      overreach: ['4b'],
      expectInsufficient: false,
      note: 'A clipboard being written on is not evidence that the records are accurate. You saw marking, not what was marked. Prepared stations sit closer to the line: you did observe the room, so the honest version describes the setup you saw rather than crediting a planning process you did not.'
    },
    discussion: [
      'Where exactly is the line between "materials were counted out" and "the teacher plans well"?',
      'What would make the clipboard genuinely observable evidence?',
      'Which of these would you raise in a conference instead of writing up?'
    ]
  });

  var SCENARIOS = [THIN, GENERALIZE, JUDGMENT, CONTRADICTION, OUT_OF_SCOPE];

  var DISCLAIMER =
    'The reference reading is one defensible reading by one author. It is not an answer key, '
    + 'not a calibration instrument, and not evidence of inter-rater reliability. Two careful '
    + 'observers can read the same lesson differently and both be defensible. Use it to start '
    + 'a conversation, not to settle one.';

  function listScenarios() {
    return SCENARIOS.map(function (scenario) {
      return {
        id: scenario.id,
        title: scenario.title,
        minutes: scenario.minutes,
        setting: scenario.setting,
        teaches: scenario.teaches
      };
    });
  }

  function getScenario(id) {
    var found = null;
    SCENARIOS.forEach(function (scenario) {
      if (scenario.id === id) found = scenario;
    });
    return found ? JSON.parse(JSON.stringify(found)) : null;
  }

  var api = {
    DISCLAIMER: DISCLAIMER,
    listScenarios: listScenarios,
    getScenario: getScenario,
    scenarioIds: SCENARIOS.map(function (scenario) { return scenario.id; })
  };

  if (typeof window !== 'undefined') {
    window.AlloModules = window.AlloModules || {};
    window.AlloModules.WalkthroughCopilotScenarios = api;
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();

  var React = window.React;
  if (!React) { console.error('[WalkthroughCopilot] React not found on window'); return; }

const WCOP_ADVISORY_QUESTIONS = [
  "Which AI provider may process observation notes, and under what data agreement.",
  "Whether a walkthrough counts as one of the evidence collections in your evaluation system. If it does, this is not formative-only, whatever it is called.",
  "How long anything typed here is retained, where, and who can see it."
];
const WCOP_STEPS = [
  ["Capture", "Read the notes, then lock them so nothing can quietly rewrite them."],
  ["Review", "Work through each suggestion. Nothing moves forward until you decide on it."],
  ["Read", "See the feedback the way the teacher will read it."],
  ["Copy", "Paste it into the form your school already uses. Nothing is sent or saved."]
];
const WCOP_STAGES = [
  { id: "capture", n: "Step 1", label: "Capture notes" },
  { id: "analyze", n: "Step 2", label: "Your call on each suggestion" },
  { id: "feedback", n: "Step 3", label: "Read the feedback" },
  { id: "copy", n: "Step 4", label: "Copy to your form" }
];
function wcopCore() {
  return window.AlloModules && window.AlloModules.WalkthroughCopilot || null;
}
function wcopFixtures() {
  return window.AlloModules && window.AlloModules.WalkthroughCopilotFixtures || null;
}
function wcopScenarios() {
  return window.AlloModules && window.AlloModules.WalkthroughCopilotScenarios || null;
}
function wcopAnnounce(message) {
  try {
    const region = document.getElementById("allo-live-wcop");
    if (!region) return;
    region.textContent = "";
    window.setTimeout(() => {
      region.textContent = message;
    }, 30);
  } catch (err) {
  }
}
function WcopFlag(props) {
  const tone = props.tone || "warn";
  const cls = tone === "stop" ? "bg-rose-50 text-rose-800 border-rose-200" : tone === "go" ? "bg-emerald-50 text-emerald-800 border-emerald-200" : "bg-amber-50 text-amber-900 border-amber-200";
  return React.createElement("p", { className: "text-sm border rounded px-3 py-2 mt-2 " + cls }, props.children);
}
function WcopFrozenNotes(props) {
  return React.createElement(
    "div",
    { className: "rounded-lg border border-stone-300 bg-stone-50 p-3" },
    React.createElement(
      "p",
      { className: "text-[11px] uppercase tracking-wider text-stone-500 font-semibold mb-2" },
      "Source notes, locked"
    ),
    React.createElement(
      "pre",
      { className: "whitespace-pre-wrap break-words text-[13px] leading-relaxed text-stone-800 m-0 font-mono" },
      props.notes
    ),
    React.createElement(
      "p",
      { className: "text-xs text-stone-500 mt-2" },
      "These are never edited by this tool."
    )
  );
}
function WcopSuggestion(props) {
  const s = props.suggestion;
  const core = props.core;
  const titleId = "wcop-sugg-" + s.id;
  const border = s.decision === "accepted" ? "border-l-4 border-l-emerald-500" : s.decision === "edited" ? "border-l-4 border-l-amber-500" : "";
  const faded = s.decision === "rejected" ? " opacity-60" : "";
  const body = [];
  if (s.result === "insufficient_evidence") {
    body.push(React.createElement("p", {
      key: "h",
      id: titleId,
      className: "text-xs uppercase tracking-wider font-bold text-teal-700 mb-1"
    }, "Not established by these notes"));
    body.push(React.createElement("p", { key: "n", className: "text-sm text-slate-700" }, s.note));
  } else {
    body.push(React.createElement("p", {
      key: "h",
      id: titleId,
      className: "text-xs uppercase tracking-wider font-bold text-teal-700 mb-1"
    }, props.componentLabel));
    body.push(React.createElement("p", { key: "l1", className: "text-[11px] uppercase tracking-wider text-slate-500 font-semibold mt-2" }, "What was observed"));
    body.push(React.createElement("p", { key: "e", className: "text-sm text-slate-800" }, s.objectiveEvidence));
    if (s.interpretation) {
      body.push(React.createElement("p", { key: "l2", className: "text-[11px] uppercase tracking-wider text-slate-500 font-semibold mt-2" }, "What it might mean"));
      body.push(React.createElement("p", { key: "i", className: "text-sm text-slate-700 italic" }, s.interpretation));
    }
    body.push(React.createElement("p", { key: "l3", className: "text-[11px] uppercase tracking-wider text-slate-500 font-semibold mt-2" }, "Cited from the notes"));
    s.sourceSpans.forEach((span, i) => {
      body.push(React.createElement("blockquote", {
        key: "q" + i,
        className: "text-[13px] italic bg-stone-50 border-l-2 border-stone-300 px-2 py-1 my-1"
      }, span.text));
    });
  }
  s.warnings.forEach((flag, i) => {
    body.push(React.createElement(WcopFlag, { key: "w" + i }, flag.message));
  });
  if (s.decision === "edited" && s.approvedText) {
    body.push(React.createElement("p", { key: "l4", className: "text-[11px] uppercase tracking-wider text-slate-500 font-semibold mt-2" }, "Your wording"));
    body.push(React.createElement("p", { key: "a", className: "text-sm text-slate-800" }, s.approvedText));
  }
  if (props.editing) {
    body.push(React.createElement(
      "div",
      { key: "edit", className: "mt-3" },
      React.createElement("label", {
        className: "block text-xs font-semibold mb-1",
        htmlFor: "wcop-edit-" + s.id
      }, "Your wording for this feedback"),
      React.createElement("textarea", {
        id: "wcop-edit-" + s.id,
        className: "w-full rounded border border-slate-300 p-2 text-sm",
        rows: 3,
        value: props.editText,
        onChange: (e) => props.onEditText(e.target.value)
      }),
      React.createElement("button", {
        type: "button",
        className: "mt-2 px-3 py-1.5 rounded bg-teal-700 text-white text-sm font-semibold",
        onClick: () => props.onDecide(s.id, "edited", props.editText)
      }, "Save and approve this wording")
    ));
  }
  const controls = React.createElement(
    "div",
    { className: "flex flex-wrap gap-2 mt-3" },
    React.createElement("button", {
      type: "button",
      "aria-pressed": s.decision === "accepted",
      "aria-describedby": titleId,
      className: "px-3 py-1.5 rounded border text-sm font-semibold " + (s.decision === "accepted" ? "bg-emerald-50 border-emerald-600 text-emerald-800" : "border-slate-300 text-slate-700"),
      onClick: () => props.onDecide(s.id, "accepted")
    }, "Keep"),
    React.createElement("button", {
      type: "button",
      "aria-pressed": s.decision === "edited",
      "aria-describedby": titleId,
      className: "px-3 py-1.5 rounded border text-sm font-semibold " + (s.decision === "edited" ? "bg-amber-50 border-amber-600 text-amber-900" : "border-slate-300 text-slate-700"),
      onClick: () => props.onStartEdit(s)
    }, "Reword"),
    React.createElement("button", {
      type: "button",
      "aria-pressed": s.decision === "rejected",
      "aria-describedby": titleId,
      className: "px-3 py-1.5 rounded border text-sm font-semibold " + (s.decision === "rejected" ? "bg-rose-50 border-rose-600 text-rose-800" : "border-slate-300 text-slate-700"),
      onClick: () => props.onDecide(s.id, "rejected")
    }, "Throw out")
  );
  return React.createElement("div", {
    className: "rounded-lg border border-slate-200 bg-white p-3 mb-3 " + border + faded
  }, body, controls);
}
function WcopIntro(props) {
  return React.createElement(
    "div",
    { className: "rounded-lg border border-slate-200 border-l-4 border-l-teal-600 bg-white p-4 mb-4" },
    React.createElement(
      "div",
      { className: "flex items-start justify-between gap-3" },
      React.createElement("h3", { className: "font-bold text-slate-800" }, "What this does"),
      React.createElement("button", {
        type: "button",
        className: "text-sm px-2 py-1 rounded border border-slate-300",
        onClick: props.onHide
      }, "Hide this")
    ),
    React.createElement(
      "p",
      { className: "text-sm text-slate-700 mt-2" },
      "You type the shorthand you already write during a walkthrough. This organizes it into evidence-based feedback under your framework, shows you the exact line of your notes behind every claim, and lets you keep, reword, or throw out each one. You write and approve the feedback. It never rates anyone."
    ),
    React.createElement("p", { className: "text-[11px] uppercase tracking-wider text-slate-500 font-semibold mt-3" }, "Four steps"),
    React.createElement(
      "ol",
      { className: "list-decimal ml-5 text-sm text-slate-700" },
      WCOP_STEPS.map((step) => React.createElement(
        "li",
        { key: step[0], className: "mb-1" },
        React.createElement("strong", null, step[0] + ". "),
        step[1]
      ))
    ),
    React.createElement(
      "p",
      { className: "text-[11px] uppercase tracking-wider text-slate-500 font-semibold mt-3" },
      "Before using this with a real staff member"
    ),
    React.createElement(
      "p",
      { className: "text-sm text-slate-700" },
      "Everything built in here is invented practice material, so you can explore it freely. Using it on a real observation is a district decision, not a settings change. Get answers to:"
    ),
    React.createElement(
      "ul",
      { className: "list-disc ml-5 text-sm text-slate-700" },
      WCOP_ADVISORY_QUESTIONS.map((q, i) => React.createElement("li", { key: i, className: "mb-1" }, q))
    ),
    React.createElement(
      "p",
      { className: "text-xs text-slate-500 mt-2" },
      "This build analyzes the practice scenarios only. Analyzing notes you write yourself needs an approved AI provider, which is a separate decision."
    )
  );
}
function WalkthroughCopilotPanel(props) {
  const t = props && props.t || ((k, d) => d || k);
  const core = wcopCore();
  const fixtures = wcopFixtures();
  const scenarioLib = wcopScenarios();
  const [stage, setStage] = React.useState("capture");
  const [scenario, setScenario] = React.useState(null);
  const [notes, setNotes] = React.useState("");
  const [draft, setDraft] = React.useState(null);
  const [introOpen, setIntroOpen] = React.useState(true);
  const [editingId, setEditingId] = React.useState(null);
  const [editText, setEditText] = React.useState("");
  const [comparison, setComparison] = React.useState(null);
  const [problem, setProblem] = React.useState("");
  if (!core || !fixtures || !scenarioLib) {
    return React.createElement(
      "div",
      { className: "p-4 text-sm text-rose-800" },
      "The Walkthrough Copilot modules did not finish loading. Close and reopen this tool."
    );
  }
  const componentLabels = React.useMemo(() => {
    const map = {};
    fixtures.PORTLAND_FRAMEWORK.components.forEach((c) => {
      map[c.id] = c.id + " " + c.label;
    });
    return map;
  }, [fixtures]);
  const edited = !!scenario && notes !== scenario.notes;
  function pickScenario(id) {
    const next = scenarioLib.getScenario(id);
    setScenario(next);
    setNotes(next.notes);
    setDraft(null);
    setComparison(null);
    setProblem("");
    wcopAnnounce("Scenario selected: " + next.title + ". Notes loaded.");
  }
  function lockAndAnalyze() {
    const created = core.createDraft({
      framework: fixtures.PORTLAND_FRAMEWORK,
      sourceNotes: notes,
      collectionType: "practice"
    });
    if (!created.ok) {
      setProblem(created.errors[0].message);
      return;
    }
    const analyzed = core.validateSuggestions(created.value, scenario.candidates);
    if (!analyzed.ok) {
      setProblem(analyzed.errors[0].message);
      return;
    }
    setProblem("");
    setDraft(analyzed.value);
    setStage("analyze");
    wcopAnnounce("Notes locked. " + analyzed.value.suggestions.length + " suggestions to review.");
  }
  function decide(id, decision, text) {
    const report = core.decideSuggestion(draft, id, decision, text);
    if (!report.ok) {
      setProblem(report.errors[0].message);
      return;
    }
    setProblem("");
    setDraft(report.value);
    setEditingId(null);
    const remaining = report.value.suggestions.filter((s) => s.decision === "pending").length;
    wcopAnnounce("Marked " + decision + ". " + (remaining === 0 ? "All suggestions decided." : remaining + " still to decide."));
  }
  function startEdit(suggestion) {
    setEditingId(suggestion.id);
    setEditText(suggestion.approvedText || (suggestion.result === "insufficient_evidence" ? suggestion.note : suggestion.objectiveEvidence));
    wcopAnnounce("Editing. The cited excerpt does not change when you reword the feedback.");
  }
  function setDisclosureText(value) {
    const next = JSON.parse(JSON.stringify(draft));
    next.disclosure.text = value;
    setDraft(next);
  }
  function toggleFormative() {
    const next = JSON.parse(JSON.stringify(draft));
    next.disclosure.includeFormativeSentence = !next.disclosure.includeFormativeSentence;
    setDraft(next);
  }
  function compare() {
    const report = core.compareToReference(scenario, draft);
    if (!report.ok) {
      setProblem(report.errors[0].message);
      return;
    }
    setProblem("");
    setComparison(report.value);
    wcopAnnounce("Comparison ready. " + report.value.agreements.length + " agreements, " + report.value.divergences.length + " differences to talk about.");
  }
  function copyText(text, what) {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(
          () => wcopAnnounce(what + " copied."),
          () => wcopAnnounce("Could not copy. Select the text and copy manually.")
        );
        return;
      }
    } catch (err) {
    }
    wcopAnnounce("Could not copy. Select the text and copy manually.");
  }
  function clearAll() {
    core.clearDraft(draft);
    setDraft(null);
    setScenario(null);
    setNotes("");
    setComparison(null);
    setStage("capture");
    wcopAnnounce("Cleared. Nothing was kept.");
  }
  const readiness = draft ? core.exportReadiness(draft) : null;
  function stageReachable(id) {
    if (id === "capture") return true;
    if (!draft) return false;
    if (id === "analyze") return true;
    const decided = draft.suggestions.every((s) => s.decision !== "pending");
    if (id === "feedback") return decided;
    if (id === "copy") return !!readiness && readiness.ok;
    return false;
  }
  const banner = React.createElement(
    "div",
    {
      className: "flex flex-wrap gap-x-4 gap-y-1 items-center rounded border border-violet-300 bg-violet-50 text-violet-800 px-3 py-2 text-sm font-semibold mb-3"
    },
    React.createElement("span", null, draft && draft.mode === "approved" ? "Approved mode" : "Demo mode"),
    React.createElement("span", { className: "opacity-60 font-normal" }, "|"),
    React.createElement(
      "span",
      { className: "font-normal" },
      "Synthetic practice only. Nothing here is a record of a real observation."
    ),
    React.createElement("span", { className: "opacity-60 font-normal" }, "|"),
    React.createElement("span", { className: "font-normal" }, "Nothing is saved. Closing discards everything.")
  );
  const nav = React.createElement(
    "ol",
    { className: "flex flex-wrap gap-2 mb-4 list-none p-0" },
    WCOP_STAGES.map((s) => React.createElement(
      "li",
      { key: s.id, className: "flex-1 min-w-[9rem]" },
      React.createElement(
        "button",
        {
          type: "button",
          disabled: !stageReachable(s.id) && stage !== s.id,
          "aria-current": stage === s.id ? "step" : void 0,
          onClick: () => setStage(s.id),
          className: "w-full text-left rounded border px-3 py-2 text-sm " + (stage === s.id ? "border-teal-600 text-slate-800 bg-white" : "border-slate-200 text-slate-500 bg-white") + (!stageReachable(s.id) && stage !== s.id ? " opacity-50 cursor-not-allowed" : "")
        },
        React.createElement("span", { className: "block text-[10px] uppercase tracking-wider opacity-75" }, s.n),
        React.createElement("span", null, s.label)
      )
    ))
  );
  let bodyNode = null;
  if (stage === "capture") {
    bodyNode = React.createElement(
      "div",
      null,
      introOpen ? React.createElement(WcopIntro, { onHide: () => setIntroOpen(false) }) : React.createElement("button", {
        type: "button",
        className: "mb-4 px-3 py-1.5 rounded border border-slate-300 text-sm",
        onClick: () => setIntroOpen(true)
      }, "What is this?"),
      React.createElement(
        "div",
        { className: "rounded-lg border border-slate-200 bg-white p-4 mb-4" },
        React.createElement("h3", { className: "font-bold text-slate-800 mb-1" }, "Choose a practice scenario"),
        React.createElement(
          "p",
          { className: "text-xs text-slate-500 mb-3" },
          "Each scenario is a synthetic observation that teaches one habit of evidence-based feedback. They carry their own suggestions, so nothing here calls an AI service."
        ),
        scenarioLib.listScenarios().map((meta) => React.createElement(
          "button",
          {
            key: meta.id,
            type: "button",
            "aria-pressed": !!scenario && scenario.id === meta.id,
            onClick: () => pickScenario(meta.id),
            className: "block w-full text-left rounded border px-3 py-2 mb-2 " + (scenario && scenario.id === meta.id ? "border-teal-600 bg-teal-50" : "border-slate-200 bg-white")
          },
          React.createElement("span", { className: "block font-semibold text-sm text-slate-800" }, meta.title),
          React.createElement(
            "span",
            { className: "block text-xs text-slate-500" },
            meta.setting + " | about " + meta.minutes + " minutes | teaches: " + meta.teaches
          )
        ))
      ),
      React.createElement(
        "div",
        { className: "rounded-lg border border-slate-200 bg-white p-4" },
        React.createElement("h3", { className: "font-bold text-slate-800 mb-1" }, "The observer notes"),
        React.createElement(
          "p",
          { className: "text-xs text-slate-500 mb-2" },
          "This is the shorthand someone typed during the visit. Locking it means your original wording is kept exactly as written for the rest of the session, so nothing can quietly tidy it up, summarize it, or put words in your mouth. Every claim later has to point back to a line in here."
        ),
        React.createElement("textarea", {
          className: "w-full rounded border border-slate-300 p-2 font-mono text-[13px]",
          rows: 10,
          "aria-label": "Observation notes",
          value: notes,
          onChange: (e) => setNotes(e.target.value)
        }),
        edited ? React.createElement(
          WcopFlag,
          null,
          "You have changed the scenario notes. The prepared suggestions quote the original wording, so they no longer match and cannot be used. Restore the notes to continue. Analyzing notes you write yourself needs an approved AI provider, which is not connected here."
        ) : null,
        React.createElement(
          "div",
          { className: "flex flex-wrap gap-2 mt-3" },
          React.createElement("button", {
            type: "button",
            disabled: !scenario || edited,
            onClick: lockAndAnalyze,
            className: "px-4 py-2 rounded bg-teal-700 text-white text-sm font-semibold " + (!scenario || edited ? "opacity-50 cursor-not-allowed" : "")
          }, "Lock these notes and see suggestions"),
          edited ? React.createElement("button", {
            type: "button",
            className: "px-3 py-2 rounded border border-slate-300 text-sm",
            onClick: () => {
              setNotes(scenario.notes);
              wcopAnnounce("Scenario notes restored.");
            }
          }, "Restore scenario notes") : null,
          !scenario ? React.createElement(
            "span",
            { className: "text-xs text-slate-500 self-center" },
            "Pick a scenario first."
          ) : null
        )
      )
    );
  } else if (stage === "analyze" && draft) {
    const total = draft.suggestions.length;
    const settled = draft.suggestions.filter((s) => s.decision !== "pending").length;
    bodyNode = React.createElement(
      "div",
      { className: "grid gap-4 md:grid-cols-[22rem_minmax(0,1fr)] items-start" },
      React.createElement(WcopFrozenNotes, { notes: draft.sourceNotesOriginal }),
      React.createElement(
        "div",
        null,
        React.createElement("h3", { className: "font-bold text-slate-800" }, "Your call on each suggestion"),
        React.createElement(
          "p",
          { className: "text-sm font-bold text-teal-700 mb-1", role: "status" },
          settled === total ? "All " + total + " decided. You can move on." : settled + " of " + total + " decided."
        ),
        React.createElement(
          "p",
          { className: "text-xs text-slate-500 mb-3" },
          "Nothing reaches your form until you decide on it. Keep what the notes genuinely support, reword anything you would put differently, and throw out the rest. Rejecting a lot is a normal outcome, not a sign something went wrong."
        ),
        draft.suggestions.map((s) => React.createElement(WcopSuggestion, {
          key: s.id,
          suggestion: s,
          core,
          componentLabel: componentLabels[s.componentId] || s.componentId,
          editing: editingId === s.id,
          editText,
          onEditText: setEditText,
          onStartEdit: startEdit,
          onDecide: decide
        })),
        draft.globalWarnings.map((w, i) => React.createElement(WcopFlag, { key: "g" + i }, w.message)),
        React.createElement("button", {
          type: "button",
          disabled: settled !== total,
          onClick: () => setStage("feedback"),
          className: "mt-3 px-4 py-2 rounded bg-teal-700 text-white text-sm font-semibold " + (settled !== total ? "opacity-50 cursor-not-allowed" : "")
        }, "Continue to the feedback")
      )
    );
  } else if (stage === "feedback" && draft) {
    const output = readiness.ok ? core.buildFormOutput(draft, fixtures.SAMPLE_FIELD_MAP) : null;
    bodyNode = React.createElement(
      "div",
      null,
      React.createElement("h3", { className: "font-bold text-slate-800 mb-2" }, "The feedback as the teacher will read it"),
      React.createElement(
        "div",
        { className: "rounded-lg border border-slate-200 bg-white p-4 mb-3" },
        React.createElement("h4", { className: "font-semibold text-sm mb-1" }, "Disclosure"),
        React.createElement(
          "p",
          { className: "text-xs text-slate-500 mb-2" },
          "This travels with every field you copy. You can reword it, but it cannot be empty, and the last sentence is a claim only your school can make truthfully."
        ),
        React.createElement(
          "label",
          { className: "block text-xs font-semibold mb-1", htmlFor: "wcop-disclosure" },
          "Disclosure wording"
        ),
        React.createElement("textarea", {
          id: "wcop-disclosure",
          className: "w-full rounded border border-slate-300 p-2 text-sm",
          rows: 3,
          value: draft.disclosure.text,
          onChange: (e) => setDisclosureText(e.target.value)
        }),
        React.createElement(
          "div",
          { className: "flex flex-wrap gap-2 items-center mt-2" },
          React.createElement("button", {
            type: "button",
            "aria-pressed": draft.disclosure.includeFormativeSentence,
            onClick: toggleFormative,
            className: "px-3 py-1.5 rounded border border-slate-300 text-sm"
          }, draft.disclosure.includeFormativeSentence ? "Formative sentence included" : "Formative sentence removed"),
          React.createElement("span", { className: "text-xs text-slate-500" }, draft.disclosure.formativeSentence)
        )
      ),
      readiness.ok ? React.createElement(
        WcopFlag,
        { tone: "go" },
        "Ready to copy. " + readiness.value.approvedCount + " approved item(s)."
      ) : readiness.errors.map((e, i) => React.createElement(WcopFlag, { key: i, tone: "stop" }, e.message)),
      output ? output.value.fields.map((f) => React.createElement(
        "div",
        {
          key: f.domainId,
          className: "rounded border border-slate-200 bg-white p-3 mt-2" + (f.empty ? " border-dashed" : "")
        },
        React.createElement("h4", { className: "font-semibold text-sm" }, f.key),
        React.createElement("pre", { className: "whitespace-pre-wrap break-words text-[13px] mt-1 font-mono" }, f.text)
      )) : null,
      React.createElement(
        "div",
        { className: "flex flex-wrap gap-2 mt-4" },
        React.createElement("button", {
          type: "button",
          disabled: !readiness.ok,
          onClick: () => setStage("copy"),
          className: "px-4 py-2 rounded bg-teal-700 text-white text-sm font-semibold " + (!readiness.ok ? "opacity-50 cursor-not-allowed" : "")
        }, "Continue to copy"),
        React.createElement("button", {
          type: "button",
          onClick: compare,
          className: "px-4 py-2 rounded border border-slate-300 text-sm font-semibold"
        }, "Compare with the reference reading")
      ),
      comparison ? React.createElement(
        "div",
        { className: "rounded-lg border border-slate-200 bg-white p-4 mt-3" },
        React.createElement("h4", { className: "font-semibold text-sm" }, "Your reading and the reference reading"),
        React.createElement("p", { className: "text-xs text-slate-500 mb-2" }, comparison.disclaimer),
        comparison.agreements.map((a, i) => React.createElement(
          WcopFlag,
          { key: "a" + i, tone: "go" },
          (a.componentId ? a.componentId + ": " : "") + a.note
        )),
        comparison.divergences.map((d, i) => React.createElement(
          WcopFlag,
          { key: "d" + i },
          (d.componentId ? d.componentId + ": " : "") + d.note
        )),
        comparison.referenceNote ? React.createElement("p", { className: "text-sm text-slate-700 mt-2" }, comparison.referenceNote) : null,
        comparison.discussion.length ? React.createElement(
          "div",
          { className: "mt-2" },
          React.createElement("p", { className: "text-[11px] uppercase tracking-wider text-slate-500 font-semibold" }, "Worth discussing"),
          React.createElement(
            "ul",
            { className: "list-disc ml-5 text-sm text-slate-700" },
            comparison.discussion.map((p, i) => React.createElement("li", { key: i }, p))
          )
        ) : null
      ) : null
    );
  } else if (stage === "copy" && draft) {
    const output = core.buildFormOutput(draft, fixtures.SAMPLE_FIELD_MAP);
    bodyNode = output.ok ? React.createElement(
      "div",
      null,
      React.createElement("h3", { className: "font-bold text-slate-800 mb-1" }, "Copy into your walkthrough form"),
      React.createElement(
        "p",
        { className: "text-xs text-slate-500 mb-3" },
        "This tool does not submit anything, send anything, or store anything. You paste these into the form your school already uses."
      ),
      React.createElement("button", {
        type: "button",
        onClick: () => copyText(output.value.copyAll, "All fields"),
        className: "px-4 py-2 rounded bg-teal-700 text-white text-sm font-semibold mb-3"
      }, "Copy everything"),
      output.value.contextFields.concat(output.value.fields).map((f, i) => React.createElement(
        "div",
        {
          key: "f" + i,
          className: "rounded border border-slate-200 bg-white p-3 mb-2" + (f.empty ? " border-dashed" : "")
        },
        React.createElement(
          "div",
          { className: "flex items-center justify-between gap-2" },
          React.createElement("h4", { className: "font-semibold text-sm" }, f.key),
          React.createElement("button", {
            type: "button",
            onClick: () => copyText(f.text, f.key),
            className: "px-3 py-1 rounded border border-slate-300 text-sm"
          }, "Copy")
        ),
        React.createElement("pre", { className: "whitespace-pre-wrap break-words text-[13px] mt-1 font-mono" }, f.text)
      )),
      React.createElement("button", {
        type: "button",
        onClick: clearAll,
        className: "mt-3 px-3 py-2 rounded border border-slate-300 text-sm"
      }, "Clear and start over")
    ) : React.createElement(WcopFlag, { tone: "stop" }, output.errors[0].message);
  }
  return React.createElement(
    "div",
    { className: "p-4" },
    banner,
    nav,
    problem ? React.createElement(WcopFlag, { tone: "stop" }, problem) : null,
    bodyNode,
    React.createElement(
      "div",
      { className: "mt-6 pt-3 border-t border-slate-200 text-xs text-slate-500" },
      React.createElement(
        "p",
        null,
        "Formative walkthrough and coaching support. This tool never assigns a rating, calculates a summative score, or makes an employment recommendation."
      ),
      React.createElement(
        "p",
        { className: "mt-1" },
        "Practice material here is invented. Before using this with a real staff member, confirm with your district which AI provider may process observation notes, whether a walkthrough counts as evidence in your evaluation system, and how long anything typed here is retained."
      ),
      React.createElement("p", { className: "mt-1" }, scenarioLib.DISCLAIMER)
    )
  );
}

  window.AlloModules = window.AlloModules || {};
  // The bundled core already registered its API under this key. Merge rather
  // than replace, so the panel and the core logic share one namespace and
  // neither clobbers the other.
  var wcopCoreApi = window.AlloModules.WalkthroughCopilot || {};
  var wcopMerged = {};
  Object.keys(wcopCoreApi).forEach(function(k) { wcopMerged[k] = wcopCoreApi[k]; });
  wcopMerged.WalkthroughCopilotPanel = WalkthroughCopilotPanel;
  wcopMerged._testing = {
    WcopSuggestion: WcopSuggestion,
    WcopIntro: WcopIntro,
    WcopFlag: WcopFlag,
    WcopFrozenNotes: WcopFrozenNotes,
    WCOP_STAGES: WCOP_STAGES,
    WCOP_STEPS: WCOP_STEPS,
    WCOP_ADVISORY_QUESTIONS: WCOP_ADVISORY_QUESTIONS
  };
  window.AlloModules.WalkthroughCopilot = wcopMerged;
  console.log('[CDN] WalkthroughCopilot loaded');
})();
