const fs=require('fs'),path=require('path'),assert=require('assert'); const out='reports/startup-recovery-enhancements-2026-09-29',scratch='C:/tmp/alloflow_dispatch/wave2/startup-recovery-2026-09-29/proofs';fs.mkdirSync(scratch,{recursive:true}); const host=fs.readFileSync('AlloFlowANTI.txt','utf8'),phase=fs.readFileSync('phase_k_helpers_source.jsx','utf8'),adventure=fs.readFileSync('adventure_handlers_source.jsx','utf8');
function replace(s,a,b){assert.equal(s.split(a).length,2,a);return s.replace(a,b)}
const hostCase=(name,a,b,test,pattern)=>({name,env:'ALLO_ANTI_CANDIDATE',extension:'txt',source:replace(host,a,b),test,pattern});
const runtime='tests/project_save_cancellation_encryption.test.js',ready='tests/k5_save_adventure_readiness.test.js';
const cases=[
 hostCase('stale-project-save','      if (!isCurrent()) return cancelled;','      if (false) return cancelled;',ready,'save startup readiness discards a delayed request after saveFileName changes'),
 hostCase('stale-adventure-start','      if (request !== adventureStartRequestRef.current || context !== adventureStartContextRef.current) return false;','      if (false) return false;',ready,'start startup readiness discards a delayed request after adventureState changes'),
 hostCase('stale-adventure-turn','      if (request !== diceCompleteRequestRef.current || context !== diceCompleteContextRef.current) return false;','      if (false) return false;',ready,'dice startup readiness discards a delayed request after pendingAdventureUpdate changes'),
 {name:'missing-encryption-plaintext',env:'ALLO_PHASE_K_CANDIDATE',extension:'js',source:replace(phase,'      if (deps.saveEncryptPassword) {','      if (deps.saveEncryptPassword && window.AlloModules && window.AlloModules.AlloCrypto) {'),test:runtime,pattern:'does not download plaintext when the crypto API is unavailable'},
 {name:'download-after-cancel',env:'ALLO_PHASE_K_CANDIDATE',extension:'js',source:replace(phase,"      if (!saveStillCurrent()) return cancelledSave;\n      const blob = new Blob",'      const blob = new Blob'),test:runtime,pattern:'cancels after encryption completes'},
 {name:'restart-after-context-change',env:'ALLO_ADVENTURE_CANDIDATE',extension:'jsx',source:replace(adventure,"      if (typeof deps.isAdventureStartCurrent === 'function' && !deps.isAdventureStartCurrent()) return false;\n      if (alloBotRef.current)","      if (alloBotRef.current)"),test:runtime,pattern:'keeps the current story if it changes while the restart dialog is open'},
];
fs.writeFileSync(out+'/proof-cases.json',JSON.stringify(cases.map(({source,...c})=>c),null,2));
for(const c of cases){const file=path.join(scratch,c.name+'.'+c.extension);fs.writeFileSync(file,c.env==='ALLO_PHASE_K_CANDIDATE'?require('esbuild').transformSync(c.source,{loader:'jsx',jsxFactory:'React.createElement',jsxFragment:'React.Fragment',target:'es2020'}).code:c.source);c.candidate=file;delete c.source;}fs.writeFileSync(scratch+'/cases.json',JSON.stringify(cases,null,2));console.log('Wrote 6 isolated candidates.');
