'use strict';

const { CORE_PAGE, READING, WRITING, MATH, CCSS_ELA, CCSS_MATH } = require('./sources.cjs');

function chapter(id, skillId, title, summary, objectives, topics) {
  return {
    id, skillId, title, summary, objectives,
    sections: topics.map(([heading, principle, terms]) => ({
      heading,
      content: principle + ' On Praxis Core, solve the task that is actually stated rather than a broader task you expected. Identify the controlling evidence or relationship, make the reasoning explicit, and test the result against the passage, sentence, source boundary, representation, equation, or unit. A defensible response preserves qualifications and avoids adding facts that the prompt does not supply. During review, name both why the best response works and what specific misconception, unsupported inference, language error, or quantitative error makes each alternative less defensible. That comparison turns feedback into a reusable decision rule instead of a memorized answer.',
      keyTerms: terms,
    })),
  };
}

const chapters = [
  chapter('core5752-ch-01', 'reading-key-ideas-details', 'Main Ideas, Supporting Details, and Inferences', 'Build passage-grounded summaries and inferences while preserving the author\'s scope and qualifications.', ['Distinguish a main idea from a memorable detail.', 'Locate evidence for explicit and implied claims.', 'Reject choices that overstate or import outside knowledge.'], [
    ['Main idea and primary purpose', 'A main idea states what the passage centrally says; primary purpose states what the author is doing with that content. Draft a brief statement that covers the whole selection, then check every paragraph or sentence cluster against it. A choice that captures only the opening example, one consequence, or an attractive topic word is too narrow.', ['main idea', 'primary purpose', 'scope']],
    ['Supporting ideas and detail', 'Supporting evidence develops the central point through examples, reasons, definitions, comparisons, data, or consequences. Trace the question language back to the relevant sentence and then read around it for qualification. The correct response must paraphrase accurately rather than merely repeat a nearby word.', ['supporting detail', 'paraphrase', 'evidence']],
    ['Inference and implication', 'A warranted inference is not directly stated, but it follows from the passage with minimal additional assumptions. Build it as a short chain from two or more textual facts. If a choice could be true in the real world but cannot be defended from this selection, it is not the best answer.', ['inference', 'implication', 'assumption']],
    ['Summary boundaries', 'An accurate summary preserves the passage\'s direction, important relationship, and degree of certainty. Watch for absolute language replacing may, some, often, or in this sample. Also reject summaries that reverse cause and effect, confuse a proposal with an outcome, or treat a limitation as the main conclusion.', ['summary', 'qualification', 'causal direction']],
  ]),
  chapter('core5752-ch-02', 'reading-craft-structure-language', 'Craft, Structure, Tone, and Vocabulary in Context', 'Analyze how wording, transitions, organization, and rhetorical choices shape meaning.', ['Identify tone from specific language rather than topic alone.', 'Explain the function of a sentence or transition.', 'Derive contextual meaning and organizational pattern.'], [
    ['Tone and attitude', 'Tone is the author\'s stance as conveyed by evaluative words, intensity, qualification, irony, and selection of detail. Separate the emotional subject matter from the language used to discuss it. A passage about a serious problem can still be measured, analytical, skeptical, hopeful, or cautiously supportive.', ['tone', 'attitude', 'connotation']],
    ['Organization and transitions', 'Structure reveals how ideas relate: sequence, cause and effect, compare and contrast, problem and solution, classification, or claim and evidence. Transition words are clues but not substitutes for reading the full relationship. State the role of each paragraph in a few words to see the architecture.', ['organization', 'transition', 'rhetorical function']],
    ['Vocabulary in context', 'Contextual meaning comes from how a word functions in the sentence and passage, including contrasts, examples, restatements, and tone. Substitute each option into the sentence and check both denotation and connotation. The everyday meaning may be wrong when the author uses a technical or figurative sense.', ['context clue', 'denotation', 'connotation']],
    ['Purpose of evidence and examples', 'A sentence may define, illustrate, qualify, concede, contrast, provide evidence, or connect a premise to a conclusion. Describe what changes if the sentence is removed. This functional test prevents confusing the topic of a sentence with its role in the author\'s reasoning.', ['example', 'qualification', 'concession']],
  ]),
  chapter('core5752-ch-03', 'reading-integration-knowledge-ideas', 'Arguments, Visual Information, and Paired Texts', 'Evaluate evidence, assumptions, graphics, and relationships across sources without overclaiming.', ['Evaluate whether evidence strengthens or weakens a claim.', 'Interpret visuals using labels, scales, and limitations.', 'Compare and synthesize two texts accurately.'], [
    ['Claims, reasons, and assumptions', 'Map an argument as conclusion, stated reasons, evidence, and the unstated bridge connecting them. A strengthening choice supports a vulnerable bridge or rules out an alternative explanation; a weakening choice does the reverse. Evidence about a side issue may be true yet irrelevant.', ['claim', 'premise', 'assumption']],
    ['Evidence quality and causation', 'Judge evidence by relevance, representativeness, measurement, comparison, and scope. Association can support a relationship without proving that one variable caused the other. Self-selection, missing comparison groups, prior trends, small convenience samples, and unmeasured alternatives limit causal claims.', ['association', 'causation', 'representativeness']],
    ['Charts, tables, and diagrams', 'Read the title, variables, units, categories, legend, scale, and time period before interpreting a visual. Distinguish counts from percentages and absolute from relative change. A graph can display a pattern but cannot by itself establish the mechanism that produced it.', ['scale', 'absolute change', 'relative change']],
    ['Paired-text comparison and synthesis', 'Compare texts along a shared question: position, evidence, assumptions, purpose, scope, and qualification. Synthesis does more than list two summaries; it states how the ideas agree, differ, complement, or constrain each other. Preserve each author\'s distinct claim.', ['paired texts', 'agreement', 'synthesis']],
  ]),
  chapter('core5752-ch-04', 'writing-production-revision', 'Argument, Organization, Revision, and Synthesis', 'Develop and revise focused writing for an educated adult audience.', ['Create a defensible thesis and logical organization.', 'Revise for unity, development, coherence, and tone.', 'Integrate and explain evidence rather than merely inserting it.'], [
    ['Thesis, audience, and purpose', 'A useful thesis answers the assigned question, takes a clear position or establishes an explanatory focus, and defines a manageable scope. It should guide selection and organization of evidence. Match tone and background explanation to educated adult readers without assuming specialized knowledge.', ['thesis', 'audience', 'purpose']],
    ['Development and organization', 'Organize around reasons, criteria, causes, stages, or concepts rather than around the order in which ideas occurred to you. Each paragraph needs a controlling idea, relevant support, explanation, and a connection to the larger line of reasoning. Parallel criteria strengthen comparisons.', ['development', 'paragraph unity', 'coherence']],
    ['Revision in context', 'Revision considers the passage as a whole before correcting a local sentence. Ask whether material is relevant, logically placed, sufficiently explained, and consistent in tone. Use transitions to name genuine relationships; adding however or therefore cannot repair reasoning that is not actually contrastive or causal.', ['revision', 'transition', 'logical flow']],
    ['Evidence integration and conclusions', 'Introduce evidence with enough source context, represent it accurately, and explain its significance. A conclusion should synthesize the reasoning and clarify implications without opening a new unsupported argument. Counterclaims are strongest when represented fairly and answered with evidence.', ['evidence integration', 'counterclaim', 'conclusion']],
  ]),
  chapter('core5752-ch-05', 'writing-language-usage', 'Usage, Sentence Structure, Mechanics, and Word Choice', 'Apply standard written English conventions in meaningful sentence and passage contexts.', ['Maintain agreement, reference, tense, and parallelism.', 'Correct sentence boundaries and modifiers.', 'Choose precise, concise, and appropriately punctuated language.'], [
    ['Agreement and pronoun reference', 'Find the grammatical head of the subject rather than agreeing with the nearest noun. Interrupting phrases such as along with do not change number. Pronouns must have clear antecedents and consistent person and number; repeat a noun when concision would create ambiguity.', ['subject-verb agreement', 'antecedent', 'pronoun reference']],
    ['Sentence boundaries and clauses', 'An independent clause can stand alone; a dependent clause cannot. Repair fragments, run-ons, and comma splices using a period, semicolon, or comma plus coordinating conjunction as the relationship requires. Punctuation must reflect the underlying clause structure.', ['independent clause', 'fragment', 'comma splice']],
    ['Modifiers, parallelism, and tense', 'Place modifiers beside what they logically describe and ensure an introductory modifier names the following subject. Coordinated ideas should use matching grammatical forms. Maintain tense unless the time relationship genuinely changes, and use sequence cues to make that change clear.', ['modifier', 'parallel structure', 'verb tense']],
    ['Mechanics, diction, and concision', 'Punctuation marks relationships and possession; it is not decorative. Choose words for exact meaning and appropriate tone, then remove redundancy, inflated phrases, and empty qualifiers. The shortest option is not automatically best if it changes emphasis, logic, or necessary detail.', ['mechanics', 'diction', 'concision']],
  ]),
  chapter('core5752-ch-06', 'writing-research-sources', 'Research Strategy, Source Credibility, Citation, and Synthesis', 'Plan focused research and preserve accurate evidence provenance.', ['Select authoritative sources suited to a research need.', 'Evaluate methods, scope, currency, and conflicts.', 'Paraphrase, cite, compare, and synthesize responsibly.'], [
    ['Focused questions and search strategy', 'Translate a broad topic into a question specifying population, intervention or issue, outcome, place, and time when relevant. Generate synonyms and search in stages. Begin with authoritative overviews to learn vocabulary, then follow citations and data links toward the primary evidence.', ['research question', 'search terms', 'primary source']],
    ['Credibility and applicability', 'Authority is contextual: an official record is appropriate for current law, while a peer-reviewed empirical study may be better for a causal research claim. Examine authorship, method, sample, measures, date, revision status, funding, limitations, and fit with the exact claim.', ['credibility', 'methodology', 'applicability']],
    ['Quotation, paraphrase, and citation', 'Quote when exact wording matters; otherwise paraphrase by rebuilding the idea in independent language and structure. Both require attribution when the idea is not common knowledge. Record source metadata during note taking so citations are accurate and copied wording remains visibly marked.', ['quotation', 'paraphrase', 'attribution']],
    ['Comparing and synthesizing sources', 'Before treating sources as contradictory, align their definitions, populations, dates, measures, and purposes. Synthesis explains patterns and differences across evidence and ties them to the writer\'s question. Do not select only agreeable findings or erase uncertainty.', ['source comparison', 'synthesis', 'uncertainty']],
  ]),
  chapter('core5752-ch-07', 'math-number-operations', 'Number Forms, Operations, and Quantitative Reasoning', 'Work accurately with integers, fractions, decimals, factors, place value, and estimation.', ['Choose operations from quantitative relationships.', 'Move among fraction, decimal, and integer forms.', 'Estimate and verify reasonableness.'], [
    ['Integers and operation meaning', 'Represent direction, change, grouping, comparison, and distance before calculating. Subtracting a negative adds its opposite, while absolute value measures distance from zero. Write a short equation from the verbal relationship to prevent relying on isolated keywords.', ['integer', 'opposite', 'absolute value']],
    ['Fractions and decimals', 'Use common denominators to add or subtract fractions and invert only the divisor when dividing. Place-value alignment matters in decimal operations. Convert forms when it reveals the relationship, then simplify and check whether the size of the answer is plausible.', ['common denominator', 'reciprocal', 'place value']],
    ['Factors, multiples, and number properties', 'Prime factorization supports greatest common factors, least common multiples, and divisibility reasoning. Distinguish an expression that equals a number from its prime factorization, which contains prime factors only. Use distributive and associative properties deliberately.', ['prime factorization', 'greatest common factor', 'least common multiple']],
    ['Estimation and verification', 'Estimate before exact computation using compatible numbers, magnitude, sign, and bounds. After solving, substitute or reverse the operation and inspect units. A calculator can execute entries but cannot decide which relationship or interpretation the problem requires.', ['estimation', 'magnitude', 'inverse operation']],
  ]),
  chapter('core5752-ch-08', 'math-ratios-percent-measurement', 'Ratios, Proportions, Percent, Rates, and Measurement', 'Model multiplicative comparisons and convert units with transparent reasoning.', ['Compute and interpret unit rates and proportions.', 'Solve percent change and discount problems.', 'Convert measurements and apply scale.'], [
    ['Ratios, proportions, and unit rates', 'A ratio compares quantities multiplicatively; a unit rate expresses the amount per one unit. Build equivalent ratios only when the relationship is proportional. Tables, double number lines, and equations such as y = kx can expose the constant of proportionality.', ['ratio', 'proportion', 'unit rate']],
    ['Percent and percent change', 'Percent means per hundred. Identify the base before multiplying: part = rate times whole. Percent change uses change divided by the original value, not the new value. A discount gives the amount removed; subtract it or multiply by the remaining percent for the final price.', ['percent', 'base', 'percent change']],
    ['Rates and dimensional reasoning', 'Label every rate and carry units through multiplication or division. Units can show whether an operation is sensible: miles divided by hours produces miles per hour. When multiple rates interact, write the quantity and unit at each step rather than multiplying every visible number.', ['rate', 'dimension', 'constant rate']],
    ['Measurement, conversion, and scale', 'Use conversion factors equal to one so unwanted units cancel. Linear scale factors multiply lengths; areas change by the square and volumes by the cube of that factor. Draw and label a representation before substituting values into a formula.', ['conversion factor', 'scale factor', 'measurement']],
  ]),
  chapter('core5752-ch-09', 'math-data-displays', 'Data Displays and Descriptive Measures', 'Read representations carefully and summarize distributions without visual or numerical distortion.', ['Interpret tables, graphs, scales, and units.', 'Compute and compare center and spread.', 'Identify unsupported conclusions from displays.'], [
    ['Reading tables and graphs', 'Start with title, variables, categories, units, legend, axes, intervals, and source. Extract exact values before describing a trend. A truncated or nonlinear axis may emphasize differences, so compare the visual impression with the actual numerical change.', ['axis', 'legend', 'truncated scale']],
    ['Mean, median, mode, and range', 'Mean balances all values, median identifies the ordered midpoint, mode identifies frequency, and range describes total spread. Select a measure based on the question and distribution. Outliers can move the mean and range substantially while leaving the median more stable.', ['mean', 'median', 'range']],
    ['Distribution and comparison', 'Compare groups using center, spread, shape, and unusual values rather than one statistic alone. Equal means do not imply equal distributions, and a difference in averages does not show that every observation in one group exceeds every observation in another.', ['distribution', 'variability', 'outlier']],
    ['Claims from data displays', 'A display supports only what its variables, sample, and design measure. It may show association or change without explaining why. Look for denominator changes, missing categories, inconsistent intervals, and whether a count or percentage provides the appropriate comparison.', ['denominator', 'association', 'data claim']],
  ]),
  chapter('core5752-ch-10', 'math-statistics-probability', 'Statistics, Sampling, Study Design, and Probability', 'Reason about uncertainty, samples, experimental design, and chance processes.', ['Distinguish samples, populations, and assignment methods.', 'Interpret variability and margins of error cautiously.', 'Compute simple and compound probabilities.'], [
    ['Samples and populations', 'The population is the group a conclusion concerns; the sample is the observed subset. Random sampling supports generalization by reducing selection bias, while convenience and voluntary-response samples can differ systematically. Sample size does not repair a badly biased selection process.', ['population', 'random sample', 'selection bias']],
    ['Experiments and observational studies', 'Random assignment helps balance other variables and supports causal comparison within a study. Random sampling serves a different purpose: population representativeness. Observational studies can reveal associations but usually retain alternative explanations and confounding.', ['random assignment', 'observational study', 'confounding']],
    ['Uncertainty and inference', 'Statistics estimate population features with uncertainty. A margin of error gives a range around an estimate under stated assumptions; it is not the probability that every individual lies in that range. Practical importance also depends on context, variation, and measurement quality.', ['margin of error', 'estimate', 'practical significance']],
    ['Probability models', 'Probability is favorable outcomes divided by equally likely possible outcomes when that model applies. For independent events, multiply probabilities for a joint outcome; for mutually exclusive alternatives, add. Listing ordered outcomes can prevent omissions and double counting.', ['sample space', 'independent events', 'mutually exclusive']],
  ]),
  chapter('core5752-ch-11', 'math-algebra-functions', 'Algebraic Expressions, Equations, Inequalities, and Functions', 'Translate relationships, preserve equality, and interpret representations.', ['Simplify expressions using properties.', 'Solve and verify equations and inequalities.', 'Interpret slope, functions, and linear models.'], [
    ['Expressions and properties', 'An expression represents a quantity but does not assert equality. Distribute multiplication across every term inside parentheses and combine only like terms. Substitution requires replacing the variable with the entire value, using parentheses when signs or powers could change meaning.', ['expression', 'distributive property', 'like terms']],
    ['Equations and inequalities', 'Maintain balance by applying equivalent operations to both sides. When multiplying or dividing an inequality by a negative value, reverse the inequality direction. Verify an equation solution by substitution and test an inequality with a value clearly inside the proposed solution set.', ['equation', 'inequality', 'solution set']],
    ['Functions and representations', 'A function assigns exactly one output to each input in its domain. Evaluate by substitution and connect tables, graphs, rules, and verbal descriptions. Attend to the domain and to whether a change is constant, multiplicative, or nonlinear.', ['function', 'domain', 'representation']],
    ['Linear relationships and slope', 'Slope is change in output divided by change in input and carries units. In y = mx + b, m is the rate and b is the value when the input is zero. Decide whether that intercept is meaningful in context rather than interpreting it mechanically.', ['slope', 'intercept', 'linear model']],
  ]),
  chapter('core5752-ch-12', 'math-geometry-measurement', 'Geometry, Similarity, Area, Surface Area, and Volume', 'Use diagrams and formulas while preserving dimensions and scale relationships.', ['Apply angle and shape properties.', 'Use perimeter, area, circumference, and volume formulas.', 'Reason with similarity and the Pythagorean theorem.'], [
    ['Angles and shape properties', 'Use definitions and marked relationships rather than appearance. Vertical angles are congruent, a linear pair sums to 180 degrees, and triangle interior angles sum to 180 degrees in Euclidean geometry. Classify shapes by required properties, not by one familiar orientation.', ['vertical angles', 'supplementary', 'polygon']],
    ['Perimeter, area, and circumference', 'Perimeter and circumference measure boundary length; area measures two-dimensional coverage. Label formulas and units before substitution. Composite figures can be decomposed into nonoverlapping familiar shapes or treated as a larger shape minus a missing region.', ['perimeter', 'area', 'circumference']],
    ['Surface area and volume', 'Surface area totals exposed two-dimensional faces, while volume measures three-dimensional capacity. Sketch hidden faces, track square versus cubic units, and ask whether the context concerns material covering a container or space inside it.', ['surface area', 'volume', 'cubic units']],
    ['Similarity and right triangles', 'Similar figures have equal corresponding angles and proportional corresponding sides. A linear scale factor changes area by its square and volume by its cube. For right triangles, apply a squared plus b squared equals c squared with c opposite the right angle.', ['similarity', 'scale factor', 'Pythagorean theorem']],
  ]),
];

const memoryAids = [
  ['Whole-before-detail', 'State the passage topic plus the author\'s central claim or purpose before evaluating answer choices.', 'Reading: Key Ideas and Details', [READING, CCSS_ELA], ['reading', 'main idea']],
  ['Text-evidence chain', 'For an inference, point to the stated facts, name the smallest connecting step, and reject any conclusion requiring another unsupported assumption.', 'Reading: Key Ideas and Details', [READING, CCSS_ELA], ['reading', 'inference']],
  ['Tone from words', 'Name the evaluative words and qualifiers first; infer tone from language rather than from whether the topic feels positive or negative.', 'Reading: Craft, Structure, and Language', [READING, CCSS_ELA], ['reading', 'tone']],
  ['Structure labels', 'Give each paragraph a short job label such as problem, evidence, contrast, qualification, or recommendation.', 'Reading: Craft, Structure, and Language', [READING, CCSS_ELA], ['reading', 'structure']],
  ['Claim bridge test', 'Map claim, evidence, and the missing bridge; strengthening supports the bridge, while weakening breaks it or supplies an alternative explanation.', 'Reading: Integration of Knowledge and Ideas', [READING, CCSS_ELA], ['reading', 'argument']],
  ['Visual first scan', 'Read title, axes, units, scale, legend, and time period before interpreting any apparent trend.', 'Reading: Integration of Knowledge and Ideas', [READING, CCSS_ELA], ['reading', 'visuals']],
  ['Thesis compass', 'Answer the assigned question with a specific claim, reason, and scope that every body paragraph can advance.', 'Writing: Text Types, Purposes, and Production', [WRITING, CCSS_ELA], ['writing', 'thesis']],
  ['Paragraph engine', 'Use controlling idea, evidence, explanation, and connection; remove sentences that do not drive that sequence.', 'Writing: Text Types, Purposes, and Production', [WRITING, CCSS_ELA], ['writing', 'organization']],
  ['Clause boundary check', 'Locate subjects and finite verbs, decide which clauses can stand alone, and choose punctuation that matches the relationship.', 'Writing: Language and Research Skills', [WRITING, CCSS_ELA], ['writing', 'grammar']],
  ['Source trail', 'Record author, title, date, location, page or section, exact wording, and whether a note is a quote, paraphrase, or your analysis.', 'Writing: Language and Research Skills', [WRITING, CCSS_ELA], ['writing', 'research']],
  ['Sign-size-unit', 'Before calculating, predict the sign, approximate magnitude, and required unit; compare all three with the result.', 'Mathematics: Number and Quantity', [MATH, CCSS_MATH], ['math', 'verification']],
  ['Fraction operations', 'Common denominators for addition or subtraction; multiply across for multiplication; invert only the divisor for division.', 'Mathematics: Number and Quantity', [MATH, CCSS_MATH], ['math', 'fractions']],
  ['Percent base', 'Write part equals rate times whole and identify the original whole before computing percent change.', 'Mathematics: Number and Quantity', [MATH, CCSS_MATH], ['math', 'percent']],
  ['Units cancel', 'Write conversion factors as ratios equal to one and orient them so unwanted units cancel visibly.', 'Mathematics: Number and Quantity', [MATH, CCSS_MATH], ['math', 'measurement']],
  ['Graph inspection', 'Check axes, intervals, denominators, truncation, and whether the display shows count, rate, percentage, or average.', 'Mathematics: Data, Statistics, and Probability', [MATH, CCSS_MATH], ['math', 'data']],
  ['Center plus spread', 'Compare distributions using both center and variability; one average never describes every observation.', 'Mathematics: Data, Statistics, and Probability', [MATH, CCSS_MATH], ['math', 'statistics']],
  ['Sample versus assignment', 'Random sampling supports generalization; random assignment supports causal comparison. They solve different validity problems.', 'Mathematics: Data, Statistics, and Probability', [MATH, CCSS_MATH], ['math', 'study design']],
  ['Equation balance', 'Apply equivalent operations to both sides, isolate the variable, and verify by substitution.', 'Mathematics: Algebra and Geometry', [MATH, CCSS_MATH], ['math', 'algebra']],
  ['Slope units', 'Compute change in output over change in input and state what one unit of input predicts in context.', 'Mathematics: Algebra and Geometry', [MATH, CCSS_MATH], ['math', 'functions']],
  ['Dimension check', 'Boundary uses linear units, area uses square units, and volume uses cubic units; match the measure to the question.', 'Mathematics: Algebra and Geometry', [MATH, CCSS_MATH], ['math', 'geometry']],
].map(([title, content, domain, references, tags]) => ({ title, content, domain, references, tags }));

function workshop(index, taskType, title, prompt, stimulus, taskParts, sampleOutline) {
  return {
    id: 'core5752-cr-' + String(index).padStart(2, '0'), taskType, title, prompt, stimulus, taskParts,
    planningFrame: [
      { label: 'Task and position', guidance: 'Restate the exact assignment, audience, central claim or explanatory focus, and the limits you must preserve.' },
      { label: 'Evidence map', guidance: 'List the specific examples or source details you will use and the point each one supports.' },
      { label: 'Organization', guidance: 'Sequence paragraphs by reasons, criteria, concepts, or relationships and plan explicit transitions.' },
      { label: 'Review', guidance: 'Check development, synthesis, attribution, sentence clarity, usage, mechanics, and whether every claim stays within the evidence.' },
    ],
    successCriteria: [
      'Addresses every part of the assigned task with a clear controlling idea suited to educated adult readers.',
      'Uses specific, relevant support and explains how that support advances the reasoning rather than merely listing it.',
      'Maintains logical organization, coherent transitions, varied effective sentences, and an appropriate professional tone.',
      'Demonstrates control of standard written English and, for source-based work, represents and cites both sources accurately.',
    ],
    commonPitfalls: [
      'Rewriting the prompt without establishing a defensible thesis or explanatory focus.',
      'Listing examples or source statements without explaining relationships and significance.',
      'Overstating evidence, inventing source details, or ignoring an important qualification or counterpoint.',
      'Using most of the time to draft and leaving no review for organization, clarity, usage, or mechanics.',
    ],
    sampleOutline,
    references: [WRITING, CORE_PAGE, CCSS_ELA],
  };
}

const workshops = [
  workshop(1, 'Argumentative Essay', 'Access and flexibility in public services', 'Write an argumentative essay taking a position on whether public institutions should preserve an in-person option whenever they add a digital-only process. Support your position with specific reasons and examples for an educated adult audience.', 'A city department has moved several applications online. Supporters emphasize faster processing, fewer printing costs, and the ability to submit materials outside office hours. Critics note that some residents lack reliable internet, accessible technology, digital literacy, or a private place to upload documents. The assignment does not require specialized policy knowledge. Use observations, reading, or experience to develop a position, acknowledge meaningful tradeoffs, and avoid claims that every digital or in-person process works the same way.', ['State a qualified position on preserving an in-person option.', 'Develop at least two reasons with concrete examples and address a credible counterpoint.', 'Conclude by explaining the principle or practical consequence that should guide the decision.'], ['Thesis: preserve a meaningful alternative when access barriers would otherwise exclude users.', 'Body: efficiency benefits, access evidence, counterargument, and a feasible blended approach.', 'Conclusion: connect service design to both effectiveness and equitable access.']),
  workshop(2, 'Argumentative Essay', 'Depth versus breadth in required learning', 'Write an argumentative essay taking a position on whether introductory courses should cover many topics briefly or examine fewer topics in greater depth. Develop the argument with reasons and specific examples.', 'An introductory course has limited instructional time. One design surveys many concepts so learners recognize the field\'s range and vocabulary. Another concentrates on fewer concepts so learners practice analysis, feedback, and transfer. Either design can be implemented well or poorly, and the prompt does not assume that one approach is always correct. Define the conditions or goals that matter, build a clear line of reasoning, and use examples that an educated adult reader can understand without specialized background.', ['Take a clear, supportable position or establish conditions under which one approach is preferable.', 'Use specific examples to explain consequences for understanding, retention, or transfer.', 'Address a reasonable objection or limitation without abandoning the thesis.'], ['Thesis: favor depth for core transferable ideas while using a map of the broader field.', 'Body: learning benefits, curriculum tradeoff, counterpoint about exposure, and synthesis.', 'Conclusion: identify the design criterion that should control topic selection.']),
  workshop(3, 'Argumentative Essay', 'When pilot programs should expand', 'Write an argumentative essay explaining what evidence an organization should require before expanding a successful pilot program. Take a position and support it with concrete reasons and examples.', 'A small pilot can reveal whether an idea is feasible and promising, but participants, staff, setting, and resources may differ from those involved in full implementation. Immediate expansion may extend benefits quickly; slower expansion may permit replication and correction. The task is not to calculate a formal effect size or apply a specialized research standard. Instead, explain a defensible evidence threshold, the role of context and risk, and how decision makers should respond to uncertainty.', ['Define the evidence threshold you believe should precede expansion.', 'Explain at least two considerations such as replication, representativeness, implementation capacity, cost, or risk.', 'Address the strongest argument for expanding sooner or waiting longer.'], ['Thesis: scale in stages after credible outcome and implementation evidence, with threshold matched to risk.', 'Body: evidence quality, capacity, equity, counterargument about delay, and staged response.', 'Conclusion: explain how transparent checkpoints balance learning and action.']),
  workshop(4, 'Argumentative Essay', 'Value of revision after feedback', 'Write an argumentative essay taking a position on whether major assignments should ordinarily allow revision after feedback. Support your claim with relevant examples and address a meaningful limitation.', 'Revision can turn feedback into another learning cycle and reveal whether a learner can improve reasoning or communication. It also requires time, may complicate grading, and can become superficial if a learner merely follows corrections without understanding them. The question asks about ordinary practice rather than an exception for every task. Clarify what kind of revision process you support or oppose, why it serves the assignment\'s purpose, and how responsibility and fairness should be maintained.', ['State a qualified position on revision opportunities.', 'Develop reasons tied to learning, feedback use, responsibility, or assessment purpose.', 'Address workload, fairness, or dependency and propose a defensible boundary.'], ['Thesis: permit structured revision when the task measures developing performance.', 'Body: feedback cycle, evidence of learning, safeguards, and response to workload concerns.', 'Conclusion: connect revision rules to the construct and purpose of the assignment.']),
  workshop(5, 'Informative/Explanatory Source-Based Essay', 'Flexible scheduling and participation', 'Using both original sources below, write an informative/explanatory essay identifying the major considerations organizations should weigh when adopting flexible schedules. Accurately synthesize and cite both sources.', 'Source A - A six-month pilot at a regional service center allowed employees to begin between 7:00 and 10:00 a.m. Average self-reported schedule satisfaction increased, and late arrivals declined. The report cautioned that participants volunteered and that some client-facing roles could not vary their start times. Source B - Interviews at three small organizations found that flexible scheduling helped some workers coordinate transportation and caregiving. Managers also reported that unclear coverage expectations sometimes delayed handoffs. The authors recommended shared coverage windows, explicit responsibilities, and evaluation by role rather than assuming one schedule fits every position.', ['Explain at least one benefit supported by the sources.', 'Explain at least one limitation or implementation condition supported by the sources.', 'Synthesize how both sources inform a qualified organizational approach and cite each source.'], ['Introduction: define flexible scheduling and a balanced explanatory focus.', 'Body: Source A outcomes and limits; Source B access benefits and coordination conditions; synthesis.', 'Conclusion: explain why role-sensitive design and monitoring matter.']),
  workshop(6, 'Informative/Explanatory Source-Based Essay', 'Community cooling strategies', 'Using both original sources below, write an informative/explanatory essay explaining how communities can evaluate strategies for reducing extreme-heat exposure. Draw relevant evidence from and cite both sources.', 'Source A - Temperature sensors placed on twelve blocks recorded lower afternoon surface temperatures on blocks with mature tree canopy than on nearby blocks dominated by dark pavement. The project did not measure indoor temperatures or health outcomes and noted that tree benefits take time and require water and maintenance. Source B - A summer review of four public cooling centers found that attendance was highest at sites near frequent transit with evening hours. Interviews identified awareness, mobility, disability access, and trust as barriers. The review emphasized that cooling centers provide immediate refuge but do not by themselves change neighborhood heat conditions.', ['Describe what each strategy can contribute according to the sources.', 'Identify important evidence limits and access or implementation conditions.', 'Explain how the strategies may complement rather than replace one another, citing both sources.'], ['Introduction: distinguish immediate protection from longer-term heat reduction.', 'Body: canopy evidence and limits; cooling-center evidence and access; complementary strategy.', 'Conclusion: connect evaluation to time horizon, access, maintenance, and measured outcomes.']),
  workshop(7, 'Informative/Explanatory Source-Based Essay', 'Interpreting reminder interventions', 'Using both original sources below, write an informative/explanatory essay about when reminders are likely to improve participation and when other supports may be necessary. Cite and synthesize both sources.', 'Source A - In a randomized trial, applicants who received two deadline reminders completed a short renewal form at a higher rate than applicants who received no reminder. The form required information already available to most participants. Source B - A field study introduced appointment reminders at two clinics. Missed visits decreased modestly at the clinic with frequent transit service but changed little at the clinic where interviews identified transportation cost and limited routes as major barriers. The investigators cautioned that reminders address forgetting but cannot supply missing transportation or documents.', ['Explain the evidence that reminders can help.', 'Explain why results may differ when structural barriers remain.', 'Synthesize a decision rule for matching an intervention to the barrier, with citations to both sources.'], ['Introduction: frame reminders as one mechanism rather than a universal solution.', 'Body: Source A experimental evidence; Source B contextual contrast; barrier-intervention synthesis.', 'Conclusion: recommend diagnosing the participation barrier and measuring the intended outcome.']),
  workshop(8, 'Informative/Explanatory Source-Based Essay', 'Reading averages with context', 'Using both original sources below, write an informative/explanatory essay explaining why averages should be interpreted together with distribution and measurement information. Cite both sources accurately.', 'Source A - Two training groups each earned a mean score of 80. In Group 1, nearly all scores fell between 76 and 84. In Group 2, scores ranged from 52 to 100, with clusters near both ends. The evaluator warned that equal means did not describe the different patterns. Source B - A survey reported an average commute of 31 minutes, but the median was 24 minutes because a smaller number of very long commutes raised the mean. The survey included only employees who traveled to the central office and did not represent remote workers. Its authors recommended reporting multiple measures and the sampled population.', ['Explain what the mean reveals and what it can conceal in each source.', 'Discuss the role of spread, skew, median, and sample definition as supported by the sources.', 'Synthesize practical guidance for reporting an average, citing both sources.'], ['Introduction: state that an average is informative but incomplete.', 'Body: equal means with different spread; mean-median difference and sample boundary; synthesis.', 'Conclusion: recommend center, spread, distribution, and population context.']),
];

module.exports = { chapters, memoryAids, workshops };
