'use strict';const special=require('../special_education_5355/item_content.cjs'),ld=require('../special_education_learning_disabilities_5383/item_content.cjs');
const ETS='https://praxis.ets.org/on/demandware.static/-/Library-Sites-ets-praxisLibrary/default/pdfs/5372.pdf',EXAM='https://praxis.ets.org/test/special-education-teaching-students-with-behavioral-disorders-and-emotional-disturbances-5372.html',IDEA_FBA='https://sites.ed.gov/idea/regs/b/e/300.530',IES_BEHAVIOR='https://ies.ed.gov/ncee/wwc/PracticeGuide/31';
const domains={development:['development-characteristics-ebd','Development and Characteristics of Students with EBD'],planning:['planning-managing-learning-environments','Planning and Managing the Learning Environments'],instruction:['instruction','Instruction'],assessment:['assessment','Assessment'],professional:['foundations-professional-responsibilities','Foundations and Professional Responsibilities']};
const clean=v=>String(v).replace(/babyish/gi,'age-inappropriate').replace(/low functioning/gi,'described only by a global support-needs label').replace(/disability category/gi,'individual support profile').replace(/student with a disability/gi,'student with behavioral or emotional support needs');
function qs(parts,a,b){return parts.flatMap(([src,i,x,z])=>src[i].questions.slice(x,z)).map(q=>({...q,promptA:a+clean(q.promptA).replace(/^./,c=>c.toLowerCase()),promptB:b+clean(q.promptB).replace(/^./,c=>c.toLowerCase()),correct:clean(q.correct),distractors:q.distractors.map(clean),rationale:clean(q.rationale)+' For 5372 preparation, define behavior observably, examine ecological and instructional context, distinguish correlation from function, teach a usable replacement skill, use the least intensive effective response, preserve dignity and belonging, and monitor both outcomes and implementation.',difficulty:q.difficulty||'application'}))}
function bank(id,n,key,label,parts,a,b,refs=[]){const[domainId,domain]=domains[key];return{id,chapterId:'ebd5372-ch-'+String(n).padStart(2,'0'),domainId,domain,label,references:[ETS,EXAM,IDEA_FBA,IES_BEHAVIOR,...refs],questions:qs(parts,a,b)}}
module.exports=[
bank('development-context-variability',1,'development','Development, Context, Culture, and Learner Variability',[[special,0,0,9]],'When interpreting behavioral or emotional development, ','When a team compares student performance across settings and relationships, '),
bank('ebd-characteristics-coexisting-needs',2,'development','EBD Characteristics, Social-Emotional Development, and Coexisting Needs',[[special,1,0,9]],'For a student with behavioral or emotional support needs, ','When distinguishing an individual pattern from a diagnostic assumption, '),
bank('individualized-curriculum-programming',3,'planning','Individualized Curriculum, IEP Goals, and Longitudinal Programming',[[special,3,0,11]],'While planning an individualized program for a student with EBD, ','When aligning present levels, measurable goals, services, and progress evidence, '),
bank('positive-environments-prevention',4,'planning','Positive Environments, Prevention, Expectations, and Daily Routines',[[special,5,0,10]],'In a safe, equitable, positive learning environment, ','When preventing predictable behavior barriers before instruction begins, '),
bank('access-regulation-safety',5,'planning','Access, Self-Regulation, Sensory and Health Considerations, and Safety',[[special,2,0,5]],'When an access, regulation, sensory, or health factor may affect behavior, ','When coordinating a safe support without exceeding educator scope, '),
bank('academic-explicit-instruction',6,'instruction','Explicit Academic Instruction and Responsive Feedback',[[ld,5,0,10]],'During explicit academic instruction for a student with EBD, ','When academic task difficulty may be contributing to disengagement, '),
bank('communication-writing-self-advocacy',7,'instruction','Communication, Written Expression, Self-Advocacy, and Generalization',[[ld,6,0,8]],'While teaching communication, self-advocacy, or written expression, ','When helping a student generalize a constructive response across settings, '),
bank('strategy-instruction-self-monitoring',8,'instruction','Strategy Instruction, Task Analysis, Self-Monitoring, and Independence',[[ld,7,0,8]],'While selecting a worked example or self-monitoring routine, ','During scaffolded strategy instruction that will be faded toward independence, '),
bank('assessment-quality-observation',9,'assessment','Assessment Quality, Direct Observation, and Multiple-Source Evidence',[[special,6,0,8]],'When selecting or administering an assessment for a student with EBD, ','When evaluating the validity and accessibility of behavioral or academic evidence, '),
bank('fba-eligibility-progress-data',10,'assessment','FBA, Eligibility, Progress Monitoring, and Data-Based Decisions',[[special,7,0,8],[special,8,0,1]],'When conducting an FBA or interpreting eligibility and intervention evidence, ','When progress data are used to test a function hypothesis or revise support, '),
bank('law-ethics-rights',11,'professional','Law, Ethics, Rights, Equity, and Restrictive-Procedure Safeguards',[[special,9,0,7]],'When applying legal and ethical safeguards for a student with EBD, ','When a proposed behavioral response may affect dignity, access, placement, or rights, '),
bank('family-team-professional-practice',12,'professional','Family Partnership, Collaboration, Professional Learning, and Advocacy',[[special,10,0,6]],'During family and interdisciplinary collaboration for a student with EBD, ','When an educator coordinates roles, communicates progress, or advocates within professional scope, ')];module.exports.sources={ETS,EXAM,IDEA_FBA,IES_BEHAVIOR};
