import fs from 'node:fs';
import { test, expect } from '@playwright/test';
import { GlHarness } from './helpers/stem_gl_harness';
const harness = new GlHarness({ toolFile: 'stem_lab/stem_tool_anatomy.js', toolId: 'anatomy', width: 390, height: 1800, appStyles: true });
const locales = [{ language: 'french', code: 'fr', rtl: false }, { language: 'spanish_latin_america', code: 'es-419', rtl: false }, { language: 'arabic', code: 'ar', rtl: true }];
test.describe.configure({ timeout: 150000 });
test.beforeAll(async () => { await harness.start(); });
test.afterAll(async () => { await harness.stop(); });
for (const locale of locales) {
  test(locale.language + ' phone study controls support translated recall and notes', async ({ page }) => {
    const dictionary = JSON.parse(fs.readFileSync('lang/' + locale.language + '.js', 'utf8')).stem.anatomy;
    await page.setViewportSize({ width: 390, height: 844 });
    await harness.mount(page, { anatomy: { system: 'skeletal', view: 'anterior', complexity: 3, _activeTab: 'flashcards', _structureConfidence: { ribs: 'practice' } } }, undefined, { expectCanvas: false });
    await page.evaluate(({ dictionary, locale }) => {
      document.documentElement.lang = locale.code; document.documentElement.dir = locale.rtl ? 'rtl' : 'ltr';
      (window as any).__localeAnnouncements = [];
      (window as any).__ctx.t = (key: string, fallback: string) => key.startsWith('stem.anatomy.') ? dictionary[key.slice('stem.anatomy.'.length)] || fallback : fallback;
      (window as any).__ctx.announceToSR = (message: string) => (window as any).__localeAnnouncements.push(message);
      (window as any).__rerender();
    }, { dictionary, locale });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
    const skip = page.locator('[data-anatomy-skip="workspace"]');
    await skip.focus();
    const skipBounds = await skip.boundingBox();
    expect(skipBounds!.width).toBeGreaterThan(44);
    expect(skipBounds!.x).toBeGreaterThanOrEqual(0);
    expect(skipBounds!.x + skipBounds!.width).toBeLessThanOrEqual(390);
    expect(await skip.evaluate(node => getComputedStyle(node).clipPath)).toBe('none');
    await skip.press('Enter');
    await expect(page.locator('#anatomy-mode-panel')).toBeFocused();
    expect(await skip.evaluate(node => getComputedStyle(node).clipPath)).toBe('inset(50%)');
    const cards = page.locator('[data-anatomy-flashcards]'); const card = page.locator('[data-anatomy-recall-card]');
    const system = page.getByRole('combobox', { name: dictionary.body_system, exact: true });
    await expect(page.getByRole('combobox', { name: dictionary.learning_level, exact: true })).toHaveValue('3');
    await expect(page.locator('[data-anatomy-study-controls-toggle]')).toHaveText(dictionary.more_study_controls);
    await cards.getByRole('button', { name: dictionary.flashcard_due + ' (1)', exact: true }).click();
    const name = await card.locator('h3').innerText();
    const announcement = dictionary.flashcard_announcement.replace('{current}', '1').replace('{total}', '1').replace('{name}', name) + dictionary.answer_hidden;
    await expect.poll(() => page.evaluate(() => (window as any).__localeAnnouncements.at(-1))).toBe(announcement);
    await card.getByRole('button', { name: dictionary.reveal_function, exact: true }).click();
    await expect(cards.locator('.anatomy-confidence')).toContainText(dictionary.confidence_question);
    await cards.getByRole('button', { name: '~ ' + dictionary.learning, exact: true }).click();
    await expect(cards.locator('[data-anatomy-round-rated]')).toContainText(dictionary.flashcard_rated_round + '1 / 1');
    await cards.locator('[data-anatomy-flashcard-note] > summary').click();
    const note = cards.locator('textarea'); await note.fill(dictionary.own_words_placeholder);
    await expect(cards.locator('[data-anatomy-own-words] [role="status"]')).toHaveText(dictionary.own_words_saved);
    await card.getByRole('button', { name: dictionary.show_structure_name, exact: true }).click();
    await expect(note).toHaveCount(0);
    await card.getByRole('button', { name: dictionary.locate_flashcard, exact: true }).click();
    await expect.poll(() => page.evaluate(() => (window as any).__localeAnnouncements.at(-1))).toBe(announcement);
    await system.selectOption('respiratory'); await expect(cards).toContainText(dictionary.flashcard_none_due);
    await system.selectOption('skeletal'); await expect(card).toHaveAttribute('data-anatomy-recall-card', 'ribs');
    await cards.screenshot({ path: '.tmp/anatomy-study-' + locale.code + '-hidden-panel.png' });
    await card.getByRole('button', { name: dictionary.reveal_function, exact: true }).click();
    await cards.locator('[data-anatomy-flashcard-note] > summary').click();
    await expect(note).toHaveValue(dictionary.own_words_placeholder);
    const noteCounter = cards.locator('[data-anatomy-own-words] bdi');
    await expect(noteCounter).toHaveText(dictionary.own_words_placeholder.length + ' / 280');
    expect(await noteCounter.evaluate(node => getComputedStyle(node).direction)).toBe('ltr');
    expect(await cards.locator('[data-anatomy-round-rated] bdi').evaluate(node => getComputedStyle(node).direction)).toBe('ltr');
    expect(await note.evaluate(node => getComputedStyle(node).direction)).toBe(locale.rtl ? 'rtl' : 'ltr');
    expect(await card.evaluate(node => getComputedStyle(node).textAlign)).toBe('start');
    expect(await card.evaluate(node => getComputedStyle(node).direction)).toBe(locale.rtl ? 'rtl' : 'ltr');
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
    await page.addScriptTag({ path: 'node_modules/axe-core/axe.min.js' });
    const violations = await page.evaluate(async () => (await (window as any).axe.run(document.querySelector('[data-anatomy-tool]'), { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } })).violations.map((item: any) => ({ id: item.id, targets: item.nodes.map((node: any) => node.target) })));
    expect(violations).toEqual([]);
    await cards.screenshot({ path: '.tmp/anatomy-study-' + locale.code + '-panel.png' });
    expect(await page.evaluate(() => (window as any).__events.errors)).toEqual([]);
  });
}
