import { test, expect } from '@playwright/test';
import { GlHarness } from './helpers/stem_gl_harness';
const harness = new GlHarness({ toolFile: 'stem_lab/stem_tool_fisherlab.js', toolId: 'fisherLab', width: 1180, height: 980, appStyles: true, extraScripts: ['desktop/web-app/node_modules/axe-core/axe.min.js'] });
test.beforeAll(async () => { await harness.start(); });
test.afterAll(async () => { await harness.stop(); });
test.afterEach(async ({ page }) => { await harness.destroy(page); });
async function openLessons(page: any) {
  await harness.mount(page, {}, undefined, { expectCanvas: false });
  await page.locator('#fl-section-search').fill('lesson');
  await page.getByRole('button', { name: /Lesson Plans/ }).last().click();
}
test('launches the selected topic and resumes its draft without mixing investigations', async ({ page }) => {
  await openLessons(page);
  const navigation = page.locator('[data-fisherlab-lesson="navigation"]');
  const sampling = page.locator('[data-fisherlab-lesson="sampling"]');
  await expect(navigation.getByText('Support participation', { exact: true })).not.toBeVisible();
  await page.locator('[data-fisherlab-teacher-lessons]').screenshot({ path: 'scratch/fisherlab-teacher-lessons-desktop.png' });
  await sampling.getByRole('button', { name: 'Launch investigation' }).click();
  const journey = page.locator('[data-fisherlab-journey]');
  await expect(journey).toHaveAttribute('data-fisherlab-journey-topic', 'sampling');
  await expect(page.locator('#fl-journey-title')).toBeFocused();
  await journey.getByLabel('My prediction', { exact: false }).fill('My sampling draft.');
  await journey.getByRole('button', { name: 'Pause and return to lesson plans' }).click();
  await expect(page.locator('#fl-teacher-title')).toBeFocused();
  await navigation.getByRole('button', { name: 'Launch investigation' }).click();
  await expect(journey).toHaveAttribute('data-fisherlab-journey-topic', 'navigation');
  await journey.getByLabel('My prediction', { exact: false }).fill('My navigation draft.');
  await journey.getByRole('button', { name: 'Test my prediction' }).click();
  await journey.getByRole('button', { name: 'Pause and return to lesson plans' }).click();
  await sampling.getByRole('button', { name: 'Resume investigation' }).click();
  await expect(journey.getByLabel('My prediction', { exact: false })).toHaveValue('My sampling draft.');
  await journey.getByRole('button', { name: 'Pause and return to lesson plans' }).click();
  await navigation.getByRole('button', { name: 'Resume investigation' }).click();
  await expect(journey).toHaveAttribute('data-fisherlab-journey', '1');
  await expect(journey).toContainText('My navigation draft.');
  await journey.getByRole('button', { name: 'Record trial 1', exact: true }).click();
  await journey.getByRole('slider', { name: /Boat speed/ }).focus();
  await page.keyboard.press('ArrowLeft');
  await page.keyboard.press('ArrowLeft');
  await journey.getByRole('button', { name: 'Record trial 2', exact: true }).click();
  await journey.getByRole('button', { name: 'Continue to the chart' }).click();
  await journey.getByRole('button', { name: 'Pause and return to lesson plans' }).click();
  await sampling.getByRole('button', { name: 'Resume investigation' }).click();
  await journey.getByRole('button', { name: 'Pause and return to lesson plans' }).click();
  await navigation.getByRole('button', { name: 'Resume investigation' }).click();
  await expect(journey).toHaveAttribute('data-fisherlab-journey', '2');
  await expect(page.locator('#fl-journey-chart')).toBeVisible();
  await expect(page.locator('#fl-journey-title')).toBeFocused();
  expect(await page.evaluate(() => (window as any).__events.errors)).toEqual([]);
});
test('downloads blank topic-specific student sheets and handles download failure without changing work', async ({ page }) => {
  await openLessons(page);
  await page.evaluate(() => localStorage.setItem('fisherLab.learningNotes.v1', JSON.stringify({ sampling: { claim: 'Private saved response' } })));
  const lesson = page.locator('[data-fisherlab-lesson="sampling"]');
  const downloadEvent = page.waitForEvent('download');
  await lesson.getByRole('button', { name: 'Download student sheet' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('fisherlab-sampling-student-sheet.txt');
  let contents = '';
  for await (const chunk of (await download.createReadStream())!) contents += chunk.toString();
  expect(contents).toContain('Can one catch tell the whole story?');
  expect(contents).toContain('My response / values and units:');
  expect(contents).toContain('[ ] The pooled percentage uses pooled counts');
  expect(contents).not.toContain('Private saved response');
  await page.evaluate(() => { (window as any).__oldCreateURL = URL.createObjectURL; URL.createObjectURL = () => { throw new Error('blocked'); }; });
  await lesson.getByRole('button', { name: 'Download student sheet' }).click();
  await expect(lesson.getByRole('status')).toContainText('download could not start');
  await lesson.locator('summary').click();
  await expect(lesson.getByRole('heading', { name: 'Look for this evidence' })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fisherLab.learningNotes.v1')!).sampling.claim)).toBe('Private saved response');
  await page.evaluate(() => { URL.createObjectURL = (window as any).__oldCreateURL; });
});
test('teaching notes fit mobile large text and preserve access to the extended lesson library', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 850 });
  await openLessons(page);
  await page.evaluate(() => { document.getElementById('wrap')!.style.width = '360px'; });
  await page.getByRole('button', { name: 'Large text', exact: true }).click();
  const lessons = page.locator('[data-fisherlab-teacher-lessons]');
  const sampling = page.locator('[data-fisherlab-lesson="sampling"]');
  await sampling.locator('summary').focus();
  await page.keyboard.press('Enter');
  await expect(sampling.getByRole('heading', { name: 'Support participation' })).toBeVisible();
  const metric = await lessons.evaluate(el => ({ client: el.clientWidth, scroll: el.scrollWidth, right: el.getBoundingClientRect().right }));
  expect(metric.scroll).toBeLessThanOrEqual(metric.client + 1);
  expect(metric.right).toBeLessThanOrEqual(360);
  const violations = await page.evaluate(async () => (await (window as any).axe.run('[data-fisherlab-teacher-lessons]', { runOnly: { type: 'rule', values: ['color-contrast', 'button-name', 'label', 'aria-valid-attr-value', 'aria-allowed-attr'] } })).violations.map((v: any) => v.id));
  expect(violations).toEqual([]);
  await sampling.screenshot({ path: 'scratch/fisherlab-teacher-sampling-mobile.png' });
  await page.getByText('Extended lesson library · 5 plans', { exact: true }).click();
  await expect(page.getByText('6th Grade: Buoyage 101 (60 min lesson)', { exact: true })).toBeVisible();
});
