import { test, expect } from '@playwright/test';
import { GlHarness } from './helpers/stem_gl_harness';
const desktop=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:1060,height:1000,appStyles:true});
const phone=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:320,height:850,appStyles:true});
test.beforeAll(async()=>{await desktop.start();await phone.start();});
test.afterAll(async()=>{await desktop.stop();await phone.stop();});
test.afterEach(async({page})=>desktop.destroy(page));
test.describe.configure({timeout:120000});
test.use({video:'off',trace:'off'});
for(const compact of [false,true])test('orbit rhythm stays synchronized on '+(compact?'phone':'desktop'),async({page},info)=>{
  await page.setViewportSize({width:compact?320:1060,height:compact?850:1000});
  await page.emulateMedia({reducedMotion:compact?'reduce':'no-preference'});
  await (compact?phone:desktop).mount(page,{solarSystem:{tutorialDismissed:true,orreryMode:true,orr_tab:0,orr_sel:'mercury',orr_paused:true,orr_time:0,orr_zoom:'inner'}},undefined,{expectCanvas:false});
  if(!compact) await page.evaluate(()=>{(window as any).__ctx.isDark=true;(window as any).__ctx.updateMulti('solarSystem',{orr_paused:true});});
  const panel=page.locator('[data-orrery-rhythm]');
  const marker=page.locator('#orrery-rhythm-marker');
  await expect(panel).toHaveAttribute('data-orrery-rhythm','mercury');
  await expect(panel.getByRole('img')).toHaveAccessibleName('Mercury: equal time, changing speed');
  await expect(panel.getByRole('img')).toHaveAccessibleDescription(/Twelve dots mark equal time intervals/);
  await expect(panel.locator('[data-rhythm-moment]')).toHaveCount(12);
  await expect(panel.locator('[data-rhythm-sector]')).toHaveCount(2);
  await expect(marker).toHaveAttribute('cx','252');
  const forward=panel.getByRole('button',{name:/Step forward/});
  await forward.focus();await forward.press('Enter');
  await expect.poll(()=>page.locator('#orrery-phase-scrubber').inputValue()).not.toBe('0');
  expect(await page.evaluate(()=>(window as any).__ctx.toolData.solarSystem.orr_paused)).toBe(true);
  await expect.poll(async()=>Number(await marker.getAttribute('cx'))).toBeLessThan(252);
  await panel.getByRole('button',{name:/Step backward/}).click();
  await expect(marker).toHaveAttribute('cx','252');
  await page.getByRole('button',{name:'Jump to aphelion for Mercury',exact:true}).click();
  await expect.poll(async()=>Number(await marker.getAttribute('cx'))).toBeCloseTo(68,6);
  await expect(page.locator('#orrery-rhythm-reading')).toContainText('0.467 AU');
  await panel.screenshot({path:info.outputPath(compact?'orbit-rhythm-phone.png':'orbit-rhythm-desktop.png')});
  const bounds=await panel.evaluate(el=>{const box=el.getBoundingClientRect();return {left:box.left,right:box.right,overflow:el.scrollWidth>el.clientWidth+1};});
  expect(bounds.left).toBeGreaterThanOrEqual(0);expect(bounds.right).toBeLessThanOrEqual(compact?320:1060);expect(bounds.overflow).toBe(false);
  // Playback updates the retained SVG marker, without replacing the canvas or diagram.
  await page.evaluate(()=>{(window as any).__rhythmMarker=document.getElementById('orrery-rhythm-marker');(window as any).__ctx.updateMulti('solarSystem',{orr_speed:0.1,orr_paused:false});});
  await panel.scrollIntoViewIfNeeded();
  // The canvas clock pauses while offscreen; keep both instruments visible to run it.
  await page.locator('canvas[role="application"]').scrollIntoViewIfNeeded();
  await expect.poll(async()=>Number(await marker.getAttribute('cx')),{timeout:15000}).not.toBeCloseTo(68,2);
  expect(await page.evaluate(()=>(window as any).__rhythmMarker===document.getElementById('orrery-rhythm-marker'))).toBe(true);
  await page.evaluate(()=>(window as any).__ctx.updateMulti('solarSystem',{orr_sel:'earth',orr_paused:true,orr_time:0}));
  await expect(panel).toHaveAttribute('data-orrery-rhythm','earth');
  await expect(panel).toContainText('nearly circular');
  await page.evaluate(()=>(window as any).__ctx.updateMulti('solarSystem',{orr_sel:null}));
  await expect(panel).toHaveCount(0);
  expect(await page.evaluate(()=>(window as any).__events.errors)).toEqual([]);
});
