import {test,expect} from '@playwright/test';
import {GlHarness} from './helpers/stem_gl_harness';
const wide=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:1060,height:1000,appStyles:true});
const phone=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:320,height:850,appStyles:true});
test.beforeAll(async()=>{await wide.start();await phone.start();});test.afterAll(async()=>{await wide.stop();await phone.stop();});test.afterEach(async({page})=>wide.destroy(page));test.describe.configure({timeout:150000});test.use({video:'off',trace:'off'});
const base={tutorialDismissed:true,solarMissionDashboardOpen:false,orreryMode:true,orr_tab:5,orr_trf:'earth',orr_trt:'mars',orr_paused:true};
for(const compact of [false,true])test('capture, explain, revise and restore '+(compact?'phone':'desktop'),async({page},info)=>{
 const harness=compact?phone:wide;await page.setViewportSize(compact?{width:320,height:850}:{width:1060,height:1000});await page.emulateMedia({reducedMotion:'reduce'});await harness.mount(page,{solarSystem:base},undefined,{expectCanvas:false});if(!compact)await page.evaluate(()=>{(window as any).__ctx.isDark=true;(window as any).__rerender();});
 const panel=page.getByRole('region',{name:'Transfer rendezvous experiment'}),details=panel.locator('[data-transfer-debrief]'),form=panel.getByRole('region',{name:'Transfer explanation'});
 await panel.getByRole('button',{name:'Compare launch alignments',exact:true}).click();await details.locator('summary').click();const capture=form.getByRole('button',{name:'Capture this arrival',exact:true});await expect(capture).toBeDisabled();await panel.getByRole('button',{name:'Show transfer arrival',exact:true}).click();await capture.click();await expect(form.locator('[data-transfer-capture]')).toContainText('0.789 AU');
 const variable=page.getByLabel('2. What changed',{exact:false}),reason=page.getByLabel('3. Explain using your captured gaps',{exact:true}),question=page.getByLabel('4. What would you test next?',{exact:true}),save=form.getByRole('button',{name:'Save transfer explanation',exact:true});
 await variable.selectOption('path');await expect(form).toContainText('Look again at the shared craft and clock');await expect(save).toBeDisabled();await variable.selectOption('destination');
 const evidence=await page.evaluate(()=>(window as any).__toolData.solarSystem.transferDebriefs['earth-mars'].snapshot);
 await page.getByLabel('Launch alignment offset:',{exact:false}).fill('-30');await expect(form.locator('[data-transfer-capture]')).toContainText('Test · +30°');
 await reason.fill('The aligned gap was zero, but the +30 degree start missed by 0.789 AU because Mars was elsewhere at arrival.');await question.fill('Would a negative starting angle produce the same gap?');
 const bounds=await details.evaluate(el=>({right:el.getBoundingClientRect().right,overflow:el.scrollWidth>el.clientWidth+1}));expect(bounds.right).toBeLessThanOrEqual(compact?320:1060);expect(bounds.overflow).toBe(false);await details.screenshot({path:info.outputPath(compact?'transfer-explanation-phone.png':'transfer-explanation-desktop.png')});
 // A newly appended observation must survive the functional save.
 await page.evaluate(()=>{const w=window as any;w.__ctx.setLabToolData((prev:any)=>({...prev,solarSystem:{...prev.solarSystem,journalEntries:[{title:'Independent observation',observation:'Keep this record'}]}}));});
 await save.evaluate((b:HTMLButtonElement)=>{b.click();b.click();});await expect(form.getByRole('button',{name:'Explanation saved',exact:true})).toBeDisabled();
 await page.evaluate(()=>{const w=window as any;w.__ctx.setLabToolData((prev:any)=>({...prev,solarSystem:{...prev.solarSystem,journalEntries:prev.solarSystem.journalEntries.filter((e:any)=>!e.transferComparisonId)}}));});await expect(save).toBeEnabled();await save.click();
 let d=await page.evaluate(()=>(window as any).__toolData.solarSystem);expect(d.journalEntries).toHaveLength(2);expect(d.journalEntries[0].title).toBe('Independent observation');expect(d.journalEntries[1].transferComparison).toEqual(evidence);
 await reason.fill('Revised: the changed destination position created the gap while spacecraft path and travel time stayed fixed.');await save.click();d=await page.evaluate(()=>(window as any).__toolData.solarSystem);expect(d.journalEntries).toHaveLength(2);expect(d.journalEntries[1].reasoning).toContain('Revised:');
 const restored=await page.evaluate(()=>(window as any).__toolData);await harness.destroy(page);await harness.mount(page,restored,undefined,{expectCanvas:false});await panel.getByRole('button',{name:'Compare launch alignments',exact:true}).click();await details.locator('summary').click();await expect(reason).toHaveValue(/Revised:/);await expect(form.getByRole('button',{name:'Explanation saved',exact:true})).toBeDisabled();
 await panel.getByRole('button',{name:'Show transfer arrival',exact:true}).click();await page.getByLabel('Launch alignment offset:',{exact:false}).fill('-30');await form.getByRole('button',{name:'Capture current arrival',exact:true}).click();await expect(form.locator('[data-transfer-capture]')).toContainText('Test · -30°');await expect(reason).toHaveValue(/Revised:/);await save.click();expect(await page.evaluate(()=>(window as any).__toolData.solarSystem.journalEntries.length)).toBe(3);
 if(!compact){await form.getByRole('button',{name:'Read saved explanation',exact:true}).click({timeout:60000});await expect(page.locator('#solar-journal-filter')).toBeFocused({timeout:30000});await expect(page.getByText('Revised: the changed destination position created the gap while spacecraft path and travel time stayed fixed.',{exact:true}).first()).toBeVisible();}
 expect(await page.evaluate(()=>(window as any).__events.errors)).toEqual([]);
});
