import {test,expect} from '@playwright/test';
import {GlHarness} from './helpers/stem_gl_harness';
const desktop=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:1060,height:1000,appStyles:true});
const phone=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:320,height:850,appStyles:true});
test.beforeAll(async()=>{await desktop.start();await phone.start();});test.afterAll(async()=>{await desktop.stop();await phone.stop();});test.afterEach(async({page})=>desktop.destroy(page));test.describe.configure({timeout:150000});test.use({video:'off',trace:'off'});
for(const compact of [false,true])test('speed chart follows the shared orbit clock '+(compact?'phone':'desktop'),async({page},info)=>{
 await page.setViewportSize(compact?{width:320,height:850}:{width:1060,height:1000});await page.emulateMedia({reducedMotion:compact?'reduce':'no-preference'});
 const journal=[{timestamp:1,observation:'Keep this observation'}],snapshots={mercury:{a:{time:0,speed:59}}};
 await (compact?phone:desktop).mount(page,{solarSystem:{tutorialDismissed:true,solarMissionDashboardOpen:false,orreryMode:true,orr_tab:0,orr_sel:'mercury',orr_paused:true,orr_time:0,orr_zoom:'inner',journalEntries:journal,orr_snapshots:snapshots}},undefined,{expectCanvas:false});
 if(!compact)await page.evaluate(()=>{(window as any).__ctx.isDark=true;(window as any).__rerender();});
 const panel=page.locator('[data-orrery-rhythm]'),chart=page.locator('#orrery-speed-profile'),marker=page.locator('#orrery-speed-marker'),orbit=page.locator('#orrery-rhythm-marker'),cursor=page.locator('#orrery-speed-cursor');
 await expect(chart).toHaveAccessibleName('Mercury: orbital speed over time');await expect(chart).toHaveAccessibleDescription(/zero-based axis/);await expect(marker).toHaveAttribute('cx','44');const peak=Number(await marker.getAttribute('cy'));const scale=await chart.getAttribute('data-speed-ceiling');const curve=await chart.locator('[data-orbit-speed-curve]').getAttribute('d');
 await page.evaluate(()=>{(window as any).__speedSvg=document.getElementById('orrery-speed-profile');(window as any).__orbitCanvas=document.querySelector('canvas');});
 const forward=panel.getByRole('button',{name:/Step forward/});await forward.focus();await forward.press('Enter');await expect(forward).toBeFocused();await expect.poll(async()=>Number(await marker.getAttribute('cx'))).toBeCloseTo(44+260/12,5);await expect.poll(async()=>Number(await cursor.getAttribute('x1'))).toBeCloseTo(44+260/12,5);
 await page.getByRole('button',{name:'Jump to aphelion for Mercury',exact:true}).click();await expect.poll(async()=>Number(await marker.getAttribute('cx'))).toBeCloseTo(174,5);expect(Number(await marker.getAttribute('cy'))).toBeGreaterThan(peak);await expect.poll(async()=>Number(await orbit.getAttribute('cx'))).toBeCloseTo(68,5);expect(await chart.getAttribute('data-speed-ceiling')).toBe(scale);expect(await chart.locator('[data-orbit-speed-curve]').getAttribute('d')).toBe(curve);
 const bounds=await panel.evaluate(el=>({right:el.getBoundingClientRect().right,overflow:el.scrollWidth>el.clientWidth+1}));expect(bounds.right).toBeLessThanOrEqual(compact?320:1060);expect(bounds.overflow).toBe(false);await panel.screenshot({path:info.outputPath('orbit-speed-'+(compact?'phone':'desktop')+'.png')});
 await page.getByRole('button',{name:'Jump to three-quarter orbit for Mercury',exact:true}).click();await expect.poll(async()=>Number(await marker.getAttribute('cx'))).toBeCloseTo(239,5);
 if(!compact){await page.evaluate(()=>{(window as any).__ctx.updateMulti('solarSystem',{orr_speed:.05,orr_paused:false});});await page.locator('canvas').first().scrollIntoViewIfNeeded();const old=await marker.getAttribute('cx');await expect.poll(()=>marker.getAttribute('cx')).not.toBe(old);await page.evaluate(()=>{(window as any).__ctx.updateMulti('solarSystem',{orr_paused:true});});}
 expect(await page.evaluate(()=>(window as any).__speedSvg===document.getElementById('orrery-speed-profile'))).toBe(true);expect(await page.evaluate(()=>(window as any).__orbitCanvas===document.querySelector('canvas'))).toBe(true);
 await page.evaluate(()=>{(window as any).__ctx.updateMulti('solarSystem',{orr_sel:'earth',orr_time:0,orr_paused:true});});await expect(chart).toHaveAccessibleName('Earth: orbital speed over time');const earthPeak=Number(await marker.getAttribute('cy'));await page.getByRole('button',{name:'Jump to aphelion for Earth',exact:true}).click();expect(Number(await marker.getAttribute('cy'))-earthPeak).toBeLessThan(3);
 expect(await page.evaluate(()=>(window as any).__toolData.solarSystem.journalEntries)).toEqual(journal);expect(await page.evaluate(()=>(window as any).__toolData.solarSystem.orr_snapshots)).toEqual(snapshots);await page.evaluate(()=>{(window as any).__ctx.updateMulti('solarSystem',{orr_sel:null});});await expect(chart).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__events.errors)).toEqual([]);
});
