import {test,expect} from '@playwright/test';
import {GlHarness} from './helpers/stem_gl_harness';
const harness=new GlHarness({toolFile:'stem_lab/stem_tool_cell.js',toolId:'cell',width:1200,height:1000,appStyles:true});
test.beforeAll(()=>harness.start());test.afterAll(()=>harness.stop());test.afterEach(async({page})=>harness.destroy(page));
for(const width of [320,1200])test('external structure explorer at '+width,async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.setViewportSize({width,height:1000});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await harness.mount(page,{cell:{mode:'observe',selectedOrganism:'plantcell',paused:true,zoom:3}},undefined,{expectCanvas:false});
 await page.addStyleTag({content:'body{background:#f8fafc}#wrap{width:100%;max-width:1200px;display:block}'});
 const canvas=page.locator('[data-cell-sim-canvas]'), panel=page.locator('[data-cell-explanation-panel]');
 await page.locator('[data-cell-anatomy-item="Endoplasmic Reticulum"]').click();
 await expect(canvas).toBeFocused();
 await expect(panel.locator('[data-cell-explanation-title]')).toHaveText('Endoplasmic Reticulum');
 await expect(panel.locator('[data-cell-explanation-text]')).toContainText('Rough ER');
 const c=(await canvas.boundingBox())!,p=(await panel.boundingBox())!;
 expect(p.y).toBeGreaterThanOrEqual(c.y+c.height);
 expect(p.x).toBeGreaterThanOrEqual(0);expect(p.x+p.width).toBeLessThanOrEqual(width+1);
 const initial=await canvas.evaluate((c:any)=>c._cellSimGetObservationView());
 const next=panel.getByRole('button',{name:'Next structure',exact:true});
 await next.focus();await page.keyboard.press('Enter');await expect(next).toBeFocused();
 await expect(panel.locator('[data-cell-explanation-title]')).not.toHaveText('Endoplasmic Reticulum');
 await panel.getByRole('button',{name:'Previous structure',exact:true}).click();
 await expect(panel.locator('[data-cell-explanation-title]')).toHaveText('Endoplasmic Reticulum');
 expect(await canvas.evaluate((c:any)=>c._cellSimGetObservationView())).toEqual(initial);
 const count=await canvas.evaluate((c:any)=>c._cellSimGetAnatomyLabels().length);
 for(let i=0;i<count;i++)await next.click();
 await expect(panel.locator('[data-cell-explanation-title]')).toHaveText('Endoplasmic Reticulum');
 await panel.screenshot({path:'reports/cell-structure-explorer/panel-'+width+'.png'});
 await panel.getByRole('button',{name:'Close structure explanation',exact:true}).click();
 await expect(canvas).toBeFocused();
 expect(await canvas.evaluate((c:any)=>c._cellSimGetOrganelleTooltip())).toBeNull();
 await next.click();await expect(panel.getByRole('button',{name:'Close structure explanation'})).toBeVisible();
 await next.press('Escape');await expect(canvas).toBeFocused();
 await next.click();
 await canvas.evaluate((c:any)=>c._cellSimSelectOrganism('amoeba',true));
 await expect(panel.locator('[data-cell-explanation-title]')).toHaveText('Explore cell structures');
 await next.click();await expect(panel).toContainText('Amoeba');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});

test('play taps wait for release and canceled gestures earn no evidence',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:1000});
 await harness.mount(page,{cell:{mode:'play',playAsOrganism:'plantcell',selectedOrganism:'plantcell',paused:true,showPlayInstructions:false,playMission:{organismId:'plantcell',startSuccess:0,predictionSkipped:true},_cellExt:{successByOrganism:{plantcell:0},tutorialsSeen:{plantcell:true}}}},undefined,{expectCanvas:false});
 await page.addStyleTag({content:'#wrap{width:100%;display:block}'});
 const canvas=page.locator('[data-cell-sim-canvas]');await page.locator('[data-cell-stage]').scrollIntoViewIfNeeded();
 await expect.poll(()=>canvas.evaluate((c:any)=>c._cellSimGetAnatomyLabels().length)).toBeGreaterThan(0);
 await canvas.evaluate(async(c:any)=>{await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);c._cellSimSetPaused(true);});
 const label=await canvas.evaluate((c:any)=>c._cellSimGetAnatomyLabels()[0]);const rect=(await canvas.boundingBox())!;
 const point={pointerId:91,pointerType:'touch',button:0,isPrimary:true,clientX:rect.x+label.x+label.width/2,clientY:rect.y+label.y+label.height/2};
 const read=()=>canvas.evaluate((c:any)=>c._cellSimGetOrganelleTooltip());
 const evidence=()=>canvas.evaluate((c:any)=>c._cellSimGetMissionEvidenceState());
 const before=await evidence();
 await canvas.dispatchEvent('pointerdown',point);expect(await read()).toBeNull();
 await canvas.dispatchEvent('pointercancel',point);await canvas.dispatchEvent('pointerup',point);
 expect(await read()).toBeNull();expect(await evidence()).toEqual(before);
 await canvas.dispatchEvent('pointerdown',point);await canvas.dispatchEvent('pointermove',{...point,clientX:point.clientX+40});await canvas.dispatchEvent('pointermove',point);await canvas.dispatchEvent('pointerup',point);
 expect(await read()).toBeNull();expect(await evidence()).toEqual(before);
 const current=await canvas.evaluate((c:any)=>c._cellSimGetAnatomyLabels()[0]);const currentRect=(await canvas.boundingBox())!;
 point.clientX=currentRect.x+current.x+current.width/2;point.clientY=currentRect.y+current.y+current.height/2;
 await canvas.dispatchEvent('pointerdown',point);await canvas.dispatchEvent('pointermove',{...point,clientX:point.clientX+4});await canvas.dispatchEvent('pointerup',{...point,clientX:point.clientX+4});
 await expect.poll(async()=>(await read())?.name).toBe(label.name);
 const panel=page.locator('[data-cell-explanation-panel]');await panel.getByRole('button',{name:'Next structure'}).focus();
 await page.keyboard.press('ArrowRight');expect((await read())?.name).toBe(label.name);
 await page.waitForTimeout(5400);expect((await read())?.name).toBe(label.name);
 await page.keyboard.press('Enter');await expect(panel.locator('[data-cell-explanation-title]')).not.toHaveText(label.name);
 await panel.getByRole('button',{name:'Close structure explanation'}).click();expect(await read()).toBeNull();await expect(canvas).toBeFocused();
});
