import { test, expect, Page } from '@playwright/test';
import { GlHarness } from './helpers/stem_gl_harness';
const harness = new GlHarness({ toolFile: (process.env.CEPHALOPOD_MODEL_SOURCE || 'stem_lab/stem_tool_cephalopodlab.js').replace(/\\/g, '/'), toolId: 'cephalopodLab', width: 900, height: 1000, layout: 'document' });
const canvas = 'canvas[role=application]', failures = new WeakMap<Page, string[]>();
async function step(page: Page, frames: number, code?: string) {
  await page.evaluate(async ({ frames, code }) => { const w = window as any, target = document.querySelector('canvas[role=application]')!, key = (type: string) => target.dispatchEvent(new KeyboardEvent(type, { code, key: code?.slice(3).toLowerCase(), bubbles: true, cancelable: true })); if (code) key('keydown'); try { for (let i = 0; i < frames; i++) { w.__cbStep = .05; do { await new Promise<void>(resolve => requestAnimationFrame(() => resolve())); } while (w.__cbStep !== 0); } } finally { if (code) key('keyup'); } }, { frames, code });
  if (code) await step(page, 1);
}
async function pause(page: Page) { await page.locator(canvas).focus(); await page.keyboard.press('Escape'); await expect(page.locator('[data-hud=burn]')).toHaveText('Paused'); }
async function resume(page: Page) { await page.locator(canvas).focus(); await page.keyboard.press('Escape'); }
async function state(page: Page) {
  return page.evaluate(() => { const w = window as any; w.__cbScene.updateMatrixWorld(true); return { player: w.__cbPlayer.position.toArray(), actors: w.__cbActors.map((root: any) => ({ uuid: root.uuid, type: root.userData.shelterType, state: root.userData.state, parent: root.parent === w.__cbPlayer ? 'player' : root.parent === w.__cbScene ? 'scene' : null, position: root.position.toArray(), rotation: root.rotation.toArray(), world: root.matrixWorld.toArray(), wobble: root.userData.wobble, createdAt: root.userData.createdAt })), time: document.querySelector('[data-hud=time]')!.textContent, status: document.querySelector('[data-hud=status]')!.textContent, camera: w.__cbCamera.position.toArray(), textures: w.__cbRenderer.info.memory.textures,
    stable: w.__cbOwned.every((r: any) => r.mesh.geometry === r.geometry && r.mesh.material === r.material && r.geometry.index === r.index && r.index.array === r.indexArray && r.indices.every((v: number, i: number) => v === r.indexArray[i]) && Object.entries(r.attrs).every(([name, old]: [string, any]) => r.geometry.attributes[name] === old.attr && old.attr.array === old.array && old.attr.version === old.version && old.values.every((v: number, i: number) => v === old.array[i]))), finite: w.__cbOwned.every((r: any) => r.mesh.matrixWorld.elements.every(Number.isFinite) && Object.values(r.geometry.attributes).every((attr: any) => Array.from(attr.array).every(Number.isFinite))), nativeStable: w.__cbNativeStable, disposed: w.__cbResources.map((r: any) => ({ owner: w.__cbActors.indexOf(r.owner), count: r.disposed })) }; });
}
function stable(row: Awaited<ReturnType<typeof state>>, textures: number) { expect(row.stable && row.finite && row.nativeStable).toBe(true); expect(row.textures).toBe(textures); }
async function freshDraws(page: Page) { return page.evaluate(async () => { const w = window as any, epoch = ++w.__cbEpoch; for (let i = 0; i < 60 && w.__cbKinds.some((kind: string) => w.__cbDraws[kind] !== epoch); i++) await new Promise<void>(resolve => requestAnimationFrame(() => resolve())); return w.__cbKinds.every((kind: string) => w.__cbDraws[kind] === epoch); }); }
async function mount(page: Page, quality: 'low' | 'balanced') {
  await harness.mount(page, { cephalopodLab: { activeSection: 'hunt', hunt3DActive: true, huntSpeciesId: 'commonOcto', huntMode: 'free', huntSeed: 2741, huntQuality: quality, _threeLoaded: true } });
  await page.evaluate(() => {
    const w = window as any, T = w.THREE; w.__cbScene = w.__glRecorder.records.filter((row: any) => row.scene && row.canvas.isConnected).at(-1).scene; w.__cbPlayer = w.__cbScene.getObjectByName('cl-player');
    const coconuts = w.__cbScene.children.filter((o: any) => o.userData.shelterType === 'coconut'), bottles = w.__cbScene.children.filter((o: any) => o.userData.shelterType === 'bottle'); if (coconuts.length !== 4 || bottles.length !== 3) throw new Error('The actual initial four coconuts and three bottles are required'); w.__cbActors = [...coconuts, ...bottles]; w.__cbSelected = [coconuts[0], bottles[0]];
    w.__cbStep = 0; T.Clock.prototype.getDelta = function () { const dt = w.__cbStep; w.__cbStep = 0; return dt; };
    w.__cbScene.children.forEach((o: any) => { if ('cooldownUntil' in o.userData) o.userData.cooldownUntil = 1e9; if (o.userData.substrate === 'rock') { o.position.x = -45; o.position.z = -45; o.userData.substrateRadius = 0; } if (o.userData.shelterType || o.userData.landmarkType) { o.position.x = -40; o.position.z = -40; } });
    w.__cbPlayer.position.x = -16; w.__cbPlayer.position.z = 0; coconuts[0].position.x = -16; coconuts[0].position.z = 1.8; bottles[0].position.x = -14.7; bottles[0].position.z = 2.5;
    w.__cbOwned = []; w.__cbResources = []; w.__cbActors.forEach((owner: any) => owner.traverse((mesh: any) => { if (!mesh.isMesh) return; w.__cbOwned.push({ owner, mesh, geometry: mesh.geometry, material: mesh.material, attrs: Object.fromEntries(Object.entries(mesh.geometry.attributes).map(([name, attr]: [string, any]) => [name, { attr, array: attr.array, values: Array.from(attr.array), version: attr.version }])), index: mesh.geometry.index, indexArray: mesh.geometry.index.array, indices: Array.from(mesh.geometry.index.array) }); [mesh.geometry, mesh.material].forEach((resource: any) => { if (w.__cbResources.some((r: any) => r.resource === resource)) throw new Error('Each shelter mesh must independently own its geometry and material'); const r = { owner, resource, disposed: 0 }; resource.addEventListener('dispose', () => r.disposed++); w.__cbResources.push(r); }); }));
    w.__cbPrograms = new Map(); w.__cbBuffers = new Map(); w.__cbNativeStable = true; w.__cbEpoch = 0; w.__cbDraws = {}; w.__cbKinds = [];
    w.__cbSelected.forEach((owner: any) => owner.children.forEach((mesh: any, index: number) => { const kind = owner.userData.shelterType + '-' + index, previous = mesh.onAfterRender; w.__cbKinds.push(kind); mesh.onAfterRender = function (renderer: any, scene: any, camera: any, geometry: any, material: any, group: any) {
      previous.call(this, renderer, scene, camera, geometry, material, group); w.__cbRenderer = renderer; w.__cbCamera = camera; w.__cbDraws[kind] = w.__cbEpoch; const gl = renderer.getContext(), program = gl.getParameter(gl.CURRENT_PROGRAM), location = gl.getUniformLocation(program, 'normalMatrix'), normal = location === null ? null : Array.from(gl.getUniform(program, location));
      const bindings = ['position', 'normal', 'color'].map(name => { const at = gl.getAttribLocation(program, name), buffer = at < 0 ? null : gl.getVertexAttrib(at, gl.VERTEX_ATTRIB_ARRAY_BUFFER_BINDING), id = kind + '/' + name; if (w.__cbBuffers.has(id)) w.__cbNativeStable &&= w.__cbBuffers.get(id) === buffer; else w.__cbBuffers.set(id, buffer); return { name, size: at < 0 ? 0 : gl.getVertexAttrib(at, gl.VERTEX_ATTRIB_ARRAY_SIZE), enabled: at >= 0 && gl.getVertexAttrib(at, gl.VERTEX_ATTRIB_ARRAY_ENABLED), bound: !!buffer }; });
      if (!w.__cbPrograms.has(kind)) w.__cbPrograms.set(kind, { kind, type: material.type, transparent: material.transparent, opacity: material.opacity, blended: gl.isEnabled(gl.BLEND), depthWrite: gl.getParameter(gl.DEPTH_WRITEMASK), linked: gl.getProgramParameter(program, gl.LINK_STATUS), bindings, normal, determinant: normal ? new T.Matrix3().fromArray(normal).determinant() : null, shaders: gl.getAttachedShaders(program).map((shader: any) => ({ compiled: gl.getShaderParameter(shader, gl.COMPILE_STATUS), source: gl.getShaderSource(shader) })) });
    }; }));
  });
  await page.locator(canvas).focus(); await step(page, 12);
}

test.describe.configure({ timeout: 180000, retries: 0 }); test.use({ video: 'off', trace: 'off' });
test.beforeAll(() => harness.start()); test.afterAll(() => harness.stop());
test.beforeEach(({ page }) => { const errors: string[] = []; failures.set(page, errors); page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); });
test.afterEach(async ({ page }) => { await harness.destroy(page); expect(failures.get(page)).toEqual([]); });

for (const quality of ['low', 'balanced'] as const) test(`${quality} coconut and glass bottle surfaces render and preserve independent shelter lifecycles`, async ({ page }, testInfo) => {
  await mount(page, quality); expect(await freshDraws(page)).toBe(true);
  const anatomy = await page.evaluate(() => { const w = window as any; return { programs: [...w.__cbPrograms.values()], actors: w.__cbActors.map((root: any) => ({ type: root.userData.shelterType, meshes: root.children.length, materials: new Set(root.children.map((m: any) => m.material)).size, vertices: root.children.reduce((n: number, m: any) => n + m.geometry.attributes.position.count, 0), triangles: root.children.reduce((n: number, m: any) => n + m.geometry.index.count / 3, 0), glass: root.children.filter((m: any) => m.material.transparent).length, materialsValid: root.children.every((m: any) => m.material.isMeshStandardMaterial && m.material.vertexColors && !Object.values(m.material).some((v: any) => v?.isTexture) && !m.geometry.groups.length) })) }; });
  expect(anatomy.actors).toHaveLength(7); for (const row of anatomy.actors) { expect(row.meshes).toBe(row.type === 'coconut' ? 1 : 2); expect(row.materials).toBe(row.meshes); expect(row.materialsValid).toBe(true); expect(row.vertices).toBeLessThanOrEqual(row.type === 'coconut' ? 1700 : 1600); expect(row.triangles).toBeLessThanOrEqual(row.type === 'coconut' ? 3000 : 2800); expect(row.glass).toBe(row.type === 'coconut' ? 0 : 1); }
  expect(anatomy.programs).toHaveLength(3); for (const row of anatomy.programs) { expect(row.type).toBe('MeshStandardMaterial'); expect(row.linked).toBe(true); expect(row.shaders).toHaveLength(2); expect(row.shaders.every((s: any) => s.compiled)).toBe(true); expect(row.shaders.map((s: any) => s.source).join('\n')).toContain('#define USE_COLOR'); for (const b of row.bindings) { expect(b.enabled && b.bound, row.kind + '/' + b.name).toBe(true); expect(b.size).toBe(3); } expect(row.normal).toHaveLength(9); expect(row.normal.every(Number.isFinite)).toBe(true); expect(Math.abs(row.determinant)).toBeGreaterThan(1e-8); if (row.transparent) { expect(row.opacity).toBeGreaterThan(0); expect(row.opacity).toBeLessThan(.5); expect(row.blended).toBe(true); expect(row.depthWrite).toBe(false); } else { expect(row.opacity).toBe(1); expect(row.blended).toBe(false); expect(row.depthWrite).toBe(true); } }
  const initial = await state(page); stable(initial, initial.textures); expect(initial.disposed).toHaveLength(20); expect(initial.disposed.every(r => r.count === 0)).toBe(true);
  await page.evaluate(() => { const w = window as any; w.__cbSelected.forEach((root: any) => { root.position.x = -30; }); }); const freeStart = await state(page); await step(page, 8, 'KeyW'); const freeEnd = await state(page), freeDistance = Math.hypot(freeEnd.player[0] - freeStart.player[0], freeEnd.player[2] - freeStart.player[2]); expect(freeDistance).toBeGreaterThan(.8);
  const history: any[] = [];
  for (const [selected, ownerIndex, type, penalty, life] of [[0, 0, 'coconut', .1, 90000], [1, 4, 'bottle', .05, 120000]] as const) {
    await page.evaluate(index => { const w = window as any; w.__cbPlayer.position.x = -16; w.__cbPlayer.position.z = 0; const root = w.__cbSelected[index]; root.position.x = -16; root.position.z = .4; }, selected); await step(page, 3);
    await expect(page.locator('.cl-hunt-action-prompt')).toContainText(type); await expect(page.locator('.cl-hunt-action-prompt')).toContainText((penalty * 100) + '% slower'); await expect(page.locator('.cl-hunt-action-prompt')).toContainText((life / 1000) + 's placed cover'); await step(page, 1, 'KeyG'); const carried = await state(page), actor = carried.actors[ownerIndex]; expect(actor.state).toBe('carried'); expect(actor.parent).toBe('player'); expect(actor.position).toEqual([0, -.1, .6]);
    const start = await state(page); await step(page, 8, 'KeyW'); const end = await state(page), distance = Math.hypot(end.player[0] - start.player[0], end.player[2] - start.player[2]); expect(distance / freeDistance).toBeCloseTo(1 - penalty, 6); expect(end.actors[ownerIndex].wobble).not.toBe(actor.wobble); stable(end, initial.textures);
    await pause(page); const paused = await state(page); expect(paused.status).toContain((penalty * 100) + '% slower'); await step(page, 5); const frozen = await state(page); expect(frozen.actors).toEqual(paused.actors); expect(frozen.time).toBe(paused.time);
    if (selected === 0) { await page.getByRole('button', { name: 'Inspect [F]', exact: true }).click(); await step(page, 2); const inspected = await state(page); await page.getByRole('button', { name: 'Orbit right', exact: true }).click(); await step(page, 5); const orbited = await state(page); expect(orbited.camera).not.toEqual(inspected.camera); expect(orbited.actors).toEqual(inspected.actors); stable(orbited, initial.textures); await page.getByRole('button', { name: 'Return to dive', exact: true }).click(); await expect(page.locator('[data-hud=burn]')).toHaveText('Paused'); }
    await resume(page);
    if (selected === 0) { await page.getByRole('button', { name: 'Help / settings', exact: true }).click(); await page.getByLabel('Reduced motion', { exact: true }).check(); await page.getByRole('button', { name: 'Resume dive', exact: true }).click(); }
    const reduced = await state(page); await step(page, 5); const live = await state(page); expect(live.actors[ownerIndex].wobble).not.toBe(reduced.actors[ownerIndex].wobble); stable(live, initial.textures); // Existing carry wobble continues under reduced motion.
    await step(page, 1, 'KeyG'); await step(page, 4); await pause(page); const dropped = await state(page); expect(dropped.actors[ownerIndex].state).toBe('dropped'); expect(dropped.actors[ownerIndex].parent).toBe('scene'); expect(dropped.actors[ownerIndex].rotation).toEqual([0, 0, type === 'bottle' ? Math.PI / 2 : 0, 'XYZ']); expect(dropped.status).toContain('IN DEN'); expect(dropped.status).toContain((life / 1000) + 's left'); await step(page, 6); expect((await state(page)).status).toBe(dropped.status);
    if (quality === 'balanced' && selected === 1) { await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => { document.getElementById('wrap')!.style.width = '100%'; window.dispatchEvent(new Event('resize')); }); await page.getByRole('button', { name: 'Help / settings', exact: true }).click(); await page.getByLabel('Larger text', { exact: true }).check(); await page.getByRole('button', { name: 'Resume dive', exact: true }).click(); await step(page, 4); await pause(page); const stage = await page.locator('.cl-hunt-stage').boundingBox(), hud = await page.locator('.cl-hunt-hud').boundingBox(), mission = await page.locator('.cl-hunt-mission').boundingBox(), controls = await page.locator('.cl-hunt-controls').boundingBox(), touch = await page.locator('.cl-hunt-touch').boundingBox(); expect(hud!.x).toBeGreaterThanOrEqual(stage!.x); expect(hud!.x + hud!.width).toBeLessThanOrEqual(stage!.x + stage!.width); expect(hud!.y + hud!.height).toBeLessThanOrEqual(mission!.y); expect(mission!.y + mission!.height).toBeLessThanOrEqual(controls!.y); expect(controls!.y + controls!.height).toBeLessThanOrEqual(touch!.y); expect(await page.locator('[data-hud=status]').evaluate(node => node.scrollWidth > node.clientWidth + 1)).toBe(false); }
    await resume(page); await step(page, 24); await pause(page); expect((await state(page)).status).toContain((life / 1000 - 1) + 's left');
    // CPU cases test the exact lifetime boundary; native uses the real actor's
    // timestamp to reach expiry without rendering several thousand idle frames.
    await page.evaluate(({ selected, life }) => { (window as any).__cbSelected[selected].userData.createdAt -= life + 1; }, { selected, life }); await resume(page); await step(page, 1); const expired = await state(page); expect(expired.actors[ownerIndex].parent).toBeNull(); expect(expired.disposed.filter(r => r.owner === ownerIndex).every(r => r.count === 1)).toBe(true); expect(expired.disposed.filter(r => r.owner !== 0 && r.owner !== ownerIndex).every(r => r.count === 0)).toBe(true); stable(expired, initial.textures); history.push({ type, carried: actor, dropped: dropped.actors[ownerIndex], expired: expired.actors[ownerIndex] });
  }
  await testInfo.attach('actual-coconut-bottle-lifecycles', { body: JSON.stringify({ quality, anatomy, history }, null, 2), contentType: 'application/json' });
  await harness.unmount(page); expect(await harness.leakedAfterUnmount(page)).toEqual([]); expect(await page.evaluate(() => (window as any).__cbResources.every((r: any) => r.disposed === 1))).toBe(true);
});
