import {test,expect} from '@playwright/test';
import {GlHarness} from './helpers/stem_gl_harness';
const harness=new GlHarness({toolFile:'stem_lab/stem_tool_ecosystem.js',toolId:'ecosystem',width:1100,height:900,appStyles:true});
test.beforeAll(async()=>harness.start());test.afterAll(async()=>harness.stop());test.afterEach(async({page})=>harness.destroy(page));
test('behavior, following inspection, isolation, rewind and branch samples stay coordinated',async({page})=>{
  await page.setViewportSize({width:1140,height:1050});
  await harness.mount(page,{ecosystem:{tab:'foodweb',tutorialDismissed:true}},undefined,{expectCanvas:false});
  await page.evaluate(()=>{document.body.className='theme-default';document.getElementById('wrap')!.style.cssText='width:100%;height:auto;display:block;padding:16px;background:white';});
  await page.getByRole('button',{name:'Insect food shortage',exact:true}).click();
  const meadow=page.locator('[data-efw-meadow]'),canvas=meadow.locator('canvas'),stage=meadow.locator('.efw-meadow-stage');
  await meadow.getByRole('button',{name:'Inspect selected group',exact:true}).click();
  await expect(meadow.locator('[data-efw-behavior]')).toContainText('Moving away');
  const setup=await page.evaluate(()=>JSON.stringify((window as any).__toolData.ecosystem.foodWeb));
  const isolate=meadow.getByRole('button',{name:'Isolate specimen',exact:true});await isolate.focus();await isolate.press('Enter');
  await expect(isolate).toHaveAttribute('aria-pressed','true');
  await expect(canvas).toHaveAttribute('data-isolated-specimen','true');await expect(canvas).toHaveAttribute('data-visible-glyphs-bluetits','1');await expect(canvas).toHaveAttribute('data-visible-glyphs-plants','0');await expect(canvas).toHaveAttribute('data-glyphs-plants','40');
  const representative=meadow.getByLabel('Representative animal',{exact:true});
  const firstPosition=await canvas.getAttribute('data-representative-position');
  await representative.selectOption('1');await expect(canvas).toHaveAttribute('data-representative-index','1');await expect(canvas).toHaveAttribute('data-visible-glyphs-bluetits','1');await expect(canvas).not.toHaveAttribute('data-representative-position',firstPosition!);
  expect(await page.evaluate(()=>JSON.stringify((window as any).__toolData.ecosystem.foodWeb))).toBe(setup);
  await representative.selectOption('0');await expect(canvas).toHaveAttribute('data-representative-position',firstPosition!);
  await stage.screenshot({path:'reports/ecosystem-action-transitions/isolated-blue-tit.jpg',type:'jpeg',quality:90});
  await page.getByRole('button',{name:'Run food-web comparison',exact:true}).click();
  const timeline=meadow.getByLabel('Meadow timeline',{exact:true});await timeline.fill('60');
  const expected=await page.evaluate(()=>{const w=window as any,a=w.StemLab.ecosystemFoodWeb,c=w.__toolData.ecosystem.foodWeb.run.config,p=a.compare(c);return {pose:a.behaviorTimeline(c,p.experiment)[60].bluetits[0],value:p.experiment[60].values.bluetits};});
  await expect(canvas).toHaveAttribute('data-behavior',expected.pose.state);await expect(meadow.locator('[data-efw-behavior]')).toContainText(expected.pose.state);
  await expect(canvas).toHaveAttribute('data-representative-position',expected.pose.x.toFixed(4)+','+expected.pose.z.toFixed(4));await expect(canvas).toHaveAttribute('data-biomass-bluetits',String(expected.value));
  const position=await canvas.getAttribute('data-representative-position'),behavior=await canvas.getAttribute('data-behavior');
  await timeline.fill('150');await timeline.fill('60');await expect(canvas).toHaveAttribute('data-representative-position',position!);await expect(canvas).toHaveAttribute('data-behavior',behavior!);
  await isolate.click();await expect(canvas).toHaveAttribute('data-visible-glyphs-bluetits',await canvas.getAttribute('data-glyphs-bluetits')||'');await expect(canvas).toHaveAttribute('data-representative-position',position!);
  await meadow.getByRole('button',{name:/Red foxes/}).click();await isolate.click();
  const hunt=await page.evaluate(()=>{
    const w=window as any,a=w.StemLab.ecosystemFoodWeb,c=w.__toolData.ecosystem.foodWeb.run.config,frames=a.behaviorTimeline(c,a.compare(c).experiment);
    for(let i=0;i<16;i++)for(let t=1;t<frames.length-16;t++)if(frames[t].foxes[i].huntStage==='airborne'&&frames[t].foxes[i].huntAge===0&&frames[t+10].foxes[i].active){const p=frames[t+4].foxes[i];return {index:i,takeoff:t,peak:t+4,position:p.x.toFixed(4)+','+p.z.toFixed(4)};}
    return null;
  });
  expect(hunt).not.toBeNull();const takeoff=hunt!.takeoff,huntStep=hunt!.peak;
  await timeline.fill(String(takeoff));await representative.selectOption(String(hunt!.index));await expect(canvas).toHaveAttribute('data-representative-index',String(hunt!.index));
  await timeline.fill(String(takeoff-1));await expect(canvas).toHaveAttribute('data-hunt-stage','prepare');await expect(meadow.locator('[data-efw-behavior]')).toContainText('Preparing to pounce');
  await stage.screenshot({path:'reports/ecosystem-action-transitions/fox-preparation.jpg',type:'jpeg',quality:90});
  await timeline.fill(String(takeoff+10));await expect(canvas).toHaveAttribute('data-hunt-stage','recover');await expect(meadow.locator('[data-efw-behavior]')).toContainText('Recovering');
  await stage.screenshot({path:'reports/ecosystem-action-transitions/fox-recovery.jpg',type:'jpeg',quality:90});
  await timeline.fill(String(huntStep));await expect(canvas).toHaveAttribute('data-behavior','Pouncing');await expect(canvas).toHaveAttribute('data-hunt-stage','airborne');await expect(canvas).toHaveAttribute('data-representative-position',hunt!.position);await expect(canvas).toHaveAttribute('data-visible-glyphs-foxes','1');
  await stage.screenshot({path:'reports/ecosystem-action-transitions/fox-pounce.jpg',type:'jpeg',quality:90});
  await page.setViewportSize({width:390,height:844});await stage.screenshot({path:'reports/ecosystem-action-transitions/mobile-inspection.jpg',type:'jpeg',quality:90});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await timeline.fill('240');await expect(canvas).toHaveAttribute('data-representative-index',String(Math.min(hunt!.index,Number(await canvas.getAttribute('data-glyphs-foxes'))-1)));await representative.selectOption('0');await timeline.fill(String(huntStep));
  await page.emulateMedia({reducedMotion:'reduce'});await expect(meadow).toContainText('Motion is frozen');await expect(canvas).toHaveAttribute('data-behavior','Starting pose');const still=await canvas.getAttribute('data-representative-position');await timeline.fill('240');await expect(canvas).toHaveAttribute('data-representative-position',still!);
  await meadow.getByRole('button',{name:'Habitat view',exact:true}).click();await expect(canvas).toHaveAttribute('data-isolated-specimen','false');await expect(canvas).toHaveAttribute('data-visible-glyphs-plants',await canvas.getAttribute('data-glyphs-plants')||'');
  await page.getByLabel('Disturbance',{exact:true}).selectOption('remove');await page.getByLabel('Affected group',{exact:true}).selectOption('foxes');await page.getByRole('button',{name:'Run food-web comparison',exact:true}).click();await meadow.getByRole('button',{name:'Inspect selected group',exact:true}).click();
  await expect(canvas).toHaveAttribute('data-visible-glyphs-foxes','0');await expect(meadow.locator('[data-efw-behavior]')).toContainText('Not present');await expect(representative).toBeDisabled();await expect(canvas).toHaveAttribute('data-representative-index','0');
  await meadow.getByLabel('Meadow scene data',{exact:true}).selectOption('baseline');await expect(canvas).not.toHaveAttribute('data-visible-glyphs-foxes','0');
  await meadow.getByRole('button',{name:'Reset camera',exact:true}).click();await expect(canvas).toHaveAttribute('data-isolated-specimen','false');await expect(canvas).toHaveAttribute('data-representative-index','0');
  expect(await page.evaluate(()=>(window as any).__events.errors)).toEqual([]);
});
