import {test,expect} from '@playwright/test';
import {GlHarness} from './helpers/stem_gl_harness';
const harness=new GlHarness({toolFile:'stem_lab/stem_tool_ecosystem.js',toolId:'ecosystem',width:1100,height:900,appStyles:true});
test.beforeAll(async()=>harness.start());test.afterAll(async()=>harness.stop());test.afterEach(async({page})=>harness.destroy(page));
test('behavior navigation follows exact moments, pauses playback and supports reduced motion',async({page})=>{
  await page.setViewportSize({width:1140,height:1050});await harness.mount(page,{ecosystem:{tab:'foodweb',tutorialDismissed:true}},undefined,{expectCanvas:false});
  await page.evaluate(()=>{document.body.className='theme-default';document.getElementById('wrap')!.style.cssText='width:100%;height:auto;display:block;padding:16px;background:white';});
  await page.getByRole('button',{name:'Insect food shortage',exact:true}).click();
  const meadow=page.locator('[data-efw-meadow]'),canvas=meadow.locator('canvas'),panel=meadow.getByRole('group',{name:'Behavior moments',exact:true}),select=panel.getByLabel('Jump to behavior',{exact:true}),timeline=meadow.getByLabel('Meadow timeline',{exact:true});
  await meadow.getByRole('button',{name:/Red foxes\s/}).click();await meadow.getByRole('button',{name:'Inspect selected group',exact:true}).click();await expect(panel).toContainText('Run a food-web comparison');await expect(select).toHaveCount(0);
  await page.getByRole('button',{name:'Run food-web comparison',exact:true}).click();await timeline.fill('0');
  const expected=await page.evaluate(()=>{const w=window as any,a=w.StemLab.ecosystemFoodWeb,c=w.__toolData.ecosystem.foodWeb.run.config,pair=a.compare(c);return {moments:a.behaviorMoments(a.behaviorTimeline(c,pair.experiment),'foxes',0),run:JSON.stringify(w.__toolData.ecosystem.foodWeb.run)};});
  expect(expected.moments.length).toBeGreaterThan(2);await expect(select.locator('option')).toHaveCount(expected.moments.length);await expect(panel.getByRole('button',{name:'Previous behavior',exact:true})).toBeDisabled();
  const next=panel.getByRole('button',{name:'Next behavior',exact:true});await next.focus();await next.press('Enter');await expect(timeline).toHaveValue(String(expected.moments[1].start));await expect(canvas).toHaveAttribute('data-behavior',expected.moments[1].state);
  await meadow.getByRole('button',{name:'Play meadow timeline',exact:true}).click();await select.selectOption('2');await expect(meadow.getByRole('button',{name:'Play meadow timeline',exact:true})).toBeVisible();await page.waitForTimeout(250);await expect(timeline).toHaveValue(String(expected.moments[2].start));
  await panel.getByRole('button',{name:'Previous behavior',exact:true}).click();await expect(timeline).toHaveValue(String(expected.moments[1].start));
  expect(await page.evaluate(()=>JSON.stringify((window as any).__toolData.ecosystem.foodWeb.run))).toBe(expected.run);
  await panel.screenshot({path:'reports/ecosystem-behavior-moments/desktop-controls.jpg',type:'jpeg',quality:90});
  await select.selectOption(String(expected.moments.length-1));await expect(next).toBeDisabled();
  await meadow.getByLabel('Representative animal',{exact:true}).selectOption('1');
  const second=await page.evaluate(()=>{const w=window as any,a=w.StemLab.ecosystemFoodWeb,c=w.__toolData.ecosystem.foodWeb.run.config;return a.behaviorMoments(a.behaviorTimeline(c,a.compare(c).experiment),'foxes',1).filter((m:any)=>m.active);});
  await expect(select.locator('option')).toHaveCount(second.length);await select.selectOption('0');await expect(canvas).toHaveAttribute('data-representative-index','1');await expect(timeline).toHaveValue(String(second[0].start));
  await timeline.fill('0');const representativeSelect=meadow.getByLabel('Representative animal',{exact:true}),lastRepresentative=(await representativeSelect.locator('option').count())-1;await representativeSelect.selectOption(String(lastRepresentative));await timeline.fill('240');const clampedIndex=await canvas.getAttribute('data-representative-index');expect(Number(clampedIndex)).toBeLessThan(lastRepresentative);await select.selectOption('0');await expect(canvas).toHaveAttribute('data-representative-index',clampedIndex!);
  await meadow.getByLabel('Representative animal',{exact:true}).selectOption('0');await page.emulateMedia({reducedMotion:'reduce'});await expect(panel).toContainText('3D pose stays frozen');const frozen=await canvas.getAttribute('data-representative-position');await select.selectOption('1');await expect(canvas).toHaveAttribute('data-representative-position',frozen!);await expect(panel.locator('[data-efw-moment-state]')).toContainText(expected.moments[1].state);await expect(canvas).toHaveAttribute('data-behavior','Starting pose');
  await page.setViewportSize({width:390,height:844});await panel.screenshot({path:'reports/ecosystem-behavior-moments/mobile-controls.jpg',type:'jpeg',quality:90});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByLabel('Disturbance',{exact:true}).selectOption('remove');await page.getByLabel('Affected group',{exact:true}).selectOption('foxes');await page.getByRole('button',{name:'Run food-web comparison',exact:true}).click();await expect(panel.locator('[data-efw-moment-state]')).toContainText('Not present');await expect(canvas).toHaveAttribute('data-visible-glyphs-foxes','0');
  await meadow.getByLabel('Meadow scene data',{exact:true}).selectOption('baseline');await expect(panel.locator('[data-efw-moment-state]')).not.toContainText('Not present');
  await meadow.getByRole('button',{name:'Habitat view',exact:true}).click();await expect(panel).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__events.errors)).toEqual([]);
});
