const fs=require('fs');let harness=fs.readFileSync('reports/geometry-world-deep-dive-2026-09-08/audit.cjs','utf8').split('const results =')[0];harness=harness.replace('window.__mount({_introShownOnce:true});','window.__mount({_introShownOnce:true,worldActive:true,renderQuality:"saver",autoCycle:false,tutorialDismissed:true});');
const run=async function(){
 const result={assertions:[],errors:[],scope:'Actual Chromium WebGL and React controls; desktop, 320px phone, and 390px-high landscape.'};await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:960},hasTouch:true});page.setDefaultTimeout(30000);page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/THREE.WebGLProgram|shader error/i.test(m.text()))result.errors.push(m.text());});
 const check=(name,pass,details)=>{result.assertions.push({name,pass:!!pass,details});console.log((pass?'PASS ':'FAIL ')+name);},shot=name=>page.screenshot({path:path.join(out,name+'.jpg'),type:'jpeg',quality:78,timeout:60000}),frames=()=>page.evaluate(()=>new Promise(resolve=>{let n=0;function tick(){if(++n>8)resolve();else requestAnimationFrame(tick);}requestAnimationFrame(tick);}));
 const expand=async()=>{const b=page.getByRole('button',{name:'Expand Free Build Studio',exact:true});if(await b.count())await b.click();},jump=async text=>{await expand();await page.getByRole('button',{name:'Find a tool',exact:true}).click();await page.getByRole('searchbox').fill(text);await page.getByRole('searchbox').press('Enter');await frames();};
 try{
  await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await page.locator('.gwe-home').waitFor({timeout:60000});await page.waitForFunction(()=>!!window.__geoWorldEngine);await page.locator('.gwe-home-card[data-path=build]').click();await page.getByRole('button',{name:'Open blank sandbox',exact:true}).click();await page.waitForFunction(()=>__geoWorldEngine._currentLesson.sandbox&&!document.querySelector('.gwe-home'));
  await jump('arch');await page.locator('#gwe-starter-corner-x').fill('0');await page.locator('#gwe-starter-corner-z').fill('0');await page.getByRole('button',{name:'Preview starter',exact:true}).click();check('Normal construction retains the single lightweight outline',await page.evaluate(()=>__geoWorldEngine._buildBatchPreview.group.children.length===1));await page.getByRole('button',{name:'Review in world',exact:true}).click();await page.waitForFunction(()=>!__geoWorldEngine._viewPresetAnim&&__geoWorldEngine._buildBatchPreview.surfaces?.visible);await frames();
  check('Review shows actual material textures without placing any blocks',await page.evaluate(()=>{const e=__geoWorldEngine;return e._buildBatchPreview.surfaces.children.some(m=>m.material.map)&&StemLab.geometryWorldBuilderPure.editableWorld(e).blocks.length===0;}));await shot('01-textured-preview');
  await page.evaluate(()=>__geoWorldEngine.applyRenderQuality('balanced'));await frames();check('Review surfaces respond to Balanced material detail',await page.evaluate(()=>__geoWorldEngine._buildBatchPreview.surfaces.children.filter(m=>m.material.userData.gwSurfaceKey).every(m=>m.material.normalMap&&m.material.roughnessMap)));check('Lighting targets the framed structure rather than the distant camera',await page.evaluate(()=>{const e=__geoWorldEngine,p=e._viewPresetLighting;return !!p&&e._sunTarget.position.distanceTo(p.target)<.1&&e._sunTarget.position.distanceTo(e.camera.position)>5;}));await shot('02-lit-preview');
  await page.getByRole('button',{name:'Apply preview',exact:true}).click();const base=await page.evaluate(()=>({count:StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks.length,history:__geoWorldEngine._undoStack.length}));check('Applying a material preview releases its GPU scene overlay',await page.evaluate(()=>!__geoWorldEngine._buildBatchPreview));
  await jump('repeat pattern');await page.locator('#gwe-creation-edit-action').selectOption('repeat');await page.locator('#gwe-pattern-total').fill('3');await page.locator('#gwe-pattern-gap').fill('1');await page.getByRole('button',{name:'Preview change',exact:true}).click();check('Three instances preview two copies and retain the source',await page.evaluate(base=>{const e=__geoWorldEngine;return e._buildBatchPreview.blocks.length===base.count*2&&e._undoStack.length===base.history;},base));await shot('03-pattern-tools');await page.getByRole('button',{name:'Review in world',exact:true}).click();await page.waitForFunction(()=>!__geoWorldEngine._viewPresetAnim);await shot('04-pattern-review');
  await page.getByRole('button',{name:'Apply preview',exact:true}).click();check('Apply selects every instance in a single undoable operation',await page.evaluate(base=>{const e=__geoWorldEngine;return e._builderSelection.blocks.length===base.count*3&&e._undoStack.length===base.history+1;},base));await page.locator('#geoworld-fs-wrap').focus();await page.keyboard.press('Control+z');check('One keyboard Undo removes all copies',await page.evaluate(base=>StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks.length===base.count,base));await page.keyboard.press('Control+Shift+z');check('Redo restores the entire selected pattern',await page.evaluate(base=>__geoWorldEngine._builderSelection.blocks.length===base.count*3,base));
  await jump('align grid');await page.locator('#gwe-creation-edit-action').selectOption('align');await page.locator('#gwe-align-edge').selectOption('end');await page.locator('#gwe-align-coordinate').fill('0');await page.getByRole('button',{name:'Preview change',exact:true}).click();check('Aligning the far grid edge places the last column at X = -1',await page.evaluate(()=>Math.max(...__geoWorldEngine._buildBatchPreview.blocks.map(b=>b.x))===-1));await page.getByRole('button',{name:'Review in world',exact:true}).click();await page.waitForFunction(()=>!__geoWorldEngine._viewPresetAnim);await shot('05-aligned-review');await page.getByRole('button',{name:'Apply preview',exact:true}).click();
  await page.setViewportSize({width:320,height:844});await jump('repeat');await page.locator('#gwe-creation-edit-action').selectOption('repeat');await page.locator('#gwe-pattern-total').fill('2');await page.locator('#gwe-pattern-gap').fill('2');await page.locator('#gwe-pattern-axis').selectOption('z');await page.locator('#gwe-pattern-total').scrollIntoViewIfNeeded();await shot('06-phone-pattern-controls');const mobile=await page.locator('.gwe-pattern-options').evaluate(el=>({overflow:document.documentElement.scrollWidth>innerWidth,fields:[...el.querySelectorAll('input,select')].map(e=>({label:e.labels?.[0]?.textContent,height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width}))}));check('Phone precision fields remain labeled, touch-sized, and within the page',!mobile.overflow&&mobile.fields.every(e=>e.label&&e.height>=44&&e.width>=44),mobile);await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByRole('button',{name:'Review in world',exact:true}).click();await page.waitForFunction(()=>!__geoWorldEngine._viewPresetAnim);await shot('07-phone-material-review');check('Phone material review keeps all three actions available',await page.locator('.gwe-preview-review button').count()===3);check('Phone review hides overlapping play controls while preserving the model',await page.evaluate(()=>['.gw-touch-controls','.gw-hotbar','.gw-shape-tray','.gw-action-bar'].every(selector=>{const e=document.querySelector(selector);return !e||getComputedStyle(e).display==='none';})&&__geoWorldEngine._buildBatchPreview.surfaces.visible));await page.getByRole('button',{name:'Cancel preview',exact:true}).click();
  await page.setViewportSize({width:844,height:390});await jump('align');await page.locator('#gwe-creation-edit-action').selectOption('align');await page.getByRole('button',{name:'Use ground level',exact:true}).scrollIntoViewIfNeeded();await shot('08-short-alignment');check('Short landscape can reach ground alignment',await page.getByRole('button',{name:'Use ground level',exact:true}).isVisible());
  await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'Open game settings and tools',exact:true}).click();await page.getByRole('combobox',{name:'Choose lesson',exact:true}).selectOption('geometryHarbor');await page.getByRole('button',{name:'Start lesson without the guided tutorial',exact:true}).click();await page.waitForFunction(()=>__geoWorldEngine._currentLesson.activities?.length===8);await frames();
  check('Expanded Harbor loads all eight activities and the eastern architecture',await page.evaluate(()=>{const e=__geoWorldEngine;return e._currentLesson.ground.xMax===44&&e.blocks['29,1,-17']&&e.blocks['34,9,-20']&&e._currentLesson.activities.length===8;}));
  const lesson=await page.evaluate(()=>{const e=__geoWorldEngine,api=StemLab.geometryWorldBuilderPure;return e._currentLesson.activities.slice(6).map(a=>({id:a.id,travel:api.travelToActivity(e,a),camera:e.camera.position.toArray(),expected:a.position}));});check('Both new activities can be reached without lifting the learner onto a structure',lesson.every(a=>a.travel&&a.camera.every((v,i)=>Math.abs(v-a.expected[i])<.01)),lesson);
  await page.evaluate(()=>{const e=__geoWorldEngine;e._entryAnim=null;e.releaseInput();e.camera.position.set(44,15,11);e.camera.lookAt(34,2,-12);e.euler.setFromQuaternion(e.camera.quaternion);e.camera.updateMatrixWorld(true);});await frames();await shot('09-harbor-arcade-overview');
  await page.evaluate(()=>{const e=__geoWorldEngine;e.camera.position.set(35,4,-8);e.camera.lookAt(34.5,3,-18);e.euler.setFromQuaternion(e.camera.quaternion);e.camera.updateMatrixWorld(true);});await frames();await shot('10-arcade-landmark');
  check('New reference arches each measure nine cubes in the running engine',await page.evaluate(()=>[29,33,37].every(x=>{const m=__geoWorldEngine.measureStructure(x,1,-17);return m&&m.blocks.length===9;})));
 }catch(error){result.failure=error.stack;console.error(error.stack);await shot('failure').catch(()=>{});}
 finally{fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.assertions.filter(a=>a.pass).length,failed:result.assertions.filter(a=>!a.pass),errors:result.errors,failure:result.failure}));await browser.close();await new Promise(r=>server.close(r));if(result.failure||result.errors.length||result.assertions.some(a=>!a.pass))process.exitCode=1;}
};eval(harness+'('+run.toString()+')();');
