import fs from 'node:fs';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {loadTool,makeCtx,renderTool,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
const files=['stem_lab/stem_tool_anatomy.js','desktop/web-app/public/stem_lab/stem_tool_anatomy.js'];
function find(n,p){if(!n||typeof n!=='object')return null;if(Array.isArray(n)){for(const child of n){const hit=find(child,p);if(hit)return hit;}return null;}return p(n)?n:find(n.props?.children,p);}
function session(file,patch={},grade='9',lang=null){resetStemLab();const tool=loadTool(file,'anatomy');let data={anatomy:{_activeTab:'explore',system:'organs',view:'anterior',complexity:3,selectedStructure:'lungs',...patch}},level=grade;const dict=lang?JSON.parse(fs.readFileSync('lang/'+lang+'.js','utf8')).stem.anatomy:null;const overrides=()=>({gradeLevel:level,t:(k,f)=>dict?.[k.slice(13)]||f,setToolData:f=>{data=typeof f==='function'?f(data):f;}});const tree=()=>tool.render(makeCtx({toolData:data,...overrides()}));return {data:()=>data.anatomy,patch:p=>{data={anatomy:{...data.anatomy,...p}};},grade:g=>{level=g;},node:(key,value)=>find(tree(),n=>n.props?.[key]===value),html:()=>{const root=document.createElement('div');root.innerHTML=renderTool('anatomy',data,overrides());return root;}};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();});
for(const file of files)describe('Anatomy breathing refinements '+file,()=>{
 for(const [system,id] of [['organs','lungs'],['organs','diaphragm'],['muscular','diaphragm_m'],['respiratory','alveoli'],['respiratory','pleura'],['respiratory','resp_muscles']])it('offers the breathing lesson and primary references for '+id,()=>{const s=session(file,{system,selectedStructure:id}),root=s.html();expect(root.querySelector('[data-anatomy-breathing-study="'+id+'"]')).not.toBeNull();const links=[...root.querySelectorAll('[data-anatomy-science-sources="'+id+'"] a')].map(a=>a.href);expect(links).toContain('https://www.nhlbi.nih.gov/health/lungs/breathing-benefits');expect(links.some(link=>link.includes('22-3-the-process-of-breathing'))).toBe(true);});
 it('keeps airflow arrows and text consistent across all three states',()=>{const s=session(file);for(const phase of ['in','out','rest']){s.node('data-anatomy-breath-phase',phase).props.onClick();const root=s.html(),panel=root.querySelector('[data-anatomy-breathing-study]');expect(panel.querySelector('[data-anatomy-breath-diagram]').getAttribute('data-anatomy-breath-diagram')).toBe(phase);expect(panel.querySelector('[data-anatomy-breath-phase="'+phase+'"]').getAttribute('aria-pressed')).toBe('true');expect(panel.querySelectorAll('[data-anatomy-breath-airflow]')).toHaveLength(phase==='rest'?0:1);expect(panel.querySelector('[data-anatomy-breath-description]').textContent).toContain(phase==='in'?'slightly below':phase==='out'?'slightly above':'pressures are equal');}expect(s.data()._breathingStudy.phase).toBe('rest');});
 it('allows revisions without changing scores, confidence, notes, or practice evidence',()=>{const evidence={quizScore:8,_structureConfidence:{lungs:'mastered'},_retrievalEvidence:{lungs:{attempts:4,correct:3}},_structureNotes:{lungs:'My own explanation'},researchPoints:20,totalRP:30};const s=session(file,evidence);s.node('data-anatomy-breath-answer','empty').props.onClick();expect(s.html().querySelector('[data-anatomy-breath-feedback]').getAttribute('data-anatomy-breath-feedback')).toBe('review');s.node('data-anatomy-breath-answer','continue').props.onClick();expect(s.html().querySelector('[data-anatomy-breath-feedback]').getAttribute('data-anatomy-breath-feedback')).toBe('correct');expect(s.data()).toMatchObject(evidence);expect(s.html().querySelectorAll('[data-anatomy-breath-answer]:disabled')).toHaveLength(0);});
 it('preserves newer learner writing while updating a retained phase control',()=>{const s=session(file),click=s.node('data-anatomy-breath-phase','out').props.onClick;s.patch({_structureNotes:{lungs:'New note'},_breathingStudy:{phase:'in',answer:'continue',band:'g912'}});click();expect(s.data()._structureNotes.lungs).toBe('New note');expect(s.data()._breathingStudy).toEqual({phase:'out',answer:'continue',band:'g912'});});
 it('restores a saved phase and explanation through a reload',()=>{const s=session(file);s.node('data-anatomy-breath-phase','rest').props.onClick();s.node('data-anatomy-breath-answer','continue').props.onClick();const restored=session(file,JSON.parse(JSON.stringify(s.data())));expect(restored.html().querySelector('[data-anatomy-breath-diagram]').getAttribute('data-anatomy-breath-diagram')).toBe('rest');expect(restored.html().querySelector('[data-anatomy-breath-feedback]').textContent).toContain('partial-pressure differences');});
 for(const saved of [null,[],7,{phase:'invalid',answer:'forged',band:'g912'}])it('recovers from malformed saved activity state '+JSON.stringify(saved),()=>{const s=session(file,{_breathingStudy:saved}),panel=s.html().querySelector('[data-anatomy-breathing-study]');expect(panel.querySelector('[data-anatomy-breath-diagram]').getAttribute('data-anatomy-breath-diagram')).toBe('in');expect(panel.querySelector('[data-anatomy-breath-feedback]')).toBeNull();s.node('data-anatomy-breath-phase','out').props.onClick();expect(s.data()._breathingStudy.phase).toBe('out');});
 for(const patch of [{selectedStructure:'diaphragm'},{_activeTab:'aiTutor'}])it('ignores a callback after leaving its structure or activity '+JSON.stringify(patch),()=>{const s=session(file),click=s.node('data-anatomy-breath-answer','continue').props.onClick;s.patch(patch);const before=structuredClone(s.data());click();expect(s.data()).toEqual(before);});
 for(const grade of ['1','4'])it('uses a simpler concept check and excludes adult pressure details at grade '+grade,()=>{const s=session(file,{complexity:1,_breathingStudy:{phase:'rest',answer:'continue',band:'g912'}},grade),panel=s.html().querySelector('[data-anatomy-breathing-study]');expect(panel.querySelector('[data-anatomy-breath-check]').getAttribute('data-anatomy-breath-check')).toBe('exchange-site');expect(panel.textContent).not.toContain('pleural pressure');expect(panel.querySelector('[data-anatomy-breath-feedback]')).toBeNull();s.node('data-anatomy-breath-answer','sacs').props.onClick();expect(s.html().querySelector('[data-anatomy-breath-feedback]').textContent).toContain('The diaphragm helps move air.');});
 it('updates the learning-band check without carrying over a prior choice',()=>{const s=session(file);s.node('data-anatomy-breath-answer','continue').props.onClick();s.grade('1');s.patch({complexity:1});expect(s.html().querySelector('[data-anatomy-breath-feedback]')).toBeNull();});
 it('corrects the diaphragm misconception and replaces the lung disease list with sourced context',()=>{const s=session(file,{selectedStructure:'diaphragm'}),myth=s.html().querySelector('[data-anatomy-myth-buster="diaphragm"]').textContent;expect(myth).toContain('Airways do contain smooth muscle');expect(myth).not.toContain('Lungs have no muscle');s.patch({selectedStructure:'lungs'});const root=s.html(),clinical=root.querySelector('[data-anatomy-clinical-note="lungs"]');expect(clinical.textContent).toContain('symptoms alone do not establish the cause');expect(clinical.querySelector('[data-anatomy-clinical-note-source]').href).toBe('https://www.nhlbi.nih.gov/health/pneumonia');expect(root.querySelector('[data-anatomy-myth-buster="lungs"]').textContent).not.toContain('300 million');});
 it('uses revised shared functions in comparison and tutor reference content',()=>{const s=session(file,{_compareStructure:'diaphragm'});expect(s.html().querySelector('[data-anatomy-compare-row="function"]').textContent).toContain('gas exchange occurs across a thin tissue barrier');s.patch({_activeTab:'aiTutor'});expect(s.html().querySelector('[data-anatomy-tutor-lesson="lungs"]').textContent).toContain('gas exchange occurs across a thin tissue barrier');});
 for(const lang of ['french','spanish_latin_america','arabic'])it('localizes the science explanation, phases, and feedback in '+lang,()=>{const s=session(file,{},'9',lang),dict=JSON.parse(fs.readFileSync('lang/'+lang+'.js','utf8')).stem.anatomy;s.node('data-anatomy-breath-phase','rest').props.onClick();s.node('data-anatomy-breath-answer','continue').props.onClick();const root=s.html(),panel=root.querySelector('[data-anatomy-breathing-study]');expect(root.textContent).toContain(dict.breath_ref_lungs_fn);expect(panel.textContent).toContain(dict.breath_ref_rest_pressure);expect(panel.textContent).toContain(dict.breath_ref_explanation);expect(panel.textContent).not.toContain('How breathing works');});
});
