import fs from 'node:fs';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {loadTool,makeCtx,renderTool,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
const bank=JSON.parse(fs.readFileSync('reports/anatomy-facts-refinements-2026-09-12/content.json','utf8'));
function find(n,p){if(!n||typeof n!=='object')return null;if(Array.isArray(n)){for(const c of n){const r=find(c,p);if(r)return r;}return null;}return p(n)?n:find(n.props?.children,p);}
function session(file,extra={},ctx={}){resetStemLab();const tool=loadTool(file,'anatomy');let data={anatomy:{system:'skeletal',view:'anterior',complexity:3,_activeTab:'explore',...extra}};const render=()=>tool.render(makeCtx({toolData:data,gradeLevel:'9',...ctx,setToolData:u=>data=typeof u==='function'?u(data):u}));return {data:()=>data.anatomy,patch:p=>data={anatomy:{...data.anatomy,...p}},node:p=>{const n=find(render(),p);expect(n).not.toBeNull();return n;},html:()=>{const root=document.createElement('div');root.innerHTML=renderTool('anatomy',data,{gradeLevel:'9',...ctx});return root;}};}
const control=(s,key)=>s.node(n=>n.props?.['data-anatomy-fact-'+key]===true);
beforeEach(()=>{resetStemLab();vi.useFakeTimers();});afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();vi.restoreAllMocks();});
for(const file of ['stem_lab/stem_tool_anatomy.js','desktop/web-app/public/stem_lab/stem_tool_anatomy.js'])describe('Fact inquiry: '+file,()=>{
 for(const [system,rows]of Object.entries(bank))it('supports all three sourced ideas for '+system,()=>{const spoken=[],s=session(file,{system},{callTTS:v=>spoken.push(v)});for(const [i,row]of rows.entries()){
  const card=()=>s.html().querySelector('[data-anatomy-fact]');expect(card().dataset.anatomyFact).toBe(system+'_'+i);expect(card().textContent).toContain(row[0]);expect(card().textContent).not.toContain(row[1]);expect(control(s,'reveal').props['aria-expanded']).toBe(false);
  s.node(n=>n.props?.['aria-label']==='Read this idea aloud').props.onClick();expect(spoken.at(-1)).toBe(row[0]);control(s,'reveal').props.onClick();expect(card().textContent).toContain(row[1]);expect(card().querySelector('a').href).toBe('https://openstax.org/books/anatomy-and-physiology-2e/pages/'+row[2]);s.node(n=>n.props?.['aria-label']==='Read this idea aloud').props.onClick();expect(spoken.at(-1)).toBe(row[0]+' '+row[1]);control(s,'reveal').props.onClick();expect(card().textContent).not.toContain(row[1]);control(s,'next').props.onClick();
 }expect(s.html().querySelector('[data-anatomy-fact]').dataset.anatomyFact).toBe(system+'_0');expect(s.data()._structureConfidence).toBeUndefined();expect(s.data()._retrievalEvidence).toBeUndefined();});
 it('keeps independent browsing positions while resetting the revealed answer on navigation',()=>{const s=session(file);control(s,'next').props.onClick();control(s,'reveal').props.onClick();s.patch({system:'nervous'});control(s,'previous').props.onClick();s.patch({system:'skeletal'});expect(s.html().querySelector('[data-anatomy-fact]').dataset.anatomyFact).toBe('skeletal_1');expect(control(s,'reveal').props['aria-expanded']).toBe(false);expect(s.data()._factStudy.positions).toEqual({skeletal:1,nervous:2});});
 it('reads fresh state for repeated navigation and preserves newer positions elsewhere',()=>{const s=session(file),next=control(s,'next').props.onClick;s.patch({_factStudy:{version:1,positions:{nervous:2}}});next();next();expect(s.data()._factStudy.positions).toEqual({skeletal:2,nervous:2});});
 it('ignores stale system controls and answer reveals from a different idea',()=>{const s=session(file),reveal=control(s,'reveal').props.onClick,next=control(s,'next').props.onClick;next();reveal();expect(control(s,'reveal').props['aria-expanded']).toBe(false);s.patch({system:'nervous'});next();expect(s.data()._factStudy.positions).toEqual({skeletal:1});});
 it('restores safe legacy positions and ignores invalid saved positions or disclosure IDs',()=>{for(const [legacy,expected]of [[-1,2],['4',1],[Infinity,0],[{},0]]){const s=session(file,{_factIdx:legacy,_factStudy:{version:1,positions:{skeletal:'2',nervous:-1,forged:1},revealedId:'forged'}});expect(s.html().querySelector('[data-anatomy-fact]').dataset.anatomyFact).toBe('skeletal_'+expected);expect(control(s,'reveal').props['aria-expanded']).toBe(false);}for(const raw of [null,[],{version:0,positions:{skeletal:2},revealedId:'skeletal_0'},{version:1,positions:[]}]){const s=session(file,{_factStudy:raw});expect(s.html().querySelector('[data-anatomy-fact]').dataset.anatomyFact).toBe('skeletal_0');expect(control(s,'reveal').props['aria-expanded']).toBe(false);}});
});
