import {afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {loadAlloModule} from './setup.js';
const require=createRequire(import.meta.url),dir=resolve('desktop/web-app/node_modules');
let React,createRoot,act,api,root,host,latest;
beforeAll(()=>{React=require(resolve(dir,'react'));({createRoot}=require(resolve(dir,'react-dom/client')));({act}=require(resolve(dir,'react-dom/test-utils')));window.React=global.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;loadAlloModule('applied_challenge_module.js');api=window.AlloModules.AppliedChallenge;});
afterEach(()=>{if(root)act(()=>root.unmount());root=null;host?.remove();sessionStorage.clear();vi.useRealTimers();});
const source={url:'https://example.org/soil',title:'Soil guide',snippet:'This preview is not learner writing.',foundAt:'2026-09-12'};
const result={source:'Serper',results:[source]};
const ownRow=()=>({id:'own',claim:'Try slower watering.',evidence:'My existing reasoning.',tradeoff:'It takes longer.',status:'verified',factId:'fact-1',factRevision:'r1'});
function Harness({profile='a',searchWeb,disabled=false}){const [data,setData]=React.useState(()=>api.normalize({title:'Garden',scope:'standard',family:'decide',brief:{context:'A fictional garden.',drivingQuestion:'Which approach should we compare?',lockedLessonFacts:['Water can soak into soil.','Water can run off.'],criteria:['Compare options.'],constraints:['No invented results.'],factVerified:true},workspace:{workingQuestion:'Which approach should we compare?',response:'My own draft.'},evidenceLedger:[ownRow()]}));latest=data;return React.createElement(window.AlloModules.AppliedChallengeView,{generatedContent:{id:'source-task',type:'applied-challenge',data},activeProfileId:profile,searchWeb,isTeacherMode:false,callGemini:null,allowRuntimeAi:!disabled,handleNoteUpdate:(key,value)=>setData(old=>({...old,[key]:typeof value==='function'?value(old[key]):value})),addToast:vi.fn()});}
async function mount(props){if(!root){host=document.createElement('div');document.body.appendChild(host);root=createRoot(host);}await act(async()=>root.render(React.createElement(Harness,props)));}
async function button(label){await act(async()=>{const el=[...host.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===label||b.textContent===label);if(!el)throw Error('Button missing: '+label);el.click();});}
async function type(selector,value){await act(async()=>{const el=host.querySelector(selector);const proto=el.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:el.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));});}
async function search(){await button('2. Explore');await act(async()=>{const details=[...host.querySelectorAll('summary')].find(el=>el.textContent==='Find outside evidence').parentElement;details.open=true;details.dispatchEvent(new Event('toggle'));});await type('#aps-source-query','soil infiltration');await button('Search for sources');}
describe('Source references preserve learner ownership',()=>{
 it('keeps links and duplicate protection across multiple batches of search results',()=>{const evidence=Array.from({length:7},(_,i)=>'https://example.org/source-'+i).join('\n');expect(api._testing.appliedChallengeEvidenceLinks(evidence)).toHaveLength(7);expect(api._testing.appliedChallengeAttachReference([{...ownRow(),evidence}],{...source,url:'https://example.org/source-6'},'own','new').reason).toBe('duplicate');});
 it('appends to an existing argument without changing its claim, tradeoff, or lesson connection',()=>{const row=ownRow();const value=api._testing.appliedChallengeAttachReference([row],source,'own','unused');expect(value.ok).toBe(true);expect(value.rows).toHaveLength(1);expect(value.rows[0]).toMatchObject({...row,status:'needs-check',evidence:expect.stringContaining('My existing reasoning.\n\n')});expect(value.rows[0].evidence).toContain(source.url);expect(value.rows[0].evidence).not.toContain(source.snippet);expect(row.status).toBe('verified');});
 it('allows a full ledger to receive a reference in an existing row',()=>{const rows=Array.from({length:12},(_,i)=>({...ownRow(),id:'row-'+i}));expect(api._testing.appliedChallengeAttachReference(rows,source,'row-11','new').ok).toBe(true);expect(api._testing.appliedChallengeAttachReference(rows,source,'','new').reason).toBe('capacity');});
 it('rejects overflow, deleted rows, duplicates and unsafe sources without truncating writing',()=>{const row={...ownRow(),evidence:'x'.repeat(2190)};expect(api._testing.appliedChallengeAttachReference([row],source,'own','new').reason).toBe('length');expect(row.evidence).toHaveLength(2190);expect(api._testing.appliedChallengeAttachReference([row],source,'removed','new').reason).toBe('missing');const inserted=api._testing.appliedChallengeAttachReference([ownRow()],source,'own','new');expect(api._testing.appliedChallengeAttachReference(inserted.rows,source,'own','new').reason).toBe('duplicate');expect(api._testing.appliedChallengeAttachReference([], {...source,url:'javascript:alert(1)'},'','new').reason).toBe('invalid');});
 it('reopens only safe standalone source links from saved evidence',()=>{expect(api._testing.appliedChallengeEvidenceLinks('My explanation.\nhttps://example.org/soil\nhttps://user:pass@example.org/secret\njavascript:alert(1)\nhttps://example.org/soil').map(x=>x.url)).toEqual([source.url]);});
});
describe('Source-search continuity and review',()=>{
 it('retains results across steps without repeating the query, and clears only search UI on request',async()=>{const provider={search:vi.fn(async()=>result)};await mount({searchWeb:provider});await search();await button('3. Build');await button('2. Explore');expect(host.querySelector('#aps-source-query').value).toBe('soil infiltration');expect(host.textContent).toContain('Google results via Serper');expect(provider.search).toHaveBeenCalledTimes(1);await button('Clear this search');expect(host.querySelector('#aps-source-query').value).toBe('');expect(host.textContent).not.toContain('Google results via Serper');expect(latest.workspace.response).toBe('My own draft.');expect(latest.evidenceLedger[0].evidence).toBe('My existing reasoning.');});
 it('attaches to the chosen row, focuses evidence, and offers review prompts without writing them',async()=>{await mount({searchWeb:{search:async()=>result}});await search();const picker=[...host.querySelectorAll('select')].find(el=>[...el.options].some(o=>o.textContent==='A new evidence row'));await act(async()=>{picker.value='own';picker.dispatchEvent(new Event('change',{bubbles:true}));});await button('Add reference to my evidence');expect(latest.evidenceLedger).toHaveLength(1);expect(latest.evidenceLedger[0].claim).toBe('Try slower watering.');expect(latest.evidenceLedger[0].status).toBe('needs-check');expect(document.activeElement.id).toBe('aps-ledger-evidence-own');expect(host.textContent).toContain('Review this source before using it');expect(latest.evidenceLedger[0].evidence).not.toContain('Who wrote it');expect([...host.querySelectorAll('a')].some(a=>a.textContent.includes('Open source: example.org'))).toBe(true);await button('Write my source check');expect(document.activeElement.id).toBe('aps-ledger-evidence-own');});
 it('clears cached search when the profile changes while Explore is hidden',async()=>{const provider={search:async()=>result};await mount({searchWeb:provider});await search();await button('3. Build');await mount({searchWeb:provider,profile:'b'});await button('2. Explore');expect(host.querySelector('#aps-source-query').value).toBe('');expect(host.textContent).not.toContain('Google results via Serper');});
 it('clears cached search when runtime access changes while Explore is hidden',async()=>{const provider={search:async()=>result};await mount({searchWeb:provider});await search();await button('3. Build');await mount({searchWeb:provider,disabled:true});await mount({searchWeb:provider,disabled:false});await button('2. Explore');expect(host.querySelector('#aps-source-query').value).toBe('');expect(host.textContent).not.toContain('Google results via Serper');});
 it('restores the query after an interrupted search and discards its late response',async()=>{let finish;const provider={search:vi.fn(()=>new Promise(resolve=>finish=resolve))};await mount({searchWeb:provider});await search();await button('3. Build');await act(async()=>finish(result));await button('2. Explore');expect(host.querySelector('#aps-source-query').value).toBe('soil infiltration');expect(host.textContent).toContain('unfinished search stopped');expect(host.textContent).not.toContain('Google results via Serper');expect(provider.search).toHaveBeenCalledTimes(1);});
});
