import {afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {loadAlloModule} from './setup.js';
const require=createRequire(import.meta.url),dir=resolve('desktop/web-app/node_modules');
let React,createRoot,act,AC,H,root,host,latest;
beforeAll(()=>{React=require(resolve(dir,'react'));({createRoot}=require(resolve(dir,'react-dom/client')));({act}=require(resolve(dir,'react-dom/test-utils')));window.React=global.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;loadAlloModule('applied_challenge_module.js');AC=window.AlloModules.AppliedChallenge;H=AC._testing;});
afterEach(()=>{if(root)act(()=>root.unmount());root=null;host?.remove();sessionStorage.clear();});
const base=()=>AC.normalize({title:'Garden decision',family:'decide',scope:'standard',brief:{drivingQuestion:'Which plan should we try?',lockedLessonFacts:['Water infiltrates soil.'],criteria:['Connect the lesson.'],constraints:['No invented results.']},workspace:{workingQuestion:'Which plan should we try?',questionAccepted:true,response:'Compare a slower watering trial with a faster approach.',evidence:'Water may run off before it infiltrates.',testReflection:'No local trial has happened yet; we need to check the soil.',revision:'Keep a small trial as the next step rather than claim measured savings.',transferReflection:'This lesson could help compare drainage in another garden.'}});
const citation=()=>H.appliedChallengeOutsideReference({title:'A soil source',url:'https://example.org/soil',foundAt:'2026-09-12'});
describe('Review identifies gaps in recorded work',()=>{
 it('does not count a bare citation as explained evidence, but accepts learner notes',()=>{const data=base();data.workspace.evidence='';data.evidenceLedger=[{id:'r',claim:'Try slower watering.',evidence:citation()}];expect(H.appliedChallengeReviewItems(data).find(x=>x.id==='evidence').recorded).toBe(false);expect(H.appliedChallengeEvidenceLedgerProgress(data.evidenceLedger).complete).toBe(0);expect(H.appliedChallengeReviewFollowups(data)[0]).toMatchObject({id:'row-r',target:{elementId:'aps-ledger-evidence-r'}});data.evidenceLedger[0].evidence+='\nIt explains how soil conditions can change infiltration; local soil is still unknown.';expect(H.appliedChallengeReviewItems(data).find(x=>x.id==='evidence').recorded).toBe(true);expect(H.appliedChallengeEvidenceLedgerProgress(data.evidenceLedger).complete).toBe(1);});
 it('recognizes localized reference metadata without judging short or uncertain notes',()=>{const labels={'applied_challenge.search.reference':'Fuente externa','applied_challenge.search.found':'Encontrado el'};const t=k=>labels[k]||k;expect(H.appliedChallengeEvidenceHasNotes('Fuente externa: Suelo\nhttps://example.org/soil\nEncontrado el: 2026-09-12',t)).toBe(false);expect(H.appliedChallengeEvidenceHasNotes('I do not know yet.')).toBe(true);expect(H.appliedChallengeEvidenceHasNotes('https://example.org/soil')).toBe(false);expect(H.appliedChallengeEvidenceHasNotes('An unfamiliar citation format')).toBe(true);});
 it('prioritizes the question and linked-work explanation, with precise targets',()=>{const d=base();d.workspace.workingQuestion='';d.workspace.response='';d.workspace.artifactUrl='https://example.org/model';let list=H.appliedChallengeReviewFollowups(d);expect(list.slice(0,2).map(x=>x.id)).toEqual(['question','response']);expect(list[1].target.elementId).toBe('applied-artifact-description');d.workspace.artifactUrl='';d.workspace.artifactDescription='My model explanation.';expect(H.appliedChallengeReviewTarget(d,'response').elementId).toBe('applied-artifact-url');});
 it('distinguishes a planned check from an observation, and accepts an honest untested note',()=>{const d=base();d.workspace.testReflection='';d.workspace.revision='';d.validationCycles=[{id:'planned',source:'self',plan:{testQuestion:'Which approach causes runoff?'},observation:{evidence:''},decision:{action:'pending'}}];let item=H.appliedChallengeReviewFollowups(d).find(x=>x.id==='cycle-planned');expect(item.message).toContain('has not happened yet');expect(item.target.elementId).toBe('aps-cycle-observed-planned');d.validationCycles[0].observation.evidence='This has not been tested yet.';item=H.appliedChallengeReviewFollowups(d).find(x=>x.id==='cycle-planned');expect(item.target.elementId).toBe('aps-cycle-decision-planned');d.validationCycles[0].decision={action:'keep',reasoning:''};expect(H.appliedChallengeReviewFollowups(d).find(x=>x.id==='cycle-planned').target.elementId).toBe('aps-cycle-reasoning-planned');d.validationCycles[0].decision.reasoning='Keep the comparison as a proposed next step.';expect(H.appliedChallengeReviewFollowups(d)).toHaveLength(0);});
 it('does not require a declined AI challenge or unused blank organizers to be completed',()=>{const d=base();d.validationCycles=[{id:'declined',source:'ai',disposition:'decline',dispositionReason:'This is outside the available materials.',plan:{testQuestion:'An unsuitable challenge'}}];d.evidenceLedger=[{id:'empty',claim:'',evidence:'',tradeoff:''}];expect(H.appliedChallengeReviewFollowups(d)).toHaveLength(0);expect(H.appliedChallengeReviewTarget(d,'check','declined').elementId).toBe('aps-cycle-choice-declined');});
 it('flags changed criteria and met ratings without notes without requiring all optional ratings',()=>{const d=base(),item=H.appliedChallengeSelfCheckItems(d.brief)[0];expect(H.appliedChallengeReviewFollowups(d)).toHaveLength(0);d.criteriaCheck[item.key]={rating:'met',note:'',revision:item.revision};expect(H.appliedChallengeReviewFollowups(d)[0].target.elementId).toBe('aps-criterion-note-'+item.key);d.criteriaCheck[item.key]={rating:'met',note:'An earlier explanation.',revision:'old'};expect(H.appliedChallengeReviewFollowups(d)[0].target.elementId).toBe('aps-criterion-'+item.key);});
 it('targets visible writing when a paper-only organizer hides evidence rows',()=>{const d=base();d.plan.visualMode='none';d.workspace.evidence='';d.evidenceLedger=[{id:'r',claim:'Option',evidence:citation()}];expect(H.appliedChallengeReviewFollowups(d).find(x=>x.id==='evidence').target.elementId).toBe('applied-workspace-evidence');});
});

function Harness({initial,profile='one'}){const [data,setData]=React.useState(initial);latest=data;return React.createElement(window.AlloModules.AppliedChallengeView,{generatedContent:{id:'review-target',type:'applied-challenge',data},activeProfileId:profile,isTeacherMode:false,callGemini:null,searchWeb:null,handleNoteUpdate:(key,value)=>setData(old=>({...old,[key]:typeof value==='function'?value(old[key]):value})),addToast:vi.fn()});}
async function mount(initial,profile='one'){if(!root){host=document.createElement('div');document.body.appendChild(host);root=createRoot(host);}await act(async()=>root.render(React.createElement(Harness,{initial,profile})));}
async function click(name){await act(async()=>{const button=[...host.querySelectorAll('button')].find(x=>x.textContent===name||x.getAttribute('aria-label')===name);if(!button)throw Error('Missing button '+name);button.click();});}
async function type(id,text){await act(async()=>{const el=host.querySelector('#'+id);Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value').set.call(el,text);el.dispatchEvent(new Event('input',{bubbles:true}));});}
async function review(){await click('5. Reflect');await click('Review my response');}
describe('Review edit-and-return flow',()=>{
 it('opens a citation-only row, preserves its reference, and updates the next step on return',async()=>{const d=base();d.workspace.evidence='';d.evidenceLedger=[{id:'r',claim:'Try slower watering.',evidence:citation()}];await mount(d);await review();expect(host.textContent).toContain('A reference alone does not explain');await click('Work on this next');expect(document.activeElement.id).toBe('aps-ledger-evidence-r');expect(host.textContent).toContain('Editing from your review');await type('aps-ledger-evidence-r',citation()+'\nMy reasoning connects soil condition to runoff.');await click('Return to my review');expect(document.activeElement.id).toBe('aps-review-heading');expect(host.querySelector('#aps-next-improvement-heading')).toBeNull();expect(latest.evidenceLedger[0].evidence).toContain('https://example.org/soil');expect(latest.workspace.response).toBe(d.workspace.response);});
 it('opens the exact detailed observation field and its collapsed ancestors',async()=>{const d=base();d.validationCycles=[{id:'planned',source:'self',plan:{testQuestion:'What might run off?'}}];await mount(d);await review();await click('Work on this next');expect(document.activeElement.id).toBe('aps-cycle-observed-planned');let el=document.activeElement.parentElement;while(el){if(el.tagName==='DETAILS')expect(el.open).toBe(true);el=el.parentElement;}expect(host.querySelector('#applied-validation-body')?.hidden).not.toBe(true);});
 it('opens criterion notes and the exact linked-work explanation from review',async()=>{const d=base(),item=H.appliedChallengeSelfCheckItems(d.brief)[0];d.workspace.response='';d.workspace.artifactUrl='https://example.org/model';d.workspace.artifactDescription='A model comparing infiltration.';d.criteriaCheck[item.key]={rating:'met',note:'',revision:item.revision};await mount(d);await review();await click('Work on this next');expect(document.activeElement.id).toBe('aps-criterion-note-'+item.key);await click('Return to my review');await click('My responseRecorded');expect(document.activeElement.id).toBe('applied-artifact-description');});
 it('clears the return-to-review context when the profile changes',async()=>{const d=base();d.workspace.transferReflection='';await mount(d);await review();await click('Work on this next');expect(host.textContent).toContain('Return to my review');await mount(d,'two');expect([...host.querySelectorAll('button')].some(x=>x.textContent==='Return to my review')).toBe(false);});
});
