import {beforeAll,describe,expect,it} from 'vitest';
import {loadAlloModule} from './setup.js';
let AC,H;
beforeAll(()=>{window.React=window.React||{};loadAlloModule('applied_challenge_module.js');AC=window.AlloModules.AppliedChallenge;H=AC._testing;});
const data=()=>AC.normalize({family:'decide',brief:{drivingQuestion:'Which watering plan should we test?',lockedLessonFacts:['Water infiltrates soil.'],criteria:['Use a lesson idea.'],constraints:['Use classroom materials.'],factVerified:true},workspace:{workingQuestion:'Which plan should we try?',questionAccepted:true}});
describe('Applied challenge response review and expression',()=>{
 it('accepts linked work with an explanation for feedback without requiring an essay',()=>{const value=data();value.workspace.artifactUrl='https://example.org/model';value.workspace.artifactDescription='My diagram compares infiltration with runoff and identifies a small test.';expect(H.appliedChallengeFeedbackReady(value).ok).toBe(true);expect(H.appliedChallengeStressTestReady(value).ok).toBe(true);expect(H.appliedChallengeWorkspaceProgress(value).started).toBe(2);expect(H.appliedChallengeReviewItems(value).find(i=>i.id==='response').recorded).toBe(true);});
 it('does not treat a bare link or an unsafe URL as a completed response',()=>{const value=data();value.workspace.artifactUrl='https://example.org/model';expect(H.appliedChallengeFeedbackReady(value).ok).toBe(false);value.workspace.artifactUrl='javascript:alert(1)';value.workspace.artifactDescription='My explanation';expect(H.appliedChallengeFeedbackReady(value).ok).toBe(false);});
 it('coaches the supplied explanation without claiming to inspect the linked artifact',()=>{const value=data();value.workspace.artifactUrl='https://example.org/private-artifact';value.workspace.artifactDescription='EXPLANATION SENTINEL: water may run off before it can enter soil.';for(const prompt of [H.buildAppliedChallengeFeedbackPrompt(value),H.buildAppliedChallengeStressTestPrompt(value),H.buildAppliedChallengeHintPrompt(value,'response')]){expect(prompt).toContain('EXPLANATION SENTINEL');expect(prompt).toContain('You have not opened or inspected linked');expect(prompt).not.toContain('https://example.org/private-artifact');}});
 it('uses recorded evidence and actual observations for the review checklist',()=>{const value=data();value.evidenceLedger=[{id:'row',claim:'Try slow watering.',evidence:'Give water time to infiltrate.'}];value.validationCycles=[{id:'check',source:'self',plan:{testQuestion:'What runs off?'},observation:{evidence:''},decision:{action:'pending'}}];let items=H.appliedChallengeReviewItems(value);expect(items.find(i=>i.id==='evidence').recorded).toBe(true);expect(items.find(i=>i.id==='check').recorded).toBe(false);value.validationCycles[0].observation.evidence='The trial has not been performed; the soil condition remains unknown.';value.validationCycles[0].decision={action:'keep',reasoning:'Keep a small trial as the next step.'};items=H.appliedChallengeReviewItems(value);expect(items.find(i=>i.id==='check').recorded).toBe(true);expect(items.find(i=>i.id==='decision').recorded).toBe(true);});
 it('keeps linked-work edits in the stale-feedback guard',()=>{const value=data();value.workspace.artifactUrl='https://example.org/model';value.workspace.artifactDescription='Initial explanation.';const old=H.appliedChallengeRequestFingerprint(value,'feedback');value.workspace.artifactDescription='Different reasoning.';expect(H.appliedChallengeRequestFingerprint(value,'feedback')).not.toBe(old);});
});
