import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),React=require('../desktop/web-app/node_modules/react'),{createRoot}=require('../desktop/web-app/node_modules/react-dom/client'),{act}=React;
const source=readFileSync('arcade_mode_concept_pictionary.js','utf8');
let mode,root,element,ctx,update,sessionChange,launch;
const future={modeId:'concept-pictionary',startedAt:'fixture',endsAt:'2099-01-01'},identity={firestoreAppId:'portfolio-fixture',sessionParticipantId:'learner-a'},one=[{term:'Evaporation',def:'Liquid becomes vapor.',image:'https://example.com/water.png'}];
const node=s=>element.querySelector(s),named=s=>[...element.querySelectorAll('button')].find(b=>b.textContent===s);
const click=async s=>{const target=typeof s==='string'?node(s):s;expect(target).toBeTruthy();await act(async()=>target.click());};
const change=async(s,value)=>act(async()=>{const f=node(s);Object.getOwnPropertyDescriptor(f.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(f,value);f.dispatchEvent(new Event('input',{bubbles:true}));});
const flush=()=>act(async()=>window.dispatchEvent(new Event('pagehide')));
const saved=()=>JSON.parse(localStorage.getItem(mode.helpers.workKey(identity)));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
async function render(extra={},initialSession=null){ctx={React,...identity,tokens:10,glossaryEntries:one,callGemini:vi.fn().mockResolvedValue('{"guess":"cloud"}'),callGeminiVision:vi.fn().mockResolvedValue('{"guess":"cloud"}'),...extra};launch=vi.fn();function Host(){const [session,setSession]=React.useState(initialSession),[more,setMore]=React.useState({});update=setMore;sessionChange=setSession;return mode.render({...ctx,...more,session,onLaunch:minutes=>{launch(minutes);setSession(future);return true;},onEndSession:()=>setSession(null)});}element=document.createElement('div');document.body.append(element);root=createRoot(element);await act(async()=>root.render(React.createElement(Host)));}
async function close(){if(root)await act(async()=>root.unmount());root=null;element?.remove();}
async function begin(extra){await render(extra);await click('[data-pic-launch]');}
async function clues(value='Warm liquid rises into the air and becomes a gas.'){await click(named('Describe with words'));await change('#arcade-pictionary-description',value);}
async function stroke(){for(const [type,x,y] of [['pointerdown',20,20],['pointermove',80,80],['pointerup',100,100]])await act(async()=>{const e=new Event(type,{bubbles:true,cancelable:true});Object.assign(e,{clientX:x,clientY:y,pointerId:1,button:0,isPrimary:true});node('canvas').dispatchEvent(e);});}
const drawing=[{tool:'pen',color:'#123456',width:5,points:[[1,2],[8,9]]}];
function work(){return {phase:'playing',setId:'set-fixture',sessionId:'fixture',source:'lesson',topic:'',minutes:5,difficulty:'medium',pool:[{term:'Evaporation',definition:'Liquid becomes vapor.'}],queue:[{term:'Evaporation',definition:'Liquid becomes vapor.'}],index:0,records:[],archive:[],attempts:[],review:'',responseMode:'draw',description:'',strokes:drawing,baseline:null,reflection:'',referenceUsed:false,color:'#123456',penWidth:5,tool:'pen',pendingAI:false};}
function record(id='set-fixture:0'){return {id,concept:{term:'Evaporation',definition:'Liquid becomes vapor.'},attempts:[],matched:false,outcome:'self',baseline:{mode:'draw',strokes:drawing},final:{mode:'describe',text:'Warm liquid rises into the air.'},reflection:'I added direction.',referenceUsed:true};}
beforeEach(()=>{localStorage.clear();globalThis.IS_REACT_ACT_ENVIRONMENT=true;window.React=React;window.AlloHavenArcade={registerMode:(_id,m)=>mode=m,isRegistered:()=>false};new Function(source)();vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue({fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},rect(){},ellipse(){}});vi.spyOn(HTMLCanvasElement.prototype,'toDataURL').mockReturnValue('data:image/jpeg;base64,c2tldGNo');vi.spyOn(HTMLCanvasElement.prototype,'getBoundingClientRect').mockReturnValue({left:0,top:0,width:720,height:480});});
afterEach(async()=>{await close();vi.restoreAllMocks();localStorage.clear();});
describe('bounded account-scoped Pictionary saves',()=>{
 it('separates accounts and apps and has no anonymous save key',()=>{const h=mode.helpers;expect(h.workKey({})).toBe('');expect(h.workKey(identity)).not.toBe(h.workKey({...identity,sessionParticipantId:'learner-b'}));expect(h.workKey(identity)).not.toBe(h.workKey({...identity,firestoreAppId:'elsewhere'}));});
 it('round trips validated work without glossary images or unrelated metadata',()=>{const h=mode.helpers,w=work();w.pool[0].image='https://example.com/private.png';w.queue[0].uid='private';const result=h.writeWork(localStorage,h.workKey(identity),null,w);expect(result.status).toBe('saved');expect(result.raw).not.toContain('private');expect(h.readWork(localStorage,h.workKey(identity)).saved.work.strokes).toEqual(drawing);});
 it('rejects broken versions, excessive drawings, invalid coordinates, and inconsistent progress',()=>{const h=mode.helpers;for(const w of [{...work(),index:1},{...work(),records:[record()]},{...work(),strokes:[{...drawing[0],points:[[Infinity,2]]}]},{...work(),strokes:Array(401).fill(drawing[0])}])expect(()=>h.cleanWork({version:1,revision:1,work:w})).toThrow();expect(()=>h.cleanWork({version:2,revision:1,work:work()})).toThrow();});
 it('preserves malformed and oversized saves rather than silently replacing them',async()=>{const key=mode.helpers.workKey(identity);for(const raw of ['{bad',JSON.stringify({version:99}), 'x'.repeat(2000001)]){localStorage.setItem(key,raw);expect(mode.helpers.readWork(localStorage,key).status).toBe('invalid');}localStorage.setItem(key,'{bad');await begin();await clues();await flush();expect(localStorage.getItem(key)).toBe('{bad');expect(node('[data-pic-save-status]').dataset.picSaveStatus).toBe('invalid');});
 it('preserves the last good save if storage is blocked or full',()=>{const h=mode.helpers,key=h.workKey(identity),old=h.writeWork(localStorage,key,null,work());vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new DOMException('quota','QuotaExceededError');});expect(h.writeWork(localStorage,key,old.raw,{...work(),reflection:'new'}).status).toBe('blocked');expect(localStorage.getItem(key)).toBe(old.raw);const failing={getItem(){throw Error('blocked');}};expect(h.readWork(failing,key).status).toBe('blocked');});
 it('detects newer tab writes and refuses to overwrite them',()=>{const h=mode.helpers,key=h.workKey(identity),first=h.writeWork(localStorage,key,null,work()),second=h.writeWork(localStorage,key,first.raw,{...work(),reflection:'Other tab'});expect(h.writeWork(localStorage,key,first.raw,{...work(),reflection:'Old tab'}).status).toBe('conflict');expect(localStorage.getItem(key)).toBe(second.raw);});
 it('uses the host timer and accepts a paused host session without restoring an expired timer',()=>{const h=mode.helpers;expect(h.sessionUsable(future)).toBe(true);expect(h.sessionUsable({...future,endsAt:'2000-01-01'})).toBe(false);expect(h.sessionUsable({...future,endsAt:'2000-01-01',timerPaused:true,pausedRemainingMs:5000})).toBe(true);expect(h.sessionUsable({...future,modeId:'another'})).toBe(false);});
 it('restores glossary pictures only when the saved concept and definition still match',()=>{const h=mode.helpers,entries=work().queue;expect(h.restorePictures(entries,h.conceptsFrom(one))[0].image).toContain('water.png');expect(h.restorePictures(entries,h.conceptsFrom([{...one[0],def:'Changed definition'}]))[0].image).toBeUndefined();});
});
describe('resume and learning gallery flow',()=>{
 it('saves strokes, alternate text, first submitted clues, attempts, and explanations on close',async()=>{await begin();await stroke();await clues('These alternate clues should stay out of the drawing portfolio.');await click(named('Draw with pointer'));await click('[data-pic-ask]');await change('[data-pic-reflection]','I will add an arrow.');await close();const w=saved().work;expect(w.strokes).toHaveLength(1);expect(w.description).toContain('alternate');expect(w.baseline.mode).toBe('draw');expect(w.attempts).toHaveLength(1);expect(w.reflection).toBe('I will add an arrow.');expect(JSON.stringify(w)).not.toContain('water.png');});
 it('reopens read-only and resumes a running session once without launching or resending AI',async()=>{await begin();await stroke();await click('[data-pic-ask]');await close();await render({},future);expect(node('[data-pic-phase]').dataset.picPhase).toBe('finished');expect(node('canvas')).toBeNull();expect(launch).not.toHaveBeenCalled();const resume=node('[data-pic-resume]');await act(async()=>{resume.click();resume.click();});expect(launch).not.toHaveBeenCalled();expect(ctx.callGeminiVision).not.toHaveBeenCalled();expect(node('[data-pic-guess]').textContent).toContain('cloud');expect(node('[data-pic-undo]').disabled).toBe(true);});
 it('keeps interrupted AI work available without automatically retrying after reopen',async()=>{const pending=deferred();await begin({callGemini:vi.fn(()=>pending.promise)});await clues();await click('[data-pic-ask]');await close();expect(saved().work.pendingAI).toBe(true);await render({},future);expect(element.textContent).toContain('no request was resent');await click('[data-pic-resume]');expect(ctx.callGemini).not.toHaveBeenCalled();expect(node('#arcade-pictionary-description').value).toContain('Warm liquid');await act(async()=>pending.resolve('{"guess":"Evaporation"}'));expect(node('[data-pic-guess]')).toBeNull();});
 it('lets expired work be viewed and exported before explicitly charging once for resume',async()=>{await begin();await clues();await act(async()=>sessionChange(null));await close();await render();expect(launch).not.toHaveBeenCalled();expect(node('[data-pic-gallery-card]')).toBeTruthy();await click('[data-pic-include-drafts]');await click('[data-pic-preview]');expect(node('iframe').srcdoc).toContain('Warm liquid');const resume=node('[data-pic-resume]');await act(async()=>{resume.click();resume.click();});expect(launch).toHaveBeenCalledTimes(1);expect(node('#arcade-pictionary-description').value).toContain('Warm liquid');});
 it('preserves the first snapshot through revision, clear and undo while the latest clues change',async()=>{await begin();await stroke();await click('[data-pic-ask]');await click('[data-pic-revise]');await click('[data-pic-clear]');await click('[data-pic-undo]');await stroke();await click('[data-pic-self-review]');await change('[data-pic-reflection]','I added a second direction.');await click('[data-pic-next]');await flush();const r=saved().work.records[0];expect(r.baseline.strokes).toHaveLength(1);expect(r.final.strokes).toHaveLength(2);expect(r.reflection).toContain('second direction');});
 it('keeps completed records in the gallery across sets and reloads, capped at ten earlier concepts',async()=>{await begin();for(let i=0;i<12;i++){await clues();await click('[data-pic-self-review]');await click('[data-pic-next]');await click('[data-pic-another]');}await close();expect(saved().work.archive).toHaveLength(10);expect(new Set(saved().work.archive.map(r=>r.id)).size).toBe(10);await render();expect(element.querySelectorAll('[data-pic-gallery-card]')).toHaveLength(10);});
 it('requires confirmation before loading another tab save or clearing work',async()=>{await begin();await clues();await flush();const key=mode.helpers.workKey(identity),other=mode.helpers.writeWork(localStorage,key,localStorage.getItem(key),{...saved().work,description:'A newer description in the other tab.'});await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key,newValue:other.raw})));expect(node('[data-pic-save-status]').dataset.picSaveStatus).toBe('conflict');await click('[data-pic-save-load]');expect(node('#arcade-pictionary-description').value).toContain('Warm liquid');await click('[data-pic-save-confirm-action]');await click('[data-pic-resume]');expect(node('#arcade-pictionary-description').value).toContain('newer description');await flush();await click('[data-pic-save-clear]');expect(localStorage.getItem(key)).not.toBeNull();await click('[data-pic-save-confirm-action]');expect(localStorage.getItem(key)).toBeNull();expect(node('[data-pic-phase]').dataset.picPhase).toBe('idle');});
 it('remounts on account change, hiding the old gallery and invalidating pending AI',async()=>{const pending=deferred();await begin({callGemini:vi.fn(()=>pending.promise)});await clues();await click('[data-pic-ask]');await act(async()=>update({sessionParticipantId:'learner-b'}));expect(node('[data-pic-phase]').dataset.picPhase).toBe('idle');expect(node('[data-pic-gallery-card]')).toBeNull();await act(async()=>pending.resolve('{"guess":"Evaporation"}'));expect(node('[data-pic-guess]')).toBeNull();expect(saved().work.description).toContain('Warm liquid');});
 it('invalidates preview after notes change and preserves work when download fails',async()=>{await begin();await clues();await click('[data-pic-self-review]');await click('[data-pic-next]');await click('[data-pic-preview]');expect(node('[data-pic-download="html"]').disabled).toBe(false);await change('[data-pic-gallery-note]','A new explanation');expect(node('[data-pic-download="html"]').disabled).toBe(true);expect(node('[data-pic-portfolio-stale]')).toBeTruthy();await click('[data-pic-preview]');const old=URL.createObjectURL;URL.createObjectURL=()=>{throw Error('blocked');};await click('[data-pic-download="html"]');URL.createObjectURL=old;expect(element.textContent).toContain('could not be downloaded');expect(node('[data-pic-gallery-note]').value).toBe('A new explanation');});
});
describe('safe selected portfolio output',()=>{
 it('keeps unfinished work opt-in and excludes unchecked records, explanations and automatic names',()=>{const h=mode.helpers,cards=[record(),{...record('set-fixture:1'),outcome:'unfinished'}],m=h.portfolioModel(cards,{ids:cards.map(r=>r.id),notes:false,drafts:false});expect(m.name).toBe('');expect(m.cards).toHaveLength(1);expect(m.cards[0].reflection).toBe('');expect(h.portfolioModel(cards,{ids:[cards[1].id],notes:true,drafts:true}).cards).toHaveLength(1);});
 it('escapes arbitrary content and renders only validated script-free vector shapes',()=>{const h=mode.helpers,r=record();r.reflection='<script>alert(1)</script>';r.concept.term='<img src=x onerror=alert(1)>';const m=h.portfolioModel([r],{ids:[r.id],name:'<iframe>',notes:true}),html=h.portfolioHTML(m);const doc=new DOMParser().parseFromString(html,'text/html');expect(doc.querySelector('script,img,iframe,foreignObject,a')).toBeNull();expect(doc.querySelectorAll('svg')).toHaveLength(1);expect(doc.body.textContent).toContain(r.reflection);expect(doc.querySelector('meta[http-equiv]').content).toContain("default-src 'none'");expect(()=>h.drawingSVG([{...drawing[0],color:'red\" onload=alert(1)'}],'test')).toThrow();expect(()=>h.drawingSVG([{...drawing[0],points:[[-1,2]]}],'test')).toThrow();});
 it('exports the chosen first and latest modes without hidden alternate clues or AI request metadata',()=>{const h=mode.helpers,r={...record(),hiddenDescription:'PRIVATE',uid:'PRIVATE',attempts:[{raw:'cloud',reasoning:'PRIVATE',correct:false,mode:'draw'}]},m=h.portfolioModel([r],{ids:[r.id],notes:true});for(const output of [h.portfolioHTML(m),h.portfolioText(m)]){expect(output).not.toContain('PRIVATE');expect(output).toContain('First submitted clues');expect(output).toContain('Warm liquid');}});
 it('deduplicates archived and current copies by record identity',()=>{const r=record();expect(mode.helpers.portfolioCards([r],[r],r)).toHaveLength(1);});
});
