import {beforeAll,afterEach,describe,it,expect,vi} from 'vitest';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const require=createRequire(import.meta.url),React=require('../desktop/web-app/node_modules/react'),{createRoot}=require('../desktop/web-app/node_modules/react-dom/client'),{act}=React;
const candidate=process.env.ALLO_ASSESS_CANDIDATE || 'view_quiz_module.js';
let root,host,serial=0;
const t=(key,opts)=>opts?.defaultValue||({'quiz.reveal_answer':'Reveal answer','quiz.hide_answer':'Hide answer','quiz.show_explanation':'Show explanation','common.start_game':'Games'}[key])||key;
const questions=()=>[
 {type:'short-answer',question:'Explain root growth.',expectedAnswer:'PRIVATE_WRITTEN'},
 {type:'mcq',question:'Choose sunlight.',options:['Sunlight','Stone'],correctAnswer:'Sunlight',factCheck:'PRIVATE_EXPLANATION'},
 {type:'numeric-response',question:'How many leaves?',correctValue:17,unit:'leaves'},
 {type:'multi-select',question:'Choose living things.',options:['Tree','Rock','Flower'],correctAnswers:['Tree','Flower']},
 {type:'fill-blank',question:'Plants use ___.',expectedFill:'PRIVATE_FILL'},
 {type:'self-explanation',question:'Explain photosynthesis.',rubric:'PRIVATE_RUBRIC'},
 {type:'sequence-sense',question:'Inspect the sequence.',items:['First','Second','Third'],presentedOrder:[1,0,2],orderingPrinciple:'process',principleOptions:['process','size']},
 {type:'relation-mismatch',question:'Inspect the pairs.',pairs:[{left:'Root',right:'Air'},{left:'Leaf',right:'Sun'}],wrongPairIndex:0,correctPartnerForWrong:'Water',candidatePartners:['Water','Stone']},
 {type:'answer-evidence',question:'Choose answer and evidence.',answerOptions:['Water','Stone'],correctAnswer:'Water',evidenceOptions:['Roots absorb water','Roots eat rocks'],correctEvidence:'Roots absorb water'}
];
function props(extra={}){return {t,isTeacherMode:false,isParentMode:false,isIndependentMode:false,studentProjectSettings:{},activeSessionCode:null,sessionData:{},isPresentationMode:false,isReviewGame:false,isEditingQuiz:false,escapeRoomState:{isActive:false},presentationState:{},reviewGameState:{},isFactChecking:{},showQuizAnswers:false,leveledTextLanguage:'English',generatedContent:{id:'experience-'+(++serial),type:'quiz',data:{title:'Attempt '+serial,questions:questions(),deliverySettings:{feedbackTiming:'after-submit'}}},formatInlineText:v=>v,renderFormattedText:v=>v,getReviewCategories:()=>[],getRows:()=>1,playSound:vi.fn(),addToast:vi.fn(),onResourceComplete:vi.fn(),handleQuizQuestionAction:vi.fn(),handleToggleIsPresentationMode:vi.fn(),ErrorBoundary:({children})=>children,TeacherLiveQuizControls:()=>null,ConfettiExplosion:()=>null,Stamp:()=>null,...extra};}
const node=s=>host.querySelector(s),button=text=>[...host.querySelectorAll('button')].find(el=>el.textContent.trim()===text);
async function render(p){if(!root){host=document.createElement('div');document.body.append(host);root=createRoot(host);}await act(async()=>root.render(React.createElement(window.AlloModules.QuizView,p)));}
async function click(el){expect(el).toBeTruthy();await act(async()=>el.click());}
async function fill(el,text){expect(el).toBeTruthy();await act(async()=>{const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:el.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,text);el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));});}
async function submit(){await click(button('Review & submit'));await click(button('Submit assessment'));if(button('Submit with unanswered items'))await click(button('Submit with unanswered items'));}
const deferred=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject};};
beforeAll(()=>{global.React=window.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;window.AlloLanguageContext=React.createContext({t});window.__alloT=t;window.AlloIcons={};new Function('window',readFileSync(candidate,'utf8'))(window);});
afterEach(async()=>{if(root)await act(async()=>root.unmount());host?.remove();root=host=null;localStorage.clear();sessionStorage.clear();vi.restoreAllMocks();});

describe('Assess authored question flow and feedback policies',()=>{
 it.each(['immediate','after-submit','teacher-release'])('keeps all nine types in authored order for %s',async timing=>{const p=props();p.generatedContent.data.deliverySettings.feedbackTiming=timing;await render(p);expect([...host.querySelectorAll('[id^="assessment-question-"]')].map(n=>n.id)).toEqual(questions().map((_,i)=>'assessment-question-'+i));expect(host.textContent).not.toContain('Additional Assessment Items');});
 it('holds every answer guide and grading shortcut before delayed submission',async()=>{const p=props({callGemini:vi.fn()});await render(p);expect(host.querySelectorAll('[data-assessment-deferred-item]')).toHaveLength(8);await fill(node('textarea'),'A draft response');await click(node('[id="assessment-question-1"] [role="button"]'));expect(host.textContent).not.toMatch(/PRIVATE_/);expect(host.textContent).not.toMatch(/Grade my answer|Check value|Explain this concept/);expect(p.callGemini).not.toHaveBeenCalled();});
 it('shows saved responses and all answer guides only after submission',async()=>{await render(props());await fill(node('textarea'),'My own response');await submit();expect(node('[data-assessment-delivery-status]').textContent).toBe('Saved on this device');expect(node('[data-assessment-attempt-feedback]').textContent).toContain('My own response');expect(host.textContent).toContain('PRIVATE_WRITTEN');expect(host.querySelectorAll('[data-assessment-answer-guide]')).toHaveLength(9);});
 it('keeps teacher-release feedback hidden after submission until a matching release arrives',async()=>{const p=props();p.generatedContent.data.deliverySettings.feedbackTiming='teacher-release';await render(p);await submit();expect(node('[data-assessment-feedback-waiting]')).toBeTruthy();expect(host.textContent).not.toMatch(/PRIVATE_/);await render({...p,sessionData:{quizState:{assessmentFeedbackRelease:{resourceId:p.generatedContent.id,signature:'another-assessment',releasedAt:1}}}});expect(node('[data-assessment-attempt-feedback]')).toBeNull();});
 it('changes pacing without resetting the chosen feedback policy',async()=>{const p=props({isTeacherMode:true});p.generatedContent.data.deliverySettings.feedbackTiming='teacher-release';await render(p);const preset=[...host.querySelectorAll('button')].find(el=>el.textContent.includes('Focused steps'));await click(preset);expect(p.handleQuizQuestionAction).toHaveBeenCalledWith(0,'patch-assessment',expect.objectContaining({deliverySettings:expect.objectContaining({feedbackTiming:'teacher-release',pacing:'one-at-a-time'})}));});
 it('waits for a confirmed teacher release and reports release failures',async()=>{const wait=deferred(),p=props({isTeacherMode:true,handleQuizQuestionAction:vi.fn(()=>wait.promise)});p.generatedContent.data.deliverySettings.feedbackTiming='teacher-release';await render(p);await click(node('[data-assessment-release-feedback]'));expect(node('[data-assessment-release-feedback]').disabled).toBe(true);await act(async()=>wait.reject(Error('Connection unavailable')));expect(host.textContent).toContain('Connection unavailable');expect(node('[data-assessment-release-feedback]').disabled).toBe(false);});
});

describe('Assess completed-attempt delivery',()=>{
 it('does not claim receipt or completion while the first answer is awaiting confirmation',async()=>{const wait=deferred(),send=vi.fn().mockReturnValueOnce(wait.promise).mockResolvedValue({status:'received'}),p=props({activeSessionCode:'CLASS',sessionData:{quizState:{activityId:'quiz-1',isActive:true}},onSubmitLiveAnswer:send});await render(p);await submit();expect(node('[data-assessment-delivery-status]').textContent).toBe('Sending to teacher...');expect(p.onResourceComplete).not.toHaveBeenCalled();await act(async()=>wait.resolve({status:'received'}));expect(node('[data-assessment-delivery-status]').textContent).toBe('Received by teacher');expect(send).toHaveBeenCalledTimes(10);expect(send.mock.calls.at(-1)[0]).toMatchObject({itemType:'assessment-complete',requireConfirmation:true,activityId:'quiz-1'});expect(p.onResourceComplete).toHaveBeenCalledTimes(1);});
 it.each([undefined,false,{status:'unavailable'},{status:'unconfirmed'},{status:'rejected'}])('retains the attempt and offers retry for unconfirmed outcome %j',async result=>{const send=vi.fn().mockResolvedValue(result),p=props({activeSessionCode:'CLASS',sessionData:{quizState:{activityId:'quiz-1',isActive:true}},onSubmitLiveAnswer:send});await render(p);await fill(node('textarea'),'Keep this response');await submit();expect(node('[data-assessment-delivery-status]').textContent).toBe('Saved on this device');expect(button('Retry delivery')).toBeTruthy();expect(button('Start another attempt')).toBeUndefined();expect(p.onResourceComplete).not.toHaveBeenCalled();const id=send.mock.calls[0][0].requestId;send.mockResolvedValue({status:'received'});await click(button('Retry delivery'));expect(send.mock.calls[1][0].requestId).toBe(id);expect(send.mock.calls[1][0].answer.text).toBe('Keep this response');expect(node('[data-assessment-delivery-status]').textContent).toBe('Received by teacher');});
 it('handles a rejected promise without discarding the completed work',async()=>{const p=props({activeSessionCode:'CLASS',sessionData:{quizState:{activityId:'quiz-1',isActive:true}},onSubmitLiveAnswer:vi.fn().mockRejectedValue(Error('Network failed'))});await render(p);await submit();expect(node('[data-assessment-delivery-status]').textContent).toBe('Saved on this device');expect(host.textContent).toContain('Network failed');expect(button('Download my responses')).toBeTruthy();});
 it('restores an unconfirmed attempt without automatically resending it',async()=>{const p=props({activeSessionCode:'CLASS',sessionData:{quizState:{activityId:'quiz-1',isActive:true}},onSubmitLiveAnswer:vi.fn().mockResolvedValue({status:'unavailable'})});await render(p);await submit();await act(async()=>root.unmount());root=null;host.remove();host=null;p.onSubmitLiveAnswer.mockClear();await render(p);expect(button('Retry delivery')).toBeTruthy();expect(p.onSubmitLiveAnswer).not.toHaveBeenCalled();});
 it('ignores a late delivery result after switching resources',async()=>{const wait=deferred(),p=props({activeSessionCode:'CLASS',sessionData:{quizState:{activityId:'quiz-1',isActive:true}},onSubmitLiveAnswer:vi.fn(()=>wait.promise)});await render(p);await submit();await render({...p,generatedContent:{...p.generatedContent,id:'next-resource',data:{...p.generatedContent.data,title:'A different assessment'}}});await act(async()=>wait.resolve({status:'received'}));expect(node('[data-assessment-submitted]')).toBeNull();expect(p.onResourceComplete).not.toHaveBeenCalled();expect(p.onSubmitLiveAnswer).toHaveBeenCalledTimes(1);});
});

describe('Assess student preview isolation',()=>{
 it('shows the learner layout without writing drafts, submitting, calling AI, or changing teacher content',async()=>{const p=props({isTeacherMode:true,callGemini:vi.fn(),onSubmitLiveAnswer:vi.fn()}),before=JSON.stringify(p.generatedContent);await render(p);await click(node('[data-assessment-preview-toggle]'));expect(node('[data-assessment-student-view]')).toBeTruthy();expect(node('[data-assessment-facilitator-tools]')).toBeNull();await fill(node('textarea'),'Temporary preview');await new Promise(r=>setTimeout(r,400));expect(localStorage.length).toBe(0);await click(button('Review & submit'));expect(button('Submission disabled in preview').disabled).toBe(true);await click(button('Submission disabled in preview'));expect(p.onSubmitLiveAnswer).not.toHaveBeenCalled();expect(p.onResourceComplete).not.toHaveBeenCalled();expect(p.callGemini).not.toHaveBeenCalled();expect(JSON.stringify(p.generatedContent)).toBe(before);});
 it('clears temporary responses when leaving and reopening preview',async()=>{await render(props({isTeacherMode:true}));await click(node('[data-assessment-preview-toggle]'));await fill(node('textarea'),'Temporary');await click(node('[data-assessment-preview-toggle]'));expect(node('[data-assessment-facilitator-tools]')).toBeTruthy();await click(node('[data-assessment-preview-toggle]'));expect(node('textarea').value).toBe('');expect(localStorage.length).toBe(0);});
 it('does not expose preview controls to ordinary Student View',async()=>{await render(props());expect(node('[data-assessment-preview-toggle]')).toBeNull();});
});

async function voice(action,extra={}){let result;await act(async()=>window.dispatchEvent(new CustomEvent('alloflow:quiz-voice-control',{detail:{action,requestId:'experience-'+action,...extra,respond:r=>result=r}})));return result;}
describe('Assess session and voice boundaries',()=>{
 it('keeps feedback release available while live quiz settings are hidden',async()=>{const p=props({isTeacherMode:true,activeSessionCode:'ROOM',sessionData:{quizState:{isActive:true,activityId:'active',questions:[]}},handleQuizQuestionAction:vi.fn().mockResolvedValue(true)});p.generatedContent.data.deliverySettings.feedbackTiming='teacher-release';await render(p);expect(node('[data-assessment-feedback-timing]')).toBeNull();await click(node('[data-assessment-live-feedback-release] [data-assessment-release-feedback]'));expect(p.handleQuizQuestionAction).toHaveBeenCalledWith(0,'release-feedback',{signature:expect.stringMatching(/^assessment-/)});});
 it('reveals completed responses only for the matching resource release',async()=>{const handler=vi.fn().mockResolvedValue(true),p=props({isTeacherMode:true,handleQuizQuestionAction:handler});p.generatedContent.data.deliverySettings.feedbackTiming='teacher-release';await render(p);await click(node('[data-assessment-release-feedback]'));const signature=handler.mock.calls[0][2].signature;const student={...p,isTeacherMode:false};await render(student);await submit();expect(node('[data-assessment-feedback-waiting]')).toBeTruthy();await render({...student,sessionData:{quizState:{assessmentFeedbackRelease:{resourceId:'different-resource',signature}}}});expect(node('[data-assessment-answer-guide]')).toBeNull();await render({...student,sessionData:{quizState:{assessmentFeedbackRelease:{resourceId:p.generatedContent.id,signature}}}});expect(host.querySelectorAll('[data-assessment-answer-guide]')).toHaveLength(9);});
 it('keeps completed attempts separate when another student uses this device',async()=>{const p=props({user:{uid:'learner-a'}});await render(p);await fill(node('textarea'),'Private response A');await submit();await render({...p,user:{uid:'learner-b'}});expect(node('[data-assessment-submitted]')).toBeNull();expect(node('textarea').value).toBe('');await render(p);expect(node('[data-assessment-attempt-feedback]').textContent).toContain('Private response A');});
 it('starts a fresh draft in a new class activity without losing the old pending attempt',async()=>{const p=props({user:{uid:'learner'},activeSessionCode:'ROOM',sessionData:{quizState:{activityId:'first',isActive:true}},onSubmitLiveAnswer:vi.fn().mockResolvedValue({status:'unavailable'})});await render(p);await submit();await render({...p,sessionData:{quizState:{activityId:'second',isActive:true}}});expect(node('[data-assessment-submitted]')).toBeNull();await render(p);expect(button('Retry delivery')).toBeTruthy();});
 it('holds feedback for typed and multiple-choice voice checks',async()=>{const p=props();p.generatedContent.data.deliverySettings.pacing='one-at-a-time';await render(p);expect(await voice('check')).toMatchObject({ok:false,state:'feedback-held'});await voice('next');await voice('choose',{choice:'first'});expect(await voice('check')).toMatchObject({ok:false,state:'feedback-held'});expect(JSON.stringify(await voice('status'))).not.toMatch(/PRIVATE_/);});
 it('does not submit student preview by voice',async()=>{const p=props({isTeacherMode:true,onSubmitLiveAnswer:vi.fn()});await render(p);await click(node('[data-assessment-preview-toggle]'));expect(await voice('submit',{confirmed:true})).toMatchObject({ok:false,state:'preview'});expect(p.onResourceComplete).not.toHaveBeenCalled();expect(p.onSubmitLiveAnswer).not.toHaveBeenCalled();});
 it('describes an unconfirmed completed attempt truthfully by voice',async()=>{const p=props({activeSessionCode:'ROOM',sessionData:{quizState:{activityId:'active',isActive:true}},onSubmitLiveAnswer:vi.fn().mockResolvedValue({status:'unavailable'})});await render(p);const result=await voice('submit',{confirmed:true});expect(result.message).toContain('saved on this device');expect((await voice('status')).message).toContain('Teacher receipt is not yet confirmed');});
});
