import { beforeEach, afterEach, describe, it, expect } from 'vitest';
import { React, ReactDOMClient, loadTool, makeCtx, resetStemLab } from './helpers/stem_widgets_smoke_harness.js';
let root;
beforeEach(()=>{resetStemLab();document.body.innerHTML='<div id="root"></div>';});
afterEach(async()=>{if(root)await React.act(()=>root.unmount());root=null;});
async function mount(initial={}){const tool=loadTool('stem_lab/stem_tool_numberline.js','numberline');let latest;function App(){const[state,setState]=React.useState({_numberline:{tab:'skipcount',muted:true,...initial}});latest=state;return tool.render(makeCtx({toolData:state,labToolData:state,setToolData:setState,setLabToolData:setState}));}root=ReactDOMClient.createRoot(document.getElementById('root'));await React.act(()=>root.render(React.createElement(App)));return()=>latest._numberline;}
function button(label){const b=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===label);expect(b,label).toBeTruthy();return b;}
async function click(label){await React.act(()=>button(label).click());}
async function input(label,value){const el=document.querySelector('input[aria-label="'+label+'"]');expect(el,label).toBeTruthy();await React.act(()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});return el;}
const equation=()=>document.querySelector('[data-skip-equation]').textContent;
const hops=()=>[...document.querySelectorAll('[data-skip-hop]')];
const landings=()=>[...document.querySelectorAll('[data-skip-landing]')].map(e=>Number(e.dataset.skipLanding));
describe('Skip Count: equal intervals and directed movement',()=>{
  it('represents eight hops as eight intervals and nine positions',async()=>{await mount();expect(hops()).toHaveLength(8);expect(landings()).toEqual([0,2,4,6,8,10,12,14,16]);expect(equation()).toBe('0 + 8 × 2 = 16');});
  it('connects a nonzero start to the hop equation',async()=>{await mount({skipFrom:7,skipBy:5,skipCount:3});expect(landings()).toEqual([7,12,17,22]);expect(equation()).toBe('7 + 3 × 5 = 22');});
  it('counts backward across zero with equal descending hops',async()=>{await mount({skipFrom:5,skipBy:3,skipCount:4});await click('← Backward: subtract');expect(landings()).toEqual([5,2,-1,-4,-7]);expect(equation()).toBe('5 − 4 × 3 = -7');for(const hop of hops())expect(Number(hop.dataset.to)-Number(hop.dataset.from)).toBe(-3);expect(button('← Backward: subtract').getAttribute('aria-pressed')).toBe('true');});
  it('keeps the sequence and equations when hiding the line markers',async()=>{await mount();await click('Hide markers on line');expect(document.querySelectorAll('[data-skip-marker]')).toHaveLength(0);expect(landings()).toHaveLength(9);expect(hops()).toHaveLength(8);await click('Show markers on line');expect(document.querySelectorAll('[data-skip-marker]')).toHaveLength(9);});
  it('walks forward and backward through a bounded sequence without changing score',async()=>{const state=await mount({skipFrom:-2,skipBy:3,skipCount:2,score:{correct:4,total:5}});await click('Start at zero hops');expect(hops()).toHaveLength(0);expect(equation()).toBe('-2 + 0 × 3 = -2');expect(button('Previous hop').disabled).toBe(true);await click('Next hop');expect(landings()).toEqual([-2,1]);await click('Next hop');expect(equation()).toBe('-2 + 2 × 3 = 4');expect(button('Next hop').disabled).toBe(true);await click('Previous hop');expect(landings()).toEqual([-2,1]);await click('Show all hops');expect(landings()).toEqual([-2,1,4]);expect(state().score).toEqual({correct:4,total:5});});
  it('restarts the walkthrough when direction or hop size changes',async()=>{await mount();await click('Start at zero hops');await click('Next hop');await click('← Backward: subtract');expect(equation()).toBe('0 − 0 × 2 = 0');await click('Next hop');await input('Skip By','5');expect(equation()).toBe('0 − 0 × 5 = 0');});
  it('preserves start, direction and hop count when selecting a size preset',async()=>{const state=await mount({skipFrom:20,skipCount:3,skipDirection:'backward'});await click('5');expect(equation()).toBe('20 − 3 × 5 = 5');expect(state().skipFrom).toBe(20);expect(state().skipCount).toBe(3);});
  it('supports signed input drafts without moving the committed start until complete',async()=>{await mount({skipFrom:5});const el=await input('Start From','-');expect(el.value).toBe('-');expect(landings()[0]).toBe(5);await input('Start From','-7');expect(landings()[0]).toBe(-7);});
  it('enforces visible input bounds and retains a valid model for incomplete drafts',async()=>{await mount();await input('Skip By','900');await input('Number of hops','99');await input('Start From','-9000');expect(hops()).toHaveLength(20);expect(equation()).toBe('-1000 + 20 × 100 = 1000');await input('Number of hops','');expect(hops()).toHaveLength(20);await input('Number of hops','1');expect(hops()).toHaveLength(1);});
  it.each(['forward','backward'])('keeps the one-hop and maximum-hop models finite (%s)',async(skipDirection)=>{await mount({skipDirection,skipFrom:1000,skipBy:100,skipCount:20});expect(hops()).toHaveLength(20);expect(landings().at(-1)).toBe(skipDirection==='forward'?3000:-1000);for(const p of document.querySelectorAll('[data-skip-hop] path'))expect(p.getAttribute('d')).not.toMatch(/NaN|Infinity/);});
});
