import {beforeEach,describe,expect,it} from 'vitest';
import {loadTool,resetStemLab,renderTool} from './helpers/stem_widgets_smoke_harness.js';
let api;
const q=(id=3,c='C',e='0',base='B',polarity='npn',parameters={})=>({id,type:'bjt',a:c,b:e,bjt:{base,polarity,...parameters}});
const v=(id,a,value,b='0')=>({id,type:'voltage',a,b,value});
const r=(id,a,b,value)=>({id,type:'resistor',a,b,value});
const bias=(polarity='npn',drive=.65)=>({components:[v(1,'A',polarity==='npn'?5:-5),r(2,'A','C',1000),q(3,'C','0','B',polarity),v(4,'B',polarity==='npn'?drive:-drive)]});
const loaded=(input=5,rb=10000)=>({components:[v(1,'A',5),r(2,'A','C',1000),q(),r(4,'D','B',rb),v(5,'D',input)]});
const row=(s,id=3)=>s.rows.find(row=>row.component.id===id);
const normalize=p=>api.circuitNetworkDesign({components:[p]}).components[0];
const reference=(p,vbe,vbc)=>{const m=p.bjt,sign=m.polarity==='pnp'?-1:1,af=m.betaForward/(1+m.betaForward),ar=m.betaReverse/(1+m.betaReverse),forward=m.saturationCurrent/af*Math.expm1(sign*vbe/.02585),reverse=m.saturationCurrent/ar*Math.expm1(sign*vbc/.02585);return [sign*(af*forward-reverse),sign*((1-af)*forward+(1-ar)*reverse),-sign*(forward-ar*reverse)];};
const bisect=(f,lo,hi)=>{expect(f(lo)*f(hi)).toBeLessThanOrEqual(0);for(let i=0;i<90;i++){const mid=(lo+hi)/2;if(f(mid)>0)hi=mid;else lo=mid;}return (lo+hi)/2;};
const balance=s=>{expect(s.ok,s.message).toBe(true);for(const b of s.balances)if(b.current!=null)expect(Math.abs(b.current)).toBeLessThan(2e-9);if(s.absorbed!=null)expect(s.absorbed).toBeCloseTo(s.delivered,8);for(const x of s.rows.filter(r=>r.component.bjt)){expect(x.current+x.baseCurrent+x.emitterCurrent).toBe(0);expect(x.power).toBeCloseTo(x.voltage*x.current+x.bjtVBE*x.baseCurrent,12);}};
beforeEach(()=>{resetStemLab();loadTool('stem_lab/stem_tool_circuit.js','circuit');api=window.StemLab;});
describe('reciprocal Ebers-Moll transistor model',()=>{
 it('normalizes NPN/PNP parameters without changing input or non-transistor designs',()=>{const p=q(1,'A','0','Z','bad',{betaForward:Infinity,betaReverse:0,saturationCurrent:0}),original=JSON.stringify(p),n=normalize(p);expect(n.bjt).toEqual({model:'ebers-moll',polarity:'npn',base:'B',betaForward:100,betaReverse:.1,saturationCurrent:1e-18,thermalVoltage:.02585});expect(JSON.stringify(p)).toBe(original);expect(normalize(r(2,'A','0',1000))).not.toHaveProperty('bjt');expect(normalize(q(2,'A','0','0','pnp',{betaForward:2000,betaReverse:200,saturationCurrent:1})).bjt).toMatchObject({polarity:'pnp',base:'0',betaForward:1000,betaReverse:100,saturationCurrent:1e-9});});
 it.each(['npn','pnp'])('matches independent alpha-form equations in all %s bias quadrants',polarity=>{const p=normalize(q(1,'C','E','B',polarity,{betaForward:175,betaReverse:3.5})),sign=polarity==='npn'?1:-1;for(const [be,bc] of [[0,0],[.65,-3],[.7,.6],[-3,.65],[-2,-3],[.1,-.1]]){const actual=api.circuitNetworkBJTLaw(p,sign*be,sign*bc),expected=reference(p,sign*be,sign*bc);for(const [i,key] of ['collector','base','emitter'].entries())expect(actual[key]).toBeCloseTo(expected[i],12);expect(actual.collector+actual.base+actual.emitter).toBe(0);}});
 it.each(['npn','pnp'])('matches the %s terminal Jacobian to independent finite differences',polarity=>{const p=normalize(q(1,'C','E','B',polarity)),sign=polarity==='npn'?1:-1;for(const voltages of [[.1,.69,0],[4,.65,.02],[.1,.02,.68]]){const nodes=voltages.map(v=>v*sign),law=api.circuitNetworkBJTLaw(p,nodes[1]-nodes[2],nodes[1]-nodes[0]);for(let j=0;j<3;j++){const plus=[...nodes],minus=[...nodes];plus[j]+=1e-6;minus[j]-=1e-6;const a=reference(p,plus[1]-plus[2],plus[1]-plus[0]),b=reference(p,minus[1]-minus[2],minus[1]-minus[0]);for(let i=0;i<3;i++)expect(law.jacobian[i][j]).toBeCloseTo((a[i]-b[i])/2e-6,7);}}});
 it('labels bias regions by junction polarity without a fixed on-voltage',()=>{const p=normalize(q());for(const [be,bc,region] of [[0,-5,'Cutoff / leakage'],[.1,-5,'Forward active'],[.7,.1,'Saturation'],[-5,.1,'Reverse active']])expect(api.circuitNetworkBJTLaw(p,be,bc).region).toBe(region);});
 it('does not replace an overflowing exponential with a clipped current',()=>{const p=normalize(q());expect(Number.isFinite(api.circuitNetworkBJTLaw(p,1000,0).collector)).toBe(false);const d={components:[q(),v(1,'C',5),v(2,'B',24)]},s=api.solveNetworkCircuit(d);expect(s.ok).toBe(false);expect(row(s).current).toBeNull();expect(row(s).baseCurrent).toBeNull();expect(row(s).power).toBeNull();});
});
describe('three-terminal network solving',()=>{
 it.each(['npn','pnp'])('solves a voltage-biased %s with independently calculated currents and power',polarity=>{const d=bias(polarity),s=api.solveNetworkCircuit(d),x=row(s),sign=polarity==='npn'?1:-1,ic=sign*1e-14*(Math.expm1(.65/.02585)+2),ib=sign*1e-14*(Math.expm1(.65/.02585)/100-1);balance(s);expect(x.current).toBeCloseTo(ic,12);expect(x.baseCurrent).toBeCloseTo(ib,12);expect(x.voltage).toBeCloseTo(sign*5-1000*ic,11);expect(x.bjtRegion).toBe('Forward active');expect(x.power).toBeGreaterThan(x.voltage*x.current);});
 it.each([[1,100000],[5,10000]])('matches a nested independent DC root for input %s V through %s ohms', (input,rb)=>{const d=loaded(input,rb),p=normalize(q()),collector=base=>bisect(vc=>reference(p,base,base-vc)[0]-(5-vc)/1000,0,5),base=bisect(vb=>reference(p,vb,vb-collector(vb))[1]-(input-vb)/rb,0,Math.min(input,.9)),vc=collector(base),s=api.solveNetworkCircuit(d);balance(s);expect(row(s).bjtVBE).toBeCloseTo(base,8);expect(row(s).voltage).toBeCloseTo(vc,8);expect(row(s).baseCurrent).toBeCloseTo((input-base)/rb,10);});
 it('limits saturated collector current through the load instead of forcing beta times base current',()=>{const s=api.solveNetworkCircuit(loaded()),x=row(s);balance(s);expect(x.bjtRegion).toBe('Saturation');expect(x.voltage).toBeGreaterThan(0);expect(x.voltage).toBeLessThan(.15);expect(x.current).toBeLessThan(.005);expect(x.current/x.baseCurrent).toBeLessThan(20);});
 it('retains signed leakage at cutoff',()=>{const s=api.solveNetworkCircuit(bias('npn',0)),x=row(s);balance(s);expect(x.bjtRegion).toBe('Cutoff / leakage');expect(x.current).toBeCloseTo(2e-14,22);expect(x.baseCurrent).toBeCloseTo(-1e-14,22);expect(x.voltage).toBeCloseTo(5,8);});
 it('solves reverse active bias with the reverse gain',()=>{const s=api.solveNetworkCircuit({components:[q(),v(1,'C',-.65),v(2,'B',0)]}),x=row(s),p=normalize(q()),expected=reference(p,0,.65);balance(s);expect(x.bjtRegion).toBe('Reverse active');expect(x.current).toBeCloseTo(expected[0],12);expect(x.emitterCurrent/x.baseCurrent).toBeCloseTo(p.bjt.betaReverse,8);});
 it('solves a loaded emitter follower and includes base loading',()=>{const d={components:[v(1,'A',5),q(3,'A','C','B'),v(2,'D',1.5),r(4,'D','B',10000),r(5,'C','0',1000)]},s=api.solveNetworkCircuit(d),x=row(s);balance(s);expect(s.difference('C','0')).toBeGreaterThan(.7);expect(s.difference('C','0')).toBeLessThan(.9);expect(s.difference('D','B')).toBeCloseTo(x.baseCurrent*10000,10);expect(s.difference('C','0')/1000).toBeCloseTo(-x.emitterCurrent,10);});
 it('solves two coupled transistors with the reference branch supplying both base currents',()=>{const d={components:[v(1,'A',5),r(2,'A','B',1000),q(3,'B','0','B'),q(4,'C','0','B'),r(5,'A','C',1000)]},s=api.solveNetworkCircuit(d),a=row(s,3),b=row(s,4);balance(s);expect(a.current).toBeCloseTo(b.current,9);expect(row(s,2).current).toBeCloseTo(a.current+a.baseCurrent+b.baseCurrent,10);});
 it('keeps all three internal currents and differences in a fully floating circuit',()=>{const d=loaded(),floating={components:d.components.map(p=>({...p,a:p.a==='0'?'G':p.a,b:p.b==='0'?'G':p.b}))},s=api.solveNetworkCircuit(floating),base=api.solveNetworkCircuit(d);balance(s);expect(s.difference('B','0')).toBeNull();expect(s.difference('C','G')).toBeCloseTo(row(base).voltage,9);expect(row(s).baseCurrent).toBeCloseTo(row(base).baseCurrent,11);});
 it('counts a base-only node and every current incidence, including tied terminals',()=>{const d=bias(),s=api.solveNetworkCircuit(d),base=api.circuitNetworkNodeInspection(s,'B');expect(s.nodes.find(n=>n.id==='B').used).toBe(true);expect(base.connections.find(c=>c.id===3)).toMatchObject({terminal:'B',leaving:row(s).baseCurrent});expect(base.residual).toBeCloseTo(0,11);const same=api.solveNetworkCircuit({components:[q(3,'A','A','A')]});balance(same);expect(row(same).current).toBe(0);expect(api.circuitNetworkNodeInspection(same,'A').connections.map(c=>c.terminal)).toEqual(['C','E','B']);expect(same.difference('A','0')).toBeNull();});
 it('supports a diode-connected transistor driven by a known current',()=>{const d={components:[{id:1,type:'current',a:'0',b:'B',value:.001},q(3,'B','0','B')]},s=api.solveNetworkCircuit(d),expected=.02585*Math.log1p(.001/(1.01e-14));balance(s);expect(row(s).bjtVBE).toBeCloseTo(expected,10);expect(row(s).current+row(s).baseCurrent).toBeCloseTo(.001,11);});
});
describe('transistor dynamics and presentation',()=>{
 it.each(['backward-euler','trapezoidal'])('couples to capacitor state using %s with finite conserved readings',integration=>{const d={...loaded(),integration,duration:.03};d.components[4].value=0;d.components[4].waveform={shape:'pulse',amplitude:5,frequency:100,edge:2};d.components.push({id:6,type:'capacitor',a:'C',b:'0',value:1,initial:5});const run=api.circuitNetworkTransient(d);expect(run.ok,run.message).toBe(true);expect(run.frames[0].rows.find(r=>r.component.id===6).voltage).toBeCloseTo(5,10);expect(Math.min(...run.frames.map(f=>row(f).voltage))).toBeLessThan(.2);for(const f of run.frames)balance(f);expect(run.frames.some(f=>row(f).bjtRegion==='Saturation')).toBe(true);});
 it.each(['backward-euler','trapezoidal'])('matches an independent RC analytical response with a biased BJT using %s',integration=>{const d={...bias(),integration,duration:.005};d.components.push({id:6,type:'capacitor',a:'C',b:'0',value:1,initial:5});const run=api.circuitNetworkTransient(d),ic=1e-14*(Math.expm1(.65/.02585)+2);expect(run.ok,run.message).toBe(true);for(const f of run.frames){const exact=5-1000*ic*(1-Math.exp(-f.time/.001));expect(Math.abs(row(f).voltage-exact)).toBeLessThan(integration==='trapezoidal'?.0002:.002);expect(row(f).current).toBeCloseTo(ic,12);balance(f);}
 // Use the established 200 microvolt trapezoidal RC budget; the default integrator includes startup restarts.
 // An independently constructed current-source circuit must reproduce the full transistor trajectory.
 const equivalent=api.circuitNetworkTransient({...d,components:d.components.filter(p=>p.id!==4).map(p=>p.id===3?{id:3,type:'current',a:'C',b:'0',value:ic}:p)});expect(equivalent.ok,equivalent.message).toBe(true);expect(equivalent.frames).toHaveLength(run.frames.length);for(let i=0;i<run.frames.length;i++){expect(run.frames[i].time).toBeCloseTo(equivalent.frames[i].time,12);expect(row(run.frames[i],6).voltage).toBeCloseTo(row(equivalent.frames[i],6).voltage,10);}});
 it('preserves capacitor voltage across an explicit switch in the transistor base drive',()=>{const d={integration:'trapezoidal',duration:.005,components:[v(1,'A',5),r(2,'A','C',1000),q(),v(4,'D',.65),{id:5,type:'switch',a:'D',b:'B',closed:true,switching:{enabled:true,events:[{id:1,time:.002,closed:false}]}},r(6,'B','0',100000),{id:7,type:'capacitor',a:'C',b:'0',value:1,initial:5}]},run=api.circuitNetworkTransient(d);expect(run.ok,run.message).toBe(true);const before=api.circuitNetworkFrame(run,.002,'before'),after=api.circuitNetworkFrame(run,.002,'after');expect(row(before).voltage).toBeCloseTo(row(after).voltage,12);expect(row(before).current).toBeGreaterThan(.0008);expect(Math.abs(row(after).current)).toBeLessThan(1e-10);balance(before);balance(after);});

 it('integrates a BJT, diode, and controlled source in one nonlinear network',()=>{const d=loaded(1,100000);d.components.push({id:6,type:'diode',a:'C',b:'0',diode:{model:'silicon',seriesResistance:1000}},{id:7,type:'vccs',a:'C',b:'0',value:.0001,control:{positive:'B',negative:'0'}});balance(api.solveNetworkCircuit(d));});
 it('invalidates held samples when base connection or model parameters change',()=>{const d={...bias(),duration:.01},run=api.circuitNetworkTransient(d),held=api.circuitNetworkHold(run,run.frames[0]);for(const change of [{base:'C'},{betaForward:200},{polarity:'pnp'}]){const updated={...d,components:d.components.map(p=>p.type==='bjt'?{...p,bjt:{...p.bjt,...change}}:p)},next=api.circuitNetworkTransient(updated);expect(api.circuitNetworkHeld(next,held)).toBeNull();}});
 it('exports aligned three-terminal model, current, and junction columns in DC and time data',()=>{const d=bias(),s=api.solveNetworkCircuit(d),run=api.circuitNetworkTransient(d);for(const text of [api.circuitNetworkCSV(d,s),api.circuitNetworkTransientCSV(d,run)]){const [header,...lines]=text.split('\n'),keys=header.split(','),cells=lines.find(line=>line.includes(',bjt,')).split(','),values=Object.fromEntries(keys.map((k,i)=>[k,cells[i]]));for(const line of lines)expect(line.split(',')).toHaveLength(keys.length);expect(values.bjt_base_node).toBe('B');expect(values.bjt_polarity).toBe('npn');expect(Number(values.bjt_base_current_A)).toBeCloseTo(row(s).baseCurrent,12);expect(Number(values.bjt_emitter_current_A)+Number(values.bjt_base_current_A)+Number(values.current_a_to_b_A)).toBeCloseTo(0,12);expect(values.bjt_region).toBe('Forward active');expect(Number(values.bjt_VCE_V)).toBeCloseTo(row(s).voltage,12);expect(Number(values.bjt_collector_current_A)).toBeCloseTo(row(s).current,12);expect(Number(values.bjt_total_power_W)).toBeCloseTo(row(s).power,12);}});
 it('routes all three terminals and preserves the base node in the orbit geometry',()=>{const d=api.circuitNetworkDesign(bias()),layout=api.circuitNetworkLayout(d.components),routes=api.circuitNetworkRoutes(d.components,layout,false,{}),g=api.circuitNetworkOrbitGeometry(d),part=g.parts.find(p=>p.id===3);expect(routes.routes[2]).toHaveLength(3);expect(part.paths.map(p=>[p.terminal,p.node])).toEqual([['C','C'],['E','0'],['B','B']]);expect(g.nodes.some(n=>n.id==='B')).toBe(true);expect(part.paths.every(p=>p.clear&&p.points.every(v=>v.every(Number.isFinite)))).toBe(true);const s=api.solveNetworkCircuit(d);expect([0,1,2].map(j=>api.circuitNetworkTerminalCurrent(row(s),j))).toEqual([row(s).current,row(s).emitterCurrent,row(s).baseCurrent]);});
 it.each([false,true])('keeps the base-wire approach outside the package and reaches its own pad, projected=%s',solid=>{const d=api.circuitNetworkDesign(bias()),layout=api.circuitNetworkLayout(d.components),geometry=api.circuitNetworkRoutes(d.components,layout,solid,{}),route=geometry.routes[2][2],own=geometry.obstacles.find(r=>r.part===3),entry=route.points.at(-4),pad=route.points.at(-3);expect(route.clear).toBe(true);expect(entry[0]).toBeCloseTo(pad[0],12);expect(entry[1]).toBeLessThanOrEqual(own.y0-12);expect(pad[1]-entry[1]).toBeGreaterThanOrEqual(22);for(let i=1;i<route.points.length-3;i++){const a=route.points[i-1],b=route.points[i];if(Math.abs(a[0]-b[0])<1e-8&&a[0]>own.x0&&a[0]<own.x1)expect(Math.min(a[1],b[1])>=own.y1||Math.max(a[1],b[1])<=own.y0).toBe(true);if(Math.abs(a[1]-b[1])<1e-8&&a[1]>own.y0&&a[1]<own.y1)expect(Math.min(a[0],b[0])>=own.x1||Math.max(a[0],b[0])<=own.x0).toBe(true);}});
 it('renders transistor editing, model limits, C/B/E routes, and correctly named measurements',()=>{const html=renderTool('circuit',{_circuit:{networkWorkbench:true},_circuitNetwork:{...bias(),selected:3,view:'flat',analysis:'time',duration:.001}});for(const text of ['Collector node C','Emitter node E','Base node B','Transistor polarity','Forward current gain βF','Transistor operating point','Collector current IC','Voltage C − E','IC + IB + IE','data-terminal-route="3:C"','data-terminal-route="3:E"','data-terminal-route="3:B"','charge storage','NPN: a base-driven switch'])expect(html).toContain(text);expect(html).not.toContain('NaN');});
 it('hides all transistor currents when initial constraints make time response fail',()=>{const d=bias();d.components.push({id:6,type:'capacitor',a:'A',b:'0',value:1,initial:0});const html=renderTool('circuit',{_circuit:{networkWorkbench:true},_circuitNetwork:{...d,selected:3,analysis:'time'}});expect(html).toContain('data-bjt-region="Undetermined"');expect(html).toContain('data-bjt-current="B">Undetermined');expect(html).toContain('data-bjt-current="E">Undetermined');expect(html).not.toContain('Time response of Q3');});
});
