import { beforeAll, afterEach, describe, it, expect, vi } from 'vitest';
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import * as engine from '../connected_escape_room_engine.js';
import { playerReviewCase, reviewPrompt, assessReview, reviewRoom } from '../connected_escape_room_review.js';
import { restoreSolo, soloAction, soloStorageKey } from '../connected_escape_room_solo.js';
import { loadAlloModule } from './setup.js';
const require=createRequire(import.meta.url),{source,makeRoom}=require('../dev-tools/fixtures/connected_escape_room.cjs'),{reviewResponse}=require('../dev-tools/fixtures/connected_escape_review.cjs');
const React=require('../desktop/web-app/node_modules/react'),{createRoot}=require('../desktop/web-app/node_modules/react-dom/client'),{act}=React;
let host,root,api,write;
const t=k=>k,base={user:{uid:'solo-student'},appId:'app',inputText:source,activeSessionCode:null,allowLive:false,t,onClose:()=>{},callGemini:async prompt=>prompt.startsWith('Independently')?reviewResponse(prompt):JSON.stringify(makeRoom())};
beforeAll(()=>{global.React=window.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;write=vi.fn();window.__alloFirebase={db:{},doc:()=>({}),updateDoc:write};loadAlloModule('connected_escape_room_module.js');window.AlloLanguageContext=React.createContext({t});window.UiLanguageSelector=()=>null;loadAlloModule('view_quiz_module.js');api=window.AlloModules;});
afterEach(async()=>{if(root)await act(async()=>root.unmount());host?.remove();root=host=null;sessionStorage.clear();localStorage.clear();write.mockReset();vi.restoreAllMocks();});
async function render(props={},Component=api.ConnectedEscapeRoomSetup){if(!host){host=document.createElement('div');document.body.appendChild(host);}if(!root)root=createRoot(host);await act(async()=>root.render(React.createElement(Component,{...base,...props})));}
async function click(el){expect(el).toBeTruthy();await act(async()=>el.click());}
const button=name=>[...host.querySelectorAll('button')].find(el=>el.textContent.trim()===name);
const object=id=>host.querySelector('[data-object="'+id+'"]');
async function choose(i,value){await act(async()=>{const s=host.querySelector('[data-control="'+i+'"]');s.value=value;s.dispatchEvent(new Event('change',{bubbles:true}));});}
async function generated(){await render();await click(button('Generate connected room'));}
async function unmount(){await act(async()=>root.unmount());root=null;}
const answer=(answer,confidence='clear')=>({answer,confidence,reason:'The evidence supports the settings.',suggestion:''});

describe('Independent player-visible AI review',()=>{
 it('hides answer metadata, hints, own reward, source key and downstream evidence',()=>{const room=makeRoom();room.nodes[4].reward.text='SECRET_FUTURE_REWARD';room.nodes[4].hints=['SECRET_HINT_A','SECRET_HINT_B','SECRET_HINT_C'];room.nodes[4].explanation='SECRET_EXPLANATION';room.debrief='SECRET_DEBRIEF';room.nodes[4].sourceQuote='SECRET_SOURCE';const payload=JSON.stringify(playerReviewCase(room,'device'));expect(payload).toContain(source);for(const secret of ['SECRET_','correctIndex','sourceQuote','toolId','order','learningObjective'])expect(payload).not.toContain(secret);expect(payload).not.toContain('Cycle key');});
 it('never sends a hidden coordinate origin or displacement',()=>{const room=makeRoom();const n=room.nodes[5];n.type='route';n.grid={size:4,originX:2,originY:2,dx:1,dy:-1};const p=JSON.stringify(playerReviewCase(room,n.id));expect(p).toContain('gridSize');expect(p).not.toMatch(/originX|originY|"dx"|"dy"/);expect(assessReview(room,n,answer([3,1])).status).toBe('matched');});
 it('compares independently proposed answers instead of trusting an AI pass label',()=>{const room=makeRoom(),n=room.nodes[4];expect(assessReview(room,n,{...answer([0,1]),pass:true}).status).toBe('needs-review');expect(assessReview(room,n,answer([1,0])).status).toBe('matched');expect(assessReview(room,n,answer([1,0],'ambiguous')).status).toBe('needs-review');expect(assessReview(room,n,answer(null,'insufficient')).matches).toBe(false);});
 it.each([[1],[9,0],['1',0],null])('rejects invalid check data %#',value=>{const room=makeRoom();expect(()=>assessReview(room,room.nodes[4],value===null?{}:answer(value))).toThrow();});
 it('rejects duplicate sequence indices and unavailable tool choices',()=>{const room=makeRoom();expect(()=>assessReview(room,room.nodes[5],answer([0,0,1,2]))).toThrow();expect(()=>assessReview(room,room.nodes[2],answer('device-found'))).toThrow();});
 it('uses one independent JSON request per device and reports matching answers',async()=>{const provider=vi.fn(async p=>reviewResponse(p)),progress=[];const result=await reviewRoom(provider,makeRoom(),{language:'Spanish'},v=>progress.push(v));expect(provider).toHaveBeenCalledTimes(3);expect(provider.mock.calls.every(c=>c[1]===true&&c[0].includes('Spanish'))).toBe(true);expect(result.complete).toBe(true);expect(result.checks.map(c=>c.status)).toEqual(['matched','matched','matched']);expect(progress.map(p=>p.current)).toEqual([1,2,3]);});
 it.each(['{}','not json','x'.repeat(17000)])('does not report malformed provider output as a pass',async response=>{const provider=vi.fn(async()=>response),r=await reviewRoom(provider,makeRoom());expect(r.complete).toBe(false);expect(r.checks[0].status).toBe('unavailable');expect(provider).toHaveBeenCalledTimes(1);});
 it('stops subsequent requests when cancelled and does not return stale results',async()=>{let finish,active=true;const provider=vi.fn(()=>new Promise(r=>finish=r));const pending=reviewRoom(provider,makeRoom(),{shouldContinue:()=>active});active=false;finish(reviewResponse(provider.mock.calls[0][0]));expect(await pending).toBeNull();expect(provider).toHaveBeenCalledTimes(1);});
 it('stops after an unavailable provider and leaves the room untouched',async()=>{const room=makeRoom(),before=JSON.stringify(room),provider=vi.fn(async()=>{throw Error('offline');});expect((await reviewRoom(provider,room)).complete).toBe(false);expect(provider).toHaveBeenCalledTimes(1);expect(JSON.stringify(room)).toBe(before);});
});

describe('Solo state independent of live sessions',()=>{
 it('can solve the entire room, with hints and wrong answers, using the production rules',()=>{const room=makeRoom();let state=restoreSolo(room,null);expect(soloAction(room,state,'door','interact','').code).toBe('locked');for(const n of room.nodes){if(n.type==='configure'){expect(soloAction(room,state,n.id,'interact','0,1').code).toBe('try-again');state=soloAction(room,state,n.id,'hint','').state;}const result=soloAction(room,state,n.id,'interact',engine.solutionValue(room,n));state=result.state;}expect(engine.complete(room,state.progress)).toBe(true);expect(engine.hintLevel(state.progress,'device')).toBe(1);expect(state.progress.receipts).toEqual({});});
 it('restores known reachable progress and drops invalid or forged fields',()=>{const room=makeRoom(),state=restoreSolo(room,null);state.progress={solved:{lens:true,wall:true,door:true,unknown:true},hints:{wall:{h1:true,h3:true},door:{h1:true}},receipts:{old:{}},assisted:{wall:true}};const p=restoreSolo(room,state).progress;expect(p.solved).toEqual({lens:true,wall:true});expect(p.hints).toEqual({wall:{h1:true}});expect(p.receipts).toEqual({});expect(p.assisted).toEqual({});});
 it('isolates learners and resets progress for changed room content',()=>{const room=makeRoom(),state=restoreSolo(room,null);state.progress.solved.lens=true;const changed=makeRoom();changed.nodes[0].instruction+=' New';expect(restoreSolo(changed,state).progress.solved).toEqual({});expect(soloStorageKey(room,'one')).not.toBe(soloStorageKey(room,'two'));expect(soloStorageKey(room,'one')).not.toBe(soloStorageKey(changed,'one'));});
});

describe('Solo launch, recovery and review UI',()=>{
 it('opens solo without a session, uses personal labels, and never writes multiplayer state',async()=>{await generated();expect(host.querySelector('[data-launch-connected]')).toBeNull();await click(button('Play solo'));expect(host.querySelector('[data-solo-room]')).toBeTruthy();expect(host.textContent).toContain('Your journal');expect(host.textContent).not.toContain('Shared inventory');await click(host.querySelector('[data-submit-object="lens"]'));expect(host.querySelector('[role="progressbar"]').getAttribute('aria-valuenow')).toBe('1');expect(write).not.toHaveBeenCalled();});
 it('resumes discoveries and unfinished settings after reload without any submission',async()=>{await generated();await click(button('Play solo'));for(const id of ['lens','notes']){await click(object(id));await click(host.querySelector('[data-submit-object="'+id+'"]'));}await click(object('wall'));await act(async()=>{const select=host.querySelector('[data-tool]');select.value='0';select.dispatchEvent(new Event('change',{bubbles:true}));});await click(host.querySelector('[data-submit-object="wall"]'));await click(object('device'));await choose(0,'1');await unmount();await render();await click(button('Play solo'));expect(host.querySelector('[role="progressbar"]').getAttribute('aria-valuenow')).toBe('3');expect(host.querySelector('[data-control="0"]').value).toBe('1');expect(host.querySelector('[data-control="1"]').value).toBe('');expect(write).not.toHaveBeenCalled();});
 it('requires explicit reset and retains progress when reset is cancelled',async()=>{await generated();await click(button('Play solo'));await click(host.querySelector('[data-submit-object="lens"]'));await click(button('Restart solo room'));expect(document.activeElement).toBe(button('Cancel'));await click(button('Cancel'));expect(host.querySelector('[role="progressbar"]').getAttribute('aria-valuenow')).toBe('1');await click(button('Restart solo room'));await click(button('Reset my progress'));expect(host.querySelector('[role="progressbar"]').getAttribute('aria-valuenow')).toBe('0');expect(document.activeElement).toBe(button('Restart solo room'));});
 it('remains playable when browser progress storage fails',async()=>{await generated();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('quota');});await click(button('Play solo'));expect(host.textContent).toContain('Progress could not be saved');await click(host.querySelector('[data-submit-object="lens"]'));expect(host.querySelector('[role="progressbar"]').getAttribute('aria-valuenow')).toBe('1');});
 it('keeps a room-save failure visible after entering solo even when progress storage works',async()=>{await generated();const original=Storage.prototype.setItem;vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(key,value){if(this===localStorage)throw Error('blocked');return original.call(this,key,value);});await click(button('Play solo'));expect(host.querySelector('[data-solo-room]')).toBeTruthy();expect(host.querySelector('[role="alert"]').textContent).toContain('Keep this page open');await click(host.querySelector('[data-submit-object="lens"]'));expect(host.querySelector('[role="progressbar"]').getAttribute('aria-valuenow')).toBe('1');});
 it('does not reuse another participant progress in the same browser tab',async()=>{await generated();await click(button('Play solo'));await click(host.querySelector('[data-submit-object="lens"]'));await unmount();await render({user:{uid:'another'}});await click(button('Play solo'));expect(host.querySelector('[role="progressbar"]').getAttribute('aria-valuenow')).toBe('0');});
 it('shows review results and invalidates them when player instructions change',async()=>{await generated();await click(button('Check playability with AI'));expect(host.textContent).toContain('independently matched every device');const textarea=host.querySelector('textarea');await act(async()=>{const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set;setter.call(textarea,'Changed instruction');textarea.dispatchEvent(new Event('input',{bubbles:true}));});expect(host.textContent).not.toContain('independently matched every device');});
 it('makes provider failures recoverable and keeps the room playable',async()=>{await generated();await render({callGemini:async()=>{throw Error('offline');}});await click(button('Check playability with AI'));expect(host.textContent).toContain('Review incomplete');expect(button('Play solo').disabled).toBe(false);});
 it('cancels an in-flight review without starting further provider requests',async()=>{await generated();let finish;const provider=vi.fn(()=>new Promise(r=>finish=r));await render({callGemini:provider});await click(button('Check playability with AI'));await click(button('Stop review'));await act(async()=>finish(reviewResponse(provider.mock.calls[0][0])));expect(provider).toHaveBeenCalledTimes(1);expect(host.textContent).not.toContain('Solution matched');expect(button('Play solo').disabled).toBe(false);});
 it('ignores a late review result after a source change',async()=>{await generated();let finish;const provider=vi.fn(()=>new Promise(r=>finish=r));await render({callGemini:provider});await click(button('Check playability with AI'));await render({inputText:source+' A different lesson.'});await act(async()=>finish(reviewResponse(provider.mock.calls[0][0])));expect(host.textContent).not.toContain('Solution matched');expect(host.querySelector('[data-play-solo]')).toBeNull();});
 it('makes background content inert and restores it on close',async()=>{const outside=document.createElement('button');outside.textContent='Outside';document.body.appendChild(outside);outside.focus();await render();expect(outside.inert).toBe(true);await unmount();expect(outside.inert).toBeFalsy();expect(document.activeElement).toBe(outside);outside.remove();});
 it('opens the new mode from an independent learner Quiz resource',async()=>{const props={...base,isTeacherMode:false,isParentMode:false,isIndependentMode:true,studentProjectSettings:{},sessionData:{},isPresentationMode:false,isReviewGame:false,isEditingQuiz:false,escapeRoomState:{isActive:false},presentationState:{},reviewGameState:{},soundEnabled:false,globalPoints:0,isFactChecking:{},showQuizAnswers:false,leveledTextLanguage:'English',generatedContent:{id:'solo-quiz',type:'quiz',data:{questions:[{type:'mcq',question:'Water?',options:['Hot','Cold'],correctAnswer:'Hot'}]}},addToast:vi.fn(),getRows:()=>1,formatInlineText:v=>v,renderFormattedText:v=>v,getReviewCategories:()=>[],playSound:()=>{},ErrorBoundary:p=>p.children};await render(props,api.QuizView);await click(host.querySelector('[data-open-connected-room]'));expect(host.querySelector('[role="dialog"]')).toBeTruthy();await click(button('Generate connected room'));await click(button('Play solo'));expect(host.querySelector('[data-solo-room]')).toBeTruthy();expect(write).not.toHaveBeenCalled();});
});
