import {describe,it,expect} from 'vitest';
import {internals,renderTab,baseData} from './helpers/dino_lab_harness.js';
const {dinoBodyPartDefinitions:definitions,dinoBodyLabelLayout:layout}=internals();
const points=[{id:'head',x:160,y:135},{id:'tail',x:700,y:195},{id:'trunk',x:420,y:200},{id:'hand',x:245,y:290},{id:'foot',x:495,y:375},{id:'neck',x:295,y:175},{id:'knee',x:535,y:290},{id:'ankle',x:560,y:340}];
function check(items,width,height,top,bottom){for(const p of items){expect(p.x).toBeGreaterThanOrEqual(8);expect(p.x+p.width).toBeLessThanOrEqual(width-8);expect(p.y).toBeGreaterThanOrEqual(top);expect(p.y+p.height).toBeLessThanOrEqual(height-bottom);expect([p.x,p.y,p.anchorX,p.anchorY,p.lineX,p.lineY].every(Number.isFinite)).toBe(true);}for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const a=items[i],b=items[j];expect(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y).toBe(true);}}
describe('Dino Lab anatomy callouts',()=>{
 it('uses hand/foot terminology appropriate to the forelimb posture',()=>{const biped=definitions(false),quad=definitions(true);expect(biped.find(p=>p.id==='hand').label).toBe('Hand');expect(quad.find(p=>p.id==='hand').label).toBe('Front foot');expect(quad.find(p=>p.id==='foot').label).toBe('Hind foot');expect(new Set(biped.map(p=>p.id)).size).toBe(biped.length);expect(biped.find(p=>p.id==='knee').detail).toContain('distinct from the ankle');});
 it('places desktop labels without collisions or covering their anchors',()=>{const out=layout(points,900,520,64,88);expect(out.length).toBeGreaterThanOrEqual(5);check(out,900,520,64,88);for(const r of out)for(const p of points)expect(p.x>r.x&&p.x<r.x+r.width&&p.y>r.y&&p.y<r.y+r.height).toBe(false);});
 it('limits phone density and respects reserved readouts',()=>{const out=layout(points.map(p=>({...p,x:p.x*.42})),390,520,82,132);expect(out.length).toBeGreaterThanOrEqual(2);expect(out.length).toBeLessThanOrEqual(4);check(out,390,520,82,132);});
 it('omits offscreen and invalid anchors',()=>{expect(layout([{id:'bad',x:NaN,y:100},{id:'left',x:-40,y:90},{id:'hud',x:100,y:30},{id:'bottom',x:100,y:499}],390,520,64,132)).toEqual([]);});
 it('handles dense or tiny layouts without returning overlapping labels',()=>{for(const [w,h] of [[320,340],[180,240],[110,190]]){const out=layout(Array.from({length:10},(_,i)=>({id:String(i),x:w/2+i,y:h/2+i})),w,h,70,85);check(out,w,h,70,85);expect(out.length).toBeLessThanOrEqual(4);}});
 it('does not mutate projected coordinates and is stable across paused frames',()=>{const copy=JSON.stringify(points);expect(layout(points,900,520,64,88)).toEqual(layout(points,900,520,64,88));expect(JSON.stringify(points)).toBe(copy);});
 it('provides an accessible text key even when spatial labels are crowded',()=>{const data=baseData('field3d');data.field3dLabelMode='anatomy';const html=renderTab(data);expect(html).toContain('Body-part key');expect(html).toContain('<dt');expect(html).toContain('The knee joins');expect(html).toContain('Crowded labels are hidden');expect(html).toContain('data-dino-part-label="ankle"');expect(html).toContain('aria-pressed="true"');});
 it('keeps a chosen joint ahead of crowded phone labels without moving its anchor',()=>{const phone=points.map(p=>({...p,x:p.x*.42}));const before=JSON.stringify(phone),out=layout(phone,390,520,82,132,'ankle');expect(out[0].id).toBe('ankle');expect(out[0].selected).toBe(true);expect(out[0].anchorX).toBe(phone.find(p=>p.id==='ankle').x);expect(out[0].anchorY).toBe(340);expect(out.length).toBeLessThanOrEqual(4);check(out,390,520,82,132);expect(JSON.stringify(phone)).toBe(before);});
 it('finds a reserved-space-safe callout for a selected anchor near the readouts',()=>{const out=layout([{id:'knee',x:180,y:74}],390,520,100,132,'knee');expect(out).toHaveLength(1);expect(out[0].anchorY).toBe(74);check(out,390,520,100,132);});
 it('does not invent positions for a selected landmark outside the canvas',()=>{expect(layout([{id:'knee',x:-25,y:200}],390,520,82,132,'knee')).toEqual([]);expect(layout(points,90,150,80,80,'head')).toEqual([]);});
 it('offers every body part through a labeled selector and explains its camera behavior',()=>{const data=baseData('field3d');data.field3dLabelMode='anatomy';const html=renderTab(data);expect(html).toContain('for="dinolab-part-picker"');expect(html).toContain('value="ankle"');expect(html).toContain('value="thigh"');expect(html).toContain('Choose a part to frame its region');expect(html).toContain('data-dino-part-ring="knee"');expect(html).toContain('aria-describedby="dinolab-part-explanation"');});

});
