import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';

const GALAXY_PATHS = [
  'stem_lab/stem_tool_galaxy.js',
  'desktop/web-app/public/stem_lab/stem_tool_galaxy.js',
];

describe('galaxy visual layout', () => {
  it.each(GALAXY_PATHS)('%s uses the canvas-first responsive workspace', (filePath) => {
    const source = readFileSync(filePath, 'utf8');

    expect(source).toContain('className: "max-w-7xl mx-auto animate-in fade-in duration-200"');
    expect(source).toContain('xl:grid-cols-[minmax(0,1fr)_360px]');
    expect(source).toContain("height: 'clamp(360px, 58vw, 620px)'");
    expect(source).toContain("var galaxyControlPanel = d.galaxyControlPanel || 'view';");
    expect(source).toContain('Galaxy control groups');
    expect(source).toContain("{ key: 'view', icon: '◉', label: 'View' }");
    expect(source).toContain('Explore the science behind the simulation');

    const workspace = source.indexOf('Canvas-first workspace');
    const infoCard = source.indexOf('Galaxy type info card');
    expect(workspace).toBeGreaterThan(0);
    expect(workspace).toBeLessThan(infoCard);
  });

  it.each(GALAXY_PATHS)('%s keeps navigation and Star Life responsive', (filePath) => {
    const source = readFileSync(filePath, 'utf8');

    expect(source).toContain('ml-auto grid w-full grid-cols-2');
    expect(source).toContain('sm:grid-cols-3 xl:flex xl:w-auto');
    expect(source).toContain('data-galaxy-real-sky-launcher');
    expect(source).toContain('min-h-[44px]');
    expect(source).toContain('grid grid-cols-1 lg:grid-cols-[minmax(280px,38%)_minmax(0,1fr)]');
    expect(source).toContain('order-1 lg:order-2 lg:sticky');
    expect(source).toContain('order-2 lg:order-1');
    expect(source).not.toContain('style: { display: "flex", gap: "16px", alignItems: "stretch" }');
    expect(source).not.toContain('text-[10px]');
  });

  it.each(GALAXY_PATHS)('%s uses the simplified simulation HUD', (filePath) => {
    const source = readFileSync(filePath, 'utf8');

    expect(source).toContain('Compact spectral legend');
    expect(source).toContain('O B A F G K M');
    expect(source).toContain('Galaxy camera controls');
    expect(source).toContain('data-galaxy-orientation');
    expect(source).toContain('data-galaxy-status');
    expect(source).toContain('selectionMarker');
    expect(source).toContain('getPinchDistance');
    expect(source).toContain("touchAction: 'none'");
    expect(source).toContain('Drag or use arrows to orbit · scroll, pinch, or plus and minus to zoom · brackets select stars');
    expect(source).not.toContain('left: \'10%\', right: \'10%\', top: \'50%\'');
  });

  it.each(GALAXY_PATHS)('%s includes cinematic depth and adaptive detail systems', (filePath) => {
    const source = readFileSync(filePath, 'utf8');

    expect(source).toContain("var galaxyQuality = d.galaxyQuality || 'auto';");
    expect(source).toContain('data-resolved-quality');
    expect(source).toContain('volumetricAtmosphere');
    expect(source).toContain('satellitesAndTidalStreams');
    expect(source).toContain('starBirthSprites');
    expect(source).toContain('diffraction');
    expect(source).toContain('data-galaxy-observe-transition');
    expect(source).toContain('Grand Tour');
    expect(source).toContain('Rendering detail');
    expect(source).toContain('prefersReducedMotion');
    expect(source).toContain('targetExposure');
    expect(source).toContain('aLuminosity');
    expect(source).toContain('airyRing');
    expect(source).toContain('microStarCount');
    expect(source).toContain('textureResolutionScale');
    expect(source).toContain('tuneGalaxyTexture');
    expect(source).toContain('galaxyTextureAnisotropy');
    expect(source).toContain('data-render-resolution');
    expect(source).toContain('bloomStrength');
    expect(source).toContain('globularClusterHalo');
    expect(source).toContain('dustFeatherMats');
    expect(source).toContain('spiralLuminosityRidges');
    expect(source).toContain('spiralRidgeMaterials');
    expect(source).toContain('spiralArmSpurs');
    expect(source).toContain('spiralArmLightScattering');
    expect(source).toContain('armScatteringCount');
    expect(source).toContain('armScatteringDetailLevel');
    expect(source).toContain('stellarHaloShells');
    expect(source).toContain('haloShellCount');
    expect(source).toContain('haloContextLevel');
    expect(source).toContain('uCameraDir');
    expect(source).toContain('vDepthCue');
    expect(source).toContain('foregroundStellarParallax');
    expect(source).toContain('foregroundStarCount');
    expect(source).toContain('dustLaneBacklightingShafts');
    expect(source).toContain('dustBacklightAngleFactor');
    expect(source).toContain('uOpticalDetail');
    expect(source).toContain('chromaticFringe');
    expect(source).toContain('luminousChromaticHalos');
    expect(source).toContain('chromaticHaloCount');
    expect(source).toContain('updateLuminousOverlayOrbit');
    expect(source).toContain('coreEinsteinRingCaustics');
    expect(source).toContain('causticCount');
    expect(source).toContain('coreLensingDetailLevel');
    expect(source).toContain('dustScatteringColorGradients');
    expect(source).toContain('dustColorPairCount');
    expect(source).toContain('dustColorScatteringLevel');
    expect(source).toContain('resolvedOpenClusterCoronas');
    expect(source).toContain('resolvedClusterCount');
    expect(source).toContain('resolvedClusterDetailLevel');
    expect(source).toContain('binaryStellarCompanions');
    expect(source).toContain('resolvedBinaryPairCount');
    expect(source).toContain('emissionLineStratification');
    expect(source).toContain('emissionLineDetailLevel');
    expect(source).toContain('dustDepthParallaxFactor');
    expect(source).toContain('dustNearSide');
    expect(source).toContain('spiralDensityWaveShockFronts');
    expect(source).toContain('downstreamStarFormationOffsets');
    expect(source).toContain('shockFrontDetailLevel');
    expect(source).toContain('magneticallyAlignedDustFilaments');
    expect(source).toContain('magneticFilamentCount');
    expect(source).toContain('magneticFilamentDetailLevel');
    expect(source).toContain('warpedOuterDiskStellarArcs');
    expect(source).toContain('outerWarpArcCount');
    expect(source).toContain('outerWarpDetailLevel');
    expect(source).toContain('extraplanarSuperbubbleChimneys');
    expect(source).toContain('gasChimneyCount');
    expect(source).toContain('extraplanarGasDetailLevel');
    expect(source).toContain('galacticFountainParticleFlows');
    expect(source).toContain('galacticFountainParticleCount');
    expect(source).toContain('aHeight');
    expect(source).toContain('layeredSuperbubbleCapShells');
    expect(source).toContain('superbubbleCapCount');
    expect(source).toContain('fountainParticleMaterial.uniforms.uOpacity');
    expect(source).toContain('uDepthOfField');
    expect(source).toContain('vFocusDefocus');
    expect(source).toContain('bokehHalo');
    expect(source).toContain('focusDepthTarget');
    expect(source).toContain('cameraLayeredHaloScattering');
    expect(source).toContain('haloScatteringLayerCount');
    expect(source).toContain('layeredHaloDepthLevel');
    expect(source).toContain('resolvedBipolarPlanetaryNebulae');
    expect(source).toContain('planetaryNebulaCount');
    expect(source).toContain('planetaryNebulaDetailLevel');
    expect(source).toContain('stellarWindBowShocks');
    expect(source).toContain('bowShockCount');
    expect(source).toContain('bowShockDetailLevel');
    expect(source).toContain('updateLuminousOverlayOrbit(bowShock');
    expect(source).toContain('resolvedCircumstellarNurseries');
    expect(source).toContain('resolvedProtoplanetaryDisks');
    expect(source).toContain('circumstellarNurseryCount');
    expect(source).toContain('circumstellarDetailLevel');
    expect(source).toContain('bipolarProtostellarJets');
    expect(source).toContain('protostellarJetSprites');
    expect(source).toContain('protostellarShockKnots');
    expect(source).toContain('protostellarJetMode');
    expect(source).toContain('resolvedSupernovaEjecta');
    expect(source).toContain('resolvedRemnantCount');
    expect(source).toContain('ejectaFilamentCount');
    expect(source).toContain('reverseShockShells');
    expect(source).toContain('supernovaEjectaKnots');
    expect(source).toContain('compactRemnantCoreSprites');
    expect(source).toContain('supernovaEjectaMode');
    expect(source).toContain('supernovaEjectaDetailLevel');
    expect(source).toContain('clusterDissolutionTidalTails');
    expect(source).toContain('clusterTailCount');
    expect(source).toContain('clusterTailSegments');
    expect(source).toContain('clusterTailPointCount');
    expect(source).toContain('escapedClusterMemberMaterial');
    expect(source).toContain('clusterTidalTailMode');
    expect(source).toContain('clusterTailDetailLevel');
    expect(source).toContain('resolvedSatelliteDwarfMorphologies');
    expect(source).toContain('satelliteEnvelopeLayerCount');
    expect(source).toContain('ramPressureTailCount');
    expect(source).toContain('strippedGasKnotCount');
    expect(source).toContain('satelliteDwarfMode');
    expect(source).toContain('ramPressureMode');
    expect(source).toContain('satelliteMorphologyDetailLevel');
    expect(source).toContain('circumnuclearFeedingStructures');
    expect(source).toContain('circumnuclearRingCount');
    expect(source).toContain('nuclearMiniSpiralCount');
    expect(source).toContain('nuclearFeedingHotKnotCount');
    expect(source).toContain('nuclearFeedingHotKnots');
    expect(source).toContain('nuclearFeedingMode');
    expect(source).toContain('nuclearFeedingDetailLevel');
    expect(source).toContain('radioMagneticPolarizationField');
    expect(source).toContain('radioPolarizationVectorCount');
    expect(source).toContain('faradayDepthRibbonCount');
    expect(source).toContain('radioPolarizationMaterial');
    expect(source).toContain('faradayRibbonMaterials');
    expect(source).toContain('radioPolarizationDetailLevel');
    expect(source).toContain('OBSERVATORY_INSTRUMENTS');
    expect(source).toContain('activeInstrument');
    expect(source).toContain('data-galaxy-instrument-reticle');
    expect(source).toContain('data-galaxy-instrument-readout');
    expect(source).toContain('data-galaxy-radio-polarization-key');
    expect(source).toContain('data-galaxy-gravity-legend');
    expect(source).toContain('xrayTemperatureStratifiedShockFronts');
    expect(source).toContain('xrayTemperatureShellCount');
    expect(source).toContain('xrayThermalShellMaterials');
    expect(source).toContain('xrayLayeredNuclearOutflow');
    expect(source).toContain('xrayNuclearOutflowLayerCount');
    expect(source).toContain('xrayOutflowMaterials');
    expect(source).toContain('xrayOutflowSprites');
    expect(source).toContain('data-galaxy-xray-structure-key');
    expect(source).toContain('outerContextCompression');
    expect(source).toContain('uZoomPointScale');
    expect(source).toContain('uZoomOpacity');
    expect(source).not.toContain('outerDiskLift * 0.07');
    expect(source).toContain('transientGlareCompression');
    expect(source).toContain('adaptiveBloomThreshold');
    expect(source).toContain('edgeOnDustSilhouette');
    expect(source).toContain('edgeOnFactor');
    expect(source).toContain('ionizedShells');
    expect(source).toContain('satelliteCoreSprites');
    expect(source).toContain('openClusterStarCount');
    expect(source).toContain('thickDiskCount');
    expect(source).toContain('supernovaRemnantArcs');
    expect(source).toContain('populationTarget');
    expect(source).toContain('fineStarTex');
    expect(source).toContain('molecularCloudFilaments');
    expect(source).toContain('molecularCloudCount');
    expect(source).toContain('embeddedProtostarKnots');
    expect(source).toContain('protostarCount');
    expect(source).toContain('foregroundParallaxDust');
    expect(source).toContain('cloudTarget');
    expect(source).toContain('OBSERVE_GUIDES');
    expect(source).toContain('data-galaxy-science-overlay');
    expect(source).toContain('data-galaxy-observation-guide');
    expect(source).toContain('galaxy-evidence-note');
    expect(source).toContain('previousObserveMode');
    expect(source).toContain('data-galaxy-science-toggle');
    expect(source).toContain('galactocentricMeasurementRuler');
    expect(source).toContain('data-galaxy-measurement');
    expect(source).toContain('data-galaxy-rotation-measurement');
    expect(source).toContain('orbitalMeasurementForModel');
    expect(source).toContain('selectedStarMeasurement');
    expect(source).toContain('mission_step_measure_star');
    expect(source).toContain('selectedStarOrbitalMechanics');
    expect(source).toContain('ORBIT_GUIDE_SEGMENTS');
    expect(source).toContain('tangentialVelocity');
    expect(source).toContain('inwardGravity');
    expect(source).toContain('data-galaxy-orbit-vectors');
    expect(source).toContain('weakLensingField');
    expect(source).toContain('weakLensingCount');
    expect(source).toContain('weakLensingVisual');
    expect(source).toContain('mark_weak_lensing');
    expect(source).toContain('data-galaxy-weak-lensing-guide');
    expect(source).toContain('dopplerVelocityField');
    expect(source).toContain('velocityMapSize');
    expect(source).toContain('velocitySampleCount');
    expect(source).toContain('mark_doppler_field');
    expect(source).toContain('data-galaxy-radio-velocity-legend');
    expect(source).toContain('data-galaxy-radio-velocity-guide');
    expect(source).toContain('morphologySignatureStructures');
    expect(source).toContain('getGalaxyEvolutionForAge');
    expect(source).toContain('ageEvolutionTarget');
    expect(source).toContain('infraredThermalEmission');
    expect(source).toContain('thermalCloudCount');
    expect(source).toContain('xrayEnergeticEvents');
    expect(source).toContain('xraySourceCount');
    expect(source).toContain('data-galaxy-infrared-legend');
    expect(source).toContain('data-galaxy-xray-legend');
    expect(source).toContain('data-galaxy-infrared-transfer-guide');
    expect(source).toContain('data-galaxy-xray-energy-guide');
    expect(source).toContain('data-galaxy-live-scale');
    expect(source).toContain('_galaxyCycleStar');
    expect(source).toContain('cameraLookGoal');
    expect(source).toContain('_galaxyClearSelection');
    expect(source).toContain('stellarFeedbackMicrostructure');
    expect(source).toContain('feedbackIonizationRims');
    expect(source).toContain('feedbackPillarSprites');
    expect(source).toContain('bokGlobuleSprites');
    expect(source).toContain('nuclearStarClusterLOD');
    expect(source).toContain('nuclearStarClusterMaterial');
    expect(source).toContain('depthFocusBokeh');
    expect(source).toContain('data-galaxy-scale-regime');
    expect(source).toContain('selectionColor');
    expect(source).toContain('selectionDepthReticle');
    expect(source).toContain('selectionHalo');
    expect(source).toContain('_setDetailLayer');
  });

  it.each(GALAXY_PATHS)('%s preserves the WCAG interaction contract', (filePath) => {
    const source = readFileSync(filePath, 'utf8');

    expect(source).toContain('id: "galaxy-canvas-description"');
    expect(source).toContain('id: "galaxy-canvas-instructions"');
    expect(source).toContain('id: "galaxy-motion-note"');
    expect(source).toContain('data-galaxy-announcer');
    expect(source).toContain('"aria-atomic": "true"');
    expect(source).toContain('"aria-keyshortcuts"');
    expect(source).toContain('galaxy-canvas-description galaxy-canvas-instructions galaxy-motion-note galaxy-canvas-status');
    expect(source).toContain('@media (forced-colors: active)');
    expect(source).toContain('focus-visible:outline-4');
    expect(source).toContain('focus-visible:ring-4');
    expect(source).toContain('reducedMotionQuery.addEventListener');
    expect(source).toContain('_onMotionPreferenceChange');
    expect(source).toContain('disabled: galaxyReducedMotion');
    expect(source).toContain('h-11 w-11');
    expect(source).not.toContain('outline: \'none\'');
    expect(source).not.toContain('text-[9px]');
    expect(source).not.toContain('text-[10px]');
    expect(source).not.toContain('min-h-[32px]');
    expect(source).not.toContain('min-h-[36px]');
  });
});