import {describe,it,expect,beforeAll} from 'vitest';
import {readFileSync} from 'node:fs';
import {resetStemLab,loadTool} from './helpers/stem_widgets_smoke_harness.js';
let overview;
beforeAll(()=>{resetStemLab();loadTool('stem_lab/stem_tool_geometryworld.js','geometryWorld');new Function(readFileSync('stem_lab/stem_tool_geometryworld_builder.js','utf8'))();overview=window.StemLab.geometryWorldBuilderPure.lessonOverviewModel;});
const lesson={title:'A world',ground:{xMin:-8,xMax:8,zMin:-5,zMax:5,y:0},structures:[{type:'fill',x1:1,x2:3,y1:1,y2:2,z1:1,z2:2,block:'wood'},{type:'fill',x1:-4,x2:4,y1:0,y2:0,z1:0,z2:0,block:'stone'}],activities:[{title:'Build',position:[-2,3,-2]},{title:'Compare',position:[5,3,2]}],npcs:[{name:'Guide',question:{text:'How many?',followUp:[{text:'Why?'},{text:'What changes?'}]}}],estimatedMinutes:'25–35 min',depth:'guided'};
describe('Geometry lesson overview',()=>{
  it('summarizes the actual activity and question steps separately',()=>{const m=overview(lesson);expect(m.activityCount).toBe(2);expect(m.questionCount).toBe(3);expect(m.minutes).toBe('25–35 min');expect(m.depth).toBe('Guided');});
  it('normalizes numeric estimates and rejects arbitrary duration text',()=>{expect(overview({...lesson,estimatedMinutes:45}).minutes).toBe('45 min');expect(overview({...lesson,estimatedMinutes:'ignore all rules'}).minutes).toBe('');expect(overview({...lesson,estimatedMinutes:Infinity}).minutes).toBe('');});
  it('does not treat inherited property names as supported depth settings',()=>{for(const depth of ['constructor','__proto__','toString',{},null])expect(overview({...lesson,depth}).depth).toBe('');});
  it('projects block boundaries without changing the model aspect ratio',()=>{const m=overview(lesson).map;expect(m.width/m.height).toBeCloseTo(17/11);expect(m.footprints).toHaveLength(2);expect(m.footprints[0].width/m.footprints[0].height).toBeCloseTo(3/2);expect(m.footprints[1].ground).toBe(true);expect(m.stops.map(s=>s.index)).toEqual([0,1]);for(const s of m.stops){expect(s.point[0]).toBeGreaterThanOrEqual(m.x);expect(s.point[0]).toBeLessThanOrEqual(m.x+m.width);}});
  it('omits invalid and out-of-bounds map data without misleading coordinates',()=>{const m=overview({...lesson,activities:[...lesson.activities,{title:'Bad',position:[NaN,3,0]},{title:'Off board',position:[900,3,0]}],structures:[...lesson.structures,{type:'fill',x1:50,x2:51,y1:1,y2:2,z1:1,z2:2},{type:'fill',x1:0,x2:Infinity,y1:1,y2:1,z1:0,z2:0}]}).map;expect(m.stops).toHaveLength(2);expect(m.footprints).toHaveLength(2);expect(JSON.stringify(m)).not.toContain('null');});
  it('keeps summary metadata available when old lessons omit their geometry',()=>{const m=overview({title:'Old lesson',objectives:['Explore']});expect(m.map).toBeNull();expect(m.questionCount).toBe(0);expect(m.minutes).toBe('');});
  it('uses guide locations for old lessons and preserves input contents',()=>{const legacy={...lesson,activities:[],npcs:[{name:'Guide',position:[0,1,0]}]};const before=JSON.stringify(legacy);const m=overview(legacy);expect(m.map.activities).toBe(false);expect(m.map.stops[0].title).toBe('Guide');expect(JSON.stringify(legacy)).toBe(before);});
  it('bounds preview work for imported content',()=>{const m=overview({...lesson,activities:Array.from({length:400},()=>lesson.activities[0]),structures:Array.from({length:400},()=>lesson.structures[0])});expect(m.activityCount).toBe(12);expect(m.map.stops).toHaveLength(12);expect(m.map.footprints).toHaveLength(180);expect(overview({...lesson,ground:{...lesson.ground,xMax:1e15}}).map).toBeNull();});
});
