import {afterEach,beforeAll,describe,it,expect} from 'vitest';
import {React,ReactDOMClient,loadTool,makeCtx,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let cfg,mounted;
const box=extra=>({shape:'box',size:[1,1,1],position:[0,.5,0],rotation:[0,0,0],color:'#60a5fa',group:'Studio',...extra});
beforeAll(()=>{resetStemLab();cfg=loadTool('stem_lab/stem_tool_geosandbox.js','geoSandbox');});
afterEach(()=>{if(mounted){React.act(()=>mounted.root.unmount());mounted.container.remove();mounted=null;}});
function mount(parts){const container=document.createElement('div');document.body.appendChild(container);const view={container,root:ReactDOMClient.createRoot(container)};function Host(){const[data,setData]=React.useState({_threeLoaded:true,geoSandbox:{mode:'sculpt',sculptRecipe:{parts}}});view.state=data.geoSandbox;return cfg.render(makeCtx({toolData:data,setToolData:setData}));}mounted=view;React.act(()=>view.root.render(React.createElement(Host)));click(container.querySelector('#geo-sculpt-tab-edit'));return view;}
function click(el){expect(el).toBeTruthy();React.act(()=>el.click());}
function field(label){const el=mounted.container.querySelector('[aria-label="'+label+'"]');expect(el).toBeTruthy();return el;}
function value(el,v){React.act(()=>{const proto=el.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,v);el.dispatchEvent(new window.Event('input',{bubbles:true}));el.dispatchEvent(new window.Event('change',{bubbles:true}));});}
function key(el,k){React.act(()=>el.dispatchEvent(new window.KeyboardEvent('keydown',{key:k,bubbles:true})));}
function history(name){click([...mounted.container.querySelectorAll('button')].find(el=>el.textContent.trim()===name));}
function group(){value(field('Apply material to'),'group');}
describe('Sculpt material scope and exact colors',()=>{
 it('applies custom color to unlocked group members while preserving each finish and other groups',()=>{const v=mount([box({finish:'matte'}),box({finish:'metal'}),box({locked:true}),box({group:'Other'})]);group();value(field('Part color'),'#123456');expect(v.state.sculptRecipe.parts.map(p=>p.color)).toEqual(['#123456','#123456','#60a5fa','#60a5fa']);expect(v.state.sculptRecipe.parts.slice(0,2).map(p=>p.finish)).toEqual(['matte','metal']);history('↶ Undo');expect(v.state.sculptRecipe.parts.every(p=>p.color==='#60a5fa')).toBe(true);history('Redo');expect(v.state.sculptRecipe.parts[1].color).toBe('#123456');});
 it('reports mixed surfaces and applies finish without replacing individual colors',()=>{const v=mount([box({finish:'matte'}),box({color:'#c98566',finish:'metal'}),box({locked:true})]);group();expect(field('Finish').value).toBe('mixed');expect(field('Hex color').placeholder).toBe('Mixed colors');expect(v.container.querySelector('.geo-material-scope').textContent).toContain('2 editable parts · 1 locked skipped');value(field('Finish'),'gloss');expect(v.state.sculptRecipe.parts.map(p=>p.finish)).toEqual(['gloss','gloss',undefined]);expect(v.state.sculptRecipe.parts.map(p=>p.color)).toEqual(['#60a5fa','#c98566','#60a5fa']);history('↶ Undo');expect(field('Finish').value).toBe('mixed');});
 it('commits short hex drafts as one reversible edit and does not duplicate on blur',()=>{const v=mount([box()]);const before=JSON.stringify(v.state.sculptRecipe);value(field('Hex color'),'AbC');expect(JSON.stringify(v.state.sculptRecipe)).toBe(before);key(field('Hex color'),'Enter');expect(v.state.sculptRecipe.parts[0].color).toBe('#aabbcc');React.act(()=>field('Hex color').dispatchEvent(new window.FocusEvent('focusout',{bubbles:true})));history('↶ Undo');expect(v.state.sculptRecipe.parts[0].color).toBe('#60a5fa');expect([...v.container.querySelectorAll('button')].find(el=>el.textContent.trim()==='↶ Undo').disabled).toBe(true);});
 it('keeps invalid color drafts out of geometry and history, and Escape cancels them',()=>{const v=mount([box()]);value(field('Finish'),'metal');history('↶ Undo');const before=JSON.stringify(v.state.sculptRecipe);value(field('Hex color'),'#not-a-color');key(field('Hex color'),'Enter');expect(field('Hex color').getAttribute('aria-invalid')).toBe('true');expect(v.container.querySelector('#geo-sculpt-color-help').getAttribute('role')).toBe('alert');expect(JSON.stringify(v.state.sculptRecipe)).toBe(before);key(field('Hex color'),'Escape');expect(field('Hex color').value).toBe('#60a5fa');expect(field('Hex color').hasAttribute('aria-invalid')).toBe(false);history('Redo');expect(v.state.sculptRecipe.parts[0].finish).toBe('metal');});
 it('indicates presets only when all editable targets match and preserves history for an identical material',()=>{const v=mount([box({color:'#91A4B6',finish:'metal'}),box({color:'#c98566',finish:'matte'}),box({locked:true})]);expect(field('Apply material Steel').getAttribute('aria-pressed')).toBe('true');group();expect(field('Apply material Steel').getAttribute('aria-pressed')).toBe('false');click(field('Apply material Steel'));expect(field('Apply material Steel').getAttribute('aria-pressed')).toBe('true');click(field('Apply material Steel'));history('↶ Undo');expect(v.state.sculptRecipe.parts[1].color).toBe('#c98566');expect(v.state.sculptRecipe.parts[0].color).toBe('#91A4B6');});
 it('allows group surface edits from a locked selection while keeping that selected part unchanged',()=>{const v=mount([box({locked:true}),box()]);expect(field('Hex color').disabled).toBe(true);group();expect(field('Hex color').disabled).toBe(false);value(field('Hex color'),'123456');key(field('Hex color'),'Enter');expect(v.state.sculptRecipe.parts.map(p=>p.color)).toEqual(['#60a5fa','#123456']);value(field('Apply material to'),'part');expect(field('Part color').disabled).toBe(true);expect(field('Finish').disabled).toBe(true);});
 it('discards uncommitted color drafts when the selection or scope changes',()=>{mount([box(),box({color:'#c98566'})]);value(field('Hex color'),'bad');click(mounted.container.querySelector('#geo-sculpt-choice-edit-1'));expect(field('Hex color').value).toBe('#c98566');value(field('Hex color'),'bad');group();expect(field('Hex color').value).toBe('');});
});
