import {afterEach,beforeAll,describe,it,expect} from 'vitest';
import {React,ReactDOMClient,loadTool,makeCtx,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let cfg,mounted;
const box=extra=>({shape:'box',size:[1,2,.5],position:[1,.5,-1],rotation:[0,0,0],color:'#60a5fa',group:'Pair',...extra});
beforeAll(()=>{resetStemLab();cfg=loadTool('stem_lab/stem_tool_geosandbox.js','geoSandbox');});
afterEach(()=>{if(mounted){React.act(()=>mounted.root.unmount());mounted.container.remove();mounted=null;}});
function mount(parts=[box()],bucket={}){const container=document.createElement('div');document.body.appendChild(container);const v={container,root:ReactDOMClient.createRoot(container)};function Host(){const[data,setData]=React.useState({_threeLoaded:true,geoSandbox:{mode:'sculpt',sculptRecipe:{parts},...bucket}});v.state=data.geoSandbox;return cfg.render(makeCtx({toolData:data,setToolData:setData}));}mounted=v;React.act(()=>v.root.render(React.createElement(Host)));click(container.querySelector('#geo-sculpt-tab-edit'));return v;}
function click(el){expect(el).toBeTruthy();React.act(()=>el.click());}
function field(label){const el=mounted.container.querySelector('[aria-label="'+label+'"]');expect(el).toBeTruthy();return el;}
function value(el,v,blur=false){React.act(()=>{const proto=el.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,String(v));el.dispatchEvent(new window.Event('input',{bubbles:true}));el.dispatchEvent(new window.Event('change',{bubbles:true}));if(blur)el.dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}));});}
function history(name){click([...mounted.container.querySelectorAll('button')].find(el=>el.textContent.trim()===name));}

describe('Sculpt proportional resize controls',()=>{
 it('places resize controls in Size and previews actual display-unit dimensions',()=>{const v=mount([box()],{sculptRecipe:{scale:2,parts:[box()]}});expect(field('Make part bigger').closest('details').id).toBe('geo-sculpt-section-size');value(field('Resize factor'),'1.5');const values=[...field('Make part bigger').querySelectorAll('strong')].map(el=>el.textContent);expect(values).toEqual(['7.8 u','15.6 u','3.9 u']);click(field('Make part bigger'));expect(v.state.sculptRecipe.parts[0].size).toEqual([1.5,3,.75]);expect(v.state.sculptRecipe.parts[0].position).toEqual([1,.5,-1]);});
 it('makes Shrink reciprocal to Grow and keeps each action independently undoable',()=>{const v=mount();value(field('Resize factor'),'1.25');click(field('Make part bigger'));expect(v.state.sculptRecipe.parts[0].size).toEqual([1.25,2.5,.625]);click(field('Make part smaller'));v.state.sculptRecipe.parts[0].size.forEach((n,i)=>expect(n).toBeCloseTo([1,2,.5][i],12));history('↶ Undo');expect(v.state.sculptRecipe.parts[0].size).toEqual([1.25,2.5,.625]);history('↶ Undo');expect(v.state.sculptRecipe.parts[0].size).toEqual([1,2,.5]);});
 it('previews a shared size limit and disables Grow there without changing proportions',()=>{const v=mount([box({size:[2,3.5,1]})]);value(field('Resize factor'),'2');expect(field('Make part bigger').textContent).toContain('Stops at the size limit');const preview=[...field('Make part bigger').querySelectorAll('strong')].map(el=>parseFloat(el.textContent));click(field('Make part bigger'));const size=v.state.sculptRecipe.parts[0].size;expect(size[1]).toBe(4);expect(size[0]/size[1]).toBeCloseTo(2/3.5,12);size.forEach((n,i)=>expect(n*2.6).toBeCloseTo(preview[i],4));expect(field('Make part bigger').disabled).toBe(true);history('↶ Undo');expect(field('Make part bigger').disabled).toBe(false);});
 it('validates custom factors as drafts and preserves the sculpture while choosing settings',()=>{const v=mount();value(field('Resize factor'),'custom');const before=JSON.stringify(v.state.sculptRecipe);value(field('Custom resize factor'),1.375);expect(v.state.sculptResizeFactor).toBeUndefined();value(field('Custom resize factor'),1,true);expect(v.state.sculptResizeFactor).toBeUndefined();expect(field('Custom resize factor').value).toBe('1.15');value(field('Custom resize factor'),1.375,true);expect(v.state.sculptResizeFactor).toBe(1.375);expect(JSON.stringify(v.state.sculptRecipe)).toBe(before);click(field('Make part bigger'));expect(v.state.sculptRecipe.parts[0].size).toEqual([1.375,2.75,.6875]);});
 it('keeps other group members and rotations unchanged regardless of group movement setting',()=>{const v=mount([box({rotation:[10,20,30]}),box()],{sculptMoveGroup:true});click(field('Make part bigger'));expect(v.state.sculptRecipe.parts[0].rotation).toEqual([10,20,30]);expect(v.state.sculptRecipe.parts[1].size).toEqual([1,2,.5]);expect(v.state.sculptRecipe.parts[0].size).toEqual([1.15,2.3,.575]);});
 it('preserves torus proportions at the minimum gap and prevents further shrink',()=>{const v=mount([box({shape:'torus',size:[.4,.38,.5]})]);expect(field('Make part smaller').disabled).toBe(true);expect(field('Make part smaller').textContent).toContain('Size limit reached');expect(v.state.sculptRecipe.parts[0].size).toEqual([.4,.38,.5]);});
 it('disables resizing for locked parts',()=>{mount([box({locked:true})]);expect(field('Make part bigger').disabled).toBe(true);expect(field('Make part smaller').disabled).toBe(true);});
});
