import {afterEach,beforeAll,describe,it,expect} from 'vitest';
import {React,ReactDOMClient,loadTool,makeCtx,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let cfg,mounted;
const box=extra=>({shape:'box',size:[1,2,.5],position:[1,.5,-1],rotation:[0,0,0],color:'#60a5fa',group:'Pair',...extra});
beforeAll(()=>{resetStemLab();cfg=loadTool('stem_lab/stem_tool_geosandbox.js','geoSandbox');});
afterEach(()=>{if(mounted){React.act(()=>mounted.root.unmount());mounted.container.remove();mounted=null;}});
function mount(parts=[box()],bucket={}){const container=document.createElement('div');document.body.appendChild(container);const v={container,root:ReactDOMClient.createRoot(container)};function Host(){const[data,setData]=React.useState({_threeLoaded:true,geoSandbox:{mode:'sculpt',sculptRecipe:{parts},...bucket}});v.state=data.geoSandbox;return cfg.render(makeCtx({toolData:data,setToolData:setData}));}mounted=v;React.act(()=>v.root.render(React.createElement(Host)));click(container.querySelector('#geo-sculpt-tab-edit'));return v;}
function click(el){expect(el).toBeTruthy();React.act(()=>el.click());}
function field(label){const el=mounted.container.querySelector('[aria-label="'+label+'"]');expect(el).toBeTruthy();return el;}
function value(el,v,blur=false){React.act(()=>{const proto=el.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,String(v));el.dispatchEvent(new window.Event('input',{bubbles:true}));el.dispatchEvent(new window.Event('change',{bubbles:true}));if(blur)el.dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}));});}
function history(name){click([...mounted.container.querySelectorAll('button')].find(el=>el.textContent.trim()===name));}


function partsTab(){click(mounted.container.querySelector('#geo-sculpt-tab-parts'));}
function keepAdding(){return mounted.container.querySelector('.geo-keep-adding input');}
describe('Sculpt shape chooser',()=>{
 it('puts the chooser before the collection with all five primitives',()=>{const v=mount();partsTab();const chooser=v.container.querySelector('.geo-shape-chooser'),collection=v.container.querySelector('.geo-part-collection');expect(chooser.compareDocumentPosition(collection)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(chooser.querySelectorAll('.geo-sculpt-palette button')).toHaveLength(5);expect(chooser.textContent).toContain('13 available');});
 it('opens the newly added part in Size without modifying older parts',()=>{const v=mount([box({partId:'original',label:'Original'})],{sculptInspectorSection:'material'}),before=JSON.stringify(v.state.sculptRecipe.parts[0]);partsTab();click(field('Add cone'));expect(v.state.sculptRecipe.parts).toHaveLength(2);expect(v.state.sculptRecipe.parts[1].shape).toBe('cone');expect(JSON.stringify(v.state.sculptRecipe.parts[0])).toBe(before);expect(field('Selected part').value).toBe('1');expect(v.state.sculptPanel).toBe('edit');expect(v.state.sculptInspectorSection).toBe('size');});
 it('starts an empty project directly from the chosen primitive and undoes in one step',()=>{const v=mount(undefined,{sculptRecipe:null});partsTab();click(field('Add sphere'));expect(v.state.sculptRecipe.parts).toHaveLength(1);expect(v.state.sculptRecipe.parts[0].shape).toBe('sphere');expect(v.state.sculptPanel).toBe('edit');history('↶ Undo');expect(v.state.sculptRecipe).toBeNull();history('Redo');expect(v.state.sculptRecipe.parts[0].shape).toBe('sphere');});
 it('keeps the chooser open for repeated additions and selects each new part',()=>{const v=mount();partsTab();click(keepAdding());click(field('Add cylinder'));click(field('Add torus'));expect(v.state.sculptPanel).toBe('parts');expect(v.state.sculptKeepAdding).toBe(true);expect(v.state.sculptRecipe.parts.map(p=>p.shape)).toEqual(['box','cylinder','torus']);expect(field('Selected part').value).toBe('2');history('↶ Undo');expect(v.state.sculptRecipe.parts.map(p=>p.shape)).toEqual(['box','cylinder']);history('↶ Undo');expect(v.state.sculptRecipe.parts).toHaveLength(1);});
 it('restores the keep-adding preference and can return to automatic editing',()=>{const v=mount(undefined,{sculptKeepAdding:true});partsTab();expect(keepAdding().checked).toBe(true);click(keepAdding());click(field('Add box'));expect(v.state.sculptPanel).toBe('edit');expect(v.state.sculptKeepAdding).toBe(false);});
 it('disables adding at capacity and re-enables it after Undo',()=>{const v=mount(Array.from({length:13},(_,i)=>box({partId:'p'+i})),{sculptKeepAdding:true});partsTab();click(field('Add cone'));expect(v.state.sculptRecipe.parts).toHaveLength(14);expect([...v.container.querySelectorAll('.geo-sculpt-palette button')].every(b=>b.disabled)).toBe(true);expect(v.container.querySelector('.geo-shape-chooser').textContent).toContain('Open Edit');history('↶ Undo');expect(field('Add cone').disabled).toBe(false);expect(v.container.querySelector('.geo-shape-chooser').textContent).toContain('1 available');});
 it('does not create history entries when changing the adding preference',()=>{const v=mount(),before=JSON.stringify(v.state.sculptRecipe);partsTab();click(keepAdding());expect(JSON.stringify(v.state.sculptRecipe)).toBe(before);expect([...v.container.querySelectorAll('button')].find(b=>b.textContent==='↶ Undo').disabled).toBe(true);});
});
