import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const require=createRequire(import.meta.url),R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),M=require('../stem_lab/kitchen_studio/recipe_lab_crushing.js'),cook=require('../dev-tools/kitchen_recipe_fixture.cjs');
function prepared(count=2){let s=R.start('tomato',count);for(const a of ['wash','rinse','cut','dry','oil','produce'])s=R.act(s,a);return s;}
function soft(count=2){let s=prepared(count);s=R.act(s,'panHeat',1);while(Math.min(...s.pan.pieces.map(p=>p.soft))<.85)s=R.act(s,'advance',30);return s;}
function crushed(s){for(let i=0;i<14;i++)s=R.act(R.act(s,'crushTomato',i),'crushTomato',i);return s;}
describe('Masher gesture',()=>{
 it('requires a full downward press; a tap or partial drag does nothing',()=>{const g=M.start({x:0,y:0});expect(M.complete(g)).toBe(false);expect(M.complete(M.move(g,{x:0,y:40}))).toBe(false);expect(M.complete(M.move(g,{x:0,y:75}))).toBe(true);expect(g.progress).toBe(0);});
 it('rejects sideways scrubbing, upward reversal, and non-finite coordinates',()=>{const g=M.start({x:0,y:0});expect(M.complete(M.move(g,{x:35,y:80}))).toBe(false);expect(M.move(M.move(g,{x:0,y:65}),{x:0,y:30}).invalid).toBe(true);expect(M.complete(M.move(M.move(g,{x:40,y:40}),{x:0,y:80}))).toBe(false);expect(M.move(g,{x:NaN,y:90}).invalid).toBe(true);expect(M.start(null)).toBeNull();});
});
describe('Crushing softened tomatoes',()=>{
 it('keeps firm pieces and their juice intact when pressed too early',()=>{const s=prepared(),n=R.act(s,'crushTomato',0,'masher-press');expect(n.log.at(-1).accepted).toBe(false);expect(n.feedback).toContain('resists');expect(n.pan).toEqual(s.pan);expect(n.time).toBe(s.time);});
 it('splits then crushes one selected piece, moving its finite juice into the sauce',()=>{const s=soft(),a=R.act(s,'crushTomato',3,'scene-masher'),b=R.act(a,'crushTomato',3);expect(a.pan.pieces[3].crushed).toBe(1);expect(b.pan.pieces[3].crushed).toBe(2);expect(a.pan.pieces[3].juice*2).toBeCloseTo(s.pan.pieces[3].juice);expect(b.pan.pieces[3].juice).toBe(0);expect(b.pan.moisture-s.pan.moisture).toBeCloseTo(s.pan.pieces[3].juice);expect(b.pan.waterAdded).toBe(s.pan.waterAdded);expect(b.pot).toEqual(s.pot);expect(a.time).toBe(s.time);expect(s.pan.pieces[3].crushed).toBe(0);expect(a.log.at(-1).interaction).toBe('scene-masher');expect(R.act(b,'crushTomato',3)).toBe(b);});
 it.each([2,4])('conserves sauce moisture plus retained juice for %i servings',count=>{const s=soft(count),n=crushed(s),before=s.pan.moisture+R.tomatoHandling(s).juiceRemaining,after=n.pan.moisture+R.tomatoHandling(n).juiceRemaining;expect(after).toBeCloseTo(before);expect(R.tomatoHandling(n).juiceReleased).toBeCloseTo(60*count/2);expect(R.tomatoHandling(n).crushed).toBe(14);expect(R.tomatoHandling(n).juiceRemaining).toBe(0);});
 it('makes uneven prepared sizes yield at different times under the same heat',()=>{let s=R.start('tomato');for(const a of ['wash','rinse'])s=R.act(s,a);s=R.act(s,'slice','0:5');s=R.act(s,'finishCuts');for(const a of ['oil','produce'])s=R.act(s,a);s=R.act(s,'panHeat',1);while(!s.pan.pieces.some(p=>p.soft>=.85))s=R.act(s,'advance',30);const small=s.pan.pieces.findIndex(p=>p.width===5),large=s.pan.pieces.findIndex(p=>p.width===35);expect(R.act(s,'crushTomato',small).log.at(-1).accepted).toBe(true);expect(R.act(s,'crushTomato',large).log.at(-1).accepted).toBe(false);});
 it('preserves prepared widths, positions, browning, and irreversible scorch damage',()=>{const s=soft();s.pan.damage=1.2;s.pan.pieces[0].damage=[1.2,.2];const n=R.act(s,'crushTomato',0),p=s.pan.pieces[0],q=n.pan.pieces[0];for(const key of ['width','cutIndex','faces','damage','soft','down','x','z'])expect(q[key]).toEqual(p[key]);expect(n.pan.damage).toBe(1.2);expect(n.feedback).toContain('Scorched patches remain');});
 it('requires folding newly released juice and checking again after a final press',()=>{let s=R.startRescue('watery',1);s.pan.moisture=100;s=R.act(s,'taste');const sample=R.inspections(s).at(-1);s=R.act(s,'crushTomato',0);expect(s.pan.tasted).toBe(false);expect(R.mixing(s).waterSinceMix).toBe(0);expect(R.mixing(s).juiceSinceMix).toBeGreaterThan(0);expect(R.criteria(s)[0].met).toBe(false);s=R.act(s,'taste');expect(R.inspections(s).at(-1).label).toBe('Juice not folded through');expect(sample.tomatoTexture).toContain('0 split');s=R.act(s,'stirSweep','gesture');expect(R.mixing(s).liquidSinceMix).toBe(0);expect(s.pan.tasted).toBe(false);expect(R.inspections(R.act(s,'taste')).at(-1).type).toBe('coating');});
 it('changes the modeled spoon coating with texture but does not replace liquid reduction',()=>{const s=R.startRescue('watery',1);s.pan.moisture=60;const chunky=R.inspections(R.act(s,'taste')).at(-1),smooth=R.act(crushed(s),'stirPan'),reading=R.inspections(R.act(smooth,'taste')).at(-1);expect(reading.closureSeconds).toBeGreaterThan(chunky.closureSeconds);expect(reading.tomatoTexture).toContain('All 14');smooth.pan.moisture=400;expect(R.inspections(R.act(smooth,'taste')).at(-1).type).toBe('watery');});
 it('rejects invalid pieces, other recipes, empty pans, older models, and completed cooks',()=>{const s=soft();for(const value of [-1,14,.5,NaN,{},'1',undefined])expect(R.act(s,'crushTomato',value)).toBe(s);const m=R.start('mushroom');expect(R.act(m,'crushTomato',0)).toBe(m);expect(R.act(R.start('tomato'),'crushTomato',0).log.at(-1).accepted).toBe(false);const old={...s,tomatoModel:0},finished={...s,plated:true};expect(R.act(old,'crushTomato',0)).toBe(old);expect(R.act(finished,'crushTomato',0)).toBe(finished);});
 it('restores partial texture from actions and retains genuine older tomato physics',()=>{const s=R.act(soft(),'crushTomato',5,'masher-press');expect(R.restore(JSON.parse(JSON.stringify(s)))).toEqual(s);const old=JSON.parse(readFileSync('tests/fixtures/kitchen_recipe_pre_crushing.json','utf8')),restored=R.restore(old);expect(restored.tomatoModel).toBe(0);for(const key of ['pan','pot','prep','log','time'])expect(restored[key]).toEqual(old[key]);expect(R.replay(restored,restored.log.length).state.pan).toEqual(old.pan);});
 it.each([2,4])('completes and replays a crushed tomato recipe for %i, reducing released liquid when needed',count=>{let s=R.start('tomato',count,'demonstrate');for(const[a,v]of cook('tomato',count).steps){if(a==='combine'){s=crushed(s);while(s.pan.moisture>180*count/2-10)s=R.act(s,'advance',15);}s=R.act(s,a,v);}s=R.submit({...s,answers:[0,1]});expect(R.criteria(s).every(g=>g.met)).toBe(true);expect(R.restore(JSON.parse(JSON.stringify(s)))).toEqual(s);expect(R.evidence(s).tomatoHandling.crushed).toBe(14);const frame=R.replay(s,s.log.findIndex(e=>e.action==='crushTomato')+1);expect(R.tomatoHandling(frame.state).split).toBe(1);expect(frame.changes.some(c=>c.startsWith('Tomato texture:'))).toBe(true);expect(R.review(s).timeline.some(e=>e.event==='Softened tomato pressed into sauce')).toBe(true);});
 it('loads the masher before the app and mirrors changed assets',()=>{const html=readFileSync('stem_lab/kitchen_studio/recipe_lab.html','utf8');expect(html.indexOf('recipe_lab_crushing.js')).toBeLessThan(html.indexOf('src="recipe_lab.js"'));for(const name of ['recipe_lab_crushing.js','recipe_lab_engine.js','recipe_lab_scene.js','recipe_lab.js','recipe_lab.html','recipe_lab_hands.css'])expect(readFileSync('desktop/web-app/public/stem_lab/kitchen_studio/'+name,'utf8')).toBe(readFileSync('stem_lab/kitchen_studio/'+name,'utf8'));});
});
