import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),S=require('../stem_lab/kitchen_studio/recipe_lab_sauce_check.js'),G=require('../stem_lab/kitchen_studio/recipe_lab_gesture_guide.js');
describe('Native spoon trail',()=>{
 it('requires starting at the left and drawing across before release can record a check',()=>{for(const p of [null,{x:NaN,z:0},{x:.2,z:0},{x:-.4,z:.4}])expect(S.start(p)).toBeNull();const g=S.start({x:-.45,z:.1});expect(S.complete(g)).toBe(false);expect(S.complete(S.move(g,{x:.4,z:.1}))).toBe(false);expect(S.complete(S.move(g,{x:.43,z:.15}))).toBe(true);expect(g.x).toBe(-.45);});
 it('rejects lateral drifts, reversals, invalid coordinates and a path outside the pan even after reaching the end',()=>{const g=S.move(S.start({x:-.45,z:0}),{x:.1,z:0});for(const p of [null,{x:NaN,z:0},{x:.45,z:.3},{x:-.1,z:0},{x:.8,z:0}]){const invalid=S.move(g,p);expect(invalid.invalid).toBe(true);expect(S.complete(S.move(invalid,{x:.45,z:0}))).toBe(false);}expect(S.complete(S.move(g,{x:.45,z:.1}))).toBe(true);});
 it('guides the draw, release and retry phases without revealing or recording an observation',()=>{const s=R.startRescue('dry',0),before=JSON.stringify(s),g={kind:'sauce-check',trace:S.start({x:-.45,z:0})};expect(G.describe(s,g).phase).toBe('draw');g.trace=S.move(g.trace,{x:.45,z:0});expect(G.describe(s,g).phase).toBe('release');expect(G.describe(s,g).progress).toBe(1);g.trace=S.move(g.trace,{x:.45,z:.3});expect(G.describe(s,g).phase).toBe('retry');expect(JSON.stringify(s)).toBe(before);expect(S.reading(s)).toBeNull();});
 it('locks unfinished dishes, active serving, finished cooks and recorded views',()=>{expect(S.available(R.start(),false).ready).toBe(false);const s=R.startRescue('dry',0);expect(S.available(s,false).ready).toBe(true);expect(S.available(s,true).ready).toBe(false);const checked=R.act(s,'taste');expect(S.available(R.act(checked,'servePortion',0),false).ready).toBe(false);expect(S.available(R.act(checked,'plate'),false).ready).toBe(false);});
 it('records the same inspection and cooking effect as the keyboard equivalent, with native provenance',()=>{const s=R.startRescue('dry',0),a=R.act(s,'taste',undefined,'scene-sauce-trail'),b=R.act(s,'taste',undefined,'keyboard');expect(a.pan).toEqual(b.pan);expect(R.inspections(a)).toEqual(R.inspections(b));expect(a.time).toBe(s.time);expect(a.log.at(-1).interaction).toBe('scene-sauce-trail');expect(R.restore(a)).toEqual(a);});
 it('distinguishes the observed track and coating, retains previous readings and marks adjustments stale',()=>{let s=R.startRescue('dry',0);s=R.act(s,'taste');expect(S.cues(S.reading(s))).toMatchObject({track:'Stays open',coating:'Thick patches cling'});s=R.act(s,'pour',50);expect(S.reading(s).stale).toBe(true);s=R.act(s,'taste');expect(S.cues(S.reading(s))).toMatchObject({track:'Closes quickly',coating:'Thin liquid runs off'});expect(S.reading(s).previous.type).toBe('dry');s=R.act(R.act(s,'stirSweep','button'),'taste');expect(S.cues(S.reading(s))).toMatchObject({track:'Closes gradually',coating:'An even layer stays'});s=R.act(R.startRescue('watery',1),'taste');expect(S.reading(s).type).toBe('watery');expect(S.cues(S.reading(s)).thin).toBe(true);s={...s,pan:{...s.pan,damage:1}};s=R.act(s,'taste');expect(S.cues(S.reading(s))).toMatchObject({track:'Stays open',coating:'Dark patches cling'});});
 it('reconstructs native observation evidence in replay without inventing animation time',()=>{let s=R.startRescue('dry',0);s=R.act(s,'taste',undefined,'scene-sauce-trail');const index=s.log.length;s=R.act(R.act(s,'pour',50),'stirSweep','button');s=R.submit({...R.act(R.act(s,'taste'),'plate'),answers:[0,null]});expect(R.replay(s,index).state.pan.tasted).toBe(true);expect(R.inspections(R.replay(s,index).state).at(-1).type).toBe('dry');expect(s.time).toBe(0);});
});
