import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const require=createRequire(import.meta.url),R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),cook=require('../dev-tools/kitchen_recipe_fixture.cjs');
function ready(servings=2){let s=R.start('mushroom',servings);s=R.act(s,'fill');s.pot.pasta=true;s.pot.progress=.9;s=R.act(s,'sample');return s;}
function fullRecipe(){let s=R.start('mushroom',2,'demonstrate');for(const [a,v]of cook().steps){if(a==='reserve'){for(let i=0;i<4;i++)s=R.act(s,'ladle',undefined,'ladle-carry');}else if(a==='drain'){while(!s.pot.drained)s=R.act(s,'drainPour',250,'drain-tilt');}else s=R.act(s,a,v);}return R.submit({...s,answers:[0,0]});}
describe('Saving and gradually draining cooking water',()=>{
 it('conserves water and leaves temperature and cooking time unchanged when carrying a ladle',()=>{const s=ready(),before=JSON.stringify(s),n=R.act(s,'ladle',undefined,'scene-ladle');expect(n.pot.reserve).toBe(50);expect(n.pot.water).toBe(s.pot.water-50);expect(n.pot.temp).toBe(s.pot.temp);expect(n.time).toBe(s.time);expect(n.log.at(-1).transfer).toEqual({to:'jug',amount:50});expect(n.log.at(-1).interaction).toBe('scene-ladle');expect(JSON.stringify(s)).toBe(before);});
 it.each([2,4])('limits saved and already-used water to the allowance for %i servings',servings=>{let s=ready(servings);for(let i=0;i<12;i++)s=R.act(s,'ladle');expect(s.pot.reserve).toBe(200*servings/2);s.pan.produce=true;s=R.act(s,'pour',50);const n=R.act(s,'ladle');expect(n.log.at(-1).accepted).toBe(false);expect(n.pot).toEqual(s.pot);expect(R.waterHandling(n).remaining).toBe(0);});
 it('tops up a partially filled allowance with the simplified control without duplicating water',()=>{let s=R.act(ready(),'ladle');const initial=s.pot.water+s.pot.reserve;s=R.act(s,'reserve');expect(s.pot.reserve).toBe(200);expect(s.pot.water+s.pot.reserve).toBe(initial);expect(R.act(s,'reserve').log.at(-1).accepted).toBe(false);});
 it('handles small and fractional remnants without inventing water',()=>{const s=ready();s.pot.water=37.6;const n=R.act(s,'ladle');expect(n.pot.reserve).toBe(30);expect(n.pot.water).toBeCloseTo(7.6);expect(R.waterHandling(n).scoop).toBe(0);const d=R.act(n,'drainPour',25);expect(d.pot.water).toBe(0);expect(d.pot.drained).toBe(true);expect(d.log.at(-1).transfer.amount).toBeCloseTo(7.6);});
 it('requires cooking water for scooping and a sample before draining',()=>{const s=R.start();expect(R.act(s,'ladle').log.at(-1).accepted).toBe(false);expect(R.act(s,'drainPour',100).log.at(-1).accepted).toBe(false);const noSample=ready();noSample.pot.sample=null;expect(R.act(noSample,'drainPour',100).pot).toEqual(noSample.pot);});
 it('partially drains while keeping the saved jug, food, burner setting, and sample intact',()=>{const s=R.act(ready(),'ladle');s.pot.heat=3;const n=R.act(s,'drainPour',100,'drain-tilt');expect(n.pot.water).toBe(s.pot.water-100);expect(n.pot.drained).toBe(false);expect(n.pot.reserve).toBe(50);expect(n.pot.heat).toBe(3);expect(n.pot.progress).toBe(s.pot.progress);expect(n.pot.sample).toEqual(s.pot.sample);expect(R.waterHandling(n).drained).toBe(100);expect(n.feedback).toContain('burner is still on');});
 it('makes emptied water unavailable and only permits combining after drainage finishes',()=>{let s=ready();s.pan.produce=s.pan.garlic=true;s=R.act(s,'drainPour',100);expect(R.act(s,'combine').log.at(-1).accepted).toBe(false);while(!s.pot.drained)s=R.act(s,'drainPour',250);expect(s.pot.water).toBe(0);expect(R.act(s,'ladle').pot.reserve).toBe(0);expect(R.act(s,'reserve').pot.reserve).toBe(0);expect(R.act(s,'combine').pan.combined).toBe(true);});
 it('rejects invalid drainage amounts and all water handling after a cook finishes',()=>{const s=ready();for(const n of [undefined,null,0,-25,1,26,300,NaN,'100',{}])expect(R.act(s,'drainPour',n)).toBe(s);const ended={...s,plated:true};expect(R.act(ended,'ladle')).toBe(ended);expect(R.act(ended,'drainPour',100)).toBe(ended);});
 it('preserves genuine older saved pot state and action history',()=>{const old=JSON.parse(readFileSync('tests/fixtures/kitchen_recipe_legacy_sizes.json','utf8')),next=R.restore(old);for(const key of ['pot','pan','time','log'])expect(next[key]).toEqual(old[key]);});
 it('completes a recipe and reconstructs transferred amounts, partial drains, and review evidence',()=>{const s=fullRecipe();expect(s.submitted).toBe(true);expect(R.criteria(s).every(c=>c.met)).toBe(true);expect(R.restore(JSON.parse(JSON.stringify(s)))).toEqual(s);const index=s.log.findIndex(e=>e.action==='drainPour')+1,frame=R.replay(s,index);expect(frame.state.pot.drained).toBe(false);expect(frame.changes.some(c=>c.startsWith('Water in the pot'))).toBe(true);expect(R.evidence(s).waterHandling.drained).toBeGreaterThan(0);expect(R.review(s).timeline.some(t=>t.event.includes('gradually drained'))).toBe(true);});
 it('loads each runtime once and keeps the desktop copy identical',()=>{const html=readFileSync('stem_lab/kitchen_studio/recipe_lab.html','utf8');for(const runtime of ['heat','water'])expect(html.match(new RegExp('src="recipe_lab_'+runtime+'\\.js"','g'))).toHaveLength(1);expect(html.indexOf('recipe_lab_water.js')).toBeLessThan(html.indexOf('src="recipe_lab.js"'));for(const name of ['recipe_lab_water.js','recipe_lab_engine.js','recipe_lab_scene.js','recipe_lab.js','recipe_lab.html','recipe_lab_hands.css'])expect(readFileSync('desktop/web-app/public/stem_lab/kitchen_studio/'+name,'utf8')).toBe(readFileSync('stem_lab/kitchen_studio/'+name,'utf8'));});
});
