import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),J=require('../stem_lab/kitchen_studio/recipe_lab_jug.js'),H=require('../stem_lab/kitchen_studio/recipe_lab_hands.js'),G=require('../stem_lab/kitchen_studio/recipe_lab_gesture_guide.js');
const pan={x:1.02,z:-.45},p=(x,z,u=0,v=0)=>({x,z,u,v}),docked=()=>J.move(J.start(p(-1.2,1.06)),p(1.02,-.45,100,100),pan);
describe('Deliberate saved-water jug tilt',()=>{
 it('does not pour while carrying, hovering over the pan or holding a level jug',()=>{let g=J.start(p(-1.2,1.06));expect(g.phase).toBe('carry');expect(g.tilt).toBe(0);g=J.move(g,p(1.02,-.45,100,100),pan);expect(g.phase).toBe('level');for(let i=0;i<10;i++)g=J.move(g,p(1.02,-.45,100,100),pan);expect(g.tilt).toBe(0);expect(H.pourStep(0,g.tilt,100,200).amount).toBe(0);});
 it('lets carrying settle over the pan before a distinct downward movement starts the flow',()=>{let g=J.move(J.start(p(-1.2,1.06)),p(.5,-.45,80,130),pan);g=J.move(g,p(1.02,-.45,100,100),pan);expect(g.anchor).toEqual({u:100,v:100});expect(g.tilt).toBe(0);const tilted=J.move(g,p(1.02,.1,100,160),pan);expect(tilted.phase).toBe('pour');expect(tilted.tilt).toBe(45);expect(tilted.position).toEqual(pan);expect(g.tilt).toBe(0);});
 it('levels immediately, resets fractional flow, and resumes only with a new tilt',()=>{const initial=docked(),tilted=J.move(initial,p(1.02,.1,100,180),pan);expect(tilted.tilt).toBe(60);const level=J.move(tilted,p(1.02,-.45,100,100),pan);expect(level.phase).toBe('level');expect(level.tilt).toBe(0);expect(H.pourStep(8,level.tilt,100,200)).toEqual({amount:0,remainder:0});expect(J.move(level,p(1.02,.1,100,140),pan).tilt).toBe(30);});
 it('stops on sideways movement and lets the level jug be carried away and redocked',()=>{const g=J.move(docked(),p(1.02,.1,100,170),pan);expect(J.move(g,p(1.4,.1,145,170),pan).tilt).toBe(0);const carried=J.move(g,p(-1.2,1.06,200,170),pan);expect(carried.phase).toBe('carry');expect(carried.tilt).toBe(0);const again=J.move(carried,p(1.02,-.45,100,100),pan);expect(again.phase).toBe('level');expect(again.tilt).toBe(0);});
 it('invalid coordinates interrupt the movement without allowing later flow',()=>{expect(J.start(null)).toBeNull();for(const p of [null,{x:NaN,z:0,u:0,v:0}]){const invalid=J.move(docked(),p,pan);expect(invalid.invalid).toBe(true);expect(invalid.tilt).toBe(0);expect(J.move(invalid,{x:1.02,z:0,u:100,v:180},pan).tilt).toBe(0);}});
 it('allows a gentle or larger tilt to control the rate while doses conserve actual jug contents',()=>{function volume(tilt){let n=0,r=0;for(let i=0;i<10;i++){const d=H.pourStep(r,tilt,100,200-n);n+=d.amount;r=d.remainder;}return n;}expect(volume(30)).toBe(20);expect(volume(70)).toBe(60);let s=R.startRescue('dry',0),trace=J.move(docked(),p(1.02,0,100,180),pan),remaining=0;const original=s.pot.reserve+s.pan.waterAdded;for(let i=0;i<50;i++){const dose=H.pourStep(remaining,trace.tilt,100,s.pot.reserve);remaining=dose.remainder;if(dose.amount)s=R.act(s,'pour',dose.amount,'scene-pour');}expect(s.pot.reserve+s.pan.waterAdded).toBe(original);expect(s.pot.reserve).toBe(0);expect(s.time).toBe(0);expect(R.restore(s)).toEqual(s);});
 it('guides carrying, level and flow phases with the measured amount without changing evidence',()=>{const s=R.startRescue('dry',0),before=JSON.stringify(s),g={kind:'pour',trace:J.start(p(-1.2,1.06)),tilt:0,poured:0};expect(G.describe(s,g).phase).toBe('carry');g.trace=docked();expect(G.describe(s,g).phase).toBe('level');g.trace=J.move(g.trace,p(1.02,0,100,170),pan);g.tilt=g.trace.tilt;g.poured=30;expect(G.describe(s,g).phase).toBe('pour');expect(G.describe(s,g).detail).toContain('30 mL added');expect(G.describe(s,g).instruction).toContain('level');expect(JSON.stringify(s)).toBe(before);});
 it('respects preparation, empty jugs, serving, replay and completion locks',()=>{expect(J.available(R.start(),false).ready).toBe(false);const s=R.startRescue('dry',0);expect(J.available(s,false).ready).toBe(true);expect(J.available(s,true).ready).toBe(false);expect(J.available({...s,pot:{...s.pot,reserve:0}},false).ready).toBe(false);const checked=R.act(s,'taste');expect(J.available(R.act(checked,'servePortion',0),false).ready).toBe(false);expect(J.available(R.act(checked,'plate'),false).ready).toBe(false);});
});
