import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),W=require('../stem_lab/kitchen_studio/recipe_lab_weighing.js'),K=require('../stem_lab/kitchen_studio/recipe_lab_garlic.js'),M=require('../stem_lab/kitchen_studio/recipe_lab_crushing.js'),H=require('../stem_lab/kitchen_studio/recipe_lab_hands.js'),S=require('../stem_lab/kitchen_studio/recipe_lab_stir.js'),G=require('../stem_lab/kitchen_studio/recipe_lab_gesture_guide.js');
describe('Guidance observes direct kitchen gestures',()=>{
 it('distinguishes carrying, positioning, and flowing pasta without recording a portion',()=>{const s=R.start(),before=JSON.stringify(s),g={kind:'weigh',over:false,tilt:0};expect(G.describe(s,g,{amount:0}).phase).toBe('carry');g.over=true;expect(G.describe(s,g,{amount:0}).phase).toBe('tilt');g.tilt=60;const live=G.describe(s,g,{amount:80});expect(live.phase).toBe('pour');expect(live.progress).toBe(.5);expect(live.detail).toContain('80 g');g.tilt=0;expect(G.describe(s,g,{amount:80}).phase).toBe('tilt');expect(G.describe(s,g,{amount:200}).progress).toBe(1);expect(JSON.stringify(s)).toBe(before);});
 it('only marks a handful return at the actual release-plane destination',()=>{const s=R.start(),g={kind:'handful',moved:true,current:W.scene.packet};expect(G.describe(s,g,{amount:90,releasePoint:{x:0,z:0}}).over).toBe(false);expect(G.describe(s,g,{amount:90,releasePoint:W.scene.packet}).phase).toBe('release');});
 it('requires the down and up portions of a garlic pass',()=>{const s=R.act(R.start(),'wash'),g={kind:'mince',index:0,trace:K.start({x:0,y:0})};expect(G.describe(s,g).phase).toBe('down');g.trace=K.move(g.trace,{x:0,y:70});expect(G.describe(s,g).phase).toBe('up');expect(G.describe(s,g).progress).toBe(.5);g.trace=K.move(g.trace,{x:0,y:0});expect(G.describe(s,g).phase).toBe('release');expect(G.describe(s,g).progress).toBe(1);});
 it('shows a retry for a sideways knife stroke even after full downward travel',()=>{const g={kind:'cut',stroke:H.knifeMove(H.knifeStart(80,20,[40]),110,110)},d=G.describe(R.start(),g);expect(d.invalid).toBe(true);expect(d.phase).toBe('retry');expect(d.progress).toBe(0);});
 it('does not mistake a completed press on firm tomato for released juice',()=>{const s=R.start('tomato'),g={kind:'crush',index:0,press:M.move(M.start({x:0,y:0}),{x:0,y:75})};const d=G.describe(s,g);expect(d.phase).toBe('release');expect(d.detail).toContain('firm piece resists');expect(s.pan.produce).toBe(false);});
 it('follows the stir recognizer when a sweep reverses or leaves the pan',()=>{let trace=S.start(0);trace=S.move(trace,Math.PI/2,true);const s=R.start(),g={kind:'stir',trace};expect(G.describe(s,g).progress).toBeGreaterThan(.24);g.trace=S.move(trace,0,true);expect(G.describe(s,g).progress).toBe(0);g.trace=S.move(trace,Math.PI,false);expect(G.describe(s,g).progress).toBe(0);});
 it('requires dipping before a jug drop can save water',()=>{const s=R.start(),g={kind:'ladle',current:{x:-1.2,z:1.06},dipped:false};expect(G.describe(s,g).phase).toBe('dip');expect(G.describe(s,g).over).toBe(false);g.dipped=true;expect(G.describe(s,g).phase).toBe('release');expect(G.describe(s,g).target).toEqual({item:'jug'});});
 it('keeps completed drainage visible while a pot is leveled',()=>{const s=R.start();s.pot.water=750;const g={kind:'drain',over:true,tilt:0,drained:250};const d=G.describe(s,g);expect(d.phase).toBe('tilt');expect(d.progress).toBe(.25);expect(d.detail).toContain('250 mL drained');g.tilt=50;expect(G.describe(s,g).phase).toBe('drain');});
 it('shows the bowl when the drying cloth is full and tracks contact independently',()=>{const s=R.act(R.act(R.start(),'wash'),'rinse');s.prep.clothLoad=8;const g={kind:'dry',target:0,step:{elapsed:225}};expect(G.describe(s,g).phase).toBe('full');expect(G.describe(s,g).target).toEqual({bowl:true});expect(G.describe(s,g).progress).toBe(0);g.target='wring';g.step.elapsed=450;expect(G.describe(s,g).phase).toBe('wring');expect(G.describe(s,g).progress).toBe(.5);});
 it('marks the matching cookware without promising that recipe prerequisites passed',()=>{const g={kind:'move',item:'pasta'},s=R.start();expect(G.describe(s,g,{destination:'pan'}).phase).toBe('carry');const d=G.describe(s,g,{destination:'pot'});expect(d.phase).toBe('release');expect(d.detail).toContain('checks preparation');expect(s.pot.pasta).toBe(false);});
 it('does not mark a piece outside the pan as a valid drop',()=>{const s=R.start(),g={kind:'piece',index:0,moved:true,current:{x:3,z:3}};expect(G.describe(s,g).phase).toBe('outside');g.current=R.panPosition(s);expect(G.describe(s,g).phase).toBe('release');});
 it('follows the actual plate position while keeping a valid alternate plate available',()=>{const s=R.startRescue('dry',0,'practice'),plates=[{x:-.3,z:1.1},{x:.65,z:1.1}],g={kind:'serve',from:'pan',moved:true,current:plates[1]};const d=G.describe(s,g,{plates});expect(d.target).toEqual({servingPlate:1});expect(d.phase).toBe('release');g.from=1;g.current=R.panPosition(s);expect(G.describe(s,g,{plates}).target).toEqual({pan:true});});
 it('has no output for idle or unknown gestures',()=>{expect(G.describe(R.start(),null)).toBeNull();expect(G.describe(R.start(),{kind:'unknown'})).toBeNull();});
});
