import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import * as e from '../lesson_board_engine.js';
import {completionGuide,learningDocument,learningHTML,learningText} from '../lesson_board_sharing.js';
import {prepareReplay,checkReplay,replayState} from '../lesson_board_replay.js';
const {makeBoard}=createRequire(import.meta.url)('../dev-tools/fixtures/lesson_board.cjs');
function completed(board){let run=e.emptyRun();for(const id of ['heater','cloud','bridge','river','research']){run=e.merge(run,e.begin(board,run,id));const node=board.locations.find(node=>node.id===id);if(node){e.stepOf(run).answers.solo={value:e.solution(node),correct:true};run=e.merge(run,e.resolve(board,run,{solo:{}}));}if(!e.derive(board,run).complete)run=e.merge(run,e.advance(board,run));}return run;}
const plan=()=>({started:true,projectId:'bridge',effectChoice:'path',evidenceIds:['heater','river'],mode:'text',explanation:'Use our bridge to investigate how evaporation connects with collection.',checks:{connection:true,evidence:true,purpose:true},reviewed:true});
const practice=(b,r)=>{let value=prepareReplay(b,r,{started:true,targetIds:['heater']});return checkReplay(b,r,{...value,draft:e.solution(replayState(b,value).node)});};
describe('Completion steps and readable learning documents',()=>{
 it('updates the suggested next step without treating follow-ups as part of the mission score',()=>{const b=makeBoard(),r=completed(b);expect(completionGuide(b,e.emptyRun()).available).toBe(false);expect(completionGuide(b,r).recommended).toBe('finale');expect(completionGuide(b,r,{...plan(),reviewed:false}).finaleStatus).toBe('draft');expect(completionGuide(b,r,plan()).recommended).toBe('practice');expect(completionGuide(b,r,plan(),practice(b,r))).toMatchObject({recommended:'share',finaleStatus:'complete',practiceStatus:'complete'});});
 it('offers review and sharing at the move limit without claiming the mission is complete',()=>{const b=makeBoard(),r={turn:47,steps:{t47:{phase:'review',targetId:'heater',result:{success:false,marks:{solo:false}}}}};expect(completionGuide(b,r)).toMatchObject({available:true,missionComplete:false,finaleStatus:'unavailable',recommended:'practice'});});
 it('separates original game responses, self-reviewed explanations and current practice checks',()=>{const b=makeBoard(),r=completed(b),before=JSON.stringify(r),model=learningDocument(b,r,{finale:plan(),replay:practice(b,r)}),text=learningText(model);expect(text).toContain('My recorded game responses');expect(text).toContain('Self-review complete');expect(text).toContain('Correct checks including retries: 1/1');expect(text).toContain('not an independent assessment');expect(JSON.stringify(r)).toBe(before);});
 it('exports only the selected learner and omits identity fields and classmates',()=>{const b=makeBoard(),r=completed(b);r.steps.t0.result.marks={solo:true,other:false};r.steps.t0.answers={...(r.steps.t0.answers||{}),other:{value:'0',correct:false}};const model=learningDocument(b,r,{uid:'solo',roster:{other:{name:'Private classmate'}}});expect(JSON.stringify(model)).not.toContain('Private classmate');expect(JSON.stringify(model)).not.toContain('other');expect(model.name).toBe('');expect(model).not.toHaveProperty('uid');});
 it('labels teacher and preview summaries without including learner response tables',()=>{const b=makeBoard(),r=completed(b),teacher=learningText(learningDocument(b,r,{role:'teacher',finale:plan()}));expect(teacher).toContain('Teacher demonstration');expect(teacher).not.toContain('My recorded game responses');expect(learningText(learningDocument(b,r,{preview:true}))).toContain('Preview session; not a learner assessment');});
 it('respects section and evidence choices and bounds an optional name',()=>{const b=makeBoard(),r=completed(b),model=learningDocument(b,r,{finale:plan(),replay:practice(b,r)},{game:false,practice:false,evidence:false,name:'x'.repeat(100)});expect(model.name).toHaveLength(80);expect(model.sections.some(section=>section.rows)).toBe(false);expect(model.sections.some(section=>section.quote)).toBe(false);expect(learningDocument(b,r,{finale:plan()},{game:false,practice:false,evidence:true}).sections.some(section=>section.quote)).toBe(true);});
 it('excludes a hidden written draft when the plan uses communication tools',()=>{const b=makeBoard(),r=completed(b),model=learningDocument(b,r,{finale:{...plan(),mode:'oral',oralConfirmed:true,explanation:'Hidden private draft'}});expect(learningText(model)).not.toContain('Hidden private draft');expect(learningHTML(model)).not.toContain('Hidden private draft');expect(learningText(model)).toContain('No recording is included');});
 it('shows a draft status and the selected incorrect construction effect without grading the explanation',()=>{const b=makeBoard(),r=completed(b),text=learningText(learningDocument(b,r,{finale:{...plan(),effectChoice:'instant'}}));expect(text).toContain('Draft plan');expect(text).toContain('Selected board effect: Collect another full reward immediately');expect(text).toContain('Construction rule: Opens a direct path');expect(text).toContain('Construction rule checked: Not yet');});
 it('exports checked practice totals while excluding unfinished response values',()=>{const b=makeBoard(),r=completed(b),replay=prepareReplay(b,r,{started:true,targetIds:['heater'],draft:'1'}),model=learningDocument(b,r,{replay},{game:false,finale:false});expect(learningText(model)).toContain('Correct checks including retries: 0/0');expect(model.sections[0].rows[0]).toEqual(['Heating station','0','0','No recorded response']);});
 it('escapes all active markup and keeps printable HTML free of scripts, media and remote resources',()=>{const b=makeBoard(),r=completed(b);b.title='<img src="https://invalid.test/x" onerror="alert(1)">';const model=learningDocument(b,r,{finale:{...plan(),explanation:'</p><script>alert(1)</script><iframe src="https://invalid.test"></iframe>'}},{name:'<svg onload="alert(1)">'}),html=learningHTML(model),doc=new DOMParser().parseFromString(html,'text/html');expect(doc.querySelector('script,img,iframe,svg,object,link,a')).toBeNull();expect(doc.body.textContent).toContain('<script>alert(1)</script>');expect(doc.querySelector('meta[http-equiv="Content-Security-Policy"]').content).toContain("default-src 'none'");expect(doc.querySelectorAll('th[scope="col"]').length).toBeGreaterThan(0);});
 it('preserves Unicode and right-to-left document direction while rejecting injected language attributes',()=>{const b=makeBoard(),r=completed(b),model=learningDocument(b,r,{}, {name:'نور Éva 水'});expect(learningText(model)).toContain('نور Éva 水');const html=learningHTML(model,{lang:'ar',dir:'rtl'});expect(html).toContain('lang="ar" dir="rtl"');expect(learningHTML(model,{lang:'x" onload="alert(1)',dir:'bad'})).toContain('lang="en" dir="ltr"');});
});
