import {beforeAll,afterEach,describe,it,expect,vi} from 'vitest';
import {createRequire} from 'node:module';
import * as e from '../lesson_board_engine.js';
import {saveBoard,readSolo} from '../lesson_board_storage.js';
import {saveSupport,readSupport} from '../lesson_board_support.js';
import {activitySignature} from '../lesson_board_visual.js';
const require=createRequire(import.meta.url),{makeBoard,source,png,support}=require('../dev-tools/fixtures/lesson_board_support.cjs'),React=require('../desktop/web-app/node_modules/react'),{createRoot}=require('../desktop/web-app/node_modules/react-dom/client'),{act}=React;
let UI,root,element;const t=key=>key;
async function render(Component,props={}){if(!root){element=document.createElement('div');element.className='lb';document.body.append(element);root=createRoot(element);}await act(async()=>root.render(React.createElement(Component,{t,...props})));}
const click=async selector=>{const node=typeof selector==='string'?element.querySelector(selector):selector;expect(node).toBeTruthy();await act(async()=>{node.click();await new Promise(resolve=>setTimeout(resolve,0));});};
const change=async(selector,value)=>act(async()=>{const node=element.querySelector(selector);expect(node).toBeTruthy();if(node.tagName==='INPUT'||node.tagName==='TEXTAREA')Object.getOwnPropertyDescriptor(node.tagName==='INPUT'?HTMLInputElement.prototype:HTMLTextAreaElement.prototype,'value').set.call(node,value);else node.value=value;node.dispatchEvent(new Event(node.tagName==='SELECT'?'change':'input',{bubbles:true}));if(node.tagName!=='SELECT')node.dispatchEvent(new Event('change',{bubbles:true}));});
async function reload(Component,props){await act(async()=>root.unmount());root=null;element.remove();await render(Component,props);}
const named=name=>[...element.querySelectorAll('button')].find(button=>button.textContent===name);
const board=()=>e.prepareBoard(makeBoard());
function visualSupport(id='heater'){const b=board(),raw=support(),node=b.locations.find(node=>node.id===id);const prefix=node.kind==='order'?'item2':node.kind==='settings'?'setting0_0':'option1';raw.definitionMode='review';raw.activities={[id]:{signature:activitySignature(node),reviewed:true,cues:{prompt:{termId:'evaporation',imageId:'picture',description:'Sunlight warms a bowl of liquid water.'},[prefix]:{termId:'evaporation',imageId:'picture',description:'Liquid water changes into vapor.'}}}};return raw;}
const props=(extra={})=>({inputText:source,language:'English',appId:'guided-test',user:{uid:'u'},allowLive:false,onClose(){},...extra});
async function answer(id){const node=board().locations.find(node=>node.id===id);if(node.kind==='choice')await change('.lb-current [data-board-choice]',String(node.answer));else for(let i=0;i<node.controls.length;i++)await change('.lb-current [data-board-control="'+i+'"]',String(node.controls[i].answer));await click('[data-board-submit]');}
async function move(id){await click('[data-ready-move="'+id+'"]');await click('[data-board-move="'+id+'"]');}
beforeAll(()=>{window.React=React;globalThis.IS_REACT_ACT_ENVIRONMENT=true;window.AlloLanguageContext=React.createContext({t});const bundle=require('node:child_process').execFileSync(process.execPath,['-e',"process.stdout.write(require('esbuild').buildSync({stdin:{contents:\"export {BoardView,Activity} from './lesson_board_ui.jsx';export {LessonBoardSetup,LessonBoardSolo} from './lesson_board_source.jsx';\",resolveDir:process.cwd()},bundle:true,write:false,format:'iife',globalName:'GuideUI',jsxFactory:'React.createElement',jsxFragment:'React.Fragment'}).outputFiles[0].text)"],{encoding:'utf8'});UI=new Function(bundle+';return GuideUI;')();});
afterEach(async()=>{if(root)await act(async()=>root.unmount());element?.remove();element=root=null;localStorage.clear();sessionStorage.clear();vi.restoreAllMocks();});
describe('First build guide and visual challenge interactions',()=>{
 it('previews and explicitly enables suggested pictures without starting a game',async()=>{const b=board();saveBoard(localStorage,source,'English',b);saveSupport(localStorage,b,'guided-test','u',support(),null);await render(UI.LessonBoardSetup,props());await click('[data-suggest-visuals]');expect(element.querySelector('[data-enable-visual]').disabled).toBe(true);await click('[data-preview-visual]');expect(element.querySelector('[data-visual-preview] img')).toBeTruthy();await click('[data-visual-preview] [data-visual-answer="option1"]');expect(element.querySelector('[data-visual-preview] [data-board-choice]').value).toBe('1');await click('[data-enable-visual]');await click(named('Save board'));expect(readSupport(localStorage,b,'guided-test','u').support.activities.heater.reviewed).toBe(true);expect(Object.keys(localStorage).some(key=>key.startsWith('allo-board-solo'))).toBe(false);});
 it('requires another preview and review when a cue description is edited',async()=>{const b=board();saveBoard(localStorage,source,'English',b);saveSupport(localStorage,b,'guided-test','u',visualSupport(),null);await render(UI.LessonBoardSetup,props());expect(element.querySelector('[data-enable-visual]').checked).toBe(true);await change('[data-visual-description="prompt"]','A new equivalent description.');expect(element.querySelector('[data-enable-visual]').checked).toBe(false);expect(element.querySelector('[data-enable-visual]').disabled).toBe(true);await click('[data-preview-visual]');await click('[data-enable-visual]');expect(element.querySelector('[data-enable-visual]').checked).toBe(true);await change('[data-visual-description="prompt"]','');expect(element.querySelector('[data-preview-visual]').disabled).toBe(true);});
 it('shows reviewed challenge cues while preserving review-only glossary support',async()=>{const b=board(),run=e.merge(e.emptyRun(),e.begin(b,e.emptyRun(),'heater'));await render(UI.BoardView,{board:b,run,support:visualSupport()});expect(element.querySelector('.lb-current [data-visual-cue] img')).toBeTruthy();expect(element.querySelector('.lb-current [data-vocabulary-withheld]')).toBeTruthy();expect(element.querySelector('.lb-current [data-vocabulary-definition]')).toBeNull();});
 it('uses the same response and equivalent text when pictures are hidden, including after reload',async()=>{const b=board(),p={board:b,support:visualSupport(),appId:'guided-test',user:{uid:'u'}};await render(UI.LessonBoardSolo,p);await move('heater');await click('.lb-current [data-visual-answer="option1"]');const before=JSON.stringify(readSolo(localStorage,b,'guided-test','u').run);await click('[data-board-images]');expect(element.querySelectorAll('[data-board-play] img')).toHaveLength(0);expect(element.querySelector('.lb-current').textContent).toContain('Sunlight warms a bowl');expect(element.querySelector('.lb-current option[value="1"]').textContent).toContain('Liquid water changes');expect(element.querySelector('.lb-current [data-visual-answer="option1"]').textContent).toContain('Liquid water changes');await reload(UI.LessonBoardSolo,p);expect(element.querySelector('.lb-current [data-board-choice]').value).toBe('1');expect(element.querySelector('[data-board-images]').getAttribute('aria-pressed')).toBe('false');expect(JSON.stringify(readSolo(localStorage,b,'guided-test','u').run)).toBe(before);await click('[data-board-submit]');expect(e.derive(b,readSolo(localStorage,b,'guided-test','u').run).visited).toContain('heater');});
 it('moves a sequence picture with its item rather than its displayed position',async()=>{const b=board(),node=b.locations.find(node=>node.id==='sequence'),raw=visualSupport('sequence'),onChange=vi.fn();await render(UI.Activity,{node,value:'0,1,2,3',support:raw,onChange});expect(element.querySelector('[data-board-up="2"]').parentElement.textContent).toContain('Liquid water changes');await click('[data-board-up="2"]');expect(onChange).toHaveBeenCalledWith('0,2,1,3');await render(UI.Activity,{node,value:'0,2,1,3',support:raw,onChange});const rows=[...element.querySelectorAll('.lb-order li')];expect(rows[1].textContent).toContain('Evaporation');expect(rows[1].querySelector('img')).toBeTruthy();expect(rows[2].querySelector('img')).toBeNull();});
 it('uses pictured configuration choices without erasing the other control',async()=>{const b=board(),node=b.locations.find(node=>node.id==='weather'),onChange=vi.fn();await render(UI.Activity,{node,value:',1',support:visualSupport('weather'),onChange});await click('[data-visual-answer="setting0_0"]');expect(onChange).toHaveBeenCalledWith('0,1');});
 it('keeps teacher, paused, and confirmed visual responses disabled',async()=>{const b=board(),run=e.merge(e.emptyRun(),e.begin(b,e.emptyRun(),'heater'));for(const flags of [{role:'teacher'},{paused:true},{busy:true},{pending:{kind:'answer'}}]){const onAnswer=vi.fn();await render(UI.BoardView,{board:b,run,support:visualSupport(),onAnswer,onToggleRoles(){},...flags});expect(element.querySelector('[data-visual-answer="option1"]').disabled).toBe(true);await click('[data-visual-answer="option1"]');expect(onAnswer).not.toHaveBeenCalled();}});
 it('restores guided progress and reveals planning after the first successful exploration',async()=>{const b=board(),p={board:b,appId:'guided-test',user:{uid:'u'}};await render(UI.LessonBoardSolo,p);await click('[data-start-board-guide]');expect(element.querySelector('[data-board-guide]').dataset.boardGuide).toBe('explore');expect(element.querySelectorAll('[data-guided-tools]')).toHaveLength(2);await move('heater');expect(element.querySelector('[data-board-guide]').dataset.boardGuide).toBe('answer');await answer('heater');expect(element.querySelector('[data-board-guide]').dataset.boardGuide).toBe('reward');expect(element.querySelectorAll('[data-guided-tools]')).toHaveLength(0);await reload(UI.LessonBoardSolo,p);expect(element.querySelector('[data-board-guide]').dataset.boardGuide).toBe('reward');await click('[data-board-next]');await move('cloud');await answer('cloud');await click('[data-board-next]');expect(element.querySelector('[data-board-guide]').dataset.boardGuide).toBe('build');await click('[data-guide-inspect]');const target=element.querySelector('[data-board-move]').dataset.boardMove;await click('[data-board-move]');expect(element.querySelector('[data-board-guide]').dataset.boardGuide).toBe('complete');expect(e.derive(b,readSolo(localStorage,b,'guided-test','u').run).built).toContain(target);await click('[data-end-board-guide]');expect(element.querySelector('[data-board-guide]')).toBeNull();expect(readSolo(localStorage,b,'guided-test','u').workspace.guideMode).toBe('off');});
 it('explains classroom control and keeps guide inspection private',async()=>{const b=board(),onMove=vi.fn();await render(UI.BoardView,{board:b,run:e.emptyRun(),role:'student',uid:'learner',workspaceKey:'guided-class',onMove});await click('[data-start-board-guide]');expect(element.querySelector('[data-board-guide]').textContent).toContain('The teacher chooses');await click('[data-guide-inspect]');expect(onMove).not.toHaveBeenCalled();expect(JSON.parse(sessionStorage.getItem('guided-class')).guideMode).toBe('active');});
 it('guides failed exploration through retry and can be dismissed without changing progress',async()=>{const b=board(),p={board:b,appId:'guided-test',user:{uid:'u'}};await render(UI.LessonBoardSolo,p);await click('[data-start-board-guide]');await move('heater');await change('.lb-current [data-board-choice]','0');await click('[data-board-submit]');expect(element.querySelector('[data-board-guide]').dataset.boardGuide).toBe('retry');expect(element.querySelector('[data-board-guide]').textContent).toContain('No supplies were lost');const before=JSON.stringify(readSolo(localStorage,b,'guided-test','u').run);await click('[data-end-board-guide]');expect(JSON.stringify(readSolo(localStorage,b,'guided-test','u').run)).toBe(before);});
 it('uses cue text when a challenge picture cannot load',async()=>{const b=board();await render(UI.Activity,{node:b.locations[0],support:visualSupport(),value:'',onChange(){}});await act(async()=>element.querySelector('[data-visual-cue] img').dispatchEvent(new Event('error')));expect(element.textContent).toContain('Picture unavailable');expect(element.textContent).toContain('Sunlight warms a bowl');});
});
