import {beforeAll,afterEach,describe,it,expect,vi} from 'vitest';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import * as e from '../lesson_board_engine.js';
import * as boardStorage from '../lesson_board_storage.js';
import {exportBoardFile} from '../lesson_board_transfer.js';
import {loadAlloModule} from './setup.js';
const require=createRequire(import.meta.url),{source,makeBoard}=require('../dev-tools/fixtures/lesson_board.cjs'),React=require('../desktop/web-app/node_modules/react'),{createRoot}=require('../desktop/web-app/node_modules/react-dom/client'),{act}=React;
let root,el,api,write,read;const base={appId:'app',targetAppId:'app',activeSessionCode:'BOARD',user:{uid:'u'},inputText:source,language:'English',t:k=>k,onClose:()=>{},callGemini:async()=>JSON.stringify(makeBoard())};
const data=()=>({hostId:'host',roster:{u:{name:'Rowan'},v:{name:'Sky'}},escapeRoomState:e.createSession(makeBoard(),'host',{u:{},v:{}})});
const run=d=>e.runOf(d.escapeRoomState),step=d=>e.stepOf(run(d));
const render=async(Component,props={})=>{if(!root){el=document.createElement('div');document.body.appendChild(el);root=createRoot(el);}await act(async()=>root.render(React.createElement(Component,{...base,...props})));};
const button=name=>[...el.querySelectorAll('button')].find(b=>b.textContent.trim()===name),click=async node=>{expect(node).toBeTruthy();await act(async()=>node.click());},change=async(selector,value)=>{await act(async()=>{const node=el.querySelector(selector);node.value=value;node.dispatchEvent(new Event('change',{bubbles:true}));});};
beforeAll(()=>{global.React=window.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;write=vi.fn();read=vi.fn();window.__alloFirebase={db:{},doc:()=>({}),getDoc:(...args)=>read(...args),updateDoc:(...args)=>write(...args)};window.__alloShared={db:{},warnLog(){}};window.AlloLanguageContext=React.createContext({t:k=>k});window.UiLanguageSelector=()=>null;window.__alloHooks={useFocusTrap(){}};loadAlloModule('lesson_board_module.js');loadAlloModule('teacher_module.js');loadAlloModule('view_quiz_module.js');api=window.AlloModules;});
afterEach(async()=>{if(root)await act(async()=>root.unmount());el?.remove();el=root=null;write.mockReset();read.mockReset();localStorage.clear();sessionStorage.clear();delete window.__alloLessonBoardMailboxVersion;vi.useRealTimers();});
describe('Lesson board setup and solo',()=>{
 it('generates, saves and begins a solo board with no live reads or writes',async()=>{const ai=vi.fn(base.callGemini);await render(api.LessonBoardSetup,{callGemini:ai,allowLive:false});await click(button('Generate lesson board'));await click(button('Play solo'));expect(el.querySelector('[data-board-map]')).toBeTruthy();expect(localStorage.length).toBe(1);await click(el.querySelector('[data-board-move="heater"]'));await change('[data-board-choice]','1');await click(el.querySelector('[data-board-submit]'));expect(el.textContent).toContain('Location explored');expect(el.textContent).toContain('Observation tokens: 2');expect(write).not.toHaveBeenCalled();expect(read).not.toHaveBeenCalled();expect(ai).toHaveBeenCalledTimes(1);});
 it('preserves the previous board on failed generation',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await render(api.LessonBoardSetup,{callGemini:async()=>'{"bad":true}'});await click(button('Generate another board'));expect(el.textContent).toContain('could not be validated');expect(button('Play solo').disabled).toBe(false);});
 it('restores solo progress, current activity and unfinished settings on remount',async()=>{await render(api.LessonBoardSolo,{board:makeBoard()});await click(el.querySelector('[data-board-move="heater"]'));await change('[data-board-choice]','1');await click(el.querySelector('[data-board-submit]'));await click(el.querySelector('[data-board-next]'));await click(el.querySelector('[data-location="cloud"]'));await click(el.querySelector('[data-board-move="cloud"]'));await change('[data-board-control="0"]','1');await act(async()=>root.unmount());root=null;el.remove();await render(api.LessonBoardSolo,{board:makeBoard()});expect(el.textContent).toContain('Observation tokens: 2');expect(el.querySelector('[data-board-control="0"]').value).toBe('1');expect(el.querySelector('[data-board-control="1"]').value).toBe('');});
 it('confirms reset and restores focus when cancelled',async()=>{await render(api.LessonBoardSolo,{board:makeBoard()});const trigger=button('Restart solo board');trigger.focus();await click(trigger);expect(document.activeElement).toBe(button('Cancel'));await click(button('Cancel'));expect(document.activeElement).toBe(trigger);});
 it('blocks a stale live launch and an outdated Mailbox before writing',async()=>{read.mockResolvedValue({data:()=>({hostId:'host',quizState:{isActive:true}})});await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await click(button('Launch for everyone'));expect(write).not.toHaveBeenCalled();expect(el.textContent).toContain('End the current live activity');window.__alloLessonBoardMailboxVersion=()=>20;read.mockClear();await click(button('Launch for everyone'));expect(read).not.toHaveBeenCalled();expect(el.textContent).toContain('version 21');});
 it('ignores a provider result after unmount and restores trigger focus',async()=>{let finish;const trigger=document.createElement('button');document.body.appendChild(trigger);trigger.focus();await render(api.LessonBoardSetup,{callGemini:()=>new Promise(resolve=>finish=resolve)});await click(button('Generate lesson board'));await act(async()=>root.unmount());root=null;await act(async()=>finish(JSON.stringify(makeBoard())));expect(document.activeElement).toBe(trigger);expect(write).not.toHaveBeenCalled();trigger.remove();});
});
describe('Live board delivery and turn isolation',()=>{
 it('routes existing teacher/student activity wrappers to the board',async()=>{const d=data();await render(api.StudentEscapeRoomOverlay,{sessionData:d});expect(el.querySelector('[data-board-map]')).toBeTruthy();await render(api.EscapeRoomTeacherControls,{sessionData:d});expect(button('Pause board')).toBeTruthy();});
 it('does not optimistically confirm actions and retries the exact saved request',async()=>{const d=data();write.mockRejectedValueOnce(Error('offline')).mockResolvedValue(undefined);await render(api.LessonBoardStudent,{sessionData:d});await click(el.querySelector('[data-board-move="heater"]'));const sent=Object.values(write.mock.calls[0][1])[0];expect(el.textContent).not.toContain('Your confirmed proposal:');await click(button('Retry this action'));expect(Object.values(write.mock.calls[1][1])[0]).toEqual(sent);expect(sessionStorage.length).toBeGreaterThan(0);});
 it('restores an unconfirmed request after remount and consumes only its own receipt',async()=>{write.mockResolvedValue(undefined);const d=data();await render(api.LessonBoardStudent,{sessionData:d});await click(el.querySelector('[data-board-move="heater"]'));const sent=Object.values(write.mock.calls[0][1])[0];await act(async()=>root.unmount());root=null;el.remove();await render(api.LessonBoardStudent,{sessionData:d});expect(el.querySelector('[data-board-pending]')).toBeTruthy();const updated=structuredClone(d);step(updated).seen.u={requestId:sent.requestId,code:'vote-recorded'};step(updated).votes.u='heater';await render(api.LessonBoardStudent,{sessionData:updated});expect(el.querySelector('[data-board-pending]')).toBeNull();expect(el.textContent).toContain('Your proposal is confirmed');});
 it('prevents a second send while the first transmission is unresolved',async()=>{let finish;write.mockImplementation(()=>new Promise(resolve=>finish=resolve));await render(api.LessonBoardStudent,{sessionData:data()});await click(el.querySelector('[data-board-move="heater"]'));expect(el.querySelector('[data-board-move="heater"]').disabled).toBe(true);expect(write).toHaveBeenCalledTimes(1);await act(async()=>finish());});
 it('retains a response draft across pause/resume and ignores a stale completion',async()=>{let fail;write.mockImplementation(()=>new Promise((_,reject)=>fail=reject));const d=data();Object.assign(run(d),e.merge(run(d),e.begin(d.escapeRoomState.board,run(d),'heater')));await render(api.LessonBoardStudent,{sessionData:d});await change('[data-board-choice]','1');const paused=structuredClone(d);paused.escapeRoomState.isPaused=true;await render(api.LessonBoardStudent,{sessionData:paused});expect(el.querySelector('[data-board-submit]').disabled).toBe(true);expect(el.querySelector('[data-board-choice]').value).toBe('1');await render(api.LessonBoardStudent,{sessionData:d});await click(el.querySelector('[data-board-submit]'));await render(api.LessonBoardStudent,{sessionData:data()});await act(async()=>fail(Error('old failure')));expect(el.querySelector('[role="alert"]')).toBeNull();});
 it('deduplicates two mounted hosts and scopes all acknowledgements to the attempt',async()=>{let finish;write.mockImplementation(()=>new Promise(resolve=>finish=resolve));const d=data(),a={attemptId:d.escapeRoomState.attemptId,turn:0,requestId:'request_a',targetId:'heater',kind:'vote',value:''};d.escapeRoomState.teamProgress.All.boardActions={u:a};const Twin=props=>React.createElement(React.Fragment,null,React.createElement(api.LessonBoardHost,props),React.createElement(api.LessonBoardHost,props));await render(Twin,{sessionData:d});expect(write).toHaveBeenCalledTimes(1);expect(Object.keys(write.mock.calls[0][1]).every(key=>key.includes('.boardRuns.'+d.escapeRoomState.attemptId+'.steps.t0.'))).toBe(true);await act(async()=>finish());});
 it('allows a late joiner to join only their own All slot',async()=>{const d=data();delete d.escapeRoomState.teams.u;write.mockResolvedValue(undefined);await render(api.LessonBoardStudent,{sessionData:d});expect(write.mock.calls[0][1]).toEqual({'escapeRoomState.teams.u':'All'});});
 it('keeps roots and desktop modules identical',()=>{for(const file of ['lesson_board_module.js','teacher_module.js','view_quiz_module.js'])expect(readFileSync(file,'utf8')).toBe(readFileSync('desktop/web-app/public/'+file,'utf8'));for(const file of ['AlloFlowANTI.txt','desktop/web-app/src/AlloFlowANTI.txt','desktop/web-app/src/App.jsx'])expect(readFileSync(file,'utf8')).toContain('<window.AlloModules.LessonBoardHost');});
});

describe('Board generation and control regression cases',()=>{
 it('starts only one provider request on a rapid repeated activation',async()=>{let finish;const ai=vi.fn(()=>new Promise(resolve=>finish=resolve));await render(api.LessonBoardSetup,{callGemini:ai});const trigger=button('Generate lesson board');await act(async()=>{trigger.click();trigger.click();});expect(ai).toHaveBeenCalledTimes(1);await act(async()=>finish(JSON.stringify(makeBoard())));expect(button('Play solo')).toBeTruthy();});
 it('accepts a provider result under React StrictMode',async()=>{const Strict=props=>React.createElement(React.StrictMode,null,React.createElement(api.LessonBoardSetup,props));await render(Strict);await click(button('Generate lesson board'));expect(button('Play solo')).toBeTruthy();});
 it('keeps generated location IDs separate from teacher command names',async()=>{const b=makeBoard();b.locations[0].id='pause';b.starts=b.starts.map(id=>id==='heater'?'pause':id);b.edges=b.edges.map(edge=>edge.map(id=>id==='heater'?'pause':id));const d={hostId:'host',roster:{u:{}},escapeRoomState:e.createSession(b,'host',{u:{}})};read.mockResolvedValue({data:()=>d});write.mockResolvedValue(undefined);await render(api.LessonBoardTeacher,{sessionData:d});await click(el.querySelector('[data-board-move="pause"]'));expect(write).toHaveBeenCalledTimes(1);const patch=write.mock.calls[0][1];expect(patch).not.toHaveProperty('escapeRoomState.isPaused');expect(Object.values(patch)).toContain('answer');});
});

describe('Decision, authoring and recovery refinements',()=>{
 const editText=async(selector,value)=>{await act(async()=>{const node=el.querySelector(selector);Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));});};
 it('releases an old proposal when the teacher opens an activity, even while the old send is unresolved',async()=>{let failOld;write.mockImplementationOnce(()=>new Promise((_,reject)=>failOld=reject)).mockResolvedValue(undefined);const d=data();await render(api.LessonBoardStudent,{sessionData:d});await click(el.querySelector('[data-board-move="heater"]'));const opened=structuredClone(d);Object.assign(run(opened),e.merge(run(opened),e.begin(opened.escapeRoomState.board,run(opened),'heater')));await render(api.LessonBoardStudent,{sessionData:opened});expect(el.querySelector('[data-board-pending]')).toBeNull();await change('[data-board-choice]','1');await click(el.querySelector('[data-board-submit]'));expect(write).toHaveBeenCalledTimes(2);expect(Object.values(write.mock.calls[1][1])[0].kind).toBe('answer');await act(async()=>failOld(Error('proposal arrived too late')));expect(el.querySelector('[role="alert"]')).toBeNull();expect(el.querySelector('[data-board-pending]')).toBeTruthy();});
 it('preserves an unconfirmed proposal while paused in the same action window',async()=>{write.mockResolvedValue(undefined);const d=data();await render(api.LessonBoardStudent,{sessionData:d});await click(el.querySelector('[data-board-move="heater"]'));const paused=structuredClone(d);paused.escapeRoomState.isPaused=true;await render(api.LessonBoardStudent,{sessionData:paused});expect(el.querySelector('[data-board-pending]')).toBeTruthy();expect(button('Retry this action').getAttribute('aria-disabled')).toBe('true');});
 it('waits for learner identity before joining or rendering actionable controls',async()=>{await render(api.LessonBoardStudent,{sessionData:data(),user:null});expect(el.textContent).toContain('Waiting for your live session connection');expect(write).not.toHaveBeenCalled();});
 it('joins only once under StrictMode while a join request is in flight',async()=>{let finish;write.mockImplementation(()=>new Promise(resolve=>finish=resolve));const d=data();delete d.escapeRoomState.teams.u;const Strict=props=>React.createElement(React.StrictMode,null,React.createElement(api.LessonBoardStudent,props));await render(Strict,{sessionData:d});expect(write).toHaveBeenCalledTimes(1);expect(button('Join shared board').disabled).toBe(true);await act(async()=>finish());});
 it('warns when a pending action cannot be saved and still sends it',async()=>{write.mockResolvedValue(undefined);await render(api.LessonBoardStudent,{sessionData:data()});const spy=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('quota');});try{await click(el.querySelector('[data-board-move="heater"]'));expect(write).toHaveBeenCalledTimes(1);expect(el.textContent).toContain('a reload may lose this pending action');expect(el.textContent).not.toContain('your action is saved');}finally{spy.mockRestore();}});
 it('allows generating for a new lesson while ignoring the old lesson request',async()=>{let finishOld;const ai=vi.fn().mockImplementationOnce(()=>new Promise(resolve=>finishOld=resolve)).mockResolvedValue(JSON.stringify({...makeBoard(),title:'New lesson board'}));await render(api.LessonBoardSetup,{callGemini:ai});await click(button('Generate lesson board'));await render(api.LessonBoardSetup,{callGemini:ai,inputText:'A new lesson context. '+source});await click(button('Generate lesson board'));expect(el.textContent).toContain('New lesson board');await act(async()=>finishOld(JSON.stringify({...makeBoard(),title:'Old lesson board'})));expect(el.textContent).not.toContain('Old lesson board');expect(ai).toHaveBeenCalledTimes(2);});
 it('uses edited options, answer key and hints in solo play',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await editText('[data-edit-location="heater"] [data-edit-option="0"]','Edited response');await change('[data-edit-location="heater"] [data-edit-answer]','0');await editText('[data-edit-location="heater"] [data-edit-hint="0"]','Look at the heat source.');await click(button('Play solo'));await click(el.querySelector('[data-board-move="heater"]'));expect(el.querySelector('[data-board-choice] option[value="0"]').textContent).toBe('Edited response');expect(el.textContent).toContain('Look at the heat source.');await change('[data-board-choice]','0');await click(el.querySelector('[data-board-submit]'));expect(el.textContent).toContain('Your response demonstrated this idea');});
 it('validates source edits before allowing a saved or live board',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await editText('[data-edit-location="heater"] [data-edit-quote]','This is not in the lesson.');expect(el.querySelector('[data-board-validation]').textContent).toContain('Quote must match');await click(button('Play solo'));expect(el.querySelector('[data-board-play]')).toBeNull();await click(button('Launch for everyone'));expect(read).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();expect(localStorage.length).toBe(0);});
 it('shows teacher proposals without starting the chosen activity on inspection',async()=>{const d=data();step(d).votes={u:'cloud',v:'cloud'};await render(api.LessonBoardTeacher,{sessionData:d});expect(el.querySelector('[data-class-proposals]').textContent).toContain('2/2');await click(el.querySelector('[data-proposal-target="cloud"]'));expect(el.querySelector('.lb-current h3').textContent).toBe('Cloud laboratory');expect(write).not.toHaveBeenCalled();});
 it('keeps the learner review on the teacher surface with missing responses labelled separately',async()=>{const d=data();step(d).phase='review';step(d).targetId='heater';step(d).result={success:true,marks:{u:true}};await render(api.LessonBoardTeacher,{sessionData:d});expect(el.querySelector('[data-learning-uid="u"]').textContent).toContain('1/1');expect(el.querySelector('[data-learning-uid="v"]').textContent).toContain('No recorded responses');await render(api.LessonBoardStudent,{sessionData:d});expect(el.querySelector('[data-board-learning]')).toBeNull();});
});

describe('Additional answer-key editing formats',()=>{
 it('uses revised settings keys in a played activity',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await change('[data-edit-location="cloud"] [data-edit-control="0"] [data-edit-answer]','0');await change('[data-edit-location="cloud"] [data-edit-control="1"] [data-edit-answer]','1');await click(button('Try the board'));await click(el.querySelector('[data-location="cloud"]'));await click(el.querySelector('[data-board-move="cloud"]'));await change('[data-board-control="0"]','0');await change('[data-board-control="1"]','1');await click(el.querySelector('[data-board-submit]'));expect(el.textContent).toContain('Your response demonstrated this idea');});
 it('saves a revised ordering key without changing the original item identities',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await click(el.querySelector('[data-edit-location="sequence"] [data-board-up="3"]'));await click(button('Save board'));const stored=JSON.parse(localStorage.getItem(Object.keys(localStorage).find(key=>key.startsWith('allo-lesson-boards:'))));const node=stored.boards[0].locations.find(node=>node.id==='sequence');expect(node.order).toEqual([3,2,0,1]);expect(node.items).toEqual(makeBoard().locations[5].items);expect(e.solution(node)).toBe('3,2,0,1');});
});

describe('Board file and library workflows',()=>{
 const importFile=async(text)=>{const file=typeof text==='string'?{size:text.length,text:async()=>text}:text;await act(async()=>{const input=el.querySelector('[data-import-board]');Object.defineProperty(input,'files',{configurable:true,value:[file]});input.dispatchEvent(new Event('change',{bubbles:true}));});};
 it('opens an included lesson for review without an AI call, save or session write',async()=>{const ai=vi.fn();await render(api.LessonBoardSetup,{inputText:'',language:'French',callGemini:ai});await importFile(exportBoardFile(makeBoard(),source,'English'));expect(el.querySelector('[data-board-editor]')).toBeNull();expect(el.querySelector('[data-board-file-review]')).toBeTruthy();expect(localStorage.length).toBe(0);await click(el.querySelector('[data-open-board-file]'));expect(el.querySelector('[data-board-editor]')).toBeTruthy();expect(el.textContent).toContain('Board language: English');expect(ai).not.toHaveBeenCalled();expect(read).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();expect(localStorage.length).toBe(0);await click(button('Try the board'));expect(el.querySelector('[data-board-map]')).toBeTruthy();});
 it('cancels an import without replacing the edited preview',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await importFile(exportBoardFile({...makeBoard(),title:'A different board'},source,'English'));await click(button('Cancel'));expect(el.querySelector('[data-board-editor] input').value).toBe(makeBoard().title);expect(el.querySelector('[data-board-file-review]')).toBeNull();expect(document.activeElement).toBe(el.querySelector('[data-import-board]'));});
 it('preserves a current board when the imported file is invalid',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await importFile('not JSON');expect(el.querySelector('[data-board-editor] input').value).toBe(makeBoard().title);expect(el.querySelector('[data-board-file-review]')).toBeNull();expect(el.textContent).toContain('supported AlloFlow lesson board file');});
 it('ignores a pending file read when the lesson changes',async()=>{let finish;await render(api.LessonBoardSetup);await importFile({size:100,text:()=>new Promise(resolve=>finish=resolve)});await render(api.LessonBoardSetup,{inputText:'A different source with enough text to generate a new lesson.'});await act(async()=>finish(exportBoardFile(makeBoard(),source,'English')));expect(el.querySelector('[data-board-file-review]')).toBeNull();expect(el.querySelector('[data-board-editor]')).toBeNull();});
 it('returns to the main lesson only after confirmation',async()=>{const original={...makeBoard(),title:'Original board'};boardStorage.saveBoard(localStorage,source,'English',original);await render(api.LessonBoardSetup);await importFile(exportBoardFile({...makeBoard(),title:'Imported board'},'Another reference. '+source,'Spanish'));await click(el.querySelector('[data-open-board-file]'));await click(button('Return to main lesson'));expect(button('Cancel')).toBe(document.activeElement);await click(button('Cancel'));expect(el.querySelector('[data-board-editor] input').value).toBe('Imported board');await click(button('Return to main lesson'));await click(button('Use main lesson'));expect(el.querySelector('[data-board-editor] input').value).toBe('Original board');expect(el.textContent).toContain('Board language: English');});
 it('drops imported context when the main lesson changes',async()=>{await render(api.LessonBoardSetup);await importFile(exportBoardFile(makeBoard(),source,'Spanish'));await click(el.querySelector('[data-open-board-file]'));await render(api.LessonBoardSetup,{inputText:'A different main lesson with enough text to generate a new board.'});expect(el.textContent).toContain('Board language: English');expect(el.querySelector('[data-board-editor]')).toBeNull();});
 it('replaces a saved copy in a full library only after confirmation',async()=>{for(let i=0;i<4;i++)boardStorage.saveBoard(localStorage,source,'English',{...makeBoard(),title:'Saved '+i});await render(api.LessonBoardSetup);await click(button('Generate another board'));const before=localStorage.getItem(boardStorage.libraryKey(source,'English'));await click(el.querySelector('[data-replace-saved="1"]'));expect(localStorage.getItem(boardStorage.libraryKey(source,'English'))).toBe(before);await click(button('Cancel'));expect(localStorage.getItem(boardStorage.libraryKey(source,'English'))).toBe(before);await click(el.querySelector('[data-replace-saved="1"]'));await click(button('Replace saved copy'));const boards=boardStorage.readLibrary(localStorage,source,'English');expect(boards).toHaveLength(4);expect(boards.some(board=>board.title==='Saved 2')).toBe(false);expect(boards[0].title).toBe(makeBoard().title);});
 it('does not overwrite a different copy after another tab changes the library',async()=>{boardStorage.saveBoard(localStorage,source,'English',{...makeBoard(),title:'Saved'});await render(api.LessonBoardSetup);await click(button('Generate another board'));await click(el.querySelector('[data-replace-saved="0"]'));boardStorage.removeBoard(localStorage,source,'English',0);boardStorage.saveBoard(localStorage,source,'English',{...makeBoard(),title:'Another tab'});await click(button('Replace saved copy'));expect(el.textContent).toContain('changed in another tab');expect(boardStorage.readLibrary(localStorage,source,'English')[0].title).toBe('Another tab');});
 it('offers an explicit resume action with a read-only progress description',async()=>{await render(api.LessonBoardSetup);await click(button('Generate lesson board'));await click(button('Play solo'));await click(el.querySelector('[data-board-move="heater"]'));await change('[data-board-choice]','1');await click(el.querySelector('[data-board-submit]'));await click(button('Back to board setup'));expect(button('Resume solo board')).toBeTruthy();expect(el.querySelector('[data-solo-resume]').textContent).toContain('Concepts explored: 1');const before=sessionStorage.getItem(boardStorage.soloStorageKey(makeBoard(),'app','u'));await click(button('Resume solo board'));expect(el.textContent).toContain('Location explored');expect(sessionStorage.getItem(boardStorage.soloStorageKey(makeBoard(),'app','u'))).toBe(before);});
 it('shows only learners without a confirmed response in the teacher waiting list',async()=>{const d=data();Object.assign(run(d),e.merge(run(d),e.begin(d.escapeRoomState.board,run(d),'heater')));step(d).answers.u={value:'1',correct:true};await render(api.LessonBoardTeacher,{sessionData:d});const waiting=el.querySelector('[data-board-awaiting]');expect(waiting.textContent).toContain('Sky');expect(waiting.textContent).not.toContain('Rowan');await render(api.LessonBoardStudent,{sessionData:d});expect(el.querySelector('[data-board-awaiting]')).toBeNull();});
});

describe('Nested dismissal and imported generation',()=>{
 const file=async()=>{const text=exportBoardFile(makeBoard(),'Included lesson. '+source,'Spanish');await act(async()=>{const input=el.querySelector('[data-import-board]');Object.defineProperty(input,'files',{configurable:true,value:[{size:text.length,text:async()=>text}]});input.dispatchEvent(new Event('change',{bubbles:true}));});};
 it('cancels a file review with Escape without closing the setup dialog',async()=>{const close=vi.fn();await render(api.LessonBoardSetup,{onClose:close});await file();const heading=el.querySelector('[data-board-file-review] h3');heading.focus();await act(async()=>heading.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(close).not.toHaveBeenCalled();expect(el.querySelector('[data-board-file-review]')).toBeNull();expect(el.querySelector('[role="dialog"]')).toBeTruthy();});
 it('cancels a saved-copy confirmation with Escape without closing setup',async()=>{boardStorage.saveBoard(localStorage,source,'English',{...makeBoard(),title:'Saved'});const close=vi.fn();await render(api.LessonBoardSetup,{onClose:close});await click(button('Generate another board'));await click(el.querySelector('[data-replace-saved="0"]'));await act(async()=>button('Cancel').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(close).not.toHaveBeenCalled();expect(button('Replace saved copy')).toBeUndefined();expect(boardStorage.readLibrary(localStorage,source,'English')[0].title).toBe('Saved');});
 it('uses the included source and language for subsequent generation',async()=>{const ai=vi.fn(base.callGemini);await render(api.LessonBoardSetup,{callGemini:ai});await file();await click(el.querySelector('[data-open-board-file]'));await click(button('Generate another board'));expect(ai).toHaveBeenCalledTimes(1);expect(ai.mock.calls[0][0]).toContain('Included lesson. '+source);expect(ai.mock.calls[0][0]).toContain('Spanish');});
});
