import { describe, it, expect, vi } from 'vitest';
import { createRequire } from 'node:module';
import * as e from '../lesson_board_engine.js';
import * as s from '../lesson_board_storage.js';
const require=createRequire(import.meta.url),{makeBoard,source}=require('../dev-tools/fixtures/lesson_board.cjs');
const request=(run,kind,targetId,value='',extra={})=>({attemptId:'attempt',turn:run.turn,requestId:e.identity('action'),kind,targetId,value,...extra});
const context={attemptId:'attempt',active:true,paused:false};
const answer=(board,run,uid='solo',value=e.solution(board.locations.find(n=>n.id===e.stepOf(run).targetId)))=>e.merge(run,e.processAction(board,run,request(run,'answer',e.stepOf(run).targetId,value),uid,context));
const explore=(board,run,id)=>{let next=e.merge(run,e.begin(board,run,id));next=answer(board,next);return e.merge(next,e.resolve(board,next,{solo:{}}));};
const next=(board,run)=>e.merge(run,e.advance(board,run));
const memory=()=>{const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};};
describe('Generated lesson board validation',()=>{
 it('accepts a complete board and strips arbitrary AI fields',()=>{const b=makeBoard();b.script='untrusted';b.locations[0].html='<script>';expect(e.validateBoard(b,source)).toEqual([]);expect(e.prepareBoard(b,source)).not.toHaveProperty('script');expect(e.prepareBoard(b,source).locations[0]).not.toHaveProperty('html');});
 it.each([null,[],{}, {concepts:{}},{...makeBoard(),concepts:{}},{...makeBoard(),resources:null}])('rejects malformed data without crashing %#',b=>expect(e.validateBoard(b,source).length).toBeGreaterThan(0));
 it.each(['quote','cycle-island','resource-shortage','duplicate-edge','unknown-edge','duplicate-id','reserved-id','invalid-control','invalid-order','zero-reward','unknown-effect','start-shortcut','unused-concept','oversize'])('rejects invalid %s',kind=>{const b=makeBoard();if(kind==='quote')b.locations[0].sourceQuote='Outside fact.';if(kind==='cycle-island')b.edges=b.edges.filter(edge=>!edge.includes('weather'));if(kind==='resource-shortage')b.locations.forEach(n=>n.reward=[1,0]);if(kind==='duplicate-edge')b.edges.push(b.edges[0].slice().reverse());if(kind==='unknown-edge')b.edges[0][0]='missing';if(kind==='duplicate-id')b.projects[0].id='heater';if(kind==='reserved-id')b.locations[0].id='constructor';if(kind==='invalid-control')b.locations[1].controls[0].answer=9;if(kind==='invalid-order')b.locations[5].order=[0,0,1,2];if(kind==='zero-reward')b.locations[0].reward=[0,0];if(kind==='unknown-effect')b.projects[0].effect={kind:'execute'};if(kind==='start-shortcut')b.projects[0].effect.targetId='heater';if(kind==='unused-concept')b.concepts.push({id:'extra',name:'Extra'});if(kind==='oversize')b.mission='x'.repeat(33000);expect(e.validateBoard(b,source).length).toBeGreaterThan(0);});
 it('uses one bounded repair with validation feedback and retains lesson/language',async()=>{const provider=vi.fn().mockResolvedValueOnce('{}').mockResolvedValueOnce(JSON.stringify(makeBoard())),stage=vi.fn();expect(await e.generateBoard(provider,source,{language:'Spanish',seed:'example'},stage)).toEqual(e.prepareBoard(makeBoard(),source));expect(provider).toHaveBeenCalledTimes(2);expect(provider.mock.calls[1][0]).toContain('Validation errors');expect(provider.mock.calls[1][0]).toContain('Spanish');expect(provider.mock.calls[1][0]).toContain(source);expect(stage.mock.calls.flat()).toEqual(['generating','repairing']);});
 it.each([null,'',{},'x'.repeat(100001)])('stops for empty or unusable provider output %#',async value=>{const provider=vi.fn().mockResolvedValue(value);await expect(e.generateBoard(provider,source)).rejects.toThrow('could not be validated');expect(provider).toHaveBeenCalledTimes(1);});
 it('does not loop on failure or invent a board when source is insufficient',async()=>{const provider=vi.fn().mockRejectedValue(Error('offline'));await expect(e.generateBoard(provider,source)).rejects.toThrow('offline');expect(provider).toHaveBeenCalledTimes(1);await expect(e.generateBoard(provider,'short')).rejects.toThrow('40 characters');});
});
describe('Deterministic shared construction game',()=>{
 it.each([[0,1],[0,2],[1,2]])('completes with project pair %s, %s', (a,b)=>{const board=makeBoard();let run=e.emptyRun();for(const node of board.locations){if(e.derive(board,run).complete)break;if(e.stepOf(run).phase==='review')run=next(board,run);run=explore(board,run,node.id);}for(const index of [a,b]){run=next(board,run);run=e.merge(run,e.begin(board,run,board.projects[index].id));}const p=e.derive(board,run);expect(p.complete).toBe(true);expect(p.built).toEqual([board.projects[a].id,board.projects[b].id]);expect(p.balance.every(v=>v>=0)).toBe(true);expect(p.performance.solo).toEqual({answered:8,correct:8});});
 it('does not expose distant locations or unaffordable constructions',()=>{const b=makeBoard(),r=e.emptyRun();expect(e.targets(b,r).map(n=>n.id)).toEqual(['heater','cloud']);expect(()=>e.begin(b,r,'weather')).toThrow('no longer available');expect(()=>e.begin(b,r,'research')).toThrow();});
 it('gives a built shortcut a real effect on available routes',()=>{const b=makeBoard();let r=explore(b,e.emptyRun(),'heater');r=next(b,r);r=explore(b,r,'cloud');r=next(b,r);expect(e.targets(b,r).some(n=>n.id==='sequence')).toBe(false);r=e.merge(r,e.begin(b,r,'bridge'));expect(e.derive(b,r).opened).toContain('sequence');r=next(b,r);expect(e.targets(b,r).some(n=>n.id==='sequence')).toBe(true);});
 it('applies yield only to later successful locations and awards once',()=>{const b=makeBoard();let r=explore(b,e.emptyRun(),'heater');r=next(b,r);r=explore(b,r,'cloud');r=next(b,r);r=e.merge(r,e.begin(b,r,'research'));const before=e.derive(b,r);r=next(b,r);r=explore(b,r,'river');const after=e.derive(b,r);expect(after.balance[0]-before.balance[0]).toBe(3);expect(e.derive(b,r)).toEqual(after);r=next(b,r);expect(()=>e.begin(b,r,'heater')).toThrow();expect(()=>e.begin(b,r,'research')).toThrow();});
 it('allows unsuccessful activities to be retried without resource loss',()=>{const b=makeBoard();let r=e.merge(e.emptyRun(),e.begin(b,e.emptyRun(),'heater'));r=answer(b,r,'solo','0');r=e.merge(r,e.resolve(b,r,{solo:{}}));expect(e.derive(b,r).balance).toEqual([0,0]);expect(e.derive(b,r).visited).toEqual([]);r=next(b,r);r=explore(b,r,'heater');expect(e.derive(b,r).performance.solo).toEqual({answered:2,correct:1});expect(e.derive(b,r).visited).toEqual(['heater']);});
 it('counts only submitted roster responses, not absent learners or outsiders',()=>{const b=makeBoard();let r=e.merge(e.emptyRun(),e.begin(b,e.emptyRun(),'heater'));r=answer(b,r,'a','1');r=answer(b,r,'b','0');r=answer(b,r,'outsider','0');r=e.merge(r,e.resolve(b,r,{a:{},b:{},absent:{}}));expect(e.stepOf(r).result).toEqual({success:true,marks:{a:true,b:false}});expect(e.derive(b,r).performance).not.toHaveProperty('absent');});
 it('does not resolve before at least one confirmed response',()=>{const b=makeBoard(),r=e.merge(e.emptyRun(),e.begin(b,e.emptyRun(),'heater'));expect(()=>e.resolve(b,r,{a:{}})).toThrow('at least one');});
 it('deduplicates actions, keeps first response, and permits proposal revisions',()=>{const b=makeBoard();let r=e.emptyRun();const vote=request(r,'vote','heater');r=e.merge(r,e.processAction(b,r,vote,'a',context));expect(e.processAction(b,r,vote,'a',context)).toEqual({});r=e.merge(r,e.processAction(b,r,request(r,'vote','cloud'),'a',context));expect(e.stepOf(r).votes.a).toBe('cloud');r=e.merge(r,e.begin(b,r,'heater'));r=answer(b,r,'a','0');r=answer(b,r,'a','1');expect(e.stepOf(r).answers.a).toEqual({value:'0',correct:false});});
 it.each([{turn:9},{turn:0.5},{attemptId:'old'},{requestId:'constructor'},{targetId:'constructor'},{value:'essay'},{kind:'build'},{extra:true}])('ignores malformed or stale inputs %#',extra=>{const b=makeBoard(),r=e.emptyRun();expect(e.processAction(b,r,request(r,'vote','heater','',extra),'a',context)).toEqual({});});
 it.each([{active:false},{paused:true}])('acknowledges closed actions without mutating gameplay %#',condition=>{const b=makeBoard(),r=e.emptyRun(),patch=e.processAction(b,r,request(r,'vote','heater'),'a',{...context,...condition});expect(Object.keys(patch)).toEqual(['steps.t0.seen.a']);});
 it.each(['','10','-1','1,0','0,','00'])('does not grade malformed choice values as wrong: %s',value=>expect(e.validValue(makeBoard().locations[0],value)).toBe(false));
 it('rejects malformed sequence/settings values and keeps a non-solution initial order',()=>{const b=makeBoard();expect(e.validValue(b.locations[5],'0,0,1,2')).toBe(false);expect(e.validValue(b.locations[1],',0')).toBe(false);expect(e.initialDraft(b.locations[5])).not.toBe(e.solution(b.locations[5]));});
 it('starts every live restart with a new attempt and no game results',()=>{const b=makeBoard(),a=e.createSession(b,'host',{a:{}}),c=e.createSession(b,'host',{a:{},b:{}});expect(c.attemptId).not.toBe(a.attemptId);expect(c.teams).toEqual({a:'All',b:'All'});expect(e.runOf(c)).toEqual(e.emptyRun());});
 it('protects patch paths from prototype pollution',()=>expect(()=>e.merge({}, {'steps.__proto__.bad':true})).toThrow('Unsafe'));
});
describe('Board replay and library',()=>{
 it('separates lessons/languages, deduplicates saves and never evicts a fifth board',()=>{const storage=memory();for(let i=0;i<4;i++)s.saveBoard(storage,source,'English',{...makeBoard(),title:'Board '+i});expect(s.readLibrary(storage,source,'English')).toHaveLength(4);expect(()=>s.saveBoard(storage,source,'English',makeBoard())).toThrow('Four');expect(s.readLibrary(storage,source,'Spanish')).toEqual([]);expect(s.saveBoard(storage,source,'English',{...makeBoard(),title:'Board 0'})).toHaveLength(4);expect(s.removeBoard(storage,source,'English',0)).toHaveLength(3);});
 it('keeps corrupt saves intact',()=>{const storage=memory(),key=s.libraryKey(source,'English');storage.setItem(key,'broken');expect(()=>s.saveBoard(storage,source,'English',makeBoard())).toThrow('kept');expect(storage.getItem(key)).toBe('broken');});
 it('restores a solo run by replaying legal moves and exact board identity',()=>{const b=makeBoard();let r=explore(b,e.emptyRun(),'heater');r=next(b,r);r=e.merge(r,e.begin(b,r,'cloud'));const raw=JSON.stringify({version:1,board:JSON.stringify(b),run:r});const restored=s.restoreSolo(b,raw);expect(e.derive(b,restored)).toEqual(e.derive(b,r));expect(e.stepOf(restored).targetId).toBe('cloud');expect(()=>s.restoreSolo({...b,title:'different'},raw)).toThrow('could not be restored');});
 it.each(['broken','x'.repeat(130001),JSON.stringify({version:2})])('rejects invalid solo saves %#',raw=>expect(()=>s.restoreSolo(makeBoard(),raw)).toThrow('could not be restored'));
});

it('rejects a saved construction with a corrupted result',()=>{const b=makeBoard();let r=explore(b,e.emptyRun(),'heater');r=next(b,r);r=explore(b,r,'cloud');r=next(b,r);r=e.merge(r,e.begin(b,r,'bridge'));e.stepOf(r).result.success=false;expect(()=>s.restoreSolo(b,JSON.stringify({version:1,board:JSON.stringify(b),run:r}))).toThrow('could not be restored');});
