import {beforeEach,describe,it,expect} from 'vitest';
import {loadTool,renderTool,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
let model,grid;
beforeEach(()=>{resetStemLab();loadTool('stem_lab/stem_tool_renewables.js','renewablesLab');model=window.StemLab.renewablesEnergyModel;grid=window.StemLab.renewablesMicrogridModel;});
const close=(a,b)=>expect(Math.abs(a-b)).toBeLessThanOrEqual(Math.max(Math.abs(a),Math.abs(b),1e-20)*1e-8);
function balance(run){const p=model.pathway(run),b=p.budget;expect(p.nodes.map(n=>n.id)).toEqual(['resource','converter','generator']);expect(p.nodes.every(n=>Number.isFinite(n.value)&&n.value>=0)).toBe(true);expect(b.segments.every(s=>Number.isFinite(s.value)&&s.value>=0)).toBe(true);close(b.segments.reduce((a,s)=>a+s.value,0),b.total);expect(p.nodes[0].value).toBe(run.available);expect(p.nodes[2].value).toBe(run.power);expect(p.nodes[0].unit).toBe('kW');expect(p.nodes[2].unit).toBe('kW');if(b.total){close(b.segments.reduce((a,s)=>a+s.share,0),1);expect(b.segments.every(s=>s.share>=0&&s.share<=1+1e-9)).toBe(true);}else expect(b.segments.every(s=>s.share===null)).toBe(true);return p;}
describe('Interactive energy pathway and balance graphic',()=>{
 for(const id of ['solarPv','wind','hydro','geothermal','solarThermal','wave','tidal','biomass','storage'])it(id+' reconciles every minute in both native scenarios and the steady workbench',()=>{for(const minute of [0,30,60,90,120])balance(model.simulate(id,{},minute));for(const profile of model.programs[id])for(const row of model.scenario(id,{},profile.id).rows)balance(row.run);});
 it('partitions known PV input once without counting DC power again',()=>{const p=balance(model.simulate('solarPv',{irradiance:1000,incidence:0,area:20,efficiency:20}));expect(p.nodes.map(n=>n.value)).toEqual([20,4,3.84]);p.budget.segments.forEach((s,i)=>close(s.value,[3.84,16,.16][i]));expect(p.budget.segments.map(s=>s.label)).toEqual(['AC electricity','Not converted to DC','Inverter loss']);expect(p.budget.total).toBe(20);});
 it('exposes a percentage instead of inventing intermediate power in combined models',()=>{for(const id of ['hydro','geothermal','wave']){const run=model.simulate(id,{}),p=balance(run);expect(p.nodes[1].unit).toBe('%');expect(p.nodes[1].label).toBe('Combined conversion');expect(p.nodes[1].value).toBe(run.extra.efficiency*100);expect(p.nodes[1].note).toContain('no separate intermediate power');expect(p.budget.segments).toHaveLength(2);}});
 it('accounts for protective shutdown as unextracted stream power',()=>{const p=balance(model.simulate('wind',{speed:25}));expect(p.budget.total).toBeGreaterThan(0);expect(p.nodes[1].value).toBe(0);expect(p.nodes[2].value).toBe(0);expect(p.budget.segments[1].value).toBe(p.budget.total);expect(p.budget.segments[2].value).toBe(0);expect(p.budget.empty).toBe(false);});
 it('includes the generator rating in the downstream remainder',()=>{const run=model.simulate('wind',{speed:20,radius:80,rating:500}),p=balance(run);expect(p.budget.segments[0].value).toBe(500);expect(p.budget.segments[2].value).toBeGreaterThan(500);close(p.budget.segments[1].value+p.budget.segments[2].value,run.loss);});
 it('shows a true empty balance and undefined shares when the resource is absent',()=>{const p=balance(model.simulate('solarPv',{irradiance:0}));expect(p.budget.empty).toBe(true);expect(p.budget.total).toBe(0);expect(p.budget.segments.every(s=>s.value===0&&s.share===null)).toBe(true);});
 it('retains finite proportional shares for tiny positive resource values',()=>{const p=balance(model.simulate('solarPv',{irradiance:1e-12,incidence:0}));expect(p.budget.empty).toBe(false);expect(p.nodes[2].value).toBeGreaterThan(0);expect(p.budget.segments.every(s=>Number.isFinite(s.share))).toBe(true);});
 it('preserves tidal-direction symmetry in all chart segments',()=>{const a=balance(model.simulate('tidal',{speed:2})),b=balance(model.simulate('tidal',{speed:-2}));expect(a).toEqual(b);});
 it('separates battery power from stored energy at the half-cycle and endpoint',()=>{const mid=balance(model.simulate('storage',{roundtrip:100,initial:0},60)),end=balance(model.simulate('storage',{roundtrip:100,initial:0},120));expect(mid.nodes.map(n=>n.unit)).toEqual(['kW','kWh','kW']);expect(mid.nodes.map(n=>n.value)).toEqual([0,50,50]);expect(mid.budget.total).toBe(50);expect(mid.budget.segments.map(s=>s.value)).toEqual([0,50,0]);expect(end.nodes.map(n=>n.value)).toEqual([0,0,0]);expect(end.budget.segments.map(s=>s.value)).toEqual([50,0,0]);expect(end.budget.unit).toBe('kWh');expect(end.budget.scope).toBe('accumulated-energy');});
 it('includes initial battery energy before any charging occurs',()=>{const p=balance(model.simulate('storage',{capacity:100,initial:50},0));expect(p.budget.total).toBe(50);expect(p.budget.initial).toBe(50);expect(p.budget.acceptedCharge).toBe(0);expect(p.budget.segments.map(s=>s.value)).toEqual([0,50,0]);expect(p.nodes[0].value).toBe(50);});
 it('reconciles native storage losses throughout a complete cycle',()=>{const p=balance(model.simulate('storage',{initial:0,roundtrip:81,power:50},120));close(p.budget.total,50);close(p.budget.segments[0].value,40.5);close(p.budget.segments[1].value,0);close(p.budget.segments[2].value,9.5);});
 it('uses actual battery-bank accounting from microgrid dispatch, including an absent bank',()=>{for(const batteryUnits of [0,1,3]){const study=grid.simulate({source:'solarPv',profileId:'clouds',batteryUnits,battery:{initial:50},grid:'outage',demand:4});for(const row of study.rows){balance(row.sourceRun);const p=balance(row.batteryRun);close(p.budget.total,study.initialStored+row.energy.charge);expect(p.nodes[1].value).toBe(row.stored);expect(p.nodes[2].value).toBe(row.discharge);if(batteryUnits===0)expect(p.budget.empty).toBe(true);}}});
 it('does not mutate the simulation and rejects absent or unknown runs',()=>{const run=model.simulate('biomass',{}),before=JSON.stringify(run);model.pathway(run);expect(JSON.stringify(run)).toBe(before);expect(model.pathway(null)).toBeNull();expect(model.pathway({id:'unknown'})).toBeNull();});
 it('renders interactive stage controls with energy-budget values',()=>{const html=renderTool('renewablesLab',{renewablesLab:{view:'energy3d',energyLab:{selected:'solarPv',settings:{solarPv:{irradiance:1000,incidence:0}}}}});for(const text of ['Interactive energy pathway','Trace Sunlight','Trace PV array','Trace Inverter','Energy balance graphic','Where the input power goes','Not converted to DC','Inverter loss'])expect(html).toContain(text);expect(html).not.toContain('NaN');expect(html).not.toContain('failed to render');});
 it('renders an empty battery balance without undefined percentages',()=>{const html=renderTool('renewablesLab',{renewablesLab:{view:'energy3d',energyLab:{selected:'storage',settings:{storage:{initial:0}},phases:{storage:0}}}});expect(html).toContain('Energy balance so far');expect(html).toContain('No starting energy or accepted charging');expect(html).toContain('Share unavailable');expect(html).not.toContain('NaN');});
});
