import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
const s=readFileSync('stem_lab/stem_tool_solarsystem.js','utf8');
const {save,signature}=new Function(s.slice(s.indexOf('  function transferDebriefSignature('),s.indexOf('  var _stableViewTypes'))+';return {save:saveTransferDebrief,signature:transferDebriefSignature};')();
const snapshot={route:'earth-mars',from:'Earth',to:'Mars',planet:'Mars',offset:30,days:258.9,referenceGap:0,testGap:0.78888045,timestamp:100,missionStartedAt:50};
const note={snapshot,changed:'destination',explanation:'The shifted destination misses the same path by 0.789 AU.',question:'Would a negative angle make the same gap?'};
const data=(n=note)=>({transferDebriefs:{'earth-mars':n},journalEntries:[{title:'Other evidence',observation:'Preserve me'}],marsMission:{startedAt:50,prediction:'miss'}});
describe('captured transfer explanation',()=>{
 it('saves captured numbers and student writing without mutating existing evidence',()=>{const d=data(),before=JSON.stringify(d),next=save(d,'earth-mars',200);expect(JSON.stringify(d)).toBe(before);expect(next.marsMission).toBe(d.marsMission);expect(next.journalEntries[0]).toBe(d.journalEntries[0]);expect(next.journalEntries[1]).toMatchObject({source:'experiment',planet:'Mars',missionStartedAt:50,reasoning:note.explanation,question:note.question,transferComparison:snapshot});expect(next.journalEntries[1].observation).toContain('+30° gap was 0.789 AU');});
 it('makes repeated saves idempotent and revisions update the same captured record',()=>{const saved=save(data(),'earth-mars',200);expect(save(saved,'earth-mars',300)).toBe(saved);const edited={...saved,transferDebriefs:{'earth-mars':{...saved.transferDebriefs['earth-mars'],explanation:'My revised explanation uses both captured arrival gaps.'}}};expect(signature(edited.transferDebriefs['earth-mars'])).not.toBe(edited.transferDebriefs['earth-mars'].savedSignature);const next=save(edited,'earth-mars',400);expect(next.journalEntries).toHaveLength(2);expect(next.journalEntries[1].timestamp).toBe(200);expect(next.journalEntries[1].reasoning).toContain('revised');});
 it('keeps a new capture as a separate experiment and retains prior writing',()=>{const saved=save(data(),'earth-mars',200),next=save({...saved,transferDebriefs:{'earth-mars':{...note,snapshot:{...snapshot,offset:-30,timestamp:300}}}},'earth-mars',400);expect(next.journalEntries).toHaveLength(3);expect(next.journalEntries[1].transferComparison.offset).toBe(30);expect(next.journalEntries[2].transferComparison.offset).toBe(-30);});
 it('requires a valid nonzero comparison, identified variable, and both writing fields',()=>{for(const patch of [{snapshot:null},{changed:'path'},{explanation:'short'},{question:'short'},{snapshot:{...snapshot,offset:0}},{snapshot:{...snapshot,days:NaN}},{snapshot:{...snapshot,testGap:-1}},{snapshot:{...snapshot,route:'mars-earth'}},{snapshot:{...snapshot,from:'Mars'}}]){const d=data({...note,...patch});expect(save(d,'earth-mars',200)).toBe(d);}});
 it('restores a missing journal record even if a save marker remains',()=>{const saved=save(data(),'earth-mars',200);saved.journalEntries=[];expect(save(saved,'earth-mars',300).journalEntries).toHaveLength(1);});
});
