import {describe,it,expect} from 'vitest';import {readFileSync} from 'node:fs';
const s=readFileSync('stem_lab/stem_tool_solarsystem.js','utf8'),helpers=s.slice(s.indexOf('  function marsFollowUpHistory('),s.indexOf('  function marsFollowUpOutcome('))+s.slice(s.indexOf('  function transferExperimentHistory('),s.indexOf('  function transferDebriefSignature('));const history=new Function(helpers+';return marsFollowUpHistory;')();
const mission={startedAt:100,completedAt:200};const entry=(id,launch,stamp,patch={})=>({source:'experiment',transferComparisonId:id,observation:'Saved comparison',transferComparison:{route:'earth-mars',missionStartedAt:100,offset:60,days:258.9,referenceGap:0,testGap:1.524,timestamp:stamp,followUp:{launchedAt:launch,offset:60,prediction:'Prediction at launch'},...patch}});
describe('Mars follow-up history',()=>{
 it('groups saved captures by launch and retains the latest capture from each',()=>{const a=entry('a',300,310),b=entry('b',300,320),c=entry('c',400,410),entries=[a,c,b],before=JSON.stringify(entries);expect(history(mission,entries)).toEqual([c,b]);expect(JSON.stringify(entries)).toBe(before);});
 it('orders launches by launch time even if an older capture is saved later',()=>{const older=entry('a',300,600),newer=entry('b',400,500);expect(history(mission,[older,newer])).toEqual([newer,older]);});
 it('ignores other missions, generic experiments and malformed launch links',()=>{const bad=[entry('a',300,400,{missionStartedAt:99}),entry('b',300,400,{followUp:null}),entry('c',99,400),entry('d',300,299),entry('e',300,400,{offset:-60}),entry('f',300,400,{followUp:{launchedAt:300,offset:60,prediction:' '}}),entry('g',300,400,{route:'mars-earth'})];expect(history(mission,bad)).toEqual([]);expect(history({...mission,completedAt:null},[entry('ok',300,400)])).toEqual([]);});
 it('retains repeated equal-offset launches as distinct investigations',()=>{expect(history(mission,[entry('a',300,310),entry('b',400,410)])).toHaveLength(2);});
});
