import { beforeAll, beforeEach, afterEach, describe, it, expect, vi } from 'vitest';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { readFileSync } from 'node:fs';
import { loadAlloModule } from './setup.js';
const require=createRequire(import.meta.url), React=require(resolve('desktop/web-app/node_modules/react'));
const {createRoot}=require(resolve('desktop/web-app/node_modules/react-dom/client')),{act}=require(resolve('desktop/web-app/node_modules/react-dom/test-utils'));
let api,audio,root,host;
const applied=()=>({id:'a1',type:'applied-challenge',data:{title:'A challenge',scope:'compact',brief:{lockedLessonFacts:['A fact'],factVerified:true},workspace:{response:'My response'},sourceExcerpt:'PRIVATE SOURCE'}});
const memory=()=>({id:'m1',type:'memory-aid',data:{cards:[{id:'c1',target:'Gravity',essentialFacts:['Attraction'],factVerified:false,aiExample:'Pull',studentDraft:'My cue',visualImage:'data:image/png;base64,AAAA',visualAlt:'',practiceAttempts:[{response:'PRIVATE ATTEMPT'}]}]}});
beforeAll(()=>{global.React=window.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;['karaoke_audio_store_module.js','memory_aid_module.js','applied_challenge_module.js','studio_response_module.js','resource_read_aloud_module.js'].forEach(loadAlloModule);api=window.AlloModules.StudioResponse;audio=window.AlloModules.ResourceReadAloud;});
beforeEach(()=>{sessionStorage.clear();});
afterEach(()=>{if(root)act(()=>root.unmount());root=null;host?.remove();vi.useRealTimers();vi.unstubAllGlobals();delete window.__alloGetReadAloudAudioBridge;});
function mount(Component,props={}){host=document.createElement('div');document.body.appendChild(host);root=createRoot(host);act(()=>root.render(React.createElement(Component,props)));}
const button=label=>[...host.querySelectorAll('button')].find(b=>b.textContent===label);
async function click(label){await act(async()=>button(label).click());}
function learner(r,extra={}){let saved;function Harness(){const [responses,set]=React.useState({});saved=responses;return React.createElement(api.Boundary,{View:r.type==='memory-aid'?window.AlloModules.MemoryAidView:window.AlloModules.AppliedChallengeView,generatedContent:r,isTeacherMode:false,studentResponses:responses,onResponseChange:(id,studio)=>set(p=>({...p,[id]:{studio}})),allowRuntimeAi:false,activeProfileId:'p1',...extra});}mount(Harness);return()=>saved;}
async function write(node,value){await act(async()=>{Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));});}
describe('studio text recovery',()=>{
 it.each([memory,applied])('round-trips writing without teacher sources or private evidence',factory=>{const r=factory(),response=api.responseFromData(r.type,r.data),data=api.backup(r,response),encoded=JSON.stringify(data);expect(encoded).not.toContain('PRIVATE');expect(encoded).not.toContain('data:image');expect(api.readBackup(r,JSON.parse(encoded))).toEqual(api.toSubmission(r,response).data);expect(()=>api.readBackup({...r,id:'different'},data)).toThrow();});
 it('rejects malformed backup structures rather than clearing writing',()=>{for(const factory of [memory,applied]){const r=factory(),value=api.backup(r,api.responseFromData(r.type,r.data));expect(()=>api.readBackup(r,{...value,studio:{}})).toThrow();expect(()=>api.readBackup(r,{...value,studio:{...value.studio,schemaVersion:9}})).toThrow();if(r.type==='memory-aid'){expect(()=>api.readBackup(r,{...value,studio:{schemaVersion:1,cards:[{id:'unknown',studentDraft:'X'}]}})).toThrow();expect(()=>api.readBackup(r,{...value,studio:{schemaVersion:1,cards:[{id:'c1',studentDraft:42}]}})).toThrow();}else{expect(()=>api.readBackup(r,{...value,studio:{schemaVersion:1,workspace:'Invalid'}})).toThrow();expect(()=>api.readBackup(r,{...value,studio:{schemaVersion:1,workspace:{response:12}}})).toThrow();expect(()=>api.readBackup(r,{...value,studio:{schemaVersion:1,workspace:{},criteriaCheck:{'criterion-1':null}}})).toThrow();}}});
 it('only downloads backups that fit the UTF-8 restore limit',()=>{const r=applied(),rows=Array.from({length:24},(_,i)=>({id:String(i),claim:'🌊'.repeat(6000),evidence:'🌊'.repeat(6000),tradeoff:'🌊'.repeat(6000),note:'🌊'.repeat(6000)}));expect(()=>api.serializeBackup(r,{workspace:{response:'Keep my work'},evidenceLedger:rows})).toThrow(RangeError);const valid=api.serializeBackup(r,{workspace:{response:'Réponse عربية'}});expect(new Blob([valid]).size).toBeLessThan(api.maxBackupBytes);expect(api.readBackup(r,JSON.parse(valid)).workspace.response).toBe('Réponse عربية');});
 it('preserves existing learner visuals when restoring a text backup',()=>{const r=memory(),prior=api.responseFromData(r.type,r.data);const backup=api.backup(r,prior);backup.studio.cards[0].studentDraft='Earlier writing';const restored=api.readBackup(r,backup,prior);expect(restored.cards[0].visualImage).toBe(prior.cards[0].visualImage);expect(restored.cards[0].studentDraft).toBe('Earlier writing');});
 it('offers retries only to actual learners and downloads a bounded backup',async()=>{const retry=vi.fn(),urls=[];vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});Object.defineProperty(URL,'createObjectURL',{configurable:true,value:vi.fn(blob=>{urls.push(blob);return 'blob:backup';})});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:vi.fn()});mount(api.Boundary,{View:()=>null,generatedContent:applied(),isTeacherMode:false,studentWorkStatus:'error',onRetrySave:retry,onResponseChange:vi.fn()});await click('Retry save');expect(retry).toHaveBeenCalledOnce();await click('Download my work');expect(urls[0].type).toBe('application/json');expect(host.textContent).toContain('does not submit');await act(async()=>root.render(React.createElement(api.Boundary,{View:()=>null,generatedContent:applied(),isTeacherMode:true,startInPreview:true})));expect(button('Retry save')).toBeUndefined();expect(button('Download my work')).toBeUndefined();vi.restoreAllMocks();});
 it('ignores a backup that finishes loading after leaving the resource',async()=>{const r=applied(),save=vi.fn();let release;mount(api.Boundary,{View:()=>null,generatedContent:r,isTeacherMode:false,onResponseChange:save});const input=host.querySelector('input[type=file]');Object.defineProperty(input,'files',{configurable:true,value:[{size:200,text:()=>new Promise(resolve=>release=resolve)}]});await act(async()=>input.dispatchEvent(new Event('change',{bubbles:true})));act(()=>root.unmount());root=null;await act(async()=>release(JSON.stringify(api.backup(r,{workspace:{response:'Old'}}))));expect(save).not.toHaveBeenCalled();});
 it('keeps newer typing when a backup file is still loading',async()=>{const r=applied(),save=vi.fn();let release;const props={View:()=>null,generatedContent:r,isTeacherMode:false,onResponseChange:save};mount(api.Boundary,props);const input=host.querySelector('input[type=file]');Object.defineProperty(input,'files',{configurable:true,value:[{size:200,text:()=>new Promise(resolve=>release=resolve)}]});await act(async()=>input.dispatchEvent(new Event('change',{bubbles:true})));await act(async()=>root.render(React.createElement(api.Boundary,{...props,studentResponses:{a1:{studio:{workspace:{response:'New typing'}}}}})));await act(async()=>release(JSON.stringify(api.backup(r,{workspace:{response:'Old'}}))));expect(save).not.toHaveBeenCalled();expect(host.textContent).toContain('Your current work has not changed.');});
 it('restores a downloaded response through the real learner response lane',async()=>{const r=applied(),save=vi.fn();mount(api.Boundary,{View:()=>null,generatedContent:r,isTeacherMode:false,onResponseChange:save});const input=host.querySelector('input[type=file]'),data=api.backup(r,{workspace:{response:'Restored answer'}});Object.defineProperty(input,'files',{configurable:true,value:[{size:200,text:async()=>JSON.stringify(data)}]});await act(async()=>input.dispatchEvent(new Event('change',{bubbles:true})));expect(save).toHaveBeenCalledWith(r.id,expect.objectContaining({workspace:{response:'Restored answer'}}));});
});
describe('actual host autosave recovery',()=>{
 function hostSave(storage,capture){let s=readFileSync('AlloFlowANTI.txt','utf8');s=s.slice(s.indexOf('  const [studentResponses, setStudentResponses] = useState({});'),s.indexOf('  const [generatedContent, _setGeneratedContent] = useState(null);'));s=s.replace('const isStudentWorkLoaded = useRef(false);','const isStudentWorkLoaded = useRef(true);');return new Function('React','storageDB','capture',`return function Host(){const {useState,useRef,useEffect,useCallback}=React;const isTeacherMode=false,showStudentEntry=false;const _alloShouldSuppressLearnerDeviceStorage=()=>false;${s};capture({setStudentResponses,studentWorkStatus,retryStudentWorkSave});return null;}`)(React,storage,capture);}
 it('treats a refused write as an error and retries current work',async()=>{vi.useFakeTimers();let current;const storage={set:vi.fn().mockResolvedValueOnce(false).mockResolvedValue(true)};mount(hostSave(storage,v=>current=v));await act(async()=>vi.advanceTimersByTimeAsync(1000));expect(current.studentWorkStatus).toBe('error');act(()=>current.setStudentResponses({a1:{studio:{workspace:{response:'Latest'}}}}));act(()=>current.retryStudentWorkSave());await act(async()=>vi.advanceTimersByTimeAsync(1000));expect(current.studentWorkStatus).toBe('saved');expect(storage.set.mock.lastCall[1].a1.studio.workspace.response).toBe('Latest');});
 it('serializes pending writes and ignores an old completion status',async()=>{vi.useFakeTimers();let current,release;const storage={set:vi.fn().mockImplementationOnce(()=>new Promise(resolve=>release=resolve)).mockResolvedValue(true)};mount(hostSave(storage,v=>current=v));await act(async()=>vi.advanceTimersByTimeAsync(1000));act(()=>current.setStudentResponses({a1:{answer:'New'}}));await act(async()=>vi.advanceTimersByTimeAsync(1000));expect(storage.set).toHaveBeenCalledTimes(1);await act(async()=>release(true));expect(storage.set).toHaveBeenCalledTimes(2);expect(storage.set.mock.lastCall[1]).toEqual({a1:{answer:'New'}});expect(current.studentWorkStatus).toBe('saved');});
});
describe('Applied focus mode',()=>{
 it('shows one step, moves keyboard focus, and retains writing across navigation',async()=>{const r=applied(),saved=learner(r);expect(button('Show all steps')).toBeTruthy();const visible=()=>[...host.querySelectorAll('textarea[id^="applied-workspace-"]')].filter(n=>!n.closest('[hidden]'));expect(visible()).toHaveLength(1);const first=visible()[0];await write(first,'First-step thinking');await click('Next');expect(document.activeElement).toBe(visible()[0]);expect(visible()[0].id).not.toBe(first.id);await click('Back');expect(visible()[0].value).toBe('First-step thinking');expect(JSON.stringify(saved())).toContain('First-step thinking');await click('Show all steps');expect(visible().length).toBeGreaterThan(1);});
 it('ignores malformed saved focus preferences',()=>{sessionStorage.setItem('allo-applied-focus:'+JSON.stringify(['p1','a1']),'null');expect(()=>learner(applied())).not.toThrow();expect(button('Show all steps')).toBeTruthy();});
 it('remembers the selected step for this profile but keeps preview navigation ephemeral',async()=>{const r=applied();learner(r);await click('Next');const id=document.activeElement.id;act(()=>root.unmount());root=null;host.remove();learner(r);expect(host.querySelector('#'+id).closest('[hidden]')).toBeNull();sessionStorage.clear();act(()=>root.unmount());root=null;host.remove();mount(api.Boundary,{View:window.AlloModules.AppliedChallengeView,generatedContent:r,isTeacherMode:true,startInPreview:true,allowRuntimeAi:false});await click('Next');expect(sessionStorage.length).toBe(0);});
});
describe('audio pacing and sharing review',()=>{
 function player(extra={}){const clips=[];vi.stubGlobal('Audio',class{constructor(){this.play=vi.fn(()=>Promise.resolve());this.pause=vi.fn();clips.push(this);}});window.__alloGetReadAloudAudioBridge=()=>({inspect:()=>({status:'ready',url:'blob:clip'})});mount(audio.Controls,{resource:memory(),...extra});return clips;}
 it('pauses and resumes a clip, then waits between fields without advancing',async()=>{const clips=player();await click('Read-along and clips');await act(async()=>host.querySelector('input[type=checkbox]').click());await click('Read reference aloud');await click('Pause reading');expect(clips[0].pause).toHaveBeenCalled();await click('Resume reading');expect(clips[0].play).toHaveBeenCalledTimes(2);await act(async()=>clips[0].onended());expect(button('Resume reading')).toBeTruthy();expect(clips).toHaveLength(1);await click('Resume reading');expect(clips).toHaveLength(2);await act(async()=>clips[1].onended());await click('Stop reading');expect(button('Resume reading')).toBeUndefined();expect(clips).toHaveLength(2);});
 it('can disable focus following and repeat only the current field',async()=>{const onActiveSegment=vi.fn(),clips=player({onActiveSegment});await click('Read-along and clips');await act(async()=>host.querySelectorAll('input[type=checkbox]')[1].click());await click('Read reference aloud');expect(onActiveSegment).not.toHaveBeenCalled();await click('Repeat this field');expect(clips).toHaveLength(2);await act(async()=>clips[1].onended());expect(button('Stop reading')).toBeUndefined();expect(clips).toHaveLength(2);});
 it('pauses device reading without saving learner audio',async()=>{const speech={speak:vi.fn(),pause:vi.fn(),resume:vi.fn(),cancel:vi.fn()};vi.stubGlobal('speechSynthesis',speech);vi.stubGlobal('SpeechSynthesisUtterance',class{constructor(text){this.text=text;}});mount(audio.LocalText,{text:'Private writing',voiceSpeed:0.8});await click('Read my writing');expect(speech.speak.mock.calls[0][0].rate).toBe(0.8);await click('Pause reading');expect(speech.pause).toHaveBeenCalledOnce();await click('Resume reading');expect(speech.resume).toHaveBeenCalledOnce();await click('Stop reading');expect(speech.cancel).toHaveBeenCalledOnce();});
 it('links a teacher review item to its editable facts',async()=>{mount(api.Boundary,{View:window.AlloModules.MemoryAidView,generatedContent:memory(),isTeacherMode:true,handleNoteUpdate:vi.fn(),allowRuntimeAi:false});const issues=audio.sharingReview(memory()).issues;expect(issues.some(i=>i.code==='facts')).toBe(true);expect(issues.some(i=>i.code==='description')).toBe(true);await act(async()=>{button('Check and verify lesson facts: Gravity').click();await new Promise(resolve=>setTimeout(resolve,5));});expect(button('Done editing')).toBeTruthy();expect(document.activeElement.dataset.studioReview).toBe('facts');});
 it('preserves translated placeholders in all three added locales',()=>{for(const locale of ['spanish_castilian','french','arabic']){const data=JSON.parse(readFileSync('lang/'+locale+'.js','utf8'));expect(data.studio_response.retry_save).toBeTruthy();expect(data.resource_read_aloud.pause_between).toBeTruthy();expect(data.studio_sharing.review_note).toBeTruthy();expect(data.applied_challenge.focus.progress).toContain('{current}');expect(data.applied_challenge.focus.progress).toContain('{total}');}});
});
