import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';

const WATER_CYCLE_PATHS = [
  'stem_lab/stem_tool_watercycle.js',
  'desktop/web-app/public/stem_lab/stem_tool_watercycle.js',
];

const STEM_MODULE_PATHS = [
  'stem_lab/stem_lab_module.js',
  'desktop/web-app/public/stem_lab/stem_lab_module.js',
];

describe('Water Cycle 3D Droplet Journey', () => {
  it('loads Three.js only when the learner selects the 3D view', () => {
    STEM_MODULE_PATHS.forEach((filePath) => {
      const source = readFileSync(filePath, 'utf8');

      expect(source).toContain("var wcNeedsThree = stemLabTool === 'waterCycle'");
      expect(source).toContain("labToolData.waterCycle.journeyView === '3d'");
      expect(source).toContain("labToolData.waterCycle && labToolData.waterCycle.journeyView");
    });
  });

  it('keeps the tested 2D journey engine mounted as the state authority', () => {
    WATER_CYCLE_PATHS.forEach((filePath) => {
      const source = readFileSync(filePath, 'utf8');

      expect(source).toContain("var journeyView = d.journeyView || '2d';");
      expect(source).toContain("opacity: journeyView === '2d' ? 1 : 0");
      expect(source).toContain('"data-render-mode": journeyView === \'2d\' ? \'visual\' : \'state-only\'');
      expect(source).toContain('"data-journey-state": d.journeyActive ? (d.journeyState || \'ocean\') : \'idle\'');
      expect(source).toContain('"data-watercycle-journey-3d": "true"');
      expect(source).toContain('ref: journey3dRef');
    });
  });

  it('provides a complete, lifecycle-safe, reduced-motion-aware scene', () => {
    WATER_CYCLE_PATHS.forEach((filePath) => {
      const source = readFileSync(filePath, 'utf8');

      expect(source).toContain('new THREE.WebGLRenderer');
      expect(source).toContain('new THREE.CatmullRomCurve3');
      expect(source).toContain('var stateCurves3d = {');
      expect(source).toContain('activeCurve3d.getPointAt(journeyProgress3d)');
      expect(source).toContain('syncJourneyRoute3d(state3d);');
      expect(source).toContain('canvasEl.dataset.journeyProgress = String(journeyProgress3d);');
      expect(source).toContain('new THREE.MeshPhysicalMaterial');
      expect(source).toContain('var stageTargets3d = {');
      expect(source).toContain("window.matchMedia('(prefers-reduced-motion: reduce)').matches");
      expect(source).toContain('canvasEl.dataset.rendered = \'true\';');
      expect(source).toContain('function cleanupJourney3d()');
      expect(source).toContain('renderer.dispose();');
      expect(source).toContain('if (resizeObserver3d) resizeObserver3d.disconnect();');
      expect(source).toContain('if (controls3d) controls3d.dispose();');
      expect(source).toContain('if (detached3d && !detached3d.isConnected && detached3d._wc3dCleanup)');
      expect(source).toContain('WebGL is unavailable on this device. Use the 2D Cycle view instead.');
      expect(source).toContain('"Return to 2D Cycle"');
      expect(source).toMatch(/: "Loading the 3D water journey\.\.\."\r?\n\s+\),\r?\n/);
      expect(source).toContain('canvasEl._wc3dResetCamera = function()');
      expect(source).toContain('canvasEl._wc3dResetCamera = null;');
      expect(source).toContain('"aria-label": "Resume guided camera"');
      expect(source).toContain('canvasEl._wc3dAdjustCamera = function(action)');
      expect(source).toContain('canvasEl._wc3dAdjustCamera = null;');
      expect(source).toMatch(/function cleanupJourney3d\(\) \{[\s\S]*?canvasEl\._wc3dAdjustCamera = null;\r?\n\s+\}/);
      expect(source).toContain('onKeyDown: handleJourney3dKey');
    });
  });

  it('exposes an accessible segmented view control and stage status', () => {
    WATER_CYCLE_PATHS.forEach((filePath) => {
      const source = readFileSync(filePath, 'utf8');

      expect(source).toContain('"aria-label": "Water Cycle visualization"');
      expect(source).toContain('"aria-pressed": journeyView === \'2d\'');
      expect(source).toContain('"aria-pressed": journeyView === \'3d\'');
      expect(source).toContain('"aria-live": "polite"');
      expect(source).toContain('illustrative scale');
      expect(source).toContain('Three-dimensional tracked water parcel');
      expect(source).toContain('var journeyLensMap = {');
      expect(source).toContain('"aria-label": "Current water parcel state"');
      expect(source).toContain("driver: 'Hydraulic gradient'");
      expect(source).toContain("driver: 'Water-potential gradient'");
      expect(source).toContain("pace: 'Path dependent'");
      expect(source).toContain('className: "wc-viewport-dock"');
      expect(source).toContain('var journeyStatusLabel =');
      expect(source).toContain("'Waiting for a land pathway choice'");
      expect(source).toContain("'Journey paused'");
      expect(source).toContain('React.createElement("span", null, "Journey status")');
      expect(source).toContain('"aria-keyshortcuts": "ArrowLeft ArrowRight ArrowUp ArrowDown F"');
      expect(source).toContain('" + journeyStatusLabel + " | illustrative scale"');
      expect(source).toContain('className: "wc-viewport-choice"');
      expect(source).toContain("chooseJourneyPath('runoff')");
      expect(source).toContain("chooseJourneyPath('infiltrate')");
      expect(source).toContain("chooseJourneyPath('plant')");
      expect(source).toContain('"data-clim-solar": String(currentSolar)');
      expect(source).toContain('"data-clim-temp": String(currentTemp)');
      expect(source).toContain('"data-clim-wind": String(currentWind)');
      expect(source).toContain('scene.background.setHSL');
      expect(source).toContain('vapor3d.material.opacity = Math.min');
      expect(source).toContain('rain3d.material.color.setHex');
      expect(source).toContain('cloudGroup3d.position.x =');
    });
  });

  it('renders a climate-responsive, route-focused immersive environment', () => {
    WATER_CYCLE_PATHS.forEach((filePath) => {
      const source = readFileSync(filePath, 'utf8');

      expect(source).toContain('var skyUniforms3d = {');
      expect(source).toContain('new THREE.ShaderMaterial({');
      expect(source).toContain('var sunOrb3d = new THREE.Group();');
      expect(source).toContain('var moon3d = new THREE.Mesh');
      expect(source).toContain('skyUniforms3d.topColor.value.setHSL');
      expect(source).toContain('stars3d.material.opacity =');
      expect(source).toContain('var oceanBasePositions3d = new Float32Array');
      expect(source).toContain('oceanGeometry3d.computeVertexNormals();');
      expect(source).toContain('var foam3d = new THREE.Mesh');
      expect(source).toContain('var cloudShadeMat3d =');
      expect(source).toContain('var distantClouds3d = new THREE.Group();');
      expect(source).toContain('var forestGroup3d = new THREE.Group();');
      expect(source).toContain('var canopyInterceptionGroup3d = new THREE.Group();');
      expect(source).toContain('var canopyBeadCount3d = 32;');
      expect(source).toContain('var canopyBeadOrigins3d = new Float32Array');
      expect(source).toContain('var canopyBeads3d = new THREE.Points');
      expect(source).toContain('var canopyThroughfallCount3d = 28;');
      expect(source).toContain('var canopyEvaporationCount3d = 24;');
      expect(source).toContain("'canopy_interception', 'Canopy interception'");
      expect(source).toContain('var canopyStorageMemory3d = 0;');
      expect(source).toContain("var canopyRainActive3d = coverVisual3d === 'forest'");
      expect(source).toContain('var canopyStorageTarget3d = canopyRainActive3d');
      expect(source).toContain('var canopyReleaseRate3d = frameDelta3d *');
      expect(source).toContain('var canopyThroughfallStrength3d = Math.max');
      expect(source).toContain('var canopyEvaporationStrength3d = canopyStorageMemory3d');
      expect(source).toContain('canopyBeadGeometry3d.setDrawRange');
      expect(source).toContain('visualTime3d * (0.035 + canopyThroughfallStrength3d * 0.1)');
      expect(source).toContain('canvasEl.dataset.canopyThroughfall =');
      expect(source).toContain("runoffCoverFactor3d *= 1 - canopyStorageMemory3d * 0.18");
      expect(source).toContain('With forest cover, water beads show rain stored on leaves');
      expect(source).toContain('var urbanGroup3d = new THREE.Group();');
      expect(source).toContain('var urbanStormwaterGroup3d = new THREE.Group();');
      expect(source).toContain('var urbanRoofRunoffCount3d = 28;');
      expect(source).toContain('var urbanStormwaterCurves3d = [');
      expect(source).toContain('new THREE.TubeGeometry(urbanStormwaterCurves3d[urbanChannelIndex3d], 32');
      expect(source).toContain('var urbanStormDrain3d = new THREE.Mesh');
      expect(source).toContain('var urbanStormOutletCurve3d = makeJourneyCurve3d');
      expect(source).toContain('var urbanStormMarkers3d = new THREE.Points');
      expect(source).toContain("'urban_stormwater', 'Stormwater runoff'");
      expect(source).toContain('var urbanStormPulseMemory3d = 0;');
      expect(source).toContain("var urbanRainActive3d = coverVisual3d === 'urban'");
      expect(source).toContain('var urbanStormTarget3d = urbanRainActive3d');
      expect(source).toContain("var urbanStormFlowStrength3d = coverVisual3d === 'urban'");
      expect(source).toContain('urbanStormMarkerCurve3d.getPointAt(urbanStormMarkerT3d)');
      expect(source).toContain("canvasEl.dataset.roofRunoff = urbanRainActive3d ? 'rapid-shedding'");
      expect(source).toContain("canvasEl.dataset.stormDrain = urbanStormwaterVisible3d ? 'converging-flow'");
      expect(source).toContain('canvasEl.dataset.urbanRunoffPulse = String(Math.round');
      expect(source).toContain("runoffCoverFactor3d *= 1 + urbanStormPulseMemory3d * 0.08");
      expect(source).toContain('With urban cover, roof runoff converges through curb channels');
      expect(source).toContain('var meadowGroup3d = new THREE.Group();');
      expect(source).toContain('var meadowHydrologyGroup3d = new THREE.Group();');
      expect(source).toContain('var meadowRetentionBeadCount3d = 36;');
      expect(source).toContain('var meadowInfiltrationCurves3d = [];');
      expect(source).toContain('new THREE.TubeGeometry(meadowInfiltrationCurve3d, 24');
      expect(source).toContain('var meadowInfiltrationMarkerCount3d = 30;');
      expect(source).toContain('var meadowInfiltrationMarkers3d = new THREE.Points');
      expect(source).toContain("'meadow_infiltration', 'Grassland infiltration'");
      expect(source).toContain('var meadowRetentionMemory3d = 0;');
      expect(source).toContain("var meadowRainActive3d = coverVisual3d === 'grass'");
      expect(source).toContain('var meadowRetentionTarget3d = meadowRainActive3d');
      expect(source).toContain("var meadowInfiltrationStrength3d = coverVisual3d === 'grass'");
      expect(source).toContain('meadowInfiltrationMarkerCurve3d.getPointAt(meadowInfiltrationMarkerT3d)');
      expect(source).toContain('canvasEl.dataset.grassRetention = String(Math.round');
      expect(source).toContain("canvasEl.dataset.grassInfiltration = meadowHydrologyVisible3d ? 'shallow-percolation'");
      expect(source).toContain("runoffCoverFactor3d *= 1 - meadowRetentionMemory3d * 0.12");
      expect(source).toContain('With grass cover, droplets pause on blades');
      expect(source).toContain('var routeGlow3d = new THREE.Mesh');
      expect(source).toContain('var routeMarkers3d = new THREE.Points');
      expect(source).toContain('var dropletTrail3d = new THREE.Points');
      expect(source).toContain('new THREE.LatheGeometry(dropletProfile3d, 32)');
      expect(source).toContain('dropletGroup3d.quaternion.slerp');
      expect(source).toContain('var rainBasePositions3d = new Float32Array');
      expect(source).toContain('var snowMode3d = tempVisual3d < 0;');
      expect(source).toContain('if (!motionReduced3d && !journeyPaused3d) visualTime3d += frameDelta3d;');
      expect(source).toContain('function makeProcessLabel3d');
      expect(source).toContain('new THREE.CanvasTexture(labelCanvas3d)');
      expect(source).toContain('var stateLabelKey3d = {');
      expect(source).toContain("canvasEl.dataset.sceneFocus = groundChoiceActive3d ? 'route-choice' : activeLabelKey3d;");
      expect(source).toContain('var focusBeacon3d = new THREE.Group();');
      expect(source).toContain('focusRingMat3d.color.setHex(stateVisualColor3d);');
      expect(source).toContain("var undergroundMode3d = state3d === 'infiltrating'");
      expect(source).toContain('landMat3d.opacity += ((undergroundMode3d ? 0.28 : 1)');
      expect(source).toContain('canvasEl.dataset.cutaway = String(undergroundMode3d);');
      expect(source).toContain('var snowCover3d = new THREE.Mesh');
      expect(source).toContain('var rainRipples3d = new THREE.Group();');
      expect(source).toContain('rippleMesh3d.material.opacity =');
      expect(source).toContain('var vaporBasePositions3d = new Float32Array');
      expect(source).toContain('var vaporRiseRate3d =');
      expect(source).toContain("canvasEl.dataset.moistureSource = condensationTransfer3d ? 'cloud'");
      expect(source).toContain('var windStreams3d = new THREE.Group();');
      expect(source).toContain('windStreamCurves3d[windCurveIndex3d].getPointAt');
      expect(source).toContain("canvasEl.dataset.windField = showWindField3d ? 'visible' : 'hidden';");
      expect(source).toContain('var windArrowGroup3d = new THREE.Group();');
      expect(source).toContain('new THREE.ConeGeometry(0.07, 0.24, 8)');
      expect(source).toContain("'wind_transport', 'Atmospheric transport'");
      expect(source).toContain('windArrowCurve3d.getTangentAt');
      expect(source).toContain('windArrowMesh3d.quaternion.setFromUnitVectors');
      expect(source).toContain('var windArrowSpeedFactor3d = 1 + windArrowCurveIndex3d * 0.13;');
      expect(source).toContain('canvasEl.dataset.windAdvection =');
      expect(source).toContain("canvasEl.dataset.windShear = showWindField3d ? 'layered' : 'hidden';");
      expect(source).toContain('canvasEl.dataset.precipitationDeflection =');
      expect(source).toContain('Wind streamlines and arrowheads show layered atmospheric transport');
      expect(source).toContain('var orographicLiftGroup3d = new THREE.Group();');
      expect(source).toContain('var orographicLiftCurves3d = [];');
      expect(source).toContain('orographicCurve3d.getPoints(48)');
      expect(source).toContain('new THREE.ConeGeometry(0.065, 0.23, 8)');
      expect(source).toContain('var mountainPrecipitationCount3d = 42;');
      expect(source).toContain('var mountainPrecipitation3d = new THREE.Points');
      expect(source).toContain("'orographic_lift', 'Orographic lift'");
      expect(source).toContain('var orographicLiftActive3d = showWindField3d');
      expect(source).toContain('windVisual3d / 3 * 0.55 + rainVisual3d / 100 * 0.45');
      expect(source).toContain('orographicArrowCurve3d.getTangentAt');
      expect(source).toContain('mountainPrecipitationGeometry3d.setDrawRange');
      expect(source).toContain("canvasEl.dataset.orographicLift = orographicLiftActive3d ? 'windward-rising-air'");
      expect(source).toContain("canvasEl.dataset.mountainPrecipitation = orographicLiftActive3d ? (tempVisual3d < 0 ? 'snow' : 'rain')");
      expect(source).toContain('airflow arcs upward over the mountains and produces windward rain or snow');
      expect(source).toContain('var rainShadowGroup3d = new THREE.Group();');
      expect(source).toContain('new THREE.CircleGeometry(1, 40)');
      expect(source).toContain('var rainShadowCracks3d = new THREE.LineSegments');
      expect(source).toContain('var rainShadowHazeCount3d = 24;');
      expect(source).toContain('var rainShadowHaze3d = new THREE.Points');
      expect(source).toContain('new THREE.ConeGeometry(0.06, 0.22, 8)');
      expect(source).toContain("'rain_shadow', 'Rain shadow'");
      expect(source).toContain('var rainShadowStrength3d = Math.max');
      expect(source).toContain('orographicStrength3d * (0.58 + solarVisual3d / 2 * 0.42)');
      expect(source).toContain('var rainShadowArrowT3d = 0.66 + rainShadowArrowPhase3d * 0.32;');
      expect(source).toContain('rainShadowHazePhase3d * windVisual3d * 0.08');
      expect(source).toContain("canvasEl.dataset.rainShadow = orographicLiftActive3d ? 'leeward-drying'");
      expect(source).toContain('Descending leeward air reveals a warmer, drier rain shadow');
      expect(source).toContain('var plantRootGroup3d = new THREE.Group();');
      expect(source).toContain('var plantRootPulseGroup3d = new THREE.Group();');
      expect(source).toContain('rootPulseMesh3d.position.copy');
      expect(source).toContain('canvasEl.dataset.rootUptake = String(plantTransferActive3d);');
      expect(source).toContain('var vaporShell3d = new THREE.Mesh(new THREE.IcosahedronGeometry');
      expect(source).toContain('var iceCrystal3d = new THREE.Group();');
      expect(source).toContain('var fallStreak3d = new THREE.Mesh');
      expect(source).toContain("canvasEl.dataset.parcelPhase = frozenParcel3d ? 'solid'");
      expect(source).toContain('var riverFlow3d = new THREE.Points');
      expect(source).toContain('riverCurve.getPointAt(riverMarkerT3d)');
      expect(source).toContain("canvasEl.dataset.surfaceFlow = riverFlow3d.visible ? 'moving' : 'quiet';");
      expect(source).toContain('var riverTurbidity3d = new THREE.Mesh');
      expect(source).toContain('var suspendedSedimentCount3d = 56;');
      expect(source).toContain('var suspendedSedimentSeeds3d = new Float32Array');
      expect(source).toContain('var suspendedSediment3d = new THREE.Points');
      expect(source).toContain('var sedimentPlume3d = new THREE.Mesh');
      expect(source).toContain('var floodplainStorageGroup3d = new THREE.Group();');
      expect(source).toContain('var floodplainPoolSpecs3d = [');
      expect(source).toContain('var floodplainPools3d = [];');
      expect(source).toContain('var floodplainExchangeCurves3d = [');
      expect(source).toContain('new THREE.TubeGeometry(floodplainExchangeCurve3d, 28');
      expect(source).toContain('var floodplainExchangeMarkerCount3d = 24;');
      expect(source).toContain('var floodplainExchangeMarkers3d = new THREE.Points');
      expect(source).toContain("'sediment_transport', 'Suspended sediment'");
      expect(source).toContain("'floodplain_storage', 'Floodplain storage'");
      expect(source).toContain('var floodplainStorageMemory3d = 0;');
      expect(source).toContain('var floodplainStorageTarget3d = runoffRouteActive3d');
      expect(source).toContain('var floodplainStorageTrend3d = floodplainStorageTarget3d');
      expect(source).toContain('var floodplainStorageVisible3d = !undergroundMode3d');
      expect(source).toContain('var localFloodplainStorage3d = Math.max');
      expect(source).toContain("var floodplainMarkerT3d = floodplainStorageTrend3d === 'draining'");
      expect(source).toContain('canvasEl.dataset.floodplainStorage = String(Math.round');
      expect(source).toContain('canvasEl.dataset.floodplainExchange = floodplainStorageVisible3d ?');
      expect(source).toContain("var sedimentCoverFactor3d = coverVisual3d === 'urban'");
      expect(source).toContain('var sedimentStrength3d = runoffRouteActive3d');
      expect(source).toContain('(1 - floodplainStorageMemory3d * 0.18)');
      expect(source).toContain('var sedimentTransportVisible3d = runoffRouteActive3d');
      expect(source).toContain('suspendedSedimentGeometry3d.setDrawRange');
      expect(source).toContain('var sedimentPhase3d =');
      expect(source).toContain('var sedimentRiverPoint3d = riverCurve.getPointAt');
      expect(source).toContain('var sedimentPlumeT3d =');
      expect(source).toContain("canvasEl.dataset.sedimentTransport = sedimentTransportVisible3d ? 'river-to-estuary'");
      expect(source).toContain('canvasEl.dataset.riverTurbidity = sedimentTransportVisible3d ?');
      expect(source).toContain("canvasEl.dataset.floodplainSedimentTrap = floodplainStorageVisible3d ?");
      expect(source).toContain('tan particles show a relative suspended-sediment signal');
      expect(source).toContain('side pools fill across the floodplain');
      expect(source).toContain('var aquiferCurrentCurve3d = new THREE.CatmullRomCurve3');
      expect(source).toContain('var aquiferFlow3d = new THREE.Points');
      expect(source).toContain('aquiferCurrentCurve3d.getPointAt(aquiferMarkerT3d)');
      expect(source).toContain("canvasEl.dataset.groundwaterFlow = aquiferFlow3d.visible ? 'moving' : 'hidden';");
      expect(source).toContain('var soilPercolation3d = new THREE.Points');
      expect(source).toContain('percolationPosition3d.setY');
      expect(source).toContain("canvasEl.dataset.percolation = soilPercolation3d.visible ? 'visible' : 'hidden';");
      expect(source).toContain('var urbanPonding3d = new THREE.Group();');
      expect(source).toContain("canvasEl.dataset.ponding = urbanPonding3d.visible ? 'visible' : 'hidden';");
      expect(source).toContain('var branchPreviewGroup3d = new THREE.Group();');
      expect(source).toContain("{ key: 'runoff', labelKey: 'river'");
      expect(source).toContain("{ key: 'infiltrate', labelKey: 'aquifer'");
      expect(source).toContain("{ key: 'plant', labelKey: 'plant'");
      expect(source).toContain('new THREE.TetrahedronGeometry(0.15, 0)');
      expect(source).toContain('branchPreviewGroup3d.visible = groundChoiceActive3d;');
      expect(source).toContain("var isChoiceLabel3d = labelKey3d === 'river'");
      expect(source).toContain('branchSpec3d.markerMesh.position.copy');
      expect(source).toContain('function makeBranchShareLabel3d(branchSpec3d)');
      expect(source).toContain('function updateBranchShareLabel3d(branchSpec3d, branchPercent3d)');
      expect(source).toContain('branchSpec3d.shareSprite3d = branchShareSprite3d;');
      expect(source).toContain("shareLabel: 'Runoff'");
      expect(source).toContain("shareLabel: 'Recharge'");
      expect(source).toContain("shareLabel: 'Plant'");
      expect(source).toContain("var branchRunoffCoverWeight3d = coverVisual3d === 'urban'");
      expect(source).toContain("var branchInfiltrationCoverWeight3d = coverVisual3d === 'urban'");
      expect(source).toContain("var branchPlantBase3d = coverVisual3d === 'forest'");
      expect(source).toContain('var branchScoreTotal3d = branchRunoffScore3d +');
      expect(source).toContain('var branchPlantPercent3d = Math.max(0, 100 -');
      expect(source).toContain('var branchSharePercentByKey3d = {');
      expect(source).toContain('var branchMarkerT3d = motionReduced3d ?');
      expect(source).toContain('visualTime3d * (0.055 + branchShare3d * 0.13)');
      expect(source).toContain('updateBranchShareLabel3d(branchSpec3d, branchSharePercent3d);');
      expect(source).toContain("canvasEl.dataset.routePreview = groundChoiceActive3d ? 'runoff,infiltrate,plant' : 'hidden';");
      expect(source).toContain('canvasEl.dataset.routeBalance = groundChoiceActive3d ?');
      expect(source).toContain("canvasEl.dataset.routeBalanceModel = 'relative-tendency';");
      expect(source).toContain('At the land decision, percentages compare relative runoff');
      expect(source).toContain('"data-route-choice": "runoff"');
      expect(source).toContain('"data-route-choice": "infiltrate"');
      expect(source).toContain('"data-route-choice": "plant"');
      expect(source).toContain('button[data-route-choice="runoff"]');
      expect(source).toContain('var branchRaycaster3d = new THREE.Raycaster();');
      expect(source).toContain('new THREE.TubeGeometry(branchSpec3d.curve, 40, 0.16');
      expect(source).toContain('branchSpec3d.routeHitMesh.userData.routeChoice = branchSpec3d.key;');
      expect(source).toContain('branchRaycaster3d.intersectObjects(branchPreviewGroup3d.children, true)');
      expect(source).toContain('var branchDragDistance3d = Math.hypot');
      expect(source).toContain('if (branchDragDistance3d > 7) return;');
      expect(source).toContain('canvasEl.dataset.routeChoiceRequest = selectedBranchKey3d;');
      expect(source).toContain("canvasEl.addEventListener('pointermove', handleBranchPointerMove3d);");
      expect(source).toContain("canvasEl.removeEventListener('pointermove', handleBranchPointerMove3d);");
      expect(source).toContain('function handleJourney3dSceneClick(e)');
      expect(source).toContain("var requestedPath = journeyCanvas.dataset.routeChoiceRequest || '';");
      expect(source).toContain('if (journeyCanvas._wc3dResetCamera) journeyCanvas._wc3dResetCamera();');
      expect(source).toContain('chooseJourneyPath(requestedPath);');
      expect(source).toContain('onClick: handleJourney3dSceneClick');
      expect(source).toContain("makeProcessLabel3d('cycle', 'Cycle continues'");
      expect(source).toContain("complete: 'cycle'");
      expect(source).toContain('var arrivalWaveGroup3d = new THREE.Group();');
      expect(source).toContain('var arrivalSpark3d = new THREE.Points');
      expect(source).toContain('var cycleCrown3d = new THREE.Group();');
      expect(source).toContain('var lastArrivalState3d = null;');
      expect(source).toContain('var arrivalStateChanged3d =');
      expect(source).toContain('if (!motionReduced3d && !journeyPaused3d && arrivalAge3d < 2)');
      expect(source).toContain('canvasEl.dataset.arrivalEffect =');
      expect(source).toContain('cycleCrown3d.visible = cycleCompleteActive3d;');
      expect(source).toContain("canvasEl.dataset.completionEffect = cycleCompleteActive3d ? 'cycle-continues' : 'hidden';");
      expect(source).toContain('var cloudShadowMat3d = new THREE.ShaderMaterial({');
      expect(source).toContain('uniforms: { shadowOpacity: { value: 0 } }');
      expect(source).toContain('cloudShadow3d.position.x = cloudGroup3d.position.x;');
      expect(source).toContain("canvasEl.dataset.cloudShadow = cloudShadow3d.visible ? 'visible' : 'hidden';");
      expect(source).toContain('var rainbowGroup3d = new THREE.Group();');
      expect(source).toContain('new THREE.TorusGeometry(3.5 - rainbowIndex3d * 0.075');
      expect(source).toContain('var rainbowMemory3d = 0;');
      expect(source).toContain('var rainbowTrigger3d = rainbowWeather3d &&');
      expect(source).toContain('if (motionReduced3d) rainbowMemory3d = rainbowTrigger3d ? 1 : 0;');
      expect(source).toContain('rainbowGroup3d.visible = rainbowVisible3d;');
      expect(source).toContain("canvasEl.dataset.weatherOptics = rainbowVisible3d ? 'rainbow' : 'none';");
      expect(source).toContain('function makeSolarEnergyPath3d(pathPoints3d)');
      expect(source).toContain('var solarEnergyPaths3d = {');
      expect(source).toContain('new THREE.TubeGeometry(solarLaneCurve3d, 40, 0.018');
      expect(source).toContain('var activeSolarEnergyKey3d = vaporTransfer3d ?');
      expect(source).toContain('solarMarkerPosition3d.setXYZ');
      expect(source).toContain('var latentHeatGroup3d = new THREE.Group();');
      expect(source).toContain('var latentHeatVisible3d = condensationTransfer3d');
      expect(source).toContain('var latentHeatPhase3d = motionReduced3d ?');
      expect(source).toContain("canvasEl.dataset.energyDriver = latentHeatVisible3d ? 'latent-heat-release'");
      expect(source).toContain("driver: 'Cooling; latent heat released'");
      expect(source).toContain('var soilIntakePatch3d = new THREE.Mesh');
      expect(source).toContain('var soilMoistureFrontGroup3d = new THREE.Group();');
      expect(source).toContain('new THREE.ConeGeometry(0.48, 1.4');
      expect(source).toContain('var wettingFrontRing3d = new THREE.Mesh');
      expect(source).toContain('var waterTableRecharge3d = new THREE.Mesh');
      expect(source).toContain('var groundwaterStorageGroup3d = new THREE.Group();');
      expect(source).toContain('var waterTableSurfaceGeometry3d = new THREE.PlaneGeometry(8.15, 6.15');
      expect(source).toContain('var waterTableSurfaceBasePositions3d = new Float32Array');
      expect(source).toContain('var waterTableRim3d = new THREE.LineSegments');
      expect(source).toContain('var capillaryFringeCount3d = 64;');
      expect(source).toContain('var capillaryFringeSeeds3d = new Float32Array');
      expect(source).toContain('var capillaryFringe3d = new THREE.Points');
      expect(source).toContain("'water_table', 'Water table'");
      expect(source).toContain('var groundwaterStorageMemory3d = 0.24;');
      expect(source).toContain('var infiltrationStrength3d = Math.max');
      expect(source).toContain('0.18 + journeyProgress3d * (0.68 + infiltrationStrength3d * 0.18)');
      expect(source).toContain('soilMoistureFrontGroup3d.position.set');
      expect(source).toContain('var wettingPulse3d = motionReduced3d ? 0');
      expect(source).toContain('waterTableRecharge3d.visible = aquiferRechargeActive3d;');
      expect(source).toContain('var groundwaterRechargeTarget3d = aquiferRechargeActive3d');
      expect(source).toContain('var groundwaterStorageTrend3d = groundwaterRechargeTarget3d');
      expect(source).toContain('var waterTableLevel3d = -2.08 + groundwaterStorageMemory3d * 0.34;');
      expect(source).toContain('waterTableRecharge3d.position.y = waterTableLevel3d + 0.015;');
      expect(source).toContain('waterTableSurfaceGeometry3d.computeVertexNormals();');
      expect(source).toContain('var capillaryFringePhase3d =');
      expect(source).toContain('canvasEl.dataset.waterTableStorage = String(Math.round');
      expect(source).toContain("canvasEl.dataset.waterTableTrend = groundwaterStorageVisible3d ?");
      expect(source).toContain("canvasEl.dataset.capillaryFringe = groundwaterStorageVisible3d ? 'visible'");
      expect(source).toContain("canvasEl.dataset.soilMoistureFront = wettingFrontActive3d ? 'advancing'");
      expect(source).toContain("canvasEl.dataset.surfaceIntake = soilIntakePatch3d.visible ? 'visible' : 'hidden';");
      expect(source).toContain('the luminous water table rises during recharge');
      expect(source).toContain('var surfaceRunoffTributaries3d = new THREE.Group();');
      expect(source).toContain('var surfaceRunoffCurves3d = [];');
      expect(source).toContain('new THREE.TubeGeometry(tributaryCurve3d, 36');
      expect(source).toContain('var surfaceRunoffMarkers3d = new THREE.Points');
      expect(source).toContain('var runoffConfluenceGroup3d = new THREE.Group();');
      expect(source).toContain("var runoffCoverFactor3d = coverVisual3d === 'urban' ? 1.25");
      expect(source).toContain('Math.ceil(effectiveRunoff3d / 25)');
      expect(source).toContain('surfaceRunoffCurves3d[surfaceCurveIndex3d].getPointAt');
      expect(source).toContain('var confluencePulse3d = motionReduced3d ? 1');
      expect(source).toContain('canvasEl.dataset.tributaryCount = String(activeTributaryCount3d);');
      expect(source).toContain("coverVisual3d === 'urban' ? 'urban-rapid'");
      expect(source).toContain("coverVisual3d === 'forest' ? 'forest-buffered' : 'grass-moderate'");
      expect(source).toContain('var xylemFlowGroup3d = new THREE.Group();');
      expect(source).toContain('var xylemFlowCurves3d = [');
      expect(source).toContain('new THREE.TubeGeometry(xylemCurve3d, 34, 0.018');
      expect(source).toContain('var xylemMarkers3d = new THREE.Points');
      expect(source).toContain('var stomatalReleaseGroup3d = new THREE.Group();');
      expect(source).toContain('var stomatalVapor3d = new THREE.Points');
      expect(source).toContain('var plantFlowStrength3d = Math.max');
      expect(source).toContain('xylemFlowCurves3d[xylemCurveIndex3d].getPointAt');
      expect(source).toContain('stomatalRingMesh3d.quaternion.copy(camera.quaternion);');
      expect(source).toContain('var stomatalPulse3d = motionReduced3d ? 1');
      expect(source).toContain('stomatalPhase3d * windVisual3d * 0.28');
      expect(source).toContain('canvasEl.dataset.xylemFlow = plantTransferActive3d ?');
      expect(source).toContain("canvasEl.dataset.stomatalRelease = stomatalReleaseActive3d ? 'active' : 'hidden';");
      expect(source).toContain('var rainCurtainCount3d = 72;');
      expect(source).toContain('var rainCurtain3d = new THREE.LineSegments');
      expect(source).toContain('var rainImpactMist3d = new THREE.Points');
      expect(source).toContain('var precipitationFieldActive3d =');
      expect(source).toContain('var liquidRainActive3d = precipitationFieldActive3d && tempVisual3d >= 0;');
      expect(source).toContain('var snowDriftActive3d = precipitationFieldActive3d && tempVisual3d < 0;');
      expect(source).toContain('var rainWindSlant3d = windVisual3d * 0.11;');
      expect(source).toContain('rainCurtainPosition3d.setXYZ');
      expect(source).toContain('rainImpactPosition3d.setXYZ');
      expect(source).toContain("canvasEl.dataset.hydrometeorMode = snowDriftActive3d ? 'snow-drift'");
      expect(source).toContain('var showRainRipples3d = liquidRainActive3d;');
      expect(source).toContain('rain3d.material.size = snowDriftActive3d ? 0.105 : 0.075;');
      expect(source).toContain('var oceanCurrentGroup3d = new THREE.Group();');
      expect(source).toContain('var oceanCurrentCurves3d = [');
      expect(source).toContain('new THREE.TubeGeometry(oceanCurrentCurve3d, 72');
      expect(source).toContain('var oceanCurrentMarkers3d = new THREE.Points');
      expect(source).toContain('var estuaryMixing3d = new THREE.Points');
      expect(source).toContain('var groundwaterSeep3d = new THREE.Points');
      expect(source).toContain('var oceanCurrentActive3d =');
      expect(source).toContain('oceanCurrentCurves3d[oceanCurrentCurveIndex3d].getPointAt');
      expect(source).toContain("var estuaryMixingActive3d = state3d === 'river_runoff'");
      expect(source).toContain("var groundwaterSeepActive3d = state3d === 'aquifer_flow';");
      expect(source).toContain('visualTime3d * (0.08 + effectiveRunoff3d * 0.001)');
      expect(source).toContain('visualTime3d * (0.04 + infiltrationVisual3d * 0.0005)');
      expect(source).toContain("canvasEl.dataset.oceanExchange = estuaryMixingActive3d ? 'river-mixing'");
      expect(source).toContain("estuaryMixingGeometry3d.setAttribute('color'");
      expect(source).toContain('function setEstuarySalinityColor3d');
      expect(source).toContain('vertexColors: true, size: 0.085');
      expect(source).toContain('var estuaryRibbonShape3d = new THREE.Shape();');
      expect(source).toContain('var estuaryMixingRibbonGeometry3d = new THREE.ShapeGeometry');
      expect(source).toContain('estuaryMixingRibbon3d.userData.salinityProbe = true;');
      expect(source).toContain('var estuarySalinityProbe3d = new THREE.Mesh');
      expect(source).toContain('var estuarySalinityLabelGroup3d = new THREE.Group();');
      expect(source).toContain("zone: 'brackish', text: 'Brackish mix'");
      expect(source).toContain('function salinityZoneAtPointer3d');
      expect(source).toContain('intersectObject(estuaryMixingRibbon3d, false)');
      expect(source).toContain("canvasEl.dataset.salinityHover = hoveredSalinityZone3d || 'none';");
      expect(source).toContain('estuaryProbeEnabled3d = estuaryMixingActive3d;');
      expect(source).toContain('var salinityProbePulse3d = motionReduced3d ? 1');
      expect(source).toContain('setEstuarySalinityColor3d(estuaryMixingColor3d');
      expect(source).toContain("canvasEl.dataset.salinityGradient = estuaryMixingActive3d ? 'freshwater,brackish,marine' : 'hidden';");
      expect(source).toContain('During river runoff, move across the estuary plume');
      expect(source).toContain('var coastalWaveGroup3d = new THREE.Group();');
      expect(source).toContain('var coastalWaveCount3d = 7;');
      expect(source).toContain('new THREE.TubeGeometry(coastalWaveCurve3d, 54');
      expect(source).toContain('coastalWaveCrest3d.userData.phase =');
      expect(source).toContain('var shoreWash3d = new THREE.Mesh');
      expect(source).toContain('var breakingSpray3d = new THREE.Points');
      expect(source).toContain('var coastalWaveSpeed3d = 0.028 + windVisual3d * 0.016;');
      expect(source).toContain('coastalWavePhase3d * coastalWavePhase3d * (3 - 2 * coastalWavePhase3d)');
      expect(source).toContain('shoreBreakStrength3d = Math.max');
      expect(source).toContain('visualTime3d * (0.32 + windVisual3d * 0.08)');
      expect(source).toContain("windVisual3d > 1.6 ? 'wind-driven-breakers' : 'gentle-shoaling'");
      expect(source).toContain("motionReduced3d ? 'reduced-static' : 'advancing'");
      expect(source).toContain('The wind control changes ocean wave speed and breaking intensity.');
      expect(source).toContain('var cloudMicrophysicsGroup3d = new THREE.Group();');
      expect(source).toContain('var cloudMicrophysicsCount3d = 54;');
      expect(source).toContain('var cloudDroplets3d = new THREE.Points');
      expect(source).toContain('var cloudNuclei3d = new THREE.Points');
      expect(source).toContain('var cloudCoalescence3d = new THREE.LineSegments');
      expect(source).toContain('var cloudIceCrystalGroup3d = new THREE.Group();');
      expect(source).toContain('cloudGroup3d.add(cloudMicrophysicsGroup3d);');
      expect(source).toContain('var cloudMicrophysicsActive3d = condensationTransfer3d');
      expect(source).toContain('cloudDroplets3d.material.size = 0.045 + cloudGrowth3d * 0.095;');
      expect(source).toContain('var cloudCompaction3d = 1 - cloudGrowth3d * 0.18;');
      expect(source).toContain('var cloudCoalescenceStrength3d = Math.max');
      expect(source).toContain('var cloudCoalescenceActive3d = tempVisual3d >= 0');
      expect(source).toContain('var cloudIceMicrophysicsActive3d = tempVisual3d < 0;');
      expect(source).toContain("tempVisual3d < 0 ? 'ice-nucleation'");
      expect(source).toContain("cloudGrowth3d < 0.72 ? 'droplet-growth' : 'collision-coalescence'");
      expect(source).toContain('During condensation, bright nuclei seed growing cloud droplets');
      expect(source).toContain('var evaporationInterfaceGroup3d = new THREE.Group();');
      expect(source).toContain('var evaporationMoleculeCount3d = 48;');
      expect(source).toContain('var evaporationMolecules3d = new THREE.Points');
      expect(source).toContain('var evaporationCoolingPatch3d = new THREE.Mesh');
      expect(source).toContain('var evaporationHeatRingGroup3d = new THREE.Group();');
      expect(source).toContain('var oceanEvaporationActive3d =');
      expect(source).toContain('evaporationSolarEnergy3d * 0.45 + evaporationThermalEnergy3d * 0.35 + evaporationWindEnergy3d * 0.2');
      expect(source).toContain('evaporationMoleculeGeometry3d.setDrawRange');
      expect(source).toContain('evaporationMoleculePhase3d * windVisual3d * 0.28');
      expect(source).toContain('evaporationCoolingMat3d.color.setHSL');
      expect(source).toContain('evaporationHeatRingGroup3d.children.forEach');
      expect(source).toContain("evaporationEnergy3d < 0.68 ? 'moderate-energy' : 'high-energy'");
      expect(source).toContain("motionReduced3d ? 'reduced-static' : 'molecules-escaping'");
      expect(source).toContain("canvasEl.dataset.surfaceCooling = oceanEvaporationActive3d ? 'localized' : 'hidden';");
      expect(source).toContain('During evaporation, solar energy, temperature, and wind change how many surface molecules escape');
      expect(source).toContain('var snowmeltRouteGroup3d = new THREE.Group();');
      expect(source).toContain('var snowmeltCurves3d = [];');
      expect(source).toContain('new THREE.TubeGeometry(snowmeltCurve3d, 36');
      expect(source).toContain('var snowmeltMarkers3d = new THREE.Points');
      expect(source).toContain('var snowpackMemory3d = null;');
      expect(source).toContain('var snowAccumulationTarget3d = tempVisual3d < 0');
      expect(source).toContain('snowpackMemory3d + frameDelta3d *');
      expect(source).toContain('var snowmeltRate3d = frameDelta3d *');
      expect(source).toContain('var snowmeltIntensity3d = Math.max');
      expect(source).toContain('snowmeltCurves3d[snowmeltCurveIndex3d].getPointAt');
      expect(source).toContain('snowMat3d.opacity =');
      expect(source).toContain('canvasEl.dataset.snowpackStorage =');
      expect(source).toContain('canvasEl.dataset.snowmeltRunoff =');
      expect(source).toContain('runoffVisual3d / 145 + snowmeltIntensity3d * 0.18');
      expect(source).toContain('Cold conditions store water as snow; warming and sunlight release meltwater');
      expect(source).toContain('var snowStorageGaugeGroup3d = new THREE.Group();');
      expect(source).toContain('var snowStorageFill3d = new THREE.Mesh');
      expect(source).toContain('for (var snowGaugeTickIndex3d = 0; snowGaugeTickIndex3d < 5;');
      expect(source).toContain('var snowStorageLabelCanvas3d = document.createElement');
      expect(source).toContain('function updateSnowStorageLabel3d');
      expect(source).toContain("snowStorageStatus3d = snowmeltActive3d ? 'Melting to river'");
      expect(source).toContain('snowStorageFill3d.scale.y = Math.max');
      expect(source).toContain('canvasEl.dataset.snowpackPercent =');
      expect(source).toContain('canvasEl.dataset.snowmeltContribution =');
      expect(source).toContain('The mountain gauge reports stored snow percentage');
      expect(source).toContain('labelTextures3d.forEach(function(labelTexture3d)');
    });
  });
});
