'use strict';

const ETS = 'https://praxis.ets.org/on/demandware.static/-/Library-Sites-ets-praxisLibrary/default/pdfs/5412.pdf';
const PSEL = 'https://www.npbea.org/wp-content/uploads/2017/06/Professional-Standards-for-Educational-Leaders_2015.pdf';
const CONTINUOUS_IMPROVEMENT = 'https://ies.ed.gov/use-work/resource-library/resource/other-resource/continuous-improvement-education-toolkit-schools-and-districts';
const FERPA = 'https://studentprivacy.ed.gov/faq/who-school-official-under-ferpa';
const IDEA_EVAL = 'https://sites.ed.gov/idea/regs/b/d/300.304';
const IDEA_MTSS = 'https://sites.ed.gov/idea/idea-files/rts-qa-child-find-part-b-08-24-2021/';
const CIVIL_RIGHTS = 'https://www.ed.gov/laws-and-policy/civil-rights-laws';
const EOP = 'https://www.ed.gov/teaching-and-administration/safe-learning-environments/school-safety-and-security/emergency-planning';
const CYBER = 'https://www.cisa.gov/resources-tools/resources/report-protecting-our-future';
const FAMILY_ENGAGEMENT = 'https://www.ed.gov/teaching-and-administration/lead-and-manage-my-school/state-support-network/ssn-resources/strategies-for-equitable-family-engagement';

const q = (promptA, promptB, correct, distractors, rationale, difficulty = 'application') => ({ promptA, promptB, correct, distractors, rationale, difficulty });

const banks = [
  {
    id: 'mission-vision-goals-core-values', chapterId: 'lead5412-ch-01', domainId: 'strategic-leadership', domain: 'Strategic Leadership',
    label: 'Mission, Vision, Goals, and Core Values', references: [ETS, PSEL, CONTINUOUS_IMPROVEMENT],
    questions: [
      q('What should precede revision of a school mission?', 'A new leader wants to replace the mission during the first week. What is the strongest first move?', 'Analyze disaggregated student, opportunity, implementation, climate, and stakeholder evidence before facilitating an inclusive review.', ['Copy a highly rated school mission.', 'Ask only the leadership team to draft it privately.', 'Delay all review until test scores rise.'], 'A mission should respond to the actual school context and each student, so leaders first establish a representative evidence base and an inclusive process.'),
      q('What makes a school vision educationally useful?', 'A vision statement is inspiring but has no implications for practice. What revision is needed?', 'Connect a clear future state for every student with shared values, observable commitments, and decisions the community can enact.', ['Add more slogans without defining action.', 'Limit the vision to the highest-performing group.', 'Replace the vision with an annual event calendar.'], 'A useful vision guides choices and collective action; it expresses an equitable future, shared commitments, and a basis for monitoring progress.'),
      q('Which goal is best designed for strategic monitoring?', 'A team proposes that students will improve soon. How should the leader strengthen the goal?', 'Specify the learner outcome, baseline, target, timeframe, relevant subgroup evidence, responsible actions, and review intervals.', ['Use a broad aspiration with no measure.', 'Set a target without examining baseline variation.', 'Measure only staff attendance at meetings.'], 'A strategic goal is measurable and time bound while linking outcomes to adult actions, access, implementation, and scheduled evidence reviews.'),
      q('How should district and school goals relate?', 'A school priority conflicts with a district requirement. What should the leader do?', 'Clarify the governing requirements, align the school strategy where possible, and document any needed escalation or approved adaptation.', ['Ignore the district requirement.', 'Abandon all school-specific needs.', 'Let each teacher choose whether policy applies.'], 'Strategic coherence requires lawful alignment with district direction while preserving evidence-based responses to the school context through authorized processes.'),
      q('What is the role of core values in leadership?', 'A leader invokes equity only in speeches. What would demonstrate that it is a core value?', 'Use the value consistently in resource, access, staffing, instruction, discipline, communication, and improvement decisions.', ['Display the value on posters only.', 'Apply it only when no tradeoff is required.', 'Treat values as private preferences.'], 'Core values become credible when they shape routine and difficult decisions, are made visible in practice, and are open to evidence and accountability.'),
      q('How should leaders engage dissent during goal setting?', 'Several families question a proposed attendance goal. What response best supports shared commitment?', 'Surface the concerns, examine evidence and barriers with affected groups, revise the strategy when warranted, and explain the final rationale.', ['Label disagreement as resistance.', 'Hold the vote before sharing the data.', 'Remove dissenting families from the process.'], 'Inclusive strategic leadership treats dissent as information, protects meaningful participation, and builds commitment through transparent evidence and reasoning.'),
      q('What is a sound way to prioritize among several needs?', 'A needs assessment identifies ten urgent problems. How should the team choose a focus?', 'Apply transparent criteria such as impact, inequity, urgency, evidence, feasibility, dependencies, and alignment with mission.', ['Select the easiest problem automatically.', 'Choose the concern raised by the loudest person.', 'Pursue all ten with equal resources.'], 'Explicit criteria make tradeoffs visible and reduce arbitrary priority setting while keeping student impact and equity central.'),
      q('How should a leader communicate strategic goals?', 'Staff members can repeat a goal but cannot explain their role. What is missing?', 'Translate the goal for different audiences into responsibilities, supports, evidence, timelines, and feedback channels while preserving one coherent message.', ['Send the same dense memo repeatedly.', 'Limit information to administrators.', 'Change the goal for each audience.'], 'Communication supports implementation when stakeholders understand the purpose, their contribution, available support, and how progress will be discussed.'),
      q('When should a strategic goal be revised?', 'A goal is off track after two review cycles. What is the best leadership response?', 'Examine implementation and outcome evidence, test the causal assumptions, consult affected stakeholders, and document a justified adaptation.', ['Lower the target without analysis.', 'Keep every action unchanged to show resolve.', 'Replace the team before reviewing conditions.'], 'Responsible adaptation distinguishes weak implementation from a weak theory of action and changes the plan transparently rather than reacting to one number.'),
    ],
  },
  {
    id: 'continuous-improvement-change-strategy', chapterId: 'lead5412-ch-02', domainId: 'strategic-leadership', domain: 'Strategic Leadership',
    label: 'Continuous Improvement, Change, and Strategic Alignment', references: [ETS, PSEL, CONTINUOUS_IMPROVEMENT],
    questions: [
      q('What begins a disciplined continuous-improvement cycle?', 'A team wants to launch solutions before defining the problem. What should the leader request?', 'Develop a specific evidence-based problem statement that identifies who is affected, where, when, and under what conditions.', ['Purchase the most popular program.', 'Set a solution as the problem statement.', 'Wait for perfect causal proof.'], 'A precise problem statement focuses inquiry without assuming the cause or solution and makes later measures and tests interpretable.'),
      q('What is a theory of action in strategic school improvement?', 'A school plan lists activities but not why they should improve outcomes. What should be added?', 'An explicit if-then account linking actions, implementation conditions, intermediate changes, and intended student outcomes.', ['A guarantee that the plan will work.', 'A list of staff members without responsibilities.', 'A restatement of the mission only.'], 'A theory of action exposes causal assumptions so the team can measure implementation, examine mechanisms, and adapt responsibly.'),
      q('How should a small change test be used?', 'A team wants to pilot a new feedback routine. What design best supports learning?', 'Define the prediction and measures, test on a manageable scale, study process and outcome evidence, and decide what to adapt next.', ['Implement everywhere before collecting evidence.', 'Judge success from one enthusiastic comment.', 'Change several unrelated systems at once.'], 'A bounded test reduces risk and produces interpretable learning when its prediction, implementation, evidence, and next decision are specified.'),
      q('What distinguishes a leading measure from a lagging outcome?', 'Annual achievement data arrive too late to guide a tutoring rollout. What additional evidence is needed?', 'Frequent evidence of access, dosage, attendance, instructional quality, and near-term learning that can guide implementation before annual outcomes.', ['More copies of the annual score report.', 'Teacher intentions without observation.', 'A ranking of schools with no process evidence.'], 'Leading measures show whether key conditions and intermediate changes are occurring, while lagging outcomes summarize later results.'),
      q('How should leaders respond to implementation variation?', 'One grade uses an initiative consistently and another cannot fit it into the schedule. What should happen first?', 'Study the schedule, training, resources, adaptations, and fidelity evidence with each team before attributing outcome differences.', ['Assume the second grade lacks commitment.', 'Average the results and ignore variation.', 'Require identical surface routines regardless of context.'], 'Implementation evidence explains whether a strategy received a fair test and whether contextual barriers or productive adaptations matter.'),
      q('What supports people during organizational change?', 'Staff understand the rationale for change but report low confidence using the new practice. What is the priority?', 'Provide protected learning time, modeling, rehearsal, feedback, resources, role clarity, and responsive follow-up.', ['Repeat the announcement more forcefully.', 'Evaluate performance before training.', 'Describe all questions as resistance.'], 'Change requires capacity and psychological support in addition to rationale; leaders monitor learning needs and remove implementation barriers.'),
      q('How should quick wins be interpreted?', 'A pilot produces an early attendance increase. What is the best conclusion?', 'Treat it as encouraging preliminary evidence, check implementation and subgroup patterns, and continue monitoring durability and unintended effects.', ['Declare the initiative proven.', 'Scale immediately without capacity analysis.', 'Ignore the result because it is not final.'], 'Early signals can build momentum but do not establish durable impact; leaders preserve uncertainty and keep studying the system.'),
      q('What makes an improvement review productive?', 'A monthly review meeting becomes a presentation of favorable numbers. What redesign is needed?', 'Use a stable inquiry routine that compares predictions with complete evidence, invites disconfirming information, names adaptations, owners, and next review dates.', ['Remove unfavorable measures.', 'Use the meeting only to celebrate.', 'Change indicators every month.'], 'Continuous improvement depends on honest comparison, shared learning, documented decisions, and follow-through rather than impression management.'),
    ],
  },
  {
    id: 'professional-capacity-feedback-learning', chapterId: 'lead5412-ch-03', domainId: 'instructional-leadership', domain: 'Instructional Leadership',
    label: 'Professional Capacity, Feedback, and Adult Learning', references: [ETS, PSEL, CONTINUOUS_IMPROVEMENT],
    questions: [
      q('What makes professional learning job embedded?', 'Teachers attend a workshop but cannot transfer the routine to their classrooms. What should follow?', 'Use co-planning, modeling, rehearsal, observation, actionable feedback, and student evidence within teachers actual curriculum and schedules.', ['Schedule the same lecture again.', 'Require implementation without support.', 'Measure only workshop satisfaction.'], 'Job-embedded learning connects a defined student need to authentic practice, feedback, collaboration, and evidence over time.'),
      q('How should a leader identify professional-learning needs?', 'A principal chooses training from a catalog before reviewing evidence. What is a stronger process?', 'Integrate student work, disaggregated outcomes, observation, curriculum demands, teacher goals, and implementation evidence to define a focused need.', ['Select the least expensive session only.', 'Assume every teacher needs identical support.', 'Use one test score as the complete diagnosis.'], 'Professional learning is more relevant when multiple sources establish the learner and educator need and distinguish shared from differentiated support.'),
      q('What makes instructional feedback actionable?', 'A walkthrough note says teach better. How should it be improved?', 'Describe specific evidence, connect it to an agreed instructional goal, offer a manageable next step, and arrange practice or follow-up.', ['Add a numerical rating without evidence.', 'Compare the teacher publicly with peers.', 'List every possible improvement at once.'], 'Actionable feedback is evidence based, goal aligned, specific, feasible, dialogic, and connected to support and follow-up.'),
      q('How should walkthrough evidence be used?', 'A leader wants to evaluate a teacher from one three-minute visit. What is the best response?', 'Use brief visits for pattern finding and formative feedback within policy, while relying on adequate evidence and required procedures for formal evaluation.', ['Treat the visit as a complete performance record.', 'Publish the observation to staff.', 'Avoid all classroom evidence.'], 'The intended use of evidence must match its scope, reliability, policy context, and procedural protections.'),
      q('What is productive teacher leadership?', 'A principal delegates improvement work to one expert teacher without authority or time. What is missing?', 'Define a meaningful role, decision boundaries, protected time, support, compensation when applicable, and reciprocal accountability.', ['An honorary title only.', 'Responsibility for evaluating peers secretly.', 'Unlimited authority without governance.'], 'Distributed leadership requires authentic influence, capacity, resources, role clarity, and safeguards rather than transferring work without support.'),
      q('How should professional learning be evaluated?', 'All participants liked a coaching cycle. What additional evidence is needed?', 'Examine educator learning and practice, implementation conditions, student opportunity and outcomes, subgroup access, and unintended effects over time.', ['Use satisfaction as the only outcome.', 'Count certificates as proof of impact.', 'Attribute all score changes to coaching.'], 'A useful evaluation tests the pathway from adult learning to practice and student experience without overclaiming causality.'),
      q('What does differentiated adult learning require?', 'Novice and experienced teachers receive the same introductory session. What should the leader consider?', 'Use common outcomes with supports, practice, pacing, content, coaching, and leadership opportunities responsive to evidence and expertise.', ['Lower expectations for novices permanently.', 'Let preference replace school priorities.', 'Assume experience guarantees mastery.'], 'Adult learning honors prior expertise and agency while differentiating pathways toward clear, shared instructional outcomes.'),
      q('How should leaders support a struggling new teacher?', 'A beginning teacher reports unclear routines and isolation. What is the strongest response?', 'Provide a trained mentor, clear expectations, focused modeling and feedback, protected collaboration, resources, and documented review points.', ['Wait for the annual evaluation.', 'Assign extra duties to build resilience.', 'Share concerns informally with families.'], 'Induction combines relational support, explicit practice, timely evidence, and fair supervision to develop competence and retention.'),
      q('What makes a professional learning community effective?', 'A PLC spends each meeting exchanging activities. What should refocus its work?', 'Use a shared student-learning question, common evidence, collaborative analysis, a testable instructional response, and follow-up on results.', ['Require identical worksheets.', 'Discuss students without examining work.', 'Use the meeting for announcements only.'], 'A PLC improves collective capacity when inquiry connects evidence, instruction, joint responsibility, and iterative learning.'),
      q('How should leaders address initiative overload?', 'Teachers are implementing six unrelated improvement priorities. What is the best leadership move?', 'Map initiatives to strategic goals, retire or sequence low-value work, protect core practices, and communicate the rationale and capacity plan.', ['Add another tracking form.', 'Ask teachers to work faster.', 'Keep every initiative to avoid disappointing sponsors.'], 'Coherence requires prioritization, alignment, capacity analysis, and removal of competing demands that dilute implementation.'),
      q('What role does self-reflection play in leadership?', 'A leader receives recurring feedback about inaccessible meetings. What is the best response?', 'Examine the pattern with affected participants, identify assumptions and barriers, change the design, and monitor whether access improves.', ['Explain why the meetings are already fair.', 'Seek only confirming opinions.', 'Delegate all responsibility for access.'], 'Professional growth requires openness to evidence, examination of impact rather than intent, a concrete adjustment, and accountability for results.'),
      q('How should coaching confidentiality be handled?', 'Teachers are unsure whether coaching notes will be used in evaluation. What should happen before coaching begins?', 'Clarify purpose, roles, confidentiality limits, data use, decision authority, documentation, and any policy-based exceptions.', ['Promise absolute secrecy regardless of law.', 'Leave the boundary unstated.', 'Send all notes to the full staff.'], 'Transparent boundaries protect trust and due process while preventing promises that conflict with policy, safety, or legal obligations.'),
    ],
  },
  {
    id: 'curriculum-instruction-assessment-accountability', chapterId: 'lead5412-ch-04', domainId: 'instructional-leadership', domain: 'Instructional Leadership',
    label: 'Curriculum, Instruction, Assessment, and Accountability', references: [ETS, PSEL, IDEA_EVAL, CONTINUOUS_IMPROVEMENT],
    questions: [
      q('What should a curriculum alignment review examine?', 'Student work shows gaps between grades. What should the instructional leader investigate?', 'Compare standards, intended and enacted curriculum, tasks, assessments, pacing, access, and student work vertically and horizontally.', ['Compare textbook covers only.', 'Require identical daily lessons across grades.', 'Use annual scores without examining opportunities.'], 'Alignment is coherence among intended outcomes, learning opportunities, tasks, assessment, and progression, not mere use of the same materials.'),
      q('How should student work inform instructional leadership?', 'A team labels student responses low without analyzing them. What should the leader facilitate?', 'Use a common protocol to identify evidence of thinking, misconceptions, task demands, subgroup opportunity, and a specific instructional response.', ['Rank teachers from one work sample.', 'Replace the task without identifying the issue.', 'Discuss student traits instead of the work.'], 'Collaborative work analysis connects observable evidence with instruction while avoiding unsupported judgments about students or teachers.'),
      q('What is the best use of formative assessment?', 'Teachers administer weekly checks but record only grades. What is missing?', 'Use timely evidence during learning to adjust instruction, feedback, grouping, scaffolds, and student self-monitoring.', ['Treat each check as a final evaluation.', 'Use it only for report cards.', 'Wait until the end of the term to respond.'], 'Formative assessment is a process for eliciting and using evidence to guide next learning actions, not simply frequent testing.'),
      q('How should leaders interpret subgroup outcome gaps?', 'A report shows persistent differences among student groups. What is the strongest next step?', 'Disaggregate opportunity, access, instruction, climate, discipline, attendance, assessment, and implementation evidence before selecting a response.', ['Infer fixed ability differences.', 'Hide subgroup results to avoid conflict.', 'Attribute the gap to families without evidence.'], 'Equity-focused analysis examines system conditions and student experiences rather than treating group averages as causes or individual destinies.'),
      q('What supports rigorous instruction for each student?', 'A school equates rigor with giving more difficult work without support. What should the leader emphasize?', 'Maintain worthwhile cognitive goals while providing explicit instruction, language and access supports, feedback, productive practice, and multiple pathways to demonstrate learning.', ['Lower the goal whenever support is needed.', 'Increase workload regardless of purpose.', 'Reserve complex tasks for advanced groups.'], 'Rigor combines meaningful cognitive demand with equitable opportunities, responsive supports, and evidence of learning.'),
      q('How should a leader evaluate an instructional program?', 'Scores increased after a new curriculum was adopted. What evidence is needed before attributing improvement?', 'Examine baseline and comparison context, implementation, access, multiple outcomes, subgroup patterns, concurrent changes, stakeholder experience, and unintended effects.', ['Credit the program from the trend alone.', 'Use vendor testimonials as the evaluation.', 'Ignore implementation because materials were purchased.'], 'Program evaluation tests whether the design was enacted, for whom outcomes changed, under what conditions, and what alternative explanations remain.'),
      q('What makes classroom technology educationally justified?', 'A school buys devices and requires daily use. What criterion should lead implementation?', 'Use technology when it advances a defined learning or access goal, preserves privacy and safety, supports pedagogy, and can be evaluated.', ['Maximize screen time as the goal.', 'Select tools by novelty alone.', 'Assume access is equal because devices exist.'], 'Technology is a means rather than an outcome; leaders connect it to curriculum, accessibility, professional learning, security, and evidence.'),
      q('How should leaders respond to weak core instruction and intervention demand?', 'Intervention rosters expand while classroom evidence shows inconsistent core routines. What is the best systems response?', 'Strengthen evidence-based core instruction and access while providing timely targeted support and monitoring both levels of the system.', ['Remove intervention until core instruction is perfect.', 'Place all struggling students in permanent tiers.', 'Treat intervention as a substitute for evaluation.'], 'A coherent support system improves universal opportunity and responds to individual need concurrently without delaying warranted evaluation.'),
      q('What is required when interpreting an assessment result?', 'A benchmark score is used to make a high-stakes placement decision by itself. What should the leader question?', 'Whether the use is supported by the assessment purpose, validity evidence, reliability, administration, access, multiple measures, and current policy.', ['Whether the score has two decimal places.', 'Whether the result confirms expectations.', 'Whether the test is popular.'], 'An assessment supports only interpretations and uses justified by its evidence and conditions; one measure should not bear an unsupported decision.'),
      q('How should accountability data influence improvement?', 'A leader posts rankings and tells teams to work harder. What would be more productive?', 'Pair outcome data with opportunity and implementation evidence, facilitate root-cause inquiry, resource an action plan, and monitor near-term indicators.', ['Use public comparison as the intervention.', 'Remove contextual evidence from discussion.', 'Change the target whenever performance drops.'], 'Accountability information becomes actionable when leaders connect it with system evidence, capacity, decisions, and iterative monitoring.'),
      q('How should leaders protect instructional time?', 'Frequent announcements, testing, and pullouts fragment core lessons. What is the best first response?', 'Audit the schedule and interruptions by student group, clarify priorities, coordinate services, and redesign routines to preserve equitable learning time.', ['Eliminate every student support.', 'Ask teachers to skip planning.', 'Protect only tested subjects.'], 'Instructional time is a strategic resource; leaders analyze access and coordinate supports rather than trading one essential need against another blindly.'),
    ],
  },
  {
    id: 'inclusive-community-belonging-student-support', chapterId: 'lead5412-ch-05', domainId: 'climate-cultural-leadership', domain: 'Climate and Cultural Leadership',
    label: 'Inclusive Community, Belonging, and Student Support', references: [ETS, PSEL, CIVIL_RIGHTS, IDEA_MTSS],
    questions: [
      q('What evidence best describes school climate?', 'A leader wants to understand whether students feel safe and connected. What evidence should be combined?', 'Use disaggregated student, family, and staff perception data with attendance, discipline, participation, safety, access, and observational evidence.', ['Use the leaders impressions only.', 'Use one schoolwide average.', 'Count posters about belonging.'], 'Climate is experienced differently across groups and settings, so leaders triangulate perception, participation, outcome, and process evidence.'),
      q('How should leaders respond to disproportionality in discipline referrals?', 'Referral rates differ sharply by race and disability status. What is the best first systems response?', 'Audit referral definitions, comparable incidents, decision points, classroom supports, access, consequences, and stakeholder experience under current civil-rights requirements.', ['Assume the data prove individual bias in every case.', 'Stop reporting subgroup data.', 'Increase penalties for all students.'], 'Disproportionality is a signal for careful inquiry into policy, implementation, opportunity, discretion, and legal obligations, not a complete causal finding.'),
      q('What builds authentic student belonging?', 'A school adds a celebration week but students still report exclusion from decisions and activities. What should change?', 'Create sustained structures for voice, representation, accessible participation, trusted relationships, responsive support, and accountability for experience.', ['Add more decorations.', 'Invite only high-achieving students to advise leaders.', 'Treat belonging as attendance at events.'], 'Belonging grows from daily relationships, identity safety, meaningful participation, access, and evidence that student input affects the institution.'),
      q('How should student voice inform decisions?', 'A student survey identifies an inaccessible homework policy. What is a responsible response?', 'Share the findings accessibly, involve affected students in examining causes and options, act within governance, and report what changed and why.', ['Promise every suggestion will be adopted.', 'Collect feedback without follow-up.', 'Ask students to solve the issue alone.'], 'Meaningful voice includes representation, influence, transparent constraints, adult responsibility, and a feedback loop.'),
      q('What is a culturally responsive climate practice?', 'Staff interpret one communication style as disrespectful across all contexts. What should a leader facilitate?', 'Examine cultural and linguistic assumptions, clarify teachable expectations, compare comparable behavior, and use relationship-centered, nondiscriminatory responses.', ['Eliminate behavior expectations.', 'Apply stereotypes more consistently.', 'Avoid discussing culture.'], 'Responsive leadership preserves clear expectations while examining bias, communication differences, context, and equitable implementation.'),
      q('How should leaders support multilingual families and students?', 'Important school information is available only in complex English. What is the best systems response?', 'Identify language and accessibility needs, provide qualified communication supports and plain-language formats, and verify reciprocal understanding under current requirements.', ['Rely on children to interpret sensitive information.', 'Translate only promotional materials.', 'Assume silence means agreement.'], 'Equitable communication requires timely, accurate, accessible exchange and safeguards for confidentiality and meaningful participation.'),
      q('What is the relationship between safety and belonging?', 'A proposed security procedure would make many students feel routinely suspected. What should leaders do?', 'Assess actual risk, legal and equity implications, student experience, less intrusive options, implementation safeguards, and effectiveness before adoption.', ['Adopt any measure labeled secure.', 'Ignore student experience because safety is separate.', 'Eliminate all safety procedures.'], 'A safe environment integrates physical, emotional, identity, and procedural safety through proportionate, evidence-based, nondiscriminatory measures.'),
      q('How should a leader respond to suspected bullying or harassment?', 'A student reports repeated identity-based targeting. What is the appropriate leadership posture?', 'Activate current reporting and response procedures promptly, protect against retaliation, preserve confidentiality appropriately, support affected students, investigate impartially, and document follow-up.', ['Promise a specific outcome before inquiry.', 'Require public mediation in every case.', 'Wait for several more reports.'], 'Leaders must respond promptly and fairly within current law and policy while protecting safety, due process, privacy, and access to learning.'),
      q('What makes student-support coordination effective?', 'A student receives disconnected academic, behavioral, and attendance plans. What should the leader promote?', 'With appropriate consent and privacy, coordinate goals, roles, data, culturally responsive supports, family partnership, progress monitoring, and review across relevant teams.', ['Create a separate plan for every adult.', 'Share the full record with anyone who asks.', 'Let the most urgent team override all others.'], 'Coordinated support reduces fragmentation while maintaining role boundaries, privacy, family participation, and timely evaluation obligations.'),
    ],
  },
  {
    id: 'culture-collaboration-conflict-wellbeing', chapterId: 'lead5412-ch-06', domainId: 'climate-cultural-leadership', domain: 'Climate and Cultural Leadership',
    label: 'Professional Culture, Collaboration, Conflict, and Well-Being', references: [ETS, PSEL, CONTINUOUS_IMPROVEMENT, EOP],
    questions: [
      q('What characterizes a professional culture of collective responsibility?', 'Teachers describe student success as belonging only to individual classrooms. What should a leader build?', 'Shared learning goals, collaborative evidence use, mutual support, clear norms, distributed expertise, and accountability for every student.', ['Public competition for the highest scores.', 'Identical beliefs enforced without dialogue.', 'Isolation to protect teacher autonomy.'], 'Collective responsibility combines professional agency with shared commitments, collaboration, evidence, and support across classrooms.'),
      q('How should team norms be established?', 'A committee repeatedly interrupts and dismisses minority viewpoints. What should the facilitator do?', 'Co-create and enforce observable norms for participation, listening, evidence, challenge, decision making, and repair, then monitor who is heard.', ['Ask quieter members to adapt.', 'Use unwritten norms known only to veterans.', 'End discussion whenever disagreement appears.'], 'Explicit, consistently facilitated norms improve psychological safety, equitable participation, and the quality of collective reasoning.'),
      q('What is a productive approach to conflict?', 'Two departments disagree about shared instructional time. What should the leader do first?', 'Clarify the common student-centered interest, gather constraints and evidence, distinguish positions from needs, and facilitate options with decision criteria.', ['Choose the louder department.', 'Avoid the issue until scheduling closes.', 'Frame one side as unprofessional.'], 'Constructive conflict work focuses on interests, evidence, transparent criteria, and relationships rather than suppression or positional victory.'),
      q('How should leaders repair trust after a process failure?', 'A decision was announced before promised consultation occurred. What is the strongest response?', 'Acknowledge the breach specifically, explain without defensiveness, restore meaningful input where possible, correct the process, and report follow-through.', ['Say that intent should be enough.', 'Remove the consultation promise from records.', 'Hold a celebration to change the subject.'], 'Trust repair requires accountability, voice, corrective action, and consistent future behavior rather than image management.'),
      q('What supports staff well-being without lowering professional expectations?', 'Absence and burnout indicators rise during an initiative. What should leaders examine?', 'Workload, role clarity, schedule, resources, psychological safety, autonomy, support, recognition, and policy while preserving clear student-centered priorities.', ['Offer self-care tips as the only response.', 'Assume stress proves lack of commitment.', 'Remove all accountability.'], 'Well-being is shaped by organizational conditions; leaders address preventable demands and supports while sustaining meaningful standards.'),
      q('How should recognition be used in professional culture?', 'Only highly visible individual achievements receive praise. What is a more inclusive design?', 'Use transparent criteria to recognize varied contributions, collaboration, growth, service, innovation, and student impact without creating unhealthy competition.', ['Recognize favorites privately.', 'Tie every acknowledgment to test rankings.', 'Avoid recognition entirely.'], 'Fair recognition reinforces shared values when criteria are visible, contributions are varied, and incentives do not undermine collaboration.'),
      q('What is psychological safety in a school team?', 'Staff avoid reporting implementation problems because they fear blame. What should the leader model?', 'Invite concerns and mistakes as learning evidence, respond without humiliation, distinguish accountability from blame, and act on reported barriers.', ['Guarantee that no one will ever be evaluated.', 'Ignore errors to preserve comfort.', 'Require anonymous communication only.'], 'Psychological safety supports candor and learning while retaining clear standards, responsibility, and fair response to misconduct.'),
      q('How should leaders manage rumors during uncertainty?', 'A staffing rumor is spreading before decisions are final. What is the best communication response?', 'Share what is known, unknown, confidential, and next, identify the decision process and timeline, correct misinformation, and provide a reliable update channel.', ['Invent reassurance.', 'Disclose confidential personnel details.', 'Remain silent until every detail is final.'], 'Timely bounded transparency reduces speculation while protecting privacy and preserving the integrity of a pending process.'),
      q('What makes collaboration sustainable?', 'A cross-role team succeeds only when the principal attends every meeting. What should be developed?', 'Shared facilitation routines, role clarity, accessible evidence, decision authority, documentation, capacity, and feedback loops that do not depend on one person.', ['More principal control of every agenda.', 'Informal memory instead of records.', 'Permanent dependence on an external consultant.'], 'Sustainable collaboration embeds structures and distributed capacity while maintaining governance and accountability.'),
    ],
  },
  {
    id: 'ethics-professional-norms-equity-decisions', chapterId: 'lead5412-ch-07', domainId: 'ethical-leadership', domain: 'Ethical Leadership',
    label: 'Ethics, Professional Norms, Equity, and Decision Making', references: [ETS, PSEL, CIVIL_RIGHTS],
    questions: [
      q('What is the first step in analyzing an ethical dilemma?', 'A decision could improve average results but reduce access for a smaller group. What should the leader do?', 'Identify affected rights, duties, values, evidence, power differences, alternatives, consequences, and governing requirements before deciding transparently.', ['Choose the option with the highest average only.', 'Follow personal preference without disclosure.', 'Avoid naming the tradeoff.'], 'Ethical analysis makes competing obligations and impacts visible, centers those affected, and integrates law, professional standards, evidence, and transparency.'),
      q('How should a leader handle a personal financial conflict?', 'A principal has a financial interest in a vendor seeking a school contract. What is required?', 'Disclose the interest, follow ethics and procurement rules, preserve an objective process, and recuse when impartiality cannot be maintained.', ['Keep the interest private if the product seems useful.', 'Approve the contract before competitors apply.', 'Use confidential student information in marketing.'], 'Actual and apparent conflicts can undermine trust and fairness; disclosure and required recusal protect the institution and decision process.'),
      q('What does equitable resource allocation mean?', 'A leader proposes equal dollars for programs serving substantially different needs. What should be examined?', 'Use transparent criteria tied to student need, access, program requirements, effectiveness, legal obligations, and opportunity, then monitor distribution and impact.', ['Assume equal amounts always create equity.', 'Allocate based on political influence.', 'Hide the criteria to prevent disagreement.'], 'Equity may require differentiated resources; leaders document the rationale and test whether allocation improves fair access and outcomes.'),
      q('How should leaders use authority ethically?', 'A staff member questions an initiative during a meeting. What response best models ethical authority?', 'Invite evidence and respectful challenge, clarify decision rights, protect against retaliation, and explain how input will inform or not inform the decision.', ['Threaten an unfavorable assignment.', 'End all discussion of the initiative.', 'Promise the staff member final authority.'], 'Ethical authority combines role responsibility with voice, procedural fairness, reason giving, and protection from retaliation.'),
      q('What makes transparency responsible rather than absolute?', 'Families request details about an unresolved personnel matter. What should a leader communicate?', 'Explain the process, applicable standards, timeline, and what can be shared while protecting privacy, due process, safety, and the integrity of the review.', ['Release the entire personnel file.', 'Say nothing about process or timing.', 'Speculate about likely findings.'], 'Responsible transparency provides meaningful process information without violating confidentiality or prejudging an unresolved matter.'),
      q('How should a leader respond to a directive that may conflict with law or policy?', 'A supervisor asks a principal to bypass a required student safeguard. What is the best response?', 'Clarify the directive, consult current policy and qualified authority, document the concern, protect immediate rights and safety, and use established escalation channels.', ['Comply silently because it came from a supervisor.', 'Post the accusation publicly first.', 'Invent a local exception.'], 'Professional responsibility includes lawful implementation, documentation, consultation, and appropriate escalation rather than blind compliance or improvisation.'),
      q('What is ethical evidence use in public communication?', 'A leader wants to promote a program using only its strongest subgroup result. What should happen?', 'Present complete relevant evidence, uncertainty, limitations, subgroup variation, implementation conditions, and conflicts of interest without implying unsupported causation.', ['Select only favorable results.', 'Guarantee the program caused improvement.', 'Remove limitations to simplify the message.'], 'Ethical communication supports informed judgment and avoids manipulating audiences through selective reporting or causal overclaiming.'),
      q('How should intent and impact be considered?', 'A policy was intended to be neutral but creates recurring access barriers. What should the leader do?', 'Examine the impact and governing obligations with affected groups, remove unjustified barriers, document corrective action, and monitor results.', ['Defend the policy solely because intent was neutral.', 'Wait until every person is affected.', 'Blame individuals for not adapting.'], 'Ethical leadership evaluates actual opportunity and consequences in addition to intent and corrects inequitable system effects.'),
    ],
  },
  {
    id: 'law-rights-due-process-privacy', chapterId: 'lead5412-ch-08', domainId: 'ethical-leadership', domain: 'Ethical Leadership',
    label: 'Law, Rights, Due Process, Privacy, and Protected Access', references: [ETS, PSEL, FERPA, IDEA_EVAL, IDEA_MTSS, CIVIL_RIGHTS],
    questions: [
      q('How should identifiable student records be shared internally?', 'A broad staff email is proposed for a detailed student support record. What should the leader require?', 'Verify legitimate educational interest and applicable authority, use the minimum necessary information and a secure method, and follow FERPA and local policy.', ['Share because every employee works for the district.', 'Remove the name but leave uniquely identifying details.', 'Post the record in a shared public folder.'], 'Professional curiosity is not legitimate educational interest; education records require role-based, purpose-limited, secure handling under current law and policy.'),
      q('What is required before relying on a vendor for student data services?', 'A free application requests identifiable student information. What should school leaders examine?', 'Educational purpose, authority or consent, direct control, data minimization, security, use and redisclosure limits, retention, deletion, accessibility, and procurement terms.', ['Accept the default consumer terms immediately.', 'Assume free tools are outside privacy rules.', 'Let each teacher upload any data independently.'], 'Vendor convenience does not remove institutional privacy, security, accessibility, contracting, and oversight responsibilities.'),
      q('How should MTSS relate to special-education evaluation?', 'A team wants to require months of intervention before considering a warranted referral. What should the leader clarify?', 'Provide appropriate supports, but MTSS must not delay or deny a full individual evaluation when a disability is suspected under current requirements.', ['Require every tier before any referral.', 'Treat intervention response as the sole eligibility criterion.', 'Stop general-education support once evaluation begins.'], 'MTSS and evaluation can proceed responsively; federal guidance states that MTSS cannot delay or deny a warranted evaluation.'),
      q('What makes an evaluation process defensible?', 'A team proposes determining disability from one screening score. What should the leader question?', 'Use varied valid tools and strategies, parent information, qualified personnel, nondiscriminatory administration, relevant functional and academic evidence, and no single measure as the sole criterion.', ['Use the fastest measure only.', 'Ignore language and sensory access.', 'Let program availability determine eligibility.'], 'IDEA evaluation procedures require comprehensive, technically sound, nondiscriminatory evidence related to disability and educational need.'),
      q('What is procedural due process in an employment decision?', 'A tenured employee faces serious discipline based on disputed allegations. What should the leader do?', 'Follow current law, contract, and policy for notice, evidence, an opportunity to respond, impartial review, representation rights, documentation, and appeal where applicable.', ['Announce guilt before the process.', 'Destroy notes after the meeting.', 'Substitute rumor for an investigation.'], 'High-stakes employment action requires fair, documented procedures and qualified guidance; exact rights vary by jurisdiction and agreement.'),
      q('How should leaders respond to a request for disability accommodation?', 'A family requests an access support for a student. What is the appropriate first posture?', 'Use the applicable qualified team and current process to gather individualized evidence, engage the family, determine access needs, document decisions, and implement approved supports.', ['Reject the request because grades are passing.', 'Promise a specific plan before evaluation.', 'Let one administrator diagnose eligibility alone.'], 'Accommodation decisions are individualized, participatory, documented, and governed by current law and policy rather than grades or informal diagnosis alone.'),
      q('What should guide response to possible discrimination or retaliation?', 'An employee reports unequal treatment and fears adverse consequences for speaking up. What should a leader do?', 'Activate current reporting and response procedures, protect against retaliation, preserve evidence and appropriate confidentiality, consult qualified authority, and ensure impartial follow-up.', ['Investigate only if the report becomes public.', 'Promise absolute secrecy regardless of process.', 'Change the reporters assignment immediately without review.'], 'Leaders must respond promptly and fairly within current civil-rights, employment, safety, and policy requirements while avoiding retaliation.'),
      q('How should leaders approach changing legal requirements?', 'A study guide and a local policy appear inconsistent. What is the safest decision method?', 'Verify current federal, state, local, board, contract, and agency requirements with qualified authority, then document the controlling rule and implementation plan.', ['Treat the study guide as legal advice.', 'Use the oldest familiar procedure.', 'Assume one states rule applies everywhere.'], 'Legal duties and local implementation can change and vary; leaders verify controlling authority instead of relying on test-prep material or memory.'),
    ],
  },
  {
    id: 'operations-budget-resources-technology', chapterId: 'lead5412-ch-09', domainId: 'organizational-leadership', domain: 'Organizational Leadership',
    label: 'Operations, Budget, Resources, Facilities, and Technology', references: [ETS, PSEL, FERPA, CYBER, EOP],
    questions: [
      q('What makes a school budget strategic?', 'A proposed budget rolls every line forward without reviewing priorities. What should the leader do?', 'Connect expenditures to student needs, legal obligations, strategic goals, evidence of effectiveness, equity, total cost, sustainability, and measurable review.', ['Fund programs only because they are longstanding.', 'Use available money without defining outcomes.', 'Hide tradeoffs from stakeholders.'], 'Strategic budgeting is a transparent allocation process that connects finite resources with priorities, obligations, implementation, and evaluation.'),
      q('How should leaders analyze the total cost of an initiative?', 'A program appears affordable because only its license fee is listed. What else belongs in the analysis?', 'Include staffing, training, substitutes, devices, accessibility, data integration, maintenance, security, opportunity cost, renewal, and exit costs.', ['Ignore staff time because salaries already exist.', 'Assume future renewals will be free.', 'Exclude supports needed for access.'], 'Total-cost analysis prevents hidden implementation demands from undermining feasibility, equity, or sustainability.'),
      q('What is a sound procurement safeguard?', 'A preferred vendor helped write the selection criteria. What should the leader ensure?', 'Use disclosed conflicts, objective requirements, fair competition or authorized exceptions, documented evaluation, required approvals, and contract protections.', ['Guarantee the vendor the award.', 'Delete competing proposals.', 'Use student data during the sales demonstration without authority.'], 'Fair procurement protects public resources, integrity, privacy, and trust through transparent criteria and required controls.'),
      q('How should facility priorities be set?', 'A school has more repair needs than available capital funds. What is the strongest prioritization approach?', 'Use life safety, legal access, instructional impact, condition, risk, affected populations, cost, dependencies, and continuity criteria with transparent documentation.', ['Prioritize the most visible cosmetic project.', 'Allocate by staff popularity vote only.', 'Delay urgent hazards until the next cycle.'], 'Facilities decisions should be risk based, equitable, legally compliant, and connected to learning and continuity rather than appearance or influence.'),
      q('What is a key K-12 cybersecurity leadership responsibility?', 'A principal assumes cybersecurity belongs only to the technology department. What should be added?', 'Establish a shared security culture with multifactor authentication, updates, tested backups, incident response, training, vendor controls, and continuity planning appropriate to role.', ['Publish passwords for easier access.', 'Rely on one untested backup.', 'Keep incidents secret from response personnel.'], 'CISA emphasizes that K-12 cyber resilience requires leadership, prioritized controls, trained users, tested recovery, and coordinated response.'),
      q('How should a leader evaluate schedule efficiency?', 'A master schedule is efficient for adults but blocks some students from advanced courses and services. What should be examined?', 'Analyze access, conflicts, instructional minutes, service obligations, staffing, transitions, student pathways, subgroup participation, and feasible redesigns.', ['Preserve the schedule because it is familiar.', 'Count filled rooms as the only measure.', 'Remove services that create complexity.'], 'Operational efficiency must serve equitable learning, required supports, and strategic priorities rather than optimize one adult-centered metric.'),
      q('What makes operational delegation effective?', 'A principal assigns purchasing approval to a staff member without limits or review. What should be established?', 'Clarify authority, competence, controls, segregation of duties, documentation, thresholds, supervision, escalation, and accountability while retaining nondelegable responsibilities.', ['Allow unlimited informal approval.', 'Delegate responsibility but not information.', 'Avoid any review to show trust.'], 'Delegation distributes work and develops capacity only when authority, controls, support, and accountability are explicit.'),
    ],
  },
  {
    id: 'personnel-safety-crisis-continuity', chapterId: 'lead5412-ch-10', domainId: 'organizational-leadership', domain: 'Organizational Leadership',
    label: 'Personnel Systems, Safety, Crisis Response, and Continuity', references: [ETS, PSEL, EOP, CYBER, CIVIL_RIGHTS],
    questions: [
      q('What makes a personnel selection process defensible?', 'A hiring team wants to choose a familiar candidate before interviews. What should the leader require?', 'Use job-related criteria, structured evidence, trained diverse reviewers, consistent procedures, reference checks, documented reasoning, accessibility, and current employment requirements.', ['Use personal familiarity as the main criterion.', 'Ask different protected-status questions of each candidate.', 'Discard interview records immediately.'], 'A fair selection system links evidence to role requirements and applies transparent, consistent, lawful procedures that reduce arbitrary influence.'),
      q('How should an employee performance concern be addressed?', 'A supervisor has repeated concerns but has provided no specific feedback. What should happen?', 'Document job-related evidence, clarify expectations, hear the employee response, provide support and timelines, monitor progress, and follow current contract, policy, and due process.', ['Build a secret case until dismissal.', 'Discuss the employee publicly.', 'Use student rumors as the sole evidence.'], 'Effective supervision is timely, evidence based, developmental, documented, and procedurally fair; exact requirements vary by jurisdiction and agreement.'),
      q('What is the foundation of a high-quality emergency operations plan?', 'A school emergency plan was copied from another campus and has never been exercised. What should leaders do?', 'Develop a collaborative, site-specific emergency operations plan that defines risk, roles, communication, access, reunification, training, exercises, evidence-based revision, and recovery.', ['Rely on the copied plan without review.', 'Keep roles unknown to avoid alarm.', 'Plan only for the initial response.'], 'Federal guidance describes comprehensive, collaborative, regularly reviewed EOPs supported by training, exercises, accessible procedures, and recovery planning.'),
      q('How should leaders communicate during an active emergency?', 'Unverified information is spreading during an incident. What is the best leadership approach?', 'Follow the incident communication plan, coordinate with authorized responders, prioritize life safety, share verified accessible updates, protect sensitive details, and document decisions.', ['Post speculation immediately.', 'Use several conflicting unofficial channels.', 'Delay all communication until the incident ends.'], 'Crisis communication must be timely, coordinated, accurate, accessible, and bounded by safety, privacy, and operational needs.'),
      q('What belongs in continuity planning?', 'A cyber incident makes core systems unavailable for several days. What should the school have prepared?', 'Prioritized essential functions, offline contacts and procedures, tested backups, alternative instructional and operational workflows, decision authority, communications, restoration criteria, and after-action review.', ['A single online copy of the plan.', 'Dependence on one unavailable employee.', 'Restoration without checking integrity.'], 'Continuity planning identifies essential services and rehearsed alternatives so learning, safety, communication, and recovery can continue through disruption.'),
      q('How should after-action review be conducted?', 'A drill exposes delayed assistance for students needing mobility supports. What is the correct response?', 'Document the gap without blame, involve affected participants and qualified personnel, assign corrective actions and owners, revise the plan, retrain, and exercise the change.', ['Remove the finding from the report.', 'Repeat the identical drill without changes.', 'Assume individuals will improvise next time.'], 'Exercises create value when leaders convert evidence into accessible corrective action, accountability, retraining, and a new test of the system.'),
    ],
  },
  {
    id: 'family-engagement-communication-partnerships', chapterId: 'lead5412-ch-11', domainId: 'community-engagement-leadership', domain: 'Community Engagement Leadership',
    label: 'Family Engagement, Communication, and Reciprocal Partnerships', references: [ETS, PSEL, FAMILY_ENGAGEMENT, FERPA],
    questions: [
      q('What makes family engagement reciprocal?', 'A school contacts families mainly when it needs volunteers. What should change?', 'Learn family goals, knowledge, languages, access needs, and experiences; co-design meaningful roles and maintain two-way communication tied to student learning and well-being.', ['Send more one-way reminders.', 'Limit engagement to fundraising.', 'Assume attendance at events measures partnership.'], 'Reciprocal engagement treats families as knowledgeable partners with influence, accessible communication, shared learning goals, and ongoing feedback.'),
      q('How should leaders reduce participation barriers?', 'Evening meetings attract the same small group of families. What should the school examine?', 'Use participation data and family input to vary time, format, location, language, childcare, transportation, technology, outreach, and decision pathways.', ['Conclude other families are uninterested.', 'Keep the format unchanged for consistency.', 'Require families to find their own interpreters.'], 'Equitable engagement changes institutional access conditions and offers multiple meaningful ways to participate rather than blaming families.'),
      q('What is effective crisis communication with families?', 'A water problem changes dismissal procedures. What should leaders communicate?', 'Provide prompt verified plain-language information through accessible channels about the issue, immediate actions, student safety, family responsibilities, supports, and next update.', ['Wait for rumors to settle.', 'Share technical detail without action steps.', 'Use only a channel many families cannot access.'], 'Families need timely, accurate, actionable, accessible updates with a reliable feedback and update process.'),
      q('How should a leader respond to a contentious public meeting?', 'Speakers are angry about a proposed boundary change. What facilitation best protects participation?', 'State the decision process and constraints, enforce viewpoint-neutral safety and time norms, provide accessible evidence, listen for interests and impacts, and document follow-up.', ['Allow threats because the topic is emotional.', 'Silence all criticism of the proposal.', 'Promise an outcome before governance review.'], 'Leaders can protect vigorous participation while maintaining safety, fairness, transparency, and the lawful decision process.'),
      q('What makes a school-community partnership strategic?', 'A nonprofit offers a popular program unrelated to current school needs. What should the leader examine?', 'Alignment with identified needs and goals, evidence, access, roles, safeguarding, data terms, capacity, cost, accountability, and sustainability before agreement.', ['Accept any donated program.', 'Share student records to secure the offer.', 'Let the partner define school priorities.'], 'Partnerships add value when mission alignment, protections, reciprocal responsibilities, implementation, and evaluation are explicit.'),
      q('How should family feedback be closed into a loop?', 'A survey is administered annually, but families never hear what happened. What is missing?', 'Report representative findings and limitations, explain decisions and constraints, identify actions and owners, invite continued input, and monitor whether access and trust improve.', ['Publish only favorable comments.', 'Collect more data without responding.', 'Promise every request will be implemented.'], 'A feedback loop demonstrates that participation has been considered, makes tradeoffs visible, and creates accountability for action and continued learning.'),
      q('What is appropriate communication about an individual student?', 'A community partner asks for a detailed student record to tailor services. What should the leader do?', 'Determine the educational purpose and governing authority or consent, share only necessary information securely, document required terms, and verify privacy responsibilities.', ['Send the entire file because the partner is helpful.', 'Use a verbal agreement to avoid documentation.', 'Assume de-identification when names are removed but identity remains obvious.'], 'Community partnership does not erase FERPA, consent, data-minimization, security, contracting, and redisclosure requirements.'),
    ],
  },
  {
    id: 'community-advocacy-governance-accountability', chapterId: 'lead5412-ch-12', domainId: 'community-engagement-leadership', domain: 'Community Engagement Leadership',
    label: 'Community Assets, Advocacy, Governance, and Public Accountability', references: [ETS, PSEL, FAMILY_ENGAGEMENT, CIVIL_RIGHTS, CONTINUOUS_IMPROVEMENT],
    questions: [
      q('How should leaders map community assets?', 'A school describes its neighborhood only through needs and deficits. What is a stronger approach?', 'Identify organizations, cultural and linguistic knowledge, trusted leaders, services, spaces, networks, student and family strengths, access conditions, and partnership gaps with community members.', ['List only problems from public data.', 'Assume formal organizations represent everyone.', 'Treat families as service recipients only.'], 'Asset mapping recognizes community capacity and relationships while still examining unmet needs, access, representation, and fit with school goals.'),
      q('What makes educational advocacy evidence based?', 'A leader seeks additional mental-health resources after several urgent incidents. What should the case include?', 'Combine lived experience with disaggregated need and access data, service capacity, research, legal and equity analysis, resource implications, implementation design, and measurable follow-up.', ['Use one story as proof of total prevalence.', 'Promise the resource will solve every problem.', 'Exclude affected students and families.'], 'Responsible advocacy integrates multiple forms of evidence, names uncertainty, centers affected communities, and proposes an implementable, evaluable response.'),
      q('How should a school leader work within governance?', 'A board adopts a policy the principal believes will create implementation problems. What is the professional response?', 'Clarify the policy and authority, provide evidence and implementation implications through proper channels, carry out lawful direction, document concerns, and monitor effects.', ['Ignore the policy privately.', 'Attack individual board members publicly.', 'Invent a contradictory school rule.'], 'School leaders exercise professional judgment within lawful governance by advising candidly, implementing authorized decisions, and reporting evidence through established channels.'),
      q('What does public accountability require?', 'A school improvement report highlights gains but omits missed targets and subgroup access problems. What should be added?', 'Present complete relevant outcomes, opportunity and implementation evidence, subgroup patterns, limitations, corrective actions, owners, timelines, and ways stakeholders can respond.', ['Remove difficult findings to protect morale.', 'Attribute every miss to families.', 'Report activities instead of results.'], 'Public accountability is transparent about progress and gaps and connects evidence to responsibility, corrective action, and continued participation.'),
      q('How should leaders assess representation in advisory groups?', 'A council has open membership but consistently excludes families most affected by its decisions. What should happen?', 'Analyze participation barriers and influence, conduct trusted targeted outreach, provide access supports, redesign selection and meeting processes, and monitor whose input affects decisions.', ['Claim openness alone guarantees representation.', 'Appoint one person to speak for every group.', 'Stop collecting demographic participation data.'], 'Formal openness may not create meaningful access; leaders examine representation, power, barriers, and actual influence.'),
      q('How should a partnership be ended responsibly?', 'A community program no longer meets agreed outcomes and has unresolved data-security concerns. What should the school do?', 'Follow the agreement and governing requirements, protect students and records, communicate evidence and transition plans, preserve essential supports, document closure, and review lessons.', ['Continue indefinitely to avoid conflict.', 'Delete all records without checking retention duties.', 'End services overnight without a transition.'], 'Responsible exit protects students, privacy, continuity, contractual duties, relationships, and institutional learning while acting on evidence and risk.'),
    ],
  },
];

module.exports = banks;
module.exports.sources = { ETS, PSEL, CONTINUOUS_IMPROVEMENT, FERPA, IDEA_EVAL, IDEA_MTSS, CIVIL_RIGHTS, EOP, CYBER, FAMILY_ENGAGEMENT };
