const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const base=pathToFileURL(path.join(__dirname,'current-preview.html')).href;
async function main(){const browser=await chromium.launch({headless:true});const results={states:[],errors:[],calls:[]};try{
 async function open(width,query=''){const page=await browser.newPage({viewport:{width,height:900}});page.setDefaultTimeout(18000);page.on('pageerror',error=>results.errors.push(error.message));await page.goto(base+'?pass=8&'+query);await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});return page;}
 async function audit(page,label){const state=await page.evaluate(async()=>({width:innerWidth,pageWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,firstField:Math.round((document.querySelector('textarea')?.getBoundingClientRect().top||0)+scrollY),active:document.activeElement.id,violations:(await axe.run(document.querySelector('#root'),{rules:{region:{enabled:false}}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))}));assert.equal(state.pageWidth,state.width,label+' overflow');assert.deepEqual(state.violations,[],label+' accessibility');results.states.push({label,...state});}
 async function review(page){await page.getByRole('button',{name:'5. Reflect',exact:true}).click();await page.getByRole('button',{name:'Review my response',exact:true}).click();}
 for(const width of [1280,390,320]){
  const page=await open(width);await audit(page,'Initial '+width);await page.screenshot({path:path.join(__dirname,'pass8-start-'+width+'.png'),fullPage:true});
  await page.getByRole('button',{name:'Start writing',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'applied-workspace-workingQuestion');await page.locator('#applied-workspace-workingQuestion').fill('Which watering plan should we compare?');
  const reference=page.locator('details.aps-reference');await reference.locator(':scope > summary').click();await reference.getByText('Lesson ideas',{exact:true}).click();assert(await reference.getByText('Water can enter the soil through infiltration.',{exact:true}).isVisible());await reference.getByRole('button',{name:'Return to my writing',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'applied-workspace-workingQuestion');
  await page.getByRole('button',{name:'3. Build',exact:true}).click();await page.getByRole('button',{name:'Use a sketch, model, or recording',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'applied-artifact-url');assert(await page.locator('#applied-artifact-url').isVisible());await page.getByRole('button',{name:'Write here',exact:true}).click();
  await page.locator('#applied-workspace-response').fill('Infiltration affects runoff. No local trial has happened yet. Keep a small comparison as the next step because local conditions are unknown. This also helps us compare drainage for a sports field.');await review(page);
  for(const part of ['Lesson connection','What I checked','Keep or revise, and why','Where else this could help']){
    const summary=page.getByLabel('Point to existing reasoning: '+part,{exact:true});await summary.click();const editor=summary.locator('..');await editor.getByLabel(part+': Passage or location',{exact:true}).fill('Paragraph 1');await editor.getByRole('button',{name:'Save my reference',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Save my reference');await summary.click();
  }
  assert.equal(await page.locator('#aps-next-improvement-heading').count(),0);assert.equal(await page.getByText('Pointed to in my response',{exact:true}).count(),4);await audit(page,'Referenced review '+width);await page.screenshot({path:path.join(__dirname,'pass8-review-'+width+'.png'),fullPage:true});
  await page.getByRole('button',{name:'Lesson connection Pointed to in my response',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'applied-workspace-response');await page.locator('#applied-workspace-response').fill('Revised reasoning. The soil is still unknown.');await page.getByRole('button',{name:'Return to my review',exact:true}).click();assert.equal(await page.getByText('Recheck my reference',{exact:true}).count(),4);await audit(page,'Changed reference '+width);
  const roundTrip=await page.evaluate(()=>{const AC=window.AlloModules.AppliedChallenge,SR=window.AlloModules.StudioResponse,response=window.reviewResponses[window.reviewResource.id].studio;const json=SR.serializeBackup(window.reviewResource,response);const restored=SR.readBackup(window.reviewResource,JSON.parse(json),response);return {count:restored.reasoningReferences.length,leaked:json.includes('REVIEW_PRIVATE_SOURCE'),text:restored.workspace.response,ai:window.reviewAiPrompts.length,search:window.reviewSearchQueries.length};});assert.equal(roundTrip.count,4);assert.equal(roundTrip.leaked,false);assert.equal(roundTrip.ai,0);assert.equal(roundTrip.search,0);results.calls.push(roundTrip);await page.close();
 }
 const plain=await open(390,'plain');await plain.getByRole('button',{name:'2. Explore',exact:true}).click();await plain.getByText('Find outside evidence',{exact:true}).click();await plain.getByText('Start from a question we still need to answer',{exact:true}).click();await plain.getByRole('button',{name:'How quickly does the garden soil absorb water?',exact:true}).click();assert.equal(await plain.evaluate(()=>window.reviewSearchQueries.length),0);await plain.getByRole('button',{name:'Search for sources',exact:true}).click();await plain.getByRole('button',{name:'Add reference to my evidence',exact:true}).first().click();assert.equal(await plain.evaluate(()=>document.activeElement.id),'applied-workspace-evidence');const value=await plain.locator('#applied-workspace-evidence').inputValue();assert(value.includes('https://example.org/soil-water'));assert.equal(await plain.evaluate(()=>(Object.values(window.reviewResponses)[0].studio.evidenceLedger || []).length),0);await audit(plain,'Search without organizer');await plain.screenshot({path:path.join(__dirname,'pass8-notes-search-390.png'),fullPage:true});await plain.close();
 const setup=await open(390,'setup');assert(await setup.getByLabel('Available time',{exact:false}).isVisible());await audit(setup,'Teacher setup');await setup.screenshot({path:path.join(__dirname,'pass8-setup-390.png'),fullPage:true});await setup.close();
 assert.deepEqual(results.errors,[]);fs.writeFileSync(path.join(__dirname,'pass8-browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));
 }finally{await browser.close();}}
main().catch(error=>{console.error(error);process.exitCode=1;});
