
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=process.cwd(),out=path.join(root,'reports/circuit-enhancement');
(async()=>{
const browser=await chromium.launch({headless:true});
try{
const page=await browser.newPage({viewport:{width:1280,height:1000},reducedMotion:'reduce'});
const errors=[]; page.on('pageerror',e=>{errors.push(e.message);console.error('Page error:',e.message);});
await page.setContent('<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Circuit bench review</title></head><body><main id="root"></main></body></html>');
await page.addStyleTag({path:path.join(root,'dev-tools/.cache/sweep-tailwind.css')});
await page.addStyleTag({content:'body{margin:0;background:#070f1b;font-family:system-ui}#root{max-width:960px;margin:20px auto;padding:12px}*{box-sizing:border-box}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #facc15;outline-offset:3px}'});
await page.addScriptTag({path:path.join(root,'desktop/web-app/node_modules/react/umd/react.development.js')});
await page.addScriptTag({path:path.join(root,'desktop/web-app/node_modules/react-dom/umd/react-dom.development.js')});
await page.addScriptTag({path:path.join(root,'stem_lab/stem_tool_circuit.js')});
await page.evaluate(()=>{
const noop=()=>{},icons=new Proxy({},{get:()=>()=>React.createElement('span')});
function Host(){
const [data,setData]=React.useState({_circuit:{pauseMotion:true}});
window.state=data;window.setState=setData;
return StemLab._registry.circuit.render({React,icons,toolData:data,setToolData:setData,t:(k,f)=>f||k,gradeLevel:'8',
addToast:noop,awardXP:noop,announceToSR:noop,a11yClick:f=>({onClick:f}),setStemLabTool:noop,setStemLabTab:noop,setToolSnapshots:noop});
}
ReactDOM.createRoot(document.querySelector('#root')).render(React.createElement(Host));
});
await page.getByRole('heading',{name:'Small circuits. Big discoveries.'}).waitFor();









await page.getByRole('button',{name:'Connected circuits',exact:true}).click();






const results={scenarios:[],axe:[]},board=page.getByRole('region',{name:'Scrollable connected circuit board',exact:true}),panel=page.getByRole('region',{name:'Node connection inspector',exact:true});
const click=async name=>page.getByRole('button',{name,exact:true}).click();const load=async id=>{await page.getByLabel('Connected circuit example',{exact:true}).selectOption(id);await click('Load network example');assert.equal(await page.locator('.circuit-network-status').getAttribute('data-ok'),'true');};
const stable=()=>page.evaluate(()=>JSON.stringify({components:state._circuitNetwork.components,undo:state._circuitNetwork.undo,redo:state._circuitNetwork.redo,scopeView:state._circuitNetwork.scopeView,scopeMeasure:state._circuitNetwork.scopeMeasure}));const probes=()=>page.evaluate(()=>[state._circuitNetwork.probeRed,state._circuitNetwork.probeBlack]);
const feeder={analysis:'dc',selected:1,probeRed:'C',probeBlack:'A',scopeView:{start:.2,end:.6},components:[{id:1,type:'voltage',a:'A',b:'0',value:12},{id:2,type:'resistor',a:'A',b:'B',value:100},{id:3,type:'resistor',a:'B',b:'0',value:300},{id:4,type:'resistor',a:'B',b:'0',value:600}]};await page.evaluate(d=>setState(prev=>({...prev,_circuitNetwork:d})),feeder);const before=await stable(),meter=await probes();await click('Inspect network nodes');assert.equal(await page.getByLabel('Inspected network node',{exact:true}).inputValue(),'A');await board.getByRole('button',{name:'Inspect node B',exact:true}).click();assert.deepEqual(await probes(),meter);assert.equal(await panel.locator('[data-node-connection]').count(),3);assert.equal(await board.locator('[data-node-highlight=true]').count(),3);assert.equal(await board.locator('[data-node-arrow=in]').count(),1);assert.equal(await board.locator('[data-node-arrow=out]').count(),2);assert.equal(await board.locator('[data-terminal-route="2:B"]').getAttribute('data-node-flow'),'in');assert.match(await panel.innerText(),/40.00 mA/);
await click('Select R2 terminal B');assert.equal(await page.getByLabel('Board component',{exact:true}).inputValue(),'2');assert.equal(await page.getByLabel('Inspected network node',{exact:true}).inputValue(),'B');assert.equal(await stable(),before);await click('Focus inspected node');assert.equal(await page.evaluate(()=>document.activeElement.dataset.nodeId),'B');await board.screenshot({path:path.join(out,'nodes34-feeder-board.jpg'),type:'jpeg',quality:93});await panel.screenshot({path:path.join(out,'nodes34-feeder-panel.jpg'),type:'jpeg',quality:92});
await click('Measure node relative to 0');assert.deepEqual(await probes(),['B','0']);assert.match(await page.getByLabel('Connected voltmeter reading',{exact:true}).innerText(),/8.00V/);await click('Finish inspecting');await page.waitForFunction(()=>document.activeElement&&document.activeElement.hasAttribute('data-node-inspection-toggle'));assert.equal(await panel.count(),0);await click('Place network black probe');await board.getByRole('button',{name:'Place black probe on node A',exact:true}).click();assert.deepEqual(await probes(),['B','A']);await click('Inspect network nodes');assert.equal(await page.getByLabel('Inspected network node',{exact:true}).inputValue(),'B');assert.deepEqual(await probes(),['B','A']);results.scenarios.push('Per-terminal flow at a shared feeder, stable inspected node during branch selection, focus centering, explicit probe measurement and keyboard focus on close');
await load('switch-flyback');await page.getByLabel('Inspected network node',{exact:true}).selectOption('B');await page.getByLabel('Board switch event',{exact:true}).selectOption('0');assert.equal(await board.locator('[data-terminal-route="3:A"]').getAttribute('data-node-flow'),'out');await click('After switch on board');assert.equal(await board.locator('[data-terminal-route="3:A"]').getAttribute('data-node-flow'),'in');assert.equal(await board.locator('[data-terminal-route="2:B"]').getAttribute('data-node-flow'),'zero');assert.equal(await board.locator('[data-arrow-terminal="2:B"]').count(),0);assert.match(await panel.innerText(),/after switching/);await click('Stored energy');assert.equal(await page.getByRole('region',{name:'Stored energy explorer',exact:true}).count(),1);assert.equal(await board.locator('[data-network-energy]').count(),1);await board.screenshot({path:path.join(out,'nodes34-flyback-board.jpg'),type:'jpeg',quality:93});await panel.screenshot({path:path.join(out,'nodes34-flyback-panel.jpg'),type:'jpeg',quality:92});
await click('Node voltages');const colors=await board.locator('[data-terminal-route] > path:nth-child(2)').evaluateAll(paths=>paths.map(p=>p.getAttribute('stroke')));await click('Finish inspecting');assert.deepEqual(await board.locator('[data-terminal-route] > path:nth-child(2)').evaluateAll(paths=>paths.map(p=>p.getAttribute('stroke'))),colors);await click('Inspect network nodes');results.scenarios.push('Switch snapshots reverse resistor flow correctly; open contacts have no arrow; energy and node-voltage overlays remain compatible');
await page.evaluate(()=>setState(prev=>({...prev,_circuitNetwork:{analysis:'dc',boardNodeMode:'inspect',inspectNode:'F',selected:1,components:[{id:1,type:'voltage',a:'F',b:'0',value:2},{id:2,type:'vcvs',a:'B',b:'0',value:3,control:{positive:'F',negative:'0'}},{id:3,type:'resistor',a:'B',b:'0',value:1000}]}})));assert.equal(await panel.locator('[data-node-connection]').count(),1);assert.match(await panel.innerText(),/Voltage-sensing connections/);assert.equal(await board.locator('[data-network-sense]').count(),1);assert.equal(await board.locator('[data-node-arrow]').count(),0);await click('Select E2 positive sense');assert.equal(await page.getByLabel('Board component',{exact:true}).inputValue(),'2');assert.equal(await page.getByLabel('Inspected network node',{exact:true}).inputValue(),'F');await panel.screenshot({path:path.join(out,'nodes34-sensing-panel.jpg'),type:'jpeg',quality:92});results.scenarios.push('Voltage-sensing inputs are highlighted separately and excluded from branch current totals');
await page.evaluate(()=>setState(prev=>({...prev,_circuitNetwork:{analysis:'dc',boardNodeMode:'inspect',inspectNode:'B',components:[{id:1,type:'voltage',a:'A',b:'B',value:5},{id:2,type:'resistor',a:'A',b:'B',value:1000}]}})));assert.equal(await page.getByLabel('Inspected node voltage',{exact:true}).innerText(),'Undetermined');assert.match(await panel.innerText(),/5.00 mA/);assert.equal(await panel.locator('.circuit-network-node-notice').count(),0);
await page.evaluate(()=>setState(prev=>({...prev,_circuitNetwork:{analysis:'dc',boardNodeMode:'inspect',inspectNode:'A',components:[{id:1,type:'voltage',a:'A',b:'0',value:5},{id:2,type:'voltage',a:'A',b:'0',value:5},{id:3,type:'resistor',a:'A',b:'0',value:1000}]}})));assert.equal(await panel.locator('[data-node-direction=unknown]').count(),2);assert.match(await panel.locator('.circuit-network-node-balance').innerText(),/Undetermined/);assert.equal(await board.locator('[data-node-arrow]').count(),1);await page.evaluate(()=>setState(prev=>({...prev,_circuitNetwork:{...prev._circuitNetwork,components:prev._circuitNetwork.components.map(p=>p.id===2?{...p,value:3}:p)}})));assert.equal(await board.locator('[data-node-arrow]').count(),0);assert.equal(await page.getByLabel('Inspected node voltage',{exact:true}).innerText(),'Undetermined');results.scenarios.push('Known currents in floating circuits, unknown ideal-source sharing, and failed-solution suppression');
await page.evaluate(d=>setState(prev=>({...prev,_circuitNetwork:{...d,boardNodeMode:'inspect',inspectNode:'B'}})),feeder);await page.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});for(const width of [1280,390,320]){await page.setViewportSize({width,height:1000});await click('Focus inspected node');assert.equal(await page.evaluate(()=>{const box=document.activeElement.getBoundingClientRect(),view=document.activeElement.closest('.circuit-network-scroll').getBoundingClientRect();return box.left>=view.left&&box.right<=view.right&&box.top>=view.top&&box.bottom<=view.bottom;}),true);await panel.screenshot({path:path.join(out,'nodes34-panel-'+width+'.jpg'),type:'jpeg',quality:91});await board.screenshot({path:path.join(out,'nodes34-board-'+width+'.jpg'),type:'jpeg',quality:91});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);const violations=await page.evaluate(async()=>{const r=await axe.run('.circuit-network-root',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.html)}));});results.axe.push({width,violations});assert.deepEqual(violations,[]);}
await click('Flat network map');assert.equal(await board.locator('[data-node-highlight=true]').count(),3);await click('3D network board');await click('Right perspective');await click('Emphasize selected');assert.equal(await board.locator('[data-node-highlight=true]').count(),3);const saved=await page.evaluate(()=>JSON.stringify(state));await click('Finish inspecting');await page.evaluate(saved=>setState(JSON.parse(saved)),saved);assert.equal(await page.getByLabel('Inspected network node',{exact:true}).inputValue(),'B');await panel.getByText('Why entering and leaving currents match',{exact:true}).click();assert.match(await panel.innerText(),/both are listed/);results.scenarios.push('Desktop/phone accessibility and focus containment, flat/camera/emphasis compatibility, saved inspection state and current-conservation explanation');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'nodes34-browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
