
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=process.cwd(),out=path.join(root,'reports/circuit-enhancement');
(async()=>{
const browser=await chromium.launch({headless:true});
try{
const page=await browser.newPage({viewport:{width:1280,height:1000},reducedMotion:'reduce'});
const errors=[]; page.on('pageerror',e=>{errors.push(e.message);console.error('Page error:',e.message);});
await page.setContent('<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Circuit bench review</title></head><body><main id="root"></main></body></html>');
await page.addStyleTag({path:path.join(root,'dev-tools/.cache/sweep-tailwind.css')});
await page.addStyleTag({content:'body{margin:0;background:#070f1b;font-family:system-ui}#root{max-width:960px;margin:20px auto;padding:12px}*{box-sizing:border-box}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #facc15;outline-offset:3px}'});
await page.addScriptTag({path:path.join(root,'desktop/web-app/node_modules/react/umd/react.development.js')});
await page.addScriptTag({path:path.join(root,'desktop/web-app/node_modules/react-dom/umd/react-dom.development.js')});
await page.addScriptTag({path:path.join(root,'stem_lab/stem_tool_circuit.js')});
await page.evaluate(()=>{
const noop=()=>{},icons=new Proxy({},{get:()=>()=>React.createElement('span')});
function Host(){
const [data,setData]=React.useState({_circuit:{pauseMotion:true}});
window.state=data;window.setState=setData;
return StemLab._registry.circuit.render({React,icons,toolData:data,setToolData:setData,t:(k,f)=>f||k,gradeLevel:'8',
addToast:noop,awardXP:noop,announceToSR:noop,a11yClick:f=>({onClick:f}),setStemLabTool:noop,setStemLabTab:noop,setToolSnapshots:noop});
}
ReactDOM.createRoot(document.querySelector('#root')).render(React.createElement(Host));
});
await page.getByRole('heading',{name:'Small circuits. Big discoveries.'}).waitFor();






await page.getByRole('button',{name:'Active electronics',exact:true}).click();
const active=page.locator('.circuit-active-root'),book=page.locator('.circuit-active-notebook'),records=page.locator('.circuit-notebook-observation');
const calc=()=>page.evaluate(()=>StemLab.solveActiveCircuit(state._circuitActive));
const savedState=()=>page.evaluate(()=>JSON.stringify(StemLab.circuitActiveInvestigation(state._circuitActive)));
await page.getByRole('button',{name:'Input 1 V',exact:true}).click();await page.getByRole('button',{name:'Measure base resistor',exact:true}).click();await page.getByRole('button',{name:'Reverse active probes',exact:true}).click();
const history=await page.evaluate(()=>JSON.stringify(state._circuitActive.undo));await page.getByRole('button',{name:'Record operating point',exact:true}).click();assert.equal(await page.evaluate(()=>state._circuitActive.observations.length),1);assert.equal(await page.evaluate(()=>JSON.stringify(state._circuitActive.undo)),history);
await page.getByRole('button',{name:'Open investigation notebook',exact:true}).click();assert.equal(await book.getAttribute('open'),'');
await page.getByLabel('Investigation title',{exact:true}).fill('A small input controls a larger current');await page.getByLabel('My investigation question',{exact:true}).fill('How does raising the input change lamp current when the supply and resistors stay the same?');await page.getByLabel('My prediction',{exact:true}).fill('The lamp current will increase because more base current flows.');await records.nth(0).locator('summary').click();await page.getByLabel('Observation 1 note',{exact:true}).fill('At 1.0 V, the lamp carries 3 mA. The reversed probes read −0.30 V across the base resistor.');assert.match(await records.first().innerText(),/-300.00 mV/);
await page.getByLabel('Graph input voltage (V) exact value',{exact:true}).fill('1.5');await page.getByLabel('Graph input voltage (V) exact value',{exact:true}).press('Enter');await page.getByRole('button',{name:'Measure transistor',exact:true}).click();await page.getByRole('button',{name:'Record operating point',exact:true}).click();await records.nth(1).locator('summary').click();await page.getByLabel('Observation 2 note',{exact:true}).fill('At 1.5 V, the lamp carries 8 mA and VCE drops to 3.24 V.');
assert.equal(await page.evaluate(()=>state._circuitActive.observations[0].design.input),1);assert.match(await records.first().innerText(),/3.00 mA/);await page.getByRole('button',{name:'Use observation 1 as reference',exact:true}).click();assert.equal((await calc()).design.input,1.5);assert.equal(await page.evaluate(()=>state._circuitActive.reference.design.input),1);
await page.getByRole('button',{name:'Revisit observation 1',exact:true}).click();assert.equal((await calc()).design.input,1);assert.equal(await page.evaluate(()=>state._circuitActive.probeRed),'base');await page.getByRole('button',{name:'Undo active edit',exact:true}).click();assert.equal((await calc()).design.input,1.5);
await page.getByRole('button',{name:'Remove observation 1',exact:true}).click();assert.equal(await records.count(),1);assert.equal(await page.evaluate(()=>state._circuitActive.observations[0].design.input),1.5);await page.getByRole('button',{name:'Undo removed observation',exact:true}).click();assert.equal(await records.count(),2);assert.equal(await page.evaluate(()=>state._circuitActive.observations[0].design.input),1);
await page.getByLabel('My evidence-based explanation',{exact:true}).fill('The prediction was supported: lamp current rose from 3 mA to 8 mA. Only input voltage changed; the 5 V supply, 10 kΩ base resistor, and 220 Ω lamp stayed fixed. The supply provides the lamp energy.');assert.match(await page.getByLabel('Transistor experiment explanation',{exact:true}).inputValue(),/prediction was supported/);
const download=async(name,file)=>{const promise=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();const d=await promise;await d.saveAs(path.join(out,file));};
await download('Save investigation JSON','notebook20-investigation.json');const doc=JSON.parse(fs.readFileSync(path.join(out,'notebook20-investigation.json'),'utf8'));assert.equal(doc.format,'circuit-investigation-v1');assert.equal(doc.notebook.observations.length,2);assert.equal(doc.reference.design.input,1);assert.equal(doc.notebook.title,'A small input controls a larger current');
await download('Download investigation report','notebook20-report.html');const html=fs.readFileSync(path.join(out,'notebook20-report.html'),'utf8');assert.ok(html.includes('3.00 mA'));assert.ok(html.includes('8.00 mA'));assert.ok(html.includes('5 V'));assert.ok(!html.includes('<script'));
await book.screenshot({path:path.join(out,'notebook-desktop.jpg'),type:'jpeg',quality:88});await page.locator('.circuit-notebook-observations').screenshot({path:path.join(out,'notebook-observations-desktop.jpg'),type:'jpeg',quality:90});
const file=page.getByLabel('Open investigation file',{exact:true}),beforeOpen=await savedState();
await file.setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await book.getByRole('alert').filter({hasText:'not valid JSON'}).waitFor();assert.equal(await savedState(),beforeOpen);assert.equal(await page.getByRole('button',{name:'Load investigation',exact:true}).count(),0);
const invalid=structuredClone(doc);invalid.design.supply=999;await file.setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await book.getByRole('alert').filter({hasText:'invalid supply'}).waitFor();assert.equal(await savedState(),beforeOpen);
await file.setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(131073,32)});await book.getByRole('alert').filter({hasText:'128 KB'}).waitFor();assert.equal(await savedState(),beforeOpen);
await page.getByLabel('Investigation title',{exact:true}).fill('Unsaved second investigation');await page.getByLabel('Input voltage (V) exact value',{exact:true}).fill('2');await page.getByLabel('Input voltage (V) exact value',{exact:true}).press('Enter');const beforeLoad=await savedState();
await file.setInputFiles(path.join(out,'notebook20-investigation.json'));await page.getByRole('button',{name:'Load investigation',exact:true}).waitFor();assert.equal(await savedState(),beforeLoad);await page.locator('.circuit-notebook-preview').screenshot({path:path.join(out,'notebook-import-preview.jpg'),type:'jpeg',quality:90});await page.getByRole('button',{name:'Dismiss investigation preview',exact:true}).click();assert.equal(await savedState(),beforeLoad);
await file.setInputFiles(path.join(out,'notebook20-investigation.json'));await page.getByRole('button',{name:'Load investigation',exact:true}).click();assert.equal((await calc()).design.input,1.5);assert.equal(await page.getByLabel('Investigation title',{exact:true}).inputValue(),doc.notebook.title);assert.equal(await records.count(),2);assert.equal(await page.getByRole('button',{name:'Undo active edit',exact:true}).isDisabled(),true);
await page.getByRole('button',{name:'Restore previous investigation',exact:true}).click();assert.equal(await savedState(),beforeLoad);assert.equal(await page.getByRole('button',{name:'Restore previous investigation',exact:true}).count(),0);
await file.setInputFiles(path.join(out,'notebook20-investigation.json'));await page.getByRole('button',{name:'Load investigation',exact:true}).click();assert.equal(await savedState(),JSON.stringify(doc));
await page.getByRole('button',{name:'Mixed circuits',exact:true}).click();await page.getByRole('button',{name:'Active electronics',exact:true}).click();assert.equal(await savedState(),JSON.stringify(doc));
// Loading a new investigation replaces only this workspace and stale async file reads never win.
await page.evaluate(()=>{window.savedFileText=File.prototype.text;window.pendingInvestigationReads=[];File.prototype.text=function(){return new Promise(resolve=>pendingInvestigationReads.push(resolve));};});
await file.setInputFiles({name:'first.json',mimeType:'application/json',buffer:Buffer.from('{}')});await file.setInputFiles({name:'second.json',mimeType:'application/json',buffer:Buffer.from('{}')});
await page.evaluate(d=>pendingInvestigationReads[1](JSON.stringify({...d,notebook:{...d.notebook,title:'Second selection'}})),doc);await page.locator('.circuit-notebook-preview h4').filter({hasText:'Second selection'}).waitFor();await page.evaluate(d=>pendingInvestigationReads[0](JSON.stringify({...d,notebook:{...d.notebook,title:'Stale selection'}})),doc);await page.waitForTimeout(50);assert.equal(await page.locator('.circuit-notebook-preview h4').innerText(),'Second selection');await page.getByRole('button',{name:'Dismiss investigation preview',exact:true}).click();
await file.setInputFiles({name:'unmounted.json',mimeType:'application/json',buffer:Buffer.from('{}')});await page.getByRole('button',{name:'Mixed circuits',exact:true}).click();await page.evaluate(d=>pendingInvestigationReads[2](JSON.stringify(d)),doc);await page.getByRole('button',{name:'Active electronics',exact:true}).click();assert.equal(await page.locator('.circuit-notebook-preview').count(),0);await page.evaluate(()=>{File.prototype.text=savedFileText;});
// Maximum capacity does not discard earlier evidence.
for(let n=0;n<6;n++)await page.getByRole('button',{name:'Record current readings',exact:true}).click();assert.equal(await page.evaluate(()=>state._circuitActive.observations.length),8);assert.equal(await page.getByRole('button',{name:'Record current readings',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Record operating point',exact:true}).isDisabled(),true);assert.equal(await page.evaluate(()=>state._circuitActive.observations[0].design.input),1);
await file.setInputFiles(path.join(out,'notebook20-investigation.json'));await page.getByRole('button',{name:'Load investigation',exact:true}).click();
await page.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});const audit=async()=>page.evaluate(async()=>axe.run({include:[['.circuit-active-root']]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));let a=await audit();assert.deepEqual(a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),[]);
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await book.screenshot({path:path.join(out,'notebook-mobile.jpg'),type:'jpeg',quality:88});await records.first().locator('summary').click();await records.first().screenshot({path:path.join(out,'notebook-observation-mobile.jpg'),type:'jpeg',quality:90});a=await audit();assert.deepEqual(a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),[]);await page.setViewportSize({width:320,height:760});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const reportPage=await browser.newPage({viewport:{width:1060,height:1000}});const reportRequests=[];reportPage.on('request',r=>reportRequests.push(r.url()));await reportPage.setContent(html);assert.equal(await reportPage.locator('script,img,iframe,link').count(),0);assert.equal(await reportPage.locator('.observation').count(),2);await reportPage.screenshot({path:path.join(out,'notebook-report-desktop.jpg'),type:'jpeg',quality:90,fullPage:true});await reportPage.locator('.chart').screenshot({path:path.join(out,'notebook-report-response.jpg'),type:'jpeg',quality:90});await reportPage.emulateMedia({media:'print'});await reportPage.evaluate(()=>scrollTo(0,0));await reportPage.screenshot({path:path.join(out,'notebook-report-print.jpg'),type:'jpeg',quality:90});assert.deepEqual(reportRequests,[]);await reportPage.setViewportSize({width:390,height:844});await reportPage.emulateMedia({media:'screen'});assert.ok(await reportPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'notebook20-browser-results.json'),JSON.stringify({passed:true,checks:['recorded settings and probes frozen','notes outside electrical history','revisit and reference from observations','removal undo','shared explanation','JSON and HTML downloads','invalid and oversized file rejection','preview/dismiss without mutation','load and restore previous investigation','workspace persistence','newest async file selection wins','unmount ignores stale read','eight-point capacity','390/320 px layout','standalone report values and zero requests','print styles'],axeViolations:a.violations.length},null,2));console.log('Investigation notebook browser and report checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
