const fs=require('node:fs'),parser=require('@babel/parser'),traverse=require('@babel/traverse').default,crypto=require('node:crypto');const file='stem_lab/stem_tool_anatomy.js';let s=fs.readFileSync(file,'utf8'),english={};const baseline=crypto.createHash('sha256').update(s).digest('hex');if(baseline!=='41bda3c8f638c7c7b746266e16c62177fe62e1a927fdee412701b3ebb19db87a')throw Error('Source changed since last verification');fs.writeFileSync(__dirname+'/baseline.json',JSON.stringify({sha256:baseline},null,2));const bank=JSON.parse(fs.readFileSync(__dirname+'/content.json','utf8'));
function T(key,value){english['fact_ref_'+key]=value;return 't('+JSON.stringify('stem.anatomy.fact_ref_'+key)+','+JSON.stringify(value)+')';}function rep(a,b){if(s.split(a).length!==2)throw Error('Missing/duplicate '+a.slice(0,100));s=s.replace(a,b);}
const desc={skeletal:'Bones support movement, protect organs, store minerals, and house blood-forming marrow. Counts depend on age and anatomical conventions.',muscular:'Muscles produce force, support posture and movement, and generate heat. Skeletal, cardiac, and smooth muscle have different roles.',circulatory:'The heart and blood vessels circulate blood, transporting gases, nutrients, hormones, and wastes. Flow changes with the body’s needs.',lymphatic:'Lymphatic vessels return tissue fluid and absorb dietary fats. Lymph nodes, thymus, and spleen support immune function.',integumentary:'Skin, hair, nails, and glands support the body’s barrier, temperature regulation, and sensation. Skin size and renewal vary.',respiratory:'Airways conduct air; alveoli exchange gases with blood. Breathing rate, breath volume, and gas exchange are related but different.'};
const structures={femur:{fn:'The femur is the thigh bone and usually the longest bone. Its head meets the hip socket, and its lower end forms part of the knee. Shape, bone tissue, and loading direction all influence its strength.',clinicalKid:'Your femur is your thigh bone. It joins your hip to your knee and supports you when you stand and move. Bones are living tissues that grow and change.'},heart:{fn:'A muscular pump with four chambers. The right side sends blood toward the lungs; the left side sends it around the body. Cardiac output depends on heart rate and the blood volume pumped per beat.'},pituitary:{fn:'The pituitary lies in the sella turcica. Its anterior lobe produces hormones including GH, ACTH, TSH, FSH, LH, and prolactin. Its posterior lobe stores and releases ADH and oxytocin made in the hypothalamus. It regulates many endocrine pathways, but not all.',clinicalKid:'Your pituitary is a small gland below your brain. It releases hormones that help control growth and other body functions. It works with the hypothalamus, and other glands can also respond to signals in the blood.'}};
const simple={heart:{g35:'The heart has four chambers. It contracts to pump blood and relaxes to fill again. Its rate changes, for example when you exercise or rest.'},femur:{k2:'The femur is your thigh bone. It helps support you when you stand and move.',g35:'The femur is the long bone in your thigh. It joins the hip and knee and helps support your body during movement.'}};
const edits=[];traverse(parser.parse(s,{sourceType:'script'}),{VariableDeclarator(p){const name=p.node.id.name;if(name==='FUN_FACTS'){edits.push({start:p.node.init.start,end:p.node.init.end,text:'{'+Object.entries(bank).map(([sys,rows])=>JSON.stringify(sys)+':['+rows.map((r,i)=>'{id:'+JSON.stringify(sys+'_'+i)+',question:'+T(sys+'_'+i+'_question',r[0])+',text:'+T(sys+'_'+i+'_text',r[1])+',reference:'+JSON.stringify('https://openstax.org/books/anatomy-and-physiology-2e/pages/'+r[2])+'}').join(',')+']').join(',')+'}'});}else if(name==='SYSTEMS'){for(const system of p.node.init.properties){const key=system.key.name||system.key.value;if(desc[key]){const value=system.value.properties.find(p=>p.key.name==='desc').value;edits.push({start:value.start,end:value.end,text:T(key+'_desc',desc[key])});}const list=system.value.properties.find(p=>p.key.name==='structures')?.value.elements||[];for(const st of list){const id=st.properties.find(p=>p.key.name==='id')?.value.value;if(!structures[id])continue;for(const [field,text]of Object.entries(structures[id])){const value=st.properties.find(p=>p.key.name===field).value;edits.push({start:value.start,end:value.end,text:T(id+'_'+field,text)});}}}}else if(name==='SIMPLE_DESC'){for(const row of p.node.init.properties){const key=row.key.name;if(!simple[key])continue;for(const [field,text]of Object.entries(simple[key])){const value=row.value.properties.find(p=>p.key.name===field).value;edits.push({start:value.start,end:value.end,text:T(key+'_'+field,text)});}}}}});for(const e of edits.sort((a,b)=>b.start-a.start))s=s.slice(0,e.start)+e.text+s.slice(e.end);
rep('        var rawFactIdx = Number(d._factIdx);',`        function validFactPositions(raw){var positions={};if(!raw||raw.version!==1||!raw.positions||typeof raw.positions!=='object'||Array.isArray(raw.positions))return positions;Object.keys(FUN_FACTS).forEach(function(key){var value=raw.positions[key];if(Number.isInteger(value)&&value>=0&&value<FUN_FACTS[key].length)positions[key]=value;});return positions;}
        function legacyFactIndex(state,count){var value=typeof state._factIdx==='number'||typeof state._factIdx==='string'?Number(state._factIdx):0;return count&&Number.isFinite(value)?((Math.floor(value)%count)+count)%count:0;}
        var factPositions=validFactPositions(d._factStudy);
        var rawFactIdx = Object.prototype.hasOwnProperty.call(factPositions,sysKey)?factPositions[sysKey]:legacyFactIndex(d,sysFacts.length);`);
const anchor='        var currentFact = sysFacts.length > 0 ? sysFacts[factIdx] : null;';rep(anchor,anchor+`
        var factRevealed=!!(currentFact&&d._factStudy&&d._factStudy.version===1&&d._factStudy.revealedId===currentFact.id);
        function changeFact(action){
          if(['next','previous','reveal'].indexOf(action)===-1||!currentFact)return;
          setLabToolData(function(previous){var state=previous.anatomy||{},system=SYSTEMS[state.system]?state.system:'skeletal';if(system!==sysKey)return previous;var positions=validFactPositions(state._factStudy),index=Object.prototype.hasOwnProperty.call(positions,system)?positions[system]:legacyFactIndex(state,sysFacts.length),shown=state._factStudy&&state._factStudy.version===1?state._factStudy.revealedId:null;
            if(action==='reveal'){if(sysFacts[index].id!==currentFact.id)return previous;shown=shown===currentFact.id?null:currentFact.id;}else{index=(index+(action==='next'?1:sysFacts.length-1))%sysFacts.length;shown=null;}
            positions[system]=index;return Object.assign({},previous,{anatomy:Object.assign({},state,{_factStudy:{version:1,positions:positions,revealedId:shown}})});
          });
        }
`);
const start=s.indexOf('          // ── Fun fact banner (Always visible) ──'),end=s.indexOf('          // ── Mnemonics section (Always visible) ──',start);if(start<0||end<0)throw Error('Fact renderer bounds');
s=s.slice(0,start)+`          // ── Sourced fact prompts ──
          !focusedAnatomyWorkspace && currentFact ? h('section',{className:'anatomy-fact-card anatomy-fact-study mb-3','data-anatomy-fact':currentFact.id,'aria-labelledby':'anatomy-fact-title'},
            h('div',{className:'anatomy-fact-header'},h('h3',{id:'anatomy-fact-title'},t('stem.anatomy.did_you_know','Did you know?')),h('span',{'data-anatomy-fact-position':true},${T('position','{current} of {total}')}.replace('{current}',String(factIdx+1)).replace('{total}',String(sysFacts.length)))),
            h('p',{className:'anatomy-fact-guide'},${T('guide','Think through the question, then compare with the explanation. You can read first if this is new to you.')}),
            h('p',{'data-anatomy-fact-question':true,className:'anatomy-fact-question','aria-live':'polite','aria-atomic':true},currentFact.question),
            h('div',{className:'anatomy-fact-actions'},h('button',{type:'button','data-anatomy-fact-reveal':true,'aria-expanded':factRevealed,'aria-controls':'anatomy-fact-explanation',onClick:function(){changeFact('reveal');}},factRevealed?${T('hide','Hide explanation and try again')}:${T('reveal','Show explanation')}),ttsBtn(currentFact.question+(factRevealed?' '+currentFact.text:''),${T('read','Read this idea aloud')})),
            h('div',{id:'anatomy-fact-explanation',hidden:!factRevealed,'data-anatomy-fact-explanation':true},factRevealed?h('div',null,h('p',null,currentFact.text),h('a',{href:currentFact.reference,target:'_blank',rel:'noopener noreferrer'},${T('source','Source: OpenStax Anatomy and Physiology')})):null),
            h('div',{className:'anatomy-fact-navigation'},h('button',{type:'button','data-anatomy-fact-previous':true,onClick:function(){changeFact('previous');}},${T('previous','Previous idea')}),h('button',{type:'button','data-anatomy-fact-next':true,onClick:function(){changeFact('next');}},${T('next','Next idea')}))
          ) : null,

`+s.slice(end);
const css='.anatomy-fact-study{padding:14px;border:1px solid #a16207;border-radius:10px;background:#fffbeb;color:#422006;min-width:0}.anatomy-fact-study h3{margin:0;font-size:15px;font-weight:800;color:#78350f}.anatomy-fact-header{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.anatomy-fact-study p,.anatomy-fact-study a,.anatomy-fact-header span{font-size:13px;line-height:1.6}.anatomy-fact-study p{margin-block:10px}.anatomy-fact-guide{color:#713f12}.anatomy-fact-question{font-weight:700}.anatomy-fact-actions,.anatomy-fact-navigation{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px;align-items:center}.anatomy-fact-navigation{justify-content:space-between;border-top:1px solid #d6b982;padding-top:12px}.anatomy-fact-study button{min-height:44px;padding:8px 12px;border:1px solid #a16207;border-radius:7px;background:#fff;color:#713f12;font-size:13px;text-align:start;max-width:100%}.anatomy-fact-study a{color:#075985;text-decoration:underline;display:inline-block;margin-block:4px}.anatomy-fact-study [hidden]{display:none!important}.anatomy-fact-study :focus-visible{outline:3px solid #0284c7;outline-offset:3px}.theme-dark .anatomy-fact-study{background:#1e293b!important;color:#f8fafc!important;border-color:#a3a3a3!important}.theme-dark .anatomy-fact-study h3,.theme-dark .anatomy-fact-study p,.theme-dark .anatomy-fact-header span{color:#fef3c7!important}.theme-dark .anatomy-fact-study button{background:#0f172a!important;color:#fef3c7!important;border-color:#fbbf24!important}.theme-dark .anatomy-fact-study a{color:#7dd3fc!important}';rep('".anatomy-clinical-study{',JSON.stringify(css)+',\n      ".anatomy-clinical-study{');
parser.parse(s,{sourceType:'script'});fs.writeFileSync(file,s);fs.writeFileSync('desktop/web-app/public/'+file,s);fs.writeFileSync(__dirname+'/english.json',JSON.stringify(english,null,2)+'\n');console.log(Object.keys(english).length+' strings; 30 fact prompts, 6 summaries, 8 structure/grade descriptions.');
