const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),sourcePath=path.join(root,'stem_lab/stem_tool_circuit.js');
const source=fs.readFileSync(sourcePath,'utf8'),hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const results={sourceSha256:hash(source),checks:[],errors:[],axe:[],layouts:[],contentBounds:[],actions:[],focus:[],focusTransitions:[],nodeIds:[],textResize:[],motion:[],styleScope:[],screenshots:[],visualIssues:[]};
const simpleScope='.circuit-lab-workflow',activeScope='.circuit-active-lesson-lab';
(async()=>{
  const browser=await chromium.launch({headless:true});let page;
  try{
    console.log('Circuit evidence continuity audit: '+results.sourceSha256);
    page=await browser.newPage({viewport:{width:1280,height:1000},reducedMotion:'reduce'});page.on('pageerror',error=>results.errors.push(error.message));
    await page.setContent('<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Circuit evidence continuity</title></head><body><main id="root"></main></body></html>');
    await page.addStyleTag({path:path.join(root,'dev-tools/.cache/sweep-tailwind.css')});
    await page.addStyleTag({content:'body{margin:0;background:#070f1b;font-family:system-ui}#root{max-width:960px;margin:20px auto;padding:12px}*{box-sizing:border-box}'});
    for(const file of ['desktop/web-app/node_modules/react/umd/react.development.js','desktop/web-app/node_modules/react-dom/umd/react-dom.development.js'])await page.addScriptTag({path:path.join(root,file)});
    await page.addScriptTag({content:source});
    await page.evaluate(()=>{
      const noop=()=>{},icons=new Proxy({},{get:()=>()=>React.createElement('span')});window.awards=[];window.auditBlobs=[];
      const create=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{auditBlobs.push(blob);return create(blob);};
      const simple={mode:'series',voltage:9,components:[{id:41,type:'resistor',value:100}],pauseMotion:false,startGuideOpen:false,prediction:'I predict the current will halve when resistance doubles.'};
      const active={...StemLab.circuitActiveDesign({input:2.4}),view:'schematic',probeRed:'drive',probeBlack:'base',reference:{version:1,design:StemLab.circuitActiveDesign({input:.9})},observations:[StemLab.circuitActiveObservation({input:1},'My original operating-point observation.')],investigationTitle:'My independent investigation',investigationQuestion:'What sets the lamp current?',investigationPrediction:'My own prediction stays here.',reflection:'My notebook explanation stays independent.'};
      function Host(){const[data,setData]=React.useState({_circuit:simple,_circuitActive:active});window.state=data;window.setState=setData;return StemLab._registry.circuit.render({React,icons,toolData:data,setToolData:setData,t:(_key,fallback)=>fallback,gradeLevel:'8',addToast:noop,awardXP:(...args)=>awards.push(args),announceToSR:noop,a11yClick:fn=>({onClick:fn}),setStemLabTool:noop,setStemLabTab:noop,setToolSnapshots:noop});}
      window.auditRoot=ReactDOM.createRoot(document.querySelector('#root'));auditRoot.render(React.createElement(Host));
    });
    await page.getByRole('heading',{name:'Small circuits. Big discoveries.'}).waitFor();await page.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});
    const simple=page.locator(simpleScope),active=page.locator(activeScope);
    const click=name=>page.getByRole('button',{name,exact:true}).click();
    const ownActive=()=>page.evaluate(()=>JSON.stringify(Object.fromEntries(['reference','observations','investigationTitle','investigationQuestion','investigationPrediction','reflection','probeRed','probeBlack'].map(key=>[key,state._circuitActive[key]]))));
    async function screenshot(name,scope,width){
      await page.evaluate(()=>document.activeElement?.blur());await page.mouse.move(0,0);
      const clip=await page.locator(scope).evaluate(el=>{const r=el.getBoundingClientRect(),x=Math.max(0,Math.floor(r.x+scrollX)-6),y=Math.max(0,Math.floor(r.y+scrollY)-6);return {x,y,width:Math.min(document.documentElement.scrollWidth-x,Math.ceil(r.right+scrollX)+6-x),height:Math.ceil(r.bottom+scrollY)+6-y};});
      const file=name+'-'+width+'.png';await page.screenshot({path:path.join(__dirname,file),clip,fullPage:true,animations:'disabled'});results.screenshots.push({name,width,file,clip});
    }
    async function focusCheck(name,scope,selector,width){
      const locator=page.locator(scope).locator(selector);await locator.evaluate(el=>el.blur());const before=await locator.evaluate(el=>getComputedStyle(el).boxShadow);await page.keyboard.press('Tab');await locator.focus();
      const actual=await locator.evaluate(el=>{const s=getComputedStyle(el);return {focused:document.activeElement===el,focusVisible:el.matches(':focus-visible'),outlineStyle:s.outlineStyle,outlineWidth:s.outlineWidth,outlineColor:s.outlineColor,boxShadow:s.boxShadow};});
      actual.visible=actual.focused&&actual.focusVisible&&((actual.outlineStyle!=='none'&&parseFloat(actual.outlineWidth)>=2&&!['transparent','rgba(0, 0, 0, 0)'].includes(actual.outlineColor))||(actual.boxShadow!=='none'&&actual.boxShadow!==before));results.focus.push({name,width,selector,...actual});if(!actual.visible)results.visualIssues.push({name,width,type:'focus',selector,actual});
    }
    async function inspect(name,scope,{widths=[1280,390,320],focus=[],scale=1}={}){
      for(const width of widths){
        await page.setViewportSize({width,height:1000});await page.evaluate(()=>document.fonts.ready);
        const violations=await page.evaluate(async()=>{const scan=await axe.run(document.querySelector('#root'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return scan.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});results.axe.push({name,width,scale,violations});if(violations.length)results.visualIssues.push({name,width,type:'axe',violations});
        const dimensions=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));results.layouts.push({name,scale,...dimensions});if(dimensions.scrollWidth>width+1)results.visualIssues.push({name,width,type:'page-overflow',...dimensions});
        const duplicates=await page.evaluate(()=>{const ids=new Map();for(const el of document.querySelectorAll('[id]'))if(el.id)ids.set(el.id,(ids.get(el.id)||0)+1);return [...ids].filter(([,count])=>count>1);});results.nodeIds.push({name,width,duplicates});if(duplicates.length)results.visualIssues.push({name,width,type:'duplicate-ids',duplicates});
        const cards=await page.locator(scope).locator('.circuit-inquiry-trial,.circuit-inquiry-removed,.circuit-comparison>div,.circuit-active-lesson-reading,.circuit-active-lesson-delta,.circuit-active-lesson-saved-prediction,.circuit-active-lesson-replay,[data-active-lesson-result]').evaluateAll(elements=>elements.filter(el=>el.checkVisibility()).map(el=>{
          const r=el.getBoundingClientRect(),s=getComputedStyle(el),left=r.left+parseFloat(s.borderLeftWidth)+parseFloat(s.paddingLeft),right=r.right-parseFloat(s.borderRightWidth)-parseFloat(s.paddingRight),lines=[],violations=[];const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let text;
          while((text=walker.nextNode())){if(!text.textContent.trim()||!text.parentElement.checkVisibility()||text.parentElement.closest('[aria-hidden="true"],textarea,input'))continue;const range=document.createRange();range.selectNodeContents(text);for(const rect of range.getClientRects()){if(rect.width<.1||rect.height<.1)continue;const line={text:text.textContent.trim(),left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom};lines.push(line);if(rect.left<left-1||rect.right>right+1)violations.push({...line,overLeft:Math.max(0,left-rect.left),overRight:Math.max(0,rect.right-right)});}}
          return {selector:el.id?'#'+el.id:'.'+el.className.trim().split(/\s+/).join('.'),stage:el.getAttribute('data-stage'),left,right,clientWidth:el.clientWidth,scrollWidth:el.scrollWidth,lines,violations};
        }));results.contentBounds.push({name,width,scale,cards});for(const card of cards)if(card.violations.length||card.scrollWidth>card.clientWidth+1)results.visualIssues.push({name,width,type:'card-content-bounds',card});
        const actions=await page.locator(scope).locator('button,summary,textarea,select').evaluateAll(elements=>elements.filter(el=>el.checkVisibility()).map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return {tag:el.tagName,label:el.getAttribute('aria-label')||el.textContent.trim(),width:r.width,height:r.height,disabled:!!el.disabled,transitionDuration:s.transitionDuration};}));results.actions.push({name,width,scale,actions});for(const action of actions){if(action.width<43.9||action.height<43.9)results.visualIssues.push({name,width,type:'control-size',action});if(action.transitionDuration.split(',').some(value=>parseFloat(value)*(value.trim().endsWith('ms')?.001:1)>.0000101))results.visualIssues.push({name,width,type:'reduced-motion-transition',action});}
        for(const selector of focus)await focusCheck(name,scope,selector,width);
        await screenshot(name,scope,width);
        if(results.visualIssues.length)throw Error('Material visual issue in '+name+' at '+width+'px; inspect evidence-results.json.');
      }
      await page.setViewportSize({width:1280,height:1000});
    }
    async function resizeText(scope,scale){
      const record=await page.locator(scope).evaluate((el,scale)=>{for(const[node,style]of window.auditTextStyles||[]){if(style===null)node.removeAttribute('style');else node.setAttribute('style',style);}window.auditTextStyles=[];if(scale===1)return null;const nodes=[el,...el.querySelectorAll('*')],sizes=nodes.map(node=>parseFloat(getComputedStyle(node).fontSize));window.auditTextStyles=nodes.map(node=>[node,node.getAttribute('style')]);nodes.forEach((node,i)=>{if(Number.isFinite(sizes[i])){node.style.setProperty('transition','none','important');node.style.setProperty('animation','none','important');node.style.setProperty('font-size',(sizes[i]*scale)+'px','important');}});const target=el.querySelector('textarea,button')||el;return {scale,elements:nodes.length,beforeFontSize:sizes[nodes.indexOf(target)],afterFontSize:parseFloat(getComputedStyle(target).fontSize)};},scale);
      if(record){results.textResize.push({scope,...record});assert.equal(record.afterFontSize,record.beforeFontSize*scale);}return record;
    }
    async function exactInput(value){const input=page.getByRole('spinbutton',{name:'Input voltage (V) exact value',exact:true});await input.fill(String(value));await input.press('Enter');await page.waitForFunction(value=>state._circuitActive.input===value,value);}
    const exportedJSON=async()=>JSON.parse(await page.evaluate(()=>auditBlobs.at(-1).text()));
    async function notebookFocus(action){await page.waitForFunction(()=>document.activeElement===document.querySelector('.circuit-inquiry-notebook > summary'),null,{timeout:15000});results.focusTransitions.push({action,target:'.circuit-inquiry-notebook > summary',focused:true});}

    await simple.locator(':scope > details > summary').click();await click('Save baseline');await click('Double resistance');await click('Record comparison');
    await page.locator('#circuit-explanation').fill('90 mA became 45 mA. Doubling resistance halved the current.');
    assert.equal(await page.evaluate(()=>state._circuit.observations[0].explanation),'90 mA became 45 mA. Doubling resistance halved the current.');
    await simple.locator('.circuit-inquiry-notebook > summary').click();await page.getByRole('textbox',{name:'Trial 1 explanation',exact:true}).fill('Revised evidence: the supply stayed at 9 V while resistance doubled.');
    assert.equal(await page.locator('#circuit-explanation').inputValue(),'Revised evidence: the supply stayed at 9 V while resistance doubled.');await click('Download evidence');const simpleExport=await exportedJSON();assert.equal(simpleExport.trials[0].explanation,await page.locator('#circuit-explanation').inputValue());
    const simpleDesign=await page.evaluate(()=>JSON.stringify(StemLab.circuitDesignDocument(state._circuit)));await page.locator('.circuit-file-tools > summary').click();await page.locator('#circuit-design-file').setInputFiles({name:'same-circuit.json',mimeType:'application/json',buffer:Buffer.from(simpleDesign)});await click('Load this circuit');
    assert.equal(await page.evaluate(()=>state._circuit.components[0].id),1);assert.equal(await simple.getByRole('button',{name:'Record comparison',exact:true}).isDisabled(),true);assert.equal(await page.evaluate(()=>state._circuit.observations.length),1);
    const baseline=await page.evaluate(()=>JSON.stringify(state._circuit.experimentBaseline)),bench=await page.evaluate(()=>JSON.stringify(StemLab.circuitDesignDocument(state._circuit)));
    const presets=simple.locator('details.circuit-notebook').filter({has:page.getByText('Guided investigations',{exact:true})});await presets.locator(':scope > summary').click();await click('2. Add another path');await click('Undo');
    assert.equal(await page.evaluate(()=>JSON.stringify(state._circuit.experimentBaseline)),baseline);assert.equal(await page.evaluate(()=>JSON.stringify(StemLab.circuitDesignDocument(state._circuit))),bench);await presets.locator(':scope > summary').click();
    results.checks.push({name:'Simple recorded explanation remains editable, both editors agree, download contains the revision, import deduplicates regenerated IDs, and preset Undo retains the baseline'});
    const simpleFocus=['#circuit-explanation','textarea[aria-label="Trial 1 explanation"]','.circuit-inquiry-notebook > summary','.circuit-guided-lab > summary','button:text-is("Download evidence")','details.circuit-notebook:not(.circuit-inquiry-notebook) > summary'];
    await inspect('simple-notebook',simpleScope,{focus:simpleFocus});await resizeText(simpleScope,2);await inspect('simple-notebook-200pct-text',simpleScope,{widths:[320],focus:simpleFocus,scale:2});await resizeText(simpleScope,1);
    await page.evaluate(()=>{window.savedSimple=state._circuit;const before={mode:'series',voltage:9,components:[{type:'resistor',value:100,id:41}]};const observations=Array.from({length:8},(_,i)=>({before,after:{...before,voltage:i+1},delta:(i+1-9)/100,prediction:'One supply change',explanation:'Keep trial '+(i+1),controlled:true,changes:['Supply voltage']}));setState(prev=>({...prev,_circuit:{...prev._circuit,...before,voltage:10,observations,experimentBaseline:{circuit:before,prediction:'One supply change'},experimentResult:null,removedObservation:null}}));});
    await page.waitForFunction(()=>state._circuit.observations.length===8);assert.equal(await simple.getByRole('button',{name:'Record comparison',exact:true}).isDisabled(),true);assert.match(await simple.innerText(),/notebook is full/i);
    await click('Remove trial 2');await notebookFocus('Remove trial 2');assert.equal(await page.evaluate(()=>state._circuit.observations.length),7);await click('Restore removed trial');await notebookFocus('Restore removed trial');assert.equal(await page.evaluate(()=>state._circuit.observations[1].explanation),'Keep trial 2');
    await click('Remove trial 2');await click('Record comparison');assert.equal(await page.evaluate(()=>state._circuit.observations.length),8);assert.equal(await page.getByRole('button',{name:'Restore removed trial',exact:true}).isDisabled(),true);assert.equal(await page.evaluate(()=>state._circuit.removedObservation.entry.explanation),'Keep trial 2');
    await click('Remove trial 1');await notebookFocus('Make room for recovery');assert.equal(await page.evaluate(()=>state._circuit.removedObservation.entry.explanation),'Keep trial 2');
    await resizeText('.circuit-inquiry-recovery',2);await inspect('simple-recovery-200pct-text','.circuit-inquiry-recovery',{widths:[320],scale:2,focus:['button:text-is("Restore removed trial")','button:text-is("Discard removed trial")','button:text-is("Restore removed trial 2")','button:text-is("Discard removed trial 2")']});await resizeText('.circuit-inquiry-recovery',1);
    await click('Restore removed trial');await notebookFocus('Restore first pending trial');assert.equal(await page.evaluate(()=>state._circuit.observations.some(trial=>trial.explanation==='Keep trial 2')),true);assert.equal(await page.evaluate(()=>state._circuit.removedObservation.entry.explanation),'Keep trial 1');
    await click('Discard removed trial');await notebookFocus('Discard pending trial');assert.equal(await page.evaluate(()=>state._circuit.removedObservations.length),0);assert.equal(await page.evaluate(()=>state._circuit.observations.length),8);
    results.checks.push({name:'Full Simple notebook preserves all eight trials; making room again retains both removals; the first can be restored and the second explicitly discarded, with notebook-summary focus after each action'});
    await page.evaluate(()=>setState(prev=>({...prev,_circuit:{...savedSimple,activeWorkbench:true}})));await active.waitFor();const independent=await ownActive();
    await click('Start transistor prediction');assert.equal(await page.evaluate(()=>document.activeElement?.hasAttribute('data-active-lesson-question')),true);await active.getByRole('button',{name:'Decreases',exact:true}).click();
    assert.equal(await active.locator('.circuit-active-lesson-evidence').count(),0);await inspect('active-baseline',activeScope,{focus:['select','[data-active-lesson-question]']});
    await click('Test transistor prediction');assert.equal(await page.evaluate(()=>document.activeElement?.hasAttribute('data-active-lesson-result')),true);
    const activeText='I first predicted a decrease. The readings show 3 mA becoming 8 mA as base drive increases.';await active.getByRole('textbox',{name:'Transistor experiment explanation',exact:true}).fill(activeText);
    assert.equal(await page.evaluate(()=>document.activeElement?.tagName),'TEXTAREA');await exactInput(4.2);
    assert.deepEqual(await active.locator('.circuit-active-lesson-reading > strong').allTextContents(),['3.00 mA','8.00 mA']);assert.match(await active.locator('.circuit-active-lesson-bench-note').innerText(),/live bench has changed/i);assert.match(await active.locator('.circuit-active-lesson-saved-prediction').innerText(),/Decreases/);
    await inspect('active-edited-result',activeScope,{focus:['select','[data-active-lesson-result]','textarea']});await resizeText(activeScope,2);await inspect('active-edited-result-200pct-text',activeScope,{widths:[320],focus:['select','[data-active-lesson-result]','textarea'],scale:2});await resizeText(activeScope,1);
    const selected=active.getByRole('combobox',{name:'Transistor prediction experiment',exact:true});const beforeSelect=await page.evaluate(()=>JSON.stringify(StemLab.circuitActiveDesign(state._circuitActive)));await selected.selectOption('limit');assert.equal(await page.evaluate(()=>JSON.stringify(StemLab.circuitActiveDesign(state._circuitActive))),beforeSelect);await click('Start transistor prediction');await active.getByRole('button',{name:'Stays the same',exact:true}).click();await click('Test transistor prediction');await active.getByRole('textbox',{name:'Transistor experiment explanation',exact:true}).fill('The lamp current stays at the saturation limit.');
    await selected.selectOption('sensor');await click('Start transistor prediction');await active.getByRole('button',{name:'Increases',exact:true}).click();await click('Test transistor prediction');await active.getByRole('textbox',{name:'Transistor experiment explanation',exact:true}).fill('Less light gives more lamp current in the dark-sensor circuit.');
    const sensorBench=await page.evaluate(()=>JSON.stringify(StemLab.circuitActiveDesign(state._circuitActive)));await selected.selectOption('gain');assert.equal(await page.evaluate(()=>JSON.stringify(StemLab.circuitActiveDesign(state._circuitActive))),sensorBench);assert.equal(await active.getByRole('textbox',{name:'Transistor experiment explanation',exact:true}).inputValue(),activeText);assert.equal(await ownActive(),independent);
    const records=await page.evaluate(()=>JSON.stringify(StemLab.circuitActiveLessonRecords(state._circuitActive)));await click('Load experiment baseline');assert.equal(await page.evaluate(()=>state._circuitActive.input),1);await click('Undo active edit');assert.equal(await page.evaluate(()=>JSON.stringify(StemLab.circuitActiveDesign(state._circuitActive))),sensorBench);await click('Load this experiment result');assert.equal(await page.evaluate(()=>state._circuitActive.input),1.5);assert.equal(await page.evaluate(()=>JSON.stringify(StemLab.circuitActiveLessonRecords(state._circuitActive))),records);assert.equal(await ownActive(),independent);
    await page.locator('#circuit-active-notebook > summary').click();await click('Save investigation JSON');const activeExport=await exportedJSON();const roundTrip=await page.evaluate(doc=>{const restored=StemLab.parseCircuitInvestigation(JSON.stringify(doc));return {records:StemLab.circuitActiveLessonRecords(restored),document:StemLab.circuitActiveInvestigation(restored)};},activeExport);assert.deepEqual(roundTrip.document,activeExport);assert.equal(roundTrip.records.gain.choice,'less');assert.equal(Object.values(roundTrip.records).filter(record=>record.tested).length,3);
    results.checks.push({name:'Active lessons retain wrong prediction, each explanation, and modeled evidence across live edits and lesson switches; replay is undoable; notebook/reference/probes survive; JSON round-trips all three records'});
    const styles=await page.evaluate(()=>{const live=document.querySelector('.circuit-active-lesson-reading'),sentinel=document.createElement('div');sentinel.style.display='none';sentinel.innerHTML='<div class="circuit-active-lesson-reading"><strong>Outside component root</strong></div>';document.body.appendChild(sentinel);const sample=sentinel.firstChild,a=getComputedStyle(live),b=getComputedStyle(sample),result={liveBackground:a.backgroundColor,outsideBackground:b.backgroundColor,liveBorder:a.borderTopWidth,outsideBorder:b.borderTopWidth,styleNodes:document.querySelectorAll('style').length};sentinel.remove();return result;});assert.notEqual(styles.liveBackground,styles.outsideBackground);results.styleScope.push(styles);
    const beforeMotion=await page.evaluate(()=>({tick:state._circuit.tick||0,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches}));await page.waitForTimeout(250);const afterMotion=await page.evaluate(()=>({tick:state._circuit.tick||0,animations:document.getAnimations().filter(animation=>animation.playState==='running'&&Number(animation.effect?.getTiming().duration)>.01).length}));assert.equal(beforeMotion.reduced,true);assert.equal(afterMotion.tick,beforeMotion.tick);assert.equal(afterMotion.animations,0);results.motion.push({before:beforeMotion,after:afterMotion});
    assert.deepEqual(await page.evaluate(()=>awards),[]);assert.deepEqual(results.errors,[]);assert.deepEqual(results.visualIssues,[]);results.passed=true;await page.evaluate(()=>auditRoot.unmount());
  }catch(error){results.failure=error.stack;throw error;}
  finally{results.sourceSha256AtEnd=hash(fs.readFileSync(sourcePath));results.sourceChangedDuringRun=results.sourceSha256AtEnd!==results.sourceSha256;if(results.sourceChangedDuringRun){results.passed=false;results.errors.push('Circuit source changed during the audit.');process.exitCode=1;}fs.writeFileSync(path.join(__dirname,'evidence-results.json'),JSON.stringify(results,null,2));await browser.close();}
  console.log('Evidence continuity: '+results.checks.length+' workflows, '+results.axe.length+' axe scans, '+results.screenshots.length+' screenshots, '+results.visualIssues.length+' visual issues.');
})().catch(error=>{console.error(error);process.exitCode=1;});
