from pathlib import Path
import json,time
bands=['elementary','middle','high']
def banded(xs):return dict(zip(bands,xs))
def option(title,skill,when,limit,words):return dict(title=title,skill=skill,when=when,limit=limit,words=banded(words))
cases=[dict(id='effort',title='Effort, rest and useful support',setup=banded(['You have tried a tricky task several times. You are tired and the same part still does not make sense.','You are practising for an assessment, but repeating the same method is not helping and other responsibilities need time.','You are balancing a demanding task with work, care or other commitments. More hours alone may not address the difficulty.']),question='What is the obstacle: missing information, an inaccessible method, limited time, tiredness or something else?',options=[option('Try a different small step','Curiosity and flexible persistence','A smaller step or another format may reveal what you understand and where help is needed.','Repeating harder is not always useful. Decide when to stop and reassess; needing access or support is not a lack of strength.',['Could we try one part another way?','Can I try a worked example or another format before repeating this?','Could we identify the specific barrier and test a smaller, accessible step?']),option('Pause and ask for practical support','Self-awareness and self-advocacy','Rest, clarification, an accommodation or a revised plan may make participation more workable.','You may not control deadlines or resources. An adult or organizer shares responsibility for addressing barriers; a request need not guarantee a yes.',['I need a break and help with this part.','I need help figuring out what to change, including time or the way I do it.','What support or adjustment is available, and which commitment can realistically change?'])],changed='The deadline stays the same, but the current method is still inaccessible.',review='Name the access barrier and ask the responsible adult for a workable alternative. Do not treat exhaustion or missing support as evidence that you lack perseverance.'),
dict(id='welcome',title='Welcome with access and choice',setup=banded(['A classmate is alone near a game. You do not know whether they want to join or prefer their own activity.','A new group member has not joined the usual activity. You do not know their interest, comfort or access needs.','Someone has not taken part in a group event. The format may present a barrier, but their reasons and preferences are unknown.']),question='What can you observe, and what would you need to ask without putting someone on the spot?',options=[option('Offer an invitation with room to decline','Kindness and respect','A quiet, specific invitation can make an option visible while leaving the decision with the person.','Being alone does not mean lonely. Do not repeat invitations after a no or ask for private explanations.',['Would you like to play, watch, or do your own thing?','Would you like to join in any way? It is okay to pass.','Would an invitation or a different way to participate be welcome? No explanation is needed.']),option('Improve access with others','Fairness and collaboration','Changing the format or asking an organizer for help can make participation more possible for everyone.','Do not publicly identify someone’s needs or make them responsible for fixing the activity. Adults and organizers have responsibilities too.',['Could we make another way to play?','Could we offer different roles or a quieter option?','Could the organizer review access, cost and participation options without singling anyone out?'])],changed='The person declines the invitation, while the activity still has an access barrier.',review='Respect the decline and continue addressing access with the organizer. Participation is a choice, not proof that your kindness worked.'),
dict(id='leadership',title='Shared decisions and fair roles',setup=banded(['Two classmates both want to lead a group task. Other group members have not said what they need or want to do.','A group has different ideas about roles and who should decide. Some members need another way or more time to contribute.','A team has competing priorities, unequal availability and a deadline. One person has started assigning roles without checking with others.']),question='Whose preferences, workload and access needs have not yet shaped the plan?',options=[option('Ask before dividing the work','Listening and perspective','Inviting input in more than one way can reveal preferences and practical limits before roles are assigned.','A public discussion may not suit everyone. Allow writing or processing time without treating quietness as having nothing to contribute.',['What would each person like to try? You can tell us or show us.','Can we collect ideas in writing too, then check what is workable?','Could we check preferences, capacity and access before agreeing on responsibilities?']),option('Agree on a small trial and review it','Fairness and flexible leadership','A temporary division of work can be reviewed using actual workload and what people communicate.','Fairness is not necessarily identical tasks or equal minutes. A trial needs consent, a review point and a way to ask for support.',['Can we try these jobs and check if they work for everyone?','Could we try this division, then review the workload before the next session?','Can we agree on a short trial, decision rules and a way to change roles without blame?'])],changed='A quieter member says the agreed role is not accessible to them.',review='Revisit the role or format with that person’s input. Their request is useful information, not failure to be a team player.'),
dict(id='harm',title='Responding to a hurtful comment',setup=banded(['Someone makes a joke about a classmate’s way of speaking. You can seek help without repeating the words.','A peer makes a hurtful comment about a tradition or identity. You do not know how safe it would feel to respond directly.','A group member dismisses another person’s identity or access needs. You are considering support, a boundary or involving someone responsible.']),question='Who may need support, what feels safe, and who has responsibility to help?',options=[option('Set a limit when it is workable','Courage and care','A brief limit can communicate that the behavior is unwelcome without requiring a debate.','Direct confrontation is optional. You do not owe a personal story, calm performance or lesson about your identity; stop if pressure escalates.',['I do not want to join that joke.','I am not okay with that comment. I am stepping away.','That comment is harmful. I want it to stop; I am not going to debate someone’s identity.']),option('Seek support or check privately','Care and shared responsibility','A trusted adult can address the behavior, and a private check can ask what support would be welcome.','Do not promise secrecy about danger or make the targeted person choose the whole response. Quiet or indirect support is not lesser courage.',['Can you help with a hurtful comment?','Would support be useful? We can ask a trusted adult.','Could someone responsible help address this? I also want to check what support the affected person wants.'])],changed='The comments continue after someone asks them to stop.',review='Shift toward trusted support and a plan for safety. The responsibility for stopping harmful behavior does not rest on finding perfect words.')]
p=Path('sel_hub/sel_tool_strengths.js');s=p.read_text(encoding='utf-8');a=s.index('  var SCENARIOS =');b=s.index('  // ═',a)
s=s[:a]+'  var STRENGTH_CASES = '+json.dumps(cases,ensure_ascii=False,indent=2)+';\n\n'+s[b:]
a=s.index("              scenarios: {");b=s.index('\n',a);s=s[:a]+"              scenarios: { accent: '#9333ea', soft: 'rgba(147,51,234,0.14)', icon: '\\uD83C\\uDFAD', title: 'Scenarios — strengths in context', hint: 'Compare possible actions, the support they need and their limits. A choice in one situation does not define your character. Rest, quiet support and asking for help can be workable choices.' },"+s[b:]
a=s.index("            tab === 'scenarios' ?");b=s.index('            // ── QUIZ TAB',a)
s=s[:a]+r'''            tab === 'scenarios' ? (function() {
              var obj = function(value) { return value && typeof value === 'object' && !Array.isArray(value) ? value : {}; };
              var selections = obj(d.contextSelections);
              var selected = selections[band];
              var example = STRENGTH_CASES.find(function(item) { return item.id === selected; }) || STRENGTH_CASES[0];
              var own = selected === 'own';
              var contextId = own ? 'own' : example.id;
              var key = band + ':' + contextId;
              var drafts = obj(d.contextDrafts);
              var draft = obj(drafts[key]);
              var note = function(id) { return typeof draft[id] === 'string' ? draft[id] : ''; };
              var surface = _strHC ? '#000000' : _strL ? '#ffffff' : '#0f172a';
              var ink = _strHC ? '#ffffff' : _strFg('#e2e8f0');
              var edge = _strHC ? '#ffff00' : _strL ? '#64748b' : '#94a3b8';
              var card = { padding: '16px', margin: '14px 0', border: '1px solid ' + edge, borderRadius: '12px', background: surface, color: ink, minWidth: 0 };
              var control = { width: '100%', minHeight: '44px', padding: '10px', boxSizing: 'border-box', border: '1px solid ' + edge, borderRadius: '8px', background: surface, color: ink, font: 'inherit', fontSize: '16px' };
              var summary = { minHeight: '44px', padding: '10px 0', cursor: 'pointer', fontWeight: 700 };
              var fields = [
                { id: 'notice', label: 'What do I notice, and what do I still need to ask?' },
                { id: 'support', label: 'What support, access or boundaries matter here?' },
                { id: 'action', label: 'What might I try, combine, adapt or pause?' },
                { id: 'review', label: 'What would tell me to keep or change the plan?' }
              ];
              var preview = ['Strengths in context — practice notes, not a character assessment.', 'Context: ' + (own ? 'My own example' : example.title)].concat(fields.map(function(field) { return field.label + '\n' + (note(field.id).trim() || '(No note yet)'); })).join('\n\n');
              return h('section', { role: 'region', 'aria-label': 'Strengths in context practice', style: { maxWidth: '760px', margin: '0 auto', padding: '16px', background: surface, color: ink, fontSize: '16px', lineHeight: 1.6, overflowWrap: 'anywhere' } },
                h('h3', { style: { fontSize: '22px', margin: '0 0 8px' } }, 'Explore strengths in context'),
                h('p', null, band === 'elementary' ? 'Different actions can help in different moments. You can ask for help, rest or change your plan. A choice does not tell us what kind of person you are.' : 'Consider what an action makes possible, its limits and the support available. A choice in a fictional situation does not measure a fixed strength or your worth.'),
                h('p', null, 'Read, think or discuss with someone you trust. Every note is optional; there are no stars or right-answer points in this practice.'),
                h('label', { htmlFor: 'str-context', style: { display: 'block', fontWeight: 700 } }, 'Choose a strengths context'),
                h('select', { id: 'str-context', value: contextId, style: control, onChange: function(ev) { var next = Object.assign({}, selections); next[band] = ev.target.value; upd({ contextSelections: next }); } }, STRENGTH_CASES.map(function(item) { return h('option', { key: item.id, value: item.id }, item.title); }), h('option', { value: 'own' }, 'My own example')),
                h('div', { key: key, style: card }, h('h4', { style: { margin: '0 0 8px', fontSize: '18px' } }, own ? 'Consider a situation of your own' : example.title),
                  h('p', null, own ? 'Use an everyday or fictional situation. Start with what happened, what you do not know and what support might help. Personal details are not needed.' : example.setup[band]),
                  h('p', null, own ? 'Which possible actions fit the needs, access and boundaries involved? You can consider more than one.' : example.question),
                  !own && callTTS && h('button', { 'aria-label': 'Read this strengths scenario aloud', onClick: function() { speak(example.setup[band]); }, style: Object.assign({}, control, { width: 'auto', cursor: 'pointer' }) }, 'Read scenario aloud')),
                !own && h('details', { key: key + '-compare', style: card }, h('summary', { style: summary }, 'Compare possible approaches'),
                  h('p', null, 'These approaches can be combined or adapted. The strengths named are possible ways to describe an action, not labels assigned to you.'),
                  example.options.map(function(option) { return h('div', { key: option.title, style: card }, h('h4', { style: { margin: '0 0 8px', fontSize: '18px' } }, option.title), h('p', null, 'Possible strengths: ' + option.skill), h('p', null, 'When it may help: ' + option.when), h('p', null, 'Limits and support: ' + option.limit), h('p', { style: { fontWeight: 700 } }, 'Words to adapt: ' + option.words[band])); })),
                h('details', { key: key + '-change', style: card }, h('summary', { style: summary }, 'Reconsider when something changes'), h('p', null, own ? 'What if an offer is declined, a barrier remains or your capacity changes?' : example.changed), h('p', null, own ? 'You can revise the action, seek support or pause. Changing a plan does not mean you lack a strength.' : example.review)),
                h('details', { key: key + '-notes', style: card }, h('summary', { style: summary }, 'Consider my own response (optional)'),
                  h('p', null, 'Notes stay with this context and grade. They are not monitored, do not request help and are not sent to the AI coach by this activity.'),
                  fields.map(function(field) { var id = 'str-context-' + field.id; return h('div', { key: id, style: { margin: '16px 0' } }, h('label', { htmlFor: id, style: { display: 'block', fontWeight: 700 } }, field.label + ' (optional)'), h('textarea', { id: id, rows: 3, value: note(field.id), style: Object.assign({}, control, { resize: 'vertical' }), onChange: function(ev) { var next = Object.assign({}, drafts); var values = Object.assign({}, draft); values[field.id] = ev.target.value; next[key] = values; upd({ contextDrafts: next }); } })); })),
                h('details', { key: key + '-preview', style: card }, h('summary', { style: summary }, 'Review my practice notes'), h('label', { htmlFor: 'str-context-preview', style: { display: 'block', fontWeight: 700 } }, 'Notes to review or copy'), h('textarea', { id: 'str-context-preview', rows: 9, readOnly: true, value: preview, style: Object.assign({}, control, { resize: 'vertical' }) })),
                (d.scenarioChoice || (Array.isArray(d.scenariosDone) && d.scenariosDone.length > 0) || d.topScenarios) && h('details', { style: card }, h('summary', { style: summary }, 'Earlier scenario activity'),
                  h('p', null, 'Earlier choices, completion records and awards remain stored. Their ratings belong to the earlier activity; they are not assessments of your character. This practice does not add ratings or change your selected strengths.'),
                  d.scenarioChoice && d.scenarioChoice.choice && typeof d.scenarioChoice.choice.text === 'string' && h('p', null, 'Earlier choice: ' + d.scenarioChoice.choice.text))
              );
            })() : null,

'''+s[b:]
for file in [p,Path('desktop/web-app/public/sel_hub/sel_tool_strengths.js')]:
    for attempt in range(5):
        try:file.write_bytes(s.encode('utf-8'));break
        except OSError:
            if attempt==4:raise
            time.sleep(1)
print('Updated Strengths scenarios and public copy')
