'use strict';

const S = require('./item_content.cjs').sources;

const section = (heading, content, keyTerms) => ({ heading, content, keyTerms });
const chapter = (id, skillId, title, summary, objectives, sections, flashcards) => ({ id, skillId, title, summary, objectives, sections, flashcards });

const chapters = [
  chapter('sc5422-ch-01', 'counselor-role-national-model', 'School Counselor Role and Program Foundations',
    'Define the school counselor as a leader, advocate, collaborator, consultant, and program manager serving every student through academic, career, and social/emotional development.',
    ['Distinguish a comprehensive program from isolated services.', 'Identify appropriate and inappropriate counselor duties.', 'Use role, equity, and time data for collaborative advocacy.'], [
      section('A comprehensive program for every student', 'A school counseling program is a planned part of the educational system, not merely a referral service. It combines developmental instruction, responsive supports, planning, consultation, collaboration, and systems work across academic, career, and social/emotional development. The program serves every student while varying intensity based on need. On exam items, reject choices that reduce the role to therapy, scheduling, discipline, testing logistics, or crisis response alone.', ['comprehensive program', 'developmental', 'student domains']),
      section('Five connected professional roles', 'Leadership turns a shared vision into coordinated action. Advocacy names and removes barriers. Collaboration shares ownership with students, families, educators, administrators, and community partners. Consultation helps another person understand and address a concern without taking over that person’s role. Program management aligns time, services, resources, and evidence. Strong answers often combine several roles while keeping student access and outcomes central.', ['leadership', 'advocacy', 'consultation']),
      section('Appropriate duties and role advocacy', 'Direct and indirect student services, program planning, data use, family engagement, career and academic planning, short-term counseling, referral, and systems advocacy fit the counselor role. Routine discipline supervision, primary test coordination, clerical scheduling, and other extensive noncounseling assignments displace that work. A counselor should document time and access effects, discuss them with administration, propose feasible alternatives, and monitor whether the change restores services.', ['appropriate activity', 'noncounseling assignment', 'time-use data']),
      section('Equity, professional identity, and wellness', 'Equity work asks who has access, who benefits, and which policies or practices create avoidable barriers. Disaggregate evidence and include affected student and family voices before proposing change. Professional organizations, current standards, supervision, and continuing development strengthen competence but do not transfer ethical responsibility. Counselors also monitor stress, impairment, and secondary trauma, seeking consultation and support early enough to protect sound judgment and continuity of care.', ['educational equity', 'professional competence', 'wellness']),
    ], [['What makes a counseling program comprehensive?', 'It coordinates planned academic, career, and social/emotional supports for every student while varying intensity by need.'], ['What is advocacy?', 'Using evidence and voice to remove barriers and improve equitable access and outcomes.'], ['What is consultation?', 'A collaborative process that helps another person address a concern while respecting that person’s role.'], ['Why track use of time?', 'To show how assignments affect access to counseling services and support role-aligned decisions.'], ['What is a noncounseling assignment?', 'A duty such as extensive clerical, testing, or discipline work that displaces the comprehensive program.'], ['How does wellness connect to ethics?', 'Monitoring impairment and obtaining support protects competent service and student welfare.']]),

  chapter('sc5422-ch-02', 'development-learning-family-systems', 'Human Development, Learning, and Family Systems',
    'Apply developmental and learning theories as flexible lenses for designing supports, not as rigid labels or stand-alone diagnoses.',
    ['Recognize major developmental tasks and cognitive shifts.', 'Connect learning theory to counseling and instruction.', 'Interpret behavior within family, cultural, and school systems.'], [
      section('Psychosocial development', 'Erikson described development through recurring tensions. School-age children often seek competence in industry versus inferiority; adolescents explore identity versus role confusion. Earlier trust, autonomy, and initiative still influence current functioning, while development varies across people and cultures. Use stage ideas to generate developmentally plausible supports, never to declare that every student of one age thinks or behaves identically. Strengths, context, disability, opportunity, and relationships all matter.', ['Erikson', 'industry versus inferiority', 'identity versus role confusion']),
      section('Cognitive development and scaffolding', 'Piaget’s concrete operational learners reason logically about tangible examples, classifications, and transformations, while formal operational thinking adds systematic work with abstractions and hypothetical possibilities. These are broad patterns rather than rigid age gates. Vygotsky emphasizes the zone of proximal development: what a learner can accomplish with skilled support. Model, prompt, rehearse, and fade assistance as competence grows while preserving meaningful goals and student agency.', ['concrete operations', 'formal operations', 'zone of proximal development']),
      section('Behavioral, cognitive, and social learning', 'Behavioral approaches examine antecedents, observable responses, and consequences; reinforcement increases future behavior and is not the same as bribery or punishment. Cognitive approaches examine interpretations and beliefs that shape emotion and action. Social learning highlights attention to models, observed consequences, self-efficacy, and practice. A counselor selects a theory because it explains the target and suggests an ethical, feasible intervention, then tests the plan with student evidence.', ['reinforcement', 'cognitive appraisal', 'social learning']),
      section('Family and ecological systems', 'Family-systems perspectives view behavior within reciprocal roles, boundaries, communication, alliances, and transitions rather than locating all causation in one member. Ecological thinking adds peers, school practices, community conditions, culture, and policy. Gather information respectfully across settings, ask what works and what the family values, and avoid treating cultural difference as dysfunction. The practical question is which interaction or barrier can be changed to improve student functioning.', ['family systems', 'ecological context', 'cultural responsiveness']),
    ], [['What is the central Eriksonian task of adolescence?', 'Identity versus role confusion: exploring and integrating roles, values, relationships, and future possibilities.'], ['What is concrete operational reasoning?', 'Logical thought that is especially effective with tangible examples and observable relationships.'], ['What is formal operational reasoning?', 'The capacity to reason systematically about abstractions, hypotheses, and possible futures.'], ['What is the zone of proximal development?', 'The range between independent performance and performance possible with skilled assistance.'], ['What does social learning add to behavior theory?', 'Learning through models, observed consequences, expectations, self-efficacy, and practice.'], ['What does family-systems thinking prevent?', 'Treating one family member as the sole cause while ignoring reciprocal patterns and context.']]),

  chapter('sc5422-ch-03', 'ethics-law-equity-wellness', 'Ethics, Law, Equity, Safety, and Boundaries',
    'Use a structured ethical process, protect developmentally appropriate privacy, and act promptly within current law and policy when safety or reporting duties arise.',
    ['Explain confidentiality and its limits.', 'Respond appropriately to safety and mandated-reporting concerns.', 'Apply ethical decision making, boundaries, and disability-rights principles.'], [
      section('Privacy, confidentiality, and education records', 'Explain counseling purpose, records, information sharing, and foreseeable privacy limits before services begin in language the student can understand. Honor privacy to the greatest extent possible while balancing safety, parent or guardian rights, law, and policy. FERPA governs education-record access and disclosure but does not mean every employee may see every record. Verify legitimate educational interest, consent, and applicable exceptions; disclose only what is authorized and necessary through protected channels.', ['confidentiality', 'privacy limit', 'FERPA']),
      section('Safety, abuse, and urgent protective action', 'Never promise secrecy about imminent danger or suspected abuse. For immediate suicide, self-harm, or violence risk, maintain appropriate supervision, activate the current school crisis plan, involve required caregivers or emergency supports, and document. For suspected abuse or neglect, follow the jurisdiction’s reporting threshold and procedure promptly rather than conducting an independent investigation. Duty-to-warn or protect rules vary by state, so use current law, policy, qualified consultation, and timely action.', ['crisis protocol', 'mandated reporting', 'duty to protect']),
      section('Boundaries, values, and equitable service', 'Power differences make gifts, social media, business relationships, and other multiple roles ethically significant. Examine risk of exploitation, loss of objectivity, cultural meaning, continuity, and policy; consult and document. Personal beliefs do not justify withholding equitable services or imposing values. Notice bias, seek supervision and training, use culturally sustaining practice, and protect student dignity, identity, autonomy, access, and informed participation.', ['professional boundary', 'value imposition', 'implicit bias']),
      section('A disciplined ethical decision process', 'Define the dilemma and the parties, rights, power dynamics, cultural factors, developmental factors, and competing duties. Review current ethical standards, law, credential rules, and district policy. Consult knowledgeable professionals without unnecessary disclosure, generate options, compare likely benefits and harms, choose and document an action, and evaluate the result. For IDEA and Section 504 matters, contribute relevant expertise and advocacy within authorized team procedures rather than making unilateral eligibility or accommodation decisions.', ['ethical decision model', 'consultation', 'Section 504']),
    ], [['What should be explained before counseling?', 'Purpose, expectations, records, information sharing, and foreseeable limits to confidentiality in developmentally appropriate language.'], ['What comes first with imminent self-harm risk?', 'Maintain safety and supervision while activating the current crisis protocol and required protective supports.'], ['What is the counselor’s role in suspected abuse?', 'Follow current mandated-reporting law and policy promptly without independently investigating guilt.'], ['Why is duty to protect a legal caution area?', 'Specific duties and procedures vary across jurisdictions and must be verified.'], ['What is value imposition?', 'Directing a student toward the counselor’s personal beliefs rather than supporting the student ethically and equitably.'], ['What anchors an ethical decision?', 'Standards, current law and policy, cultural and developmental context, consultation, consequences, documentation, and follow-up.']]),

  chapter('sc5422-ch-04', 'individual-counseling-academic-career', 'Individual Counseling, Academic Planning, and Career Development',
    'Select brief counseling skills and planning services that match the student’s developmental need, goal, culture, context, and level of support.',
    ['Apply major brief counseling approaches.', 'Set observable collaborative goals and monitor progress.', 'Deliver developmentally responsive academic and career planning.'], [
      section('Core helping conditions and skills', 'Person-centered work emphasizes accurate empathy, genuineness, and nonjudgmental regard. Use attentive silence, open questions, concise reflections, summaries, clarification, and collaborative focus rather than interrogation or premature advice. Development, culture, language, disability, and power influence how helping behavior is experienced. Establish the purpose and privacy limits, assess safety when indicated, and keep sessions oriented to a student-valued school-relevant outcome.', ['empathy', 'reflection', 'open question']),
      section('Brief theories into action', 'CBT connects thoughts, emotions, physical responses, and behavior; identify an unhelpful interpretation, examine evidence, build a balanced alternative, and practice action. Solution-focused work identifies preferred outcomes, exceptions, coping, strengths, scaling, and small next steps. Choice or reality approaches explore wants, current behavior, evaluation, and feasible plans while preserving autonomy. Theory should clarify a decision and guide observable practice, not become jargon applied without student collaboration.', ['cognitive behavioral counseling', 'solution-focused counseling', 'scaling']),
      section('Goals, scope, referral, and progress', 'Turn vague hopes into observable, feasible student goals with a baseline, action, and review evidence. School counseling is generally brief and connected to educational functioning. When needs exceed role, time, or competence, coordinate a suitable referral, obtain required consent for communication, address transportation, cost, language, or availability barriers, follow up on connection, and continue appropriate school support. A referral list alone is not continuity of care.', ['observable goal', 'scope of practice', 'supported referral']),
      section('Academic and career development across grades', 'Educational planning integrates strengths, interests, requirements, performance, supports, access barriers, and student and family priorities. Career development begins with broad, stereotype-free awareness; later it adds exploration, self-knowledge, work values, decision skills, and comparison of multiple postsecondary routes. Interest, aptitude, achievement, and career measures are sources for exploration, not prescriptions. Explain constructs and limitations and integrate results with experiences, goals, opportunity, and contextual evidence.', ['educational planning', 'career development', 'interest inventory']),
    ], [['What are the person-centered core conditions?', 'Empathy, congruence or genuineness, and unconditional positive regard.'], ['What does CBT connect?', 'Thoughts, emotions, bodily responses, and behavior in a pattern that can be examined and practiced.'], ['What is an exception question?', 'A question about times the problem was absent or smaller and what made those times different.'], ['What makes a counseling goal useful?', 'It is collaborative, student valued, observable, feasible, and paired with evidence and a review point.'], ['What makes a referral supported?', 'Appropriate fit, consent, access problem solving, continuity, and follow-up.'], ['How should a career inventory be used?', 'As one source for exploration, integrated with goals, context, experience, skills, and other evidence.']]),

  chapter('sc5422-ch-05', 'group-classroom-crisis-prevention', 'Group, Classroom, Crisis, and Prevention Services',
    'Design safe group and classroom services, respond within coordinated crisis systems, and match prevention or intervention to the student concern and power context.',
    ['Screen and orient group members responsibly.', 'Design accessible lessons and proactive classroom routines.', 'Differentiate crisis, bullying, conflict, trauma, and common student concerns.'], [
      section('Group formation and development', 'Screen prospective members for need, readiness, safety, developmental fit, goals, schedule, and whether another service is indicated. Explain purpose, expectations, voluntary or required conditions, records, counselor privacy limits, and the inability to guarantee peer confidentiality. Early stages need structure and safety; working stages use cohesion, feedback, and practice; endings consolidate learning, prepare for feelings about termination, evaluate progress, and connect students to continuing support.', ['group screening', 'group stages', 'peer confidentiality']),
      section('Classroom instruction and management', 'Start with an observable student objective aligned to the program goal and student standards. Use explicit modeling, guided rehearsal, feedback, application, and a quick aligned check rather than equating exposure with learning. Proactive management teaches routines, provides active opportunities to respond, reinforces productive participation, and adjusts pacing and support. Preserve the goal while offering clear language, multiple representations, accessible materials, choice, and varied ways to participate and demonstrate learning.', ['lesson objective', 'guided practice', 'accessible instruction']),
      section('Crisis and trauma-informed response', 'Immediate crises require the established incident structure, accurate communication, assigned safety and reunification roles, triage, documentation, and referral. Trauma-informed support increases physical and emotional safety, predictability, voice, choice, regulation, and connection without forcing disclosure or assuming diagnosis. After a death or major event, coordinate with the team and affected family, protect privacy, use developmentally appropriate verified information, monitor risk, and avoid sensational or compulsory memorial practices.', ['crisis response', 'trauma-informed care', 'postvention']),
      section('Bullying, conflict, anxiety, and substance concerns', 'Peer mediation can fit a voluntary conflict when power is reasonably balanced and there is no serious safety threat. Bullying requires protection, authorized investigation, accountability, and work on the power imbalance, not equal compromise. Brief anxiety support can combine regulation, realistic thinking, preparation, and practice with follow-up. Suspected intoxication or overdose begins with medical and safety procedure, followed by assessment, family involvement as required, referral, and coordinated prevention.', ['bullying', 'peer mediation', 'substance-use safety']),
    ], [['What should group screening examine?', 'Need, readiness, safety, goals, developmental fit, group fit, and whether a different service is indicated.'], ['Can a counselor guarantee group confidentiality?', 'No. The counselor protects privacy and teaches norms but cannot guarantee peers’ behavior.'], ['What is an observable lesson objective?', 'A defined student behavior, the condition for performing it, and evidence or a criterion of success.'], ['What makes support trauma informed?', 'Safety, predictability, voice, choice, regulation, cultural responsiveness, connection, and no forced disclosure.'], ['When is peer mediation inappropriate?', 'When bullying, violence, coercion, or a serious power imbalance prevents safe voluntary problem solving.'], ['What comes first with visible substance impairment?', 'Immediate medical and safety action under current school protocol.']]),

  chapter('sc5422-ch-06', 'consultation-collaboration-mtss-referrals', 'Consultation, Collaboration, MTSS, Plans, and Referrals',
    'Coordinate indirect services through operational definitions, shared roles, culturally responsive partnership, tiered supports, authorized student-plan participation, and referral follow-through.',
    ['Use a structured consultation cycle.', 'Match MTSS intensity to data and review fidelity.', 'Support families, teams, IEPs, Section 504 plans, and community referrals within role.'], [
      section('Consultation as shared problem solving', 'Consultation often helps a teacher, caregiver, or other adult support a student. Build rapport, define the concern in observable terms, compare settings and exceptions, identify strengths and current supports, set a shared goal, select a feasible strategy, clarify who will do what, and schedule review. The consultee retains appropriate authority and responsibility. Follow-up should examine implementation, target outcomes, feasibility, and student experience rather than treating the meeting itself as success.', ['consultation cycle', 'operational definition', 'shared goal']),
      section('Culturally responsive family and team partnership', 'Families contribute history, culture, priorities, routines, strengths, and evidence outside school. Use accessible language, qualified interpreters, translated information when available, and communication methods that fit family access. Do not use children as interpreters for sensitive adult decisions. Interdisciplinary work clarifies goals, consent, information boundaries, roles, actions, and common data. Student voice belongs in planning through accessible opportunities to name strengths, needs, preferences, goals, and helpful supports.', ['family partnership', 'qualified interpreter', 'student voice']),
      section('MTSS without labeling students by tiers', 'MTSS combines universal prevention and instruction, targeted support, and more individualized intensive intervention. Use screening and other evidence to identify need, monitor response with repeated data, and review implementation fidelity, dosage, access, and intervention match. A tier describes support intensity, not a permanent trait. Movement should be responsive rather than a waiting period for failure, and MTSS cannot be used to delay an evaluation required under governing disability law.', ['MTSS', 'tiered support', 'implementation fidelity']),
      section('IEP, Section 504, and community coordination', 'Counselors may contribute academic, career, social/emotional, attendance, transition, and access information to authorized teams; support student and family participation; and help implement relevant services. They do not unilaterally determine eligibility or prescribe a standard plan from a diagnosis. Community referral requires resource fit, required consent for coordination, access problem solving, follow-up, and continued school support. Share only authorized information needed for the legitimate purpose.', ['IEP team', 'Section 504 team', 'referral follow-through']),
    ], [['What begins a consultation cycle?', 'A collaborative, observable definition of the concern, context, strengths, current supports, and desired change.'], ['Who owns the classroom plan in teacher consultation?', 'The teacher retains classroom responsibility while counselor and teacher share planning and review.'], ['What does an MTSS tier describe?', 'The intensity of support, not a fixed label for the student.'], ['Why collect fidelity data?', 'To distinguish a poor intervention match from incomplete or inconsistent implementation.'], ['What is an appropriate IEP contribution?', 'Relevant student evidence, family and student voice, transition and access support, and team collaboration within role.'], ['What completes a community referral?', 'Fit, consent, access support, connection follow-up, coordination, and continued role-appropriate school support.']]),

  chapter('sc5422-ch-07', 'program-foundations-alignment', 'Program Vision, Mission, Alignment, and Partnership',
    'Build foundations that connect a desired student future, the program’s present purpose, the school mission, role-aligned use of time, and representative stakeholder guidance.',
    ['Distinguish vision and mission statements.', 'Use an annual administrative conference and time data.', 'Engage a representative advisory council without breaching privacy.'], [
      section('Vision and mission do different work', 'A vision describes the desired future for students: what they can access, become, and accomplish in an equitable school system. A mission states the program’s current purpose, who it serves, how it delivers academic, career, and social/emotional development, and how it supports the school mission. Both should be concise, student centered, inclusive, ambitious, and usable for decisions. A list of counselor duties is neither a vision nor a mission.', ['program vision', 'program mission', 'school alignment']),
      section('Design is a cycle, not a calendar of activities', 'Begin with student and context evidence plus stakeholder voice. Establish foundations and measurable goals, select aligned student standards and services, assign responsibilities and resources, deliver with fidelity, assess learning and outcomes, and revise. Each activity should answer: which need and goal, for whom, through what mechanism, with what evidence? Copying another school’s program without local analysis can preserve activities while missing local barriers and priorities.', ['program design', 'alignment', 'continuous cycle']),
      section('Administrative partnership and use of time', 'An annual administrative conference creates shared understanding about priorities, counselor roles, planned services, calendars, resources, emergency coverage, and how progress will be reviewed. Verify the current template and local expectations because models update. Weekly and annual calendars make access visible. Time-use evidence should be interpreted alongside student need and service quality, then used to negotiate role-aligned assignments and feasible staffing support.', ['annual administrative conference', 'annual calendar', 'time analysis']),
      section('Advisory input with professional boundaries', 'A representative advisory group can include students, families, teachers, administrators, and community partners. It reviews program-level goals, reach, results, access, and stakeholder needs, then offers recommendations and advocacy. It does not inspect identifiable counseling records, decide individual cases, or replace professional ethical responsibility. Provide accessible aggregate information, protect small groups from identification, document recommendations, and report how input shaped the program.', ['advisory council', 'stakeholder voice', 'aggregate data']),
    ], [['What does a program vision describe?', 'The desired equitable future and outcomes for students.'], ['What does a program mission describe?', 'The program’s present purpose, population, approach, domains, and contribution to the school mission.'], ['What question aligns an activity?', 'Which student need and goal does it address, for whom, through what mechanism, and with what evidence?'], ['What is the annual administrative conference for?', 'Shared agreement about priorities, roles, time, resources, services, and review.'], ['What do calendars make visible?', 'How planned and actual counselor time provides or limits access to program services.'], ['What may an advisory council review?', 'Aggregate program goals, implementation, access, results, needs, and improvement recommendations.']]),

  chapter('sc5422-ch-08', 'program-goals-data-psychometrics', 'Outcome Goals, Data Types, Action Plans, and Measurement',
    'Translate needs into measurable outcome goals and coherent action plans while interpreting participation, learning, outcome, reliability, validity, and normative scores correctly.',
    ['Classify participation, learning, and outcome data.', 'Write annual student outcome goals and action plans.', 'Apply basic reliability, validity, percentile, and stanine concepts.'], [
      section('Three kinds of program evidence', 'Participation data describe what service occurred and who received it: lessons, sessions, students, grade levels, dosage, and reach. Mindsets & Behaviors or learning evidence shows what students know, believe, or can demonstrate after support. Outcome data show change in achievement, attendance, or behavior and discipline. A persuasive results story connects all three: the intended students received the service, learned the target, and showed movement on the meaningful outcome.', ['participation data', 'learning data', 'outcome data']),
      section('Annual student outcome goals', 'A strong goal names an identified population, a meaningful achievement, attendance, or behavior outcome, the baseline, a realistic target or magnitude, and a deadline. Disaggregate the pattern so the goal does not hide a gap. An activity such as “deliver six lessons” is not the outcome goal. Explain why the target matters, how it aligns with foundations and school priorities, and how progress will be reviewed before the endpoint.', ['baseline', 'annual outcome goal', 'closing the gap']),
      section('Action plans make goals executable', 'Connect the goal to student standards, evidence-informed strategies, delivery mode, responsible people, timeline, resources, access supports, participation data, learning checks, outcome measures, fidelity evidence, and decision points. Use needs assessments carefully: check response access, representation, nonresponse, wording, and stakeholder trust, and combine surveys with administrative data, interviews, focus groups, and observations. A plan should be specific enough that another team member can understand implementation and evaluation.', ['action plan', 'needs assessment', 'decision point']),
      section('Reliability, validity, and score interpretation', 'Reliability concerns consistency or precision under relevant conditions. Validity concerns whether evidence supports a proposed interpretation and use for the population and context; reliability alone never makes every use valid. Percentile rank is the percentage of the norm group scoring at or below a score, not percent correct. Stanines summarize normative standing in nine broad bands and should not imply false precision. Always explain the construct, comparison group, uncertainty, accommodations, and cultural or contextual limits.', ['reliability', 'validity', 'percentile rank']),
    ], [['What do participation data show?', 'Who received which service, how much, when, and through what delivery mode.'], ['What do learning data show?', 'Changes in targeted student knowledge, attitudes, beliefs, or demonstrated skills.'], ['What do outcome data show?', 'Changes in meaningful achievement, attendance, or behavior and discipline indicators.'], ['What belongs in an annual outcome goal?', 'Population, meaningful outcome, baseline, target or magnitude, timeframe, and equity context.'], ['What is reliability?', 'The consistency or precision of scores under relevant conditions.'], ['What is validity?', 'Evidence supporting a specific interpretation and use for a population and context.']]),

  chapter('sc5422-ch-09', 'program-operations-technology-resources', 'Program Operations, Technology, Resources, and Communication',
    'Manage triage, caseload, resources, technology, communication, and professional learning so the program remains safe, equitable, accessible, and evidence informed.',
    ['Prioritize urgent and routine demands transparently.', 'Protect identifiable program information and allocate resources equitably.', 'Communicate access routes and evaluate professional learning.'], [
      section('Triage, continuity, and caseload management', 'Safety and urgent protective duties come first under the crisis plan. Then sequence time-sensitive student needs, planned direct and indirect services, and routine administrative work using transparent program priorities. A backup and referral pathway protects continuity during counselor absence or demand surges. For large caseloads, combine universal, targeted, and individual delivery, use ethical triage, examine wait and reach data, and advocate for staffing rather than placing every student on an indefinite individual list.', ['triage', 'continuity plan', 'caseload']),
      section('Equitable resource decisions', 'Scarce time, grants, space, and partnerships should be allocated using disaggregated need, expected benefit, evidence, access barriers, feasibility, stakeholder input, and program alignment. Equal shares are not automatically equitable when needs and barriers differ. State criteria before choosing, document conflicts of interest, track who receives the resource and who does not, and evaluate both outcomes and reach. Adjust when a program works only for students who can already access it.', ['resource allocation', 'equity', 'reach']),
      section('Technology and data governance', 'Use approved systems, role-based access, secure authentication, minimal necessary fields, defined retention and deletion, protected transmission, and aggregate or suppressed reporting. Removing names alone may not prevent reidentification from small cells or combined details. Virtual services also require privacy expectations, accessibility, consent or assent as required, location and emergency procedures, technology alternatives, and response plans when the counselor is unavailable.', ['data minimization', 'role-based access', 'reidentification']),
      section('Communication and professional learning', 'A communication plan repeatedly explains the program, services, access routes, privacy limits, urgent-help procedures, results, and opportunities for feedback in accessible multilingual formats. It avoids guarantees and confidential examples. Select professional learning from identified competence and program needs, current evidence, ethical scope, and student context. Supported transfer includes modeling, rehearsal, feedback, supervision or coaching, implementation data, and evaluation of student effects.', ['communication plan', 'language access', 'professional learning']),
    ], [['What governs triage?', 'Immediate safety first, followed by time sensitivity, student impact, program priorities, role, and continuity.'], ['How can a large caseload be managed ethically?', 'Balance universal, targeted, and individual services with triage, referrals, reach data, and staffing advocacy.'], ['What makes resource allocation equitable?', 'Need, access barriers, expected benefit, evidence, feasibility, voice, transparency, and monitored reach.'], ['What is data minimization?', 'Collecting, using, retaining, and sharing only information needed for a legitimate purpose.'], ['Why can deidentified data still be risky?', 'Small cells and combinations of details may permit reidentification.'], ['How is professional learning evaluated?', 'By supported implementation and meaningful student or program outcomes, not attendance alone.']]),

  chapter('sc5422-ch-10', 'program-assessment-implementation', 'Program Assessment and Implementation Quality',
    'Use program and competency assessments, aligned evaluation designs, baseline and implementation evidence, and student voice to determine what is in place and what to improve.',
    ['Distinguish implementation assessment from outcome evaluation.', 'Use baseline, aligned measures, and fidelity data.', 'Convert assessment findings into prioritized improvement actions.'], [
      section('Program assessment asks what is in place', 'A program assessment compares current components and practices with an articulated model or standard. It identifies strengths, partial implementation, gaps, and priorities for development. The process should use evidence rather than aspiration and involve the team responsible for improvement. A checklist result does not establish that student outcomes changed; it tells the program whether the structures and practices expected to support those outcomes are present and implemented.', ['program assessment', 'implementation gap', 'priority']),
      section('Competency assessment supports growth', 'A professional standards and competencies assessment helps a counselor reflect on current knowledge, skills, mindsets, evidence, and development needs. Pair ratings with examples, supervision, performance feedback, student and program evidence, and a manageable learning goal. Revisit progress after supported practice. It is not an official test score, a diagnosis, or a substitute for state credentialing and district evaluation procedures.', ['competency assessment', 'self-reflection', 'professional growth goal']),
      section('Aligned evaluation starts before delivery', 'Define the student target and meaningful outcome, identify the population, record a comparable baseline, select measures aligned to the construct, establish data protections, and state a decision rule. Add pre/post or repeated learning checks, outcome indicators, participation, disaggregation, and qualitative feedback as appropriate. A measure chosen only because it is convenient or standardized may still be invalid for the decision the program needs to make.', ['baseline', 'aligned measure', 'decision rule']),
      section('Implementation evidence explains results', 'Fidelity includes adherence to core components, dosage, quality, reach, participant responsiveness, and contextual adaptations. Weak outcomes with weak implementation do not fairly test the planned intervention. Strong implementation with weak outcomes suggests a poor fit, weak theory, insufficient intensity, or an inaccurate need definition. Strong outcomes with uneven reach require access improvement. Document adaptations so the team can learn which version produced which result.', ['implementation fidelity', 'dosage', 'adaptation']),
    ], [['What does a program assessment measure?', 'The extent to which defined program components and practices are currently implemented.'], ['What does it not prove by itself?', 'That the program caused a change in student outcomes.'], ['What is a competency assessment for?', 'Evidence-based reflection, professional learning goals, supervision, and growth over time.'], ['Why collect baseline data?', 'To define the starting condition and support comparison with later evidence.'], ['What belongs in fidelity data?', 'Adherence, dosage, quality, reach, responsiveness, context, and documented adaptations.'], ['What does weak outcome plus weak fidelity mean?', 'Implementation must be addressed before the planned intervention can be judged fairly.']]),

  chapter('sc5422-ch-11', 'results-data-interpretation-reporting', 'Results Data, Interpretation, and Reporting',
    'Interpret aggregate and disaggregated results cautiously, triangulate mixed evidence, avoid unsupported causal claims, and report actionable findings without compromising privacy.',
    ['Disaggregate outcomes and examine access.', 'Interpret surveys, comparisons, and mixed evidence cautiously.', 'Build plain-language results reports with limitations and next actions.'], [
      section('Disaggregation reveals who benefits', 'A favorable schoolwide average can coexist with a worsening gap. Break down achievement, attendance, behavior, participation, and learning data by relevant grade, program, and student groups when lawful and statistically responsible. Check denominator size, missingness, opportunity, and small-cell privacy. Describe patterns without blaming groups, combine them with student and family evidence, and examine policies or access conditions that could explain unequal reach or outcomes.', ['disaggregation', 'denominator', 'outcome gap']),
      section('Survey and qualitative evidence', 'Write neutral, clear, single-focus items with response options that fit the question and intended audience. Pilot wording and accessibility, offer needed language and communication access, and examine who did not respond. Interviews and focus groups add meaning but require consent, privacy, skilled facilitation, and transparent selection. Treat stakeholder voice as evidence, not decoration, and distinguish common themes from isolated but potentially important experiences.', ['leading question', 'nonresponse bias', 'focus group']),
      section('Association is not automatically causation', 'Students who choose a service may differ from students who do not. Maturation, concurrent initiatives, historical events, regression, and measurement change can also explain improvement. Acknowledge design limits and say the program contributed to or was associated with change unless stronger methods support causal inference. Baseline, repeated measures, credible comparisons, fidelity, and converging evidence strengthen conclusions but do not erase every alternative explanation.', ['selection bias', 'causal inference', 'alternative explanation']),
      section('A useful results report leads to a decision', 'State the need and goal, intended population, services, reach and dosage, learning evidence, outcome evidence, disaggregated patterns, implementation, stakeholder voice, limitations, and the next action and review date. Use plain language, labeled visuals, definitions, and context. Protect confidentiality through aggregation, suppression, and access controls. Report unfavorable results as honestly as favorable ones and distinguish findings from recommendations.', ['results report', 'limitation', 'data visualization']),
    ], [['Why disaggregate program results?', 'To reveal differences in access, learning, and outcomes that an average may conceal.'], ['What is nonresponse bias?', 'The risk that respondents differ systematically from people who did not respond.'], ['What makes a survey item leading?', 'Wording that signals a preferred answer or embeds an untested judgment.'], ['Why avoid causal language after a simple pre/post comparison?', 'Other changes, selection, maturation, and context may explain some or all of the difference.'], ['What should a results report connect?', 'Need, goal, services, reach, learning, outcomes, equity, fidelity, limitations, and next decisions.'], ['How should small-group results be protected?', 'Use aggregation, suppression, limited access, and checks for reidentification.']]),

  chapter('sc5422-ch-12', 'continuous-improvement-advocacy', 'Continuous Improvement and Data-Based Advocacy',
    'Turn evaluation into transparent choices about what to retain, adapt, stop, scale, resource, and monitor while keeping equity and stakeholder learning central.',
    ['Use decision rules and stakeholder feedback to revise programs.', 'Communicate misses and limitations honestly.', 'Build evidence-based advocacy and responsible scaling plans.'], [
      section('Improvement is a disciplined learning cycle', 'Compare actual implementation and outcomes with the goal and prespecified decision rule. Ask which students participated, learned, and improved; which did not; what barriers and adaptations occurred; and what the data cannot establish. Retain effective components, address access and fidelity problems, change weak strategies, and identify one testable next step. Specify the responsible person, resources, timeline, and next review so reflection becomes implementation.', ['continuous improvement', 'decision rule', 'testable adaptation']),
      section('Transparent communication builds credibility', 'If a goal is missed, report the result, data quality, implementation, context, and limitations without changing the goal after seeing results or blaming students and families. Explain what was learned and the evidence-informed revision. If a goal is met, avoid overclaiming causality or permanence. Give stakeholders accessible opportunities to question interpretations and contribute contextual knowledge before final decisions are made.', ['transparent reporting', 'goal integrity', 'stakeholder interpretation']),
      section('Data-based advocacy connects need to a feasible ask', 'An advocacy case combines disaggregated local need, student and family voice, service access, counselor time and capacity, credible research, applicable standards, and a specific resource or policy request. Describe how the proposal would work, likely barriers, costs, alternatives, and how impact will be evaluated. Protect confidentiality and avoid relying only on emotionally vivid cases or a national benchmark detached from local conditions.', ['data-based advocacy', 'capacity', 'feasible request']),
      section('Scale only after checking durability and fit', 'A promising intervention should show adequate implementation, meaningful outcomes, acceptable burden, equitable reach, and stakeholder support. Before expansion, identify core components versus adaptable features, resource and training needs, data protections, and likely contextual differences. Pilot responsibly, monitor unintended effects, and build feedback loops. Sustainability depends on ownership, routines, staffing, funding, leadership, and evidence that continues after initial enthusiasm.', ['scaling', 'core component', 'sustainability']),
    ], [['What begins continuous improvement?', 'Compare goal, implementation, reach, learning, outcomes, equity, and limitations using a stated decision rule.'], ['What is a testable adaptation?', 'A defined change with a rationale, responsible person, implementation plan, outcome measure, and review date.'], ['How should a missed goal be reported?', 'Honestly, with context, limitations, learning, and a specific revision rather than blame or hidden data.'], ['What strengthens an advocacy request?', 'Local evidence, voice, research, capacity analysis, a feasible ask, privacy protection, and an evaluation plan.'], ['What should be checked before scaling?', 'Core components, fidelity, outcomes, equitable reach, burden, resources, context, and stakeholder support.'], ['What supports sustainability?', 'Ownership, routines, staffing, funding, leadership, training, feedback, and durable evidence.']]),
];

const memoryAids = [
  { title: 'Role Lens: Lead, Advocate, Collaborate, Consult, Manage', content: 'When choices all sound helpful, ask which professional role is needed and whether the response preserves shared ownership, student access, ethical boundaries, and program outcomes.', tags: ['role', 'program'], references: [S.ETS, S.ASCA_PRO] },
  { title: 'Three Student Domains: A-C-S/E', content: 'Track the complete program through Academic, Career, and Social/Emotional development. A choice that collapses counseling into only one domain is usually incomplete.', tags: ['domains', 'comprehensive program'], references: [S.ETS, S.ASCA_PRO] },
  { title: 'Development Is a Lens, Not a Label', content: 'Use stage and learning theories to predict supports and questions, then verify with the individual student and context. Age or theory alone never becomes a diagnosis.', tags: ['development', 'theory'], references: [S.ETS] },
  { title: 'Privacy: Explain, Protect, Limit, Document', content: 'Explain privacy and foreseeable limits early, protect information, disclose only when authorized or required and only as needed, then document the basis and follow-up.', tags: ['confidentiality', 'ethics'], references: [S.ASCA_ETHICS, S.FERPA] },
  { title: 'Safety Overrides Secrecy Promises', content: 'For imminent danger, maintain supervision and activate current crisis procedures. For suspected abuse, follow the jurisdiction’s mandated-reporting process without investigating independently.', tags: ['safety', 'mandated reporting'], references: [S.ASCA_ETHICS] },
  { title: 'Ethical STEPS: Standards, Team, Effects, Protect, Study', content: 'Review standards and law, consult an appropriate team, compare likely effects and power dynamics, protect student rights and safety, then study the outcome and revise.', tags: ['ethical decision making', 'consultation'], references: [S.ASCA_ETHICS] },
  { title: 'Brief Counseling: Connect, Clarify, Choose, Check', content: 'Build the relationship, clarify need and safety, choose a theory-linked student action, and check progress. Refer with continuity when the need exceeds school scope or competence.', tags: ['counseling', 'progress'], references: [S.ETS, S.ASCA_ETHICS] },
  { title: 'Service Match: All, Some, Few', content: 'Use classroom or schoolwide services for common needs, targeted groups for shared needs, and individual or intensive supports for fewer students based on evidence and safety.', tags: ['delivery', 'MTSS'], references: [S.ETS] },
  { title: 'Group Safety Before Cohesion', content: 'Screen for fit and risk, explain purpose and privacy limits, teach norms, build low-risk participation, and refer students whose needs exceed the group’s purpose or safety.', tags: ['group counseling', 'screening'], references: [S.ETS, S.ASCA_ETHICS] },
  { title: 'Bullying Is Not Balanced Conflict', content: 'Mediation requires safe voluntary participation and relative power balance. Bullying calls for protection, policy-based response, accountability, and attention to the power difference.', tags: ['bullying', 'mediation'], references: [S.ETS, S.ASCA_ETHICS] },
  { title: 'Consultation: Define, Plan, Do, Review', content: 'Operationalize the concern, define a shared goal and roles, implement a feasible strategy, then review fidelity, outcomes, feasibility, and student or family experience.', tags: ['consultation', 'collaboration'], references: [S.ETS] },
  { title: 'MTSS: Intensity, Not Identity', content: 'A tier names support intensity, not the kind of student. Maintain universal supports, add targeted or intensive help based on response data, and never use MTSS to delay required evaluation.', tags: ['MTSS', 'tiers'], references: [S.ETS, S.IDEA] },
  { title: 'Referral: Match, Consent, Access, Connect, Follow', content: 'Match the resource to need, obtain required consent for coordination, address access barriers, confirm connection, follow up, and continue appropriate school-based support.', tags: ['referral', 'continuity'], references: [S.ETS, S.ASCA_ETHICS] },
  { title: 'Vision Is Future; Mission Is Present Purpose', content: 'Vision states the desired equitable future for students. Mission states whom the program serves, what it does now, across which domains, and how it supports the school mission.', tags: ['vision', 'mission'], references: [S.ETS, S.ASCA_PROGRAM] },
  { title: 'Data Story: Participate, Learn, Improve', content: 'Participation shows who received what; learning shows targeted knowledge, attitude, or skill; outcomes show achievement, attendance, or behavior change. Strong reports connect all three.', tags: ['data types', 'results'], references: [S.ETS, S.ASCA_PRO] },
  { title: 'Goal Formula: Group + Baseline + Outcome + Target + Time', content: 'A measurable annual student outcome goal names the population, documented starting point, meaningful outcome, realistic magnitude or criterion, deadline, and equity context.', tags: ['outcome goal', 'planning'], references: [S.ETS] },
  { title: 'Measurement: Consistent Is Not Necessarily Valid', content: 'Reliability is consistency or precision. Validity is support for a specific interpretation and use. A measure can score consistently while being used for the wrong construct or decision.', tags: ['reliability', 'validity'], references: [S.ETS] },
  { title: 'Evaluation: Baseline, Delivery, Learning, Outcome, Equity', content: 'Define the starting point, verify what was delivered and to whom, measure target learning and meaningful outcomes, disaggregate results, and include limitations before deciding.', tags: ['evaluation', 'fidelity'], references: [S.ETS, S.IES_DATA] },
  { title: 'Report Both the Average and the Gap', content: 'A schoolwide gain can hide worsening access or outcomes for a group. Report aggregate and responsible disaggregated results, protect small cells, investigate barriers, and adjust.', tags: ['disaggregation', 'equity'], references: [S.ASCA_PRO, S.ASCA_ETHICS] },
  { title: 'Improve: Retain, Repair, Replace, Review', content: 'Retain effective core components, repair access or fidelity barriers, replace weak strategies when evidence warrants, and set a dated review with defined implementation and outcome data.', tags: ['continuous improvement', 'decision rule'], references: [S.ETS, S.IES_DATA] },
];

module.exports = { chapters, memoryAids };
