// Harmony Lab checks: native gestures, restorable experiments, full exports and drawing transfers.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const read=file=>fs.readFileSync(file,'utf8'),out=path.resolve('reports/artstudio-workspace');
const shell=read('dev-tools/pixel_contrast_probe.cjs').match(/const SHELL = `([\s\S]+?)`;/)[1].replace('var ctx = { React: React','window.__edit=pair[1];window.__state=pair[0];var ctx = { React: React');
(async()=>{
  const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
  page.on('pageerror',error=>errors.push(error.message));
  const studio=()=>page.locator('[data-artstudio-harmony]'),wheel=()=>page.locator('#artstudio-harmony-wheel');
  const click=name=>studio().getByRole('button',{name,exact:true}).click(),scheme=value=>page.getByLabel('Hue relationship',{exact:true}).selectOption(value);
  const colors=()=>page.locator('[data-harmony-swatch]').evaluateAll(nodes=>nodes.map(node=>({text:node.textContent,color:getComputedStyle(node).backgroundColor})));
  async function range(id,value){await page.locator('#hh-'+id).evaluate((node,next)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(node,String(next));node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));},value);}
  try{
    await page.goto('about:blank');await page.setContent('<html><head><style>'+read('dev-tools/.cache/sweep-tailwind.css')+'</style><style>body{margin:0;font-family:system-ui;background:white}*{box-sizing:border-box}</style></head><body><div id="slot"></div></body></html>');
    for(const file of ['desktop/web-app/node_modules/react/umd/react.production.min.js','desktop/web-app/node_modules/react-dom/umd/react-dom.production.min.js','stem_lab/stem_lab_module.js','stem_lab/stem_tool_artstudio.js'])await page.addScriptTag({content:read(file)});
    await page.addScriptTag({content:shell});await page.evaluate(()=>__mount('artStudio',false,{tab:'harmonyHunt',studioStarted:true,studioHome:false,pixelGrid:16,pixelData:{'2,2':'red'},studioFreeProjectId:'harmony-project',studioCurrentProjectRunId:'harmony-project',_harmonyHunt:{baseHue:200,satBlend:10,litVar:50,paletteSize:6,rotation:0,hypothesis:'My saved observation'}}));
    assert((await wheel().getAttribute('aria-label')).includes('Evenly spaced'));assert.equal(await page.locator('#hh-saturation').inputValue(),'54');await page.getByRole('button',{name:'Focus workspace',exact:true}).click();const desktop=await wheel().boundingBox();assert(desktop.width>=700);checks.push({legacyLowSaturationCorrected:true,legacyColorsPreserved:true,desktopWheelWidth:desktop.width});
    await scheme('analogous');await range('spread',30);assert.deepEqual(await page.locator('[data-harmony-swatch] span').allTextContents(),['200°','170°','230°']);await click('Log palette experiment');const original=await colors();
    const slider=page.locator('#hh-baseHue');await slider.scrollIntoViewIfNeeded();const box=await slider.boundingBox();await page.mouse.move(box.x+box.width*.2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width*.8,box.y+box.height/2,{steps:9});await page.mouse.up();await slider.focus();await page.keyboard.press('Control+z');assert.deepEqual(await colors(),original);checks.push({analogousAnglesCorrect:true,nativeSliderWholeGestureUndo:true});
    await scheme('split');await range('rotation',40);await click('Log palette experiment');const changed=await colors();await click('Restore experiment 1');assert.deepEqual(await colors(),original);await click('Undo harmony edit');assert.deepEqual(await colors(),changed);assert.equal(await page.getByLabel('Color harmony hypothesis',{exact:true}).inputValue(),'My saved observation');checks.push({experimentRestoreUndo:true,writtenObservationPreserved:true});
    await page.locator('[data-harmony-controls]').evaluate(node=>node.scrollTop=0);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'harmony-focus-desktop.png'),animations:'disabled'});
    await scheme('even');await range('paletteSize',12);assert(await studio().getByRole('button',{name:'Save first 8 colors to Thread Kit',exact:true}).isVisible());await click('Save first 8 colors to Thread Kit');assert.equal(await page.evaluate(()=>__state.artStudio.studioThreadKit.runs[0].palette.colors.length),8);
    for(const format of ['SVG','CSS']){const download=page.waitForEvent('download');await click('Download harmony '+format);await(await download).saveAs(path.join(out,'harmony-browser-export.'+format.toLowerCase()));}
    const svg=read(path.join(out,'harmony-browser-export.svg')),css=read(path.join(out,'harmony-browser-export.css'));
    const exportCheck=await page.evaluate(async({svg,css})=>{const parsed=new DOMParser().parseFromString(svg,'image/svg+xml');if(parsed.querySelector('parsererror'))throw new Error(parsed.querySelector('parsererror').textContent);const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;canvas.getContext('2d').drawImage(img,0,0);const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);const valid=[...document.querySelectorAll('[data-harmony-swatch]')].every((node,index)=>{const sample=document.createElement('span');sample.style.backgroundColor='var(--harmony-'+(index+1)+')';document.body.appendChild(sample);const same=getComputedStyle(sample).backgroundColor===getComputedStyle(node).backgroundColor;sample.remove();return same;});style.remove();return {width:img.width,height:img.height,labels:parsed.querySelectorAll('text').length,cssMatches:valid,png:canvas.toDataURL()};},{svg,css});
    assert.equal(exportCheck.width,900);assert.equal(exportCheck.height,1185);assert(exportCheck.cssMatches);for(const color of await colors())assert(svg.includes(color.text.match(/#[0-9A-F]{6}/)[0]));fs.writeFileSync(path.join(out,'harmony-export-preview.png'),Buffer.from(exportCheck.png.split(',')[1],'base64'));checks.push({fullTwelveColorSvg:true,svgDecodedDimensions:[exportCheck.width,exportCheck.height],cssMatchesEverySwatch:true,explicitEightColorTransfer:true});
    await scheme('triadic');const chosen=(await colors())[1].color;await page.locator('[data-harmony-swatch="1"]').click();await click('Use in Pixel Art');const pixel=page.locator('#pixelCanvas');await pixel.waitFor();await pixel.focus();await pixel.press('Home');await pixel.press('Enter');const painted=await pixel.evaluate(async(node)=>{const img=new Image();img.src=node._pixelExportNative();await img.decode();const c=document.createElement('canvas');c.width=c.height=16;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);return {pixel:[...ctx.getImageData(0,0,1,1).data],existing:[...ctx.getImageData(2,2,1,1).data]};});assert.deepEqual(painted.pixel,[...chosen.match(/[\d.]+/g).map(Number).map(Math.round),255]);assert.deepEqual(painted.existing,[255,0,0,255]);await page.getByLabel('Studio tool',{exact:true}).selectOption('harmonyHunt');const pigment=(await colors())[0].text.match(/#[0-9A-F]{6}/)[0].toLowerCase();await page.locator('[data-harmony-swatch="0"]').click();await click('Paint in Watercolor');assert.equal(await page.evaluate(()=>__state.artStudio.watercolorColor),pigment);await page.getByLabel('Studio tool',{exact:true}).selectOption('harmonyHunt');checks.push({pixelTransferPaintedCorrectRgb:true,existingPixelPreserved:true,watercolorTransferExact:true});
    await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));const preview=await page.locator('[data-harmony-preview]').boundingBox(),controls=await page.locator('[data-harmony-controls]').boundingBox();assert(preview.y<controls.y);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=390));const sizes=await studio().locator('button,input,select').evaluateAll(nodes=>nodes.map(node=>({width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height,overflow:node.scrollWidth>node.clientWidth+1})));assert(sizes.every(node=>node.width>=44&&node.height>=44&&!node.overflow),JSON.stringify(sizes));await page.screenshot({path:path.join(out,'harmony-phone-preview.png'),animations:'disabled'});await page.locator('[data-harmony-controls]').evaluate(node=>window.scrollBy(0,node.getBoundingClientRect().top-165));await page.screenshot({path:path.join(out,'harmony-phone-controls.png'),animations:'disabled'});checks.push({phonePreviewFirst:true,phoneNoOverflow:true,phoneTouchTargets44:true});
    assert.deepEqual(errors,[]);const result={passed:true,checks,errors};fs.writeFileSync(path.join(out,'harmony-browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
