#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const bank=JSON.parse(fs.readFileSync(path.join(root,'test_prep','eppp_native_items.json'),'utf8'));
const qa=JSON.parse(fs.readFileSync(path.join(root,'test_prep','eppp_native_qa.json'),'utf8'));
const audit=JSON.parse(fs.readFileSync(path.join(root,'test_prep','eppp_native_expansion_1500_audit.json'),'utf8'));
if(bank.length!==1500||qa.summary.totalItems!==1500||qa.summary.passedItems!==1500||qa.summary.status!=='pass')throw new Error('The 1,500-question record requires a fully passing 1,500-item bank.');
const latest=bank.filter(x=>x.expansionBatch==='native-1001-1500');if(latest.length!==500||audit.summary.addedItems!==500||audit.summary.status!=='builder-pass')throw new Error('Latest 500-item expansion audit is incomplete.');
const byDomain={};for(const x of bank)byDomain[x.domainId]=(byDomain[x.domainId]||0)+1;
const migrated=bank.filter(x=>x.legacySourceId).length,authored=bank.filter(x=>x.authoredSourceId).length,nativeOriginal=bank.length-migrated-authored;
const report={schemaVersion:3,generatedAt:new Date().toISOString(),target:1500,scope:'AlloFlow EPPP Part 1 source-reviewed practice bank',summary:{targetItems:1500,editorialQaPassedItems:qa.summary.passedItems,legacySeededReauthoredItems:migrated,sourceAuthoredItems:authored,nativeOriginalItems:nativeOriginal,pendingItems:0,status:'complete-editorial-qa'},domainCounts:byDomain,batching:{batchSize:100,batches:15,feedback:'Descriptive domain and confidence diagnostics appear after every bank; no pass prediction is made.'},latestExpansion:{id:audit.expansionId,addedItems:audit.summary.addedItems,fullChoiceRationales:audit.summary.addedItemsWithFourChoiceRationales,fullSourceDetails:audit.summary.addedItemsWithFullSourceDetails,lengthClueSetsReauthored:audit.summary.lengthClueSetsReauthored},limitations:['Not psychometrically calibrated.','Not affiliated with or endorsed by ASPPB.','Independent licensed-psychologist validation remains pending.'],items:qa.items.map((x,index)=>({slot:index+1,id:x.id,domainId:x.domainId,provenance:x.provenance,editorialQaStatus:x.qaStatus,sourceCount:x.references.length}))};
const s=report.summary,markdown='# EPPP 1,500-question curation record\n\nGenerated: '+report.generatedAt+'\n\n## Result\n\n| Metric | Count |\n| --- | ---: |\n| Target and total items | '+s.targetItems+' |\n| Editorial-QA-passed | '+s.editorialQaPassedItems+' |\n| Legacy-seeded and re-authored | '+s.legacySeededReauthoredItems+' |\n| Source-authored | '+s.sourceAuthoredItems+' |\n| Earlier native-original | '+s.nativeOriginalItems+' |\n| Pending | '+s.pendingItems+' |\n\nThe bank is arranged as fifteen blueprint-balanced banks of 100 with descriptive feedback after each bank. Results are not pass predictions.\n\n## Important limitations\n\n'+report.limitations.map(x=>'- '+x).join('\n')+'\n\n## Domain counts\n\n'+Object.entries(byDomain).map(([id,count])=>'- '+id+': '+count).join('\n')+'\n';
for(const out of [path.join(root,'test_prep','eppp_legacy'),path.join(root,'desktop/web-app','public','test_prep','eppp_legacy')]){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'curation_1500.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'curation_1500.md'),markdown);}
console.log('EPPP 1,500 curation: '+s.editorialQaPassedItems+'/1500 editorial-QA passed; '+migrated+' legacy-seeded, '+authored+' source-authored, '+nativeOriginal+' native-original.');