#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),banks=require('./school_librarian_5312/item_content.cjs'),root=path.resolve(__dirname,'..');
const refs=[...new Set(banks.flatMap(bank=>bank.references))];
const chapterPlan=[
  ['program-administration','Program Vision, Needs Assessment, and Improvement'],['program-administration','Operations, Budget, Policy, and Evaluation'],
  ['organization-access','Collection Development and Inclusive Curation'],['organization-access','Organization, Discovery, Scheduling, and Privacy'],
  ['information-access-learning-environment','Inquiry, Search, and Source Evaluation'],['information-access-learning-environment','Intellectual Freedom, Copyright, and Digital Citizenship'],
  ['teaching-learning','Collaborative Planning and Instructional Alignment'],['teaching-learning','Differentiation, Accessibility, and Learning Evidence'],['teaching-learning','Reading Engagement and Media Literacy'],['teaching-learning','Learning Environments and Purposeful Technology'],
  ['professional-development-leadership-advocacy','Professional Learning and Instructional Leadership'],['professional-development-leadership-advocacy','Partnerships, Advocacy, and Program Communication'],
];
const byId=Object.fromEntries(banks.map(bank=>[bank.id,bank]));
const reviewNote='Independently authored and source reviewed for study use; independent school-librarian, accessibility, legal, and psychometric validation remains pending.';
const chapterUse={};
const chapters=[],skills=[],flashcards=[];
for(let index=0;index<chapterPlan.length;index++){
  const [domainId,title]=chapterPlan[index],bank=byId[domainId],use=chapterUse[domainId]||0;chapterUse[domainId]=use+1;
  const chapterId='sl5312-ch-'+String(index+1).padStart(2,'0'),concepts=bank.concepts;
  const chosen=Array.from({length:5},(_,offset)=>concepts[(use*2+offset)%concepts.length]);
  const skillId=domainId+'-'+String(use+1).padStart(2,'0');
  skills.push({id:skillId,label:title,domainId,domain:bank.label,chapterId,description:chosen.map(c=>c[0]).join(', ')+'.'});
  const sections=Array.from({length:4},(_,offset)=>{const [concept,principle,,rationale]=chosen[offset];return{id:chapterId+'-section-'+String(offset+1).padStart(2,'0'),heading:concept.replace(/^./,c=>c.toUpperCase()),content:`Core decision rule: ${principle} ${rationale} On scenario questions, identify the learner or program need, examine the quality and limits of the available evidence, preserve access and professional responsibilities, select a feasible response, and state how its effect will be monitored.`,keyTerms:[concept,'equitable access','evidence-based practice'],references:refs,reviewStatus:'source-reviewed-editorial-pass',reviewNote}});
  const knowledgeChecks=chosen.map((concept,offset)=>{const [name,correct,distractors,rationale]=concept,answerIndex=offset%4,choices=[];let d=0;for(let i=0;i<4;i++)choices.push(i===answerIndex?correct:distractors[d++]);return{id:chapterId+'-check-'+String(offset+1).padStart(2,'0'),prompt:`Which action best applies sound school-library practice to ${name}?`,choices,answerIndex,rationale,references:refs,reviewStatus:'source-reviewed-editorial-pass',reviewNote}});
  chapters.push({id:chapterId,title,domainId,domain:bank.label,skillId,summary:`Apply evidence-based school-library judgment to ${chosen.map(c=>c[0]).join(', ')}.`,objectives:['Identify the governing professional principle in an applied scenario.','Distinguish equitable, evidence-based action from convenient but unsupported action.','Connect implementation evidence to a defensible next step.'],references:refs,reviewStatus:'source-reviewed-editorial-pass',reviewNote,sectionCount:4,knowledgeCheckCount:5,referenceCount:refs.length,sections,knowledgeChecks});
  const cardCount=index<3?7:6;
  for(let card=0;card<cardCount;card++){const [name,principle,,rationale]=chosen[card%chosen.length];flashcards.push({id:'sl5312-card-'+String(flashcards.length+1).padStart(3,'0'),chapterId,skillId,domainId,front:`What is the strongest decision rule for ${name}?`,back:principle+' '+rationale,reviewStatus:'source-reviewed-editorial-pass',references:refs,reviewNote:'Source-reviewed independent study card; not official ETS, AASL, or ALA content.'})}
}
const allConcepts=banks.flatMap(bank=>bank.concepts.map(concept=>({bank,concept})));
const memoryAids=allConcepts.slice(0,20).map(({bank,concept},index)=>({id:'sl5312-memory-'+String(index+1).padStart(2,'0'),title:`Decision Lens: ${concept[0].replace(/^./,c=>c.toUpperCase())}`,content:`Remember the sequence NEED → EVIDENCE → ACCESS → ACTION → MONITOR. For ${concept[0]}, the key is: ${concept[1]}`,tags:[bank.id,concept[0]],references:refs,reviewStatus:'source-reviewed-editorial-pass',reviewNote:'Retrieval cue only; verify current law, policy, license terms, professional standards, and local requirements.'}));
const summary={chapters:12,sections:48,diagrams:0,diagramPlacements:0,knowledgeChecks:60,flashcards:75,memoryAids:20,sourceReviewedChapters:12,sourceReviewedFlashcards:75,sourceReviewedMemoryAids:20,editorialReviewedSourcePendingMemoryAids:0};
const library={schemaVersion:1,generatedAt:new Date().toISOString(),libraryId:'praxis-school-librarian-5312-learning-library',packId:'praxis-school-librarian-5312',title:'Praxis School Librarian (5312) learning library',description:'Twelve source-reviewed chapters covering program administration, organization and access, information access, teaching and learning, and professional leadership.',reviewStandard:'AlloFlow School Librarian 5312 learning-library source and editorial review v1',simulation:{questionCount:120,timeMinutes:120,note:'The simulation mirrors the official selected-response count, timing, and five-domain distribution; AlloFlow does not calculate an official scaled score.'},legalCaution:'Independent preparation, not official scoring, a pass prediction, licensure decision, legal advice, copyright or privacy determination, or substitute for current requirements.',frameworkCaution:'AASL and ALA sources inform professional context; this independent library is not endorsed by ETS, AASL, or ALA.',summary,skills,chapters,diagrams:[],flashcards,memoryAids};
for(const out of[path.join(root,'test_prep'),path.join(root,'desktop/web-app','public','test_prep')]){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'school_librarian_5312_learning_library.json'),JSON.stringify(library,null,2)+'\n')}console.log('Built School Librarian 5312 learning library: 12 chapters, 48 sections, 60 checks, 75 flashcards, 20 memory aids.');
