const fs=require('fs'),{chromium}=require('playwright'),{expect}=require('@playwright/test');
const {source,makeRoom}=require('./fixtures/connected_escape_room.cjs'),{reviewResponse}=require('./fixtures/connected_escape_review.cjs');
const out=process.env.CONNECTED_ESCAPE_QA_DIR||'docs/connected-escape-room-pending/solo';fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[],audits=[];let keyboardSteps=0;
 page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.route('http://solo.test/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="en"><head><title>Independent escape room verification</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;font-family:system-ui;background:#f6f7fc}</style></head><body><button id="outside">Open connected escape room</button><main id="root"></main><button id="background">Background control</button></body></html>'}));
 async function setup(){
  await page.addScriptTag({path:'desktop/web-app/node_modules/react/umd/react.development.js'});await page.addScriptTag({path:'desktop/web-app/node_modules/react-dom/umd/react-dom.development.js'});
  await page.exposeFunction('reviewFixture',reviewResponse).catch(()=>{});
  await page.evaluate(({source,room})=>{
    window.aiCalls=[];window.liveWrites=0;window.__alloFirebase={db:{},doc:()=>{throw Error('Solo must not open a session');},updateDoc:()=>{liveWrites++;throw Error('Solo must not write live state');}};
    window.fixtureProvider=async(prompt,json)=>{aiCalls.push({prompt,json});return prompt.startsWith('Independently')?reviewFixture(prompt):JSON.stringify(window.fixtureVariant||room);};window.fixtureSource=source;
  },{source,room:makeRoom()});
  await page.addScriptTag({path:'connected_escape_room_module.js'});
  await page.evaluate(()=>{const e=React.createElement;function Root(){const [open,setOpen]=React.useState(false);window.openRoom=()=>setOpen(true);return open&&e(AlloModules.ConnectedEscapeRoomSetup,{inputText:fixtureSource,callGemini:fixtureProvider,appId:'solo-fixture',user:{uid:'learner-a'},allowLive:false,t:k=>k,onClose:()=>setOpen(false)});}window.fixtureRoot=ReactDOM.createRoot(document.getElementById('root'));fixtureRoot.render(e(Root));document.getElementById('outside').onclick=()=>openRoom();});
 }
 await page.goto('http://solo.test/');await setup();
 async function focusedVisible(){const v=await page.evaluate(()=>{const el=document.activeElement,r=el.getBoundingClientRect();const left=Math.max(0,r.left),right=Math.min(innerWidth,r.right),top=Math.max(0,r.top),bottom=Math.min(innerHeight,r.bottom);const hit=right>left&&bottom>top?document.elementFromPoint((left+right)/2,(top+bottom)/2):null;return {visible:!!hit&&(el===hit||el.contains(hit)),inside:!!el.closest('[role=dialog]'),tag:el.tagName};});expect(v.inside).toBe(true);expect(v.visible).toBe(true);}
 async function tabTo(locator){await expect(locator).toBeVisible();for(let i=0;i<180;i++){if(await locator.evaluate(el=>el===document.activeElement))return;await page.keyboard.press('Tab');keyboardSteps++;await focusedVisible();}throw Error('Could not reach '+locator);}
 async function keyButton(locator){await tabTo(locator);await page.keyboard.press('Enter');}
 const btn=name=>page.getByRole('button',{name,exact:true});
 const obj=id=>page.locator('[data-object="'+id+'"]');
 const submit=id=>keyButton(page.locator('[data-submit-object="'+id+'"]'));
 async function selectIndex(locator,index){await tabTo(locator);await page.keyboard.press('Home');for(let i=0;i<index;i++)await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}
 await page.keyboard.press('Tab');await expect(page.locator('#outside')).toBeFocused();await page.keyboard.press('Enter');await expect(btn('Close')).toBeFocused();
 expect(await page.locator('#background').evaluate(el=>el.inert)).toBe(true);
 await keyButton(btn('Generate connected room'));await expect(btn('Play solo')).toBeVisible();await expect(page.locator('[data-launch-connected]')).toHaveCount(0);
 await keyButton(btn('Check playability with AI'));await expect(page.locator('[data-playability-review]')).toContainText('independently matched every device');expect(await page.evaluate(()=>aiCalls.length)).toBe(4);
 await page.screenshot({path:out+'/review-desktop.png',fullPage:true});
 await keyButton(btn('Play solo'));await expect(btn('Back to room setup')).toBeFocused();await submit('lens');await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','1');await expect(page.locator('.cer-panel h3').first()).toBeFocused();
 await keyButton(obj('notes'));await submit('notes');await keyButton(obj('wall'));await selectIndex(page.locator('[data-tool]'),1);await submit('wall');await keyButton(obj('device'));
 await selectIndex(page.locator('[data-control="0"]'),1);await selectIndex(page.locator('[data-control="1"]'),2);await submit('device');await expect(page.getByRole('status').filter({hasText:'did not activate'})).toBeVisible();
 await keyButton(page.locator('[data-investigation-guide] summary'));await keyButton(page.locator('[data-guide-object="ledger"]'));await expect(page.locator('.cer-panel h3').first()).toBeFocused();await keyButton(page.locator('[data-guide-object="device"]'));await expect(page.locator('[data-control="0"]')).toHaveValue('0');await keyButton(btn('Jump to journal'));await expect(page.locator('.cer-journal')).toBeFocused();await keyButton(btn('Jump to selected object'));await expect(page.locator('.cer-panel h3').first()).toBeFocused();await keyButton(page.locator('[data-investigation-guide] summary'));
 await page.reload();await setup();await page.keyboard.press('Tab');await page.keyboard.press('Enter');await keyButton(btn('Play solo'));await expect(obj('device')).toHaveAttribute('aria-pressed','true');await expect(page.locator('[data-control="0"]')).toHaveValue('0');await expect(page.locator('[data-control="1"]')).toHaveValue('1');await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','3');
 await keyButton(page.locator('[data-hint-object="device"]'));await expect(page.getByRole('heading',{name:'Hint 1',exact:true})).toBeVisible();
 await selectIndex(page.locator('[data-control="0"]'),2);await selectIndex(page.locator('[data-control="1"]'),1);
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
 async function audit(name,width,dark=false,large=false,forced=false){await page.setViewportSize({width,height:900});await page.emulateMedia({forcedColors:forced?'active':'none',reducedMotion:'reduce'});await page.evaluate(({dark,large})=>{document.documentElement.classList.toggle('dark',dark);document.documentElement.style.fontSize=large?'200%':'';document.getElementById('spacing')?.remove();if(large){const s=document.createElement('style');s.id='spacing';s.textContent='.cer *{line-height:1.5!important;letter-spacing:.12em!important;word-spacing:.16em!important}.cer p{margin-bottom:2em!important}';document.head.appendChild(s);}},{dark,large});
  const result=await page.evaluate(async()=>{const dialog=document.querySelector('[role=dialog]');return {overflow:dialog.scrollWidth>dialog.clientWidth+1,violations:(await axe.run(dialog,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))};});audits.push({name,width,dark,large,forced,...result});expect(result.overflow).toBe(false);expect(result.violations).toEqual([]);if(large && await page.locator('[data-control="0"]').count())expect(await page.locator('[data-control="0"]').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(32);if(await page.locator('[data-control="0"]').count())await page.locator('[data-control="0"]').scrollIntoViewIfNeeded();else await page.getByRole('heading',{name:'The exit is open!',exact:true}).scrollIntoViewIfNeeded();if(name.startsWith('solo-debrief-'))await page.locator('[data-debrief-object="device"]').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/'+name+'.png',fullPage:true});
 }
 await audit('solo-device-desktop',1280);await audit('solo-device-mobile',320);await audit('solo-device-dark',390,true);await audit('solo-device-large-text',320,false,true);await audit('solo-device-forced-colors',390,false,false,true);await audit('solo-device-reset',1280);
 await submit('device');await keyButton(btn('Archive'));await keyButton(obj('ledger'));await submit('ledger');await keyButton(obj('sequence'));
 const order=makeRoom().nodes[5].order;for(let i=0;i<order.length;i++)while(await page.locator('[data-move-up]').evaluateAll((els,id)=>els.findIndex(el=>el.getAttribute('data-move-up')===String(id)),order[i])>i)await keyButton(page.locator('[data-move-up="'+order[i]+'"]'));
 await expect(page.locator('[data-move-up="2"]')).toHaveAttribute('aria-disabled','true');await keyButton(page.locator('[data-move-up="2"]'));expect(await page.locator('[data-move-up]').evaluateAll(els=>els.map(el=>Number(el.dataset.moveUp)))).toEqual(order);
 await submit('sequence');await keyButton(obj('door'));await submit('door');await expect(page.getByRole('heading',{name:'The exit is open!',exact:true})).toBeVisible();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','7');await expect(page.getByRole('heading',{name:'The exit is open!',exact:true})).toBeFocused();await expect(page.locator('[data-room-debrief]')).toContainText('Hints revealed: 1');await expect(page.locator('[data-room-debrief]')).not.toContainText('Objects completed with teacher support');await expect(page.getByText('Your unfinished settings are saved in this tab.',{exact:true})).toHaveCount(0);await audit('solo-complete-mobile',320);await keyButton(page.locator('[data-debrief-trail] > summary'));await keyButton(page.locator('[data-debrief-object="device"] > summary'));await expect(page.locator('[data-debrief-object="device"]')).toContainText('Water-cycle notes');await expect(page.locator('[data-debrief-object="device"]')).toContainText('Heat Chamber A');await keyButton(page.locator('[data-revisit-object="device"]'));await expect(page.getByRole('heading',{name:'Weather simulator',exact:true})).toBeFocused();await keyButton(btn('Jump to room debrief'));await expect(page.getByRole('heading',{name:'The exit is open!',exact:true})).toBeFocused();await keyButton(page.locator('[data-debrief-discussion] > summary'));await expect(page.locator('[data-debrief-discussion]')).toContainText('Reflect on what you discovered');await audit('solo-debrief-expanded',320);await audit('solo-debrief-large-text',320,false,true);await audit('solo-debrief-dark',390,true);await audit('solo-debrief-forced-colors',390,false,false,true);await audit('solo-debrief-reset',1280);
 await keyButton(btn('Back to room setup'));await expect(btn('Play solo')).toBeFocused();await keyButton(btn('Play solo'));await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','7');
 await keyButton(btn('Restart solo room'));await expect(btn('Cancel')).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','7');await keyButton(btn('Restart solo room'));await keyButton(btn('Reset my progress'));await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('#outside')).toBeFocused();expect(await page.locator('#background').evaluate(el=>el.inert)).toBe(false);expect(await page.evaluate(()=>liveWrites)).toBe(0);expect(errors).toEqual([]);
 // Preserve two variants and their own solo progress, including library selection on reload.
 await page.locator('#outside').click();await btn('Play solo').click();await page.locator('[data-submit-object="lens"]').click();await expect(page.locator('[data-new-lead="wall"]')).toBeVisible();await btn('Back to room setup').click();
 await page.evaluate(room=>window.fixtureVariant={...room,title:'The Observatory Variation'},makeRoom());await btn('Generate another room').click();await btn('Save room in this browser').click();await btn('Play solo').click();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await obj('notes').click();await page.locator('[data-submit-object="notes"]').click();await btn('Back to room setup').click();
 await page.locator('[data-room-library] summary').click();const options=await page.locator('[data-saved-room-picker] option').evaluateAll(els=>els.map(el=>({value:el.value,text:el.textContent})));expect(options.filter(o=>o.value)).toHaveLength(2);const first=options.find(o=>o.text.includes('Weather Station')).value;await page.locator('[data-saved-room-picker]').selectOption(first);await expect(page.locator('[data-saved-room-picker]')).toHaveValue(first);
 const libraryAxe=await page.evaluate(async()=>(await axe.run(document.querySelector('[role=dialog]'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>v.id));expect(libraryAxe).toEqual([]);await page.screenshot({path:out+'/saved-library-mobile.png',fullPage:true});
 await btn('Play solo').click();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','1');await expect(obj('lens')).toContainText('Complete');await expect(obj('notes')).toContainText('Ready to investigate');await btn('Back to room setup').click();await page.reload();await setup();await page.locator('#outside').click();await btn('Play solo').click();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','1');
 await page.locator('[data-investigation-guide] summary').click();await page.locator('[data-investigation-guide]').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/investigation-guide-mobile.png',fullPage:true});await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});expect(await page.evaluate(async()=>(await axe.run(document.querySelector('[role=dialog]'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>v.id))).toEqual([]);await page.keyboard.press('Escape');
 // Separate coordinate room confirms keyboard position announcements and boundary focus.
 await page.evaluate(room=>{const node=room.nodes[5];node.type='route';node.grid={size:3,originX:1,originY:1,dx:1,dy:1};window.routeRoom=room;const state=AlloModules.ConnectedEscapeRoomEngine.emptyProgress();state.solved={notes:true,ledger:true};const session=AlloModules.ConnectedEscapeRoomEngine.createSession(room,'host',{learner:{}});session.teamProgress.All.connected[session.attemptId]=state;window.__alloFirebase.updateDoc=async()=>{};fixtureRoot.render(React.createElement(AlloModules.ConnectedEscapeRoomStudent,{sessionData:{escapeRoomState:session},user:{uid:'learner'},targetAppId:'route',activeSessionCode:'ROUTE',t:k=>k}));},makeRoom());
 await btn('Archive').click();await obj('sequence').click();await btn('West').focus();await page.keyboard.press('Enter');await expect(btn('West')).toBeFocused();await expect(page.getByRole('status').filter({hasText:'Position: column'})).toContainText('column 1, row 1');await btn('North').focus();await page.keyboard.press('Enter');await btn('East').focus();await page.keyboard.press('Enter');await expect(page.getByRole('status').filter({hasText:'Position: column'})).toContainText('column 2, row 2');
 fs.writeFileSync(out+'/verification.json',JSON.stringify({passed:true,ai:'Deterministic fixture through independent production review requests',soloTransportWrites:0,keyboardTabSteps:keyboardSteps,scenarios:['saved library preserves two variations and separate progress','saved selection resumes after reload','guide cross-area keyboard navigation','journal keyboard shortcuts','new investigation links','standalone solo generation','independent review without answer key','keyboard-only complete room','wrong-answer feedback','reload progress and unsent settings','personal hints','boundary focus and movement announcements','resume completed room','expanded evidence and lesson review','keyboard revisit with debrief return','completed solo reflection prompts','confirmed restart','modal background inertness and restored trigger focus','coordinate boundary and text position'],audits,errors},null,2));console.log('Solo and review browser checks passed; '+keyboardSteps+' keyboard tab steps, zero live writes, WCAG 2.2 automated rules, large text and forced colors.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
