const fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{expect}=require('@playwright/test');
const {makeGsSandbox}=require('./fixtures/shared_activity_mailbox.cjs'),{source,makeRoom}=require('./fixtures/connected_escape_room.cjs');
const anti=fs.readFileSync('AlloFlowANTI.txt','utf8');
const start=anti.indexOf('// ── Class Mailbox session-document bridge (Phase C: single-pathway unification) ──'),end=anti.indexOf('_applyMbSessionAdapter(); // Boot wrap',start);
if(start<0||end<0)throw Error('Production session adapter not found');
const adapter=anti.slice(start,end);
(async()=>{
 const sb=makeGsSandbox(),admin=sb.call({a:'claim'}).admin,code='ESCAP',secret='connected_fixture_secret_12345';
 const check=result=>{if(!result.ok)throw Error('Mailbox: '+JSON.stringify(result));return result;};
 check(sb.call({a:'open',admin,c:code,k:secret}));
 const guests=Array.from({length:3},()=>check(sb.call({a:'join',c:code,k:secret})));
 const roster=Object.fromEntries(guests.slice(0,2).map((g,i)=>[g.uid,{uid:g.uid,name:['Rowan','Sky'][i]}]));
 const hostCall=p=>check(sb.call({admin,c:code,k:secret,...p}));
 hostCall({a:'dset',p:'s',d:{hostId:'host',mode:'sync',roster,quizState:{isActive:false}}});
 let completedReceiptCount=0, completedDocumentChars=0;
 const browser=await chromium.launch({headless:true}),pages=[],errors=[],writes=[],out=process.env.CONNECTED_ESCAPE_QA_DIR||'docs/connected-escape-room-pending/live';fs.mkdirSync(out,{recursive:true});
 try{
  const setup=async(page,guest=null)=>{
   await page.addScriptTag({path:'desktop/web-app/node_modules/react/umd/react.development.js'});
   await page.addScriptTag({path:'desktop/web-app/node_modules/react-dom/umd/react-dom.development.js'});
   await page.evaluate(({adapter,admin,code,secret,guest})=>{
    const fail=()=>{throw Error('Unexpected Firebase fallback');};
    window.__alloShared={db:{},warnLog:()=>{}};window.AlloModules={};window.fixtureWrites=[];
    const base={doc:fail,getDoc:fail,setDoc:fail,updateDoc:fail,deleteDoc:fail,onSnapshot:fail,collection:fail,mailboxCall:async(_url,p)=>{
     if(p.a==='dpatch'&&window.failNextWrite){window.failNextWrite=false;throw Error('Simulated offline request');}
     if(p.a==='dpatch'&&window.failHostProgress&&Object.keys(p.u||{}).some(k=>k.includes('.connected.')))throw Error('Teacher connection interrupted');
     if(p.a==='dpatch')fixtureWrites.push(p.u);if(p.a==='dpatch'&&window.holdNextWrite){window.holdNextWrite=false;await new Promise(resolve=>window.releaseHeldWrite=resolve);}
     const result=await mailboxCall(p);if(result.ok===false)throw Object.assign(Error(result.e),{code:'allo/mailbox-'+result.e});return result;
    },isDeleteSentinel:v=>v?.__op==='deleteField'};
    const factory=new Function('base',`let doc=base.doc,getDoc=base.getDoc,setDoc=base.setDoc,updateDoc=base.updateDoc,deleteDoc=base.deleteDoc,onSnapshot=base.onSnapshot,collection=base.collection;const _alloMailboxCall=base.mailboxCall,_alloMailboxCallWithRetry=base.mailboxCall,_alloLanIsDeleteSentinel=base.isDeleteSentinel;${adapter}\n_applyMbSessionAdapter();return {doc:(...a)=>doc(...a),getDoc:r=>getDoc(r),setDoc:(...a)=>setDoc(...a),updateDoc:(...a)=>updateDoc(...a),onSnapshot:(...a)=>onSnapshot(...a),install:_alloMbInstallBridge,teardown:_alloMbTeardownBridge,pump:()=>_alloMbPumpTick(_alloMbBridgeState)};`);
    window.bridge=factory(base);bridge.install(guest?{url:'http://connected.test/exec',code,participant:guest.pt,isTeacher:false,uid:guest.uid}:{url:'http://connected.test/exec',code,admin,secret,isTeacher:true});
    window.__alloFirebase={...bridge,deleteField:()=>({__op:'deleteField'}),db:{},auth:{currentUser:{uid:guest?.uid||'host'}}};
    window.fixtureRef=bridge.doc({},'artifacts','fixture','public','data','sessions',code);
   },{adapter,admin:guest?'':admin,code,secret:guest?'':secret,guest});
   await page.addScriptTag({path:'connected_escape_room_module.js'});
   await page.evaluate(({guest,source,room})=>{
    const e=React.createElement;window.aiCalls=[];window.aiMode='repair';
    window.fixtureProvider=async(prompt,json)=>{aiCalls.push({prompt,json});if(window.aiMode==='offline')throw Error('AI provider offline');if(window.aiMode==='repair'&&aiCalls.length===1)return '{}';return JSON.stringify(room);};
    function Root(){const [data,setData]=React.useState(null),[open,setOpen]=React.useState(!guest),[showHost,setHost]=React.useState(true),[mountId,setMountId]=React.useState(0);window.setHostVisible=setHost;window.remountStudent=()=>setMountId(n=>n+1);window.openSetup=()=>setOpen(true);React.useEffect(()=>bridge.onSnapshot(fixtureRef,s=>{window.fixtureData=s.data();setData(s.data());}),[]);const props={sessionData:data,activeSessionCode:'ESCAP',appId:'fixture',targetAppId:'fixture',user:{uid:guest?.uid||'host'},t:k=>k};if(guest)return e(AlloModules.ConnectedEscapeRoomStudent,{...props,key:mountId});return e(React.Fragment,null,open&&e(AlloModules.ConnectedEscapeRoomSetup,{...props,inputText:source,callGemini:fixtureProvider,onClose:()=>setOpen(false)}),showHost&&e(AlloModules.ConnectedEscapeRoomTeacher,props));}
    window.fixtureRoot=ReactDOM.createRoot(document.getElementById('root'));fixtureRoot.render(e(Root));
   },{guest,source,room:makeRoom()});
  };
  const newPage=async guest=>{
   const page=await browser.newPage({viewport:{width:guest?390:1280,height:guest?844:980}});pages.push(page);page.on('pageerror',e=>errors.push(e.message));
   await page.route('http://connected.test/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="en"><head><title>Connected escape room verification</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#f6f7fc}#root{max-width:1150px;margin:auto;padding:20px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}</style></head><body><main id="root"></main></body></html>'}));
   await page.goto('http://connected.test/');await page.exposeFunction('mailboxCall',p=>{if(p.a==='dpatch')writes.push(p);return sb.call(p);});await setup(page,guest);return page;
  };
  const teacher=await newPage(),a=await newPage(guests[0]),b=await newPage(guests[1]);
  const pump=async()=>{await Promise.all(pages.map(p=>p.evaluate(()=>bridge.pump())));};
  const progress=()=>{const s=hostCall({a:'dget',ps:[{p:'s'}]}).docs[0].d.escapeRoomState;return s?.teamProgress.All.connected[s.attemptId];};
  const synced=async fn=>expect.poll(async()=>{await pump();return fn();},{timeout:20000,intervals:[200,300,500]}).toBe(true);
  const object=async(page,id)=>{await page.getByRole('button',{name:['ledger','sequence','door'].includes(id)?'Archive':'Laboratory',exact:true}).click();await page.locator('[data-object="'+id+'"]').click();};
  const submit=async(page,id)=>{await page.locator('[data-submit-object="'+id+'"]').click();};
  await teacher.getByRole('button',{name:'Generate connected room',exact:true}).click();await expect(teacher.getByRole('button',{name:'Try the room',exact:true})).toBeVisible();expect(await teacher.evaluate(()=>aiCalls.length)).toBe(2);
  await teacher.getByRole('button',{name:'Close',exact:true}).focus();await teacher.keyboard.press('Shift+Tab');await expect(teacher.locator('[data-launch-connected]')).toBeFocused();await teacher.keyboard.press('Tab');await expect(teacher.getByRole('button',{name:'Close',exact:true})).toBeFocused();await teacher.addScriptTag({path:require.resolve('axe-core/axe.min.js')});expect(await teacher.evaluate(async()=>(await axe.run(document.querySelector('[role=dialog]'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}})).violations.map(v=>v.id))).toEqual([]);await teacher.screenshot({path:out+'/teacher-review.png',fullPage:true});
  await teacher.getByRole('button',{name:'Try the room',exact:true}).click();await submit(teacher,'lens');await expect(teacher.getByRole('progressbar')).toHaveAttribute('aria-valuenow','1');await teacher.getByRole('button',{name:'Reset preview',exact:true}).click();await expect(teacher.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');
  await teacher.evaluate(()=>window.aiMode='offline');await teacher.getByRole('button',{name:'Generate another room',exact:true}).click();await expect(teacher.getByRole('alert')).toContainText('AI provider offline');await expect(teacher.getByRole('progressbar')).toBeVisible();
  const beforeImportWrites=writes.length;await teacher.locator('[data-room-transfer] > summary').click();await teacher.locator('[data-import-room]').setInputFiles({name:'class-room.alloroom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'alloflow-connected-escape',version:1,source,language:'English',room:makeRoom()}))});await expect(teacher.locator('[data-open-imported]')).toBeEnabled();await teacher.locator('[data-open-imported]').click();expect(writes.length).toBe(beforeImportWrites);
  await teacher.evaluate(()=>window.failNextWrite=true);await teacher.locator('[data-launch-connected]').click();await expect(teacher.getByRole('alert')).toContainText('could not launch');await teacher.locator('[data-launch-connected]').click();await expect(teacher.getByRole('dialog')).toHaveCount(0);await pump();
  await expect(a.getByRole('heading',{name:makeRoom().title})).toBeVisible();await object(b,'notes');await Promise.all([submit(a,'lens'),submit(b,'notes')]);await synced(()=>Object.keys(progress()?.solved||{}).length===2);await pump();await expect(a.getByRole('progressbar')).toHaveAttribute('aria-valuenow','2');await expect(b.getByRole('progressbar')).toHaveAttribute('aria-valuenow','2');
  await expect(a.locator('[data-new-lead="wall"]')).toBeVisible();await a.locator('[data-new-lead="wall"]').click();await expect(a.locator('[data-object="wall"]')).toHaveAttribute('aria-pressed','true');
  await object(a,'wall');await a.locator('[data-tool]').selectOption('0');await submit(a,'wall');await synced(()=>progress()?.solved.wall===true);
  await object(a,'device');await a.locator('[data-control="0"]').selectOption('0');await a.locator('[data-control="1"]').selectOption('1');
  await expect(a.locator('[data-relevant-clue="notes-found"]')).toContainText('Water evaporates when heated');await expect(a.locator('[data-relevant-clue="wall-found"]')).toContainText('Chamber A');
  await a.evaluate(()=>{bridge.teardown();fixtureRoot.unmount();});await a.reload();await setup(a,guests[0]);await expect(a.locator('[data-control="0"]')).toHaveValue('0');await expect(a.locator('[data-control="1"]')).toHaveValue('1');expect(await a.evaluate(()=>fixtureWrites.length)).toBe(0);
  await submit(a,'device');await synced(()=>Object.values(progress()?.receipts||{}).some(r=>r.code==='try-again'));await expect(a.getByRole('status').filter({hasText:'did not activate'})).toBeVisible();await expect(a.locator('[data-control="0"]')).toHaveValue('0');
  await a.locator('.cer-panel').first().evaluate(el=>el.scrollIntoView({block:'start'}));await a.screenshot({path:out+'/student-evidence-mobile.png',fullPage:true});
  await teacher.locator('[data-team-activity] summary').click();await expect(teacher.locator('[data-team-activity]')).toContainText('1 attempt needs another try');await teacher.screenshot({path:out+'/teacher-team-activity.png',fullPage:true});
  await teacher.getByRole('button',{name:'Pause room',exact:true}).click();await pump();await expect(a.locator('[data-submit-object="device"]')).toBeDisabled();await expect(a.locator('[data-control="0"]')).toHaveValue('0');await teacher.getByRole('button',{name:'Resume room',exact:true}).click();await pump();
  await teacher.locator('[data-support-picker]').selectOption('device');await expect(teacher.locator('[data-hint-preview]')).toContainText('Hint 1 of 3');await a.locator('[data-hint-object="device"]').click();await synced(()=>progress()?.hints.device?.h1===true);await object(b,'device');await pump();await expect(b.getByRole('heading',{name:'Shared hint 1',exact:true})).toBeVisible();await expect(teacher.locator('[data-hint-preview]')).toContainText('Hint 1 of 3');await expect(teacher.locator('[data-hint-preview]')).toContainText('already been shared');await teacher.locator('[data-preview-next-hint]').click();await expect(teacher.locator('[data-hint-preview]')).toContainText('Hint 2 of 3');await teacher.locator('[data-share-hint]').click();await synced(()=>progress()?.hints.device?.h2===true);await pump();await expect(b.getByRole('heading',{name:'Shared hint 2',exact:true})).toBeVisible();
  // A failed write is retained; retry sends the exact same request ID.
  await a.locator('[data-control="0"]').selectOption('1');await a.locator('[data-control="1"]').selectOption('0');await a.evaluate(()=>window.failNextWrite=true);await submit(a,'device');await expect(a.getByRole('alert')).toContainText('attempt is kept');const retained=await a.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('allo-connected-pending:')).map(k=>JSON.parse(sessionStorage.getItem(k)))[0].requestId);await a.getByRole('button',{name:'Retry this action',exact:true}).click();await synced(()=>progress()?.solved.device===true);expect(progress().receipts[retained].accepted).toBe(true);
  // Host navigation / temporary unavailability queues the student's action.
  await teacher.evaluate(()=>setHostVisible(false));await object(b,'ledger');await submit(b,'ledger');await pump();expect(progress().solved.ledger).toBeUndefined();
  await a.locator('[data-team-activity] summary').click();await expect(a.locator('[data-activity-node="ledger"]')).toContainText('awaiting confirmation');await expect(a.locator('[data-team-activity]')).not.toContainText('Sky');const writesBefore=await a.evaluate(()=>fixtureWrites.length);await a.locator('[data-activity-node="ledger"] button').click();await expect(a.locator('[data-object="ledger"]')).toHaveAttribute('aria-pressed','true');expect(await a.evaluate(()=>fixtureWrites.length)).toBe(writesBefore);
  await expect(b.getByRole('status').filter({hasText:'Waiting for the teacher'})).toBeVisible();
  await b.evaluate(()=>{bridge.teardown();fixtureRoot.unmount();});await b.reload();await setup(b,guests[1]);await expect(b.getByRole('status').filter({hasText:'Waiting for the teacher'})).toBeVisible();
  await teacher.evaluate(()=>setHostVisible(true));await synced(()=>progress()?.solved.ledger===true);await pump();await expect(b.getByRole('status').filter({hasText:'Discovery confirmed'})).toBeVisible();
  // Late joiner claims only its own party slot and receives existing evidence.
  const g=guests[2];hostCall({a:'dpatch',p:'s',u:{['roster.'+g.uid]:{uid:g.uid,name:'River'}}});const c=await newPage(g);await synced(()=>hostCall({a:'dget',ps:[{p:'s'}]}).docs[0].d.escapeRoomState.teams[g.uid]==='All');await pump();await expect(c.getByRole('progressbar')).toHaveAttribute('aria-valuenow','5');
  await object(b,'sequence');const order=[2,3,0,1];for(let i=0;i<order.length;i++){while(await b.locator('.cer-sequence li').evaluateAll((els,id)=>els.findIndex(el=>el.querySelector('[data-move-up]').getAttribute('data-move-up')===String(id)),order[i])>i)await b.locator('[data-move-up="'+order[i]+'"]').click();}
  await b.evaluate(()=>{bridge.teardown();fixtureRoot.unmount();});await b.reload();await setup(b,guests[1]);await expect(b.locator('[data-object="sequence"]')).toHaveAttribute('aria-pressed','true');expect(await b.locator('[data-move-up]').evaluateAll(els=>els.map(el=>Number(el.getAttribute('data-move-up'))))).toEqual(order);
  await submit(b,'sequence');await synced(()=>progress()?.solved.sequence===true);
  await object(c,'door');await submit(c,'door');await synced(()=>progress()?.solved.door===true);await pump();for(const page of [a,b,c])await expect(page.getByRole('heading',{name:'The exit is open!',exact:true})).toBeVisible();
  completedReceiptCount=Object.keys(progress().receipts).length;completedDocumentChars=JSON.stringify(hostCall({a:'dget',ps:[{p:'s'}]}).docs[0].d).length;expect(completedReceiptCount).toBeLessThanOrEqual(3);expect(completedDocumentChars).toBeLessThan(85*1024);
  const completionWrites=writes.length;for(const page of [teacher,a]){await page.locator('[data-debrief-trail] > summary').click();await page.locator('[data-debrief-object="device"] > summary').click();await expect(page.locator('[data-debrief-object="device"]')).toContainText('Water-cycle notes');await expect(page.locator('[data-debrief-object="device"]')).toContainText('Heat Chamber A');await page.locator('[data-debrief-discussion] > summary').click();}await a.locator('[data-revisit-object="device"]').click();await expect(a.getByRole('heading',{name:'Weather simulator',exact:true})).toBeFocused();await a.getByRole('button',{name:'Jump to room debrief',exact:true}).click();await expect(a.getByRole('heading',{name:'The exit is open!',exact:true})).toBeFocused();expect(writes.length).toBe(completionWrites);const completionAudits=[];for(const page of [teacher,a]){await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const result=await page.evaluate(async()=>({overflow:document.documentElement.scrollWidth>innerWidth,violations:(await axe.run(document.querySelector('.cer'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}})).violations.map(v=>v.id)}));expect(result.overflow).toBe(false);expect(result.violations).toEqual([]);completionAudits.push({state:'expanded completion review',...result});}await teacher.screenshot({path:out+'/teacher-complete.png',fullPage:true});await a.screenshot({path:out+'/student-complete-mobile.png',fullPage:true});
  await teacher.getByRole('button',{name:'Restart this room',exact:true}).click();await teacher.getByRole('button',{name:'Restart for everyone',exact:true}).click();await pump();await expect(a.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');
  await teacher.getByRole('combobox',{name:'Choose an available object',exact:true}).selectOption('lens');await teacher.getByRole('combobox',{name:'Reason for a rescue unlock',exact:true}).selectOption('technical');const beforeRescue=writes.length;const rescue=teacher.getByRole('button',{name:'Unlock this object for the team',exact:true});await rescue.click();await expect(teacher.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();expect(writes.length).toBe(beforeRescue);await teacher.keyboard.press('Escape');await expect(rescue).toBeFocused();expect(writes.length).toBe(beforeRescue);await rescue.click();await teacher.locator('[data-rescue-confirm]').scrollIntoViewIfNeeded();await teacher.screenshot({path:out+'/teacher-rescue-review.png',fullPage:true});await teacher.evaluate(()=>window.failNextWrite=true);await teacher.locator('[data-confirm-rescue]').click();await expect(teacher.getByRole('alert')).toContainText('could not be saved');await expect(teacher.locator('[data-rescue-confirm]')).toBeVisible();await teacher.locator('[data-confirm-rescue]').click();await synced(()=>progress()?.assisted.lens===true);expect(progress().rescueReasons.lens).toBe('technical');
  await object(a,'wall');await pump();await a.screenshot({path:out+'/student-tool-mobile.png',fullPage:true});await teacher.screenshot({path:out+'/teacher-live.png',fullPage:true});
  // Prepare another puzzle while a send, and then its host confirmation, are delayed.
  await object(b,'notes');await submit(b,'notes');await object(c,'ledger');await submit(c,'ledger');await a.locator('[data-tool]').selectOption('0');await submit(a,'wall');await synced(()=>progress()?.solved.notes===true&&progress()?.solved.ledger===true&&progress()?.solved.wall===true);await pump();
  await teacher.evaluate(()=>setHostVisible(false));await object(a,'device');await a.locator('[data-control="0"]').selectOption('1');await a.locator('[data-control="1"]').selectOption('0');await a.evaluate(()=>window.holdNextWrite=true);await submit(a,'device');await expect(a.locator('[data-pending-action]')).toContainText('Sending your action');
  const heldRequest=await a.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('allo-connected-pending:')).map(k=>JSON.parse(sessionStorage.getItem(k)))[0]);const draftWrites=await a.evaluate(()=>fixtureWrites.length);
  await object(a,'sequence');await expect(a.locator('[data-move-up="2"]')).toBeEnabled();const preparedOrder=[2,3,0,1];for(let i=0;i<preparedOrder.length;i++)while(await a.locator('[data-move-up]').evaluateAll((els,id)=>els.findIndex(el=>el.getAttribute('data-move-up')===String(id)),preparedOrder[i])>i){await a.locator('[data-move-up="'+preparedOrder[i]+'"]').focus();await a.keyboard.press('Enter');}
  await expect(a.locator('[data-submit-object="sequence"]')).toBeDisabled();await expect(a.locator('[data-hint-object="sequence"]')).toBeDisabled();expect(await a.evaluate(()=>fixtureWrites.length)).toBe(draftWrites);
  await a.evaluate(()=>releaseHeldWrite());await synced(()=>hostCall({a:'dget',ps:[{p:'s'}]}).docs[0].d.escapeRoomState.teamProgress.All.connectedActions[guests[0].uid]?.requestId===heldRequest.requestId);await expect(a.locator('[data-pending-action]')).toContainText('Waiting for the teacher');expect(progress().solved.device).toBeUndefined();
  await a.locator('[data-return-pending]').click();await expect(a.getByRole('heading',{name:'Weather simulator',exact:true})).toBeFocused();await expect(a.locator('[data-control="0"]')).toBeDisabled();await object(a,'sequence');
  await a.evaluate(()=>{bridge.teardown();fixtureRoot.unmount();});await a.reload();await setup(a,guests[0]);await expect(a.locator('[data-object="sequence"]')).toHaveAttribute('aria-pressed','true');expect(await a.locator('[data-move-up]').evaluateAll(els=>els.map(el=>Number(el.dataset.moveUp)))).toEqual(preparedOrder);await expect(a.locator('[data-pending-action]')).toContainText('Waiting for the teacher');expect(await a.evaluate(()=>fixtureWrites.length)).toBe(0);
  const pendingAudits=[];await a.addScriptTag({path:require.resolve('axe-core/axe.min.js')});for(const [width,dark,large] of [[320,false,false],[390,true,false],[320,false,true],[390,false,false]]){await a.setViewportSize({width,height:900});await a.evaluate(({dark,large})=>{document.documentElement.classList.toggle('dark',dark);document.documentElement.style.fontSize=large?'200%':'';},{dark,large});const result=await a.evaluate(async()=>({overflow:document.documentElement.scrollWidth>innerWidth,violations:(await axe.run(document.querySelector('.cer'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}})).violations.map(v=>v.id)}));expect(result.overflow).toBe(false);expect(result.violations).toEqual([]);pendingAudits.push({state:'pending action with editable second puzzle',width,dark,large,...result});await a.locator('[data-pending-action]').scrollIntoViewIfNeeded();await a.screenshot({path:out+'/pending-'+width+'-'+dark+'-'+large+'.png',fullPage:true});}
  const focusMove=a.locator('[data-move-up="3"]');await focusMove.focus();await teacher.evaluate(()=>setHostVisible(true));await synced(()=>progress()?.solved.device===true);await pump();await expect(a.locator('[data-pending-action]')).toHaveCount(0);await expect(focusMove).toBeFocused();expect(await a.locator('[data-move-up]').evaluateAll(els=>els.map(el=>Number(el.dataset.moveUp)))).toEqual(preparedOrder);await expect(a.locator('[data-submit-object="sequence"]')).toBeEnabled();expect(await a.evaluate(()=>fixtureWrites.length)).toBe(0);await expect(a.locator('[data-action-feedback]')).toContainText('Weather simulator: Discovery confirmed');await submit(a,'sequence');await synced(()=>progress()?.solved.sequence===true);await pump();
  const audits=[];for(const [page,width,dark] of [[teacher,1280,false],[a,390,false],[a,320,false],[b,390,true]]){await page.setViewportSize({width,height:900});await page.evaluate(dark=>document.documentElement.classList.toggle('dark',dark),dark);await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const result=await page.evaluate(async()=>({overflow:document.documentElement.scrollWidth>innerWidth,violations:(await axe.run(document.querySelector('.cer'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))}));audits.push({width,dark,...result});expect(result.overflow).toBe(false);expect(result.violations).toEqual([]);}
  await teacher.getByRole('button',{name:'End room',exact:true}).click();await teacher.getByRole('button',{name:'End for everyone',exact:true}).click();await pump();await expect(a.getByRole('region',{name:'Collaborative escape room'})).toHaveCount(0);expect(errors).toEqual([]);
  fs.writeFileSync(out+'/verification.json',JSON.stringify({passed:true,transport:'Real AlloFlow session adapter + real Apps Script handlers with local service substitutes',ai:'Deterministic provider fixture through production generation and validation flow',independentBrowsers:4,completedReceiptCount,completedDocumentChars,permissionCheckedWrites:writes.length,scenarios:['AI repair','keyboard focus trap','setup accessibility','bounded acknowledgement history','AI failure preserves preview','preview reset','imported room launch','launch failure and retry','concurrent discoveries','newly opened investigation navigation','functional tool','wrong settings preserve draft','pause/resume','shared hints','relevant collected clues','unsent device draft reload','sequence draft reload','read-only teammate navigation','teacher retry overview','failed action retry identity','student reload with pending action','host reconnection drains queue','late join','sequence device','shared final exit','restart','teacher rescue reason','previewed hint protected from concurrent learner hints','expanded shared completion review','read-only revisit and debrief focus','rescue cancellation and failure retry','prepare a second puzzle during a delayed send','pending request and prepared draft survive reload','submitted settings stay fixed','no second submission before confirmation','confirmation preserves focus on another puzzle','end room'],audits:[...completionAudits,...pendingAudits,...audits],errors},null,2));console.log('Connected escape browser collaboration passed: '+writes.length+' permission-checked writes, four independent browsers, mobile and accessibility checks.');
 }finally{for(const page of pages)try{await page.evaluate(()=>bridge?.teardown());}catch(_){}await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
