const fs=require('fs'),path=require('path'),http=require('http'),{chromium}=require('playwright'),{expect}=require('@playwright/test'),{makeBoard,source,glossary}=require('./fixtures/lesson_board_support.cjs');
const out=path.resolve('reports/lesson-board-visuals-2026-09-12'),asset=name=>path.join(out,'assets',name),html='<!doctype html><html lang="en"><head><title>Board glossary and artwork check</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#f6f7fc}#root{max-width:1150px;margin:auto;padding:16px}</style></head><body><main id="root"></main></body></html>';
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/world.png'||req.url==='/vocabulary.png'){res.writeHead(200,{'Content-Type':'image/png'});fs.createReadStream(asset(req.url==='/world.png'?'waterworks-setting.png':'evaporation-glossary.png')).pipe(res);}else{res.writeHead(200,{'Content-Type':'text/html'});res.end(html);}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true}),results=[],errors=[];
 try{for(const width of [1280,390,320]){const page=await browser.newPage({viewport:{width,height:960}});page.setDefaultTimeout(60000);page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:'+server.address().port);const setup=async()=>{await page.addScriptTag({path:'desktop/web-app/node_modules/react/umd/react.development.js'});await page.addScriptTag({path:'desktop/web-app/node_modules/react-dom/umd/react-dom.development.js'});await page.addScriptTag({path:'lesson_board_module.js'});await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});await page.evaluate(async({board,source,resource})=>{const dataUrl=async url=>{const blob=await(await fetch(url)).blob();return new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(blob);});};window.worldFixture=await dataUrl('/world.png');resource.data.forEach(term=>delete term.image);resource.data[0].image=await dataUrl('/vocabulary.png');resource.data[0].imageAlt='Sunlight warms a bowl of water; pale wisps symbolize evaporation.';window.fixtureBoard=board;window.fixtureSource=source;window.imageCalls=[];window.textCalls=[];window.fixtureRoot=ReactDOM.createRoot(document.getElementById('root'));fixtureRoot.render(React.createElement(AlloModules.LessonBoardSetup,{inputText:source,history:[resource],language:'English',appId:'visual-qa',user:{uid:'u'},allowLive:false,t:key=>key,callGemini:async prompt=>{textCalls.push(prompt);return JSON.stringify(board);},callImagen:async(prompt,w,q,options)=>{imageCalls.push({prompt,width:w,quality:q,hasSignal:!!options?.signal});return worldFixture;},onClose(){}}));},{board:makeBoard(),source,resource:glossary()});};await setup();
 const scans=[],scan=async label=>{const violations=await page.evaluate(async()=>(await axe.run(document.querySelector('.lb'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(item=>({id:item.id,nodes:item.nodes.map(node=>node.target)})));expect(violations,label).toEqual([]);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1||[...document.querySelectorAll('.lb-dialog,.lb-panel,.lb-current,.lb-support')].some(node=>node.scrollWidth>node.clientWidth+1));expect(overflow,label+' overflow').toBe(false);scans.push({label,violations,overflow});};
 const open=async selector=>{const details=page.locator(selector);if(!await details.evaluate(node=>node.open))await details.locator(':scope > summary').click();};
 const screenshot=async(name,selector)=>{if(selector)await page.locator(selector).evaluate(node=>node.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(out,width+'-'+name+'.png')});};
 const savedRun=async()=>page.evaluate(()=>{const key=Object.keys(localStorage).find(key=>key.startsWith('allo-board-solo-v2:'));return key?JSON.parse(localStorage.getItem(key)).run:AlloModules.LessonBoardEngine.emptyRun();});
 await open('[data-board-support-setup]');await expect(page.locator('[data-board-term-count]')).toContainText('3 of 3');await page.locator('[data-generate-board]').click();await expect(page.locator('[data-board-vocabulary-linked]')).toBeVisible();await expect(page.locator('[data-generate-board]')).toBeEnabled();expect(await page.evaluate(()=>textCalls[0].includes('VOCABULARY REFERENCE'))).toBe(true);expect(await page.evaluate(()=>imageCalls.length)).toBe(0);
 await open('[data-board-vocabulary-links]');const evaporation=page.locator('.lb-vocab-links').filter({has:page.getByRole('heading',{name:'Evaporation',exact:true})});await evaporation.locator('[data-term-location$=":heater"]').check();const condensation=page.locator('.lb-vocab-links').filter({has:page.getByRole('heading',{name:'Condensation',exact:true})});await condensation.locator('[data-term-location$=":cloud"]').check();await page.locator('[data-board-vocabulary-links] > summary').click();await page.locator('[data-board-definition-mode]').selectOption('review');await open('[data-board-artwork]');
 for(const target of ['world','bridge']){await page.locator('[data-generate-board-image="'+target+'"]').click();await expect(page.locator('[data-artwork-slot="'+target+'"] img')).toBeVisible();await expect(page.locator('[data-generate-board-image="'+target+'"]').first()).toBeEnabled();}
 expect(await page.evaluate(()=>imageCalls.length)).toBe(2);await scan('setup glossary links and generated artwork previews');await screenshot('artwork-setup','[data-board-artwork]');await page.getByRole('button',{name:'Save board',exact:true}).click();await expect(page.getByText('Board saved in this browser.',{exact:true})).toBeVisible();
 await open('[data-board-transfer]');const downloaded=page.waitForEvent('download');await page.locator('[data-export-board]').click();const file=await downloaded;await file.saveAs(path.join(out,width+'-illustrated-board.alloboard.json'));const pack=JSON.parse(fs.readFileSync(path.join(out,width+'-illustrated-board.alloboard.json'),'utf8'));expect(pack.support.terms).toHaveLength(3);expect(Object.keys(pack.support.assets)).toHaveLength(3);expect(pack.support.art.world).toBeTruthy();expect(pack.support.art.projects.bridge).toBeTruthy();
 await page.reload();await setup();await open('[data-board-support-setup]');await open('[data-board-artwork]');await expect(page.locator('[data-artwork-slot="world"] img')).toBeVisible();expect(await page.evaluate(()=>imageCalls.length)).toBe(0);await page.locator('[data-board-play-solo]').click();await expect(page.locator('[data-board-world] img')).toBeVisible();await scan('illustrated board and accessible map');await screenshot('world-map','[data-board-world]');await open('[data-board-vocabulary]');await expect(page.locator('[data-vocabulary-withheld]')).toBeVisible();await expect(page.locator('[data-vocabulary-definition]')).toHaveCount(0);await page.locator('[data-board-move="heater"]').click();await page.locator('.lb-current [data-board-choice]').selectOption('1');await page.locator('[data-board-submit]').click();await open('[data-board-vocabulary]');await open('[data-vocabulary-definition]');await expect(page.locator('[data-board-vocabulary] img')).toBeVisible();await expect(page.locator('[data-vocabulary-definition]')).toContainText('Évaporation');await scan('vocabulary pictures and translations after review');await screenshot('vocabulary-review','[data-board-vocabulary]');
 const before=await savedRun();await page.locator('[data-board-images]').click();await expect(page.locator('[data-board-play] img')).toHaveCount(0);expect(await savedRun()).toEqual(before);await page.locator('[data-board-focus]').click();await page.reload();await setup();await page.locator('[data-board-play-solo]').click();await expect(page.locator('[data-board-images]')).toHaveAttribute('aria-pressed','false');await expect(page.locator('[data-board-play]')).toHaveAttribute('data-play-view','focus');expect(await savedRun()).toEqual(before);await scan('text-only focus restored without changing progress');await page.locator('[data-board-images]').click();
 const move=async id=>{await page.locator('[data-ready-move="'+id+'"]').click();await page.locator('[data-board-move="'+id+'"]').click();};const answer=async id=>{const node=makeBoard().locations.find(node=>node.id===id);if(node.kind==='choice')await page.locator('.lb-current [data-board-choice]').selectOption(String(node.answer));else if(node.kind==='settings'){for(let i=0;i<node.controls.length;i++)await page.locator('.lb-current [data-board-control="'+i+'"]').selectOption(String(node.controls[i].answer));}else{for(let i=0;i<node.order.length;i++)while(await page.locator('.lb-current [data-board-up]').evaluateAll((buttons,id)=>buttons.findIndex(button=>button.dataset.boardUp===String(id)),node.order[i])>i)await page.locator('.lb-current [data-board-up="'+node.order[i]+'"]').click();}await page.locator('[data-board-submit]').click();};
 await page.locator('[data-board-next]').click();await move('cloud');await answer('cloud');await page.locator('[data-board-next]').click();await move('bridge');await expect(page.locator('.lb-current img')).toBeVisible();await scan('constructed project artwork in focus view');await screenshot('project-reveal','.lb-current');await page.locator('[data-board-next]').click();await move('river');await answer('river');await page.locator('[data-board-next]').click();await move('research');await page.locator('[data-board-next]').click();for(const id of ['rain','lake','sequence','cooler','weather']){await move(id);await answer(id);if(id!=='weather')await page.locator('[data-board-next]').click();}await expect(page.getByRole('heading',{name:'Your board is complete',exact:true})).toBeVisible();await scan('complete illustrated expedition');
 if(width===320){await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await scan('forced colors and reduced motion');await page.getByRole('button',{name:'Board view',exact:true}).click();await page.evaluate(()=>document.querySelector('[data-board-play]').style.fontSize='200%');await scan('200 percent text');}
 results.push({width,scans,glossaryReuse:true,artworkRequests:2,backupBytes:fs.statSync(path.join(out,width+'-illustrated-board.alloboard.json')).size,saveReload:true,definitionsAfterReview:true,hideImagesPreservesRun:true,expeditionComplete:true});await page.close();}
 expect(errors).toEqual([]);fs.writeFileSync(path.join(out,'browser-verification.json'),JSON.stringify({passed:true,scope:'Production board UI and authored activities. Image provider is a fixture returning real generated sample artwork; no configured provider credentials were used.',results,errors},null,2));console.log(JSON.stringify({passed:true,widths:results.map(row=>row.width),out}));
 }catch(error){for(const page of browser.contexts().flatMap(context=>context.pages()))await page.screenshot({path:path.join(out,'failure-'+page.viewportSize().width+'.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({message:error.stack,results,errors},null,2));throw error;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
