'use strict';

const reviewedAt = '2026-08-20';
const reviewWave = 'eppp-native-quality-wave-45';
const baselineMetrics = Object.freeze({
  distractor: {
    totalItems: 1500,
    warningOnly: true,
    forbiddenAggregateChoices: 0,
    uniqueKeyStemLexicalLeakageCandidates: 38,
    asymmetricExtremeDistractorCandidates: 43,
    advancedDirectRecallCandidates: 1,
    semanticConceptDuplicatePairs: 50,
    semanticConceptDuplicateClusters: 32,
    editorialAnchorsWithActiveWarnings: 0,
    editorialAnchorsWithNoCurrentWarning: 10,
    priorityDocketItems: 20,
  },
  feedback: {
    totalItems: 1500,
    totalIncorrectOptions: 4500,
    itemsWithWarnings: 419,
    incorrectOptionsWithWarnings: 1164,
    insufficientDetailOptions: 578,
    genericTemplateOptions: 534,
    choiceRestatementOptions: 132,
    fullKeyEchoOptions: 61,
    priorityDocketItems: 100,
  },
});

const revisions = [
  {
    id: 'eppp-b008-biological-2', expectedAnswerIndex: 2, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Which observation best supports a central nervous system contribution to phantom-limb pain?',
    prompt: 'After an amputation, a patient reports pain when viewing a mirror-box reflection that restores the missing limb. Which inference best fits this pattern?',
    choices: [
      'Residual-tissue irritation that varies with local palpation',
      'Peripheral neuroma discharge that accounts for symptoms during a residual-limb examination',
      'Central remapping of the body schema can maintain the symptom after sensory input is lost',
      'A prosthetic socket pressure point that explains discomfort during visual conditions',
    ],
    rationale: 'A mirror-box manipulation changes the visual representation of the missing limb while peripheral tissue remains the same. Pain that shifts with that representation supports central integration and cortical reorganization, although peripheral factors can also contribute.',
    feedback: {
      0: 'Local tissue irritation can contribute to phantom pain, yet it would not explain a response that changes when the patient sees an altered limb representation.',
      1: 'Neuroma activity is a peripheral mechanism worth assessing, but the mirror-box manipulation points beyond a symptom tied to a single residual-nerve site.',
      3: 'Socket pressure may aggravate residual-limb discomfort, but visual modulation implicates central representation rather than a mechanical contact point.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-biological-central-pain',
    distractorDesign: ['peripheral tissue account', 'local nerve account', 'mechanical prosthesis account'],
  },
  {
    id: 'eppp-b015-biological-2', expectedAnswerIndex: 2, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Gate-control theory proposes that pain transmission is:',
    prompt: 'A patient reports less pain while attending to a demanding conversation, but pain increases when attention returns to an injured area. Which mechanism is most consistent?',
    choices: [
      'Nociceptor firing provides a fixed readout that attention cannot alter',
      'Cortical appraisal occurs after spinal signals have already reached awareness unchanged',
      'Spinal gating integrates peripheral input with descending attention-related signals',
      'Distraction reduces pain by changing tissue damage at the injury site',
    ],
    rationale: 'Gate-control theory describes pain as an interaction between peripheral nociceptive input and modulatory signals within the spinal cord and brain. Attention and descending control can therefore change perceived pain without changing the injury itself.',
    feedback: {
      0: 'Nociceptor activity supplies important input, but the clinical pattern shows that perceived pain is not a fixed copy of peripheral firing.',
      1: 'The theory places modulation within spinal and descending systems before conscious experience, rather than treating cortical appraisal as an unchanged final readout.',
      3: 'Attention can alter pain processing, but distraction does not have to repair tissue; the change reflects neural modulation of incoming signals.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-biological-gate-control',
    distractorDesign: ['fixed peripheral readout', 'late cortical-only account', 'tissue-change account'],
  },
  {
    id: 'eppp-b020-biological-1', expectedAnswerIndex: 0, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'The dorsolateral prefrontal cortex is especially important for:',
    prompt: 'During a medication-management task, a patient can recall instructions but loses track when switching between doses and goals. Which neural function is most implicated?',
    choices: [
      'Maintaining and manipulating goal-relevant information while coordinating a plan',
      'Relaying retinal signals through early visual pathways before cortical analysis',
      'Generating automatic respiratory rhythm within lower brainstem circuits',
      'Releasing pituitary hormones through hypothalamic endocrine control',
    ],
    rationale: 'The dorsolateral prefrontal cortex supports working memory, planning, set shifting, and the manipulation of information needed for goal-directed behavior. Losing track across changing medication steps fits an executive-control difficulty.',
    feedback: {
      1: 'Early visual pathways process retinal input, but the task describes organizing changing instructions rather than interpreting visual signals.',
      2: 'Lower brainstem circuits help sustain breathing automatically; they do not explain difficulty holding and updating a medication plan.',
      3: 'Hypothalamic and pituitary systems regulate endocrine functions, whereas the observed problem concerns executive coordination of information.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-biological-executive-control',
    distractorDesign: ['visual relay function', 'autonomic rhythm function', 'endocrine control function'],
  },
  {
    id: 'eppp-v2-cognitive-affective-023', expectedAnswerIndex: 0, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Which situation best illustrates Anchoring bias in clinical judgment?',
    prompt: 'A referral labels a client “treatment resistant.” During intake, the clinician notices several findings inconsistent with that label but keeps interpreting new data as evidence of resistance. Which bias is illustrated?',
    choices: [
      'Giving an early impression excessive weight as new information arrives',
      'Revising a formulation after each new data point even when the overall pattern is stable',
      'Giving greater weight to vivid information that is easy to recall than to base rates',
      'Attributing a client’s behavior to stable traits while discounting the treatment context',
    ],
    rationale: 'Anchoring occurs when an initial impression or label receives disproportionate weight as later evidence is interpreted. The clinician’s continued reliance on the referral description despite discrepant findings is the defining pattern.',
    feedback: {
      1: 'Frequent revision describes responsiveness to evidence, whereas the case centers on an early label continuing to guide interpretation despite contrary data.',
      2: 'Availability gives weight to memorable examples; the referral label is influential because it came first, not because it was especially vivid.',
      3: 'A trait attribution error concerns person-versus-context explanations. It does not capture the chronology of the influential referral label.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-cognitive-anchoring',
    distractorDesign: ['overcorrection pattern', 'availability contrast', 'person-context attribution contrast'],
  },
  {
    id: 'eppp-v2-cognitive-affective-026', expectedAnswerIndex: 3, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Complete the statement: The flashbulb memory concept (Brown & Kulik) suggests that:',
    prompt: 'After a nationally televised crisis, a client confidently recalls where they were and who told them, yet corroborating records show several details changed over time. Which conclusion best applies?',
    choices: [
      'The event should be forgotten quickly because intense arousal disrupts encoding of the event',
      'High confidence demonstrates that the memory record is more accurate than routine memories',
      'Memory accuracy can be established from vividness alone when an event is emotional',
      'Emotional arousal can produce vivid, confident recollection while reconstruction introduces errors',
    ],
    rationale: 'Flashbulb memories are experienced as unusually vivid and certain after surprising, emotional events. Confidence and vividness can remain high even as reconstructive processes alter details, so subjective certainty is not an accuracy guarantee.',
    feedback: {
      0: 'Arousal often strengthens the subjective vividness of an event rather than making the entire memory disappear; the documented changes show reconstruction.',
      1: 'Confidence is a feature of flashbulb recollection, but the corroborating discrepancies demonstrate that confidence does not establish superior accuracy.',
      2: 'Vividness describes the experience of remembering. It cannot by itself verify the correspondence between remembered details and the original event.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-cognitive-flashbulb',
    distractorDesign: ['arousal-as-forgetting claim', 'confidence-equals-accuracy claim', 'vividness-as-verification claim'],
  },
  {
    id: 'eppp-v2-cognitive-affective-061', expectedAnswerIndex: 2, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Complete the statement: Inductive reasoning moves from:',
    prompt: 'A researcher observes that several clinics with reminder calls have higher attendance, then proposes that reminders generally improve attendance while noting that more data are needed. Which reasoning process is used?',
    choices: [
      'Applying a general rule to predict a specific clinic’s outcome',
      'Deriving a conclusion from formal premises whose truth entails the result',
      'Moving from a set of particular cases toward a tentative general conclusion',
      'Choosing a treatment because it feels familiar to the clinician',
    ],
    rationale: 'Inductive reasoning moves from particular observations toward a broader conclusion that remains probable rather than guaranteed. The researcher uses several observed clinic patterns to propose a general expectation while acknowledging uncertainty.',
    feedback: {
      0: 'Applying a broad rule to a particular case is deductive in direction; the researcher instead moves from clinic observations toward a general claim.',
      1: 'Formal premises that guarantee a conclusion describe deductive reasoning. The attendance pattern supports a tentative generalization rather than certainty.',
      3: 'Familiarity may influence a clinical choice, but it is not a reasoning direction from observed cases to a population-level proposition.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-cognitive-inductive',
    distractorDesign: ['deductive direction', 'deductive certainty', 'familiarity heuristic'],
  },
  {
    id: 'eppp-v2-social-cultural-054', expectedAnswerIndex: 2, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Leader–member exchange theory focuses most directly on which feature of leadership?',
    prompt: 'In a clinic, a supervisor gives one trainee frequent developmental feedback and autonomy, while another receives narrowly defined exchanges despite similar role requirements. Which theory best explains this pattern?',
    choices: [
      'A universal leadership style should produce the same relationship with each follower',
      'Team performance is determined primarily by the leader’s general cognitive ability',
      'Leadership quality is represented by distinct leader–member relationships with individual followers',
      'Removing status distinctions between supervisor and trainees is the central leadership task',
    ],
    rationale: 'Leader–member exchange theory treats leadership as a set of differentiated dyadic relationships. The contrasting feedback and autonomy reflect variation in relationship quality between the supervisor and each trainee.',
    feedback: {
      0: 'A uniform-style account predicts similar exchanges, which conflicts with the differentiated relationships described in the clinic.',
      1: 'Cognitive ability may influence some leadership outcomes, but it does not explain why one follower receives a different relational exchange.',
      3: 'Leader–member exchange examines relationship quality within existing roles; it does not require eliminating supervisory status differences.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-social-leader-member-exchange',
    distractorDesign: ['uniform-style account', 'ability-as-cause account', 'role-erasure account'],
  },
  {
    id: 'eppp-v3-social-cultural-019', expectedAnswerIndex: 2, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: "Which concept from social psychology describes the tendency for group discussion to strengthen members' initial attitudes?",
    prompt: 'Before discussion, members of a committee mildly favor expanding outreach. After hearing arguments from one another, their shared recommendation becomes much more supportive of expansion. Which process is illustrated?',
    choices: [
      'Social facilitation increases performance when others are present',
      'Groupthink suppresses dissent in a highly cohesive decision group',
      'A collective attitude intensifies toward its starting direction through group interaction',
      'Deindividuation reduces self-awareness under conditions of anonymity',
    ],
    rationale: 'Group polarization is a shift toward a more extreme version of the group’s initial leaning after discussion. Social comparison and persuasive arguments can both move members in that direction.',
    feedback: {
      0: 'Social facilitation concerns performance changes in the presence of others, not a collective shift in an attitude after exchanging arguments.',
      1: 'Groupthink involves defective decision processes and pressure for unanimity; the case emphasizes movement toward a stronger version of the starting preference.',
      3: 'Deindividuation concerns reduced self-awareness and altered behavior under anonymity, not a discussion-driven change in the group’s policy attitude.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-social-group-polarization',
    distractorDesign: ['presence-performance process', 'conformity decision process', 'anonymity process'],
  },
  {
    id: 'eppp-v3-social-cultural-020', expectedAnswerIndex: 3, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Social loafing is LEAST likely when:',
    prompt: 'A four-person team must produce a community presentation. Members know their individual sections will be rated, and the topic matters to each of them. Which condition predicts the least social loafing?',
    choices: [
      'A large team in which individual effort blends into a single score',
      'A task perceived as routine with little personal value',
      'A cohesive team whose contributions remain difficult to identify',
      'A meaningful task with identifiable individual contributions',
    ],
    rationale: 'Social loafing is reduced when people value the task and expect their personal contribution to be visible and consequential. Individual evaluation and meaningful work increase the perceived instrumentality of effort.',
    feedback: {
      0: 'Large groups and merged performance scores make personal effort harder to detect, which can reduce perceived responsibility and increase loafing.',
      1: 'Low personal value weakens motivation to invest effort, so a routine task is less protective against loafing.',
      2: 'Cohesion can support effort, but contributions that remain unidentifiable still weaken accountability; the combination is less protective than visible work.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-social-loafing',
    distractorDesign: ['diffuse accountability', 'low task value', 'cohesion without visibility'],
  },
  {
    id: 'eppp-v2-lifespan-021', expectedAnswerIndex: 1, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Which statement most accurately defines Continuity vs. discontinuity in development?',
    prompt: 'One researcher describes vocabulary growth as steady year by year; another divides cognitive development into qualitatively different stages. Their disagreement concerns which developmental issue?',
    choices: [
      'Whether developmental patterns generalize across cultural settings',
      'Whether change accumulates gradually or appears as distinct reorganizations',
      'Whether genes or environmental experience has the stronger influence',
      'Whether developmental gains can be reversed after they appear',
    ],
    rationale: 'The continuity–discontinuity issue asks whether development is a smooth, cumulative progression or a sequence of qualitative reorganizations. The two researchers disagree about the form and pacing of change, not its cause or reversibility.',
    feedback: {
      0: 'Cross-cultural generalizability concerns context and culture; the disagreement here is about whether developmental change is smooth or stage-like.',
      2: 'Nature–nurture addresses sources of development. Both researchers could accept the same source while still disagreeing about continuity and stages.',
      3: 'Reversibility concerns stability of gains, whereas the example contrasts gradual accumulation with qualitative stage transitions. The disagreement is about the shape of change, not whether a developmental gain can later be lost.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-lifespan-continuity',
    distractorDesign: ['cultural-generalization issue', 'causal-source issue', 'stability issue'],
  },
  {
    id: 'eppp-v2-lifespan-049', expectedAnswerIndex: 1, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Which feature most clearly characterizes Resistant/ambivalent attachment (Ainsworth, Type C)?',
    prompt: 'During reunion, a toddler seeks the caregiver, then pushes away and continues crying; exploration remains limited while monitoring the caregiver. Which attachment pattern best fits?',
    choices: [
      'A secure pattern with rapid comfort and renewed exploration',
      'An ambivalent/resistant response marked by proximity bids and difficulty accepting comfort',
      'An avoidant pattern marked by minimized contact and emotional distance',
      'A disorganized pattern defined by contradictory, disoriented approach behavior',
    ],
    rationale: 'Resistant or ambivalent attachment involves intense distress, difficulty being soothed, and a push–pull reunion response. The child seeks proximity yet resists comfort and remains preoccupied with caregiver availability.',
    feedback: {
      0: 'Secure attachment is usually followed by effective soothing and a return to exploration; persistent push–pull distress points elsewhere.',
      2: 'Avoidant children tend to minimize reunion contact and emotional expression, unlike the active but resistant proximity seeking described here.',
      3: 'Disorganized attachment may include contradictory or disoriented behavior, but the organized push–pull pattern with persistent monitoring is more characteristic of resistance.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-lifespan-resistant-attachment',
    distractorDesign: ['secure reunion pattern', 'avoidant reunion pattern', 'disorganized reunion pattern'],
  },
  {
    id: 'eppp-v3-lifespan-048', expectedAnswerIndex: 1, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Permissive parenting (Baumrind) is characterized by:',
    prompt: 'Parents are affectionate and responsive but rarely set expectations, follow through on limits, or ask for developmentally suitable responsibility. Which parenting style best fits?',
    choices: [
      'Authoritative parenting combines warmth with firm, reasoned expectations',
      'Permissive parenting combines warmth with few demands and limited behavioral control',
      'Authoritarian parenting emphasizes obedience with low emotional responsiveness',
      'Uninvolved parenting provides limited warmth and limited guidance',
    ],
    rationale: 'Permissive parents are warm and accepting but set few demands or consistent limits. The pattern in the case combines high responsiveness with limited behavioral control, distinguishing it from authoritative, authoritarian, and uninvolved styles.',
    feedback: {
      0: 'Authoritative parenting also includes warmth, but it adds consistent expectations and follow-through that the case specifically lacks.',
      2: 'Authoritarian parenting emphasizes control and obedience with less warmth, the reverse of the affectionate, low-demand pattern described.',
      3: 'Uninvolved parenting is low in warmth as well as guidance; the parents here remain responsive and affectionate.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-lifespan-parenting-style',
    distractorDesign: ['warmth-plus-structure contrast', 'control-with-low-warmth contrast', 'low-warmth disengagement contrast'],
  },
  {
    id: 'eppp-b021-assessment-2', expectedAnswerIndex: 1, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Evidence based on test content is strengthened most directly when qualified experts determine that items:',
    prompt: 'A licensing board wants evidence that a new exam samples all competencies in its blueprint. Experts map each item to the blueprint and flag missing areas. What kind of evidence is being gathered?',
    choices: [
      'Predictive evidence based on later job outcomes for the exam domain',
      'Blueprint mapping demonstrates representative coverage of the defined domain',
      'Face validity based on whether examinees find the blueprint appealing',
      'Inter-rater reliability based on agreement when rating competencies',
    ],
    rationale: 'Content-related evidence examines whether the item sample adequately represents the defined construct domain. Expert blueprint mapping directly evaluates coverage and relevance, whereas outcomes, appeal, and scorer agreement address different questions.',
    feedback: {
      0: 'Later job outcomes can support predictive validity, but the board is examining blueprint coverage before interpreting scores against an outcome.',
      2: 'Face validity is an impression of surface relevance from examinees; expert mapping of competencies asks whether the content domain is represented.',
      3: 'Inter-rater reliability concerns consistency among scorers. The case concerns the match between test content and the blueprint.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-assessment-content-evidence',
    distractorDesign: ['outcome-evidence contrast', 'surface-appeal contrast', 'scorer-consistency contrast'],
  },
  {
    id: 'eppp-v2-assessment-016', expectedAnswerIndex: 0, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Which statement most accurately defines Ecological validity of a neuropsychological assessment?',
    prompt: 'A neuropsychological score predicts whether patients manage medications and navigate transportation six months later. Which validity concept does this finding most directly support?',
    choices: [
      'Ecological validity because test performance forecasts functioning in everyday contexts',
      'Construct validity because the test’s items resemble a theoretical cognitive model',
      'Face validity because patients recognize the tasks as realistic',
      'Internal consistency because items correlate with one another',
    ],
    rationale: 'Ecological validity concerns how well assessment performance maps onto real-world functioning. Predicting medication management and transportation skills extends the meaning of the score beyond the testing room to everyday behavior.',
    feedback: {
      1: 'Construct validity asks whether scores represent the intended theoretical attribute; resemblance to a model does not specifically establish everyday functional prediction.',
      2: 'Face validity is a subjective impression that a task looks relevant. The finding instead uses an external daily-life outcome.',
      3: 'Internal consistency describes relationships among items within a measure, not whether scores predict practical functioning months later.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-assessment-ecological-validity',
    distractorDesign: ['theory-representation contrast', 'surface-relevance contrast', 'within-test consistency contrast'],
  },
  {
    id: 'eppp-v2-assessment-053', expectedAnswerIndex: 1, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Complete the statement: An ipsative interpretation of test scores compares:',
    prompt: 'A clinician notes that a client’s verbal reasoning score is a relative strength compared with that same client’s processing speed, without comparing either score to norms. What interpretation is being used?',
    choices: [
      'Normative interpretation compares the client with a reference population',
      'Ipsative interpretation compares scores within the individual’s own profile',
      'Criterion interpretation judges performance against a fixed external standard',
      'Concurrent validity compares scores from separate tests administered together',
    ],
    rationale: 'Ipsative interpretation compares an individual’s scores with one another within that person’s profile. It identifies relative strengths and weaknesses without claiming how the person ranks against a normative group or criterion.',
    feedback: {
      0: 'Normative interpretation locates a score relative to a reference group; the clinician is comparing two scores belonging to the same person.',
      2: 'Criterion interpretation evaluates performance against a predefined standard. No external cutoff or mastery threshold is used in this comparison.',
      3: 'Concurrent validity examines agreement between measures, whereas this interpretation describes relative standing among the client’s own scores.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-assessment-ipsative',
    distractorDesign: ['norm-referenced contrast', 'criterion-referenced contrast', 'validity-coefficient contrast'],
  },
  {
    id: 'eppp-v2-intervention-004', expectedAnswerIndex: 1, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Complete the statement: Play therapy in pediatric clinical settings is most developmentally appropriate for:',
    prompt: 'A seven-year-old uses puppets and drawings to communicate feelings that are difficult to describe in an interview. Which rationale best supports play therapy?',
    choices: [
      'It replaces assessment of language, family context, and developmental level',
      'A developmentally accessible symbolic medium enables expression and therapeutic work',
      'It is reserved for a specific neurodevelopmental diagnosis even when treatment goals differ',
      'It is selected primarily to avoid verbal interaction with the child',
    ],
    rationale: 'Play therapy uses children’s natural symbolic and expressive activities as a developmentally appropriate route to communication, assessment, and change. The modality should still be matched to the child’s goals, context, and capacities.',
    feedback: {
      0: 'Play can add information and expression, but it does not remove the need to assess language, family context, and developmental functioning.',
      2: 'A diagnosis alone does not determine the modality; the child’s developmental communication needs and treatment goals guide the decision.',
      3: 'Play may open communication rather than avoid it. Clinicians still use verbal and relational exchanges suited to the child.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-intervention-play-therapy',
    distractorDesign: ['assessment-replacement claim', 'diagnosis-only indication', 'verbal-avoidance claim'],
  },
  {
    id: 'eppp-v3-intervention-023', expectedAnswerIndex: 1, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: "The 'Dodo bird verdict' in psychotherapy research suggests that:",
    prompt: 'A clinic compares several bona fide therapies for depression using credible trials and finds similar average symptom improvement, with patient characteristics explaining more variation than brand name. Which conclusion fits the Dodo bird verdict?',
    choices: [
      'One named therapy is superior across patients and outcome measures',
      'Different established therapies often yield comparable outcomes, with common factors and fit still mattering',
      'Medication should replace psychotherapy because psychotherapy effects cannot be measured',
      'Therapy labels alone determine outcomes after treatment begins',
    ],
    rationale: 'The Dodo bird verdict refers to the finding that bona fide psychotherapies often show broadly comparable average outcomes. Common factors, client characteristics, therapist skill, and treatment fit can still influence individual response.',
    feedback: {
      0: 'The verdict challenges a simple universal winner. It does not imply that one branded approach dominates every client or outcome.',
      2: 'Comparable psychotherapy outcomes do not make medication a replacement or imply that psychotherapy effects lack measurement.',
      3: 'The verdict emphasizes that labels do not fully determine response; common factors and person–treatment fit remain relevant.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-intervention-dodo-verdict',
    distractorDesign: ['universal-superiority claim', 'medication-substitution claim', 'label-determinism claim'],
  },
  {
    id: 'eppp-v3-intervention-053', expectedAnswerIndex: 1, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Contingency contracting involves:',
    prompt: 'A parent and adolescent sign an agreement specifying that completing homework by 7 p.m. earns weekend driving privileges, while missed work delays that privilege. What intervention procedure is illustrated?',
    choices: [
      'A vague supportive discussion that leaves contingencies unspecified',
      'A written contingency contract linking observable behavior with agreed consequences',
      'Unconditional reinforcement delivered independently of the adolescent’s actions',
      'A cognitive restructuring exercise targeting beliefs about school',
    ],
    rationale: 'Contingency contracting is a collaborative written agreement that defines observable behavior and its agreed consequence. The explicit homework criterion and driving privilege make the behavioral contingency clear and measurable.',
    feedback: {
      0: 'A contract gains its behavioral value from specifying the response and consequence; a vague discussion would not define the contingency.',
      2: 'Reinforcement is contingent on the stated homework behavior in this example, so it is not delivered independently of action.',
      3: 'Cognitive restructuring changes interpretations and beliefs, whereas this procedure arranges consequences for an observable behavior. The contract is defined by its behavioral contingency rather than by a belief-change exercise.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-intervention-contingency-contract',
    distractorDesign: ['nonspecific support', 'noncontingent reinforcement', 'cognitive intervention contrast'],
  },
  {
    id: 'eppp-v2-research-031', expectedAnswerIndex: 3, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Which statement best distinguishes an effect-size estimate from a p-value?',
    prompt: 'Two studies report p < .05, but one shows a small mean difference and the other a large difference; a reviewer asks which statistic communicates practical magnitude. Which answer is best?',
    choices: [
      'A p-value establishes causality for the larger difference',
      'Sampling error affects p-values but cannot affect estimates of magnitude',
      'An effect-size estimate becomes meaningful after significance is reached',
      'Effect size summarizes magnitude, whereas a p-value describes compatibility with a null model',
    ],
    rationale: 'An effect-size estimate communicates the magnitude of a difference or association, while a p-value summarizes how unusual the data would be under a specified null model and assumptions. Neither statistic alone establishes causality.',
    feedback: {
      0: 'A larger difference may be practically important, but causality depends on design and assumptions rather than on a p-value.',
      1: 'Effect-size estimates also vary across samples and should be interpreted with uncertainty; sampling variability is not unique to p-values.',
      2: 'Magnitude should be estimated whether or not a chosen significance threshold is crossed; statistical significance is not a prerequisite for an effect estimate.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-research-effect-size',
    distractorDesign: ['causality inference', 'sampling-variability denial', 'significance-gate claim'],
  },
  {
    id: 'eppp-v3-research-015', expectedAnswerIndex: 1, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Selection bias threatens:',
    prompt: 'A clinical trial enrolls volunteers from one specialty clinic; those assigned to treatment differ at baseline and the sample excludes most community patients. Which validity threats follow from this selection process?',
    choices: [
      'External generalizability is limited, while baseline imbalance cannot affect causal interpretation',
      'Both internal validity and external validity are threatened by systematic group and sampling differences',
      'Neither validity domain is affected when the outcome measure is reliable',
      'Internal validity is threatened by baseline imbalance, while sampling composition has no bearing on generalization',
    ],
    rationale: 'Selection can threaten internal validity when groups differ before treatment, creating confounding, and external validity when the recruited sample differs from the intended population. The case supplies evidence for both pathways.',
    feedback: {
      0: 'The specialty-clinic sample does limit generalizability, but baseline group differences can also confound the treatment comparison and threaten internal validity.',
      2: 'Reliable outcome measurement does not repair systematic recruitment or assignment differences; both validity domains can remain compromised.',
      3: 'Baseline imbalance is an internal threat, but the restricted sampling frame also limits how confidently results generalize to community patients.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-research-selection-bias',
    distractorDesign: ['external-only claim', 'measurement-reliability distraction', 'internal-only claim'],
  },
  {
    id: 'eppp-v3-research-030', expectedAnswerIndex: 2, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'In a meta-analysis, what is the primary outcome measure?',
    prompt: 'A reviewer combines standardized mean differences from twelve trials and weights estimates by precision. What quantity is the primary outcome being synthesized?',
    choices: [
      'The calendar year in which each trial appeared',
      'Whether each individual p-value crossed a significance threshold',
      'A pooled index of intervention impact',
      'The number of participants recruited by the largest trial',
    ],
    rationale: 'Meta-analysis synthesizes comparable effect-size estimates, such as standardized mean differences, correlations, or odds ratios. Weighting by precision changes each study’s contribution to the pooled estimate but does not replace the outcome with publication year or sample size.',
    feedback: {
      0: 'Publication year can be examined as a moderator or for trends, but it is not the quantitative outcome being pooled across the trials.',
      1: 'Individual significance decisions discard magnitude information; meta-analysis ordinarily combines effect estimates and their uncertainty rather than vote counts of p-values.',
      3: 'Sample size influences precision and weighting, yet the synthesized result is an estimate of effect magnitude rather than the largest enrollment.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-research-meta-analysis',
    distractorDesign: ['publication-time distractor', 'threshold-count distractor', 'enrollment distractor'],
  },
  {
    id: 'eppp-v2-professional-075', expectedAnswerIndex: 1, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'A psychologist notices that personal distress may be interfering with competent work. Which response best follows the APA Ethics Code?',
    prompt: 'A psychologist notices sleep deprivation and escalating anxiety are impairing concentration during sessions. What is the most ethical next step?',
    choices: [
      'Continue the caseload unchanged and wait for outside feedback',
      'Seek consultation or assistance, then evaluate whether duties need limits, suspension, or transfer',
      'End the full caseload in a single step while leaving continuity arrangements unaddressed',
      'Share personal clinical details with clients even when irrelevant to their care',
    ],
    rationale: 'APA Standard 2.06 requires psychologists to address personal problems that could impair competent work. Consultation, assistance, and a careful decision about limiting or transferring duties protect clients while preserving continuity where possible.',
    feedback: {
      0: 'Waiting for a complaint leaves clients exposed after impairment is already suspected; the ethical duty is to assess and address the risk proactively.',
      2: 'A service transition may be needed, but a single abrupt termination without continuity planning can create additional avoidable harm.',
      3: 'Clients need relevant service information, not indiscriminate disclosure of the psychologist’s private distress; consultation can occur without that burden.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-professional-impairment',
    distractorDesign: ['passive-monitoring response', 'abrupt-transition response', 'overdisclosure response'],
  },
  {
    id: 'eppp-v2-professional-077', expectedAnswerIndex: 3, expectedDifficulty: 'intermediate', targetDifficulty: 'advanced',
    expectedPrompt: 'Which practice best supports ethically valid informed consent for psychological services?',
    prompt: 'Before starting therapy, a clinician explains services, fees, foreseeable risks, confidentiality limits, and alternatives in language the client can discuss and question. Which practice is exemplified?',
    choices: [
      'A signed form substitutes for conversation about material decisions',
      'Consent is assumed once the client attends an appointment',
      'Confidentiality limits are disclosed after a breach makes them relevant',
      'Understandable, material disclosure supports an informed and voluntary decision',
    ],
    rationale: 'Ethically valid informed consent requires understandable disclosure of information relevant to the person’s decision, including service terms, foreseeable risks, alternatives, and confidentiality limits. Discussion and questions help establish a voluntary, informed choice.',
    feedback: {
      0: 'A signature documents a process but cannot replace communication when material information needs explanation or clarification.',
      1: 'Attendance does not demonstrate that the client received or understood the information needed for a voluntary treatment decision.',
      2: 'Confidentiality limits should be discussed before services and when circumstances change, rather than introduced only after a disclosure problem.',
    },
    cognitiveProcess: 'application', learningObjectiveId: 'wave45-professional-informed-consent',
    distractorDesign: ['paperwork substitution', 'passive-consent assumption', 'delayed-limit disclosure'],
  },
  {
    id: 'eppp-v2-professional-038', expectedAnswerIndex: 3, expectedDifficulty: 'foundation', targetDifficulty: 'advanced',
    expectedPrompt: 'Complete the statement: Authorship credit on publications should be based on:',
    prompt: 'A senior faculty member provided lab space and funding but did not help design, analyze, interpret, or write a manuscript. Which decision follows authorship guidance?',
    choices: [
      'Place the senior member first because rank determines author order',
      'Add the senior member as an author because funding establishes authorship',
      'Grant authorship because institutional affiliation establishes a scholarly contribution',
      'Recognize substantial intellectual or writing contributions as the basis for authorship; acknowledge other support separately',
    ],
    rationale: 'Authorship should reflect substantial professional contributions to the study’s design, analysis, interpretation, or writing. Providing space, funding, rank, or affiliation can be acknowledged without converting administrative support into authorship.',
    feedback: {
      0: 'Academic rank does not determine authorship or order; credit should follow substantive contributions to the work.',
      1: 'Funding can be acknowledged, but financial support alone does not establish the intellectual contribution expected for authorship.',
      2: 'Institutional affiliation identifies where someone works, not what scholarly contribution they made to the manuscript. Authorship requires evidence of substantive intellectual or writing work on the publication itself.',
    },
    cognitiveProcess: 'analysis', learningObjectiveId: 'wave45-professional-authorship',
    distractorDesign: ['rank-based credit', 'funding-based credit', 'affiliation-based credit'],
  },
];

module.exports = { baselineMetrics, reviewedAt, reviewWave, revisions };
