#!/usr/bin/env node
'use strict';

const reviewWave = 'eppp-diagram-review-wave-02';
const reviewDate = '2026-07-16';

const sourceRecords = {
  axonInitialSegment: {
    title: 'Axon initial segments: structure, function, and disease',
    organization: 'Annals of the New York Academy of Sciences; PubMed Central, U.S. National Library of Medicine',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5992072/',
    whyReputable: 'This peer-reviewed Baylor College of Medicine review synthesizes evidence about somatodendritic input, action-potential initiation at the axon initial segment, and propagation through myelinated axons and nodes. PubMed Central provides stable full text and traceable publication metadata.',
  },
  synapsePhysiology: {
    title: 'Physiology, Synapse',
    organization: 'StatPearls, NCBI Bookshelf, U.S. National Library of Medicine',
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK526047/',
    whyReputable: 'This clinician-authored and medically reviewed NCBI Bookshelf chapter explains synaptic anatomy, the synaptic cleft, action-potential arrival at terminals, and neurotransmitter release. It directly supports the diagram’s terminal and synapse labels.',
  },
  centralNervousSystemAnatomy: {
    title: 'Anatomy, Central Nervous System',
    organization: 'StatPearls, NCBI Bookshelf, U.S. National Library of Medicine (updated 2026)',
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK542179/',
    whyReputable: 'This current clinician-authored and medically reviewed anatomy reference describes the cerebral lobes, major cortical landmarks, cerebellum, brainstem, and their broad functions. NCBI Bookshelf supplies editorial oversight and traceable revision information.',
  },
  languageNetworkReview: {
    title: 'The language network as a natural kind within the broader landscape of the human brain',
    organization: 'Nature Reviews Neuroscience (2024)',
    url: 'https://www.nature.com/articles/s41583-024-00802-4',
    whyReputable: 'This peer-reviewed state-of-the-field review describes language as a distributed functional network and addresses individual variability. It supports presenting Broca and Wernicke regions as approximate historical landmarks rather than isolated universal language centers.',
  },
  eriksonStatPearls: {
    title: "Erikson's Stages of Psychosocial Development",
    organization: 'StatPearls, NCBI Bookshelf, U.S. National Library of Medicine (updated 2026)',
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK556096/',
    whyReputable: 'This current clinician-authored and medically reviewed reference summarizes Erikson’s eight proposed conflicts and ego strengths, notes that the original formulation did not supply exact initial ages, and explains that conflicts can be revisited.',
  },
  openStaxErikson: {
    title: 'Psychology 2e: Lifespan Theories',
    organization: 'OpenStax, Rice University',
    url: 'https://openstax.org/books/psychology-2e/pages/9-2-lifespan-theories',
    whyReputable: 'OpenStax is Rice University’s nonprofit educational publisher. This expert-authored, peer-reviewed psychology chapter presents Erikson’s stages as a classic lifespan theory and supplies the conventional conflicts and associated life periods used for introductory instruction.',
  },
  openRnDevelopment: {
    title: 'Nursing Health Promotion, Chapter 13: Nursing Care for Infancy Through Adolescence',
    organization: 'Open RN; NCBI Bookshelf, U.S. National Library of Medicine (2025)',
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK615351/',
    whyReputable: 'This current academic health-sciences text is published through NCBI Bookshelf and explicitly cautions that developmental ages vary and that Erikson’s framework has cultural limitations. It supports non-rigid period labels and qualification of universality.',
  },
  openStaxOperant: {
    title: 'Psychology 2e: Operant Conditioning',
    organization: 'OpenStax, Rice University',
    url: 'https://openstax.org/books/psychology-2e/pages/6-3-operant-conditioning',
    whyReputable: 'OpenStax is Rice University’s nonprofit educational publisher. This expert-authored, peer-reviewed psychology chapter defines positive and negative contingencies by presentation or removal and reinforcement or punishment by their effects on future behavior.',
  },
  irisConsequences: {
    title: 'Behavioral Principles: The Basics of Understanding Student Behavior — Page 4: Consequences',
    organization: 'IRIS Center, Vanderbilt University, supported by the U.S. Department of Education Office of Special Education Programs',
    url: 'https://iris.peabody.vanderbilt.edu/module/bp/cresource/q1/p04/',
    whyReputable: 'The IRIS Center develops evidence-based educator resources with subject-matter and accessibility review. This BCBA-D-informed module defines consequences by observed changes in future behavior and distinguishes reinforcement from punishment without relying on intent.',
  },
  testingStandards: {
    title: 'Standards for Educational and Psychological Testing (2014 Edition)',
    organization: 'American Educational Research Association, American Psychological Association, and National Council on Measurement in Education',
    url: 'https://www.testingstandards.net/uploads/7/6/6/4/76643089/9780935302356.pdf',
    whyReputable: 'This joint professional standard is the authoritative U.S. framework for educational and psychological testing. It defines validity in relation to intended score interpretations and uses and distinguishes precision under replications from systematic and random measurement error.',
  },
  beckInstituteCbt: {
    title: 'Understanding CBT',
    organization: 'Beck Institute for Cognitive Behavior Therapy',
    url: 'https://beckinstitute.org/about/understanding-cbt/',
    whyReputable: 'Beck Institute is a specialist nonprofit founded by CBT developer Aaron T. Beck. Its clinician-facing educational material describes contemporary cognitive-behavioral formulation, collaborative treatment planning, and the interaction of thoughts, emotions, and behavior.',
  },
  genericCognitiveModel: {
    title: 'Advances in cognitive theory and therapy: the generic cognitive model',
    organization: 'Annual Review of Clinical Psychology; PubMed, U.S. National Library of Medicine',
    url: 'https://pubmed.ncbi.nlm.nih.gov/24387236/',
    whyReputable: 'This peer-reviewed review by Aaron T. Beck and Emily A. P. Haigh presents the generic cognitive model and situates cognition within a broader formulation of psychopathology. PubMed supplies traceable author, journal, and publication metadata.',
  },
  uwDbt: {
    title: 'Dialectical Behavior Therapy',
    organization: 'University of Washington Behavioral Research & Therapy Clinics',
    url: 'https://depts.washington.edu/uwbrtc/about-us/dialectical-behavior-therapy/',
    whyReputable: 'This University of Washington specialty clinic was founded by DBT developer Marsha Linehan. Its institutional overview describes the treatment components, target hierarchy, and four skills-training modules of comprehensive dialectical behavior therapy.',
  },
  dbtComponentTrial: {
    title: 'Dialectical behavior therapy for high suicide risk in individuals with borderline personality disorder: a randomized clinical trial and component analysis',
    organization: 'JAMA Psychiatry; PubMed, U.S. National Library of Medicine',
    url: 'https://pubmed.ncbi.nlm.nih.gov/25806661/',
    whyReputable: 'This peer-reviewed randomized component trial directly distinguishes DBT skills training from other components of comprehensive DBT. The PubMed record provides traceable authorship, methods, journal, and publication information.',
  },
};

function withSources(record, sourceKeys) {
  const sourceDetails = sourceKeys.map((key) => sourceRecords[key]);
  return { ...record, references: sourceDetails.map((source) => source.url), sourceDetails };
}

const commonChecks = {
  textAlternative: 'editorial-pass',
  reducedMotion: 'shared-renderer-pass',
  keyboardDependency: 'shared-renderer-pass',
  conceptAccuracy: 'assisted-editorial-pass-expert-pending',
  labelQuality: 'editorial-pass',
  sourceSupport: 'topically-aligned-reputable-source',
  expertReview: 'pending-independent-review',
};

const corrections = [
  withSources({
    key: 'neuronActionPotential',
    correctionSummary: 'Reframed the animation as a schematic sequence, corrected axon-initial-segment and terminal terminology, qualified dendritic input, and raised the smallest labels to a readable size.',
    historicalContext: 'not-applicable',
    expectedPlacementCount: 1,
    replacements: [
      { from: '                <!-- Cell body (soma) -->', to: '                <text x="350" y="20" text-anchor="middle" class="diagram-label" font-weight="700" font-size="13" fill="#a78bfa">Example Myelinated Multipolar Neuron — Schematic</text>\n                <!-- Cell body (soma) -->' },
      { from: '(receive signals)', to: '(common input sites)' },
      { from: 'Axon Hillock', to: 'Axon Initial Segment', expectedOccurrences: 2, replaceAll: true },
      { from: '<!-- Action potential signal flowing -->', to: '<!-- Schematic sequence marker; not a physical particle or voltage trace -->' },
      { from: 'values="145;550" dur="2s" repeatCount="indefinite"', to: 'values="145;238;320;400;480;550" keyTimes="0;0.2;0.4;0.6;0.8;1" calcMode="discrete" dur="2s" repeatCount="indefinite"', expectedOccurrences: 2, replaceAll: true },
      { from: '>Terminal</text>', to: '>Axon</text>' },
      { from: '>Buttons</text>', to: '>Terminals</text>' },
      { from: 'style="font-size:7px;fill:#94a3b8">(common input sites)', to: 'style="font-size:9px;fill:#94a3b8">(common input sites)' },
      { from: 'style="font-size:7px;fill:#6ee7b7">Node of', to: 'style="font-size:9px;fill:#6ee7b7">Node of' },
      { from: 'style="font-size:7px;fill:#6ee7b7">Ranvier', to: 'style="font-size:9px;fill:#6ee7b7">Ranvier' },
      { from: 'style="font-size:7px;fill:#fbbf24">(NTs released', to: 'style="font-size:9px;fill:#fbbf24">(neurotransmitter release' },
      { from: 'style="font-size:7px;fill:#fbbf24"> into synapse)', to: 'style="font-size:9px;fill:#fbbf24"> into synaptic cleft)' },
      { from: '⚡ Signal direction →', to: '⚡ Schematic node-to-node sequence →' },
      {
        from: '🔬 A neuron showing dendrites (receive), soma (integrate), axon with myelin sheaths (conduct), and terminal buttons (release neurotransmitters). The green pulse shows the action potential traveling along the axon.',
        to: '🔬 Simplified example of a myelinated multipolar neuron. Dendrites and the soma commonly receive and integrate synaptic inputs, and the soma contains the nucleus. Action potentials usually initiate at the axon initial segment, propagate along the axon, and trigger neurotransmitter release from axon terminals into the synaptic cleft. In a myelinated axon, active regeneration occurs at nodes of Ranvier while depolarizing current spreads beneath myelin. The green marker represents direction and sequence, not a physical particle or an exact continuous voltage trace.',
      },
    ],
  }, ['axonInitialSegment', 'synapsePhysiology']),
  withSources({
    key: 'brainRegions',
    correctionSummary: 'Added orientation, modernized lobe-function wording, and replaced pulsing localization circles with approximate dominant-left language-network landmarks.',
    historicalContext: 'editorial-pass',
    expectedPlacementCount: 1,
    replacements: [
      { from: 'Major Brain Lobes — Lateral View', to: 'Cerebral Lobes &amp; Selected Landmarks — Left Lateral Schematic' },
      { from: '                <!-- Brain outline -->', to: '                <text x="70" y="45" class="diagram-label-sm" fill="#94a3b8">← Anterior</text>\n                <text x="530" y="45" text-anchor="end" class="diagram-label-sm" fill="#94a3b8">Posterior →</text>\n                <!-- Brain outline -->' },
      { from: 'Planning, decision-', to: 'Executive functions,' },
      { from: 'making, personality', to: 'planning, motor control' },
      { from: 'Somatosensory,', to: 'Somatosensory &amp;' },
      { from: 'spatial processing', to: 'spatial attention' },
      { from: 'Auditory processing,', to: 'Auditory processing;' },
      { from: 'memory, language', to: 'memory/language networks' },
      { from: 'style="font-size:7px;fill:#f9a8d4">Coordination,', to: 'style="font-size:9px;fill:#f9a8d4">Coordination,' },
      { from: 'style="font-size:7px;fill:#f9a8d4">balance, motor learning', to: 'style="font-size:9px;fill:#f9a8d4">balance, motor learning' },
      { from: '<circle cx="148" cy="220" r="12" fill="none" stroke="#f472b6" stroke-width="1.5" stroke-dasharray="3 2" class="diagram-fade-pulse"/>', to: '<ellipse cx="148" cy="220" rx="18" ry="12" fill="none" stroke="#f472b6" stroke-width="1.5" stroke-dasharray="3 2"/>' },
      { from: '<text x="100" y="240" style="font-size:7px;fill:#f472b6">Broca\'s</text>', to: '<text x="100" y="240" style="font-size:9px;fill:#f472b6">Classic Broca</text>' },
      { from: '<text x="100" y="248" style="font-size:7px;fill:#f472b6">Area</text>', to: '<text x="100" y="251" style="font-size:9px;fill:#f472b6">region</text>' },
      { from: '<circle cx="340" cy="225" r="12" fill="none" stroke="#fbbf24" stroke-width="1.5" stroke-dasharray="3 2" class="diagram-fade-pulse" style="animation-delay:1s"/>\n                <text x="355" y="228" style="font-size:7px;fill:#fbbf24">Wernicke\'s</text>', to: '<ellipse cx="340" cy="225" rx="22" ry="12" fill="none" stroke="#fbbf24" stroke-width="1.5" stroke-dasharray="3 2"/>\n                <text x="365" y="221" style="font-size:9px;fill:#fbbf24">Classic Wernicke</text>\n                <text x="365" y="232" style="font-size:9px;fill:#fbbf24">region</text>' },
      {
        from: String.raw`🧩 The four major brain lobes: Frontal (blue — executive function), Parietal (purple — sensory/spatial), Temporal (yellow — memory/language), Occipital (green — vision). Broca\'s and Wernicke\'s areas are highlighted with pulsing circles.`,
        to: '🧩 Simplified left lateral view of the four conventionally named cerebral lobes and selected landmarks. The frontal lobe participates in executive and motor functions; the parietal lobe in somatosensory processing and spatial attention; the temporal lobe in auditory, memory, and language networks; and the occipital lobe in visual processing. The central sulcus separates frontal and parietal cortex. The outlined Broca and Wernicke regions are approximate, classically named regions in the usually dominant left hemisphere; language depends on a broader connected network whose precise functional locations vary across people. The cerebellum and brainstem are orientation landmarks, not cerebral lobes.',
      },
    ],
  }, ['centralNervousSystemAnatomy', 'languageNetworkReview']),
  withSources({
    key: 'eriksonStages',
    correctionSummary: 'Replaced rigid ages and a moving lifespan dot with approximate life-period labels, identified ego strengths, and stated that the classic conflicts can be revisited.',
    historicalContext: 'editorial-pass',
    expectedPlacementCount: 1,
    replacements: [
      { from: "Erikson's Psychosocial Stages", to: "Erikson's Eight-Stage Psychosocial Theory" },
      { from: "{age:'0-1'", to: "{age:'Infancy'" },
      { from: "{age:'1-3'", to: "{age:'Early Childhood'" },
      { from: "{age:'3-6'", to: "{age:'Play Age'" },
      { from: "{age:'6-12'", to: "{age:'School Age'" },
      { from: "{age:'12-18'", to: "{age:'Adolescence'" },
      { from: "{age:'18-40'", to: "{age:'Young Adulthood'" },
      { from: "{age:'40-65'", to: "{age:'Adulthood'" },
      { from: "{age:'65+'", to: "{age:'Later Adulthood'" },
      { from: 'Shame/Doubt', to: 'Shame &amp; Doubt' },
      { from: '>Virtue:</text>', to: '>Ego strength:</text>' },
      { from: 'style="font-size:7px;fill:#94a3b8">Ego strength:', to: 'style="font-size:9px;fill:#94a3b8">Ego strength:' },
      { from: '>Birth</text>', to: '>Earlier life</text>' },
      { from: '>Old Age</text>', to: '>Later life</text>' },
      { from: '→ Lifespan Development →', to: 'Proposed sequence; conflicts may be revisited across life' },
      { from: '                <!-- Animated progress dot -->\n                <circle r="4" fill="#6ee7b7" filter="url(#neonGlow)">\n                    <animate attributeName="cx" values="20;690" dur="8s" repeatCount="indefinite"/>\n                    <animate attributeName="cy" values="165;165" dur="8s" repeatCount="indefinite"/>\n                </circle>', to: '                <!-- Motion removed: the theory does not prescribe one fixed developmental timetable. -->' },
      {
        from: "📊 Erikson\\'s 8 psychosocial stages from birth through old age, showing the core crisis and associated virtue at each stage. The green dot traces the lifespan journey.",
        to: '📊 Erikson’s classic theory proposes eight psychosocial tensions and associated ego strengths: trust versus mistrust—hope; autonomy versus shame and doubt—will; initiative versus guilt—purpose; industry versus inferiority—competence; identity versus role confusion—fidelity; intimacy versus isolation—love; generativity versus stagnation—care; and integrity versus despair—wisdom. The life periods are approximate teaching conventions, not rigid deadlines; within the theory, earlier conflicts can be revisited across the lifespan. This is a developmental framework, not a universal timetable.',
      },
    ],
  }, ['eriksonStatPearls', 'openStaxErikson', 'openRnDevelopment']),
  withSources({
    key: 'operantConditioning',
    correctionSummary: 'Defined all four contingencies by presentation or removal and by observed future behavior, replaced intent-based examples, and removed visual privileging of negative reinforcement.',
    historicalContext: 'not-applicable',
    expectedPlacementCount: 1,
    replacements: [
      { from: 'Operant Conditioning (Skinner)', to: 'Four Operant-Consequence Contingencies' },
      { from: 'ADD Stimulus (Positive +)', to: 'PRESENT / ADD (positive +)' },
      { from: 'REMOVE Stimulus (Negative -)', to: 'WITHDRAW / REMOVE (negative −)' },
      { from: '(Increases Behavior)', to: '(Future behavior increases)' },
      { from: '(Decreases Behavior)', to: '(Future behavior decreases)' },
      { from: 'Remove an aversive stimulus', to: 'Remove a stimulus after behavior;' },
      { from: 'to INCREASE a behavior.', to: 'that behavior later INCREASES.' },
      { from: 'Add a desirable stimulus to', to: 'Present a stimulus after behavior;' },
      { from: 'INCREASE a behavior.', to: 'that behavior later INCREASES.' },
      { from: 'Remove a desirable stimulus', to: 'Remove a stimulus after behavior;' },
      { from: 'to DECREASE a behavior.', to: 'that behavior later DECREASES.' },
      { from: 'Add an aversive stimulus to', to: 'Present a stimulus after behavior;' },
      { from: 'DECREASE a behavior.', to: 'that behavior later DECREASES.' },
      { from: 'Ex: Giving a child a cookie', to: 'Ex: Cookie follows room cleaning;' },
      { from: 'when they clean their room.', to: 'later room cleaning increases.' },
      { from: 'Ex: Turning off an alarm', to: 'Ex: Buckling stops a warning tone;' },
      { from: 'by pressing snooze.', to: 'later buckling increases.' },
      { from: 'Ex: Giving a speeding ticket', to: 'Ex: Ticket follows speeding;' },
      { from: 'to stop fast driving.', to: 'later speeding decreases.' },
      { from: "Ex: Taking away a teen's", to: 'Ex: Phone access is removed after' },
      { from: 'phone for breaking curfew.', to: 'curfew-breaking; it later decreases.' },
      { from: 'Behavior goes UP ↑', to: 'Future behavior ↑', expectedOccurrences: 2, replaceAll: true },
      { from: 'Behavior goes DOWN ↓', to: 'Future behavior ↓', expectedOccurrences: 2, replaceAll: true },
      { from: '                <!-- Highlight showing the difference between Negative Reinforcement and Punishment -->\n                <rect x="350" y="80" width="200" height="150" fill="none" stroke="#22c55e" stroke-width="3" opacity="0.8" class="diagram-fade-pulse" style="animation-duration: 4s"/>', to: '                <!-- No contingency is visually privileged; classification depends on the observed future effect. -->' },
      {
        from: '🐀 The Four Quadrants of Operant Conditioning. Remember: Positive means ADDING something, Negative means REMOVING something. Reinforcement INCREASES behavior, Punishment DECREASES behavior. The flashing green box highlights Negative Reinforcement (removing a bad thing to increase a behavior), which is highly tested and often confused with punishment.',
        to: '🐀 Operant consequences are classified on two axes. Positive means a stimulus is presented; negative means a stimulus is removed. Reinforcement means the target behavior becomes more likely in similar future conditions; punishment means it becomes less likely. Thus the four standard contingencies are positive reinforcement (present; behavior increases), negative reinforcement (remove; behavior increases), positive punishment (present; behavior decreases), and negative punishment (remove; behavior decreases). A consequence is classified by its observed effect on future behavior—not by whether someone intended it as a reward or penalty or assumed it was desirable or aversive.',
      },
    ],
  }, ['openStaxOperant', 'irisConsequences']),
  withSources({
    key: 'reliabilityValidity',
    correctionSummary: 'Relabeled the target analogy as precision and bias rather than direct proof of validity and narrowed it to the intended reliability section.',
    historicalContext: 'editorial-pass',
    expectedPlacementCount: 1,
    replacements: [
      { from: 'Reliability vs. Validity', to: 'Target Analogy: Precision, Bias, and Validity' },
      { from: '<svg viewBox="0 0 650 250" xmlns="http://www.w3.org/2000/svg" style="max-width:650px">', to: '<svg viewBox="0 0 650 270" xmlns="http://www.w3.org/2000/svg" style="max-width:650px">' },
      { from: 'id="target"', to: 'id="rvTarget"' },
      { from: 'href="#target"', to: 'href="#rvTarget"', expectedOccurrences: 3, replaceAll: true },
      { from: 'id="bullseye-hit"', to: 'id="rvHit"' },
      { from: 'href="#bullseye-hit"', to: 'href="#rvHit"', expectedOccurrences: 15, replaceAll: true },
      { from: 'Unreliable & Invalid', to: 'Low Precision; Off Target', expectedOccurrences: 2, replaceAll: true },
      { from: 'Inconsistent, misses mark', to: 'Scattered under these replications' },
      { from: 'Reliable, Not Valid', to: 'High Precision; Biased' },
      { from: 'Consistent, but misses mark', to: 'Tight grouping with systematic offset' },
      { from: 'Reliable & Valid', to: 'High Precision; Near Target', expectedOccurrences: 2, replaceAll: true },
      { from: 'Consistent AND hits the mark!', to: 'Tight grouping near the reference' },
      { from: '<line x1="110" y1="230" x2="540" y2="230" stroke="#a78bfa" stroke-width="2" marker-end="url(#drugArrow)"/>', to: '<line x1="110" y1="230" x2="540" y2="230" stroke="#a78bfa" stroke-width="2"/>' },
      { from: '"Consistency is necessary evidence, but validity depends on the intended score interpretation and use."', to: 'Grouping illustrates precision; closeness to center illustrates bias—not validity by itself.' },
      {
        from: '🎯 The classic Target Analogy for Measurement. Reliability/precision concerns consistency across defined replications (grouping of hits). The bullseye is only an analogy: validity concerns evidence for a specified score interpretation and use, not a test property called accuracy.',
        to: '🎯 This target analogy illustrates random versus systematic measurement error. Grouping represents reliability/precision across a defined set of replications; distance from the center represents bias or accuracy in this analogy. Neither feature, by itself, establishes validity. Validity is a unitary, evidence-based judgment about a specified interpretation of scores for a proposed use. Reliable/precise scores can still support an invalid interpretation when systematic error or other evidence undermines that use.',
      },
      { from: "if ((heading.includes('reliability') || heading.includes('validity') || heading.includes('psychometrics') || heading.includes('measure') || heading.includes('construct')) && !heading.includes('threats')", to: "if ((ch.id === 'ch-1' && heading.includes('reliability: is the test consistent')) && !heading.includes('threats')" },
    ],
  }, ['testingStandards']),
  withSources({
    key: 'typesOfValidity',
    correctionSummary: 'Reorganized older validity-type labels into the unified validity framework and its current sources of evidence, while preserving a concise note about historical terminology.',
    historicalContext: 'editorial-pass',
    expectedPlacementCount: 1,
    replacements: [
      { from: 'Construct Validity and its Subtypes', to: 'Unified Validity: Sources of Evidence' },
      { from: '>Construct Validity</text>', to: '>Validity Argument</text>' },
      { from: '>Does the test measure</text>', to: '>Do evidence and theory support</text>' },
      { from: '>the underlying theory?</text>', to: '>the intended interpretation and use?</text>' },
      { from: 'Internal / Content Focus', to: 'Evidence Within the Assessment' },
      { from: 'Content Validity:', to: 'Test content:' },
      { from: 'Face credibility (not validity evidence):', to: 'Response processes:' },
      { from: 'Does it appear relevant to test takers?', to: 'Do responses reflect intended processes?' },
      { from: 'External / Criterion Focus', to: 'Structure &amp; External Relations' },
      { from: 'Concurrent Validity:', to: 'Internal structure:' },
      { from: 'Relation to a concurrent criterion.', to: 'Do item/scale relations fit the construct?' },
      { from: 'Predictive Validity:', to: 'Relations to criteria:' },
      { from: 'Relation to a criterion measured later.', to: 'Concurrent or later outcomes, as predicted.' },
      { from: 'Convergent: Expected relation to similar constructs.', to: 'Convergent: predicted related constructs align.' },
      { from: 'Discriminant: Distinct from theoretically different constructs.', to: 'Discriminant: predicted distinctions appear.' },
      {
        from: '📊 Construct Validity Framework. Validity is a unified argument for an intended score interpretation and use. Evidence may come from content representation, response processes, internal structure, and theoretically expected relations to concurrent or later criteria and to similar or distinct constructs. Face credibility can affect engagement but is not itself validity evidence.',
        to: '📊 Validity is a unified argument about whether accumulated evidence and theory support a particular interpretation of test scores for a proposed use; it is not a fixed property of a test. The Standards describe sources of validity evidence—not separate “types of validity”—including test content, response processes, internal structure, and relations to other variables (such as concurrent or later criteria and convergent/discriminant patterns). The evidence needed depends on the claims being made. Perceived face relevance is not a separate psychometric validity type, although it can affect engagement or response processes. Older textbooks and exam items may still use “content validity,” “criterion-related validity” (concurrent/predictive), and “construct validity.” Treat those as historical labels; the current Standards organize a unified validity argument around sources of evidence.',
      },
      { from: "heading.includes('predictive validity') || heading.includes('construct & statistical') || heading.includes('validity: does the test measure')", to: "heading.includes('predictive validity') || heading.includes('validity: does the test measure')" },
    ],
  }, ['testingStandards']),
  withSources({
    key: 'cbtTriangle',
    correctionSummary: 'Presented the triangle as a simplified individualized formulation aid, added omitted contextual limits, removed a false affordance, and routed the generic overview away from the Ellis-specific section.',
    historicalContext: 'not-applicable',
    expectedPlacementCount: 1,
    replacements: [
      { from: '                <!-- Connections -->', to: '                <text x="250" y="24" text-anchor="middle" class="diagram-label" font-weight="700" font-size="16" fill="#a78bfa">Simplified CBT Formulation</text>\n                <!-- Connections -->' },
      { from: '.cbt-node { fill: #1E293B; stroke: url(#cbtGrad); stroke-width: 3px; filter: url(#cbtGlow); transition: all 0.3s ease; cursor: pointer; }', to: '.cbt-node { fill: #1E293B; stroke: url(#cbtGrad); stroke-width: 3px; filter: url(#cbtGlow); }' },
      { from: '.cbt-node:hover { stroke: #6EE7B7; filter: drop-shadow(0 0 8px rgba(110, 231, 183, 0.6)); }', to: '/* Static nodes: guided reveal controls provide the diagram interaction. */' },
      { from: 'id="arrowHead"', to: 'id="cbtArrowHead"' },
      { from: 'url(#arrowHead)', to: 'url(#cbtArrowHead)' },
      { from: '>What we think</text>', to: '>Appraisals / meanings</text>' },
      { from: '>What we feel</text>', to: '>Emotions</text>' },
      { from: '>What we do</text>', to: '>Actions / avoidance</text>' },
      { from: '>Core</text>', to: '>Underlying</text>' },
      { from: '>Beliefs</text>', to: '>beliefs</text>' },
      { from: '                </g>\n            </svg>`,\n            description: \'🔺 Cognitive-Behavioral Therapy holds that psychological distress is maintained by the reciprocal interactions between core beliefs, automatic thoughts, emotional states, and behavioral responses. Intervening at any corner of the triangle impacts the others.\'', to: '                </g>\n                <text x="250" y="425" text-anchor="middle" fill="#94A3B8" font-family="\'Inter\', sans-serif" font-size="11px">A formulation aid; situation, physiology, culture, and context also matter.</text>\n            </svg>`,\n            description: \'🔺 A simplified CBT formulation. In a situation, appraisals, emotions, behavior, and physiological responses can influence one another, while deeper beliefs can shape appraisals. Changing one element may affect others, but change is not guaranteed and cognition is not presented as the sole cause of distress. CBT uses an individualized, evolving formulation to select cognitive, behavioral, and other interventions.\'' },
      { from: "if ((heading.includes('cognitive therapy') || heading.includes('cognitive-behavioral therapy') || heading.includes('beck') || heading.includes('ellis')) && !sec.interactiveDiagram)", to: "if ((ch.id === 'ch-14' && heading === 'why this chapter matters') && !sec.interactiveDiagram)" },
    ],
  }, ['beckInstituteCbt', 'genericCognitiveModel']),
  withSources({
    key: 'dbtModules',
    correctionSummary: 'Clarified the four skills modules, distinguished skills training from comprehensive DBT, added the treatment target hierarchy, and improved module-label precision.',
    historicalContext: 'not-applicable',
    expectedPlacementCount: 1,
    replacements: [
      { from: '<svg viewBox="0 0 500 450" xmlns="http://www.w3.org/2000/svg" style="max-width:500px">\n                <defs>\n                    <radialGradient id="dbtCenter"', to: '<svg viewBox="0 0 500 480" xmlns="http://www.w3.org/2000/svg" style="max-width:500px">\n                <defs>\n                    <radialGradient id="dbtCenter"' },
      { from: '.dbt-quad { fill: #1E293B; stroke: #475569; stroke-width: 2px; transition: all 0.3s ease; cursor: pointer; }', to: '.dbt-quad { fill: #1E293B; stroke: #475569; stroke-width: 2px; }' },
      { from: '.dbt-quad:hover { stroke: #A78BFA; filter: url(#dbtGlow); transform: scale(1.02); }', to: '/* Static module cards: guided reveal controls provide the diagram interaction. */' },
      { from: '                <rect x="0" y="0" width="500" height="450" fill="url(#dbtCenter)" rx="10"/>', to: '                <text x="250" y="22" text-anchor="middle" class="dbt-title">DBT Skills-Training Modules</text>\n                <g transform="translate(0,30)">\n                <rect x="0" y="0" width="500" height="450" fill="url(#dbtCenter)" rx="10"/>' },
      { from: '>Focus: Grounding</text>', to: ' style="font-size:11px">Present-moment awareness</text>' },
      { from: '>Without judgment</text>', to: ' style="font-size:9px">Nonjudgmentally and effectively</text>' },
      { from: '>Focus: Crisis Survival</text>', to: '>Focus: Crisis survival</text>' },
      { from: '>TIPP Skills (Temp, Intense Exer,</text>\n                    <text x="85" y="95" class="dbt-desc">Paced breathing, Paired relax)</text>\n                    <text x="85" y="120" class="dbt-desc">Radical Acceptance</text>', to: ' style="font-size:9px">Crisis-survival skills (e.g., TIPP)</text>\n                    <text x="85" y="95" class="dbt-desc">Reality-acceptance skills</text>\n                    <text x="85" y="120" class="dbt-desc">Radical acceptance</text>' },
      { from: '>Focus: Modulate Mood</text>', to: '>Understand &amp; regulate</text>' },
      { from: '>Identify & Label Emotions</text>', to: '>Identify &amp; Label Emotions</text>' },
      { from: '>DEAR MAN (Objective effect)</text>', to: '>DEAR MAN — objectives</text>' },
      { from: '>GIVE (Relationship effect)</text>', to: '>GIVE — relationships</text>' },
      { from: '>FAST (Self-respect effect)</text>', to: '>FAST — self-respect</text>' },
      { from: '                </g>\n            </svg>`,\n            description: \'☯️ Dialectical Behavior Therapy (DBT) relies heavily on four core skills modules that balance the central dialectic of Acceptance (Mindfulness & Distress Tolerance) and Change (Emotion Regulation & Interpersonal Effectiveness).\'', to: '                </g>\n                </g>\n            </svg>`,\n            description: \'☯️ These are the four DBT skills-training modules. Mindfulness and distress tolerance are acceptance-oriented; emotion regulation and interpersonal effectiveness are change-oriented. Skills training is one component of comprehensive DBT, which also includes individual therapy, between-session phone coaching, and a therapist consultation team. DBT uses a target hierarchy that prioritizes life-threatening behavior, therapy-interfering behavior, quality-of-life-interfering behavior, and then skills acquisition. Teaching selected skills alone should not be labeled comprehensive DBT.\'' },
    ],
  }, ['uwDbt', 'dbtComponentTrial']),
].map((item) => ({
  ...item,
  reviewStatus: 'source-reviewed-editorial-pass',
  reviewWave,
  reviewDate,
  reviewNote: `Diagram wording, labels, and placement were corrected for accuracy, nuance, source alignment, and learner interpretation. ${item.correctionSummary} Independent qualified expert validation remains pending.`,
  checks: { ...commonChecks, historicalContext: item.historicalContext },
}));

module.exports = { reviewWave, reviewDate, sourceRecords, corrections };
