const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('@playwright/test');
const R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),cook=require('./kitchen_recipe_fixture.cjs');
const out=path.resolve(process.env.KITCHEN_QA_OUT||'reports/kitchen-visual-detail-2026-09-29'),url=process.env.KITCHEN_RECIPE_URL||'http://127.0.0.1:53061/stem_lab/kitchen_studio/recipe_lab.html';fs.mkdirSync(out,{recursive:true});
const result={checks:[],errors:[],screenshots:[]};
(async()=>{const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});let page;try{
 page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(120000);page.on('pageerror',e=>result.errors.push(e.message));
 await page.addInitScript(()=>{const seed=sessionStorage.getItem('detail-seed');if(seed){localStorage.setItem('alloflow-kitchen-recipes-v1',seed);sessionStorage.removeItem('detail-seed');}});
 await page.goto(url);await page.locator('#meetIngredients').waitFor();
 async function load(s){await page.evaluate(s=>sessionStorage.setItem('detail-seed',JSON.stringify({version:1,current:s,history:[],textView:false})),s);await page.reload();await page.locator('#meetIngredients').waitFor();assert.equal(await page.locator('#recipeScene').isVisible(),true,'The detailed scene starts in 3D');assert.equal(await page.locator('#textView').isDisabled(),false);}
 async function shot(name,view){await page.locator('[data-view='+view+']').click();await page.locator('#recipeScene').screenshot({path:path.join(out,name+'.png')});result.screenshots.push(name+'.png');}
 async function detail(name,view){await page.locator('[data-view='+view+']').click();await page.locator('#recipeScene').scrollIntoViewIfNeeded();const b=await page.locator('#recipeScene > canvas').boundingBox();await page.mouse.move(b.x+b.width*.6,b.y+b.height*.55);for(let i=0;i<10;i++)await page.mouse.wheel(0,-100);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.locator('#recipeScene').screenshot({path:path.join(out,name+'.png')});result.screenshots.push(name+'.png');}
 async function saved(){return page.evaluate(()=>JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).current);}
 function check(message){result.checks.push(message);console.log(message);}
 await load(R.start());const initial=await saved();await shot('detailed-bench','bench');await shot('cookware-and-cloth','top');await shot('mushroom-prep','prep');assert.deepEqual(await saved(),initial);check('Detailed cookware, cabinet edges, cloth, and raw produce render without changing the cook.');
 let portion=R.act(R.start(),'weigh',160,'scene-weigh');await load(portion);await page.locator('#sceneKitchenTool').selectOption('weigh');await page.locator('#recipeScene').screenshot({path:path.join(out,'hollow-pasta-on-scale.png')});result.screenshots.push('hollow-pasta-on-scale.png');assert.match(await page.locator('#sceneWeighReading').innerText(),/160 g/);
 for(const recipe of ['mushroom','tomato']){
   let s=R.start(recipe),beforePan=null;for(const [a,v]of cook(recipe).steps){if(a==='combine')beforePan=s;if(a==='plate')break;s=R.act(s,a,v);}assert.ok(beforePan&&beforePan.pan.produce);
   await load(beforePan);await page.locator('#sceneKitchenTool').selectOption('arrange');await page.locator('[data-view=pan]').click();await page.locator('#recipeScene').scrollIntoViewIfNeeded();let piece=R.panSurface(beforePan).pieces.slice().sort((a,b)=>b.z-a.z)[0],at=R.panPosition(beforePan),size=beforePan.pan.size==='wide'?1.08:1;
   const p=await page.evaluate(({x,z})=>{const b=document.querySelector('#recipeScene > canvas').getBoundingClientRect(),c=new THREE.PerspectiveCamera(38,b.width/b.height,.1,100);c.position.set(3.32,4.2,2.75);c.lookAt(1.02,1.4,-.45);c.updateMatrixWorld();const q=new THREE.Vector3(x,1.49,z).project(c);return{x:b.x+(q.x+1)*b.width/2,y:b.y+(1-q.y)*b.height/2};},{x:at.x+piece.x*size,z:at.z+piece.z*size});
   await page.mouse.click(p.x,p.y);const turned=await saved();assert.equal(turned.log.at(-1).action,'flipPiece');assert.equal(turned.log.at(-1).accepted,true);check(recipe+': textured food still responds to a real pan-piece turn.');
   await shot(recipe+'-browned-pan','pan');await load(s);await shot(recipe+'-sauced-pasta','pan');await detail(recipe+'-food-closeup','pan');
   let served=s;for(let plate=0;plate<s.servings;plate++)for(let n=0;n<4;n++)served=R.act(served,'servePortion',plate,'scene-serve');served=R.act(served,'plate');assert.equal(served.plated,true);await load(served);const displayed=await saved();await shot(recipe+'-plated-dish','plate');await detail(recipe+'-plated-closeup','plate');assert.deepEqual(await saved(),displayed);
 }
 await page.setViewportSize({width:640,height:900});await load(R.start('tomato'));await page.locator('#expandKitchen').click();await shot('compact-expanded-kitchen','top');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.keyboard.press('Escape');
 await page.evaluate(()=>{const c=document.querySelector('#recipeScene > canvas'),gl=c.getContext('webgl2')||c.getContext('webgl');gl.getExtension('WEBGL_lose_context').loseContext();});await page.locator('#recipeFallback').waitFor();assert.equal(await page.locator('#ingredientHandle').innerText(),'Open hands-on controls');check('Both cooked recipes, plated food, compact expanded view, and graphics-loss fallback render correctly.');
 assert.deepEqual(result.errors,[]);result.pass=true;
}catch(e){result.failure=e.stack;if(page)await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{fs.writeFileSync(path.join(out,'visual-results.json'),JSON.stringify(result,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
