const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('@playwright/test');
const R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),cook=require('./kitchen_recipe_fixture.cjs');
(async()=>{const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});const out=path.resolve('reports/kitchen-lab-enhancement'),results={checks:[],accessibility:[],errors:[]};try{
const page=await browser.newPage({viewport:{width:1360,height:1050},reducedMotion:'reduce'});page.on('pageerror',e=>results.errors.push(e.message));const url=(process.env.KITCHEN_RECIPE_URL||'http://127.0.0.1:53061/stem_lab/kitchen_studio/recipe_lab.html');
const completed=R.submit({...cook().state,answers:[0,0],hints:1,reflection:'I sampled before draining.'}),source=R.restore({...completed,log:[{action:'cut',value:null},...completed.log]});
await page.addInitScript(()=>{const seed=sessionStorage.getItem('recipe-replay-seed');if(seed){localStorage.setItem('alloflow-kitchen-recipes-v1',seed);sessionStorage.removeItem('recipe-replay-seed');}});await page.goto(url);assert.equal(await page.locator('#openRecipeReplay').isVisible(),false);
await page.evaluate(source=>sessionStorage.setItem('recipe-replay-seed',JSON.stringify({version:1,current:source,history:[]})),source);await page.reload();await page.locator('#recipeResult').waitFor();const saved=await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).current));
await page.locator('#reviewReplay').click();assert.equal(await page.locator('#recipeReplayControls').isVisible(),true);assert.equal(await page.locator('#recipeReplayPrevious').isDisabled(),true);assert.equal(await page.locator('.time-controls').isVisible(),false);assert.match(await page.locator('#monitorTitle').innerText(),/Recorded finished dish/);assert.match(await page.locator('#potObservation').innerText(),/Empty pot/);
await page.locator('#recipeReplayNext').click();assert.match(await page.locator('#recipeReplayAction').innerText(),/Correction recorded.*Wash hands/);const pastaIndex=source.log.findIndex(a=>a.action==='pasta')+1;await page.locator('#recipeReplayJump').selectOption(String(pastaIndex));assert.match(await page.locator('#recipeReplayChanges').innerText(),/water temperature/);assert.match(await page.locator('#potObservation').innerText(),/Pasta cooking/);await page.locator('[data-view=pot]').click();await page.screenshot({path:path.join(out,'recipe-replay-pasta.png'),fullPage:true});
await page.addScriptTag({path:path.resolve('node_modules/axe-core/axe.min.js')});async function audit(label){const issues=await page.evaluate(async()=>(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})));assert.deepEqual(issues,[]);results.accessibility.push({label,issues});}await audit('Recipe replay with 3D and change observations');
await page.locator('#recipeReplayStep').focus();await page.keyboard.press('End');assert.equal(await page.locator('#recipeReplayNext').isDisabled(),true);assert.match(await page.locator('#panObservation').innerText(),/Plated/);await page.keyboard.press('ArrowLeft');assert.equal(Number(await page.locator('#recipeReplayStep').inputValue()),source.log.length-1);await page.keyboard.press('Home');assert.equal(await page.locator('#recipeReplayStep').inputValue(),'0');await page.locator('#textView').click();await page.locator('#recipeReplayJump').selectOption(String(pastaIndex));assert.equal(await page.locator('#recipeFallback').isVisible(),true);assert.match(await page.locator('#recipeReplayChanges').innerText(),/Weighed pasta entered/);results.checks.push('Recorded cook replays the starting bench, rejected decision, pasta heat load, and final dish through the slider, keyboard, and decision jump.');
assert.equal(await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).current)),saved);const dl=page.waitForEvent('download');await page.locator('#downloadRecipe').click();const download=await dl;await download.saveAs(path.join(out,'kitchen-recipe-replayed-evidence.json'));const exported=JSON.parse(fs.readFileSync(path.join(out,'kitchen-recipe-replayed-evidence.json')));assert.deepEqual(exported.cooks,[R.evidence(source)]);
await page.setViewportSize({width:320,height:844});await page.locator('.skip').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'recipeReplayControls');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await audit('320px recipe replay in text view');await page.screenshot({path:path.join(out,'recipe-replay-mobile.png'),fullPage:true});await page.locator('#closeRecipeReplay').click();assert.equal(await page.locator('#recipeReplayControls').isVisible(),false);assert.match(await page.locator('#panObservation').innerText(),/Plated/);assert.equal(await page.evaluate(()=>document.activeElement.id),'openRecipeReplay');
await page.locator('#openRecipeReplay').click();await page.reload();assert.equal(await page.locator('#recipeReplayControls').isVisible(),false);assert.match(await page.locator('#recipeResult').innerText(),/completed with support/);await page.locator('#openRecipeReplay').click();await page.locator('#newCook').click();assert.equal(await page.locator('#recipeReplayControls').isVisible(),false);assert.equal(await page.locator('#openRecipeReplay').isVisible(),false);assert.equal(await page.locator('#clock').innerText(),'0:00');assert.equal(await page.locator('#play').isEnabled(),true);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).history.length),1);results.checks.push('Replay preserves complete saved/exported evidence, supports mobile/text/skip navigation, returns to the finished dish, and clears on reload or a fresh cook.');
const fallback=await browser.newPage();fallback.on('pageerror',e=>results.errors.push(e.message));await fallback.route('**/three.min.js',r=>r.abort());await fallback.addInitScript(source=>localStorage.setItem('alloflow-kitchen-recipes-v1',JSON.stringify({version:1,current:source,history:[]})),source);await fallback.goto(url);await fallback.locator('#openRecipeReplay').click();await fallback.locator('#recipeReplayJump').selectOption(String(pastaIndex));assert.equal(await fallback.locator('#recipeFallback').isVisible(),true);assert.match(await fallback.locator('#recipeReplayChanges').innerText(),/Weighed pasta entered/);await fallback.close();results.checks.push('Recipe replay remains usable when the 3D runtime is unavailable.');assert.deepEqual(results.errors,[]);results.pass=true;
}finally{fs.writeFileSync(path.join(out,'recipe-replay-qa-results.json'),JSON.stringify(results,null,2));await browser.close();}console.log(JSON.stringify(results,null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
