const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('@playwright/test');
const R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),S=require('../stem_lab/kitchen_studio/recipe_lab_serving.js'),cook=require('./kitchen_recipe_fixture.cjs');
const url=process.env.KITCHEN_RECIPE_URL||'http://127.0.0.1:53061/stem_lab/kitchen_studio/recipe_lab.html',out=path.resolve(process.env.KITCHEN_QA_OUT||'reports/kitchen-serving-2026-09-27');fs.mkdirSync(out,{recursive:true});const result={checks:[],accessibility:[],errors:[]};
function ready(id='mushroom',count=2){let s=R.start(id,count,'demonstrate');for(const[a,v]of cook(id,count).steps){if(a==='plate')break;s=R.act(s,a,v);}return s;}
function complete(){let s=ready('tomato',4);for(let i=0;i<4;i++)for(let n=0;n<4;n++)s=R.act(s,'servePortion',i,'scene-serve');return R.submit({...R.act(s,'plate'),answers:[0,1]});}
(async()=>{const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});let page;try{
 page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});page.setDefaultTimeout(60000);page.on('pageerror',e=>result.errors.push(e.message));await page.goto(url);
 const state=(p=page)=>p.evaluate(()=>JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).current);
 async function load(s,p=page,textView=false){await p.addInitScript(()=>{const seed=sessionStorage.getItem('serving-seed');if(seed){localStorage.setItem('alloflow-kitchen-recipes-v1',seed);sessionStorage.removeItem('serving-seed');}});await p.evaluate(data=>sessionStorage.setItem('serving-seed',JSON.stringify({version:1,current:data.s,history:[],textView:data.textView})),{s,textView});await p.reload();await p.locator('#servingTools').waitFor({state:'attached'});}
 async function open(p=page){await p.locator('[data-bench=finish]').click();if(!await p.locator('#servingTools').evaluate(e=>e.open))await p.locator('#servingTools summary').click();}
 async function tool(p=page){await p.locator('#sceneKitchenTool').selectOption('serve');await p.locator('#recipeScene').scrollIntoViewIfNeeded();}
 async function point(where,p=page){const s=await state(p),pan=R.panPosition(s),v=where==='pan'?[pan.x,1.48,pan.z]:where==='outside'?[-1.8,1.3,1.2]:[where%2?.65:-.3,1.3,s.servings===2?1.1:.63+Math.floor(where/2)*.75];return p.evaluate(v=>{const b=document.querySelector('#recipeScene canvas').getBoundingClientRect(),c=new THREE.PerspectiveCamera(38,b.width/b.height,.1,100);c.position.set(1.95,4.8,3.55);c.lookAt(.45,1.3,.35);c.updateMatrixWorld();const q=new THREE.Vector3(...v).project(c);return{x:b.x+(q.x+1)*b.width/2,y:b.y+(1-q.y)*b.height/2};},v);}
 async function carry(from,to,{cancel=false,capture=false}={},p=page){const a=await point(from,p),b=await point(to,p);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:14});if(capture)await p.locator('#recipeScene').screenshot({path:path.join(out,'spoon-carry-in-kitchen.png')});if(cancel)await p.keyboard.press('Escape');await p.mouse.up();}
 async function illustrated(from,to,{cancel=false}={},p=page){const s=await state(p),b=await p.locator('#servingSvg').boundingBox(),pos=v=>v==='pan'?{x:180,y:75}:v==='outside'?{x:5,y:370}:S.layout(s.servings)[v],a=pos(from),z=pos(to);await p.mouse.move(b.x+a.x*b.width/360,b.y+a.y*b.height/375);await p.mouse.down();await p.mouse.move(b.x+z.x*b.width/360,b.y+z.y*b.height/375,{steps:14});if(cancel)await p.keyboard.press('Escape');await p.mouse.up();}
 await load(R.start());await tool();const empty=await state();await carry('pan',0);assert.deepEqual(await state(),empty);assert.match(await page.locator('#sceneActionStatus').innerText(),/Combine and check/);
 await load(ready());await tool();const initial=await state();await carry(0,'pan');assert.deepEqual(await state(),initial);await carry('pan','pan');assert.deepEqual(await state(),initial);await carry('pan','outside');assert.deepEqual(await state(),initial);await carry('pan',0,{cancel:true});assert.deepEqual(await state(),initial);await carry('pan',0,{capture:true});let partial=await state();assert.deepEqual(R.serving(partial).plates,[1,0]);assert.equal(partial.log.at(-1).interaction,'scene-serve');assert.equal(partial.time,initial.time);assert.equal(partial.pan.moisture,initial.pan.moisture);assert.equal(await page.locator('#play').isDisabled(),true);assert.equal(await page.locator('#sceneFinishServing').isDisabled(),true);await page.reload();assert.deepEqual(await state(),partial);await tool();await carry(0,'pan');assert.equal(R.serving(await state()).served,0);assert.equal(await page.locator('#play').isDisabled(),false);
 for(let i=0;i<6;i++)await carry('pan',0);for(let i=0;i<2;i++)await carry('pan',1);assert.deepEqual(R.serving(await state()).plates,[6,2]);await page.locator('#recipeScene').screenshot({path:path.join(out,'uneven-serving-portions.png')});await carry('pan',0);assert.deepEqual(R.serving(await state()).plates,[6,2]);for(let i=0;i<2;i++){await carry(0,'pan');await carry('pan',1);}assert.deepEqual(R.serving(await state()).plates,[4,4]);await page.locator('#recipeScene').screenshot({path:path.join(out,'balanced-serving-portions.png')});await page.locator('#sceneFinishServing').click();assert.equal((await state()).plated,true);assert.equal(R.criteria(await state()).every(g=>g.met),true);
 result.checks.push('Real 3D carries require a checked dish and burners off. Wrong drops, taps, empty plates, and Escape leave portions unchanged. Spoonfuls remain finite, partial portions survive reload, returning all food unlocks cooking, and an uneven batch can be rebalanced and finished in 3D.');
 await load(R.act(ready('tomato',4),'panPlace','trivet'));await tool();for(let i=0;i<4;i++)await carry('pan',i);assert.deepEqual(R.serving(await state()).plates,[1,1,1,1]);await carry(3,'pan');assert.deepEqual(R.serving(await state()).plates,[1,1,1,0]);await page.locator('#recipeScene').screenshot({path:path.join(out,'four-plates-pan-on-trivet.png')});
 await page.locator('#sceneKeyboardTools').click();assert.equal(await page.locator('#servingPan').evaluate(e=>e===document.activeElement),true);await page.locator('#servingPlateChoice').selectOption('3');await page.locator('#servingPan').focus();assert.match(await page.locator('#servingPan').getAttribute('aria-label'),/plate 4/);await page.keyboard.down('Enter');await page.keyboard.down('Enter');await page.keyboard.up('Enter');assert.equal(R.serving(await state()).plates[3],1);await page.locator('#servingPlates [data-serving-source="3"]').focus();await page.keyboard.press('Space');assert.equal(R.serving(await state()).plates[3],0);await page.locator('#servingSvg').scrollIntoViewIfNeeded();const before=await state();await illustrated('pan','outside');await illustrated('pan',2,{cancel:true});assert.deepEqual(await state(),before);await illustrated('pan',2);assert.equal(R.serving(await state()).plates[2],2);await illustrated(2,'pan');assert.equal(R.serving(await state()).plates[2],1);await page.locator('#servingTools').screenshot({path:path.join(out,'serving-controls-desktop.png')});
 result.checks.push('Every plate works for four servings, including a pan resting on the trivet. Keyboard focus, destination labels, single-key passes, illustrated carries, and returning spoonfuls all share the same model.');
 async function audit(label){await page.addScriptTag({path:path.resolve('node_modules/axe-core/axe.min.js')});const issues=await page.evaluate(async()=>(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})));result.accessibility.push({label,issues});assert.deepEqual(issues,[]);}
 await audit('Desktop serving controls');await page.setViewportSize({width:320,height:844});await page.locator('#textView').click();await open();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await audit('320px illustrated serving');await page.locator('#servingTools').screenshot({path:path.join(out,'serving-controls-mobile.png')});await page.emulateMedia({forcedColors:'active'});await audit('Forced colors');await page.emulateMedia({forcedColors:'none'});await page.setViewportSize({width:1440,height:1100});
 await load(complete(),page,true);const saved=await state();await page.locator('#openRecipeReplay').click();await page.locator('#recipeReplayStep').fill(String(saved.log.findIndex(e=>e.action==='servePortion')+1));await open();assert.equal(await page.locator('#serveSpoonful').isDisabled(),true);assert.equal(await page.locator('#returnSpoonful').isDisabled(),true);assert.match(await page.locator('#recipeReplayChanges').innerText(),/Serving portions/);assert.match(await page.locator('#servingReading').innerText(),/Plate 1: 1 of 4/);assert.deepEqual(await state(),saved);await page.locator('#closeRecipeReplay').click();const download=page.waitForEvent('download');await page.locator('#downloadRecipe').click();await(await download).saveAs(path.join(out,'serving-evidence.json'));const evidence=JSON.parse(fs.readFileSync(path.join(out,'serving-evidence.json'),'utf8')).cooks.at(-1);assert.deepEqual(evidence.serving.plates,[4,4,4,4]);assert.equal(evidence.actions.filter(e=>e.interaction==='scene-serve').length,16);
 result.checks.push('Locked replay reconstructs the historical portions without changing the cook. Exported evidence includes individual plates and exact serving transfers. Desktop, 320px, and forced-color views pass accessibility scans.');
 const mobile=await browser.newPage({viewport:{width:600,height:950},hasTouch:true,isMobile:true});mobile.setDefaultTimeout(60000);mobile.on('pageerror',e=>result.errors.push(e.message));await mobile.goto(url);await load(ready(),mobile);await tool(mobile);const cdp=await mobile.context().newCDPSession(mobile),a=await point('pan',mobile),b=await point(0,mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[b]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(R.serving(await state(mobile)).plates[0],1);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[b]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(R.serving(await state(mobile)).plates[0],1);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[b]});await mobile.evaluate(()=>{const c=document.querySelector('#recipeScene canvas'),gl=c.getContext('webgl2')||c.getContext('webgl');gl.getExtension('WEBGL_lose_context').loseContext();});await mobile.locator('#recipeFallback').waitFor();await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(R.serving(await state(mobile)).plates[0],1);await open(mobile);await mobile.locator('#returnSpoonful').click();assert.equal(R.serving(await state(mobile)).served,0);await mobile.locator('#servingSvg').scrollIntoViewIfNeeded();const mb=await mobile.locator('#servingSvg').boundingBox(),pa={x:mb.x+180*mb.width/360,y:mb.y+75*mb.height/375},pb={x:mb.x+87*mb.width/360,y:mb.y+245*mb.height/375};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pa]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[pb]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(R.serving(await state(mobile)).plates[0],1);await mobile.close();
 result.checks.push('Real touch serves in 3D and without WebGL. Touch cancellation and graphics loss during a carry leave all food conserved; completed portions remain available to return.');assert.deepEqual(result.errors,[]);result.pass=true;
 }catch(e){if(page)await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}finally{fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));await browser.close();}console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
