const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('@playwright/test');
const R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),cook=require('./kitchen_recipe_fixture.cjs');
const out=path.resolve(process.env.KITCHEN_QA_OUT||'reports/kitchen-food-lens-2026-09-29'),url=process.env.KITCHEN_RECIPE_URL||'http://127.0.0.1:53061/stem_lab/kitchen_studio/recipe_lab.html';
function prepared(id='mushroom',uneven=false){let s=R.start(id);for(const[a,v]of [['wash'],['rinse'],...(uneven?[['slice','0:5'],['finishCuts']]:[['cut']]),['dry'],['oil'],['produce'],['spreadPan']])s=R.act(s,a,v);return s;}
fs.mkdirSync(out,{recursive:true});const result={checks:[],errors:[],accessibility:[]};
(async()=>{const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});let page;try{
 page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(120000);page.on('pageerror',e=>result.errors.push(e.message));
 await page.addInitScript(()=>{const seed=sessionStorage.getItem('lens-seed');if(seed){localStorage.setItem('alloflow-kitchen-recipes-v1',seed);sessionStorage.removeItem('lens-seed');}});await page.goto(url);await page.locator('#sceneKitchenTool').waitFor();
 const current=(p=page)=>p.evaluate(()=>JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).current),check=m=>{result.checks.push(m);console.log(m);};
 async function load(s,p=page){await p.evaluate(s=>sessionStorage.setItem('lens-seed',JSON.stringify({version:1,current:s,history:[],textView:false})),s);await p.reload();await p.locator('#sceneKitchenTool').waitFor();assert.equal(await p.locator('#textView').isDisabled(),false);}
 async function tool(p=page){await p.locator('#sceneKitchenTool').selectOption('inspect');await p.locator('#recipeScene').scrollIntoViewIfNeeded();assert.equal(await p.locator('#recipeScene>canvas').getAttribute('data-camera-view'),'pan');}
 async function point(index,p=page){const s=await current(p),piece=R.panSurface(s).pieces[index],at=R.panPosition(s),scale=s.pan.size==='wide'?1.08:1;return p.evaluate(({x,z,at})=>{const b=document.querySelector('#recipeScene>canvas').getBoundingClientRect(),c=new THREE.PerspectiveCamera(38,b.width/b.height,.1,100);c.position.set(at.x+2.3,4.2,at.z+3.2);c.lookAt(at.x,1.4,at.z);c.updateMatrixWorld();const q=new THREE.Vector3(x,1.49,z).project(c);return {x:b.x+(q.x+1)*b.width/2,y:b.y+(1-q.y)*b.height/2};},{x:at.x+piece.x*scale,z:at.z+piece.z*scale,at});}
 async function audit(name){await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const scan=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}}));result.accessibility.push({name,violations:scan.violations});assert.deepEqual(scan.violations,[],name+' accessibility');}
 await load(prepared());await tool();const before=await current();let points=await Promise.all([point(0),point(4)]);await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();assert.equal(await page.locator('.food-loupe').isVisible(),true);assert.equal(await page.locator('#lensPiece').inputValue(),'0');await page.mouse.move(points[1].x,points[1].y,{steps:12});assert.equal(await page.locator('#lensPiece').inputValue(),'4');assert.deepEqual(await current(),before);
 const pixels=await page.locator('.food-loupe canvas').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,colors=new Set();for(let i=0;i<d.length;i+=64)colors.add([d[i],d[i+1],d[i+2],d[i+3]].join(','));return colors.size;});assert.ok(pixels>20,'Lens contains actual scene detail');await page.locator('#recipeScene').screenshot({path:path.join(out,'scan-food-in-3d.png')});await page.mouse.up();assert.equal(await page.locator('.food-loupe').isVisible(),false);assert.equal(await page.locator('#lensPiece').inputValue(),'4');await audit('Desktop food lens');check('A real pointer drag scans multiple food pieces and magnifies the actual 3D canvas. Release selects the view without cooking actions, time or evidence.');
 await tool();points=await Promise.all([point(0),point(4)]);await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.keyboard.press('Escape');await page.mouse.up();assert.equal(await page.locator('.food-loupe').isVisible(),false);assert.deepEqual(await current(),before);check('Escape cancels the lens overlay and leaves the cook unchanged.');
 await page.locator('#play').click();await page.locator('#recipeScene').scrollIntoViewIfNeeded();const runningPoint=await point(0);await page.mouse.move(runningPoint.x,runningPoint.y);await page.mouse.down();assert.match(await page.locator('#clockStatus').innerText(),/paused/);const paused=await current();await page.waitForTimeout(250);assert.deepEqual(await current(),paused);await page.keyboard.press('Escape');await page.mouse.up();check('Grabbing the lens pauses a running kitchen for an observation.');
 await page.locator('#sceneKeyboardTools').click();assert.equal(await page.locator('#lensPiece').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Home');await page.locator('#lensKeep').click();const kept=await page.locator('#lensHeldReading').innerText();await page.locator('[data-bench=pan]').click();await page.locator('#panPieceChoice').selectOption('0');await page.locator('#turnPanPiece').click();assert.match(await page.locator('#lensComparison').innerText(),/other face/);assert.equal(await page.locator('#lensHeldReading').innerText(),kept);const turned=await current();assert.equal(turned.log.at(-1).action,'flipPiece');assert.equal(turned.time,paused.time);/* Use the existing, canonical burner control. */await page.locator('#scenepanHeat').selectOption('2');await page.locator('#advance').click();assert.match(await page.locator('#lensComparison').innerText(),/30 simulated seconds later/);assert.equal(await page.locator('#lensHeldReading').innerText(),kept);await page.locator('#foodLens').screenshot({path:path.join(out,'kept-and-current-observations.png')});check('Keyboard selection and keeping a view pause the kitchen. Real turning and time advancement update only the current observation; the kept view remains intact.');
 await load(prepared('mushroom',true));await tool();await page.locator('#lensPiece').selectOption('0');await page.locator('#lensKeep').click();await page.locator('#lensPiece').selectOption('7');assert.match(await page.locator('#lensComparison').innerText(),/5 → 35 mm/);await page.locator('#foodLens').screenshot({path:path.join(out,'compare-cut-sizes.png')});const untouched=await current();await page.locator('#textView').click();assert.equal(await page.locator('#recipeFallback').isVisible(),true);await page.locator('#lensPiece').selectOption('1');await page.locator('#lensKeep').click();assert.deepEqual(await current(),untouched);await audit('Text view food comparisons');check('Cut labels distinguish unequal widths; sketches show the recorded upward face. Text view offers the same observations and comparisons without changing the cook.');
 await page.locator('#newCook').click();assert.equal(await page.locator('#lensClear').isDisabled(),true);assert.equal(await page.locator('#lensKeep').isDisabled(),true);check('A fresh cook clears kept observations and disables the lens until food is in the pan.');
 const finished=R.submit({...cook().state,answers:[0,0]});await load(finished);await page.locator('#openRecipeReplay').click();const produceIndex=finished.log.findIndex(e=>e.action==='produce'&&e.accepted)+1,flipIndex=finished.log.findIndex(e=>e.action==='stirPan'&&e.accepted&&finished.log.indexOf(e)>=produceIndex)+1;
 await page.locator('#recipeReplayJump').selectOption(String(produceIndex));await page.locator('#foodLens>summary').click();assert.match(await page.locator('#lensLiveReading').innerText(),new RegExp('Recorded at '+Math.floor(R.replay(finished,produceIndex).state.time/60)+':'));const completedBaseline=await current();await page.locator('#lensKeep').click();const recorded=await page.locator('#lensHeldReading').innerText();await page.locator('#recipeReplayJump').selectOption(String(flipIndex));assert.equal(await page.locator('#lensHeldReading').innerText(),recorded);assert.deepEqual(await current(),completedBaseline);await audit('Recorded food observation');await page.locator('#closeRecipeReplay').click();assert.equal(await page.locator('#lensClear').isDisabled(),true);check('Replay observes its historical pan frame, allows comparisons within that recording, and never reads the final dish as an earlier observation or alters stored evidence.');
 const mobile=await browser.newPage({viewport:{width:390,height:900},hasTouch:true,isMobile:true,reducedMotion:'reduce'});mobile.setDefaultTimeout(60000);mobile.on('pageerror',e=>result.errors.push(e.message));await mobile.addInitScript(()=>{const seed=sessionStorage.getItem('lens-seed');if(seed){localStorage.setItem('alloflow-kitchen-recipes-v1',seed);sessionStorage.removeItem('lens-seed');}});await mobile.goto(url);await mobile.locator('#sceneKitchenTool').waitFor();await load(prepared(),mobile);await tool(mobile);const mobileBefore=await current(mobile),ps=await Promise.all([point(0,mobile),point(4,mobile)]),cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[ps[0]]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[ps[1]]});assert.equal(await mobile.locator('.food-loupe').isVisible(),true);assert.equal(await mobile.locator('#lensPiece').inputValue(),'4');await mobile.locator('#recipeScene').screenshot({path:path.join(out,'touch-food-lens.png')});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual(await current(mobile),mobileBefore);assert.equal(await mobile.locator('.food-loupe').isVisible(),false);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await mobile.close();check('Real touch scans pieces at 390px, shows the magnifier, and leaves the cook unchanged with no horizontal overflow.');
 await load(prepared());await tool();await page.setViewportSize({width:320,height:900});await tool();await page.locator('#foodLens').screenshot({path:path.join(out,'compact-food-lens.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await audit('320px food lens');await page.emulateMedia({forcedColors:'active'});await audit('Forced-color observations');await page.emulateMedia({forcedColors:'none'});await page.setViewportSize({width:1440,height:1100});await tool();
 const pt=await point(0);await page.mouse.move(pt.x,pt.y);await page.mouse.down();const beforeLoss=await current();await page.evaluate(()=>{const c=document.querySelector('#recipeScene>canvas'),gl=c.getContext('webgl2')||c.getContext('webgl');gl.getExtension('WEBGL_lose_context').loseContext();});await page.locator('#recipeFallback').waitFor();await page.mouse.up();assert.equal(await page.locator('.food-loupe').isVisible(),false);await page.locator('#lensPiece').selectOption('5');await page.locator('#lensKeep').click();assert.deepEqual(await current(),beforeLoss);check('The lens fits 320px and forced colors. Graphics loss cancels an active lens and retains working observation controls.');
 assert.deepEqual(result.errors,[]);result.pass=true;
}catch(e){result.failure=e.stack;if(page)await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{fs.writeFileSync(path.join(out,'lens-results.json'),JSON.stringify(result,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
