const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('@playwright/test'),R=require('../stem_lab/kitchen_studio/recipe_lab_engine.js'),cook=require('./kitchen_recipe_fixture.cjs');
const out=path.resolve(process.env.KITCHEN_QA_OUT||'reports/kitchen-deliberate-plating-2026-09-30/plating-ux'),url='http://127.0.0.1:53061/stem_lab/kitchen_studio/recipe_lab.html?v=20260930-plating';fs.mkdirSync(out,{recursive:true});const result={checks:[],errors:[],accessibility:[]};
function ready(){let s=R.start();for(const[a,v]of cook().steps){if(a==='plate')break;s=R.act(s,a,v);}return s;}
(async()=>{const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});let page;try{
 page=await browser.newPage({viewport:{width:390,height:900},hasTouch:true,isMobile:true,reducedMotion:'reduce'});page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(120000);page.on('pageerror',e=>result.errors.push(e.message));await page.addInitScript(()=>{const s=sessionStorage.getItem('plating-seed');if(s){localStorage.setItem('alloflow-kitchen-recipes-v1',s);sessionStorage.removeItem('plating-seed');}});await page.goto(url);await page.locator('#sceneKitchenTool').waitFor({state:'attached'});
 const current=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).current),check=t=>{result.checks.push(t);console.log(t);};
 async function load(s){await page.evaluate(s=>sessionStorage.setItem('plating-seed',JSON.stringify({version:1,current:s,history:[],textView:false})),s);await page.reload();await page.locator('#sceneKitchenTool').waitFor({state:'attached'});await tool();}
 async function tool(){await page.locator('#sceneKitchenTool').selectOption('serve');await page.locator('#recipeScene').scrollIntoViewIfNeeded();}
 async function project(where){return page.evaluate(where=>{const s=JSON.parse(localStorage.getItem('alloflow-kitchen-recipes-v1')).current,at=KitchenRecipes.panPosition(s),p=[{x:-.3,z:1.1},{x:.65,z:1.1}],x=(Math.min(at.x-.75,p[0].x-.45)+Math.max(at.x+.75,p[1].x+.45))/2,z=(at.z-.75+Math.max(at.z+.75,p[1].z+.45))/2,b=document.querySelector('#recipeScene > canvas').getBoundingClientRect(),c=new THREE.PerspectiveCamera(38,b.width/b.height,.1,100),f=Math.max(1,1.35/c.aspect);c.position.set(x+.2*f,1.35+3.6*f,z+2.9*f);c.lookAt(x,1.35,z);c.updateMatrixWorld();const a=where==='pan'?at:p[where],q=new THREE.Vector3(a.x,where==='pan'?1.48:1.3,a.z).project(c);return {x:b.x+(q.x+1)*b.width/2,y:b.y+(1-q.y)*b.height/2,unit:b.height/420};},where);}
 const cdp=await page.context().newCDPSession(page),send=(type,p)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:p?[{x:p.x,y:p.y,id:1}]:[]}),phase=p=>page.waitForFunction(p=>document.querySelector('#recipeScene > canvas').dataset.platingPhase===p,p);
 async function dock(from='pan',to=0){const a=await project(from),b=await project(to);await send('touchStart',a);await send('touchMove',{x:a.x,y:a.y+34*a.unit});await phase('lift');await send('touchMove',a);await phase('carry');for(let i=1;i<=12;i++)await send('touchMove',{x:a.x+(b.x-a.x)*i/12,y:a.y+(b.y-a.y)*i/12});await phase('tip');return b;}
 async function tip(b){await send('touchMove',{x:b.x,y:b.y+40*b.unit});await phase('release');}
 async function audit(name){await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const a=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}}));result.accessibility.push({name,violations:a.violations});assert.deepEqual(a.violations,[]);}
 await load(R.start());assert.equal(await page.locator('#scenePlatingRemaining').textContent(),'No finished dish');assert.equal(await page.locator('#scenePlatingKeyboard').isDisabled(),true);await page.locator('#recipeScene').screenshot({path:path.join(out,'phone-empty-place-settings.png')});check('The fresh kitchen shows place settings without inventing a finished batch or enabling serving.');
 await load(ready());let before=await current(),b=await dock();assert.deepEqual(await current(),before);assert.equal(await page.locator('#scenePlatingCarry').textContent(),'1 · preview');assert.equal(await page.locator('#scenePlatingCards strong').first().textContent(),'0 / 4 spoonfuls');await send('touchEnd');assert.deepEqual(await current(),before);check('A real phone scoop and level hover keep every portion and the clock unchanged.');
 b=await dock();await tip(b);await send('touchMove',b);await phase('tip');await send('touchEnd');assert.deepEqual(await current(),before);b=await dock();await tip(b);assert.deepEqual(await current(),before);await page.locator('#recipeScene').screenshot({path:path.join(out,'phone-tipped-spoon.png')});await send('touchEnd');assert.equal(R.serving(await current()).plates[0],1);assert.equal(await page.locator('#scenePlatingCarry').textContent(),'Empty');b=await dock(0,'pan');await tip(b);await send('touchEnd');assert.equal(R.serving(await current()).served,0);assert.equal(await page.locator('#play').isDisabled(),false);await audit('390px portion feedback');check('Leveling cancels a tipped preview; tip and release transfer exactly one spoonful in either direction and returning all food unlocks cooking.');
 before=await current();await page.locator('#scenePlatingCards button').nth(1).click();assert.equal(await page.locator('#servingPlateChoice').inputValue(),'1');assert.equal(await page.locator('#serveSpoonful').evaluate(e=>e===document.activeElement),true);assert.deepEqual(await current(),before);await page.keyboard.press('Enter');assert.equal(R.serving(await current()).plates[1],1);check('Adjust-plate controls focus the exact keyboard destination and change no evidence until the serving action.');
 let uneven=ready();for(let i=0;i<6;i++)uneven=R.act(uneven,'servePortion',0);for(let i=0;i<2;i++)uneven=R.act(uneven,'servePortion',1);await load(uneven);assert.match(await page.locator('#scenePlatingCards p').first().textContent(),/2 extra/);assert.match(await page.locator('#scenePlatingCards p').nth(1).textContent(),/2 more/);await page.reload();await page.locator('#sceneKitchenTool').waitFor({state:'attached'});await tool();assert.equal(await page.locator('#scenePlatingCards strong').first().textContent(),'6 / 4 spoonfuls');await page.locator('#scenePlatingResult').screenshot({path:path.join(out,'phone-portion-balance.png')});check('Underfilled and overfilled plate feedback restores from canonical actions after reloading.');
 await load(ready());before=await current();await dock();await page.evaluate(()=>document.querySelector('[data-action="taste"]').click());const changed=await current();assert.equal(changed.log.length,before.log.length+1);assert.equal(changed.log.at(-1).action,'taste');await phase('idle');await send('touchEnd');assert.deepEqual(await current(),changed);check('A cooking-state change cancels a held spoon without transferring food.');
 await page.setViewportSize({width:320,height:860});await tool();await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#scenePlatingResult').screenshot({path:path.join(out,'compact-plating-panel.png')});await audit('320px forced colors');check('The new portion panel fits 320px and remains accessible with forced colors and reduced motion.');assert.deepEqual(result.errors,[]);result.pass=true;
}catch(e){result.failure=e.stack;if(page)await page.screenshot({path:path.join(out,'plating-failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{fs.writeFileSync(path.join(out,'plating-results.json'),JSON.stringify(result,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
