const {session}=require('./science_refinement_session.cjs');exports.refine=p=>{const {E,get,replaceAll,finish}=session(p);
replaceAll('Every straight line can be written as y = mx + b.','Every nonvertical straight line can be written as y = mx + b.');
replaceAll('Every straight line can be written as y = mx + b','Every nonvertical straight line can be written as y = mx + b');
E('reading','data',`## Slope and Start

A proportional model y = mx passes through the origin, (0,0). A nonvertical line can also have a nonzero y-intercept: **y = mx + b**. This lesson uses that form. A vertical line cannot be written this way and is not a function of x.

Consider invented phone prices. Plan A costs $2 per gigabyte with no fee: y = 2x. Plan B costs $10 per month plus $1 per gigabyte: y = x + 10. Define x as gigabytes used and y as monthly dollars, assuming no other charges.

The **slope m** is the change in y divided by the change in x between two distinct points. Keep the same subtraction order. The change in x must be nonzero. For (0,4) and (2,10), rise is 6 and run is 2, so slope is 3. Rise is a signed vertical change: it can be negative. Run is a signed horizontal change.

The **y-intercept b** is the output at x = 0. It is a starting amount only when zero input represents the beginning of the situation. A line does not literally begin at its intercept, and real data may cover a domain that excludes zero.

For Plan B, m is $1 per gigabyte and b is $10. At 15 gigabytes, cost is 15 + 10 = $25. State units when interpreting these numbers.

With x increasing to the right, positive slope means y increases, negative slope means y decreases, and zero slope means y is constant. A positive slope does not require positive output: y = 0.5x - 3 rises even where its values are negative. Apparent steepness also depends on axis scales; numerical slope comes from coordinate changes.

Real situations use **models**. Constant rates can be useful approximations over a limited interval, but plants and batteries need not change linearly. A tank with 100 litres draining at five litres per minute follows y = 100 - 5x from zero through twenty minutes. Continuing the line below zero would predict an impossible negative amount of water.

Two distinct nonvertical lines with the same slope are parallel. Different slopes can produce an intersection. For weekly costs y = 40x and y = 25x + 300, equality gives 15x = 300, so x = 20 weeks and y = $800. Before that point the first is cheaper; after it the second is cheaper, under the stated assumptions.

Read the equation as a model: what are the quantities and units, what do m and b mean, and for which inputs is it useful?`);
const defs={0:'In this lesson, a function y = mx + b whose graph lies on a nonvertical straight line.',1:'Change in y divided by nonzero change in x, using the same subtraction order.',2:'The y-intercept here: the output when x = 0. Other intercepts refer to other axes.',3:'The signed vertical change between two points; it may be negative.',4:'The signed horizontal change between two points; it must be nonzero to calculate slope.',8:'For slope: y increases as x increases; y itself need not be positive.',9:'For slope: y decreases as x increases; y itself need not be negative.'};for(const [i,v]of Object.entries(defs))E('glossary',`data.${i}.def`,v);
E('anchor','data.sections.0.bullets.1','Signed change in y divided by nonzero change in x');E('anchor','data.sections.1.bullets.2','A starting value when x = 0 means the start');E('anchor','data.sections.3.bullets.0','For allowed inputs: multiply by m, then add b');E('anchor','data.sections.3.bullets.2','Name units, assumptions and allowed inputs');
E('memory','data.sourceExcerpt','Every nonvertical line has y = mx + b. The slope is signed change in y divided by nonzero change in x. The intercept is y when x = 0; interpret the model within its domain.');E('memory','data.cards.0.essentialFacts.1','b is the output at x = 0, a starting amount if zero input marks the beginning.');E('memory','data.cards.1.mapping','Read increasing x from left to right. The line is a graph of quantities, not necessarily a physical hill; its visible angle also depends on axis scales.');E('memory','data.cards.1.essentialFacts.0','Positive slope means y increases with x; actual plant growth is not necessarily linear.');E('memory','data.cards.1.essentialFacts.1','Negative slope means y decreases with x; a draining model stops when the tank is empty.');
E('sort','data.categories.0.label','POSITIVE');E('sort','data.categories.1.label','NEGATIVE');E('sort','data.categories.2.label','ZERO');E('sort','data.items.5.content','A battery model losing 8 percentage points of full charge per hour');E('sort','data.items.8.content','A model of plant height increasing 1 cm per day over a limited interval');
E('math','data.problems.3.question','Assume a 20 cm candle loses height at a constant 4 cm per hour until used up. Write its height model and domain.');E('math','data.problems.3.answer','y = -4x + 20, for 0 ≤ x ≤ 5 hours');E('math','data.problems.3.steps.2.explanation','The model is y = -4x + 20. Height reaches zero at five hours, so do not use it beyond 0 ≤ x ≤ 5. This is an assumed model, not a burning activity.');E('math','data.problems.3.realWorld','Constant decrease is a limited model; real rates may vary.');E('quiz','data.questions.5.expectedAnswer','y = -5x + 50, for 0 ≤ x ≤ 10 minutes. The intercept is 50 gallons initially, and the slope is -5 gallons per minute. At ten minutes the pool is empty; the line must not be extended to negative water amounts.');
const fa=['Numerical slope is signed vertical change divided by horizontal change. Larger absolute slope is steeper when axis scales are held fixed. A negative slope can be very steep too.','A nonzero intercept adds an output at x = 0. Proportional models are the special case b = 0; both kinds may be useful within specified domains.','Yes. Slope 1/2 means an increase of one output unit for two input units. State the axis units and scales before interpreting its apparent angle.','A zero slope gives a horizontal line: y stays constant as x changes. This does not mean nothing in the real situation changes, only the modeled output.','Distinct nonvertical parallel lines have equal slopes and different intercepts. Coincident lines have the same slope and intercept; vertical parallel lines have undefined slope.','Linear models are useful for fixed-rate prices and other approximately steady changes. Real data may need another model, and predictions require checking assumptions and domain.'];fa.forEach((v,i)=>E('faq',`data.${i}.answer`,v));
E('challenge','data.instructions','Use the supplied hypothetical vendor prices to compare two linear cost models. Find the break-even point and state which is cheaper for the requested session lengths.');E('challenge','data.brief.lockedLessonFacts.0','Every nonvertical straight line can be written as y = mx + b.');E('challenge','data.brief.lockedLessonFacts.2','b is the cost at zero weeks under the assumed billing rules.');E('challenge','data.coachHint','A = 40x; B = 25x + 300. At 12 weeks: $480 versus $600. At 30: $1200 versus $1050. Equality at 20 weeks, $800. Week counts are nonnegative whole numbers; the lines show the model rule.');
return finish();};
