const {session}=require('./science_refinement_session.cjs');exports.refine=p=>{const {E,get,replaceAll,finish}=session(p);
E('reading','data',`## Ten Is a Friendly Number

Look at a ten frame. It has two rows of five spaces. Fill each space with one counter. Now you have **ten**!

Each whole number from zero to ten has a **partner** that makes ten. Six and four are partners. Seven and three are partners. Five and five are partners too. Ten and zero make ten: one group can be empty.

A number **bond** shows a whole and its parts. Here, our whole is ten.

Try 8 + 5 with counters. Eight needs two more to be ten. **Break** the five into two and three. Move the two to the eight. Now you have ten and three **left**. Ten and three make thirteen.

You moved counters between groups. You did not add any new counters or take any away. The **sum** stays the same.

Try 9 + 6. Nine needs one more. Break six into one and five. Move one to the nine. Ten and five make fifteen.

You can also count on or use a **double**, like 6 + 6. Different ways can help. Use counters, drawings or fingers if they work for you. Take the time you need.

Can you show one way to make ten?`);
E('glossary','data.0.def','The number after nine; two groups of five make ten.');E('glossary','data.3.def','In this lesson, the whole number that joins another to make ten.');E('glossary','data.4.def','A way to show a whole number and its parts; here the whole is ten.');E('glossary','data.8.def','To match one number word to each object; the last word tells how many.');
replaceAll('Some sums are hard. But there is a trick. If you can make a ten first, the rest is easy.','Making a ten can help you add. Use counters, pictures or fingers if they work for you. Take the time you need.');replaceAll('say each answer out loud first','say, point to or show each answer first');replaceAll('Ten Problems','Make-Ten Problems');
E('anchor','data.sections.0.bullets.0','9 and 1; also 10 and 0');E('anchor','data.sections.1.bullets.0','For 8 + 5, start with eight');E('anchor','data.sections.1.bullets.1','Eight needs two to make ten');E('anchor','data.sections.1.bullets.2','Split five into two and three; move two');E('anchor','data.sections.2.label','TEN AND SOME MORE');E('anchor','data.sections.3.label','OTHER WAYS TO ADD');E('anchor','data.sections.3.bullets.1','Count on, including when adding one');E('anchor','data.sections.3.bullets.2','Choose a way you can explain');
E('memory','data.sourceExcerpt','Each whole number from zero to ten has a partner that makes ten. Eight needs two more. Split five into two and three.');
const M=(i,k,v)=>E('memory',`data.cards.${i}.${k}`,v);M(0,'target','A ten frame shows partners for ten');M(0,'essentialFacts.0','A ten frame has two rows of five spaces.');M(0,'essentialFacts.2','Each whole number from zero to ten has a whole-number partner that makes ten.');M(0,'aiExample','Fill six spaces in a ten frame. Four spaces are empty. Six and four make ten. Add one counter to each empty space to check.');M(0,'mapping','Filled spaces show one part. Empty spaces show how many more are needed. You can count or recognize the groups.');M(0,'scaffoldStarter','I filled ____ spaces. ____ spaces are empty.');M(0,'scaffoldSteps.0','Use a ten frame with two rows of five spaces.');M(0,'scaffoldSteps.1','Fill some spaces with one counter each.');M(0,'scaffoldSteps.2','Count the empty spaces to find the partner.');M(0,'studentPrompt','Show two partners with counters, a drawing or fingers if helpful.');M(0,'reasoningPrompt','How does your picture show the two parts of ten?');M(0,'hookFact.text','A ten frame has two rows of five spaces. Together, that is ten.');M(1,'essentialFacts.0','For these examples, choose an addend below ten to fill to ten.');M(1,'aiExample','LOOK, NEED, MOVE. Look at eight. It needs two. Split five into two and three, then move two to eight. Ten and three make thirteen.');M(1,'reasoningPrompt','Why might starting with eight help in 8 + 5? Could you show another way?');
E('sort','data.categories.0.label','MAKES TEN');E('sort','data.categories.1.label','NOT TEN');
E('math','data.problems.3.steps.0.explanation','Put six counters into a ten frame.');E('math','data.problems.3.steps.1.explanation','Count the empty spaces. There are four.');E('math','data.problems.3.steps.2.explanation','Fill those four spaces. Six and four make ten.');
E('faq','data.0.question','Why does a ten frame help?');E('faq','data.0.answer','Two rows of five make ten. The spaces help you see how many you have and how many more you need.');E('faq','data.1.answer','Yes. You can use fingers, counters, drawings or a ten frame. Choose a tool that works for you. Counting helps you explain your thinking.');E('faq','data.3.answer','Fill a ten frame with the number you have. Count the empty spaces. That tells how many more will make ten.');E('faq','data.5.answer','No. You can count on, use doubles or make a ten. Choose a way that helps you, and show how it works.');
E('challenge','data.brief.context','Use ten teacher-provided counters, blocks or picture tokens and a ten frame. Move them, point while a partner moves them, or use a digital version.');E('challenge','data.brief.lockedLessonFacts.0','A ten frame has two rows of five spaces.');E('challenge','data.brief.lockedLessonFacts.1','Each whole number from zero to ten has a partner that makes ten.');E('challenge','data.brief.openQuestions.1','Do 6 and 4 and 4 and 6 give the same total? What changes about the groups?');E('challenge','data.brief.constraints.1','Two groups each time; one group may be empty');E('challenge','data.brief.constraints.2','Count, point, draw or explain with a partner');E('challenge','data.supports.frameChoices.2','Ten picture tokens');E('challenge','data.supports.frameChoices.3','Ten digital counters');E('challenge','data.coachHint','Keep ten in total. Move one at a time. If left and right count as different, there are eleven pairs from 0 and 10 through 10 and 0. Ignoring order gives six pairs. One group can be empty.');E('challenge','data.sourceExcerpt','Each whole number from zero to ten has a partner that makes ten. Moving counters between groups keeps the total the same.');
return finish();};
