const fs=require('fs'),path=require('path'),vm=require('vm');
let source=fs.readFileSync(path.join(__dirname,'ml_scene_shots.cjs'),'utf8');source=source.slice(0,source.indexOf('  const manifest = [];')).replace("const OUT = process.argv[2] || '.';","const OUT = path.resolve(process.argv[2] || '.');").replace('deviceScaleFactor: 2','deviceScaleFactor: 1');
source=source.replace("const tool = read('stem_lab/stem_tool_machinelab.js');","const tool = read('stem_lab/stem_tool_machinelab.js').replace('build: buildSimpleMachineScene','build: function(THREE,S,m){buildSimpleMachineScene(THREE,S,m);window.__qaShop=S;}');");
source=source.replace('var ctx = {','window.__qaState = pair[0].machineLab; var ctx = {');
source+=String.raw`
const checks=[],shots=[];let overflow=false;const theme={dark:DARK||CONTRAST,contrast:CONTRAST,band:BAND};const bay=pg.locator('.ml-shop-bay');const panel=pg.locator('.ml-station-comparison');
async function mount(kind,width,extra={}){await pg.setViewportSize({width,height:1000});await pg.evaluate(([s,o])=>window.__mount(s,o),[S({view:'machines',bench:kind,shopMotionProgress:0.5,...extra}),theme]);await bay.scrollIntoViewIfNeeded();await pg.waitForFunction(kind=>window.__qaShop?.mlDemo?.kind===kind,kind);}
async function open(){await panel.locator('summary').focus();await pg.keyboard.press('Enter');}
async function check(label){const r=await panel.evaluate(el=>{const state=window.__qaState,saved=state.benchReferences[state.bench],M=window.__mlMath(),id=state.bench;function ma(d){return id==='lever'?M.leverMA(d.leverEffortArm,d.leverLoadArm):id==='pulley'?M.pulleyMA(d.pulleySegments):id==='windlass'?M.windlassMA(d.windlassHandleR,d.windlassDrumR):id==='ramp'?M.rampMA(d.rampLength,d.rampHeight):id==='wedge'?M.wedgeMA(d.wedgeLength,d.wedgeThickness):M.screwMA(d.screwHandleR,d.screwPitch);}const issues=[];for(const metric of el.querySelectorAll('[data-ml-reference-metric]')){const expected=[saved,state].map(d=>metric.dataset.mlReferenceMetric==='force'?M.effortForce(d[id+'Load'],ma(d)):M.effortDistance(d.loadDistance,ma(d)));const values=[...metric.querySelectorAll('[data-ml-reference-value]')].map(x=>Number(x.dataset.value));if(values.some((v,i)=>Math.abs(v-expected[i])>1e-8))issues.push('Wrong values '+values+' vs '+expected);const direction=Math.abs(expected[1]-expected[0])<=1e-9*Math.max(1,Math.abs(expected[0]))?'same':expected[1]<expected[0]?'less':'more';if(metric.querySelector('[data-ml-reference-direction]').dataset.mlReferenceDirection!==direction)issues.push('Direction mismatch');const bars=[...metric.querySelectorAll('[data-ml-reference-bar]')];for(let i=0;i<2;i++){if(Math.abs(parseFloat(bars[i].style.width)-100*expected[i]/Math.max(...expected))>1e-4)issues.push('Bar scale');if(getComputedStyle(bars[i]).borderTopStyle!==(i===0?'dashed':'solid'))issues.push('Bar style');}}for(const control of document.querySelectorAll('.ml-station-control')){const input=control.querySelector('input'),key=input.id.slice(3),value=saved[key],marker=control.querySelector('[data-ml-saved-marker]'),description=control.querySelector('[data-ml-setting-reference]');if(!marker||!description){issues.push('Missing reference '+key);continue;}const r=input.getBoundingClientRect(),m=marker.getBoundingClientRect(),fraction=(value-Number(input.min))/(Number(input.max)-Number(input.min));if(Math.abs(m.left+m.width/2-(r.left+12+(r.width-24)*fraction))>1)issues.push('Marker alignment '+key);if(Math.abs(Number(marker.dataset.referenceFill)-fraction*100)>1e-7)issues.push('Marker value '+key);if(control.dataset.mlSettingChanged!==String(state[key]!==value))issues.push('Change status '+key);if(input.getAttribute('aria-describedby')!==description.id||marker.getAttribute('aria-hidden')!=='true'||marker.getAttribute('focusable')!=='false')issues.push('Reference semantics '+key);}
const changedKeys=Object.keys(saved).filter(key=>saved[key]!==state[key]);if(Number(el.querySelector('[data-ml-reference-count]').dataset.mlReferenceCount)!==changedKeys.length)issues.push('Change count');const jumps=[...el.querySelectorAll('[data-ml-adjust-setting]')];if(jumps.length!==changedKeys.length)issues.push('Jump count');for(const jump of jumps){const key=jump.dataset.mlAdjustSetting;if(!changedKeys.includes(key)||jump.getAttribute('aria-controls')!=='ml-'+key||!document.getElementById(jump.getAttribute('aria-describedby'))||jump.getBoundingClientRect().height<44)issues.push('Jump semantics/target '+key);}
return {issues,overflow:document.documentElement.scrollWidth>innerWidth,pose:state.shopMotionProgress};});if(r.issues.length||r.overflow||r.pose!==0.5)errors.push(label+': '+JSON.stringify(r));overflow=overflow||r.overflow;checks.push(label);}
try{
 for(const width of [1150,390,320])for(const kind of ['lever','pulley','windlass','ramp','wedge','screw']){
  await mount(kind,width);if(await panel.getAttribute('open')!==null)errors.push('Not collapsed');await open();if(await panel.locator('[data-ml-reference-metric]').count())errors.push('Unexpected initial reference');if(await pg.locator('[data-ml-saved-marker]').count())errors.push('Unexpected initial slider markers');
  const before=await pg.evaluate(()=>JSON.stringify(window.__qaState));await panel.getByRole('button',{name:'Save current setup',exact:true}).focus();await pg.keyboard.press('Enter');
  const snapshot=await pg.evaluate(()=>window.__qaState);const original=JSON.parse(before);const references=snapshot.benchReferences;delete snapshot.benchReferences;if(JSON.stringify(snapshot)!==before)errors.push('Saving mutated current setup');if(!references[kind]||references[kind].loadDistance!==original.loadDistance)errors.push('Bad snapshot');await check('Save '+kind+'/'+width);if(!await panel.getByRole('button',{name:'Restore saved setup',exact:true}).isDisabled())errors.push('Unchanged restore enabled');
  const slider=pg.locator('.ml-station-range').first();await slider.focus();await pg.keyboard.press('ArrowRight');await check('Change '+kind+'/'+width);if(await panel.locator('[data-ml-reference-changes] li').count()!==1)errors.push('Change list');
  const countBadge=panel.locator('[data-ml-reference-count]');await panel.locator('summary').focus();await pg.keyboard.press('Space');if(!await countBadge.isVisible())errors.push('Collapsed count hidden');await pg.keyboard.press('Enter');const jump=panel.locator('[data-ml-adjust-setting]').first();const target=await jump.getAttribute('aria-controls');const beforeJump=await pg.evaluate(()=>JSON.stringify(window.__qaState));await jump.focus();await pg.keyboard.press('Enter');await pg.waitForFunction(id=>document.activeElement?.id===id,target);if(await pg.evaluate(()=>JSON.stringify(window.__qaState))!==beforeJump)errors.push('Navigation mutated state');const visible=await pg.locator('#'+target).evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&getComputedStyle(el).outlineStyle==='solid';});if(!visible)errors.push('Target not visible/focused');checks.push('Collapsed count and keyboard jump '+kind+'/'+width);

  if(width===1150||kind==='lever'||kind==='screw'){const name='comparison-'+kind+'-'+width;await panel.locator('..').screenshot({path:path.join(OUT,name+'.png')});shots.push(name);}
  const beforeRestore=await pg.evaluate(()=>window.__qaState);const savedSetup=beforeRestore.benchReferences[kind];const firstInput=await slider.getAttribute('id');await panel.getByRole('button',{name:'Restore saved setup',exact:true}).focus();await pg.keyboard.press('Enter');await pg.waitForFunction(id=>document.activeElement?.id===id,firstInput);const afterRestore=await pg.evaluate(()=>window.__qaState);for(const key of Object.keys(savedSetup))if(afterRestore[key]!==savedSetup[key])errors.push('Restore setting '+kind+'/'+key);for(const key of Object.keys(beforeRestore))if(!(key in savedSetup)&&key!=='benchResult'&&key!=='glTick'&&JSON.stringify(beforeRestore[key])!==JSON.stringify(afterRestore[key]))errors.push('Unrelated state changed '+key);if(afterRestore.benchResult!==null)errors.push('Stale proof after restore');if(!await panel.getByRole('button',{name:'Restore saved setup',exact:true}).isDisabled())errors.push('Restored button enabled');await check('Restore and slider focus '+kind+'/'+width);await pg.keyboard.press('ArrowRight');await check('New experiment after restore '+kind+'/'+width);
  await panel.getByRole('button',{name:'Replace saved setup',exact:true}).click();await check('Replace '+kind+'/'+width);if(await panel.locator('[data-ml-reference-changes]').count())errors.push('Replace kept old change');
  await panel.getByRole('button',{name:'Clear comparison',exact:true}).focus();await pg.keyboard.press('Enter');await pg.waitForFunction(()=>document.activeElement?.hasAttribute('data-ml-save-reference'));if(await panel.locator('[data-ml-reference-metric]').count())errors.push('Clear kept metrics');if(await pg.locator('[data-ml-saved-marker], [data-ml-setting-reference], .ml-station-range[aria-describedby]').count())errors.push('Clear kept slider references');if(await panel.locator('[data-ml-reference-count]').count())errors.push('Clear kept count');checks.push('Clear and focus '+kind+'/'+width);
 }
 await mount('lever',390);await open();await panel.getByRole('button',{name:'Save current setup',exact:true}).click();await pg.locator('#ml-leverEffortArm').fill('4');await check('Lever double arm halves force and doubles travel');const lever=await pg.evaluate(()=>JSON.stringify(window.__qaState.benchReferences.lever));
 await pg.locator('#ml-bench-tab-pulley').click();await bay.scrollIntoViewIfNeeded();await pg.waitForFunction(()=>window.__qaShop.mlDemo.kind==='pulley');await open();if(await panel.locator('[data-ml-reference-metric]').count())errors.push('Reference leaked to pulley');await panel.getByRole('button',{name:'Save current setup',exact:true}).click();await pg.locator('#ml-bench-tab-lever').click();await bay.scrollIntoViewIfNeeded();await pg.waitForFunction(()=>window.__qaShop.mlDemo.kind==='lever');await open();if(await pg.evaluate(()=>JSON.stringify(window.__qaState.benchReferences.lever))!==lever)errors.push('Reference lost');checks.push('Independent references survive station switching');
 await mount('lever',320,{benchReferences:{lever:{leverEffortArm:0}}});await open();if(await panel.locator('[data-ml-reference-metric]').count())errors.push('Invalid snapshot accepted');checks.push('Malformed saved setup ignored');
 await mount('ramp',320,{rampLength:0.5,rampHeight:4});await open();if(!await panel.getByRole('button',{name:'Save current setup',exact:true}).isDisabled())errors.push('Invalid setup saved');checks.push('Invalid machine cannot be saved');
 for(const band of ['k2','g35','g912']){await mount('lever',320,{bandOverride:band});if(await panel.count()!==(band==='g912'?1:0))errors.push('Reading level '+band);checks.push('Reading level '+band);}
 const reference={leverEffortArm:2,leverLoadArm:1,leverLoad:400,loadDistance:0.5};
 await mount('lever',320,{leverEffortArm:4,leverLoadArm:2,leverLoad:800,loadDistance:1,shopRotY:72,shopRotX:32,shopZoom:1.38,benchResult:{ok:true,message:'Existing result'},benchReferences:{lever:reference,pulley:{pulleySegments:2,pulleyLoad:400,loadDistance:0.5}}});await open();const jumpState=await pg.evaluate(()=>JSON.stringify(window.__qaState));for(const key of ['leverEffortArm','leverLoadArm','leverLoad','loadDistance']){const button=panel.locator('[data-ml-adjust-setting='+key+']');await button.focus();await pg.keyboard.press('Enter');await pg.waitForFunction(key=>document.activeElement?.id==='ml-'+key,key);}if(await pg.evaluate(()=>JSON.stringify(window.__qaState))!==jumpState)errors.push('Multi-change navigation altered state');checks.push('All four changed rows target their own slider');await panel.screenshot({path:path.join(OUT,'changes-multiple-320.png')});shots.push('changes-multiple-320');await panel.getByRole('button',{name:'Restore saved setup',exact:true}).click();await bay.scrollIntoViewIfNeeded();await pg.waitForFunction(()=>window.__qaShop.data.params.effortArm===2&&window.__qaShop.data.params.loadArm===1);const restored=await pg.evaluate(()=>window.__qaState);if(restored.benchResult!==null||restored.shopRotY!==72||restored.shopRotX!==32||restored.shopZoom!==1.38||restored.shopMotionProgress!==0.5||restored.leverLoad!==400||restored.loadDistance!==0.5||!restored.benchReferences.pulley)errors.push('Multi-setting restore isolation');await check('Restore all parameters while preserving camera, pose and other reference');
 await mount('lever',320,{benchReferences:{lever:{...reference,leverEffortArm:400}}});await open();if(await panel.getByRole('button',{name:'Restore saved setup',exact:true}).count())errors.push('Out-of-range restore offered');checks.push('Out-of-range saved setup rejected');
 await mount('ramp',320,{rampLength:0.5,rampHeight:4,benchReferences:{ramp:{rampLength:4,rampHeight:1,rampLoad:400,loadDistance:0.5}}});await open();if(!await panel.getByRole('button',{name:'Save current setup',exact:true}).count()&&await panel.getByRole('button',{name:'Replace saved setup',exact:true}).isEnabled())errors.push('Invalid setup can replace reference');await panel.getByRole('button',{name:'Restore saved setup',exact:true}).click();await check('Restore valid setup from invalid ramp geometry');
 for(const effortArm of [0.2,4]){await mount('lever',320,{benchReferences:{lever:{leverEffortArm:effortArm,leverLoadArm:1,leverLoad:400,loadDistance:0.5}}});await open();await check('Saved marker at range endpoint '+effortArm);}
 for(const band of ['k2','g35']){await mount('lever',320,{bandOverride:band,benchReferences:{lever:reference}});if(await pg.locator('[data-ml-saved-marker]').count())errors.push('Younger band marker leak');checks.push('Saved markers hidden at '+band);}
 await mount('lever',320,{benchReferences:{lever:{...reference,leverLoad:99999}}});await open();if(await pg.locator('[data-ml-saved-marker]').count())errors.push('Malformed reference markers');checks.push('Invalid saved setup has no markers');
 await pg.emulateMedia({forcedColors:'active'});await mount('lever',320);await open();await panel.getByRole('button',{name:'Save current setup',exact:true}).click();await pg.locator('#ml-leverEffortArm').fill('4');await check('System high contrast');await panel.locator('..').screenshot({path:path.join(OUT,'comparison-forced-colors.png')});shots.push('comparison-forced-colors');
 fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify({errors,overflow,checks,shots},null,2));if(errors.length||overflow)process.exitCode=1;
}finally{await b.close();}
})();`;vm.runInThisContext('(function(require){'+source+'\n})',{filename:__filename})(require);
