const fs=require('fs'),{chromium}=require('playwright'),dir='allopacks/media/day_night_sky_grade1/';fs.mkdirSync(dir,{recursive:true});if(fs.existsSync(dir+'manifest.json'))throw Error('Existing manifest');
const style='Use case: scientific-educational. Square Grade 1 educational CUT-PAPER COLLAGE. Hand-cut colored paper shapes, visible fine paper fibers, gently irregular cut edges, shallow layered paper shadows, restrained composition. Not a cartoon drawing, not photorealistic, not a 3D render. No outlines, no faces, no people, no text, letters, numerals, logos, watermark or labels. Astronomical objects are round, never five-point shapes. ';
const sources=[
['sun','A single round golden-yellow Sun disk made of layered yellow and amber paper on deep indigo paper background. A few short paper ray strips may suggest light, not solid spikes. No planets or flames.'],
['stars','A dark indigo paper sky with scattered tiny circular ivory light dots of varied small apparent sizes. Stars are distant points of light, no five-point stars, no falling streaks. Minimal layered low hill silhouette at the bottom.'],
['moon','One round pale gray Moon disk with a few irregular darker gray paper patches suggesting surface terrain, on deep indigo paper. No self-luminous halo, no emitted rays, no faces. Whole disk visible; no invented planet rings.'],
['earth','A round blue Earth disk with simplified green land shapes and white polar paper patches, on cream paper. Suggest recognizable broad land shapes but no borders or labels. No Sun or Moon.'],
['top','One simple wooden-style spinning top represented in layered colored paper, balanced upright on its tip. A curved paper motion strip around it suggests turning in place. No hands, numbers or letters.'],
['day','A quiet landscape of one small cream house with a red roof, rounded green tree to its left, and low green hills. Broad bright blue paper sky above, one small round yellow Sun high to the right. No Moon and no visible stars. Composition is about the bright sky.'],
['night','A quiet landscape of one small cream house with a red roof, rounded tree to its left, low dark hills. Broad dark indigo paper sky with tiny round ivory star dots. No Moon is necessary, no Sun, no lit windows. Composition is about the dark sky.'],
['daymoon','A pale white half-Moon high in a bright blue paper sky above low green hills. The full round outline is subtly present but only its right half is bright. No Sun shown, no stars, no clouds resembling the Moon. The illuminated shape is half of a round rocky body.']
];
const rect=(x,y,w,h,c)=>'<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" fill="'+c+'"/>';
const circle=(x,y,r,c)=>'<circle cx="'+x+'" cy="'+y+'" r="'+r+'" fill="'+c+'"/>';
const arrow=(x,y,x2,y2)=>'<path d="M'+x+' '+y+'L'+x2+' '+y2+'" stroke="#d5a740" stroke-width="9" marker-end="url(#tip)" fill="none"/>';
const wrap=s=>'<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000" viewBox="0 0 1000 1000"><defs><marker id="tip" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="3" markerHeight="3" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#d5a740"/></marker></defs>'+rect(0,0,1000,1000,'#f8f0df')+s+'</svg>';
const lit=(x,y,r)=>circle(x,y,r,'#28344e')+'<path d="M'+x+' '+(y-r)+'A'+r+' '+r+' 0 0 0 '+x+' '+(y+r)+'Z" fill="#87c5cf"/>';
const turn=circle(135,500,80,'#edbf50')+arrow(245,360,470,360)+arrow(245,500,430,500)+arrow(245,640,470,640)+lit(680,500,220)+'<path d="M850 710A270 270 0 1 1 850 290" stroke="#528b78" stroke-width="13" fill="none"/><path d="M830 255L870 302L810 305Z" fill="#528b78"/>';
const reflect=circle(140,250,80,'#edbf50')+lit(760,400,125)+arrow(235,275,625,370)+arrow(645,445,370,735)+circle(260,810,95,'#80bccc')+'<path d="M220 750L280 745L310 790L275 845L215 810Z" fill="#739c71"/>';
function horizon(rising){let s='';const ys=rising?[705,650,590]:[590,650,705];for(let i=0;i<3;i++){const x=55+i*315;s+=rect(x,250,280,500,['#d6dfdd','#c3d7df','#acd2e4'][i])+circle(x+140,ys[i],44,'#efbd58')+rect(x,685,280,65,'#709476');}return s;}
function pattern(){let s='';for(let i=0;i<4;i++){const x=70+i*230,c=i%2?'#25354d':'#91c8e2';s+=rect(x,300,205,340,c)+rect(x,585,205,55,i%2?'#3c5350':'#76a377');if(i%2){for(const [dx,dy] of [[45,55],[95,100],[150,65]])s+=circle(x+dx,300+dy,5,'#f3efdc');}else s+=circle(x+140,370,27,'#f0c663');}return s;}
function shadows(){let s='';for(let i=0;i<3;i++){const x=60+i*315;s+=rect(x,230,280,520,'#e6d8be');const bx=x+140,by=600,ex=bx+[-115,35,115][i],ey=by+[80,35,-40][i];s+='<path d="M'+(bx-7)+' '+by+'L'+(ex-8)+' '+ey+'L'+(ex+8)+' '+(ey+10)+'L'+(bx+7)+' '+by+'Z" fill="#697776"/>'+rect(bx-7,395,14,205,'#795d48')+circle(bx,by,13,'#9b7950');}return s;}
const diagrams={turn,reflect,sunrise:horizon(true),sunset:horizon(false),pattern:pattern(),shadows:shadows()};
const m={slug:'day_night_sky_grade1',prefix:'dn',status:'in-progress',provider:'Built-in image generation and deterministic SVG diagrams',style:'Layered cut-paper collage with simple paper-color science diagrams',groups:['Earth turns','Patterns we observe','Sunlight and moonlight','Watch and record'],lessonTitles:['The lit half and the dark half','A repeating sky pattern','Sunrise sequence','Sunset sequence','Light reaches the Moon','The Moon in a blue sky','A shadow can change','Stars in a dark sky'],note:'Paper collage pictures are illustrative, not scale drawings or exact maps. Diagram arrows show light paths or turning; they are not solid beams or orbital paths. The Sun stays fixed only in this simplified daily-rotation model, not absolutely still in space. Left-to-right horizon panels represent apparent sky motion as Earth turns. Stars remain in space during daytime; they are usually hidden by bright sky. A Moon picture does not imply it is visible every night. Shadow panels show possible changes, not a guaranteed direction or length. Never look directly at the Sun.',sources:sources.map(([key,scene])=>({key,prompt:style+scene,status:'pending'})),assets:[]};
const descriptions={
turn:'Light arrows approach a round planet from a golden disk on the left; the planet has a lit left half, a dark right half and a curved turning arrow.',
reflect:'Arrows lead from a golden disk to the lit side of a gray-blue round body, then toward a smaller blue-green planet.',
sunrise:'Three horizon panels show a golden disk mostly below the ground edge, then partly above it, then fully above it.',
sunset:'Three horizon panels show a golden disk above the ground edge, then partly hidden, then mostly below it.',
pattern:'Four landscape panels alternate bright blue sky with a golden disk and dark sky with small light dots.',
shadows:'Three panels show the same upright stick and base position with shadows of different lengths and directions.'
};
function add(kind,key,caption){const index=m.assets.filter(a=>a.kind===kind).length,id='dn-'+kind+'-'+(index+1);const a={id,kind,index,sourceKey:key,caption,prompt:diagrams[key]?'Exact diagram specification: '+descriptions[key]:m.sources.find(s=>s.key===key).prompt,status:'pending',method:diagrams[key]?'deterministic-svg':'built-in-imagegen'};if(diagrams[key]){a.vectorFile=id+'.svg';a.file=id+'-diagram.png';a.alt=descriptions[key];a.status='diagram-review-pending';fs.writeFileSync(dir+a.vectorFile,wrap(diagrams[key]));}m.assets.push(a);}
['sun','stars','moon','earth','top','day','night','sunrise','sunset','pattern'].forEach((key,i)=>add('term',key,['Our nearest star gives Earth light and warmth.','Distant stars look like points of light.','The Moon is a round rocky body reflecting sunlight.','We live on Earth. This is a simplified paper view.','A top turns in place; it is a model for spinning.','A bright sky is a daytime observation.','A dark sky can reveal distant stars.','Read left to right: the Sun appears above the horizon.','Read left to right: the Sun disappears below the horizon.','Day and night repeat in order in this simple example.'][i]));
['turn','day','night','reflect'].forEach((key,i)=>add('anchor',key,['Earth turns; sunlight reaches the side facing the Sun.','The Sun-facing side has daylight.','The side facing away has night.','The Moon reflects sunlight; it does not produce its own light.'][i]));
const sortKeys=['turn','sun','stars','moon','sun','daymoon','sunrise','stars'];sortKeys.forEach(key=>add('sort',key,'Use the card statement and lesson to decide. The picture is a subject cue, not a true/false answer label.'));
['turn','pattern','sunrise','sunset','reflect','daymoon','shadows','stars'].forEach((key,i)=>add('lesson',key,['The half facing the Sun is lit. Earth turns places toward and away from sunlight; sizes and distances are not to scale.','This simple day-night pattern repeats. Pictures do not claim equal lengths of day and night.','The Sun appears to rise as Earth turns. These are successive views, not three Suns.','The Sun appears to set as Earth turns. Sky color alone cannot tell sunrise from sunset.','Sunlight reaches the Moon and some reflects toward Earth. The Moon is not a lamp; the diagram is not to scale.','The Moon can sometimes be seen during daytime. Its shape and visibility vary.','Keep the object in the same place and record its shadow. These are example observations, not measurements or a universal daily path.','Stars do not fall down or go away each morning. Bright daytime sky usually hides their light.'][i]));
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:1000,height:1000}});for(const a of m.assets.filter(a=>a.vectorFile)){await p.setContent(fs.readFileSync(dir+a.vectorFile,'utf8'));await p.locator('svg').screenshot({path:dir+a.file});}fs.writeFileSync(dir+'manifest.json',JSON.stringify(m,null,2));console.log(JSON.stringify({images:m.assets.length,generatedSources:m.sources.length,diagramSources:Object.keys(diagrams).length}));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
