exports.refine=function(p){const {E,get,replaceAll,finish}=require('./science_refinement_session.cjs').session(p);
replaceAll('The Man Who Was Laughed At','Following the Evidence');
E('reading','data',`## Following the Evidence

In 1912, Alfred Wegener proposed that continents had once been joined and later moved apart. He assembled several kinds of evidence. Some scientists supported continental drift; many objected, especially to his proposed forces and the idea of continents pushing through oceanic rock.

The Atlantic margins of South America and Africa have complementary shapes. Their submerged continental margins fit better than modern shorelines, which erosion and sea-level change can alter. Related fossils, matching rock sequences and mountain belts also occur across the Atlantic. The distribution of Mesosaurus, an aquatic reptile, was more readily explained by connected land than by crossing a wide ocean. Antarctic coal records former vegetation and very different environmental conditions. Coal alone does not prove continental movement; climate can change too. The strength is in several independent lines of evidence agreeing.

New ocean-floor evidence helped transform the debate in the mid-twentieth century. Mapping revealed ridge systems in detail. Oceanic rocks tend to get older away from spreading ridges, and bands recording past magnetic polarity often mirror one another on opposite sides. Together with earthquake patterns and other measurements, these findings supported seafloor spreading and the broader theory of plate tectonics.

A tectonic plate is a slab of lithosphere: crust plus rigid uppermost mantle. Plates can carry both continents and ocean floor. They move over warmer, mostly solid mantle that deforms slowly over long times. They do not float on a global ocean of liquid magma. Gravity acting on sinking slabs and elevated lithosphere, together with mantle motion, contributes to plate movement; the balance varies.

At divergent boundaries, plates move apart. Along ocean ridges, rising mantle partly melts and magma forms new oceanic crust. Iceland lies on the Mid-Atlantic Ridge, and the East African Rift shows continental extension.

At convergent boundaries, plates move toward one another. Dense oceanic lithosphere can descend beneath another plate at a subduction zone, producing a trench and often a volcanic belt. The Andes are an example. Where continental lithosphere collides, crust can shorten and thicken, helping build mountains such as the Himalayas.

At transform boundaries, plates slide past. Locked fault patches store elastic stress and may suddenly slip, producing earthquakes. Other patches creep. Earthquakes also occur at other boundaries and within plates.

Rates vary, but a few centimeters per year is common. Small annual movements become large changes over millions of years. Wegener died in 1930, decades before plate tectonics became widely accepted in the 1960s. His proposal was an important precursor, not the complete modern theory. Science can recognize strong evidence before every mechanism is known; new tests help distinguish competing explanations.`);
E('reading','meta','6th Grade • Evidence, boundaries and model limits');
E('directions','data.body',get('directions').data.body.replace('A scientist noticed that South America and Africa look like puzzle pieces. Everyone laughed at him for fifty years. He was right — but for a reason he never figured out.','How can fossils, rock ages and seafloor patterns reveal moving continents? Compare several kinds of evidence and ask what each can establish.').replace('The real lesson here is not about rocks. It is about how science changes its mind when the evidence finally forces it.','Use rocks and patterns to compare explanations. New evidence can change scientific understanding.'));
E('glossary','data.0.def','A moving slab of lithosphere: crust plus rigid uppermost mantle, which may include continental and oceanic regions.');E('glossary','data.2.def','The mostly solid rocky layer below the crust; warmer parts deform slowly over long times.');
E('anchor','data.sections.2.bullets.0','Locked patches store stress and may suddenly slip; others creep');E('anchor','data.sections.2.bullets.2','Sudden slip releases seismic waves; earthquakes also occur at other boundaries');E('anchor','data.sections.4.label','EVIDENCE AND A BETTER MODEL');E('anchor','data.sections.4.bullets.0','Continental margins, fossils, rocks and ancient-climate clues support past connections');E('anchor','data.sections.4.bullets.1','Many scientists rejected Wegener’s proposed forces; some supported drift');E('anchor','data.sections.4.bullets.2','Seafloor ages, magnetic bands and earthquake patterns helped establish plate tectonics');
E('memory','data.cards.0.essentialFacts.0','Continental margins: South America and Africa have complementary shapes; submerged margins fit better than modern shorelines.');E('memory','data.cards.0.essentialFacts.1','Related Mesosaurus fossils on both continents support a past connection rather than a crossing of a wide ocean.');E('memory','data.cards.0.essentialFacts.3','Antarctic coal records former vegetation and different environmental conditions; climate clues alone do not prove drift.');E('memory','data.cards.0.hookFact.text','Antarctic coal is evidence of past vegetation. Combine climate clues with fossils, rock sequences and seafloor data when testing plate movement.');E('memory','data.cards.0.reasoningPrompt','Explain what each evidence type supports and what it cannot establish alone.');
E('memory','data.cards.1.essentialFacts.2','Transform boundaries involve sideways motion; locked patches can store stress then slip in earthquakes, while others creep.');
E('memory','data.cards.2.target','How new ocean-floor evidence helped establish plate tectonics');E('memory','data.cards.2.essentialFacts.0','Many geologists objected to Wegener’s proposed forces and mechanism; some supported continental drift.');E('memory','data.cards.2.essentialFacts.1','Postwar mapping revealed ridge systems in greater detail; seafloor spreading explains new crust forming at ridges.');E('memory','data.cards.2.essentialFacts.3','Continents and ocean floor can be parts of the same moving lithospheric plate.');E('memory','data.cards.2.aiExample','Continental clues → disputed drift model → seafloor ages and magnetic bands → spreading and subduction → a broader plate-tectonics theory.');E('memory','data.cards.2.hookFact.text','Evidence can strongly support a pattern before its mechanism is fully understood. Plate tectonics grew from many observations and testable explanations.');E('memory','data.cards.2.mapping','The chain connects independent observations with a broader model; one discovery did not settle every question about driving forces.');E('memory','data.cards.2.coachPrompts.0','Which links are observations and which are proposed processes?');E('memory','data.sourceExcerpt','Continental margins, fossils, matching rocks and climate clues support former connections. Seafloor ages and magnetic bands support spreading. Lithospheric plates include crust and rigid uppermost mantle. Different boundary motions produce different landforms.');
E('quiz','data.questions.0.question','What was a major reason many geologists rejected Wegener’s drift model?');const fossil='Their distribution is more readily explained by a former connection than a wide-ocean crossing';E('quiz','data.questions.1.options.3',fossil);E('quiz','data.questions.1.correctAnswer',fossil);E('quiz','data.questions.3.question','Which later discovery helped explain how ocean floor and continents could move as parts of plates?');E('quiz','data.questions.5.question','Antarctic coal records former vegetation. What does this support, and why is coal alone not enough to prove continental drift?');E('quiz','data.questions.5.expectedAnswer','Coal supports past vegetation and environmental conditions different from today. Climate can change without plate motion, so coal alone does not prove drift. Combine it with independent fossil, rock and seafloor evidence.');E('quiz','data.questions.6.question','How did later evidence strengthen and change Wegener’s proposal? Can evidence matter before a mechanism is fully understood?');E('quiz','data.questions.6.expectedAnswer','Seafloor ages, magnetic bands and earthquake patterns supported spreading, subduction and moving lithospheric plates. This differed from continents plowing through ocean floor. Strong evidence can matter before a mechanism is fully known; scientists still compare alternatives and test explanations.');
E('faq','data.0.answer','Another supercontinent may form over hundreds of millions of years. Several scenarios are modeled, but its shape, timing and location are uncertain.');E('faq','data.4.answer','The Pacific margin has many volcanoes and earthquake zones. Subduction accounts for many volcanic belts, but not every boundary around the Pacific is convergent.');E('timeline','data.items.2.event','Many scientists reject Wegener’s proposed mechanism, while some support continental drift.');E('timeline','data.items.3.event','Wegener dies during a Greenland expedition; continental drift remains disputed.');E('timeline','data.items.4.event','Postwar ocean mapping reveals ridge and trench systems in increasing detail.');
E('challenge','data.instructions','Build an evidence-based case for a former continental connection, then compare it with seafloor ages and the plate-motion model. Mark observations, interpretations and uncertainty separately.');E('challenge','data.brief.lockedLessonFacts.1','Many scientists rejected Wegener’s proposed forces; later seafloor and earthquake evidence supported the broader plate model.');E('challenge','data.brief.context','Your class has maps of plate boundaries, fossils, rocks and ocean-floor ages. At spreading ridges the youngest crust is near the axis and ages generally increase outward; subduction recycles older oceanic lithosphere.');E('challenge','data.brief.seedDirection','Start with margin shapes, then test the proposed connection against independent fossil, rock and seafloor evidence.');E('challenge','data.supports.parallelExample.move','A student compares Red Sea margin shapes with published ridge, seafloor-age and plate-motion data. She records sources and uncertainty, then checks whether the data support opening between Africa and Arabia.');E('challenge','data.supports.parallelExample.whyItHelps','An explanation should agree with several observations. A ridge pattern supports spreading but does not by itself reveal every force moving the plates.');return finish();};
