'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),pack=JSON.parse(fs.readFileSync(path.join(root,'allopacks/illustrated/body_systems_grade6.allopack.json'),'utf8'));
async function main(){const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1100,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://alloflow-qa.test/',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><main id="memory"></main><main id="challenge"></main></body></html>'}));await page.goto('https://alloflow-qa.test/');for(const file of ['desktop/web-app/node_modules/react/umd/react.development.js','desktop/web-app/node_modules/react-dom/umd/react-dom.development.js','memory_aid_module.js','applied_challenge_module.js','doc_pipeline_module.js'])await page.addScriptTag({path:path.join(root,file)});await page.context().setOffline(true);
await page.evaluate(p=>{const noop=()=>{},t=(k,f)=>typeof f==='string'?f:k,deny=()=>{throw Error('Unexpected model call');};for(const[type,id,name]of [['memory-aid','memory','MemoryAidView'],['applied-challenge','challenge','AppliedChallengeView']])ReactDOM.createRoot(document.getElementById(id)).render(React.createElement(window.AlloModules[name],{generatedContent:p.history.find(r=>r.type===type),isTeacherMode:false,isProcessing:false,handleNoteUpdate:noop,callGemini:deny,callImagen:deny,addToast:noop,gradeLevel:'6th Grade',t,allowRuntimeAi:false,previewMode:true}));},pack);
await page.waitForFunction(()=>document.querySelector('#memory').innerText.length>200&&document.querySelector('#challenge').innerText.length>200,{},{timeout:10000}).catch(async e=>{console.error(JSON.stringify({errors,body:await page.locator('body').innerText()}));throw e;});
const dir=path.join(root,'scratch/body-systems-quality');fs.mkdirSync(dir,{recursive:true});
await page.locator('#challenge summary').filter({hasText:'Lesson ideas and requirements'}).click();await page.locator('#challenge summary').filter({hasText:'Limits and unknowns'}).click();
const views=await page.evaluate(()=>({memory:document.querySelector('#memory').innerText,challenge:document.querySelector('#challenge').innerText}));fs.writeFileSync(path.join(dir,'native-text.json'),JSON.stringify(views,null,2));assert(views.memory.includes('Remember the Relay Team'));assert(views.challenge.includes('What Changes When You Move?'));assert(!JSON.stringify(views).includes('[object Object]'));assert(views.challenge.includes('Case A: rest 4 / 18'));assert(views.challenge.includes('Case C: rest 4 / 20'));assert(views.challenge.includes('no exercise or personal measurements'));assert(!views.challenge.includes('At least three volunteers'));await page.screenshot({path:path.join(dir,'activities-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(dir,'activities-mobile.png'),fullPage:true});
const exports=await page.evaluate(p=>{const deny=()=>{throw Error('Unexpected model call');};const pipe=window.AlloModules.createDocPipeline({callGemini:deny,callGeminiVision:deny,callImagen:deny,addToast:()=>{},t:k=>k,isRtlLang:()=>false,updateExportPreview:()=>{},getDefaultTitle:()=>p.allopack.title,state:{}});const items=p.history.filter(r=>['memory-aid','applied-challenge','quiz'].includes(r.type));return {student:pipe.generateFullPackHTML(items,p.allopack.title,true,{}, {includeTeacherKey:false,annotations:[]}),teacher:pipe.generateFullPackHTML(items,p.allopack.title,true,{}, {includeTeacherKey:true,annotations:[]})};},pack);
for(const[key,html]of Object.entries(exports)){assert(html.includes('What Changes When You Move?'));assert(html.includes('Remember the Relay Team'));assert(!html.includes('[object Object]'));fs.writeFileSync(path.join(dir,key+'.html'),html);await page.setContent(html);assert.equal(await page.locator('body').innerText().then(s=>s.includes('fictional')),true);}
assert.deepEqual(errors,[]);const report={pack:'body_systems_grade6',nativeMemoryAndChallengeRendered:true,desktopAndMobile:true,studentAndTeacherHtmlExported:true,offline:true,modelCalls:0,pageErrors:errors,scope:'Production native activity views and HTML export; not signed-in live-library publication or full app interaction.'};fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}finally{await browser.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
