const fs=require('fs'),{chromium}=require('playwright'),dir='allopacks/media/probability_models_grade7/',f=dir+'manifest.json',m=JSON.parse(fs.readFileSync(f));
if(m.revision===2)throw Error('Revision already exists');
fs.writeFileSync(dir+'manifest-v1.json',JSON.stringify(m,null,2));
const C={blue:'#2465b4',red:'#d64640'};
const rect=(x,y,w,h,fill='#fff')=>'<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="18" fill="'+fill+'" stroke="#203849" stroke-width="4"/>';
const counter=(x,y,color,r=40)=>'<circle cx="'+x+'" cy="'+y+'" r="'+r+'" fill="'+C[color]+'" stroke="#203849" stroke-width="4" data-counter="'+color+'"/>';
const bag=(x,y,w=240,h=300)=>'<path d="M'+x+' '+y+' Q'+(x+w/2)+' '+(y+35)+' '+(x+w)+' '+y+' L'+(x+w+15)+' '+(y+h-35)+' Q'+(x+w/2)+' '+(y+h+30)+' '+(x-15)+' '+(y+h-35)+' Z" fill="#ead2a9" stroke="#203849" stroke-width="5"/>';
const arrow=(x,y,x2,y2)=>'<path d="M'+x+' '+y+'L'+x2+' '+y2+'" stroke="#203849" stroke-width="7"/><path d="M'+(x2-20)+' '+(y2-15)+'L'+x2+' '+y2+'L'+(x2-20)+' '+(y2+15)+'" fill="none" stroke="#203849" stroke-width="7"/>';
const wrap=s=>'<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000" viewBox="0 0 1000 1000"><rect width="1000" height="1000" fill="#fffaf0"/>'+s+'</svg>';
const row=(colors,y,start=200,gap=150,r=40)=>colors.map((c,i)=>counter(start+i*gap,y,c,r)).join('');
const record=['blue','red','blue','blue','red','blue','red','blue','blue','red','blue','blue','red','blue','blue','blue','red','blue','red','blue'];
const specs=[
['prb-term-3',bag(100,320)+arrow(390,480,550,480)+counter(690,480,'red',65),'A tan bag leads by an arrow to one red counter, representing a single selected result.','One draw produces one result. The red counter is one possible example, not a promised result.','One opaque bag leads to exactly one sampled red counter.'],
['prb-term-6',bag(330,330)+'<path d="M280 380 Q190 500 280 630 M720 380 Q810 500 720 630 M250 350 Q110 500 250 660 M750 350 Q890 500 750 660" stroke="#203849" stroke-width="8" fill="none"/>','Curved motion strokes surround an opaque tan bag whose contents are hidden.','Mix, then select without looking. Shaking alone does not prove equal selection chances.','An opaque bag with curved mixing motion strokes; no visible counters or people.'],
['prb-lesson-1',rect(70,170,370,630)+rect(560,170,370,630)+bag(140,300,220,330)+row(['blue','blue','blue','red'],320,620,80,30)+arrow(710,420,830,420)+counter(740,620,'blue',52),'An opaque bag appears in one panel. The other shows four possible counters above one example blue result.','Use an opaque bag and draw without looking. The separate diagram reveals the model: three blue counters and one red; one blue draw is only an example.','Opaque bag beside a separate model panel with exactly three blue and one red counter and one example blue result.'],
['prb-lesson-5',rect(80,240,840,390)+row(['blue','red','blue','blue','red','blue'],440,150,140,44),'Six outlined record spaces each contain one result: blue, red, blue, blue, red and blue.','Record every trial in order. This six-trial example contains two red results; do not omit unexpected outcomes.','Six successive record slots each holding one colored result.'],
['prb-lesson-8',rect(90,90,820,200)+row(['blue','blue','blue','red'],190,245,170,44)+rect(90,390,820,510)+record.map((c,i)=>counter(210+(i%5)*145,480+Math.floor(i/5)*105,c,32)).join(''),'A four-counter model with one red sits above a twenty-result record containing seven red results.','Compare model probability 1/4 with this sample frequency 7/20. A mismatch needs investigation; a larger sample need not match better every time.','One-red-in-four model above an example record of seven red and thirteen blue results.']
];
specs[3][1]+=Array.from({length:6},(_,i)=>rect(95+i*140,345,110,190,'none')).join('');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:1000,height:1000}});for(const [id,body,alt,caption,prompt] of specs){const a=m.assets.find(a=>a.id===id);a.previousIllustration={file:a.file,sourcePath:a.sourcePath,prompt:a.prompt};delete a.sourcePath;Object.assign(a,{file:id+'-concept-v2.png',vectorFile:id+'-concept-v2.svg',method:'deterministic-svg',prompt:'Exact diagram specification: '+prompt,caption,alt,status:'diagram-review-pending'});fs.writeFileSync(dir+a.vectorFile,wrap(body));await p.setContent(wrap(body));await p.locator('svg').screenshot({path:dir+a.file});}
await p.setViewportSize({width:1500,height:1100});await p.setContent('<body style="margin:0;display:flex;flex-wrap:wrap">'+specs.map(([id])=>{const a=m.assets.find(a=>a.id===id);return '<div style="width:500px">'+id+'<img width="490" src="data:image/png;base64,'+fs.readFileSync(dir+a.file).toString('base64')+'"></div>';}).join(''));await p.locator('img').evaluateAll(is=>Promise.all(is.map(i=>i.decode())));await p.screenshot({path:'scratch/probability-concept-v2-review.png',fullPage:true});
m.revision=2;m.provider='Deterministic SVG diagrams';m.style='Text-free concept diagrams; no classroom portraits';m.status='review-pending';m.note+=' Arrows show process steps, not a guaranteed color sequence. Record panels show example data, not additional bag contents.';fs.writeFileSync(f,JSON.stringify(m,null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
