const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const repo=process.env.UNIVERSE_REPO||path.resolve(__dirname,'..');
const report=process.env.UNIVERSE_STELLAR_REPORT||path.join(repo,'reports/universe-flight-2026-09-29');
const baselineSource=process.env.UNIVERSE_STELLAR_BASELINE_SOURCE||path.join(report,'stellar-baseline-renderer.js');
const {chromium}=require(path.join(repo,'node_modules/playwright'));
const phase=process.argv[2]||'refined';assert.ok(['baseline','refined'].includes(phase));fs.mkdirSync(report,{recursive:true});
const hash=buffer=>crypto.createHash('sha256').update(buffer).digest('hex');
const source=fs.readFileSync(phase==='baseline'?baselineSource:path.join(repo,'stem_lab/universe_flight_scene.js'),'utf8');
const result={phase,sourceHash:hash(source),completed:false,interceptions:0,checks:[],captures:[],errors:[],graphics:[],stability:[],transition:[],lifecycle:[]};
const save=()=>fs.writeFileSync(path.join(report,'stellar-'+phase+'.json'),JSON.stringify(result,null,2));
function png(buffer){
  let w,h,channels,offset=8;const parts=[];assert.equal(buffer.subarray(1,4).toString(),'PNG');
  while(offset<buffer.length){const n=buffer.readUInt32BE(offset),type=buffer.subarray(offset+4,offset+8).toString(),data=buffer.subarray(offset+8,offset+8+n);offset+=n+12;if(type==='IHDR'){w=data.readUInt32BE(0);h=data.readUInt32BE(4);assert.equal(data[8],8);assert.ok([2,6].includes(data[9]));channels=data[9]===6?4:3;}else if(type==='IDAT')parts.push(data);else if(type==='IEND')break;}
  const raw=zlib.inflateSync(Buffer.concat(parts)),stride=w*channels,pixels=Buffer.alloc(stride*h);const paeth=(a,b,c)=>{const p=a+b-c,aa=Math.abs(p-a),bb=Math.abs(p-b),cc=Math.abs(p-c);return aa<=bb&&aa<=cc?a:bb<=cc?b:c;};
  for(let y=0;y<h;y++)for(let x=0;x<stride;x++){const i=y*stride+x,f=raw[y*(stride+1)],a=x>=channels?pixels[i-channels]:0,b=y?pixels[i-stride]:0,c=y&&x>=channels?pixels[i-stride-channels]:0;assert.ok(f<=4);pixels[i]=(raw[y*(stride+1)+1+x]+(f===0?0:f===1?a:f===2?b:f===3?(a+b)>>1:paeth(a,b,c)))&255;}
  return {w,h,channels,pixels};
}
function imageStats(image){
  let max=0,count=0,sum=0,colored=0,clipped=0,x0=image.w,y0=image.h,x1=-1,y1=-1;
  for(let y=0;y<image.h;y++)for(let x=0;x<image.w;x++){const i=(y*image.w+x)*image.channels,r=image.pixels[i],g=image.pixels[i+1],b=image.pixels[i+2],l=.2126*r+.7152*g+.0722*b;sum+=l;count++;max=Math.max(max,r,g,b);if(Math.max(r,g,b)-Math.min(r,g,b)>8)colored++;if(Math.min(r,g,b)>=250)clipped++;if(l>10){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}}
  return {mean:sum/count,max,colorFraction:colored/count,clippedWhiteFraction:clipped/count,luminousBounds:x1<0?null:{x:x0,y:y0,width:x1-x0+1,height:y1-y0+1}};
}
function cropDifference(a,b,size=80){
  assert.equal(a.w,b.w);assert.equal(a.h,b.h);let sum=0,max=0,count=0,changed=0;
  for(let y=Math.floor(a.h/2-size/2);y<Math.floor(a.h/2+size/2);y++)for(let x=Math.floor(a.w/2-size/2);x<Math.floor(a.w/2+size/2);x++)for(let c=0;c<3;c++){const d=Math.abs(a.pixels[(y*a.w+x)*a.channels+c]-b.pixels[(y*b.w+x)*b.channels+c]);sum+=d;max=Math.max(max,d);count++;if(d>1)changed++;}
  return {meanAbsolute:sum/count,max,changedFraction:changed/count};
}
(async()=>{
  save();const browser=await chromium.launch({args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  try{
    async function createPage(dpr=1,limit=null){
      const page=await browser.newPage({viewport:{width:1280,height:800},deviceScaleFactor:dpr});page.on('pageerror',error=>result.errors.push(String(error)));
      if(phase==='baseline')await page.route(/universe_flight_scene\.js(?:\?.*)?$/,async route=>{result.interceptions++;await route.fulfill({contentType:'application/javascript',body:source});});
      await page.addInitScript(({limit})=>{
        const getContext=HTMLCanvasElement.prototype.getContext;window.__stellarGL=[];window.__stellarScenes=[];window.__stellarOnly=null;
        HTMLCanvasElement.prototype.getContext=function(type,...args){const gl=getContext.call(this,type,...args);if(type!=='webgl'||!gl||gl.__stellarProbe)return gl;gl.__stellarProbe=true;
          const record={created:0,deleted:0,textures:[],indices:{},pointBytes:null};window.__stellarGL.push({gl,record});
          const get=gl.getParameter.bind(gl),data=gl.bufferData.bind(gl),draw=gl.drawArrays.bind(gl),create=gl.createTexture.bind(gl),remove=gl.deleteTexture.bind(gl);
          record.actualRange=Array.from(get(gl.ALIASED_POINT_SIZE_RANGE));gl.getParameter=function(value){return value===gl.ALIASED_POINT_SIZE_RANGE&&limit?new Float32Array([1,limit]):get(value);};
          gl.createTexture=function(){const texture=create();record.created++;record.textures.push(texture);return texture;};gl.deleteTexture=function(texture){if(texture)record.deleted++;return remove(texture);};
          gl.bufferData=function(target,values,...args){if(values instanceof Float32Array&&values.length>9000&&values.length%9===0){const landmarks={amber:[-3.1,1,8.5],blue:[4.3,-2.2,16],pale:[.65,2.4,24]};const indices={};for(let i=0;i<values.length;i+=9)for(const [name,p] of Object.entries(landmarks))if(p.every((v,k)=>Math.abs(values[i+k]-v)<.00001))indices[name]=i/9;if(Object.keys(indices).length===3){record.indices=indices;record.pointBytes=Array.from(new Uint8Array(values.buffer,values.byteOffset,values.byteLength));}}return data(target,values,...args);};
          gl.drawArrays=function(mode,first,count){if(window.__stellarOnly){if(mode!==gl.POINTS)return;const index=record.indices[window.__stellarOnly];if(index===undefined)throw new Error('Landmark point not found');return draw(mode,index,1);}return draw(mode,first,count);};return gl;
        };
        let api;Object.defineProperty(window,'UniverseFlight',{configurable:true,get(){return api;},set(value){const create=value.create;value.create=function(canvas,options){const telemetry=options.onTelemetry,status=options.onStatus;const scene=create.call(this,canvas,Object.assign({},options,{onTelemetry(info){window.__stellarInfo=info;if(telemetry)telemetry(info);},onStatus(info){window.__stellarStatus=info;if(status)status(info);}}));window.__stellarScene=scene;window.__stellarCanvas=canvas;window.__stellarScenes.push(scene);return scene;};api=value;}});
      },{limit});
      await page.goto(process.env.UNIVERSE_STELLAR_URL||'http://127.0.0.1:3187/reports/universe-flight-2026-09-29/preview.html?stellar=qa');await page.waitForFunction(()=>window.__stellarScene&&window.__stellarStatus?.state==='ready');
      if(phase==='baseline')assert.ok(result.interceptions>0,'The preserved baseline renderer was actually intercepted');
      await page.getByRole('button',{name:'Toggle full screen for the 3D view',exact:true}).click();await page.waitForFunction(()=>!!document.fullscreenElement);return page;
    }
    const targets={amber:{id:'amber-star',position:[-3.1,1,8.5],radius:.6,size:.08},blue:{id:'blue-star',position:[4.3,-2.2,16],radius:.8,size:.1},pale:{id:'pale-star',position:[.65,2.4,24],radius:1,size:.1}};
    const next=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    async function pose(page,name,{distance=targets[name].radius,fov=65,exposure=1,quality='auto',only=false,mode='explore',compareRest=false}={}){
      await page.evaluate(({target,distance,fov,exposure,quality,only,name,mode,compareRest})=>{const scene=window.__stellarScene,saved=scene.snapshot();Object.assign(saved.settings,{region:'neighborhood',mode,beta:.99,compareRest,fov,exposure,quality});Object.assign(saved.state,{position:[target.position[0],target.position[1],target.position[2]-distance],yaw:0,pitch:0,distanceLy:0,universeYears:0,travelerYears:0});saved.targetId=target.id;if(!scene.restore(saved))throw new Error('Star pose rejected');scene.set({running:false});window.__stellarOnly=only?name:null;},{target:targets[name],distance,fov,exposure,quality,only,name,mode,compareRest});await next(page);
    }
    async function cssPose(page,size,options={}){const height=await page.evaluate(()=>window.__stellarCanvas.clientHeight),fov=options.fov||65;await pose(page,'amber',{...options,distance:targets.amber.size*height/Math.tan(fov*Math.PI/360)/size,fov,only:true});}
    async function capture(page,name){
      const capture=await page.evaluate(()=>window.__stellarScene.capture());assert.ok(capture?.dataUrl.startsWith('data:image/png;base64,'));const buffer=Buffer.from(capture.dataUrl.split(',')[1],'base64'),image=png(buffer),stats=imageStats(image);assert.ok(stats.max>32,'The source shader renders visible starlight');fs.writeFileSync(path.join(report,'stellar-'+phase+'-'+name+'.png'),buffer);
      const errors=await page.evaluate(()=>window.__stellarGL.map(({gl})=>gl.getError()));assert.ok(errors.every(code=>code===0),'Actual star drawing has no GL errors');result.graphics.push({name,errors});result.captures.push({name,width:image.w,height:image.h,pixelHash:hash(image.pixels),snapshot:capture.snapshot,stats});save();return image;
    }
    const page=await createPage();const points=await page.evaluate(()=>window.__stellarGL.at(-1).record.pointBytes);assert.ok(points?.length>0);result.pointDataHash=hash(Buffer.from(points));
    for(const name of ['amber','blue','pale'])for(const fov of [65,30]){await pose(page,name,{fov});await capture(page,name+(fov===65?'-arrival':'-zoom'));result.checks.push(name+' '+fov+' degree full-world view renders');}
    for(const size of [6,10,40]){await cssPose(page,size);const first=await capture(page,'isolated-css'+size);const frozen=await page.evaluate(()=>window.__stellarScene.snapshot());await page.waitForTimeout(150);const repeated=await page.evaluate(()=>window.__stellarScene.capture());assert.deepEqual(png(Buffer.from(repeated.dataUrl.split(',')[1],'base64')).pixels,first.pixels,'Paused stellar detail has no temporal noise');assert.deepEqual(repeated.snapshot,frozen);result.stability.push({size,identicalPixels:true});}
    await pose(page,'blue',{quality:'low',exposure:2,fov:30});await capture(page,'blue-low-exposure2');result.checks.push('low resolution and high exposure retain a valid star rendering');
    await pose(page,'amber',{mode:'relativity'});await capture(page,'relativity-shifted');const shifted=await page.evaluate(()=>window.__stellarScene.snapshot());await pose(page,'amber',{mode:'relativity',compareRest:true});await capture(page,'relativity-unshifted');const unshifted=await page.evaluate(()=>window.__stellarScene.snapshot());assert.deepEqual(unshifted.state,shifted.state);assert.equal(unshifted.settings.beta,shifted.settings.beta);assert.equal(unshifted.settings.fov,shifted.settings.fov);result.checks.push('shifted and unshifted displays preserve physical camera state');
    result.math=await page.evaluate(()=>({gamma:UniverseFlight.math.gamma(.99),doppler:UniverseFlight.math.doppler(.5,.9),spectrum:UniverseFlight.math.viewSpectrum(.99,.3,-.2,550),clock:UniverseFlight.math.lightClock(.99,1)}));
    if(phase==='refined'){
      const baseline=JSON.parse(fs.readFileSync(path.join(report,'stellar-baseline.json'),'utf8'));assert.equal(baseline.completed,true);assert.equal(result.pointDataHash,baseline.pointDataHash,'The new star shader preserves exact point data');assert.deepEqual(result.math,baseline.math,'The new star shader preserves numerical relativity and spectrum results');
      for(const size of [6,10]){const name='isolated-css'+size,old=png(fs.readFileSync(path.join(report,'stellar-baseline-'+name+'.png'))),actual=png(fs.readFileSync(path.join(report,'stellar-refined-'+name+'.png')));assert.deepEqual(actual.pixels,old.pixels,'Unresolved '+size+' CSS pixel stars retain the exact baseline pixels');}result.checks.push('isolated unresolved stars are pixel-identical to baseline');
      for(let size=11;size<=27;size+=.5){await cssPose(page,size);const profile=await page.evaluate(()=>{window.__stellarScene.capture();const gl=window.__stellarGL.at(-1).gl,n=80,pixels=new Uint8Array(n*n*4);gl.readPixels(Math.floor(gl.drawingBufferWidth/2-n/2),Math.floor(gl.drawingBufferHeight/2-n/2),n,n,gl.RGBA,gl.UNSIGNED_BYTE,pixels);let sum=0;for(let i=0;i<pixels.length;i+=4)sum+=Math.max(0,(.2126*pixels[i]+.7152*pixels[i+1]+.0722*pixels[i+2])-4);return {sum,error:gl.getError()};});assert.equal(profile.error,0);result.transition.push({cssSize:size,lightPerSpriteArea:profile.sum/(size*size)});}
      const jumps=result.transition.slice(1).map((item,i)=>Math.abs(item.lightPerSpriteArea-result.transition[i].lightPerSpriteArea));result.transitionMaxJump=Math.max(...jumps);assert.ok(result.transitionMaxJump<8,'Small angular-size steps have a continuous light profile');result.checks.push('continuous angular-size sweep crosses the resolved transition without a brightness jump');
      await pose(page,'amber',{distance:10});await page.evaluate(()=>{window.__stellarOnly=null;window.__stellarScene.set({speed:5});if(!window.__stellarScene.navigateTo('amber-star',1))throw new Error('Genuine nearby approach failed');});await page.waitForFunction(()=>window.__stellarInfo?.navigation?.completed&&window.__stellarInfo.running===false,{},{timeout:30000});const arrival=await capture(page,'actual-approach');const target=targets.amber.position,separation=Math.hypot(...(await page.evaluate(()=>window.__stellarScene.snapshot())).state.position.map((v,i)=>v-target[i]));assert.ok(Math.abs(separation-.6)<1e-9);await page.evaluate(()=>{if(!window.__stellarScene.startOrbit('amber-star'))throw new Error('Genuine nearby orbit failed');});const before=await page.evaluate(()=>window.__stellarScene.snapshot());await page.waitForFunction(p=>Math.hypot(...window.__stellarScene.snapshot().state.position.map((v,i)=>v-p[i]))>.05,before.state.position);await page.evaluate(()=>window.__stellarScene.set({running:false}));const after=await page.evaluate(()=>window.__stellarScene.snapshot());assert.ok(Math.abs(Math.hypot(...after.state.position.map((v,i)=>v-target[i]))-.6)<1e-9);await capture(page,'actual-orbit-paused');result.checks.push('genuine nearby approach and fixed-radius orbit retain resolved star rendering');
    }
    await pose(page,'amber');const original=await capture(page,'reopen-reference');const live=await page.evaluate(()=>window.__stellarGL.map(({gl,record})=>({created:record.created,deleted:record.deleted,live:record.textures.filter(t=>gl.isTexture(t)).length})));await page.getByRole('button',{name:'Toggle full screen for the 3D view',exact:true}).click();await page.waitForFunction(()=>!document.fullscreenElement);await page.getByRole('button',{name:'Close flight explorer',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.uf-stage'));const released=await page.evaluate(()=>window.__stellarGL.map(({gl,record})=>({created:record.created,deleted:record.deleted,live:record.textures.filter(t=>gl.isTexture(t)).length})));assert.ok(released.every(c=>c.created===c.deleted&&c.live===0));result.lifecycle.push({live,released});await page.getByRole('button',{name:'Open 3D flight',exact:true}).click();await page.waitForFunction(()=>window.__stellarScenes.length===2&&window.__stellarStatus?.state==='ready');await page.getByRole('button',{name:'Toggle full screen for the 3D view',exact:true}).click();await page.waitForFunction(()=>!!document.fullscreenElement);await pose(page,'amber');const rebuilt=await capture(page,'reopened');assert.deepEqual(rebuilt.pixels,original.pixels);result.checks.push('closing releases textures and reopening reproduces stable stellar pixels');await page.close();
    const high=await createPage(2);await pose(high,'amber',{fov:30,quality:'high'});await capture(high,'amber-dpr2-zoom');await cssPose(high,16,{quality:'high'});const normal16=await capture(high,'dpr2-css16');await high.close();result.checks.push('DPR2 retains the resolved surface rendering');
    if(phase==='refined'){const limited=await createPage(2,32);await cssPose(limited,120,{quality:'high'});const constrained=await capture(limited,'dpr2-limit32');assert.ok(imageStats(constrained).luminousBounds.width<=32&&imageStats(constrained).luminousBounds.height<=32,'A simulated 32 device pixel limit actually clamps the sprite');const comparison=cropDifference(normal16,constrained);result.limitedRangeComparison=comparison;assert.ok(comparison.meanAbsolute<.25&&comparison.changedFraction<.02,'The transition uses hardware-clamped CSS size, matching an unconstrained 16 CSS pixel star');result.checks.push('32 device pixel hardware limit uses the actual DPR2 sprite size for the transition');await limited.close();}
    assert.deepEqual(result.errors,[]);result.completed=true;save();console.log('Stellar '+phase+' checks passed: '+result.checks.length+' groups, '+result.captures.length+' captures; source '+result.sourceHash+'.');
  }catch(error){result.failure=String(error);save();throw error;}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
