const fs=require('fs'),path=require('path'),vm=require('vm'),provider=require('./run_text_complexity_live_pilot.cjs');
const CASES=[
 {id:'fractions-primary',level:'Grade3',goal:'core',source:'A fraction describes equal parts of one whole. The denominator names how many equal parts make the whole. The numerator names how many of those parts are counted. In one half, the whole has two equal parts and one part is counted. In one quarter, the whole has four equal parts and one part is counted. Two quarters cover the same amount as one half when both fractions describe equal-sized wholes. Four quarters make one whole. One half is larger than one quarter of the same whole. Three quarters is larger than one half of the same whole. To compare these fractions, arrange the amounts from smallest to largest: one quarter, one half, three quarters, one whole. Pieces must be equal for this fraction model. A shape cut into four unequal pieces does not show quarters. Fraction names describe an amount, not the shape of the pieces. Comparing parts from different-sized wholes can be misleading. Always identify the whole before comparing fractions.'},
 {id:'ecosystems-middle',level:'Grade6',goal:'expedition',source:'In this meadow model, grass uses sunlight, water, and carbon dioxide to make sugars through photosynthesis. Grass is a producer. Rabbits eat grass and are primary consumers. Foxes eat rabbits and are secondary consumers. Arrows in a food chain point from the food source to the organism receiving its energy. The energy path in this model is sunlight, grass, rabbit, fox. Fungi break down dead plants and animals. They are decomposers. Decomposition returns nutrients to the soil where plants can use them. Energy flows through the food chain, while nutrients can be reused in the ecosystem. A population is a group of organisms of one species living in an area. A community contains populations of different species. An ecosystem includes that community and nonliving conditions such as soil, sunlight, and water. A reduction in grass can reduce the food available to rabbits. A model shows selected relationships and may leave out other food sources. Changes in a real ecosystem can have several causes, so one observation alone may not establish a cause.'},
 {id:'evidence-secondary',level:'Grade9',goal:'architect',source:'In this fictional school investigation, Group A recorded a library with twenty seats and Group B recorded a library with forty seats. Each group observed one afternoon. Both observed that every seat was occupied. These observations support a claim that both libraries were full during the observed afternoons. They do not establish that either library is always full. A claim is a statement that may be supported or challenged. Evidence is information used to evaluate a claim. Reasoning explains how the evidence relates to the claim. A qualification limits a claim to what the evidence supports. Comparing the two libraries requires attention to their different capacities. A count of occupied seats and a proportion of occupied seats answer different questions. A counterexample could challenge an overly broad statement such as all school libraries are full every afternoon. Repeated observations on different days would provide a stronger basis for describing usual occupancy. An opinion about a comfortable room does not by itself measure occupancy. A responsible conclusion reports the observed evidence, explains its relevance, and acknowledges limits.'}
];
function loadEngine(){const code=require('esbuild').buildSync({entryPoints:['lesson_board_engine.js'],bundle:true,write:false,platform:'node',format:'cjs'}).outputFiles[0].text;const context={module:{exports:{}},exports:{},require,console,crypto:globalThis.crypto};vm.runInNewContext(code,context);return context.module.exports;}
function solve(engine,board){let run=engine.emptyRun(),didRetry=false;for(let turn=0;turn<48&&!engine.derive(board,run).complete;turn++){
 const progress=engine.derive(board,run),required=engine.goalOf(board)==='architect'?3:2,targets=engine.targets(board,run),node=progress.built.length<required?targets.find(item=>item.cost)||targets.find(item=>!item.cost):targets.find(item=>!item.cost);
 if(!node)throw Error('No available move before completion');run=engine.merge(run,engine.begin(board,run,node.id));
 if(!node.cost){const answer=value=>{const action={attemptId:'validation',turn:run.turn,requestId:engine.requestId(run),kind:'answer',targetId:node.id,value};run=engine.merge(run,engine.processAction(board,run,action,'reviewer',{attemptId:'validation',active:true}));run=engine.merge(run,engine.resolve(board,run,{reviewer:{}}));};
  if(!didRetry&&node.kind==='choice'){answer(String((node.answer+1)%node.options.length));if(engine.stepOf(run).result.success)throw Error('Wrong answer passed');run=engine.merge(run,engine.retry(board,run));didRetry=true;}answer(engine.solution(node));}
 if(!engine.derive(board,run).complete)run=engine.merge(run,engine.advance(board,run));
 }if(!engine.derive(board,run).complete)throw Error('Mission did not finish');return {moves:run.turn+1,retryChecked:didRetry,progress:engine.missionProgress(board,run)};}
async function runValidation({generate,engine=loadEngine(),cases=CASES,outputDir}={}){
 const results=[];let calls=0;for(const scenario of cases){try{const board=await engine.generateBoard(async prompt=>{if(calls>=6)throw Error('Validation call limit reached');calls++;return generate(prompt);},scenario.source,{level:scenario.level,goal:scenario.goal,language:'English',seed:'board-validation-'+scenario.id});const play=solve(engine,board);results.push({id:scenario.id,level:scenario.level,goal:scenario.goal,status:'playable',...play,educatorReview:'pending'});if(outputDir)fs.writeFileSync(path.join(outputDir,scenario.id+'.alloboard.json'),JSON.stringify({format:'alloflow-lesson-board',version:1,source:scenario.source,language:'English',board},null,2));}catch(error){results.push({id:scenario.id,level:scenario.level,goal:scenario.goal,status:'failed',reason:String(error.message).slice(0,1800)});}}
 return {status:results.every(item=>item.status==='playable')?'generated-and-playable':'needs-review',calls,results,scope:'Automated playability and exact-source checks. Educator review of accuracy, clarity, and age fit remains required.'};
}
module.exports={CASES,loadEngine,solve,runValidation};
if(require.main===module)(async()=>{
 const config=provider.parseArgs(process.argv.slice(2)),out=path.resolve('reports/lesson-board-followthrough-2026-09-12/ai-validation');fs.mkdirSync(out,{recursive:true});const readiness=provider.providerReadiness(config);let report;
 if(!config.execute)report={status:'prepared',cases:CASES.map(({id,level,goal})=>({id,level,goal})),maxProviderCalls:6,providerReady:readiness.ready,readiness:readiness.code};
 else if(!readiness.ready)report={status:'blocked',reason:readiness.code,backend:config.backend,cases:CASES.map(({id,level,goal})=>({id,level,goal})),calls:0};
 else {const events=[],budget={used:0,maximum:6},generate=provider.createProviderGenerator({...config,maxTokens:12000,maxRetries:1,timeoutMs:90000},events,process.env,budget);report=await runValidation({generate:async prompt=>(await generate({prompt})).text,outputDir:out});report.backend=config.backend;report.requestedModel=config.model;}
 fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(report.status==='blocked')process.exitCode=2;else if(report.status==='needs-review')process.exitCode=1;
})().catch(error=>{console.error('Board validation failed: '+String(error.message).slice(0,500));process.exitCode=1;});
