'use strict';
// Focused, owned-browser verification of the responsive dashboard layout.
// Run: node dev-tools/watercycle_dashboard_layout_qa.cjs [--preflight]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'reports/watercycle-dashboard-layout');
const PREFLIGHT=process.argv.includes('--preflight');
const MAIN=path.join(ROOT,'stem_lab/stem_tool_watercycle.js'),PUBLIC=path.join(ROOT,'desktop/web-app/public/stem_lab/stem_tool_watercycle.js');
const source=fs.readFileSync(MAIN),hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const report={title:'Water Cycle dashboard layout',mode:PREFLIGHT?'layout preflight':'full browser QA',startedAt:new Date().toISOString(),sourceSha256:hash(source),publicSha256:hash(fs.readFileSync(PUBLIC)),method:'Frozen actual runtime in an owned ephemeral localhost server and isolated Chromium. Native controls, SVG geometry and container font scaling, reading order and measured layout gaps, scenario evidence and paused parcel preservation. No learner tabs, port 8770, runtime edits, or Git writes.',measurementNote:'SVG geometry is measured after two animation frames. Text bounds are assessed in both axes and rendered font sizes include SVG scale. The frozen baseline in this report directory supplies before measurements.',checks:[],cases:[],layouts:[],audits:[],failures:[],errors:[],completed:false,successful:false,browserClosed:false,serverClosed:false};
function check(pass,label,detail){report.checks.push({label,pass:!!pass,...(detail===undefined?{}:{detail})});if(!pass)report.failures.push(label);}
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Water Cycle signal inspection QA</title><link rel="stylesheet" href="/dev-tools/.cache/sweep-tailwind.css"><style>body{margin:0;background:#eef2f2;font-family:system-ui}main{padding:12px;max-width:1500px;margin:auto}</style></head><body><main id="slot"></main><script src="/desktop/web-app/node_modules/react/umd/react.production.min.js"></script><script src="/desktop/web-app/node_modules/react-dom/umd/react-dom.production.min.js"></script><script src="/vendor/three-r128/three.min.js"></script><script src="/vendor/three-r128/OrbitControls.js"></script><script src="/stem_lab/stem_lab_module.js"></script><script src="/stem_lab/stem_tool_watercycle.js"></script><script>
const Icons=new Proxy({},{get:()=>()=>React.createElement('span',{'aria-hidden':true})});
window.mountSignalReview=function(seed,theme){function Host(){const[data,setData]=React.useState({waterCycle:seed,_threeLoaded:true});window.signalData=data.waterCycle;window.signalSet=setData;const noop=()=>{};return StemLab._registry.waterCycle.render({React,toolData:data,setToolData:setData,isDark:theme==='dark',isContrast:theme==='contrast',gradeBand:'6-8',gradeLevel:'7th Grade',icons:Icons,setStemLabTool:noop,setStemLabTab:noop,setToolSnapshots:noop,toolSnapshots:[],addToast:noop,announceToSR:noop,awardXP:noop,getXP:()=>0,beep:noop,celebrate:noop,canvasNarrate:noop,canvasA11yDesc:noop,a11yClick:f=>({onClick:f}),t:(k,f)=>f==null?k:f,props:{},srOnly:{},callGemini:null});}document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.classList.toggle('high-contrast',theme==='contrast');document.body.style.background=theme==='dark'?'#081b21':'#eef2f2';ReactDOM.unmountComponentAtNode(document.getElementById('slot'));ReactDOM.render(React.createElement(Host),document.getElementById('slot'));};
window.patchSignalReview=fields=>signalSet(previous=>({...previous,waterCycle:{...previous.waterCycle,...fields}}));
</script></body></html>`;
const mime={'.js':'text/javascript','.css':'text/css'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html'});return res.end(html);}if(url.pathname==='/stem_lab/stem_tool_watercycle.js'){res.writeHead(200,{'Content-Type':'text/javascript'});return res.end(source);}const file=path.resolve(ROOT,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,bytes)=>{res.writeHead(error?404:200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(error?'Not found':bytes);});});
const places=['surface','air','cloud','land','return'],labels=['Surface','Air','Cloud','Land','Return'];
async function patch(page,fields){await page.evaluate(fields=>patchSignalReview(fields),fields);await page.waitForTimeout(80);}
async function snapshot(page,label){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));return page.evaluate(label=>{
 const panel=document.querySelector('.wc-signal-dashboard'),chart=panel.querySelector('.wc-signal-chart'),svg=chart.querySelector('.wc-signal-plot');
 const rect=el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};};
 const box=rect(panel),plotRect=rect(svg),view=svg.viewBox.baseVal,axes=svg.querySelector('.wc-signal-axis');
 const top=Number(axes.getAttribute('y1')),bottom=Number(axes.getAttribute('y2'));
 const value=y=>100*(bottom-y)/(bottom-top);
 const series=[...svg.querySelectorAll('.wc-signal-series')].map(el=>{const s=getComputedStyle(el);const points=[...el.getAttribute('d').matchAll(/[ML]\s+(-?[\d.]+)\s+(-?[\d.]+)/g)].map(m=>({x:Number(m[1]),y:Number(m[2]),score:value(Number(m[2]))}));return{key:el.dataset.signalSeries,stroke:s.stroke,dash:s.strokeDasharray,width:s.strokeWidth,opacity:s.opacity,points};});
 const markers=[...svg.querySelectorAll('.wc-signal-point')].map(el=>{const b=el.getBBox(),s=getComputedStyle(el);return{key:el.dataset.signalMarker,tag:el.tagName,shape:el.getAttribute('d'),center:{x:b.x+b.width/2,y:b.y+b.height/2},score:value(b.y+b.height/2),fill:s.fill,stroke:s.stroke,bounds:{x:b.x,y:b.y,w:b.width,h:b.height}};});
 const texts=[...svg.querySelectorAll('text')].map(el=>{const s=getComputedStyle(el);return{text:el.textContent,className:el.getAttribute('class'),font:parseFloat(s.fontSize),renderedFont:parseFloat(s.fontSize)*plotRect.w/view.width,fill:s.fill,rect:rect(el)};});
 const textCollisions=[];for(let i=0;i<texts.length;i++)for(let j=i+1;j<texts.length;j++){const a=texts[i].rect,b=texts[j].rect;if(Math.min(a.right,b.right)-Math.max(a.x,b.x)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y)>1)textCollisions.push([texts[i].text,texts[j].text]);}
 const plotHeading=rect(chart.querySelector('.wc-signal-chart-heading')),headingText=[...chart.querySelector('.wc-signal-chart-heading').children].map(el=>({text:el.innerText,rect:rect(el)}));
 const visible=el=>{const s=getComputedStyle(el),r=rect(el);return r.w>0&&r.h>0&&s.display!=='none'&&(!el.closest('details')||el.closest('details').open||el.tagName==='SUMMARY');};
 const overflow=[...panel.querySelectorAll('*')].filter(el=>!el.closest('svg')&&!el.closest('.sr-only')&&visible(el)).map(el=>({el,rect:rect(el)})).filter(({el,rect:r})=>r.x<box.x-1||r.right>box.right+1||(el.clientWidth>0&&el.scrollWidth>el.clientWidth+1&&getComputedStyle(el).overflow!=='visible')).map(({el,rect})=>({className:el.className,tag:el.tagName,text:el.innerText.slice(0,80),rect}));
 const readout=[...panel.querySelectorAll('[data-signal-reading-series]')].map(el=>({key:el.dataset.signalReadingSeries,label:el.querySelector('dt').innerText,score:Number(el.querySelector('dd').firstChild.textContent)}));
 const rows=[...panel.querySelectorAll('[data-signal-values-place]')].map(el=>({place:el.dataset.signalValuesPlace,highlight:el.dataset.inspected==='true',rowHeader:el.querySelector('th').getAttribute('scope'),scores:Object.fromEntries([...el.querySelectorAll('[data-signal-value]')].map(td=>[td.dataset.signalValue,Number(td.textContent)]))}));
 const legend=[...chart.querySelectorAll('.wc-signal-legend>[role=listitem]')].map(el=>{const line=el.querySelector('.wc-signal-key-line'),mark=el.querySelector('.wc-signal-point');return{key:line.dataset.signalSeries,text:el.innerText,dash:getComputedStyle(line).strokeDasharray,marker:mark.tagName,stroke:getComputedStyle(line).stroke};});
 const graphicsInk=[...svg.querySelectorAll('.wc-signal-gridline,.wc-signal-axis,.wc-signal-stage-marker,.wc-signal-stage-marker-dot')].map(el=>{const s=getComputedStyle(el);return{className:el.getAttribute('class'),tag:el.tagName,stroke:s.stroke,fill:s.fill,opacity:s.opacity};});
 const data={...signalData};delete data.wcSignalInspectPlace;
 const canvas=document.getElementById('wcCanvas');
 return{label,stageIndex:Number(chart.dataset.signalStageIndex),inspectIndex:Number(chart.dataset.signalInspectIndex),inspectChoice:chart.dataset.signalInspectPlace,followOption:document.getElementById('wcSignalInspectPlace').options[0].textContent,focusChip:panel.querySelector('.wc-signal-focus-chip').innerText,focusChipAria:panel.querySelector('.wc-signal-focus-chip').getAttribute('aria-label'),focusState:panel.dataset.wcFocusState,markerLabel:svg.querySelector('.wc-signal-stage-marker-label').textContent,markerX:Number(svg.querySelector('.wc-signal-stage-marker').getAttribute('x1')),description:svg.querySelector('desc').textContent,readoutPlace:panel.querySelector('.wc-signal-reading').dataset.signalReadingPlace,readoutHeader:panel.querySelector('.wc-signal-reading-head').innerText,readout,rows,series,markers,legend,texts,textCollisions,plotHeading,headingText,graphicsInk,ink:getComputedStyle(chart).color,paper:getComputedStyle(chart).backgroundColor,plotRect,panelRect:box,viewportWidth:innerWidth,scrollWidth:document.documentElement.scrollWidth,overflow,folded:!panel.querySelector('details').open,tableCaption:panel.querySelector('caption').textContent,columnScopes:[...panel.querySelectorAll('thead th')].map(el=>el.getAttribute('scope')),chartSelect:rect(document.getElementById('wcSignalInspectPlace')),summary:rect(panel.querySelector('summary')),dataWithoutInspection:JSON.stringify(data),parcel:{active:signalData.journeyActive,state:canvas.dataset.journeyState,stage:canvas.dataset.activeStage,paused:canvas.dataset.journeyPaused,progress:Number(canvas.dataset.journeyProgress||0)},solar:signalData.climSolar};
 },label);}
function assessScores(m,label){
 check(m.series.every(series=>series.points.length===5&&series.points.every((point,i)=>Math.abs(point.score-m.rows[i].scores[series.key])<.08&&m.rows[i].scores[series.key]>=0&&m.rows[i].scores[series.key]<=100)),label+' all plotted coordinates agree with five-place table',m.series.map(s=>({key:s.key,plot:s.points.map(p=>p.score),table:m.rows.map(r=>r.scores[s.key])})));
 check(m.readoutPlace===places[m.inspectIndex]&&m.readout.every(r=>r.score===m.rows[m.inspectIndex].scores[r.key])&&m.rows.filter(r=>r.highlight).length===1&&m.rows[m.inspectIndex].highlight,label+' selected place readout and highlighted table row agree',{readout:m.readout,rows:m.rows,choice:m.inspectChoice});
 check(m.markers.every(mark=>{const line=m.series.find(s=>s.key===mark.key),point=line.points[m.inspectIndex];return Math.abs(mark.center.x-point.x)<.06&&Math.abs(mark.center.y-point.y)<.06&&Math.abs(mark.score-m.rows[m.inspectIndex].scores[mark.key])<.01;}),label+' selected shape marks the actual plotted score',m.markers);
}
function assessLayout(m,label){
 check(m.scrollWidth<=m.viewportWidth&&m.overflow.length===0,label+' panel fits viewport without clipping or page overflow',m.overflow);
 check(m.texts.every(t=>t.renderedFont>=11.8)&&m.textCollisions.length===0,label+' plot text remains about 12px or larger and labels do not overlap',{fonts:m.texts.map(t=>({text:t.text,font:t.renderedFont})),collisions:m.textCollisions});
 const collides=(a,b)=>Math.min(a.right,b.right)-Math.max(a.x,b.x)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y)>1;
 check(m.texts.every(t=>t.rect.x>=m.panelRect.x-1&&t.rect.right<=m.panelRect.right+1&&!m.headingText.some(h=>collides(t.rect,h.rect)))&&m.markers.every(mark=>mark.bounds.x>=0&&mark.bounds.y>=0&&mark.bounds.x+mark.bounds.w<=420&&mark.bounds.y+mark.bounds.h<=196),label+' plot labels clear the heading and shape marks stay inside the scene',{heading:m.headingText,texts:m.texts,markers:m.markers});
 if(label.includes('forced-colors'))check(m.texts.every(t=>t.fill===m.ink),label+' forced-color SVG labels use the CanvasText foreground',{ink:m.ink,texts:m.texts.map(t=>({text:t.text,fill:t.fill}))});
 if(label.includes('forced-colors'))check(m.graphicsInk.length===7&&m.graphicsInk.every(node=>node.tag==='circle'?node.fill===m.ink&&node.stroke===m.paper&&Number(node.opacity)===1:node.stroke===m.ink&&Number(node.opacity)===1),label+' forced-color axes gridlines stage marker and dot use opaque system ink',{ink:m.ink,paper:m.paper,nodes:m.graphicsInk});
}
async function audit(page,label){const violations=await page.evaluate(async()=>(await axe.run(document.querySelector('.wc-signal-dashboard'),{rules:{region:{enabled:false}}})).violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({html:n.html,summary:n.failureSummary}))})));report.audits.push({label,violations});check(violations.length===0,label+' scoped accessibility audit',violations);}
async function capture(page,name){await page.locator('.wc-signal-dashboard').screenshot({path:path.join(OUT,name),animations:'disabled',timeout:60000});}
async function layoutSnapshot(page,label){const m=await page.evaluate(label=>{const panel=document.querySelector('.wc-signal-dashboard'),grid=panel.querySelector('.wc-signal-grid'),chart=grid.querySelector('.wc-signal-chart'),inspection=grid.querySelector('.wc-signal-inspection'),stores=grid.querySelector('.wc-signal-stores'),values=grid.querySelector('.wc-signal-values');const rect=el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};};const children=[...grid.children],last=stores.querySelector('.wc-signal-bar:last-child'),heading=stores.querySelector('h2,h3,h4,strong,[role=heading]');return{label,viewport:innerWidth,host:rect(document.getElementById('slot')),panel:rect(panel),grid:rect(grid),chart:rect(chart),inspection:rect(inspection),stores:rect(stores),values:rect(values),lastBar:rect(last),unusedHeightBelowLastBar:Math.max(0,chart.getBoundingClientRect().bottom-last.getBoundingClientRect().bottom),tableOpen:values.open,domOrder:children.map(el=>['wc-signal-chart','wc-signal-inspection','wc-signal-stores','wc-signal-values'].find(c=>el.classList.contains(c))||el.className),storeHeading:heading?.innerText||null,storeHeadingRect:heading?rect(heading):null,storeAria:stores.getAttribute('aria-labelledby'),storeAriaReferences:(stores.getAttribute('aria-labelledby')||'').split(/\s+/).filter(Boolean).map(id=>({id,exists:!!document.getElementById(id)})),selectInInspection:inspection.contains(document.getElementById('wcSignalInspectPlace')),readingInInspection:!!inspection.querySelector('.wc-signal-reading'),tableCaption:values.querySelector('caption').innerText,panelText:panel.innerText};},label);report.layouts.push(m);return m;}
function assessDashboardLayout(m,label){check(m.domOrder.join('|')==='wc-signal-chart|wc-signal-inspection|wc-signal-stores|wc-signal-values',label+' four semantic groups follow plot inspection stores table DOM order',m.domOrder);check(m.selectInInspection&&m.readingInInspection&&!!m.storeHeading&&m.storeHeadingRect.h>0&&m.storeAriaReferences.length>0&&m.storeAriaReferences.every(r=>r.exists),label+' inspection and stores have visible coherent grouping and named references',{heading:m.storeHeading,storeAria:m.storeAria,references:m.storeAriaReferences});check(Math.abs(m.values.w-m.grid.w)<=1&&m.values.y>=Math.max(m.chart.bottom,m.inspection.bottom,m.stores.bottom)-1,label+' values table spans the complete grid below the other groups',{grid:m.grid,values:m.values});const stacked=m.chart.y+1<m.stores.y;check(stacked?m.chart.bottom<=m.inspection.y+1&&m.inspection.bottom<=m.stores.y+1&&m.stores.bottom<=m.values.y+1:m.stores.right<=m.chart.x+1&&Math.abs(m.stores.y-m.chart.y)<2,label+' visual groups follow the responsive desktop or phone arrangement',{stacked,chart:m.chart,inspection:m.inspection,stores:m.stores,values:m.values});}
async function selectStage(page,stage){await page.locator('button[aria-label^="Stage"]').filter({hasText:stage[0].toUpperCase()+stage.slice(1)}).first().click();await page.waitForTimeout(80);}
async function main(){fs.mkdirSync(OUT,{recursive:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;try{
 browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const configs=PREFLIGHT?[{theme:'light',width:320},{theme:'light',width:1280},{theme:'light',width:1280,hostWidth:390}]:[{theme:'light',width:320},{theme:'light',width:390},{theme:'light',width:768},{theme:'light',width:1280},{theme:'dark',width:1280},{theme:'forced-colors',width:320},{theme:'dark',width:1280,forced:true},{theme:'light',width:1280,hostWidth:620},{theme:'light',width:1280,hostWidth:390}];
 for(const config of configs){const label=(config.forced?'dark-forced-colors':config.theme)+'-'+config.width+(config.hostWidth?'-host-'+config.hostWidth:'');const context=await browser.newContext({viewport:{width:config.width,height:1800},reducedMotion:'reduce',...(config.forced||config.theme==='forced-colors'?{forcedColors:'active'}:{})});const page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',error=>report.errors.push(label+': '+String(error)));await page.goto('http://127.0.0.1:'+server.address().port);if(config.hostWidth)await page.locator('#slot').evaluate((el,width)=>{el.style.width=width+'px';el.style.maxWidth='100%';el.style.boxSizing='border-box';},config.hostWidth);
 const seed={wcMode:'explore',wcSection:'data',journeyView:'2d',journeyActive:false,journeyState:'idle',journeyPaused:true,wc2dPaused:true,activeStage:'infiltration',climTemp:15,climSolar:1,climWind:1,landRainIntensity:55,landSaturation:45,landPermeability:'medium',landSlope:'moderate',landCover:'grass',wcScenarioBaseline:{climSolar:1,climTemp:15,climWind:1,landRainIntensity:55,landSaturation:45,landPermeability:'medium',landSlope:'moderate',landCover:'grass'},wcProcessCompare:{first:'condensation',second:'precipitation',notes:{'condensation|precipitation':'Cloud particles grow and fall; condensation forms droplets.'}},wcExperimentLog:[{id:'signal-inspection-evidence',note:'Saved observation must survive chart inspection',inputs:{climSolar:1,climTemp:15,climWind:1}}]};
 await page.evaluate(({seed,theme})=>mountSignalReview(seed,theme==='forced-colors'?'contrast':theme),{seed,theme:config.theme});await page.locator('.wc-signal-dashboard').waitFor();await page.waitForTimeout(100);let initial=await snapshot(page,label+' default');report.cases.push(initial);
 check(initial.inspectChoice==='follow'&&initial.inspectIndex===3&&initial.stageIndex===3&&initial.markerLabel==='Land'&&initial.readoutPlace==='land',label+' default follows standalone Infiltration at Land',initial);
 check(initial.folded&&initial.tableCaption.includes('Independent teaching scores')&&initial.columnScopes.length===4&&initial.columnScopes.every(s=>s==='col')&&initial.rows.every(r=>r.rowHeader==='row'),label+' values table starts folded and has caption and row/column headers');
 assessScores(initial,label+' default');assessLayout(initial,label+' default');
 const layoutInitial=await layoutSnapshot(page,label+' folded');assessDashboardLayout(layoutInitial,label+' folded');check(layoutInitial.panelText.includes('Scores use current conditions; replay changes the focus'),label+' current-condition note distinguishes replay focus from restored conditions');
 const styles=initial.series.map(s=>s.dash);check(new Set(styles).size===3&&initial.legend.every(item=>item.dash===initial.series.find(s=>s.key===item.key).dash)&&initial.markers.map(m=>m.tag).join('|')==='circle|rect|path'&&initial.legend.map(m=>m.marker).join('|')==='circle|rect|path',label+' solid dashed dotted styles and circle square diamond shapes match their legend',{series:initial.series,legend:initial.legend});
 check(initial.description.includes('not measurements')&&initial.description.includes('not elapsed time')&&initial.description.includes('Stage focus is Land')&&initial.description.includes('inspected values are at Land'),label+' accessible chart description states score and place limits');
 if(config.width!==390)await capture(page,'final-dashboard-folded-'+label+'.png');
 if(PREFLIGHT){await page.locator('.wc-signal-values summary').click();const opened=await snapshot(page,label+' preflight open');assessLayout(opened,label+' preflight open');const openLayout=await layoutSnapshot(page,label+' preflight open');assessDashboardLayout(openLayout,label+' preflight open');await capture(page,'preflight-dashboard-open-'+label+'.png');await page.evaluate(()=>ReactDOM.unmountComponentAtNode(document.getElementById('slot')));await context.close();console.log('Preflight checked '+label);continue;}
 for(const place of places){await page.locator('#wcSignalInspectPlace').selectOption(place);const m=await snapshot(page,label+' inspect '+place);report.cases.push(m);assessScores(m,label+' '+place);check(m.inspectChoice===place&&m.stageIndex===3&&m.markerLabel==='Land'&&m.inspectIndex===places.indexOf(place)&&m.description.includes('inspected values are at '+labels[places.indexOf(place)]),label+' '+place+' inspection leaves current-stage marker distinct');}
 let after=await snapshot(page,label+' inspected all');check(after.dataWithoutInspection===initial.dataWithoutInspection&&JSON.stringify(after.parcel)===JSON.stringify(initial.parcel),label+' inspecting all places preserves scenario writing baseline evidence and parcel',{before:initial.parcel,after:after.parcel});
 await page.locator('#wcSignalInspectPlace').focus();await page.keyboard.press('Tab');const forward=await page.locator('.wc-signal-values summary').evaluate(el=>el===document.activeElement);await page.keyboard.press('Shift+Tab');check(forward&&await page.locator('#wcSignalInspectPlace').evaluate(el=>el===document.activeElement),label+' tab order moves between native place selector and table summary');
 const select=page.locator('#wcSignalInspectPlace');await select.focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');after=await snapshot(page,label+' keyboard Surface');const focus=await select.evaluate(el=>{const s=getComputedStyle(el);return{focus:el===document.activeElement,visible:el.matches(':focus-visible'),style:s.outlineStyle,width:s.outlineWidth,height:el.getBoundingClientRect().height};});check(after.inspectChoice==='surface'&&focus.focus&&focus.visible&&focus.style!=='none'&&parseFloat(focus.width)>=3&&focus.height>=44,label+' native selector responds to keyboard with visible focus and 44px target',{choice:after.inspectChoice,focus});
 await selectStage(page,'evaporation');after=await snapshot(page,label+' manual Surface after Evaporation');check(after.inspectChoice==='surface'&&after.inspectIndex===0&&after.stageIndex===1&&after.markerLabel==='Air'&&after.readoutHeader.includes('stage focus Air'),label+' manual place remains selected as native stage changes',after.readoutHeader);
 await select.selectOption('follow');after=await snapshot(page,label+' follow Evaporation');check(after.inspectIndex===1&&after.readoutPlace==='air'&&after.readoutHeader.includes('Following stage focus')&&after.followOption.includes('Follow stage focus'),label+' Follow resumes tracking current stage');
 const stageCases=[];for(const[stage,index]of [['condensation',2],['precipitation',3],['collection',0],['transpiration',4],['infiltration',3]]){await selectStage(page,stage);const m=await snapshot(page,label+' follow '+stage);stageCases.push({stage,index,actual:m.stageIndex,inspected:m.inspectIndex,marker:m.markerLabel});}
 check(stageCases.every(m=>m.actual===m.index&&m.inspected===m.index&&m.marker===labels[m.index]),label+' Follow maps all six standalone processes to modeled places',stageCases);
 await patch(page,{journeyActive:true,journeyState:'infiltrating',activeStage:'infiltration',journeyReplayProgress:null,journeyLastPath:'infiltrate'});await page.locator('#wcCanvas').evaluate(el=>el._wcSetJourneyProgress(0.37));const parcelBefore=await snapshot(page,label+' active paused parcel');await select.selectOption('cloud');await page.locator('.wc-signal-values summary').focus();await page.keyboard.press('Enter');after=await snapshot(page,label+' paused parcel table');report.cases.push(after);
 check(after.inspectChoice==='cloud'&&!after.folded&&JSON.stringify(after.parcel)===JSON.stringify(parcelBefore.parcel)&&after.dataWithoutInspection===parcelBefore.dataWithoutInspection,label+' native table and manual inspection preserve live paused parcel progress and learner work',{before:parcelBefore.parcel,after:after.parcel});
 assessLayout(after,label+' expanded table');check(after.summary.h>=44,label+' folded-table summary has 44px target');
 const layoutOpen=await layoutSnapshot(page,label+' open table');assessDashboardLayout(layoutOpen,label+' open table');check(Math.abs(layoutOpen.chart.h-layoutInitial.chart.h)<1&&Math.abs(layoutOpen.stores.h-layoutInitial.stores.h)<1,label+' opening values adds its own row without stretching plot or stores',{folded:layoutInitial,open:layoutOpen});
 if(config.theme==='light'&&config.width===1280&&!config.hostWidth){const baseline=JSON.parse(fs.readFileSync(path.join(OUT,'baseline-results.json'),'utf8')).snapshots;const before=baseline.find(m=>m.label==='desktop-or-phone-open-1280');check(layoutOpen.unusedHeightBelowLastBar<before.unusedHeightBelowLastBar*.4&&layoutOpen.panel.h<before.dashboard.h,label+' desktop layout measurably reduces the frozen baseline gap and total height',{beforeGap:before.unusedHeightBelowLastBar,afterGap:layoutOpen.unusedHeightBelowLastBar,beforeHeight:before.dashboard.h,afterHeight:layoutOpen.panel.h});const beforeResize=await snapshot(page,label+' before host resize'),resizeLayouts=[];for(const width of [890,620,390,320,1280]){await page.locator('#slot').evaluate((el,width)=>{el.style.width=width+'px';el.style.maxWidth='100%';el.style.boxSizing='border-box';},width);const resized=await snapshot(page,label+' resized host '+width);assessLayout(resized,label+' resized host '+width);const lm=await layoutSnapshot(page,label+' resized host '+width);assessDashboardLayout(lm,label+' resized host '+width);resizeLayouts.push({width,state:resized.dataWithoutInspection,parcel:resized.parcel,selection:resized.inspectChoice,open:lm.tableOpen});}check(resizeLayouts.every(m=>m.state===beforeResize.dataWithoutInspection&&JSON.stringify(m.parcel)===JSON.stringify(beforeResize.parcel)&&m.selection===beforeResize.inspectChoice&&m.open),label+' resizing across wide narrow and embedded phone hosts preserves learner work paused progress and inspection',resizeLayouts);}
 if(config.width!==390)await capture(page,'final-dashboard-open-table-'+label+'.png');
 await page.addScriptTag({url:'/desktop/web-app/node_modules/axe-core/axe.min.js'});await audit(page,label+' open table');
 const activeCases=[];for(const[state,stage,index]of [['evaporating','evaporation',1],['condensing','condensation',2],['precipitating','precipitation',3],['infiltrating','infiltration',3],['aquifer_flow','infiltration',3],['plant_absorb','transpiration',4],['river_runoff','collection',0]]){await patch(page,{journeyState:state,activeStage:stage});await select.selectOption('follow');const m=await snapshot(page,label+' active '+state);activeCases.push({state,index,actual:m.stageIndex,inspect:m.inspectIndex});}
 check(activeCases.every(c=>c.actual===c.index&&c.inspect===c.index),label+' active journey stages follow atmosphere surface soil and plant stores',activeCases);
 const beforeReplay=await snapshot(page,label+' before replay');await patch(page,{journeyState:'plant_absorb',activeStage:'transpiration',journeyReplayProgress:0.78,journeyLastPath:'infiltrate'});const replay=await snapshot(page,label+' infiltration replay');report.cases.push(replay);check(replay.focusState==='infiltrating'&&replay.stageIndex===3&&replay.inspectIndex===3&&replay.description.includes('Replay focus is Land')&&replay.readoutHeader.includes('Following replay focus')&&replay.followOption.includes('Follow replay focus')&&replay.focusChip==='Replay focus · Land'&&replay.focusChipAria==='Replay focus: Land',label+' replay inspection identifies scrubbed soil entry separately from live plant step',{focusState:replay.focusState,stage:replay.stageIndex,inspect:replay.inspectIndex,description:replay.description,header:replay.readoutHeader,follow:replay.followOption,chip:replay.focusChip});check(JSON.stringify(replay.rows.map(row=>row.scores))===JSON.stringify(beforeReplay.rows.map(row=>row.scores)),label+' replay changes focus while every score retains current conditions');
 await patch(page,{journeyReplayProgress:null,journeyActive:false,activeStage:'evaporation'});await select.selectOption('surface');const solarBefore=await snapshot(page,label+' solar baseline');await page.locator('.wc-section-tabs').getByRole('button',{name:/^Change the conditions\./}).click();await page.locator('#wc-climate-solar').focus();await page.keyboard.press('ArrowRight');const newSolar=await page.locator('#wc-climate-solar').inputValue();await page.locator('.wc-section-tabs').getByRole('button',{name:/^What the data shows\./}).click();const solarAfter=await snapshot(page,label+' solar change');report.cases.push(solarAfter);assessScores(solarAfter,label+' climate update');
 check(Number(newSolar)===1.05&&solarAfter.inspectChoice==='surface'&&solarAfter.readout.find(r=>r.key==='energy').score===Math.round(Number(newSolar)*52)&&solarAfter.readout.find(r=>r.key==='energy').score>solarBefore.readout.find(r=>r.key==='energy').score,label+' actual solar keyboard change updates exact plotted and tabulated energy scores',{before:solarBefore.readout,after:solarAfter.readout,solar:newSolar});
 check(await page.evaluate(seed=>JSON.stringify(signalData.wcScenarioBaseline)===JSON.stringify(seed.wcScenarioBaseline)&&JSON.stringify(signalData.wcProcessCompare)===JSON.stringify(seed.wcProcessCompare)&&JSON.stringify(signalData.wcExperimentLog)===JSON.stringify(seed.wcExperimentLog),seed),label+' climate and section change preserve saved baseline comparison writing and experiment evidence');
 await page.locator('.wc-signal-values summary').focus();if(await page.locator('.wc-signal-values').evaluate(el=>el.open))await page.keyboard.press('Enter');await audit(page,label+' folded table');
 await page.evaluate(()=>ReactDOM.unmountComponentAtNode(document.getElementById('slot')));await context.close();console.log('Checked '+label);
 }
 check(report.errors.length===0,'No browser runtime errors',report.errors);report.finalSourceSha256=hash(fs.readFileSync(MAIN));report.finalPublicSha256=hash(fs.readFileSync(PUBLIC));check(report.sourceSha256===report.finalSourceSha256&&report.sourceSha256===report.finalPublicSha256,'Frozen tested source stays unchanged and matches public mirror');report.completed=true;check(true,PREFLIGHT?'Browser completes the phone geometry preflight':'Browser completes every requested inspection and evidence case');
 }catch(error){report.completed=false;report.errors.push('Interrupted browser run: '+String(error.stack||error));check(false,'Browser completes every requested inspection and evidence case',{error:String(error)});throw error;
 }finally{try{if(browser)await browser.close();report.browserClosed=true;}catch(error){report.errors.push('Browser cleanup failed: '+String(error));check(false,'Owned browser closes successfully');}try{await new Promise(resolve=>server.close(resolve));report.serverClosed=true;}catch(error){report.errors.push('Server cleanup failed: '+String(error));check(false,'Owned server closes successfully');}report.finishedAt=new Date().toISOString();report.passed=report.checks.filter(c=>c.pass).length;report.failed=report.checks.length-report.passed;report.successful=report.completed&&report.failed===0&&report.errors.length===0&&report.browserClosed&&report.serverClosed;fs.writeFileSync(path.join(OUT,PREFLIGHT?'preflight-results.json':'results.json'),JSON.stringify(report,null,2)+'\n');}
 console.log(JSON.stringify({sourceSha256:report.sourceSha256,checks:report.checks.length,cases:report.cases.length,audits:report.audits.length,failures:report.failures,errors:report.errors,completed:report.completed,successful:report.successful,browserClosed:report.browserClosed,serverClosed:report.serverClosed},null,2));assert.deepEqual(report.failures,[]);assert.deepEqual(report.errors,[]);
}
main().catch(error=>{console.error(error);process.exitCode=1;server.close();});
