
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');const {chromium}=require('playwright');const root=path.resolve(__dirname,'../..');
(async()=>{await require('esbuild').build({entryPoints:[path.join(__dirname,'fixture.jsx')],bundle:true,outfile:path.join(__dirname,'fixture.js'),platform:'browser',format:'iife',define:{'process.env.NODE_ENV':'"production"'}});
const css=fs.readdirSync(path.join(root,'desktop/web-app/build/static/css')).find(n=>n.endsWith('.css'));
const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Preserved reading browser fixture</title><link rel="stylesheet" href="/app.css"><style>body{margin:0;background:#f8fafc;color:#0f172a;font-family:Arial,sans-serif}button,input,select{font:inherit}button:focus-visible,input:focus-visible{outline:3px solid #4338ca;outline-offset:3px}</style><div id="root"></div><script src="/strings.js"></script><script src="/fixture.js"></script></html>';
const server=http.createServer((req,res)=>{const files={'/fixture.js':path.join(__dirname,'fixture.js'),'/strings.js':path.join(__dirname,'strings.js'),'/app.css':path.join(root,'desktop/web-app/build/static/css',css)};if(files[req.url]){res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'application/javascript');res.end(fs.readFileSync(files[req.url]));}else{res.setHeader('Content-Type','text/html');res.end(html);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;const errors=[],checks=[];try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1280,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('[data-reading-comparison]').waitFor();
const getBodies=()=>page.locator('[data-compare-version]').evaluateAll(nodes=>nodes.map(n=>({key:n.getAttribute('data-compare-version'),text:(()=>{const copy=n.cloneNode(true);copy.querySelectorAll('[data-reading-gloss]').forEach(x=>x.remove());return copy.textContent;})()})));
const before=await getBodies();assert.equal(before.length,2);const toggle=page.getByRole('checkbox',{name:'Show changes',exact:true});assert.equal(await toggle.isChecked(),false);await page.screenshot({path:path.join(__dirname,'both-clean-desktop.png'),fullPage:true});
await toggle.check();assert.ok(await page.locator('ins,del').count()>0);assert.deepStrictEqual(await getBodies(),before);await page.screenshot({path:path.join(__dirname,'both-changes-desktop.png'),fullPage:true});await page.emulateMedia({forcedColors:'active'});const markers=await page.locator('ins,del').evaluateAll(nodes=>nodes.map(n=>({tag:n.tagName,decoration:getComputedStyle(n).textDecorationLine})));assert.ok(markers.some(n=>n.tag==='DEL'&&n.decoration.includes('line-through')));assert.ok(markers.some(n=>n.tag==='INS'&&n.decoration.includes('underline')));await page.screenshot({path:path.join(__dirname,'both-changes-forced-colors.png'),fullPage:true});await page.emulateMedia({forcedColors:'none'});checks.push('Change markings remain distinguishable without color');await toggle.uncheck();assert.equal(await page.locator('ins,del').count(),0);assert.deepStrictEqual(await getBodies(),before);checks.push('Diff on/off keeps both passage strings exact');
await page.reload();await page.locator('[data-reading-comparison]').waitFor();assert.equal(await toggle.isChecked(),false);checks.push('Diff preference restored after reload');const listen=page.locator('[data-reading-comparison] section').first().getByRole('button',{name:/^Listen/});await listen.click();await page.locator('[data-reading-comparison] section').first().getByRole('button',{name:/^Stop/}).click();assert.equal(await page.locator('[data-reading-comparison] section').first().getByRole('button',{name:/^Listen/}).count(),1);const heard=await page.evaluate(()=>window.fixture.events.find(e=>e.type==='speak'));assert.equal(heard.text,await page.evaluate(()=>window.fixture.source));assert.equal(heard.language,'English');checks.push('Original-pane audio receives exact source and can be stopped directly');
for(const width of [390,320]){await page.setViewportSize({width,height:900});await page.screenshot({path:path.join(__dirname,'both-clean-'+width+'.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,'overflow at '+width);}checks.push('Both view fits 390px and 320px widths');
await page.getByRole('button',{name:'Original',exact:true}).click();await page.locator('[data-original-source]').waitFor();const cleanOriginal=await page.locator('[data-original-source]').evaluate(n=>{const copy=n.cloneNode(true);copy.querySelectorAll('[data-reading-gloss]').forEach(x=>x.remove());return copy.textContent;});assert.equal(cleanOriginal,await page.evaluate(()=>window.fixture.source));checks.push('Original reader preserves exact CRLF and punctuation with additive glosses');
await page.screenshot({path:path.join(__dirname,'original-glosses-320.png'),fullPage:true});
const glossToggle=page.getByRole('checkbox',{name:'Show glosses',exact:true});if(await glossToggle.count()){const prior=await glossToggle.isChecked();await glossToggle.setChecked(!prior);await glossToggle.setChecked(prior);checks.push('Gloss visibility can be toggled');}
await page.setViewportSize({width:1280,height:1000});await page.screenshot({path:path.join(__dirname,'original-glosses-desktop.png'),fullPage:true});
assert.deepStrictEqual(errors,[]);checks.push('No browser runtime errors');fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({checks,errors,scope:'Real reader module in isolated stateful fixture; audio and AI callbacks mocked.'},null,2));console.log(JSON.stringify({checks,errors}));
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
