// AlloFlow Section: __pre_core__
// Module: core/bootstrap
// Source lines: 1–285 (285 lines)
// Hash: 70681f432115afb7
// Extracted: 2026-04-02T18:54:31.213Z
// Variant: web
// DO NOT EDIT — re-generated by scripts/extract_modules.js
// @mode react
/*
    AlloFlow - Adaptive Levels, Layers, & Outputs
    Copyright (C) 2026 Aaron Pomeranz, PsyD
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, version 3
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.
    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
import React, { useState, useEffect, useRef, useCallback, useContext, useMemo, useReducer } from 'react';
import ReactDOM from 'react-dom';
import { ArrowRight, ArrowLeft, ArrowUp, ArrowDown, ArrowUpRight, ChevronUp, ChevronDown, ChevronLeft, ChevronRight, Move, ExternalLink, DoorOpen, Link } from 'lucide-react';
import { CheckCircle, CheckCircle2, CheckSquare, Check, AlertCircle, AlertTriangle, XCircle, Info, Lightbulb, ShieldCheck, Loader2, Ban, Octagon, X } from 'lucide-react';
import { Save, SaveAll, Download, Upload, Copy, Send, Search, Plus, Trash2, Pencil, Edit2, PenTool, Bold, Italic, Highlighter, RefreshCw, Filter, Lock, Unlock, Wrench, Wand2, Scissors, GripVertical, GripHorizontal } from 'lucide-react';
import { Volume2, VolumeX, StopCircle, Mic, MicOff, Play, PlayCircle, Pause, Music, Headphones, Shuffle, Ear, MonitorPlay } from 'lucide-react';
import { Activity, Inbox, BookOpen, Globe, Layers, Sparkles, FileText, Layout, HelpCircle, CircleHelp,
  Image as ImageIcon, Quote, FileDown, Palette, Printer, History, Heart, Code, Clock, Settings2,
  MessageSquare, Smile, FileQuestion, GitMerge, ListChecks, Maximize, Minimize, Maximize2, Minimize2,
  GalleryHorizontal, Languages, ClipboardList, Gamepad2, ScanLine, Users, FolderDown, FolderUp,
  School, GraduationCap, Map as MapIcon, List, Share2, Cloud, CloudOff, Wifi, WifiOff, Brain,
  Trophy, Flag, GitCompare, Folder, FolderPlus, FolderOpen, FolderInput, Backpack, Zap, ZapOff,
  Calculator, Cpu, Settings, ListOrdered, MessageCircleQuestion, Terminal, AlignJustify, ShoppingBag,
  Unplug, Star, UserCircle2, Scale, Monitor, User, Key, UserCheck, Package, BarChart2, BarChart3,
  Type, Sun, Moon, Eye, EyeOff, MousePointerClick, ScanSearch, Calendar, TrendingUp,
  Award, Target
} from 'lucide-react';

// Local-only: no Firebase or cloud backends

// WebSearchProvider + AIProvider loaded from ai_backend_module.js (or not needed for local-only)
let WebSearchProvider = null;
let AIProvider = null;
let _AUDIO_BANK = null;
const _AUDIO_BANK_URL = 'https://raw.githubusercontent.com/Apomera/AlloFlow/main/audio_bank.json';
function getAudio(category, key) {
    if (!_AUDIO_BANK) return null;
    if (_AUDIO_BANK[category] && _AUDIO_BANK[category][key]) return _AUDIO_BANK[category][key];
    if (_AUDIO_BANK['misc'] && _AUDIO_BANK['misc'][key]) return _AUDIO_BANK['misc'][key];
    return null;
}
async function _initAudioBank() {
    console.log("Initializing Audio Bank from " + _AUDIO_BANK_URL);
    try {
        const response = await fetch(_AUDIO_BANK_URL);
        if (!response.ok) throw new Error("HTTP " + response.status);
        _AUDIO_BANK = await response.json();
        console.log("Audio Bank loaded successfully. Categories:", Object.keys(_AUDIO_BANK));
        window.dispatchEvent(new Event('audio_bank_loaded'));
    } catch (err) {
        console.warn("[AudioBank] Auto-fetch failed:", err.message, "- Use the Upload button in the header to load audio_bank.json manually.");
    }
}
_initAudioBank();
window.addEventListener('audio_bank_loaded', () => {
    // Use try/catch because these let-declared cache variables may not yet be
    // initialized when this event fires (TDZ in bundled single-scope output).
    try { _CACHE_PHONEME_AUDIO_BANK = null; } catch(e) {}
    try { _CACHE_INSTRUCTION_AUDIO = null; } catch(e) {}
    try { _CACHE_LETTER_NAME_AUDIO = null; } catch(e) {}
    try { _CACHE_ISOLATION_AUDIO = null; } catch(e) {}
    console.log("[AudioBank] Caches invalidated - audio data now available.");
});
let _CACHE_WORD_AUDIO_BANK = null;
async function loadWordAudioBank() {
    if (_CACHE_WORD_AUDIO_BANK) return;
    // word_audio_bank.json not yet published to GitHub — skip fetch to prevent 404 console noise.
    // Re-enable this block once the file is uploaded to the repo.
    _CACHE_WORD_AUDIO_BANK = {};
    return;
    /* --- original fetch (re-enable when file exists) ---
    try {
        const response = await fetch("https://raw.githubusercontent.com/Apomera/AlloFlow/main/word_audio_bank.json");
        if (!response.ok) throw new Error("HTTP " + response.status);
        _CACHE_WORD_AUDIO_BANK = await response.json();
        console.log("Word Audio Bank loaded successfully. Categories:", Object.keys(_CACHE_WORD_AUDIO_BANK).length);
    } catch (err) {
        console.warn("[WordAudioBank] Auto-fetch failed:", err.message);
        _CACHE_WORD_AUDIO_BANK = {}; 
    }
    */
}
// #region --- CONFIGURATION & SETUP ---
// Local-only configuration: no Firebase or cloud backends

// ─── Data Layer (LocalStorage-Only) ─────────────────────────────────────────
// Local storage backend only. All session CRUD flows through localStorage.
// No PocketBase, Firebase, or external backends.
let alloData = null; // Set via minimal shim below
const _initAlloData = async () => {
    // Minimal data layer: just expose localStorage
    alloData = {
        backend: 'localStorage',
        // Session CRUD stubs (for compatibility with existing code)
        createSession: (data) => data,
        readSession: (id) => null,
        updateSession: (id, data) => data,
        deleteSession: (id) => true,
    };
    console.log('[AlloFlow] DataProvider initialized: backend=localStorage');
    return alloData;
};
_initAlloData();
const appId = 'alloflow-local-app';
const apiKey = ''; // Local-only, no API key needed
const fisherYatesShuffle = (arr) => {
  const shuffled = [...arr];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};
window.fisherYatesShuffle = fisherYatesShuffle;
const STYLE_POINTER_EVENTS_NONE = { pointerEvents: 'none' };
const STYLE_IMAGE_PIXELATED = { imageRendering: 'pixelated' };
const STYLE_TEXT_SHADOW_WHITE = { textShadow: '0 2px 4px rgba(255,255,255,1)' };
const STYLE_ANIMATION_DELAY_HALF = { animationDelay: '0.5s' };
const TRANSLATION_VERSION = 'v1';
const DOM_TO_TOOL_ID_MAP = {
  'ui-tool-wordsounds': 'word-sounds-generator',
  'tour-input-panel': 'source-input',
  'ui-tool-glossary': 'glossary',
  'ui-tool-simplified': 'simplified',
  'tour-tool-outline': 'outline',
  'tour-tool-visual': 'image',
  'tour-tool-faq': 'faq',
  'tour-tool-scaffolds': 'sentence-frames',
  'tour-tool-brainstorm': 'brainstorm',
  'tour-tool-timeline': 'timeline',
  'tour-tool-concept-sort': 'concept-sort',
  'tour-tool-math': 'math',
  'tour-tool-adventure': 'adventure',
  'ui-tool-quiz': 'quiz',
  'tour-tool-alignment': 'alignment-report',
  'tour-tool-lesson-plan': 'lesson-plan',
  'tour-tool-analysis': 'analysis',
  'tour-tool-persona': 'persona',
  'tour-tool-fullpack': 'lesson-plan',
};
const APP_CONFIG = {
  _cfg_validation_key: "",
  features: {
    adventureMode: true,
    mathSolver: true,
    answerKeys: true,
    scaffolds: true
  }
};
const TEACHER_ONLY_TYPES = [
    'lesson-plan',
    'udl-advice',
    'brainstorm',
    'alignment-report'
];
let globalAudioCtx = null;
let globalTtsQueue = Promise.resolve();
let globalBotTtsQueue = Promise.resolve();
let globalTtsUrlCache = new Map();
let globalTtsRateLimitedUntil = 0;
const safeGetItem = (key, fallback = null) => {
    try { return localStorage.getItem(key); } catch(e) { return fallback; }
};
const safeSetItem = (key, value) => {
    try { localStorage.setItem(key, value); } catch(e) { /* silent - storage unavailable */ }
};
const safeRemoveItem = (key) => {
    try { localStorage.removeItem(key); } catch(e) { /* silent */ }
};
const sanitizeHtml = (html) => {
    if (!html || typeof html !== 'string') return '';
    let clean = html.replace(/<script[\s\S]*?<\/script>/gi, '');
    clean = clean.replace(/\s+on\w+\s*=\s*["'][^"']*["']/gi, '');
    clean = clean.replace(/\s+on\w+\s*=\s*\S+/gi, '');
    clean = clean.replace(/<\/?(iframe|object|embed|form|link|meta|base)[^>]*>/gi, '');
    clean = clean.replace(/href\s*=\s*["']?javascript:/gi, 'href="');
    clean = clean.replace(/src\s*=\s*["']?javascript:/gi, 'src="');
    return clean;
};
let globalMuteEnabled = safeGetItem('alloflow-global-muted') === 'true';
let globalCachedKey = "";
const getGlobalAudioContext = () => {
    if (globalAudioCtx) return globalAudioCtx;
    const AudioContext = window.AudioContext || window.webkitAudioContext;
    if (AudioContext) {
        globalAudioCtx = new AudioContext();
    }
    return globalAudioCtx;
};
window.getGlobalAudioContext = getGlobalAudioContext;
const setGlobalMute = (muted) => {
    globalMuteEnabled = muted;
    safeSetItem('alloflow-global-muted', muted ? 'true' : 'false');
    window.dispatchEvent(new CustomEvent('alloflow-mute-changed', { detail: { muted } }));
};
const isGlobalMuted = () => globalMuteEnabled;
