// AlloFlow Section: __main_app__
// Module: app/main
// Source lines: 68821–68853 (33 lines)
// Hash: 69cf5eeaded7ab26
// Extracted: 2026-04-02T18:54:31.213Z
// Variant: web
// DO NOT EDIT — re-generated by scripts/extract_modules.js
function App() {
  return (
    <LanguageProvider>
      <AlloFlowContent />
    </LanguageProvider>
  );
}
export default function WrappedApp() {
  return (
    <AlloFlowErrorBoundary>
      <App />
    </AlloFlowErrorBoundary>
  );
}
if (typeof __firebase_config !== 'undefined') {
  const container = document.getElementById('root');
  if (container) {
    if (ReactDOM.createRoot) {
       const originalConsoleError = console.error;
       console.error = (...args) => {
         if (typeof args[0] === 'string' && args[0].includes('You are calling ReactDOMClient.createRoot()')) {
           return;
         }
         originalConsoleError(...args);
       };
       const root = ReactDOM.createRoot(container);
       root.render(React.createElement(AlloFlowErrorBoundary, null, React.createElement(App)));
    } else {
       ReactDOM.render(React.createElement(AlloFlowErrorBoundary, null, React.createElement(App)), container);
    }
  }
}
// #endregion