const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');const out='reports/video-studio-prepared-files-2026-09-19',html=fs.readFileSync('video_studio/video_studio.html','utf8');const vsReadZip=new Function(html.slice(html.indexOf('  function vsFormatTimestamp('),html.indexOf('// [VS_SHARED_END]'))+';return vsReadZip;')();
(async()=>{const browser=await chromium.launch({headless:true});try{
 const p=await browser.newPage({viewport:{width:1360,height:960}}),errors=[];p.setDefaultTimeout(90000);p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith('http://studio.test/')?r.fulfill({contentType:'text/html',body:html}):r.abort());await p.goto('http://studio.test/');
 const bytes=fs.readFileSync('reports/video-studio-usability-2026-09-08/regression/export-fixture.webm');await p.locator('#importInput').setInputFiles({name:'Prepared lesson.webm',mimeType:'video/webm',buffer:bytes});await p.waitForFunction(()=>document.querySelector('#editVideo').duration>0);await p.locator('#editorFocusMode').selectOption('all');await p.locator('#importCapInput').setInputFiles({name:'lesson.vtt',mimeType:'text/vtt',buffer:Buffer.from('WEBVTT\n\n00:00:00.400 --> 00:00:01.500\nOriginal prepared caption\n')});await p.locator('#trimStart').fill('0.3');await p.locator('#trimStart').blur();await p.locator('#tabExport').click();await p.locator('#exportPreset').selectOption('small');await p.locator('#capMode').selectOption('none');await p.locator('#titleInput').fill('First export');await p.locator('#exportContainer').selectOption('webm');await p.locator('#exportBtn').click();await p.locator('#resultCard').waitFor({state:'visible',timeout:60000});
 await p.waitForFunction(()=>document.querySelector('#preparedFileHint').textContent.startsWith('Up to date'));assert.equal(await p.locator('#preparedUpdateBtn').isVisible(),false);await p.waitForFunction(()=>document.querySelector('#thumbStatus').textContent.startsWith('Thumbnail ready'));assert.match(await p.locator('#thumbPreview').getAttribute('src'),/^data:image\/jpeg/);
 await p.locator('#tabEdit').click();const caption=p.getByRole('textbox',{name:'text for caption 1',exact:true});await caption.fill('New caption after exporting');await caption.blur();await p.locator('#tabExport').click();assert.match(await p.locator('#preparedFileHint').textContent(),/Changes since export/);assert.equal(await p.locator('#preparedUpdateBtn').isVisible(),true);
 const download=async(id,name)=>{const pending=p.waitForEvent('download');await p.locator(id).click();const d=await pending;await d.saveAs(out+'/'+name);return fs.readFileSync(out+'/'+name);};
 const transcript=await download('#downloadTranscriptResultBtn','original-transcript.txt');assert.match(transcript.toString(),/Original prepared caption/);assert.doesNotMatch(transcript.toString(),/New caption/);
 const archive=await download('#downloadProjectResultBtn','prepared.allopack');const entries=vsReadZip(archive),vtt=Buffer.from(entries.find(e=>e.name.endsWith('.vtt')).data).toString();assert.match(vtt,/Original prepared caption/);assert.doesNotMatch(vtt,/New caption/);assert.match(vtt,/00:00:00.100 --> 00:00:01.200/);
 // Undo restores export parity, and preview-only speed does not mark an export stale.
 await p.locator('#tabEdit').click();await p.locator('#captionUndoBtn').click();await p.locator('#previewSpeed').selectOption('2');await p.locator('#tabExport').click();assert.match(await p.locator('#preparedFileHint').textContent(),/^Up to date/);
 await p.locator('#titleInput').fill('Updated export');assert.match(await p.locator('#preparedFileHint').textContent(),/Changes since export/);await p.locator('#preparedUpdateBtn').click();await p.waitForFunction(()=>document.querySelector('#preparedFileSummary').textContent.includes('Updated export')&&document.querySelector('#preparedFileHint').textContent.startsWith('Up to date'),null,{timeout:60000});assert.equal(await p.locator('#preparedUpdateBtn').isVisible(),false);
 await p.locator('#importInput').setInputFiles({name:'Other lesson.webm',mimeType:'video/webm',buffer:bytes});await p.waitForFunction(()=>document.querySelectorAll('#takesList .take').length===2);await p.locator('#tabExport').click();assert.match(await p.locator('#preparedFileHint').textContent(),/another take/);assert.equal(await p.locator('#preparedUpdateBtn').textContent(),'Prepare selected take');await p.locator('#preparedSourceBtn').click();assert.equal(await p.locator('#titleInput').inputValue(),'Updated export');assert.match(await p.locator('#preparedFileHint').textContent(),/^Up to date/);
 await p.locator('#captionPosition').selectOption('top');assert.match(await p.locator('#preparedFileHint').textContent(),/Changes since export/);await p.locator('#preparedFileSummary').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/prepared-desktop.png'});await p.setViewportSize({width:390,height:844});await p.locator('#preparedFileSummary').scrollIntoViewIfNeeded();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await p.screenshot({path:out+'/prepared-mobile.png'});
 // Changing thumbnail settings rebuilds the actual preview; downloading yields JPEG bytes.
 await p.locator('#thumbTitleOverlay').uncheck();await p.waitForFunction(()=>document.querySelector('#thumbStatus').textContent.startsWith('Thumbnail ready'));const thumb=await download('#downloadThumbBtn','thumbnail.jpg');assert.equal(thumb[0],255);assert.equal(thumb[1],216);
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({passed:true,checks:['fresh export state','caption edits mark stale','undo clears stale state','preview speed ignored','settings mark stale','one-click updated export','another-take state and return shortcut','prepared transcript and bundled VTT preserved with trimmed timings','real thumbnail rebuild and JPEG download','mobile fit'],errors},null,2));console.log('Prepared-file browser checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
