const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'../../..');process.chdir(root);
const baseline=process.argv.includes('--baseline');const result={date:new Date().toISOString(),baseline,checks:[],scans:[],errors:[]};
const prior=fs.readFileSync('tests/history_panel_theme.test.js','utf8');const fixtures=prior.slice(prior.indexOf('const history = ['),prior.indexOf('\nfunction App('));
const source=fs.readFileSync('view_history_panel_source.jsx','utf8'),strings=JSON.parse(fs.readFileSync('ui_strings.js','utf8')),dictionary={};
for(const m of source.matchAll(/\bt\('([^']+)'/g)){const value=m[1].split('.').reduce((a,k)=>a?.[k],strings);if(typeof value==='string')dictionary[m[1]]=value;}
const setup='const noop=()=>{};'+fixtures+'\n'+
'const dictionary='+JSON.stringify(dictionary)+'; const t=(key,p={})=>{let v=dictionary[key];for(const [k,x] of Object.entries(p||{}))if(v)v=v.replaceAll("{"+k+"}",String(x));return v;};'+
'const fixtureRoot=ReactDOM.createRoot(document.getElementById("root"));'+
'function Fixture({theme,emptyUnits,removeOnMove}) { const [movingItemId,setMovingItemId]=React.useState(null),[rows,setRows]=React.useState(history);return React.createElement(AlloThemeContext.Provider,{value:{theme,colorOverlay:"none"}},React.createElement("main",{className:"fixed inset-0 overflow-auto "+(theme==="light"?"theme-default":"theme-"+theme)},React.createElement(AlloModules.AppStyles.AppStyles),React.createElement("div",{style:{width:"100%",maxWidth:420,padding:12}},React.createElement(AlloModules.HistoryPanel.HistoryPanel,{...makeProps(),t,history:rows,getFilteredHistory:()=>rows,movingItemId,setMovingItemId,handleSetMovingItemIdToNull:()=>setMovingItemId(null),units:emptyUnits?[]:[{id:"unit-1",name:"Biology"},{id:"unit-2",name:"Chemistry"},{id:"unit-3",name:"Physics"}],handleMoveToUnit:(id,unit)=>{window.moves.push({id,unit});setMovingItemId(null);if(removeOnMove)setRows([]);}}))));}'+
'let version=0;window.renderHistory=(theme,options={})=>{window.moves=[];ReactDOM.flushSync(()=>fixtureRoot.render(React.createElement(Fixture,{key:++version,theme,...options})));};';
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>History Move menu audit</title></head><body><div id="root"></div></body></html>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});result.browser=browser.version();
try{for(const theme of ['light','dark','contrast']){const page=await browser.newPage({viewport:{width:420,height:900}});page.setDefaultTimeout(4000);page.on('pageerror',e=>result.errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
for(const file of ['desktop/web-app/node_modules/react/umd/react.development.js','desktop/web-app/node_modules/react-dom/umd/react-dom.development.js'])await page.addScriptTag({path:path.join(root,file)});
await page.evaluate(()=>{window.AlloThemeContext=React.createContext({theme:'light'});window.AlloModules={};for(const name of ['AlertCircle','ChevronDown','ChevronUp','Cloud','CloudOff','Download','Folder','FolderInput','FolderOpen','FolderPlus','GripVertical','History','Lock','Maximize','Minimize','Pencil','RefreshCw','Save','Search','Settings','Share2','Trash2','Upload','X'])window[name]=()=>null;localStorage.setItem('alloflow_stem_stations','[]');localStorage.setItem('alloflow_sel_stations','[]');});
const cssDir=path.join(root,'app/static/css');await page.addStyleTag({path:path.join(cssDir,fs.readdirSync(cssDir).find(f=>/^main\.[a-z0-9]+\.css$/i.test(f)))});
for(const file of ['app_styles_module.js',baseline?'reports/wcag-audit-2026-09-19/history-move-menu/before-history-module.js':'view_history_panel_module.js','node_modules/axe-core/axe.min.js'])await page.addScriptTag({path:path.join(root,file)});await page.addScriptTag({content:setup});
const trigger=()=>page.locator('[data-help-key="history_move_to_unit_btn"]').first();const menu=()=>page.locator('[id^="history-move-menu-"]');const items=()=>menu().getByRole('menuitem');
async function reset(options={}){await page.evaluate(([theme,options])=>window.renderHistory(theme,options),[theme,options]);await trigger().waitFor();await page.waitForFunction(()=>!document.querySelector('[id^="history-move-menu-"]'));}
async function focused(locator){await page.waitForFunction(el=>el===document.activeElement,await locator.elementHandle());}
async function check(name,fn){try{await reset();await fn();result.checks.push({theme,name,passed:true});}catch(e){result.checks.push({theme,name,passed:false,error:e.message});}console.log(theme,name,result.checks.at(-1).passed?'PASS':'FAIL');}
async function open(key='Enter'){await trigger().focus();await page.keyboard.press(key);await menu().waitFor();}
await check('closed ARIA relationship',async()=>{assert.equal(await trigger().getAttribute('aria-controls'),null);assert.equal(await trigger().getAttribute('aria-expanded'),'false');});
await check('Enter, arrows, Home/End, typeahead, Escape',async()=>{await open();await focused(items().first());assert.equal(await menu().getAttribute('aria-labelledby'),await trigger().getAttribute('id'));await page.keyboard.press('ArrowUp');await focused(items().last());await page.keyboard.press('ArrowDown');await focused(items().first());await page.keyboard.press('End');await focused(items().last());await page.keyboard.press('Home');await focused(items().first());await page.keyboard.press('c');await focused(items().nth(2));await page.keyboard.press('Escape');await focused(trigger());assert.equal(await menu().count(),0);assert.equal(await trigger().getAttribute('aria-controls'),null);});
await check('ArrowUp opens last; Space opens first',async()=>{await open('ArrowUp');await focused(items().last());await page.keyboard.press('Escape');await open('Space');await focused(items().first());});
await check('Tab exits forward and closes',async()=>{await trigger().focus();await page.keyboard.press('Tab');const next=await page.evaluateHandle(()=>document.activeElement);await open();await page.keyboard.press('Tab');assert.equal(await menu().count(),0);await page.waitForFunction(el=>document.activeElement===el,next);});
await check('Shift+Tab exits backward and closes',async()=>{await open();await page.keyboard.press('Shift+Tab');assert.equal(await menu().count(),0);await focused(page.locator('[data-help-key="history_move_down_btn"]').first());});
await check('selection invokes callback once and restores trigger',async()=>{await open();await items().nth(2).focus();await page.keyboard.press('Enter');await focused(trigger());assert.equal(await menu().count(),0);const moves=await page.evaluate(()=>window.moves);assert.equal(moves.length,1);assert.equal(moves[0].unit,'unit-2');assert.ok(moves[0].id);});
await check('selection removing resource restores unit filter',async()=>{await reset({removeOnMove:true});await open();await items().nth(1).focus();await page.keyboard.press('Enter');await focused(page.locator('[data-help-key="history_filter_unit_select"]'));assert.equal(await menu().count(),0);assert.equal((await page.evaluate(()=>window.moves)).length,1);});
await check('empty units remain keyboard operable',async()=>{await reset({emptyUnits:true});await open();assert.equal(await items().count(),1);await focused(items().first());await page.keyboard.press('ArrowUp');await focused(items().first());await page.keyboard.press('Escape');await focused(trigger());});
await check('outside pointer dismissal',async()=>{await open();await page.locator('[data-help-key="history_filter_unit_select"]').click();assert.equal(await menu().count(),0);});
await reset();await open();result.scans.push({theme,...await page.evaluate(async()=>{const r=await axe.run(document.getElementById('tour-history-panel'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22a','wcag22aa']}});return{violations:r.violations,incomplete:r.incomplete};})});
await page.setViewportSize({width:320,height:600});
await check('320px menu focus is visible and not clipped',async()=>{await open();await items().last().focus();await focused(items().last());const bounds=await items().last().evaluate(el=>{const r=el.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,visible:el.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2))};});assert.ok(bounds.left>=0&&bounds.right<=320&&bounds.top>=0&&bounds.bottom<=600,JSON.stringify(bounds));assert.ok(bounds.visible,JSON.stringify(bounds));await page.screenshot({path:path.join(__dirname,(baseline?'baseline-':'')+theme+'-320-menu.png')});});
await page.close();}
}catch(e){result.errors.push(e.stack);console.error(e);}finally{result.passed=!result.errors.length&&result.checks.length===30&&result.checks.every(c=>c.passed)&&result.scans.length===3&&result.scans.every(s=>!s.violations.length);fs.writeFileSync(path.join(__dirname,baseline?'baseline.json':'results.json'),JSON.stringify(result,null,2));await browser.close();await new Promise(r=>server.close(r));if(!result.passed&&!baseline)process.exitCode=1;console.log(JSON.stringify({passed:result.passed,checks:result.checks.length,failed:result.checks.filter(c=>!c.passed).map(c=>c.theme+': '+c.name),errors:result.errors}));}})();
