'use strict';
const fs=require('fs'),vm=require('vm'),dir=__dirname;
const file='stem_lab/stem_tool_geometryworld_builder.js',raw=fs.readFileSync(file,'utf8'),crlf=raw.includes('\r\n');let s=raw.replace(/\r\n/g,'\n');
function replace(a,b){if(!s.includes(a)||s.indexOf(a)!==s.lastIndexOf(a))throw Error('Anchor not unique: '+a.slice(0,110));s=s.replace(a,b);}
function section(a,b,text){const start=s.indexOf(a),end=s.indexOf(b,start);if(start<0||end<0)throw Error(a);s=s.slice(0,start)+text+'\n'+s.slice(end);}
section('  // Curated recipes use','  var WORLD_SHELF_KEY',fs.readFileSync('reports/geometry-world-design-2026-09-12/starters.txt','utf8').replace(/\r\n/g,'\n'));
replace('y<4+Math.floor((h-7)/3)','y<5+Math.floor((h-7)/3)');
replace('  function workshopScreenSelection(engine,rect,viewport) {','  function workshopScreenSelection(engine,rect,viewport,depth) {');
replace('    engine.camera.updateMatrixWorld(true);\n    return Object.keys(engine.blocks||{})',`    engine.camera.updateMatrixWorld(true);
    var ray=depth==='visible'?new THREE.Raycaster():null,targets=ray?(engine.getRaycastTargets?engine.getRaycastTargets():Object.values(engine.blocks)):null;
    if(ray && engine.scene)engine.scene.updateMatrixWorld(true);
    function visible(mesh){if(!ray)return true;mesh.geometry.computeBoundingBox();var center=mesh.geometry.boundingBox.getCenter(new THREE.Vector3()).applyMatrix4(mesh.matrixWorld),ndc=center.project(engine.camera);ray.setFromCamera(new THREE.Vector2(ndc.x,ndc.y),engine.camera);var hits=ray.intersectObjects(targets);return !!hits.length && hits[0].object===mesh;}
    return Object.keys(engine.blocks||{})`);
replace('x<=rect.right && y>=rect.top && y<=rect.bottom;','x<=rect.right && y>=rect.top && y<=rect.bottom && visible(m);');
replace('function installWorkshopPointer(engine,canvas,mode,operation,onSelection,onExit)', 'function installWorkshopPointer(engine,canvas,mode,operation,onSelection,onExit,depth)');
replace('bottom:Math.max(start.y,e.clientY)},v);','bottom:Math.max(start.y,e.clientY)},v,depth);');
replace('  function previewPrintPreparation(engine,kind) {',fs.readFileSync('reports/geometry-world-design-2026-09-12/handles.txt','utf8').replace(/\r\n/g,'\n')+'\n  function previewPrintPreparation(engine,kind) {');
replace('architecturalStarters:architecturalStarters,','architecturalStarters:architecturalStarters, configureArchitecturalStarter:configureArchitecturalStarter, workshopDragOffset:workshopDragOffset, installWorkshopTransform:installWorkshopTransform,');
replace("      var _pointerMode=React.useState('build')", "      var _starterOptions=React.useState({}),starterOptions=_starterOptions[0],setStarterOptions=_starterOptions[1];\n      var _selectionDepth=React.useState('visible'),selectionDepth=_selectionDepth[0],setSelectionDepth=_selectionDepth[1];\n      var _pointerMode=React.useState('build')");
replace('      var projectCards=React.useMemo',`      var configuredStarter=React.useMemo(function(){return configureArchitecturalStarter(starterId,starterOptions);},[starterId,starterOptions]);
      var configuredStarterImage=React.useMemo(function(){return starterOpen && configuredStarter.ok?'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(activitySnapshotSvg({blocks:configuredStarter.stamp.blocks})):'';},[starterOpen,configuredStarter]);
      function setStarterOption(key,value){setStarterOptions(function(previous){var next=Object.assign({},previous);next[key]=value;return next;});cancelSelectionPreview();}
      var projectCards=React.useMemo`);
replace("setStarterCategory(c);setStarterId(starters.find", "setStarterCategory(c);setStarterOptions({});setStarterId(starters.find");
replace('setStarterId(s.id);cancelSelectionPreview();','setStarterId(s.id);setStarterOptions({});cancelSelectionPreview();');
replace("          renderCoordinateInputs('gwe-starter-corner'",`          h('div',{className:'gwe-starter-custom'},h('h4',null,'Make it yours'),
            configuredStarterImage && h('img',{className:'gwe-configured-preview',src:configuredStarterImage,alt:'Preview of your customized starter'}),
            h('div',{className:'gwe-starter-dimensions'},Object.keys((starters.find(function(s){return s.id===starterId;})||starters[0]).fields).map(function(key){var field=(starters.find(function(s){return s.id===starterId;})||starters[0]).fields[key];return h('label',{key:key},key==='rise'?'Roof rise':key.charAt(0).toUpperCase()+key.slice(1),h('input',{type:'number',inputMode:'numeric','aria-label':'Starter '+key,min:field[1],max:field[2],step:field[3]||1,value:starterOptions[key]===undefined?field[0]:starterOptions[key],onChange:function(e){setStarterOption(key,e.target.value);}}));})),
            h('p',{className:'gwe-builder-note'},'Dimensions are in blocks. Each block stays editable.'),
            h('label',{className:'gwe-edit-label'},'Materials',h('select',{'aria-label':'Starter materials',value:starterOptions.palette||'original',onChange:function(e){setStarterOption('palette',e.target.value);}},[['original','Original palette'],['timber','Warm timber'],['stone','All stone'],['brick','All brick']].map(function(a){return h('option',{value:a[0],key:a[0]},a[1]);}))),
            h('label',{className:'gwe-edit-label'},'Rotation',h('select',{'aria-label':'Starter rotation',value:starterOptions.rotation||0,onChange:function(e){setStarterOption('rotation',e.target.value);}},[0,1,2,3].map(function(turn){return h('option',{key:turn,value:turn},turn*90+'°');}))),
            h('p',{role:'status',className:'gwe-builder-note'},configuredStarter.ok?configuredStarter.stamp.blocks.length+' editable blocks ready to preview.':configuredStarter.reason),
            h('button',{type:'button',onClick:function(){setStarterOptions({});cancelSelectionPreview();}},'Reset starter options')),
          renderCoordinateInputs('gwe-starter-corner'`);
replace("h('button',{type:'button',onClick:function(){var s=starters.find(function(s){return s.id===starterId;})||starters[0],result=previewBuildStamp", "h('button',{type:'button',disabled:!configuredStarter.ok,onClick:function(){if(!configuredStarter.ok)return;var s=configuredStarter.stamp,result=previewBuildStamp");
replace("[['build','Build'],['select','Select blocks'],['orbit','Orbit camera']]", "[['build','Build'],['select','Select blocks'],['transform','Move handles'],['orbit','Orbit camera']]");
replace("'aria-pressed':pointerMode===m[0],onClick:", "'aria-pressed':pointerMode===m[0],disabled:m[0]==='transform' && !hasRetainedSelection,onClick:");
replace("pointerMode==='select'?'Click one block or drag a rectangle. The rectangle includes blocks behind the visible surface. Escape returns to building.':pointerMode==='orbit'?", "pointerMode==='select'?'Click a block or drag a rectangle. Choose visible block centers or include hidden blocks below. Shift adds; Alt removes. Escape returns to building.':pointerMode==='transform'?'Drag an axis to preview a grid move. Arrow keys move one block; Shift moves five. The circular arrow previews a 90° rotation around the footprint corner. Apply commits; Escape cancels.':pointerMode==='orbit'?");
replace("          pointerMode==='select' && h('label',{className:'gwe-edit-label'},'Selection action'", "          pointerMode==='select' && h('label',{className:'gwe-edit-label'},'Selection depth',h('select',{'aria-label':'Selection depth',value:selectionDepth,onChange:function(e){setSelectionDepth(e.target.value);}},h('option',{value:'visible'},'Visible block centers'),h('option',{value:'all'},'Include hidden blocks'))),\n          pointerMode==='select' && h('label',{className:'gwe-edit-label'},'Selection action'");
replace("      React.useEffect(function(){\n        if(pointerMode==='build'", "      var transformSelectionKey=pointerMode==='transform'?JSON.stringify(engine && engine._builderSelection):'';\n      React.useEffect(function(){\n        if(pointerMode==='build'");
replace('        return live && canvas?installWorkshopPointer', `        if(pointerMode==='transform')return live && canvas?installWorkshopTransform(live,canvas,function(result,offset){setSelectionEditPreview(result);setSelectionEditNotice(result?(result.ok?(offset?'Move '+['X','Y','Z'].map(function(a){return a+' '+offset[a.toLowerCase()];}).join(' · '):'Rotate 90°')+'. Review the outline, then apply.':result.reason):'');},function(){setPointerMode('build');}):undefined;
        return live && canvas?installWorkshopPointer`);
replace("function(){setPointerMode('build');}):undefined;\n      },[engine,pointerMode,selectionOperation", "function(){setPointerMode('build');},selectionDepth):undefined;\n      },[engine,pointerMode,selectionOperation,selectionDepth,transformSelectionKey");
replace("      var additions = [h('style',{key:'gwe-drawing-css'},drawingCss)", "      var additions = [h('style',{key:'gwe-design-css'},"+JSON.stringify(fs.readFileSync(dir+'/style.css','utf8'))+"),h('style',{key:'gwe-drawing-css'},drawingCss)");
replace("pointerMode==='select'?'Select blocks':'Orbit camera'", "pointerMode==='select'?'Select blocks':pointerMode==='transform'?'Move & rotate':'Orbit camera'");
replace("pointerMode==='select'?'Click or drag · '+selectionOperation:'Drag to orbit · Shift-drag to pan'", "pointerMode==='select'?'Click or drag · '+selectionOperation+' · '+(selectionDepth==='visible'?'visible centers':'through depth'):pointerMode==='transform'?(selectionEditNotice || 'Drag an axis · Review · Apply'):'Drag to orbit · Shift-drag to pan'");
replace("pointerMode==='orbit' && h('div',{className:'gwe-pointer-zoom'}", "pointerMode==='transform' && selectionEditPreview && h('div',{className:'gwe-pointer-zoom'},h('button',{type:'button',disabled:!selectionEditPreview.ok,onClick:applyCreationChange},'Apply move or rotation'),h('button',{type:'button',onClick:cancelSelectionPreview},'Cancel move or rotation')),pointerMode==='orbit' && h('div',{className:'gwe-pointer-zoom'}");
new vm.Script(s);fs.writeFileSync(dir+'/builder-before.js',raw);let output=crlf?s.replace(/\n/g,'\r\n'):s;let fd=fs.openSync(file,'r+');fs.writeSync(fd,output);fs.ftruncateSync(fd,Buffer.byteLength(output));fs.closeSync(fd);console.log('Starter customization, selection depth, and transform handles applied.');
