
import React from '../../desktop/web-app/node_modules/react/index.js';
import {createRoot} from '../../desktop/web-app/node_modules/react-dom/client.js';
window.React=React; window.AlloIcons=new Proxy({}, {get:()=>()=>null});
require('../../instructional_context_module.js'); require('../../pure_helpers_module.js'); require('../../phase_n_misc_helpers_module.js'); require('../../view_simplified_module.js');
const pure=window.AlloModules.PureHelpers, phase=window.AlloModules.PhaseNHelpers, View=window.AlloModules.SimplifiedView, api=window.AlloModules.InstructionalContext;
const source='THE RIVER\r\n\r\nBeneath the bridge, the restless river whispered.\r\nMaya paused, listening to its persistent voice.\r\n\r\n“Where are you going?” she asked.\r\nThe water hurried toward the sea.';
const snapshot=api.createSourceSnapshot(source,{language:'English',sourceArtifactId:'analysis-one',selection:'input'});
const original=api.createSupportedReading(snapshot,{id:'original-one',title:'The River — Original with supports'});
const glossStart=source.indexOf('persistent'); original.readingSupports=api.validateReadingSupports(snapshot,[{id:'persistent',kind:'gloss',start:glossStart,end:glossStart+10,quote:'persistent',text:'continuing for a long time'}]);
const adapted={id:'adapted-one',type:'simplified',data:'THE RIVER\r\n\r\nUnder the bridge, the moving river whispered.\r\nMaya stopped and listened to its steady voice.\r\n\r\n“Where are you going?” she asked.\r\nThe water rushed toward the sea.',sourceSnapshot:snapshot,instructionalText:{role:'supplemental',form:'adapted'},config:{language:'English',grade:'5'}};
window.fixture={source,adapted:adapted.data,events:[]}; const noop=()=>{};
function App(){const [history,setHistory]=React.useState(()=>JSON.parse(localStorage.getItem('novak-curation-fixture')||'null')||[original,adapted]);const historyRef=React.useRef(history);historyRef.current=history;const [itemId,setItemId]=React.useState(original.id);const item=history.find(row=>row.id===itemId);const setItem=next=>setItemId(next.id);React.useEffect(()=>localStorage.setItem('novak-curation-fixture',JSON.stringify(history)),[history]);window.fixture.history=history;
const commit=(id,update)=>{let updated;const next=historyRef.current.map(row=>{if(row.id!==id)return row;updated=update(row);return updated;});historyRef.current=next;setHistory(next);return updated;};
const onUpdateReadingSupports=(target,action)=>{const updated=commit(target.id,row=>{const supports=action.type==='upsert'?api.upsertReadingSupport(row,row.readingSupports,action.annotation):action.type==='remove'?api.removeReadingSupport(row,row.readingSupports,action.id):api.setReadingSupportPinned(row,row.readingSupports,action.id,action.pinned);return{...row,readingSupports:supports};});return updated.readingSupports;};
const onGenerateReadingSupports=async target=>{await new Promise(resolve=>{window.fixture.finishGeneration=resolve;});const rest=source.indexOf('restless'),persist=source.indexOf('persistent');const incoming=api.validateReadingSupports(target,[{id:'generated-restless',start:rest,end:rest+8,quote:'restless',text:'moving without settling',priority:'helpful'},{id:'generated-persistent',start:persist,end:persist+10,quote:'persistent',text:'AI replacement should not overwrite teacher wording',priority:'essential'}]);return commit(target.id,row=>({...row,readingSupports:api.mergeReadingSupports(row,row.readingSupports,incoming)})).readingSupports;};
const [compare,setCompare]=React.useState(false),[mode,setMode]=React.useState('read'),[playing,setPlaying]=React.useState(false),[playingId,setPlayingId]=React.useState(null),[theme,setTheme]=React.useState('light'),[focus,setFocus]=React.useState(false),[focused,setFocused]=React.useState(null);
const stop=()=>{setPlaying(false);setPlayingId(null);};
const open=(next,both=false)=>{stop();setItem(next);setCompare(both);};
const t=k=>k.split('.').reduce((v,p)=>v?.[p],window.fixtureStrings)||k;
const props={ComplexityGauge:()=>null,setComplexityLevel:noop,setSaveOriginalOnAdjust:noop,setReadingTheme:setTheme,readingTheme:theme,setSelectionMenu:noop,setIsCustomReviseOpen:noop,setInteractionMode:setMode,setIsCompareMode:setCompare,setIsFluencyMode:noop,stopPlayback:stop,closeDefinition:noop,closePhonics:noop,closeRevision:noop,handleToggleIsEditingLeveledText:noop,t,generatedContent:item,inputText:'Unrelated source must never be shown',gradeLevel:'5',leveledTextLanguage:'English',studentInterests:[],selectedVoice:'Kore',voiceSpeed:1,isTeacherMode:true,isEditingLeveledText:false,isImmersiveReaderActive:false,isCompareMode:compare,isSideBySide:false,isZenMode:true,isProcessing:false,isPlaying:playing,playingContentId:playingId,interactionMode:mode,history,textEditorRef:React.useRef(null),splitTextToSentences:s=>pure.splitTextToSentences(s,{}),getSideBySideContent:()=>null,handleFormatText:noop,handleSimplifiedTextChange:noop,callTTS:noop,handleSpeak:(text,id,idx,restart,language)=>{window.fixture.events.push({type:'speak',text,id,language});setPlayingId(id);setPlaying(true);},handleWordClick:(word,event,context)=>window.fixture.events.push({type:'define',word,context}),handleQuickAddGlossary:noop,handlePhonicsClick:(word,event,context)=>window.fixture.events.push({type:'phonics',word,context}),isLineFocusMode:focus,setIsLineFocusMode:setFocus,focusedParagraphIndex:focused,setFocusedParagraphIndex:setFocused,cursorStyles:{read:'',define:'','add-glossary':'',revise:''},getContentDirection:()=> 'ltr',isRtlLang:()=>false,renderFormattedText:text=>React.createElement('div',null,text),formatInteractiveText:(text,cloze)=>phase.formatInteractiveText(text,cloze,false,{highlightGlossaryTerms:x=>x,latestGlossary:[],MathSymbol:({text})=>text}),SourceReferencesPanel:()=>null,playbackState:{currentIdx:-1},handleTextMouseUp:noop,highlightGlossaryTerms:x=>x,latestGlossary:[],onReadOriginal:()=>open(history.find(row=>row.id===original.id)),onOpenReadingArtifact:open,onUpdateReadingSupports,onGenerateReadingSupports};
return React.createElement('main',{className:'max-w-6xl mx-auto p-4'},React.createElement('h1',{className:'text-2xl font-bold mb-3'},'The River — Word supports'),React.createElement(View,props));}
createRoot(document.getElementById('root')).render(React.createElement(App));
