const fs=require('node:fs'),parser=require('@babel/parser'),traverse=require('@babel/traverse').default,crypto=require('node:crypto');const file='stem_lab/stem_tool_anatomy.js';let s=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),english={};
fs.writeFileSync(__dirname+'/baseline.json',JSON.stringify({sha256:crypto.createHash('sha256').update(s).digest('hex')},null,2));
function T(key,value){english[key]=value;return "t('stem.anatomy."+key+"', "+JSON.stringify(value)+")";}
function rep(a,b,n=1){if(s.split(a).length-1!==n)throw Error('Missing/duplicate '+a.slice(0,110));s=s.split(a).join(b);}
const bank=JSON.parse(fs.readFileSync(__dirname+'/tours.json','utf8'));bank.integumentary[0][1]='The epidermis is the outer skin layer and has no blood vessels. Its barrier reduces water loss and entry of harmful substances; renewal varies with body site, age, and other conditions.';fs.writeFileSync(__dirname+'/tours.json',JSON.stringify(bank,null,2)+'\n');
let tourNode;traverse(parser.parse(s,{sourceType:'script'}),{VariableDeclarator(p){if(p.node.id.name==='GUIDED_TOURS')tourNode=p.node.init;}});if(!tourNode)throw Error('Tours not found');const edits=[];
for(const group of tourNode.properties){const system=group.key.name,rows=bank[system];if(rows.length!==group.value.elements.length)throw Error(system);group.value.elements.forEach((step,i)=>{const id=step.properties.find(p=>p.key.name==='structureId').value.value;if(id!==rows[i][0])throw Error(id);const narration=step.properties.find(p=>p.key.name==='narration').value,base='tour_ref_'+system+'_'+i;edits.push({start:narration.start,end:narration.end,text:T(base+'_narration',rows[i][1])});edits.push({start:step.end-1,end:step.end-1,text:', recall: '+T(base+'_recall',rows[i][2])+", reference: 'https://openstax.org/books/anatomy-and-physiology-2e/pages/"+rows[i][3]+"' "});if(id==='adrenal_endo'){const title=step.properties.find(p=>p.key.name==='title').value;edits.push({start:title.start,end:title.end,text:T('tour_ref_adrenal_title','Adrenal gland: cortex and medulla')});}});}
for(const e of edits.sort((a,b)=>b.start-a.start))s=s.slice(0,e.start)+e.text+s.slice(e.end);
// Bind recap answers to this content version and system. Legacy answers do not score new clues.
rep("var tourRecapActive = tourActive && rawTourRecap.active === true && tourSteps.length >= 2;","var tourRecapActive = tourActive && rawTourRecap.active === true && rawTourRecap.version === 2 && rawTourRecap.systemId === sysKey && tourSteps.length >= 2;");
rep("var tourRecapAnswers = rawTourRecap.answers && typeof rawTourRecap.answers === 'object' && !Array.isArray(rawTourRecap.answers) ? rawTourRecap.answers : {};","var tourRecapAnswers = {};\n        function validTourAnswers(raw,questions){var result={};if(!raw||typeof raw!=='object'||Array.isArray(raw))return result;questions.forEach(function(q){if(q.options.some(function(option){return option.id===raw[q.index];}))result[q.index]=raw[q.index];});return result;}");
rep("stem: clipAtSentence(maskStructureName(item.text, itemContext.structure), 170)","stepIndex: item.stepIndex, explanation: item.text, reference: item.reference, stem: item.recall");
rep("{ structureId: step.structureId, text: step.narration, title: step.title }","{ structureId: step.structureId, text: step.narration, title: step.title, recall: step.recall, reference: step.reference, stepIndex: tourSteps.indexOf(step) }");
rep("          return tourRecapQuestionsMemo;","          tourRecapAnswers = tourRecapActive ? validTourAnswers(rawTourRecap.answers,tourRecapQuestionsMemo) : {};\n          return tourRecapQuestionsMemo;");
const a=s.indexOf('        function answerTourRecap(question, optionId)'),b=s.indexOf('        function completeGuidedTour()',a);if(a<0||b<0)throw Error('Answer bounds');s=s.slice(0,a)+`        function answerTourRecap(question, optionId) {
          if (!tourRecapActive || !question.options.some(function(option){return option.id===optionId;})) return;
          var questions=getTourRecapQuestions(); if(tourRecapAnswers[question.index])return;
          var correct=optionId===question.structureId;
          setLabToolData(function(previous){
            var state=previous.anatomy||{},recap=state._tourRecap||{},systemId=SYSTEMS[state.system]?state.system:'skeletal';
            if(state._tourActive!==true||systemId!==sysKey||recap.active!==true||recap.version!==2||recap.systemId!==sysKey)return previous;
            var answers=validTourAnswers(recap.answers,questions);if(answers[question.index])return previous;
            answers[question.index]=optionId;
            var patch=Object.assign({_tourRecap:{active:true,version:2,systemId:sysKey,answers:answers}},confidenceEvidencePatch(question.structureId,correct,state));
            return Object.assign({},previous,{anatomy:Object.assign({},state,patch)});
          });
          playSound(correct?'quizCorrect':'quizWrong');
          if(typeof announceToSR==='function')announceToSR((correct?t('stem.anatomy.recap_correct','Correct: '):t('stem.anatomy.recap_incorrect','Not quite. It was '))+question.structure.name+'.');
        }
        function focusTourStep(){setTimeout(function(){var panel=document.querySelector('[data-anatomy-tour-step]')||document.querySelector('#anatomy-tour-step-select');if(panel){panel.focus({preventScroll:true});panel.scrollIntoView({block:'start',behavior:'auto'});}},0);}
        function reviewTourQuestion(question){updMulti(structureFocusPatch(question.structureId,{_tourActive:true,_tourStepIdx:question.stepIndex,_tourRecap:null}));announceStructure(question.structureId);focusTourStep();}
        function showTourDiagram(){if(!currentTourStep)return;updMulti(structureFocusPatch(currentTourStep.structureId,{_tourStepIdx:tourStepIdx}));announceStructure(currentTourStep.structureId);setTimeout(function(){var panel=document.querySelector('[data-anatomy-model-shell]');if(panel){panel.focus({preventScroll:true});panel.scrollIntoView({block:'start',behavior:'auto'});}},0);}
`+s.slice(b);
// Every caller keeps its prior semantics; transactional tour answers may supply fresher state.
const ca=s.indexOf('        function confidenceEvidencePatch(structureId, correct)'),cb=s.indexOf('        function setStructureConfidence',ca);if(ca<0||cb<0)throw Error('Evidence bounds');s=s.slice(0,ca)+`        function confidenceEvidencePatch(structureId, correct, sourceState) {
          if(knownStructureIds.indexOf(structureId)===-1)return {};
          var state=sourceState||d,now=Date.now(),ratings=anatomySharedRatings(state,knownStructureIds,now),current=ratings.confidence[structureId]||null;
          var nextLevel=correct?((current===null||current==='practice')?'learning':current):'practice';
          var nextConfidence=Object.assign({},ratings.confidence),nextAt=Object.assign({},ratings.at),nextEvidence={};
          anatomyConceptPeers(structureId,knownStructureIds).forEach(function(id){nextConfidence[id]=nextLevel;nextAt[id]=now;});
          knownStructureIds.forEach(function(id){var record=anatomyRecallRecord(state,id,knownStructureIds);if(record.attempts)nextEvidence[anatomyEvidenceId(id,knownStructureIds)]=record;});
          var previous=anatomyRecallRecord(state,structureId,knownStructureIds),increment=previous.attempts<1000000?1:0;
          nextEvidence[anatomyEvidenceId(structureId,knownStructureIds)]={attempts:previous.attempts+increment,correct:previous.correct+(correct?increment:0)};
          return {_structureConfidence:nextConfidence,_confidenceAt:nextAt,_retrievalEvidence:nextEvidence};
        }
`+s.slice(cb);
rep("_tourRecap: { active: true, answers: {} }","_tourRecap: { active: true, version: 2, systemId: sysKey, answers: {} }");
rep("// Generic recap builder, shared by the Guided Tour and Pathways: items are\n        // { structureId, text }; every item becomes one clue with the structure name masked and\n        // the other items as distractors. Built lazily (see the tour note above).","// Tour retrieval uses authored clues with alternatives from this tour.\n        // Built lazily because the stable-shuffle helper is initialized later.");
rep("// One question per tour step (max 4): the step narration with the structure name masked,","// Up to four selected tour steps use authored location/function clues,");
// Feedback explains the identified structure, and a miss can return to the teaching step.
const start=s.indexOf('        function renderRecapPanel(cfg)'),end=s.indexOf('        // ── Study sheet',start);let recap=s.slice(start,end);const target='                }))\n              );';if(recap.split(target).length!==2)throw Error('Recap feedback insertion');recap=recap.replace(target,'                })),\n                chosen !== null && h(\'div\',{className:\'anatomy-tour-answer\',\'data-anatomy-tour-feedback\':chosen===question.structureId?\'correct\':\'incorrect\',role:\'status\'},h(\'strong\',null,chosen===question.structureId?t(\'stem.anatomy.recap_correct\',\'Correct: \'):t(\'stem.anatomy.recap_incorrect\',\'Not quite. It was \')),question.structure.name, h(\'p\',null,question.explanation), h(\'a\',{href:question.reference,target:\'_blank\',rel:\'noopener noreferrer\'},'+T('tour_ref_source','Read the science — OpenStax')+'), chosen!==question.structureId && h(\'button\',{type:\'button\',\'data-anatomy-tour-review\':question.stepIndex,onClick:function(){reviewTourQuestion(question);}},t(\'stem.anatomy.route_review_step\',\'Revisit the related step\')))\n              );');s=s.slice(0,start)+recap+s.slice(end);
const pstart=s.indexOf(") : activeTab === 'tour' ? ("),pend=s.indexOf(") : activeTab === 'spotter' ? (",pstart);let panel=s.slice(pstart,pend);function pr(a,b){if(panel.split(a).length!==2)throw Error('Tour panel: '+a.slice(0,90));panel=panel.replace(a,b);}
pr("className: 'bg-white rounded-xl border-2 border-emerald-200 p-4 space-y-3'","className: 'anatomy-tour-panel bg-white rounded-xl border-2 border-emerald-200 p-4 space-y-3', 'data-anatomy-tour-panel':true");
pr("'\\uD83E\\uDDED Guided Tour: ' + sys.icon + ' ' + sys.name",T('tour_ref_heading','Guided tour: ')+" + sys.icon + ' ' + sys.name");
pr("tourSteps.length > 0 ? h('div', { className: 'space-y-3' },","h('p',{className:'anatomy-tour-goal'},"+T('tour_ref_goal','Locate each structure, connect its shape or position to its function, then recall what you learned.')+"),\n                  h('label',{className:'anatomy-route-jump',htmlFor:'anatomy-tour-system-select'},"+T('tour_ref_choose','Choose a tour')+",h('select',{id:'anatomy-tour-system-select',value:sysKey,onChange:function(event){var id=event.target.value;if(!GUIDED_TOURS[id]||!GUIDED_TOURS[id].length)return;var first=GUIDED_TOURS[id][0];updMulti(Object.assign(structureFocusPatch(first.structureId,{_tourActive:true,_tourStepIdx:0,_tourRecap:null}),{system:id}));announceStructure(first.structureId);}},ANATOMY_SYSTEM_IDS.map(function(id){return h('option',{key:id,value:id},SYSTEMS[id].name);}))),\n                  tourSteps.length > 0 ? h('div', { className: 'space-y-3' },");
pr("'Step ' + (tourStepIdx + 1) + ' of ' + tourSteps.length","t('stem.anatomy.route_step_number','Step {step} of {total}').replace('{step}',String(tourStepIdx+1)).replace('{total}',String(tourSteps.length))");
pr("tourRecapActive ? renderTourRecap() : currentTourStep ? h('div', { className: 'bg-emerald-50 rounded-lg p-4 border border-emerald-200', role: 'status',","h('label',{className:'anatomy-route-jump',htmlFor:'anatomy-tour-step-select'},t('stem.anatomy.route_jump','Go to step'),h('select',{id:'anatomy-tour-step-select',value:tourStepIdx,onChange:function(event){var index=Number(event.target.value);if(!Number.isInteger(index)||!tourSteps[index])return;updMulti(structureFocusPatch(tourSteps[index].structureId,{_tourActive:true,_tourStepIdx:index,_tourRecap:null}));announceStructure(tourSteps[index].structureId);}},tourSteps.map(function(step,index){return h('option',{key:index,value:index},(index+1)+'. '+step.title);}))),\n                    tourRecapActive ? renderTourRecap() : currentTourStep ? h('div', { className: 'anatomy-tour-step bg-emerald-50 rounded-lg p-4 border border-emerald-200', 'data-anatomy-tour-step':tourStepIdx,tabIndex:-1, role: 'status',");
pr("'Diagram: ' + sys.name + ' - ' + (view === 'anterior' ? 'Anterior' : 'Posterior')","t('stem.anatomy.route_diagram_context','Diagram: {system} - {view}').replace('{system}',sys.name).replace('{view}',view==='anterior'?t('stem.anatomy.route_anterior','Anterior'):t('stem.anatomy.route_posterior','Posterior'))");
pr("!diagramMatchesTourStep ? h('button', {\n                          onClick: function() { updMulti(structureFocusPatch(currentTourStep.structureId, { _tourStepIdx: tourStepIdx })); announceStructure(currentTourStep.structureId); },","h('button', { 'data-anatomy-tour-diagram':true,\n                          onClick: showTourDiagram,");
pr("}, 'Focus diagram') : null","},diagramMatchesTourStep?t('stem.anatomy.route_show_marker','Show marker on diagram'):t('stem.anatomy.route_focus_diagram','Focus diagram'))");
pr("ttsBtn(currentTourStep.narration,", "h('a',{href:currentTourStep.reference,target:'_blank',rel:'noopener noreferrer',className:'anatomy-route-reference'},"+T('tour_ref_source','Read the science — OpenStax')+"),\n                      ttsBtn(currentTourStep.narration,");
s=s.slice(0,pstart)+panel+s.slice(pend);
rep("h('div', { className: 'anatomy-body-header' },","h('div', { className: 'anatomy-body-header' },\n                activeTab==='tour'&&currentTourStep&&h('button',{type:'button',className:'anatomy-route-return','data-anatomy-tour-return':true,onClick:focusTourStep},"+T('tour_ref_return','Return to tour step')+"),");
const css='.anatomy-tour-panel{min-width:0;color:#0f172a}.anatomy-tour-goal{font-size:13px;line-height:1.5}.anatomy-tour-panel button{min-height:44px}.anatomy-tour-panel a{color:#075985;text-decoration:underline}.anatomy-tour-panel :focus-visible{outline:3px solid #0891b2;outline-offset:3px}.anatomy-tour-answer{font-size:13px;line-height:1.5;margin-top:10px}.anatomy-tour-answer p{margin-block:6px}.anatomy-tour-answer button{display:block;margin-top:8px;border:1px solid #64748b;border-radius:7px;padding:8px}.theme-dark .anatomy-tour-panel,.theme-dark .anatomy-tour-panel [data-anatomy-recap-question]{background:#0f172a!important;color:#e2e8f0!important;border-color:#64748b!important}.theme-dark .anatomy-tour-panel h4,.theme-dark .anatomy-tour-panel h5,.theme-dark .anatomy-tour-panel p,.theme-dark .anatomy-tour-answer{color:#e2e8f0!important}.theme-dark .anatomy-tour-panel button{background:#1e293b!important;color:#e2e8f0!important;border-color:#64748b!important}.theme-dark .anatomy-tour-step{background:#132b2b!important;border-color:#34d399!important}.theme-dark .anatomy-tour-panel a{color:#7dd3fc}.theme-dark .anatomy-tour-panel [role=progressbar]{background:#334155!important}.theme-dark .anatomy-tour-panel [role=progressbar]>div{background:#6ee7b7!important}@media(max-width:900px){.anatomy-tool-shell[data-anatomy-tab="tour"] .anatomy-side-column{order:-1}}';
rep("      '.theme-dark .anatomy-tool-shell{color:",'      '+JSON.stringify(css)+',\n'+"      '.theme-dark .anatomy-tool-shell{color:");
parser.parse(s,{sourceType:'script'});fs.writeFileSync(file,s);fs.copyFileSync(file,'desktop/web-app/public/'+file);fs.writeFileSync(__dirname+'/english.json',JSON.stringify(english,null,2)+'\n');console.log(Object.keys(english).length+' new tour strings.');
