const fs=require('node:fs'),parser=require('@babel/parser');const file='stem_lab/stem_tool_anatomy.js';let s=fs.readFileSync(file,'utf8');function rep(a,b,n=1){if(s.split(a).length-1!==n)throw Error(a);s=s.split(a).join(b);}
rep("var tourSteps = GUIDED_TOURS[sysKey] || [];","var tourSystemId = d._tourActive === true && GUIDED_TOURS[d._tourSystem] ? d._tourSystem : sysKey;\n        var tourSystem = SYSTEMS[tourSystemId];\n        var tourSteps = GUIDED_TOURS[tourSystemId] || [];");
rep("var tourPatch = { _activeTab: tab, quizMode: false, _tourActive: true, _tourStepIdx: nextTourIndex };","var tourPatch = { _activeTab: tab, quizMode: false, _tourActive: true, _tourStepIdx: nextTourIndex, _tourSystem: tourActive ? tourSystemId : sysKey };");
rep("rawTourRecap.systemId === sysKey","rawTourRecap.systemId === tourSystemId");
rep("'tour|' + sysKey, 4","'tour|' + tourSystemId, 4");
rep("systemId=SYSTEMS[state.system]?state.system:'skeletal';","systemId=GUIDED_TOURS[state._tourSystem]?state._tourSystem:(SYSTEMS[state.system]?state.system:'skeletal');");
rep("systemId!==sysKey||recap.active!==true||recap.version!==2||recap.systemId!==sysKey","systemId!==tourSystemId||recap.active!==true||recap.version!==2||recap.systemId!==tourSystemId");
rep("systemId:sysKey,answers:answers","systemId:tourSystemId,answers:answers");
rep("{_tourActive:true,_tourStepIdx:question.stepIndex,_tourRecap:null}","{_tourActive:true,_tourSystem:tourSystemId,_tourStepIdx:question.stepIndex,_tourRecap:null}");
rep("{_tourStepIdx:tourStepIdx}","{_tourStepIdx:tourStepIdx,_tourSystem:tourSystemId}");
rep("_tourRecap: { active: true, version: 2, systemId: sysKey, answers: {} }","_tourRecap: { active: true, version: 2, systemId: tourSystemId, answers: {} }");
const a=s.indexOf(") : activeTab === 'tour' ? ("),b=s.indexOf(") : activeTab === 'spotter' ? (",a);let panel=s.slice(a,b);panel=panel.replace("+ sys.icon + ' ' + sys.name","+ tourSystem.icon + ' ' + tourSystem.name").replace("value:sysKey,onChange","value:tourSystemId,onChange").replace("{_tourActive:true,_tourStepIdx:0,_tourRecap:null}","{_tourActive:true,_tourSystem:id,_tourStepIdx:0,_tourRecap:null}").replace("{_tourActive:true,_tourStepIdx:index,_tourRecap:null}","{_tourActive:true,_tourSystem:tourSystemId,_tourStepIdx:index,_tourRecap:null}").replace("{ _tourStepIdx: prev }","{ _tourStepIdx: prev, _tourSystem: tourSystemId }").replace("{ _tourStepIdx: next }","{ _tourStepIdx: next, _tourSystem: tourSystemId }");s=s.slice(0,a)+panel+s.slice(b);
rep("function systemSelectionPatch(systemId) {","function systemSelectionPatch(systemId) {\n          if(activeTab==='tour' && GUIDED_TOURS[systemId] && GUIDED_TOURS[systemId].length){return Object.assign(structureFocusPatch(GUIDED_TOURS[systemId][0].structureId,{_tourActive:true,_tourSystem:systemId,_tourStepIdx:0,_tourRecap:null}),{system:systemId});}");
parser.parse(s,{sourceType:'script'});fs.writeFileSync(file,s);fs.copyFileSync(file,'desktop/web-app/public/'+file);
const test='tests/anatomy_tour_refinements.test.js';let t=fs.readFileSync(test,'utf8');t=t.replace("s.answer('femur','skull')()","s.answer('pelvis','skull')()").replace("{femur:{attempts:1,correct:0}}","{pelvis:{attempts:1,correct:0}}").replace('_structureConfidence.femur','_structureConfidence.pelvis').replace("toContain('hip to the knee')","toContain('pelvic cavity')").replace("['data-anatomy-tour-review']===3","['data-anatomy-tour-review']===4").replace("_tourStepIdx:3,selectedStructure:'femur'","_tourStepIdx:4,selectedStructure:'pelvis'").replace("['skull','vertebral','femur','pelvis']","['skull','vertebral','ribs','pelvis']");fs.writeFileSync(test,t);
const regression='tests/anatomy_lab_science.test.js';let tests=fs.readFileSync(regression,'utf8');tests=tests.replace("var tourPatch = { _activeTab: tab, quizMode: false, _tourActive: true, _tourStepIdx: nextTourIndex };","var tourPatch = { _activeTab: tab, quizMode: false, _tourActive: true, _tourStepIdx: nextTourIndex, _tourSystem: tourActive ? tourSystemId : sysKey };").replace("updMulti(structureFocusPatch(tourSteps[next].structureId, { _tourStepIdx: next }))","updMulti(structureFocusPatch(tourSteps[next].structureId, { _tourStepIdx: next, _tourSystem: tourSystemId }))");fs.writeFileSync(regression,tests);
