from pathlib import Path
p=Path('stem_lab/stem_tool_moonmission.js');s=p.read_bytes()
def replace(old,new):
 global s
 a=old.encode('utf8');b=new.encode('utf8');assert s.count(a)==1,(a[:100],s.count(a));s=s.replace(a,b)
replace("if(name==='pause'){paused=!!value;upd('departurePaused',paused);if(!paused)upd('animPaused',false);}","if(name==='pause'){paused=!!value;upd('departurePaused',paused);if(!paused){var host=cv.closest('[data-return-workspace]'),other=host&&host.querySelector('[data-teicoast-canvas]');if(other&&other._returnAction)other._returnAction('pause',true);upd('animPaused',false);}}")
replace("            if (cv && cv._returnAction) cv._returnAction(action, value);", "            if (action === 'pause' && value === false) { var other = host && host.querySelector('[data-departure-canvas]'); if (other && other._departureAction) other._departureAction('pause', true); }\n            if (cv && cv._returnAction) cv._returnAction(action, value);")
replace("onClick:function(){upd('departureOpen',!d.departureOpen);upd('departurePaused',true);}","onClick:function(){if(!d.departureOpen){if(returnCanvas&&returnCanvas._returnAction)returnCanvas._returnAction('pause',true);else upd('returnPaused',true);}upd('departureOpen',!d.departureOpen);upd('departurePaused',true);}")
replace('Compare the burns below, then inspect the separate Earth-return preset.', 'Compare the burns below, then inspect the separate Earth-return preset. Playing either view pauses the other.')
p.write_bytes(s);Path('desktop/web-app/public/stem_lab/stem_tool_moonmission.js').write_bytes(s)
t=Path('tests/moonmission_departure_saved_state.test.js');text=t.read_text(encoding='utf8');text=text.replace("expect(walk(app.tree(),n=>n.props?.['data-departure-canvas'])).toBeTruthy();expect(app.state().loiResult)","expect(walk(app.tree(),n=>n.props?.['data-departure-canvas'])).toBeTruthy();expect(app.state().returnPaused).toBe(true);expect(app.state().loiResult)");t.write_text(text,encoding='utf8',newline='\n')
t=Path('tests/e2e/moon-mission-departure.spec.ts');text=t.read_text(encoding='utf8');anchor="test('hidden playback and close reopen preserve time without wall-clock catch-up',async({page})=>{await mount(page);";assert anchor in text;text=text.replace(anchor,anchor+"const returnTime=Number(await page.locator('[data-teicoast-canvas]').getAttribute('data-return-elapsed'));");anchor="await expect.poll(async()=>(await live(page)).time).toBeGreaterThan(1);await page.evaluate";assert anchor in text;text=text.replace(anchor,"await expect.poll(async()=>(await live(page)).time).toBeGreaterThan(1);expect(Number(await page.locator('[data-teicoast-canvas]').getAttribute('data-return-elapsed'))).toBe(returnTime);expect((await saved(page)).returnPaused).toBe(true);await page.evaluate");anchor="test('320px keyboard seek, view resize";assert anchor in text
new="test('playing Earth return holds the departure playhead and preserves its review',async({page})=>{await mount(page);await page.locator('[data-departure-review]').click();await seek(page,200);const before=(await saved(page)).departureResult;await page.locator('[data-departure-pause]').click();await expect.poll(async()=>(await live(page)).time).toBeGreaterThan(200);await page.locator('[data-return-play-pause]').click();const held=await live(page);await expect.poll(async()=>Number(await page.locator('[data-teicoast-canvas]').getAttribute('data-return-elapsed'))).toBeGreaterThan(1);await page.waitForTimeout(200);expect(await live(page)).toEqual(held);expect((await saved(page)).departureResult).toEqual(before);expect((await saved(page)).departurePaused).toBe(true);await page.locator('[data-return-play-pause]').click();});\n"
text=text.replace(anchor,new+anchor);t.write_text(text,encoding='utf8',newline='\n')
