'use strict';

const S = require('./item_content.cjs').sources;
const section = (heading, content, keyTerms) => ({ heading, content, keyTerms });
const chapter = (id, skillId, title, summary, objectives, sections, flashcards) => ({ id, skillId, title, summary, objectives, sections, flashcards });
const aid = (title, content, tags, references = [S.ETS]) => ({ title, content, tags, references });

const chapters = [
  chapter('aud5343-ch-01', 'auditory-anatomy-acoustics', 'Auditory Anatomy, Physiology, Acoustics, and Instrumentation',
    'Connect peripheral and central auditory structures with acoustic measurement, transduction, calibration, and clinically meaningful signal behavior.',
    ['Trace sound from the outer ear through central pathways.', 'Apply core sound-level and wavelength relationships.', 'Explain why calibration and routine equipment checks are complementary.'], [
      section('Outer, middle, and inner-ear systems', 'The pinna and ear canal collect and shape sound before the tympanic membrane and ossicular chain transfer energy into cochlear fluid. The middle ear improves impedance matching through area and lever relationships; the Eustachian tube supports pressure regulation. In the cochlea, traveling-wave mechanics create a place code, with high-frequency maxima toward the base and low-frequency maxima toward the apex. Structural knowledge should guide hypotheses, not replace examination and converging measurements.', ['ossicular chain', 'impedance matching', 'cochlear tonotopy']),
      section('Hair-cell transduction and cochlear mechanics', 'Inner hair cells provide most afferent auditory input, while outer hair-cell motility contributes active gain, sharp frequency selectivity, and compressive nonlinearity. Stereocilia deflection changes receptor current, and auditory-nerve fibers encode timing and level within physiologic limits. Otoacoustic emissions can provide evidence about outer hair-cell function, but no single cochlear measure establishes hearing ability or the complete site of lesion.', ['inner hair cell', 'outer hair cell', 'cochlear amplifier']),
      section('Neural pathways and binaural organization', 'Cranial nerve VIII carries cochlear and vestibular afferent information to the brainstem. Above the cochlear nuclei, extensive bilateral projections support localization, binaural summation, and speech understanding in complex environments. Interaural time differences are especially useful at lower frequencies and interaural level differences at higher frequencies. A central finding must be interpreted with peripheral status, task demands, cognition, language, and neurologic context.', ['cranial nerve VIII', 'binaural hearing', 'central auditory pathway']),
      section('Acoustics, decibels, and measurement quality', 'Sound speed equals frequency times wavelength, so wavelength decreases as frequency rises in a constant medium. Sound pressure level uses 20 log10 of a pressure ratio; in an ideal free field, doubling distance from a point source reduces level by about 6 dB. Calibration connects instrument output to standards, while listening, biological, ambient-noise, and equipment checks can detect interim problems. Document transducer, environment, calibration status, and deviations that affect interpretation.', ['decibel', 'inverse square', 'calibration']),
    ], [['Where are high frequencies represented in the cochlea?', 'Near the basal cochlea and oval window; lower-frequency maxima occur progressively toward the apex.'], ['What is the main role of inner hair cells?', 'They transduce cochlear motion and provide most afferent auditory-nerve input.'], ['What is the main role of outer hair cells?', 'They contribute active cochlear gain, compression, and sharp frequency selectivity.'], ['What does 20 log10 describe in acoustics?', 'A sound-pressure amplitude ratio expressed in decibels.'], ['What is the ideal distance rule?', 'Doubling distance from a point source in a free field reduces level by about 6 dB.'], ['Why use routine checks after annual calibration?', 'They can reveal interim transducer, equipment, connection, or environmental problems.']]),

  chapter('aud5343-ch-02', 'psychoacoustics-development', 'Psychoacoustics, Auditory Development, and Lifespan Effects',
    'Use psychophysical principles and lifespan development to explain detection, discrimination, masking, localization, speech perception, and age-related change.',
    ['Differentiate threshold, loudness, pitch, and temporal processing.', 'Explain masking and binaural cues.', 'Relate developmental and aging effects to assessment without stereotyping.'], [
      section('Detection, loudness, pitch, and frequency selectivity', 'Threshold estimates the lowest level detected under defined conditions; suprathreshold loudness, pitch, and quality are different perceptual dimensions. Equal-loudness relationships vary across frequency and level. Auditory filters and critical-band concepts help explain frequency selectivity and why energy near a target frequency can be especially effective at masking it. Psychophysical performance depends on task, attention, response rules, signal properties, and measurement reliability.', ['threshold', 'loudness', 'critical band']),
      section('Masking and temporal processing', 'Masking elevates the detectability threshold of one signal because of another, with greater effects when masker and signal overlap in frequency or time. Upward spread of masking means low-frequency energy can mask higher-frequency energy more than the reverse under many conditions. Temporal resolution supports detection of brief gaps and rapid changes important for speech. Separate the auditory construct from language, cognition, motivation, and procedural learning when interpreting results.', ['masking', 'temporal resolution', 'upward spread']),
      section('Binaural hearing and speech in noise', 'Interaural timing, level, and spectral cues support localization and spatial release from masking. Real environments add reverberation, competing talkers, distance, visual access, and cognitive load, so quiet thresholds cannot fully predict communication. Speech-in-noise and functional reports can add information when chosen for the referral question and interpreted against applicable evidence. Technology can improve access but does not erase all adverse listening conditions.', ['interaural time difference', 'interaural level difference', 'speech in noise']),
      section('Development and aging across the lifespan', 'Auditory access interacts with language, cognition, motor development, education, health, and experience. Infants require developmentally appropriate physiologic and behavioral cross-checks; children may need conditioned tasks and family or teacher evidence. Aging can affect high-frequency sensitivity, temporal processing, speech-in-noise performance, cognition, dexterity, and device management, but individual variation is large. Avoid treating chronological age as a diagnosis or a complete predictor of outcome.', ['auditory development', 'presbycusis', 'lifespan']),
    ], [['What is a critical band?', 'A psychoacoustic model of the frequency region over which masker energy strongly affects target detection.'], ['What is upward spread of masking?', 'Lower-frequency masker energy often masks higher-frequency targets more than higher-frequency energy masks lower targets.'], ['What does temporal resolution support?', 'Detection of rapid changes and brief gaps that contribute to speech perception.'], ['Which binaural cue is prominent at low frequencies?', 'Interaural time difference.'], ['Can quiet thresholds predict all speech-in-noise performance?', 'No; suprathreshold processing, environment, language, cognition, and other factors also matter.'], ['How should age inform audiology?', 'Use developmentally and functionally appropriate methods while preserving individual variability and cross-checking results.']]),

  chapter('aud5343-ch-03', 'hearing-prevention-conservation', 'Hearing Prevention, Conservation, and Ototoxic Monitoring',
    'Plan prevention around exposure control, education, monitoring, protection, and timely follow-up rather than relying on one test or device.',
    ['Apply a hierarchy of controls to hazardous sound.', 'Match protection and education to exposure and communication demands.', 'Recognize the role and limits of ototoxic monitoring.'], [
      section('Hazard recognition and exposure control', 'Risk depends on sound level, duration, spectrum, repetition, impulse characteristics, recovery, and individual factors. Prevention begins by measuring or estimating exposure under current occupational, educational, and recreational standards. Engineering and administrative controls reduce exposure at its source or along its path; hearing protection supplements those controls. A single threshold test cannot establish that an exposure is safe or identify the cause of every change.', ['noise dose', 'engineering control', 'administrative control']),
      section('Hearing protection and communication needs', 'Select earplugs, earmuffs, level-dependent devices, or combined protection according to the measured hazard, fit, comfort, compatibility, communication, localization, and warning-signal needs. Nominal attenuation ratings do not guarantee field performance. Fit testing, training, observation, and follow-up improve real-world protection. Overprotection can interfere with communication or safety, so the goal is adequate effective attenuation within a complete control program.', ['hearing protection', 'fit testing', 'attenuation']),
      section('Monitoring and standard threshold shifts', 'A conservation program uses a valid baseline, comparable follow-up conditions, equipment quality controls, exposure records, education, and protocol-defined review of threshold changes. Apparent shifts require confirmation and consideration of calibration, transducer, test environment, middle-ear status, reliability, and medical or occupational follow-up. Current regulations define required calculations and actions; study heuristics do not replace jurisdictional standards or professional judgment.', ['baseline audiogram', 'threshold shift', 'hearing conservation']),
      section('Ototoxic and recreational risk counseling', 'Some medications and chemicals can affect cochlear or vestibular function, often in interaction with dose, timing, health, and noise. Monitoring should follow the medical referral, drug-specific protocol, baseline status, feasible sensitive measures, symptoms, and coordinated communication. Recreational counseling should be practical and nonjudgmental: reduce level or duration, increase distance, use well-fitted protection, take breaks, and respond to persistent tinnitus or hearing change with qualified evaluation.', ['ototoxicity', 'monitoring', 'recreational noise']),
    ], [['What comes before personal protective equipment in the control hierarchy?', 'Reduce hazardous sound through feasible engineering and administrative controls.'], ['Does a labeled attenuation rating guarantee field protection?', 'No; actual attenuation depends on fit, use, environment, and verification.'], ['Why can overprotection be a problem?', 'It may unnecessarily reduce speech, warning-signal, and environmental access.'], ['What supports valid threshold-shift review?', 'Comparable testing plus calibration, reliability, middle-ear, exposure, and protocol evidence.'], ['What is needed before ototoxic monitoring?', 'A defined medical context, baseline when feasible, suitable measures, and coordinated follow-up.'], ['What is practical recreational-risk counseling?', 'Lower level or duration, increase distance, take breaks, use fitted protection, and evaluate persistent symptoms.']]),

  chapter('aud5343-ch-04', 'screening-ehdi-school', 'Screening, EHDI, and School Identification Programs',
    'Design screening pathways that identify risk efficiently, protect access and privacy, and reliably connect every refer result to diagnostic follow-up.',
    ['Distinguish screening from diagnosis.', 'Explain newborn and school screening pathways.', 'Monitor program quality through referral and follow-up outcomes.'], [
      section('Screening purpose and decision rules', 'Screening is a brief risk-identification process for people without a confirmed condition; it does not determine diagnosis, educational eligibility, or treatment. Select tools and pass or refer criteria for the target population, setting, prevalence, available follow-up, and current protocol. Sensitivity, specificity, false-positive and false-negative consequences, feasibility, language, accessibility, and equity all matter. Communicate results as pass, refer, or incomplete rather than as proof of normal hearing or disorder.', ['screening', 'sensitivity', 'specificity']),
      section('Newborn screening and EHDI pathways', 'Newborn programs commonly use automated OAE, automated ABR, or protocol-defined combinations. A refer result needs prompt rescreening or diagnostic evaluation through the current Early Hearing Detection and Intervention pathway; it is not itself a diagnosis. Risk indicators can justify surveillance even after a pass because some differences are delayed onset or progressive. Family-centered communication should explain the next action, timing, uncertainty, and contact path without blame or false reassurance.', ['newborn hearing screening', 'EHDI', 'surveillance']),
      section('School-age screening and educational access', 'School programs may combine pure-tone, tympanometric, or other procedures under local policy, with developmentally accessible instructions, controlled ambient noise, equipment checks, infection control, and consistent referral criteria. A failed screen can reflect hearing difference, temporary middle-ear status, environment, attention, or procedure. Prompt rescreening or referral and communication with families and authorized school personnel are essential. Screening alone does not describe classroom listening or needed accommodations.', ['school screening', 'ambient noise', 'educational access']),
      section('Program quality, follow-up, and equity', 'A high-quality program tracks coverage, incomplete screens, refer rate, timely follow-up, diagnostic completion, loss to follow-up, demographic disparities, equipment quality, staff competency, and data accuracy. Repeated screening without a defined escalation path can delay diagnosis. Use accessible multilingual communication, consent and privacy procedures, reliable referral partners, and active navigation for barriers. Program improvement should target the whole pathway, not merely the number screened.', ['loss to follow-up', 'program evaluation', 'health equity']),
    ], [['What does a hearing screen establish?', 'Risk and need for follow-up, not diagnosis, eligibility, or a complete functional profile.'], ['What follows a newborn refer result?', 'Protocol-defined timely rescreening or diagnostic evaluation through the EHDI pathway.'], ['Can a newborn pass end all surveillance?', 'No; risk indicators or later concern can require monitoring for delayed-onset or progressive change.'], ['Why control ambient noise in school screening?', 'Noise can elevate apparent thresholds and increase invalid referrals.'], ['What is loss to follow-up?', 'Failure to complete the recommended next step after a refer or incomplete result.'], ['Which metrics show pathway quality?', 'Coverage, referral, diagnostic completion, timeliness, loss to follow-up, disparities, and data quality.']]),

  chapter('aud5343-ch-05', 'behavioral-audiologic-assessment', 'Behavioral Audiometry, Speech Measures, and Functional Listening',
    'Select behavioral methods, masking, speech measures, and functional evidence that answer the referral question with transparent reliability limits.',
    ['Interpret air- and bone-conduction patterns.', 'Use speech and suprathreshold measures appropriately.', 'Adapt conditioned methods without mistaking behavior for exact physiology.'], [
      section('Pure-tone thresholds and transducer choices', 'Air-conduction thresholds reflect the entire auditory pathway available to the task, while bone conduction largely bypasses the outer and middle ear but stimulates both cochleae. Configuration, symmetry, air–bone gaps, transducer characteristics, calibration, collapse risk, and reliability shape interpretation. Threshold is a probabilistic response level under defined conditions, not a perfect boundary. Confirm unexpected results with reinstruction, retest, and cross-checks before drawing diagnostic conclusions.', ['air conduction', 'bone conduction', 'air–bone gap']),
      section('Masking and cross-hearing control', 'Masking is needed when the nontest ear may detect the test signal through interaural attenuation. Choose initial and maximum levels using the signal, transducer, air- and bone-conduction thresholds, occlusion effects, and the current protocol. The plateau method seeks stable test-ear responses across increasing masker levels. Overmasking and undermasking can both create invalid conclusions, so document assumptions and interpret masking dilemmas explicitly.', ['interaural attenuation', 'plateau method', 'overmasking']),
      section('Speech threshold, recognition, and speech in noise', 'Speech-recognition threshold should generally agree with the pure-tone average when the measures, language, and responses are valid. Word-recognition performance depends on presentation level, audibility, materials, language, list length, and measurement uncertainty. Speech-in-noise measures can better represent complex listening but remain task-specific. Select materials for the person and decision, report conditions, and avoid treating one percentage as a complete neural or functional diagnosis.', ['speech-recognition threshold', 'word recognition', 'speech in noise']),
      section('Pediatric conditioning and functional evidence', 'Visual reinforcement audiometry and conditioned play audiometry use developmentally appropriate conditioned responses, but minimum response levels can be affected by attention, development, state, and reinforcement. Sound-field results generally represent the better response and are not ear specific without appropriate ear-specific methods. Combine caregiver and teacher reports, observation, aided and unaided information, and physiologic cross-checks. Reliability is established through repeatable patterns, not assumed from age alone.', ['visual reinforcement audiometry', 'conditioned play audiometry', 'minimum response level']),
    ], [['What does an air–bone gap suggest?', 'A conductive component when measurements are valid and masking and calibration support the comparison.'], ['Why is bone conduction not inherently ear specific?', 'The oscillator can stimulate both cochleae, so masking may be necessary.'], ['What does the plateau method seek?', 'A stable test-ear threshold across increases in masking noise.'], ['What should SRT usually cross-check?', 'The pure-tone average, considering language, materials, and response validity.'], ['What limits word-recognition interpretation?', 'Presentation level, audibility, list properties, language, variability, and measurement error.'], ['What does sound-field testing usually represent?', 'The better responding auditory pathway, not an ear-specific threshold.']]),

  chapter('aud5343-ch-06', 'immittance-oae-electrophysiology', 'Immittance, Otoacoustic Emissions, and Electrophysiology',
    'Integrate middle-ear, cochlear, neural, and electrophysiologic measures through a cross-check principle rather than assigning diagnosis from one pattern.',
    ['Interpret tympanometric and reflex findings cautiously.', 'Explain what OAEs do and do not measure.', 'Use ABR and related responses for defined threshold and neural questions.'], [
      section('Tympanometry and ear-canal volume', 'Tympanometry describes acoustic admittance as ear-canal pressure changes; peak pressure, static admittance, width, and equivalent ear-canal volume are interpreted with age, probe tone, history, and otoscopy. A flat tracing with a large volume can suggest a patent tube or perforation, while a flat tracing with a typical volume can be consistent with reduced middle-ear mobility. These patterns are hypotheses, not medical diagnoses, and require quality checks and clinical correlation.', ['tympanometry', 'ear-canal volume', 'static admittance']),
      section('Acoustic reflexes and differential patterns', 'Acoustic reflex threshold and decay measures involve the cochlea, auditory nerve, brainstem pathways, facial nerve, stapedius muscle, and measurable middle-ear status. Probe and stimulus ear matter. Conductive components can prevent measurement even when the reflex arc is otherwise intact. Interpret present, elevated, absent, or decaying responses with thresholds, tympanometry, symptoms, and other neural evidence rather than applying a pattern table mechanically.', ['acoustic reflex', 'reflex decay', 'facial nerve']),
      section('Otoacoustic emissions', 'Transient-evoked and distortion-product OAEs provide frequency-related evidence about cochlear outer hair-cell function under suitable probe fit, noise, and middle-ear transmission. OAEs can be present when behavioral responses are abnormal in auditory neuropathy spectrum disorder and absent because of middle-ear dysfunction. Presence does not prove normal hearing or speech understanding; absence does not specify degree or cause. Report stimulus, noise, response criteria, and technical limitations.', ['otoacoustic emission', 'outer hair cell', 'noise floor']),
      section('ABR, ASSR, and cross-checking', 'Auditory brainstem response evaluates synchronized neural activity to controlled stimuli and can estimate frequency-specific auditory sensitivity when behavioral results are unavailable or unreliable. Click ABR emphasizes a broad high-frequency region; tone-burst or other frequency-specific stimuli support threshold estimation with correction and protocol limits. ASSR may add information at selected levels and frequencies. Electrophysiology is not a direct behavioral audiogram, so integrate timing, morphology, middle-ear and cochlear measures, and later behavioral confirmation.', ['auditory brainstem response', 'ASSR', 'cross-check principle']),
    ], [['What helps interpret a flat tympanogram?', 'Equivalent ear-canal volume, probe conditions, age, otoscopy, and clinical context.'], ['Does an absent reflex always mean neural pathology?', 'No; middle-ear transmission, degree of loss, technical factors, and the full reflex arc also matter.'], ['What do OAEs primarily reflect?', 'Outer hair-cell-related cochlear function under suitable middle-ear and recording conditions.'], ['Do present OAEs prove normal hearing?', 'No; they do not establish behavioral thresholds, neural synchrony, or speech understanding.'], ['What does ABR measure?', 'Time-locked neural activity evoked by controlled auditory stimuli.'], ['Why cross-check electrophysiology?', 'Each measure samples a different mechanism and carries technical and inferential limits.']]),

  chapter('aud5343-ch-07', 'vestibular-tinnitus-apd-assessment', 'Vestibular, Tinnitus, Sound-Tolerance, and Auditory-Processing Assessment',
    'Choose symptom-driven vestibular and auditory tests, recognize urgent red flags, and separate measured mechanisms from broader medical or functional diagnoses.',
    ['Match vestibular tests to frequency and organ questions.', 'Assess tinnitus and sound tolerance without unsupported causal claims.', 'Use auditory-processing measures within a differential framework.'], [
      section('Vestibular history and urgent triage', 'Clarify onset, duration, triggers, positional relation, hearing symptoms, neurologic symptoms, falls, medication, migraine, vision, and functional impact. Acute focal neurologic signs, inability to stand, severe new headache, trauma, sudden hearing change, or other emergency features require prompt medical or emergency action under current protocol. Audiologic vestibular testing can characterize system function but does not replace medical diagnosis or the broader neurologic and cardiovascular differential.', ['dizziness history', 'red flag', 'triage']),
      section('Canal and otolith test selection', 'Caloric testing emphasizes low-frequency horizontal semicircular-canal and superior vestibular-nerve function, while video head impulse testing samples higher-frequency vestibulo-ocular reflexes across canals. VEMPs provide information related to otolith and reflex pathways under specific recording conditions. Positional testing can support identification of characteristic nystagmus patterns. No one test is a global balance test; integrate eye movement, symptom, hearing, and medical evidence.', ['caloric test', 'video head impulse test', 'VEMP']),
      section('Tinnitus and decreased sound tolerance', 'Assessment includes laterality, pulsatility, onset, hearing, sleep, distress, mental health, medication, noise, somatic factors, and functional effects. Pulsatile unilateral tinnitus, sudden change, neurologic signs, or other red flags need appropriate medical referral. Use validated impact measures and shared goals; matching procedures do not reveal a single cause. Counseling and management should avoid promises of cure and address hearing access, coping, safety, and referral needs.', ['tinnitus', 'hyperacusis', 'pulsatile']),
      section('Auditory-processing differential reasoning', 'Auditory-processing concerns often involve difficulty in noise, competing signals, rapid speech, localization, or complex directions, but similar complaints can arise from peripheral hearing, language, attention, memory, learning, neurodevelopment, or environment. Use age-appropriate measures with known limitations and adequate peripheral access, gather functional evidence, and coordinate the team. Test performance supports a defined interpretation; it should not be converted into a universal explanation for school difficulty.', ['auditory processing', 'differential diagnosis', 'functional listening']),
    ], [['Which history can require urgent escalation?', 'New focal neurologic signs, severe acute symptoms, trauma, sudden hearing change, or other protocol-defined red flags.'], ['What does caloric testing emphasize?', 'Low-frequency horizontal-canal and related superior vestibular-nerve function.'], ['What does vHIT emphasize?', 'Higher-frequency vestibulo-ocular reflex function for the tested canals.'], ['What do VEMPs sample?', 'Otolith-related reflex pathways under specific stimulus and recording conditions.'], ['Does tinnitus matching establish cause?', 'No; it describes selected perceptual characteristics but does not identify one etiology.'], ['What must APD differential reasoning consider?', 'Peripheral hearing, language, attention, memory, learning, development, and environment.']]),

  chapter('aud5343-ch-08', 'integrated-pediatric-diagnostic', 'Integrated Diagnostic Reasoning and Pediatric Educational Assessment',
    'Synthesize history, behavioral and physiologic measures, development, function, and referral urgency into defensible audiologic and educational conclusions.',
    ['Apply the pediatric cross-check principle.', 'Recognize patterns requiring urgent or specialized referral.', 'Connect audiologic findings to classroom access and team decisions.'], [
      section('Cross-checking and resolving disagreement', 'Begin with the referral decision, then combine otoscopy, immittance, behavioral thresholds, speech measures, OAEs, electrophysiology, symptoms, and functional reports as appropriate. When findings conflict, examine probe fit, calibration, attention, development, transducer, masking, middle-ear status, neural synchrony, timing, and task demands. Do not average incompatible data into false certainty. State what is known, what remains uncertain, and which next measure can resolve the decision.', ['cross-check principle', 'test reliability', 'diagnostic uncertainty']),
      section('Pediatric diagnostic pathways', 'Infant and child assessment may require frequency- and ear-specific physiologic estimates, developmentally conditioned behavioral responses, and repeated visits as reliable skills emerge. Correct for test-specific estimates and document minimum response levels. Risk indicators, caregiver concern, speech-language development, and changing medical status can warrant surveillance after an earlier pass. Family communication should be timely, accessible, neutral, and connected to intervention and medical pathways without delaying language access.', ['pediatric assessment', 'minimum response level', 'surveillance']),
      section('Urgent and specialized referral patterns', 'Sudden sensorineural hearing loss is time sensitive and requires urgent medical evaluation rather than routine retest weeks later. Asymmetry, unilateral or pulsatile tinnitus, pain, drainage, neurologic signs, rapid progression, or vestibular red flags may also require medical referral under current guidance. Patterns such as present OAEs with absent or abnormal ABR can raise concern for neural dys-synchrony but require technical confirmation and comprehensive follow-up before labeling.', ['sudden sensorineural hearing loss', 'auditory neuropathy spectrum', 'medical referral']),
      section('Educational and functional assessment', 'School audiology links auditory status with distance, noise, reverberation, teacher and peer access, technology, language, literacy, participation, self-advocacy, and fatigue. Use observation, teacher and student reports, classroom acoustics, aided performance when appropriate, and curriculum demands. Contribute specialized evidence to IEP or Section 504 processes while respecting team authority and current law. Diagnosis alone does not dictate identical eligibility, goals, or accommodations.', ['educational audiology', 'classroom listening', 'IEP']),
    ], [['What should happen when audiologic measures disagree?', 'Check technical and task factors, identify plausible mechanisms, state uncertainty, and choose the next resolving measure.'], ['Why may pediatric assessment require repeated visits?', 'Reliable ear- and frequency-specific behavioral skills emerge over time and must cross-check physiologic estimates.'], ['What is the response to suspected sudden sensorineural hearing loss?', 'Urgent medical evaluation through current protocol.'], ['What pattern can raise concern for auditory neuropathy spectrum?', 'Preserved cochlear outer hair-cell evidence with abnormal neural synchrony, after technical confirmation.'], ['Does a hearing diagnosis determine school eligibility by itself?', 'No; educational impact, need, law, and team evidence guide individualized decisions.'], ['What broadens classroom assessment?', 'Noise, distance, reverberation, technology, language, participation, fatigue, partners, and student report.']]),

  chapter('aud5343-ch-09', 'hearing-aid-selection-verification', 'Hearing-Aid Selection, Fitting, Verification, and Validation',
    'Move from candidacy and person-centered goals through prescriptive fitting, electroacoustic verification, outcome validation, counseling, and follow-up.',
    ['Differentiate verification from validation.', 'Explain compression, directionality, feedback, and coupling tradeoffs.', 'Use iterative follow-up to improve audibility and participation safely.'], [
      section('Candidacy, goals, and device selection', 'Selection starts with audiologic findings, communication goals, environments, dexterity, vision, cognition, ear health, preferences, prior experience, connectivity, support, cost, and relevant medical or educational coordination. Choose style, receiver, coupling, microphone, controls, telecoil or wireless features, and durability to fit those needs. No audiogram uniquely determines a product. Use informed choice and disclose financial relationships and realistic limits.', ['hearing-aid candidacy', 'feature matching', 'informed choice']),
      section('Prescriptive targets and real-ear verification', 'A validated prescription provides frequency- and input-specific targets based on the audiologic data and fitting context. Real-ear or appropriate simulated-ear measures verify aided output at the eardrum and help account for individual ear acoustics. Verification evaluates audibility, target match, output limits, and feature behavior; manufacturer first-fit settings alone are not individualized proof. Pediatric and special cases require current protocol and calibrated equipment.', ['prescriptive target', 'real-ear measurement', 'maximum output']),
      section('Compression, microphones, and feedback', 'Wide dynamic range compression maps a reduced input range into the listener’s usable output range; kneepoint, ratio, attack, release, channels, and maximum output affect sound. Directional microphones can improve signal-to-noise ratio when the desired source and noise geometry support them. Feedback management must be paired with fit, coupling, wax, vent, receiver, and acoustic-leak checks. Feature changes should be verified rather than inferred from a software label.', ['compression ratio', 'directional microphone', 'feedback management']),
      section('Validation, counseling, and follow-up', 'Validation asks whether the fitting improves the person’s communication, participation, comfort, and goals through interviews, questionnaires, functional measures, and real-world experience. Counseling covers insertion, care, charging or batteries, connectivity, listening expectations, communication strategies, repairs, and safety. Follow-up reviews data logging only with context, repeats measures when needed, and modifies the plan through shared decisions. Device use alone is not the outcome.', ['validation', 'outcome measure', 'follow-up']),
    ], [['What is verification?', 'Objective confirmation that the device delivers intended electroacoustic output, often through real-ear measures.'], ['What is validation?', 'Evidence that the fitting improves the person’s real-world goals, function, and participation.'], ['Why is manufacturer first fit insufficient?', 'It does not account fully for individual ear acoustics or prove target match and safe output.'], ['What does compression do?', 'Maps a broad input-level range into the listener’s smaller usable output range.'], ['When can directionality help?', 'When spatial arrangement lets the microphones favor the desired source relative to noise.'], ['What should feedback troubleshooting include?', 'Fit, coupling, wax, venting, receiver, leakage, programming, and verified feature behavior.']]),

  chapter('aud5343-ch-10', 'implants-assistive-technology', 'Implants, Assistive Technology, Connectivity, and Device Management',
    'Match implantable and nonimplantable technologies to anatomy, access goals, environments, candidacy processes, safety constraints, and ongoing outcomes.',
    ['Describe cochlear and bone-conduction technology roles.', 'Use remote microphone and alerting systems to improve access.', 'Verify device-specific medical and connectivity requirements.'], [
      section('Cochlear-implant candidacy and team care', 'Cochlear implants electrically stimulate the auditory nerve through an electrode array and require multidisciplinary evaluation, surgery, activation, mapping, rehabilitation, and outcome monitoring. Candidacy considers appropriately fitted hearing-aid benefit, speech and language access, anatomy and medical factors, development, communication goals, support, and current criteria. Counseling should present variability and continued learning needs without guaranteeing speech perception or treating one communication approach as mandatory.', ['cochlear implant', 'candidacy', 'mapping']),
      section('Bone-conduction and other implantable options', 'Bone-conduction systems route vibration to the cochleae and may be considered for selected conductive, mixed, or single-sided configurations after individualized assessment and medical coordination. Other implantable options have distinct indications and risks. Demonstration or aided comparison can inform expectations when feasible. Technology choice must account for anatomy, thresholds, speech access, skin or surgical issues, retention, school use, preferences, and current candidacy rules.', ['bone conduction', 'single-sided deafness', 'implantable device']),
      section('Remote microphones, alerting, and classroom systems', 'Remote microphone systems improve signal-to-noise ratio by placing the microphone near the desired source, reducing effects of distance and some background noise. Selection includes compatibility, microphone use, mixing with environmental input, peer access, privacy, charging, handoff routines, and student control. Alerting and captioning technologies address different access goals. Verify electroacoustic or functional performance and train users and communication partners rather than simply issuing equipment.', ['remote microphone', 'signal-to-noise ratio', 'alerting device']),
      section('Connectivity, troubleshooting, and safety', 'Bluetooth and proprietary streaming add convenience but can introduce pairing, latency, routing, update, battery, and privacy issues. Troubleshoot systematically from power and physical condition through microphones, coupling, device settings, accessories, source settings, network, and verified output. MRI and procedure safety depend on exact manufacturer, model, implant generation, magnet conditions, field strength, and current medical instructions. Never generalize compatibility across devices.', ['connectivity', 'troubleshooting', 'MRI conditional']),
    ], [['What does a cochlear implant stimulate?', 'The auditory nerve through electrical stimulation delivered by an implanted electrode array.'], ['Does implantation guarantee a specific speech outcome?', 'No; outcomes vary with auditory, medical, developmental, language, rehabilitation, and personal factors.'], ['What is a major remote-microphone benefit?', 'Improved signal-to-noise ratio by reducing the effective distance to the desired talker.'], ['Are remote microphones only for hearing aids?', 'No; compatibility and routing vary across hearing aids, implants, receivers, and other access systems.'], ['What is the first troubleshooting principle?', 'Move systematically from power and physical connections to settings, accessories, source, and verified output.'], ['How is MRI safety determined?', 'Use the exact device model and current manufacturer and medical conditions; never assume class-wide compatibility.']]),

  chapter('aud5343-ch-11', 'audiologic-rehabilitation-education', 'Audiologic Rehabilitation, Counseling, and Educational Access',
    'Combine technology, communication strategies, auditory and visual access, counseling, family partnership, environmental change, and self-advocacy around meaningful goals.',
    ['Build person- and family-centered rehabilitation plans.', 'Support accessible language and communication choices.', 'Improve school participation through environmental and instructional supports.'], [
      section('Goal setting and rehabilitation planning', 'Begin with the person’s communication priorities, identities, partners, environments, strengths, barriers, technology, language, cognition, vision, motor needs, health, and support. Convert priorities into measurable functional goals and select technology, environmental modifications, communication strategies, training, counseling, and referrals accordingly. Use shared decision making and repeated outcome monitoring. A device-centered plan is incomplete when participation, fatigue, confidence, or partner behavior remains unaddressed.', ['audiologic rehabilitation', 'shared decision making', 'functional goal']),
      section('Counseling and communication strategies', 'Informational counseling explains findings, options, uncertainty, and device use in accessible language. Adjustment counseling supports emotional response, identity, stigma, expectations, problem solving, and confidence within professional scope, with mental-health referral when appropriate. Strategies can include optimizing distance and lighting, gaining attention, reducing competing noise, clarifying rather than merely repeating, confirming key information, and teaching partners. Match strategies to real situations and preferences.', ['informational counseling', 'adjustment counseling', 'communication strategy']),
      section('Family-centered language and early intervention', 'Families need timely, balanced information about spoken languages, signed languages, multimodal communication, technology, early-intervention resources, Deaf community connections, and developmental monitoring. Support reliable accessible language without delaying communication while waiting for device outcomes. Respect culture, family goals, and informed choice, and use qualified language access. Coordinate audiology, education, speech-language, medical, and community resources without presenting one pathway as universally superior.', ['family-centered practice', 'accessible language', 'early intervention']),
      section('Classroom acoustics, plans, and self-advocacy', 'School access can improve through reduced noise and reverberation, favorable seating and visual access, remote microphones, captioning, clear instructional routines, peer access, and planned equipment checks. Audiologists contribute findings and recommendations through authorized IEP or Section 504 processes but do not make unilateral legal determinations. Teach students to identify breakdowns, manage technology, request accommodations, explain preferences, repair communication, and participate in their own planning.', ['classroom acoustics', 'Section 504', 'self-advocacy']),
    ], [['What makes rehabilitation person centered?', 'Goals and supports reflect the person’s priorities, identities, environments, access needs, strengths, and outcomes.'], ['How does adjustment counseling differ from information giving?', 'It addresses emotional response, identity, expectations, coping, and problem solving within scope.'], ['Should language access wait for technology outcomes?', 'No; timely accessible communication and language development remain priorities.'], ['What helps classroom listening beyond seating?', 'Acoustics, technology, visual access, instructional routines, peer access, and monitoring.'], ['What is the audiologist’s school-team role?', 'Contribute specialized audiologic and functional evidence within the authorized collaborative process.'], ['What supports self-advocacy?', 'Recognizing breakdowns, managing devices, requesting access, making choices, and practicing repair strategies.']]),

  chapter('aud5343-ch-12', 'professional-ethical-evidence-practice', 'Professional, Ethical, Legal, Evidence-Based, and Practice Responsibilities',
    'Apply consent, privacy, competence, supervision, evidence, documentation, telepractice, quality, referral, and conflict-of-interest duties to audiologic practice.',
    ['Use ethical decision processes rather than memorized slogans.', 'Differentiate privacy and jurisdiction by setting.', 'Recognize scope, quality, billing, and urgent-referral responsibilities.'], [
      section('Consent, autonomy, privacy, and access', 'Informed consent is an accessible ongoing process describing purpose, procedures, meaningful risks, expected benefits, alternatives, costs when relevant, limits, and voluntary choice. Capacity, assent, surrogate authority, emergencies, and state law can affect the process. For records, identify the setting, record holder, applicable FERPA, HIPAA, state, and organizational rules, authority, and secure minimum-necessary disclosure. Communication access is part of ethical participation, not an optional convenience.', ['informed consent', 'FERPA', 'HIPAA']),
      section('Competence, delegation, and interprofessional care', 'Practice only within current education, training, experience, licensure, certification, and available support. When a task is delegated to an assistant or student, the audiologist must follow applicable rules, confirm competence, provide required supervision, and retain professional accountability. Refer or collaborate when medical, vestibular, mental-health, language, educational, technical, or other needs exceed competence. Automated equipment does not transfer diagnostic responsibility.', ['scope of competence', 'supervision', 'interprofessional practice']),
      section('Evidence, quality, documentation, and conflicts', 'Evidence-based practice integrates appraised research, clinical expertise and data, and the person’s values, culture, circumstances, and goals. Quality systems include calibration, routine equipment and biological checks, infection control, data security, incident response, and outcome monitoring. Documentation and claims must accurately represent findings and services without cloning, omission, upcoding, or misrepresentation. Disclose relevant financial conflicts and preserve objective alternatives and informed choice.', ['evidence-based practice', 'quality assurance', 'conflict of interest']),
      section('Telepractice, jurisdiction, and safety escalation', 'Before teleaudiology, verify authority where the client is located, consent, identity, privacy, accessibility, technology validity, local support, emergency planning, and whether remote procedures answer the clinical question. Licensure and rules can change, so current jurisdictional verification is essential. Acute neurologic signs, sudden hearing loss, severe vestibular symptoms, trauma, or other red flags take priority over finishing a routine battery. Activate medical or emergency procedures and document communication and follow-up.', ['teleaudiology', 'jurisdiction', 'emergency referral']),
    ], [['What makes consent valid?', 'Accessible material information, capacity and authority, questions, voluntariness, and continuing agreement under current law.'], ['Does HIPAA govern every school audiology record?', 'No; determine the setting, record holder, FERPA or HIPAA status, state law, and policy.'], ['Who retains accountability for delegated audiology services?', 'The qualified supervising audiologist within applicable delegation and supervision rules.'], ['What are the three EBP inputs?', 'Best research, clinical expertise and data, and the individual’s values, culture, circumstances, and goals.'], ['What supports ethical documentation and billing?', 'Accurate, timely records and codes that truthfully represent the service and decision.'], ['What must teleaudiology verify?', 'Client-location authority, consent, privacy, accessibility, technical validity, local support, and emergency planning.']]),
];

const memoryAids = [
  aid('Sound Path: Collect, Transfer, Transduce, Transmit', 'Outer ear collects, middle ear transfers, cochlea transduces, and cranial nerve VIII and central pathways transmit and process the signal.', ['anatomy', 'pathway'], [S.ETS, S.ASHA_SCOPE]),
  aid('Cochlear Map: Base High, Apex Low', 'High-frequency traveling-wave maxima occur toward the basal cochlea; low-frequency maxima occur progressively toward the apex.', ['cochlea', 'tonotopy']),
  aid('Hair Cells: IHC Inform, OHC Optimize', 'Inner hair cells provide most afferent information; outer hair cells optimize sensitivity, compression, and frequency selectivity.', ['hair cells', 'physiology']),
  aid('Pressure Decibels: Twenty Log', 'For sound-pressure ratios, use 20 log10. Keep reference quantity and measurement conditions explicit.', ['acoustics', 'decibel']),
  aid('Binaural Cues: Low Time, High Level', 'Lower-frequency localization relies strongly on interaural time differences; higher-frequency localization relies strongly on interaural level differences.', ['binaural', 'localization']),
  aid('Screen, Then Complete the Path', 'A screen identifies risk; it does not diagnose. Every refer or incomplete result needs a clear, timely next step and tracking.', ['screening', 'follow-up'], [S.ETS, S.CDC_EHDI]),
  aid('Cross-Check Before Concluding', 'Compare behavioral, middle-ear, cochlear, neural, symptom, developmental, and functional evidence; investigate disagreement rather than averaging it away.', ['assessment', 'cross-check']),
  aid('Air, Bone, Then Mask When Needed', 'Air tests the available pathway, bone largely bypasses outer and middle ears, and masking controls possible cross-hearing.', ['audiometry', 'masking']),
  aid('SRT Cross-Checks PTA', 'Speech-recognition threshold should generally agree with the pure-tone average when materials, language, responses, and measurement conditions are valid.', ['speech audiometry', 'reliability']),
  aid('Flat Tymp: Check Volume and Context', 'A flat tympanogram needs ear-canal volume, probe quality, otoscopy, age, history, and related findings before interpretation.', ['immittance', 'tympanometry']),
  aid('OAE Is Cochlear Evidence, Not a Hearing Verdict', 'OAEs inform outer hair-cell function under suitable conditions; they do not establish behavioral thresholds, neural synchrony, or speech understanding.', ['OAE', 'cochlea']),
  aid('ABR Estimates, Behavior Confirms', 'ABR samples synchronized neural responses and can estimate sensitivity; stimulus and correction limits apply, and behavioral cross-check remains important.', ['ABR', 'electrophysiology']),
  aid('Vestibular Frequency Map', 'Calorics emphasize low-frequency horizontal-canal function, vHIT samples higher-frequency canal reflexes, and VEMPs sample otolith-related pathways.', ['vestibular', 'test selection']),
  aid('Red Flags Before Routine Testing', 'Sudden hearing change, acute neurologic signs, severe new vestibular symptoms, trauma, or protocol-defined danger signs require timely medical or emergency action.', ['safety', 'referral']),
  aid('Verify the Fitting, Validate the Outcome', 'Verification measures electroacoustic delivery; validation measures benefit, participation, comfort, and goal attainment in real life.', ['hearing aids', 'outcomes']),
  aid('Compression Maps Inputs to the Usable Range', 'Wide dynamic range compression changes gain across input levels to improve access while respecting comfort and maximum-output limits.', ['compression', 'hearing aids']),
  aid('Remote Microphone: Shorten the Acoustic Distance', 'Putting a microphone near the desired talker can improve signal-to-noise ratio despite physical distance, but compatibility and use must be checked.', ['assistive technology', 'school access']),
  aid('Language Access Now, Choices Without Bias', 'Provide balanced information and timely accessible language while respecting culture, identity, family goals, and informed communication choices.', ['early intervention', 'family centered'], [S.ETS, S.ASHA_SCHOOLS]),
  aid('Privacy Starts With the Setting', 'Identify the record holder, setting, applicable FERPA, HIPAA, state, and organizational rules, authority, and secure minimum-necessary disclosure.', ['privacy', 'records'], [S.FERPA, S.HIPAA]),
  aid('EBP Is a Three-Way Integration', 'Combine critically appraised research, clinical expertise and data, and the individual’s values, culture, circumstances, preferences, and goals.', ['evidence-based practice', 'ethics'], [S.ASHA_EBP, S.ASHA_ETHICS]),
];

module.exports = { chapters, memoryAids };
