const fs=require('node:fs'),parser=require('@babel/parser'),traverse=require('@babel/traverse').default,crypto=require('node:crypto');const file='stem_lab/stem_tool_anatomy.js';let s=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),english={};
fs.writeFileSync(__dirname+'/baseline.json',JSON.stringify({sha256:crypto.createHash('sha256').update(s).digest('hex')},null,2));const bank=JSON.parse(fs.readFileSync(__dirname+'/content.json','utf8'));
function T(key,value){english['case_ref_'+key]=value;return 't('+JSON.stringify('stem.anatomy.case_ref_'+key)+','+JSON.stringify(value)+')';}function rep(a,b){if(s.split(a).length!==2)throw Error('Missing/duplicate '+a.slice(0,100));s=s.replace(a,b);}
const edits=[];traverse(parser.parse(s,{sourceType:'script'}),{VariableDeclarator(p){if(p.node.id.name!=='CLINICAL_CASES')return;for(const cs of p.node.init.elements){const id=cs.properties.find(p=>p.key.name==='id').value.value,row=bank[id];for(const field of ['presentation','question','answer','explanation']){const n=cs.properties.find(p=>p.key.name===field).value;edits.push({start:n.start,end:n.end,text:T(id+'_'+field,row[field])});}edits.push({start:cs.end-1,end:cs.end-1,text:','+['hint','limit','scope'].map(field=>field+':'+T(id+'_'+field,row[field])).join(',')+',structureId:'+JSON.stringify(row.structureId)+',reference:'+JSON.stringify(row.reference)});}}});for(const edit of edits.sort((a,b)=>b.start-a.start))s=s.slice(0,edit.start)+edit.text+s.slice(edit.end);
const stateAnchor="        var activeCaseFeedback = activeCaseId && d._activeCaseFeedback === 'reveal' ? 'reveal' : null;";
rep(stateAnchor,stateAnchor+`
        function validCaseStudy(raw){var result={};if(!raw||raw.version!==1||!raw.cases||typeof raw.cases!=='object'||Array.isArray(raw.cases))return result;clinicalCaseIds.forEach(function(id){var row=raw.cases[id];if(row&&typeof row==='object'&&!Array.isArray(row))result[id]={draft:typeof row.draft==='string'?row.draft.slice(0,600):'',hint:row.hint===true,revealed:row.revealed===true};});return result;}
        var caseStudy=validCaseStudy(d._clinicalStudy);
        function caseIsRevealed(cs,entry,state){return entry?entry.revealed:!!(safeFlagMap(state._clinicalSolvedIds,clinicalCaseIds)[cs.id]||(state._activeCaseId===cs.id&&state._activeCaseFeedback==='reveal'));}
        function updateCaseStudy(cs,action,value){
          if(!cs||clinicalCaseIds.indexOf(cs.id)===-1||['draft','hint','reveal','hide','review'].indexOf(action)===-1)return;
          if(action==='draft'&&typeof value!=='string')return;
          setLabToolData(function(previous){var state=previous.anatomy||{};if((SYSTEMS[state.system]?state.system:'skeletal')!==cs.system||state._showClinical!==true)return previous;var cases=validCaseStudy(state._clinicalStudy),prior=cases[cs.id],entry=Object.assign({draft:'',hint:false,revealed:caseIsRevealed(cs,prior,state)},prior||{}),patch={};
            if(action==='draft')entry.draft=value.slice(0,600);
            else if(action==='hint')entry.hint=!entry.hint;
            else if(action==='reveal')entry.revealed=true;
            else if(action==='hide'){entry.revealed=false;entry.hint=false;}
            else {if(!entry.revealed)return previous;var reviewed=safeFlagMap(state._clinicalSolvedIds,clinicalCaseIds);if(reviewed[cs.id])return previous;reviewed[cs.id]=true;patch={_activeCaseId:cs.id, _activeCaseFeedback: 'reveal', _clinicalSolvedIds:reviewed,_clinicalSolved:Object.keys(reviewed).length};}
            cases[cs.id]=entry;patch._clinicalStudy={version:1,cases:cases};return Object.assign({},previous,{anatomy:Object.assign({},state,patch)});
          });
          if(action==='review'){playSound('guidedStep');setTimeout(checkAnatomyChallenges,50);}
        }
        function focusClinicalCase(id){setTimeout(function(){var panel=document.querySelector('[data-anatomy-case="'+id+'"]');if(panel){panel.focus({preventScroll:true});panel.scrollIntoView({block:'start',behavior:'auto'});}},0);}
        function showCaseMarker(cs){updMulti(structureFocusPatch(cs.structureId,{_caseDiagramReturn:cs.id}));announceStructure(cs.structureId);setTimeout(function(){var panel=document.querySelector('[data-anatomy-model-shell]');if(panel){panel.focus({preventScroll:true});panel.scrollIntoView({block:'start',behavior:'auto'});}},0);}
        function renderClinicalCase(cs){
          var entry=caseStudy[cs.id],revealed=caseIsRevealed(cs,entry,d),hint=entry&&entry.hint,reviewed=!!clinicalSolvedIds[cs.id],id='anatomy-case-'+cs.id;
          return h('article',{key:cs.id,'data-anatomy-case':cs.id,className:'anatomy-case-card',tabIndex:-1,'aria-labelledby':id+'-title'},
            h('h4',{id:id+'-title'},cs.title),
            reviewed?h('p',{className:'anatomy-case-reviewed','data-anatomy-case-reviewed':cs.id},${T('reviewed','Explanation reviewed')}):null,
            h('p',null,cs.presentation),
            h('p',{className:'anatomy-case-question',id:id+'-question'},cs.question),
            ttsBtn(cs.presentation+' '+cs.question,${T('read_case','Read this case aloud')}),
            h('label',{htmlFor:id+'-draft'},${T('reasoning','Your reasoning (optional)')}),
            h('p',{id:id+'-help',className:'anatomy-case-help'},${T('reasoning_help','Name a relevant structure or mechanism, cite a clue, and note what remains uncertain. Your draft stays with this case in this activity.')}),
            h('textarea',{id:id+'-draft','data-anatomy-case-draft':cs.id,'aria-describedby':id+'-help',maxLength:600,rows:3,value:entry?entry.draft:'',onChange:function(event){updateCaseStudy(cs,'draft',event.target.value);}}),
            h('div',{className:'anatomy-case-actions'},h('button',{type:'button','data-anatomy-case-hint-toggle':cs.id,'aria-expanded':!!hint,'aria-controls':id+'-hint',onClick:function(){updateCaseStudy(cs,'hint');}},hint?${T('hide_hint','Hide hint')}:${T('show_hint','Use a hint')}),
              h('button',{type:'button','data-anatomy-case-reveal':cs.id,'aria-expanded':revealed,'aria-controls':id+'-explanation',onClick:function(){updateCaseStudy(cs,revealed?'hide':'reveal');}},revealed?${T('try_again','Hide explanation and try again')}:${T('compare','Compare with the explanation')})),
            h('div',{id:id+'-hint',hidden:!hint,'data-anatomy-case-hint':cs.id,className:'anatomy-case-hint'},hint?cs.hint:null),
            h('div',{id:id+'-explanation',hidden:!revealed,'data-anatomy-case-explanation':cs.id,className:'anatomy-case-explanation'},revealed?h('div',null,
              h('h5',null,${T('anatomical_explanation','Anatomical explanation')}),h('p',{className:'anatomy-case-answer'},cs.answer),h('p',null,cs.explanation),
              h('h5',null,${T('uncertainty','What the clues cannot establish')}),h('p',null,cs.limit),
              h('p',{className:'anatomy-case-help'},${T('compare_prompt','Compare this with your reasoning. Which clue mattered, and what would you change?')}),
              h('a',{href:cs.reference,target:'_blank',rel:'noopener noreferrer'},${T('source','Read the source')}),
              ttsBtn(cs.answer+' '+cs.explanation+' '+cs.limit,${T('read_explanation','Read the explanation aloud')}),
              h('p',{className:'anatomy-case-scope'},cs.scope),
              h('div',{className:'anatomy-case-actions'},h('button',{type:'button','data-anatomy-case-marker':cs.id,onClick:function(){showCaseMarker(cs);}},${T('marker','Show the related anatomy')}),
                h('button',{type:'button','data-anatomy-case-review':cs.id,disabled:reviewed,onClick:function(){updateCaseStudy(cs,'review');}},reviewed?${T('reviewed','Explanation reviewed')}:${T('mark_reviewed','Mark explanation reviewed')}))
            ):null)
          );
        }
`);
const start=s.indexOf('              systemClinicalCases.slice(0, 3).map(function(cs, ci) {'),end=s.indexOf('\n            ) : null\n          ) : null,',start);if(start<0||end<0)throw Error('Clinical rendering bounds');
s=s.slice(0,start)+"              h('p',{className:'anatomy-case-intro'},"+T('intro','Use these fictional cases to connect clues with anatomy. Write or think through an explanation, compare it with the model, then mark it reviewed. Reviewed records participation, not diagnostic accuracy.')+"),\n              systemClinicalCases.map(renderClinicalCase)"+s.slice(end);
const sectionStart=s.indexOf('// ── Clinical Cases section'),sectionEnd=s.indexOf('// ── Badge section',sectionStart);let block=s.slice(sectionStart,sectionEnd);
block=block.replace("className: 'mt-4 rounded-xl border border-rose-200 p-3'","className: 'anatomy-clinical-study mt-4 rounded-xl border border-rose-200 p-3', 'data-anatomy-clinical-study':true");
block=block.replace("'\\uD83E\\uDE7A Clinical Cases (' + clinicalSolved + ' reviewed)'",T('title','Clinical Cases')+" + ' (' + "+T('progress','{count} reviewed')+".replace('{count}',String(clinicalSolved)) + ')'");
block=block.replace("showClinical ? 'Hide' : 'Show Cases'","showClinical ? "+T('hide_cases','Hide')+" : "+T('show_cases','Show Cases'));
s=s.slice(0,sectionStart)+block+s.slice(sectionEnd);
rep("                activeTab === 'connections' && expandedConnectionId ?", "                showClinical && clinicalCaseIds.indexOf(d._caseDiagramReturn)!==-1 && CLINICAL_CASES.some(function(cs){return cs.id===d._caseDiagramReturn&&cs.system===sysKey;}) && h('button',{type:'button',className:'anatomy-route-return','data-anatomy-case-return':d._caseDiagramReturn,onClick:function(){focusClinicalCase(d._caseDiagramReturn);}},"+T('return','Return to case')+"),\n                activeTab === 'connections' && expandedConnectionId ?");
const css='.anatomy-clinical-study{color:#0f172a}.anatomy-clinical-study>div:first-child{gap:12px;flex-wrap:wrap}.anatomy-clinical-study h3{color:#9f1239!important;font-size:14px!important}.anatomy-clinical-study p,.anatomy-clinical-study label,.anatomy-clinical-study a{font-size:13px;line-height:1.6}.anatomy-case-card{background:#fff;border:1px solid #94a3b8;border-radius:10px;padding:16px;margin-block:14px;scroll-margin-top:16px}.anatomy-case-card h4{font-size:16px;font-weight:800;color:#881337;margin-bottom:8px}.anatomy-case-card h5{font-size:14px;font-weight:800;margin-block:10px 4px}.anatomy-case-card p{margin-block:8px}.anatomy-case-card label{display:block;font-weight:700;margin-top:12px}.anatomy-case-card textarea{display:block;width:100%;box-sizing:border-box;resize:vertical;min-height:96px;padding:10px;border:1px solid #64748b;border-radius:8px;background:#fff;color:#0f172a;font-size:16px;line-height:1.5}.anatomy-case-help,.anatomy-case-scope{color:#475569}.anatomy-case-question,.anatomy-case-answer{font-weight:700}.anatomy-case-actions{display:flex;flex-wrap:wrap;gap:8px;margin-block:12px}.anatomy-clinical-study button{min-height:44px;font-size:13px;padding:8px 12px;border:1px solid #9f1239;border-radius:7px;color:#881337;background:#fff;text-align:start}.anatomy-clinical-study button:disabled{color:#334155;border-color:#94a3b8;background:#e2e8f0}.anatomy-case-hint,.anatomy-case-explanation{border:1px solid #cbd5e1;border-radius:8px;padding:12px;margin-top:10px;background:#f8fafc}.anatomy-case-hint{font-size:13px;line-height:1.6}.anatomy-clinical-study [hidden]{display:none!important}.anatomy-case-reviewed{color:#166534;font-weight:700}.anatomy-clinical-study a{display:inline-block;color:#075985;text-decoration:underline;margin-block:8px}.anatomy-clinical-study :focus-visible,.anatomy-case-card:focus{outline:3px solid #0284c7;outline-offset:3px}.theme-dark .anatomy-clinical-study,.theme-dark .anatomy-case-card{background:#0f172a!important;color:#e2e8f0!important;border-color:#64748b!important}.theme-dark .anatomy-clinical-study h3,.theme-dark .anatomy-clinical-study h4{color:#fecdd3!important}.theme-dark .anatomy-clinical-study p,.theme-dark .anatomy-clinical-study label,.theme-dark .anatomy-clinical-study h5{color:#e2e8f0!important}.theme-dark .anatomy-clinical-study button,.theme-dark .anatomy-clinical-study textarea,.theme-dark .anatomy-case-hint,.theme-dark .anatomy-case-explanation{background:#1e293b!important;color:#e2e8f0!important;border-color:#94a3b8!important}.theme-dark .anatomy-clinical-study a{color:#7dd3fc}.theme-dark .anatomy-clinical-study .anatomy-case-reviewed{color:#86efac!important}';
rep('".anatomy-tour-panel{',JSON.stringify(css)+',\n      ".anatomy-tour-panel{');
parser.parse(s,{sourceType:'script'});fs.writeFileSync(file,s);fs.writeFileSync('desktop/web-app/public/'+file,s);fs.writeFileSync(__dirname+'/english.json',JSON.stringify(english,null,2)+'\n');console.log(Object.keys(english).length+' strings; clinical reasoning flow applied.');
