const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto'),parser=require('@babel/parser'),traverse=require('@babel/traverse').default;
const source=fs.readFileSync('stem_lab/stem_tool_anatomy.js','utf8'),hash=crypto.createHash('sha256').update(source).digest('hex');assert.equal(source,fs.readFileSync('desktop/web-app/public/stem_lab/stem_tool_anatomy.js','utf8'));
const english=JSON.parse(fs.readFileSync(__dirname+'/english.json','utf8')),registry=JSON.parse(fs.readFileSync('dev-tools/i18n/stem_anatomy_en.json','utf8')),table=JSON.parse(fs.readFileSync('dev-tools/i18n/handtl_anatomy_cases_20260912.json','utf8')),seen=new Set(),vars=s=>(s.match(/\{\w+\}/g)||[]).sort();
traverse(parser.parse(source,{sourceType:'script'}),{CallExpression(p){const key=p.node.arguments[0]?.value;if(typeof key==='string'&&key.startsWith('stem.anatomy.case_ref_')){assert.equal(p.node.arguments[1]?.value,english[key.slice(13)]);seen.add(key.slice(13));}}});assert.equal(seen.size,77);
for(const [key,value]of Object.entries(english))assert.equal(registry[key],value);
for(const [lang,dict]of Object.entries(table)){const packs=['','desktop/web-app/public/'].map(prefix=>JSON.parse(fs.readFileSync(prefix+'lang/'+lang+'.js','utf8')).stem.anatomy);assert.equal(Object.keys(dict).length,77);for(const [key,value]of Object.entries(dict)){assert.ok(value&&value!==english[key]);assert.deepEqual(vars(value),vars(english[key]));for(const pack of packs)assert.equal(pack[key],value);}}
const b=JSON.parse(fs.readFileSync(__dirname+'/browser-results.json','utf8')),t=JSON.parse(fs.readFileSync(__dirname+'/test-results.json','utf8'));assert.equal(t.success,true);assert.equal(t.numFailedTests,0);assert.equal(b.cases.length,8);assert.equal(b.axe.length,25);assert.deepEqual(b.errors,[]);assert.deepEqual(b.axe.flatMap(x=>x.violations),[]);assert.deepEqual(b.axe.flatMap(x=>x.incomplete),[]);
const v={syntax:'pass',source:'stem_lab/stem_tool_anatomy.js',sha256:hash,mirrorIdentical:true,localizedStrings:77,validatedPacks:6,cases:8,testFiles:t.testResults.length,passedTests:t.numPassedTests,failedTests:t.numFailedTests,axeScans:b.axe.length,axeViolations:0,axeIncomplete:0,browserErrors:0,screenshots:b.screens.length};fs.writeFileSync(__dirname+'/verification.json',JSON.stringify(v,null,2)+'\n');console.log(JSON.stringify(v,null,2));
const file=__dirname+'/README.md';let report=fs.readFileSync(file,'utf8');if(!report.includes('### Automated results')){report+='\n### Automated results\n\n- '+v.passedTests+' tests passed across '+v.testFiles+' anatomy test files.\n- '+v.axeScans+' axe scans: no violations or incomplete checks.\n- Active source SHA-256: `'+hash+'`.\n- Two initial targeted tests exceeded the cold-file-access time limits; the full run used a 30-second test timeout and a 60-second hook timeout. No assertion changes were needed for those timeouts.\n';fs.writeFileSync(file,report);}
