const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),parser=require('@babel/parser'),traverse=require('@babel/traverse').default;
const file='stem_lab/stem_tool_anatomy.js',source=fs.readFileSync(file,'utf8'),ast=parser.parse(source),decls={};
traverse(ast,{VariableDeclarator(p){if(['SYSTEMS','ANAT_VOCAB','SIMPLE_DESC','ELEMENTARY_IDS'].includes(p.node.id.name))decls[p.node.id.name]=p.node.init;}});
function evaluate(name,dict={}){const n=decls[name];return vm.runInNewContext('('+source.slice(n.start,n.end)+')',{t:(key,fallback)=>dict[key.slice(13)]||fallback});}
const systems=evaluate('SYSTEMS'),vocab=evaluate('ANAT_VOCAB'),simple=evaluate('SIMPLE_DESC'),elementary=evaluate('ELEMENTARY_IDS');
const structs=Object.entries(systems).flatMap(([system,s])=>s.structures.map(item=>({system,...item})));
const languages={};for(const lang of ['english','spanish_latin_america','french','arabic']){const dict=lang==='english'?{}:JSON.parse(fs.readFileSync('lang/'+lang+'.js','utf8')).stem.anatomy;const list=Object.values(evaluate('SYSTEMS',dict)).flatMap(s=>s.structures);languages[lang]=Object.keys(vocab).map(term=>({term,structures:list.filter(s=>s.name.toLowerCase().includes(term.toLowerCase())).map(s=>({id:s.id,name:s.name}))}));}
const result={source:file,sha256:crypto.createHash('sha256').update(source).digest('hex'),mirrorIdentical:fs.readFileSync(file).equals(fs.readFileSync('desktop/web-app/public/'+file)),counts:{structures:structs.length,uniqueIds:new Set(structs.map(s=>s.id)).size,vocabulary:Object.keys(vocab).length,elementaryIds:elementary.length},vocabulary:languages,elementaryWithoutSimpleDescription:elementary.filter(id=>!simple[id]),brain:structs.find(s=>s.id==='brain')};
fs.writeFileSync(__dirname+'/inventory.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({sha256:result.sha256,mirrorIdentical:result.mirrorIdentical,counts:result.counts,glossaryReach: Object.fromEntries(Object.entries(languages).map(([lang,terms])=>[lang,{matched:terms.filter(t=>t.structures.length).map(t=>t.term),unmatched:terms.filter(t=>!t.structures.length).map(t=>t.term)}])),elementaryWithoutSimpleDescription:result.elementaryWithoutSimpleDescription},null,2));
