#!/usr/bin/env node
/**
 * Build script: story_forge_source.jsx → story_forge_module.js
 *
 * Reads StoryForge JSX source, transforms JSX → React.createElement via esbuild,
 * wraps in IIFE with dependency injection, outputs CDN-ready module.
 */

const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

const SOURCE_JSX = path.join(__dirname, 'story_forge_source.jsx');
const OUTPUT = path.join(__dirname, 'story_forge_module.js');
const OUTPUT_PUBLIC = path.join(__dirname, 'prismflow-deploy', 'public', 'story_forge_module.js');
const TEMP = path.join(__dirname, '_temp_story_forge.jsx');

if (!fs.existsSync(SOURCE_JSX)) {
    console.error('❌ Source file not found: ' + SOURCE_JSX);
    process.exit(1);
}

console.log('📦 Building story_forge_module.js...\n');

const jsxSource = fs.readFileSync(SOURCE_JSX, 'utf-8');
const totalLines = jsxSource.split('\n').length;
console.log(`   Read ${totalLines} lines from story_forge_source.jsx`);

// ── Write temp JSX file for esbuild ──
const preamble = `/* eslint-disable */
// StoryForge module — DO NOT EDIT MANUALLY
// Generated by _build_story_forge_module.js
`;

fs.writeFileSync(TEMP, preamble + jsxSource, 'utf-8');
console.log(`   Temp JSX file: ${TEMP}`);

// ── Transform JSX via esbuild ──
console.log('   Running esbuild JSX transform...');
let transformed;
try {
    transformed = execSync(
        `npx esbuild "${TEMP}" --jsx=transform --bundle=false --target=es2020`,
        { encoding: 'utf-8', maxBuffer: 1024 * 1024 * 50 }
    );
} catch (e) {
    console.error('❌ esbuild failed:', e.message);
    if (e.stderr) console.error(e.stderr);
    process.exit(1);
}

// Clean up temp file
fs.unlinkSync(TEMP);
console.log('   ✅ JSX transformed successfully');

// ── Post-process: const → var for top-level declarations ──
// esbuild emits `const` for top-level declarations. Inside the IIFE these
// need to be `var` so they're accessible at the bottom for registration.
const TOP_LEVEL_CONSTS = [
    'escapeHtml', 'cleanJson', 'useAudioRecorder', 'useDictation', 'useReducedMotion',
    'VOICE_POOL', 'ART_STYLE_MAP', 'LAYOUT_MODES',
    'GENRE_TEMPLATES', 'SAVE_KEY', 'STORY_STARTERS', 'computeReadingLevel',
    'PHASES', 'PHASE_LABELS', 'LANG_OPTIONS', 'StoryForge'
];

TOP_LEVEL_CONSTS.forEach(name => {
    const pattern = new RegExp(`const ${name} = `, 'g');
    transformed = transformed.replace(pattern, `var ${name} = `);
});

// ── Icons used by StoryForge ──
const iconList = [
    'ArrowLeft', 'ArrowRight', 'BookOpen', 'CheckCircle2', 'Download',
    'Eye', 'HelpCircle', 'ImageIcon', 'Mic', 'Palette', 'Play', 'Plus',
    'RefreshCw', 'Sparkles', 'Star', 'Trash2', 'Type', 'Volume2', 'X'
];

// ── Build IIFE wrapper ──
const iifeHeader = `/**
 * AlloFlow StoryForge Module
 *
 * Scaffolded creative writing with AI illustration, narration, grading, and storybook export.
 *
 * Auto-generated by _build_story_forge_module.js — DO NOT EDIT MANUALLY.
 * Source: story_forge_source.jsx
 */
(function() {
  'use strict';

  // ── Duplicate-load guard ──
  if (window.__storyForgeModuleLoaded) {
    console.warn('[StoryForge] Already loaded — skipping');
    return;
  }
  window.__storyForgeModuleLoaded = true;

  // ── React dependencies ──
  var React = window.React;
  if (!React) { console.error('[StoryForge] React not found on window'); return; }
  var useState = React.useState;
  var useEffect = React.useEffect;
  var useRef = React.useRef;
  var useCallback = React.useCallback;
  var useMemo = React.useMemo;
  var useReducer = React.useReducer;

  // ── Lucide icons from host app ──
  var _icons = window.AlloIcons || {};
${iconList.map(ic => `  var ${ic} = _icons.${ic} || function() { return null; };`).join('\n')}

  // ═══════════════════════════════════════════════════════════════
  // STORYFORGE COMPONENT (JSX pre-transformed by esbuild)
  // ═══════════════════════════════════════════════════════════════

`;

const iifeFooter = `

  // ═══════════════════════════════════════════════════════════════
  // REGISTRATION
  // ═══════════════════════════════════════════════════════════════
  window.AlloModules = window.AlloModules || {};
  window.AlloModules.StoryForge = StoryForge;

  console.log('[StoryForge] Module registered');
})();
`;

const finalModule = iifeHeader + transformed + iifeFooter;

// ── Write output ──
fs.writeFileSync(OUTPUT, finalModule, 'utf-8');
console.log(`\n📄 Written: ${path.relative(__dirname, OUTPUT)} (${finalModule.split('\n').length} lines)`);

fs.writeFileSync(OUTPUT_PUBLIC, finalModule, 'utf-8');
console.log(`📄 Written: ${path.relative(__dirname, OUTPUT_PUBLIC)}`);

console.log(`\n✅ story_forge_module.js built successfully`);
