#!/usr/bin/env node
/**
 * Build script: VisualPanelGrid → visual_panel_module.js
 *
 * Contains: VisualPanelGrid (visual lesson plan editor with drawing,
 *           labels, image overrides, and challenge mode)
 *
 * Reads JSX source, transforms via esbuild, wraps in IIFE with
 * dependency injection, outputs CDN-ready module.
 */

const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

const SOURCE_JSX = path.join(__dirname, 'visual_panel_source.jsx');
const OUTPUT = path.join(__dirname, 'visual_panel_module.js');
const OUTPUT_PUBLIC = path.join(__dirname, 'prismflow-deploy', 'public', 'visual_panel_module.js');
const TEMP = path.join(__dirname, '_temp_visual_panel.jsx');

console.log('📦 Building visual_panel_module.js...\n');

if (!fs.existsSync(SOURCE_JSX)) {
    console.error('❌ visual_panel_source.jsx not found');
    process.exit(1);
}

const jsxSource = fs.readFileSync(SOURCE_JSX, 'utf-8');
console.log(`   Read ${jsxSource.split('\n').length} lines from visual_panel_source.jsx`);

// ── Write temp JSX file for esbuild ──
const preamble = `/* eslint-disable */
// Auto-extracted VisualPanelGrid — DO NOT EDIT MANUALLY
// Generated by _build_visual_panel_module.js
`;

fs.writeFileSync(TEMP, preamble + jsxSource, 'utf-8');
console.log(`   Temp JSX file: ${TEMP}`);

// ── Transform JSX via esbuild ──
console.log('   Running esbuild JSX transform...');
let transformed;
try {
    transformed = execSync(
        `npx esbuild "${TEMP}" --jsx=transform --bundle=false --target=es2020`,
        { encoding: 'utf-8', maxBuffer: 1024 * 1024 * 50 }
    );
} catch (e) {
    console.error('❌ esbuild failed:', e.message);
    if (e.stderr) console.error(e.stderr);
    process.exit(1);
}

// Clean up temp file
fs.unlinkSync(TEMP);
console.log('   ✅ JSX transformed successfully');

// ── Post-process: fix const → var for top-level declarations ──
const topLevelNames = ['VisualPanelGrid'];
topLevelNames.forEach(name => {
    const pattern = new RegExp(`const ${name} = `, 'g');
    transformed = transformed.replace(pattern, `var ${name} = `);
});

// ── Build IIFE wrapper ──
const iifeHeader = `/**
 * AlloFlow Visual Panel Module
 *
 * Contains: VisualPanelGrid
 *
 * Auto-generated by _build_visual_panel_module.js — DO NOT EDIT MANUALLY.
 * Source: visual_panel_source.jsx
 */
(function() {
  'use strict';

  // ── Duplicate-load guard ──
  if (window.__visualPanelModuleLoaded) {
    console.warn('[VisualPanelModule] Already loaded — skipping');
    return;
  }
  window.__visualPanelModuleLoaded = true;

  // ── React dependencies ──
  var React = window.React;
  if (!React) { console.error('[VisualPanelModule] React not found on window'); return; }
  var useState = React.useState;
  var useEffect = React.useEffect;
  var useRef = React.useRef;
  var useCallback = React.useCallback;
  var useMemo = React.useMemo;

  // ═══════════════════════════════════════════════════════════════
  // VISUAL PANEL COMPONENTS (JSX pre-transformed by esbuild)
  // ═══════════════════════════════════════════════════════════════

`;

const iifeFooter = `

  // ═══════════════════════════════════════════════════════════════
  // REGISTRATION
  // ═══════════════════════════════════════════════════════════════
  window.AlloModules = window.AlloModules || {};
  window.AlloModules.VisualPanelGrid = VisualPanelGrid;
  window.AlloModules.VisualPanelModule = true;

  console.log('[VisualPanelModule] VisualPanelGrid registered successfully');
})();
`;

const finalModule = iifeHeader + transformed + iifeFooter;

// ── Write output ──
fs.writeFileSync(OUTPUT, finalModule, 'utf-8');
console.log(`\n📄 Written: ${path.relative(__dirname, OUTPUT)} (${finalModule.split('\n').length} lines)`);

fs.writeFileSync(OUTPUT_PUBLIC, finalModule, 'utf-8');
console.log(`📄 Written: ${path.relative(__dirname, OUTPUT_PUBLIC)}`);

console.log('\n✅ visual_panel_module.js built successfully');
