const fs=require('node:fs'),assert=require('node:assert/strict');const {chromium}=require('playwright');const out='reports/video-studio-portable-projects-2026-09-08';
const html=fs.readFileSync('video_studio/video_studio.html','utf8'),shared=html.slice(html.indexOf('  function vsFormatTimestamp('),html.indexOf('// [VS_SHARED_END]'));const {vsReadZip,vsBuildZip}=new Function(shared+';return {vsReadZip,vsBuildZip};')();
const source=fs.readFileSync('reports/video-studio-usability-2026-09-08/regression/export-fixture.webm');
const wav=Buffer.alloc(44+16000*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
(async()=>{const browser=await chromium.launch({headless:true});const errors=[];try{
 const fresh=async()=>{const p=await browser.newPage({viewport:{width:1360,height:960}});p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.request().url().startsWith('http://studio.test/')?r.fulfill({contentType:'text/html',body:html}):r.abort());await p.goto('http://studio.test/');return p;};
 const page=await fresh();await page.locator('#importInput').setInputFiles({name:'Portable lesson.webm',mimeType:'video/webm',buffer:source});await page.waitForFunction(()=>document.querySelector('#editVideo').duration>0);await page.locator('#editorFocusMode').selectOption('all');
 await page.locator('#trimStart').fill('0.3');await page.locator('#trimEnd').fill('0.2');await page.locator('#trimEnd').blur();await page.locator('#addZoomBtn').click();await page.locator('#importCapInput').setInputFiles({name:'lesson.vtt',mimeType:'text/vtt',buffer:Buffer.from('WEBVTT\n\n00:00:00.100 --> 00:00:01.500\nA portable caption\n')});await page.locator('#musicFileInput').setInputFiles({name:'Music.wav',mimeType:'audio/wav',buffer:wav});await page.locator('#clipFileInput').setInputFiles({name:'Sound.wav',mimeType:'audio/wav',buffer:wav});
 await page.locator('#tabExport').click();await page.locator('#titleInput').fill('Portable fractions');await page.locator('#exportPreset').selectOption('social_square');await page.locator('#closingCardText').fill('Keep practicing');await page.locator('#closingCardChk').check();await page.locator('#captionPosition').selectOption('top');
 const download=async(p,locator,name)=>{const event=p.waitForEvent('download');await locator.click();const d=await event;await d.saveAs(out+'/'+name);return fs.readFileSync(out+'/'+name);};
 await page.locator('#tabRecord').click();const archive=await download(page,page.locator('#saveProjectBtn'),'editable.allopack');const entries=vsReadZip(archive),get=name=>entries.find(e=>e.name===name);const video=entries.find(e=>/\.webm$/.test(e.name)&&!/^audio\/|music_bed/.test(e.name));assert.deepEqual(Buffer.from(video.data),source,'Bundled video is byte-for-byte original');assert.match(Buffer.from(get('project_readme.txt').data).toString(),/^AlloFlow Video Studio project bundle/);const state=JSON.parse(Buffer.from(get('editor_state.json').data));assert.equal(state.exportSettings.titleInput,'Portable fractions');assert.deepEqual(state.trim,{start:0.3,end:0.2});assert.equal(state.zooms.length,1);assert.deepEqual(Buffer.from(get('music_bed.wav').data),wav);assert.deepEqual(Buffer.from(entries.find(e=>/^audio\//.test(e.name)).data),wav);
 const reopened=await fresh();await reopened.locator('#importInput').setInputFiles({name:'editable.allopack',mimeType:'application/zip',buffer:archive});await reopened.waitForFunction(()=>document.querySelector('#editVideo').duration>0);await reopened.locator('#editorFocusMode').selectOption('all');assert.equal(await reopened.locator('#trimStart').inputValue(),'0.3');assert.equal(await reopened.locator('#trimEnd').inputValue(),'0.2');assert.equal(await reopened.getByRole('button',{name:'Delete zoom 1',exact:true}).count(),1);assert.equal(await reopened.getByRole('textbox',{name:'text for caption 1',exact:true}).inputValue(),'A portable caption');assert.match(await reopened.locator('#musicBedBox').textContent(),/Music.wav/);assert.equal(await reopened.getByRole('button',{name:'Preview clip 1',exact:true}).count(),1);assert.match(await reopened.locator('#editImportSummaryBox').textContent(),/trim and zoom edits/);await reopened.locator('#editImportSummaryBox').scrollIntoViewIfNeeded();await reopened.screenshot({path:out+'/restored-desktop.png'});await reopened.setViewportSize({width:390,height:844});await reopened.locator('#editImportSummaryBox').scrollIntoViewIfNeeded();assert.equal(await reopened.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await reopened.screenshot({path:out+'/restored-mobile.png'});await reopened.setViewportSize({width:1360,height:960});await reopened.getByRole('button',{name:'Open review export settings for this restored project',exact:true}).click();assert.equal(await reopened.locator('#titleInput').inputValue(),'Portable fractions');assert.equal(await reopened.locator('#exportFormat').inputValue(),'square_1080');assert.equal(await reopened.locator('#captionPosition').inputValue(),'top');assert.equal(await reopened.locator('#closingCardText').inputValue(),'Keep practicing');
 // Saving a shelf row must use that draft, even when another take is selected.
 await page.locator('#importInput').setInputFiles({name:'Other lesson.webm',mimeType:'video/webm',buffer:source});await page.locator('#tabExport').click();await page.locator('#titleInput').fill('Other title');await page.locator('#tabRecord').click();const shelf=page.locator('#projectShelf .project-row').filter({hasText:'Portable lesson'});const shelfArchive=await download(page,shelf.getByRole('button',{name:'Save .allopack',exact:true}),'shelf.allopack');const shelfState=JSON.parse(Buffer.from(vsReadZip(shelfArchive).find(e=>e.name==='editor_state.json').data));assert.equal(shelfState.exportSettings.titleInput,'Portable fractions');assert.deepEqual(shelfState.trim,{start:0.3,end:0.2});
 // Recovery also retains the edits restored from a portable project.
 await reopened.reload();await reopened.locator('#recoverBtn').click();assert.equal(await reopened.locator('#trimStart').inputValue(),'0.3');await reopened.locator('#tabExport').click();assert.equal(await reopened.locator('#titleInput').inputValue(),'Portable fractions');
 // Prepare a real rendered file and ensure the result bundle does not restore source edits/audio again.
 await reopened.locator('#exportPreset').selectOption('small');await reopened.locator('#closingCardChk').uncheck();await reopened.locator('#exportContainer').selectOption('webm');await reopened.locator('#capMode').selectOption('none');await reopened.locator('#exportBtn').click();await reopened.locator('#resultCard').waitFor({state:'visible',timeout:60000});const renderedVideo=await download(reopened,reopened.locator('#downloadBtn'),'rendered.webm');const rendered=await download(reopened,reopened.locator('#downloadProjectResultBtn'),'rendered.allopack');const renderedEntries=vsReadZip(rendered);assert.deepEqual(Buffer.from(renderedEntries.find(e=>/\.webm$/.test(e.name)).data),renderedVideo);assert.ok(!renderedEntries.some(e=>e.name==='editor_state.json'||e.name==='music_bed.wav'||/^audio\//.test(e.name)));assert.match(Buffer.from(renderedEntries.find(e=>e.name==='project_readme.txt').data).toString(),/Rendered export bundle/);
 const resultPage=await fresh();await resultPage.locator('#importInput').setInputFiles({name:'rendered.allopack',mimeType:'application/zip',buffer:rendered});await resultPage.waitForFunction(()=>document.querySelector('#editVideo').duration>0);assert.equal(await resultPage.locator('#trimStart').inputValue(),'0');assert.equal(await resultPage.getByRole('button',{name:'Delete zoom 1',exact:true}).count(),0);assert.equal(await resultPage.locator('#musicBedBox').textContent(),'');
 // Recover the exact former saver bug: video bytes under README, empty video entry.
 const damaged=vsBuildZip(entries.filter(e=>e.name!=='editor_state.json').map(e=>e.name==='project_readme.txt'?{name:e.name,data:new Uint8Array(source)}:e.name===video.name?{name:e.name,data:new Uint8Array()}:e));
 const repaired=await fresh();await repaired.locator('#importInput').setInputFiles({name:'old-layout.allopack',mimeType:'application/zip',buffer:Buffer.from(damaged)});await repaired.waitForFunction(()=>document.querySelector('#editVideo').duration>0);assert.match(await repaired.locator('#editImportSummaryBox').textContent(),/Recovered video from an older bundle layout/);await repaired.locator('#tabRecord').click();const repairedArchive=await download(repaired,repaired.locator('#saveProjectBtn'),'repaired.allopack');const repairedEntries=vsReadZip(repairedArchive);assert.deepEqual(Buffer.from(repairedEntries.find(e=>e.name.endsWith('.webm')&&!/^audio\/|music_bed/.test(e.name)).data),source);assert.match(Buffer.from(repairedEntries.find(e=>e.name==='project_readme.txt').data).toString(),/^AlloFlow/);
 const emptyVideo=vsBuildZip(entries.map(e=>e.name===video.name?{name:e.name,data:new Uint8Array()}:e));const rejected=await fresh();await rejected.locator('#importInput').setInputFiles({name:'empty-video.allopack',mimeType:'application/zip',buffer:Buffer.from(emptyVideo)});await rejected.waitForFunction(()=>document.querySelector('#importStatus').textContent.includes('No video found'));assert.equal(await rejected.locator('#takesList .take').count(),0);
 // Legacy projects without editor_state.json still open; invalid future state does not block media import.
 const legacy=vsBuildZip(entries.filter(e=>e.name!=='editor_state.json'));const legacyPage=await fresh();await legacyPage.locator('#importInput').setInputFiles({name:'legacy.allopack',mimeType:'application/zip',buffer:Buffer.from(legacy)});await legacyPage.waitForFunction(()=>document.querySelector('#editVideo').duration>0);assert.equal(await legacyPage.locator('#trimStart').inputValue(),'0');
 const badState=vsBuildZip(entries.map(e=>e.name==='editor_state.json'?{name:e.name,data:new TextEncoder().encode('{"version":999,"applyToSource":true}')}:e));await legacyPage.locator('#importInput').setInputFiles({name:'newer.allopack',mimeType:'application/zip',buffer:Buffer.from(badState)});await legacyPage.waitForFunction(()=>document.querySelectorAll('#takesList .take').length===2);assert.match(await legacyPage.locator('#importStatus').textContent(),/unsupported format/);assert.match(await legacyPage.locator('#editImportSummaryBox').textContent(),/unsupported format/);
 await reopened.locator('#tabEdit').click();await reopened.setViewportSize({width:390,height:844});assert.equal(await reopened.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await reopened.screenshot({path:out+'/editor-mobile.png'});
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({passed:true,checks:['source video bytes intact','README stays readable','music and clip bytes intact','trim and zoom roundtrip','caption and export choice roundtrip','correct saved-shelf draft','recovered imported draft','actual rendered export bundle bytes','no reapplied source trim zoom or music in rendered bundle','legacy archive-layout recovery and repaired resave','empty media rejected without substituting README text','legacy bundles open','unsupported editor state warns without blocking video','mobile fit'],errors},null,2));console.log('Portable project roundtrip checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
