'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'../..'),OUT=__dirname,source=fs.readFileSync(path.join(OUT,'baseline-runtime.js'));
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const fixture=fs.readFileSync(path.join(ROOT,'dev-tools/watercycle_signal_inspection_qa.cjs'),'utf8');
const html=Function('return '+fixture.match(/const html=(`[^]*?`);\r?\nconst mime=/)[1])();
const report={title:'Water Cycle Explore Conditions clarity audit',startedAt:new Date().toISOString(),sourceSha256:hash(source),method:'Frozen current runtime, owned ephemeral localhost server and isolated Chromium. Read-only visual and interaction audit. No learner tabs, preview port, runtime or test edits, or Git writes.',snapshots:[],actions:[],captures:[],errors:[],completed:false,successful:false,browserClosed:false,serverClosed:false};
const mime={'.js':'text/javascript','.css':'text/css'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html'});return res.end(html);}if(url.pathname==='/stem_lab/stem_tool_watercycle.js'){res.writeHead(200,{'Content-Type':'text/javascript'});return res.end(source);}const file=path.resolve(ROOT,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,bytes)=>{res.writeHead(error?404:200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(error?'Not found':bytes);});});
const base={wcMode:'explore',wcSection:'conditions',journeyView:'2d',journeyActive:false,journeyState:'idle',journeyPaused:true,wc2dPaused:true,activeStage:'infiltration',climTemp:15,climSolar:1,climWind:1,landRainIntensity:55,landSaturation:45,landPermeability:'medium',landSlope:'moderate',landCover:'grass'};
const scenarioKeys=['climSolar','climTemp','climWind','landRainIntensity','landSaturation','landPermeability','landSlope','landCover'];
async function painted(page){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function capture(page,selector,name){await page.locator(selector).screenshot({path:path.join(OUT,name),animations:'disabled',timeout:60000});report.captures.push(name);}
async function snapshot(page,label){await painted(page);return page.evaluate(({label,scenarioKeys})=>{
 const rect=el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};};
 const labs=[...document.querySelectorAll('.wc-climate-lab,.wc-land-lab')].map(lab=>{const controls=[...lab.querySelectorAll('input,select,button')].map(el=>{const s=getComputedStyle(el),wrapper=el.closest('.wc-climate-control,.wc-land-control,.wc-preset-control');return{id:el.id,tag:el.tagName,type:el.type,label:el.getAttribute('aria-label')||el.textContent.trim(),text:el.textContent.trim(),value:el.value,min:el.min,max:el.max,step:el.step,ariaValueText:el.getAttribute('aria-valuetext'),describedBy:el.getAttribute('aria-describedby'),pressed:el.getAttribute('aria-pressed'),rect:rect(el),font:s.fontSize,focus:el===document.activeElement,focusVisible:el.matches(':focus-visible'),outline:{style:s.outlineStyle,width:s.outlineWidth,color:s.outlineColor},wrapperText:wrapper?wrapper.innerText:null};});const fonts=[...lab.querySelectorAll('p,small,label,legend,h4,strong,.wc-lab-summary-title,.wc-lab-summary-note')].map(el=>({className:el.className,text:el.innerText,font:getComputedStyle(el).fontSize,rect:rect(el)}));const results=lab.querySelector('.wc-land-results,.wc-climate-response');return{className:lab.className,open:lab.open,rect:rect(lab),summary:lab.querySelector('summary').innerText,summaryRect:rect(lab.querySelector('summary')),heading:lab.querySelector('h4')?.innerText,controls,fonts,resultText:results?.innerText,resultRect:results?rect(results):null};});
 const cv=document.getElementById('wcCanvas');return{label,viewport:{width:innerWidth,height:innerHeight},scrollWidth:document.documentElement.scrollWidth,scenario:Object.fromEntries(scenarioKeys.map(key=>[key,signalData[key]])),preset:signalData.wcScenarioPreset||'custom',labs,baseline:signalData.wcScenarioBaseline||null,experimentFocus:document.getElementById('wcScenarioPresetHint')?.innerText,compareHeadline:document.querySelector('.wc-compare-copy')?.innerText,compareWorkflow:document.getElementById('wcScenarioWorkflowStatus')?.innerText,parcel:{active:signalData.journeyActive,state:cv?.dataset.journeyState,stage:cv?.dataset.activeStage,paused:cv?.dataset.journeyPaused,progress:cv?.dataset.journeyProgress},preserved:{baseline:JSON.stringify(signalData.wcScenarioBaseline),writing:JSON.stringify(signalData.wcProcessCompare),evidence:JSON.stringify(signalData.wcExperimentLog)}};
 },{label,scenarioKeys});}
async function openLand(page,open=true){const lab=page.locator('.wc-land-lab');if(await lab.evaluate(el=>el.open)!==open){await lab.locator('summary').click();await page.waitForTimeout(80);}}
async function main(){await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;try{
 browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const configs=[{width:320,theme:'light'},{width:390,theme:'light'},{width:1280,theme:'light'},{width:320,theme:'dark'},{width:320,theme:'dark',forced:true}];
 for(const config of configs){const label=(config.forced?'dark-forced-colors':config.theme)+'-'+config.width;const context=await browser.newContext({viewport:{width:config.width,height:1600},reducedMotion:'reduce',...(config.forced?{forcedColors:'active'}:{})}),page=await context.newPage();page.on('pageerror',error=>report.errors.push(label+': '+String(error)));await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(({seed,theme})=>mountSignalReview(seed,theme),{seed:base,theme:config.theme});await page.locator('.wc-climate-lab').waitFor();await page.waitForTimeout(100);report.snapshots.push(await snapshot(page,label+' default land folded'));await capture(page,'.wc-climate-lab','climate-default-'+label+'.png');await openLand(page);report.snapshots.push(await snapshot(page,label+' default both open'));await capture(page,'.wc-land-lab','land-default-'+label+'.png');
 if(config.theme==='light'&&config.width!==390){await openLand(page,false);const before=await snapshot(page,label+' before Heavy storm');await page.locator('#wcScenarioPreset').selectOption('heavy_storm');await page.waitForTimeout(100);const after=await snapshot(page,label+' Heavy storm with land folded');report.snapshots.push(after);report.actions.push({label:label+' preset Heavy storm',before:before.scenario,after:after.scenario,changed:scenarioKeys.filter(key=>before.scenario[key]!==after.scenario[key]),landRemainsFolded:!after.labs.find(l=>l.className==='wc-land-lab').open,closedLandSummary:after.labs.find(l=>l.className==='wc-land-lab').summary,baselineCaptured:after.baseline,parcelBefore:before.parcel,parcelAfter:after.parcel});await capture(page,'.wc-climate-lab','climate-heavy-storm-'+label+'.png');await capture(page,'.wc-land-lab','land-folded-heavy-storm-'+label+'.png');await openLand(page);report.snapshots.push(await snapshot(page,label+' Heavy storm expanded land'));await capture(page,'.wc-land-lab','land-heavy-storm-'+label+'.png');}
 if(config.theme==='light'&&config.width===1280){const baseline=Object.fromEntries(scenarioKeys.map(key=>[key,base[key]]));const seeded={...base,journeyActive:true,journeyState:'infiltrating',journeyLastPath:'infiltrate',wcLandLabOpen:true,wcScenarioBaseline:baseline,wcProcessCompare:{first:'condensation',second:'precipitation',notes:{'condensation|precipitation':'Saved explanation stays with the learner.'}},wcExperimentLog:[{id:'conditions-audit-evidence',note:'Saved observation stays with the learner.',inputs:{climSolar:1,climTemp:15,climWind:1}}]};await page.evaluate(seed=>mountSignalReview(seed,'light'),seeded);await page.waitForTimeout(100);await page.locator('#wcCanvas').evaluate(el=>el._wcSetJourneyProgress(0.37));const start=await snapshot(page,'paused preservation before controls');report.snapshots.push(start);
 const actions=[['land rain keyboard',async()=>{await page.locator('#wc-land-rain').focus();await page.keyboard.press('ArrowRight');}],['sunlight keyboard',async()=>{await page.locator('#wc-climate-solar').focus();await page.keyboard.press('ArrowRight');}],['high permeability',async()=>page.locator('[data-wc-input="landPermeability"]').getByRole('button',{name:'Soil permeability: High'}).click()],['climate reset',async()=>page.getByRole('button',{name:'Reset climate settings',exact:true}).click()],['land reset',async()=>page.getByRole('button',{name:'Reset land-surface scenario',exact:true}).click()]];
 for(const[name,action]of actions){await action();await page.waitForTimeout(100);const current=await snapshot(page,'paused '+name);report.snapshots.push(current);report.actions.push({label:name,scenario:current.scenario,parcel:current.parcel,parcelPreserved:JSON.stringify(current.parcel)===JSON.stringify(start.parcel),baselinePreserved:current.preserved.baseline===start.preserved.baseline,writingPreserved:current.preserved.writing===start.preserved.writing,evidencePreserved:current.preserved.evidence===start.preserved.evidence,focusedControls:current.labs.flatMap(l=>l.controls).filter(c=>c.focus),resultTexts:current.labs.map(l=>({lab:l.className,text:l.resultText}))});}
 }
 await page.evaluate(()=>ReactDOM.unmountComponentAtNode(document.getElementById('slot')));await context.close();console.log('Audited '+label);
 }
 report.completed=true;report.successful=report.errors.length===0;
 }catch(error){report.errors.push(String(error.stack||error));report.completed=false;report.successful=false;throw error;}finally{try{if(browser)await browser.close();report.browserClosed=true;}catch(error){report.errors.push('Browser cleanup: '+String(error));report.successful=false;}try{await new Promise(resolve=>server.close(resolve));report.serverClosed=true;}catch(error){report.errors.push('Server cleanup: '+String(error));report.successful=false;}report.finishedAt=new Date().toISOString();report.finalLiveSourceSha256=hash(fs.readFileSync(path.join(ROOT,'stem_lab/stem_tool_watercycle.js')));fs.writeFileSync(path.join(OUT,'baseline-results.json'),JSON.stringify(report,null,2)+'\n');}console.log(JSON.stringify({sourceSha256:report.sourceSha256,snapshots:report.snapshots.length,captures:report.captures.length,actions:report.actions.length,errors:report.errors,completed:report.completed,successful:report.successful,browserClosed:report.browserClosed,serverClosed:report.serverClosed},null,2));}
main().catch(error=>{console.error(error);process.exitCode=1;server.close();});
