import { test, expect, Page } from '@playwright/test';
import { GlHarness } from './helpers/stem_gl_harness';
const harness = new GlHarness({ toolFile: 'stem_lab/stem_tool_fisherlab.js', toolId: 'fisherLab', width: 1180, height: 980, appStyles: true, extraScripts: ['desktop/web-app/node_modules/axe-core/axe.min.js'] });
test.beforeAll(async () => { await harness.start(); });
test.afterAll(async () => { await harness.stop(); });
test.afterEach(async ({ page }) => { await harness.destroy(page); });
async function openMeasurement(page: Page) {
  await harness.mount(page, {}, undefined, { expectCanvas: false });
  const warmup = page.locator('[data-fisherlab-warmup]');
  await warmup.getByLabel('Warmup topic').selectOption('measurement');
  await warmup.getByRole('button', { name: 'Check alignment and repeat the measurement' }).click();
  const model = page.locator('[data-fisherlab-investigation="measurement"]');
  await model.locator('summary').click();
  return model;
}
test('keeps an independent set, explains controlled changes, and retains it across topics', async ({ page }) => {
  const model = await openMeasurement(page);
  const before = await page.evaluate(() => localStorage.getItem('fisherLab.state.v1'));
  await model.getByRole('button', { name: 'Keep this set for comparison' }).click();
  const comparison = model.locator('[data-measurement-comparison]');
  await expect(comparison).toHaveAttribute('data-measurement-comparison', 'none');
  await expect(comparison.getByRole('button')).toBeDisabled();
  await model.getByLabel('Align the ruler with zero').check();
  await expect(comparison).toContainText('Only alignment changed');
  await expect(model.locator('[data-measurement-set="Kept set"]')).toContainText('Mean 12.5');
  await expect(model.locator('[data-measurement-set="Current set"]')).toContainText('Mean 12.0');
  await model.getByLabel('Reading spread').selectOption('wide');
  await expect(comparison).toContainText('Both settings changed');
  await model.getByLabel('Align the ruler with zero').uncheck();
  await expect(comparison).toContainText('Only reading spread changed');
  await expect(model.locator('[data-measurement-set="Current set"]')).toContainText('Range 0.8');
  await expect(model.locator('[data-measurement-set="Kept set"]')).toContainText('Range 0.2');
  const axes = await model.locator('svg').evaluateAll(elements => elements.map(el => Array.from(el.querySelectorAll('text')).map(t => t.textContent)));
  expect(axes).toEqual([['11.4','12.0','12.6','13.2'],['11.4','12.0','12.6','13.2']]);
  await page.getByLabel('Warmup topic').selectOption('sampling');
  await page.getByLabel('Warmup topic').selectOption('measurement');
  await model.locator('summary').click();
  await expect(model.getByLabel('Reading spread')).toHaveValue('wide');
  await expect(model.locator('[data-measurement-set="Kept set"]')).toContainText('Range 0.2');
  await model.screenshot({ path: 'scratch/fisherlab-measurement-comparison-desktop.png' });
  await model.getByRole('button', { name: 'Replace kept set with current set' }).click();
  await expect(comparison).toHaveAttribute('data-measurement-comparison', 'none');
  await expect(model.locator('[data-measurement-set="Kept set"]')).toContainText('Range 0.8');
  expect(await page.evaluate(() => localStorage.getItem('fisherLab.state.v1'))).toEqual(before);
  expect(await page.evaluate(() => (window as any).__events.errors)).toEqual([]);
});
test('adds comparison to the current draft once and protects full notes and saved writing', async ({ page }) => {
  const model = await openMeasurement(page);
  const note = page.locator('[data-fisherlab-learning-note="measurement"]');
  await note.locator('summary').click();
  const evidence = note.getByLabel('Evidence & reasoning', { exact: true });
  await evidence.fill('My own observation.');
  await note.getByRole('button', { name: 'Save note', exact: true }).click();
  await model.getByRole('button', { name: 'Keep this set for comparison' }).click();
  await model.getByLabel('Align the ruler with zero').check();
  const add = model.getByRole('button', { name: 'Add comparison to measurement note' });
  await add.click();
  await expect(evidence).toBeFocused();
  const text = await evidence.inputValue();
  expect(text).toContain('My own observation.');
  expect(text).toContain('Changed: alignment');
  expect(text).toContain('not catch measurements');
  await add.click();
  await expect(evidence).toHaveValue(text);
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fisherLab.learningNotes.v1')!).measurement.evidence)).toBe('My own observation.');
  await evidence.fill('x'.repeat(590));
  await add.click();
  await expect(model.getByRole('status')).toContainText('not enough space');
  await expect(evidence).toHaveValue('x'.repeat(590));
  await model.getByLabel('Reading spread').selectOption('wide');
  await expect(model.getByRole('status')).toBeEmpty();
  await evidence.fill('My revised observation.');
  await add.click();
  await note.getByRole('button', { name: 'Save note', exact: true }).click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fisherLab.learningNotes.v1')!).measurement.evidence)).toContain('Changed: both');
});
test('comparison works with keyboard and large text at phone width', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 850 });
  const model = await openMeasurement(page);
  await page.evaluate(() => { document.getElementById('wrap')!.style.width = '360px'; });
  await page.getByRole('button', { name: 'Large text', exact: true }).click();
  const keep = model.getByRole('button', { name: 'Keep this set for comparison' });
  await keep.focus();
  await page.keyboard.press('Enter');
  await model.getByLabel('Align the ruler with zero').focus();
  await page.keyboard.press('Space');
  await expect(model.locator('[data-measurement-comparison]')).toContainText('Only alignment changed');
  await model.getByLabel('Reading spread').focus();
  await page.keyboard.press('End');
  await page.keyboard.press('Enter');
  await expect(model.getByLabel('Reading spread')).toHaveValue('wide');
  const metrics = await page.locator('[data-fisherlab-investigation], .fl-fisherlab-root').evaluateAll(els => els.map(el => ({ client: el.clientWidth, scroll: el.scrollWidth, right: el.getBoundingClientRect().right })));
  for (const m of metrics) { expect(m.scroll).toBeLessThanOrEqual(m.client + 1); expect(m.right).toBeLessThanOrEqual(360); }
  const violations = await page.evaluate(async () => (await (window as any).axe.run('[data-fisherlab-investigation="measurement"]', { runOnly: { type: 'rule', values: ['color-contrast','button-name','label','aria-valid-attr-value','aria-allowed-attr'] } })).violations.map((v: any) => ({ id: v.id, nodes: v.nodes.map((n: any) => n.target) })));
  expect(violations).toEqual([]);
  await model.screenshot({ path: 'scratch/fisherlab-measurement-comparison-mobile.png' });
  await model.getByRole('button', { name: 'Add comparison to measurement note' }).click();
  await expect(page.getByLabel('Evidence & reasoning', { exact: true })).toBeFocused();
  expect(await page.evaluate(() => (window as any).__events.errors)).toEqual([]);
});
