import {test,expect} from '@playwright/test';
import {GlHarness} from './helpers/stem_gl_harness';
const desktop=new GlHarness({toolFile:'stem_lab/stem_tool_spacecolony.js',toolId:'spaceColony',width:1100,height:900,appStyles:true});
const phone=new GlHarness({toolFile:'stem_lab/stem_tool_spacecolony.js',toolId:'spaceColony',width:360,height:820,appStyles:true});
test.beforeAll(async()=>{await desktop.start();await phone.start();});test.afterAll(async()=>{await desktop.stop();await phone.stop();});
test.afterEach(async({page})=>{await desktop.destroy(page);});test.describe.configure({timeout:300000});test.use({video:'off',trace:'off'});
test('installed engineering and restoration follow a real campaign turn without remounting the scene',async({page},info)=>{
 await page.setViewportSize({width:1100,height:900});await desktop.mount(page,{},undefined,{expectCanvas:false});
 const canvas=page.locator('[data-colony-3d-canvas]'),view=page.locator('[data-colony-3d]');
 await canvas.scrollIntoViewIfNeeded();await expect(canvas).toHaveAttribute('data-colony-turn','0',{timeout:60000});
 await page.locator('[data-spacecolony-launch]').click();
 await page.evaluate(()=>{(window as any).__ctx.setToolData((p:any)=>({...p,colonyBuildings:['solar','waterReclaim','greenhouse','atmo','fusion','shield','hydroponics'],buildingEff:{solar:0},colonyTerraform:12,turnPhase:'dusk',fateRoll:{raw:45,modified:45,bonus:0,result:{icon:'Sun',label:'Calm',color:'#22c55e',type:'calm'}},fateAnimating:false}));});
 await canvas.scrollIntoViewIfNeeded();await expect(canvas).toHaveAttribute('data-colony-visible-tech',/atmo.*fusion.*greenhouse.*hydroponics.*shield.*solar.*waterReclaim/,{timeout:60000});
 await canvas.evaluate(el=>(window as any).__firstColonyCanvas=el);
 await view.getByRole('button',{name:'Solar arrays',exact:true}).click();await expect(view.locator('[data-colony-tech-inspector]')).toContainText('Installed · offline');
 expect((await canvas.getAttribute('data-colony-operating-tech'))!.split(',')).not.toContain('solar');
 await view.getByRole('button',{name:'Fusion plant',exact:true}).click();await expect(view.locator('[data-colony-tech-inspector]')).toContainText('speculative colony plant');
 await view.getByRole('button',{name:'Engineering close-up',exact:true}).click();await expect(canvas).toHaveAttribute('data-colony-camera','works');
 await view.getByRole('button',{name:'Pause visual motion',exact:true}).click();await expect(canvas).toHaveAttribute('data-colony-motion','still');
 const before=await page.evaluate(()=>({turn:(window as any).__toolData.colonyTurn,res:(window as any).__toolData.colonyRes}));
 await view.getByRole('button',{name:'Rotate colony view left',exact:true}).press('Enter');
 expect(await page.evaluate(()=>({turn:(window as any).__toolData.colonyTurn,res:(window as any).__toolData.colonyRes}))).toEqual(before);
 await view.getByRole('button',{name:'Go to turn controls',exact:true}).click();await expect(page.locator('[data-colony-turn-controls=dusk]')).toBeFocused();
 await page.getByRole('button',{name:/Continue to Dawn/}).click();
 await expect.poll(()=>page.evaluate(()=>(window as any).__toolData.colonyTurn)).toBe(2);
 await canvas.scrollIntoViewIfNeeded();await expect(canvas).toHaveAttribute('data-colony-turn','2');
 expect(Number(await canvas.getAttribute('data-colony-terraform'))).toBeGreaterThan(12);
 await expect(view.locator('[data-colony-turn-change]')).toContainText('Sol 1 → 2');
 expect(await canvas.evaluate(el=>el===(window as any).__firstColonyCanvas)).toBe(true);
 await view.getByRole('button',{name:'Overview',exact:true}).click();await canvas.scrollIntoViewIfNeeded();
 await canvas.screenshot({path:info.outputPath('terraforming-colony-desktop.png'),timeout:60000});
 await view.getByRole('button',{name:'Resume visual motion',exact:true}).click();await expect(canvas).toHaveAttribute('data-colony-motion','animated');
 await page.getByRole('textbox',{name:'Habitat design reasoning'}).scrollIntoViewIfNeeded();await page.waitForTimeout(300);
 const pausedFrames=Number(await canvas.getAttribute('data-colony-frames'));await page.waitForTimeout(1200);expect(Number(await canvas.getAttribute('data-colony-frames'))-pausedFrames).toBeLessThanOrEqual(1);
 expect(await page.evaluate(()=>(window as any).__events.errors)).toEqual([]);
 await desktop.destroy(page);expect(await page.evaluate(()=>(window as any).__firstColonyCanvas.dataset.colonyDisposed)).toBe('true');
});
test('phone camera works with reduced motion and offers a usable fallback after context loss',async({page},info)=>{
 await page.setViewportSize({width:360,height:820});await page.emulateMedia({reducedMotion:'reduce'});
 await phone.mount(page,{colony:{name:'Habitat',planet:'Centauri Haven (fictional)'},colonyPhase:'playing',colonyTurn:4,turnPhase:'day',colonyTerraform:60,colonyBuildings:['solar','waterReclaim','greenhouse','atmo','fusion','shield']},undefined,{expectCanvas:false});
 const view=page.locator('[data-colony-3d]'),canvas=view.locator('canvas');await canvas.scrollIntoViewIfNeeded();await expect(canvas).toHaveAttribute('data-colony-motion','still',{timeout:60000});
 await view.getByRole('button',{name:'Habitat close-up',exact:true}).click();await expect(canvas).toHaveAttribute('data-colony-camera','habitat');
 await view.getByRole('button',{name:'Shielding station',exact:true}).click();await expect(view.locator('[data-colony-tech-inspector]')).toContainText('fictional field');
 const box=await view.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(360);
 for(const b of await view.getByRole('button').all())if(await b.isVisible())expect((await b.boundingBox())!.height).toBeGreaterThanOrEqual(44);
 await canvas.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('terraforming-colony-phone.png'),timeout:60000});
 await canvas.evaluate((c:HTMLCanvasElement)=>{const gl=c.getContext('webgl2')||c.getContext('webgl');gl!.getExtension('WEBGL_lose_context')!.loseContext();});
 await expect(view.getByText(/3D is unavailable/)).toBeVisible();await expect(canvas).toBeHidden();
 await page.getByText('2D system diagram',{exact:true}).click();await expect(page.getByRole('img',{name:/Habitat systems:/})).toBeVisible();
 await page.getByRole('button',{name:/Food loop ·/}).click();await expect(page.locator('[data-habitat-projection]')).toBeVisible();
 expect(await page.evaluate(()=>(window as any).__toolData.colonyTurn)).toBe(4);
 expect((await page.evaluate(()=>(window as any).__events.errors)).filter((e:string)=>!/CONTEXT_LOST_WEBGL|context lost/i.test(e))).toEqual([]);
});
