import {test,expect} from '@playwright/test';import {GlHarness} from './helpers/stem_gl_harness';
const wide=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:1100,height:1000,appStyles:true}),phone=new GlHarness({toolFile:'stem_lab/stem_tool_solarsystem.js',toolId:'solarSystem',width:320,height:850,appStyles:true});test.beforeAll(async()=>{await wide.start();await phone.start();});test.afterAll(async()=>{await wide.stop();await phone.stop();});test.afterEach(async({page})=>wide.destroy(page));test.describe.configure({timeout:150000});test.use({video:'off',trace:'off'});
const prediction='I predict a larger gap with a larger angle.',trials={aligned:{separation:0,days:258.9},offset:{separation:.789,days:258.9}},report={source:'mission',missionId:'earth-mars',missionStartedAt:100,observation:'Original report',expedition:{trials,reflection:'Original reasoning'}};
const mission={active:false,startedAt:100,completedAt:200,prediction:'miss',trials,followUp:{offset:60,prediction,launched:{offset:60,prediction,timestamp:300}}};
const result=(launch:number)=>({source:'experiment',transferComparisonId:'result-'+launch,observation:'Saved comparison',reasoning:'My saved explanation for launch '+launch,transferComparison:{route:'earth-mars',missionStartedAt:100,offset:60,days:258.9,referenceGap:0,testGap:1.524,timestamp:launch+10,followUp:{launchedAt:launch,offset:60,prediction}}});
const base={tutorialDismissed:true,orreryMode:true,orr_tab:5,orr_paused:true,solarMissionFocus:'mars'};


for(const compact of [false,true])test('preview angles without changing evidence '+(compact?'phone':'desktop'),async({page},info)=>{
 const harness=compact?phone:wide;await page.setViewportSize(compact?{width:320,height:850}:{width:1100,height:1000});await page.emulateMedia({reducedMotion:'reduce'});const old=result(250);old.transferComparison.offset=-30;old.transferComparison.testGap=.789;old.transferComparison.followUp.offset=-30;const entries=[report,old,result(300)],m={...mission,active:true};
 await harness.mount(page,{solarSystem:{...base,solarMissionDashboardOpen:false,marsMission:m,journalEntries:entries}},undefined,{expectCanvas:false});if(!compact)await page.evaluate(()=>{(window as any).__ctx.isDark=true;(window as any).__rerender();});await page.locator('[data-mars-follow-up] > summary').click();await page.locator('[data-mars-angle-explorer] > summary').click();const explorer=page.getByRole('region',{name:'Arrival angle explorer',exact:true}),angle=explorer.getByRole('slider',{name:'Preview arrival angle',exact:true}),reading=explorer.locator('[data-preview-gap-reading]');await expect(angle).toHaveValue('60');await expect(reading).toContainText('1.932');await expect(explorer.getByRole('button',{name:'Reset to saved angle',exact:true})).toBeDisabled();
 await explorer.getByRole('button',{name:'Mirror preview angle',exact:true}).click();await expect(angle).toHaveValue('-60');await expect(reading).toContainText('1.932');const originalY=await explorer.locator('[data-preview-destination]').getAttribute('cy');expect(Number(originalY)).toBeGreaterThan(108);
 const presets=explorer.getByRole('group',{name:'Preview angle presets',exact:true});await presets.getByRole('button',{name:'0°',exact:true}).click();await expect(reading).toContainText('0.000 orbit radii');await expect(explorer.getByRole('button',{name:'Mirror preview angle',exact:true})).toBeDisabled();await angle.focus();await angle.press('ArrowRight');await expect(angle).toHaveValue('1');await expect(angle).toBeFocused();await angle.press('End');await angle.press('ArrowLeft');await expect(angle).toHaveValue('59');await expect(reading).toContainText('+59°');await explorer.getByRole('button',{name:'Reset to saved angle',exact:true}).click();await expect(angle).toHaveValue('60');
 await presets.getByRole('button',{name:'-30°',exact:true}).click();await expect(reading).toContainText('1.000 ×');await expect(presets.getByRole('button',{name:'-30°',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('figure',{name:'Arrival geometry comparison',exact:true})).toContainText('Larger recorded gap');const bounds=await explorer.evaluate(el=>({right:el.getBoundingClientRect().right,overflow:el.scrollWidth>el.clientWidth+1}));expect(bounds.right).toBeLessThanOrEqual(compact?320:1100);expect(bounds.overflow).toBe(false);await page.locator('[data-mars-angle-explorer]').screenshot({path:info.outputPath(compact?'explorer-phone.png':'explorer-desktop.png')});
 await page.getByLabel('Review an investigation',{exact:true}).selectOption('result-250');await expect(angle).toHaveValue('-30');await expect(explorer.getByRole('button',{name:'Reset to saved angle',exact:true})).toBeDisabled();await presets.getByRole('button',{name:'+30°',exact:true}).click();await expect(reading).toContainText('1.000 ×');await expect(page.getByRole('figure',{name:'Arrival geometry comparison',exact:true})).toContainText('Same gap at the displayed precision');const data=await page.evaluate(()=>(window as any).__toolData.solarSystem);expect(data.marsMission).toEqual(m);expect(data.journalEntries).toEqual(entries);expect(data.transferDebriefs).toBeUndefined();expect(await page.evaluate(()=>(window as any).__events.errors)).toEqual([]);
});
