import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { GlHarness } from './helpers/stem_gl_harness';
const harness = new GlHarness({ toolFile: 'stem_lab/stem_tool_cell.js', toolId: 'cell', width: 1100, height: 900, appStyles: true });
test.beforeAll(async()=>harness.start());test.afterAll(async()=>harness.stop());
test('portable notebook keeps recorded evidence and safely resumes on a phone',async({page})=>{
  test.setTimeout(180000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await harness.mount(page,{cell:{mode:'osmoHunt',_cellPicked:true,_cellCategory:'interactive'}},undefined,{expectCanvas:false});
  const lab=page.locator('[data-cell-osmosis-lab]');await expect(lab).toBeVisible();
  await lab.getByRole('button',{name:'Water leaves',exact:true}).click();
  await lab.getByLabel('Osmosis prediction',{exact:true}).fill('Opening water channels will increase outward flow.');
  await lab.getByLabel('Osmosis observation',{exact:true}).fill('At 50%, net water moves out of the cell.');
  await lab.getByRole('button',{name:'Record trial',exact:true}).click();
  await lab.getByRole('button',{name:'Blocked membrane',exact:true}).click();
  await lab.getByLabel('Osmosis observation',{exact:true}).fill('At 0%, flow is blocked, but the solution remains hypertonic.');
  await lab.getByRole('button',{name:'Record trial',exact:true}).click();
  await lab.getByLabel('Osmosis explanation',{exact:true}).fill('Permeability controls flow; it does not change tonicity.');
  const downloadPromise=page.waitForEvent('download');
  await lab.getByRole('button',{name:'Download notebook (.json)',exact:true}).click();
  const download=await downloadPromise;const downloadedPath=await download.path();expect(downloadedPath).toBeTruthy();
  const packet=JSON.parse(await readFile(downloadedPath!,'utf8'));
  expect(packet.log).toHaveLength(2);expect(packet.log[0].perm).toBe(50);expect(packet.log[1].perm).toBe(0);
  expect(packet.log[0].observation).toContain('At 50%');expect(packet.log[1].observation).toContain('At 0%');
  const reportPromise=page.waitForEvent('download');await lab.getByRole('button',{name:'Download report (.txt)',exact:true}).click();
  const report=await reportPromise;expect(await readFile((await report.path())!,'utf8')).toContain('Permeability controls flow; it does not change tonicity.');
  await lab.getByRole('button',{name:'Reset controls',exact:true}).click();
  await lab.getByLabel('Osmosis explanation',{exact:true}).fill('A different draft');
  await lab.getByText('Import a notebook',{exact:true}).click();
  await lab.locator('#cell-osmosis-import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{no')});
  await expect(lab.getByRole('status')).toContainText('Import failed');await expect(lab.getByLabel('Osmosis explanation',{exact:true})).toHaveValue('A different draft');
  await lab.locator('#cell-osmosis-import').setInputFiles({name:'resume.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(packet))});
  await expect(lab.getByRole('status')).toContainText('2 trials restored');await expect(lab.locator('#oh-perm')).toHaveValue('0');
  await expect(lab.getByLabel('Osmosis explanation',{exact:true})).toHaveValue(packet.explanation);
  await expect(lab.getByRole('table')).toContainText(packet.log[0].observation);
  await page.addScriptTag({path:'axe-core/4.12.1/axe.min.js'});
  const violations=await page.evaluate(async()=>{const result=await (window as any).axe.run(document.querySelector('[data-cell-osmosis-lab]'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return result.violations.map((v:any)=>({id:v.id,nodes:v.nodes.map((n:any)=>n.failureSummary)}));});
  expect(violations).toEqual([]);
  await lab.screenshot({path:'reports/cell-notebook-enhancement/notebook-desktop.png'});
  await page.setViewportSize({width:390,height:844});await page.addStyleTag({content:'#wrap{width:100%;}'});
  expect(await lab.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
  await lab.locator('#oh-perm').focus();await page.keyboard.press('End');await expect(lab.locator('#oh-perm')).toHaveValue('100');
  await lab.screenshot({path:'reports/cell-notebook-enhancement/notebook-phone.png'});
  expect(errors).toEqual([]);
});