import { test, expect } from '@playwright/test';
import { GlHarness } from './helpers/stem_gl_harness';
test.use({ hasTouch: true, viewport: { width: 390, height: 844 } });
const harness = new GlHarness({ toolFile: 'stem_lab/stem_tool_coasterlab.js', toolId: 'coasterLab', width: 390, height: 844,
  probes: "document.head.insertAdjacentHTML('beforeend', '<style>#wrap{width:100%}.clab-root{width:100%;height:100vh!important}</style>');" });
test.beforeAll(async () => { await harness.start(); });
test.afterAll(async () => { await harness.stop(); });
test.afterEach(async ({ page }) => { await harness.destroy(page); });
test('touch users can inspect, cancel, frame, and add a piece without stale insertions', async ({ page }, testInfo) => {
  test.setTimeout(240000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => { localStorage.setItem('coaster_lab_onboarding_v1', 'complete'); });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const ready = "document.querySelector('[aria-label=\"Coaster Lab 3-D designer\"]')._lab";
  await harness.mount(page, {}, ready);
  const state = () => page.evaluate(() => (document.querySelector('[aria-label="Coaster Lab 3-D designer"]') as any)._lab.elementPresentation());
  const design = () => page.evaluate(() => (document.querySelector('[aria-label="Coaster Lab 3-D designer"]') as any)._lab.exportDesign());
  const hill = page.locator('.clab-element-btn[data-element="hill"]');
  const loop = page.locator('.clab-element-btn[data-element="loop"]');
  const panel = page.locator('#clab-piecePreview');
  await expect(page.locator('#clab-previewFirst')).toBeChecked();
  await page.locator('.clab-edit-track').first().tap();
  const original = await design(), before = (await state()).nodes;
  await hill.tap();
  await expect(panel).toBeVisible();
  await expect(panel).toBeFocused();
  const cardBounds = (await loop.boundingBox())!, panelBounds = (await panel.boundingBox())!;
  expect(cardBounds.y + cardBounds.height).toBeLessThanOrEqual(panelBounds.y);
  await expect(hill).toHaveAttribute('aria-expanded', 'true');
  await expect(page.locator('#clab-hud')).toBeHidden();
  await expect(page.locator('#clab-viewTools')).toBeHidden();
  await expect.poll(state).toMatchObject({ pinnedKind: 'hill', previewVisible: true, previewNodes: 3, nodes: before });
  await page.locator('#clab-btnFramePreview').tap();
  await expect.poll(state).toMatchObject({ pinnedKind: 'hill', previewVisible: true });
  expect(await design()).toBe(original);
  await expect.poll(() => page.evaluate(() => (document.querySelector('[aria-label="Coaster Lab 3-D designer"]') as any)._lab.cameraFraming())).toMatchObject({ mode: 'orbit', autoFit: false });
  await page.screenshot({ path: testInfo.outputPath('touch-hill-preview.png') });
  await page.locator('#clab-btnCancelPreview').focus(); await page.keyboard.press('Escape');
  await expect(panel).toBeHidden(); await expect(hill).toBeFocused();
  await expect(hill).toHaveAttribute('aria-expanded', 'false');
  await expect(page.locator('#clab-hud')).toBeVisible();
  await expect(page.locator('#clab-viewTools')).toBeVisible();
  expect(await design()).toBe(original);
  await loop.tap();
  await expect.poll(state).toMatchObject({ pinnedKind: 'loop', previewNodes: 10 });
  await hill.tap();
  await expect.poll(state).toMatchObject({ pinnedKind: 'hill', previewNodes: 3 });
  await page.locator('#clab-btnNextPt').tap();
  await expect(panel).toBeHidden();
  await expect.poll(state).toMatchObject({ pinnedKind: null, previewVisible: false, nodes: before });
  await hill.tap();
  await page.locator('#clab-btnAddPreview').tap();
  await expect(panel).toBeHidden();
  await expect.poll(state).toMatchObject({ nodes: before + 3, pinnedKind: null, previewVisible: false });
  await page.locator('#clab-btnUndo').tap();
  await expect.poll(state).toMatchObject({ nodes: before });
  await page.locator('.clab-edit-track').first().tap();
  await hill.tap();
  await page.evaluate(() => {
    const lab = (document.querySelector('[aria-label="Coaster Lab 3-D designer"]') as any)._lab;
    lab.importDesign(lab.exportDesign());
  });
  await expect(panel).toBeHidden();
  await expect.poll(state).toMatchObject({ pinnedKind: null, previewVisible: false });
  await page.locator('#clab-previewFirst').uncheck();
  await harness.destroy(page); await harness.mount(page, {}, ready);
  await expect(page.locator('#clab-previewFirst')).not.toBeChecked();
  await page.locator('.clab-edit-track').first().tap(); await hill.tap();
  await expect.poll(state).toMatchObject({ nodes: before + 3, pinnedKind: null });
  expect(errors).toEqual([]);
});
