import { test, expect } from '@playwright/test';
import { GlHarness } from './helpers/stem_gl_harness';
test.use({ viewport: { width: 1280, height: 900 } });
const harness = new GlHarness({ toolFile: 'stem_lab/stem_tool_coasterlab.js', toolId: 'coasterLab', width: 1200, height: 850,
  probes: "document.head.insertAdjacentHTML('beforeend', '<style>#wrap{width:100%;height:100vh}.clab-root{width:100%;height:100vh!important}</style>');" });
const ready = "document.querySelector('[aria-label=\"Coaster Lab 3-D designer\"]')._lab";
test.beforeAll(async () => { await harness.start(); });
test.afterAll(async () => { await harness.stop(); });
test.afterEach(async ({ page }) => { await harness.destroy(page); });
test('learners revise predictions, retain writing, and take an experiment to Build', async ({ page }, testInfo) => {
  test.setTimeout(240000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('coaster_lab_onboarding_v1', 'complete'));
  await harness.mount(page, {}, ready);
  const design = () => page.evaluate(() => (document.querySelector('[aria-label="Coaster Lab 3-D designer"]') as any)._lab.exportDesign());
  const original = await design();
  await page.locator('#clab-btnPhysicsPit').click();
  await expect(page.locator('#clab-pitTitle')).toBeFocused();
  const headingBounds = (await page.locator('#clab-physicsPit .clab-pit-heading').boundingBox())!;
  const tabsBounds = (await page.locator('#clab-tabs').boundingBox())!;
  expect(headingBounds.y).toBeGreaterThanOrEqual(tabsBounds.y + tabsBounds.height);
  await expect(page.locator('#clab-pitCheck')).toBeDisabled();
  await page.screenshot({ path: testInfo.outputPath('physics-pit-desktop.png') });
  await page.locator('.clab-pit-figure').screenshot({ path: testInfo.outputPath('energy-diagram.png') });
  await page.getByText('Need a clue?', { exact: true }).click();
  await expect(page.getByText('Compare the energy stored by height at the top and bottom of the hill.')).toBeVisible();
  await page.getByRole('radio', { name: 'It stays at the same speed', exact: true }).check();
  const reason = 'I thought energy staying constant meant speed stayed constant. <img src=x onerror=alert(1)>';
  await page.locator('#clab-pitReason').fill(reason);
  await page.locator('#clab-pitCheck').click();
  await expect(page.locator('#clab-pitFeedback')).toBeFocused();
  await expect(page.locator('#clab-pitFeedback')).toContainText('Total mechanical energy stays constant');
  await expect(page.locator('#clab-pitProgress')).toHaveText('1 of 3 ideas explored');
  await page.getByRole('radio', { name: 'It speeds up', exact: true }).check();
  await expect(page.locator('#clab-pitFeedback')).toBeHidden();
  await page.locator('#clab-pitCheck').click();
  await expect(page.locator('#clab-pitFeedback')).toContainText('That fits the model.');
  await expect(page.locator('#clab-pitProgress')).toHaveText('1 of 3 ideas explored');
  await page.locator('[data-pit-next]').click();
  await page.locator('.clab-pit-figure').screenshot({ path: testInfo.outputPath('turns-diagram.png') });
  await page.getByRole('radio', { name: 'The tighter turn', exact: true }).check();
  await page.locator('#clab-pitCheck').click();
  await page.locator('[data-pit-next]').click();
  await page.locator('.clab-pit-figure').screenshot({ path: testInfo.outputPath('airtime-diagram.png') });
  await page.getByRole('radio', { name: 'Gravity has switched off', exact: true }).check();
  await page.locator('#clab-pitCheck').click();
  await expect(page.locator('#clab-pitFeedback')).toContainText('Gravity still acts');
  await expect(page.locator('#clab-pitProgress')).toContainText('3 of 3 ideas explored');
  await page.locator('[data-pit-try]').click();
  await expect(page.locator('#clab-pitExperiment')).toBeVisible();
  await expect(page.locator('#clab-pitExperiment h3')).toBeFocused();
  await page.screenshot({ path: testInfo.outputPath('experiment-plan-desktop.png') });
  await expect(page.locator('#clab-pitExperiment')).toContainText('Keep the ride settings fixed');
  expect(await design()).toBe(original);
  await harness.destroy(page); await harness.mount(page, {}, ready);
  await expect(page.locator('#clab-pitExperiment')).toBeVisible();
  await page.locator('[data-pit-return]').click();
  await expect(page.locator('#clab-pitFeedback')).toContainText('Gravity still acts');
  await page.locator('[data-pit-stop="energy"]').click();
  await expect(page.locator('#clab-pitReason')).toHaveValue(reason);
  await expect(page.locator('#clab-physicsPit img')).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.clab-pit-figure').screenshot({ path: testInfo.outputPath('energy-diagram-phone.png') });
  await page.screenshot({ path: testInfo.outputPath('physics-illustration-phone.png') });
  await page.locator('#clab-pitCheck').click();
  await page.screenshot({ path: testInfo.outputPath('physics-pit-phone.png') });
  const overflow = await page.locator('#clab-physicsPit').evaluate(el => el.scrollWidth > el.clientWidth);
  expect(overflow).toBe(false);
  await page.locator('[data-pit-try]').click();
  await page.locator('[data-pit-dismiss]').click();
  await expect(page.locator('#clab-pitExperiment')).toBeHidden();
  await expect(page.locator('#clab-btnPhysicsPit')).toBeFocused();
  expect(errors).toEqual([]);
});
test('unavailable storage keeps the activity usable and reports the limitation', async ({ page }) => {
  test.setTimeout(180000);
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem;
    Storage.prototype.setItem = function(key, value) { if(key === 'coaster_lab_physics_pit_v1') throw new Error('storage unavailable'); return original.call(this, key, value); };
  });
  await harness.mount(page, {}, ready);
  await page.locator('#clab-tab-missions-btn').click();
  await page.getByRole('radio', { name: 'It speeds up', exact: true }).check();
  await page.locator('#clab-pitCheck').click();
  await expect(page.locator('[data-pit-save]')).toContainText('Device storage is unavailable');
  await expect(page.locator('#clab-pitFeedback')).toContainText('That fits the model.');
});
