'use strict';
const q=(skillId,prompt,correct,distractors,rationale,difficulty,cognitiveLevel)=>({skillId,prompt,correct,distractors,rationale,difficulty,cognitiveLevel});
const s='implants-assistive-technology';
module.exports=[
q(s,'At a cochlear-implant follow-up, one electrode shows an impedance value far outside its prior stable range. What should the audiologist do first?','Repeat the measure, check equipment and connection, review symptoms and trends, and follow device guidance.',[
['Increase stimulation on that electrode before confirming the abnormal measurement.','Changing stimulation before verifying the finding could create discomfort and obscures the cause.'],
['Conclude that the entire implant has failed from one unconfirmed value.','A single outlying impedance requires confirmation and context rather than a global failure conclusion.'],
['Ignore the change because electrode impedances provide no information about device integrity.','Impedance patterns are useful integrity and programming checks when interpreted appropriately.']],
'Electrode impedance can change because of connection, measurement, tissue-interface, or device factors. Repetition, comparison with longitudinal patterns, symptom review, manufacturer guidance, and implant-team coordination distinguish artifact from an actionable channel or device concern.','advanced','analysis'),
q(s,'A cochlear-implant candidate reports limited everyday benefit despite well-verified hearing aids. Which evidence most directly supports the audiologic candidacy evaluation?','Standardized aided speech-perception results with verified hearing aids, integrated with goals and team findings.',[
['Unaided tympanometry used as the sole measure of speech understanding.','Middle-ear admittance does not quantify aided speech perception.'],
['Unaided speech testing alone because verified hearing-aid performance is not required for candidacy interpretation.','Unaided performance does not show the benefit available from appropriately fitted amplification and cannot replace aided candidacy measures.'],
['One unaided pure-tone threshold used without verifying current hearing-aid function.','Candidacy requires aided performance and comprehensive evidence, not one unaided threshold.']],
'Aided speech testing characterizes performance with appropriately fit amplification under defined conditions and is central to many implant candidacy protocols. Results must be combined with audiometric, medical, communication, support, access, and informed-preference evidence.','advanced','analysis'),
q(s,'A cochlear-implant recipient uses a hearing aid on the opposite ear. What is the key bimodal-management priority?','Coordinate audibility, loudness, timing, device features, and functional goals across the implant and hearing-aid systems.',[
['Program each side independently and avoid checking how they function together.','Bimodal benefit depends partly on combined perception and requires coordinated validation.'],
['Turn off the hearing aid whenever residual hearing provides useful low-frequency information.','Useful acoustic information may complement electric input and should be evaluated rather than discarded reflexively.'],
['Match nominal compression settings across the two devices and infer that combined loudness and timing are coordinated.','Matching nominal settings across different electric and acoustic systems does not verify bilateral audibility, loudness, timing, or benefit.']],
'Bimodal listening combines electric and acoustic information that may differ in bandwidth, timing, loudness, and processing. Separate verification plus bilateral sound-quality, speech, localization, and real-world validation supports individualized coordination.','advanced','analysis'),
q(s,'A preschooler frequently removes a hearing device during active play. Which plan best addresses consistent access?','Assess fit, comfort, and retention; teach a safe caregiver routine; and monitor use in daily settings.',[
['Increase output so the child keeps the device in place because it sounds louder.','More output does not solve physical retention and may reduce comfort or safety.'],
['Secure the device with an improvised cord that creates a strangulation risk.','Retention accessories must be developmentally safe and used according to applicable guidance.'],
['Count device ownership as proof of full-time auditory access without observing use.','A device cannot provide access when it is not worn and functioning.']],
'Consistent pediatric device access depends on fit, comfort, sensory tolerance, retention, caregiver skill, routines, safety, and rapid troubleshooting. Collaborative observation and data logging where appropriate help distinguish physical, acoustic, and behavioral barriers.','application','analysis'),
q(s,'Before recommending surgical bone-conduction technology for a young child, what can a softband trial contribute?','It can provide a nonsurgical estimate of aided access, comfort, retention, and functional benefit while candidacy is evaluated.',[
['It reproduces osseointegrated transmission exactly and removes the need for medical evaluation.','Softband coupling differs from implanted transmission and does not replace medical candidacy assessment.'],
['It makes aided sound-field thresholds sufficient by themselves to establish surgical candidacy.','Aided thresholds can inform access, but surgical candidacy also requires medical, audiologic, developmental, and family-centered evidence.'],
['It diagnoses the cause of conductive loss from one aided threshold.','Aided performance does not by itself establish etiology.']],
'A softband or test-band trial offers reversible experience with bone-conducted input and can support aided testing and family observation. Coupling limitations, anatomy, age, medical factors, alternatives, expectations, and long-term goals still require team evaluation.','application','analysis'),
q(s,'A client with hearing loss may miss a smoke alarm while asleep. Which assistive solution most directly addresses this task?','A verified visual, tactile, or bed-shaker alert appropriate for the sleeping environment.',[
['A speech-in-noise program that activates only during restaurant conversations.','A restaurant microphone program does not provide a sleeping emergency alert.'],
['A quiet tinnitus masker placed where the client cannot detect an alarm.','Masking sound is not a substitute for an accessible safety signal.'],
['A hearing aid set to higher gain at bedtime so its microphone makes the existing acoustic alarm accessible.','A hearing aid may not be worn, retained, powered, or sufficient during sleep and is not a verified substitute for an accessible alerting system.']],
'Assistive technology should be selected from the functional task: reliable detection of an emergency signal during sleep. Signal modality, intensity, placement, power backup, compatibility, household procedures, and actual user testing all matter for safety.','application','application'),
q(s,'A classroom remote-microphone receiver connects to a student’s hearing devices, but benefit has not been measured. What should verification include?','Electroacoustic transparency or output checks plus functional listening with the transmitter at realistic distance and noise conditions.',[
['Confirm the receiver icon and transmitter indicator visually, then infer benefit without measuring the signal delivered through the student’s devices.','Appearance does not establish routing, output, or functional benefit.'],
['Use unaided pure-tone thresholds to estimate remote-microphone signal quality, without checking wireless routing, device mixing, or aided output.','Unaided thresholds do not verify remote-microphone transmission or device mixing.'],
['Increase transmitter gain until classroom listeners notice acoustic feedback, then treat that observation as evidence of an effective signal-to-noise ratio.','Provoking feedback is not a safe or valid verification endpoint.']],
'A connected icon does not prove that remote-microphone input reaches the listener at an appropriate level. Device-specific electroacoustic comparison, listening checks, speech or functional measures, orientation, and teacher-student practice verify the complete signal path.','application','analysis'),
q(s,'A cochlear-implant user reports intermittent sound after changing cables and batteries. What is the most appropriate next troubleshooting step?','Use the manufacturer’s systematic component check, document when failure occurs, and contact the implant program if the problem persists or internal failure is suspected.',[
['Open or manipulate the internal receiver in the clinic after the external swaps, rather than using the implant team’s approved integrity pathway.','Internal-device evaluation and surgery require the authorized implant medical team.'],
['Raise stimulation levels across the map whenever a dropout occurs, without determining whether the processor, coil, cable, power source, or internal device is involved.','Dropouts suggest a hardware or connection problem rather than a need for higher stimulation.'],
['Replace all available external components at once and infer the failed component if the intermittent sound stops.','Changing every component simultaneously may restore sound but cannot isolate the fault or document a reproducible failure pattern.']],
'Systematic troubleshooting isolates processor, coil, cable, microphone, power, connection, and environmental contributors using approved procedures and known-good parts. Persistent interruption, pain, site concerns, or suspected internal failure requires prompt implant-team coordination.','advanced','analysis'),
];
