const fs=require('node:fs'),assert=require('node:assert/strict');const {chromium}=require('playwright');const out='reports/video-studio-draft-settings-2026-09-08';
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1360,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.request().url().startsWith('http://studio.test/')?r.fulfill({contentType:'text/html',body:fs.readFileSync('video_studio/video_studio.html','utf8')}):r.abort());await page.goto('http://studio.test/');
 const buffer=fs.readFileSync('reports/video-studio-usability-2026-09-08/regression/export-fixture.webm');
 const importTake=async name=>{await page.locator('#importInput').setInputFiles({name:name+' lesson.webm',mimeType:'video/webm',buffer});await page.waitForFunction(()=>document.querySelector('#editVideo').duration>0);};
 const select=async name=>{await page.locator('#tabEdit').click();await page.getByRole('button',{name:new RegExp('Select.*'+name+' lesson')}).click();await page.locator('#tabExport').click();};
 const snapshot=()=>page.evaluate(()=>Object.fromEntries(['titleInput','exportPreset','exportFormat','exportFraming','exportContainer','titleCardChk','titleCardStyle','closingCardChk','closingCardText','demoStepTransition','capMode','captionStyle','captionSize','captionFont','captionPosition','captionBackground','captionOpacity'].map(id=>{const e=document.getElementById(id);return[id,e.type==='checkbox'?e.checked:e.value];})));
 const drafts=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('allo_video_studio');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,q=db.transaction('takes').objectStore('takes').getAll();q.onsuccess=()=>{resolve(q.result.map(r=>({name:r.name,settings:r.exportSettings})));db.close();};};}));
 await importTake('First');await page.locator('#tabExport').click();
 await page.locator('#titleInput').fill('Fractions — lesson one');await page.locator('#exportPreset').selectOption('social_vertical');await page.locator('#exportContainer').selectOption('webm');await page.locator('#titleCardChk').check();await page.locator('#titleCardStyle').selectOption('calm-family');await page.locator('#closingCardChk').check();await page.locator('#closingCardText').fill('Try your own fraction!');await page.locator('#demoStepTransition').selectOption('smooth');await page.locator('#captionSize').selectOption('large');await page.locator('#captionFont').selectOption('legible');await page.locator('#captionPosition').selectOption('top');await page.locator('#captionBackground').selectOption('solid');await page.locator('#captionOpacity').selectOption('strong');
 const first=await snapshot();await importTake('Second');await page.locator('#tabExport').click();assert.equal(await page.locator('#titleInput').inputValue(),'');assert.equal(await page.locator('#closingCardText').inputValue(),'Thanks for watching');
 await page.locator('#titleInput').fill('Shapes — lesson two');await page.locator('#exportPreset').selectOption('small');await page.locator('#exportFormat').selectOption('square_1080');await page.locator('#closingCardChk').uncheck();await page.locator('#captionPosition').selectOption('bottom');const second=await snapshot();
 await select('First');assert.deepEqual(await snapshot(),first);await select('Second');assert.deepEqual(await snapshot(),second);
 const saved=await drafts();assert.equal(saved.find(r=>/First/.test(r.name)).settings.titleInput,first.titleInput);assert.equal(saved.find(r=>/Second/.test(r.name)).settings.titleInput,second.titleInput);
 await page.reload();await page.locator('#recoverBtn').click();await select('First');assert.deepEqual(await snapshot(),first);await select('Second');assert.deepEqual(await snapshot(),second);
 // Templates update the draft even though their changes are programmatic.
 await page.locator('#titleInput').fill('');await page.locator('#templateSelect').selectOption('family');await page.locator('#applyTemplateBtn').click();const templated=await snapshot();assert.ok(templated.titleInput);await page.reload();await page.locator('#recoverBtn').click();await select('Second');assert.deepEqual(await snapshot(),templated);
 // Older demo drafts initialize their cards once; stale or malformed values are ignored.
 await page.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('allo_video_studio');req.onsuccess=()=>{const db=req.result,tx=db.transaction('takes','readwrite'),store=tx.objectStore('takes'),q=store.getAll();q.onsuccess=()=>{for(const r of q.result){if(/First/.test(r.name)){delete r.exportSettings;r.demoPolish={openingTitle:'Original demo title',openingEnabled:true,closingEnabled:true,closingText:'Original demo ending',transition:'smooth'};}else{r.exportSettings={titleInput:'x'.repeat(180),exportFormat:'not-a-format',titleCardChk:'false',closingCardText:'y'.repeat(180),suggestPrivacyAck:true,unknown:'value'};}store.put(r);}};tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};}));
 await page.reload();await page.locator('#recoverBtn').click();await select('First');assert.equal(await page.locator('#titleInput').inputValue(),'Original demo title');assert.equal(await page.locator('#closingCardText').inputValue(),'Original demo ending');
 await page.locator('#titleInput').fill('Revised demo title');await page.locator('#titleCardChk').uncheck();await page.locator('#closingCardText').fill('Revised ending');await page.locator('#demoStepTransition').selectOption('none');const revised=await snapshot();
 await select('Second');assert.equal((await page.locator('#titleInput').inputValue()).length,120);assert.equal((await page.locator('#closingCardText').inputValue()).length,120);assert.notEqual(await page.locator('#exportFormat').inputValue(),'');assert.equal(await page.locator('#suggestPrivacyAck').isChecked(),false);
 await select('First');assert.deepEqual(await snapshot(),revised);await page.reload();await page.locator('#recoverBtn').click();await select('First');assert.deepEqual(await snapshot(),revised);
 assert.equal(Object.hasOwn((await drafts()).find(r=>/Second/.test(r.name)).settings,'suggestPrivacyAck'),false);
 // Clearing a title is intentional and remains cleared through recovery.
 await page.locator('#titleInput').fill('');await page.reload();await page.locator('#recoverBtn').click();await select('First');assert.equal(await page.locator('#titleInput').inputValue(),'');
 // A real prepared export uses the recovered title and requested format.
 await page.locator('#titleInput').fill('Recovered lesson');await page.locator('#exportPreset').selectOption('small');await page.locator('#exportFormat').selectOption('original');await page.locator('#exportContainer').selectOption('webm');await page.locator('#closingCardChk').uncheck();await page.locator('#capMode').selectOption('none');
 await page.reload();await page.locator('#recoverBtn').click();await select('First');await page.locator('#exportBtn').click();await page.locator('#resultCard').waitFor({state:'visible',timeout:60000});const downloadPromise=page.waitForEvent('download');await page.locator('#downloadBtn').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/Recovered.lesson.*webm/i);await download.saveAs(out+'/recovered-export.webm');
 await page.locator('#titleInput').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/export-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('#titleInput').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:out+'/export-mobile.png'});
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({passed:true,checks:['independent take titles and all export choices','fresh take does not inherit title or closing message','settings survive draft recovery','programmatic template changes persist','legacy demo settings initialize once','manual demo edits survive switching and recovery','cleared title stays empty','invalid settings rejected and text bounded','review acknowledgements excluded','actual export uses recovered title','desktop and mobile layout'],download:download.suggestedFilename(),errors},null,2));console.log('Draft settings browser checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
