'use strict';

const { ETS, ETS_PAGE, TESOL, WIDA, EL_TOOLKIT, ED_EL } = require('./sources.cjs');
const commonRefs = [ETS, ETS_PAGE, TESOL, WIDA];
const equityRefs = [ETS, TESOL, WIDA, EL_TOOLKIT, ED_EL];

function chapter(id, skillId, title, summary, objectives, topics) {
  return {
    id, skillId, title, summary, objectives,
    sections: topics.map(([heading, principle, terms]) => ({
      heading,
      content: principle + ' For Praxis ESOL, connect the concept to observable learner language, the communicative or disciplinary purpose, and the evidence needed to choose an instructional or assessment response. Avoid treating multilingual development, accent, dialect, culture, identity, schooling history, or one score as a deficit or diagnosis. A strong decision preserves grade-level access and intellectual challenge while making language demands visible, using multilingual assets strategically, and specifying how support will be monitored and adjusted. During review, explain why the best response fits the construct and why each alternative overgeneralizes, removes meaningful participation, confuses language difference with disability, changes the measured construct, or exceeds the educator\'s role.',
      keyTerms: terms,
    })),
  };
}

const chapters = [
  chapter('esol5362-ch-01', 'linguistics-language-structure', 'Phonology, Morphology, Syntax, and Language Structure', 'Use linguistic analysis to interpret learner patterns and design focused, meaningful instruction.', ['Analyze sound and connected-speech patterns.', 'Explain inflectional and derivational morphology.', 'Connect syntax with grammatical roles and meaning.'], [
    ['Phonetics, phonology, and intelligibility', 'Phonetics describes speech production and perception; phonology explains how sound contrasts and patterns function in a language. Analyze place, manner, voicing, stress, rhythm, reduction, and linking when they affect perception or intelligibility. Prioritize communicative load rather than attempting to erase accent identity.', ['phoneme', 'minimal pair', 'intelligibility']],
    ['Morphology and word formation', 'Morphemes are the smallest meaningful units. Inflection marks grammatical information such as number or tense, while derivation creates new meanings and sometimes new word classes. Roots, affixes, allomorphs, and word families support vocabulary, grammar, and literacy development.', ['morpheme', 'inflection', 'derivation']],
    ['Syntax and grammatical relationships', 'Syntax organizes words and phrases into clauses and sentences. Word order, function words, agreement, tense, aspect, voice, subordination, and phrase attachment signal relationships. Analyze the meaning a learner intends before selecting a contrast, model, or scaffold.', ['syntax', 'constituent', 'voice']],
    ['Contrastive and developmental analysis', 'A recurring form may reflect cross-linguistic influence, overgeneralization, developmental sequence, task demands, or attention. Contrast languages when useful, but verify rather than assume the cause. Treat learner language as systematic evidence and plan opportunities to notice, test, revise, and reuse forms.', ['transfer', 'overgeneralization', 'interlanguage']],
  ]),
  chapter('esol5362-ch-02', 'linguistics-meaning-language-use', 'Semantics, Pragmatics, Discourse, and Sociolinguistics', 'Interpret meaning across words, interaction, extended discourse, register, and language varieties.', ['Analyze lexical and contextual meaning.', 'Interpret intent, register, and interactional conventions.', 'Distinguish systematic variation from deficit.'], [
    ['Semantics and lexical relationships', 'Semantic knowledge includes word meaning, multiple meanings, synonyms, antonyms, semantic fields, collocations, and relationships among propositions. Context, syntax, morphology, topic, and conventional word partnerships help learners select the intended meaning.', ['semantics', 'polysemy', 'collocation']],
    ['Pragmatics and communicative intent', 'Pragmatics concerns how speakers interpret requests, implicature, politeness, stance, shared knowledge, and indirect meaning in context. The same form can perform different functions across relationships and settings, so instruction should compare authentic examples without ranking cultural conventions.', ['pragmatics', 'implicature', 'speech act']],
    ['Discourse, cohesion, and interaction', 'Extended language depends on organization, reference, lexical ties, transitions, rhetorical moves, turn taking, topic management, clarification, and repair. Word-level accuracy alone does not guarantee coherent academic explanation or successful participation.', ['discourse', 'cohesion', 'repair']],
    ['Register, dialect, and language variation', 'Languages vary systematically by community, region, identity, genre, medium, audience, and purpose. Teach additional academic and high-stakes conventions transparently while respecting home varieties, global Englishes, and accent. Difference is not disorder.', ['register', 'dialect', 'sociolinguistics']],
  ]),
  chapter('esol5362-ch-03', 'learning-acquisition-development', 'Language Acquisition, Interaction, Feedback, and Development', 'Apply language-learning principles to input, interaction, output, feedback, practice, and learner engagement.', ['Distinguish receptive and productive development.', 'Design comprehensible input and negotiated interaction.', 'Select feedback and practice that support development.'], [
    ['Input, noticing, and comprehension', 'Learners need meaningful input they can understand while attending to relevant form-function relationships. Visuals, context, modeling, prior knowledge, predictable structure, and checks for understanding increase access without eliminating conceptual challenge.', ['comprehensible input', 'noticing', 'receptive language']],
    ['Interaction and pushed output', 'Information and reasoning gaps create purposes for questions, clarification, confirmation, explanation, and repair. Output can prompt learners to notice gaps and refine language, especially when listeners respond and tasks require precision rather than scripted repetition.', ['negotiation of meaning', 'output', 'information gap']],
    ['Feedback, interlanguage, and variability', 'Interlanguage is developing and variable. Choose feedback based on objective, pattern, readiness, communicative impact, and activity focus. Recasts, prompts, explicit explanation, and metalinguistic cues are useful only when learners notice, process, and reuse the language.', ['interlanguage', 'corrective feedback', 'uptake']],
    ['Practice, retrieval, and motivation', 'Durable language access grows through spaced, varied, meaningful retrieval after understanding. Motivation and willingness to communicate are shaped by identity, safety, belonging, autonomy, competence, task value, and relationships, not a fixed learner trait.', ['retrieval', 'automatization', 'investment']],
  ]),
  chapter('esol5362-ch-04', 'learning-multilingualism-transfer-identity', 'Multilingualism, Transfer, Identity, and Learner Factors', 'Build on the full linguistic repertoire while responding to age, schooling, literacy, identity, and individual development.', ['Use cross-linguistic transfer strategically.', 'Explain distributed multilingual competence.', 'Plan additive, identity-affirming support.'], [
    ['Cross-linguistic influence and transfer', 'Prior-language knowledge can support cognates, concepts, literacy strategies, genre knowledge, and metalinguistic awareness. It can also produce predictable contrasts. Elicit existing knowledge, compare systems, verify meaning, and bridge explicitly rather than banning or romanticizing transfer.', ['cross-linguistic influence', 'cognate', 'transfer']],
    ['Translanguaging and multilingual resources', 'Purposeful use of the full repertoire can support planning, reasoning, identity, collaboration, and access. Maintain the English-language outcome while allowing strategic multilingual sense making, comparison, and rehearsal. Translation requires verification and should not replace independent learning goals.', ['translanguaging', 'repertoire', 'translation']],
    ['Identity, age, and individual factors', 'Language learning interacts with identity, age, literacy, education, trauma, social position, aptitude, opportunity, and goals. No single factor determines outcomes across pronunciation, interaction, reading, writing, academic discourse, and content learning.', ['identity', 'learner factors', 'opportunity']],
    ['Newcomers, interrupted schooling, and biliteracy', 'Newcomers and students with interrupted formal education need age-respectful content access plus explicit language, literacy, routines, background, and coordinated support. Home-language literacy and family communication are assets rather than obstacles to English development.', ['newcomer', 'interrupted schooling', 'biliteracy']],
  ]),
  chapter('esol5362-ch-05', 'planning-objectives-materials-differentiation', 'Standards, Objectives, Materials, and Differentiation', 'Plan integrated content-language learning from standards, learner evidence, material demands, and access needs.', ['Write observable content and language objectives.', 'Analyze materials and disciplinary language.', 'Differentiate support without reducing rigor.'], [
    ['Standards and integrated objectives', 'Begin with grade-level content and language-development standards. Analyze the language function, discourse, sentence patterns, vocabulary, modes, and interaction needed to learn and demonstrate the content. State observable content and language outcomes with aligned evidence.', ['content objective', 'language objective', 'language function']],
    ['Task and material analysis', 'Evaluate conceptual demand, assumed background, text structure, syntax, vocabulary, visuals, audio rate, cultural positioning, accessibility, and bias. Adapt representation and support while retaining essential ideas, evidence, and meaningful learner agency.', ['task analysis', 'materials', 'language demand']],
    ['Vocabulary, background, and modalities', 'Prioritize conceptually central, transferable, and recurring words. Build relevant background diagnostically and without stereotyping. Connect listening, speaking, reading, and writing so learners encounter, negotiate, rehearse, and produce ideas across modes.', ['academic vocabulary', 'background knowledge', 'modalities']],
    ['Differentiation, grouping, and technology', 'Differentiate input, process, interaction, output, scaffolds, and independence from evidence. Use flexible purpose-driven groups. Evaluate technology for alignment, accessibility, accuracy, privacy, learner control, and contribution to language learning.', ['differentiation', 'flexible grouping', 'educational technology']],
  ]),
  chapter('esol5362-ch-06', 'instruction-interaction-scaffolding-literacy', 'Interaction, Scaffolding, Feedback, and Integrated Literacy', 'Implement communicative, disciplinary, and literacy instruction with responsive scaffolds and feedback.', ['Facilitate equitable extended interaction.', 'Scaffold disciplinary genres and explanations.', 'Develop strategic reading, writing, and intelligible speech.'], [
    ['Classroom interaction and comprehension', 'Increase wait time, distribute participation, ask open and probing questions, promote student-to-student uptake, and teach clarification and repair. Check comprehension through restatement, demonstration, examples, sequencing, or task performance rather than yes-no self-report.', ['wait time', 'uptake', 'comprehension check']],
    ['Scaffolding and gradual release', 'Model the target, think aloud, use visuals or organizers, jointly construct, rehearse, prompt, and fade support from performance evidence. A scaffold enables the intended reasoning and language temporarily; it should not become a completed answer or a ceiling.', ['scaffold', 'joint construction', 'gradual release']],
    ['Genre, reading, and writing development', 'Deconstruct authentic disciplinary genres for purpose, organization, evidence, rhetorical moves, and language features. Teach readers and writers to plan, monitor, infer, use morphology and context, evaluate sources, draft, receive feedback, revise, and transfer strategies.', ['genre', 'reading strategy', 'revision']],
    ['Form-focused feedback and intelligibility', 'Respond to meaning and selectively address recurring, objective-aligned forms. Use perception, articulation, prosody, and meaningful production when pronunciation affects intelligibility. Invite self-correction and reuse while protecting participation and accent identity.', ['focus on form', 'pronunciation', 'intelligibility']],
  ]),
  chapter('esol5362-ch-07', 'assessment-purpose-validity-proficiency', 'Assessment Purpose, Validity, Reliability, and Proficiency', 'Align assessment purpose, construct, evidence, interpretation, access, and decision boundaries.', ['Distinguish diagnostic, formative, and summative purposes.', 'Evaluate validity, reliability, and fairness.', 'Interpret proficiency evidence within its limits.'], [
    ['Purpose, construct, and evidence', 'Clarify the decision and intended construct before selecting a task. Diagnostic assessment identifies starting patterns, formative assessment guides ongoing learning, and summative assessment evaluates achievement after instruction. Each requires evidence aligned to its use.', ['assessment purpose', 'construct', 'evidence']],
    ['Validity, reliability, and fairness', 'Validity concerns support for score interpretation and use; reliability concerns consistency. Fairness examines access, bias, representation, opportunity, and construct-irrelevant barriers. Authentic complexity may remain when it is part of what the task intends to measure.', ['validity', 'reliability', 'fairness']],
    ['Proficiency frameworks and reference frames', 'Proficiency is multidimensional across modes, purposes, genres, topics, contexts, and supports. Norm-referenced results compare with a group; criterion-referenced results compare with expectations. Composite levels cannot replace domain and task evidence.', ['proficiency', 'norm referenced', 'criterion referenced']],
    ['Standardized assessment and accommodations', 'Use standardized scores only for supported interpretations and authorized purposes. Accommodations remove access barriers without changing the essential construct and follow approved procedures. One score is not a diagnosis, disability decision, or complete learner profile.', ['standardized assessment', 'accommodation', 'score interpretation']],
  ]),
  chapter('esol5362-ch-08', 'assessment-classroom-data-fairness', 'Classroom Assessment, Data Use, Fairness, and Monitoring', 'Gather and interpret multiple evidence sources for feedback, instruction, monitoring, and program decisions.', ['Design aligned formative and performance assessments.', 'Use rubrics, portfolios, and error analysis.', 'Triangulate data for monitoring and evaluation.'], [
    ['Formative and performance assessment', 'Elicit a brief authentic performance using the target content-language function, apply transparent criteria, analyze patterns, and take an instructional next step. Completion, enjoyment, and attendance may matter but do not directly measure the target performance.', ['formative assessment', 'performance task', 'feedback loop']],
    ['Rubrics, portfolios, and self-assessment', 'Rubrics need observable task-aligned descriptors and exemplars. Portfolios need purposeful samples across time and modes, common criteria, context, reflection, feedback, and revision. Teach learners to use criteria for planning and self-monitoring.', ['analytic rubric', 'portfolio', 'self-assessment']],
    ['Error analysis and multiple measures', 'Classify learner patterns by form, function, context, frequency, communicative effect, development, and response to support. Triangulate proficiency measures, classroom work, content performance, opportunity, attendance, and family or learner perspectives while naming uncertainty.', ['error analysis', 'triangulation', 'uncertainty']],
    ['Identification, exit, monitoring, and program evidence', 'Follow current authorized criteria for EL identification, services, exit, former-EL monitoring, and program evaluation. Use valid multiple evidence, accessible communication, documentation, longitudinal outcomes, implementation data, subgroup patterns, and responsive support.', ['identification', 'exit criteria', 'monitoring']],
  ]),
  chapter('esol5362-ch-09', 'culture-identity-responsiveness-power', 'Culture, Identity, Responsiveness, and Power', 'Create rigorous, culturally sustaining learning while examining representation, interaction, identity, and institutional norms.', ['Avoid cultural essentialism and tokenism.', 'Interpret interaction across contexts.', 'Analyze bias, representation, and language ideology.'], [
    ['Dynamic culture and intersectionality', 'Culture changes and intersects with language, race, class, religion, gender, disability, migration, schooling, generation, place, and individual experience. Use broad knowledge to ask better questions, not to assign fixed preferences or identities to a learner.', ['culture', 'intersectionality', 'essentialism']],
    ['Culturally sustaining curriculum', 'Use accurate varied perspectives, contemporary and historical complexity, community knowledge, counternarratives, and meaningful learner choice. Avoid portraying a group only through problems, celebrations, foods, or one representative student.', ['culturally sustaining pedagogy', 'representation', 'tokenism']],
    ['Interaction, norms, and cross-cultural interpretation', 'Eye contact, silence, turn taking, disagreement, questioning, authority, time, and feedback can carry different meanings. Suspend judgment, explain school expectations, co-construct norms, offer multiple entry points, and examine participation and power.', ['interactional norm', 'cross-cultural', 'participation']],
    ['Language ideology, bias, and belonging', 'Materials and institutions communicate beliefs about which languages, varieties, accents, and identities count as intelligent or legitimate. Teach critical language awareness and additional access conventions without demanding assimilation or devaluing existing repertoires.', ['language ideology', 'bias', 'belonging']],
  ]),
  chapter('esol5362-ch-10', 'culture-family-community-partnerships', 'Family, Community, and Cross-Cultural Partnerships', 'Build reciprocal, accessible partnerships grounded in family expertise, language access, privacy, consent, and institutional responsibility.', ['Provide meaningful family language access.', 'Design reciprocal engagement across barriers.', 'Use community knowledge and partnerships responsibly.'], [
    ['Qualified language access', 'Consequential communication requires understandable translated or interpreted information through qualified approved procedures. Address caregivers directly, protect confidentiality, verify understanding, invite questions, and avoid using children as interpreters or unreviewed automated output for high-stakes matters.', ['language access', 'qualified interpreter', 'confidentiality']],
    ['Reciprocal family engagement', 'Investigate schedules, transportation, technology, literacy, language, prior institutional experiences, communication preferences, and goals. Offer varied channels and co-design meaningful roles. Event attendance and quick English replies are not measures of family commitment.', ['family engagement', 'reciprocity', 'institutional barrier']],
    ['Funds of knowledge and community expertise', 'Households and communities hold knowledge from work, caregiving, art, language, faith, technology, advocacy, and local history. Connect this expertise to rigorous objectives with consent, reciprocity, and choice rather than turning learners into cultural exhibits.', ['funds of knowledge', 'community expertise', 'reciprocity']],
    ['Partnership roles, data, and repair', 'Define partner purpose, consent or authority, roles, training, data minimization, security, accessibility, oversight, evaluation, and exit terms. When misunderstandings occur, clarify intent and impact, invite perspectives, repair harm, and establish a clearer shared process.', ['data minimization', 'partnership', 'repair']],
  ]),
  chapter('esol5362-ch-11', 'professional-collaboration-ethics-inquiry', 'Collaboration, Ethics, Inquiry, and Professional Boundaries', 'Collaborate across roles, use evidence, protect privacy and agency, and distinguish instruction from diagnosis or legal decisions.', ['Co-plan language and content instruction.', 'Conduct focused reflective inquiry.', 'Maintain ethical role, privacy, and learner-agency boundaries.'], [
    ['Language-content collaboration', 'Co-plan content and language objectives, disciplinary demands, materials, grouping, scaffolds, assessment, and review before instruction. Share relevant learner evidence and responsibilities. Complementary expertise does not make the ESOL teacher solely responsible for all access or remediation.', ['co-planning', 'collaboration', 'shared responsibility']],
    ['Reflective inquiry and research use', 'Frame a focused practice question, gather learner work and interaction evidence, consult credible research and colleagues, implement a feasible change, and evaluate intended and unintended effects. Appraise participants, measures, comparisons, limitations, fit, and equity.', ['reflective inquiry', 'evidence', 'implementation']],
    ['Disability, role, and multidisciplinary process', 'Language difference and disability can coexist. Provide language support, document specific observations across contexts and languages, and collaborate in timely qualified multidisciplinary procedures. Do not diagnose, determine eligibility alone, or wait for full English mastery before warranted evaluation.', ['language difference', 'disability', 'multidisciplinary team']],
    ['Privacy, consent, and learner agency', 'Share identifiable information only for legitimate authorized responsibilities through secure procedures. Do not coerce personal disclosure or assign bilingual students adult interpreting roles. Protect choice, dignity, confidentiality, and meaningful participation.', ['privacy', 'consent', 'student agency']],
  ]),
  chapter('esol5362-ch-12', 'professional-advocacy-programs-access', 'Advocacy, Program Evaluation, Rights, and Meaningful Access', 'Use evidence and collaboration to remove barriers, evaluate programs, and support legally and educationally sound access.', ['Identify and address systemic access barriers.', 'Evaluate EL program implementation and outcomes.', 'Apply rights and service boundaries through current qualified procedures.'], [
    ['Meaningful access and language assistance', 'Physical placement or identical materials do not guarantee meaningful participation. Schools provide educationally sound, adequately staffed and resourced language assistance plus access to grade-level curricula, advanced courses, extracurricular activities, services, and safe inclusive environments.', ['meaningful access', 'language assistance', 'opportunity']],
    ['Evidence-based advocacy', 'Document a barrier and its effects, center learner and family perspectives, analyze policy and data, identify role and authority, propose feasible equitable changes, build coalitions, and monitor access and outcomes. Preserve legitimate standards while removing irrelevant barriers.', ['advocacy', 'barrier analysis', 'coalition']],
    ['Program implementation and evaluation', 'Evaluate language growth, content access and outcomes, participation, staffing, services, fidelity and quality, subgroup patterns, family input, exit, former-EL monitoring, and unintended effects over time. Use findings to improve rather than select only favorable indicators.', ['program evaluation', 'implementation', 'longitudinal outcome']],
    ['Segregation, opt-out, and current procedures', 'Targeted language support may be appropriate, but separation must be educationally justified, limited, effective, and reviewed. Declining one service does not erase access obligations. Verify current federal, state, local, program, privacy, and civil-rights procedures with qualified authority.', ['segregation', 'opt out', 'civil rights']],
  ]),
];

const memoryAids = [
  ['Sound to meaning', 'Identify the sound contrast, articulatory and perceptual features, communicative load, meaningful examples, feedback, and transfer context.', 'Foundations of Linguistics', commonRefs, ['linguistics', 'phonology']],
  ['Morpheme map', 'Separate root, inflection, and derivation; connect each form to meaning, grammatical function, and word-family use.', 'Foundations of Linguistics', commonRefs, ['linguistics', 'morphology']],
  ['Form-meaning-use', 'Teach what a language form looks or sounds like, what it means, and when or why speakers choose it.', 'Foundations of Linguistics', commonRefs, ['linguistics', 'grammar']],
  ['Discourse lens', 'Track purpose, organization, reference, lexical ties, transitions, rhetorical moves, turn taking, and repair beyond the sentence.', 'Foundations of Linguistics', commonRefs, ['linguistics', 'discourse']],
  ['Input-interaction-output', 'Make input comprehensible, create a reason to negotiate meaning, require purposeful output, provide feedback, and invite reuse.', 'Foundations of Language Learning', commonRefs, ['learning', 'interaction']],
  ['Feedback fit', 'Match feedback to objective, pattern, readiness, activity focus, communicative impact, learner processing, and opportunity to revise.', 'Foundations of Language Learning', commonRefs, ['learning', 'feedback']],
  ['Transfer verify', 'Elicit prior-language knowledge, compare systems, identify possible positive or negative transfer, and verify rather than assume.', 'Foundations of Language Learning', commonRefs, ['multilingualism', 'transfer']],
  ['Asset not ceiling', 'Use the full multilingual repertoire for thinking and access while maintaining rigorous content and English-language outcomes.', 'Foundations of Language Learning', commonRefs, ['multilingualism', 'assets']],
  ['Content-language pair', 'Name the grade-level concept and the language function, discourse, forms, vocabulary, modes, and evidence needed to demonstrate it.', 'Planning and Implementing Instruction', commonRefs, ['planning', 'objectives']],
  ['Scaffold and fade', 'Model, jointly construct, prompt and rehearse, observe performance, then reduce or change support while preserving the goal.', 'Planning and Implementing Instruction', commonRefs, ['instruction', 'scaffolding']],
  ['Meaningful interaction', 'Build an information, opinion, or reasoning gap with audience, outcome, accountable roles, wait time, clarification, and uptake.', 'Planning and Implementing Instruction', commonRefs, ['instruction', 'interaction']],
  ['Genre pathway', 'Deconstruct purpose and features, jointly construct, guide independent production, give aligned feedback, revise, and transfer.', 'Planning and Implementing Instruction', commonRefs, ['literacy', 'genre']],
  ['Purpose-construct-evidence', 'Start assessment design with the intended decision, construct, task evidence, interpretation, and action.', 'Assessment and Evaluation', commonRefs, ['assessment', 'validity']],
  ['Validity-reliability-fairness', 'Ask whether the interpretation is supported, results are dependable, and learners can access the construct without irrelevant barriers.', 'Assessment and Evaluation', commonRefs, ['assessment', 'fairness']],
  ['Multiple-measures boundary', 'Triangulate domain scores, classroom performance, opportunity, learner and family evidence, and uncertainty without inventing a diagnosis or decision.', 'Assessment and Evaluation', equityRefs, ['assessment', 'data']],
  ['Dynamic culture', 'Use cultural knowledge to ask respectful questions, then learn the individual, intersectional, historical, and changing context.', 'Culture', equityRefs, ['culture', 'identity']],
  ['Access is two-way', 'Provide qualified language access, address families directly, invite expertise and questions, verify understanding, and follow up.', 'Culture', equityRefs, ['family', 'language access']],
  ['Role-authority-evidence', 'Name your role, share specific authorized evidence, collaborate with the qualified process, protect privacy, document, and follow up.', 'Professionalism and Advocacy', equityRefs, ['professionalism', 'ethics']],
  ['Barrier to remedy', 'Document the access barrier, center affected voices, analyze policy and data, propose a feasible remedy, build collaboration, and monitor results.', 'Professionalism and Advocacy', equityRefs, ['advocacy', 'equity']],
  ['Program evidence cycle', 'Examine implementation, language and content outcomes, participation, subgroup patterns, family input, exit and monitoring, then improve.', 'Professionalism and Advocacy', equityRefs, ['program evaluation', 'data']],
].map(([title, content, domain, references, tags]) => ({ title, content, domain, references, tags }));

function workshop(index, taskType, title, prompt, stimulus, taskParts, sampleOutline, references = commonRefs) {
  return {
    id: 'esol5362-workshop-' + String(index).padStart(2, '0'), taskType, title, prompt, stimulus, taskParts,
    planningFrame: [
      { label: 'Evidence', guidance: 'Identify the exact transcript, prosody, learner-language, classroom, assessment, cultural, or program evidence that controls the analysis.' },
      { label: 'Concept', guidance: 'Name the relevant linguistic, learning, instructional, assessment, cultural, or professional principle without overgeneralizing.' },
      { label: 'Response', guidance: 'Select a feasible action that preserves meaning, rigor, multilingual assets, access, identity, role, and learner participation.' },
      { label: 'Follow-up', guidance: 'State what evidence would show whether the response helped and when support, grouping, feedback, or process should change.' },
    ],
    successCriteria: [
      'Uses specific stimulus evidence rather than relying on a stereotype or an unsupported assumption about language, culture, ability, or motivation.',
      'Applies an accurate ESOL concept and distinguishes language difference, development, task demand, and disability or legal decisions.',
      'Proposes a rigorous, accessible, identity-affirming response within the educator\'s role and current authorized procedures.',
      'Includes an observable follow-up measure and acknowledges important limits of the transcript, classroom sample, or available data.',
    ],
    commonPitfalls: [
      'Treating a transcript as a complete audio sample or inferring pronunciation features that are not described.',
      'Correcting every language difference instead of prioritizing the stated objective, meaning, intelligibility, or access need.',
      'Lowering content expectations, banning multilingual resources, or assigning one learner to represent an entire group.',
      'Making a diagnosis, proficiency, exit, civil-rights, or legal determination from a single workshop stimulus.',
    ],
    sampleOutline,
    references,
  };
}

const workshops = [
  workshop(1, 'Transcript and Prosody Analysis', 'Reduced speech in a classroom announcement', 'Analyze the listening demand, identify two scaffolds that preserve natural spoken English, and explain how the teacher can check whether learners recognize the key message independently.', 'Transcript: "You\'re gonna needta turn those in by Friday, but you can leave the cover sheet till Monday." Delivery notes: The speaker uses a natural conversational rate. Going to is reduced, need to is linked, the words turn and Friday receive prominent stress, and but signals a qualification. Two intermediate learners identify Friday and Monday but reverse which document is due on each day. They can read the printed sentence accurately when it is shown after listening. No audio recording is included; the notes describe only the features relevant to this original practice case.', ['Identify the connected-speech and discourse cues affecting meaning.', 'Select perception, transcript, and rehearsal scaffolds without permanently slowing all input.', 'Define a transfer check using a new announcement with comparable features.'], ['Evidence: reductions, linking, contrast, stress, and reversed deadlines.', 'Response: repeated listening, marked transcript, chunking, reconstruction, and faded text support.', 'Follow-up: a new natural-rate message requiring correct action and explanation.']),
  workshop(2, 'Transcript and Pragmatics Analysis', 'Indirect request during collaborative work', 'Explain why the learner response is pragmatically understandable, propose explicit instruction that avoids cultural deficit framing, and identify evidence of successful transfer.', 'Transcript: Teacher says, "Could we make a little more room for Maya?" A learner replies, "Yes, we could," but does not move materials. Delivery notes: The teacher uses rising-falling intonation and looks toward the crowded table. In a later interview, the learner explains that the sentence sounded like a question about possibility rather than a request. The learner understands the words could, make, room, and Maya. No audio is supplied; this original transcript and description are designed for analysis of form, intent, and contextual cues.', ['Distinguish literal grammatical form from contextual speech-act function.', 'Plan comparison and rehearsal across direct and mitigated requests.', 'Specify a new context in which the learner must interpret and respond to intent.'], ['Evidence: literal interpretation despite lexical comprehension.', 'Response: contrast forms, context and prosody, role-play, clarification language, and no moral judgment.', 'Follow-up: accurate response and explanation across a new relationship and setting.']),
  workshop(3, 'Transcript and Intelligibility Analysis', 'Word stress in an academic explanation', 'Identify the feature most likely affecting listener comprehension, plan a focused intelligibility intervention, and explain what should not be inferred from the sample.', 'Transcript: "The CONtent changed when we conTENT the solution" is produced while a student explains a chemistry procedure. Delivery notes: The learner places stress on the first syllable in both uses of the spelled form and speaks all other key terms clearly. Peers understand the first clause but ask what action occurred in the second. The written explanation correctly distinguishes the noun content from the intended verb-like form, though the chosen wording is awkward. This is a constructed practice description, not a recording or diagnosis.', ['Analyze stress, lexical choice, grammar, and listener evidence separately.', 'Prioritize a meaningful perception-production task tied to the explanation.', 'Define an intelligibility check and state the limits of one sample.'], ['Evidence: stress pattern and peer breakdown localized to one phrase.', 'Response: choose a clearer verb, compare stress patterns where applicable, mark prominence, rehearse in context.', 'Follow-up: listener paraphrase in a new explanation; no global accent judgment.']),
  workshop(4, 'Transcript and Discourse Analysis', 'Tracking contrast in an oral argument', 'Analyze why listeners lose the argument, select discourse-focused scaffolds, and describe how the teacher should evaluate improvement beyond word-level accuracy.', 'Transcript: "The plan costs less. It reaches fewer neighborhoods. The old plan costs more. It has more stops. I choose this one." Delivery notes: The learner speaks clearly and uses accurate simple sentences but does not name which plan this one refers to or signal whether cost or coverage controls the decision. A planning note shows the learner intended to choose the old plan because access outweighed cost. The original case contains no audio; it supplies only the transcript and contextual evidence necessary for discourse analysis.', ['Identify reference, contrast, stance, and reasoning gaps.', 'Plan modeling and joint construction of a clearer comparative argument.', 'Use criteria for listener interpretation, cohesion, and evidence-based stance.'], ['Evidence: clear clauses but ambiguous reference and unstated criterion.', 'Response: comparison organizer, connectors, explicit noun reference, stance frames, rehearsal and feedback.', 'Follow-up: listeners identify the chosen plan and supporting tradeoff in a new task.']),
  workshop(5, 'Classroom Instruction Analysis', 'Maintaining rigor in a science investigation', 'Analyze the content and language demands, propose a scaffolded instructional sequence, and define formative evidence for both scientific reasoning and English development.', 'Seventh-grade students must compare insulation materials, interpret a temperature table, and justify a recommendation. Several multilingual learners can identify the best-performing material from the table but produce labels rather than causal explanations. The current teacher plan replaces the investigation with a vocabulary worksheet for those learners. Available resources include physical samples, a model explanation, multilingual glossaries, graph paper, and structured partner time. The school expects all students to address the same scientific reasoning standard.', ['Identify the scientific construct and the language function and discourse needed.', 'Design access, interaction, modeling, and gradual-release supports without replacing the investigation.', 'Specify separate but connected evidence of content reasoning and language growth.'], ['Evidence: correct interpretation but incomplete causal discourse.', 'Response: maintain investigation, model and jointly construct explanation, use visuals and function-specific frames, rehearse, fade.', 'Follow-up: independent evidence-based recommendation scored with transparent content and language criteria.']),
  workshop(6, 'Classroom Assessment Analysis', 'Interpreting a multilingual learner profile', 'Explain what the evidence supports and does not support, propose immediate instructional next steps, and identify the qualified process for any continuing disability concern.', 'A fourth-grade learner has attended English-medium school for eighteen months. Classroom work shows strong mathematical reasoning with diagrams and home-language explanation, growing English conversation, and persistent difficulty decoding in both languages. Attendance has been regular, vision and hearing screenings are current, and targeted decoding instruction has produced limited growth across two monitored cycles. One teacher says all difficulty is caused by English learning; another says the English reading score proves a disability. The family requests qualified interpretation and reports a history of reading difficulty among relatives.', ['Separate language development, opportunity, cross-language literacy, intervention response, and disability evidence.', 'Plan continued accessible instruction and data collection without delaying a warranted evaluation.', 'Describe family participation and multidisciplinary role boundaries.'], ['Evidence: strengths, cross-language decoding concern, adequate opportunity, limited response, family history, and uncertainty.', 'Response: continue language and literacy support, share specific data, arrange language access, initiate or continue qualified evaluation as warranted.', 'Follow-up: no diagnosis from the case; multidisciplinary interpretation across languages and contexts.'], equityRefs),
  workshop(7, 'Culture and Family Partnership Analysis', 'Repairing a consequential family meeting', 'Identify the institutional and cross-cultural communication problems, design a respectful repair, and specify safeguards for future meetings.', 'A school schedules an eligibility-related meeting with two days notice and provides documents only in English. A bilingual older sibling is asked to interpret technical discussion. The caregivers nod during the meeting but later tell a community liaison that they did not understand the decision, believed disagreement would be disrespectful, and had relevant information that was never requested. Staff describe the family as uninvolved because they asked few questions. The scenario does not supply a legal conclusion; it is an original case for analyzing access, power, assumptions, and professional response.', ['Identify language-access, role, scheduling, participation, and stereotype concerns.', 'Plan qualified interpretation, understandable information, direct communication, listening, clarification, and repair.', 'Define documentation and follow-up within current authorized procedures.'], ['Evidence: inadequate notice, English-only documents, child interpreter, nodding misread, excluded expertise.', 'Response: acknowledge impact, arrange qualified access, reconvene as appropriate, invite perspective, verify understanding and rights.', 'Follow-up: accessible summary, questions channel, documented preferences, and procedure review.'], equityRefs),
  workshop(8, 'Program and Advocacy Analysis', 'Evaluating access beyond language-growth scores', 'Analyze the limits of the district conclusion, propose a multidimensional program-evaluation plan, and identify an evidence-based advocacy process.', 'A district reports that its EL program is effective because average annual English-proficiency scores increased. The same dashboard shows multilingual learners are rarely enrolled in advanced coursework, participate less in extracurricular programs with language-heavy applications, and experience higher course-failure rates after exit. Staffing vacancies caused some students to miss designated services, but implementation data are not included in the public report. Families report that translated announcements often arrive after deadlines. District leaders ask the ESOL team for a plan rather than a legal finding.', ['Explain why one favorable outcome cannot establish overall effectiveness.', 'Select implementation, access, language, content, participation, exit, monitoring, and family evidence.', 'Plan collaborative advocacy with affected voices, feasible remedies, authority, timelines, and outcome monitoring.'], ['Evidence: language growth plus access, implementation, post-exit, and communication concerns.', 'Response: disaggregate outcomes, verify service delivery, include family and student perspectives, identify barriers and responsible roles.', 'Follow-up: implement changes with checkpoints and report both access and outcome evidence transparently.'], equityRefs),
];

module.exports = { chapters, memoryAids, workshops };
