import {beforeAll,afterEach,describe,it,expect,vi} from 'vitest';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {loadAlloModule} from './setup.js';
const require=createRequire(import.meta.url);
let AC,H,SR,React,root,host,act,createRoot,latest;
beforeAll(()=>{React=require(resolve('desktop/web-app/node_modules/react'));({createRoot}=require(resolve('desktop/web-app/node_modules/react-dom/client')));({act}=require(resolve('desktop/web-app/node_modules/react-dom/test-utils')));window.React=global.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;loadAlloModule('applied_challenge_module.js');loadAlloModule('studio_response_module.js');loadAlloModule('doc_pipeline_module.js');AC=window.AlloModules.AppliedChallenge;H=AC._testing;SR=window.AlloModules.StudioResponse;});
afterEach(()=>{if(root)act(()=>root.unmount());root=null;host?.remove();sessionStorage.clear();});
const source=(patch={})=>({id:'s',url:'https://example.org/soil',rowId:'r',title:'Soil evidence',foundAt:'2026-09-19',author:'Example Lab',publicationDate:'2024',reviewNote:'A general explanation; it does not measure our local soil.',...patch});
const base=()=>AC.normalize({title:'Garden',sourceExcerpt:'PRIVATE_SOURCE',brief:{drivingQuestion:'Which plan?',lockedLessonFacts:['Water infiltrates soil.'],factVerified:true},workspace:{workingQuestion:'Which plan?',questionAccepted:true,response:'Compare two watering plans.',evidence:'My existing explanation.'},evidenceLedger:[{id:'r',claim:'Try slower watering.',evidence:'My reasoning.',status:'verified'}],sourceRecords:[source()]});
describe('Structured outside sources',()=>{
 it('bounds text, rejects unsafe links, resolves colliding IDs and preserves missing connections',()=>{const data=AC.normalize({sourceRecords:[null,source({url:'javascript:alert(1)'}),source({url:'https://u:p@example.org'}),...Array.from({length:30},(_,i)=>source({id:i===2?'s-1':'s',url:'https://example.org/'+i,title:'x'.repeat(400),reviewNote:'y'.repeat(3000),rowId:'removed',privateSource:'SECRET'}))]});expect(data.sourceRecords).toHaveLength(24);expect(new Set(data.sourceRecords.map(s=>s.id)).size).toBe(24);expect(data.sourceRecords[0]).toMatchObject({rowId:'removed',title:'x'.repeat(350),reviewNote:'y'.repeat(2000)});expect(JSON.stringify(data)).not.toContain('SECRET');});
 it('rejects duplicates per connection and full lists without using writing capacity',()=>{const row=base().evidenceLedger;expect(H.appliedChallengeSourceCaptureCheck([],row,'x'.repeat(8000),source(),'r')).toEqual({ok:true});expect(H.appliedChallengeSourceCaptureCheck([source()],row,'',source(),'r').reason).toBe('duplicate');expect(H.appliedChallengeSourceCaptureCheck([source()],row,'',source(),'').ok).toBe(true);expect(H.appliedChallengeSourceCaptureCheck([],row,'',source(),'gone').reason).toBe('missing');const full=Array.from({length:24},(_,i)=>source({url:'https://example.org/'+i}));expect(H.appliedChallengeSourceCaptureCheck(full,row,'',source(),'').reason).toBe('sources-full');expect(H.appliedChallengeSourceCaptureCheck([],Array.from({length:12},(_,i)=>({id:String(i)})),'',source(),'new').reason).toBe('capacity');});
 it('recognizes legacy citations without rewriting their prose',()=>{const d=base();d.evidenceLedger[0].evidence+='\n'+source().url;expect(H.appliedChallengeSourceCaptureCheck([],d.evidenceLedger,'',source(),'r').reason).toBe('duplicate');expect(AC.normalize(d).evidenceLedger[0].evidence).toContain(source().url);});
 it('does not credit a citation or an unreferenced check note as lesson reasoning',()=>{const d=base();d.workspace.evidence='';d.evidenceLedger=[];expect(H.appliedChallengeReviewItems(d).find(x=>x.id==='evidence').recorded).toBe(false);d.sourceRecords[0].reviewNote='';expect(H.appliedChallengeReviewFollowups(d).find(x=>x.id==='source-s').target.elementId).toBe('aps-source-note-s');});
 it('supports explicit source-note references and requires a recheck after note, URL, or claim changes',()=>{const d=base();d.reasoningReferences=[{part:'evidence',source:'sourceNote',rowId:'s',location:'My note on local limits',referenceFingerprint:H.appliedChallengeHashText(H.appliedReasoningSource(d,{source:'sourceNote',rowId:'s'}))}];expect(H.appliedReasoningReferenceState(d,'evidence').current).toBe(true);expect(H.appliedChallengeReviewTarget(d,'evidence').elementId).toBe('aps-source-note-s');for(const change of [x=>x.sourceRecords[0].reviewNote+=' Changed.',x=>x.sourceRecords[0].url='https://example.org/new',x=>x.evidenceLedger[0].claim='Another claim']){const copy=structuredClone(d);change(copy);expect(H.appliedReasoningReferenceState(copy,'evidence').current).toBe(false);}d.sourceRecords=[];expect(H.appliedReasoningReferenceState(d,'evidence').current).toBe(false);});
 it('round-trips through backups and typed submissions with no teacher source or unknown media',()=>{const d=base(),resource={id:'r1',type:'applied-challenge',data:d};d.sourceRecords[0].privateImage='SECRET_IMAGE';const json=SR.serializeBackup(resource,SR.responseFromData('applied-challenge',d));expect(json).not.toMatch(/PRIVATE_SOURCE|SECRET_IMAGE/);const restored=SR.readBackup(resource,JSON.parse(json),{});expect(restored.sourceRecords).toEqual(AC.normalize(d).sourceRecords);expect(AC.fromSubmission(d,{r1:{studio:restored}},'r1').data.sourceRecords).toEqual(restored.sourceRecords);try{delete window.AlloModules.AppliedChallenge;expect(SR.toSubmission(resource,restored).data.sourceRecords).toEqual(restored.sourceRecords);}finally{window.AlloModules.AppliedChallenge=AC;}});
 it('includes notes and coverage in bounded feedback, without adding source URLs or fetching links',()=>{const d=base();d.sourceRecords=Array.from({length:24},(_,i)=>source({id:'s'+i,url:'https://example.org/private-path-'+i,reviewNote:'n'.repeat(2000)}));d.workspace.response='r'.repeat(12000);d.workspace.revision='v'.repeat(12000);const before=H.appliedChallengeRequestFingerprint(d,'feedback'),ctx=H.appliedChallengeFeedbackContext(d);expect(ctx.coverage.sourceRecords).toBe(24);expect(ctx.context.studentWork.sourceRecords[23]).toMatchObject({id:'s23',domain:'example.org',claimVerified:false});expect(JSON.stringify(ctx.context)).not.toContain('private-path-');expect(JSON.stringify(ctx.context).length).toBeLessThanOrEqual(90000);d.sourceRecords[0].reviewNote='New findings';expect(H.appliedChallengeRequestFingerprint(d,'feedback')).not.toBe(before);});
 it('escapes source text in response exports and omits sources from blank task copies',()=>{const d=base();d.sourceRecords[0].reviewNote='MY_SOURCE_NOTE <script>';expect(AC.renderPreset(d,'response')).toContain('MY_SOURCE_NOTE &lt;script&gt;');expect(AC.renderPreset(d,'teacher')).toContain('Example Lab');for(const preset of ['task','paper'])expect(AC.renderPreset(d,preset)).not.toContain('MY_SOURCE_NOTE');});
 it('retains source notes in full HTML and its module-free fallback without private source text',()=>{const d=base();d.sourceRecords[0].reviewNote='UNIQUE_SOURCE_NOTE <script>';const pipeline=window.AlloModules.createDocPipeline({callGemini:async()=>'{}',callGeminiVision:async()=>'{}',callImagen:async()=>null,addToast:()=>{},t:key=>key,isRtlLang:()=>false,updateExportPreview:()=>{},getDefaultTitle:()=>'Document',state:{}});const render=()=>pipeline.generateFullPackHTML([{id:'source-export',type:'applied-challenge',data:d}],'Garden',true,{}, {includeTeacherKey:false,annotations:[]});expect(render()).toContain('UNIQUE_SOURCE_NOTE &lt;script&gt;');expect(render()).not.toContain('PRIVATE_SOURCE');try{delete window.AlloModules.AppliedChallenge;expect(render()).toContain('UNIQUE_SOURCE_NOTE &lt;script&gt;');expect(render()).not.toContain('PRIVATE_SOURCE');}finally{window.AlloModules.AppliedChallenge=AC;}});
});
function Harness({data=base(),profile='pass9',runtime=false}){const [responses,setResponses]=React.useState({});latest=responses;return React.createElement(SR.Boundary,{View:window.AlloModules.AppliedChallengeView,generatedContent:{id:'r1',type:'applied-challenge',data},isTeacherMode:false,activeProfileId:profile,studentResponses:responses,studentWorkStatus:'saved',onResponseChange:(id,studio)=>setResponses(old=>({...old,[id]:{studio}})),handleNoteUpdate:vi.fn(),callGemini:null,searchWeb:null,allowRuntimeAi:runtime});}
async function mount(props={}){if(!root){host=document.createElement('div');document.body.appendChild(host);root=createRoot(host);}await act(async()=>root.render(React.createElement(Harness,props)));}
async function click(name){await act(async()=>{const b=[...host.querySelectorAll('button')].find(e=>e.textContent===name||e.getAttribute('aria-label')===name);if(!b)throw Error('Missing '+name);b.click();});}
async function type(selector,text){await act(async()=>{const el=host.querySelector(selector),proto=el.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:el.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,text);el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));});}
describe('Source notebook through the real learner boundary',()=>{
 it('adds a manual source while AI is unavailable, preserving full writing and an unknown date',async()=>{const d=base();d.workspace.evidence='e'.repeat(8000);await mount({data:d});await click('2. Explore');await type('#aps-manual-source-url','https://example.org/manual');await type('#aps-manual-source-title','My own source');await click('Save source link');expect(latest.r1.studio.sourceRecords).toHaveLength(2);const added=latest.r1.studio.sourceRecords[1];expect(added).toMatchObject({url:'https://example.org/manual',foundAt:'',reviewNote:'',rowId:''});expect(latest.r1.studio.workspace.evidence).toHaveLength(8000);expect(document.activeElement.id).toBe('aps-source-note-'+added.id);});
 it('saves citation edits and blank unknown fields without moving them into evidence',async()=>{await mount();await click('2. Explore');await type('#aps-source-note-s','Checked the author; local evidence is still missing.');await type('input[aria-label="Source 1 title"]','');await type('input[aria-label="Source 1 author or organization"]','My Organization ');expect(latest.r1.studio.sourceRecords[0]).toMatchObject({title:'',author:'My Organization ',reviewNote:'Checked the author; local evidence is still missing.'});expect(latest.r1.studio.evidenceLedger[0].evidence).toBe('My reasoning.');});
 it('removes a source, focuses Undo, and restores its note and exact connection',async()=>{await mount();await click('2. Explore');await click('Remove source 1');expect(latest.r1.studio.sourceRecords).toEqual([]);expect(document.activeElement.id).toBe('aps-undo');await act(async()=>host.querySelector('#aps-undo').click());expect(latest.r1.studio.sourceRecords[0]).toEqual(source());expect(document.activeElement.id).toBe('aps-source-note-s');});
 it('keeps the source when its evidence row is removed and allows reconnection',async()=>{await mount();await click('2. Explore');const remove=[...host.querySelectorAll('button')].find(b=>b.textContent.startsWith('Remove evidence row'));expect(remove).toBeTruthy();await act(async()=>remove.click());expect(latest.r1.studio.sourceRecords[0].rowId).toBe('r');expect(host.textContent).toContain('original evidence row was removed');await type('select[aria-label="Source 1 connection"]','');expect(latest.r1.studio.sourceRecords[0].rowId).toBe('');});
 it('keeps unfinished manual-link drafts across stages, but clears them for another profile',async()=>{await mount();await click('2. Explore');await type('#aps-manual-source-url','https://example.org/draft');await click('3. Build');await click('2. Explore');expect(host.querySelector('#aps-manual-source-url').value).toBe('https://example.org/draft');await click('3. Build');await mount({profile:'another'});await click('2. Explore');expect(host.querySelector('#aps-manual-source-url').value).toBe('');});
 it('returns from final review to the exact source note',async()=>{await mount();await click('5. Reflect');await click('Review my response');expect(host.textContent).toContain(source().reviewNote);await click('Edit source 1');expect(document.activeElement.id).toBe('aps-source-note-s');await type('#aps-source-note-s','Revised check.');await click('Return to my review');expect(host.textContent).toContain('Revised check.');});
});
