import { beforeAll, afterEach, describe, it, expect, vi } from 'vitest';
import { createRequire } from 'node:module';
import { loadAlloModule } from './setup.js';
const require = createRequire(import.meta.url);
const React = require('../desktop/web-app/node_modules/react');
const { createRoot } = require('../desktop/web-app/node_modules/react-dom/client');
const { act } = React;
let root, host, api;
const t = (key, options) => options?.defaultValue || ({'common.start_game':'Games','quiz.presentation':'Present questions','quiz.presentation_board':'Presentation board','quiz.presentation_discussion':'Class discussion','quiz.reveal_answer':'Reveal answer','quiz.hide_answer':'Hide answer','quiz.review_game':'Review game'}[key]) || key;
const questions = [
  {type:'mcq', question:'What does the diagram show?',imageUrl:'question.png',imageAltText:'A growing plant',options:['Growth','Sleep'],optionImageUrls:['growth.png','sleep.png'],optionImageAltTexts:['A seedling','A closed flower'],correctAnswer:'Growth'},
  {type:'numeric-response',question:'How many leaves?',correctValue:4,imageUrl:'leaves.png',imageAltText:'Four leaves',unit:'leaves'},
];
function base(extra={}) { return {t,isTeacherMode:false,isParentMode:false,isIndependentMode:true,studentProjectSettings:{},activeSessionCode:null,sessionData:{},isPresentationMode:false,isReviewGame:false,isEditingQuiz:false,escapeRoomState:{isActive:false},presentationState:{},reviewGameState:{},isFactChecking:{},showQuizAnswers:false,leveledTextLanguage:'English',generatedContent:{id:'assess-ui',data:{questions}},formatInlineText:value=>value,renderFormattedText:value=>value,getReviewCategories:()=>[],getRows:()=>1,playSound:()=>{},handleToggleIsPresentationMode:vi.fn(),handleToggleIsReviewGame:vi.fn(),resetPresentation:vi.fn(),...extra}; }
beforeAll(()=>{global.React=window.React=React;global.IS_REACT_ACT_ENVIRONMENT=true;window.AlloLanguageContext=React.createContext({t});window.__alloT=t;window.AlloIcons={};loadAlloModule('view_quiz_module.js');api=window.AlloModules;});
afterEach(async()=>{if(root)await act(async()=>root.unmount());host?.remove();root=host=null;localStorage.clear();vi.restoreAllMocks();delete api.LessonBoardSetup;delete api.ConnectedEscapeRoomSetup;});
async function render(props){if(!root){host=document.createElement('div');document.body.append(host);root=createRoot(host);}await act(async()=>root.render(React.createElement(api.QuizView,{ErrorBoundary:({children})=>children,TeacherLiveQuizControls:()=>null,ConfettiExplosion:()=>null,Stamp:()=>null,...props})));}
const button=text=>[...host.querySelectorAll('button')].find(el=>el.textContent.trim()===text);
async function click(el){expect(el).toBeTruthy();await act(async()=>el.click());}
describe('Assess games disclosure',()=>{
  it('starts compact, opens the game choices, and closes with Escape returning focus',async()=>{await render(base());const toggle=host.querySelector('[data-quiz-games-toggle]');expect(toggle.getAttribute('aria-expanded')).toBe('false');expect(host.querySelector('[data-open-lesson-board]')).toBeNull();await click(toggle);expect(toggle.getAttribute('aria-expanded')).toBe('true');expect(host.querySelector('[data-open-lesson-board]')).toBeTruthy();host.querySelector('[data-open-connected-room]').focus();await act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(host.querySelector('#quiz-games-tools')).toBeNull();expect(document.activeElement).toBe(toggle);});
  it('launches review from Games and keeps the exit control visible outside the menu',async()=>{const props=base();await render(props);await click(host.querySelector('[data-quiz-games-toggle]'));await click(host.querySelector('[data-quiz-game="review"]'));expect(props.handleToggleIsReviewGame).toHaveBeenCalledTimes(1);expect(host.querySelector('#quiz-games-tools')).toBeNull();await render({...props,isReviewGame:true,gameTeams:[],reviewGameState:{claimed:new Set()}});expect(button('Exit review game')).toBeTruthy();await click(button('Exit review game'));expect(props.handleToggleIsReviewGame).toHaveBeenCalledTimes(2);});
  it('opens the two separate setups and closes the disclosure before launch',async()=>{api.LessonBoardSetup=()=>React.createElement('div',{'data-board-ready':true},'Board setup');api.ConnectedEscapeRoomSetup=()=>React.createElement('div',{'data-room-ready':true},'Room setup');await render(base());await click(host.querySelector('[data-quiz-games-toggle]'));await click(host.querySelector('[data-open-lesson-board]'));expect(host.querySelector('[data-board-ready]')).toBeTruthy();expect(host.querySelector('#quiz-games-tools')).toBeNull();});
  it('prevents starting a competing game while a live quiz is running',async()=>{await render(base({isTeacherMode:true,activeSessionCode:'LIVE',sessionData:{quizState:{isActive:true},roster:{}}}));await click(host.querySelector('[data-quiz-games-toggle]'));expect([...host.querySelectorAll('#quiz-games-tools button')].every(el=>el.disabled)).toBe(true);});
});
describe('Assess presentation clarity',()=>{
  const presenter=extra=>base({isTeacherMode:true,isIndependentMode:false,isPresentationMode:true,...extra});
  it('starts one question at a time, includes images, and selects neutrally without grading or submission',async()=>{const choose=vi.fn(),submit=vi.fn(),props=presenter({handlePresentationOptionClick:choose,onSubmitLiveAnswer:submit});await render(props);expect(host.textContent).toContain('Question 1 of 2');expect(host.querySelectorAll('[data-presentation-question-type]')).toHaveLength(1);expect(host.querySelector('img[alt="A growing plant"]')).toBeTruthy();expect(host.querySelector('img[alt="A seedling"]')).toBeTruthy();const option=[...host.querySelectorAll('button')].find(el=>el.textContent.includes('A.Growth'));await click(option);expect(option.getAttribute('aria-pressed')).toBe('true');expect(option.className).not.toMatch(/green|red-/);expect(button('Reveal answer')).toBeTruthy();expect(choose).not.toHaveBeenCalled();expect(submit).not.toHaveBeenCalled();await click(button('Next question'));expect(host.textContent).toContain('Question 2 of 2');expect(host.querySelector('img[alt="Four leaves"]')).toBeTruthy();expect(button('Next question').disabled).toBe(true);await click(button('Previous question'));expect(host.querySelector('[data-presentation-question-type="mcq"]')).toBeTruthy();});
  it('reveals only explicitly, retains a reveal within the same presentation, and hides every guide on demand',async()=>{await render(presenter());await click([...host.querySelectorAll('button')].find(el=>el.textContent.includes('A.Growth')));await click(button('Reveal answer'));expect([...host.querySelectorAll('button[aria-pressed="true"]')].find(el=>el.textContent.includes('Growth')).className).toContain('green');await click(button('Next question'));await click(button('Reveal answer guide'));await click(button('Previous question'));expect(button('Hide answer')).toBeTruthy();await click(button('Show all questions'));expect(host.querySelectorAll('[data-presentation-question-type]')).toHaveLength(2);expect(host.querySelector('[data-presentation-visibility]').textContent).toContain('2');await click(host.querySelector('[data-presentation-hide-guides]'));expect(button('Reveal answer')).toBeTruthy();expect(button('Reveal answer guide')).toBeTruthy();expect(host.querySelector('[data-presentation-visibility]').textContent).toContain('are hidden');});
  it('shows discussion after the final question only when prompts exist',async()=>{await render(presenter());expect(host.textContent).not.toContain('Class discussion');await render(presenter({generatedContent:{id:'reflection',data:{questions,reflections:['What changed?']}}}));expect(host.textContent).not.toContain('What changed?');await click(button('Next question'));expect(host.textContent).toContain('What changed?');});
  it('resets both reveals and navigation without calling the legacy grading callback',async()=>{const props=presenter();await render(props);expect(button('Exit presentation').getAttribute('aria-pressed')).toBe('true');await click(button('Next question'));await click(button('Reveal answer guide'));await click(host.querySelector('[aria-label="common.reset_presentation"]'));expect(props.resetPresentation).not.toHaveBeenCalled();expect(host.textContent).toContain('Question 1 of 2');expect(host.querySelector('[data-presentation-visibility]').textContent).toContain('are hidden');});
});
