import {it,expect,vi} from 'vitest';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),React=require(path.resolve('desktop/web-app/node_modules/react'));const win={React,AlloModules:{}};new Function('window',fs.readFileSync('catalog_module.js','utf8'))(win);const { _fetchCatalogLesson:fetchLesson,_parseCatalogLesson:parseLesson }=win.AlloModules.CommunityCatalog;
const entry={path:'allopacks/test.allopack.json'},pack={allopack:{spec:'0.1'},history:[{id:'reading',type:'simplified',title:'Read',data:'Water moves.',meta:''}]};
it('never reads or saves an HTTP error response as a lesson',async()=>{const text=vi.fn(async()=>JSON.stringify({error:'missing'}));await expect(fetchLesson(entry,async()=>({ok:false,status:404,text}))).rejects.toThrow('HTTP 404');expect(text).not.toHaveBeenCalled();});
it('accepts a BOM-prefixed successful response and preserves its payload',async()=>{expect(await fetchLesson(entry,async()=>({ok:true,text:async()=>'\uFEFF'+JSON.stringify(pack)}))).toEqual(pack);});
it('reports invalid JSON clearly',async()=>{await expect(fetchLesson(entry,async()=>({ok:true,text:async()=>'<html>error</html>'}))).rejects.toThrow('not valid JSON');});
it.each([null,[],{error:'server error'},{allopack:{},history:[]},{allopack:{},history:{}}])('rejects invalid AlloPack envelopes: %j',bad=>{expect(()=>parseLesson(bad,entry)).toThrow();});
it.each([{id:'',type:'quiz',title:'Quiz',data:{}},{id:'a',type:'quiz',title:'Quiz',data:null},{id:'a',type:'quiz',title:'Quiz',data:{},meta:{}}])('rejects malformed resource envelopes: %j',row=>{expect(()=>parseLesson({...pack,history:[row]},entry)).toThrow('invalid or duplicate');});
it('rejects duplicate IDs',()=>{expect(()=>parseLesson({...pack,history:[pack.history[0],pack.history[0]]},entry)).toThrow('duplicate');});
it('unwraps approved submissions while preserving valid raw legacy lessons',()=>{const lesson={title:'World',world:{name:'Test'}};expect(parseLesson({lesson_payload:lesson},{path:'catalog/approved/test.json'})).toBe(lesson);expect(parseLesson(lesson,{path:'catalog/approved/test.json'})).toBe(lesson);expect(()=>parseLesson({lesson_payload:null},{path:'catalog/approved/test.json'})).toThrow();});
it('passes abort signals to fetch',async()=>{const controller=new AbortController();controller.abort();const fetcher=vi.fn(async(url,options)=>{expect(options.signal).toBe(controller.signal);throw new DOMException('Aborted','AbortError');});await expect(fetchLesson(entry,fetcher,controller.signal)).rejects.toThrow('Aborted');});
it('accepts every current pack without rewriting resource or artwork fields',()=>{for(const dir of ['allopacks','allopacks/illustrated'])for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.allopack.json'))){const p=JSON.parse(fs.readFileSync(dir+'/'+f,'utf8').replace(/^\uFEFF/,''));expect(parseLesson(p,{path:dir+'/'+f})).toBe(p);}});

const parseManifest=win.AlloModules.CommunityCatalog._parseCatalogManifest;
it.each([null,{}, {entries:[null]}, {entries:[{slug:'a',path:'a.json',tags:'invalid'}]}, {entries:[{slug:'a',path:'a.json',title:{}}]}])('rejects malformed manifest entries before rendering: %j',bad=>{expect(()=>parseManifest(bad)).toThrow();});
it('rejects duplicate manifest identities and accepts the actual manifest',()=>{const row={slug:'a',path:'a.json'};expect(()=>parseManifest({entries:[row,row]})).toThrow('duplicate');const data=JSON.parse(fs.readFileSync('catalog/index.json','utf8'));expect(parseManifest(data)).toBe(data.entries);});
