import {beforeEach,describe,expect,it} from 'vitest';
import {loadTool,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
let api;
const amp=(timing={},extra={})=>({id:2,type:'opamp',a:'B',b:'0',value:100000,control:{positive:'A',negative:'B'},opamp:{lower:-5,upper:5,timing:{enabled:true,gbw:1000,slew:1,initial:0,...timing}},...extra});
const design=(input=1,timing={})=>({duration:.003,components:[{id:1,type:'voltage',a:'A',b:'0',value:input},amp(timing),{id:3,type:'resistor',a:'B',b:'0',value:1000}]});
const out=(f,id=2)=>f.rows.find(r=>r.component.id===id);
const check=run=>{expect(run.ok,run.message).toBe(true);for(const f of run.frames){for(const b of f.balances)if(b.current!=null)expect(Math.abs(b.current)).toBeLessThan(1e-8);expect(f.absorbed).toBeCloseTo(f.delivered,7);}};
beforeEach(()=>{resetStemLab();loadTool('stem_lab/stem_tool_circuit.js','circuit');api=window.StemLab;});
describe('op-amp bandwidth and slew dynamics',()=>{
 it('normalizes timing limits without enabling old designs or mutating input',()=>{const raw=amp({gbw:Infinity,slew:-1,initial:90}),saved=JSON.stringify(raw),p=api.circuitNetworkDesign({components:[raw]}).components[0];expect(p.opamp.model).toBe('dominant-pole-slew');expect(p.opamp.timing).toEqual({enabled:true,gbw:1000000,slew:.000001,initial:24});expect(JSON.stringify(raw)).toBe(saved);expect(api.circuitNetworkOpAmpTiming({type:'opamp'}).enabled).toBe(false);});
 it('keeps the DC solution independent of timing and starting output',()=>{const d=design(2,{gbw:10,slew:.000001,initial:4}),s=api.solveNetworkCircuit(d);expect(s.ok).toBe(true);expect(out(s).voltage).toBeCloseTo(2*100000/100001,9);expect(out(s).opampTimingActive).toBe(false);expect(out(s).opampRate).toBeNull();});
 it.each([10,1000,1000000])('matches a follower startup at GBW %s Hz',gbw=>{const A=100000,k=A/(A+1),tau=A/((A+1)*2*Math.PI*gbw),d=design(1,{gbw,slew:1000});d.duration=Math.max(.000001,8*tau);const run=api.circuitNetworkTransient(d);check(run);expect(out(run.frames[0]).voltage).toBe(0);for(const f of run.frames)expect(Math.abs(out(f).voltage-k*(1-Math.exp(-f.time/tau)))).toBeLessThan(.001);expect(run.frames.length).toBeGreaterThan(100);});
 it.each([1,10])('matches sinusoidal amplitude and phase for noise gain %s',gain=>{const A=100000,gbw=1000,freq=gbw/gain,k=A/(1+A/gain),tau=A/(2*Math.PI*gbw*(1+A/gain)),w=2*Math.PI*freq,d=design(0,{gbw,slew:10});d.duration=3/freq;d.components[0].waveform={shape:'sine',frequency:freq,amplitude:.1};if(gain!==1){d.components[1].control.negative='C';d.components.push({id:4,type:'resistor',a:'B',b:'C',value:9000},{id:5,type:'resistor',a:'C',b:'0',value:1000});}const run=api.circuitNetworkTransient(d);check(run);for(const f of run.frames){const expected=.1*k/(1+(w*tau)**2)*(Math.sin(w*f.time)-w*tau*Math.cos(w*f.time)+w*tau*Math.exp(-f.time/tau));expect(Math.abs(out(f).voltage-expected)).toBeLessThan(.002);}expect(run.frames.some(f=>out(f).opampRegion==='tracking')).toBe(true);});
 it.each([3,-3])('matches a slew-limited step of %s V, including its settling tail',level=>{const A=100000,gbw=1000,slew=.001,rate=slew*1e6,lambda=2*Math.PI*gbw*(A+1)/A,target=Math.abs(level)*A/(A+1),transition=(target-rate/lambda)/rate,d=design(level,{gbw,slew});d.duration=.006;const run=api.circuitNetworkTransient(d);check(run);for(let i=0;i<run.frames.length;i++){const f=run.frames[i],expected=Math.sign(level)*(f.time<transition?rate*f.time:target-rate/lambda*Math.exp(-lambda*(f.time-transition)));expect(Math.abs(out(f).voltage-expected)).toBeLessThan(.003);expect(Math.abs(out(f).opampRate)).toBeLessThanOrEqual(rate+1e-6);if(i){const before=run.frames[i-1];expect(Math.abs(out(f).voltage-out(before).voltage)).toBeLessThanOrEqual(rate*(f.time-before.time)+1e-7);}}expect(run.frames.some(f=>out(f).opampRegion===(level>0?'slew-up':'slew-down'))).toBe(true);expect(run.frames.every(f=>f.storedEnergy===0)).toBe(true);});
 it('matches an independent small-step RK4 reference for a slew-distorted sine',()=>{const d=design(0,{gbw:1000000,slew:.02});d.duration=.0015;d.components[0].waveform={shape:'sine',amplitude:3,frequency:2000};const run=api.circuitNetworkTransient(d);check(run);let t=0,y=0;const A=100000,tau=A/(2*Math.PI*1000000),derivative=(time,value)=>Math.max(-20000,Math.min(20000,(A*(3*Math.sin(4000*Math.PI*time)-value)-value)/tau));for(const frame of run.frames){while(t<frame.time-1e-16){const dt=Math.min(5e-8,frame.time-t),k1=derivative(t,y),k2=derivative(t+dt/2,y+k1*dt/2),k3=derivative(t+dt/2,y+k2*dt/2),k4=derivative(t+dt,y+k3*dt);y+=dt/6*(k1+2*k2+2*k3+k4);t+=dt;}expect(Math.abs(out(frame).voltage-y)).toBeLessThan(.012);}expect(run.frames.some(f=>out(f).opampRegion==='slew-up')).toBe(true);expect(run.frames.some(f=>out(f).opampRegion==='slew-down')).toBe(true);});
 it('holds output within both voltage limits while respecting the slew bound',()=>{const d=design(0,{gbw:10000,slew:.005});d.duration=.03;d.components[0].waveform={shape:'sine',amplitude:10,frequency:100};const run=api.circuitNetworkTransient(d);check(run);expect(run.frames.some(f=>out(f).opampRegion==='upper')).toBe(true);expect(run.frames.some(f=>out(f).opampRegion==='lower')).toBe(true);for(const f of run.frames){expect(out(f).voltage).toBeLessThanOrEqual(5+1e-8);expect(out(f).voltage).toBeGreaterThanOrEqual(-5-1e-8);if(out(f).opampRegion==='upper'||out(f).opampRegion==='lower')expect(out(f).opampRate).toBe(0);}});
 it('uses a configured starting output only in time response',()=>{const d=design(1,{initial:2}),run=api.circuitNetworkTransient(d);check(run);expect(out(run.frames[0]).voltage).toBe(2);expect(out(run.frames.at(-1)).voltage).toBeCloseTo(100000/100001,5);expect(api.solveNetworkCircuit(d).rows[1].voltage).toBeCloseTo(100000/100001,8);});
 it('rejects an out-of-window starting output without silently clipping it',()=>{const d=design(1,{initial:8}),run=api.circuitNetworkTransient(d);expect(run.ok).toBe(false);expect(run.frames).toEqual([]);expect(run.message).toContain('starting or carried output');expect(api.solveNetworkCircuit(d).ok).toBe(true);expect(()=>api.circuitNetworkTransientCSV(d,run)).toThrow();});
 it('preserves output across an exact switch event and changes its slope',()=>{const d={duration:.003,components:[{id:1,type:'voltage',a:'A',b:'0',value:3},{id:2,type:'resistor',a:'A',b:'C',value:1000},{id:3,type:'resistor',a:'C',b:'0',value:1000},{id:4,type:'switch',a:'C',b:'0',closed:false,switching:{enabled:true,events:[{id:1,time:.001,closed:true}]}},amp({gbw:1000,slew:.01},{id:5,control:{positive:'C',negative:'B'}}),{id:6,type:'resistor',a:'B',b:'0',value:1000}]},run=api.circuitNetworkTransient(d);check(run);const before=api.circuitNetworkFrame(run,.001,'before'),after=api.circuitNetworkFrame(run,.001,'after');expect(out(before,5).voltage).toBe(out(after,5).voltage);expect(out(before,5).opampRate).toBeGreaterThan(0);expect(out(after,5).opampRate).toBeLessThan(0);expect(out(after,5).opampStepRate).toBeNull();const f=api.circuitNetworkFrame(run,.0015);expect(out(f,5).voltage).toBeCloseTo(out(after,5).voltage*Math.exp(-2*Math.PI*1000*(100001/100000)*(f.time-.001)),2);});
 it('retains explicit timing settings when disabled and restores algebraic behavior',()=>{const d=design(2,{enabled:false,initial:4}),p=api.circuitNetworkDesign(d).components[1],run=api.circuitNetworkTransient(d);expect(p.opamp.timing.initial).toBe(4);expect(p.opamp.model).toBe('finite-gain-clamp');check(run);expect(run.frames.length).toBe(2);expect(out(run.frames[0]).voltage).toBeCloseTo(2*100000/100001,9);});
 it('exports timing settings, active mode and actual integration slope in SI units',()=>{const d=design(3,{slew:.001}),run=api.circuitNetworkTransient(d),lines=api.circuitNetworkTransientCSV(d,run).split('\n'),header=lines[0].split(','),records=lines.slice(1).filter(l=>l.split(',')[1]==='U2').map(l=>Object.fromEntries(l.split(',').map((v,i)=>[header[i],v])));expect(records[0].opamp_starting_output_V).toBe('0');expect(records[0].opamp_step_slope_V_per_s).toBe('');expect(records[1].method).toBe('backward_euler_step_doubling');expect(records[1].absolute_state_tolerance).toBe('1e-7');expect(records[1].opamp_timing_active).toBe('true');expect(records[1].opamp_gbw_Hz).toBe('1000');expect(Number(records[1].opamp_step_slope_V_per_s)).toBeCloseTo(1000,5);});
 it('drives an external capacitor while preserving its actual energy and charge current',()=>{const d=design(1,{gbw:1000,slew:1});d.components.push({id:4,type:'capacitor',a:'B',b:'0',value:1});const run=api.circuitNetworkTransient(d);check(run);for(const f of run.frames.slice(1)){const ampRow=out(f),cap=out(f,4);expect(cap.voltage).toBeCloseTo(ampRow.voltage,9);expect(cap.current).toBeCloseTo(ampRow.opampStepRate*1e-6,8);expect(cap.energy).toBeCloseTo(.5e-6*ampRow.voltage**2,12);expect(ampRow.energy).toBe(0);}});
 it('combines timed and idealized amplifiers in one connected solve',()=>{const d=design(1);d.components.push({...amp(),id:4,a:'C',control:{positive:'B',negative:'0'},value:2,opamp:{lower:-5,upper:5}},{id:5,type:'resistor',a:'C',b:'0',value:1000});const run=api.circuitNetworkTransient(d);check(run);for(const f of run.frames){expect(out(f,4).voltage).toBeCloseTo(2*out(f).voltage,9);expect(out(f,4).opampTimingActive).toBe(false);}});
 it('retains floating differential output state without inventing an absolute reference',()=>{const d=design(.1,{gbw:100,slew:1});d.duration=.1;d.components[1].a='C';d.components[1].b='D';d.components[1].value=10;d.components[1].control={positive:'A',negative:'0'};d.components[2].a='C';d.components[2].b='D';const run=api.circuitNetworkTransient(d);check(run);for(const f of run.frames){expect(f.difference('C','0')).toBeNull();expect(Math.abs(f.difference('C','D')-(1-Math.exp(-f.time*2*Math.PI*100/10)))).toBeLessThan(.001);}});

});
