import {afterEach,beforeAll,describe,it,expect} from 'vitest';
import {React,ReactDOMClient,loadTool,makeCtx,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let cfg,mounted;
const box=extra=>({shape:'box',size:[1,2,.5],position:[1,.5,-1],rotation:[0,0,0],color:'#60a5fa',group:'Pair',...extra});
beforeAll(()=>{resetStemLab();cfg=loadTool('stem_lab/stem_tool_geosandbox.js','geoSandbox');});
afterEach(()=>{if(mounted){React.act(()=>mounted.root.unmount());mounted.container.remove();mounted=null;}});
function mount(parts=[box()],bucket={}){const container=document.createElement('div');document.body.appendChild(container);const v={container,root:ReactDOMClient.createRoot(container)};function Host(){const[data,setData]=React.useState({_threeLoaded:true,geoSandbox:{mode:'sculpt',sculptRecipe:{parts},...bucket}});v.state=data.geoSandbox;return cfg.render(makeCtx({toolData:data,setToolData:setData}));}mounted=v;React.act(()=>v.root.render(React.createElement(Host)));click(container.querySelector('#geo-sculpt-tab-edit'));return v;}
function click(el){expect(el).toBeTruthy();React.act(()=>el.click());}
function field(label){const el=mounted.container.querySelector('[aria-label="'+label+'"]');expect(el).toBeTruthy();return el;}
function value(el,v,blur=false){React.act(()=>{const proto=el.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,String(v));el.dispatchEvent(new window.Event('input',{bubbles:true}));el.dispatchEvent(new window.Event('change',{bubbles:true}));if(blur)el.dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}));});}
function history(name){click([...mounted.container.querySelectorAll('button')].find(el=>el.textContent.trim()===name));}


function project(){click(mounted.container.querySelector('#geo-sculpt-tab-project'));}
function button(name){return [...mounted.container.querySelectorAll('button')].find(b=>b.textContent.trim()===name);}
describe('Sculpt project layout',()=>{
 it('places one Save and copy action beside the title, before the gallery and collapsed tools',()=>{const v=mount();project();const card=v.container.querySelector('.geo-save-status'),library=v.container.querySelector('.geo-project-library');expect(card.contains(field('Save this sculpt'))).toBe(true);expect(card.contains(button('Save a copy'))).toBe(true);expect(card.contains(field('Sculpture title'))).toBe(true);expect(v.container.querySelectorAll('[aria-label="Save this sculpt"]')).toHaveLength(1);expect(card.compareDocumentPosition(library)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect([...v.container.querySelectorAll('.geo-sculpt-project details')].every(d=>!d.open)).toBe(true);});
 it('saves an edited title and makes an independent named copy',()=>{const v=mount();project();value(field('Sculpture title'),'  New study  ',true);click(field('Save this sculpt'));expect(v.state.savedSculpts['New study'].name).toBe('New study');click(button('Save a copy'));expect(Object.keys(v.state.savedSculpts)).toEqual(['New study','New study 2']);expect(v.container.querySelector('.geo-save-status p').textContent).toContain('“New study 2”');});
 it('restores the committed title when an empty draft loses focus',()=>{const v=mount(undefined,{sculptRecipe:{name:'Original',parts:[box()]}});project();value(field('Sculpture title'),'  ',true);expect(field('Sculpture title').value).toBe('Original');expect(v.state.sculptRecipe.name).toBe('Original');});
 it('cancels a title draft with Escape without an undo entry',()=>{const v=mount(undefined,{sculptRecipe:{name:'Original',parts:[box()]}});project();const title=field('Sculpture title');React.act(()=>title.focus());value(title,'Discard me');React.act(()=>title.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(title.value).toBe('Original');expect(v.state.sculptRecipe.name).toBe('Original');expect(button('↶ Undo').disabled).toBe(true);});
 it('commits a title with Enter and supports Undo',()=>{const v=mount(undefined,{sculptRecipe:{name:'Original',parts:[box()]}});project();const title=field('Sculpture title');React.act(()=>title.focus());value(title,'Updated');React.act(()=>title.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true})));expect(v.state.sculptRecipe.name).toBe('Updated');history('↶ Undo');expect(field('Sculpture title').value).toBe('Original');});
 it('keeps the import and export actions in the file disclosure',()=>{const v=mount();project();const files=v.container.querySelector('.geo-project-files');expect(files.contains(field('Import sculpture'))).toBe(true);expect(files.contains(button('Export sculpture'))).toBe(true);click(button('Continue editing'));expect(v.container.querySelector('#geo-sculpt-tab-edit').getAttribute('aria-selected')).toBe('true');});
});
