import {afterEach,beforeAll,describe,it,expect} from 'vitest';
import {React,ReactDOMClient,loadTool,makeCtx,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let cfg,mounted;
const box=extra=>({shape:'box',size:[1,1,1],position:[0,.5,0],rotation:[0,0,0],color:'#60a5fa',group:'Pair',...extra});
beforeAll(()=>{resetStemLab();cfg=loadTool('stem_lab/stem_tool_geosandbox.js','geoSandbox');});
afterEach(()=>{if(mounted){React.act(()=>mounted.root.unmount());mounted.container.remove();mounted=null;}});
function mount(parts,bucket={}){const container=document.createElement('div');document.body.appendChild(container);const v={container,root:ReactDOMClient.createRoot(container)};function Host(){const[data,setData]=React.useState({_threeLoaded:true,geoSandbox:{mode:'sculpt',sculptRecipe:{parts},...bucket}});v.state=data.geoSandbox;return cfg.render(makeCtx({toolData:data,setToolData:setData}));}mounted=v;React.act(()=>v.root.render(React.createElement(Host)));click(container.querySelector('#geo-sculpt-tab-edit'));return v;}
function click(el){expect(el).toBeTruthy();React.act(()=>el.click());}
function field(label){const el=mounted.container.querySelector('[aria-label="'+label+'"]');expect(el).toBeTruthy();return el;}
function value(el,v,blur=false){React.act(()=>{const proto=el.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,String(v));el.dispatchEvent(new window.Event('input',{bubbles:true}));el.dispatchEvent(new window.Event('change',{bubbles:true}));if(blur)el.dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}));});}
function history(name){click([...mounted.container.querySelectorAll('button')].find(el=>el.textContent.trim()===name));}
function group(){click(mounted.container.querySelector('#geo-sculpt-section-position input[type=checkbox]'));}
describe('Precise Sculpt movement',()=>{
 it('translates grouped coordinates in displayed units and preserves relative placement',()=>{const v=mount([box(),box({position:[1,1.5,1],rotation:[10,20,30]}),box({group:'Other'})],{sculptRecipe:{scale:2,parts:[box(),box({position:[1,1.5,1],rotation:[10,20,30]}),box({group:'Other'})]}});group();value(field('Local position X (u)'),2.6,true);expect(v.state.sculptRecipe.parts.map(p=>p.position[0])).toEqual([.5,1.5,0]);expect(v.state.sculptRecipe.parts[1].rotation).toEqual([10,20,30]);history('↶ Undo');expect(v.state.sculptRecipe.parts.map(p=>p.position[0])).toEqual([0,1,0]);history('Redo');expect(v.state.sculptRecipe.parts[1].position[0]).toBe(1.5);});
 it('refuses an exact group move outside shared bounds and restores the field without losing Redo',()=>{const v=mount([box(),box({position:[3.9,.5,0]})]);group();value(field('Local position Y (u)'),2.6,true);history('↶ Undo');const before=JSON.stringify(v.state.sculptRecipe);value(field('Local position X (u)'),2.6,true);expect(JSON.stringify(v.state.sculptRecipe)).toBe(before);expect(field('Local position X (u)').value).toBe('0');expect(v.container.querySelector('.geo-status').textContent).toContain('outside the workspace');history('Redo');expect(v.state.sculptRecipe.parts[0].position[1]).toBe(1);});
 it('blocks group movement when a member is locked and allows selected-only movement after scope changes',()=>{const v=mount([box(),box({locked:true,position:[1,.5,0]})]);group();expect(field('Local position X (u)').disabled).toBe(true);expect(field('Move x positive').disabled).toBe(true);React.act(()=>window._geoNudgeSculptPart('x',1));expect(v.state.sculptRecipe.parts[0].position[0]).toBe(0);group();value(field('Local position X (u)'),2.6,true);expect(v.state.sculptRecipe.parts.map(p=>p.position[0])).toEqual([1,1]);});
 it('uses a custom step for both buttons and the published handle path',()=>{const v=mount([box()]);value(field('Move step'),'custom');value(field('Custom move step (u)'),.075,true);expect(v.state.sculptStep).toBe(.075);click(field('Move x positive'));expect(v.state.sculptRecipe.parts[0].position[0]*2.6).toBeCloseTo(.075,10);React.act(()=>window._geoNudgeSculptPart('x',1));expect(v.state.sculptRecipe.parts[0].position[0]*2.6).toBeCloseTo(.15,10);history('↶ Undo');expect(v.state.sculptRecipe.parts[0].position[0]*2.6).toBeCloseTo(.075,10);});
 it('keeps step drafts and invalid values out of movement settings',()=>{const v=mount([box()]);value(field('Move step'),'custom');value(field('Custom move step (u)'),.125);expect(v.state.sculptStep).toBeUndefined();value(field('Custom move step (u)'),0,true);expect(v.state.sculptStep).toBeUndefined();expect(field('Custom move step (u)').value).toBe('0.5');value(field('Move step'),'0.25');expect(v.state.sculptStep).toBe(.25);expect(v.container.querySelector('[aria-label="Custom move step (u)"]')).toBeNull();});
 it('keeps exact edits to the selected part when group movement is off',()=>{const v=mount([box(),box({position:[1,.5,0]})]);value(field('Local position Z (u)'),1.3,true);expect(v.state.sculptRecipe.parts.map(p=>p.position[2])).toEqual([.5,0]);});
});
