import { beforeEach, afterEach, describe, it, expect, vi } from 'vitest';
import { React, ReactDOMClient, loadTool, makeCtx, resetStemLab } from './helpers/stem_widgets_smoke_harness.js';
let root;
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);resetStemLab();document.body.innerHTML='<div id="root"></div>';loadTool('stem_lab/stem_tool_money.js','moneyMath');});
afterEach(async()=>{if(root)await React.act(()=>root.unmount());root=null;vi.restoreAllMocks();vi.unstubAllGlobals();});
const core=()=>window.MoneyMathLearning;
const cats=(pcts)=>pcts.map((pct,index)=>({name:['Housing','Food','Transport','Education','Entertainment','Savings','Other'][index]||'Category '+index,pct}));
async function mount(patch={}){let latest;const awardXP=vi.fn(),callGemini=vi.fn();function App(){const[state,setState]=React.useState({_moneyMath:{tab:'budget',currency:'USD',grade:'elementary',...patch}});latest=state;return window.StemLab._registry.moneyMath.render(makeCtx({toolData:state,setToolData:setState,awardXP,callGemini}));}root=ReactDOMClient.createRoot(document.getElementById('root'));await React.act(()=>root.render(React.createElement(App)));return {state:()=>latest._moneyMath,awardXP,callGemini};}
const panel=()=>document.getElementById('money-tool-panel');
async function click(name){const el=[...panel().querySelectorAll('button')].find(b=>b.textContent.trim()===name);expect(el,name).toBeTruthy();await React.act(()=>el.click());}
async function input(el,value){expect(el).toBeTruthy();await React.act(()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});return el;}
const income=()=>panel().querySelector('input[aria-label="Monthly income"]');
const transferPoints=()=>panel().querySelector('[data-budget-tradeoff] input');
async function select(el,value){await React.act(()=>{el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));});}
describe('budget allocation arithmetic and visual scale',()=>{
  it.each([[100,[30,20,15,10,10,10,5],100],[0.01,[30,20,15,10,10,10,5],100],[1,[30,20,15,10,10,10,5],1],[0.07,[33,33,34],100],[199.99,[25,25,25],100],[0,[100,100],100],[100,[50,50,25],100],[1000000,[100,100,100,100,100,100,100],1]])('reconciles displayed money and strips for %s',(value,pcts,scale)=>{const m=core().budgetModel(value,pcts,scale);expect(m.ok).toBe(true);expect(m.units.reduce((a,b)=>a+b,0)).toBe(m.allocated);expect(m.allocated+m.left).toBe(m.incomeUnits);expect(m.tapes.flat().reduce((sum,s)=>sum+s.width,0)).toBe(m.used);expect(m.tapes.every(t=>t.reduce((sum,s)=>sum+s.width,0)<=100)).toBe(true);for(let i=0;i<pcts.length;i++)expect(m.tapes.flat().filter(s=>s.index===i).reduce((sum,s)=>sum+s.width,0)).toBe(pcts[i]);});
  it('retains a full income plus an unnormalized 25% excess',()=>{expect(core().budgetModel(100,[50,50,25],100).tapes).toEqual([[{index:0,width:50},{index:1,width:50}],[{index:2,width:25}]]);});
  it('assigns a single cent to the largest remainder with deterministic ties',()=>{expect(core().budgetModel(0.01,[30,20,15,10,10,10,5],100).units).toEqual([1,0,0,0,0,0,0]);expect(core().budgetModel(0.01,[50,50],100).units).toEqual([1,0]);});
  it.each([[-1,[100],100],[Infinity,[100],100],[1000001,[100],100],[0.001,[100],100],[1.5,[100],1],[100,[101],100],[100,[-1],100],[100,[2.5],100],[100,[],100],[100,Array(13).fill(10),100],[100,[100],10]])('rejects invalid budget %s %s %s',(...args)=>expect(core().budgetModel(...args).ok).toBe(false));
  it('moves percentage points without changing the total or mutating the source',()=>{const original=[30,20,15,10,10,10,5],moved=core().budgetTransfer(original,4,5,5);expect(moved).toEqual([30,20,15,10,5,15,5]);expect(moved.reduce((a,b)=>a+b)).toBe(100);expect(original[4]).toBe(10);});
  it.each([[0,0,5],[0,1,31],[0,1,0],[0,1,1.5],[-1,1,5],[0,7,5],[0,1,NaN]])('rejects an unavailable transfer %s %s %s',(...args)=>expect(core().budgetTransfer([30,20,15,10,10,10,5],...args)).toBeNull());
  it('rejects invalid saved percentages and a destination over 100%',()=>{expect(core().budgetTransfer([1,NaN],0,1,1)).toBeNull();expect(core().budgetTransfer([100,99],0,1,2)).toBeNull();});
});
describe('budget planning interactions',()=>{
  it('automatically saves the first plan and keeps a transfer exactly balanced',async()=>{const app=await mount();await click('Move allocation');expect(app.state().budgetCats.map(c=>c.pct)).toEqual([30,20,15,10,5,15,5]);expect(app.state().budgetReference.categories.map(c=>c.pct)).toEqual([30,20,15,10,10,10,5]);expect(panel().querySelector('[data-budget-compare-category="5"]').textContent).toContain('+5 percentage points; +$5.00');expect(panel().querySelector('[data-budget-comparison-total]').textContent).toContain('100% → 100%; $100.00 → $100.00');expect(app.awardXP).not.toHaveBeenCalled();expect(app.callGemini).not.toHaveBeenCalled();});
  it('preserves a reference through repeated transfers then can replace and clear it',async()=>{const app=await mount();await click('Save plan to compare');await click('Move allocation');await click('Move allocation');expect(app.state().budgetReference.categories[4].pct).toBe(10);expect(app.state().budgetCats[4].pct).toBe(0);await click('Save current plan as reference');expect(app.state().budgetReference.categories[4].pct).toBe(0);await click('Clear saved plan');expect(panel().querySelector('[data-budget-comparison]')).toBeNull();});
  it('explains when money changes because income changed',async()=>{await mount();await click('Save plan to compare');await input(income(),'200');expect(panel().textContent).toContain('The incomes differ');expect(panel().querySelector('[data-budget-compare-category="0"]').textContent).toContain('0 percentage points; +$30.00');});
  it('keeps an invalid income draft visible and withholds stale plans until corrected',async()=>{const app=await mount();await click('Save plan to compare');await input(income(),'');expect(income().getAttribute('aria-invalid')).toBe('true');expect(panel().querySelector('[data-budget-tapes]')).toBeNull();expect(panel().querySelector('[data-budget-tradeoff]')).toBeNull();await React.act(()=>income().dispatchEvent(new FocusEvent('focusout',{bubbles:true})));expect(income().value).toBe('');expect(app.state().budgetIncome).toBeUndefined();await input(income(),'123.45');expect(income().hasAttribute('aria-invalid')).toBe(false);expect(panel().querySelector('[data-budget-tapes]')).not.toBeNull();expect(app.state().budgetIncome).toBe(123.45);});
  it.each(['-1','1000001','0.001'])('rejects income %s without committing it',async value=>{const app=await mount({budgetIncome:100});await input(income(),value);expect(app.state().budgetIncome).toBe(100);expect(panel().querySelector('[data-budget-tapes]')).toBeNull();expect(document.getElementById(income().getAttribute('aria-describedby')).textContent).toContain('two decimal');});
  it('uses whole-yen validation and clears currency-specific references',async()=>{const app=await mount({currency:'JPY',budgetIncome:1});await click('Save plan to compare');await input(income(),'1.5');expect(panel().textContent).toContain('whole yen');await select(document.querySelector('select[aria-label="Currency"]'),'USD');expect(app.state().budgetReference).toBeNull();expect(app.state().budgetIncomeDraft).toBeNull();expect(panel().querySelector('[data-budget-comparison]')).toBeNull();});
  it('shows literal excess strips and a positive over-allocation amount',async()=>{await mount({budgetIncome:100,budgetCats:cats([50,50,25])});expect(panel().querySelectorAll('[data-budget-strip]')).toHaveLength(2);expect(panel().querySelector('[data-budget-strip="1"] [data-budget-segment]').style.width).toBe('25%');expect(panel().querySelector('[data-budget-balance]').textContent).toBe('25% is beyond the income: $25.00');expect(panel().querySelector('[data-budget-sum]').textContent).toBe('$100.00 + $25.00 = $125.00');expect(panel().textContent).not.toContain('-25% remaining');});
  it('shows an under-allocation equation and reconciles a one-cent income',async()=>{await mount({budgetIncome:0.01,budgetCats:cats([30,20,15,10,10,10,5])});expect(panel().querySelector('[data-budget-key="0"]').textContent).toContain('$0.01');expect(panel().querySelector('[data-budget-key="1"]').textContent).toContain('$0.00');expect(panel().querySelector('[data-budget-sum]').textContent).toBe('$0.01 + $0.00 = $0.01');expect(panel().textContent).toContain('largest fractional remainders');await input(panel().querySelector('input[type="range"]'),'5');expect(panel().querySelector('[data-budget-balance]').textContent).toContain('25% is unallocated');});
  it('prevents invalid transfers and provides a correction message',async()=>{const app=await mount();await input(transferPoints(),'11');expect(panel().querySelector('[data-budget-tradeoff] button').disabled).toBe(true);expect(panel().textContent).toContain('whole number of points available');await click('Move allocation');expect(app.state().budgetCats).toBeUndefined();await input(transferPoints(),'5');await select(panel().querySelector('[data-budget-tradeoff] select'),'5');expect(panel().querySelector('[data-budget-tradeoff] button').disabled).toBe(true);});
  it('allows a keyboard-style slider change up to 100 and clears stale expense feedback',async()=>{const app=await mount({budgetEventId:'repair',budgetEventChoice:'savings',budgetEventFb:{ok:true,message:'Saved feedback'},budgetEventResolved:true});const slider=panel().querySelector('input[type="range"]');expect(slider.max).toBe('100');await input(slider,'80');expect(app.state().budgetCats[0].pct).toBe(80);expect(app.state().budgetEventFb).toBeNull();expect(app.state().budgetEventResolved).toBe(false);expect(panel().textContent).not.toContain('Saved feedback');expect(slider.getAttribute('aria-valuetext')).toBe('80% · $80.00');});
  it('handles zero income and malformed restored categories without crashing',async()=>{await mount({budgetIncome:0,budgetCats:[null,{name:'',pct:Infinity},{name:'Saved',pct:1000}]});expect(panel().textContent).toContain('With zero income, every money amount is zero');expect(panel().querySelectorAll('input[type="range"]')).toHaveLength(3);expect([...panel().querySelectorAll('button')].find(b=>b.textContent.includes('Draw an Expense')).disabled).toBe(true);});
});

it('does not generate an expense that rounds to zero or award points for a restored one',async()=>{const app=await mount({budgetIncome:0.01,budgetEventId:'repair'});const savings=[...panel().querySelectorAll('button')].find(b=>b.textContent.includes('Use savings'));expect(savings.disabled).toBe(true);await React.act(()=>savings.click());expect(app.awardXP).not.toHaveBeenCalled();expect(app.state().budgetEventScore).toBeUndefined();expect(panel().textContent).toContain('This expense rounds to zero');});
it('disables a zero-cost draw and generates a positive expense when income is sufficient',async()=>{const app=await mount({budgetIncome:0.01});const draw=()=>[...panel().querySelectorAll('button')].find(b=>b.textContent.includes('Draw an Expense'));expect(draw().disabled).toBe(true);await input(income(),'0.07');expect(draw().disabled).toBe(false);await React.act(()=>draw().click());expect(app.state().budgetEventId).toBe('repair');});
it('restores a valid income draft consistently and commits it on blur',async()=>{const app=await mount({budgetIncome:100,budgetIncomeDraft:'200'});expect(panel().querySelector('[data-budget-sum]').textContent).toBe('$200.00 + $0.00 = $200.00');await React.act(()=>income().dispatchEvent(new FocusEvent('focusout',{bubbles:true})));expect(app.state().budgetIncome).toBe(200);expect(app.state().budgetIncomeDraft).toBeNull();});
it('preserves completed expense feedback when an unchanged income merely loses focus',async()=>{const app=await mount({budgetIncome:100,budgetEventId:'repair',budgetEventResolved:true,budgetEventFb:{ok:true,message:'Completed expense',impact:'Done',points:3}});await React.act(()=>income().dispatchEvent(new FocusEvent('focusout',{bubbles:true})));expect(app.state().budgetEventResolved).toBe(true);expect(panel().textContent).toContain('Completed expense');});
