import {beforeEach,describe,it,expect} from 'vitest';
import {loadTool,renderTool,resetStemLab} from './helpers/stem_widgets_smoke_harness.js';
let model;
beforeEach(()=>{resetStemLab();loadTool('stem_lab/stem_tool_renewables.js','renewablesLab');model=window.StemLab.renewablesEnergyModel;});
const close=(a,b,scale=0)=>expect(Math.abs(a-b)).toBeLessThanOrEqual(Math.max(Math.abs(a),Math.abs(b),scale,1e-20)*1e-8);
const pv={settings:{irradiance:1000,incidence:0,area:20,efficiency:20},config:{x:{key:'area',low:10,high:30},y:{key:'efficiency',low:10,high:30},count:3,target:5}};
function csvRows(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\r'&&!quoted){}else if(c==='\n'&&!quoted){row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);rows.push(row);return rows;}
describe('Four-case explanation of a design-map combination',()=>{
  for(const id of ['solarPv','wind','hydro','geothermal','solarThermal','wave','tidal','biomass','storage'])it(id+' replays all four cases with native accounting under steady and both operating scenarios',()=>{
    for(const profileId of ['steady',...model.programs[id].map(p=>p.id)]){const m=model.designMap(id,{profileId,phase:37,config:{count:3}}),a=model.designMapExplanation(m,m.rows.length-1),e=a.effects;
      expect(a.cases.map(c=>c.key)).toEqual(['reference','horizontal','vertical','both']);expect(a.id).toBe(id);expect(a.profileId).toBe(profileId);expect(a.phase).toBe(m.phase);expect(a.unit).toBe(m.unit);expect(a.duration).toBe(m.duration);
      for(const c of a.cases){const expected=profileId==='steady'?(id==='storage'?model.simulate(id,c.settings,120).extra.delivered:model.simulate(id,c.settings).power):model.scenario(id,c.settings,profileId).totals.delivered;close(c.result.value,expected);expect(Number.isFinite(c.result.value)).toBe(true);if(id==='storage'){close(c.result.initial+c.result.input,c.result.value+c.result.remainder+c.result.endStored);if(profileId!=='steady')close(c.result.requested,c.result.value+c.result.unserved);}else close(c.result.input,c.result.value+c.result.remainder);}
      expect(a.cases[0].settings).toEqual(m.baseSettings);expect(a.cases[3].settings).toEqual(m.rows.at(-1).settings);expect(a.cases[1].settings).toEqual({...m.baseSettings,[m.config.x.key]:m.rows.at(-1).x});expect(a.cases[2].settings).toEqual({...m.baseSettings,[m.config.y.key]:m.rows.at(-1).y});
      close(e.combined,e.horizontalAlone+e.verticalAlone+e.extraCombined,m.peak);close(e.combined,e.horizontalAlone+e.verticalAfterHorizontal,m.peak);close(e.combined,e.verticalAlone+e.horizontalAfterVertical,m.peak);
    }
  });
  it('matches the analytical product and both actual comparison orders',()=>{const a=model.designMapExplanation(model.designMap('solarPv',pv),8);a.cases.forEach((c,i)=>close(c.result.value,[3.84,5.76,5.76,8.64][i]));const e=a.effects;close(e.horizontalAlone,1.92);close(e.verticalAlone,1.92);close(e.combined,4.8);close(e.extraCombined,.96);close(e.horizontalAfterVertical,2.88);close(e.verticalAfterHorizontal,2.88);expect(a.relationship).toBe('above');expect(a.cases.map(c=>c.meetsTarget)).toEqual([false,true,true,true]);});
  it('swaps standalone and conditional changes when axes are transposed',()=>{const a=model.designMapExplanation(model.designMap('solarPv',pv),2),b=model.designMapExplanation(model.designMap('solarPv',{...pv,config:{...pv.config,x:pv.config.y,y:pv.config.x}}),6);expect(a.cases[3].settings).toEqual(b.cases[3].settings);close(a.effects.horizontalAlone,b.effects.verticalAlone);close(a.effects.verticalAfterHorizontal,b.effects.horizontalAfterVertical);close(a.effects.extraCombined,b.effects.extraCombined);});
  it('handles opposite input changes with no standalone net change',()=>{const a=model.designMapExplanation(model.designMap('solarPv',pv),6);close(a.effects.horizontalAlone,-1.92);close(a.effects.verticalAlone,1.92);close(a.effects.combined,-.96);close(a.effects.extraCombined,-.96);expect(a.relationship).toBe('below');});
  it('can have a positive extra combined effect while both inputs and output decline',()=>{const a=model.designMapExplanation(model.designMap('solarPv',pv),0);expect(a.effects.horizontalAlone).toBeLessThan(0);expect(a.effects.verticalAlone).toBeLessThan(0);expect(a.effects.combined).toBeLessThan(0);close(a.effects.extraCombined,.96);expect(a.relationship).toBe('above');});
  for(const [index,unchanged] of [[5,{horizontal:false,vertical:true}],[7,{horizontal:true,vertical:false}],[4,{horizontal:true,vertical:true}]])it('recognizes coincident cases for selected trial '+(index+1),()=>{const a=model.designMapExplanation(model.designMap('solarPv',pv),index);expect(a.unchanged).toEqual(unchanged);expect(a.relationship).toBe('additive');close(a.effects.extraCombined,0,a.cases[0].result.value);if(unchanged.horizontal)expect(a.cases[0].result).toEqual(a.cases[1].result);if(unchanged.vertical)expect(a.cases[0].result).toEqual(a.cases[2].result);});
  it('stays finite with all-zero shutdown outputs',()=>{const a=model.designMapExplanation(model.designMap('wind',{settings:{speed:25},config:{count:3}}),8);expect(a.cases.every(c=>c.result.value===0&&c.result.status==='Protective shutdown')).toBe(true);expect(Object.values(a.effects).every(v=>v===0)).toBe(true);expect(a.relationship).toBe('additive');expect(a.tolerance).toBeGreaterThan(0);});
  it('supports a zero reference without division by reference output',()=>{const a=model.designMapExplanation(model.designMap('wind',{settings:{speed:0},config:{x:{key:'speed',low:0,high:15},y:{key:'radius',low:10,high:80},count:3}}),8);expect(a.cases[0].result.value).toBe(0);expect(a.cases[3].result.value).toBeGreaterThan(0);expect(Object.values(a.effects).every(Number.isFinite)).toBe(true);});
  it('reveals complementary capacity and power limits in a lossless empty battery',()=>{const a=model.designMapExplanation(model.designMap('storage',{settings:{initial:0,roundtrip:100,capacity:10,power:10},config:{x:{key:'capacity',low:10,high:30},y:{key:'power',low:10,high:30},count:3}}),8);a.cases.forEach((c,i)=>close(c.result.value,[10,10,10,30][i]));close(a.effects.extraCombined,20);expect(a.relationship).toBe('above');});
  it('reveals overlapping changes when a different battery limit takes over',()=>{const a=model.designMapExplanation(model.designMap('storage',{settings:{initial:0,roundtrip:100,capacity:30,power:10},config:{x:{key:'capacity',low:10,high:30},y:{key:'power',low:10,high:30},count:3}}),6);a.cases.forEach((c,i)=>close(c.result.value,[10,10,30,10][i]));close(a.effects.extraCombined,-20);expect(a.relationship).toBe('below');});
  it('preserves scheduled charging offers and demand in all battery cases',()=>{const a=model.designMapExplanation(model.designMap('storage',{profileId:'interrupted',settings:{initial:0},config:{count:3}}),8);expect(new Set(a.cases.map(c=>c.result.requested.toFixed(6))).size).toBe(1);for(const c of a.cases){expect(c.result.value).toBeLessThanOrEqual(44+1e-9);expect(c.result.unserved).toBeGreaterThan(0);}});
  it('accounts for initial energy changes when capacity changes at fixed SOC',()=>{const a=model.designMapExplanation(model.designMap('storage',{profileId:'evening',settings:{initial:100},config:{count:3}}),8);for(const c of a.cases)expect(c.result.initial).toBe(c.settings.capacity);expect(a.cases[0].result.initial).not.toBe(a.cases[1].result.initial);});
  it('keeps full-sequence outputs independent of the 3D inspection minute',()=>{const a=model.designMapExplanation(model.designMap('solarPv',{...pv,profileId:'daylight',phase:0}),8),b=model.designMapExplanation(model.designMap('solarPv',{...pv,profileId:'daylight',phase:720}),8);expect(a.cases).toEqual(b.cases);expect(a.effects).toEqual(b.effects);expect(b.phase).toBe(720);expect(b.cases[3].result.value).toBeGreaterThan(0);expect(model.scenario('solarPv',b.cases[3].settings,'daylight').rows[720].run.power).toBe(0);});
  it('uses exact reference coordinates even outside the sampled grid',()=>{const m=model.designMap('solarPv',{...pv,settings:{...pv.settings,area:100,efficiency:25}}),a=model.designMapExplanation(m,8);expect(a.cases[1].settings.efficiency).toBe(25);expect(a.cases[2].settings.area).toBe(100);expect(m.rows.some(r=>JSON.stringify(r.settings)===JSON.stringify(a.cases[1].settings))).toBe(false);close(a.cases[1].result.value,7.2);close(a.cases[2].result.value,28.8);});
  it('bounds selection and tolerates missing maps',()=>{const m=model.designMap('solarPv',pv);expect(model.designMapExplanation(null,2)).toBeNull();expect(model.designMapExplanation({rows:[]},2)).toBeNull();expect(model.designMapExplanation(m,-9).selected).toBe(0);expect(model.designMapExplanation(m,1000).selected).toBe(8);expect(model.designMapExplanation(m,2.8).selected).toBe(2);});
  it('reproduces serialized results without mutating the map or request',()=>{const m=model.designMap('solarPv',pv),before=JSON.stringify(m),a=model.designMapExplanation(m,8);expect(JSON.stringify(m)).toBe(before);expect(model.designMapExplanation(JSON.parse(before),8)).toEqual(a);a.cases[1].settings.area=999;expect(m.baseSettings.area).toBe(20);});
  it('exports exact case accounting, metadata, effects, and quoted observations',()=>{const a=model.designMapExplanation(model.designMap('storage',{profileId:'interrupted',phase:45,config:{count:3}}),8),note='A "limit", then\na change.',rows=csvRows(model.designMapExplanationCsv(a,note)),head=rows[0];expect(rows).toHaveLength(5);expect(new Set(rows.map(r=>r.length)).size).toBe(1);for(const row of rows.slice(1)){const get=k=>row[head.indexOf(k)],c=a.cases.find(c=>c.key===get('case'));expect(JSON.parse(get('case_settings_json'))).toEqual(c.settings);expect(JSON.parse(get('reference_settings_json'))).toEqual(a.baseSettings);expect(get('observation')).toBe(note);expect(get('scenario')).toBe('interrupted');expect(get('inspection_minute')).toBe('45');expect(get('explanation_version')).toBe('1');expect(get('map_version')).toBe('1');expect(get('mechanism_version')).toBe('1');expect(Number(get('extra_combined_effect'))).toBe(a.effects.extraCombined);expect(Number(get('output'))).toBe(c.result.value);close(Number(get('requested_kWh')),Number(get('output'))+Number(get('unserved_kWh')));}});
  it('bounds exported observation length and preserves missing targets',()=>{const a=model.designMapExplanation(model.designMap('solarPv',{}),0),rows=csvRows(model.designMapExplanationCsv(a,'x'.repeat(2500))),head=rows[0];expect(rows[1][head.indexOf('observation')]).toHaveLength(2000);expect(rows[1][head.indexOf('target')]).toBe('');expect(rows[1][head.indexOf('meets_target')]).toBe('');});
  it('renders four cases, both comparison paths, an observation and inspection controls',()=>{const html=renderTool('renewablesLab',{renewablesLab:{view:'energy3d',energyLab:{selected:'solarPv',designMaps:{solarPv:{open:true,run:pv,selected:8,explanation:{open:true,selected:8,observation:'The inputs multiply.'}}}}}});for(const text of ['Explain this combination','Four-case comparison','Horizontal input only','Vertical input only','Extra combined effect','Horizontal first','Vertical first','Inspect both inputs in 3D','Export four-case comparison CSV','The inputs multiply.'])expect(html).toContain(text);expect(html).not.toContain('NaN');expect(html).not.toContain('failed to render');});
  it('does not attach an observation to a different selected trial',()=>{const html=renderTool('renewablesLab',{renewablesLab:{view:'energy3d',energyLab:{selected:'solarPv',designMaps:{solarPv:{open:true,run:pv,selected:0,explanation:{open:true,selected:8,observation:'Note for trial nine only.'}}}}}});expect(html).not.toContain('Note for trial nine only.');});
});
