'use strict';

const q = (skillId, difficulty, cognitiveLevel, prompt, correct, distractors, rationale, whyWrong) => ({
  skillId, difficulty, cognitiveLevel, prompt, correct, distractors, rationale, whyWrong,
});

module.exports = [
  q('teaching-learning-01', 'analysis', 'apply',
    'A social studies teacher asks the librarian to “teach databases” before a local-history project but has not shared the learning goals. What should the librarian do first?',
    'Clarify the project outcomes and evidence, identify where information skills are needed, and co-design instruction and assessment.',
    [
      'Schedule a standard database tour because tool familiarity should precede discussion of the class assignment.',
      'Send a video tutorial so the teacher can preserve class time for the disciplinary content of the project.',
      'Ask students to explore every subscribed database and report which interface they prefer using for assignments.',
    ],
    'Collaborative planning begins with what students must understand and produce, then aligns information-literacy instruction, resources, practice, and evidence to that purpose. A generic tool demonstration may not transfer to the actual inquiry decisions students face.',
    [
      'starts with platform features and cannot determine which search, evaluation, or use decisions support the intended outcome.',
      'separates information practice from disciplinary learning and shifts responsibility without checking alignment or student need.',
      'collects preference information but consumes time across tools without defining the research task or performance criterion.',
    ]),
  q('teaching-learning-01', 'application', 'apply',
    'Students will create evidence-based recommendations about a community issue. Which learning objective is best aligned with that task?',
    'Students will synthesize relevant evidence from multiple credible perspectives and justify a feasible recommendation with cited reasoning.',
    [
      'Students will understand community issues and become familiar with several useful information resources.',
      'Students will search the database, save three articles, and format a bibliography in the required citation style.',
      'Students will enjoy researching a topic and appreciate why reliable information is important in civic life.',
    ],
    'An aligned objective describes observable performance at the level required by the final task. It integrates evidence selection, perspective, synthesis, reasoning, and attribution rather than naming activities, broad internal states, or hoped-for attitudes.',
    [
      'uses internal and vague verbs that do not specify what performance would demonstrate the intended understanding.',
      'lists useful component activities but does not require students to interpret evidence or use it to justify a recommendation.',
      'states desirable engagement and disposition but supplies no observable criterion for the evidence-based product.',
    ]),
  q('teaching-learning-01', 'analysis', 'analyze',
    'A jointly taught inquiry unit has strong final products, but the classroom teacher and librarian disagree about which instruction produced the gains. What evaluation plan is strongest?',
    'Use shared outcomes and rubric evidence, document each instructional component, gather student process evidence, and interpret contribution jointly.',
    [
      'Credit the librarian because source quality appears in the rubric and information literacy belongs to the library program.',
      'Credit the classroom teacher because that teacher assigns the grade and has more instructional minutes with students.',
      'Avoid evaluating the partnership because co-teaching makes it impossible to learn anything about implementation or results.',
    ],
    'Collaborative instruction is intentionally interdependent, so evaluation should examine the combined design and how its components were implemented. Shared evidence can identify plausible contributions and improvements without claiming simple individual causation.',
    [
      'infers ownership from the content of one criterion and overlooks how disciplinary and information instruction may interact.',
      'uses formal grading authority and time as proxies for instructional effect instead of examining student learning and implementation.',
      'correctly resists false attribution but discards evidence that can improve future planning even without isolating causal effects.',
    ]),
  q('teaching-learning-01', 'application', 'apply',
    'During co-planning, the teacher wants students to evaluate sources only after completing their essays. What should the librarian recommend?',
    'Embed evaluation when students select and use evidence, with checkpoints that allow them to revise sources before drafting is complete.',
    [
      'Accept the sequence because retrospective evaluation gives students a complete set of sources to compare efficiently.',
      'Move all source evaluation to a lecture before students choose topics so the skill does not interrupt the writing process.',
      'Evaluate the sources for students and provide an approved list so essay drafting remains the primary learning activity.',
    ],
    'Source evaluation is a decision process that shapes inquiry, not merely a final compliance check. Timely modeling, guided practice, and feedback at selection and integration points let students act on what they learn and observe how source quality affects claims.',
    [
      'places feedback after major research choices are fixed and makes meaningful replacement or reframing unnecessarily costly.',
      'front-loads terminology without applying it at the moment of need and may encourage students to treat evaluation as detached content.',
      'improves immediate source quality by removing the intended student judgment and transfer opportunity from the assignment.',
    ]),
  q('teaching-learning-01', 'analysis', 'evaluate',
    'A teacher asks the librarian to grade every citation in 150 research papers but offers no role in planning or instruction. Which response best supports sustainable collaboration?',
    'Clarify the learning need, propose shared instruction and a manageable evidence-sampling plan, and define responsibilities before the next unit.',
    [
      'Grade all citations this time so successful completion demonstrates that the library deserves a larger instructional role.',
      'Decline any assistance because assessment belongs exclusively to the classroom teacher who assigns the research paper.',
      'Replace citation feedback with an automated score and accept the tool\'s output as the common assessment result.',
    ],
    'A sustainable partnership links the librarian\'s expertise to instruction, assessment design, and improvement rather than a late clerical burden. Negotiating roles and using representative evidence can address the current need while redesigning the next learning cycle.',
    [
      'absorbs an unplanned workload, separates feedback from teaching, and reinforces a service pattern that cannot scale.',
      'sets an unnecessary boundary and loses an opportunity to improve both student work and the structure of future collaboration.',
      'reduces workload but delegates validity and feedback decisions to a system without checking accuracy, context, or learning value.',
    ]),
  q('teaching-learning-01', 'application', 'apply',
    'Two teachers teaching the same course want different research rubrics, although students share the same stated outcomes. What should the librarian facilitate?',
    'Unpack the common outcomes, agree on observable criteria and performance levels, and allow assignment-specific features only where justified.',
    [
      'Average the two rubric scores after each teacher grades with a preferred instrument so neither rubric must change.',
      'Select the shorter rubric because consistent administration matters more than matching criteria to the learning goals.',
      'Use separate rubrics and tell students that expectations naturally depend on which teacher evaluates the work.',
    ],
    'Common outcomes call for comparable evidence and criteria, even when products differ. Collaborative calibration clarifies constructs and performance levels, supports consistent feedback, and reveals where a course-specific or product-specific variation is genuinely needed.',
    [
      'combines potentially different constructs after scoring and does not resolve conflicting expectations or interpretations.',
      'prioritizes convenience while leaving open whether the retained criteria provide valid evidence of the outcomes.',
      'normalizes unexplained variability and makes equitable performance expectations less transparent to learners and reviewers.',
    ]),
  q('teaching-learning-01', 'analysis', 'analyze',
    'A project team has mapped standards, tasks, and resources, but the final product does not require students to use the research they conduct. What is the best revision?',
    'Redesign the product and rubric so claims or design choices must be supported by evaluated evidence gathered during inquiry.',
    [
      'Add a minimum source count to the directions while keeping the product and scoring criteria unchanged.',
      'Require students to submit search histories separately so research effort can be graded apart from the final product.',
      'Increase the number of library days so students have more time to collect information before creating the same product.',
    ],
    'Alignment requires the culminating performance to make the intended use of research visible. Evidence-linked claims or decisions and corresponding rubric criteria create a reason to evaluate, synthesize, and cite information rather than merely accumulate it.',
    [
      'changes compliance volume but leaves students able to satisfy the final task without reasoning from the collected sources.',
      'documents process and may support feedback, yet still permits the culminating work to ignore the research outcome.',
      'adds opportunity to search without correcting the structural disconnect between inquiry activity and assessed performance.',
    ]),
  q('teaching-learning-02', 'analysis', 'apply',
    'In a source-comparison lesson, one student needs text-to-speech and another processes information best through visual chunking. Which design is strongest?',
    'Provide accessible text and structured visual organizers to all, allow supported ways to examine sources, and assess the same evaluation criteria.',
    [
      'Create a simpler source-evaluation task for both students so accommodations do not affect the pace of the whole class.',
      'Give the original lesson to the class and arrange separate remediation after either student fails the assessment.',
      'Assign each student a preferred medium and prohibit switching so the differentiation plan remains easy to manage.',
    ],
    'Accessible materials and flexible supports can reduce barriers without changing the construct being assessed. Maintaining common source-evaluation criteria preserves rigor, while learner input and observation determine which options are useful rather than assigning fixed categories.',
    [
      'changes the cognitive demand based on support need and may deny students access to the intended evaluation outcome.',
      'waits for predictable barriers to produce failure instead of designing access and checking usability before assessment.',
      'offers variation but turns a current preference into a restriction and prevents strategic choice or adjustment during learning.',
    ]),
  q('teaching-learning-02', 'application', 'apply',
    'A librarian wants all students to learn how evidence changes a claim. Which lesson option best reflects flexible access without lowering the goal?',
    'Offer readable text, audio, and captioned media sources, model evidence revision, and let students explain claim changes in accessible formats using common criteria.',
    [
      'Give struggling readers shorter sources containing the correct conclusion while other students evaluate conflicting evidence.',
      'Let students choose any enjoyable activity related to the topic, whether or not it requires revising a claim from evidence.',
      'Require a handwritten paragraph from every student so the assessment conditions remain uniform and easy to compare.',
    ],
    'Flexible representation and expression support access when the intellectual target remains stable. Common criteria should capture how evidence justifies revision, while format options avoid measuring decoding, hearing, or handwriting demands irrelevant to that target.',
    [
      'removes the conflict and reasoning demand for some learners and therefore assesses a different, less complex outcome.',
      'maximizes choice but disconnects activity from the evidence-revision construct that the lesson is intended to teach.',
      'standardizes a response mode that may add irrelevant barriers and obscure whether students can perform the intended reasoning.',
    ]),
  q('teaching-learning-02', 'application', 'analyze',
    'Students submit search logs midway through an inquiry unit. Which use of those logs would make the assessment genuinely formative?',
    'Identify patterns in query revision and source selection, give actionable feedback, and provide time for students to change their searches.',
    [
      'Record a completion grade and store the logs as evidence that students participated in the research process.',
      'Rank students by number of searches so those with the fewest queries know they need to work harder.',
      'Wait until final projects are graded, then use the logs to explain why low-scoring students had difficulty.',
    ],
    'Formative assessment changes ongoing teaching or learning. Interpreting the logs against clear search-process criteria and allowing revision turns evidence into a feedback loop rather than a participation count, effort proxy, or retrospective explanation.',
    [
      'collects process evidence but does not diagnose learning or give students information they can use during the task.',
      'treats activity volume as quality even though efficient searches may be strong and numerous unrevised searches may be weak.',
      'uses potentially valuable evidence after the learner can act on it and therefore forfeits its formative purpose.',
    ]),
  q('teaching-learning-02', 'analysis', 'evaluate',
    'A student chooses a weak source, and the librarian writes only “not credible” in the margin. Which feedback would be more effective?',
    'Name the unsupported authority claim, ask the student to trace the statistic to its origin, and suggest a concrete comparison step.',
    [
      'Write “choose a better website” so the student remains responsible for deciding what quality means.',
      'Provide the correct replacement source without explaining how its evidence or provenance differs from the first one.',
      'Deduct points for credibility and postpone further explanation until the class begins the next research project.',
    ],
    'Effective feedback is specific to the evidence, connected to criteria, and usable in the current work. Identifying the precise weakness and a next action helps the student practice evaluation rather than merely receive a judgment or replacement.',
    [
      'signals that change is needed but leaves the criterion and next reasoning step undefined, limiting transfer.',
      'improves the product while doing the evaluation for the learner and conceals the comparison that would build skill.',
      'records a consequence but delays guidance beyond the decision point when the student can revise and learn from the source.',
    ]),
  q('teaching-learning-02', 'analysis', 'analyze',
    'Most students score well on a source-authority rubric row but poorly on evidence relevance. What should the librarian infer?',
    'Students may recognize source credentials yet need targeted modeling and practice connecting particular evidence to a claim and context.',
    [
      'The class has mastered source evaluation because authority is the most important criterion in every research situation.',
      'The relevance scores should be removed because a credible author makes information relevant to any question in the same subject.',
      'The rubric should be replaced with a single holistic score so different evaluation dimensions cannot conflict.',
    ],
    'Criterion-level evidence distinguishes strengths from unfinished learning. Authority and relevance answer different questions; instruction can preserve the established skill while using examples, think-alouds, and feedback to develop claim-evidence fit.',
    [
      'generalizes mastery from one dimension and ignores direct evidence that students struggle with another required judgment.',
      'conflates expertise with applicability and would reward accurate information that does not support the specific claim.',
      'hides the diagnostic pattern inside one score and makes targeted teaching and feedback more difficult rather than resolving it.',
    ]),
  q('teaching-learning-02', 'application', 'apply',
    'A multilingual learner understands the research topic but is still developing the academic language used in database abstracts. Which support best preserves the inquiry goal?',
    'Preteach key concepts with visuals and multilingual resources, model abstract structure, and allow language supports while assessing source reasoning.',
    [
      'Assign simpler factual webpages so the learner can avoid abstracts and complete the project independently.',
      'Have a fluent peer select all sources because efficient collaboration matters more than individual source judgment.',
      'Require dictionary translation of every unfamiliar word before the learner may decide whether an abstract is relevant.',
    ],
    'Language scaffolds can make disciplinary reasoning visible without replacing it. Concept preparation, strategic translation, modeling, and supported discussion help the learner evaluate relevance while the assessment remains focused on inquiry rather than exhaustive English decoding.',
    [
      'reduces language demand by changing the information task and may deny access to the source types used by classmates.',
      'produces usable materials but transfers the targeted evaluation decision to another student and obscures learning evidence.',
      'turns vocabulary lookup into a gate, overloads working attention, and ignores contextual strategies for deciding relevance.',
    ]),
  q('teaching-learning-02', 'application', 'apply',
    'Before assigning an interactive research tutorial, the librarian learns that it cannot be completed by keyboard alone. What is the best response?',
    'Provide an equally effective accessible route now, report the barrier, and avoid requiring the inaccessible tutorial until it is remediated.',
    [
      'Assign the tutorial and let students who encounter difficulty request a partner to operate the controls for them.',
      'Exempt students who cannot use a pointer device and omit the tutorial outcome from their course expectations.',
      'Require completion on a touch-screen tablet because changing hardware resolves every keyboard-access problem.',
    ],
    'Accessibility should be verified before a required learning experience. An equivalent route preserves the same outcome and student agency while the product is repaired or replaced; dependence, exemption, or untested hardware substitution does not establish access.',
    [
      'makes access dependent on disclosure and another person\'s operation, changing independence and potentially the evidence of learning.',
      'removes the barrier by removing the learner from an intended outcome rather than providing a usable means to reach it.',
      'assumes one input method is available and usable for every learner and does not address the documented keyboard failure.',
    ]),
  q('teaching-learning-02', 'analysis', 'evaluate',
    'A group inquiry rubric gives one shared score for every student, although observation shows that two students made all source decisions. What should be changed?',
    'Combine group-product criteria with individual process evidence such as conferences, annotations, reflections, or decision logs.',
    [
      'Keep the shared score because collaboration means individual contributions should not be separated or examined.',
      'Give the most active students bonus points based on the librarian\'s general impression of effort during work time.',
      'Replace the group project with an individual multiple-choice quiz that measures vocabulary from the research unit.',
    ],
    'When an outcome includes individual inquiry judgment, the assessment needs evidence attributable to each learner as well as the shared product. Multiple planned sources support fairer interpretation without discarding authentic collaboration.',
    [
      'assesses the group artifact but cannot show whether each student performed the targeted source-evaluation decisions.',
      'acknowledges uneven participation but uses an undefined and potentially biased effort judgment rather than outcome evidence.',
      'produces individual scores but changes the construct from applied inquiry performance to recognition of terminology.',
    ]),
  q('teaching-learning-03', 'application', 'apply',
    'Circulation is high among avid readers but low among students who say library recommendations feel impersonal. Which instructional response is strongest?',
    'Use low-stakes reading-interest conversations and varied book encounters, protect choice, and refine recommendations from learner feedback.',
    [
      'Assign each low-circulating student a popular series so every learner begins with a title proven to engage peers.',
      'Create public reading-level shelves and direct students to remain within the level shown in their assessment records.',
      'Offer prizes for the number of books completed because increased volume demonstrates development of a reading identity.',
    ],
    'Reader development grows through agency, knowledge of texts, social connection, and responsive guidance. Conversation and multiple discovery routes allow recommendations to evolve without reducing readers to popularity, public labels, or extrinsic counts.',
    [
      'uses group popularity as a substitute for individual interests, identities, purposes, formats, and prior reading experience.',
      'exposes sensitive performance information and turns a provisional measure into a restrictive identity and access boundary.',
      'may change reported volume while encouraging selection or completion behavior that does not reveal durable engagement or fit.',
    ]),
  q('teaching-learning-03', 'analysis', 'analyze',
    'A student advisory group says the library\'s reading promotions feature genres they rarely choose. What should the librarian do next?',
    'Invite students to analyze promotion and circulation patterns, co-curate varied displays, and evaluate whether discovery broadens across groups.',
    [
      'Replace the current displays with the students\' favorite genre because advisory members represent the preferences of the full school.',
      'Keep the campaign unchanged because professional collection knowledge should outweigh student opinions about promotion.',
      'Ask publishers for ready-made displays so marketing data determines which genres are most likely to circulate.',
    ],
    'Co-curation gives learners meaningful voice while retaining professional responsibility for breadth, access, and evaluation. Comparing who encounters and borrows promoted works helps distinguish a more inclusive discovery strategy from a simple shift to another narrow preference.',
    [
      'responds to voice by overgeneralizing from one group and may reproduce the same representational problem with a new genre.',
      'protects professional authority by ignoring direct evidence about how intended users experience the program.',
      'provides polished materials but substitutes commercial priorities and aggregate markets for local learner evidence and collection goals.',
    ]),
  q('teaching-learning-03', 'application', 'apply',
    'Students compare two short videos about a public issue. Which prompt most directly develops media-literacy reasoning?',
    'What claim does each video advance, how do production choices frame it, what evidence is shown or omitted, and who benefits from the message?',
    [
      'Which video has higher image quality, smoother editing, and a narrator who sounds confident and professional?',
      'Which video do most classmates prefer, and how many positive reactions has each received on its platform?',
      'Which video presents more facts, regardless of their sources, relevance, context, or connection to the central claim?',
    ],
    'Media literacy examines constructed messages, evidence, purpose, audience, representation, and effects. The prompt makes students connect formal choices and omissions to meaning rather than equating polish, popularity, or raw fact count with credibility.',
    [
      'notices production features but treats professional appearance as a quality verdict instead of asking how those features shape interpretation.',
      'measures preference and engagement, which may be useful audience evidence but does not establish support for the claims.',
      'counts asserted information while leaving accuracy, provenance, selection, and reasoning unexamined.',
    ]),
  q('teaching-learning-03', 'analysis', 'evaluate',
    'A generative tool produces a confident summary of a novel but invents a scene. What should the librarian ask students to do?',
    'Compare each material claim with the text and reliable sources, document discrepancies, and evaluate when the tool is unsuitable or needs verification.',
    [
      'Rewrite the summary in the student\'s own style because paraphrasing removes the factual risk created by the tool.',
      'Accept the summary if most plot details are correct because occasional invented details are an expected feature of efficient tools.',
      'Ban discussion of generative tools so students cannot confuse machine output with literary evidence in future assignments.',
    ],
    'Generated fluency is not evidence of accuracy. Claim-level verification reveals both useful and unreliable output, supports transparent decisions about use and attribution, and transfers to other systems rather than relying on surface confidence.',
    [
      'changes expression but preserves the unsupported content and may conceal rather than correct its origin.',
      'normalizes an error without considering whether the assignment requires textual accuracy or whether the fabricated scene changes interpretation.',
      'removes an immediate tool from instruction but forfeits the opportunity to teach evaluation of systems students will encounter elsewhere.',
    ]),
  q('teaching-learning-03', 'application', 'apply',
    'During an inquiry lesson, students copy the first search result into notes without opening it. Which librarian think-aloud would best interrupt that habit?',
    'Model predicting from the result snippet, opening the source, tracing publisher and evidence, and revising the decision aloud.',
    [
      'Demonstrate how to copy snippets quickly while adding the result URL so every note remains technically cited.',
      'Tell students that the first result is usually weak and direct them to begin with the fifth result instead.',
      'Hide snippets in the browser so students must judge sources from titles and domain names before opening them.',
    ],
    'A think-aloud externalizes the questions and evidence behind a source decision. It helps students see a search result as a pointer, not the source itself, and connects prediction, inspection, verification, and query revision.',
    [
      'improves recordkeeping but preserves the core error of treating decontextualized result text as examined evidence.',
      'replaces one rank shortcut with another and gives no transferable process for judging the opened source.',
      'removes one cue but still encourages a surface decision before students inspect content, provenance, and supporting evidence.',
    ]),
  q('teaching-learning-03', 'analysis', 'evaluate',
    'A book club requires every participant to finish the same novel on the same date, and attendance is dropping. Which revision best preserves shared discussion?',
    'Offer a small thematic text set in accessible formats, establish common discussion questions, and let groups set supported reading milestones.',
    [
      'Shorten each meeting so students have less time to reveal that they did not complete the assigned chapters.',
      'Keep the single novel but award attendance points that are large enough to offset difficulty completing the reading.',
      'Replace discussion with individual comprehension quizzes because independent accountability is easier to schedule consistently.',
    ],
    'Shared inquiry can be built around theme and common questions rather than identical pacing and format. Bounded choice, accessible texts, and visible milestones preserve intellectual community while allowing meaningful differences in interest and reading process.',
    [
      'conceals the participation problem and reduces community time without addressing access, fit, pacing, or motivation.',
      'adds a compliance incentive while leaving the structural barriers and lack of text choice unchanged.',
      'improves individual measurement but abandons the social interpretation and reader-to-reader exchange central to the club.',
    ]),
  q('teaching-learning-03', 'analysis', 'analyze',
    'A teacher wants students to choose books strictly from a test-derived reading band. What should the librarian recommend?',
    'Use the score as one provisional data point while considering purpose, interest, background knowledge, format, support, and student choice.',
    [
      'Enforce the band because standardized scores identify the precise text complexity each student can manage independently.',
      'Ignore all reading evidence because free choice means adults should not offer guidance about text demands or supports.',
      'Place band labels on student library cards so staff and peers can help keep selections appropriately challenging.',
    ],
    'A reading measure samples performance under particular conditions and cannot define a reader or a book relationship completely. Flexible guidance can support access and growth while allowing different purposes, formats, scaffolds, and motivated choices.',
    [
      'overinterprets measurement precision and turns a limited estimate into a fixed restriction across texts and contexts.',
      'protects agency but creates a false choice between coercive leveling and responsive professional support.',
      'makes sensitive performance information public and converts guidance into surveillance and peer-enforced restriction.',
    ]),
  q('teaching-learning-04', 'application', 'apply',
    'A class entering the library for a collaborative task becomes noisy during transitions between stations. What should the librarian change first?',
    'Teach and rehearse transition routines, clarify visual and verbal cues, check space flow, and reinforce the expected behavior.',
    [
      'Remove the most interactive station because quiet compliance is more important than preserving the collaborative learning design.',
      'Wait for the classroom teacher to correct transitions because behavior management remains outside the librarian\'s instructional role.',
      'Record the names of loud groups and lower their project grades before explaining what successful transitions look like.',
    ],
    'Productive learning environments make routines explicit and design the space and timing to support them. Modeling, rehearsal, cues, supervision, and feedback teach the expected behavior while preserving the active task and shared instructional responsibility.',
    [
      'reduces the occasion for noise by weakening the learning design and does not teach students how to manage future transitions.',
      'fragments co-teaching responsibility and leaves an environmental barrier unaddressed within the librarian\'s own space and lesson.',
      'uses a punitive academic consequence before expectations are taught and may measure noise rather than project learning.',
    ]),
  q('teaching-learning-04', 'analysis', 'evaluate',
    'Students propose a maker challenge to design low-cost book supports for readers with limited hand mobility. Which plan best supports authentic learning?',
    'Co-define needs with intended users, research constraints, prototype safely, gather usability feedback, and document design revisions.',
    [
      'Have students select a design from an online image and reproduce it so every prototype can be judged by the same appearance standard.',
      'Ask students to imagine the users\' needs without involving them because consultation may reduce creative independence.',
      'Score the first finished prototype on novelty and speed because an authentic design process rewards rapid invention.',
    ],
    'Authentic design integrates inquiry, ethical partnership, constraint analysis, making, testing, and iteration. Intended users contribute expertise rather than serving as imagined problems, and evidence from use should influence the final explanation and product.',
    [
      'supports technical practice but turns design into replication and evaluates appearance rather than fit with a documented need.',
      'protects student control by excluding the people with the most relevant lived knowledge and risks designing from stereotypes.',
      'rewards a first attempt and surface originality while omitting research, safety, usability evidence, and revision.',
    ]),
  q('teaching-learning-04', 'analysis', 'evaluate',
    'The school can license one digital annotation tool for research instruction. Which selection process is strongest?',
    'Test candidate tools against the learning goal, accessibility, privacy, interoperability, support, cost, and evidence from a representative pilot.',
    [
      'Choose the tool with the most collaboration features because feature breadth gives teachers flexibility for future lessons.',
      'Select the lowest annual price because annotation tools perform the same basic instructional function across vendors.',
      'Adopt the tool preferred by the technology committee before asking students who use assistive technology to try it.',
    ],
    'Educational technology is part of a teaching system. A representative pilot examines whether learners can perform the intended annotation and reasoning, while lifecycle and governance review address barriers and costs that a feature list or initial price will not reveal.',
    [
      'uses quantity of functions as a proxy for instructional fit and may introduce complexity, access barriers, or unused capabilities.',
      'assumes functional equivalence and ignores implementation, data, accessibility, support, and renewal differences.',
      'values committee preference but delays participation by users whose experience can reveal consequential adoption barriers.',
    ]),
  q('teaching-learning-04', 'application', 'apply',
    'A discussion platform displays student reading reflections publicly by default. What should the librarian do before using it for a required activity?',
    'Review privacy and audience settings, minimize collected data, establish an appropriate access level, and give students a clear supported workflow.',
    [
      'Use the default because public readership gives students an authentic audience and motivates careful writing.',
      'Tell students not to include personal information while leaving profiles, timestamps, and reflections publicly searchable.',
      'Let students opt out by accepting a zero for participation if they do not want their reflection posted online.',
    ],
    'Authentic audience should be intentionally matched to the learning purpose and learner safety, not inherited from a platform default. Data minimization, controlled access, transparent expectations, and an equivalent route support meaningful participation.',
    [
      'treats publicity as inherently beneficial and does not examine whether global disclosure is necessary or appropriate for the task.',
      'addresses explicit self-disclosure but leaves other identifying information and the required academic work exposed.',
      'offers formal choice through an academic penalty, so students do not have a genuinely equivalent participation option.',
    ]),
  q('teaching-learning-04', 'analysis', 'apply',
    'Students struggle to interpret a nineteenth-century letter because unfamiliar context and handwriting consume their attention. Which scaffold is best?',
    'Provide an accessible transcription, brief contextual supports, and guided sourcing questions while retaining examination of the original image.',
    [
      'Replace the letter with a textbook summary so students receive the historical conclusion without the decoding barrier.',
      'Read the letter aloud and tell students what it proves so class time remains focused on the correct interpretation.',
      'Require students to transcribe the entire letter before discussing author, audience, purpose, or historical context.',
    ],
    'A transcription and selective context reduce incidental access demands while preserving the primary-source reasoning target. Keeping the image allows students to notice material features, and guided questions support rather than replace interpretation.',
    [
      'removes the access barrier by removing the primary-source analysis that the learning task is intended to develop.',
      'supports decoding but supplies the interpretation, reducing student use of sourcing and corroboration evidence.',
      'turns a supportable handwriting difficulty into a lengthy prerequisite and postpones the central historical reasoning.',
    ]),
  q('teaching-learning-04', 'analysis', 'analyze',
    'During a project, groups use a shared document, but revision history shows that one student writes while others wait for directions. What should the co-teachers do?',
    'Clarify interdependent roles and decision points, monitor participation evidence, and require each learner to explain a substantive contribution.',
    [
      'Keep the workflow because a finished group document matters more than how students distribute the production work.',
      'Assign each student an isolated section and prevent peer revision so the document contains an equal number of words from everyone.',
      'Let the primary writer award participation scores because that student has the clearest view of the group\'s effort.',
    ],
    'Collaborative learning requires both a shared purpose and individual accountability. Structured roles should distribute meaningful reasoning rather than mere word counts, and multiple evidence sources help teachers intervene before the final product masks unequal learning.',
    [
      'judges output while ignoring whether each student practices the intended collaboration and inquiry decisions.',
      'creates measurable equality by removing authentic interdependence and may divide tasks without shared synthesis.',
      'delegates assessment authority to a peer in a power-laden role and relies on one perspective rather than planned evidence.',
    ]),
  q('teaching-learning-04', 'analysis', 'evaluate',
    'At the end of a media project, students can operate the editing software but cannot explain why they selected particular evidence. What should guide the next revision?',
    'Add planning checkpoints and reflection prompts that require evidence-based production choices, and assess those choices alongside technical execution.',
    [
      'Increase software practice time because greater fluency will lead students to make stronger evidence decisions implicitly.',
      'Remove technical criteria from the rubric and grade the written script as the sole indicator of media reasoning.',
      'Provide a fixed template that places each source in a prescribed location so every project displays evidence consistently.',
    ],
    'The evidence shows technical skill without the targeted reasoning. Making rationale visible during planning, production, and reflection aligns the technology with inquiry and gives feedback before choices are locked into the final artifact.',
    [
      'addresses the demonstrated strength rather than the missing reasoning and assumes tool fluency transfers without instruction.',
      'focuses on reasoning in one mode but abandons the legitimate integration of evidence and media-production decisions.',
      'standardizes placement while doing the design reasoning for students and may reward compliance rather than justification.',
    ]),
];
