const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm'),parser=require('@babel/parser'),traverse=require('@babel/traverse').default;
const {chromium}=require('playwright'),{GlHarness}=require('../anatomy-deep-review-2026-09-12/harness.cjs');
const source=fs.readFileSync('stem_lab/stem_tool_anatomy.js','utf8');let systemsNode;traverse(parser.parse(source),{VariableDeclarator(p){if(p.node.id.name==='SYSTEMS')systemsNode=p.node.init;}});const systems=vm.runInNewContext('('+source.slice(systemsNode.start,systemsNode.end)+')',{t:(k,f)=>f});
const results={errors:[],screens:[],quizSequence:[],relationships:[]};
(async()=>{
 const h=new GlHarness({toolFile:'stem_lab/stem_tool_anatomy.js',toolId:'anatomy',width:1120,height:1600,appStyles:true});await h.start();const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:1000},reducedMotion:'reduce'});page.on('pageerror',e=>results.errors.push(e.message));
 await page.addInitScript(()=>{window.__auditChecks=[];const p=CanvasRenderingContext2D.prototype;for(const name of ['beginPath','moveTo','lineTo','stroke']){const original=p[name];p[name]=function(...args){if(name==='beginPath')this.__auditPath=[];if(name==='moveTo'||name==='lineTo'){this.__auditPath=this.__auditPath||[];this.__auditPath.push([name,...args]);}if(name==='stroke'&&this.strokeStyle==='#16a34a'&&this.lineWidth===3){window.__auditChecks.push({path:this.__auditPath,canvasWidth:this.canvas.width,canvasHeight:this.canvas.height});if(window.__auditChecks.length>30)window.__auditChecks.shift();}return original.apply(this,args);};}});
 async function state(patch={},grade='9'){await page.evaluate(({patch,grade})=>{window.__ctx.gradeLevel=grade;window.__ctx.t=(k,f)=>f;window.__announcements=[];window.__ctx.announceToSR=text=>window.__announcements.push(text);window.__auditChecks=[];window.__ctx.setToolData(p=>({...p,anatomy:{_bodyView3d:false,_activeTab:'quiz',system:'skeletal',view:'anterior',complexity:3,...patch}}));},{patch,grade});}
 async function data(){return page.evaluate(()=>window.__ctx.toolData.anatomy);}
 const quiz=()=>page.locator('[data-anatomy-quiz-panel]');
 async function snap(name,locator){await locator.screenshot({path:path.join(__dirname,name+'.png')});results.screens.push(name);}
 async function focus(){return page.evaluate(()=>({tag:document.activeElement.tagName,label:document.activeElement.getAttribute('aria-label'),quizPanel:document.activeElement.hasAttribute('data-anatomy-quiz-panel'),text:document.activeElement.textContent.slice(0,90)}));}
 try{
  await h.mount(page,{anatomy:{_bodyView3d:false,_activeTab:'quiz',complexity:3}},undefined,{expectCanvas:false});await page.addStyleTag({content:'html,body{background:white}#wrap{height:auto;min-height:100%;width:min(1120px,100%);margin:auto}'});await state();
  let d=await data();const n=d._quizQuestion.poolIds.length,index=Math.ceil(n/4)*4;await state({quizIdx:index});d=await data();const lap=Math.floor(index/Math.max(n,4)),correctId=d._quizQuestion.poolIds[(index+lap)%n],drawnId=d._quizQuestion.poolIds[index%n];
  results.marker={poolLength:n,index,lap,correctId,drawnId,question:await quiz().innerText()};await quiz().locator('[data-anatomy-quiz-option="'+correctId+'"]').click();await page.waitForFunction(()=>window.__auditChecks.length>0);const check=await page.evaluate(()=>window.__auditChecks.at(-1));const expected=systems.skeletal.structures.find(s=>s.id===correctId),target=systems.skeletal.structures.find(s=>s.id===correctId);results.marker={...results.marker,storedFeedback:(await data()).quizFeedback,drawCall:check,markerCenter:{x:check.path[0][1]+6,y:check.path[0][2]},drawnStructure:{id:drawnId,x:expected.x*360,y:expected.y*520},correctStructure:{id:correctId,x:target.x*360,y:target.y*520}};assert.notEqual(correctId,drawnId);assert.equal(results.marker.markerCenter.x,expected.x*360);assert.equal(results.marker.markerCenter.y,expected.y*520);await snap('quiz-later-lap-feedback',quiz());await snap('quiz-later-lap-diagram',page.locator('.anatomy-canvas-frame').first());
  await state({quizIdx:1});for(let count=0;count<6;count++){d=await data();const i=d.quizIdx;const answer=d._quizQuestion.binaryTrue?'true':'false';await quiz().locator('[data-anatomy-quiz-option="'+answer+'"]').click();results.quizSequence.push({index:i,answer,correct:(await data()).quizFeedback.correct});await state({quizIdx:i+4});}assert.ok(results.quizSequence.every(x=>x.correct));assert.equal(new Set(results.quizSequence.map(x=>x.answer)).size,2);assert.ok(results.quizSequence.some((x,i,a)=>i&&x.answer===a[i-1].answer));
  await state({quizIdx:n-1,quizScore:n-1,_quizAttempts:n-1});results.progress={before:await quiz().innerText()};await quiz().locator('[data-anatomy-quiz-option]').first().click();await quiz().getByRole('button',{name:'Next Question',exact:true}).click();results.progress.after=await quiz().innerText();results.progress.focusAfterNext=await focus();results.progress.saved=await data();await snap('quiz-cycle-wrap',quiz());
  await state();await quiz().focus();await page.keyboard.press('1');await quiz().getByRole('button',{name:'Next Question',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.activeElement.hasAttribute('data-anatomy-quiz-panel'));results.keyboard={focusAfterNext:await focus(),attemptsBefore:(await data())._quizAttempts};await page.keyboard.press('1');results.keyboard.attemptsAfter=(await data())._quizAttempts;assert.equal(results.keyboard.focusAfterNext.quizPanel,true);assert.equal(results.keyboard.attemptsAfter,results.keyboard.attemptsBefore+1);
  await state({system:'organs',view:'posterior'});const organPool=(await data())._quizQuestion.poolIds;let kidneyIndex;for(let i=3;i<100;i+=4){const lap=Math.floor(i/Math.max(organPool.length,4));if(organPool[(i+lap)%organPool.length]==='kidneys'){kidneyIndex=i;break;}}assert.notEqual(kidneyIndex,undefined);await state({system:'organs',view:'posterior',quizIdx:kidneyIndex});results.clinical={index:kidneyIndex,question:await quiz().innerText()};await quiz().locator('[data-anatomy-quiz-option="kidneys"]').click();results.clinical.feedback=await quiz().getByRole('status').innerText();results.clinical.links=await quiz().locator('a').evaluateAll(nodes=>nodes.map(n=>n.href));assert.ok(results.clinical.links.some(url=>url.includes("kdigo")));assert.ok(results.clinical.feedback.includes("not an automatic start rule"));assert.ok(results.clinical.question.includes("Which paired organs"));await snap('kidney-quiz-feedback',quiz());
  for(const id of ['kidneys','liver','thyroid']){await state({_activeTab:'explore',system:'organs',view:id==='kidneys'?'posterior':'anterior',selectedStructure:id});const map=page.locator('[data-anatomy-relationship-map]');results.relationships.push({id,text:await map.innerText(),connections:await map.locator('[data-relationship-connection]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-relationship-connection')))});if(id==='kidneys')await snap('kidney-relationship-map',map);}
  await state({_activeTab:'imaging',imaging:{region:'head',plane:'axial',modality:'CT',slice:50,tool:'pin',annotations:[]}});const scan=page.locator('[data-anatomy-imaging-canvas]'),spot=page.locator('[data-anatomy-spot-challenge]');await spot.getByRole('button',{name:'Start spot challenge',exact:true}).click();results.imaging={initial:(await data()).imaging};await scan.focus();await page.keyboard.press('Enter');results.imaging.afterAnswer=(await data()).imaging;await page.keyboard.press('Enter');results.imaging.afterSecondEnter=(await data()).imaging;assert.equal(results.imaging.afterAnswer.spot.total,1);assert.equal(results.imaging.afterSecondEnter.annotations.length,0);assert.equal(results.imaging.afterSecondEnter.spot.total,1);await snap('imaging-second-enter',spot);
  await state({_activeTab:'imaging',imaging:{region:'head',plane:'axial',modality:'CT',slice:50,tool:'pin',annotations:[],kbX:.5,kbY:.5}});const box=await scan.boundingBox();await scan.click({position:{x:box.width*.3,y:box.height*.35}});results.cursor={saved:(await data()).imaging,expectedNormalizedPoint:{x:(.3-44/640)/(552/640),y:(.35-28/480)/(408/480)}};
  await state({_activeTab:'imaging',imaging:{region:'head',plane:'axial',modality:'CT',slice:50,compareModalities:true}});const compare=page.locator('[data-anatomy-modality-compare]');const firstQuestion=compare.locator('[data-anatomy-modality-check] .space-y-2');results.modality={before:await compare.innerText()};const buttons=compare.getByRole('button',{name:'CT',exact:true});await buttons.first().click();results.modality.after=await compare.innerText();await snap('modality-explanations',compare);
  // A retained answer callback is a lifecycle probe, not a claim about ordinary pointer timing.
  await state();await quiz().locator('[data-anatomy-quiz-option="skull"]').evaluate(node=>{const key=Object.keys(node).find(k=>k.startsWith('__reactProps$'));window.__retainedAnswer=node[key].onClick;});await state({_activeTab:'explore',_retrievalEvidence:{femur:{attempts:7,correct:6}},_structureConfidence:{femur:'mastered'}});results.retainedAnswer={before:await data()};await page.evaluate(()=>window.__retainedAnswer());results.retainedAnswer.after=await data();for(const key of ['_retrievalEvidence','_structureConfidence','quizFeedback','_quizAttempts','quizScore'])assert.deepEqual(results.retainedAnswer.after[key],results.retainedAnswer.before[key]);

  assert.deepEqual(results.relationships.map(x=>x.connections),[[],['conn_9'],['conn_6']]);
  assert.ok(Math.abs(results.cursor.saved.kbX-results.cursor.expectedNormalizedPoint.x)<.01);
  assert.ok(Math.abs(results.cursor.saved.kbY-results.cursor.expectedNormalizedPoint.y)<.01);
  assert.ok(results.modality.after.includes('no ionizing radiation'));assert.ok(results.modality.after.includes('MR safety conditions'));
  results.brain=[];results.axe=[];results.languages=[];
  await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
  async function audit(name,scope){const r=await page.evaluate(async scope=>{const r=await axe.run(scope,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return {violations:r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),incomplete:r.incomplete.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))};},scope);results.axe.push({name,...r});assert.deepEqual(r.violations,[]);}
  for(const grade of ['1','4','7','9']){await state({_activeTab:'explore',system:'nervous',selectedStructure:'brain',complexity:Number(grade)<=5?1:Number(grade)<=8?2:3},grade);const detail=page.locator('[data-anatomy-structure-detail]');const waves=await detail.locator('[data-anatomy-wave]').count();assert.equal(waves,Number(grade)<=5?0:5);assert.equal(await detail.locator('[data-anatomy-clinical-note]').count(),Number(grade)<=5?0:1);assert.equal((await detail.innerText()).includes('= ADHD'),false);results.brain.push({grade,waves});}
  await state({_activeTab:'explore',selectedStructure:'skull',_compareStructure:'femur',complexity:1},'1');assert.equal(await page.locator('[data-anatomy-clinical-note="femur"]').count(),0);
  for(const width of [1280,390,320]){await page.setViewportSize({width,height:1000});await state({_activeTab:'explore',system:'nervous',selectedStructure:'brain'});const brain=page.locator('[data-anatomy-brain-study]');await brain.locator('[data-anatomy-sleep-answer="late"]').click();assert.ok((await brain.getByRole('status').innerText()).includes('That matches'));await audit('brain-'+width,'[data-anatomy-brain-study]');await snap('brain-'+width,brain);await brain.locator('[data-anatomy-eeg-details] > summary').click();await brain.locator('[data-anatomy-sleep-details] > summary').click();await audit('brain-expanded-'+width,'[data-anatomy-brain-study]');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===320){await snap('brain-expanded-320',brain);await page.evaluate(()=>document.body.classList.add('theme-dark'));await audit('brain-dark-320','[data-anatomy-brain-study]');await snap('brain-dark-320',brain);await page.evaluate(()=>document.body.classList.remove('theme-dark'));}}
  for(const lang of ['french','spanish_latin_america','arabic']){await state({_activeTab:'explore',system:'skeletal',selectedStructure:'hyoid',vocabLookedUp:['Cranium']});const dict=JSON.parse(fs.readFileSync('lang/'+lang+'.js','utf8')).stem.anatomy;await page.evaluate(({dict,lang})=>{window.__ctx.t=(key,f)=>dict[key.slice(13)]||f;document.getElementById('wrap').dir=lang==='arabic'?'rtl':'ltr';document.documentElement.lang=lang==='arabic'?'ar':lang==='french'?'fr':'es';window.__ctx.setToolData(p=>({...p,anatomy:{...p.anatomy}}));},{dict,lang});const vocab=page.locator('[data-anatomy-vocabulary]');if(await vocab.getAttribute('open')===null)await vocab.locator(':scope > summary').click();if(await vocab.locator('details').getAttribute('open')===null)await vocab.locator('details > summary').click();assert.equal(await vocab.locator('[data-anatomy-vocab-term]').count(),10);assert.equal(await vocab.locator('[data-anatomy-study-term="cranium"]').count(),0);await vocab.locator('[data-anatomy-study-term="hyoid"]').click();assert.deepEqual((await data()).vocabLookedUp,['cranium','hyoid']);assert.equal((await data()).totalRP,5);await audit('vocabulary-'+lang,'[data-anatomy-vocabulary]');await snap('vocabulary-'+lang,vocab);results.languages.push(lang);}
  await page.setViewportSize({width:1280,height:1000});await page.evaluate(()=>{document.getElementById('wrap').dir='ltr';document.documentElement.lang='en';});
  await state({_activeTab:'aiTutor',system:'organs',view:'posterior',selectedStructure:'kidneys'});await page.evaluate(()=>{window.__ctx.callGemini=prompt=>{window.__testPrompt=prompt;return Promise.resolve({text:'Reviewed context received.'});};});
  await page.getByRole('textbox',{name:'Ask the anatomy AI tutor a question',exact:true}).fill('What affects dialysis decisions?');await page.getByRole('button',{name:'Ask',exact:true}).click();await page.waitForFunction(()=>!!window.__testPrompt);results.tutorPrompt=await page.evaluate(()=>window.__testPrompt);assert.ok(results.tutorPrompt.includes('KDIGO'));assert.ok(results.tutorPrompt.includes('not an automatic start rule'));assert.ok(results.tutorPrompt.includes('Why might two people'));
  assert.deepEqual(results.errors,[]);
 }finally{fs.writeFileSync(__dirname+'/browser-results.json',JSON.stringify(results,null,2)+'\n');await h.destroy(page);await browser.close();await h.stop();}
 console.log(JSON.stringify({marker:results.marker,quizSequence:results.quizSequence,keyboard:results.keyboard,clinical:results.clinical,relationships:results.relationships,imaging:results.imaging,cursor:results.cursor,errors:results.errors,screenshots:results.screens.length},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
