'use strict';
const q=(skillId,difficulty,cognitiveLevel,prompt,correct,distractors,rationale,whyWrong)=>({skillId,difficulty,cognitiveLevel,prompt,correct,distractors,rationale,whyWrong});
module.exports=[
q('physical-earth-science','analysis','analyze','A child reports, “The metal spoon feels colder than the wooden spoon.” Which follow-up asks for an observation rather than an inference?',
'“What temperature does a thermometer show for each spoon?”',
['“Why do you think metal always creates cold?”','“Which spoon probably wants to become warmer?”','“Does the feeling prove that the spoons came from different rooms?”'],
'Thermometer readings add measurable observations. Questions about causes, intentions, or proof ask for interpretations that go beyond directly gathered evidence.',
['builds an unsupported causal claim and uses an absolute rather than requesting observable data.','attributes intention to objects and does not elicit sensory or instrument-based evidence.','asks for a conclusion about location that cannot be established from the reported touch observation alone.']),
q('physical-earth-science','application','apply','Children test whether ramp height affects how far a toy car travels. Which plan creates the fairest comparison?',
'Use the same car and surface, change only ramp height, and measure distance from the same starting point.',
['Change the car, ramp height, and floor surface for every trial.','Push one car by hand but release the other car without a push.','Record only the trial that travels farthest and discard the remaining measurements.'],
'A fair comparison varies the factor of interest while holding relevant conditions consistent and measuring the outcome in the same way.',
['changes several variables, so differences in travel distance cannot be attributed to ramp height.','introduces unequal initial forces that confound the intended comparison.','selects evidence after seeing results and prevents analysis of variation across trials.']),
q('physical-earth-science','analysis','analyze','Three bean plants near a window grew 8, 9, and 9 cm; three in a cabinet grew 1, 0, and 2 cm. Which claim best matches the evidence?',
'Under these tested conditions, the plants near the window grew more than those in the cabinet.',
['Window light guarantees identical growth for every kind of plant in every setting.','The cabinet caused all seeds to die because one plant grew zero centimeters.','Plant growth is unrelated to conditions because the measurements are not all equal.'],
'The measured groups support a bounded comparison for this investigation. They do not justify universal guarantees or conclusions beyond the tested plants and conditions.',
['generalizes far beyond a small study and promises identical outcomes despite biological and environmental variation.','overstates one zero-growth result and ignores two cabinet plants that showed some growth.','mistakes natural variation for absence of a group pattern even though the measurements differ substantially.']),
q('physical-earth-science','developing','understand','Which change is a physical change in matter?',
'An ice cube melts into liquid water.',
['Iron forms rust after exposure to oxygen and moisture.','Wood burns and produces ash and gases.','Milk sours and develops new substances and odors.'],
'Melting changes the state of water without changing its chemical identity. Rusting, burning, and souring involve evidence that new substances formed.',
['is an oxidation process that forms iron oxide with properties different from the original metal.','produces new substances through combustion and is not merely a change of state or shape.','involves chemical changes caused by microbial activity rather than a reversible state change.']),
q('physical-earth-science','analysis','analyze','A child says a larger ball must roll faster down every ramp. What investigation would best test the claim?',
'Release different-size balls from the same point on the same ramp and measure their travel times across repeated trials.',
['Roll the large ball down a steep ramp and the small ball across carpet.','Ask classmates which ball looks fastest without moving either ball.','Test only one large ball once and compare it with no other object.'],
'The plan compares ball size while controlling ramp and release conditions, measures speed-related evidence, and repeats trials to examine consistency.',
['changes ramp and surface along with size, so any speed difference has multiple possible causes.','collects opinions based on appearance rather than observations of motion.','provides neither a comparison nor repeated evidence capable of testing the general claim.']),
q('physical-earth-science','application','apply','A flashlight shines on an opaque block. What change will generally make the shadow on a nearby wall larger?',
'Move the block closer to the flashlight while keeping the wall fixed.',
['Replace the opaque block with clear glass of the same size.','Turn off the flashlight and rely on the block to produce light.','Move the block behind the wall so it is outside the light path.'],
'Moving an opaque object closer to a pointlike light source makes it intercept a wider portion of diverging light rays, enlarging the projected shadow.',
['increases light transmission and usually weakens rather than reliably enlarges an opaque shadow.','removes the light source required to create a projected shadow.','places the object where it cannot block light traveling from the source to the wall.']),
q('physical-earth-science','application','apply','A rubber band produces a higher pitch after it is tightened. Which explanation is most accurate?',
'Greater tension lets the band vibrate faster, producing a higher-frequency sound.',
['The tighter band stops vibrating, so silence is interpreted as high pitch.','Pitch increases because the band becomes brighter in color.','The band creates sound without moving any surrounding matter.'],
'Pitch corresponds to vibration frequency. Increasing tension can increase the band’s vibration rate, while the vibration transfers energy through surrounding matter as sound.',
['contradicts the observed sound because a nonvibrating band would not generate that tone.','uses an unrelated visual property rather than the band’s mechanical vibration.','ignores that sound is a mechanical wave transmitted through matter such as air.']),
q('physical-earth-science','analysis','analyze','A week is unusually cold in a region that is usually warm. Which statement uses weather and climate accurately?',
'The cold week is weather; climate is described from longer-term regional patterns that can include unusual weeks.',
['The cold week permanently changes the region’s climate classification by itself.','Climate means today’s temperature, while weather means a thirty-year pattern.','The cold measurements should be removed because climate data cannot include unusual events.'],
'Weather refers to short-term atmospheric conditions, whereas climate summarizes distributions and patterns over longer periods. One event is evidence within, not a replacement for, that record.',
['infers a durable pattern from a brief event without sufficient time-scale evidence.','reverses the standard meanings of weather and climate.','would bias the record by excluding real variation and extreme conditions that are part of climate analysis.']),
q('physical-earth-science','developing','understand','What primarily causes the daily pattern of day and night?',
'Earth rotates on its axis, turning locations toward and away from the Sun.',
['The Sun travels around Earth once every twenty-four hours.','Earth moves much closer to the Sun during each daytime period.','Clouds cover the Sun on a fixed schedule to create night.'],
'As Earth rotates approximately once each day, a location alternately faces the Sun and turns away, producing the observed day-night cycle.',
['uses an Earth-centered model and misidentifies the apparent daily motion as the Sun orbiting Earth.','confuses rotation with a dramatic daily change in Earth-Sun distance that does not occur.','attributes an astronomical pattern to variable weather and cannot explain clear nights.']),
q('life-science-engineering','analysis','analyze','Children sequence pictures of a butterfly egg, caterpillar, chrysalis, and adult. Which explanation is accurate?',
'The pictures show patterned life-cycle stages, and the adult can reproduce to begin a new cycle.',
['The caterpillar is a different species because its body form differs from the adult.','The chrysalis is a nonliving container unrelated to the organism.','Every animal passes through these exact four stages in the same form.'],
'Butterflies undergo complete metamorphosis across distinct stages of one organism’s life cycle. Life-cycle patterns vary among animal groups.',
['mistakes developmental change within one species for a change of species identity.','misclassifies a living developmental stage in which major transformation occurs.','overgeneralizes a butterfly pattern to animals with different reproductive and developmental sequences.']),
q('life-science-engineering','application','apply','A seedling’s roots are covered and watered while its leaves receive light. What primary root function can children observe by adding colored water?',
'Roots absorb water that can move into the plant.',
['Roots capture sunlight to make all of the plant’s food.','Roots produce flowers before stems and leaves develop.','Roots turn soil directly into sugar without water or air.'],
'Colored water moving from the root region into plant tissues provides visible evidence of water uptake and transport. Photosynthesis occurs mainly in light-exposed green tissues.',
['assigns the primary light-capturing role of leaves to roots that are covered from light.','describes a reproductive structure that roots do not directly generate in the proposed observation.','misstates plant nutrition and ignores photosynthesis, water uptake, and gas exchange.']),
q('life-science-engineering','analysis','analyze','In the chain grass → grasshopper → frog, what happens to energy?',
'Energy captured by grass is transferred through feeding to the grasshopper and then the frog, with less usable energy at each step.',
['The grass obtains energy by consuming the grasshopper underground.','Energy cycles unchanged from the frog back to the Sun.','The arrows rank organisms from least important to most important.'],
'Food-chain arrows represent transfer of matter and energy from a resource to a consumer. Energy enters through producers and some dissipates as heat at each transfer.',
['reverses producer-consumer relationships because grass captures light energy rather than eating an animal.','confuses matter cycling with one-way energy flow and incorrectly sends energy back to its source unchanged.','interprets feeding relationships as value judgments instead of transfers within an ecosystem.']),
q('life-science-engineering','application','apply','Children must design a shade structure that covers a toy and uses no more than ten craft sticks. Which statement identifies a constraint?',
'The design may use at most ten craft sticks.',
['The structure should keep the toy in shade.','The team will compare two possible designs.','The children want the structure to look welcoming.'],
'A constraint limits a solution, here by capping material use. Keeping the toy shaded is a performance criterion, and comparison is part of the design process.',
['states the desired function used to judge success, making it a criterion rather than a resource limit.','describes an evaluation action rather than a boundary on acceptable solutions.','expresses a preference that would need operational definition before serving as a criterion or constraint.']),
q('life-science-engineering','analysis','analyze','A paper bridge holds six blocks and then bends. What is the most evidence-based next design step?',
'Identify where bending began, revise one feature such as support placement, and retest under the same loading procedure.',
['Declare the first design successful because it held at least one block.','Change several features and the test method simultaneously so the new result cannot be compared.','Hide the bending result and report only the strongest trial.'],
'Engineering improvement uses failure evidence to target a revision and comparable retesting. Changing one interpretable feature helps connect design decisions with performance.',
['ignores the stated performance evidence and avoids evaluating whether the design met its intended criterion.','confounds the redesign and the measurement, preventing a defensible comparison.','selectively removes relevant evidence and produces a misleading account of performance and variability.'])
];
