'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),fixture=require('../novak-gloss-enhancements/macbeth-act1-scene1.fixture.json');
const checks=[],errors=[],externalRequests=[];const addCheck=checks.push.bind(checks);checks.push=message=>{console.log('[journey] '+message);return addCheck(message);};
async function main(){
 const initialEvidence=require('./build-seams.cjs').buildSeams();
 await require('esbuild').build({entryPoints:[path.join(__dirname,'fixture.jsx')],bundle:true,outfile:path.join(__dirname,'fixture.js'),platform:'browser',format:'iife',define:{'process.env.NODE_ENV':'"production"'}});
 const css=fs.readdirSync(path.join(root,'desktop/web-app/build/static/css')).find(name=>name.endsWith('.css'));
 const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Local Macbeth classroom journey</title><link rel="stylesheet" href="/app.css"><style>body{margin:0;background:#f8fafc;color:#0f172a;font-family:Arial,sans-serif}button,input,select,textarea{font:inherit}button{min-height:44px;padding:.5rem;border:1px solid #94a3b8;border-radius:.4rem}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #4338ca;outline-offset:3px}select{max-width:100%}</style><div id="root"></div><script src="/purify.js"></script><script src="/strings.js"></script><script src="/fixture.js"></script></html>';
 const files={'/purify.js':path.join(root,'dompurify/3.1.7/purify.min.js'),'/fixture.js':path.join(__dirname,'fixture.js'),'/strings.js':path.join(root,'reports/novak-feedback-implementation/strings.js'),'/app.css':path.join(root,'desktop/web-app/build/static/css',css)};
 const fileBodies=Object.fromEntries(Object.entries(files).map(([name,file])=>[name,fs.readFileSync(file)]));
 const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;if(files[name]){res.setHeader('Content-Type',name.endsWith('.css')?'text/css':'application/javascript');res.end(fileBodies[name]);}else if(name==='/'){res.setHeader('Content-Type','text/html');res.end(html);}else{res.writeHead(404).end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;let browser;
 try{
  browser=await chromium.launch({headless:true,channel:'msedge'});
  async function context(){const ctx=await browser.newContext({viewport:{width:1280,height:1000}});await ctx.route('**/*',route=>{if(new URL(route.request().url()).origin===origin)return route.continue();externalRequests.push(route.request().url());return route.abort();});return ctx;}
  const teacherContext=await context(),teacher=await teacherContext.newPage();teacher.on('pageerror',error=>errors.push('teacher: '+error.message));await teacher.goto(origin,{waitUntil:'domcontentloaded',timeout:90000});await teacher.getByRole('button',{name:'Open original',exact:true}).click();await teacher.locator('[data-original-source]').waitFor();
  const state=page=>page.evaluate(()=>window.journey.snapshot());
  const originalOf=value=>value.history.find(row=>row.instructionalText?.form==='same-text-supported'&&row.unitId==='macbeth-lesson');
  const sourceBody=page=>page.locator('[data-original-source]').evaluate(node=>{const copy=node.cloneNode(true);copy.querySelectorAll('[data-reading-gloss]').forEach(gloss=>gloss.remove());return copy.textContent;});
  assert.equal(await sourceBody(teacher),fixture.text);assert.equal(await teacher.evaluate(()=>window.journey.mockProviderCalls),0);checks.push('Production host opens exact Macbeth without AI');
  await teacher.getByRole('button',{name:'Add word supports',exact:true}).click();await teacher.getByRole('button',{name:'Refresh suggested supports',exact:true}).waitFor();assert.equal(await teacher.evaluate(()=>window.journey.mockProviderCalls),1);
  await teacher.getByRole('button',{name:'Edit explanation for heath',exact:true}).click();const explanation=teacher.getByRole('textbox',{name:'Explanation',exact:true});await explanation.fill('open, uncultivated land <teacher wording>');await teacher.locator('[data-gloss-draft]').getByRole('checkbox',{name:'Always show in lighter view',exact:true}).check();await teacher.getByRole('button',{name:'Save word support',exact:true}).click();
  await teacher.getByRole('button',{name:/^Remove gloss for Paddock,/}).click();await teacher.getByRole('button',{name:'Done editing',exact:true}).click();await teacher.getByRole('button',{name:'Refresh suggested supports',exact:true}).click();await teacher.getByRole('button',{name:'Refresh suggested supports',exact:true}).waitFor();
  let original=originalOf(await state(teacher));assert.equal(original.readingSupports.annotations.find(row=>row.quote==='heath').text,'open, uncultivated land <teacher wording>');assert.equal(original.readingSupports.annotations.find(row=>row.quote==='heath').pinned,true);assert.equal(original.readingSupports.annotations.find(row=>row.quote==='heath').origin,'educator');assert.equal(original.readingSupports.annotations.some(row=>row.quote==='Paddock'),false);assert.equal(await sourceBody(teacher),fixture.text);checks.push('Actual curation/updater and production generator preserve teacher wording, pins, removals, and exact source across a mocked refresh');
  await teacher.getByRole('button',{name:'Save teacher history',exact:true}).click();await teacher.reload();await teacher.locator('[data-original-source]').waitFor();original=originalOf(await state(teacher));assert.equal(original.data,fixture.text);assert.equal(original.readingSupports.annotations.find(row=>row.quote==='heath').pinned,true);assert.ok(original.readingSupports.suppressedAnnotations.some(row=>row.quote==='Paddock'));checks.push('Production offline serializer and hydrator retain source and curation after real browser reload');
  await teacher.getByRole('button',{name:'Add prepared adapted sample',exact:true}).click();await teacher.locator('[data-reading-comparison]').waitFor();await teacher.evaluate(()=>window.journey.addUnrelated());await teacher.getByRole('button',{name:'Package selected adaptation',exact:true}).click();await teacher.waitForFunction(()=>window.journey.encoded||window.journey.error);assert.equal(await teacher.evaluate(()=>window.journey.error),undefined);
  const encoded=await teacher.evaluate(()=>window.journey.encoded),packet=await teacher.evaluate(()=>window.journey.teacherPacket);assert.deepEqual(packet.resources.map(row=>row.id),['prepared-adapted-macbeth',original.id]);assert.equal(packet.currentResourceId,'prepared-adapted-macbeth');assert.equal(JSON.stringify(packet).includes('WRONG LESSON GLOSS'),false);assert.equal(JSON.stringify(packet).includes('PRIVATE TEACHER ANALYSIS'),false);assert.equal(JSON.stringify(packet).includes('MOCK OPTIONAL NOTE TO REMOVE'),false);checks.push('Selected-assignment resolver, builder, privacy serializer and real pack codec include only the chosen adaptation and its curated original');
  fs.writeFileSync(path.join(__dirname,'student-packet.json'),JSON.stringify(packet,null,2));await teacher.screenshot({path:path.join(__dirname,'teacher-pair.png'),fullPage:true});
  const studentContext=await context(),student=await studentContext.newPage();student.on('pageerror',error=>errors.push('student: '+error.message));await student.goto(origin+'/?student=1#allo_pack='+encodeURIComponent(encoded),{waitUntil:'domcontentloaded',timeout:90000});await student.waitForFunction(()=>window.journey.loaderRequests===1||window.journey.loadError);assert.equal((await state(student)).current,null);assert.equal(await student.evaluate(()=>window.journey.pendingSnapshot().sourceSnapshot.text),fixture.text);await student.evaluate(()=>window.journey.releaseOpener());await student.waitForFunction(()=>window.journey.snapshot().current||window.journey.loadError);assert.equal(await student.evaluate(()=>window.journey.restoreCalls),1);assert.equal(await student.evaluate(()=>window.journey.pendingSnapshot()),null);checks.push('Actual lazy readiness helper, pending restore effect, wrapper and MiscHandlers opener retain the decoded packet until delayed registration and open it exactly once');assert.equal(await student.evaluate(()=>window.journey.loadError),undefined);assert.equal((await state(student)).current.id,packet.currentResourceId);assert.equal(await student.evaluate(()=>window.journey.mockProviderCalls),0);
  await student.getByRole('button',{name:'Both',exact:true}).click();await student.locator('[data-reading-comparison]').waitFor();const bodies=await student.locator('[data-compare-version]').evaluateAll(nodes=>nodes.map(node=>{const copy=node.cloneNode(true);copy.querySelectorAll('[data-reading-gloss]').forEach(gloss=>gloss.remove());return {version:node.getAttribute('data-compare-version'),text:copy.textContent};}));assert.ok(bodies.some(row=>row.text===fixture.text));assert.ok(await student.locator('[data-reading-gloss]').filter({hasText:'open, uncultivated land <teacher wording>'}).count()>0);assert.equal(await student.getByRole('button',{name:/^Review word supports/}).count(),0);await student.screenshot({path:path.join(__dirname,'student-both-desktop.png'),fullPage:true});checks.push('Separate student browser context displays matching original, adaptation, and teacher gloss without teacher editing controls');
  await student.getByRole('button',{name:'Original',exact:true}).click();await student.locator('[data-original-source]').waitFor();assert.equal(await sourceBody(student),fixture.text);await student.getByRole('combobox',{name:'Gloss density',exact:true}).selectOption('light');assert.ok(await student.locator('[data-reading-gloss]').filter({hasText:'open, uncultivated land <teacher wording>'}).count()>0);await student.setViewportSize({width:320,height:900});assert.equal(await student.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await student.screenshot({path:path.join(__dirname,'student-original-320.png'),fullPage:true});checks.push('Student Original and lighter gloss view preserve source and pinned support at 320px');
  await student.getByRole('button',{name:'Render student document',exact:true}).click();const exportHTML=await student.evaluate(()=>window.journey.exportHTML);assert.ok(exportHTML);fs.writeFileSync(path.join(__dirname,'student-export.html'),exportHTML);const exported=await student.evaluate(html=>{const doc=new DOMParser().parseFromString(html,'text/html');return {source:doc.querySelector('[data-original-text]')?.textContent,notes:doc.querySelector('.reading-support-notes')?.textContent,unsafe:!!doc.querySelector('teacher'),body:doc.body.textContent};},exportHTML);assert.equal(exported.source,fixture.text);assert.ok(exported.notes.includes('open, uncultivated land <teacher wording>'));assert.equal(exported.unsafe,false);assert.equal(exported.body.includes('MOCK OPTIONAL NOTE TO REMOVE'),false);checks.push('Actual common document pipeline preserves exact received source and separately escaped curated glosses');
  assert.deepEqual(errors,[]);assert.deepEqual(externalRequests,[]);const finalEvidence=require('./build-seams.cjs').buildSeams();assert.deepEqual(finalEvidence.map(({file,sha256})=>({file,sha256})),initialEvidence.map(({file,sha256})=>({file,sha256})));checks.push('Production source regions and module hashes remained unchanged throughout this run');checks.push('No browser runtime errors or external network requests');
  fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({status:'passed',checkedAt:new Date().toISOString(),checks,errors,externalRequests,sourceSha256:fixture.sha256,packetEncoding:encoded.slice(0,2),scope:'Production seams and modules in a local React host; canned gloss provider, pre-authored adaptation, and mocked audio. Separate teacher/student browser contexts. Not the entire app shell, live services, real speech, native screen readers, or live model quality.'},null,2));console.log(JSON.stringify({checks,errors,externalRequests},null,2));
 }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({status:'failed',checkedAt:new Date().toISOString(),checks,errors,error:error.stack,externalRequests},null,2));console.error(error);process.exitCode=1;});