// Generated by dev-tools/generate_cellatlas_real_snapshot.py
// Aggregate-only snapshot; do not edit by hand.
(function (root) {
  'use strict';
  root.__alloCellAtlasRealSnapshots = root.__alloCellAtlasRealSnapshots || {};
  root.__alloCellAtlasRealSnapshots.muraroPancreas = {
    "cellTypes": {
      "acinar": {
        "available": true,
        "cellCount": 219,
        "donorCount": 4,
        "genes": {
          "COL3A1": {
            "detectedCells": 69,
            "detectionPct": 31.5,
            "meanRawCount": 4.822,
            "relativeMeanPct": 0.5
          },
          "GCG": {
            "detectedCells": 219,
            "detectionPct": 100.0,
            "meanRawCount": 397.274,
            "relativeMeanPct": 2.4
          },
          "INS": {
            "detectedCells": 107,
            "detectionPct": 48.9,
            "meanRawCount": 1.073,
            "relativeMeanPct": 0.5
          },
          "KDR": {
            "detectedCells": 2,
            "detectionPct": 0.9,
            "meanRawCount": 0.009,
            "relativeMeanPct": 0.0
          },
          "KRT19": {
            "detectedCells": 72,
            "detectionPct": 32.9,
            "meanRawCount": 6.402,
            "relativeMeanPct": 15.1
          },
          "PRSS1": {
            "detectedCells": 219,
            "detectionPct": 100.0,
            "meanRawCount": 569.274,
            "relativeMeanPct": 100.0
          },
          "PTPRC": {
            "detectedCells": 3,
            "detectionPct": 1.4,
            "meanRawCount": 0.027,
            "relativeMeanPct": 2.4
          },
          "SST": {
            "detectedCells": 219,
            "detectionPct": 100.0,
            "meanRawCount": 166.096,
            "relativeMeanPct": 0.2
          }
        },
        "sourceCellType": "pancreatic acinar cell"
      },
      "alpha": {
        "available": true,
        "cellCount": 812,
        "donorCount": 4,
        "genes": {
          "COL3A1": {
            "detectedCells": 221,
            "detectionPct": 27.2,
            "meanRawCount": 0.61,
            "relativeMeanPct": 0.1
          },
          "GCG": {
            "detectedCells": 812,
            "detectionPct": 100.0,
            "meanRawCount": 16600.989,
            "relativeMeanPct": 100.0
          },
          "INS": {
            "detectedCells": 422,
            "detectionPct": 52.0,
            "meanRawCount": 9.65,
            "relativeMeanPct": 4.4
          },
          "KDR": {
            "detectedCells": 8,
            "detectionPct": 1.0,
            "meanRawCount": 0.01,
            "relativeMeanPct": 0.0
          },
          "KRT19": {
            "detectedCells": 150,
            "detectionPct": 18.5,
            "meanRawCount": 0.514,
            "relativeMeanPct": 1.2
          },
          "PRSS1": {
            "detectedCells": 302,
            "detectionPct": 37.2,
            "meanRawCount": 1.161,
            "relativeMeanPct": 0.2
          },
          "PTPRC": {
            "detectedCells": 1,
            "detectionPct": 0.1,
            "meanRawCount": 0.002,
            "relativeMeanPct": 0.2
          },
          "SST": {
            "detectedCells": 811,
            "detectionPct": 99.9,
            "meanRawCount": 1120.14,
            "relativeMeanPct": 1.2
          }
        },
        "sourceCellType": "pancreatic A cell"
      },
      "beta": {
        "available": true,
        "cellCount": 448,
        "donorCount": 4,
        "genes": {
          "COL3A1": {
            "detectedCells": 101,
            "detectionPct": 22.5,
            "meanRawCount": 0.837,
            "relativeMeanPct": 0.1
          },
          "GCG": {
            "detectedCells": 448,
            "detectionPct": 100.0,
            "meanRawCount": 381.484,
            "relativeMeanPct": 2.3
          },
          "INS": {
            "detectedCells": 437,
            "detectionPct": 97.5,
            "meanRawCount": 220.996,
            "relativeMeanPct": 100.0
          },
          "KDR": {
            "detectedCells": 5,
            "detectionPct": 1.1,
            "meanRawCount": 0.02,
            "relativeMeanPct": 0.0
          },
          "KRT19": {
            "detectedCells": 35,
            "detectionPct": 7.8,
            "meanRawCount": 0.344,
            "relativeMeanPct": 0.8
          },
          "PRSS1": {
            "detectedCells": 163,
            "detectionPct": 36.4,
            "meanRawCount": 1.25,
            "relativeMeanPct": 0.2
          },
          "PTPRC": {
            "detectedCells": 3,
            "detectionPct": 0.7,
            "meanRawCount": 0.007,
            "relativeMeanPct": 0.6
          },
          "SST": {
            "detectedCells": 448,
            "detectionPct": 100.0,
            "meanRawCount": 1365.643,
            "relativeMeanPct": 1.5
          }
        },
        "sourceCellType": "type B pancreatic cell"
      },
      "delta": {
        "available": true,
        "cellCount": 193,
        "donorCount": 4,
        "genes": {
          "COL3A1": {
            "detectedCells": 43,
            "detectionPct": 22.3,
            "meanRawCount": 0.43,
            "relativeMeanPct": 0.0
          },
          "GCG": {
            "detectedCells": 193,
            "detectionPct": 100.0,
            "meanRawCount": 79.269,
            "relativeMeanPct": 0.5
          },
          "INS": {
            "detectedCells": 98,
            "detectionPct": 50.8,
            "meanRawCount": 7.13,
            "relativeMeanPct": 3.2
          },
          "KDR": {
            "detectedCells": 2,
            "detectionPct": 1.0,
            "meanRawCount": 0.01,
            "relativeMeanPct": 0.0
          },
          "KRT19": {
            "detectedCells": 56,
            "detectionPct": 29.0,
            "meanRawCount": 0.596,
            "relativeMeanPct": 1.4
          },
          "PRSS1": {
            "detectedCells": 59,
            "detectionPct": 30.6,
            "meanRawCount": 0.627,
            "relativeMeanPct": 0.1
          },
          "PTPRC": {
            "detectedCells": 0,
            "detectionPct": 0.0,
            "meanRawCount": 0.0,
            "relativeMeanPct": 0.0
          },
          "SST": {
            "detectedCells": 193,
            "detectionPct": 100.0,
            "meanRawCount": 93144.601,
            "relativeMeanPct": 100.0
          }
        },
        "sourceCellType": "pancreatic D cell"
      },
      "ductal": {
        "available": true,
        "cellCount": 246,
        "donorCount": 4,
        "genes": {
          "COL3A1": {
            "detectedCells": 59,
            "detectionPct": 24.0,
            "meanRawCount": 10.846,
            "relativeMeanPct": 1.2
          },
          "GCG": {
            "detectedCells": 246,
            "detectionPct": 100.0,
            "meanRawCount": 77.939,
            "relativeMeanPct": 0.5
          },
          "INS": {
            "detectedCells": 108,
            "detectionPct": 43.9,
            "meanRawCount": 1.797,
            "relativeMeanPct": 0.8
          },
          "KDR": {
            "detectedCells": 4,
            "detectionPct": 1.6,
            "meanRawCount": 0.02,
            "relativeMeanPct": 0.0
          },
          "KRT19": {
            "detectedCells": 220,
            "detectionPct": 89.4,
            "meanRawCount": 42.313,
            "relativeMeanPct": 100.0
          },
          "PRSS1": {
            "detectedCells": 129,
            "detectionPct": 52.4,
            "meanRawCount": 4.829,
            "relativeMeanPct": 0.8
          },
          "PTPRC": {
            "detectedCells": 16,
            "detectionPct": 6.5,
            "meanRawCount": 1.146,
            "relativeMeanPct": 100.0
          },
          "SST": {
            "detectedCells": 245,
            "detectionPct": 99.6,
            "meanRawCount": 123.199,
            "relativeMeanPct": 0.1
          }
        },
        "sourceCellType": "pancreatic ductal cell"
      },
      "endothelial": {
        "available": true,
        "cellCount": 21,
        "donorCount": 4,
        "genes": {
          "COL3A1": {
            "detectedCells": 3,
            "detectionPct": 14.3,
            "meanRawCount": 14.952,
            "relativeMeanPct": 1.7
          },
          "GCG": {
            "detectedCells": 21,
            "detectionPct": 100.0,
            "meanRawCount": 59.619,
            "relativeMeanPct": 0.4
          },
          "INS": {
            "detectedCells": 7,
            "detectionPct": 33.3,
            "meanRawCount": 0.476,
            "relativeMeanPct": 0.2
          },
          "KDR": {
            "detectedCells": 20,
            "detectionPct": 95.2,
            "meanRawCount": 113.619,
            "relativeMeanPct": 100.0
          },
          "KRT19": {
            "detectedCells": 0,
            "detectionPct": 0.0,
            "meanRawCount": 0.0,
            "relativeMeanPct": 0.0
          },
          "PRSS1": {
            "detectedCells": 6,
            "detectionPct": 28.6,
            "meanRawCount": 0.381,
            "relativeMeanPct": 0.1
          },
          "PTPRC": {
            "detectedCells": 0,
            "detectionPct": 0.0,
            "meanRawCount": 0.0,
            "relativeMeanPct": 0.0
          },
          "SST": {
            "detectedCells": 21,
            "detectionPct": 100.0,
            "meanRawCount": 78.762,
            "relativeMeanPct": 0.1
          }
        },
        "sourceCellType": "endothelial cell"
      },
      "immune": {
        "available": false,
        "cellCount": 0,
        "donorCount": 0,
        "genes": {},
        "reason": "The curated CELLxGENE dataset does not list a broad immune-cell annotation, so this real-data snapshot does not fabricate one.",
        "sourceCellType": null
      },
      "stellate": {
        "available": true,
        "cellCount": 78,
        "donorCount": 4,
        "genes": {
          "COL3A1": {
            "detectedCells": 78,
            "detectionPct": 100.0,
            "meanRawCount": 888.974,
            "relativeMeanPct": 100.0
          },
          "GCG": {
            "detectedCells": 78,
            "detectionPct": 100.0,
            "meanRawCount": 92.962,
            "relativeMeanPct": 0.6
          },
          "INS": {
            "detectedCells": 38,
            "detectionPct": 48.7,
            "meanRawCount": 1.064,
            "relativeMeanPct": 0.5
          },
          "KDR": {
            "detectedCells": 2,
            "detectionPct": 2.6,
            "meanRawCount": 0.038,
            "relativeMeanPct": 0.0
          },
          "KRT19": {
            "detectedCells": 11,
            "detectionPct": 14.1,
            "meanRawCount": 0.154,
            "relativeMeanPct": 0.4
          },
          "PRSS1": {
            "detectedCells": 36,
            "detectionPct": 46.2,
            "meanRawCount": 0.885,
            "relativeMeanPct": 0.2
          },
          "PTPRC": {
            "detectedCells": 0,
            "detectionPct": 0.0,
            "meanRawCount": 0.0,
            "relativeMeanPct": 0.0
          },
          "SST": {
            "detectedCells": 78,
            "detectionPct": 100.0,
            "meanRawCount": 183.526,
            "relativeMeanPct": 0.2
          }
        },
        "sourceCellType": "mesenchymal cell"
      }
    },
    "genes": [
      "INS",
      "GCG",
      "SST",
      "KRT19",
      "PRSS1",
      "COL3A1",
      "KDR",
      "PTPRC"
    ],
    "id": "muraro-pancreas-aggregates-v2",
    "metric": {
      "definition": "For each curated source cell type, the percentage of cells whose raw count for the selected gene is greater than zero.",
      "id": "rawDetectionFrequency",
      "label": "cells with detected raw RNA",
      "relativeMetric": "relativeMeanPct divides a cell type's mean raw count by the largest mean among the displayed mapped cell types for the same gene. It is valid only as a within-gene teaching comparison.",
      "secondaryMetric": "meanRawCount is the arithmetic mean raw count across all cells in the source cell type and is provided for audit, not cross-study comparison.",
      "unit": "percent"
    },
    "privacy": {
      "aggregateOnly": true,
      "containsCellRows": false,
      "containsDonorIdentifiers": false,
      "containsSequences": false
    },
    "replicatePolicy": {
      "labels": "Source donor categories are deterministically relabeled Replicate A-D; the mapping is not exported.",
      "lowCellCountThreshold": 10,
      "pseudonymized": true,
      "sourceDonorIdsIncluded": false,
      "warning": "Replicate labels are pseudonyms, not proof of anonymity. Counts and expression summaries remain aggregate-only and must not be used for donor identification."
    },
    "replicates": [
      {
        "cellTypes": {
          "acinar": {
            "available": true,
            "cellCount": 53,
            "genes": {
              "COL3A1": {
                "detectedCells": 17,
                "detectionPct": 32.1,
                "meanRawCount": 0.962,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 53,
                "detectionPct": 100.0,
                "meanRawCount": 233.17,
                "relativeMeanPct": 0.6
              },
              "INS": {
                "detectedCells": 30,
                "detectionPct": 56.6,
                "meanRawCount": 1.283,
                "relativeMeanPct": 0.4
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 1.9,
                "meanRawCount": 0.019,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 15,
                "detectionPct": 28.3,
                "meanRawCount": 4.509,
                "relativeMeanPct": 11.6
              },
              "PRSS1": {
                "detectedCells": 53,
                "detectionPct": 100.0,
                "meanRawCount": 804.34,
                "relativeMeanPct": 100.0
              },
              "PTPRC": {
                "detectedCells": 2,
                "detectionPct": 3.8,
                "meanRawCount": 0.057,
                "relativeMeanPct": 1.4
              },
              "SST": {
                "detectedCells": 53,
                "detectionPct": 100.0,
                "meanRawCount": 196.075,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic acinar cell"
          },
          "alpha": {
            "available": true,
            "cellCount": 54,
            "genes": {
              "COL3A1": {
                "detectedCells": 7,
                "detectionPct": 13.0,
                "meanRawCount": 0.222,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 54,
                "detectionPct": 100.0,
                "meanRawCount": 40014.185,
                "relativeMeanPct": 100.0
              },
              "INS": {
                "detectedCells": 33,
                "detectionPct": 61.1,
                "meanRawCount": 49.963,
                "relativeMeanPct": 15.9
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 1.9,
                "meanRawCount": 0.019,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 14,
                "detectionPct": 25.9,
                "meanRawCount": 0.722,
                "relativeMeanPct": 1.9
              },
              "PRSS1": {
                "detectedCells": 50,
                "detectionPct": 92.6,
                "meanRawCount": 5.5,
                "relativeMeanPct": 0.7
              },
              "PTPRC": {
                "detectedCells": 1,
                "detectionPct": 1.9,
                "meanRawCount": 0.037,
                "relativeMeanPct": 0.9
              },
              "SST": {
                "detectedCells": 53,
                "detectionPct": 98.1,
                "meanRawCount": 4401.296,
                "relativeMeanPct": 2.7
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic A cell"
          },
          "beta": {
            "available": true,
            "cellCount": 14,
            "genes": {
              "COL3A1": {
                "detectedCells": 4,
                "detectionPct": 28.6,
                "meanRawCount": 1.0,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 14,
                "detectionPct": 100.0,
                "meanRawCount": 4335.929,
                "relativeMeanPct": 10.8
              },
              "INS": {
                "detectedCells": 12,
                "detectionPct": 85.7,
                "meanRawCount": 314.429,
                "relativeMeanPct": 100.0
              },
              "KDR": {
                "detectedCells": 2,
                "detectionPct": 14.3,
                "meanRawCount": 0.143,
                "relativeMeanPct": 0.1
              },
              "KRT19": {
                "detectedCells": 4,
                "detectionPct": 28.6,
                "meanRawCount": 2.786,
                "relativeMeanPct": 7.2
              },
              "PRSS1": {
                "detectedCells": 14,
                "detectionPct": 100.0,
                "meanRawCount": 15.714,
                "relativeMeanPct": 2.0
              },
              "PTPRC": {
                "detectedCells": 1,
                "detectionPct": 7.1,
                "meanRawCount": 0.071,
                "relativeMeanPct": 1.7
              },
              "SST": {
                "detectedCells": 14,
                "detectionPct": 100.0,
                "meanRawCount": 10096.071,
                "relativeMeanPct": 6.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "type B pancreatic cell"
          },
          "delta": {
            "available": true,
            "cellCount": 7,
            "genes": {
              "COL3A1": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 7,
                "detectionPct": 100.0,
                "meanRawCount": 137.286,
                "relativeMeanPct": 0.3
              },
              "INS": {
                "detectedCells": 4,
                "detectionPct": 57.1,
                "meanRawCount": 3.714,
                "relativeMeanPct": 1.2
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 14.3,
                "meanRawCount": 0.143,
                "relativeMeanPct": 0.1
              },
              "KRT19": {
                "detectedCells": 4,
                "detectionPct": 57.1,
                "meanRawCount": 1.429,
                "relativeMeanPct": 3.7
              },
              "PRSS1": {
                "detectedCells": 6,
                "detectionPct": 85.7,
                "meanRawCount": 2.286,
                "relativeMeanPct": 0.3
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 7,
                "detectionPct": 100.0,
                "meanRawCount": 164886.0,
                "relativeMeanPct": 100.0
              }
            },
            "lowCellCount": true,
            "sourceCellType": "pancreatic D cell"
          },
          "ductal": {
            "available": true,
            "cellCount": 39,
            "genes": {
              "COL3A1": {
                "detectedCells": 6,
                "detectionPct": 15.4,
                "meanRawCount": 6.718,
                "relativeMeanPct": 0.3
              },
              "GCG": {
                "detectedCells": 39,
                "detectionPct": 100.0,
                "meanRawCount": 168.872,
                "relativeMeanPct": 0.4
              },
              "INS": {
                "detectedCells": 20,
                "detectionPct": 51.3,
                "meanRawCount": 1.308,
                "relativeMeanPct": 0.4
              },
              "KDR": {
                "detectedCells": 2,
                "detectionPct": 5.1,
                "meanRawCount": 0.077,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 37,
                "detectionPct": 94.9,
                "meanRawCount": 38.718,
                "relativeMeanPct": 100.0
              },
              "PRSS1": {
                "detectedCells": 37,
                "detectionPct": 94.9,
                "meanRawCount": 21.179,
                "relativeMeanPct": 2.6
              },
              "PTPRC": {
                "detectedCells": 5,
                "detectionPct": 12.8,
                "meanRawCount": 4.128,
                "relativeMeanPct": 100.0
              },
              "SST": {
                "detectedCells": 38,
                "detectionPct": 97.4,
                "meanRawCount": 157.462,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic ductal cell"
          },
          "endothelial": {
            "available": true,
            "cellCount": 4,
            "genes": {
              "COL3A1": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 4,
                "detectionPct": 100.0,
                "meanRawCount": 129.75,
                "relativeMeanPct": 0.3
              },
              "INS": {
                "detectedCells": 1,
                "detectionPct": 25.0,
                "meanRawCount": 0.25,
                "relativeMeanPct": 0.1
              },
              "KDR": {
                "detectedCells": 4,
                "detectionPct": 100.0,
                "meanRawCount": 204.25,
                "relativeMeanPct": 100.0
              },
              "KRT19": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "PRSS1": {
                "detectedCells": 2,
                "detectionPct": 50.0,
                "meanRawCount": 0.75,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 4,
                "detectionPct": 100.0,
                "meanRawCount": 87.25,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": true,
            "sourceCellType": "endothelial cell"
          },
          "immune": {
            "available": false,
            "cellCount": 0,
            "genes": {},
            "lowCellCount": true,
            "reason": "No mapped immune annotation is available in this source replicate.",
            "sourceCellType": null
          },
          "stellate": {
            "available": true,
            "cellCount": 1,
            "genes": {
              "COL3A1": {
                "detectedCells": 1,
                "detectionPct": 100.0,
                "meanRawCount": 2332.0,
                "relativeMeanPct": 100.0
              },
              "GCG": {
                "detectedCells": 1,
                "detectionPct": 100.0,
                "meanRawCount": 497.0,
                "relativeMeanPct": 1.2
              },
              "INS": {
                "detectedCells": 1,
                "detectionPct": 100.0,
                "meanRawCount": 2.0,
                "relativeMeanPct": 0.6
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 1,
                "detectionPct": 100.0,
                "meanRawCount": 1.0,
                "relativeMeanPct": 2.6
              },
              "PRSS1": {
                "detectedCells": 1,
                "detectionPct": 100.0,
                "meanRawCount": 3.0,
                "relativeMeanPct": 0.4
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 1,
                "detectionPct": 100.0,
                "meanRawCount": 237.0,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": true,
            "sourceCellType": "mesenchymal cell"
          }
        },
        "id": "replicate_a",
        "label": "Replicate A",
        "mappedCellCount": 172,
        "primaryCellCount": 182
      },
      {
        "cellTypes": {
          "acinar": {
            "available": true,
            "cellCount": 5,
            "genes": {
              "COL3A1": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 5,
                "detectionPct": 100.0,
                "meanRawCount": 71.6,
                "relativeMeanPct": 0.6
              },
              "INS": {
                "detectedCells": 4,
                "detectionPct": 80.0,
                "meanRawCount": 1.0,
                "relativeMeanPct": 0.4
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 20.0,
                "meanRawCount": 0.2,
                "relativeMeanPct": 0.1
              },
              "KRT19": {
                "detectedCells": 2,
                "detectionPct": 40.0,
                "meanRawCount": 2.2,
                "relativeMeanPct": 3.1
              },
              "PRSS1": {
                "detectedCells": 5,
                "detectionPct": 100.0,
                "meanRawCount": 414.8,
                "relativeMeanPct": 100.0
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 5,
                "detectionPct": 100.0,
                "meanRawCount": 217.6,
                "relativeMeanPct": 0.3
              }
            },
            "lowCellCount": true,
            "sourceCellType": "pancreatic acinar cell"
          },
          "alpha": {
            "available": true,
            "cellCount": 248,
            "genes": {
              "COL3A1": {
                "detectedCells": 13,
                "detectionPct": 5.2,
                "meanRawCount": 0.097,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 248,
                "detectionPct": 100.0,
                "meanRawCount": 12470.331,
                "relativeMeanPct": 100.0
              },
              "INS": {
                "detectedCells": 141,
                "detectionPct": 56.9,
                "meanRawCount": 1.492,
                "relativeMeanPct": 0.6
              },
              "KDR": {
                "detectedCells": 2,
                "detectionPct": 0.8,
                "meanRawCount": 0.008,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 26,
                "detectionPct": 10.5,
                "meanRawCount": 0.242,
                "relativeMeanPct": 0.3
              },
              "PRSS1": {
                "detectedCells": 31,
                "detectionPct": 12.5,
                "meanRawCount": 0.46,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 248,
                "detectionPct": 100.0,
                "meanRawCount": 177.456,
                "relativeMeanPct": 0.3
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic A cell"
          },
          "beta": {
            "available": true,
            "cellCount": 154,
            "genes": {
              "COL3A1": {
                "detectedCells": 10,
                "detectionPct": 6.5,
                "meanRawCount": 0.851,
                "relativeMeanPct": 0.2
              },
              "GCG": {
                "detectedCells": 154,
                "detectionPct": 100.0,
                "meanRawCount": 78.383,
                "relativeMeanPct": 0.6
              },
              "INS": {
                "detectedCells": 152,
                "detectionPct": 98.7,
                "meanRawCount": 238.305,
                "relativeMeanPct": 100.0
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 0.6,
                "meanRawCount": 0.006,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 7,
                "detectionPct": 4.5,
                "meanRawCount": 0.11,
                "relativeMeanPct": 0.2
              },
              "PRSS1": {
                "detectedCells": 23,
                "detectionPct": 14.9,
                "meanRawCount": 0.201,
                "relativeMeanPct": 0.0
              },
              "PTPRC": {
                "detectedCells": 1,
                "detectionPct": 0.6,
                "meanRawCount": 0.006,
                "relativeMeanPct": 0.3
              },
              "SST": {
                "detectedCells": 154,
                "detectionPct": 100.0,
                "meanRawCount": 262.61,
                "relativeMeanPct": 0.4
              }
            },
            "lowCellCount": false,
            "sourceCellType": "type B pancreatic cell"
          },
          "delta": {
            "available": true,
            "cellCount": 74,
            "genes": {
              "COL3A1": {
                "detectedCells": 1,
                "detectionPct": 1.4,
                "meanRawCount": 0.014,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 74,
                "detectionPct": 100.0,
                "meanRawCount": 77.919,
                "relativeMeanPct": 0.6
              },
              "INS": {
                "detectedCells": 42,
                "detectionPct": 56.8,
                "meanRawCount": 4.338,
                "relativeMeanPct": 1.8
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 16,
                "detectionPct": 21.6,
                "meanRawCount": 0.324,
                "relativeMeanPct": 0.5
              },
              "PRSS1": {
                "detectedCells": 8,
                "detectionPct": 10.8,
                "meanRawCount": 0.216,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 74,
                "detectionPct": 100.0,
                "meanRawCount": 69374.122,
                "relativeMeanPct": 100.0
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic D cell"
          },
          "ductal": {
            "available": true,
            "cellCount": 21,
            "genes": {
              "COL3A1": {
                "detectedCells": 2,
                "detectionPct": 9.5,
                "meanRawCount": 0.143,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 21,
                "detectionPct": 100.0,
                "meanRawCount": 61.762,
                "relativeMeanPct": 0.5
              },
              "INS": {
                "detectedCells": 14,
                "detectionPct": 66.7,
                "meanRawCount": 10.429,
                "relativeMeanPct": 4.4
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 19,
                "detectionPct": 90.5,
                "meanRawCount": 71.952,
                "relativeMeanPct": 100.0
              },
              "PRSS1": {
                "detectedCells": 9,
                "detectionPct": 42.9,
                "meanRawCount": 4.381,
                "relativeMeanPct": 1.1
              },
              "PTPRC": {
                "detectedCells": 1,
                "detectionPct": 4.8,
                "meanRawCount": 1.952,
                "relativeMeanPct": 100.0
              },
              "SST": {
                "detectedCells": 21,
                "detectionPct": 100.0,
                "meanRawCount": 226.143,
                "relativeMeanPct": 0.3
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic ductal cell"
          },
          "endothelial": {
            "available": true,
            "cellCount": 2,
            "genes": {
              "COL3A1": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 2,
                "detectionPct": 100.0,
                "meanRawCount": 84.0,
                "relativeMeanPct": 0.7
              },
              "INS": {
                "detectedCells": 2,
                "detectionPct": 100.0,
                "meanRawCount": 2.0,
                "relativeMeanPct": 0.8
              },
              "KDR": {
                "detectedCells": 2,
                "detectionPct": 100.0,
                "meanRawCount": 152.0,
                "relativeMeanPct": 100.0
              },
              "KRT19": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "PRSS1": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 2,
                "detectionPct": 100.0,
                "meanRawCount": 235.0,
                "relativeMeanPct": 0.3
              }
            },
            "lowCellCount": true,
            "sourceCellType": "endothelial cell"
          },
          "immune": {
            "available": false,
            "cellCount": 0,
            "genes": {},
            "lowCellCount": true,
            "reason": "No mapped immune annotation is available in this source replicate.",
            "sourceCellType": null
          },
          "stellate": {
            "available": true,
            "cellCount": 6,
            "genes": {
              "COL3A1": {
                "detectedCells": 6,
                "detectionPct": 100.0,
                "meanRawCount": 433.5,
                "relativeMeanPct": 100.0
              },
              "GCG": {
                "detectedCells": 6,
                "detectionPct": 100.0,
                "meanRawCount": 83.333,
                "relativeMeanPct": 0.7
              },
              "INS": {
                "detectedCells": 1,
                "detectionPct": 16.7,
                "meanRawCount": 0.167,
                "relativeMeanPct": 0.1
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "PRSS1": {
                "detectedCells": 1,
                "detectionPct": 16.7,
                "meanRawCount": 0.333,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 6,
                "detectionPct": 100.0,
                "meanRawCount": 281.333,
                "relativeMeanPct": 0.4
              }
            },
            "lowCellCount": true,
            "sourceCellType": "mesenchymal cell"
          }
        },
        "id": "replicate_b",
        "label": "Replicate B",
        "mappedCellCount": 510,
        "primaryCellCount": 574
      },
      {
        "cellTypes": {
          "acinar": {
            "available": true,
            "cellCount": 55,
            "genes": {
              "COL3A1": {
                "detectedCells": 30,
                "detectionPct": 54.5,
                "meanRawCount": 17.545,
                "relativeMeanPct": 1.6
              },
              "GCG": {
                "detectedCells": 55,
                "detectionPct": 100.0,
                "meanRawCount": 1263.982,
                "relativeMeanPct": 6.1
              },
              "INS": {
                "detectedCells": 35,
                "detectionPct": 63.6,
                "meanRawCount": 2.0,
                "relativeMeanPct": 0.5
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 27,
                "detectionPct": 49.1,
                "meanRawCount": 18.782,
                "relativeMeanPct": 54.1
              },
              "PRSS1": {
                "detectedCells": 55,
                "detectionPct": 100.0,
                "meanRawCount": 611.345,
                "relativeMeanPct": 100.0
              },
              "PTPRC": {
                "detectedCells": 1,
                "detectionPct": 1.8,
                "meanRawCount": 0.055,
                "relativeMeanPct": 5.9
              },
              "SST": {
                "detectedCells": 55,
                "detectionPct": 100.0,
                "meanRawCount": 319.0,
                "relativeMeanPct": 0.2
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic acinar cell"
          },
          "alpha": {
            "available": true,
            "cellCount": 301,
            "genes": {
              "COL3A1": {
                "detectedCells": 162,
                "detectionPct": 53.8,
                "meanRawCount": 1.316,
                "relativeMeanPct": 0.1
              },
              "GCG": {
                "detectedCells": 301,
                "detectionPct": 100.0,
                "meanRawCount": 20593.159,
                "relativeMeanPct": 100.0
              },
              "INS": {
                "detectedCells": 194,
                "detectionPct": 64.5,
                "meanRawCount": 15.558,
                "relativeMeanPct": 3.9
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 0.3,
                "meanRawCount": 0.003,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 78,
                "detectionPct": 25.9,
                "meanRawCount": 0.914,
                "relativeMeanPct": 2.6
              },
              "PRSS1": {
                "detectedCells": 120,
                "detectionPct": 39.9,
                "meanRawCount": 1.07,
                "relativeMeanPct": 0.2
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 301,
                "detectionPct": 100.0,
                "meanRawCount": 2045.538,
                "relativeMeanPct": 1.6
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic A cell"
          },
          "beta": {
            "available": true,
            "cellCount": 121,
            "genes": {
              "COL3A1": {
                "detectedCells": 63,
                "detectionPct": 52.1,
                "meanRawCount": 1.57,
                "relativeMeanPct": 0.1
              },
              "GCG": {
                "detectedCells": 121,
                "detectionPct": 100.0,
                "meanRawCount": 758.595,
                "relativeMeanPct": 3.7
              },
              "INS": {
                "detectedCells": 120,
                "detectionPct": 99.2,
                "meanRawCount": 394.636,
                "relativeMeanPct": 100.0
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 10,
                "detectionPct": 8.3,
                "meanRawCount": 0.463,
                "relativeMeanPct": 1.3
              },
              "PRSS1": {
                "detectedCells": 42,
                "detectionPct": 34.7,
                "meanRawCount": 0.76,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 1,
                "detectionPct": 0.8,
                "meanRawCount": 0.008,
                "relativeMeanPct": 0.9
              },
              "SST": {
                "detectedCells": 121,
                "detectionPct": 100.0,
                "meanRawCount": 3436.62,
                "relativeMeanPct": 2.6
              }
            },
            "lowCellCount": false,
            "sourceCellType": "type B pancreatic cell"
          },
          "delta": {
            "available": true,
            "cellCount": 68,
            "genes": {
              "COL3A1": {
                "detectedCells": 37,
                "detectionPct": 54.4,
                "meanRawCount": 1.103,
                "relativeMeanPct": 0.1
              },
              "GCG": {
                "detectedCells": 68,
                "detectionPct": 100.0,
                "meanRawCount": 100.868,
                "relativeMeanPct": 0.5
              },
              "INS": {
                "detectedCells": 42,
                "detectionPct": 61.8,
                "meanRawCount": 13.485,
                "relativeMeanPct": 3.4
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 1.5,
                "meanRawCount": 0.015,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 22,
                "detectionPct": 32.4,
                "meanRawCount": 0.779,
                "relativeMeanPct": 2.2
              },
              "PRSS1": {
                "detectedCells": 23,
                "detectionPct": 33.8,
                "meanRawCount": 0.603,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 68,
                "detectionPct": 100.0,
                "meanRawCount": 130430.0,
                "relativeMeanPct": 100.0
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic D cell"
          },
          "ductal": {
            "available": true,
            "cellCount": 80,
            "genes": {
              "COL3A1": {
                "detectedCells": 34,
                "detectionPct": 42.5,
                "meanRawCount": 29.562,
                "relativeMeanPct": 2.7
              },
              "GCG": {
                "detectedCells": 80,
                "detectionPct": 100.0,
                "meanRawCount": 88.838,
                "relativeMeanPct": 0.4
              },
              "INS": {
                "detectedCells": 48,
                "detectionPct": 60.0,
                "meanRawCount": 1.025,
                "relativeMeanPct": 0.3
              },
              "KDR": {
                "detectedCells": 2,
                "detectionPct": 2.5,
                "meanRawCount": 0.025,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 72,
                "detectionPct": 90.0,
                "meanRawCount": 34.688,
                "relativeMeanPct": 100.0
              },
              "PRSS1": {
                "detectedCells": 30,
                "detectionPct": 37.5,
                "meanRawCount": 0.887,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 7,
                "detectionPct": 8.8,
                "meanRawCount": 0.925,
                "relativeMeanPct": 100.0
              },
              "SST": {
                "detectedCells": 80,
                "detectionPct": 100.0,
                "meanRawCount": 177.662,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic ductal cell"
          },
          "endothelial": {
            "available": true,
            "cellCount": 6,
            "genes": {
              "COL3A1": {
                "detectedCells": 2,
                "detectionPct": 33.3,
                "meanRawCount": 0.5,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 6,
                "detectionPct": 100.0,
                "meanRawCount": 65.0,
                "relativeMeanPct": 0.3
              },
              "INS": {
                "detectedCells": 3,
                "detectionPct": 50.0,
                "meanRawCount": 0.667,
                "relativeMeanPct": 0.2
              },
              "KDR": {
                "detectedCells": 6,
                "detectionPct": 100.0,
                "meanRawCount": 90.333,
                "relativeMeanPct": 100.0
              },
              "KRT19": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "PRSS1": {
                "detectedCells": 2,
                "detectionPct": 33.3,
                "meanRawCount": 0.333,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 6,
                "detectionPct": 100.0,
                "meanRawCount": 106.5,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": true,
            "sourceCellType": "endothelial cell"
          },
          "immune": {
            "available": false,
            "cellCount": 0,
            "genes": {},
            "lowCellCount": true,
            "reason": "No mapped immune annotation is available in this source replicate.",
            "sourceCellType": null
          },
          "stellate": {
            "available": true,
            "cellCount": 50,
            "genes": {
              "COL3A1": {
                "detectedCells": 50,
                "detectionPct": 100.0,
                "meanRawCount": 1094.72,
                "relativeMeanPct": 100.0
              },
              "GCG": {
                "detectedCells": 50,
                "detectionPct": 100.0,
                "meanRawCount": 103.72,
                "relativeMeanPct": 0.5
              },
              "INS": {
                "detectedCells": 29,
                "detectionPct": 58.0,
                "meanRawCount": 1.4,
                "relativeMeanPct": 0.4
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 2.0,
                "meanRawCount": 0.02,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 8,
                "detectionPct": 16.0,
                "meanRawCount": 0.18,
                "relativeMeanPct": 0.5
              },
              "PRSS1": {
                "detectedCells": 20,
                "detectionPct": 40.0,
                "meanRawCount": 0.68,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 50,
                "detectionPct": 100.0,
                "meanRawCount": 218.42,
                "relativeMeanPct": 0.2
              }
            },
            "lowCellCount": false,
            "sourceCellType": "mesenchymal cell"
          }
        },
        "id": "replicate_c",
        "label": "Replicate C",
        "mappedCellCount": 681,
        "primaryCellCount": 687
      },
      {
        "cellTypes": {
          "acinar": {
            "available": true,
            "cellCount": 106,
            "genes": {
              "COL3A1": {
                "detectedCells": 22,
                "detectionPct": 20.8,
                "meanRawCount": 0.377,
                "relativeMeanPct": 0.1
              },
              "GCG": {
                "detectedCells": 106,
                "detectionPct": 100.0,
                "meanRawCount": 44.981,
                "relativeMeanPct": 0.5
              },
              "INS": {
                "detectedCells": 38,
                "detectionPct": 35.8,
                "meanRawCount": 0.491,
                "relativeMeanPct": 0.8
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 28,
                "detectionPct": 26.4,
                "meanRawCount": 1.123,
                "relativeMeanPct": 2.6
              },
              "PRSS1": {
                "detectedCells": 106,
                "detectionPct": 100.0,
                "meanRawCount": 437.198,
                "relativeMeanPct": 100.0
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 106,
                "detectionPct": 100.0,
                "meanRawCount": 69.34,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic acinar cell"
          },
          "alpha": {
            "available": true,
            "cellCount": 209,
            "genes": {
              "COL3A1": {
                "detectedCells": 39,
                "detectionPct": 18.7,
                "meanRawCount": 0.301,
                "relativeMeanPct": 0.1
              },
              "GCG": {
                "detectedCells": 209,
                "detectionPct": 100.0,
                "meanRawCount": 9703.608,
                "relativeMeanPct": 100.0
              },
              "INS": {
                "detectedCells": 54,
                "detectionPct": 25.8,
                "meanRawCount": 0.407,
                "relativeMeanPct": 0.6
              },
              "KDR": {
                "detectedCells": 4,
                "detectionPct": 1.9,
                "meanRawCount": 0.019,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 32,
                "detectionPct": 15.3,
                "meanRawCount": 0.206,
                "relativeMeanPct": 0.5
              },
              "PRSS1": {
                "detectedCells": 101,
                "detectionPct": 48.3,
                "meanRawCount": 1.005,
                "relativeMeanPct": 0.2
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 209,
                "detectionPct": 100.0,
                "meanRawCount": 58.22,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic A cell"
          },
          "beta": {
            "available": true,
            "cellCount": 159,
            "genes": {
              "COL3A1": {
                "detectedCells": 24,
                "detectionPct": 15.1,
                "meanRawCount": 0.252,
                "relativeMeanPct": 0.1
              },
              "GCG": {
                "detectedCells": 159,
                "detectionPct": 100.0,
                "meanRawCount": 39.881,
                "relativeMeanPct": 0.4
              },
              "INS": {
                "detectedCells": 153,
                "detectionPct": 96.2,
                "meanRawCount": 63.862,
                "relativeMeanPct": 100.0
              },
              "KDR": {
                "detectedCells": 2,
                "detectionPct": 1.3,
                "meanRawCount": 0.038,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 14,
                "detectionPct": 8.8,
                "meanRawCount": 0.264,
                "relativeMeanPct": 0.6
              },
              "PRSS1": {
                "detectedCells": 84,
                "detectionPct": 52.8,
                "meanRawCount": 1.365,
                "relativeMeanPct": 0.3
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 159,
                "detectionPct": 100.0,
                "meanRawCount": 89.245,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "type B pancreatic cell"
          },
          "delta": {
            "available": true,
            "cellCount": 44,
            "genes": {
              "COL3A1": {
                "detectedCells": 5,
                "detectionPct": 11.4,
                "meanRawCount": 0.159,
                "relativeMeanPct": 0.0
              },
              "GCG": {
                "detectedCells": 44,
                "detectionPct": 100.0,
                "meanRawCount": 38.932,
                "relativeMeanPct": 0.4
              },
              "INS": {
                "detectedCells": 10,
                "detectionPct": 22.7,
                "meanRawCount": 2.545,
                "relativeMeanPct": 4.0
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 14,
                "detectionPct": 31.8,
                "meanRawCount": 0.636,
                "relativeMeanPct": 1.5
              },
              "PRSS1": {
                "detectedCells": 22,
                "detectionPct": 50.0,
                "meanRawCount": 1.091,
                "relativeMeanPct": 0.2
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 44,
                "detectionPct": 100.0,
                "meanRawCount": 64085.932,
                "relativeMeanPct": 100.0
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic D cell"
          },
          "ductal": {
            "available": true,
            "cellCount": 106,
            "genes": {
              "COL3A1": {
                "detectedCells": 17,
                "detectionPct": 16.0,
                "meanRawCount": 0.358,
                "relativeMeanPct": 0.1
              },
              "GCG": {
                "detectedCells": 106,
                "detectionPct": 100.0,
                "meanRawCount": 39.462,
                "relativeMeanPct": 0.4
              },
              "INS": {
                "detectedCells": 26,
                "detectionPct": 24.5,
                "meanRawCount": 0.849,
                "relativeMeanPct": 1.3
              },
              "KDR": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "KRT19": {
                "detectedCells": 92,
                "detectionPct": 86.8,
                "meanRawCount": 43.519,
                "relativeMeanPct": 100.0
              },
              "PRSS1": {
                "detectedCells": 53,
                "detectionPct": 50.0,
                "meanRawCount": 1.877,
                "relativeMeanPct": 0.4
              },
              "PTPRC": {
                "detectedCells": 3,
                "detectionPct": 2.8,
                "meanRawCount": 0.057,
                "relativeMeanPct": 100.0
              },
              "SST": {
                "detectedCells": 106,
                "detectionPct": 100.0,
                "meanRawCount": 49.094,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "pancreatic ductal cell"
          },
          "endothelial": {
            "available": true,
            "cellCount": 9,
            "genes": {
              "COL3A1": {
                "detectedCells": 1,
                "detectionPct": 11.1,
                "meanRawCount": 34.556,
                "relativeMeanPct": 7.5
              },
              "GCG": {
                "detectedCells": 9,
                "detectionPct": 100.0,
                "meanRawCount": 19.444,
                "relativeMeanPct": 0.2
              },
              "INS": {
                "detectedCells": 1,
                "detectionPct": 11.1,
                "meanRawCount": 0.111,
                "relativeMeanPct": 0.2
              },
              "KDR": {
                "detectedCells": 8,
                "detectionPct": 88.9,
                "meanRawCount": 80.333,
                "relativeMeanPct": 100.0
              },
              "KRT19": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "PRSS1": {
                "detectedCells": 2,
                "detectionPct": 22.2,
                "meanRawCount": 0.333,
                "relativeMeanPct": 0.1
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 9,
                "detectionPct": 100.0,
                "meanRawCount": 21.778,
                "relativeMeanPct": 0.0
              }
            },
            "lowCellCount": true,
            "sourceCellType": "endothelial cell"
          },
          "immune": {
            "available": false,
            "cellCount": 0,
            "genes": {},
            "lowCellCount": true,
            "reason": "No mapped immune annotation is available in this source replicate.",
            "sourceCellType": null
          },
          "stellate": {
            "available": true,
            "cellCount": 21,
            "genes": {
              "COL3A1": {
                "detectedCells": 21,
                "detectionPct": 100.0,
                "meanRawCount": 460.524,
                "relativeMeanPct": 100.0
              },
              "GCG": {
                "detectedCells": 21,
                "detectionPct": 100.0,
                "meanRawCount": 50.857,
                "relativeMeanPct": 0.5
              },
              "INS": {
                "detectedCells": 7,
                "detectionPct": 33.3,
                "meanRawCount": 0.476,
                "relativeMeanPct": 0.7
              },
              "KDR": {
                "detectedCells": 1,
                "detectionPct": 4.8,
                "meanRawCount": 0.095,
                "relativeMeanPct": 0.1
              },
              "KRT19": {
                "detectedCells": 2,
                "detectionPct": 9.5,
                "meanRawCount": 0.095,
                "relativeMeanPct": 0.2
              },
              "PRSS1": {
                "detectedCells": 14,
                "detectionPct": 66.7,
                "meanRawCount": 1.429,
                "relativeMeanPct": 0.3
              },
              "PTPRC": {
                "detectedCells": 0,
                "detectionPct": 0.0,
                "meanRawCount": 0.0,
                "relativeMeanPct": 0.0
              },
              "SST": {
                "detectedCells": 21,
                "detectionPct": 100.0,
                "meanRawCount": 69.952,
                "relativeMeanPct": 0.1
              }
            },
            "lowCellCount": false,
            "sourceCellType": "mesenchymal cell"
          }
        },
        "id": "replicate_d",
        "label": "Replicate D",
        "mappedCellCount": 654,
        "primaryCellCount": 683
      }
    ],
    "snapshotVersion": 2,
    "source": {
      "assay": "CEL-seq2",
      "assetBytes": 53067951,
      "assetSha256": "183673651cfa8c473a26641d42011d43be44eb2fea44e6e6ab8e2b0065d07483",
      "assetUrl": "https://datasets.cellxgene.cziscience.com/ac56150b-add4-4336-9059-6d3d3ce17f3b.h5ad",
      "citation": "Muraro et al. (2016), Cell Systems",
      "collectionId": "6e8c5415-302c-492a-a5f9-f29c57ff18fb",
      "datasetId": "b07e5164-baf6-43d2-bdba-5a249d0da879",
      "datasetVersionId": "ac56150b-add4-4336-9059-6d3d3ce17f3b",
      "doi": "10.1016/j.cels.2016.09.002",
      "donorCount": 4,
      "featureCount": 15643,
      "hcaProjectId": "894ae6ac-5b48-41a8-a72f-315a9b60a62e",
      "license": "CC BY 4.0",
      "primaryCellCount": 2126,
      "rawMatrixShape": [
        2126,
        15643
      ],
      "schemaVersion": "7.1.0",
      "title": "A Single-Cell Transcriptome Atlas of the Human Pancreas"
    },
    "title": "Muraro pancreas aggregate and replicate snapshot"
  };
})(typeof window !== 'undefined' ? window : globalThis);
