const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {createRequire}=require('node:module'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{
const req=createRequire(path.join(process.cwd(),'desktop/web-app/package.json'));const config=req('./tailwind.config.js');config.content=[path.join(process.cwd(),'behavior_lens_module.js')];const css=await req('postcss')([req('tailwindcss')(config)]).process('@tailwind base;\n@tailwind components;\n@tailwind utilities;',{from:undefined});fs.writeFileSync(path.join(__dirname,'preview.css'),css.css);
const workspace={targetBehaviors:[{id:'help',label:'Requests help',measurement:'count',operationalDefinition:'Shows a help card or says help during independent work.'},{id:'break',label:'Requests a break',measurement:'duration',operationalDefinition:'Asks for a short break.'}],abcEntries:[],observationSessions:[{id:'mixed',timestamp:new Date().toISOString(),duration:600,method:'frequency',data:{count:5,counters:[{behaviorId:'help',label:'Requests help',count:2},{behaviorId:'break',label:'Requests a break',count:3}]}},{id:'latency',timestamp:new Date().toISOString(),duration:20,method:'latency',behaviorId:'help',data:{latencySeconds:5}}],toolState:{supportStrategies:[{id:'support1',targetId:'help',strategy:'Offer the agreed visual prompt before independent writing.',owner:'Classroom teacher',status:'active',reviewDate:'2026-09-18'}]}};
let preview=fs.readFileSync(path.join(__dirname,'flow-preview.html'),'utf8');const marker='</script><script src="../../behavior_lens_workspace_module.js">';preview=preview.replace(marker,`localStorage.setItem('behaviorLens_workspace_audit-eagle',${JSON.stringify(JSON.stringify(workspace))});sessionStorage.clear();sessionStorage.setItem('behaviorLens_observation_draft_v1_frequency_audit-eagle',JSON.stringify({version:1,savedAt:Date.now(),data:{elapsed:90,target:{id:'help',label:'Requests help'},counters:[{id:'c',label:'Requests help',behaviorId:'help',count:2}]}}));${marker}`);fs.writeFileSync(path.join(__dirname,'daily-preview.html'),preview);
const browser=await chromium.launch({headless:true});const results=[];try{for(const width of [1280,390,320]){
const page=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(pathToFileURL(path.join(__dirname,'daily-preview.html')).href);await page.locator('[data-bl-today]').waitFor();await page.addScriptTag({path:require.resolve('axe-core')});await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important}'});
async function capture(state,focus){if(focus)await focus.scrollIntoViewIfNeeded();await page.mouse.move(0,0);await page.screenshot({path:path.join(__dirname,`daily-${state}-${width}.png`)});const metrics=await page.evaluate(async()=>({overflow:document.documentElement.scrollWidth>innerWidth,dialogOverflow:[...document.querySelectorAll('[role="dialog"]')].some(el=>el.scrollWidth>el.clientWidth+1),axe:(await axe.run(document.querySelector('#root'))).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))}));results.push({width,state,errors:[...errors],...metrics});assert.equal(metrics.overflow,false);assert.equal(metrics.dialogOverflow,false);assert.deepEqual(metrics.axe,[]);assert.deepEqual(errors,[]);}
await capture('today');await capture('supports',page.locator('[data-bl-today-supports]'));
await page.getByRole('button',{name:'Resume count recording',exact:true}).click();assert.equal(await page.getByLabel('Behavior counter label',{exact:true}).inputValue(),'Requests help');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Review observations',exact:true}).click();
const session=page.locator('[data-bl-session="mixed"]');await session.locator(':scope > summary').click();await capture('session',session);
await session.getByRole('button',{name:'Correct session details',exact:true}).click();await page.getByLabel('Target for counter 1',{exact:true}).selectOption('break');await page.getByLabel('Review notes',{exact:true}).fill('The first counter was assigned to the wrong target. Counts and timing remain as recorded.');await page.getByLabel('Reason for correction',{exact:true}).fill('Target attribution corrected during review');await capture('correction',session.getByRole('heading',{name:'Correct attribution and notes'}));await session.getByRole('button',{name:'Save session correction',exact:true}).click();await session.locator(':scope > summary').click();await session.getByText('Correction history (1)',{exact:true}).click();await capture('history',session);
await page.getByLabel('Target',{exact:true}).selectOption('help');assert.equal(await page.locator('[data-bl-session="mixed"]').count(),0);await page.close();
}}finally{fs.writeFileSync(path.join(__dirname,'daily-browser-results.json'),JSON.stringify(results,null,2));await browser.close();}console.log(JSON.stringify(results,null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
