const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),vm=require('node:vm'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
for(const name of ['README.md','run-regression.cjs','browser-check.cjs','validate.cjs','regression.json','regression-receipt.json','browser-results.json','forced-colors-diagnostic.json']){const content=fs.readFileSync(path.join(__dirname,name),'utf8');assert.ok(!/[ \t]+(?:\r?\n|$)/.test(content),'Trailing whitespace: '+name);assert.ok(!/(?:\r?\n){2,}$/.test(content),'Blank line at EOF: '+name);}
const receipt=JSON.parse(fs.readFileSync(path.join(__dirname,'regression-receipt.json'))),regression=JSON.parse(fs.readFileSync(path.join(__dirname,'regression.json'))),browser=JSON.parse(fs.readFileSync(path.join(__dirname,'browser-results.json')));
assert.equal(receipt.exitCode,0);assert.deepEqual(receipt.changedDuringRun,[]);for(const[file,expected]of Object.entries(receipt.files))assert.equal(hash(path.join(root,file)),expected,'Tested file changed: '+file);
const source='stem_lab/stem_tool_circuit.js',mirror='desktop/web-app/public/stem_lab/stem_tool_circuit.js',sourceHash=hash(path.join(root,source));assert.equal(sourceHash,hash(path.join(root,mirror)));new vm.Script(fs.readFileSync(path.join(root,source),'utf8'));
assert.equal(regression.success,true);assert.equal(regression.numFailedTests,0);assert.ok(regression.testResults.every(file=>file.status==='passed'));assert.equal(regression.testResults.length,Object.keys(receipt.files).length-2);
assert.equal(browser.passed,true);assert.equal(browser.sourceSha256,sourceHash);assert.equal(browser.sourceSha256AtEnd,sourceHash);assert.equal(browser.mirrorSha256,sourceHash);assert.equal(browser.mirrorSha256AtEnd,sourceHash);assert.equal(browser.sourceChangedDuringRun,false);assert.equal(browser.mirrorMatches,true);assert.deepEqual(browser.errors,[]);assert.deepEqual(browser.visualIssues,[]);assert.ok(browser.axe.length>0&&browser.axe.every(scan=>scan.violations.length===0));
assert.ok(browser.focus.length>0&&browser.focus.every(check=>check.visible));assert.ok(browser.focusTransitions.length>0&&browser.focusTransitions.every(check=>check.focused===(check.expected??true)));assert.ok(browser.textResize.length>=2&&browser.textResize.every(check=>check.afterFontSize===check.beforeFontSize*check.scale));assert.ok(browser.motion.length>0&&browser.motion.every(check=>check.reduced&&check.animations===0));
const ordinary=browser.axe.filter(scan=>!scan.forcedColors),forced=browser.axe.filter(scan=>scan.forcedColors);assert.equal(ordinary.length,20);assert.ok(ordinary.every(scan=>scan.excludedRules.length===0));assert.equal(forced.length,2);assert.ok(forced.every(scan=>scan.excludedRules.length===1&&scan.excludedRules[0]==='color-contrast'&&scan.exclusionReason));
assert.equal(browser.forcedColors.length,2);for(const review of browser.forcedColors){assert.equal(review.active,true);assert.deepEqual(review.violations,[]);assert.ok(review.colors.length>0&&review.colors.every(color=>Number.isFinite(color.ratio)&&color.ratio>=color.required&&color.required>=4.5));}
const diagnostic=JSON.parse(fs.readFileSync(path.join(__dirname,'forced-colors-diagnostic.json')));assert.ok(diagnostic.cases.some(item=>item.freshPageWithForcedColorsBeforeAxe&&item.forced&&item.color==='rgb(0, 0, 0)'&&item.background==='rgb(255, 255, 255)'&&item.contrast.length>0));
assert.equal(browser.numericIntegrity.length,browser.axe.length);const numericReadings=browser.numericIntegrity.flatMap(scan=>scan.readings);assert.ok(numericReadings.length>0&&numericReadings.every(reading=>reading.parts.length>0&&reading.parts.every(part=>part.intact&&part.lineCount===1)));
assert.equal(new Set(browser.screenshots.map(shot=>shot.file)).size,browser.screenshots.length);
const screenshotHashes={};for(const shot of browser.screenshots){assert.equal(path.basename(shot.file),shot.file);const file=path.join(__dirname,shot.file),bytes=fs.readFileSync(file);assert.equal(bytes.subarray(0,8).toString('hex'),'89504e470d0a1a0a');screenshotHashes[shot.file]=hash(file);}
const diff=spawnSync('git',['diff','--check','--',...Object.keys(receipt.files)],{cwd:root,encoding:'utf8'});assert.equal(diff.status,0,diff.stdout+diff.stderr);
const validation={passed:true,validatedAt:new Date().toISOString(),sourceSha256:sourceHash,mirrored:true,sourceCompiles:true,regression:{passedTests:regression.numPassedTests,files:regression.testResults.length,startedAt:receipt.startedAt,finishedAt:receipt.finishedAt},browser:{workflows:browser.checks.length,axeScans:browser.axe.length,fullContrastScans:ordinary.length,forcedColorsScans:forced.length,forcedColorsTextNodes:browser.forcedColors.reduce((sum,review)=>sum+review.colors.length,0),numericReadings:numericReadings.length,focusChecks:browser.focus.length,focusTransitions:browser.focusTransitions.length,textResizeCases:browser.textResize.length,screenshots:browser.screenshots.length,visualIssues:browser.visualIssues.length},reportHashes:Object.fromEntries(['regression.json','regression-receipt.json','browser-results.json','forced-colors-diagnostic.json'].map(file=>[file,hash(path.join(__dirname,file))])),screenshotHashes,whitespaceCheck:true};
fs.writeFileSync(path.join(__dirname,'validation.json'),JSON.stringify(validation,null,2));console.log(JSON.stringify({...validation,screenshotHashes:Object.keys(screenshotHashes)},null,2));
