const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const generated=path.join(__dirname,'capture-harness.generated.cjs');
require('esbuild').buildSync({entryPoints:[path.resolve(__dirname,'../../../tests/e2e/helpers/stem_gl_harness.ts')],bundle:true,platform:'node',format:'cjs',outfile:generated,external:['@playwright/test']});
const {GlHarness}=require(generated),initial=process.argv.includes('--initial'),prefix=initial?'initial-':'',only=process.argv.find(arg=>arg.startsWith('--only='))?.slice(7);
(async()=>{
 const harness=new GlHarness({toolFile:initial?'reports/cephalopod-hunter-enhancement/pass-eighteen/baseline.generated.cjs':'stem_lab/stem_tool_cephalopodlab.js',toolId:'cephalopodLab',width:1100,height:1000,layout:'document'});await harness.start();
 const browser=await chromium.launch({headless:true}),errors=[],warnings=[],captures=[];let page;
 try{
  page=await browser.newPage({viewport:{width:1280,height:1100}});page.setDefaultTimeout(90000);
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning'&&/WebGL|shader|context|THREE/i.test(m.text()))warnings.push(m.text());});
  await page.goto(harness.url+'/__harness');await page.waitForFunction(()=>!!window.THREE?.Clock&&!!window.StemLab?._registry?.cephalopodLab&&typeof window.__mount==='function');
  await page.evaluate(()=>{const w=window;w.__reviewStep=0;w.__reviewTicks=0;w.THREE.Clock.prototype.getDelta=function(){const dt=w.__reviewStep;w.__reviewStep=0;if(dt)w.__reviewTicks++;return dt;};w.__mount({cephalopodLab:{activeSection:'hunt',hunt3DActive:true,huntSpeciesId:'commonOcto',huntMode:'observe',huntSeed:2743,huntQuality:'balanced',_threeLoaded:true}});});
  await page.locator('canvas[role=application]').waitFor({state:'visible'});await page.waitForFunction(()=>window.__glRecorder.records.some(row=>row.scene?.getObjectByName('cl-player')&&row.canvas.isConnected));
  await page.evaluate(async()=>{const w=window;for(let i=0;i<20;i++){const previous=w.__reviewTicks;w.__reviewStep=.05;for(let tries=0;tries<120&&w.__reviewTicks===previous;tries++)await new Promise(resolve=>requestAnimationFrame(resolve));if(w.__reviewTicks!==previous+1)throw Error('Clock not consumed exactly once');}});
  const fixtures=await page.evaluate(()=>{
   const w=window,T=w.THREE,scene=w.__glRecorder.records.filter(row=>row.scene&&row.canvas.isConnected).at(-1).scene;scene.updateMatrixWorld(true);
   const crabs=scene.children.filter(o=>o.userData.cfg&&['rock','red','hermit'].includes(o.userData.type)),clams=scene.children.filter(o=>typeof o.userData.drillProgress==='number'),views={};
   const inventory=crabs.map(o=>o.userData.type);if(crabs.length!==10||clams.length!==8)throw Error('Missing actual prey groups');
   function view(object,offset,target){return{camera:object.localToWorld(new T.Vector3(...offset)).toArray(),target:object.localToWorld(new T.Vector3(...target)).toArray()};}
   for(const type of ['rock','red','hermit']){const matches=crabs.filter(o=>o.userData.type===type),crab=type==='rock'?matches.at(-1):matches[0];if(!crab)throw Error('Missing actual '+type+' crab; inventory '+JSON.stringify(inventory));const sm=crab.userData.cfg.sizeMul;views[type+'-crab']=view(crab,[.95*sm,.58*sm,1.05*sm],[0,.08*sm,0]);if(type==='hermit')views['hermit-shell']=view(crab,[-1.0*sm,.63*sm,-.65*sm],[0,.16*sm,-.03*sm]);}
   const clam=scene.getObjectByName('cl-mission-clam');if(!clam)throw Error('Missing mission clam');
   views['clam-closed']=view(clam,[.80,.55,.85],[0,.08,0]);views['clam-side']=view(clam,[.95,.20,.02],[0,.08,0]);views['clam-open']=view(clam,[.88,.27,-.08],[0,.06,-.02]);views['reef']=view(clam,[5.5,3.5,7.5],[0,.40,0]);views['clam-phone']=view(clam,[1.1,.60,1.50],[0,.10,0]);
   w.__reviewScene=scene;w.__reviewClam=clam;
   return{seed:2743,simTicks:20,inventory,crabs:crabs.map(o=>({type:o.userData.type,position:o.position.toArray(),quaternion:o.quaternion.toArray(),wanderAngle:o.userData.wanderAngle,wanderTimer:o.userData.wanderTimer,speed:o.userData.speed,legPhase:o.userData.legPhase,legPoses:o.children.slice(3,9).map(c=>({position:c.position.toArray(),quaternion:c.quaternion.toArray()}))})),clams:clams.map(o=>({position:o.position.toArray(),quaternion:o.quaternion.toArray(),alive:o.userData.alive,drillProgress:o.userData.drillProgress})),views};
  });
  const fixtureFile=path.join(__dirname,'visual-fixtures.json');if(initial){if(only&&fs.existsSync(fixtureFile)){const old=JSON.parse(fs.readFileSync(fixtureFile,'utf8')),next=JSON.parse(JSON.stringify(fixtures));delete old.views[only];delete next.views[only];assert.deepEqual(next,old,'Partial camera refresh changed another fixture field');}fs.writeFileSync(fixtureFile,JSON.stringify(fixtures,null,2)+'\n');}else assert.deepEqual(JSON.parse(JSON.stringify(fixtures)),JSON.parse(fs.readFileSync(fixtureFile,'utf8')),'Seeded prey state or cameras changed');
  async function camera(view){await page.evaluate(view=>{const w=window,T=w.THREE,position=new T.Vector3(...view.camera),target=new T.Vector3(...view.target);w.__reviewScene.onBeforeRender=function(renderer,scene,camera){camera.position.copy(position);camera.lookAt(target);camera.updateMatrixWorld(true);};},view);}
  async function capture(name){await page.evaluate(async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});const file=prefix+name+'.png';await page.locator('canvas[role=application]').screenshot({path:path.join(__dirname,file)});captures.push(file);}
  for(const name of ['rock-crab','red-crab','hermit-crab','hermit-shell','clam-closed','clam-side','clam-open','reef']){if(only&&name!==only)continue;await page.evaluate(open=>{window.__reviewClam.children[1].rotation.x=open?-Math.PI/6:0;},name==='clam-open');await camera(fixtures.views[name]);await capture(name);}
  if(!only||only==='clam-phone'){await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{window.__reviewClam.children[1].rotation.x=0;document.getElementById('wrap').style.width='100%';window.dispatchEvent(new Event('resize'));});await camera(fixtures.views['clam-phone']);await capture('clam-phone');}
  fs.writeFileSync(path.join(__dirname,prefix+(only?'capture-'+only+'-results.json':'capture-results.json')),JSON.stringify({errors,warnings,captures,inventory:fixtures.inventory,fixture:'Actual seeded crab variants and mission clam; 20 counted .05s simulation steps; unchanged world/lights/fog; camera-only close views. Open view sets actual upper child to existing maximum drill angle without advancing/capturing it. Phone390x844.'},null,2)+'\n');console.log(JSON.stringify({errors,captures,inventory:fixtures.inventory}));if(errors.length)process.exitCode=1;
 }catch(e){fs.writeFileSync(path.join(__dirname,prefix+'capture-failure.json'),JSON.stringify({message:e.message,errors,warnings,captures},null,2)+'\n');throw e;}finally{await browser.close();await harness.stop();}
})().catch(e=>{console.error(e);process.exitCode=1;});
