const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
let harness=fs.readFileSync('reports/geometry-world-deep-dive-2026-09-08/audit.cjs','utf8').split('const results =')[0];
harness=harness.replace('window.__mount({_introShownOnce:true});','window.__mount({_introShownOnce:false,renderQuality:"saver",autoCycle:false});');
const body=async function(){
 const r={checks:[],errors:[],consoleErrors:[],screenshots:[],sources:Object.fromEntries(['stem_tool_geometryworld.js','stem_tool_geometryworld_builder.js'].map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync('stem_lab/'+n)).digest('hex')]))};
 const check=(ok,label)=>{r.checks.push({label,pass:!!ok});if(!ok)throw Error(label);};await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.setDefaultTimeout(30000);page.on('pageerror',e=>r.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')r.consoleErrors.push(m.text());});
 const frames=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const shot=async name=>{await page.screenshot({path:path.join(out,name+'.png'),timeout:60000});r.screenshots.push(name+'.png');};
 const home=()=>page.getByRole('dialog',{name:/What would you like to do|Find your next discovery|Make something your own|A little room to wonder|Create a lesson worth exploring|Pick up where you left off/});
 const openHome=async()=>{if(await page.locator('.gw-settings-dialog').isVisible()){await page.keyboard.press('Escape');await frames();}await page.getByRole('button',{name:'Geometry World home',exact:true}).filter({visible:true}).first().click();await home().waitFor();await frames();};
 const allWays=async()=>{await page.getByRole('button',{name:'← All ways to explore',exact:true}).click();await frames();};
 const signature=()=>page.evaluate(()=>{const e=__geoWorldEngine;return JSON.stringify({blocks:StemLab.geometryWorldBuilderPure.editableWorld(e).blocks,selection:e._builderSelection,undo:e._undoStack,redo:e._redoStack,camera:[e.camera.position.toArray(),e.camera.quaternion.toArray()],context:__ctx.toolData.geometryWorld.builderPrintContext});});
 try{
  await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await home().waitFor({timeout:120000});await page.waitForFunction(()=>!!window.__geoWorldEngine);await frames();
  const pausedFrame=await page.evaluate(()=>__geoWorldEngine.renderer.info.render.frame);await frames();await frames();check(await page.evaluate(()=>__geoWorldEngine.renderer.info.render.frame)===pausedFrame,'Opaque Home pauses hidden 3D rendering');
  check(await page.locator('.gwe-home-card').count()===4,'Fresh visit shows four primary paths');check(await page.getByRole('button',{name:'Start Lesson',exact:true}).count()===0,'Fresh visit does not show the old lesson intro');check(await page.getByRole('button',{name:/Continue your workspace/}).count()===0,'Fresh visit does not offer the automatically seeded world as user work');
  for(const size of [{width:1440,height:1000},{width:390,height:844},{width:320,height:700},{width:844,height:390}]){await page.setViewportSize(size);await frames();await page.locator('.gwe-home').evaluate(n=>n.scrollTop=0);await shot('home-'+size.width+'x'+size.height);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow at '+size.width);for(const card of await page.locator('.gwe-home-card').all()){await card.scrollIntoViewIfNeeded();const info=await card.evaluate(n=>{const b=n.getBoundingClientRect();return {height:b.height,width:b.width,hit:n.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2))};});check(info.height>=44&&info.width>=44&&info.hit,'Mode card reachable at '+size.width);}}
  await page.setViewportSize({width:1440,height:1000});await page.locator('.gwe-home').evaluate(n=>n.scrollTop=0);await page.locator('.gwe-home').focus();await page.keyboard.press('Shift+Tab');check(await page.evaluate(()=>document.activeElement.textContent.includes('Open a saved build')),'Shift Tab wraps to last home control');await page.keyboard.press('Tab');check(await page.evaluate(()=>document.activeElement.classList.contains('gwe-home-card')),'Tab wraps to first home card');
  await page.keyboard.press('Escape');check(await home().count()===1,'Fresh home remains available after Escape');
  await page.locator('.gwe-home-card[data-path=learn]').click();await page.getByLabel('Choose a lesson',{exact:true}).selectOption('fractionBuilder');await shot('learn');await page.getByRole('button',{name:'Start this lesson',exact:true}).click();check(await page.evaluate(()=>__ctx.toolData.geometryWorld.activeLesson==='fractionBuilder'&&__geoWorldEngine._currentLesson.title.includes('Fraction')),'Learn starts the chosen real lesson');await frames();const resumedFrame=await page.evaluate(()=>__geoWorldEngine.renderer.info.render.frame);await frames();check(await page.evaluate(()=>__geoWorldEngine.renderer.info.render.frame)>resumedFrame,'Choosing a path resumes 3D rendering');
  await openHome();await page.locator('.gwe-home-card[data-path=explore]').click();await shot('explore');await page.getByRole('button',{name:'Enter Geometry Garden',exact:true}).click();check(await page.evaluate(()=>__ctx.toolData.geometryWorld.activeLesson==='geometryGarden'&&__geoWorldEngine._currentLesson.npcs.every(n=>!n.question)),'Explore opens the no-question Geometry Garden');
  await openHome();await page.locator('.gwe-home-card[data-path=build]').click();await shot('build');await page.getByRole('button',{name:'Open blank sandbox',exact:true}).click();check(await page.evaluate(()=>__geoWorldEngine._currentLesson.sandbox===true),'Build opens the actual sandbox');
  await page.evaluate(()=>{const e=__geoWorldEngine;e.placeBlock(0,1,0,'wood','cube',0);e.placeBlock(1,1,0,'stone','quarter',2);e._builderSelection={blocks:[{x:0,y:1,z:0},{x:1,y:1,z:0}]};e._entryAnim=null;e.flyMode=true;e.velocity.set(0,0,0);__ctx.updateMulti('geometryWorld',{builderPrintContext:{unitMm:12.5,aiUse:'NONE'},measureResult:e.measureStructure(0,1,0)});});await frames();const before=await signature();await openHome();await page.keyboard.press('KeyB');await page.keyboard.press('Control+z');await page.keyboard.press('KeyW');await frames();check(await signature()===before,'Home and its shortcuts preserve blocks, selection, history, camera and print scale');
  await page.locator('.gwe-home-card[data-path=learn]').click();await page.getByLabel('Choose a lesson',{exact:true}).selectOption('compositeVolume');await allWays();await page.getByRole('button',{name:/Continue your workspace/}).click();await frames();check(await signature()===before,'Browsing lesson previews and Continue preserve the entire workspace');
  await openHome();await page.getByRole('button',{name:/Open a saved build/}).click();const input=page.locator('input[type=file][accept=".json,application/json"]');await input.setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await page.getByRole('alert').filter({hasText:'File not opened'}).waitFor();check(await signature()===before,'Invalid saved-build file cannot mutate the workspace');await shot('invalid-file');
  const fixture={schema:'alloflow-geometry-world/2',title:'Home import',coordinateSystem:'x-right,y-up,z-depth',blocks:[{x:3,y:1,z:2,type:'wood',shape:'cube',rotation:0}]};
  // Reuse the canonical exporter schema, then vary just title and coordinates.
  const editable=await page.evaluate(()=>StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine));editable.title='Home import';editable.blocks=editable.blocks.slice(0,1);editable.blocks[0].x=3;editable.blocks[0].z=2;
  await input.setInputFiles({name:'build.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(editable))});await page.getByText('Ready to open: Home import',{exact:true}).waitFor();check(await signature()===before,'Saved build preview is non-destructive');check(await page.locator('#gwe-recovery-title').count()===1,'Import preview has one unique accessible heading');await shot('saved-build-preview');await page.getByRole('button',{name:'Cancel',exact:true}).click();check(await signature()===before,'Cancelling an import preserves work');check(await page.getByRole('button',{name:'Choose editable JSON',exact:true}).evaluate(n=>document.activeElement===n),'Import cancellation restores focus to the visible file control');
  await input.setInputFiles({name:'build.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(editable))});await page.getByRole('button',{name:'Replace current sandbox',exact:true}).click();await frames();check(await page.evaluate(()=>StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks.length===1&&!!__geoWorldEngine.blocks['3,1,2']&&!__ctx.toolData.geometryWorld.showGeometryHome),'Confirmed home import opens the editable build and dismisses Home');
  await openHome();await page.locator('.gwe-home-card[data-path=create]').click();await shot('create');const creatorBefore=await page.evaluate(()=>JSON.stringify(StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks));await page.getByRole('button',{name:'Create in this workspace',exact:true}).click();await page.getByRole('dialog',{name:'Creator mode',exact:true}).waitFor();check(await page.evaluate(()=>JSON.stringify(StemLab.geometryWorldBuilderPure.editableWorld(__geoWorldEngine).blocks))===creatorBefore,'Creator reuses existing work');
  await page.getByRole('button',{name:'Close creator panel',exact:true}).click();await openHome();await page.locator('.gwe-home-card[data-path=create]').click();await page.getByRole('button',{name:'Start a blank lesson',exact:true}).click();await page.getByRole('dialog',{name:'Creator mode',exact:true}).waitFor();await page.waitForTimeout(120);check(await page.evaluate(()=>!!document.activeElement.closest('[aria-label="Creator mode"]')),'Blank lesson keeps focus inside its creator dialog');
  await page.getByRole('button',{name:'Close creator panel',exact:true}).click();await openHome();await page.evaluate(()=>{__ctx.callGemini=()=>Promise.reject(Error('Should not generate from navigation'));__ctx.updateMulti('geometryWorld',{geometryHomePage:'create'});});await frames();await page.getByRole('button',{name:'Open AI lesson builder',exact:true}).click();await page.getByLabel('Describe a geometry lesson topic for AI generation',{exact:true}).waitFor();await page.waitForTimeout(80);check(await page.getByLabel('Describe a geometry lesson topic for AI generation',{exact:true}).evaluate(n=>document.activeElement===n),'AI entry focuses topic without generating');
  await openHome();await page.evaluate(()=>document.documentElement.classList.add('theme-contrast'));await shot('home-contrast');await page.evaluate(()=>document.documentElement.classList.remove('theme-contrast'));await page.getByRole('button',{name:/Continue your workspace/}).click();await page.getByRole('button',{name:'Hide the Geometry World game bar',exact:true}).click();await page.getByRole('button',{name:'Geometry World home',exact:true}).filter({visible:true}).click();check(await home().count()===1,'Home remains reachable with the game bar collapsed');await page.getByRole('button',{name:/Continue your workspace/}).click();await page.getByRole('button',{name:'Show the Geometry World game bar',exact:true}).click();
  await page.getByRole('button',{name:'Enter fullscreen for the Geometry World workspace',exact:true}).click();await page.waitForFunction(()=>!!document.fullscreenElement);await openHome();await shot('home-fullscreen');check(await home().count()===1,'Home remains available in native fullscreen');await page.getByRole('button',{name:/Continue your workspace/}).click();await page.getByRole('button',{name:'Exit fullscreen for the Geometry World workspace',exact:true}).click();

  const phone=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148'});phone.on('pageerror',e=>r.errors.push(e.message));await phone.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await phone.locator('.gwe-home').waitFor({timeout:120000});await phone.waitForFunction(()=>!!window.__geoWorldEngine,{},{timeout:120000});check(await phone.locator('.gwe-home-card').count()===4,'Fresh touch phone reaches all four modes without a device-note dead end');await phone.screenshot({path:path.join(out,'home-fresh-touch.png'),timeout:60000});r.screenshots.push('home-fresh-touch.png');await phone.locator('.gwe-home-card[data-path=build]').click();await phone.getByRole('button',{name:'Open blank sandbox',exact:true}).click();await phone.waitForFunction(()=>window.__geoWorldEngine._currentLesson.sandbox===true);check(await phone.locator('#geoworld-fs-workspace').getAttribute('data-touch-active')==='true','Fresh phone starts a usable touch sandbox');await phone.getByRole('button',{name:'Geometry World home',exact:true}).filter({visible:true}).click();check(await phone.locator('.gwe-home').isVisible(),'Touch sandbox returns to Home');await phone.close();
 }catch(error){r.failure=error.stack;await shot('failure').catch(()=>{});}finally{r.pass=!r.failure&&!r.errors.length&&!r.consoleErrors.length&&r.checks.every(c=>c.pass);fs.writeFileSync(path.join(out,'home-browser.json'),JSON.stringify(r,null,2));console.log(JSON.stringify({pass:r.pass,checks:r.checks.length,failed:r.checks.filter(c=>!c.pass),failure:r.failure,errors:r.errors,consoleErrors:r.consoleErrors}));await browser.close();await new Promise(resolve=>server.close(resolve));if(!r.pass)process.exitCode=1;}
};eval(harness+'('+body.toString()+')();');
