const keys = ['delivery_backup','delivery_conditions','delivery_hint','delivery_options_label','delivery_priority','delivery_priority_accessible','delivery_priority_assessment','delivery_priority_editable','delivery_priority_interactive','delivery_priority_offline','delivery_recommended','delivery_recommender_title','delivery_setting','delivery_setting_live','delivery_setting_lms','delivery_setting_print','delivery_setting_take_home','delivery_title'];
const make = (values) => Object.fromEntries(keys.map((key, index) => [key, values[index]]));
module.exports = {
  french: make(['Sauvegarde', 'QTI nécessite un quiz. H5P nécessite du contenu compatible et des bibliothèques de destination. Les exports Storybook et Persona restent dans leurs vues de ressources. L’expiration des devoirs et l’hébergement varient selon le déploiement.', 'Utilisez une voie principale et une sauvegarde lorsque les besoins d’accès diffèrent.', 'Options d’exportation et de diffusion', 'Priorité principale', 'Accessibilité', 'Évaluation', 'Modifiable', 'Interactif', 'Connectivité limitée', 'Recommandé', 'Aidez-moi à choisir', 'Contexte d’enseignement', 'Cours en direct', 'LMS', 'Impression / papier', 'À emporter', 'Choisir la diffusion selon l’objectif']),
  german: make(['Sicherung', 'QTI benötigt ein Quiz. H5P benötigt kompatible Inhalte und Zielbibliotheken. Storybook- und Persona-Exporte bleiben in ihren Ressourcenansichten. Ablauf von Hausaufgaben und Hosting hängen von der Bereitstellung ab.', 'Verwenden Sie einen primären Weg und eine Sicherung, wenn sich die Zugangsanforderungen unterscheiden.', 'Export- und Bereitstellungsoptionen', 'Höchste Priorität', 'Barrierefreiheit', 'Bewertung', 'Bearbeitbar', 'Interaktiv', 'Geringe Konnektivität', 'Empfohlen', 'Bei der Auswahl helfen', 'Unterrichtssituation', 'Live-Unterricht', 'LMS', 'Druck / Papier', 'Mit nach Hause', 'Bereitstellung nach Zweck auswählen']),
  arabic: make(['نسخة احتياطية', 'يتطلب QTI اختباراً. يتطلب H5P محتوى متوافقاً ومكتبات وجهة. تظل صادرات Storybook وPersona في عروض مواردها. تختلف مدة صلاحية الواجب والاستضافة حسب النشر.', 'استخدم مساراً أساسياً ونسخة احتياطية عند اختلاف احتياجات الوصول.', 'خيارات التصدير والتسليم', 'الأولوية القصوى', 'إمكانية الوصول', 'التقييم', 'قابل للتحرير', 'تفاعلي', 'اتصال منخفض', 'موصى به', 'ساعدني في الاختيار', 'إعداد التدريس', 'صف مباشر', 'نظام إدارة التعلم', 'طباعة / ورق', 'للاستخدام المنزلي', 'اختيار التسليم حسب الغرض']),
  chinese_simplified: make(['备份', 'QTI 需要测验。H5P 需要兼容内容和目标库。Storybook 与 Persona 导出仍保留在各自的资源视图中。作业过期时间和托管方式取决于部署。', '当访问需求不同时，请使用一个主要路径和一个备用路径。', '导出和交付选项', '最高优先级', '无障碍', '评估', '可编辑', '交互式', '低连接性', '推荐', '帮我选择', '教学场景', '实时课堂', '学习管理系统', '打印 / 纸张', '带回家', '按用途选择交付方式']),
  japanese: make(['バックアップ', 'QTI にはクイズが必要です。H5P には互換性のあるコンテンツと保存先ライブラリが必要です。Storybook と Persona のエクスポートは各リソース画面に残ります。宿題の有効期限とホスティングは配布方法によって異なります。', 'アクセスの要件が異なる場合は、主経路とバックアップを 1 つずつ使用してください。', 'エクスポートと配布のオプション', '最優先', 'アクセシビリティ', '評価', '編集可能', 'インタラクティブ', '低接続環境', 'おすすめ', '選び方を教えて', '授業設定', 'ライブ授業', 'LMS', '印刷 / 紙', '持ち帰り', '目的から配布方法を選択']),
  hindi: make(['बैकअप', 'QTI के लिए क्विज़ चाहिए। H5P के लिए संगत सामग्री और गंतव्य लाइब्रेरी चाहिए। Storybook और Persona निर्यात अपने संसाधन दृश्यों में रहते हैं। होमवर्क की समय-सीमा और होस्टिंग परिनियोजन के अनुसार बदलते हैं।', 'जब पहुँच की ज़रूरतें अलग हों, तो एक मुख्य मार्ग और एक बैकअप का उपयोग करें।', 'निर्यात और डिलीवरी विकल्प', 'सर्वोच्च प्राथमिकता', 'सुलभता', 'आकलन', 'संपादन योग्य', 'इंटरैक्टिव', 'कम कनेक्टिविटी', 'अनुशंसित', 'चुनने में मेरी मदद करें', 'शिक्षण सेटिंग', 'लाइव कक्षा', 'LMS', 'प्रिंट / कागज़', 'घर ले जाने योग्य', 'उद्देश्य के अनुसार डिलीवरी चुनें']),
  swahili: make(['Nakala rudufu', 'QTI inahitaji jaribio. H5P inahitaji maudhui yanayolingana na maktaba za kulengwa. Usafirishaji wa Storybook na Persona hubaki katika mwonekano wa rasilimali zao. Muda wa kazi ya nyumbani na upangishaji hutegemea usambazaji.', 'Tumia njia moja kuu na nakala rudufu wakati mahitaji ya ufikiaji yanatofautiana.', 'Chaguo za kuhamisha na kuwasilisha', 'Kipaumbele cha juu', 'Ufikivu', 'Tathmini', 'Inaweza kuhaririwa', 'Shirikishi', 'Muunganisho mdogo', 'Inapendekezwa', 'Nisaidie kuchagua', 'Mpangilio wa kufundisha', 'Darasa la moja kwa moja', 'LMS', 'Chapisha / karatasi', 'Ya kwenda nayo nyumbani', 'Chagua uwasilishaji kulingana na kusudi']),
  vietnamese: make(['Bản sao lưu', 'QTI cần một bài kiểm tra. H5P cần nội dung tương thích và thư viện đích. Bản xuất Storybook và Persona vẫn nằm trong chế độ xem tài nguyên tương ứng. Thời hạn bài tập và dịch vụ lưu trữ tùy thuộc vào triển khai.', 'Hãy dùng một lộ trình chính và một bản sao lưu khi nhu cầu truy cập khác nhau.', 'Tùy chọn xuất và phân phối', 'Ưu tiên hàng đầu', 'Khả năng tiếp cận', 'Đánh giá', 'Có thể chỉnh sửa', 'Tương tác', 'Kết nối thấp', 'Được đề xuất', 'Giúp tôi chọn', 'Bối cảnh giảng dạy', 'Lớp học trực tiếp', 'LMS', 'In / giấy', 'Mang về nhà', 'Chọn cách phân phối theo mục đích']),
  russian: make(['Резервная копия', 'Для QTI нужен тест. Для H5P нужны совместимое содержимое и библиотеки назначения. Экспорты Storybook и Persona остаются в представлениях своих ресурсов. Срок действия задания и размещение зависят от развёртывания.', 'Если требования к доступу различаются, используйте основной способ и резервный.', 'Варианты экспорта и выдачи', 'Главный приоритет', 'Доступность', 'Оценивание', 'Редактируемый', 'Интерактивный', 'Слабое подключение', 'Рекомендуется', 'Помогите выбрать', 'Условия обучения', 'Занятие в реальном времени', 'LMS', 'Печать / бумага', 'На дом', 'Выбрать способ выдачи по назначению']),
  korean: make(['백업', 'QTI에는 퀴즈가 필요합니다. H5P에는 호환 콘텐츠와 대상 라이브러리가 필요합니다. Storybook 및 Persona 내보내기는 각 리소스 보기에 남습니다. 과제 만료와 호스팅은 배포에 따라 달라집니다.', '접근 요구 사항이 다르면 기본 경로와 백업 경로를 하나씩 사용하세요.', '내보내기 및 전달 옵션', '최우선', '접근성', '평가', '편집 가능', '대화형', '연결 상태 낮음', '권장', '선택을 도와주세요', '수업 설정', '실시간 수업', 'LMS', '인쇄 / 용지', '집으로 가져가기', '목적에 따라 전달 방식 선택']),
  portuguese_brazil: make(['Backup', 'QTI precisa de um quiz. H5P precisa de conteúdo compatível e bibliotecas de destino. As exportações do Storybook e do Persona permanecem em suas visões de recursos. O prazo da tarefa e a hospedagem variam conforme a implantação.', 'Use uma rota principal e um backup quando as necessidades de acesso forem diferentes.', 'Opções de exportação e entrega', 'Maior prioridade', 'Acessibilidade', 'Avaliação', 'Editável', 'Interativo', 'Baixa conectividade', 'Recomendado', 'Ajude-me a escolher', 'Configuração de ensino', 'Aula ao vivo', 'LMS', 'Impressão / papel', 'Para levar para casa', 'Escolha a entrega por finalidade']),
  tagalog: make(['Backup', 'Kailangan ng QTI ng quiz. Kailangan ng H5P ng compatible na content at destination libraries. Nananatili ang Storybook at Persona exports sa kani-kanilang resource view. Nag-iiba ang homework expiry at hosting ayon sa deployment.', 'Gumamit ng isang pangunahing ruta at backup kapag magkaiba ang access needs.', 'Mga opsyon sa export at delivery', 'Pinakamataas na priyoridad', 'Accessibility', 'Assessment', 'Editable', 'Interactive', 'Mababang connectivity', 'Inirerekomenda', 'Tulungan akong pumili', 'Setting ng pagtuturo', 'Live na klase', 'LMS', 'Print / papel', 'Iuwi', 'Pumili ng delivery ayon sa layunin']),
};
