const keys = ['readiness_accessibility','readiness_answers','readiness_backup','readiness_confirm','readiness_delivery','readiness_directions','readiness_fix_delivery','readiness_fix_directions','readiness_fix_preview','readiness_fix_title','readiness_hint','readiness_learner_view','readiness_progress','readiness_ready','readiness_remaining','readiness_title','readiness_verified'];
const make = (values) => Object.fromEntries(keys.map((key, index) => [key, values[index]]));
module.exports = {
  french_canadian: make(['Accessibilité et ordre de lecture vérifiés', 'Les corrigés et notes réservées à l’enseignant sont masqués', 'Un accès de secours est prêt', 'Confirmer', 'Un fichier, un lien ou une séance de diffusion a été créé', 'Les consignes pour les élèves sont enregistrées', 'Choisir l’exportation ou la diffusion', 'Créer les consignes', 'Tester la vue élève', 'Terminer la configuration vérifiée', 'Les actions vérifiées sont contrôlées automatiquement. Confirmez les derniers contrôles de classe avant le lancement.', 'La vue élève a été testée', 'Progression de la préparation des élèves', 'prêt pour les élèves', 'contrôles terminés', 'Vérification avant cours', 'Vérifié']),
  farsi: make(['دسترس‌پذیری و ترتیب خواندن بررسی شد', 'کلیدهای پاسخ و یادداشت‌های مخصوص معلم پنهان هستند', 'مسیر دسترسی پشتیبان آماده است', 'تأیید', 'فایل، پیوند یا جلسهٔ ارائه ایجاد شد', 'دستورهای دانش‌آموزان ذخیره شد', 'انتخاب خروجی یا ارائه', 'ایجاد دستورها', 'آزمایش نمای دانش‌آموز', 'تکمیل تنظیمات تأییدشده', 'کارهای تأییدشده به‌طور خودکار بررسی می‌شوند. بررسی‌های باقی‌ماندهٔ کلاس را پیش از شروع تأیید کنید.', 'نمای دانش‌آموز آزمایش شد', 'پیشرفت آمادگی دانش‌آموز', 'آماده برای دانش‌آموزان', 'بررسی‌ها تکمیل شد', 'پیش‌بررسی آماده‌بودن دانش‌آموز', 'تأیید شد']),
  gujarati: make(['ઍક્સેસિબિલિટી અને વાંચન ક્રમની સમીક્ષા થઈ', 'જવાબની કી અને માત્ર શિક્ષક માટેની નોંધો છુપાયેલી છે', 'બેકઅપ ઍક્સેસ માર્ગ તૈયાર છે', 'પુષ્ટિ કરો', 'ડિલિવરી ફાઇલ, લિંક અથવા સત્ર બનાવાયું', 'વિદ્યાર્થીની સૂચનાઓ સાચવાઈ', 'નિકાસ અથવા ડિલિવરી પસંદ કરો', 'સૂચનાઓ બનાવો', 'વિદ્યાર્થી દૃશ્યનું પરીક્ષણ કરો', 'ચકાસાયેલ સેટઅપ પૂર્ણ કરો', 'ચકાસેલી ક્રિયાઓ આપમેળે તપાસાય છે. શરૂ કરતા પહેલાં બાકીની વર્ગ તપાસોની પુષ્ટિ કરો.', 'વિદ્યાર્થી દૃશ્યનું પરીક્ષણ થયું', 'વિદ્યાર્થી તૈયારીની પ્રગતિ', 'વિદ્યાર્થીઓ માટે તૈયાર', 'તપાસ પૂર્ણ', 'વિદ્યાર્થી-તૈયાર પૂર્વતપાસ', 'ચકાસાયેલ']),
  kannada: make(['ಪ್ರವೇಶಸಾಧ್ಯತೆ ಮತ್ತು ಓದುವ ಕ್ರಮವನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ', 'ಉತ್ತರ ಕೀಗಳು ಮತ್ತು ಶಿಕ್ಷಕರಿಗೆ ಮಾತ್ರದ ಟಿಪ್ಪಣಿಗಳನ್ನು ಮರೆಮಾಡಲಾಗಿದೆ', 'ಬ್ಯಾಕಪ್ ಪ್ರವೇಶ ಮಾರ್ಗ ಸಿದ್ಧವಾಗಿದೆ', 'ದೃಢೀಕರಿಸಿ', 'ವಿತರಣೆ ಫೈಲ್, ಲಿಂಕ್ ಅಥವಾ ಸೆಷನ್ ರಚಿಸಲಾಗಿದೆ', 'ವಿದ್ಯಾರ್ಥಿ ಸೂಚನೆಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ', 'ರಫ್ತು ಅಥವಾ ವಿತರಣೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ', 'ಸೂಚನೆಗಳನ್ನು ರಚಿಸಿ', 'ಕಲಿಯುವವರ ವೀಕ್ಷಣೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ', 'ಪರಿಶೀಲಿಸಿದ ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಿ', 'ಪರಿಶೀಲಿಸಿದ ಕ್ರಿಯೆಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗುತ್ತದೆ. ಪ್ರಾರಂಭಿಸುವ ಮೊದಲು ಉಳಿದ ತರಗತಿ ಪರಿಶೀಲನೆಗಳನ್ನು ದೃಢೀಕರಿಸಿ.', 'ಕಲಿಯುವವರ ವೀಕ್ಷಣೆಯನ್ನು ಪರೀಕ್ಷಿಸಲಾಗಿದೆ', 'ವಿದ್ಯಾರ್ಥಿ ಸಿದ್ಧತೆ ಪ್ರಗತಿ', 'ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಸಿದ್ಧ', 'ಪರಿಶೀಲನೆಗಳು ಪೂರ್ಣ', 'ವಿದ್ಯಾರ್ಥಿ-ಸಿದ್ಧ ಪೂರ್ವಪರಿಶೀಲನೆ', 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ']),
  korean: make(['접근성 및 읽기 순서 검토 완료', '정답과 교사용 메모는 숨겨져 있습니다', '백업 접근 경로가 준비되었습니다', '확인', '전달 파일, 링크 또는 세션이 생성되었습니다', '학습자용 안내가 저장되었습니다', '내보내기 또는 전달 선택', '안내 만들기', '학습자 보기 테스트', '확인된 설정 완료', '확인된 작업은 자동으로 검사됩니다. 시작하기 전에 남은 수업 검사를 확인하세요.', '학습자 보기를 테스트했습니다', '학습자 준비 진행률', '학습자에게 준비됨', '검사 완료', '학습자 준비 사전 점검', '확인됨']),
  lao: make(['ກວດສອບການເຂົ້າເຖິງແລະລຳດັບການອ່ານແລ້ວ', 'ຊ່ອງຄຳຕອບແລະບັນທຶກສຳລັບຄູເທົ່ານັ້ນຖືກຊ່ອນ', 'ເສັ້ນທາງເຂົ້າເຖິງສຳຮອງພ້ອມແລ້ວ', 'ຢືນຢັນ', 'ສ້າງໄຟລ໌, ລິ້ງ ຫຼື ເຊດຊັນສົ່ງມອບແລ້ວ', 'ບັນທຶກຄຳແນະນຳນັກຮຽນແລ້ວ', 'ເລືອກສົ່ງອອກ ຫຼື ສົ່ງມອບ', 'ສ້າງຄຳແນະນຳ', 'ທົດສອບມຸມມອງຜູ້ຮຽນ', 'ສຳເລັດການຕັ້ງຄ່າທີ່ຢືນຢັນ', 'ການກະທຳທີ່ຢືນຢັນຈະຖືກກວດອັດຕະໂນມັດ. ຢືນຢັນການກວດຫ້ອງຮຽນທີ່ເຫຼືອກ່ອນເລີ່ມ.', 'ທົດສອບມຸມມອງຜູ້ຮຽນແລ້ວ', 'ຄວາມຄືບໜ້າຄວາມພ້ອມຂອງຜູ້ຮຽນ', 'ພ້ອມສຳລັບຜູ້ຮຽນ', 'ການກວດສຳເລັດ', 'ການກວດກ່ອນພ້ອມສຳລັບນັກຮຽນ', 'ຢືນຢັນແລ້ວ']),
  malayalam: make(['പ്രാപ്യതയും വായനാക്രമവും അവലോകനം ചെയ്തു', 'ഉത്തര കീകളും അധ്യാപകർക്ക് മാത്രമുള്ള കുറിപ്പുകളും മറച്ചിരിക്കുന്നു', 'ബാക്കപ്പ് ആക്സസ് വഴി തയ്യാറാണ്', 'സ്ഥിരീകരിക്കുക', 'വിതരണ ഫയൽ, ലിങ്ക് അല്ലെങ്കിൽ സെഷൻ സൃഷ്ടിച്ചു', 'വിദ്യാർത്ഥികൾക്കുള്ള നിർദ്ദേശങ്ങൾ സംരക്ഷിച്ചു', 'എക്സ്പോർട്ട് അല്ലെങ്കിൽ വിതരണം തിരഞ്ഞെടുക്കുക', 'നിർദ്ദേശങ്ങൾ സൃഷ്ടിക്കുക', 'പഠിതാവിന്റെ കാഴ്ച പരിശോധിക്കുക', 'പരിശോധിച്ച സജ്ജീകരണം പൂർത്തിയാക്കുക', 'പരിശോധിച്ച പ്രവർത്തനങ്ങൾ സ്വയമേവ പരിശോധിക്കും. ആരംഭിക്കുന്നതിന് മുമ്പ് ശേഷിക്കുന്ന ക്ലാസ് പരിശോധനകൾ സ്ഥിരീകരിക്കുക.', 'പഠിതാവിന്റെ കാഴ്ച പരിശോധിച്ചു', 'പഠിതാവിന്റെ തയ്യാറെടുപ്പ് പുരോഗതി', 'പഠിതാക്കൾക്കായി തയ്യാറാണ്', 'പരിശോധനകൾ പൂർത്തിയായി', 'വിദ്യാർത്ഥി-തയ്യാർ പ്രീഫ്ലൈറ്റ്', 'പരിശോധിച്ചു']),
  marathi: make(['सुलभता आणि वाचन क्रमाचे पुनरावलोकन झाले', 'उत्तर कळा आणि फक्त शिक्षकांसाठीच्या नोंदी लपवलेल्या आहेत', 'बॅकअप प्रवेश मार्ग तयार आहे', 'पुष्टी करा', 'वितरण फाइल, लिंक किंवा सत्र तयार झाले', 'विद्यार्थ्यांच्या सूचना जतन झाल्या', 'निर्यात किंवा वितरण निवडा', 'सूचना तयार करा', 'विद्यार्थी दृश्याची चाचणी करा', 'सत्यापित सेटअप पूर्ण करा', 'सत्यापित कृती स्वयंचलितपणे तपासल्या जातात. सुरू करण्यापूर्वी उरलेल्या वर्ग तपासण्यांची पुष्टी करा.', 'विद्यार्थी दृश्याची चाचणी झाली', 'विद्यार्थी तयारीची प्रगती', 'विद्यार्थ्यांसाठी तयार', 'तपासण्या पूर्ण', 'विद्यार्थी-तयार पूर्वतपासणी', 'सत्यापित']),
  nepali: make(['पहुँचयोग्यता र पढ्ने क्रम समीक्षा गरिएको', 'उत्तर कुञ्जी र शिक्षकका लागि मात्रका नोट लुकाइएका छन्', 'ब्याकअप पहुँच मार्ग तयार छ', 'पुष्टि गर्नुहोस्', 'वितरण फाइल, लिङ्क वा सत्र सिर्जना भयो', 'विद्यार्थीका निर्देशनहरू सुरक्षित गरिए', 'निर्यात वा वितरण छान्नुहोस्', 'निर्देशनहरू सिर्जना गर्नुहोस्', 'विद्यार्थी दृश्य परीक्षण गर्नुहोस्', 'प्रमाणित सेटअप पूरा गर्नुहोस्', 'प्रमाणित कार्यहरू स्वतः जाँचिन्छन्। सुरु गर्नुअघि बाँकी कक्षा जाँचहरू पुष्टि गर्नुहोस्।', 'विद्यार्थी दृश्य परीक्षण गरियो', 'विद्यार्थी तयारीको प्रगति', 'विद्यार्थीका लागि तयार', 'जाँचहरू पूरा', 'विद्यार्थी-तयार पूर्वजाँच', 'प्रमाणित']),
  polish: make(['Dostępność i kolejność czytania sprawdzone', 'Klucze odpowiedzi i notatki tylko dla nauczyciela są ukryte', 'Zapasowa ścieżka dostępu jest gotowa', 'Potwierdź', 'Utworzono plik, link lub sesję dostarczania', 'Instrukcje dla uczniów zapisano', 'Wybierz eksport lub dostarczenie', 'Utwórz instrukcje', 'Przetestuj widok ucznia', 'Dokończ zweryfikowaną konfigurację', 'Zweryfikowane działania są sprawdzane automatycznie. Przed uruchomieniem potwierdź pozostałe kontrole klasowe.', 'Widok ucznia został przetestowany', 'Postęp gotowości ucznia', 'gotowe dla uczniów', 'kontrole ukończone', 'Kontrola gotowości ucznia', 'Zweryfikowano']),
  portuguese_angola: make(['Acessibilidade e ordem de leitura revistas', 'As chaves de respostas e notas exclusivas do professor estão ocultas', 'Está pronto um percurso de acesso alternativo', 'Confirmar', 'Foi criado um ficheiro, ligação ou sessão de entrega', 'As instruções para os alunos foram guardadas', 'Escolher exportação ou entrega', 'Criar instruções', 'Testar a vista do aluno', 'Concluir a configuração verificada', 'As acções verificadas são verificadas automaticamente. Confirme as verificações de sala restantes antes de iniciar.', 'A vista do aluno foi testada', 'Progresso da preparação do aluno', 'pronto para os alunos', 'verificações concluídas', 'Pré-verificação pronta para o aluno', 'Verificado']),
  romanian: make(['Accesibilitatea și ordinea de citire au fost verificate', 'Cheile de răspuns și notițele doar pentru profesor sunt ascunse', 'O rută de acces de rezervă este gata', 'Confirmă', 'A fost creat un fișier, un link sau o sesiune de livrare', 'Instrucțiunile pentru elevi au fost salvate', 'Alege exportul sau livrarea', 'Creează instrucțiuni', 'Testează vizualizarea elevului', 'Finalizează configurarea verificată', 'Acțiunile verificate sunt controlate automat. Confirmă verificările de clasă rămase înainte de lansare.', 'Vizualizarea elevului a fost testată', 'Progresul pregătirii elevului', 'pregătit pentru elevi', 'verificări finalizate', 'Verificare preliminară pentru elevi', 'Verificat']),
};
