const keys = ['readiness_accessibility','readiness_answers','readiness_backup','readiness_confirm','readiness_delivery','readiness_directions','readiness_fix_delivery','readiness_fix_directions','readiness_fix_preview','readiness_fix_title','readiness_hint','readiness_learner_view','readiness_progress','readiness_ready','readiness_remaining','readiness_title','readiness_verified'];
const make = (values) => Object.fromEntries(keys.map((key, index) => [key, values[index]]));
module.exports = {
  acholi: make(['Yot pa donyo ki kit me kwan oneno', 'Jami me moko ki lok pa lupwonye kene pe onyute', 'Yo me donyo ma opire tye', 'Mok', 'Fail, link, onyo kare me poko oyub', 'Cik pi latin kwan ogwoko', 'Yer gam onyo poko', 'Yub cik', 'Tem nen pa latin kwan', 'Tyek yub ma gimoko', 'Tic ma kimoko gipimo kene. Mok gicik me kilas ma odong mapud i cak.', 'Nen pa latin kwan otet', 'Mede pa yub latin kwan', 'yub pi latin kwan', 'moko otum', 'Nen anyim pi latin kwan', 'Kimoko']),
  amharic: make(['ተደራሽነትና የንባብ ቅደም ተከተል ተገምግሟል', 'የመልስ ቁልፎችና ለመምህር ብቻ የሚሆኑ ማስታወሻዎች ተደብቀዋል', 'የመጠባበቂያ የመዳረሻ መንገድ ዝግጁ ነው', 'አረጋግጥ', 'የማድረሻ ፋይል፣ አገናኝ ወይም ክፍለ ጊዜ ተፈጥሯል', 'የተማሪ መመሪያዎች ተቀምጠዋል', 'ማውጣት ወይም ማድረስ ምረጥ', 'መመሪያዎችን ፍጠር', 'የተማሪ እይታን ፈትሽ', 'የተረጋገጠ ማዋቀርን ጨርስ', 'የተረጋገጡ እርምጃዎች በራስ ሰር ይፈተሻሉ። ከመጀመር በፊት የቀሩትን የክፍል ፍተሻዎች አረጋግጥ።', 'የተማሪ እይታ ተፈትሿል', 'የተማሪ ዝግጁነት ሂደት', 'ለተማሪዎች ዝግጁ', 'ፍተሻዎች ተጠናቀዋል', 'ለተማሪ ዝግጁ የቅድመ ፍተሻ', 'ተረጋግጧል']),
  bengali: make(['অ্যাক্সেসিবিলিটি ও পড়ার ক্রম পর্যালোচনা করা হয়েছে', 'উত্তরের চাবি ও শুধু শিক্ষকের জন্য নোট লুকানো আছে', 'ব্যাকআপ অ্যাক্সেস পথ প্রস্তুত', 'নিশ্চিত করুন', 'ডেলিভারি ফাইল, লিংক বা সেশন তৈরি হয়েছে', 'শিক্ষার্থীর নির্দেশনা সেভ হয়েছে', 'এক্সপোর্ট বা ডেলিভারি বেছে নিন', 'নির্দেশনা তৈরি করুন', 'শিক্ষার্থীর ভিউ পরীক্ষা করুন', 'যাচাই করা সেটআপ শেষ করুন', 'যাচাই করা কাজগুলো স্বয়ংক্রিয়ভাবে পরীক্ষা হয়। শুরু করার আগে বাকি ক্লাস পরীক্ষা নিশ্চিত করুন।', 'শিক্ষার্থীর ভিউ পরীক্ষা করা হয়েছে', 'শিক্ষার্থীর প্রস্তুতির অগ্রগতি', 'শিক্ষার্থীদের জন্য প্রস্তুত', 'চেক সম্পন্ন', 'শিক্ষার্থী-প্রস্তুত প্রিফ্লাইট', 'যাচাই করা হয়েছে']),
  burmese: make(['အသုံးပြုနိုင်မှုနှင့် ဖတ်ရှုမှုအစီအစဉ်ကို ပြန်လည်သုံးသပ်ပြီး', 'အဖြေသော့များနှင့် ဆရာအတွက်သာ မှတ်စုများကို ဖုံးကွယ်ထားသည်', 'အရန်ဝင်ရောက်မှုလမ်းကြောင်း အသင့်ဖြစ်သည်', 'အတည်ပြုပါ', 'ပေးပို့မှုဖိုင်၊ လင့်ခ် သို့မဟုတ် အစည်းအဝေး ဖန်တီးပြီး', 'ကျောင်းသားညွှန်ကြားချက်များ သိမ်းဆည်းပြီး', 'ထုတ်ယူမှု သို့မဟုတ် ပေးပို့မှုကို ရွေးပါ', 'ညွှန်ကြားချက်များ ဖန်တီးပါ', 'သင်ယူသူမြင်ကွင်းကို စမ်းသပ်ပါ', 'အတည်ပြုထားသော တပ်ဆင်မှု ပြီးစီးပါ', 'အတည်ပြုထားသော လုပ်ဆောင်ချက်များကို အလိုအလျောက် စစ်ဆေးသည်။ မစတင်မီ ကျန်ရှိသော အတန်းစစ်ဆေးမှုများကို အတည်ပြုပါ။', 'သင်ယူသူမြင်ကွင်းကို စမ်းသပ်ပြီး', 'သင်ယူသူ အသင့်ဖြစ်မှု တိုးတက်မှု', 'သင်ယူသူများအတွက် အသင့်', 'စစ်ဆေးမှုများ ပြီးစီး', 'ကျောင်းသားအသင့်ဖြစ်မှု အကြိုစစ်ဆေးမှု', 'အတည်ပြုပြီး']),
  chinese_traditional: make(['已檢查無障礙性和閱讀順序', '答案和僅教師可見的筆記已隱藏', '備用存取路徑已準備好', '確認', '已建立交付檔案、連結或工作階段', '學生說明已儲存', '選擇匯出或交付', '建立說明', '測試學習者檢視', '完成已驗證的設定', '已驗證的操作會自動檢查。開始前請確認剩餘的課堂檢查。', '學習者檢視已測試', '學習者準備進度', '可供學習者使用', '項檢查完成', '學生就緒預檢', '已驗證']),
  dutch: make(['Toegankelijkheid en leesvolgorde gecontroleerd', 'Antwoordsleutels en notities alleen voor de docent zijn verborgen', 'Een alternatieve toegangsroute is klaar', 'Bevestigen', 'Een leveringsbestand, link of sessie is gemaakt', 'Instructies voor leerlingen zijn opgeslagen', 'Export of levering kiezen', 'Instructies maken', 'Leerlingweergave testen', 'Gecontroleerde instelling voltooien', 'Gecontroleerde acties worden automatisch nagekeken. Bevestig de resterende klascontroles voordat je start.', 'Leerlingweergave is getest', 'Voortgang van leerlinggereedheid', 'klaar voor leerlingen', 'controles voltooid', 'Voorcontrole voor leerlingen', 'Geverifieerd']),
  greek: make(['Η προσβασιμότητα και η σειρά ανάγνωσης ελέγχθηκαν', 'Τα κλειδιά απαντήσεων και οι σημειώσεις μόνο για εκπαιδευτικούς είναι κρυφά', 'Μια εφεδρική διαδρομή πρόσβασης είναι έτοιμη', 'Επιβεβαίωση', 'Δημιουργήθηκε αρχείο, σύνδεσμος ή συνεδρία παράδοσης', 'Οι οδηγίες μαθητών αποθηκεύτηκαν', 'Επιλέξτε εξαγωγή ή παράδοση', 'Δημιουργία οδηγιών', 'Δοκιμή προβολής μαθητή', 'Ολοκλήρωση επαληθευμένης ρύθμισης', 'Οι επαληθευμένες ενέργειες ελέγχονται αυτόματα. Επιβεβαιώστε τους υπόλοιπους ελέγχους τάξης πριν από την έναρξη.', 'Η προβολή μαθητή δοκιμάστηκε', 'Πρόοδος ετοιμότητας μαθητή', 'έτοιμο για μαθητές', 'έλεγχοι ολοκληρώθηκαν', 'Προέλεγχος ετοιμότητας μαθητή', 'Επαληθεύτηκε']),
  haitian_creole: make(['Aksesibilite ak lòd lekti a revize', 'Kle repons ak nòt pou pwofesè sèlman kache', 'Yon wout aksè sipò pare', 'Konfime', 'Fichye, lyen oswa sesyon livrezon an kreye', 'Enstriksyon pou elèv yo sove', 'Chwazi ekspòtasyon oswa livrezon', 'Kreye enstriksyon', 'Teste vizyon elèv la', 'Fini konfigirasyon verifye a', 'Aksyon verifye yo tcheke otomatikman. Konfime rès verifikasyon klas yo anvan ou lanse.', 'Vizyon elèv la teste', 'Pwogrè preparasyon elèv la', 'pare pou elèv yo', 'verifikasyon fini', 'Verifikasyon anvan klas la pare', 'Verifye']),
  hausa: make(['An duba damar amfani da tsarin karatu', 'An ɓoye maɓallan amsa da bayanan malami kawai', 'Hanyar madadin shiga ta shirya', 'Tabbatar', 'An ƙirƙiri fayil, mahada ko zaman bayarwa', 'An adana umarnin ɗalibai', 'Zaɓi fitarwa ko bayarwa', 'Ƙirƙiri umarni', 'Gwada kallon ɗalibi', 'Kammala saitin da aka tabbatar', 'Ana duba ayyukan da aka tabbatar ta atomatik. Tabbatar da sauran dubawar aji kafin farawa.', 'An gwada kallon ɗalibi', 'Ci gaban shirye-shiryen ɗalibi', 'a shirye ga ɗalibai', 'dubawa sun kammala', 'Dubawar shirye-shiryen ɗalibi', 'An tabbatar']),
  hebrew: make(['נבדקו הנגישות וסדר הקריאה', 'מפתחות התשובות וההערות למורה בלבד מוסתרים', 'נתיב גישה חלופי מוכן', 'אישור', 'נוצרו קובץ, קישור או מפגש למסירה', 'ההנחיות לתלמידים נשמרו', 'בחירת ייצוא או מסירה', 'יצירת הנחיות', 'בדיקת תצוגת הלומד', 'סיום הגדרה מאומתת', 'פעולות מאומתות נבדקות אוטומטית. אשרו את בדיקות הכיתה שנותרו לפני ההפעלה.', 'תצוגת הלומד נבדקה', 'התקדמות מוכנות הלומדים', 'מוכן ללומדים', 'בדיקות הושלמו', 'בדיקת מוכנות לתלמידים', 'מאומת']),
  indonesian: make(['Aksesibilitas dan urutan baca telah ditinjau', 'Kunci jawaban dan catatan khusus guru disembunyikan', 'Jalur akses cadangan siap', 'Konfirmasi', 'File, tautan, atau sesi pengiriman telah dibuat', 'Petunjuk siswa telah disimpan', 'Pilih ekspor atau pengiriman', 'Buat petunjuk', 'Uji tampilan pelajar', 'Selesaikan penyiapan terverifikasi', 'Tindakan yang telah diverifikasi diperiksa otomatis. Konfirmasikan pemeriksaan kelas yang tersisa sebelum memulai.', 'Tampilan pelajar telah diuji', 'Kemajuan kesiapan pelajar', 'siap untuk pelajar', 'pemeriksaan selesai', 'Pratinjau siap untuk siswa', 'Terverifikasi']),
  italian: make(['Accessibilità e ordine di lettura verificati', 'Chiavi delle risposte e note riservate all’insegnante nascoste', 'Un percorso di accesso alternativo è pronto', 'Conferma', 'Creati file, link o sessione di consegna', 'Istruzioni per gli studenti salvate', 'Scegli esportazione o consegna', 'Crea istruzioni', 'Prova la vista dello studente', 'Completa la configurazione verificata', 'Le azioni verificate vengono controllate automaticamente. Conferma i controlli di classe rimanenti prima di iniziare.', 'La vista dello studente è stata testata', 'Avanzamento della preparazione dello studente', 'pronto per gli studenti', 'controlli completati', 'Controllo preliminare pronto per lo studente', 'Verificato']),
};
